M7R0
I,F_4p2v_dim17%,H%"sG#!+6EQmf",++++D'*&F%""#%"uG"""#",pIh'zDF(*&F%F,F+F,#!+$\P'
Ru",++++D"%"wG#",T0r<6"F(*&F%F,F3F,#")"**3a#"*++++&*(F%F,F+F,F3F,#"(<g3'")+++D*
(F%F,F+F,F3F*#!+hWVkgF2*(F3F,F%F*F+F*#!,Pz3MJ#"-++++]7*(F%F,F+F*F3F,#!)"Q8H*"*+
++]#*(F3F,F%F*F+F,#!+6Y4@yF2*&F%F,F3F*#",Jb&zK:F(*&F%F,F+F*#!,2n%*\M#FD*&F%F*F+
F*#!)V*\b'"++++]i*&F+F,F3F,#!+V^!e+(F2*$F3F*#"+R!)Q(R$F2*&F%""$F+F*#"+n3!os%FD*
&F3F,F+F*#!+.HMuqFD*$F3Fgn#"+z[]')RF(*&F3F*F+F,#!,pIh'zDF(,HF%#",,p#G_E",+++++#
F)#!+*)*oCh"FDF/#!,$>X!*3BFDF3#",HD@h9"FfoF6#"-V'\@E0"",+++++&F:#"+BQcHT"+++]i:
F>#!-VCfHT@FDFA#"-(QA#GQP"-+++++]FE#!-T-"GL?'"-+++++DFI#!,<&3"pH(FDFL#!,tunAq&"
-+++++5FO#!-."*QiJ_FgpFR#!-*yp0M;%FjpFV#!,(3MeN5FDFY#",fXTg*pF_pFfn#"-VR50_9Fgp
Fjn#!-(Q$\?t@FgpF]o#!,*o@:s<FfoF`o#"+*)*oCh"FD,TF+#",Z'[/=`FDF%#"*Pwy6%"+++++DF
3#!,hZ))\N"",+++Dc"F/#!,nU)*zZ$",+++]7$FR#",f;/l7$F(FO#!*.gex)"++++DJFV#!+6=m_7
F[s*$F+F*#!*ZQQe$F2FY#"*pTX_$FerF:#"*$*f1W(FUFE#!,d!*>Bb#F[sFA#!,(*pl.p&F(F>#!+
zlD"R"FUF6#"+R]]M8F[sFI#!*r7TD(F[sFL#!+j-u.PF2Fjn#!+"eNk(oF(F`o#!+j1PoV",++++]#
F)#",tH-1M%FDFfn#!*PGSM*FhrF]o#"+J$))ff%Fhr*(F%F*F+F,F3F*#!,hO#*[\"Fjt*(F%FgnF+
F*F3F,#"*RF%zI"++]7`>*&F3FgnF%F,#"+`ZjMaFhr#!*<79L*FerF,6",
I,C_4p2v_dim1w,6#>%)symbolicGF,68%&_nameG%&_sizeG%#_AG%"iG%"jG%"qG%"RG%(Acoeffs
G%#iiG%#jjG%$eqsG%"lG%#t1G%#t2G%#r1G%#r2G%"AG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F]
vC3>6$8$8%6$7$%#q1G%#q2G7#-%"$G6$7$Fgn""%F*@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&
F_x6#8'F]v/Fjy;F,-%%nopsG6#F^x>F_y7#-Fby6$-I'MatrixG6$%*protectedG%(_syslibG6$F
gyw,6$%"xG%"yGF]v6$%)operatorG%&arrowGF]v-&T'6#T%6#,&F\yF,*&,&9%F,!""F,F,&&T#Fd
[l6#F,F,F,F]vF]v6(FevF_xFgvFjyFdvF^x6#F*6$7'Q!F]vF[\l"#P"#s"#O7'Fd\lF[\lFe\l"#V
Fg\lF[z?(8(F,F,F*%%trueG?(FjyF,F,FixF\]l>&&8)6#F[]lFiy&&F_yFb]l6$;F]vF]vFjy>6$&
&Fa]lF_\lF_\l&&Fa]l6#F*F_\l6$-I$<,>G6$FgzFhz6%F]yF]yF,F_^l>6$&Fj]lF]^l&F\^lF]^l
6$-F`^l6$F]y&Fe^l6#;F*Fgn-F`^l6$F]y&Ff^lF[_l>8**&-%-getRotMatrixG6#-F`^l6%F+F/F
3F,z+6%F%F+F3[[[[][[[][[[oF,[[[[][[[[[[[mF,][[[[[[[[[[[mF,!F,F,>8+w,6#%"pGF]v6$
F_[lF`[lF]v-I$<|gr>G6$FgzFhz6$-%&coeffG6$F\y%#laG-Fe`l6$F\y%#muGF]vF]vF]v6#F,6$
7'Fd\lF[\l"#9Fi\lFg\l7'Fd\lF[\lF^al"#;Fg\l>8,7%F*F*Fgn>8-7%FgnFixFix>8.7"?(8/F,
F,-F^z6#FbalF\]lC)>6$FjyF[]l6$&Fbal6#F[bl&FealFcbl>80*&Fg`lF,Fi]lF,>81*&Fj`lF,F
[^lF,>82-I".G6$FgzFhz6%)&F\^lFiy%#%TG,&-F^cl6$Fa_l-%&crossG6#FfblF,-F^cl6$-Fhcl
6#FiblFa_lF[\l&Fj]lFiy>83-F^cl6%)&F\^lFb]lFcclFdcl&Fj]lFb]l>84-F`^l6$-F[`l6#F\c
l-F[`l6#F`dl>Fhal7$&FhalF]v*&-I'factorG6$FgzFhz6#-&I.LinearAlgebraG6$FgzFhz6#%,
DeterminantG6#FgdlF,F+F[\l>85-%$mapG6$%'expandGFhal@$F[yOF^fl>86-%&minusG6$-%'i
ndetsG6#F^fl-F[gl6#F_y>6$8788-%,poly2matrixG6$F^flFffl>89-%$srtG6$Fbgl-%%tdegG6
#&FfflF]v6&7#-%/permuteColumnsG6%FaglFbglFgglFgglF^xF_xF]vF]vF]v6#F]y6@7'Fd\lF[
\lF`al""'Fg\l7'Fd\lF[\lFgn"#SFi\l7'Fd\lF[\lFgn""*"#X7'Fd\lF[\l""("#bFi\l7'Fd\lF
[\lF^il"#$*Fi\l7'Fd\lF[\lFgn"")Fcil7'Fd\lF[\lF^il"#7Fcil7'Fd\lF[\l"#5"#JFi\l7'F
d\lF[\lFgn"#UFi\l7'Fd\lF[\lFgn"#gFi\l7'Fd\lF[\lFgn"#_Fi\l7'Fd\lF[\lFgnFi\lFi\l7
'Fd\lF[\lFgn"#<Fi\lF`jl7'Fd\lF[\lFgn"#6Fi\lFbil7'Fd\lF[\lF^il"#EFi\l7'Fd\lF[\lF
^il"#AFi\lFfjlF]ilF]il7'Fd\lF[\lF^ilFe\lFi\l7'Fd\lF[\lF^il"#hFi\l7'Fd\lF[\lFgn"
#CFi\l7'Fd\lF[\lFgn"#RF\il7'Fd\lF[\lFgjlFhilF^jl7'Fd\lF[\lFgn"#QFi\l7'Fd\lF[\lF
gnFg\lFi\l7'Fd\lF[\lFgnFhilFi\l7'Fd\lF[\lFgn"#^FhilF]v
