M7R0
I*F_focal6p7,,T%"xG#!("fW:")+]i:%"yG#!*topE$"*++++&%"zG#!*87N*GF,*$F)""##")Z!3A
"")++]7*&F-"""F%F6#!*8(=17"*+++D"*&F-F1F%F6#!).UF[F9*&F-F6F)F6#")L\a^")++]i*$F-
F1#")f4PNF,*&F-F6F)F1#!*(fjbTF9*&F)F6F-F1#"*^8E'=F9*&F)F1F%F6#")J.5AF,*&F%F6F)F
6#"*tyBK%"*+++]#*&F%F6F)""$#!(4:X"F9*&F-FRF%F6#!)(fw(GF,*&F-F1F%F1#!$J)"$+&*&F-
F6F%F1#!#B"$]#*&F-FRF%F1#F6""%*(F%F6F-F6F)F6#!*zb%)o(F,*(F%F6F)F1F-F6#"*"R*Q$GF
9*(F-F1F)F6F%F6#!*tgIz#F,*(F%F1F-F6F)F6#!$,(Fen*(F-F1F%F1F)F6#!$"RFen*$F)FR#"*J
+m-"F9*$F-FR#!(@ln&")+++]#")`RmC"*++++"F6,TF%#")$G/e%FbpF)#!)ff0CF@F-#"*\-aK&F,
F0#"*"o!))=&FPF5#"*VQ$)3"FPF:#!*Pdo!H"+++++5F=#!*p`V#QF9FA#")dAD_F9FD#"*n8J\#F9
FG#"*Pn!G;FPFJ#!*jx/<&F9FM#").vyzFPFQ#!)J4r(*FPFU#!*@&["p"F,FX#!%\5"%+5Ffn#"$">
"$D"Fjn#!$`"FenF]o#!*>dQh'F,F`o#")@Tb6")+++DFco#"*.SG&=FPFfo#"$"))FenFio#"$,#Fi
nF\p#!*pbvP"F@F_p#!)F39=Fbp#!)><re"*++++#F6,HF%#!'ZN5"'++DF)#"'H*4%"'++]F-#!'(y
.$"'+]7F0#"&$4EFgtF5#!'*H#HFatF:#"&p'z"'++?F=#"'$\$\FdtFA#"'p*\%FdtFD#"'$yw%Fat
FG#!&FD%FgtFJ#"'"yL"FdtFM#"&L0("&++&FU#!&6i(FatFX!""F]o#"'*fM#FatF`o#"'`#G'FatF
co#"&(>MFatF\p#!'j08"&+D'#"'`_7F^uF6,TF%#!)Fq^tFbpF)#"*$*\qi"F9F-#!+VB^^GFcqF0#
!*RLo6"FPF5#")<cgY")++DJF:#"**3J3:F]tF=#!**y@/BFPFA#"+(3Wki"F,FD#!*2?>(RFPFG#")
f#z$=F@FJ#"+L_:O7F,FM#!*x#)o!HF9FQ#")tgW!*F@FU#!*ZBgh)FcqFX#!$8*FfrFjn#"$*>"$+#
F]o#"*Hiz.*FPF`o#")4\pF")+++?Fco#!*`\:">F9FfoFgnFio#!%j5Fen*(F%F1F)F1F-F6FgoF\p
#")H*f$)*F@F_p#!)J#\!)*Fep#"*44[4"F]tF6,TF%#!)6,FbFPF)#!**zMA:FPF-#!+^xAe6FcqF0
#")\.IBFbpF5#!)^VowF@F:#"*H0C9$F]tF=#"*dzF\$FPFA#"*HiLT&F,FD#"**Qq>PFPFG#!*P\tT
#F9FJ#!*T$R))QFepFM#")xo0:F(FQ#!*T&\!3#F9FU#!*rilK#FcqFX#!"$"")Fjn#"$d#FfrF]o#!
(pEN""(]i!RF`o#"+R/4u5F,Fco#")4X1!)FewFfoFgrFio#"$F"FinFfyFcsF\p#!(68O*"(++D'F_
p#!)(z<F"Fep#")")G#p'F]tF6,HF)#!'8GB"(+++"F-#"'h97FdtF0#!&Vj*"&]7$F5#!'^A7FatF:
#"(TC1"FdtF=#"(dV3"FatFAFeuFD#!&E;""&Dc"FG#!'p*\%FdtFJFiuFMF_tFQFguFU#!'hw&*Fdt
F]o#"'$)RBFgtF`o#"(^f^"FdtFco#"&`<%Fb]lFioF^vF\p#"&xh%Fat#!&6u""'++5F6,PF%#"("e
"Q#F9F)#!*,dJJ#FcqF-#!+Z[N'f"FcqF0#!*@6gg"FbpF5#"(*)41"")+++5F:#!*\k[V"F,F=#")L
sfuFPFA#"*Lmr"eFPFD#"+jva(3"FPFG#!'8/DF,FJ#!)"*oGJFewFM#")dQOcFPFQ#!)"[!y$*F,FU
#!**y$\c"F]tFX#FhnFenFjn#!$,*FfrF]o#"***)\#p&FPF`o#!(hAW""(+D"yFco#!+">&3fLFcqF
io#FhoFfrF\p#!**[))*f#FPF_p#!)fx[WFbp#"(zzl(FayF6,PF%#!)xux>F@F)#!*`\sZ%F]tF-#"
**oMoGFPF0#!)(*RoNFbpF5#"*n$e(G"F9F:#"*H*ybLFPF=#"*rE"HaF9FA#")"QU'pFPFD#")4j8o
F9FG#!+6XkZ=F,FJ#"*2A!=OFPFM#"*`6@y"FPFQ#"*h5'y6F,FU#!)"**o1#FepFX#FhrFinFjn#!$
>"FenF]o#!*<(*4*>FPF`o#!*V^#)G"FepFco#")(pk-&FcqFio#FdsFfrF\p#"*6t)f5FbpF_p#!)^
\/6Fep#!(j9%zF`sF6,DF)#!'Fs>FdtF-#"'B?&)Fb]l#!'`56FgtF6F0#"'.;HFgvF5#!'`kRFatF:
#"&$>qFatF=#"&*\>"&++#FA#!'ZMZFatFD#"%.%*"%]iFG#!(x'o9FdtFU#!'*ot"F^uFjnF^vF]o#
!&L0(F[vF`o#!("yL6FdtFco#!'B>UFdtF\p#"'2NFFgtF_p#"'@77F__l,6F)#!'^]nFdtF-#"'2F7
F__lF0#"(PJC"Fb]lF=#"(2PT"Fb]lFA#!%*["F`flFD#!&44&FgtFG#"'j'["FgtF\p#"&pE'FdtF_
p#!%4Y"&+D"#!'"Rd$FdtF66",
I*C_focal6pw,6#>%)symbolicGF662%&_nameG%&_sizeG%#_AG%"iG%#M1G%"XG%"FG%"KG%&omeg
aG%"GG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FehlC1>6$8$8%6$7#%"MG7#7$""'FR@%/9$
""!>8&7#-%$seqG6$-%'rndMatG6#&&Fajl6#8'Fehl/Fh[m;F6-%%nopsG6#F`jl>F][m7#-F`[m6$
-I'MatrixG6$%*protectedG%(_syslibG6$Fe[mw,6$F%F)Fehl6$%)operatorG%&arrowGFehl-&
T'6#T%6#,&FjjlF6*&,&9%F6F^vF6F6&&T#F`]m6#F6F6F6FehlFehl6(F]ilFajlF_ilFh[mF\ilF`
jl6#F16$7'Q!FehlF^v"#P"#s"#O7'F_^mF^vF`^m"#VFb^mFi[m>8(-I$<,>G6$Fe\mFf\m6$&F][m
Fj]m,$-&I.LinearAlgebraG6$Fe\mFf\m6#%/IdentityMatrixG6#FRF^v>8)-%$mapG6$w,6#F%F
ehl6$F[]mF\]mFehl-Fh^m6%-I$<|gr>G6$Fe\mFf\m6%&Fi]m6$F6Fjjl&Fi]m6$F1Fjjl&Fi]m6$F
RFjjl-F_`m6%&Fi]m6$F\oFjjl&Fi]m6$""&Fjjl&Fi]m6$FgjlFjjl-F_`m6%&Fi]m6$""(Fjjl&Fi
]m6$F\\lFjjl&Fi]m6$""*FjjlFehlFehl6$F`ilFf^m6#F66$7'F_^mF^v"#7"#*)Fb^m7'F_^mF^v
F_bm"#9Fb^m7#-%"$G6#;F6FR>8*z)6'F)F-&Fe_mFj]m&Fe_m6#F1&Fe_mFc_m[[_[[[[[[[\[sF6
\[[[[[[_[[[[sF6[[[[[\[[[[[[oF6>8+-Fh^m6%-F_`m6%F6F[[mF[[m-F_`m6%F[[mF6F[[m-F_`m
6%F[[mF[[m*$%"fGF^v>8,-I(algsubsG6$Fe\mFf\m6$/*$F[dm!"#F%-I".G6$Fe\mFf\m6$Facm)
Facm%#%TG>8-,&-Ffdm6',$FibmF1F]dm)FibmFjdmF]dmFibmF6*&-&F__m6#I&TraceG6$Fe\mFf
\m6#-Ffdm6&FibmF]dmFaemF]dmF6FibmF6F^v>8.7$&-%(convertG6$F\em%%listGFehl-&F__m6
#%,DeterminantG6#Fibm>8/-Fg_m6$%'expandGF\fm@$FijlOFifm>80-%&minusG6$-%'indetsG
6#Fifm-Fegm6#F][m>6$8182-%,poly2matrixG6$FifmF`gm>83-%$srtG6$F\hm-%%tdegG6#&F`g
mFehl6&7#-%/permuteColumnsG6%F[hmF\hmFahmFahmF`jlFajlFehlFehlFehl6#F[[m657'F_^m
F^v"#;FgjlFb^m7'F_^mF^vFR"#KFd^m7'F_^mF^vFRFjam"#X7'F_^mF^vFeam"#bFd^m7'F_^mF^v
Feam"#$*Fd^m7'F_^mF^vFR"#]Fd^m7'F_^mF^vFR"$+"Fd^m7'F_^mF^vFR"#DFd^m7'F_^mF^vFR"
#IFd^m7'F_^mF^vFR"#NFd^m7'F_^mF^vFR"#rFd^m7'F_^mF^vFR"#gFd^m7'F_^mF^vFR"#CFd^m7
'F_^mF^vFR"#RFeim7'F_^mF^v"#A"#J"#_7'F_^mF^vFR"#QFd^m7'F_^mF^vFRFb^mFd^m7'F_^mF
^vFRF^[nFd^m7'F_^mF^vFR"#^F^[nFehl
