M7R0
I-F_gp4p_scale7,,L%"vG#!&*eA"'++5%"xG#!'>t>"'++D%"yG#!'x<l"'++]%"wG#!'P9lF0%"zG
#!'([^&F0*$F%""##"'$[?""(+++"*&F1"""F%F=#!'@mVF0*&F)F=F%F=#!&T5&F,*&F-F=F%F=#"&
dG("'+]7*&F4F=F%F=#"&x%*)FF*$F1F8#"(()oV"F;*&F)F=F1F=#"'87]F,*&F-F=F1F=#!'ZH^F0
*&F4F=F1F=#!'@&y"FF*$F)F8#"'`bYF;*&F-F=F)F=#!'4%p&F,*&F4F=F)F=#"'*>L)F0*$F-F8#!
'x$R%F;*&F-F=F4F=#"'nKXF0*$F4F8#"&^.%"&++&#"'JBaF;F=,LF%#!'z.=FFF)#"'t[AFFF-#!(
t5f"F0F1#!&Vz$F,F4#!$o%"%DJF7#!'*3V%F;F<#!%<8"&]7$F@#"'<#R$F,FC#!'F+7F,FG#"'()3
#*F0FJ#"'4cGF,FM#"'@!e(F0FP#"'RmCF0FS#"%@6FboFV#!'B@^F;FY#!'dxvF0Ffn#!&2'>"&+D"
Fin#"'.&e&F0F\o#"%*z("%]iF_o#"'$G@&F;#"&`/""'++?F=,LF%#"&6A#F(F)#!&Hi$FFF-#!&<P
%"&++#F1#!&p[)F(F4#!&4l%F0F7#"%h>FFF<#!%<RF,F@#!&t7$F,FC#!'*)*3"F0FG#!$\("&+]#F
J#"'.^VF;FM#!&zt)FFFP#"'*=3$F0FS#!'**HQF,FV#"%uf"&Dc"FY#!&tz%"&+D'Ffn#"'$)>[F,F
in#!'"eK)F;F\o#"'*z\#F0F_o#!%h9Fjq#"'"z%yF;F=,LF%#!'dw=F0F)#"&Hs"FjqF-#!'JcUFFF
1#"%\IF[tF4#"'dHVF0F7#!&Fx*F,F<#"'4X!)F0F@#"&LY#FepFC#!'.1XF,FG#!'<,7F0FJ#!'`V5
FFFM#!((*o="F0FP#"&<K%F\sFS#"%hyFboFV#"&2'eFFFY#"'4DhF0Ffn#"'8KpF0Fin#!'**zzF;F
\o#!'R69F(F_o#!'HHtF;#"&.i*F,F=,LF%#!&$paF,F)#!'"RT'F;F-#"'FQ@F(F1#!'Lw8F0F4#!'
()f;F;F7#!$L(F;F<#!'V'3"F0F@#!&<8*F;FC#!$$RF_rFG#!%^yFboFJ#"(,S7"F;FM#!&67$F;FP
#!'64fF;FS#"&P.#F\sFV#!&LM)FFFY#"&J9(FdrFfn#"&HY'FdrFin#!'V+XF0F\o#!(*f$R#F;F_o
#!&2)yF;#!&(H`F(F=,LF%#!'\#)HF;F)#!&pI(F0F-#!'6O8FFF1#"'B9SF,F4#!(P66"F;F7#!&PJ
%F,F<#"&n<'FboF@#"'dxpF;FC#!'jObF0FG#!&*3@F0FJ#!&ZF""&++"FM#!'(p7#F0FP#"'V%p%F0
FS#"%R5FjqFV#!'p[$*F;FY#"(*)fl"F;Ffn#!'jNgF;Fin#!&"46FepF\o#"'2g:F,F_o#"&R(HF0#
"&4_#FFF=,LF%#!'*)\[F;F)#"'d5WF;F-#"&$y?FepF1#"'F"R&F;F4#"&`E'"&++%F7#!&"pxF;F<
#"'\')[F;F@#!'BWBF;FC#"&TW&F0FG#"&<C$Fa^lFJ#!'*oS$F0FM#!'pVCF;FP#"&ff&FdrFS#!'T
\$*F;FV#"%LM"%+]FY#!'VnkF;Ffn#"&x#**F;Fin#"'pBLF0F\o#"&Bo)F0F_o#!&xy#Fit#!%P@Ff
_lF=,LF%#"&t&QFdrF)#"'H=VF0F-#!%@$*FitF1#"'$\H&F0F4#"%B'*FepF7#"&(o[F;F<#"&<e'F
drF@#!'x0DF;FC#!'2l6F;FG#!&x\#FitFJ#!'(\X"FdrFM#!'t"H(F;FP#"&2Q'FdrFS#!',6qF0FV
#"'(Hc%F0FY#!'n&H"FFFfn#"'Fn!*F;Fin#!%<]F(F\o#"&\d(F0F_o#"&"ejF;#!#TFboF=,LF%#!
&()y"FFF)#!'z6?F0F-#!(Lr%=F;F1#"'8w'*F;F4#!(,g*>F;F7#!%*3"FdrF<#"&T8$FboF@#!'th
^F;FC#!&@N"FdrFG#!'LJ]F;FJ#!%>c"%+SFM#"'\'["F0FP#"'*f^%F;FS#"'ZG;F0FV#"&6$GFboF
Y#!'pmlF0Ffn#"&(>7Fa^lFin#"(*o@7F;F\o#"&,K%FboF_o#"&Vm#Fit#"'RV6F,F=,LF%#"'Pa"*
F;F)#!&$Q:FepF-#"%J`FboF1#!'p%z)F;F4#!'z*p'F;F7#"%'[%FftF<#!'@ptF;F@#!'fk"*F;FC
#"&8@(FFFG#!&8p*F(FJ#"'Jg]F0FM#"'n?GF,FP#!(pFE"F;FS#"(^!e7F;FV#"'T!*pF;FY#!(P#
\<F;Ffn#!'$32&F;Fin#!&.4*FdrF\o#!'ZKHF0F_o#!&zW'F0#"'4sSF;F=6",
I-C_gp4p_scalew,6#>%)symbolicGF=61%&_nameG%&_sizeG%#_AG%"iG%#bbG%"RG%#R2G%&len_
cG%&len_rG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FehlC0>6$8$8%6$7#%"bG7#7$"#8""'
@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F`jl6#8'Fehl/Fh[m;F=-%%nopsG6#F_jl>F][m7#-F
`[m6$-I'MatrixG6$%*protectedG%(_syslibG6$Fe[mw,6$F)F-Fehl6$%)operatorG%&arrowGF
ehl-&T'6#T%6#,&FjjlF=*&,&9%F=!""F=F=&&T#F`]m6#F=F=F=FehlFehl6(F]ilF`jlF_ilFh[mF
\ilF_jl6#F86$7'Q!FehlFg]m"#P"#s"#O7'F`^mFg]mFa^m"#VFc^mFi[m>8(-I".G6$Fe\mFf\m6$
&F][mF[^m-I$<,>GFf\m6(F%F1F)F-F4F=>8))-F^_m6%-I$<|gr>GFf\m6%&Fg^mF[^m&Fg^m6#""%
&Fg^m6#""(-Ff_m6%&Fg^m6#F8&Fg^m6#""&&Fg^m6#"")-Ff_m6%&Fg^m6#""$&Fg^m6#Fgjl&Fg^m
6#""*%#%TG>8*-&%"|irG6#%"^G6%Fa_m%#~$GF8>8+7#-F`[m6$-%$addG6#&Feam6$;FehlFehlFh
[m/Fh[m;F=F]am>8,7#-F`[m6$-Fcbm6#&Feam6$Fh[mFgbmFhbm>8-7,,&&F[cmF[^mF=&F[cmFb`m
Fg]m,&FgcmF=&F[cmF\amFg]m,&&F^bmF[^mF=FhcmFg]m,&F\dmF=&F^bmF\amFg]m-Fi^m6$&Fa_m
6$F=Fgbm)&Fa_m6$F8FgbmFcam-Fi^m6$Fadm)&Fa_m6$F]amFgbmFcam-Fi^m6$FddmFhdm-Fi^m6$
)&Fa_m6$FgbmF=Fcam&Fa_m6$FgbmF8-Fi^m6$F_em&Fa_m6$FgbmF]am-Fi^m6$)FbemFcamFfem>8
.-%$mapG6$%'expandGFdcm@$FijlOF\fm>8/-%&minusG6$-%'indetsG6#F\fm-Fifm6#F][m>6$8
081-%,poly2matrixG6$F\fmFdfm>82-%$srtG6$F`gm-%%tdegG6#&FdfmFehl6&7#-%/permuteCo
lumnsG6%F_gmF`gmFegmFegmF_jlF`jlFehlFehlFehl6#F[[m647'F`^mFg]m"#;FgjlFc^m7'F`^m
Fg]mF]am"#LFe^m7'F`^mFg]mF]amFbam"#X7'F`^mFg]mF^`m"#bFe^m7'F`^mFg]mF^`m"#$*Fe^m
7'F`^mFg]mF]am"#KFe^m7'F`^mFg]mF]am"#mFe^m7'F`^mFg]mF]amFfjlFe^m7'F`^mFg]mF]am"
#RFe^mFcim7'F`^mFg]mF]am"$*>Fe^m7'F`^mFg]mF]am"#CFe^m7'F`^mFg]mF]amFdimFihm7'F`
^mFg]m"#A"#J"#_7'F`^mFg]mF]am"#QFe^m7'F`^mFg]mF]amFc^mFe^m7'F`^mFg]mF]amF\jmFe^
m7'F`^mFg]mF]am"#^F\jmFehl
