M7R0
I6F_opt_vanishingpoints7&,jq%"xG#!%L7"$]#%"wG#"#B"#]*&F%"""%"yGF.#""#"#D*&F%F.%
"zGF.#!%#R""$D"*&F%F.F/F1#!%^=F7*&F%F.F4F1#"%@@F7*&F%F1F/F.#!%%G#F7*&F%F1F4F.#"
$U$F2*$F%F1#!#YF2**F)F.F%F.F/F.F4F.#"%^:F7*(F%F.F/F.F4F.#"%-JF7*(F)F.F%F.F/F.#"
$r"F2*(F)F.F%F.F4F.#"%U6F7*(F)F.F/F.F4F.#"$K"F7*(F)F.F%F.F/F1#!%@@F(*(F)F.F%F.F
4F1#"%^=F(*(F)F.F%F1F/F.#"%W5F7*(F)F.F/F.F4F1#!$r&F7*(F)F.F%F1F4F.#""$F,*(F)F.F
/F1F4F.#FOF,*(F%F.F/F.F4F1FB*(F%F.F4F.F/F1#"%%G#F7*(F%F1F4F.F/F.#!$G&F7*(F%F1F/
F.F4F1Fco*(F%F1F4F.F/F1#!$U$F2*(F%F^oF4F.F/F.#!%-JF7*(F%F.F/F1F4F1#"%2?F7*(F%F.
F/F^oF4F.FE*(F%F.F/F.F4F^o#"#YF2*$F%F^oF`p*$F%""%Fdp*&F)F.F%F.#!%2?F(*&F)F.F/F.
#"$r&F7*&F)F.F4F.#!$r"F,*&F)F.F%F1#!#pF,*&F)F.F/F1#!%^:F(*&F)F.F4F1#FIF(*&F)F.F
%F^o#"%L7F(*&F)F.F/F^o#!$[$F7*&F)F.F4F^o#!""F,*&F%F1F/F1FK*&F%F1F4F1F]p*&F%F^oF
/F.Fjo*&F%F.F/F^o#!"#F2*&F%F^oF4F.F?*&F%F.F4F^o#"%#R"F7*&F%F.F/FhpF&*&F%F.F4Fhp
F&*&F%F^oF/F1F<*&F%F^oF4F1F9*&F%FhpF/F.F5*&F%F1F/F^oF[s*&F%FhpF4F.Fgr*&F%F1F4F^
oF0*$F%""&F&,jqF/F&F)FarF-FE*&F/F.F4F.F5F8F?F>F`p*&F/F.F4F1F<*&F/F1F4F.FK*$F/F1
F0FGFNFJFBFM#FgqF7FPFTFS#!%U6F7FV#!%W5F7FYFjnFfnFWFinFjpF\oFiqF_o#"#pF,FaoF]pFb
oFfoFeoF?FhoF9FioF]pF\pFgrF_pFcoFbpFjoFcpF0*$F/F^oF9*$F/FhpFgrFipF]qF\qFZF_qFfq
FbqF`oFeqF]oFhqF`qFjq#"$[$F7F]rF[rF`r#!#BF,FcrFjo*&F/F1F4F1FBFerFdpFfrFK*&F/F^o
F4F.Fco*&F/F.F4F^oF[sF]sF[sF_sF5FasF&FbsF<*&F/F.F4FhpF&*&F/F^oF4F1F`p*&F/FhpF4F
.FE*&F/F1F4F^oFdp*$F/FfsF&,jqF4F&F)FetF3FEFhsF0F;FBFisFKFAF`pFjsF9*$F4F1F5FGF]t
FJF?FMFTFPFHFS#FaqF2FVF`oFY#!"$F,FfnFiqFinFcqF\oFZF_oFjpFaoFfoFboFKFeoFjoFhoF]p
FioF<F\pF5F_pFjoFbpF[sFcpFco*$F4F^oF<*$F4FhpF[sFipF`qF\qFfqF_qFWFbqF]qFeqFjnFhq
F_tFjq#F.F,F]rF*F`rF[rFdrF?FitFcoFirFdpFjrF]pFjtFgrF[uFBF^sF0F`sFgrFcsF&FdsF9F
\uFdpF]uFEF^uF&F_uF`p*$F4FfsF&z-6&F)F%F/F4[[[[[[][[[[[mFbr[[[][[[[[[[[mFbr][[[[
[[[[[[[mFbr[[[[[[[[[\[[lF.!Fbr6",
I6C_opt_vanishingpointsw,6#>%)symbolicGF.67%&_nameG%&_sizeG%#_AG%"iG%$mm1G%$mm2
G%$mm3G%'symMatG%$denG%"RG%#v1G%#v2G%#v3G%#JpG%$dJpG%$eqsG%#_FG%&_varsG%$_C0G%$
_V0G%#_VG6"F\vC4>6$8$8%6$7%%#M1G%#M2G%#M3G7#-%"$G6$7$""'F.F^o@%/9$""!>8&7#-%$se
qG6$-%'rndMatG6#&&F]x6#8'F\v/Fiy;F.-%%nopsG6#F\x>F^y7#-Fay6$-I'MatrixG6$%*prote
ctedG%(_syslibG6$Ffyw,6$F%F/F\v6$%)operatorG%&arrowGF\v-&T'6#T%6#,&F[yF.*&,&9%F
.FbrF.F.&&T#Fa[l6#F.F.F.F\vF\v6(FdvF]xFfvFiyFcvF\x6#F16$7'Q!F\vFbr"#P"#s"#O7'F`
\lFbrFa\l"#VFc\lFjy>6%8(8)8*6%-%(convertG6$&F^yF[\lI'VectorG6$FfzFgz-F]]l6$&F^y
6#F1F`]l-F]]l6$&F^y6#F^oF`]l>8+w,6#%"vGF\v6$F\[lF][lF\v-I$<,>GFgz6%-I$<|gr>GFgz
6%&F[yF[\l&F[yFe]l&F[yFi]l-Fd^l6%Fg^l&F[y6#Fhp&F[y6#Ffs-Fd^l6%Fh^lF]_l&F[y6#Fhx
F\vF\vF\v6#F.6$7'F`\lFbr"#8"#jFc\l7'F`\lFbrFf_l"#:Fc\l>Fg\l6%-F[^l6#Fh\l-F[^l6#
Fi\l-F[^l6#Fj\l>8,z+6%F%F/F4[[[[[[[[][[[mF.[[[[][[[[[[[mF.][[[[[[[[[[[mF.!F.>8-
-Fa^l6%-Fd^l6%z+Fe`l[[[[[[[[][[[mF.[[[[][[[[[[[mFbr][[[[[[[[[[[mFbr!F.z'Fe`l[[[
[\[[[\[[[mF1\[[[[[[[[[[[lF1z'Fe`l\[[[[[[[\[[[mF1[[[[\[[[[[[[lFhr-Fd^l6%z'Fe`l[[
[[\[[[\[[[mF1\[[[[[[[[[[[lFhrz+Fe`l[[[[[[[[][[[mFbr[[[[][[[[[[[mF.][[[[[[[[[[[m
Fbr!F.z'Fe`l\[[[\[[[[[[[mF1[[[[[[[[\[[[lF1-Fd^l6%z'Fe`l\[[[[[[[\[[[mF1[[[[\[[[[
[[[lF1z'Fe`l\[[[\[[[[[[[mF1[[[[[[[[\[[[lFhrz+Fe`l[[[[[[[[][[[mFbr[[[[][[[[[[[mF
br][[[[[[[[[[[mF.!F.>6%8.8/806%-Fa^l6%F.F\yF\y-Fa^l6%F\yF.F\y-Fa^l6%F\yF\yF.>81
,(-I".G6$FfzFgz6')F[bl%#%TGFg`lFh\l)Fg`lF]clF[blF.-Fibl6')F\blF]clFg`lFi\lF^clF
\blF.-Fibl6')F]blF]clFg`lFj\lF^clF]blF.>82-Fa^l6%-%%diffG6$FfblF%-Fjcl6$FfblF/-
Fjcl6$FfblF4>837%,&*&F)F.&FfclF[\lF.F.*&F%F.FfblF.!"%,&*&F)F.&FfclFe]lF.F.*&F/F
.FfblF.Fgdl,&*&F)F.&FfclFi]lF.F.*&F4F.FfblF.Fgdl>Fadl7$&FadlF\v,&F)F.Fc`lFbr>84
-%$mapG6$%'expandGFadl@$FjxOFeel>85-%&minusG6$-%'indetsG6#Feel-Fbfl6#F^y>6$8687
-%,poly2matrixG6$FeelF]fl>88-%$srtG6$Fifl-%%tdegG6#&F]flF\v6&7#-%/permuteColumn
sG6%FhflFiflF^glF^glF\xF]xF\vF\vF\v6#F\y687'F`\lFbr"#;FhxFc\l7'F`\lFbrF^o"#\Fe
\l7'F`\lFbrF^o""*"#X7'F`\lFbr""("#bFe\l7'F`\lFbrFehl"#$*Fe\l7'F`\lFbrF^o"#*)Fe
\l7'F`\lFbrF^oFg_lFe\l7'F`\lFbrF^o"#cFe\l7'F`\lFbrF^oF+Fe\l7'F`\lFbrF^o"$9"Fe\l
7'F`\lFbrF^o"#ZFe\l7'F`\lFbrF^o"#iFe\l7'F`\lFbrF^o"#[Fe\l7'F`\lFbrF^o"#gFe\lF^i
l7'F`\lFbrF^o"#CFe\l7'F`\lFbrF^o"#RFchl7'F`\lFbr"#A"#J"#_7'F`\lFbrF^o"#QFe\l7'F
`\lFbrF^oFc\lFe\l7'F`\lFbrF^oF_jlFe\l7'F`\lFbrF^o"#^F_jlF\v
