M7R0
I/F_p6pf_refract7&zW6&%"wG%"xG%"yG%"zG\[[\[[][[\[[p!>6QE+:"=$yEKc+B$>\[[][[\[[
\[[p!>RkuWlV#3Uy7u.Vt^[[[[[\[[\[[p"=)zscK$4[L6'p#*yt#^[[\[[[[[\[[p!>5]7wc$HUzum
Pb9>[[[\[[][[\[[oF+[[[][[\[[\[[o">6QE+:"=$yEKc+B$>][[[[[\[[\[[o">h]lM*[x!)zbJ0]
DN][[\[[[[[\[[o">,./P0#)*e2=0[Ko`[[[\[[^[[[[[o">e8)\(zdsvrql4En"][[[[[][[[[[o!=
g%[tX^:Rr'o\I%*G[[[^[[\[[[[[oF1][[\[[\[[[[[o!>e8)\(zdsvrql4En"][[][[[[[[[[oF2_[
[[[[[[[[[[o"=g%[tX^:Rr'o\I%*G\[[[[[\[[\[[nF0\[[\[[[[[\[[n!>h]lM*[x!)zbJ0]DN\[[[
[[][[[[[n!='3mBUl->94Do@1"\[[][[[[[[[[nF6^[[[[[[[[[[[n"='3mBUl->94Do@1"[[[[[[\[
[\[[m">5]7wc$HUzumPb9>[[[\[[[[[\[[mF,[[[[[[][[[[[mF4[[[\[[\[[[[[mF3[[[][[[[[[[[
mF4\[[[[[[[[[[[lF7!F2z/F%\[[[[[\[[\[[n";3w\#GZj]b!4X$Q&[[[\[[[[[\[[mF:[[[\[[\[[
[[[m!;T'yb'*>"3f[JYoT][[[[[[[[[[[m!:]J9@#G'z!4<$f*[\[[[[[[[[[[[l":TV!f!4?A@>6v#
R!":]J9@#G'z!4<$f*[z/F%\[[\[[[[[\[[n":,AJ5MHQ>j8$Hn[[[[[[\[[\[[m!:,AJ5MHQ>j8$Hn
[[[\[[\[[[[[m";o8U$y"\(**zJvc7"][[[[[[[[[[[m!:gCEV)=aa)R'*)eO\[[[[[[[[[[[l";Sxu
$\zY_fs6j9"!":gCEV)=aa)R'*)eOz/6%F'F(F)[[[[[[[[][[[m";/)[7ktJvFXD<p#[[[[\[[[\[[
[m!<Ro%)zIT+fMOp&*="[[[[][[[[[[[m!;/)[7ktJvFXD<p#][[[[[[[[[[[m!;YG#*)*=YuaG>kZW
\[[[[[[[[[[[l"<r$*o7@baWIqDt0"!";YG#*)*=YuaG>kZW6",
I/C_p6pf_refractw,6#>%)symbolicG"""67%&_nameG%&_sizeG%#_AG%"iG%"KG%#rrG%#ccG%$e
qsG%"kG%%varsG%"MG%"VG%#V1G%#M1G%$tM1G%%solsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FN
C7>6$8$8%6$7$%#xxG%"XG7#-%"$G6$7$""$""'""#@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F
jo6#8'FN/Fgq;FT-%%nopsG6#Fio>F\q7#-F_q6$-I'MatrixG6$%*protectedG%(_syslibG6$Fdq
w,6$F'F(FN6$%)operatorG%&arrowGFN-&T'6#T%6#,&FipFT*&,&9%FT!""FTFT&&T#F_s6#FTFTF
TFNFN6(FWFjoFYFgqFVFio6#Ffp6$7'Q!FNFfs"#P"#s"#O7'F_tFfsF`t"#VFbtFhq>8(-&I.Linea
rAlgebraG6$FdrFer6#%/DiagonalMatrixG6#7%FTFTF&>8)-%-getRotMatrixG6#-I$<,>GFerFG
>8*-Feu6%%"uG%"vGFjp>8+7#-F_q6$*&-I'factorG6$FdrFer6#-I".G6$FdrFer6$)-&Fit6#%-C
rossProductG6$-Fgv6%)F`u%#%TGFft&&F\qFjs6$;FNFN8,,&&&F\q6#FfpFfwFTFguFfsFcw-Feu
6%FjpFjpFTFTz+FG[[[[[[[[][[[mFT[[[[][[[[[[[mFT][[[[[[[[[[[mFT!FTFT/Fhw;FTFep>F]
v-%$mapG6$%'expandGF]v>8-7(FjuF[vF&F'F(F)>6$8.8/-%,poly2matrixG6$F]vFhx>80-Feu6
<**FjuFTF&FTF(FTF)FT*&FjuFTF'Ffp*(FjuFTF'FTF(FT*(F)FTF'FTF&FT*(F)FTF(FTF&FT*$F'
Ffp*(FjuFTF&FTF'FT*&FjuFTF(Ffp*&FjuFTF)Ffp*&FjuFTF)FTFju**F[vFTF&FTF'FTF)FT*(F[
vFTF&FTF(FT*&F[vFTF'Ffp*(F[vFTF'FTF(FT*&F[vFTF(Ffp*&F[vFTF)Ffp*&F[vFTF)FTF[v*&F
&FTF'FT*&F&FTF(FT*$F(Ffp*&F'FTF(FT*$F)FfpF)FT>81-%/permuteColumnsG6%F\yF]yFby@%
Fhp>82-&Fit6#%6ReducedRowEchelonFormG6#F\[l>Fb[l-Fbr6#7(7<FTFjpFjpFjpFjpFjpFfsF
jpFjpFjpFjpFfsFfsFjpFjpFjpFjpFjpFjpFjpFjpFjp-%"AG6#"#(*-F^\l6#"$."-F^\l6#"$4"-F
^\l6#"$:"7<FjpFTFjpFjpFjpFjpFjpFfsFTFjpFfsFjpFjpFjp-F^\l6#"#]FjpFjp-F^\l6#"#oFj
pFjpFjpFjp-F^\l6#"#)*-F^\l6#"$/"-F^\l6#"$5"-F^\l6#"$;"7<FjpFjpFTFjpFjpFjpFjpFjp
FjpFTFjpFjpFjp-F^\l6#"#XFjp-F^\l6#"#d-F^\l6#"#jFjp-F^\l6#"#vFjpFjpFjp-F^\l6#"#*
*-F^\l6#"$0"-F^\l6#"$6"-F^\l6#"$<"7<FjpFjpFjpFTFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFj
pFjpFjpFjpFjpFjpFTFjp-F^\l6#"$+"-F^\l6#"$1"-F^\l6#"$7"-F^\l6#"$="7<FjpFjpFjpFjp
FTFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFfsFjpFjp-F^\l6#"$,"-F^\l6#"$2"-F^
\l6#"$8"-F^\l6#"$>"7<FjpFjpFjpFjpFjpFTFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFjpFj
pFjpFfs-F^\l6#"$-"-F^\l6#"$3"-F^\l6#"$9"-F^\l6#"$?">F]v7#-F_q6$-Fgv6$&Fb[l6$Fgq
FgwFby/FgqFax>83&-I&solveG6$FdrFer6$7$&F]vF\x&F]v6#Fdp7$FjuF[vFjs>F]v-Fdx6$%&nu
merG7&-Fcv6#-%%subsG6$Fgbl&F]vFjs&F]v6#""%&F]v6#""&&F]v6#Fep>84Fcx@$FhpOFfdl>85
-%&minusG6$-%'indetsG6#Ffdl-F_el6#F\q>6$8687-F_y6$FfdlFjdl>88-%$srtG6$Ffel-%%td
egG6#&FjdlFN6&7$F\[l-F^[l6%FeelFfelFjelFjelFioFjoFNFNFN6#Fjp6=7'F_tFfs"#;FepFbt
7'F_tFfsFdp"#UFdt7'F_tFfsFdp""*F`^l7'F_tFfs""("#bFdt7'F_tFfsF_gl"#$*Fdt7'F_tFfs
Fdp"#ZFdt7'F_tFfsFdp"#JFdt7'F_tFfsFdp"#<Fdt7'F_tFfsFdp"$B"Fdt7'F_tFfsFdp"#DFdt7
'F_tFfsFdp"#GFdt7'F_tFfsFdp"#KFdt7'F_tFfsFdp"$i"FdtF_hlF\gl7'F_tFfsF_gl"#`Fdt7'
F_tFfsF_gl"$\'Fdt7'F_tFfsFdpFbtFdt7'F_tFfsFdp"#WFdt7'F_tFfsFdp"#tFdt7'F_tFfsFdp
"#CFdt7'F_tFfsFdp"#RF`^l7'F_tFfs"#AFfgl"#_7'F_tFfsFdp"#QFdtFghlFegl7'F_tFfsFdpF
`glFfglFN
