from .inidata_num_opt_vanishingpoints import inidata_num_opt_vanishingpoints
from .coefs_opt_vanishingpoints import coefs_opt_vanishingpoints
from .red_136x194_opt_vanishingpoints import red_136x194_opt_vanishingpoints
from .test_num_opt_vanishingpoints import test_num_opt_vanishingpoints