M7R0
I9F_parallel_robot_55_dim17',**$%"xG""#"""*$%"yGF'F(*$%"zGF'F(#!#t"%+5F(,hpF&#!
$#="$D"%"uG#!'(Gh$"'++D%"vG#"'2Z="'+]7F*#!#F"$+&%"wG#!'@7@F7F,#"$*f"$]#*&F4F(F8
F(#!',6LF7*&F4F(F?F(#!#z"&Dc"*&F4F'F&F(F1*&F&F(F8F'#!$\&FD*&F&F(F?F'FN*&F8F(F?F
(#"'V(H#F7*&F4F'F*F(#!$@'F>*&F*F(F8F'F<*&F*F(F?F'FU*&F4F'F,F(#"$)>F3*&F,F(F8F'F
Z*&F,F(F?F'FB*&F4F'F&F'F(*&F8F'F&F'F(*&F?F'F&F'F(*&F8F(F&F(#!$.#FD*&F?F(F&F(#"$
(HFD*&F4F'F*F'F(*&F8F'F*F'F(*&F?F'F*F'F(*&F4F(F*F(#"$.#FD*&F?F(F*F(#!#P"#]*&F4F
'F,F'F(*&F8F'F,F'F(*&F?F'F,F'F(*&F4F(F,F(#!$(HFD*&F8F(F,F(#"#PFjoF%F(F)F(F+F(*$
F4F'#"(*)[;#"(+++"*$F8F'#"((fbCFgp*$F?F'#"(\%[OFgp#"(<ze#FgpF(*(F4F(F8F(F&F(F_o
*(F4F(F?F(F&F(Feo*(F4F(F8F(F*F(Fbp*(F*F(F?F(F8F(Feo*(F4F(F?F(F,F(Fbp*(F,F(F?F(F
8F(F_o,hpF&#!$V'F>F4#"&.B$"&]7$F8#!'<#\'F7F*#"$z""$+"F?#"'8>\F7F,#"%>:F>FE#!&8[
*"&++&FH#!'hBfF7FLFgqFM#"$Z"F`rFPFjrFQ#"'.?:"&+D'FT#"$2&F>FWF^rFXF_sFY#"$$GF>Ff
nFasFgnFcrFhnF(FinF(FjnF(F[o#!$4$F3F^o#"#(*F3FaoF(FboF(FcoF(Fdo#"$4$F3Fgo#"$*oF
DF[pF(F\pF(F]pF(F^p#!#(*F3Fap#!$*oFDF%F(F)F(F+F(Fdp#"'(e_&FgpFhp#"(RLA"FgpF[q#"
'F8e"'++?F`qFesFaqFgsFbqF]tFcqFgsFdqF]tFeqFes#"'nZmFetF(,hpF&#!#@"#?F4#"'49>F;F
8#"&*G')F^sF*#"#")F`rF?#"&2!QFgrF,#"$h"FDFE#"'>sEF7FH#!&LO*F^sFLFitFMFUFPFUFQ#"
'.NJF;FT#"%.7F>FWF`uFXF\vFY#!$n%FDFfnF^vFgnFduFhnF(FinF(FjnF(F[o#!$9$F3F^o#!$*R
FDFaoF(FboF(FcoF(Fdo#"$9$F3Fgo#!#CF3F[pF(F\pF(F]pF(F^p#"$*RFDFap#"#CF3F%F(F)F(F
+F(Fdp#"'>)e$"'++5Fhp#"(6v?""'++]F[q#"(nZY"FawF`qFbvFaqFdvFbqFjvFcqFdvFdqFjvFeq
Fbv#"'n"o(FawF(,hpF&#"$>"F3F4#"'Ls8F^sF8#"'"H)=F;F*#"#B"#DF?#!'@-;F^sF,#"$R$FDF
E#"'r%e#F^sFH#"%-QFKFLFgwFM#!$8'FDFPFhxFQ#"&**)pF^sFT#"$x$F3FWF]xFXF\yFY#!#TF3F
fnF^yFgnFbxFhnF(FinF(FjnF(F[o#!$@%FDF^o#!$i#F3FaoF(FboF(FcoF(Fdo#"$@%FDFgo#!$^)
FDF[pF(F\pF(F]pF(F^p#"$i#F3Fap#"$^)FDF%F(F)F(F+F(Fdp#"'<eRF;Fhp#"'V^fF7F[q#"'RZ
IF^sF`qFbyFaqFdyFbqFjyFcqFdyFdqFjyFeqFby#"&Vo(FgrF(6",
I9C_parallel_robot_55_dim1w,6#>%)symbolicGF(62%&_nameG%&_sizeG%#_AG%"iG%#XXG%#x
xG%#llG%"RG%"tG%$eqsG%"AG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FdzC/>6$8$8%6$7%%"XGF&
%"LG7%7$""&""$Ff\l7$Fg\lF(@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F`\l6#8'Fdz/Fj]l;
F(-%%nopsG6#F_\l>F_]l7#-Fb]l6$-I'MatrixG6$%*protectedG%(_syslibG6$Fg]lw,6$F&F*F
dz6$%)operatorG%&arrowGFdz-&T'6#T%6#,&F\]lF(*&,&9%F(!""F(F(&&T#Fb_l6#F(F(F(FdzF
dz6(F\[lF`\lF^[lFj]lF[[lF_\l6#F'6$7'Q!FdzFi_lFcp"#s"#O7'Fb`lFi_lFcp"#VFd`lF[^l>
6%8(8)8*6%&F_]lF]`l&F_]l6#F'-%(convertG6$&F_]l6#Fh\lI'VectorG6$Fg^lFh^l>6$&Fi`l
6$F(;FdzFdz&Fj`lFjal6$-I$<|gr>G6$Fg^lFh^l6%F]]lF]]lF]]lF^bl>6$8+8,6$-%-getRotMa
trixG6#-I$<,>G6$Fg^lFh^l6%F4F8F?-F[cl6%F&F*F,>8-7#z+6&F&F*F,&F[alF]`l[[[[[[[[[]
[[mF([[[[[[][[[[[mF([[[][[[[[[[[mF(\[[[[[[[[[[[lFi_l?(Fj]lF'F(Fg\l%%trueGC$>8.,
(-I".G6$Fg^lFh^l6$Fdbl)&Fj`l6$Fj]lF[bl%#%TGF(FeblF()&Fi`lFbdlFcdlFi_l>Facl7$&Fa
clFdz*&-I'factorG6$Fg^lFh^l6#z+6&&F[alFi]l&FjclF]`l&FjclF_al&FjclFdal[[[[[[][[[
[[mF([[[][[[[[[[[mF(][[[[[[[[[[[mF([[[[[[[[[\[[lFi_lF(z+F]cl[[[[[[[[][[[mF([[[[
][[[[[[[mF(][[[[[[[[[[[mF(!F(F(>8/-%$mapG6$%'expandGFacl@$F[]lOFfel>80-%&minusG
6$-%'indetsG6#Ffel-Fcfl6#F_]l>6$8182-%,poly2matrixG6$FfelF^fl>83-%$srtG6$Fjfl-%
%tdegG6#&F^flFdz6&7#-%/permuteColumnsG6%FiflFjflF_glF_glF_\lF`\lFdzFdzFdz6#F]]l
657'Fb`lFi_l"#;""'Fd`l7'Fb`lFi_lFh\l"#_Ff`l7'Fb`lFi_lFh\l""*"#X7'Fb`lFi_l""("#b
Ff`l7'Fb`lFi_lFghl"#$*Ff`lFahl7'Fb`lFi_lFh\l"#SFf`l7'Fb`lFi_lFh\l"#WFf`l7'Fb`lF
i_lFh\l"#MFf`l7'Fb`lFi_lFh\l"")Fbil7'Fb`lFi_lF`hl"#RFf`l7'Fb`lFi_lF`hl"#xFf`l7'
Fb`lFi_lFh\lF[wFf`l7'Fb`lFi_lFh\lFdilFehl7'Fb`lFi_l"#A"#JFbhl7'Fb`lFi_lFh\l"#QF
f`l7'Fb`lFi_lFh\lFd`lFf`l7'Fb`lFi_lFh\lF[jlFf`l7'Fb`lFi_lFh\l"#^F[jlFdz
