M7R0
I$rnd,$f*6"F%6"F%,&-f*F%F%6#/%(builtinG%4RandNumberInterfaceGF%F%F%F%F%6%""'"%,
?"#6"""!%+5F2F%F%6$%6_thismoduledefinitionGF%#F2"%+5F%,
I'rndMatw,6$'%"mG%'posintG'%"nGF=F%6$%)operatorG%&arrowGF%-%'MatrixG6%9$9%w,6$%
"xG%"yGF%6$FAFBF%-F"F%F%F%F%6#""#6$7'Q!F%!"""#Y"#d"#O7'FRFSFT"#_FVF%F%F%6#FO6$7
'FRFS""*"#eFV7'FRFSFfn"#KFVF%,
I'rndVecw,6#F;F%6$FAFBF%-%'VectorG6$FFw,6#FJF%6$FAFBF%FMF%F%F%6#F26$7'FRFSFin"#
RFV7'FRFSFin"#MFVF%F%F%6#F26$7'FRFSFfn"#SFV7'FRFSFfn"#@FVF%,
I&crossw,6#%"vGF%6$FAFBF%-%$<,>G6%-%$<|gr>G6%""!,$&FF6#""$FS&FF6#FO-Fip6%F]qF[q
,$&FF6#F2FS-Fip6%,$F`qFSFeqF[qF%F%F%6#F26$7'FRFS"")FgnFV7'FRFSF]r"#5FVF%,
I-getRotMatrixw,FbpF%6$FAFBF%-&%"|irG6#%"/G6%-Ffp6%-Fip6%z+6%FeqF`qF]q[[[[[[[[]
[[[mF2[[[[][[[[[[[mFS][[[[[[[[[[[mFS!F2z'F^s[[[[\[[[\[[[mFO\[[[[[[[[[[[lFOz'F^s
\[[[[[[[\[[[mFO[[[[\[[[[[[[l!"#-Fip6%z'F^s[[[[\[[[\[[[mFO\[[[[[[[[[[[lFasz+F^s[
[[[[[[[][[[mFS[[[[][[[[[[[mF2][[[[[[[[[[[mFS!F2z'F^s\[[[\[[[[[[[mFO[[[[[[[[\[[[
lFO-Fip6%z'F^s\[[[[[[[\[[[mFO[[[[\[[[[[[[lFOz'F^s\[[[\[[[[[[[mFO[[[[[[[[\[[[lFa
sz+F^s[[[[[[[[][[[mFS[[[[][[[[[[[mFS][[[[[[[[[[[mF2!F2%#~$Gz+F^s[[[[[[[[][[[mF2
[[[[][[[[[[[mF2][[[[[[[[[[[mF2!F2F%F%F%6#F26$7'FRFS"#:"$2"FV7'FRFSFat"#<FVF%,
I.getFundMatrixw,6$%#P1G%#P2GF%6$FAFBF%-FD6$F_qw,6$%"jG%"iGF%6$FAFBF%*&)FS,&FGF
2FFF2F2-&%.LinearAlgebraG6#%,DeterminantG6#-Ffp6$-&Fgu6#%*DeleteRowG6$T$FG-F^v6
$T&FFF2F%F%6&FhtFFFitFG6#FO6$7'FRFSFV"$Z"FV7'FRFSFV"#UFVF%F%F%6#FO6$7'FRFS"#;"$
["FV7'FRFSF`w"#DFVF%,
I2getTrifocalTensorw,6%FhtFit%#P3GF%6$FAFBF%-%$mapG6$w,6#%"kGF%6$FAFBF%-FD6$F_q
w,6$F`uF_uF%6$FAFBF%*&)FS,&FbvF2F2F2F2-Ffu6#-Ffp6%-F^v6$FevFbv&T(6$FF;F%F%&T*6$
FGFayF2F%F%6*F^xFFFhtFbvFitFevFgwF_y6#FO6$7'FRFS"#^"$\"FV7'FRFSFiyFUFVF%F%6(Fht
FFFitFGFgw9&6#F26$7'FRFS"#Q"$]"FV7'FRFSFazF]pFV7%F2FOF_qF%F%F%6#F_q6$7'FRFS"#?"
$g"FV7'FRFSFhz"#LFVF%,
I)quat2rotw,6#%"qGF%6$FAFBF%-Ffp6%-Fip6%z+6&FeqF`qF]q&FF6#""%[[[[[[[[[][[mF2[[[
[[[][[[[[mF2[[[][[[[[[[[mFS][[[[[[[[[[[mFSz'Ff[l\[[[[[[[[\[[mFas[[[\[[\[[[[[mFO
z'Ff[l[[[\[[[[[\[[mFO\[[[[[\[[[[[mFO-Fip6%z'Ff[l\[[[[[[[[\[[mFO[[[\[[\[[[[[mFOz
+Ff[l[[[[[[[[[][[mF2[[[[[[][[[[[mFS[[[][[[[[[[[mF2][[[[[[[[[[[mFSz'Ff[l[[[[[[\[
[\[[mFas\[[\[[[[[[[[mFO-Fip6%z'Ff[l[[[\[[[[[\[[mFas\[[[[[\[[[[[mFOz'Ff[l[[[[[[
\[[\[[mFO\[[\[[[[[[[[mFOz+Ff[l[[[[[[[[[][[mF2[[[[[[][[[[[mFS[[[][[[[[[[[mFS][[[
[[[[[[[[mF2F%F%F%6#F26$7'FRFSF1"#!*FV7'FRFSF1"#8FVF%,
I$srtw,6$%"VG%%tordGF%6$FAFBF%-%%sortG6$FFw,FIF%6$FAFBF%-&%)GroebnerG6#%*TestOr
derG6%FGFFFbvF%F%6$F`]lFG6#FO6$7'FRFSFcw"#jFV7'FRFSFcwFinFVF%F%F%6#FO6$7'FRFSF/
"#kFV7'FRFSF/F`wFVF%,
I%suppw,6$%#plG%%varsGF%6$FAFBF%-Fdr6%-&Fi]l6#%(SupportG6$-%'expandG6#-%&numerG
6#FFFGF\t&-Fa_l6$-%&denomGFj_lFGFfqF%F%F%6#FO6$7'FRFS""("#**FV7'FRFSFc`l"#=FVF%,
I%Suppw,6$%"FGF\_l6#%#SFG6"F%C$>8$-Fjw6%Fh^lFFFGO6$F`al<#&-Fjw6$%#opGF`alF%F%F%
F%6#FO6%7'FRFSFc`lF/FV7'FRFSFfnFin"#J7'FRFSF_q"#GFXF%,
I,poly2matrixw,Fi`l6$%"TG%"BG6"F%C%>F`al-Fjw6$w,6#F[_lF%6$FAFBF%-%&tableG6#-%$z
ipG6%w,6$%"aG%"bGF%6$FAFBF%/FGFFF%F%F%6#FO6$7'FRFSFinF\wFV7'FRFSFinFazFV7#-%'co
effsG6%FFFbv.%#mnG7#FcdlF%F%6$F\_lFG6#F26$7'FRFSFf`l"#vFV7'FRFSFf`lF_pFVFF>8%7#
&&-Fg`l6$FFFGFaqF%O6$-FD6#-Fjw6$w,6#%"tGF%6$FAFBF%-Fjw6$w,6#FgclF%6$FAFBF%-%#if
G6%-%)assignedG6#&FbvFj_lFgflF[qF%F%6$FjelFF6#F26$7'FRFSF`bl"#fFV7'FRFSF`bl"#IF
VT#F%F%6$FeblF\el6#F26$7'FRFSF_pFa^lFV7'FRFSF_p"#BFVF`al-F_o6#F\elF%F%F%6#FO6&7
'FRFS"#9F/FV7'FRFSFfn"#zF^bl7'FRFS"##)"$1""#V7'FRFSF_qF]hlFXF%,
I/permuteColumnsw,6%%"MGF_]l%#V1G6#Fcdl6$FAFBF%&FF6$Fay7#-%$seqG6$-&%*ListTools
G6#%'SearchG6$F`alFG-%#inG6$F`alF]zF%F%F%6#F_q6&7'FRFSFdt"#&)FV7'FRFS"#H"#NF]r7
'FRFSFdtF`blFVF]jlF%,
I,samePatternw,6%'FfhlFD'%$symG%%nameG>'%$xclG%$setG<"6'F<F?%#MtG%#iMG%#eMG6"F%
C(>F`al-Fial6$7$F2F2FF>F\el-Fial6$7$F2FOFF>8&-%(convertG6$FFF_cl>8'7#-%(indices
G6$F\\m%+indexorderG>8(-Fjw6$w,6#F`uF%6$FAFBF%-Fbfl6%-Fgil6$&Fbv6#&&T%Fj_lF%F_y
Fb]m-T,6#,(&Fe]mFfqF2*&,&&Fe]mFaqF2FSF2F2T)F2F2*$F_^mFOFSF%F%6,FfhlFFF_[mFa\mFj
jlF]zF<F`alFfjlFG6#F26$7'FRFSF[]l"#%)FV7'FRFSF[]lFatFV7#-%"$G6#;F2-%%nopsG6#Fa
\m-FD6%F`alF\el<#&-Fbcl6%w,FIF%6$FAFBF%/&FFF%FGF%F%F%6#FO6$7'FRFSFhzFinFV7'FRFS
Fhz"#EFVFa\mFh\mF%F%F%F%6#F_q6)Fjgl7'FRFSFfnFcwF^bl7'FRFSF`bl"#WFahl7'FRFSF_qFc
wFahl7'FRFSF_qF[[lFahl7'FRFSF_q"$-"Fahl7'FRFSF_qFb`mFhzF%,
I#gbw,6%Fj`lF`]l%#ppGF%6$FAFBF%-&Fi]l6#%&BasisG6%FFFG/%/characteristicGF]zF%F%F
%6#F_q6$7'FRFS""&"#gFV7'FRFSFgamFdtFVF%,
I$dimw,6$Fj`lF[amF%6$FAFBF%-&Fi]l6#%1HilbertDimensionG6$FF/FcamFGF%F%F%6#FO6$7'
FRFSF/"#hFV7'FRFSF/F[]lFVF%,
I$degw,6$Fj`lF`]lF%6$FAFBF%-F]_m6#&-&Fi]l6#%*NormalSetGFaelFfqF%F%F%6#FO6$7'FRF
SF/FXFV7'FRFSF/FatFVF%
