M7R0
I$rnd,$f*6"F%6"F%,&-f*F%F%6#/%(builtinG%4RandNumberInterfaceGF%F%F%F%F%6%""'"%,
?"#6"""!%+5F2F%F%6$%6_thismoduledefinitionGF%#F2"%+5F%,
I'rndMatw,6$'%"mG%'posintG'%"nGF=F%6$%)operatorG%&arrowGF%-%'MatrixG6%9$9%w,6$%
"xG%"yGF%6$FAFBF%-F"F%F%F%F%6#""#6$7'Q!F%!"""#Y"#e"#O7'FRFSFT"#`FVF%F%F%6#FO6$7
'FRFS""*"#fFV7'FRFSFfn"#KFVF%,
I'rndVecw,6#F;F%6$FAFBF%-%'VectorG6$FFw,6#FJF%6$FAFBF%FMF%F%F%6#F26$7'FRFSFin"#
RFV7'FRFSFin"#MFVF%F%F%6#F26$7'FRFSFfn"#SFV7'FRFSFfn"#@FVF%,
I&crossw,6#%"vGF%6$FAFBF%-%$<,>G6%-%$<|gr>G6%""!,$&FF6#""$FS&FF6#FO-Fip6%F]qF[q
,$&FF6#F2FS-Fip6%,$F`qFSFeqF[qF%F%F%6#F26$7'FRFS"")"#gFV7'FRFSF]r"#7FVF%,
I-getRotMatrixw,6#'FcpF_oF%6$FAFBF%-%$mapG6$%'factorG-%".G6$,&-&%.LinearAlgebra
G6#%/IdentityMatrixGF^qF2-F`p6#FFFS-&F`s6#%.MatrixInverseG6#,&F^sF2FcsF2F%F%F%6
#F26$7'FRFS"#:"$f"FV7'FRFSF^t"#FFVF%,
I$srtw,6$'Fcp<%F_o%%listG%$setG'%%tordG%3ShortMonomialOrderGF%6$FAFBF%-%%sortG6
$FFw,FIF%6$FAFBF%-&%)GroebnerG6#%*TestOrderG6%FGFFT$F%F%6$FjtFG6#FO6$7'FRFS"#k"
$-"FV7'FRFSF]v"#rFVF%F%F%6#FO6$7'FRFSF/"$."FV7'FRFSF/"#bFVF%,
I,poly2matrixw,6%%"FG%#nFG%%varsG6%%%monsG%"iG%%cffsG6"F%C$>8&7#-%'coeffsG6%-%'
expandG6#-%$addG6$*&(%$q_qG8%F2&FF6#FbxF2/Fbx;F2FG9&.8$6$-FD6%FG-%%nopsG6#Fdww,
6$F_w%"jGF%6$FAFBF%-%&coeffG6$&T#6#FG(FaxFFF%F%6$F`wFdw6#FO6$7'FRFS"#E"#aFV7'FR
FSF_zFinFV-F_o6#7#FixF%F%F%6#F_q6%7'FRFS"#9F/FV7'FRFS"#="##)"#V7'FRFSF_qF`v"#JF
%,
I/permuteColumnsw,6%%"MG%"VG%#V1G6$F?F_w6"F%C$>Fix-%#opG6$F2FG-F[s6$FF-FD6$Fix<
#-%$seqG6$/6$Fbx-&%*ListToolsG6#%'SearchG6$&FGFdxFgxF2/Fbx;F2FixF%F%F%6#F_q6%7'
FRFS"#<F/FV7'FRFSFfnF_pF^[l7'FRFSF_qF]v"#?F%
