M7R0
I$rnd,$f*6"F%6"F%,&-f*F%F%6#/%(builtinG%4RandNumberInterfaceGF%F%F%F%F%6%""'"%,
?"#6"""!%+5F2F%F%6$%6_thismoduledefinitionGF%#F2"%+5F%,
I'rndMatw,6$'%"mG%'posintG'%"nGF=F%6$%)operatorG%&arrowGF%-%'MatrixG6%9$9%w,6$%
"xG%"yGF%6$FAFBF%-F"F%F%F%F%6#""#6$7'Q!F%!"""#Y"#e"#O7'FRFSFT"#`FVF%F%F%6#FO6$7
'FRFS""*"#fFV7'FRFSFfn"#KFVF%,
I'rndVecw,6#F;F%6$FAFBF%-%'VectorG6$FFw,6#FJF%6$FAFBF%FMF%F%F%6#F26$7'FRFSFin"#
RFV7'FRFSFin"#MFVF%F%F%6#F26$7'FRFSFfn"#SFV7'FRFSFfn"#@FVF%,
I&crossw,6#%"vGF%6#%'inlineGF%-%$<,>G6%-%$<|gr>G6%""!,$&FF6#""$FS&FF6#FO-Fjp6%F
^qF\q,$&FF6#F2FS-Fjp6%,$FaqFSFfqF\qF%F%F%6#F26$7'FRFS"")"#))FV7'FRFS"#J"#y"#?F%,
I-getRotMatrixw,FbpF%6#FepF%-%$mapG6$%'factorG-%".G6$,&-&%.LinearAlgebraG6#%/Id
entityMatrixGF_qF2FfpFS-&Fas6#%.MatrixInverseG6#,&F_sF2FfpF2F%F%F%6#F26$7'FRFS"
#:"$z"FV7'FRFS"#Q"$p"FcrF%,
I.getFundMatrixw,6$'%#P1GFD'%#P2GFD6%%"FG%"iG%"jG6"F%C%>8$-FDF_q?(8%F2F2F`q%%tr
ueG?(8&F2F2F`qFdu>&F`u6$FfuFcu*&)FS,&FcuF2FfuF2F2-&Fas6#%,DeterminantG6#-Fgp6$-
&Fas6#%*DeleteRowG6$FFFcu-Fev6$FGFfuF2OF`uF%F%F%6#FO6(7'FRFS"#;F/FV7'FRFSF`qF_w
"#V7'FRFSF`qF^rF^r7'FRFS""("#7F^r7'FRFSF1"$E"Faw7'FRFSF`qF1"#_F%,
I)quat2rotw,6#%"qGF%6$FAFBF%-Fgp6%-Fjp6%z+6&FfqFaqF^q&FF6#""%[[[[[[[[[][[mF2[[[
[[[][[[[[mF2[[[][[[[[[[[mFS][[[[[[[[[[[mFSz'Fdx\[[[[[[[[\[[m!"#[[[\[[\[[[[[mFOz
'Fdx[[[\[[[[[\[[mFO\[[[[[\[[[[[mFO-Fjp6%z'Fdx\[[[[[[[[\[[mFO[[[\[[\[[[[[mFOz+Fd
x[[[[[[[[[][[mF2[[[[[[][[[[[mFS[[[][[[[[[[[mF2][[[[[[[[[[[mFSz'Fdx[[[[[[\[[\[[m
Fix\[[\[[[[[[[[mFO-Fjp6%z'Fdx[[[\[[[[[\[[mFix\[[[[[\[[[[[mFOz'Fdx[[[[[[\[[\[[mF
O\[[\[[[[[[[[mFOz+Fdx[[[[[[[[[][[mF2[[[[[[][[[[[mFS[[[][[[[[[[[mFS][[[[[[[[[[[m
F2F%F%F%6#F26$7'FRFSF1"##*FV7'FRFSF1"#8FVF%,
I$adjw,6#'%"AGFD6(F?%"dG%"BG%#AAGF\u%"kG6"F%C(>F`u-%#opG6$7$F2F2FF>Fcu7#-%"$G6#
;F2,&F`uF2FSF2>Ffu*&&FF6$F2F2F2-&Fas6#%+ZeroMatrixG6#F`uF2>8')-Fgp6$-Fjp6$FFFFF
a\l%#%TG@%/-%$modG6$F`uFOF2?(8(F2F2F`uFdu?(8)F2F2F`uFdu>&Ffu6$Fj\lF\]l-F^v6#&F]
\l6$-&%"|irG6#%"+G6%Fcu%#~$GFj\l-Fe]l6%FcuFj]lF\]l?(Fj\lF2F2F`uFdu?(F\]lF2F2F`u
Fdu>F^]l*&)FS,&Fj\lF2F\]lF2F2F`]lF2OFfuF%F%F%6#F26/7'FRFSF/F/FV7'FRFSFfn"#DFar7
'FRFS"#G"#UFaw7'FRFSF`qF[_lFaw7'FRFSF`q"#EFaw7'FRFSF`qFfn"#XFcw7'FRFSF1F_wF^r7'
FRFSF]t"#lFawFcwFa_l7'FRFSF]t"#wFawFhwF%,
I$srtw,6$Fcp%%tordGF%6$FAFBF%-%%sortG6$FFw,FIF%6$FAFBF%-&%)GroebnerG6#%*TestOrd
erG6%FGFFT$F%F%6$Fi_lFG6#FO6$7'FRFSFh^l"#jFV7'FRFSFh^lFinFVF%F%F%6#FO6$7'FRFSF/
"#kFV7'FRFSF/F_wFVF%,
I%suppw,6#%"fGF%6$FAFBF%-&Ff]l6#%"/G6%-&Fb`l6#%(SupportG6#-%'expandG6#-%&numerG
6#FFFj]l&-F]bl6#-%&denomGFfblFgqF%F%F%6#F26$7'FRFSFdwFe_lFV7'FRFSFdwFfnFVF%,
I%Suppw,6#Fjt6#%#SFG6"F%C$>F`u-Fhr6$w,6#%#plGF%6$FAFBF%-FbalFfblF%F%F%6#F26$7'F
RFS"#>"#IFV7'FRFSFbdl"#AFVFFO6$F`u-%(convertG6$-Fhr6$FizF`u%$setGF%F%F%6#F26%7'
FRFSFdwF/FV7'FRFSFfnFioFar7'FRFSF`qF`tFiwF%,
I,poly2matrixw,6$Fjt%%varsG6%Feal%"TGFbz6"F%C%>Fcu7#-%$seqG6$-%&tableG6#-%$zipG
6%w,6$%"aG%"bGF%6$FAFBF%/FGFFF%F%F%6#FO6$7'FRFSFinF[_lFV7'FRFSFinF`tFV7#-%'coef
fsG6%-FbblF[\lFG.F<7#F<-%#inG6$F`uFF>Ffu-Fidl6$&-F`clFfblFbq%%listGO6$-FD6#-Fhr
6$w,6#%"tGF%6$FAFBF%-Fhr6$w,6#FiflF%6$FAFBF%-%#ifG6%-%)assignedG6#&Ff`lFfblFeil
F\qF%F%6$FhhlFF6#F26$7'FRFSFj^lFgnFV7'FRFSFj^lFcdlFVT#F%F%6$FbzFfu6#F26$7'FRFSF
_pF[alFV7'FRFSF_p"#BFVFcu-F_o6#FfuF%F%F%6#FO6&7'FRFS"#9F/FV7'FRFSFew"#!*Faw7'FR
FS"#$*"$A"Faw7'FRFSF`q"#zFiwF%,
I/permuteColumnsw,6%%"MG%"VG%#V1G6#%#mnG6$FAFBF%&FF6$;F%F%7#-F^fl6$-&%*ListTool
sG6#%'SearchG6$F`uFG-Fhgl6$F`u9&F%F%F%6#F`q6&7'FRFS"#<"#')FV7'FRFS"#H"#NF^r7'FR
FSFj\mFj^lFVF\]mF%
