M7R0
I+F_3pra_st07),bo%"vG#"8BrY$RC-0D/sS"9+++++++++++S%"uG#"8**p%[4l53WlKU"9+++++++
++++]%"wG#"9TgdL%H))>rD;C#":++++++++++++"*&F-""$F)"""#"2B0u.3vH;#"2++++++++&*&F
%F2F-F3#"2tSr"yQ4yN"2++++++]7$*&F%""#F-F<#!3"Q=uK&[&z?""3+++++++]7*&F-F2F%F3#!2
(zf:<CW2F"2+++++++]##!;,(y@"*yZ%*zn*zXQ"<+++++++++++++#F3*$F)""%#!2f]#Q.GG&G&"2
+++++++D'*$F)F2#!3B:U>*\qjE#"5+++++++++D*$F-F2#!3$Gn:IEx`-""4+++++++]7$*$F%F2#!
4$f(3vEI<zj)FO*$F%FH#"/B/?I5qB"0+++++Dc"*$F-FH#"2LWd"y%z=4(F?*(F)F3F%F<F-F3#"3$
>/zFg_nE#"3++++++++D*(F)F3F%F3F-F<#"2jCx^WXM%))F[o*(F)F<F%F3F-F3#!34-zWn9MO]F[o
*(F-F3F%F3F)F3#"42y!*4EFz)Gc"5++++++++]7*&F)F2F%F3#"3x2docu$)*3#F?*&F)F<F-F3#!4
p(*RO_7YWY$"5+++++++++]*&F)F2F-F3#"3`JE(f6&p;FF?*&F)F<F%F3#"5,6)yrRL4GS#F\p*&F)
F<F%F<#"3xY^`]o+w<F?*&F)F<F-F<#!3T[wMj,%e#GF?*&F%F<F)F3#"4JP'oX#H)\5kF\p*&F)F3F
%F2#"2,3liL3@A&FK*&F)F3F-F<#!3ZcXHRyJ`b"5+++++++++5*&F-F3F%F<#!3")\^ft'\>:$"4++
+++++++#*&F%F3F-F<#"3n>Fc5qEzbFeo*&F)F3F%F3#!7(p)*o5&o`whL')"8+++++++++++"*&F)F
3F-F3#!6nPm&=Va'4Z3""6++++++++++"*&F%F3F-F3#"7TL/LR"*\ZA!H$F]r*$F)F<#"7zDZs5%G$
G<[P"7++++++++++]*$F%F<#!7h'y\C)[7Wj*="Fhr*$F-F<#"6>,]nvGkBXe$"7++++++++++5,boF
%F&F)F*F-F.F1#!2*H1E>y_M="1++++++]iF7#"1hD5'\6GV"FCF;#!3xJ=THD1W6FKF@#!24y,8tZ;
R$"2++++++Dc"FDF3FG#"0r&fu*GFi%FCFLFMFPFQFTFUFW#"2">Tb\o))QGF:Fen#!1(**\BO-a6%"
1+++++D1RFhn#!3">DDs5Bk2$F?F\o#!3*4a#4#z$37[F?F_o#!3$=xu.UNbv(F[oFboFcoFfo#!32"
RJ`@P)GjF[oFioFjoF]p#!3p#G%G&e3i)HF[oF`pFapFcp#"32X9:x<1,>FKFfp#!2T#=8BLdVvFCFi
pFjpF\q#!3dun>%zo'>%)F[oF_qF`qFcqFdqFgqFhqFjq#"8(>eEN``x24)f"FhrF^r#"6"[Mr;s^CH
M<"5+++++++++!)Fbr#"7(=2Z9$*=e[*eF"7++++++++++?Fer#!4Ra8[$Q9se;"5++++++]7`>Fir#
!6p#\Q/^f1%yo*F_sF\s#"7@mX.:))Hmn4["7++++++++++D,boF%F&F)F*F-F.F1#!3>x()*Q)*ei-
"F?F7#"1P"f=;[wh&"1++++]7`>F;#!1>G5#>#y`x"1++++++DJF@#"2"\HVP1O.")F?FDF3FG#"2hU
/*GY,l$)F?FLFMFPFQFTFUFW#!/()4@hf;r"/++Dc^.hFen#"1$)>`90<FY"2+++++++D"Fhn#!1$pF
g_kiL%FdwF\o#!2,$)\(fh(38&F[oF_o#!2dK`!G#pA3(F[oFboFcoFfo#"2zqyGvUAy#FCFioFjoF]
p#"3`#ogRs%Q*H#F[oF`pFapFcp#"0Hb!fHC?j"0++++]i!RFfp#!28]'Gsg]dBFCFipFjpF\q#"16L
.Nz_G<FcsF_qF`qFcqFdqFgqFhqFjq#!78Y,Gd[uu>NKF]rF^r#"7V(ommwN8!))f7F]rFbr#!8r$ps
x%\ZXrHM"F]rFer#!6d#3)Q+!o6$oc$"6++++++++++&Fir#"7*f,G,BPdXY."F_sF\s#"54%e'\<m5
Ew&)"6++++++++Dc",HF%#"1J26lHqyF"1+++++++]F)#!1jZU$Q&Ha5"2++++++++"F-#!0zIf^e[l
#FgyFL#!,()f?xB%"-++++]7FP#","pL=ZK",+++]7$FT#",dxn'QqF_zFbo#"+Zo#*e#*"-+++++DF
io#!-2')[CU^"-+++++]F`p#!-fhtzVsFgzFip#",4]=$pSFgzF_q#",rcp#))R",++++D'Fcq#!-,O
e-?**FjzFgq#!,Z/2e8*F_zFjq#!.^bV")HZ$"/++++++DF^r#!.L>K"eQH"/++++++]Fbr#!-h*=!H
,:Fh[lFer#!.\d%z]gMFh[lFir#!-R_*z*HK"/+++++]7F\s#".Fi$R]1TFh[l,HF%#"/\96fcl5"/+
+++]7yF)#!0r&)QRNCE""0++++++D'F-#"1(yn51I(o7FjyFL#!,R,%HMQF_zFP#!,Z(H!y"HFbzFT#
!,PZtfY#Fa[lFbo#!,^o(>Y')FgzFio#","oKFb7",+++++"F`p#"-ncQ"*pEFgzFip#",tqaH'oFa[
lF_q#",`Lc$p"*FjzFcq#"-L85*p]"FgzFgq#!+p*=ej"",++++D"Fjq#".T6)G1&R""/++++++5F^r
#".JW'GMueF[\lFbr#!.p;9,NN""0+++++++"Fer#!-\VtsZDFh[lFir#".^o;N:A$Fh[lF\s#!.^i@
"Q$["Fb\l,HF%#"1Z&3wO?m'\"2++++++++#F)#"1Pc@Mbn?:FjyF-#"1p5P#pIfB#FjyFL#!,FU0cU
(FgzFP#!,`(He%)QFgzFT#!,t_g@D$",+++++&Fbo#",x?S(z5",++++]#Fio#!+TAJd9F``lF`p#",
$H9/c6FjzFip#!+81$*f&)"-+++++5F_q#",.m!)f-#Fa[lFcq#!,R\O;A&FjzFgq#"-@`lcZ8FjzFj
q#!/zQmRUg?F[_lF^r#!-,fZ4LJ".++++++%Fbr#!.fd<F(p;F[_lFer#",(3;;p\Ff^lFir#".pV?u
(*Q$F[\lF\s#!-,72e&4*Fb\l,*FerF3FirF3F\sF3#!&J'Q"&++%F36",
I+C_3pra_st0w,6#>%)symbolicGF36:%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G%
#_VG%"iG%#x1G%#x2G%"SG%"RG%#jjG%#kkG%"jG%"kG%#P1G%#P2G%#Q1G%#Q2G%#eqG%$eq1G%$eq
sG6"FbblC0>6$8$8%6$7%%#X1G%#X2G%"sG7%7$F2F2F]el7$F3F3@%/9$F3>8&7#-%$seqG6$-I'Ma
trixG6$%*protectedG%(_syslibG6$-%#opG6#&Ffdl6#8,w,6$%"xG%"yGFbbl6$%)operatorG%&
arrowGFbbl-&T'6#T%6#,&FaelF3*&,&9%F3!""F3F3&&T#F^gl6#F3F3F3FbblFbbl6(FjblFfdlFa
clFcflFiblFedl6#F<6$7'Q!FbblFegl"#R"#u"#O7'F^hlFeglF_hl"#XFahl/Fcfl;F3-%%nopsG6
#Fedl>Fcel7#-Ffel6$-%'rndMatG6#F^flFdhl>6%8-8.8/6%&FcelFigl&Fcel6#F<&&Fcel6#F26
$F3F3>80,(*&,&*$FdilF<F<FeglF3F3-_I.LinearAlgebraG6$F[flF\fl%/IdentityMatrixGF[
jlF3F3-I".G6$F[flF\fl6$-I$<,>GF\fl6%F)F%F-)F\[m%#%TGF<*&FdilF3-F][m6%-I$<|gr>GF
\fl6%""!,$&F\[mF[jlFegl&F\[mFhil-Fe[m6%Fi[mFg[m,$&F\[mFiglFegl-Fe[m6%,$Fj[mFegl
F^\mFg[mF3!"#>817%F<F2F3>827%F2F3F<?(FcflF3F3F2%%trueGC)>6$83846$&Fd\mFbfl&Fg\m
Fbfl>85-Fijl6$-F][m6%-Fe[m6%Fg[m,$&&Fbil6$;FbblFbblFcflF[jlFegl&F]^mFhil-Fe[m6%
F\^mFg[m,$&F]^mFiglFegl-Fe[m6%,$F`^mFeglFd^mFg[m&Fbil6$F_^mF^]m>86-Fijl6$-F][m6
%-Fe[m6%Fg[m,$&&FcilF^^mF[jlFegl&Fd_mFhil-Fe[m6%Fc_mFg[m,$&Fd_mFiglFegl-Fe[m6%,
$Fe_mFeglFi_mFg[m&FcilFi^m>87-Fijl6$Fg]m&Fbil6$F_^mF_]m>88-Fijl6$F^_m&FcilFc`m>
&89Fbfl-&Fejl6#_Fejl%,DeterminantG6#-F][m6$-Fe[m6$-Fijl6%)F[_mF`[mF^jlFh^m-Fijl
6%)F]`mF`[mF^jlFd]m-Fe[m6$-Fijl6%)Fe`mF`[mF^jlFb`m-Fijl6%)Fh`mF`[mF^jlF_`m>&8:F
bfl-F]am6#-F][m6$-Fe[m6$FiamFfam-Fe[m6$-Fijl6$F_[mF]^m,$-Fijl6$F_[mFd_mFegl>8;7
%-Ffel6$Fj`m/Fcfl;F3F2-Ffel6$FebmFicm,,FerF3FirF3F\sF3FbjlF3FeglF3>8'-%$mapG6$%
'expandGFecm@$0FaelF3OF_dm>8(-%&minusG6$-%'indetsG6#F_dm-F]em6#Fcel>6$8)8*-%,po
ly2matrixG6$F_dmFhdm>8+-%$srtG6$Fdem-%%tdegG6#-F_fl6#Fhdm6%7$%#cfG-%/permuteCol
umnsG6%FcemFdemFiemFedlFfdlFbblFbblFbbl6#Fg[m6;7'F^hlFegl"#;""'Fahl7'F^hlFeglF2
"#e"#V7'F^hlFeglF2""*Fchl7'F^hlFegl""("#&*F_gm7'F^hlFeglFcgm"#dF_gm7'F^hlFeglF2
F_hlF_gm7'F^hlFeglF2"#!)F_gm7'F^hlFeglF2"#<F_gmFjgm7'F^hlFeglF2"")F]hm7'F^hlFeg
lFcgm"#EF_gm7'F^hlFeglFcgmFahlF_gmF`hmF`hmF`hm7'F^hlFeglFcgm"$<"F_gm7'F^hlFeglF
cgm"$H"F_gm7'F^hlFeglF2"#pF_gm7'F^hlFeglF2"#CF_gm7'F^hlFeglF2"#SFchl7'F^hlFegl"
#B"#K"#_7'F^hlFeglF2"#QF_gm7'F^hlFeglF2FahlF_gm7'F^hlFeglF2"#LF_gm7'F^hlFeglF2"
#`"#JFbbl
