M7R0
I+F_3pra_st07),bo%"vG#"8BrY$RC-0D/sS"9+++++++++++S%"uG#"8**p%[4l53WlKU"9+++++++
++++]%"wG#"9TgdL%H))>rD;C#":++++++++++++"*&F)"""F%F2#!7(p)*o5&o`whL')"8++++++++
+++"*&F)F2F-F2#!6nPm&=Va'4Z3""6++++++++++"*&F%F2F-F2#"7TL/LR"*\ZA!H$F5*$F)""##"
7zDZs5%G$G<[P"7++++++++++]*$F%F>#!7h'y\C)[7Wj*="FA*$F-F>#"6>,]nvGkBXe$"7+++++++
+++5*(F)F>F%F2F-F2#!34-zWn9MO]"3++++++++D*(F-F2F%F2F)F2#"42y!*4EFz)Gc"5++++++++
]7*(F)F2F%F>F-F2#"3$>/zFg_nE#FL*(F)F2F%F2F-F>#"2jCx^WXM%))FL*$F)""%#!2f]#Q.GG&G
&"2+++++++D'*$F)""$#!3B:U>*\qjE#"5+++++++++D*$F-Fgn#!3$Gn:IEx`-""4+++++++]7$*$F
%Fgn#!4$f(3vEI<zj)Fjn*$F%FX#"/B/?I5qB"0+++++Dc"*$F-FX#"2LWd"y%z=4("3+++++++]7#!
;,(y@"*yZ%*zn*zXQ"<+++++++++++++#F2*&F)FgnF%F2#"3x2docu$)*3#Fio*&F)F>F-F2#!4p(*
RO_7YWY$"5+++++++++]*&F)FgnF-F2#"3`JE(f6&p;FFio*&F)F>F%F2#"5,6)yrRL4GS#Fcp*&F)F
>F%F>#"3xY^`]o+w<Fio*&F)F>F-F>#!3T[wMj,%e#GFio*&F%F>F)F2#"4JP'oX#H)\5kFcp*&F)F2
F%Fgn#"2,3liL3@A&Fen*&F)F2F-F>#!3ZcXHRyJ`b"5+++++++++5*&F-F2F%F>#!3")\^ft'\>:$"
4+++++++++#*&F%F2F-F>#"3n>Fc5qEzbFP*&F-FgnF)F2#"2B0u.3vH;#"2++++++++&*&F%FgnF-F
2#"2tSr"yQ4yN"2++++++]7$*&F%F>F-F>#!3"Q=uK&[&z?"Fio*&F-FgnF%F2#!2(zf:<CW2F"2+++
++++]#,HF%#"1J26lHqyF"1+++++++]F)#!1jZU$Q&Ha5"2++++++++"F-#!0zIf^e[l#FcsF1#!.^b
V")HZ$"/++++++DF6#!.L>K"eQH"/++++++]F:#!-h*=!H,:F[tF=#!.\d%z]gMF[tFB#!-R_*z*HK"
/+++++]7FE#".Fi$R]1TF[tFM#"+Zo#*e#*"-+++++DFfn#!,()f?xB%"-++++]7F[o#","pL=ZK",+
++]7$F_o#",dxn'QqF]uF`p#!-2')[CU^"-+++++]Fgp#!-fhtzVsFjtF`q#",4]=$pSFjtFfq#",rc
p#))R",++++D'Fjq#!-,Oe-?**FeuF^r#!,Z/2e8*F]u,boF%F&F)F*F-F.F1#"8(>eEN``x24)f"FA
F6#"6"[Mr;s^CHM<"5+++++++++!)F:#"7(=2Z9$*=e[*eF"7++++++++++?F=#!4Ra8[$Q9se;"5++
++++]7`>FB#!6p#\Q/^f1%yo*FHFE#"7@mX.:))Hmn4["7++++++++++DFI#!3$=xu.UNbv(FLFMFNF
Q#!3">DDs5Bk2$FioFT#!3*4a#4#z$37[FioFW#"0r&fu*GFi%F_sFfnFhnF[oF\oF_oF`oFbo#"2">
Tb\o))QGFhrFfo#!1(**\BO-a6%"1+++++D1RFjoF2F]p#!32"RJ`@P)GjFLF`pFapFdp#!3p#G%G&e
3i)HFLFgpFhpFjp#"32X9:x<1,>FenF]q#!2T#=8BLdVvF_sF`qFaqFcq#!3dun>%zo'>%)FLFfqFgq
FjqF[rF^rF_rFar#!2*H1E>y_M="1++++++]iFer#"1hD5'\6GV"F_sFir#!3xJ=THD1W6FenF\s#!2
4y,8tZ;R$"2++++++Dc",HF%#"/\96fcl5"/++++]7yF)#!0r&)QRNCE""0++++++D'F-#"1(yn51I(
o7FfsF1#".T6)G1&R""/++++++5F6#".JW'GMueF^tF:#!.p;9,NN""0+++++++"F=#!-\VtsZDF[tF
B#".^o;N:A$F[tFE#!.^i@"Q$["FetFM#!,^o(>Y')FjtFfn#!,R,%HMQF]uF[o#!,Z(H!y"HF`uF_o
#!,PZtfY#F\vF`p#","oKFb7",+++++"Fgp#"-ncQ"*pEFjtF`q#",tqaH'oF\vFfq#",`Lc$p"*Feu
Fjq#"-L85*p]"FjtF^r#!+p*=ej"",++++D",boF%F&F)F*F-F.F1#!78Y,Gd[uu>NKF5F6#"7V(omm
wN8!))f7F5F:#!8r$psx%\ZXrHM"F5F=#!6d#3)Q+!o6$oc$"6++++++++++&FB#"7*f,G,BPdXY."F
HFE#"54%e'\<m5Ew&)"6++++++++Dc"FI#!2dK`!G#pA3(FLFMFNFQ#!1$pFg_kiL%"2+++++++D"FT
#!2,$)\(fh(38&FLFW#"2hU/*GY,l$)FioFfnFhnF[oF\oF_oF`oFbo#!/()4@hf;r"/++Dc^.hFfo#
"1$)>`90<FYFc]lFjoF2F]p#"2zqyGvUAy#F_sF`pFapFdp#"3`#ogRs%Q*H#FLFgpFhpFjp#"0Hb!f
HC?j"0++++]i!RF]q#!28]'Gsg]dBF_sF`qFaqFcq#"16L.Nz_G<F[yFfqFgqFjqF[rF^rF_rFar#!3
>x()*Q)*ei-"FioFer#"1P"f=;[wh&"1++++]7`>Fir#!1>G5#>#y`x"1++++++DJF\s#"2"\HVP1O.
")Fio,HF%#"1Z&3wO?m'\"2++++++++#F)#"1Pc@Mbn?:FfsF-#"1p5P#pIfB#FfsF1#!/zQmRUg?Fc
zF6#!-,fZ4LJ".++++++%F:#!.fd<F(p;FczF=#",(3;;p\F^zFB#".pV?u(*Q$F^tFE#!-,72e&4*F
etFM#",x?S(z5",++++]#Ffn#!,FU0cU(FjtF[o#!,`(He%)QFjtF_o#!,t_g@D$",+++++&F`p#!+T
AJd9F`alFgp#",$H9/c6FeuF`q#!+81$*f&)"-+++++5Ffq#",.m!)f-#F\vFjq#!,R\O;A&FeuF^r#
"-@`lcZ8Feu,*F=F2FBF2FEF2#!&J'Q"&++%F26",
I+C_3pra_st0w,6#>%)symbolicGF268%&_nameG%&_sizeG%#_AG%"iG%$xx1G%$xx2G%#ssG%"RG%
#jjG%#kkG%$eqsG%"jG%"kG%#P1G%#P2G%#Q1G%#Q2G%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"Fbbl
C0>6$8$8%6$7%%#X1G%#X2G%"sG7$-%"$G6$7$FgnFgnF>7$F2F2@%/9$""!>8&7#-%$seqG6$-%'rn
dMatG6#&&Fddl6#8'Fbbl/F`fl;F2-%%nopsG6#Fcdl>Feel7#-Fhel6$-I'MatrixG6$%*protecte
dG%(_syslibG6$F]flw,6$%"xG%"yGFbbl6$%)operatorG%&arrowGFbbl-&T'6#T%6#,&FbelF2*&
,&9%F2!""F2F2&&T#Fjgl6#F2F2F2FbblFbbl6(FjblFddlF\clF`flFiblFcdl6#F>6$7'Q!FbblFa
hl"#P"#s"#O7'FjhlFahlF[il"#VF]ilFafl>6%8(8)8*6%&FeelFehl&Feel6#F>&&Feel6#Fgn6$F
2F2>8+,(*&,&*$FdilF>F>FahlF2F2-&I.LinearAlgebraG6$F]glF^gl6#%/IdentityMatrixGF[
jlF2F2-I".G6$F]glF^gl6$-I$<,>GF^gl6%F)F%F-)F][m%#%TGF>*&FdilF2-%&crossG6#F][mF2
!"#>6$8,8-6$7%F>FgnF27%FgnF2F>>8.7"?(F`flF2F2Fgn%%trueGC)>6$8/806$&Fi[mF_fl&Fj[
mF_fl>81-Fjjl6$-Fd[m6#&Fbil6$;FbblFbblF`fl&Fbil6$Fc]mFf\m>82-Fjjl6$-Fd[m6#&Fcil
Fb]m&FcilFe]m>83-Fjjl6$F_]m&Fbil6$Fc]mFg\m>84-Fjjl6$Fj]m&FcilFc^m>F_\m7$&F_\mFb
bl-&Fejl6#%,DeterminantG6#-F^[m6$-I$<|gr>GF^gl6$-Fjjl6%)Fg]mFa[mF^jlFd]m-Fjjl6%
)F]^mFa[mF^jlF\]m-Fd_m6$-Fjjl6%)Fe^mFa[mF^jlFb^m-Fjjl6%)Fh^mFa[mF^jlF_^m>F_\m7$
F[_m-F]_m6#-F^[m6$-Fd_m6$Fi_mFf_m-Fd_m6$-Fjjl6$F`[mFa]m,$-Fjjl6$F`[mF\^mFahl>F_
\m7$F[_m,,F=F2FBF2FEF2FbjlF2FahlF2>85-%$mapG6$%'expandGF_\m@$FaelOFgam>86-%&min
usG6$-%'indetsG6#Fgam-Fdbm6#Feel>6$8788-%,poly2matrixG6$FgamF_bm>89-%$srtG6$F[c
m-%%tdegG6#&F_bmFbbl6%7#-%/permuteColumnsG6%FjbmF[cmF`cmFcdlFddlFbblFbblFbbl6#F
cel6;7'FjhlFahl"#;""'F]il7'FjhlFahlFgn"#bF_il7'FjhlFahlFgn""*"#X7'FjhlFahl""(Fc
dmF_il7'FjhlFahlFhdm"#$*F_il7'FjhlFahlFgn"#UF_il7'FjhlFahlFgn"#!*F_il7'FjhlFahl
Fgn"#GF_il7'FjhlFahlFgn"#6F_il7'FjhlFahlFgn"")Fdem7'FjhlFahlFhdm"#EF_il7'FjhlFa
hlFhdm"#QF_ilFgemFgemFgem7'FjhlFahlFhdm"$C"F_il7'FjhlFahlFhdm"$N"F_il7'FjhlFahl
FgnF]ilF_il7'FjhlFahlFgn"#CF_il7'FjhlFahlFgn"#RFfdm7'FjhlFahl"#A"#J"#_7'FjhlFah
lFgnFhemF_ilF]fm7'FjhlFahlFgnFdfmF_il7'FjhlFahlFgn"#ZFdfmFbbl
