M7R0
I7F_3v_triang_laurent_v27%,D*$%"xG!"##"'n%y'"(+++"*&F&F'%"yG"""#"',k')F**&F&F'%
"zGF-#!%ro"'++]*&F&!"$F,F-#!(h9T"F4*&F&F6F1F-#"&,!\"'+]7*&F&F6F,""##!(\:g"F**&F
&F6F1F>#!%x!)F<*&F,F'F&F-#"'8iZF4*&F,F'F1F-#"'H!G'F**&F1F'F&F-#"&P<)"'++5*&F1F'
F,F-#!&4*p"'++?*(F&F6F,F-F1F-#"&t\""&++&*$F,!""#!&dQ'FM*$F1FW#"'PY9"'++D*$F&F6#
!'(\K"FM*$F,F'#"%(R&F4*$F1F'#"'6rQF*,DF%#"(h9T"F*F+#"(\:g"F*F0#!&t\"FMFD#"&dQ'F
MFG#!'jJ5FQFJFOFN#"'ti5FQ*&F,F6F&F-#!%(R&Fgn*&F,F6F1F-#"'$f5"F<*&F,F6F&F>#!'8iZ
F4*&F,F6F1F>#!'$\U"FQ*(F,F6F&F-F1F-#!'H!G'F4*$F&FW#!',k')F*FZ#!&RB"F*F[o#"'x=9F
MF^o#!&h?'F<*$F,F6#!'L$p"Fgn,DF%#!&,!\FgnF+FfoF0#"%x!)F<FDFHFG#"'$\U"FQFJ#!'PY9
FgnFN#"&RB"F**&F1F6F&F-#!'6rQF4*&F1F6F,F-#"&h?'"&+D'*&F1F6F&F>#!&P<)FM*&F1F6F,F
>#!'ti5FQ*(F1F6F&F-F,F-#"&4*pFMF]q#"%roF4FV#"'jJ5FQF[o#!'$f5"FgnF^o#!&(GqF**$F1
F6#!'L,ZF*6",
I7C_3v_triang_laurent_v2w,6#>%)symbolicGF-60%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%
$_C0G%$_V0G%#_VG%"iG%"PG%"vG%"XG%*cost_funcG%$eqsG6"F_tC/>6$8$8%6$7(%#P1G%#P2G%
#P3G%#x1G%#x2G%#x3G7(7$F>""%FcvFcv7$F>F-FevFev@%/9$F->8&7#-%$seqG6$-I'MatrixG6$
%*protectedG%(_syslibG6$-%#opG6#&Fiu6#8,w,6$F&F,F_t6$%)operatorG%&arrowGF_t-&T'
6#T%6#,&FhvF-*&,&9%F-FWF-F-&&T#Fcx6#F-F-F-F_tF_t6(FgtFiuF^uFjwFftFhu6#F>6$7'Q!F
_tFW"#R"#u"#O7'FbyFWFcy"#XFey/Fjw;F--%%nopsG6#Fhu>Fjv7#-F]w6$-%'rndMatG6#FewFhy
>6%&8-F]y&Fgz6#F>&Fgz6#""$6%-I$<,>GFcw6$&FjvF]y-I$<|gr>GFcw6&F-""!Fe[lFe[l-F_[l
6$&FjvFiz-Fc[l6&Fe[lF-Fe[lFe[l-F_[l6$&FjvF[[l-Fc[l6&Fe[lFe[lF-Fe[l>6%&8.F]y&Fc
\lFiz&Fc\lF[[l6%&Fjv6#Fdv&Fjv6#""&&Fjv6#""'>8/-F_[l6&F&F,F1F->80-%$addG6$,&*$,&
*&-I".G6$FbwFcw6$&&FgzFiw6$F-;F_tF_tF`]lF--F]^l6$&Fa^l6$F\[lFc^lF`]lFWF-&&Fc\lF
iw6$F-F-FWF>F-*$,&*&-F]^l6$&Fa^l6$F>Fc^lF`]lF-Fd^lFWF-&Fi^l6$F>F-FWF>F-/Fjw;F-F
\[l>81-&%"|irG6#%"*G6%#F-F>%#~$G7%-%%diffG6$Fd]lF&-Fb`l6$Fd]lF,-Fb`l6$Fd]lF1>8'
-%$mapG6$%'expandGFg_l@$0FhvF-OFi`l>8(-%&minusG6$-%'indetsG6#Fi`l-Fgal6#Fjv>6$8
)8*-%,poly2matrixG6$Fi`lFbal>8+-%$srtG6$F^bl-%%tdegG6#-Ffw6#Fbal6%7$%#cfG-%/per
muteColumnsG6%F]blF^blFcblFhuFiuF_tF_tF_t6#Fe[l637'FbyFW"#;F^]lFey7'FbyFWF\[l"#
'*"#V7'FbyFWF\[l""*Fgy7'FbyFW""("#&*Fhcl7'FbyFWF\dl"#dFhcl7'FbyFWF\[l"#!)Fhcl7'
FbyFWF\[l"#TFhcl7'FbyFWF\[l"#>Fhcl7'FbyFWF\[l"$:"Fhcl7'FbyFWF\[lFdyFhcl7'FbyFWF
\[l"#CFhcl7'FbyFWF\[l"#SFgy7'FbyFW"#B"#K"#_7'FbyFWF\[l"#QFhcl7'FbyFWF\[lFeyFhcl
7'FbyFWF\[l"#LFhcl7'FbyFWF\[l"#`"#JF_t
