M7R0
I7F_3v_triang_laurent_v27%,D%"xG#"&P<)"&++&%"yG#!&4*p"'++5%"zG#"'nB?"'++]*$F%!"
##"'n%y'F0*&F%F2F)"""#"',k')F0*&F%F2F-F6#!%ro"'++D*&F%!"$F)F6#!(h9T"F<*&F%F>F-F
6#"&,!\"&+D'*&F%F>F)""##!(\:g"F0*&F%F>F-FF#!%x!)FD*&F)F2F%F6#"'8iZF<*&F)F2F-F6#
"'H!G'F0*(F%F>F)F6F-F6#"&t\""&+]#*$F)!""#!&dQ'F(#"'B3>"'+]7F6*$F%F>#!'(\K"F(*$F
)F2#"%(R&F<,DF%F*F)#"'ti5F,F-#!%`b"&Dc"F1#"(h9T"F0F5#"(\:g"F0F9#!&t\"F(FL#"&dQ'
F(FO#!'jJ5F,*&F)F>F%F6#!%(R&Ffn*&F)F>F-F6#"'$f5"FD*&F)F>F%FF#!'8iZF<*&F)F>F-FF#
!'$\U"F,*(F)F>F%F6F-F6#!'H!G'F<*$F%FW#!',k')F0#!'J6LF0F6Fjn#"'x=9F(*$F)F>#!'L$p
"Ffn,:F1#!&,!\FfnF\q#"%roF<F5FgoF9#"%x!)FDFjn#!'$f5"FfnFLFPFV#"'jJ5F,FO#"'$\U"F
,#"'.,>F0F6F%F.F)F`oF-#"&h=(F06",
I7C_3v_triang_laurent_v2w,6#>%)symbolicGF66/%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%
#C0G%#V0G%"VG%"PG%"vG%"XG%*cost_funcG%"iG6"FgrC/>6$8$8%6$7(%#P1G%#P2G%#P3G%#x1G
%#x2G%#x3G7(7$FF""%FjtFjt7$FFF6F\uF\u@%/9$F6>8&-%$seqG6$-I'MatrixG6$%*protected
G%(_syslibG6$-%#opG6#&F`t6#80w,6$F%F)Fgr6$%)operatorG%&arrowGFgr-&T'6#T%6#,&F_u
F6*&,&9%F6FWF6F6&&T#Fiv6#F6F6F6FgrFgr6(F_sF`tFjsF`vF^sF_t6#FF6$7'Q!FgrFW"#Q"#t"
#O7'FhwFWFiw"#WF[x/F`v;F6-%%nopsG6#F_t>Fau-Fcu6$-%'rndMatG6#F[vF^x>6%&8,Fcw&F\y
6#FF&F\y6#""$6%-I$<,>GFiu6$&FauFcw-I$<|gr>GFiu6&F6""!FjyFjy-Fdy6$&FauF^y-Fhy6&F
jyF6FjyFjy-Fdy6$&FauF`y-Fhy6&FjyFjyFjyF6>6%&8-Fcw&FhzF^y&FhzF`y6%&Fau6#F[u&Fau6
#""&&Fau6#""'>8.-Fdy6&F%F)F-F6>8/-%$addG6$,&*$,&*&-I".G6$FhuFiu6$&&F\yF_v6$F6;F
grFgrFe[lF6-Fb\l6$&Ff\l6$FayFh\lFe[lFWF6&&FhzF_v6$F6F6FWFFF6*$,&*&-Fb\l6$&Ff\l6
$FFFh\lFe[lF6Fi\lFWF6&F^]l6$FFF6FWFFF6/F`v;F6Fay>8'7%-%%diffG6$Fi[lF%-F_^l6$Fi[
lF)-F_^l6$Fi[lF->F\^l-%$mapG6$%'expandGF\^l@$0F_uF6OF\^l>8(-%&minusG6$-%'indets
G6#F\^l-Fc_l6#7#Fau>6$8)8*-%,poly2matrixG6%F\^l-FaxFd_lF^_l>8+-%$srtG6$F[`l-%%t
degG6#-F\v6#F^_l6%7$%#cfG-%/permuteColumnsG6%Fj_lF[`lFa`lF_tF`tFgrFgrFgr6#Fjy63
7'FhwFW"#;Fc[lF[x7'FhwFWFay"#'*"#V7'FhwFWFay""*"#X7'FhwFW""("#$*Ffal7'FhwFWF[bl
"#bFfal7'FhwFWFay"#!)Ffal7'FhwFWFay"#TFfal7'FhwFWFay"#>Ffal7'FhwFWFay"$:"Ffal7'
FhwFWFay"#pFfal7'FhwFWFay"#DFfal7'FhwFWFayFbblFial7'FhwFW"#B"#L"#_7'FhwFWFay"#S
Ffal7'FhwFWFayFialFfal7'FhwFWFay"#IFfal7'FhwFWFay"#]"#JFgr
