M7R0
I:F_3v_triang_laurent_w_sat7&zE6%%"xG%"yG%"zG[[[[][[[_[[[q"&t/&[[[[^[[[^[[[q!']
8E\[[[][[[^[[[q"'9l<[[[[][[[^[[[p"'mRQ[[[[[[[[_[[[o"'Lz^[[[[\[[[^[[[o!&6a#\[[[[
[[[^[[[o"'5:J[[[[^[[[\[[[o!'bT[\[[[][[[\[[[o"'ZdJ[[[[_[[[[[[[o!',2]\[[[^[[[[[[[
o"'!z!**][[[][[[[[[[o!'9"o&[[[[[[[[^[[[n!'[om[[[[][[[\[[[n!'^c>[[[[^[[[[[[[n"'5
+z\[[[][[[[[[[n!(wKL"[[[[][[[[[[[m!(YtG"zEF%[[[[^[[[^[[[qF*[[[[_[[[][[[q"(xqP"
\[[[^[[[][[[q!'5&***[[[[^[[[][[[p!(#y[>[[[[[[[[_[[[o!'Lz^[[[[\[[[^[[[o"&6a#\[[[
[[[[^[[[o!'?Ii\[[[\[[[][[[o"'-c#)][[[[[[[][[[o!'79f[[[[^[[[\[[[o"'bT[[[[[_[[[[[
[[o"',2]\[[[^[[[[[[[o!'&R&\[[[[[[[[^[[[n"('pL8[[[[\[[[][[[n!&!HX\[[[[[[[][[[n"'
)o9)[[[[^[[[[[[[n!'0]R[[[[[[[[][[[m!'w'e)z;F%[[[[][[[^[[[pF+[[[[^[[[][[[pF<\[[[
][[[][[[p"'_X#*[[[[][[[][[[o"([7?"[[[[[[[[^[[[nF/[[[[\[[[][[[n!'-c#)\[[[[[[[][[
[n"'79f[[[[][[[\[[[n!'ZdJ[[[[^[[[[[[[nFE\[[[][[[[[[[n"'9"o&[[[[[[[[][[[m!'WtS[[
[[][[[[[[[m"'Qmmz'6%%"wGF&F'\[[[\[[[\[[[n"""!!""6",
I:C_3v_triang_laurent_w_satw,6#>%)symbolicGFW60%&_nameG%&_sizeG%#_AG%#_FG%&_var
sG%$_C0G%$_V0G%#_VG%"iG%"PG%"vG%"XG%*cost_funcG%$eqsG6"FYC0>6$8$8%6$7(%#P1G%#P2
G%#P3G%#x1G%#x2G%#x3G7(7$""#""%FgpFgp7$FhpFWFjpFjp@%/9$FW>8&7#-%$seqG6$-I'Matri
xG6$%*protectedG%(_syslibG6$-%#opG6#&F]p6#8,w,6$F&F'FY6$%)operatorG%&arrowGFY-&
T'6#T%6#,&F]qFW*&,&9%FWFXFWFW&&T#Fhr6#FWFWFWFYFY6(F[oF]pFboF_rFjnF\p6#Fhp6$7'Q!
FYFX"#R"#u"#O7'FgsFXFhs"#XFjs/F_r;FW-%%nopsG6#F\p>F_q7#-Fbq6$-%'rndMatG6#FjqF]t
>6%&8-Fbs&F\u6#Fhp&F\u6#""$6%-I$<,>GFhq6$&F_qFbs-I$<|gr>GFhq6&FW""!FjuFju-Fdu6$
&F_qF^u-Fhu6&FjuFWFjuFju-Fdu6$&F_qF`u-Fhu6&FjuFjuFjuFW>6%&8.Fbs&FhvF^u&FhvF`u6%
&F_q6#Fip&F_q6#""&&F_q6#""'>8/-Fdu6&F&F'F(FW>80-%$addG6$,&*$,&*&-I".G6$FgqFhq6$
&&F\uF^r6$FW;FYFYFewFW-Fbx6$&Ffx6$FauFhxFewFXFW&&FhvF^r6$FWFWFXFhpFW*$,&*&-Fbx6
$&Ffx6$FhpFhxFewFWFixFXFW&F^y6$FhpFWFXFhpFW/F_r;FWFau>81-&%"|irG6#%"*G6%#FWFhp%
#~$G7%-%%diffG6$FiwF&-Fgz6$FiwF'-Fgz6$FiwF(>F\z-%$mapG6$%&numerG7$-F[r6#F\zFT>8
'-F_[l6$%'expandGF\z@$0F]qFWOFf[l>8(-%&minusG6$-%'indetsG6#Ff[l-Fc\l6#F_q>6$8)8
*-%,poly2matrixG6$Ff[lF^\l>8+-%$srtG6$Fj\l-%%tdegG6#-F[r6#F^\l6%7$%#cfG-%/permu
teColumnsG6%Fi\lFj\lF_]lF\pF]pFYFYFY6#Fju647'FgsFX"#;FcwFjs7'FgsFXFau"#'*"#V7'F
gsFXFau""*F\t7'FgsFX""("#&*Fd^l7'FgsFXFh^l"#dFd^l7'FgsFXFau"#!)Fd^l7'FgsFXFau"#
TFd^l7'FgsFXFau"#>Fd^l7'FgsFXFau"$:"Fd^l7'FgsFXFauFisFd^l7'FgsFXFauFhsFd^l7'Fgs
FXFau"#CFd^l7'FgsFXFau"#SF\t7'FgsFX"#B"#K"#_7'FgsFXFau"#QFd^l7'FgsFXFauFjsFd^l7
'FgsFXFau"#LFd^l7'FgsFXFau"#`"#JFY
