M7R0
I:F_3v_triang_laurent_w_sat7&zE6%%"xG%"yG%"zG[[[[][[[_[[[q"'qt")[[[[^[[[^[[[q!'
X&\$\[[[][[[^[[[q"'nB?[[[[][[[^[[[p"'#Hj([[[[[[[[_[[[o"'EC&*[[[[\[[[^[[[o!'q&Q'
\[[[[[[[^[[[o"'H!G'[[[[^[[[\[[[o"',k')\[[[][[[\[[[o!&UP"[[[[_[[[[[[[o!(\:g"\[[[
^[[[[[[[o"'g%*H][[[][[[[[[[o!&;Y'[[[[[[[[^[[[n"&%z5[[[[][[[\[[[n"'n%y'[[[[^[[[[
[[[n!(AH#G\[[[][[[[[[[n"'3?R[[[[][[[[[[[m!(q\K"zEF%[[[[^[[[^[[[qF*[[[[_[[[][[[q
"'l8`\[[[^[[[][[[q!''px"[[[[^[[[][[[p!'J6L[[[[[[[[_[[[o!'EC&*[[[[\[[[^[[[o"'q&Q
'\[[[[[[[^[[[o!(egD"\[[[\[[[][[[o!':e^][[[[[[[][[[o!'lCr[[[[^[[[\[[[o!',k')[[[[
_[[[[[[[o"(\:g"\[[[^[[[[[[[o!'I(\"[[[[[[[[^[[[n!&)e@[[[[\[[[][[[n"(q(=9\[[[[[[[
][[[n"'WZ))[[[[^[[[[[[[n"(h9T"[[[[[[[[][[[m!'Ktnz;F%[[[[][[[^[[[pF+[[[[^[[[][[[
pF<\[[[][[[][[[p"&h=([[[[][[[][[[o"'.,>[[[[[[[[^[[[nF/[[[[\[[[][[[n"':e^\[[[[[[
[][[[n"'lCr[[[[][[[\[[[n"&UP"[[[[^[[[[[[[nFE\[[[][[[[[[[n"&;Y'[[[[[[[[][[[m!'sB
W[[[[][[[[[[[m!'/g>z'6%%"wGF&F'\[[[\[[[\[[[n"""!!""6",
I:C_3v_triang_laurent_w_satw,6#>%)symbolicGFW60%&_nameG%&_sizeG%#_AG%"iG%"PG%"v
G%"XG%*cost_funcG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FYC0>6$8$8%6$7(%#P1G%#P2
G%#P3G%#x1G%#x2G%#x3G7$-%"$G6$7$""#""%""$-Fhp6$7$F[qFWF]q@%/9$""!>8&7#-%$seqG6$
-%'rndMatG6#&&F]p6#8'FY/Far;FW-%%nopsG6#F\p>Ffq7#-Fiq6$-I'MatrixG6$%*protectedG
%(_syslibG6$F^rw,6$F&F'FY6$%)operatorG%&arrowGFY-&T'6#T%6#,&FcqFW*&,&9%FWFXFWFW
&&T#Fis6#FWFWFWFYFY6(F[oF]pF]oFarFjnF\p6#F[q6$7'Q!FYFX"#P"#s"#O7'FhtFXFit"#VF[u
Fbr>6%&8(Fct&Fau6#F[q&Fau6#F]q6%-I$<,>GF_s6$&FfqFct-I$<|gr>GF_s6&FWFdqFdqFdq-Fh
u6$&FfqFcu-F\v6&FdqFWFdqFdq-Fhu6$&FfqFeu-F\v6&FdqFdqFdqFW>6%&8)Fct&F[wFcu&F[wFe
u6%&Ffq6#F\q&Ffq6#""&&Ffq6#""'>8*-Fhu6&F&F'F(FW>8+-%$addG6$,&*$,&*&-I".G6$F^sF_
s6$&&FauF`r6$FW;FYFYFhwFW-Fex6$&Fix6$F]qF[yFhwFXFW&&F[wF`r6$FWFWFXF[qFW*$,&*&-F
ex6$&Fix6$F[qF[yFhwFWF\yFXFW&Fay6$F[qFWFXF[qFW/Far;FWF]q>8,-&%"|irG6#%"*G6%#FWF
[q%#~$G7%-%%diffG6$F\xF&-Fjz6$F\xF'-Fjz6$F\xF(>F_z-%$mapG6$%&numerG7$&F_zFYFT>8
--Fb[l6$%'expandGF_z@$FbqOFh[l>8.-%&minusG6$-%'indetsG6#Fh[l-Fd\l6#Ffq>6$8/80-%
,poly2matrixG6$Fh[lF_\l>81-%$srtG6$F[]l-%%tdegG6#&F_\lFY6%7#-%/permuteColumnsG6
%Fj\lF[]lF`]lF\pF]pFYFYFY6#Fdq647'FhtFX"#;FfwF[u7'FhtFXF]q"#wF]u7'FhtFXF]q""*"#
X7'FhtFX""("#bF]u7'FhtFXFg^l"#$*F]u7'FhtFXF]q"#!)F]u7'FhtFXF]q"#TF]u7'FhtFXF]q"
#>F]u7'FhtFXF]q"$:"F]u7'FhtFXF]q"#uF]u7'FhtFXF]qFitF]u7'FhtFXF]q"#CF]u7'FhtFXF]
q"#RFe^l7'FhtFX"#A"#J"#_7'FhtFXF]q"#QF]u7'FhtFXF]qF[uF]u7'FhtFXF]qF\`lF]u7'FhtF
XF]q"#ZF\`lFY
