M7R0
I4F_3v_triang_laurent7%,D%"xG#"&P<)"'++5%"yG#!&4*p"'++?%"zG#"'nB?"(+++"*$F%!"##
"'n%y'F0*&F%F2F)"""#"',k')F0*&F%F2F-F6#!%ro"'++]*&F%!"$F)F6#!(h9T"F<*&F%F>F-F6#
"&,!\"'+]7*&F%F>F)""##!(\:g"F0*&F%F>F-FF#!%x!)FD*&F)F2F%F6#"'8iZF<*&F)F2F-F6#"'
H!G'F0*(F%F>F)F6F-F6#"&t\""&++&*$F)!""#!&dQ'F(#"'B3>"'++DF6*$F%F>#!'(\K"F(*$F)F
2#"%(R&F<,DF%F*F)#"'ti5F,F-#!%`b"&]7$F1#"(h9T"F0F5#"(\:g"F0F9#!&t\"F(FL#"&dQ'F(
FO#!'jJ5F,*&F)F>F%F6#!%(R&Ffn*&F)F>F-F6#"'$f5"FD*&F)F>F%FF#!'8iZF<*&F)F>F-FF#!'
$\U"F,*(F)F>F%F6F-F6#!'H!G'F<*$F%FW#!',k')F0#!'J6LF0F6Fjn#"'x=9F(*$F)F>#!'L$p"F
fn,:F1#!&,!\FfnF\q#"%roF<F5FgoF9#"%x!)FDFjn#!'$f5"FfnFLFPFV#"'jJ5F,FO#"'$\U"F,#
"'.,>F0F6F%F.F)F`oF-#"&h=(F06",
I4C_3v_triang_laurentw,6#>%)symbolicGF660%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C
0G%$_V0G%#_VG%"iG%"PG%"vG%"XG%*cost_funcG%$eqsG6"FgrC/>6$8$8%6$7(%#P1G%#P2G%#P3
G%#x1G%#x2G%#x3G7(7$FF""%F[uF[u7$FFF6F]uF]u@%/9$F6>8&7#-%$seqG6$-I'MatrixG6$%*p
rotectedG%(_syslibG6$-%#opG6#&Fat6#8,w,6$F%F)Fgr6$%)operatorG%&arrowGFgr-&T'6#T
%6#,&F`uF6*&,&9%F6FWF6F6&&T#F[w6#F6F6F6FgrFgr6(F_sFatFfsFbvF^sF`t6#FF6$7'Q!FgrF
W"#R"#u"#O7'FjwFWF[x"#XF]x/Fbv;F6-%%nopsG6#F`t>Fbu7#-Feu6$-%'rndMatG6#F]vF`x>6%
&8-Few&F_y6#FF&F_y6#""$6%-I$<,>GF[v6$&FbuFew-I$<|gr>GF[v6&F6""!F]zF]z-Fgy6$&Fbu
Fay-F[z6&F]zF6F]zF]z-Fgy6$&FbuFcy-F[z6&F]zF]zF]zF6>6%&8.Few&F[[lFay&F[[lFcy6%&F
bu6#F\u&Fbu6#""&&Fbu6#""'>8/-Fgy6&F%F)F-F6>80-%$addG6$,&*$,&*&-I".G6$FjuF[v6$&&
F_yFav6$F6;FgrFgrFh[lF6-Fe\l6$&Fi\l6$FdyF[]lFh[lFWF6&&F[[lFav6$F6F6FWFFF6*$,&*&
-Fe\l6$&Fi\l6$FFF[]lFh[lF6F\]lFWF6&Fa]l6$FFF6FWFFF6/Fbv;F6Fdy>81-&%"|irG6#%"*G6
%#F6FF%#~$G7%-%%diffG6$F\\lF%-Fj^l6$F\\lF)-Fj^l6$F\\lF->8'-%$mapG6$%'expandGF_^
l@$0F`uF6OFa_l>8(-%&minusG6$-%'indetsG6#Fa_l-F_`l6#Fbu>6$8)8*-%,poly2matrixG6$F
a_lFj_l>8+-%$srtG6$Ff`l-%%tdegG6#-F^v6#Fj_l6%7$%#cfG-%/permuteColumnsG6%Fe`lFf`
lF[alF`tFatFgrFgrFgr6#F]z637'FjwFW"#;Ff[lF]x7'FjwFWFdy"#'*"#V7'FjwFWFdy""*F_x7'
FjwFW""("#&*F`bl7'FjwFWFdbl"#dF`bl7'FjwFWFdy"#!)F`bl7'FjwFWFdy"#TF`bl7'FjwFWFdy
"#>F`bl7'FjwFWFdy"$:"F`bl7'FjwFWFdyF\xF`bl7'FjwFWFdy"#CF`bl7'FjwFWFdy"#SF_x7'Fj
wFW"#B"#K"#_7'FjwFWFdy"#QF`bl7'FjwFWFdyF]xF`bl7'FjwFWFdy"#LF`bl7'FjwFWFdy"#`"#J
Fgr
