M7R0
I4F_3v_triang_laurent7%,D%"xG#"&P<)"'++5%"yG#!&4*p"'++?%"zG#"'nB?"(+++"*$F%!"##
"'n%y'F0*&F%F2F)"""#"',k')F0*&F%F2F-F6#!%ro"'++]*&F%!"$F)F6#!(h9T"F<*&F%F>F-F6#
"&,!\"'+]7*&F%F>F)""##!(\:g"F0*&F%F>F-FF#!%x!)FD*&F)F2F%F6#"'8iZF<*&F)F2F-F6#"'
H!G'F0*(F%F>F)F6F-F6#"&t\""&++&*$F)!""#!&dQ'F(#"'B3>"'++DF6*$F%F>#!'(\K"F(*$F)F
2#"%(R&F<,DF%F*F)#"'ti5F,F-#!%`b"&]7$F1#"(h9T"F0F5#"(\:g"F0F9#!&t\"F(FL#"&dQ'F(
FO#!'jJ5F,*&F)F>F%F6#!%(R&Ffn*&F)F>F-F6#"'$f5"FD*&F)F>F%FF#!'8iZF<*&F)F>F-FF#!'
$\U"F,*(F)F>F%F6F-F6#!'H!G'F<*$F%FW#!',k')F0#!'J6LF0F6Fjn#"'x=9F(*$F)F>#!'L$p"F
fn,:F1#!&,!\FfnF\q#"%roF<F5FgoF9#"%x!)FDFjn#!'$f5"FfnFLFPFV#"'jJ5F,FO#"'$\U"F,#
"'.,>F0F6F%F.F)F`oF-#"&h=(F06",
I4C_3v_triang_laurentw,6#>%)symbolicGF660%&_nameG%&_sizeG%#_AG%"iG%"PG%"vG%"XG%
*cost_funcG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FgrC/>6$8$8%6$7(%#P1G%#P2G%#P3
G%#x1G%#x2G%#x3G7$-%"$G6$7$FF""%""$-F\u6$7$FFF6F`u@%/9$""!>8&7#-%$seqG6$-%'rndM
atG6#&&Fat6#8'Fgr/Fdv;F6-%%nopsG6#F`t>Fiu7#-F\v6$-I'MatrixG6$%*protectedG%(_sys
libG6$Favw,6$F%F)Fgr6$%)operatorG%&arrowGFgr-&T'6#T%6#,&FfuF6*&,&9%F6FWF6F6&&T#
F\x6#F6F6F6FgrFgr6(F_sFatFasFdvF^sF`t6#FF6$7'Q!FgrFW"#P"#s"#O7'F[yFWF\y"#VF^yFe
v>6%&8(Ffx&Fdy6#FF&Fdy6#F`u6%-I$<,>GFbw6$&FiuFfx-I$<|gr>GFbw6&F6FguFguFgu-F[z6$
&FiuFfy-F_z6&FguF6FguFgu-F[z6$&FiuFhy-F_z6&FguFguFguF6>6%&8)Ffx&F^[lFfy&F^[lFhy
6%&Fiu6#F_u&Fiu6#""&&Fiu6#""'>8*-F[z6&F%F)F-F6>8+-%$addG6$,&*$,&*&-I".G6$FawFbw
6$&&FdyFcv6$F6;FgrFgrF[\lF6-Fh\l6$&F\]l6$F`uF^]lF[\lFWF6&&F^[lFcv6$F6F6FWFFF6*$
,&*&-Fh\l6$&F\]l6$FFF^]lF[\lF6F_]lFWF6&Fd]l6$FFF6FWFFF6/Fdv;F6F`u>8,-&%"|irG6#%
"*G6%#F6FF%#~$G7%-%%diffG6$F_\lF%-F]_l6$F_\lF)-F]_l6$F_\lF->8--%$mapG6$%'expand
GFb^l@$FeuOFd_l>8.-%&minusG6$-%'indetsG6#Fd_l-Fa`l6#Fiu>6$8/80-%,poly2matrixG6$
Fd_lF\`l>81-%$srtG6$Fh`l-%%tdegG6#&F\`lFgr6%7#-%/permuteColumnsG6%Fg`lFh`lF]alF
`tFatFgrFgrFgr6#Fgu637'F[yFW"#;Fi[lF^y7'F[yFWF`u"#wF`y7'F[yFWF`u""*"#X7'F[yFW""
("#bF`y7'F[yFWFdbl"#$*F`y7'F[yFWF`u"#!)F`y7'F[yFWF`u"#TF`y7'F[yFWF`u"#>F`y7'F[y
FWF`u"$:"F`y7'F[yFWF`u"#uF`y7'F[yFWF`u"#CF`y7'F[yFWF`u"#RFbbl7'F[yFW"#A"#J"#_7'
F[yFWF`u"#QF`y7'F[yFWF`uF^yF`y7'F[yFWF`uFhclF`y7'F[yFWF`u"#ZFhclFgr
