M7R0
I,F_4l3v_dim27&,hn%#w2G#"+p3>$Q#",+++]7$%#u3G#"/$4EV5D#Q"/+++++]i%#v3G#"/^H@!)=
DY"0++++++D"%#w3G#!.hNTe3;$".+++++D"*&F)"""F-F6#".d2')f!QNF4*&F)F6F1F6#"0^.&)>(
*yx"F0*&F-F6F1F6#"/23WN\LYF,*&F%F6F-F6#"+fne*3$",+++Dc"*&F%F6F)F6#!+j$fz`#"+++]
7y*&F%F6F)""##!+p#))G4#F(*&F%F6F-FH#"+JfD'p%F(*&F%F6F1FH#!+J&el)\F(*&F%FHF-F6#!
)dmx\"*+++D"*&F%FHF)F6#")jKEd")++]i*&F%FHF)FH#")Zg-<")+++]*&F%FHF-FH#!)`$>&HFfn
*&F%FHF1FH#"(8`D)Ffn*&F1F6F%FH#!(p]<""(++D"*&F%F6F1F6#")^\mD"*++Dc"*$F%FH#"($*z
B%Ffn*$F)FH#"0f5Y)=%)z?"0++++++]#*$F-FH#!0T^]faak#F[p*$F1FH#!0fiQ<:[c#F[p#"0T.V
)yUIJF[pF6*(F%F6F)F6F1F6#!+TmvkHFB*(F%F6F-F6F1F6#!+P&=TN"FF*(F%FHF)F6F1F6#")VV
\&*FT*(F%FHF-F6F1F6#")P_7OFX*(F)F6F-F6F%FH#"&"QQ"'++D*(F%F6F)F6F-F6#")8uRHFdo,h
nF%#!-(z%4L"3""-+++++DF)#!08nahVhg'F[pF-#!/V=sT'e`'F0F1#!0zi)>*\&)R"F[pF5#!0>.5
$>(oR$F[pF9#!,(ee!f))*F0F<#"/Lto(4jX&"/++++++]F?#",6j;JA"F(FC#"-@zK'o&oFjqFG#",
@L]2X#",+++++&FK#!-T^#zdn$FjqFN#"-LL]tJNFjqFQ#!(B2g*FTFU#"*pX?u""*+++]#FY#!)Fh'
f"")+++DFgn#!)@d@<FTFjn#!(FDL$")++DJF]o#"*Be!)="FgsFao#"-z([g!H?FjqFeo#"(H&)*o"
(+D"yFho#!.,`Hu$z8F4F\p#"/^$=vW"=D"/++++]i:F_p#!0tB=;dE=#F0#"/LJ68.&4$"/++++++D
F6Fdp#!,$[D2C>F(Fgp#",([$H'QiFjqFjp#!)jG'=#FjsF]q#"*n@L=%FgsF`q#!*TWAW#FgsFdq#"
,j/)=YBF^s,hnF%#!-hF$=1F"FjqF)#"0n`#z&HMy"FgrF-#"1LK')3(zYK#F[pF1#"1`_=g;j"=$"0
+++++++&F5#!/BeMpAk#)FfvF9#!0ZLR3\'z))F[pF<#"1,,bqBa2AF[pF?#"-ZK=#G5&F^sFC#"-Lh
_[$*e"-++++]7FG#".hmlrxR"FjqFK#!-6M%[ZZ"FjqFN#!.*[!)\BB6FjqFQ#!*t%>DqFgsFU#!*^k
gk"FgsFY#!+z<ofA"+++++5Fgn#")J%>'="*++++#Fjn#"(^RY)")+++SF]o#!+8uZ37"*++++&Fao#
"-zU>W5:",++++]#Feo#"+\e)\&>F^xFho#"12'>aPlH=""0+++++++#F\p#!0^O3.][e%"1+++++++
5F_p#!1zeS#e8_#HFby#!0,<KecA1&F_yF6Fdp#!,.vb['yF^sFgp#"-<'[Q,J)FawFjp#"*2f9t&Fg
sF]q#!**32K@FfnF`q#!*da`9*FgxFdq#!,(4a!GT*Fjx,hnF%#!+LahXRFjqF)#!0"ynQ:JeLFfvF-
#"04!)>.N'>7F[pF1#!/p#p:t</$FfvF5#!0p_Yu=8d"FfvF9#!/\f1f!32%F[pF<#!/>%f@zK.&Ffv
F?#!,tYD+^(FawFC#!-^&>#e<6FjqFG#",xbB1&)*FjqFK#!,n`N%)*))FjqFN#!+xZEwbFjqFQ#!)h
9g`FgsFU#"*4rqF"FgxFY#")*)*)=WFgxFgn#")4drbFgxFjn#!)*=EI)FgxF]o#"'TVIFgxFao#!-*
>D;`!>FjqFeo#!)4&yo"FgxFho#!/T]Xz-&[*FfvF\p#!0,\$4NxF:FfvF_p#"0T)HOobh?Ffv#"/,,
wY>ZTFfvF6Fdp#!,$QS^%)oFawFgp#"-^b:2m7FjqFjp#")Tz-7FgsF]q#")"p*3GFgxF`q#")Tj8lF
gxFdq#",,WiWR$Fjq6",
I,C_4l3v_dim2w,6#>%)symbolicGF662%&_nameG%&_sizeG%#_AG%"iG%$lx1G%$lx2G%$lx3G%#R
2G%#R3G%$eqsG%"MG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F`^lC0>6$8$8%6$7%%#X1G%#X2G%#X
3G7#-%"$G6$7$""$""%Fg`l@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F\`l6#8'F`^l/Fial;F6
-%%nopsG6#F[`l>F^al7#-Faal6$-I'MatrixG6$%*protectedG%(_syslibG6$Ffalw,6$%"xG%"y
GF`^l6$%)operatorG%&arrowGF`^l-&T'6#T%6#,&F[alF6*&,&9%F6!""F6F6&&T#Fccl6#F6F6F6
F`^lF`^l6(Fh^lF\`lFj^lFialFg^lF[`l6#FH6$7'Q!F`^lFjcl"#P"#s"#O7'FcdlFjclFddl"#VF
fdlFjal>6%8(8)8*6%&F^alF^dl&F^al6#FH&F^al6#Fg`l>8+*&-%-getRotMatrixG6#-I$<,>G6$
FfblFgbl6%%#u2G%#v2GF%F6z+F]fl[[[[[[[[][[[mF6[[[[][[[[[[[mF6][[[[[[[[[[[mF6!F6F
6>8,*&-Fhel6#-F[fl6%F)F-F1F6z+Fgfl[[[[[[[[][[[mF6[[[[][[[[[[[mF6][[[[[[[[[[[mF6
!F6F6>8-7"?(FialF6F6Fh`l%%trueGC$>8.-I$<|gr>G6$FfblFgbl6%&F[el6$;F`^lF`^lFial-I
".G6$FfblFgbl6$)Feel%#%TG&F\elFfgl-Figl6$)FbflF]hl&F]elFfgl>Fjfl7$&FjflF`^l-&I.
LinearAlgebraG6$FfblFgbl6#%,DeterminantG6#F`gl>Fjfl-%%subsG6%/F^fl-%$rndGF`^l/F
_flFbilFjfl>8/-%$mapG6$%'expandGFjfl@$Fj`lOFfil>80-%&minusG6$-%'indetsG6#Ffil-F
cjl6#F^al>6$8182-%,poly2matrixG6$FfilF^jl>83-%$srtG6$Fjjl-%%tdegG6#&F^jlF`^l6&7
#-%/permuteColumnsG6%FijlFjjlF_[mF_[mF[`lF\`lF`^lF`^lF`^l6#F\al667'FcdlFjcl"#;"
"'Ffdl7'FcdlFjclFg`l"#XFhdl7'FcdlFjclFg`l""*Fb\m7'FcdlFjcl""("#bFhdl7'FcdlFjclF
f\m"#$*Fhdl7'FcdlFjclFg`l"#QFhdl7'FcdlFjclFg`l"#`FhdlF\]m7'FcdlFjclFg`l"#6Fhdl7
'FcdlFjclFg`l"")Fa]m7'FcdlFjclFf\m"#_Fhdl7'FcdlFjclFf\m"#^FhdlFj\m7'FcdlFjclFg`
l"#CFhdl7'FcdlFjclFg`l"#RFb\m7'FcdlFjcl"#A"#JFc]mFj\m7'FcdlFjclFg`lFfdlFhdl7'Fc
dlFjclFg`lF\^mFhdl7'FcdlFjclFg`lFe]mF\^mF`^l
