M7R0
I,F_4l3v_dim27&,2*(%#v3G"""%#u3GF'%#u2GF'#",([s%=b$"$+&*(F)F'F(F'%#w3GF'#!,B([h
/P"$D"*&F)F'F.F'F**&F(F'F.F'#!,([s%=b$F,*&F)F'F&F'#",B([h/PF1*&F(F'F&F'F/F&F*F.
F/,hnF)#",V=[v<""$]#F(#!/(Rj3Xr^%"&+D'F&#!06:=3AX-"F@F.#!/"Rp.pWS$"&]7$*$F(""##
!0>Pkq+QW#"'++D*$F&FG#"0t]QpoGU"FJ*$F.FG#"0")RhQjG[#FJ*$F)FG")&)4,\*(F.F'F(F'F)
FG"*gY$)z%*(F.F'F&F'F)FG!)#p3Y'F-#!,x!GyZI"#D*(F)F'F&F'F.F'#",zLW6J%F1*(F&F'F(F
'F)FG"*)=t(p#F%#!-umkAw6F1F3#".BT=asH#"%]i*&F&F'F.F'#!/%)e$>^85""&Dc"F9#"/phR6
\$3(F@*&F(FGF)FG"*tTHR#*&F&FGF)FG!*Jp#oQ*&F.FGF)FG")t<_)**&F(F'F)FG!*WH9^%*&F)F
GF&F'!*7,;X#*&F(FGF)F'#!,z(4'f>(F=*&F)F'F&FG#",8oY1s$"#]*&F)F'F.FG#!-Hh?[e7F=*&
F)F'F(F'#"-F4$)yi:F1F6#"-x4"[*y7F1*&F)FGF.F'"*'4m*z'F2#!-UY$oVg"F1#!/n5ZF'Q#H"&
++&F',hnF)#!,(**y$R1#FdpF(#!0Z[1S5\G""'+]7F&#!/89oA\f5FaoF.#!0$o.!y$f*4$FiqFF#"
0j4uy&phIFJFK#!0r!36@A.8FJFN#"/Z!\&o(4,'FcqFQ!+&ejA5"FS"*_8c$pFU"+i,"y5"F-#!,co
7h?)F1FZ#!-m]C'*oCF1Fgn!+]ax[AF%#!,y"QS=UFYF3#"/P_A=^;[FEF^o#"/*)ov`'*>q"&+]#F9
#!0ppZk7\Y%FiqFdo"*$p3GCFfo!*t7]["Fho"+lh&z+"Fjo!*-x9p)F\p"*7$**fRF^p#!-Vr$)\f^
F=Fap#"-VVb_J;F=Fep#",db$))>"*FdpFhp#!-MJJ8&*>F1F6#"-W*zz^u%F1F]q!*Mv5q)F2#"-#Q
DBn&GF1#!0F"y.@'Rw%FJF',hnF)#"*FcD](FdpF(#".$*>eG1P'FiqF&#!/HIHgoZOFiqF.#!/$eT<
^#p6FiqFF#!.(*or3c#="&+D"FK#".BaBa!\6FcqFN#"/p=q-&*[NFJFQ"(GZ#**FS!)al)G$FU")_t
2JF-#!+,a!4#>FdpFZ#!,"HPx7IF1Fgn")5HLMF%#!,L6AQ$*)F=F3#".rS@St'yFiqF^o#!.@)*eB5
1"FaoF9#!.p@4(oW>FbsFdo")+[)e(Ffo!)&*)f<"Fho!)L'\S(Fjo!)U/DAF\p"*E$f>:F^p#",$H:
GU:F=Fap#"**f\6ZF=Fep#!,FICX'>F=Fhp#",.Rl@7$F1F6#",FYF6i$F=F]q")-#GD%F2#!,"\()p
]()F=#!.h_))\1="F@F'6",
I,C_4l3v_dim2w,6#>%)symbolicGF'62%&_nameG%&_sizeG%#_AG%"iG%$lx1G%$lx2G%$lx3G%#R
2G%#R3G%$eqsG%"MG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F]xC3>6$8$8%6$7%%#X1G%#X2G%#X3
G7#-%"$G6$7$""$""%Fdz@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fiy6#8'F]x/Ff[l;F'-%%n
opsG6#Fhy>F[[l7#-F^[l6$-I'MatrixG6$%*protectedG%(_syslibG6$Fc[lw,6$%"xG%"yGF]x6
$%)operatorG%&arrowGF]x-&T'6#T%6#,&FhzF'*&,&9%F'!""F'F'&&T#F`]l6#F'F'F'F]xF]x6(
FexFiyFgxFf[lFdxFhy6#FG6$7'Q!F]xFg]l"#P"#s"#O7'F`^lFg]lFa^l"#VFc^lFg[l>6%8(8)8*
6%&F[[lF[^l&F[[l6#FG&F[[l6#Fdz>6$&Fh^l6$FGF'&Fh^l6$FdzF'6$FizFiz>6$&Fi^lFd_l&Fi
^lFf_lFg_l>6$&Fj^lFd_l&Fj^lFf_lFg_l>8+-%$mapG6$I'factorG6$Fc\lFd\l-%-getRotMatr
ixG6#-I$<,>G6$Fc\lFd\l6%F)%#v2G%#w2G>8,-Fc`l6$Fe`l-Fh`l6#-F[al6%F(F&F.>8-7"?(Ff
[lF'F'Fez%%trueGC$>8.-I$<|gr>G6$Fc\lFd\l6%&Fh^l6$;F]xF]xFf[l-I".G6$Fc\lFd\l6$)F
a`l%#%TG&Fi^lFebl-Fhbl6$)FaalF\cl&Fj^lFebl>Fial7$&FialF]x-%&numerG6#-Fe`l6#*(-&
I.LinearAlgebraG6$Fc\lFd\l6#%,DeterminantG6#F_blF'F_alFg]lF.Fg]l>Fial-%%subsG6%
/F^al-%$rndGF]x/F_alFgdlFial>8/-Fc`l6$%'expandGFial@$FgzOF[el>80-%&minusG6$-%'i
ndetsG6#F[el-Fgel6#F[[l>6$8182-%,poly2matrixG6$F[elFbel>83-%$srtG6$F^fl-%%tdegG
6#&FbelF]x6&7#-%/permuteColumnsG6%F]flF^flFcflFcflFhyFiyF]xF]xF]x6#Fiz697'F`^lF
g]l"#;""'Fc^l7'F`^lFg]lFdz"#XFe^l7'F`^lFg]lFdz""*Ffgl7'F`^lFg]l""("#bFe^l7'F`^l
Fg]lFjgl"#$*Fe^l7'F`^lFg]lFdz"#QFe^l7'F`^lFg]lFdz"#HFe^lF`hlF`hl7'F`^lFg]lFdz"#
ZFe^lFbhl7'F`^lFg]lFdz"#6Fe^l7'F`^lFg]lFdz"")Fghl7'F`^lFg]lFjgl"#_Fe^l7'F`^lFg]
lFjglFb^lFe^lF^hl7'F`^lFg]lFdz"#CFe^l7'F`^lFg]lFdz"#RFfgl7'F`^lFg]l"#A"#JFihlF^
hl7'F`^lFg]lFdzFc^lFe^l7'F`^lFg]lFdzFailFe^l7'F`^lFg]lFdz"#^FailF]x
