M7R0
I,F_4p2v_dim17%,4#!9H>$>'HJk(HZoN%";++++++++++++]"""%"vG#"7*)[[@*y9&p6&z("9++++
+++++++D*&F)F(%"uG""##"3BlQ+U9*Gj$"4+++++++D"y*&F)F/F.F/#!48hXjtYCTk)"6++++++++
+]#*&F)F(F.F(#!7fZC^*eMzB)*Q#"9++++++++++]7*&F)F/F.F(#!4$Q))[4,bFak"6+++++++++D
"*$F.F/#!3RB:<95=EIF6F.#"5`Xl<R'>6E9#"7++++++++]i:*&F.F/F)""$#".$RFB3UK"2++++++
++&,4#"5`"R09L7ex+)"8++++++++++]#F(F)#"7LgDI6N-Zhk8"8+++++++++]7$F-#!44`r!o2!)4
iA"5++++++++]iF3#!4dkD%Q=m6<7"5++++++++DJF7#!6nnodj[utl9""7++++++++]7yF;#!38d(4
v3<4a$F2F?#"1,X4F([%4!*"4+++++++]7$F.#!6BH&>5zoc-%)=FPFE#!,(oJA_'*"0++++++D',4F
)#!:\"z#[Cid`VGzo)";+++++++++++]iF.#"6..M=qd&eds<FY#!:.zkh[U'*fJbe%\"<+++++++++
+++D"F(F7#!7p,'*y\<)Q^r,"FYF3#"5(z$\#H$=Sy')pF>F-#!2ziy,!=4\R"4++++++++]#F?#"3>
#GwHyh)p8F>F;#"6$QKb*)HcV\+7"6++++++]7G)[FE#"4j$p4#e-$[u>FS6",
I,C_4p2v_dim1w,6#>%)symbolicGF(63%&_nameG%&_sizeG%#_AG%"iG%#x1G%#x2G%#R2G%"SG%"
qG%$eqsG%"cG%"FG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FepC3>6$8$8%6$7$%#X1G%#X2G7#-%"
$G6$7$FF""%F/@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fbr6#8'Fep/F]t;F(-%%nopsG6#Far
>Fbs7#-Fes6$-I'MatrixG6$%*protectedG%(_syslibG6$Fjsw,6$%"xG%"yGFep6$%)operatorG
%&arrowGFep-&T'6#T%6#,&F_sF(*&,&9%F(!""F(F(&&T#Fgu6#F(F(F(FepFep6(F]qFbrF_qF]tF
\qFar6#F/6$7'Q!FepF^v"#P"#s"#O7'FgvF^vFhv"#VFjvF^t>6$8(8)6$&FbsFbv&Fbs6#F/>6%&F
_w6$F(F(&F_w6$F/F(&F_w6$F(F/6%F`sF`sF`s>6%&F`wFhw&F`wFjw&F`wF\xF]x>8**&-%-getRo
tMatrixG6#-I$<,>G6$FjtF[u6%F.F7%"wGF(z+6%F.F)F]y[[[[][[[][[[oF([[[[[[[[][[[mF(]
[[[[[[[[[[[mF(!F(F(>8+-Fjx6#-Fes6$-I".G6$FjtF[u6%)&F_w6$;FepFepF]t%#%TG)FdxF^z-
%&crossG6#&F`wF\z/F]t;F(F\s>8,w,6%F_q%"jG%"kGFep6$FbuFcuFep-%&coeffG6%-F^[l6%-F
^[l6%FavF.F_sF)F]vF]y9&FepFep6$Fgq8/6#FF6$7'FgvF^v"")"#cFjv7'FgvF^vFj[l"#;Fjv>8
-7"?&8.7%7%F(F/FF7%F(F/F\s7%F(FFF\s%%trueGC$>Ff[l-&I.LinearAlgebraG6$FjtF[u6#%,
DeterminantG6#&Fay6$Fb\lF]z>F_\l7$&F_\lFep,T*&F]yFF-Fgz6%F(F`s""&F(F(*&F.F/-Fgz
6%Fj]lF`sF`sF(F(*&F]yF/-Fgz6%F(F`sF\sF(F(*&F.F(-Fgz6%F\sF`sF`sF(F(*&F]yF(-Fgz6%
F(F`sF(F(F(*&F)F(-Fgz6%F(F(F`sF(F(-Fgz6%F(F`sF`sF(**F.F/F)F(F]yF(-Fgz6%Fj]lF(F(
F(F(**F.F/F)F/F]yF(-Fgz6%Fj]lF\sF(F(F(**F.F(F)F(F]yF/-Fgz6%F/F(F\sF(F(**F.F/F)F
FF]yF(-Fgz6%Fj]lFj]lF(F(F(**F.F(F)F/F]yF/-Fgz6%F\sF\sF/F(F(**F.F(F)F(F]yF(-Fgz6
%F\sF(F(F(F(**F.F(F)F/F]yF(-Fgz6%F\sF\sF(F(F(*(F.F/F]yF(-Fgz6%Fj]lF`sF(F(F(*(F.
F/F)F(-Fgz6%Fj]lF(F`sF(F(*(F.F(F]yF/-Fgz6%F/F`sF\sF(F(*(F)F(F]yFF-Fgz6%F(F(Fj]l
F(F(*(F.F(F]yF(-Fgz6%F\sF`sF(F(F(*(F.F/F)F/-Fgz6%Fj]lF\sF`sF(F(*(F.F/F)FF-Fgz6%
Fj]lFj]lF`sF(F(*(F)F(F]yF/-Fgz6%F(F(F\sF(F(*(F.F(F)F(-Fgz6%F/F(F`sF(F(*(F.F(F)F
/-Fgz6%F\sF\sF`sF(F(*(F)F(F]yF(-Fgz6%F(F(F(F(F(>F_\l-%%subsG6$/F]y-%$rndGFepF_
\l>80-%$mapG6$%'expandGF_\l@$F^sOFjbl>81-%&minusG6$-%'indetsG6#Fjbl-Fgcl6#Fbs>6
$8283-%,poly2matrixG6$FjblFbcl>84-%$srtG6$F^dl-%%tdegG6#&FbclFep6&7#-%/permuteC
olumnsG6%F]dlF^dlFcdlFcdlFarFbrFepFepFep6#F`s697'FgvF^vF]\l""'Fjv7'FgvF^vFF"#SF
\w7'FgvF^vFF""*"#X7'FgvF^v""("#bF\w7'FgvF^vFjel"#$*F\w7'FgvF^vFF"#CF\w7'FgvF^vF
F"#RF\wF`fl7'FgvF^vFF"#`F\wFbfl7'FgvF^vFFF[\lF\w7'FgvF^vFF"#6F\w7'FgvF^vFFFj[lF
j[l7'FgvF^vFjel"#YF\w7'FgvF^vFjel"$Q%F\w7'FgvF^vFF"#FF\wF^fl7'FgvF^vFFFaflFhel7
'FgvF^v"#A"#J"#_7'FgvF^vFF"#QF\w7'FgvF^vFFFjvF\w7'FgvF^vFFFaglF\w7'FgvF^vFF"#^F
aglFep
