M7R0
I(F_4p_v27%,4*$%"uG""##"0$owe9WGT"3+++++++]7F&#!4f)G7U,$RDd$"6+++++++++D"*&F&F'
%"vGF'#"2h2%)=<N&Q;"3+++++++DJ*&F/""$F&F'#!,Z?!pFL"0++++++]#F/#"5*)z^o#)H"f:I#"
6+++++++++D'*&F&"""F/F<#"5V[%p')>N7)RW"6++++++++]7$*&F/F'F&F<#!2.Fl*Hf'yK("3+++
++++]i*&F/F<F&F'#!2"*QKxNX?P$"3++++++++]#!6z>2/?+,u#*4*"8++++++++++D'F<,4F%#"2,
#)G&HH/oJ"4+++++++++&F&#"4Lv.Rh+[3V&F:F.#"2Vl,(>t/LKFNF3#!.4JGqNb#"2++++++++"F/
#!5Zzzd!)[Jly%*"7++++++++++DF;#"5TS'4O]r<#*3)F:F@#!2Ji2Et8tR$"4++++++++D"FD#!2>
WSD@<&GQ"4++++++++]##"7@0S*\5jb&4&4$":+++++++++++D"F<,4F/#"7,)\!)RI3X)yDv"8++++
+++++D"yF&#"4f%fZ&Q)=(*z@"5+++++++]i:#!7pW4!*zmyPXFPFJF<F%#"1H#yOreOg&"3+++++++
+DF;#!5pM!eL&y>!3'*)"7+++++++++]7FD#"3(z_)*>Vp_s#FjnF@#!5^W2e<nw(o."F-F.#!1xJu5
gM5`"2+++++]i!RF3#"1,OtZ@Oh*)F26",
I(C_4p_v2w,6#>%)symbolicGF<64%&_nameG%&_sizeG%#_AG%"iG%#x1G%#x2G%#R2G%"SG%$indG
%"FG%"qG%#eqG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FfpC2>6$8$8%6$7$%#X1G%#X2G7$
7$F4""%Fjr@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fdr6#8'Ffp/F\t;F<-%%nopsG6#Fcr>Fa
s7#-Fds6$-I'MatrixG6$%*protectedG%(_syslibG6$Fisw,6$%"xG%"yGFfp6$%)operatorG%&a
rrowGFfp-&T'6#T%6#,&F^sF<*&,&9%F<!""F<F<&&T#Ffu6#F<F<F<FfpFfp6(F^qFdrF`qF\tF]qF
cr6#F'6$7'Q!FfpF]v"#P"#s"#O7'FfvF]vFgv"#VFivF]t>6$8(8)6$&FasFav&Fas6#F'>6%&F^w6
$F<F<&F^w6$F'F<&F^w6$F<F'6%F_sF_sF_s>6%&F_wFgw&F_wFiw&F_wF[xF\x>8**&-%-getRotMa
trixG6#-I$<,>G6$FitFjt6%F&F;%"wGF<z+6%F&F/F\y[[[[][[[][[[oF<[[[[[[[[][[[mF<][[[
[[[[[[[[mF<!F<F<>8+-Fix6#-Fds6$-I".G6$FitFjt6%-I$<|gr>G6$FitFjt6%&F^w6$F<F\t&F^
w6$F'F\t&F^w6$F4F\t)Fcx%#%TG-%&crossG6#-Fix6%&F_wF^z&F_wF`z&F_wFbz/F\t;F<F[s>8,
7%7%F<F'F47%F<F'F[s7%F<F4F[s?(F\tF<F<-F`t6#F`[l%%trueGC%>8--&I.LinearAlgebraG6$
FitFjt6#%,DeterminantG6#&F`y6$&F`[lF[t;FfpFfp>8.w,6%%#i1G%#j1G%#k1GFfp6$FauFbuF
fp-%&coeffG6%-F`]l6%-F`]l6%F`vF&F^sF/F\vF\y9&FfpFfp6$FfqF[\l6#F46$7'FfvF]v"#7"#
oFiv7'FfvF]vF[^l"#DFiv>&8/F[t,T-Fh\l6%F<F_sF_sF<*(F&F'F\yF<-Fh\l6%""&F_sF<F<F<*
(F/F<F\yF4-Fh\l6%F<F<Fh^lF<F<*(F&F<F\yF'-Fh\l6%F'F_sF[sF<F<*(F&F<F\yF<-Fh\l6%F[
sF_sF<F<F<*(F&F'F/F'-Fh\l6%Fh^lF[sF_sF<F<*(F&F'F/F4-Fh\l6%Fh^lFh^lF_sF<F<*(F/F<
F\yF'-Fh\l6%F<F<F[sF<F<*(F&F<F/F<-Fh\l6%F'F<F_sF<F<*(F&F<F/F'-Fh\l6%F[sF[sF_sF<
F<*(F/F<F\yF<-Fh\l6%F<F<F<F<F<*(F&F'F/F<-Fh\l6%Fh^lF<F_sF<F<*&F\yF4-Fh\l6%F<F_s
Fh^lF<F<*&F&F'-Fh\l6%Fh^lF_sF_sF<F<*&F\yF'-Fh\l6%F<F_sF[sF<F<*&F&F<-Fh\l6%F[sF_
sF_sF<F<*&F\yF<-Fh\l6%F<F_sF<F<F<*&F/F<-Fh\l6%F<F<F_sF<F<**F&F'F/F<F\yF<-Fh\l6%
Fh^lF<F<F<F<**F&F'F/F'F\yF<-Fh\l6%Fh^lF[sF<F<F<**F&F<F/F<F\yF'-Fh\l6%F'F<F[sF<F
<**F&F'F/F4F\yF<-Fh\l6%Fh^lFh^lF<F<F<**F&F<F/F'F\yF'-Fh\l6%F[sF[sF'F<F<**F&F<F/
F<F\yF<-Fh\l6%F[sF<F<F<F<**F&F<F/F'F\yF<-Fh\l6%F[sF[sF<F<F<>807#-Fds6$F`^l/F\t;
F<Ff[l>81-%$mapG6$%'expandGF_cl@$F]sOFfcl>82-%&minusG6$-%'indetsG6#Ffcl-Fcdl6#F
as>6$8384-%,poly2matrixG6$FfclF^dl>85-%$srtG6$Fjdl-%%tdegG6#&F^dlFfp6&7#-%/perm
uteColumnsG6%FidlFjdlF_elF_elFcrFdrFfpFfpFfp6#F_s697'FfvF]v"#;""'Fiv7'FfvF]vF4"
#WF[w7'FfvF]vF4""*"#X7'FfvF]v""("#bF[w7'FfvF]vFgfl"#$*F[w7'FfvF]vF4"#CF[w7'FfvF
]vF4"#RF[wF]gl7'FfvF]vF4"#`F[w7'FfvF]vF4"#()F[w7'FfvF]vF4FivF[w7'FfvF]vF4"")Feg
l7'FfvF]vFgfl"#^F[w7'FfvF]vFgflF\^lF[w7'FfvF]vFgfl"$J%F[w7'FfvF]vF4FgvF[wF[gl7'
FfvF]vF4F^glFefl7'FfvF]v"#A"#J"#_7'FfvF]vF4"#QF[wFcgl7'FfvF]vF4F_hlF[w7'FfvF]vF
4FgglF_hlFfp
