M7R0
I'F_5p2v7,,J%"xG#!+,c08:"*++++&%"yG#!*6G1w#"*+++]#%"zG#!(Hf[("(]i!R*(F-"""F)F2F
%F2#!*T@3T)F(*$F%""##"*h]/+#"*++++"*&F%F2F)F2#")<m!o$F(*&F%F2F-F2#!*zYdV$"*+++D
"*$F)F6#"*nhd!HF(*&F)F2F-F2#"+t2P#)=F(*$F-F6#")h*[h"")+++?*&F)F2F%F6#"*6LS6"F,*
&F-F2F%F6#"*V^%foF,*&F)F6F%F2#"*fi:L""*++++#*&F-F6F%F2#"+FmB/7F(*&F-F2F)F6#!)4o
Q")FT*&F-F6F)F2#!*fXT&zF(*$F%""$#!)xK4N")+++]*$F)Fin#!)dQeiFT*$F-Fin#")2bUTF@#"
*$fbqEF,F2,JF%#"+^v2n?F(F)#!*$p<iRF,F-#!)$)R"Q"")++DJF1#!)LOhQF\oF5#"*(RYgDF@F:
#!+z(p&)R#F(F=#!+PlnFIF(FA#"+4QY*[""+++++5FD#"**GTZ"*F(FG#!*$f;WLF(FK#")Ht57F(F
N#"+*==%3@F(FQ#"*<iK%RFgpFU#"+pj@p;F(FX#")n$Q)=FTFen#!*2!Hj<F@Fhn#!)zi=AF9F]o#!
'.ae"(+++)F`o#!)VN()>F,#!(.La$")+]i:F2,JF%#"*t5@!oF,F)#!+JF*eo"F(F-#!*$*>rF&F(F
1#"+(HztN"F(F5#"*P`v">F9F:#!*LuVA%F9F=#"*z:<*>F9FA#"+`)y33"F(FD#")x<xEF,FG#!+^@
ZY8F(FK#"*zN9c)F(FN#!*2.XU"F\pFQ#")r=IFF\oFU#"*tY!3dF9FX#!*F/[$zFgpFen#!*Pr>$RF
(Fhn#!)T7tqF\oF]o#!*p)G+?F(F`o#!*"\=0DF(#"*x&)QZ'F(F2,JF%#!*rt)f7")++]iF)#")"f-
\&FarF-#")TMtrF9F1#")ffc#*F\oF5#"*d1"z]F@F:#!*JJ)fuF@F=#")hByC"(+++&FA#"(8eH(")
+++5FD#!*ZMD>*F(FG#"+(\]U-"F(FK#"**RB^<F@FN#!+$yB`k#F(FQ#"*$)H.&HF(FU#!+PHH-CF(
FX#")Z[FEF,Fen#")")**R\F\oFhn#!)ZyMvF^uF]o#!*"3wZPFgpF`o#")rq-?F^u#!)*[0D$")+++
DF2,JF%#!*8fNq'F,F)#"*L$p'>"F9F-#!*h*='>"F(F1#")j$*\'*FarF5#"+tJ*>">F(F:#!)"Q+)
GF^vF=#!*n]aI*F(FA#"($\h$)FarFD#"*ZNYG%F(FG#"*f5@J'F(FK#"*(HTK9F9FN#!*P'><DF^uF
Q#")x4q6F(FU#!)<k&>%F(FX#!**)))yp%F,Fen#!*`IF4$F(Fhn#!)(pbe&F\oF]o#!)@MlQF,F`o#
"*R7p(>F(#!*,x[e"F(F2,JF%#"*B7v.%F(F)#!*8jfx'F,F-#!+hl%\S"F(F1#!**e]%>#F(F5#!*Z
W)GOF^uF:#"*nD'e&*F@F=#"*TI4`&F9FA#!)<GAV")+++SFD#")8-LLF^uFG#!)`*oj(F(FK#!*BDi
f"F,FN#!)2#o0&FarFQ#!*V<4b(FgpFU#"+`o#3)>F(FX#")f_E[FTFen#!)FW6'*F\oFhn#"*2zzA%
F(F]o#"*(GS'=$FgpF`o#")6feEF,#"*t&o'3#F,F2,JF%#!*Hn)4FF(F)#"&,e&FgwF-#"*p:5.%F(
F1#"*>UP_$F9F5#!*f?-c"F@F:#"**>iw=F(F=#!+zAj#4#F(FA#!)^l_LF(FD#"*\!GU<F,FG#!*FH
.?%F(FK#")t,+BFgwFN#!(t[_"F^uFQ#"*Z>kc"F(FU#"*2`)>#*F(FX#!*pq36#FTFen#!)(4=5&F@
Fhn#!*Vgj*QF(F]o#!*88+q"FgpF`o#!*x)yd8F(#"*"*G8:"F,F2,JF%#!+$exuh"F,F)#"*L=yo#F
\oF-#")(4nl#F^vF1#!(P-T$F,F5#!*hvs[#F(F:#"+81=-;F,F=#!)$3*3@FgwFA#!+*z/ml$FgpFD
#!+n$)p/:F(FG#"*P%\jFF(FK#!*<E<H$F,FN#"*tm1-"F@FQ#!*rH65)FgpFU#"+rpI85F(FX#")p(
e%*)F@Fen#!*$QzRBF,Fhn#")R#ov&F\oF]o#")zM'R#F\oF`o#")6:k8F@#!*.v#QiF(F2,JF%#!+r
Cb,DF(F)#"*FYf9%F,F-#!*^KeG"F(#").&R"[F(F2F1#!*4xb#**F,F5#")(*43VF\pF:#"+>#GFG"
F(F=#"*>#RdXF^uFA#!+`fmL7FgpFD#!*$[&Q)*)F,FG#!*,tKF$F(FK#!*(Q86=F,FN#"*t9C)\F(F
Q#"),/%o(F,FU#!*zsD?)F(FX#"*")z'[NFTFen#"*t)zmUF(Fhn#")p+pJF@F]o#")h'fv"F(F`o#!
)fWCJF@,JF%#!+r5Z!)=FgpF)#!+$zRD3"FgpF-#!*4I/-"F@F1#!*J_-M#F,F5#")j2AUF^uF:#"*R
s'4=F9F=#"+J^Nd7FgpFA#!)p`Z\F(FD#")^6J!)FTFG#!*j'H")[FgpFK#!*dI8*yFgpFN#"*pXx%>
FgpFQ#!**3&4y%FgpFU#!*T$Gq#)FgpFX#")dtNXF,Fen#"*fWV@#F(Fhn#"*"zMi8FTF]o#"*>HRf#
FgpF`o#!)PC9LFT#"*FRt@"F@F26",
I'C_5p2vw,6#>%)symbolicGF260%&_nameG%&_sizeG%#_AG%"iG%"aG%"XG%"EG%"GG%$eqsG%#_F
G%&_varsG%$_C0G%$_V0G%#_VG6"F_glC/>6$8$8%6$7#%"AG7#7$""%""*@%/9$""!>8&7#-%$seqG
6$-%'rndMatG6#&&Fihl6#8'F_gl/Fajl;F2-%%nopsG6#Fhhl>Ffil7#-Fiil6$-I'MatrixG6$%*p
rotectedG%(_syslibG6$F^jlw,6$F%F)F_gl6$%)operatorG%&arrowGF_gl-&T'6#T%6#,&FcilF
2*&,&9%F2!""F2F2&&T#Fi[m6#F2F2F2F_glF_gl6(FgglFihlFiglFajlFfglFhhl6#F66$7'Q!F_g
lF`\m"#P"#s"#O7'Fi\mF`\mFj\m"#VF\]mFbjl>8(&FfilFd\m>8)-Fiil6$-I$<,>G6$F^[mF_[m6
%-I$<|gr>G6$F^[mF_[m6%&F`]m6$FajlF2&F`]m6$FajlF6&F`]m6$FajlFin-F[^m6%&F`]m6$Faj
lF_il&F`]m6$Fajl""&&F`]m6$Fajl""'-F[^m6%&F`]m6$Fajl""(&F`]m6$Fajl"")&F`]m6$Fajl
F`il/Fajl;F2F_il>8*z+6)F%F)F-&Fc]mFd\m&Fc]m6#F6&Fc]m6#Fin&Fc]m6#F_il[[[[\[[[[[[
[\[mF2[[\[[[[[[[\[[[mF2\[[[[[[[\[[[[[mF2[[[[[[\[[[[[[[lF2>8+,&-I".G6$F^[mF_[m6%
,$F[`mF6)F[`m%#%TGF[`mF2*&-&I.LinearAlgebraG6$F^[mF_[m6#I&TraceG6$F^[mF_[m6#-Fi
`m6$F[`mF]amF2F[`mF2F`\m>8,7$&-%(convertG6$Ff`m%%listGF_gl-&Fbam6#%,Determinant
G6#F[`m>8--%$mapG6$%'expandGF[bm@$FbilOFhbm>8.-%&minusG6$-%'indetsG6#Fhbm-Fecm6
#Ffil>6$8/80-%,poly2matrixG6$FhbmF`cm>81-%$srtG6$F\dm-%%tdegG6#&F`cmF_gl6&7#-%/
permuteColumnsG6%F[dmF\dmFadmFadmFhhlFihlF_glF_glF_gl6#Fdil637'Fi\mF`\m"#;F]_mF
\]m7'Fi\mF`\mFin"#KF^]m7'Fi\mF`\mFinF`il"#X7'Fi\mF`\mFb_m"#bF^]m7'Fi\mF`\mFb_m"
#$*F^]m7'Fi\mF`\mFin"#7F^]m7'Fi\mF`\mFin"#')F^]mFbem7'Fi\mF`\mFin"#ZF^]m7'Fi\mF
`\mFin"#gF^]m7'Fi\mF`\mFin"#CF^]m7'Fi\mF`\mFin"#RFeem7'Fi\mF`\m"#A"#J"#_7'Fi\mF
`\mFin"#QF^]m7'Fi\mF`\mFinF\]mF^]m7'Fi\mF`\mFinFhfmF^]m7'Fi\mF`\mFin"#^FhfmF_gl
