M7R0
I.F_8ptF_radial7%,6%"xG#"*FDYz""*++++#%"yG#!(2ur&")++DJ%"zG#"->hro?A"-+++++D*&F
%"""F-F2#!,"p-#zM""-+++++]*&F)F2F-F2#"-"[&p=.5F5*&F-""#F)F2#"+HYH8^",++++D'*&F-
F:F%F2#",FP8r<""-++++]7*$F-F:#!+FD>CsFA*$F-""$#!+>oY(y"F0#"*Ju,B#"*+++]#F2,6F%#
"*d[cI%"*++++&F)#")$)G"3"F,F-#",@%48SE",++++D"F1#!+^-01#*",++++]#F6#!+`OWH\FWF9
#!*T'enB"*+++D'F>#!)Bi&3)FKFB#"+.z@f5"+++]i:FE#"+.]0'G$FT#"*"4MC=FKF2,joF%#"&$o
c"'++5F)#!&")3)"'++?F-#"(r$*p""(+++"F1#"&"*p#FcoF6#"($\07Fio*&F)F:F-F2#"($)36"F
ioF9#!(JaK#Fio*&F)F2F%F2#"&zv%"&++%*$F)F:#!'V4^Fio*&F%F:F-F:#"(ZSO#Fio*&F%F2F-F
F#"'^/mFio*&F-F2F%F:#!(VG"=FioF>#!$z""&++#*&F)F:F-F:#"&VA%"'++D*&F)F2F-FF#"&p;'
"&]7$*&F)FFF-F:#!'p9))Fio*&F)F:F-FF#"'._7"'++]*&F-F2F)FF#"'pp?Fiq*&F-""%F)F2#"&
>!zFdr*$F%F:#"%r'*"&++&*&F)F2F%F:#"'TnTFdr*&F%F2F)F:#!&$*z"F]r*&F%FFF-F:#"'^(Q"
Fio*&F%F:F-FF#!'xJ<Fiq*&F%FFF-F2#!&db%"'+]7*&F-FirF%F2#!$x#Feq*(F-F2F)F2F%F2#!'
4jDFiq*(F%F2F-F:F)F2#"(t3["Fio*(F%F:F-F:F)F2#"%f"*F_s*(F%F2F-F:F)F:#!'^F9Fdr*(F
%F2F-FFF)F2#!'HC[Fiq*(F%F:F-F2F)F2#!'"HL'Fdr*(F%F2F-F2F)F:#"#B"%+!)FB#!&*[y"&+D
'*$F-Fir#"&@6%FiqFE#!&PX(Fiq*$F)FF#!&Rw%Fio*$F%FF#!'P,8Fdr#!&8C)F_tF26",
I.C_8ptF_radialw,6#>%)symbolicGF267%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V
0G%#_VG%"iG%#vvG%$f11G%$f21G%$f31G%$f12G%$f22G%$f32G%"FG%$xx1G%$xx2G%$epiG%$eqs
G6"FivC6>6$8$8%6$7%%"dG%#x1G%#x2G7%7$""'""(7$F:F:Fdy@%/9$F2>8&7#-%$seqG6$-I'Mat
rixG6$%*protectedG%(_syslibG6$-%#opG6#&Fjx6#8,w,6$F%F)Fiv6$%)operatorG%&arrowGF
iv-&T'6#T%6#,&FgyF2*&,&9%F2!""F2F2&&T#Fb[l6#F2F2F2FivFiv6(FawFjxFhwFizF`wFix6#F
:6$7'Q!FivFi[l"#R"#u"#O7'Fb\lFi[lFc\l"#XFe\l/Fiz;F2-%%nopsG6#Fix>Fiy7#-F\z6$-%'
rndMatG6#FdzFh\l>8--I$<,>GFbz6)F1F6FBF%F)F-F2>8.-%$addG6$*&&&FiyF]\l6$F2FizF2&F
e]lFhzF2/Fiz;F2Fcy>8/-F\^l6$*&&F`^l6$F:FizF2Fb^lF2Fc^l>80-F\^l6$*&&F`^l6$FFFizF
2Fb^lF2Fc^l>81-F\^l6$*&&F`^l6$FirFizF2Fb^lF2Fc^l>82-F\^l6$*&&F`^l6$""&FizF2Fb^l
F2Fc^l>83-F\^l6$*&&F`^l6$FbyFizF2Fb^lF2Fc^l>84-Fg]l6%-I$<|gr>GFbz6%Fj]lFd_lF%-F
^al6%Ff^lF[`lF)-F^al6%F]_lFc`lF2>85-Fg]l6$&Fiy6#F:-F^al6$,&F2F2*&z'6$&Fhal6$F2F
2&Fhal6$F:F2[[[[[_[[[[sF2][[[[[[[[[sF2F2F-F2F2,&F2F2*&z'6$&Fhal6$F2F:&Fhal6$F:F
:[[[[[_[[[[sF2][[[[[[[[[sF2F2F-F2F2>86-Fg]l6$&Fiy6#FF-F^al6$,&F2F2*&z'6$&F`clFa
bl&F`clFcbl[[[[[_[[[[sF2][[[[[[[[[sF2F2F-F2F2,&F2F2*&z'6$&F`clFibl&F`clF[cl[[[[
[_[[[[sF2][[[[[[[[[sF2F2F-F2F2>87-I".G6$FazFbz6%)F]cl%#%TGFj`lFeal>887%&FadlFab
l&FadlF[cl-&I.LinearAlgebraG6$FazFbz6#_F_el%,DeterminantG6#Fj`l>8'-%$mapG6$%'ex
pandGFidl@$0FgyF2OFfel>8(-%&minusG6$-%'indetsG6#Ffel-Fdfl6#Fiy>6$8)8*-%,poly2ma
trixG6$FfelF_fl>8+-%$srtG6$F[gl-%%tdegG6#-Fez6#F_fl6%7$%#cfG-%/permuteColumnsG6
%FjflF[glF`glFixFjxFivFivFiv6#""!6:7'Fb\lFi[l"#;FbyFe\l7'Fb\lFi[lFF"#e"#V7'Fb\l
Fi[lFF""*Fg\l7'Fb\lFi[lFcy"#&*Ffhl7'Fb\lFi[lFcy"#dFfhl7'Fb\lFi[lFF"#NFfhl7'Fb\l
Fi[lFF"#QFfhlF_ilF_ilF_ilF_ilF_il7'Fb\lFi[lFF"#YFfhl7'Fb\lFi[lFF"#$)FfhlFcil7'F
b\lFi[lFF"#@Ffhl7'Fb\lFi[lFF"#gFfhl7'Fb\lFi[lFF"#CFfhl7'Fb\lFi[lFF"#SFg\l7'Fb\l
Fi[lFgu"#K"#_F_il7'Fb\lFi[lFFFe\lFfhl7'Fb\lFi[lFF"#LFfhl7'Fb\lFi[lFF"#`"#JFiv
