M7R0
I*F_focal6p7,,T%"xG#"'rSW"(+++"%"yG#!*BHN,("*++++&%"zG#"*^C`P$"*++++#*&F-"""F%F
2#"*.NB1#F0*&F-""#F%F2#")<^#y&"*+++D"*(F%F2F-F2F)F2#"*$)\/6"F,*(F%F2F)F6F-F2#!*
(4[$*R"+++++5*(F-F6F)F2F%F2#"*h@OE""*+++]#*(F%F6F-F2F)F2#!$,*"$+&*(F-F6F%F6F)F2
#"#BFH*$F)F6#"'4)z$FD*&F-F2F)F2#!)>s$G%")+++]*$F-F6#!*x@k"=F9*&F-F2F)F6#")x&4*f
")++]i*&F)F2F-F6#")ronHFR*&F)F6F%F2#!*86]([F,*&F%F2F)F2#")t!o)z")+++D*&F%F2F)""
$#!*Lt\^"F,*&F-F_oF%F2#")B&))p*F@*&F-F6F%F6#!$(=FH*&F-F2F%F6#!""F6*&F-F_oF%F6#!
"$"")*$F)F_o#"*,^Xf"FD*$F-F_o#!(F>$Q"(]i!R#")(Rs!oFDF2,TF%#")8sgn")+++SF)#"+(o'
G2>F@F-#"*de$Q')FDF1#")\1:ZF]oF5#")PR([*F0F:#")4a7dFRF=#!*,!)QS*F,FA#!*<'pUPF@F
E#"$`""$]#FI#!$t&"%+5FL#"*(pv.lF,FO#"*Hn$=<FDFS#")**e2s")+++?FV#!)V*32"")++DJFZ
#!*BhrW#FDFgn#!(x60'"(++g"Fjn#"*,Ra1"F0F^o#!*$fV"f*F@Fbo#"'Fs'*F]oFeo#!%*Q"F_rF
ho#!$*>"$+"F[p#!$">F\rF_p#")`#zl&FDFbp#!)nYWIF9#"*L>_X#F@F2,HF%#!%,@"&++%F)#"(*
fC:"'++]F-#"'pAG"'+]7F1#!'**[B"'++5F5#!("=$>#F(F:#!'Bf:"'++DF=#"&\N""&]7$FA#!'V
'G#FhtFL#!'f\WFcuFO#"(h>#>FhtFS#!&Rf""&Dc"FV#!'FN;FcuFZ#"&@g(F[uFgn#"&jX*F(Fjn#
"%hR"&+]#Fbo#!'2#y#FhtFeoF2F_p#!'BU@Fcu#"'pm8F(F2,TF%#!)"pAp#FfrF)#!+.ACy=F@F-#
!*6pNQ#F9F1#"*zyY8"FRF5#"*(H*\N#FDF:#"**yHdsF,F=#!*2w:#G"*++++"FA#!*h\qk%F@FEFi
oFI#"$(=F_r*(F%F6F)F6F-F2FFFL#"+Jn:O8F,FO#"*jQ6!yFDFS#"*Pnn/%F^xFV#!(FHn$"(+D"y
FZ#!)x)p5$FDFgn#!*Hf8%\F,Fjn#"*t(3iSF0F^o#!*<%)4h(F@Fbo#")$**HY#FDFeo#!$"RFHF[p
#"$B""$D"F_p#!)PvKEFRFbp#!)LR'p*F9#!)fS_zF,F2,TF%#"(Jcl$")+++5F)#!)$Q;V"FezF-#"
+LAWS@F@F1#")L\G5F0F5#!)***=f&FDF:#!*B1ph)F,F=#"+J6&**3"F@FA#!),m<))F^xFEFgsFI#
"#TF[zFcxFjqFL#"**R*[o#FDFO#!*<j$p6FDFS#"*"yv_9F9FV#"(x*HIF\yFZ#!*p1EO%FDFgn#"*
jN8a#F,Fjn#"*,otB"FRF^o#")fI**>F9Fbo#!*$\g'G"F@Feo#!#")F\rF[p#!$"))F_rF_p#!*^:.
&GFDFbp#")HXgUFir#")p.*R(FDF2,HF)#!(L"46F(F-#"(**G["FhtF1#!&ZH""&+D"F5#!'"o3*Fh
tF:#"&$=<F[uF=#"%*3(F_vFA#"'Lle"'++?FIF2FL#!(8nw"FhtFO#!'8c9"&++&FSFbvFV#!'J&>#
FcuFZ#"&Rf"F_vFgnFfvFjnFctF^oFdvFbo#"%@VFg^lF_p#"'V=?Fcu#"&$eYF[uF2,PF%#Fdt"'++
;F)#"+(\yBq#F@F-#!*T#)H$GF@F1#!)d6w<F[qF5#")">ek&F^xF:#")BAaWFRF=#!+npsj;F@FA#!
+*4L,;#F@FI#FGF_rFL#!(fry*F^xFO#"*VuvK$F^xFS#")(4jG*FRFV#!)V5>?")++]7FZ#!*`q\&>
FDFgn#")>&Rm"F^xFjn#!','3$F[qF^o#")j7?&)F@Fbo#!),@`JF@Feo#Fjo""%F[p#!$d#F_rF_p#
")\!>"QFRFbp#")@$)H@FY#!)F&)H<F^xF2,PF%#!'*4=%"(+++)F)#!)Vp4JF]oF-#!*tYB.%F^xF1
#")$z(GCFfrF5#"*"=BDDF0F:#"*t'3+<F^xF=#!*Hf<W(F,FA#"*FX*>')F,FI#F[rFHFL#")^jOvF
RFO#"*$f$p;*F,FS#!*H]'\cF,FV#!*R$e0?F9FZ#"*\;]Z$FDFgn#"(4:7*F0Fjn#"(4WZ$FfrF^o#
!)R"oW"F,Fbo#!)n/g9F,Feo#Fhs"$+#F[p#!$>"FHF_p#!*"Q:_?FDFbp#")@W#)HF9#!)z:ttF0F2
,DF)#!'(*4nFhtF-#!(d,k$F(F1#"&,@)FetF5#"&`]"FhvF:#!%hRFhvF=#"(Pa!>F(FA#"'H(e"Fh
tFL#"&hm$FfuFO#!'Z;<F^uFS#!&Ry)F^uFV#"'(Q)>F[uFZ#!&$p*)F[uFbo#"'$pA"F(F[pF2F_p#
"'xbQFhtFbp#!(pVB"Fht#!'(ou"F^uF2,6F)#"'h,mF(F-#"&*G%)FcuFL#!(.x!>F(FO#"'<$G$Fh
tFS#"'8(f(F(FV#!'L8EFhtFZ#"&@.#FfuF_p#!'(>-&F(Fbp#"(^@3"F(#!&4(pF^uF26",
I*C_focal6pw,6#>%)symbolicGF262%&_nameG%&_sizeG%#_AG%"iG%"aG%"XG%"FG%"KG%&omega
G%"GG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FfhlC1>6$8$8%6$7#%"AG7#7$F_o""'@%/9$
""!>8&7#-%$seqG6$-%'rndMatG6#&&Fbjl6#8'Ffhl/Fi[m;F2-%%nopsG6#Fajl>F^[m7#-Fa[m6$
-I'MatrixG6$%*protectedG%(_syslibG6$Ff[mw,6$F%F)Ffhl6$%)operatorG%&arrowGFfhl-&
T'6#T%6#,&F[[mF2*&,&9%F2FjoF2F2&&T#Fa]m6#F2F2F2FfhlFfhl6(F^ilFbjlF`ilFi[mF]ilFa
jl6#F66$7'Q!FfhlFjo"#P"#s"#O7'F`^mFjoFa^m"#VFc^mFj[m>8(-I$<|gr>GFg\m6$&F^[mF[^m
-&I.LinearAlgebraG6$Ff\mFg\m6#%/IdentityMatrixG6#F_o>8)-%$mapG6$w,6#F%Ffhl6$F\]
mF]]mFfhl-I$<,>GFg\m6%-Fi^m6%&Fj]m6$F[[mF2&Fj]m6$F[[mF6&Fj]m6$F[[mF_o-Fi^m6%&Fj
]m6$F[[mFhal&Fj]m6$F[[m""&&Fj]m6$F[[mFhjl-Fi^m6%&Fj]m6$F[[m""(&Fj]m6$F[[mF^p&Fj
]m6$F[[m""*FfhlFfhl6$FailFg^m6#F26$7'F`^mFjo"#7"#!)Fc^m7'F`^mFjoF]bm"#9Fc^m7#-%
"$G6#;F2F_o>8*z)6'F)F-&Fd_mF[^m&Fd_m6#F6&Fd_mFb_m[[_[[[[[[[\[sF2\[[[[[[_[[[[sF2
[[[[[\[[[[[[oF2>8+-F\`m6%-Fi^m6%F2F\[mF\[m-Fi^m6%F\[mF2F\[m-Fi^m6%F\[mF\[m*$%"f
GFjo>8,-I(algsubsG6$Ff\mFg\m6$/*$Ficm!"#F%-I".G6$Ff\mFg\m6$F_cm)F_cm%#%TG>8-,&-
Fddm6',$FgbmF6F[dm)FgbmFhdmF[dmFgbmF2*&-&F^_m6#I&TraceG6$Ff\mFg\m6#-Fddm6&FgbmF
[dmF_emF[dmF2FgbmF2Fjo>8.7$&-%(convertG6$Fjdm%%listGFfhl-&F^_m6#%,DeterminantG6
#Fgbm>8/-Ff_m6$%'expandGFjem@$FjjlOFgfm>80-%&minusG6$-%'indetsG6#Fgfm-Fcgm6#F^[
m>6$8182-%,poly2matrixG6$FgfmF^gm>83-%$srtG6$Fjgm-%%tdegG6#&F^gmFfhl6&7#-%/perm
uteColumnsG6%FigmFjgmF_hmF_hmFajlFbjlFfhlFfhlFfhl6#F\[m657'F`^mFjo"#;FhjlFc^m7'
F`^mFjoF_o"#KFe^m7'F`^mFjoF_oFham"#X7'F`^mFjoFcam"#bFe^m7'F`^mFjoFcam"#$*Fe^m7'
F`^mFjoF_o"#ZFe^m7'F`^mFjoF_o"#"*Fe^m7'F`^mFjoF_o"#DFe^m7'F`^mFjoF_o"#IFe^m7'F`
^mFjoF_o"#NFe^m7'F`^mFjoF_o"#rFe^m7'F`^mFjoF_o"#gFe^m7'F`^mFjoF_o"#CFe^m7'F`^mF
joF_o"#RFcim7'F`^mFjo"#A"#J"#_7'F`^mFjoF_o"#QFe^m7'F`^mFjoF_oFc^mFe^m7'F`^mFjoF
_oF\[nFe^m7'F`^mFjoF_o"#^F\[nFfhl
