M7R0
I*F_focal6p7,,T%"xG#"'rSW"(+++"%"yG#!*BHN,("*++++&%"zG#"*^C`P$"*++++#*$F)""$#"*
,^Xf""*+++]#*$F-F2#!(F>$Q"(]i!R*(F%"""F-F;F)F;#"*$)\/6"F,*(F%F;F)""#F-F;#!*(4[$
*R"+++++5*(F-F?F)F;F%F;#"*h@OE"F5*(F%F?F-F;F)F;#!$,*"$+&*(F%F?F-F?F)F;#"#BFI#")
(Rs!oF5F;*&F-F;F)F;#!)>s$G%")+++]*$F-F?#!*x@k"="*+++D"*$F)F?#"'4)z$F5*&F-F;F)F?
#")x&4*f")++]i*&F)F;F-F?#")ronHFR*&F)F?F%F;#!*86]([F,*&F%F;F)F;#")t!o)z")+++D*&
F%F;F-F?#")<^#y&FV*&F%F;F-F;#"*.NB1#F0*&F%F;F)F2#!*Lt\^"F,*&F-F2F%F;#")B&))p*FB
*&F%F?F-F?#!$(=FI*&F-F;F%F?#!""F?*&F%F?F-F2#!"$""),TF%#")8sgn")+++SF)#"+(o'G2>F
BF-#"*de$Q')F5F1#")`#zl&F5F6#!)nYWIFVF:#")4a7dFRF>#!*,!)QS*F,FC#!*<'pUPFBFF#"$`
""$]#FJ#!$t&"%+5#"*L>_X#FBF;FO#"*Hn$=<F5FS#")**e2s")+++?FW#"*(pv.lF,FZ#!)V*32""
)++DJFhn#!*BhrW#F5F[o#!(x60'"(++g"F^o#"*,Ra1"F0Fbo#")PR([*F0Feo#")\1:ZFaoFho#!*
$fV"f*FBF[p#"'Fs'*FaoF^p#!%*Q"F_rFap#!$*>"$+"Fdp#!$">F\r,HF%#!%,@"&++%F)#"(*fC:
"'++]F-#"'pAG"'+]7F1#!'BU@"'++DF:#!'Bf:F^uF>#"&\N""&]7$FC#!'V'G#Fht#"'pm8F(F;FO
#"(h>#>FhtFS#!&Rf""&Dc"FW#!'f\WF^uFZ#!'FN;F^uFhn#"&@g(F[uF[o#"&jX*F(F^o#"%hR"&+
]#Fbo#!("=$>#F(Feo#!'**[B"'++5F[p#!'2#y#FhtF^pF;,TF%#!)"pAp#FfrF)#!+.ACy=FBF-#!
*6pNQ#FVF1#!)PvKEFRF6#!)LR'p*FVF:#"**yHdsF,F>#!*2w:#G"*++++"FC#!*h\qk%FBFFFbpFJ
#"$(=F_r*(F%F?F)F?F-F;FG#!)fS_zF,F;FO#"*jQ6!yF5FS#"*Pnn/%F^xFW#"+Jn:O8F,FZ#!(FH
n$"(+D"yFhn#!)x)p5$F5F[o#!*Hf8%\F,F^o#"*t(3iSF0Fbo#"*(H*\N#F5Feo#"*zyY8"FRFho#!
*<%)4h(FBF[p#")$**HY#F5F^p#!$"RFIFdp#"$B""$D",TF%#"(Jcl$")+++5F)#!)$Q;V"FezF-#"
+LAWS@FBF1#!*^:.&GF5F6#")HXgUF[sF:#!*B1ph)F,F>#"+J6&**3"FBFC#!),m<))F^xFFF]tFJ#
"#TFazFcxFjq#")p.*R(F5F;FO#!*<j$p6F5FS#"*"yv_9FVFW#"**R*[o#F5FZ#"(x*HIF^yFhn#!*
p1EO%F5F[o#"*jN8a#F,F^o#"*,otB"FRFbo#!)***=f&F5Feo#")L\G5F0Fho#")fI**>FVF[p#!*$
\g'G"FBF^p#!#")F\rFdp#!$"))F_r,HF)#!(L"46F(F-#"(**G["FhtF1#"'V=?F^uF:#"&$=<F[uF
>#"%*3(F\vFC#"'Lle"'++?FJF;#"&$eYF[uF;FO#!'8c9"&++&FSFavFW#!(8nw"FhtFZ#!'J&>#F^
uFhn#"&Rf"F\vF[oFevF^oFctFbo#!'"o3*FhtFeo#!&ZH""&+D"FhoFcvF[p#"%@VFd^l,PF%#Fdt"
'++;F)#"+(\yBq#FBF-#!*T#)H$GFBF1#")\!>"QFRF6#")@$)H@FgnF:#")BAaWFRF>#!+npsj;FBF
C#!+*4L,;#FBFJ#FHF_r#!)F&)H<F^xF;FO#"*VuvK$F^xFS#")(4jG*FRFW#!(fry*F^xFZ#!)V5>?
")++]7Fhn#!*`q\&>F5F[o#")>&Rm"F^xF^o#!','3$F[qFbo#")">ek&F^xFeo#!)d6w<F[qFho#")
j7?&)FBF[p#!),@`JFBF^p#Fcp""%Fdp#!$d#F_r,PF%#!'*4=%"(+++)F)#!)Vp4JFaoF-#!*tYB.%
F^xF1#!*"Q:_?F5F6#")@W#)HFVF:#"*t'3+<F^xF>#!*Hf<W(F,FC#"*FX*>')F,FJ#F[rFIFO#"*$
f$p;*F,FS#!*H]'\cF,FW#")^jOvFRFZ#!*R$e0?FVFhn#"*\;]Z$F5F[o#"(4:7*F0F^o#"(4WZ$Ff
rFbo#"*"=BDDF0Feo#")$z(GCFfrFho#!)R"oW"F,F[p#!)n/g9F,F^p#F^t"$+#Fdp#!$>"FI#!)z:
ttF0F;,DF)#!'(*4nFhtF-#!(d,k$F(F1#"'xbQFhtF6#!(pVB"FhtF:#!%hRFgvF>#"(Pa!>F(FC#"
'H(e"FhtFO#!'Z;<F\wFS#!&Ry)F\wFW#"&hm$FcuFZ#"'(Q)>F[uFhn#!&$p*)F[uFbo#"&`]"FgvF
eo#"&,@)FetF[p#"'$pA"F(FdpF;#!'(ou"F\wF;,6F)#"'h,mF(F-#"&*G%)F^uF1#!'(>-&F(F6#"
(^@3"F(#!&4(pF\wF;FO#"'<$G$FhtFS#"'8(f(F(FW#!(.x!>F(FZ#!'L8EFhtFhn#"&@.#Fcu6",
I*C_focal6pw,6#>%)symbolicGF;62%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G%#
_VG%"iG%"aG%"XG%"FG%"PG%&omegaG%"GG%$eqsG6"FfhlC1>6$8$8%6$7#%"AG7#7$F2""'@%/9$F
;>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fbjl6#8,w,6$F%F)Ffh
l6$%)operatorG%&arrowGFfhl-&T'6#T%6#,&F[[mF;*&,&9%F;FcpF;F;&&T#Ff\m6#F;F;F;Ffhl
Ffhl6(F^ilFbjlFeilF]\mF]ilFajl6#F?6$7'Q!FfhlFcp"#R"#u"#O7'Fe]mFcpFf]m"#XFh]m/F]
\m;F;-%%nopsG6#Fajl>F][m7#-F`[m6$-%'rndMatG6#Fh[mF[^m>8--I$<|gr>GFf[m6$&F][mF`]
m-&I.LinearAlgebraG6$Fe[mFf[m6#_F__m%/IdentityMatrixG6#F2>8.-%$mapG6$w,6#F%Ffhl
6$Fa\mFb\mFfhl-I$<,>GFf[m6%-Fj^m6%&F_]m6$F[[mF;&F_]m6$F[[mF?&F_]m6$F[[mF2-Fj^m6
%&F_]m6$F[[mF^bl&F_]m6$F[[m""&&F_]m6$F[[mFhjl-Fj^m6%&F_]m6$F[[m""(&F_]m6$F[[mFg
p&F_]m6$F[[m""*FfhlFfhl6$FfilFh^m6#F;6$7'Fe]mFcp"#7"#')Fh]m7'Fe]mFcpF_bm"#9Fh]m
7#-%"$G6#;F;F2>8/z)6'F)F-&Ff_mF`]m&Ff_m6#F?&Ff_mFd_m[[_[[[[[[[\[sF;\[[[[[[_[[[[
sF;[[[[[\[[[[[[oF;>80-F^`m6%-Fj^m6%F;""!Ffcm-Fj^m6%FfcmF;Ffcm-Fj^m6%FfcmFfcm*$%
"fGFcp>81-I(algsubsG6$Fe[mFf[m6$/*$F\dm!"#F%-I".G6$Fe[mFf[m6$Facm)Facm%#%TG>82,
&-Fgdm6',$FibmF?F^dm)FibmF[emF^dmFibmF;*&-&F__m6#_F__m%&TraceG6#-Fgdm6&FibmF^dm
FbemF^dmF;FibmF;Fcp>837$-Fi[m6#-%(convertG6$F]em%%listG-&F__m6#_F__m%,Determina
ntG6#Fibm>8'-Fh_m6$%'expandGF]fm@$0F[[mF;OF\gm>8(-%&minusG6$-%'indetsG6#F\gm-Fi
gm6#F][m>6$8)8*-%,poly2matrixG6$F\gmFdgm>8+-%$srtG6$F`hm-%%tdegG6#-Fi[m6#Fdgm6%
7$%#cfG-%/permuteColumnsG6%F_hmF`hmFehmFajlFbjlFfhlFfhlFfhl6#Ffcm657'Fe]mFcp"#;
FhjlFh]m7'Fe]mFcpF2"#K"#V7'Fe]mFcpF2FjamFj]m7'Fe]mFcpFeam"#&*Fjim7'Fe]mFcpFeam"
#dFjim7'Fe]mFcpF2"#ZFjim7'Fe]mFcpF2"#(*Fjim7'Fe]mFcpF2"#DFjim7'Fe]mFcpF2Fh]mFji
mFfjm7'Fe]mFcpF2"#tFjim7'Fe]mFcpF2"#iFjim7'Fe]mFcpF2"#CFjim7'Fe]mFcpF2"#SFj]m7'
Fe]mFcpFLFiim"#_7'Fe]mFcpF2"#QFjimFfjm7'Fe]mFcpF2"#LFjim7'Fe]mFcpF2"#`"#JFfhl
