M7R0
I-F_focal6p_1s7,,J%"xG#")2+&Q$")+++]%"yG#!*Zn"oG"*+++D"%"zG#")PstBF(#")zF!*[F,"
""*(F-F2F)F2F%F2#"*@tmu$"*++++&*(F%F2F)""#F-F2#"*t3+V)"+++++5*(F%F2F)F2F-F8#!*<
R;q"F;*$F)F8#"*8(ov")"*+++]#*&F)F2F-F2#!)Z"e0"")+]i:*$F-F8#!*,L&R:FB*&F-F2F)F8#
!*HwQ(RF;*&F-F8F)F2#"*.j)*3#FB*&F)F8F%F2#!*@@"\jF6*&F%F2F)F2#!*8')yl$F6*&F-F8F%
F2#"*pF[)fF6*&F%F2F-F2#!)\so)*")++]i*&F%F2F)""$#!)pCQP"*++++#*&F%F2F-Fhn#!*j/j'
HF;*$F)Fhn#!*R1*H5F[o*$F-Fhn#!(6W9)F6,JF%#!(T*3eF,F)#"*jndu#F,F-#!)R"[*=")+++5F
3#!*(3'*)R'FBF7#!*$3GKLF;F<#"*r$>i$)F;#!)$[PD#F,F2F?#"*P_.;$F[oFC#!*@bvB#"*++++
"FG#"*<p6K#F,FJ#"*TFWd$F;FM#!*xl%4AF6FP#"*"*\>o%F;FS#"**\q(o*F6FV#!*F:Zn$F;FY#"
)"*GuQF,Fgn#!)4([#GF;F\o#")"yIT#F[oF_o#!*"39O>F;Fbo#!(L9@""(++D',JF%#"*(e,DzF6F
)#"*$fGaEFBF-#!)@f0<F,F3#!*dY*4hFBF7#!(RBe'")+++DF<#"*fr06"F,#!),8^9F(F2F?#"*h3
Mi"FipFC#!*^y>!*)F6FG#!)*efB"F6FJ#"*f.z()*F6FM#!)j\g&)FBFP#"(>ON(F\sFS#"("y%=&"
(+]7$FV#"*@#>maFBFY#!+Z!pwh"F6Fgn#!(d$psFfnF\o#!)ts7hF,F_o#!*x(yXKFBFbo#")B-[WF
6,JF%#!*HaM*=F,F)#!(>"G_"(+++#F-#"*(H%=D&FBF3#!*tFn'=F,F7#!*8Om#fF;F<#"*Pyx"=FB
#"'J!>%"(DJ&>F2F?#"+*[B?`"F6FC#!*z^lz#FfnFG#"((\R$*FFFJ#"*h,t)RF[oFM#!)"pA&oF6F
P#"*R">'*\F6FS#"*"Rl&\"FBFV#")tL'H$FBFY#"*frD`$FBFgn#")(e^C"FBF\o#!*$[!Qr#F;F_o
#!)>Pb7F\pFbo#!)*z(p^F6,JF%#!*2K<:%F6F)#!*xvy(pFBF-#"($z7]"(+D"yF3#!*J5H"pF6F7#
!*BUYn$F6F<#")*GpM)Fip#"*`FMG"FBF2F?#"*$=p+xFBFC#!*>!G([(F6FG#")h4G%)F6FJ#"*xw"
4FF,FM#!*n8T,"F,FP#"*2[&=PF6FS#"(zWr"FFFV#")jtlOFipFY#"*8z_x#F6Fgn#")L&y#zFBF\o
#!*^&*zA"F6F_o#!*4&y#z"F,Fbo#")4F\XF6,JF%#"*@=\v#FBF)#"*LRw.%F,F-#!*ZJpi%FBF3#"
+f%Hhe"F6F7#"*r7S/$F;F<#!**[_i)*F;F?#!+(Q"4#H&F;FC#"+43KPAF6FG#!)BqdSF(FJ#!*j8*
G%*F;FM#"*t.e:"F6FP#!*`>"G5F[oFS#!+4XI67F6FV#!)$*f!Q&F[oFY#!*$e^u5F,Fgn#!)x#4)=
F[oF\o#"**p!yP#F;#!(`k<%FFF2F_o#"**>U'R*F;Fbo#")(*[@?FB,JF%#!'j@$*FauF)#!*d`"yX
F6F-#!*p])f\F6F3#!*p2QN#F6F7#!*xCu1"F;F<#")P9-:FipF?#!*H\]<(F6FC#")r.)G&FfnFG#"
*pvKf"FBFJ#"+(R\n-"F;FM#")"Qn2%FBFP#")$p;M*F6FS#")drqYF,FV#!**o"=_$F6FY#"**3,r
\F6Fgn#")P$)4LF6F\o#"*^f&f;F;F_o#!)>n8@F\sFbo#!)Ht*4#Ffn#"*Lm#e6F,F2,JF%#!*P/]&
=FipF)#!*F_=I"F\sF-#"*fFg@#F,F3#")66Z!)F(F7#")tB-EFipF<#!*h/P9&F;F?#!'h*Q'"(+++
)FC#"*HD"**fF,FG#!*F?8l"F,FJ#!**4d%)yF6FM#!)^UdHFipFP#!*(*\e<%F;FS#!*8`i:$FBFV#
!+$e[bL#F;FY#"*ZOq+*FBFgn#!)`lfbF;F\o#"*`Fh_#F6F_o#"+L8'p?"F;Fbo#!)jz(H"F6#"*Tt
$=:FBF2,JF%#!*j)y)R)F6F)#!*"3a7[F,F-#!***)*)GVFBF3#"(t_!>"(++D"F7#")@"eK'FBF<#!
*R0)=DF6F?#"+hJ)3w"F;FC#"*>!>1_F6FG#"(d-5%"(]i!RFJ#!)xG4hFfnFM#"*T8c0%F6FP#!*d7
H#QF;FS#!*Zh`w&F6FV#!*\jmc%F[oFY#"*jAuB%F,Fgn#!)^JuDF6F\o#"*p,NG"FBF_o#"*FM]_"F
6Fbo#!*x19R#F6#"*$=4SWFBF2,6F)#!+r5Z!)=F;F-#!+$zRD3"F;F?#")j2AUFfnFC#"*Rs'4=Fip
FG#!)p`Z\F6FJ#!*dI8*yF;FM#!**3&4y%F;F_o#"*"zMi8F[oFbo#"*>HRf#F;#"*FRt@"F,F26",
I-C_focal6p_1sw,6#>%)symbolicGF262%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0
G%#_VG%"iG%"aG%"XG%"FG%"PG%&omegaG%"GG%$eqsG6"F]flC1>6$8$8%6$7#%"AG7#7$Fhn""*@%
/9$F2>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Figl6#8,w,6$F%F
)F]fl6$%)operatorG%&arrowGF]fl-&T'6#T%6#,&FbhlF2*&,&9%F2!""F2F2&&T#F]jl6#F2F2F2
F]flF]fl6(FeflFiglF\glFdilFdflFhgl6#F86$7'Q!F]flFdjl"#R"#u"#O7'F][mFdjlF^[m"#XF
`[m/Fdil;F2-%%nopsG6#Fhgl>Fdhl7#-Fghl6$-%'rndMatG6#F_ilFc[m>8-&FdhlFhjl>8.-%$ma
pG6$w,6#F%F]fl6$FhilFiilF]fl-I$<,>GF]il6%-I$<|gr>GF]il6%&Fgjl6$FbhlF2&Fgjl6$Fbh
lF8&Fgjl6$FbhlFhn-F^]m6%&Fgjl6$Fbhl""%&Fgjl6$Fbhl""&&Fgjl6$Fbhl""'-F^]m6%&Fgjl6
$Fbhl""(&Fgjl6$Fbhl"")&Fgjl6$FbhlF_hlF]flF]fl6$F]glF`\m6#F26$7'F][mFdjl"#7"#')F
`[m7'F][mFdjlF__m"#9F`[m7#-%"$G6#;F2Fhn>8/z)6'F)F-&Fc\mFhjl&Fc\m6#F8&Fc\m6#Fhn[
[_[[[[[[[\[sF2\[[[[[[_[[[[sF2[[[[[\[[[[[[oF2>80-F[]m6%-F^]m6%F2""!Fg`m-F^]m6%Fg
`mF2Fg`m-F^]m6%Fg`mFg`m*$%"fGFdjl>81-I(algsubsG6$F\ilF]il6$/*$F]am!"#F%-I".G6$F
\ilF]il6$Fb`m)Fb`m%#%TG>82,&-Fham6&,$Fi_mF8F_am)Fi_mF\bmFi_mF2*&-&I.LinearAlgeb
raG6$F\ilF]il6#_Fgbm%&TraceG6#-Fham6%Fi_mF_amFcbmF2Fi_mF2Fdjl>837$-F`il6#-%(con
vertG6$F^bm%%listG-&Fgbm6#_Fgbm%,DeterminantG6#Fi_m>8'-Fe\m6$%'expandGF`cm@$0Fb
hlF2OF_dm>8(-%&minusG6$-%'indetsG6#F_dm-F\em6#Fdhl>6$8)8*-%,poly2matrixG6$F_dmF
gdm>8+-%$srtG6$Fcem-%%tdegG6#-F`il6#Fgdm6%7$%#cfG-%/permuteColumnsG6%FbemFcemFh
emFhglFiglF]flF]flF]fl6#Fg`m657'F][mFdjl"#;F`^mF`[m7'F][mFdjlFhn"#K"#V7'F][mFdj
lFhnF_hlFb[m7'F][mFdjlFe^m"#&*F]gm7'F][mFdjlFe^m"#dF]gm7'F][mFdjlFhnF__mF]gm7'F
][mFdjlFhn"#(*F]gm7'F][mFdjlFhn"#DF]gm7'F][mFdjlFhnF`[mF]gmFhgm7'F][mFdjlFhn"#h
F]gm7'F][mFdjlFhn"#iF]gm7'F][mFdjlFhn"#CF]gm7'F][mFdjlFhn"#SFb[m7'F][mFdjl"#BF
\gm"#_7'F][mFdjlFhn"#QF]gmFhgm7'F][mFdjlFhn"#LF]gm7'F][mFdjlFhn"#`"#JF]fl
