M7R0
I-F_gp4p_scale7,,L%"vG#!'tR_"'++]%"xG#!'d5LF(%"yG#"(*\98F(%"wG#"(LCw"F(%"zG#!'8
<uF(*$F%""##!'47P"(+++"*&F/"""F%F;#"'F8TF(*&F)F;F%F;#"'<P?F(*&F,F;F%F;#"'*)3@"&
+D'*&F2F;F%F;#"&dv("&++&*$F/F6#"'Hg"*F9*&F)F;F/F;#!'rS=F(*&F,F;F/F;#!'40E"'++D*
&F2F;F/F;#!&xP""%]i*$F)F6#!'Z))pF9*&F,F;F)F;#"'tAxFR*&F2F;F)F;#"'.z7"'+]7*$F,F6
#!'rkOF9*&F,F;F2F;#"'jGGFR*$F2F6#"(,c<"F9#"'`$Q""'++?F;,LF%#"'"yO"F(F)#"&>w$F(F
,#"'\QFF(F/#"'(RK)FRF2#!'J`oF(F5#"'>pVF(F:#!'2dUF(F>#"'BW\F(FA#"'P'f%FRFE#"&UO#
"&Dc"FI#"'>/NFRFL#"'*)QBF(FO#"'*\7$F(FS#!(pbK"F(FW#"%wUF\qFZ#"'42gF(Fgn#"&d6%FD
F[o#!'VluF9F^o#!'<8AF(Fao#"&fc$F9#"'Hr'*F9F;,LF%#!'ju9F(F)#!$8#"%]7F,#"'4gGFjnF
/#"&h8&FHF2#"&*zDFjnF5#!&R([FjnF:#"&$e%*FHF>#"&"*o$FHFA#"(.J]"F(FE#"'\OHF(FI#!'
HQUF(FL#"$B""$+&FO#!&2D'FHFS#"&jn$"'++5FW#!%6m"&++#FZ#"%(o&"%+DFgn#"%8AFbtF[o#"
'`89FfoF^o#"(LUg"F(Fao#"(<v3"F9#!'Pa>F9F;,LF%#"'$)4ZF(F)#"%@<"%+?F,#"'<$f"FRF/#
!'B2NF(F2#"'L"4&F(F5#"%@#)FDF:#"'"y<(F(F>#"'(\c&FRFA#"'4&=)F(FE#"&LF&FbtFI#!'B$
Q"FbtFL#!'ZbVF(FO#!%\8FjnFS#"'x&f"F(FW#"'*\\'F9FZ#"'PF8FRFgn#!%nXF(F[o#"(L\P"F9
F^o#"((*G"=F(Fao#"&z%RFH#!&H*=F(F;,LF%#!&"4rFDF)#!'47wF9F,#"'F1@FRF/#!'JE@F9F2#
"&L0(FjnF5#"&j8"FRF:#!'pt5FHF>#!'LQ=FRFA#!%x()"&++%FE#"("=x5F9FI#"(Z$H8F9FL#!'B
"H"FRFO#"'6#Q"FfoFS#!'zDJFRFW#!%6HFbyFZ#!'^=;FfoFgn#"'P75FRF[o#"&dz&FjnF^o#!'t?
`F9Fao#"'6M<F(#!'xZwF9F;,LF%#"&T"RF(F)#!'()R=F9F,#!&Zj'FRF/#"'`G7F9F2#"'Ld5FbtF
5#!&\D%F9F:#!&`p*F9F>#"&,g*F9FA#"'4n(*F9FE#"'>c6FjnFI#"'V^!*F9FL#!'F8GF9FO#!'xq
7FjnFS#!'8#H&F9FW#"'(o0"F(FZ#"'L'Q$F9Fgn#"&dS(FDF[o#"'dw#)F9F^o#"'44CFjnFao#"'8
[JF(#!'H@\F9F;,LF%#"&,)pFjnF)#"'t!p'F9F,#!'HPGF9F/#!&$f6"&+D"F2#"&,"QF9F5#!&zL"
F(F:#!'n"G$F(F>#"&*>[FjnFA#"&rp)FfoFE#!'$zu%F9FI#"'*33"FfoFL#!'ZzGF(FO#!&LI*FRF
S#!'n/LF9FW#"'Bo6FfoFZ#!($=$>"F9Fgn#!'pt8F9F[o#!%,sFbtF^o#"'B1@F(Fao#"&tL$Fbt#"
&8!QFbtF;,LF%#"'(y:*F9F)#"'(Q=&F(F,#!'h$=#F9F/#"'n`8FRF2#!&d4%FDF5#!&RT"FfoF:#"
'8E$*F9F>#"'z#\"F(FA#!'L*H#FRFE#!'P3hF(FI#!'$3Q#F9FL#"',_KF9FO#"&xB)FDFS#"(*>W9
F9FW#"&"oUFbtFZ#!(RMz"F9Fgn#!'(=*eF(F[o#"'Bz5F9F^o#!(\cP"F9Fao#!'tS))F9#"'tz9FR
F;,LF%#"'^)[$F(F)#"'$zf"FRF,#"'>\8F(F/#"&6M""&]7$F2#!&*e)*F9F5#"'fA9F9F:#"'.3@F
foF>#"&"H%*FjnFA#!'xdJF9FE#!'*QQ#F(FI#!'L(Q$F9FL#!'*>8"F9FO#"'\GlF(FS#"'x85FbtF
W#!%TeFHFZ#"'"z7(F9Fgn#"'R_@F9F[o#!'(\<$F(F^o#!'>1UF9Fao#"&@&RFjn#"&"3#*FRF;,LF
%#"'.r>F(F)#!&*y5FbtF,#"&>L$FRF/#"'^')\F9F2#!'"R5&F(F5#"'87IF(F:#!(B@N"F9F>#"'6
Z=F9FA#!'hl))F9FE#"'@hDF9FI#"'>_yF(FL#!'6!o#F9FO#"&6K#FbtFS#!'RL9FjnFW#!$f&"%+5
FZ#"&2(pFjnFgn#!'V39FfoF[o#"&Z&RFbtF^o#"%z&)FfoFao#"%\M"&+]##"'H(f'F9F;6",
I-C_gp4p_scalew,6#>%)symbolicGF;61%&_nameG%&_sizeG%#_AG%"iG%#bbG%"RG%#R2G%&len_
cG%&len_rG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FfhlC0>6$8$8%6$7#%"bG7#7$"#8""'
@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fajl6#8'Ffhl/Fi[m;F;-%%nopsG6#F`jl>F^[m7#-F
a[m6$-I'MatrixG6$%*protectedG%(_syslibG6$Ff[mw,6$F)F,Ffhl6$%)operatorG%&arrowGF
fhl-&T'6#T%6#,&F[[mF;*&,&9%F;!""F;F;&&T#Fa]m6#F;F;F;FfhlFfhl6(F^ilFajlF`ilFi[mF
]ilF`jl6#F66$7'Q!FfhlFh]m"#P"#s"#O7'Fa^mFh]mFb^m"#VFd^mFj[m>8(-I".G6$Ff\mFg\m6$
&F^[mF\^m-I$<,>GFg\m6(F%F/F)F,F2F;>8))-F__m6%-I$<|gr>GFg\m6%&Fh^mF\^m&Fh^m6#""%
&Fh^m6#""(-Fg_m6%&Fh^m6#F6&Fh^m6#""&&Fh^m6#"")-Fg_m6%&Fh^m6#""$&Fh^m6#Fhjl&Fh^m
6#""*%#%TG>8*-&%"|irG6#%"^G6%Fb_m%#~$GF6>8+7#-Fa[m6$-%$addG6#&Ffam6$;FfhlFfhlFi
[m/Fi[m;F;F^am>8,7#-Fa[m6$-Fdbm6#&Ffam6$Fi[mFhbmFibm>8-7,,&&F\cmF\^mF;&F\cmFc`m
Fh]m,&FhcmF;&F\cmF]amFh]m,&&F_bmF\^mF;FicmFh]m,&F]dmF;&F_bmF]amFh]m-Fj^m6$&Fb_m
6$F;Fhbm)&Fb_m6$F6FhbmFdam-Fj^m6$Fbdm)&Fb_m6$F^amFhbmFdam-Fj^m6$FedmFidm-Fj^m6$
)&Fb_m6$FhbmF;Fdam&Fb_m6$FhbmF6-Fj^m6$F`em&Fb_m6$FhbmF^am-Fj^m6$)FcemFdamFgem>8
.-%$mapG6$%'expandGFecm@$FjjlOF]fm>8/-%&minusG6$-%'indetsG6#F]fm-Fjfm6#F^[m>6$8
081-%,poly2matrixG6$F]fmFefm>82-%$srtG6$Fagm-%%tdegG6#&FefmFfhl6%7#-%/permuteCo
lumnsG6%F`gmFagmFfgmF`jlFajlFfhlFfhlFfhl6#F\[m647'Fa^mFh]m"#;FhjlFd^m7'Fa^mFh]m
F^am"#LFf^m7'Fa^mFh]mF^amFcam"#X7'Fa^mFh]mF_`m"#bFf^m7'Fa^mFh]mF_`m"#$*Ff^m7'Fa
^mFh]mF^am"#KFf^m7'Fa^mFh]mF^am"#mFf^m7'Fa^mFh]mF^amFgjlFf^m7'Fa^mFh]mF^am"#RFf
^mFdim7'Fa^mFh]mF^am"$*>Ff^m7'Fa^mFh]mF^am"#CFf^m7'Fa^mFh]mF^amFeimFjhm7'Fa^mFh
]m"#A"#J"#_7'Fa^mFh]mF^am"#QFf^m7'Fa^mFh]mF^amFd^mFf^m7'Fa^mFh]mF^amF]jmFf^m7'F
a^mFh]mF^am"#ZF]jmFfhl
