M7R0
I)F_hyb51f7'z[p6'%#a1G%#a2G%#a3G%#a4G%#a5G[[[[[][[[[][[l"(+_G)\[[[[\[[[[][[l!(+
!\N[[c[[[[[[[][[lF+\[_[[[[[[[][[l!)+q$Q)\[[[[\[_[[\[[l!*+Snn"\[_[[[[_[[\[[l"(+!
)4([[[[[][c[[[[[lF+\[[[[\[c[[[[[l"(+!\N[[c[[[[c[[[[[lF+\[_[[[[c[[[[[l")+q$Q)[[[
[[\[[[[][w!(td$)*[[_[[[[[[[][w")^nXC\[[[[[[[[[][w!)++v\[[[[[\[_[[\[w")-N"*[[[_[
[[[_[[\[w")Y:n>[[[[[][[[[\[w")+#ph#\[[[[\[[[[\[w"*+++9"[[c[[[[[[[\[wF7\[_[[[[[[
[\[w")++]**[[[[[\[c[[[[w"(td$)*[[_[[[[c[[[[w!)^nXC\[[[[[[c[[[[wF4[[[[[][_[[[[w!
)+sZX\[[[[\[_[[[[wF9[[c[[[[_[[[[wF<\[_[[[[_[[[[w!*+++9"[[[[[\[[[[\[s")[v[;[[_[[
[[[[[\[s!(c)>B\[[[[[[[[[\[s!)+!=g([[[[[\[_[[[[sF?[[_[[[[_[[[[s!)[v[;\[[[[[[_[[[
[s!)+!)**z[[[[[][[[[[[s!(+_G)\[[[[\[[[[[[s")+qa$)[[c[[[[[[[[[sFC\[_[[[[[[[[[s!(
+!>y[[[[[\[[[[[[o")"e-i"[[_[[[[[[[[[o")jIz?\[[[[[[[[[[[o")++v\z[pF%[[[[[][[[[][
[l"*]Uz*>\[[[[\[[[[][[l!)+N`^[[c[[[[[[[][[lFJ\[_[[[[[[[][[l"(+ba'\[[[[\[_[[\[[l
")+548\[_[[[[_[[\[[l"*+q1."[[[[[][c[[[[[lFJ\[[[[\[c[[[[[l")+N`^[[c[[[[c[[[[[lFJ
\[_[[[[c[[[[[l!(+ba'[[[[[\[[[[][w"*j"RcB[[_[[[[[[[][w"),e'R)\[[[[[[[[[][w!)++]6
[[[[[\[_[[\[w"*-;$z;[[_[[[[_[[\[w!*E$y7Z[[[[[][[[[\[w!*+SL\#\[[[[\[[[[\[w"*+++4
"[[c[[[[[[[\[wFV\[_[[[[[[[\[w")+++B[[[[[\[c[[[[w!*j"RcB[[_[[[[c[[[[w!),e'R)\[[[
[[[c[[[[wFS[[[[[][_[[[[w"*+5*ze\[[[[\[_[[[[wFX[[c[[[[_[[[[wFen\[_[[[[_[[[[w!*++
+4"[[[[[\[[[[\[s")r5Q=[[_[[[[[[[\[s"*2#yCJ\[[[[[[[[[\[s!)+IE?[[[[[\[_[[[[sFhn[[
_[[[[_[[[[s!)r5Q=\[[[[[[_[[[[s"(+!Qq[[[[[][[[[[[s!*]Uz*>\[[[[\[[[[[[s")+b\W[[c[
[[[[[[[[sF\o\[_[[[[[[[[[s")+&3o#[[[[[\[[[[[[o"**zpTA[[_[[[[[[[[[o!*(Q856\[[[[[[
[[[[[o")++]6z[pF%[[[[[][[[[][[l"*+&[E=\[[[[\[[[[][[l")+DJ<[[c[[[[[[[][[lFco\[_[
[[[[[[][[l"*+Sz<$\[[[[\[_[[\[[l"*+!)eN'\[_[[[[_[[\[[l!)+]iM[[[[[][c[[[[[lFco\[[
[[\[c[[[[[l!)+DJ<[[c[[[[c[[[[[lFco\[_[[[[c[[[[[l!*+Sz<$[[[[[\[[[[][w!*vyBa"[[_[
[[[[[[][w!*7P#)*H\[[[[[[[[[][w!*++]]$[[[[[\[_[[\[w!*Cuk*f[[_[[[[_[[\[w"*]dZ3$[[
[[[][[[[\[w"*++v>"\[[[[\[[[[\[w"++++]7[[c[[[[[[[\[wF_p\[_[[[[[[[\[w"*+++,([[[[[
\[c[[[[w"*vyBa"[[_[[[[c[[[[w"*7P#)*H\[[[[[[c[[[[wF\p[[[[[][_[[[[w"*+S7)*)\[[[[
\[_[[[[wFap[[c[[[[_[[[[wFdp\[_[[[[_[[[[w!++++]7[[[[[\[[[[\[s"*(>tgD[[_[[[[[[[\[
s!)]UK"*\[[[[[[[[[\[s"*+!Qo;[[[[[\[_[[[[sFgp[[_[[[[_[[[[s!*(>tgD\[[[[[[_[[[[s"*
+](GE[[[[[][[[[[[s!*+&[E=\[[[[\[[[[[[s!*+v=!G[[c[[[[[[[[[sF[q\[_[[[[[[[[[s"*+g&
4:[[[[[\[[[[[[o!)DJHq[[_[[[[[[[[[o!*77wH$\[[[[[[[[[[[o"*++]]$z[pF%[[[[[][[[[][[
l"*+gG,%\[[[[\[[[[][[l"*+!*[q)[[c[[[[[[[][[lFbq\[_[[[[[[[][[l!*+IH_#\[[[[\[_[[
\[[l!*+ge/&\[_[[[[_[[\[[l!++!y4u"[[[[[][c[[[[[lFbq\[[[[\[c[[[[[l!*+!*[q)[[c[[[[
c[[[[[lFbq\[_[[[[c[[[[[l"*+IH_#[[[[[\[[[[][w")x0(G"[[_[[[[[[[][w"*^]ZM'\[[[[[[[
[[][w!*+++,*[[[[[\[_[[\[w"+-,&*o7[[_[[[[_[[\[w!)a6uD[[[[[][[[[\[w!*+SA=(\[[[[\[
[[[\[w"*+++u"[[c[[[[[[[\[wF^r\[_[[[[[[[\[w"++++-=[[[[[\[c[[[[w!)x0(G"[[_[[[[c[[
[[w!*^]ZM'\[[[[[[c[[[[wF[r[[[[[][_[[[[w!*++f!o\[[[[\[_[[[[wF`r[[c[[[[_[[[[wFcr
\[_[[[[_[[[[w!*+++u"[[[[[\[[[[\[s"*st6B([[_[[[[[[[\[s"*O#[Ft\[[[[[[[[[\[s!*++PL
$[[[[[\[_[[[[sFfr[[_[[[[_[[[[s!*st6B(\[[[[[[_[[[[s!++!oJx"[[[[[][[[[[[s!*+gG,%
\[[[[\[[[[[[s"*+!zE!*[[c[[[[[[[[[sFjr\[_[[[[[[[[[s")+q2")[[[[[\[[[[[[o!*Z#\Uj[[
_[[[[[[[[[o!)hME@\[[[[[[[[[[[o"*+++,*z[pF%[[[[[][[[[][[l!*+IXA"\[[[[\[[[[][[l!*
+I.[$[[c[[[[[[[][[lFas\[_[[[[[[[][[l!(+5b$\[[[[\[_[[\[[l!(+?5(\[_[[[[_[[\[[l"*+
g1'p[[[[[][c[[[[[lFas\[[[[\[c[[[[[l"*+I.[$[[c[[[[c[[[[[lFas\[_[[[[c[[[[[l"(+5b$
[[[[[\[[[[][w"*8zHJ"[[_[[[[[[[][w"*6\j(Q\[[[[[[[[[][w"*+++t&[[[[[\[_[[\[w"*A)p_
x[[_[[[[_[[\[w!*Eefi#[[[[[][[[[\[w!*+gWK#\[[[[\[[[[\[w"++++_8[[c[[[[[[[\[wF]t\[
_[[[[[[[\[w!++++Y6[[[[[\[c[[[[w!*8zHJ"[[_[[[[c[[[[w!*6\j(Q\[[[[[[c[[[[wFjs[[[[[
][_[[[[w"++gc@7\[[[[\[_[[[[wF_t[[c[[[[_[[[[wFbt\[_[[[[_[[[[w!++++_8[[[[[\[[[[\[
s"*Q6LS"[[_[[[[[[[\[s!)W&\$z\[[[[[[[[[\[s"*+?OS$[[[[[\[_[[[[sFet[[_[[[[_[[[[s!*
Q6LS"\[[[[[[_[[[[s"*+?_%H[[[[[][[[[[[s"*+IXA"\[[[[\[[[[[[s")+5^`[[c[[[[[[[[[sFi
t\[_[[[[[[[[[s!*+I"RM[[[[[\[[[[[[o"*r%*[k#[[_[[[[[[[[[o"*2CK7$\[[[[[[[[[[[o!*++
+t&6",
I)C_hyb51fw,6#>%)symbolicG"""67%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G%#
_VG%"iG%,skewsymmmatG%,quat2rotmatG%#QsG%#PsG%#TgG%"PG%"QG%"KG%#KRG%"RG%"tG%$eq
sG6"F_uC6>6$8$8%6$7%%#qsG%#psG%#tgG7%7$""#""&Fhw7$""$Fjw@%/9$Feu>8&7#-%$seqG6$-
I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Faw6#8,w,6$%"xG%"yGF_u6$%)operatorG
%&arrowGF_u-&T'6#T%6#,&F_xFeu*&,&9%Feu!""FeuFeu&&T#F\z6#FeuFeuFeuF_uF_u6(FhuFaw
F_vFayFguF`w6#Fiw6$7'Q!F_uFcz"#R"#u"#O7'F\[lFczF][l"#XF_[l/Fay;Feu-%%nopsG6#F`w
>Fax7#-Fdx6$-%'rndMatG6#F\yFb[l>8-w,6#%"vG6#%"XG6"F_uC$>F`w-%(convertG6$7%7%""!
,$&F_x6$F\xFeuFcz&F_x6$FiwFeu7%F_]lF]]l,$&F_x6$FeuFeuFcz7%,$Fa]lFczFe]lF]]lFgxO
F`wF_uF_uF_u6#Feu6%7'F\[lFcz"#="#5F_[l7'F\[lFcz""("$+""#V7'F\[lFczF`^l"#:"#_>8.
w,6#%%quatG6&%%tempGFivFb\l%"sG6"F_uC'>Fax-Fi\l6$7%7#&F_x6#Fiw7#&F_x6#F\x7#&F_x
6#""%Fgx>8'&F_xFgz>F`w-_I,TypesettingG6$FixFjx%0delayDotProductG6$-&I.LinearAlg
ebraG6$FixFjx6#_Fj`l%*TransposeG6#FaxFax>Faw,(-Fc`l6$FaxFh`lFiw*&F_`lFeu-FfzF_a
lFeu!"#*&,&*$F_`lFiwFeu&F`wFf]lFczFeu-&Fj`l6#_Fj`l%/IdentityMatrixGFi_lFeuFeuO*
&FawFeu,**$&FaxFf]lFiwFeu*$&FaxFb]lFiwFeu*$&FaxF`]lFiwFeuFialFeuFczF_uF_u6$F`vF
_\l6#Feu6(F\^l7'F\[lFczF`^l"#hFb^l7'F\[lFczF`^lF]^lFb^l7'F\[lFczF`^lF^[lFb^l7'F
\[lFczF`^l"$["Fb^l7'F\[lFczF`^l"#cFe^l>6%8/80816%&FaxFgz&FaxFf_l&FaxFi_l>82-Fi
\l6$-&I+ArrayToolsG6$FixFjx6#%,ConcatenateG6%FeuFgcl-Fgx6%FeuFjw/%%fillGFeuFgx>
83-Fi\l6$-Fbdl6%FeuFfclFhdlFgx>84-Fi\l6$7%7%FeuF]]lF]]l7%F]]lFeuF]]l7%F]]lF]]l%
"fGFgx>85-Fc`l6$-Fi\l6$7%7%%#r3G,$%#r4GFczF]]l7%FeflFcflF]]l7%F]]lF]]lFeuFgx-Fg
^l6#7&Feu%#r1G%#r2GF]]l>86-Fc`l6$*&FjelFeu-&Fj`l6#_Fj`l%.MatrixInverseG6#FcelFe
uF\fl>87-Fi\l6$7%7#%#t3G7#F]]lF]hlFgx>88-%$mapG6$w,6#F_vF_u6$FgyFhyF_u-&Fj`l6#_
Fj`l%+DotProductG6%-Fc`l6$Ffz&F]z6$;F_uF_uF_x-&Fj`l6#_Fj`l%-CrossProductG6$&F[z
Fail,&-Fc`l6$Ffz&T)FailFeu&T+6$FbilFeuFeu/%*conjugateG%&falseGF_uF_u6,FhvF\flFe
vF^dlFfvF]elFdvFhclFjvFigl6#Feu6$7'F\[lFcz"#9"$D#F_[l7'F\[lFczFijl"#<F_[l7#-Fdx
6#;FeuFjw>Fahl-Fchl6$w,6#%"eGF_u6$FgyFhyF_u-%'expandG6#-%&numerG6#-I)simplifyG6
$FixFjx6#**F_xFeuz'6$F[glF\gl[[[[[_[[[[sFeu][[[[[[[[[sFeu!#5F^hlFe\mFeflFe\mF_u
F_uF_u6#Feu6$7'F\[lFczFijl"#vF_[lF[[mFahl>Fahl-%%subsG6$7'/F[glF&/F\glF'/FcflF(
/FeflF)/F^hlF*Fahl>F_`l-Fchl6$Fi[mFahl@$0F_xFeuOF_`l>8(-%&minusG6$-%'indetsG6#F
_`l-F`^mF_al>6$8)8*-%,poly2matrixG6$F_`lF[^m>8+-%$srtG6$Ff^m-%%tdegG6#-F]y6#F[^
m6%7$%#cfG-%/permuteColumnsG6%Fe^mFf^mF[_mF`wFawF_uF_uF_u6#F]]l6:7'F\[lFcz"#;""
'F_[l7'F\[lFczF\x"#fFb^l7'F\[lFczF\x""*Fa[l7'F\[lFczF`^l"#&*Fb^l7'F\[lFczF`^l"#
dFb^l7'F\[lFczF\xF^^lFb^lFg`m7'F\[lFczF\x"#NFb^l7'F\[lFczF\x"#yFb^lFj`m7'F\[lFc
zF\xFf`mFb^l7'F\[lFczF\x"$A"Fb^l7'F\[lFczF\xF^[lFb^l7'F\[lFczF\x"#TFb^l7'F\[lFc
zF\x"$T#Fb^l7'F\[lFczF\x"#")Fb^l7'F\[lFczF\x"#lFb^l7'F\[lFczF\x"#CFb^l7'F\[lFcz
F\x"#SFa[l7'F\[lFcz"#B"#KFe^l7'F\[lFczF\x"#QFb^l7'F\[lFczF\xF_[lFb^l7'F\[lFczF
\x"#LFb^l7'F\[lFczF\x"#`"#JF_u
