M7R0
I7F_hyb13f_depth_laurent76,8**%#a1G"""%#a2G!""%#a3GF)%#b1GF)!(+++"*&F*F)F+F)"(+
++"*&F(F)F+F)F.*&F&F)F+F)F,**F&F)F(F)F*F)F+F'"(I,9#*,F&F'F(F)F*F)F+F)%"fGF)!'wX
7*(F*F)F+F)F4F)!'g=V*(F(F)F+F)F4F)"&'4?*(F&F)F+F)F4F)"'I(\"*(F&F)F(F)F*F)!'01Q*
*F&F)F(F)F*F)F+F)!'9G?,8**F&F'F(F)%#a4GF)F+F)F,*&FBF)F+F)F.F/F.F0F,**F&F)F(F)FB
F)F+F'F2*,F&F'F(F)FBF)F+F)F4F)F5*(FBF)F+F)F4F)F7F8!'W\NF:!(h9T"*(F&F)F(F)FBF)!(
pkK"**F&F)F(F)FBF)F+F)!'"H!*),6F-F,F/F.**F&F)F(F'F*F)F+F)F.F0F,F6"'g=VF8F9*,F&F
)F(F'F*F)F+F)F4F)"(\:g"F:F;F<"(RDq"F>!(ZOf#,6FCF,F/F.**F&F)F(F'FBF)F+F)F.F0F,FF
FOF8FG*,F&F)F(F'FBF)F+F)F4F)FQF:FHFI"'vmvFK!(C6G$,8**F&F'F*F)FBF)F+F)!'++]FC"'+
+]F-FfnF0Fen**F&F)F*F)FBF)F+F'"(l+2"*,F&F'F*F)FBF)F+F)F4F)!&)GiFF"&[+"F6!'su<F:
"&-!)**(F&F)F*F)FBF)"'N!)=**F&F)F*F)FBF)F+F)!&9G',6F-F,F/F.F0F.**F&F)F(F)F*F'F+
F)F,F6FOF8F9F:!'I(\"*,F&F)F(F)F*F'F+F)F4F)!&;Y'F<FRF>"'V">%,6*(F*F)FBF)F+F)F,*(
F(F)F*F)F+F)F.*(F&F)FBF)F+F)F.*(F&F)F(F)F+F)F,**F*F)FBF)F+F)F4F)FO**F(F)F*F)F+F
)F4F)FG**F&F)FBF)F+F)F4F)Fdo**F&F)F(F)F+F)F4F)"'/g>**F&F)F(F)F*F)FBF)FW*,F&F)F(
F)F*F)FBF)F+F)"&'=x,6FCF,F-F.**F&F)F*F'FBF)F+F)F.F0F,FF!&'4?F6FG*,F&F)F*F'FBF)F
+F)F4F)"&;Y'F:FapF^o!'ke%*F`o!'d>M,6FioF,*(F(F)FBF)F+F)F.*(F&F)F*F)F+F)F.F\pF,F
]pFO**F(F)FBF)F+F)F4F)F9**F&F)F*F)F+F)F4F)"(h9T"F`pFapFbpFRFcp"'jYw,6FCF,F/F.F0
F.**F&F)F(F)FBF'F+F)F,FFFOF8FGF:Faq*,F&F)F(F)FBF'F+F)F4F)!(q\K"FIFWFK"(P)[;,6FC
FenF-FfnF0Ffn**F&F)F*F)FBF'F+F)FenFF!&[+"F6F\oF:!&-!)**,F&F)F*F)FBF'F+F)F4F)!'&
[i'F^o!'KHZF`o"'(3U%,4*(F(F'F*F)FBF)F,*$FBF)F.*$F*F)F.*$F(F)F,**F(F'F*F)FBF)F4F
)!(\:g"*&FBF)F4F)Fdo*&F*F)F4F)Faq*&F(F)F4F)Fap*(F(F)F*F)FBF)"(5$eL,4FbrF,FcrF.*
(F(F)F*F'FBF)F.FdrF,FgrF;FhrFaq**F(F)F*F'FBF)F4F)FipFirFapFjr"'?bM,4FbrF,FcrF.F
drF.*(F(F)F*F)FBF'F,FgrF;FhrFaqFir!'/g>**F(F)F*F)FBF'F4F)FfqFjr"(^;d",4*(F&F'F(
F)F+F)F,*$F+F)"(+++#*(F&F)F(F'F+F)F,*(F&F)F(F)F+F'F2**F&F'F(F)F+F)F4F)F5*&F+F)F
4F)!'?P')**F&F)F(F'F+F)F4F)Ffr*&F&F)F(F)!(WJ3#F\p"(L3R#,4*(F&F'F*F)F+F)F,FgsFhs
*(F&F)F*F'F+F)F,*(F&F)F*F)F+F'F2**F&F'F*F)F+F)F4F)F5F\t"&#>S**F&F)F*F'F+F)F4F)F
fo*&F&F)F*F)"(M>K"F^q"'Hj@,4*(F&F'FBF)F+F)FenFgsF.*(F&F)FBF'F+F)Fen*(F&F)FBF)F+
F'Fhn**F&F'FBF)F+F)F4F)FjnF\tFG**F&F)FBF'F+F)F4F)F]r*&F&F)FBF)!'(*[GF[p"'t#z$,0
*&F(F'F*F)F,FhsF'*&F(F)F*F'F,*(F4F)F(F'F*F)Ffr*$F4F)!'g%*H*(F4F)F(F)F*F'Ffo*&F(
F)F*F)"(!z7I,0*&F(F'FBF)F,FhsF'*&F(F)FBF'F,*(F4F)F(F'FBF)FfrFiu"(AH#G*(F4F)F(F)
FBF'Ffq*&F(F)FBF)"(h*H\,0*&F*F'FBF)F,FhsF'*&F*F)FBF'F,*(F4F)F*F'FBF)FfoFiu!'3?R
*(F4F)F*F)FBF'Ffq*&F*F)FBF)"(JhA"6",
I7C_hyb13f_depth_laurentw,6#>%)symbolicGF'6>%&_nameG%&_sizeG%#_AG%"iG%,skewsymm
matG%,quat2rotmatG%"QG%"PG%"XG%(CentersG%"KG%"RG%$noXG%"TG%&alphaG%%betaG%#XQG%
#XPG%"EG%%tempG%%combG%#E1G%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F^wCD>6$8$8%6$
7%%"qG%"pG%"xG7%7$""#""%7$F^zF'7$""$Fbz@%/9$F'>8&7#-%$seqG6$-I'MatrixG6$%*prote
ctedG%(_syslibG6$-%#opG6#&Ffy6#8'w,6$F[z%"yGF^w6$%)operatorG%&arrowGF^w-&T'6#T%
6#,&FezF'*&,&9%F'F)F'F'&&T#Fa\l6#F'F'F'F^wF^w6(FfwFfyFhwFg[lFewFey6#F^z6$7'Q!F^
wF)"#R"#u"#O7'F`]lF)Fa]l"#XFc]l/Fg[l;F'-%%nopsG6#Fey>Fgz7#-Fjz6$-%'rndMatG6#Fb[
lFf]l>8(w,6#%"vG6#F]x6"F^wC$>Fey-%(convertG6$7%7%""!,$&Fez6$FbzF'F)&Fez6$F^zF'7
%Fb_lF`_l,$&Fez6$F'F'F)7%,$Fd_lF)Fh_lF`_lF][lOFeyF^wF^wF^w6#F'6%7'F`]lF)"#="#5F
c]l7'F`]lF)""("$+""#V7'F`]lF)Fc`l"#:"#_>8)w,6#%%quatG6&FhxF`xFf^l%"sG6"F^wC'>Fg
z-F\_l6$7%7#&Fez6#F^z7#&Fez6#Fbz7#&Fez6#F_zF][l>Fg[l&FezF[]l>Fey-_I,Typesetting
G6$F_[lF`[l%0delayDotProductG6$-&I.LinearAlgebraG6$F_[lF`[l6#%*TransposeG6#FgzF
gz>Ffy,(-Fcbl6$FgzFhblF^z*&Fg[lF'-Fj\lF^clF'!"#*&,&*$Fg[lF^zF'&FeyFi_lF)F'-&Fjb
l6#%/IdentityMatrixGF[blF'F'O*&FfyF',**$&FgzFi_lF^zF'*$&FgzFe_lF^zF'*$&FgzFc_lF
^zF'FhclF'F)F^wF^w6$FiwFc^l6#F'6(F_`l7'F`]lF)Fc`l"#hFe`l7'F`]lF)Fc`lF``lFe`l7'F
`]lF)Fc`lFb]lFe`l7'F`]lF)Fc`l"$["Fe`l7'F`]lF)Fc`l"#cFh`l>6%8*8+8,6%&FgzF[]l-F\_
l6$&FgzFhalI'VectorG6$F_[lF`[l&FgzF[bl>Feel-F\_l6$-&I+ArrayToolsG6$F_[lF`[l6#%,
ConcatenateG6%F'Feel-F][l6%F'F'/%%fillGF'F][l>Feel-F\_l6$-Fcfl6%F^zFeelFfelF][l
>Fdel-F\_l6$-Fcfl6%F'Fdel-F][l6%F'F_zF[glF][l>8--F][l6%FbzF_z/F\glF`_l>8.-&Fjbl
6#%/DiagonalMatrixG6#7%F4F4F'>8/-Fj`l6#7&F'%#r1G%#r2G%#r3G>80F_z>81-F][l6%FbzF'
/%'symbolG%"tG>82-Fahl6#-%$mapG6$w,6#FhwF^w6$F\\lF]\lF^w-%$catG6$.%"aGFezF^wF^w
F^w6#F'6$7'F`]lF)"#Y"#gFc]l7'F`]lF)Fijl"#\Fc]l7#-Fjz6#;F'F_il>83-Fahl6#-F\jl6$w
,F_jlF^w6$F\\lF]\lF^w-Fbjl6$.%"bGFezF^wF^wF^w6#F'6$7'F`]lF)Fe]l"#fFc]l7'F`]lF)F
e]l"#[Fc]lF][m>&Fb[m6$F^zF^zF'>&Fb[m6$FbzFbzF'>&Fb[m6$F_zF_zF'>84-I".G6$F_[lF`[
l6%-&Fjbl6#%.MatrixInverseG6#F_hlFdelFhil>85-&%"|irG6#%"+G6%-F_]m6$Fghl,&-F_]m6
$FeelFb[mF'FjglF'%#~$G-F_]m6$Fail-F][l6%F'F_ilF[gl>867">87F[_m?&88-&I)combinatG
6$F_[lF`[l6#%'chooseG6$F_ilF^z%%trueGC$>F]_m7$-Fc[l6#F]_m/,&&Fh]m6$;F^wF^w&F__m
F[]lF'&Fh]m6$Fa`m&F__mFhalF),&&F]]mF``mF'&F]]mFd`mF)>Fj^m7$-Fc[l6#Fj^m-%&numerG
6#,&-I)simplifyG6$F_[lF`[l6#-F_]m6$-Fibl6#-%$lhsG6#&F]_m6#F)FiamF'-Fbam6#-F_]m6
$-Fibl6#-%$rhsGF[bmFdbmF)>89F[_m?&F__m-Fa_m6$-%)numelemsGF\`mF^zFg_m>Fgbm7$-Fc[
l6#Fgbm-F^am6#,&-Fbam6#-F_]m6$-Fibl6#-Fjam6#&F]_m6#Fb`m-Fjam6#&F]_m6#Fe`mF'-Fba
m6#-F_]m6$-Fibl6#-FebmF[dm-FebmF_dmF)>8:7$F_cmF[am>F[em-F\jl6$w,6#%"eGF^w6$F\\l
F]\lF^w-%'expandG6#-Fbam6#*&FezF'-F\_l6$-%'indetsG6#Fez%"*GF)F^wF^wF^w6#F'6$7'F
`]lF)"#9F[elFc]l7'F`]lF)Fcfm"#<Fc]l-%%subsG6$7#/F4-I%sqrtG6$F_[lF`[l6#F4F[em>F[
em-%'subsopG6$/""&%%NULLGF[em>8;-F\jl6$FeemF[em@$/FezF`_lOFggm>8<-%&minusG6$-F]
fm6#Fggm-F]fmF^cl>6$8=8>-%,poly2matrixG6$FggmF^hm>8?-%$srtG6$Fhhm-%%tdegG6#&F^h
mF^w6%7#-%/permuteColumnsG6%FghmFhhmF]imFeyFfyF^wF^wF^w6#F`_l6K7'F`]lF)"#;""'Fc
]l7'F`]lF)FbzFaelFe`l7'F`]lF)Fbz""*Fe]l7'F`]lF)Fc`l"#&*Fe`l7'F`]lF)Fc`l"#dFe`l7
'F`]lF)FbzFa`lFe`lFfjm7'F`]lF)FbzF\[mFe`l7'F`]lF)Fbz"#xFe`lF_jmFhjm7'F`]lF)Fbz"
#NFe`l7'F`]lF)Fbz"#ZFe`lFjjm7'F`]lF)Fbz"#6Fe`l7'F`]lF)Fbz"#JFe`l7'F`]lF)Fbz"#zF
e`l7'F`]lF)Fbz"#yFe`l7'F`]lF)FbzF``lFe`lFf[nFf[nF_jm7'F`]lF)Fbz"#sFe`l7'F`]lF)F
bzFajmFe`l7'F`]lF)Fbz"#7Fe`l7'F`]lF)Fbz"")F]\n7'F`]lF)Fc`l"$>"Fe`l7'F`]lF)Fc`l"
$o"Fe`lFfjmF\\n7'F`]lF)Fc`l"$!>Fe`l7'F`]lF)Fbz"#CFe`l7'F`]lF)Fbz"#))Fe`l7'F`]lF
)Fbz"#GFe`lFd\n7'F`]lF)FbzFa]lFe]l7'F`]lF)"#AFa[nFh`l7'F`]lF)Fbz"#QFe`l7'F`]lF)
FbzFc]lFe`lF`[n7'F`]lF)FbzF][nFa[nF^w
