M7R0
I;F_hyb13f_depth_formulation77,8*&%#a1G""#%"fG"""!""*(F&F)%#a2GF)F(F)F)*(F&F)%#
a3GF)F(F)F)*(F,F)F.F)F(F)F**&%#b1GF'F(F)F)*$F&F'F**&F&F)F,F)#"$t&"%+5*&F.F)F&F)
#!$,#"$]#*&F.F)F,F)#"'Bu?"'++D*&F1F)F(F)#"$Z(F6F(#"'*G4""'++],8F%F*F+F)*(F&F)%#
a4GF)F(F)F)*(F,F)FGF)F(F)F*F0F)F2F*F3F4*&F&F)FGF)#"$`""$+&*&FGF)F,F)#!&j*y"(+++
"F?#"$Z*F6F(#!'*)>$)FP,6F+F*F-F)*&F,F'F(F)F)F/F*F3#!$t&F6F7F8*$F,F'#"'xWBFDF;F<
F?#"$J""$+#F(#!'2njFP,6F+F*FFF)FVF)FHF*F3FWFIFJFYFZFMFNF?#"$r"FhnF(#!'PO%)FD,6F
-F*FFF)F/F)FHF*F7#"$,#F:FIFJF;#!'Bu?F>FMFNF?#F)""&F(#!(n00"FP,8F%F*F-F)FFF)*(F.
F)FGF)F(F)F*F0F)F2F*F7F8FIFJ*&F.F)FGF)#!$H%"&+D'F?#"$,)FLF(#"'@P6FP,6F+F*F-F)F/
F)*&F.F'F(F)F*F3FWF7F8F;Fco*$F.F'#!'<45F^pF?FfnF(#"'B$*)*FP,6F+F*FFF)F/F)FjoF*F
3FWFIFJF;FcoF[pF\pF?F\oF(#!'d[5FP,6F-F*FFF)FdpF)FjoF*F7FaoFIFJFep#"'<45F^pF[pF
\pF?FeoF(#!&4Z&"&++&,6F+F*F-F)FHF)FjoF*F3FWF7F8FM#"&j*yFPF[pF\pF?FfnF(#"&rX*"'+
+5,6F+F*FFF)FHF)*&FGF'F(F)F*F3FWFIFJFMFdq*$FGF'#!&P>$"'++?F?F\oF(#"'j#R&F^r,6F-
F*FFF)FjoF)FjqF*F7FaoFIFJF[p#"$H%F^pF[rF\rF?FeoF(#"'@,NF^r,4FVF*F/F)FHF)FjoF*FY
#!'xWBFDF;FcoFMFdqF[pF\pF(#"(<Ce"FP,4F/F*FHF)FdpF)FjoF*F;F<FMFdqFepF^qF[pF\pF(#
!&8O%FP,4F/F*FHF)FjoF)FjqF*F;F<FMFdqF[pFbrF[rF\rF(#"'$H+(F>,4F%F*F+F'FVF*F0F)F2
F*F3#F5FLFYFgrF?#"#BF:F(#"'d5<F^r,4F%F*F-F'FdpF*F0F)F2F*F7#F9"$D"FepFfpF?#"$,(F
LF(#"(,z?"FP,4F%F*FFF'FjqF*F0F)F2F*FI#FKF:F[rF\rF?#"$,*FLF(#"'j@$*FD,0FVF*F/F'F
dpF*FYFgrF;#Fdo"'+]7FepFfpF(#"'.E;Fhq,0FVF*FHF'FjqF*FYFgrFM#FeqFDF[rF\rF(#"(*e$
Q%FP,0FdpF*FjoF'FjqF*FepFfpF[p#Fcr"&]7$F[rF\rF(#"'d*o&F^r6",
I;C_hyb13f_depth_formulationw,6#>%)symbolicGF)6=%&_nameG%&_sizeG%#_AG%"iG%,skew
symmmatG%,quat2rotmatG%"KG%"RG%$noXG%"TG%(centersG%"QG%"PG%&alphaG%%betaG%#XQG%
#XPG%"EG%%tempG%%combG%#E1G%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FbuCI>6$8$8%6$
7#%"AG7#7$"#:F)@%/9$F)>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6
#&Fiw6#8'w,6$%"xG%"yGFbu6$%)operatorG%&arrowGFbu-&T'6#T%6#,&FbxF)*&,&9%F)F*F)F)
&&T#F_z6#F)F)F)FbuFbu6(FjuFiwF\vFdyFiuFhw6#F'6$7'Q!FbuF*"#R"#u"#O7'F^[lF*F_[l"#
XFa[l/Fdy;F)-%%nopsG6#Fhw>Fdx7#-Fgx6$-%'rndMatG6#F_yFd[l>8(w,6#%"vG6#%"XG6"FbuC
$>Fhw-%(convertG6$7%7%""!,$&Fbx6$""$F)F*&Fbx6$F'F)7%Fa]lF_]l,$&Fbx6$F)F)F*7%,$F
d]lF*Fh]lF_]lFjxOFhwFbuFbuFbu6#F)6%7'F^[lF*"#="#5Fa[l7'F^[lF*""("$+""#V7'F^[lF*
Fc^lF_x"#_>8)w,6#%%quatG6&F[wF`vFd\l%"sG6"FbuC'>Fdx-F[]l6$7%7#&Fbx6#F'7#&Fbx6#F
c]l7#&Fbx6#""%Fjx>Fdy&FbxFiz>Fhw-_I,TypesettingG6$F\yF]y%0delayDotProductG6$-&I
.LinearAlgebraG6$F\yF]y6#%*TransposeG6#FdxFdx>Fiw,(-Fc`l6$FdxFh`lF'*&FdyF)-FhzF
^alF)!"#*&,&*$FdyF'F)&FhwFi]lF*F)-&Fj`l6#%/IdentityMatrixGFj_lF)F)O*&FiwF),**$&
FdxFi]lF'F)*$&FdxFe]lF'F)*$&FdxFb]lF'F)FhalF)F*FbuFbu6$F]vFa\l6#F)6(F_^l7'F^[lF
*Fc^l"#hFe^l7'F^[lF*Fc^lF`^lFe^l7'F^[lF*Fc^lF`[lFe^l7'F^[lF*Fc^l"$["Fe^l7'F^[lF
*Fc^l"#cFg^l>8*-&Fj`l6#%/DiagonalMatrixG6#7%F(F(F)>8+-Fi^l6#7&F)%#r1G%#r2G%#r3G
>8,F^`l>8--Fjx6%Fc]lF)/%'symbolG%"tG>8.-Fjx6%Fc]lFcdl/Fidl%"cG>8/-Fjx6%Fc]lFcdl
/Fidl%"qG>80-Fjx6%Fc]lFcdl/Fidl%"pG>&Fhel6$;FbuFbuF)-F[]l6$7%7#F_]lFdfl7#F)Fjx>
&FbelF_fl-F[]l6$7%FeflFdflFeflFjx>&Fbel6$Fc]lF`flF)>&F\el6$F`fl;F)F^`lF_]l>81-F
ecl6#-%$mapG6$w,6#F\vFbu6$FjyF[zFbu-%$catG6$.%"aGFbxFbuFbuFbu6#F)6$7'F^[lF*"#Y"
#gFa[l7'F^[lF*Fdhl"#\Fa[l7#-Fgx6#;F)Fcdl>82-Fecl6#-Fggl6$w,FjglFbu6$FjyF[zFbu-F
]hl6$.%"bGFbxFbuFbuFbu6#F)6$7'F^[lF*Fc[l"#fFa[l7'F^[lF*Fc[l"#[Fa[lFhhl>&F]il6$F
'F'F)>&F]il6$Fc]lFc]lF)>&F]il6$F^`lF^`lF)>83-I".G6$F\yF]y6%-&Fj`l6#%.MatrixInve
rseG6#FcclFbelFcgl>84-&%"|irG6#%"+G6%-Fjjl6$F[dl,&-Fjjl6$FhelF]ilF)F\elF)%#~$G-
Fjjl6$Fedl-Fjx6%F)Fcdl/%%fillGF)>857">86Fh\m?&87-&I)combinatG6$F\yF]y6#%'choose
G6$FcdlF'%%trueGC$>Fj\m7$-F`y6#Fj\m/,&&Fc[m6$F`fl&F\]mFizF)&Fc[m6$F`fl&F\]mFg_l
F*,&&FhjlF]^mF)&FhjlF`^mF*>Fg\m7$-F`y6#Fg\m-%&numerG6#,&-I)simplifyG6$F\yF]y6#-
Fjjl6$-Fi`l6#-%$lhsG6#&Fj\m6#F*Fe_mF)-F^_m6#-Fjjl6$-Fi`l6#-%$rhsGFg_mF``mF*>88F
h\m?&F\]m-F^]m6$-%)numelemsGFi]mF'Fd]m>Fc`m7$-F`y6#Fc`m-Fj^m6#,&-F^_m6#-Fjjl6$-
Fi`l6#-Ff_m6#&Fj\m6#F^^m-Ff_m6#&Fj\m6#Fa^mF)-F^_m6#-Fjjl6$-Fi`l6#-Fa`mFgam-Fa`m
F[bmF*>Fg\m-Fggl6$w,6#%"eGFbu6$FjyF[zFbu-Fj^m6#-F^_m6#FbxFbuFbuFbu6#F)6$7'F^[lF
*"#7"#MFa[l7'F^[lF*FdcmF_xFa[l-%%subsG6$7#/F(-I%sqrtG6$F\yF]y6#F(Fg\m>Fc`m-Fggl
6$w,FjbmFbu6$FjyF[zFbuF]cmFbuFbuFbu6#F)6$7'F^[lF*"#8"#NFa[l7'F^[lF*Fhdm"#;Fa[l-
Fhcm6$FjcmFc`m>897$F[amFg^m>F_em-Fhcm6$7#-F`y6#-&Ff[m6#%"=G6%71&F\fl6$F)F'&F\fl
6$F)Fc]l&F\fl6$F)F^`l&F\flF`jl&F\fl6$F'Fc]l&F\fl6$F'F^`l&F\fl6$Fc]lF'&F\flFcjl&
F\fl6$Fc]lF^`l&FfelF^fm&FfelF`fm&FfelFbfm&FfelF`jl&FfelFefm&FfelFgfmF_\m-Fggl6$
w,FjglFbu6$FjyF[zFbu&F\xF`cmFbuFbuFbu6#F)6$7'F^[lF*"$i""$q"Fa[l7'F^[lF*F[hm"$l"
Fa[l7#-Fgx6#;F)F_xF_em>F_em-Fhcm6$7#-F`y6#-Fhem6%-Fggl6$w,FjglFbu6$FjyF[zFbuFgg
mFbuFbuFbu6#F)6$7'F^[lF*Fds"#HFa[l7'F^[lF*Fds"#DFa[lF_hmF_\m-F[]l6%&FdxFiz%%lis
tG/%'nestedG%&falseGF_em>F_em-Fggl6$w,FjbmFbu6$FjyF[zFbu-%'expandGF^cmFbuFbuFbu
6#F)6$7'F^[lF*"#9"#PFa[l7'F^[lF*Ffjm"#<Fa[l7#-F`y6#F_em>8:-Fggl6$FbjmF_em@$/Fbx
F_]lOF^[n>8;-%&minusG6$-%'indetsG6#F^[n-Fj[nF^al>6$8<8=-%,poly2matrixG6$F^[nFe[
n>8>-%$srtG6$F`\n-%%tdegG6#&Fe[nFbu6&7#-%/permuteColumnsG6%F_\nF`\nFe\nFe\nFhwF
iwFbuFbuFbu6#F_]l6P7'F^[lF*F[em""'Fa[l7'F^[lF*Fc]l"#LFe^l7'F^[lF*Fc]l""*Fc[l7'F
^[lF*Fc^l"#&*Fe^l7'F^[lF*Fc^l"#dFe^l7'F^[lF*Fc]lFa^lFe^lF^^n7'F^[lF*Fc]l"#ZFe^l
7'F^[lF*Fc]lFidmFe^l7'F^[lF*Fc]l"#6Fe^l7'F^[lF*Fc]l"#JFe^l7'F^[lF*Fc]lF_[lFe^lF
f]nFf]n7'F^[lF*Fc]lFg^lFe^lFg^n7'F^[lF*Fc]l"#AFe^lFf]n7'F^[lF*Fc]l"#zFe^l7'F^[l
F*Fc]l"#yFe^l7'F^[lF*Fc]lF`^lFe^lF^_nF^_n7'F^[lF*Fc]lFaclFe^l7'F^[lF*Fc]l"#sFe^
l7'F^[lF*Fc]lFi]nFe^l7'F^[lF*Fc]lFdcmFe^l7'F^[lF*Fc]l"")Fe_n7'F^[lF*Fc^l"$>"Fe^
l7'F^[lF*Fc^l"$o"Fe^lF^^nFd_n7'F^[lF*Fc^l"$!>Fe^l7'F^[lF*Fc]lF[jlFe^l7'F^[lF*Fc
]lF[clFe^l7'F^[lF*Fc]lFdsFe^l7'F^[lF*Fc]l"$&>Fe^l7'F^[lF*Fc]l"#*)Fe^l7'F^[lF*Fc
]lFghlFe^l7'F^[lF*Fc]l"#CFe^l7'F^[lF*Fc]lF_[lFc[l7'F^[lF*Fi^nFe^nFg^l7'F^[lF*Fc
]l"#QFe^l7'F^[lF*Fc]lFa[lFe^lFd^n7'F^[lF*Fc]l"#^Fe^nFbu
