M7R0
I;F_hyb13f_depth_formulation77,8*&%#a1G""#%"fG"""!""*(F&F)%#a2GF)F(F)F)*(F&F)%#
a3GF)F(F)F)*(F,F)F.F)F(F)F**&%#b1GF'F(F)F)*$F&F'F**&F&F)F,F)#"$z#"$+&*&F.F)F&F)
#!")"#D*&F.F)F,F)#"',y?"(+++"*&F1F)F(F)#!$^(F6F(#"(V&z6F>,8F%F*F+F)*(F&F)%#a4GF
)F(F)F)*(F,F)FFF)F(F)F*F0F)F2F*F3F4*&F&F)FFF)#"$r*"%+5*&FFF)F,F)#!&P\&"&+D'F?#!
%h6FKF(#!'"fW#"'++],6F+F*F-F)*&F,F'F(F)F)F/F*F3#!$z#F6F7F8*$F,F'#"&P$))"'++?F;F
<F?#!#M"$D"F(#!&@3'"'++D,6F+F*FEF)FVF)FGF*F3FWFHFIFYFZFLFMF?#"#pFKF(#!(4?">F>,6
F-F*FEF)F/F)FGF*F7#"")F:FHFIF;#!',y?F>FLFMF?#"$T$FKF(#!&\n'"&++%,8F%F*F-F)FEF)*
(F.F)FFF)F(F)F*F0F)F2F*F7F8FHFI*&F.F)FFF)#"'(=$>FTF?#!%L9FKF(#"&n=""'++5,6F+F*F
-F)F/F)*&F.F'F(F)F*F3FWF7F8F;Feo*$F.F'#!'h*3"F>F?FgnF(#"%fb"&++",6F+F*FEF)F/F)F
]pF*F3FWFHFIF;FeoF^pF_pF?F^oF(#!(t31"F>,6F-F*FEF)FgpF)F]pF*F7FcoFHFIFhp#"'h*3"F
>F^pF_pF?FgoF(#!(tnh"F>,6F+F*F-F)FGF)F]pF*F3FWF7F8FL#"&P\&FOF^pF_pF?FgnF(#"'j>:
F\o,6F+F*FEF)FGF)*&FFF'F(F)F*F3FWFHFIFLFgq*$FFF'#!((>:=F>F?F^oF(#"'(zn$F\o,6F-F
*FEF)F]pF)F\rF*F7FcoFHFIF^p#!'(=$>FTF]rF^rF?FgoF(#"'<z5"'+]7,4FVF*F/F)FGF)F]pF*
FY#!&P$))FfnF;FeoFLFgqF^pF_pF(#"&*H8"&Dc",4F/F*FGF)FgpF)F]pF*F;F<FLFgqFhpFbqF^p
F_pF(#"%ZKFO,4F/F*FGF)F]pF)F\rF*F;F<FLFgqF^pFcrF]rF^rF(#"(h?`#F>,4F%F*F+F'FVF*F
0F)F2F*F3#F5"$]#FYFirF?#!$B""$+"F(#"(FGU"F>,4F%F*F-F'FgpF*F0F)F2F*F7#!#;F:FhpFi
pF?#!$())F6F(#"(Vat"F>,4F%F*FEF'F\rF*F0F)F2F*FH#FJF6F]rF^rF?#!$t#FfsF(#"'.5\FT,
0FVF*F/F'FgpF*FYFirF;#FfoFTFhpFipF(#"&\*\FO,0FVF*FGF'F\rF*FYFirFL#Fhq"&]7$F]rF^
rF(#"((>$Q$F>,0FgpF*F]pF'F\rF*FhpFipF^p#FdrF\oF]rF^rF(#"(4,[#F>6",
I;C_hyb13f_depth_formulationw,6#>%)symbolicGF)6=%&_nameG%&_sizeG%#_AG%"iG%,skew
symmmatG%,quat2rotmatG%"KG%"RG%$noXG%"TG%(centersG%"QG%"PG%&alphaG%%betaG%#XQG%
#XPG%"EG%%tempG%%combG%#E1G%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FfuCI>6$8$8%6$
7#%"AG7#7$"#:F)@%/9$F)>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6
#&F]x6#8'w,6$%"xG%"yGFfu6$%)operatorG%&arrowGFfu-&T'6#T%6#,&FfxF)*&,&9%F)F*F)F)
&&T#Fcz6#F)F)F)FfuFfu6(F^vF]xF`vFhyF]vF\x6#F'6$7'Q!FfuF*"#R"#u"#O7'Fb[lF*Fc[l"#
XFe[l/Fhy;F)-%%nopsG6#F\x>Fhx7#-F[y6$-%'rndMatG6#FcyFh[l>8(w,6#%"vG6#%"XG6"FfuC
$>F\x-%(convertG6$7%7%""!,$&Ffx6$""$F)F*&Ffx6$F'F)7%Fe]lFc]l,$&Ffx6$F)F)F*7%,$F
h]lF*F\^lFc]lF^yOF\xFfuFfuFfu6#F)6%7'Fb[lF*"#="#5Fe[l7'Fb[lF*""(Fis"#V7'Fb[lF*F
g^lFcx"#_>8)w,6#%%quatG6&F_wFdvFh\l%"sG6"FfuC'>Fhx-F_]l6$7%7#&Ffx6#F'7#&Ffx6#Fg
]l7#&Ffx6#""%F^y>Fhy&FfxF][l>F\x-_I,TypesettingG6$F`yFay%0delayDotProductG6$-&I
.LinearAlgebraG6$F`yFay6#%*TransposeG6#FhxFhx>F]x,(-Ff`l6$FhxF[alF'*&FhyF)-F\[l
FaalF)!"#*&,&*$FhyF'F)&F\xF]^lF*F)-&F]al6#%/IdentityMatrixGF]`lF)F)O*&F]xF),**$
&FhxF]^lF'F)*$&FhxFi]lF'F)*$&FhxFf]lF'F)F[blF)F*FfuFfu6$FavFe\l6#F)6(Fc^l7'Fb[l
F*Fg^l"#hFh^l7'Fb[lF*Fg^lFd^lFh^l7'Fb[lF*Fg^lFd[lFh^l7'Fb[lF*Fg^l"$["Fh^l7'Fb[l
F*Fg^l"#cFj^l>8*-&F]al6#%/DiagonalMatrixG6#7%F(F(F)>8+-F\_l6#7&F)%#r1G%#r2G%#r3
G>8,Fa`l>8--F^y6%Fg]lF)/%'symbolG%"tG>8.-F^y6%Fg]lFfdl/F\el%"cG>8/-F^y6%Fg]lFfd
l/F\el%"qG>80-F^y6%Fg]lFfdl/F\el%"pG>&F[fl6$;FfuFfuF)-F_]l6$7%7#Fc]lFgfl7#F)F^y
>&FeelFbfl-F_]l6$7%FhflFgflFhflF^y>&Feel6$Fg]lFcflF)>&F_el6$Fcfl;F)Fa`lFc]l>81-
Fhcl6#-%$mapG6$w,6#F`vFfu6$F^zF_zFfu-%$catG6$.%"aGFfxFfuFfuFfu6#F)6$7'Fb[lF*"#Y
"#gFe[l7'Fb[lF*Fghl"#\Fe[l7#-F[y6#;F)Ffdl>82-Fhcl6#-Fjgl6$w,F]hlFfu6$F^zF_zFfu-
F`hl6$.%"bGFfxFfuFfuFfu6#F)6$7'Fb[lF*Fg[l"#fFe[l7'Fb[lF*Fg[l"#[Fe[lF[il>&F`il6$
F'F'F)>&F`il6$Fg]lFg]lF)>&F`il6$Fa`lFa`lF)>83-I".G6$F`yFay6%-&F]al6#%.MatrixInv
erseG6#FfclFeelFfgl>84-&%"|irG6#%"+G6%-F][m6$F^dl,&-F][m6$F[flF`ilF)F_elF)%#~$G
-F][m6$Fhdl-F^y6%F)Ffdl/%%fillGF)>857">86F[]m?&87-&I)combinatG6$F`yFay6#%'choos
eG6$FfdlF'%%trueGC$>F]]m7$-Fdy6#F]]m/,&&Ff[m6$Fcfl&F_]mF][lF)&Ff[m6$Fcfl&F_]mFj
_lF*,&&F[[mF`^mF)&F[[mFc^mF*>Fj\m7$-Fdy6#Fj\m-%&numerG6#,&-I)simplifyG6$F`yFay6
#-F][m6$-F\al6#-%$lhsG6#&F]]m6#F*Fh_mF)-Fa_m6#-F][m6$-F\al6#-%$rhsGFj_mFc`mF*>8
8F[]m?&F_]m-Fa]m6$-%)numelemsGF\^mF'Fg]m>Ff`m7$-Fdy6#Ff`m-F]_m6#,&-Fa_m6#-F][m6
$-F\al6#-Fi_m6#&F]]m6#Fa^m-Fi_m6#&F]]m6#Fd^mF)-Fa_m6#-F][m6$-F\al6#-Fd`mFjam-Fd
`mF^bmF*>Fj\m-Fjgl6$w,6#%"eGFfu6$F^zF_zFfu-F]_m6#-Fa_m6#FfxFfuFfuFfu6#F)6$7'Fb[
lF*"#7"#MFe[l7'Fb[lF*FgcmFcxFe[l-%%subsG6$7#/F(-I%sqrtG6$F`yFay6#F(Fj\m>Ff`m-Fj
gl6$w,F]cmFfu6$F^zF_zFfuF`cmFfuFfuFfu6#F)6$7'Fb[lF*"#8"#NFe[l7'Fb[lF*F[em"#;Fe[
l-F[dm6$F]dmFf`m>897$F^amFj^m>Fbem-F[dm6$7#-Fdy6#-&Fi[m6#%"=G6%71&F_fl6$F)F'&F_
fl6$F)Fg]l&F_fl6$F)Fa`l&F_flFcjl&F_fl6$F'Fg]l&F_fl6$F'Fa`l&F_fl6$Fg]lF'&F_flFfj
l&F_fl6$Fg]lFa`l&FielFafm&FielFcfm&FielFefm&FielFcjl&FielFhfm&FielFjfmFb\m-Fjgl
6$w,F]hlFfu6$F^zF_zFfu&F`xFccmFfuFfuFfu6#F)6$7'Fb[lF*"$i""$q"Fe[l7'Fb[lF*F^hm"$
l"Fe[l7#-F[y6#;F)FcxFbem>Fbem-F[dm6$7#-Fdy6#-F[fm6%-Fjgl6$w,F]hlFfu6$F^zF_zFfuF
jgmFfuFfuFfu6#F)6$7'Fb[lF*"#B"#HFe[l7'Fb[lF*FeimF:Fe[lFbhmFb\m-F_]l6%&FhxF][l%%
listG/%'nestedG%&falseGFbem>Fbem-Fjgl6$w,F]cmFfu6$F^zF_zFfu-%'expandGFacmFfuFfu
Ffu6#F)6$7'Fb[lF*"#9"#PFe[l7'Fb[lF*Fijm"#<Fe[l7#-Fdy6#Fbem>8:-Fjgl6$FejmFbem@$/
FfxFc]lOFa[n>8;-%&minusG6$-%'indetsG6#Fa[n-F]\nFaal>6$8<8=-%,poly2matrixG6$Fa[n
Fh[n>8>-%$srtG6$Fc\n-%%tdegG6#&Fh[nFfu6%7#-%/permuteColumnsG6%Fb\nFc\nFh\nF\xF]
xFfuFfuFfu6#Fc]l6P7'Fb[lF*F^em""'Fe[l7'Fb[lF*Fg]l"#LFh^l7'Fb[lF*Fg]l""*Fg[l7'Fb
[lF*Fg^l"#&*Fh^l7'Fb[lF*Fg^l"#dFh^l7'Fb[lF*Fg]lFe^lFh^lFa^n7'Fb[lF*Fg]l"#ZFh^l7
'Fb[lF*Fg]lF\emFh^l7'Fb[lF*Fg]l"#6Fh^l7'Fb[lF*Fg]l"#JFh^l7'Fb[lF*Fg]lFc[lFh^lFi
]nFi]n7'Fb[lF*Fg]lFj^lFh^lFj^n7'Fb[lF*Fg]l"#AFh^lFi]n7'Fb[lF*Fg]l"#zFh^l7'Fb[lF
*Fg]l"#yFh^l7'Fb[lF*Fg]lFd^lFh^lFa_nFa_n7'Fb[lF*Fg]lFdclFh^l7'Fb[lF*Fg]l"#sFh^l
7'Fb[lF*Fg]lF\^nFh^l7'Fb[lF*Fg]lFgcmFh^l7'Fb[lF*Fg]lFdoFdo7'Fb[lF*Fg^l"$>"Fh^l7
'Fb[lF*Fg^l"$o"Fh^lFa^nFg_n7'Fb[lF*Fg^l"$!>Fh^l7'Fb[lF*Fg]lF^jlFh^l7'Fb[lF*Fg]l
F^clFh^l7'Fb[lF*Fg]lFeimFh^l7'Fb[lF*Fg]l"$&>Fh^l7'Fb[lF*Fg]l"#*)Fh^l7'Fb[lF*Fg]
lFjhlFh^l7'Fb[lF*Fg]l"#CFh^l7'Fb[lF*Fg]lFc[lFg[l7'Fb[lF*F\_nFh^nFj^l7'Fb[lF*Fg]
l"#QFh^l7'Fb[lF*Fg]lFe[lFh^lFg^n7'Fb[lF*Fg]lFc^nFh^nFfu
