M7R0
I5F_inverse_kinematics7(,.*(%#c1G"""%#c4GF'%#s7GF'"$?"*(F&F'%#s4GF'%#c7GF'F**&F
&F'F(F'!#;*&F&F'F,F'"$O"F&!#W#!"("#]F',.*(%#s1GF'F(F'F)F'F**(F8F'F,F'F-F'F**&F8
F'F(F'F/*&F,F'F8F'F1F8F2#"$"R"$+&F',,*&F(F'F-F'!$?"*&F)F'F,F'F*F(!$O"F,F/#!$$f"
"%F'z)6$F&F8[[[[[_[[[[sF'][[[[[[[[[sF'!!""z)6$F(F,[[[[[_[[[[sF'][[[[[[[[[sF'!FI
z)6$F-F)[[[[[_[[[[sF'][[[[[[[[[sF'!FI6",
I5C_inverse_kinematicsw,6#>%)symbolicGF'6-%&_nameG%&_sizeG%#_AG%"iG%#xxG%$eqsG%
#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FNC,>6$8$8%6$7#%"XG7#7$""$F'@%/9$""!>8&7#-%$seqG
6$-%'rndMatG6#&&F_o6#8'FN/Ffp;F'-%%nopsG6#F^o>F[p7#-F^p6$-I'MatrixG6$%*protecte
dG%(_syslibG6$Fcpw,6$%"xG%"yGFN6$%)operatorG%&arrowGFN-&T'6#T%6#,&FhoF'*&,&9%F'
FIF'F'&&T#F`r6#F'F'F'FNFN6(FVF_oFXFfpFUF^o6#""#6$7'Q!FNFI"#P"#s"#O7'F`sFIFas"#V
FcsFgp>8(-%(convertG6$&F[pFjrI'VectorG6$FcqFdq>8)7(z/6(F&F(F-F,F)&FgsFjr[[][[[[
[[\[][wF*[[[[_[c[[[[][wF*[[[[[[[[[\[][sF/[[[[_[[[[[[][sF1[[[[[[[[[[[][oF2\[[[[[
[[[[[[[oF'z/6(F(F-F8F,F)&Fgs6#F]s[[][[[c[[[[][wF*[[[[_[c[[\[[[wF*[[[[[[c[[[[][s
F/[[[[_[c[[[[[[sF1[[[[[[c[[[[[[oF2\[[[[[[[[[[[[oF'z/6'F(F-F,F)&Fgs6#Feo[[[[[[[_
[[\[sFA[[_[[\[[[[[[sF*[[[[[[[[[[\[oFC[[[[[\[[[[[[oF/\[[[[[[[[[[[oF'!!$["z)FH[[[
[[_[[[[sF'][[[[[[[[[sF'!FIz)FK[[[[[_[[[[sF'][[[[[[[[[sF'!FIz)FM[[[[[_[[[[sF'][[
[[[[[[[sF'!FI>8*-%$mapG6$%'expandGF_t@$FgoOFau>8+-%&minusG6$-%'indetsG6#Fau-F^v
6#F[p>6$8,8--%,poly2matrixG6$FauFiu>8.-%$srtG6$Fev-%%tdegG6#&FiuFN6&7#-%/permut
eColumnsG6%FdvFevFjvFjvF^oF_oFNFNFN6#Fio607'F`sFI"#;""'Fcs7'F`sFIFeo"#KFes7'F`s
FIFeo""*"#X7'F`sFI""("#bFes7'F`sFIFbx"#$*Fes7'F`sFIFeo"#IFes7'F`sFIFeo"#SFes7'F
`sFIFeo"#CFes7'F`sFIFeo"#RF`x7'F`sFI"#A"#J"#_7'F`sFIFeo"#QFes7'F`sFIFeoFcsFes7'
F`sFIFeoF`yFes7'F`sFIFeo"#^F`yFN
