M7R0
I&F_IOD70,fp%$x11G#"**G>K")",+++]7$%$x12G#"*FN.r'F(%$x22G#"*hzq`&"-++++]7%$x14G
#!+*4f5*QF(%$x24G#!+dVt5K",++++D'%$x44G#",4Qy<'=F/*&F)"""F%F;#!*FN.r'F6*&F)F;F,
F;F<*&F0F;F%F;#"+*4f5*QF6*&%$x13GF;%$x23GF;F<*&F%F;FDF;#!)"pi?""*++D"y*&FCF;F)F
;#")"pi?"FH*&F)F;F3F;#"(Z<(G")]il(**&F0F;F)F;#!($zs<FO*&FCF;%$x34GF;F@*&F,F;F3F
;#"+dVt5KF/*&F%F;FTF;#!*ZZ^>""+++D1R*&FDF;FTF;FV*&F0F;FCF;#"*ZZ^>"Fen*&FDF;F3F;
#"*f>vf""+++]7y*&F,F;FTF;#!*f>vf"F]o*&F,F;F%F;#!+<&R9m#"-+++++D*&F)F;FDF;#!(8O&
**"+++]i:*&F,F;FCF;#"(8O&**Fho*&F3F;F%F;#"+(R4*zaF/*&F%F;F7F;#!,tmF@T"Fdo*&F)F;
FTF;#!*ZA#e[F]o*&F)F;F7F;#")*p_%G"*]7G)[*&F3F;FCF;#!)teuB"*+Dcw**&FCF;F7F;#!*x$
\=dF]o*$F0""##!)"[kv"F\q*&F,F;F0F;#"+>59`?F6*&FDF;F0F;#"*J#*yv'F]o*&F0F;F3F;#!)
*p_%GFhp*&F0F;FTF;#"*x$\=dF]o*&F,F;F7F;#!+L/h=oFdo*&FDF;F7F;#!*$oQj#*F]o*$F3Faq
#!)@04YF\q*&F3F;FTF;#"*$oQj#*F]o*$FTFaq#!,4Qy<'=Fdo*$F%Faq#!**G>K")F6*$FCFaqF`s
*$F,Faq#!*hzq`&Fdo*$FDFaqFds*$F)Faq#!'H*y"")+D1R,fpF%#"-"o!)H>^%"-+++++]F)#"-P=
GnrAF/F,#"-\_]uV6F/F0#!+F2PWcF6F3#!+zd$=%GF(F7#")4/hqF(F:#!-P=GnrAFdoF>FitF?#"+
F2PWcF/FBFitFE#",P0QG@'FdoFI#!,P0QG@'FdoFL#!,^GFqZ#F/FP#",z(R#[+&FdoFSF[uFU#"+z
d$=%GF6FX#!-F]vjMOF^tFfnFeuFgn#"-F]vjMOF^tFjn#",^FXq0*F/F^o#!,^FXq0*F/Fao#!-"["
=rW()".++++++"Feo#",\^[!GJF/Fio#!,\^[!GJF/F\p#!,jm*3oQFdoF_p#",8!QDLe"-+++++?Fb
p#!-@&4GW"=F/Fep#"-@6<6\9FdoFip#",>VA@s$",+++++&F]q#!+4&))oa%F/F`q#!-4mX#z#HFav
Fdq#",*y@t?:F6Fgq#"-Zu\zn<FdoFjq#!-@6<6\9FdoF]r#"+4&))oa%F/F`r#",8w9Q9(FdoFcr#!
+@AQ]AF6Ffr#!,\#*e?<(FdoFir#"+@AQ]AF6F\s#!)4/hqF6F_s#!-"o!)H>^%FavFbsFhxFcs#!-
\_]uV6FdoFfsFjxFgs#!+\]&\b)Fdo,fpF%#",@Tg&[7",+++++#F)#"+@p"\C&",++++D"F,#"+@(p
K?#F(F0#"*@E#>O"*+++D'F3#"*@a._"FHF7#")@6\5")+]7yF:#!+@p"\C&",++++]#F>F_zF?#!*@
E#>O"++++]7FBF_zFE#!,$pfr:M"-+++++5FI#",$pfr:MFgzFL#"+V^,n@F6FP#!,"G"za!=FawFSF
bzFU#!*@a._"FhoFX#!+d0k*f'",+++++"FfnF^[lFgn#"+d0k*f'Fb[lFjn#"*r0vK$",+++Dc"F^o
#!*r0vK$Fg[lFao#!,(GU<(e"F6Feo#!,$4U'[V"F/Fio#",$4U'[V"F/F\p#",4yl*=8FawF_p#"*
\-o7""*++++%Fbp#!*"\fbWFhoFep#"*2wp=%"++++]iFip#"+V&)f_ZFdyF]q#"*d]I">FiyF`q#!+
pzV)[$Fb[lFdq#!,$>YJE?F6Fgq#!*BXiP#"+++++DFjq#!*2wp=%Fi\lF]r#!*d]I">FiyF`r#!*z"
e))**Fg[lFcr#")r7'H#FHFfr#!)@RD]Fg[lFir#!)r7'H#FHF\s#!)@6\5"*++Dc"F_s#!,@Tg&[7"
,+++++%FbsFd^lFcs#!+@(pK?#F6FfsFg^lFgs#!,p>aWM*Fav,fpF%#"+*3X%HAF(F)#!+8-N#>%F]
oF,#"+@l[$)yF]oF0#"+jWk(y#FdyF3#!+rP,U_Fi\lF7#"+@Ng&[$FayF:#"+8-N#>%Fg[lF>Fh_lF
?#!+jWk(y#FazFBFh_lFE#!*2*)*zoFi\lFI#"*2*)*zoFi\lFL#!+p*fof'FazFP#")fAi5FazFSFj
_lFU#"+rP,U_FdyFX#")$>@W$F/FfnFd`lFgn#!)$>@W$F/Fjn#",rIC)>SF6F^o#!,rIC)>SF6Fao#
!+P])Q6(Fg[lFeo#"+>Xu$H""++++DJFio#!+>Xu$H"FbalF\p#",$G0MZ5FazF_p#!,tXW#*3"F/Fb
p#",,I_Z7#F/Fep#"*Jn/I$F^tFip#",(3')ej@F/F]q#!)J%RI%FgzF`q#!'T9`FavFdq#"+`xg/>F
dyFgq#!*nK0q'"++]7`>Fjq#!*Jn/I$F^tF]r#")J%RI%FgzF`r#"+J@`ktF6Fcr#!,@yDHn#FgzFfr
#!-@@gs\?FavFir#",@yDHn#FgzF\s#!+@Ng&[$Ff^lF_s#!+*3X%HAF6FbsFfclFcs#!+@l[$)yFg[
lFfsFhclFgs#!*TSJ7#Fd]l,fpF%#",\eVXF$F^tF)#!,`i_yC(FdoF,#"-T)zMUg"F^tF0#",>fX!f
YF/F3#!-V++BJ5F/F7#",*3c#*GmF/F:#",`i_yC(F^tF>FidlF?#!,>fX!fYFdoFBFidlFE#"-(f$p
jx5F^tFI#!-(f$pjx5F^tFL#",`fLs3*FdoFP#",\`ZGO$F(FSF[elFU#"-V++BJ5FdoFX#!,L3Y=-"
F(FfnFeelFgn#",L3Y=-"F(Fjn#",(p@z6hFdoF^o#!,(p@z6hFdoFao#"-^dMw9;FavFeo#!-41VB&
Q#F^tFio#"-41VB&Q#F^tF\p#!-\F![!f;FdoF_p#",$oA"ev#FawFbp#"-4$[Db3#FdoFep#!+<Tx;
')Fg[lFip#!,BkN`o'FawF]q#",BS!*QX"Fg[lF`q#!+hzu)=$FenFdq#!+Bh&y9#FenFgq#",.p6dG
'F/Fjq#"+<Tx;')Fg[lF]r#!,BS!*QX"Fg[lF`r#!+6e6v5Fi\lFcr#!,J>m(GRF/Ffr#!,\Oi%GBFd
oFir#",J>m(GRF/F\s#!,*3c#*GmFdoF_s#!,\eVXF$FavFbsFehlFcs#!-T)zMUg"FavFfsFghlFgs
#!-T9EXYNFavz/6&F%FCF,FD[[[[[[[[[][[mF;[[[[[[][[[[[mF;[[[][[[[[[[[m!""][[[[[[[[
[[[mF]il[[[[[[[[[\[[lF]il[[[\[[[[[[[[lF;z+6'F%F)FCF,FD[[[[[[[_[[\[sF;[[_[[[[_[[
[[sF;\[[[[\[[[[[[sF;[[[[[[[_[[[[oF]ilz+6%F)F,FD[[[[[[[[][[[mF;[[[[][[[[[[[mF;][
[[[[[[[[[[mF;[[[[\[[[[[[[lF]ilz)6&F%F)FCFD\[[[[[[[[\[[mF]il[[[\[[\[[[[[mF;\[[[[
[[[[[[[lF;z+6(F%F)FCF0F3FT[[[[_[[[[[[][sF;[[][[[[[[\[[[sF;\[[[[[c[[[[[[sF;[[[[_
[[[[[[[[oF]ilz+6(F)F0F,FDF3FT[[[[[[[[[\[][sF;[[][[[c[[[[[[sF;\[[[_[[[[[[[[sF;[[
][[[[[[[[[[oF]ilz-6)F%FCF0F,FDF3FT\[[[[[[[[[[[\[mF]il[[[[[[[[\[\[[[mF;\[[[[[\[[
[[[[[mF]il[[\[\[[[[[[[[[mF;\[[[[[[[[[[[[[lF;z/6%F%F,FD[[[[\[[[\[[[mF;[[[[][[[[[
[[mF;][[[[[[[[[[[mF;[[[[[[[[\[[[lF]il[[[[\[[[[[[[l!"#!F;z)6&F)FCF,FD\[[[[[[[[\[
[mF]il[[[\[[\[[[[[mF;[[[[[[\[[[[[lF]il6",
I&C_IODw,6#>%)symbolicGF;6-%&_nameG%&_sizeG%#_AG%"iG%#Q1G%$eqsG%#_FG%&_varsG%$_
C0G%$_V0G%#_VG6"F_jlC,>6$8$8%6$7'%#A1G%#A2G%#A3G%#A4G%#A5G7#-%"$G6$7$""%Faq""&@
%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Ff[m6#8'F_jl/Fe]m;F;-%%nopsG6#Fe[m>Fj\m7#-F]
]m6$-I'MatrixG6$%*protectedG%(_syslibG6$Fb]mw,6$%"xG%"yGF_jl6$%)operatorG%&arro
wGF_jl-&T'6#T%6#,&Fg\mF;*&,&9%F;F]ilF;F;&&T#F__m6#F;F;F;F_jlF_jl6(FgjlFf[mFijlF
e]mFfjlFe[m6#Faq6$7'Q!F_jlF]il"#P"#s"#O7'F^`mF]ilF_`m"#VFa`mFf]m>8(-I$<,>GFc^m6
&-I$<|gr>GFc^m6&F%F)FCF0-Fj`m6&F)F,FDF3-Fj`m6&FCFD,(FaqF;F%F]ilF,F]ilFT-Fj`m6&F
0F3FTF7>8)7,-F]]m6$-&I.LinearAlgebraG6$Fb^mFc^m6#%,DeterminantG6#-I".G6$Fb^mFc^
m6%)&Fj\mFd]m%#%TGFe`mFdbm/Fe]m;F;Fd\mF[ilF^ilF`ilFbilFdilFfilFhilFjilF]jl>8*-%
$mapG6$%'expandGFdam@$Ff\mOFibm>8+-%&minusG6$-%'indetsG6#Fibm-Ffcm6#Fj\m>6$8,8-
-%,poly2matrixG6$FibmFacm>8.-%$srtG6$F]dm-%%tdegG6#&FacmF_jl6%7#-%/permuteColum
nsG6%F\dmF]dmFbdmFe[mFf[mF_jlF_jlF_jl6#Fh\m607'F^`mF]il"#;""'Fa`m7'F^`mF]il""$"
#hFc`m7'F^`mF]ilFeem""*"#X7'F^`mF]il""("#bFc`m7'F^`mF]ilF[fm"#$*Fc`m7'F^`mF]ilF
eem"##)Fc`m7'F^`mF]ilFeem"#BFc`m7'F^`mF]ilFeem"#CFc`m7'F^`mF]ilFeem"#RFiem7'F^`
mF]il"#A"#J"#_7'F^`mF]ilFeem"#QFc`m7'F^`mF]ilFeemFa`mFc`m7'F^`mF]ilFeemFifmFc`m
7'F^`mF]ilFeem"#ZFifmF_jl
