M7R0
I&F_IOD70,fp%$x11G#"+@*e*zH"-++++]7%$x12G#!+B4;'o#",++++D'%$x22G#"+\)G8U#F(%$x1
4G#"+p#e*4U",+++]7$%$x24G#!+ZI*[z$F3%$x44G#"+T'[w%fF3*&F)"""F%F;#"+B4;'o#F(*&F)
F;F-F;F<*&F0F;F%F;#!+p#e*4UF,*&%$x13GF;%$x23GF;F<*&F%F;FDF;#"*<NG]"F,*&FCF;F)F;
#!*<NG]"F,*&F)F;F4F;#"*pYUG#F,*&F0F;F)F;#"*r@#4IF,*&FCF;%$x34GF;F@*&F-F;F4F;#"+
ZI*[z$F,*&F%F;FRF;#!+B)fp'fF(*&FDF;FRF;FT*&F0F;FCF;#"+B)fp'fF(*&FDF;F4F;#"+6C&G
3%F(*&F-F;FRF;#!+6C&G3%F(*&F-F;F%F;#!+ne[&o#F(*&F)F;FDF;#!*roYN"F,*&F-F;FCF;#"*
roYN"F,*&F4F;F%F;#"*>F\t)",+++Dc"*&F%F;F7F;#!+j[^oB",+++++&*&F)F;FRF;#"+B8/a\F,
*&F)F;F7F;#!+6(H&p!*F(*&F4F;FCF;#!+,g#zA'F(*&FCF;F7F;#"+Z^')H%)F,*$F0""##!,\--[
>""-+++++D*&F-F;F0F;#!+p9>>AF3*&FDF;F0F;#!*H8.O(",++++]#*&F0F;F4F;#"+6(H&p!*F(*
&F0F;FRF;#!+Z^')H%)F,*&F-F;F7F;#!+n^@"Q$F]p*&FDF;F7F;#!+L2'*)R'F,*$F4F[q#!+H(=X
)oF^q*&F4F;FRF;#"+L2'*)R'F,*$FRF[q#!+T'[w%fF,*$F%F[q#!+@*e*zHF^q*$FCF[qF\s*$F-F
[q#!+\)G8U#F^q*$FDF[qF`s*$F)F[q#!(4!zvF,,fpF%#"*,#p_a"+++++]F)#!*hs5V#"++++]7F-
#"*@*)Q3"F\tF0#!+^b'fo""+++++DF4#"*6Yo^(F\tF7#"+,W)H@&FisF:#"*hs5V#FatF>FftF?#"
+^b'fo"FisFBFftFE#")h\ks"++++]iFH#!)h\ksF\uFK#"*^A%=_FioFN#"+p(3i."F3FQFhtFS#!*
6Yo^(FatFV#!+HxsxxFeqFYFcuFZ#"+HxsxxFeqFgn#"+^:NY<F\uFjn#!+^:NY<F\uF]o#!,*)*odJ
CF^qF`o#!)@')QK"++++DJFco#")@')QKFavFfo#!,8G`k3#F,Fjo#!+BP(GU#F3F^p#"*R^h%="*++
]7$Fap#!,RX+re&F,Fdp#!+Z3X=I",++++D"Fgp#!,zoj[S#FeqFjp#!-T-iT46F^qF_q#",n2Suz$F
(Fbq#!+8Z:mVF_wFfq#",RX+re&F,Fiq#",zoj[S#FeqF\r#!,,xVwx"F^qF_r#",Tz16@"F_wFbr#!
,"3Vq8GF,Fer#!,Tz16@"F_wFhr#!+,W)H@&",+++++"F[s#!*,#p_aFfxF^sFgxF_s#!*@*)Q3"Fat
FbsFixFcs#!(@$y'*Fio,fpF%#"+*od1h"F3F)#!+4zCY#)F3F-#",HP:>A%F(F0#"*">t0XFavF4#!
+r`%oI#F\uF7#"*Hb/E"F\tF:#"+4zCY#)F,F>FjyF?#!*">t0XF\uFBFjyFE#!*Pv&*>""*++D"yFH
#"*Pv&*>"F`zFK#!*BoS[#FjvFN#!(jhY*"*++Dc"FQF\zFS#"+r`%oI#F_wFV#!*675F"F\uFYFhzF
Z#"*675F"F\uFgn#",6YCwq"FeqFjn#!,6YCwq"FeqF]o#"+$)zJ.<F]pF`o#"*(zeTh"+++]i:Fco#
!*(zeThFf[lFfo#"+6%QT1$F_wFjo#!("R+H")++]iF^p#"+6J.$*>F\uFap#!*p)*>j#FatFdp#"+
\s'Q.#F_wFgp#")4fbNF\tFjp#!)*))H+"FatF_q#"+pKc<XF\uFbq#!+rM$*>gF_wFfq#"*p)*>j#F
atFiq#!)4fbNF\tF\r#"+L8f-kFfxF_r#!**GUI$*FatFbr#!+\Mx1pFfxFer#"**GUI$*FatFhr#!*
Hb/E"FatF[s#!+*od1h"F,F^sFj]lF_s#!,HP:>A%F^qFbsF\^lFcs#!(@T$*)")+D1R,fpF%#"+4qs
?jF3F)#"+**p$y+$FatF-#"+*)eLJ9"*++++)F0#",Hkv0p"F,F4#"+>E#\/)FfxF7#",\a/<_%"-++
+++]F:#!+**p$y+$FisF>F`_lF?#!,Hkv0p"F(FBF`_lFE#"*d;n&H"++]7`>FH#!*d;n&HFf_lFK#"
+(z)>*4""+++D1RFN#!*F7F<""*+Dcw*FQFb_lFS#!+>E#\/)",+++++#FV#"+*4op]#FioFYF_`lFZ
#!+*4op]#FioFgn#!,z\.#=6FfxFjn#",z\.#=6FfxF]o#!-8l%\1R*".++++++"F`o#"*F4qS"FjvF
co#!*F4qS"FjvFfo#!-^s>!3T"F__lFjo#",Z-3?%=F\alF^p#",dCUhm#F3Fap#"+z!))*>$*F3Fdp
#!,hUD^h$F,Fgp#!+><F0nF,Fjp#!**3IV**FioF_q#!,Lz6!3_F(Fbq#!,`1frr"F,Ffq#!+z!))*>
$*F3Fiq#"+><F0nF,F\r#"-FC!H@/$F\alF_r#!,4IS\G'F^qFbr#!,pp[dt)F^qFer#",4IS\G'F^q
Fhr#!,\a/<_%F\alF[s#!+4qs?jF,F^sFaclF_s#!+*)eLJ9"+++++;FbsFcclFcs#!)h4$Q""*D19W
#,fpF%#")Ht@%)"+++]7yF)#"),**pr"*]7G)[F-#"*Qf3A"FhclF0#!*Vhrx$F\dlF4#!*n_d@$F^`
lF7#"+"GjSp"F3F:#!),**prF^`lF>FhdlF?#"*Vhrx$FioFBFhdlFE#!+P1_4\F3FH#"+P1_4\F3FK
#",([*e)3CF^qFN#"+(G#=(R(FfxFQFjdlFS#"*n_d@$Ff_lFV#"*z.*o7FatFYFdelFZ#!*z.*o7Fa
tFgn#"*^fz^$F\dlFjn#!*^fz^$F\dlF]o#"-TG>\BAF^qF`o#!+`l!)zTF[`lFco#"+`l!)zTF[`lF
fo#!-**H#zwV"F^qFjo#",HJ>'Q#*F\alF^p#",@u&G>@F,Fap#!*H$)eA'Fa`lFdp#!,zJNDO%F,Fg
p#"*$\0"p&FisFjp#!*Hf=">FeclF_q#!,*>J^/=F^qFbq#",zyC;7"F3Ffq#"*H$)eA'Fa`lFiq#!*
$\0"p&FisF\r#!,n<ex]#F\alF_r#!+$HmK&=F(Fbr#!+H2VF?F\alFer#"+$HmK&=F(Fhr#!+"GjSp
"F,F[s#!)Ht@%)FioF^sFdhlF_s#!)pH/hFhclFbsFfhlFcs#!-h.n/iGF^qz/6&F%FCF-FD[[[[[[[
[[][[mF;[[[[[[][[[[[mF;[[[][[[[[[[[m!""][[[[[[[[[[[mF\il[[[[[[[[[\[[lF\il[[[\[[
[[[[[[lF;z+6'F%F)FCF-FD[[[[[[[_[[\[sF;[[_[[[[_[[[[sF;\[[[[\[[[[[[sF;[[[[[[[_[[[
[oF\ilz+6%F)F-FD[[[[[[[[][[[mF;[[[[][[[[[[[mF;][[[[[[[[[[[mF;[[[[\[[[[[[[lF\ilz
)6&F%F)FCFD\[[[[[[[[\[[mF\il[[[\[[\[[[[[mF;\[[[[[[[[[[[lF;z+6(F%F)FCF0F4FR[[[[_
[[[[[[][sF;[[][[[[[[\[[[sF;\[[[[[c[[[[[[sF;[[[[_[[[[[[[[oF\ilz+6(F)F0F-FDF4FR[[
[[[[[[[\[][sF;[[][[[c[[[[[[sF;\[[[_[[[[[[[[sF;[[][[[[[[[[[[oF\ilz-6)F%FCF0F-FDF
4FR\[[[[[[[[[[[\[mF\il[[[[[[[[\[\[[[mF;\[[[[[\[[[[[[[mF\il[[\[\[[[[[[[[[mF;\[[[
[[[[[[[[[[lF;z/6%F%F-FD[[[[\[[[\[[[mF;[[[[][[[[[[[mF;][[[[[[[[[[[mF;[[[[[[[[\[[
[lF\il[[[[\[[[[[[[l!"#!F;z)6&F)FCF-FD\[[[[[[[[\[[mF\il[[[\[[\[[[[[mF;[[[[[[\[[[
[[lF\il6",
I&C_IODw,6#>%)symbolicGF;6-%&_nameG%&_sizeG%#_AG%"iG%#Q1G%$eqsG%#_FG%&_varsG%$_
C0G%$_V0G%#_VG6"F^jlC,>6$8$8%6$7'%#A1G%#A2G%#A3G%#A4G%#A5G7#-%"$G6$7$""%F[q""&@
%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fe[m6#8'F^jl/Fd]m;F;-%%nopsG6#Fd[m>Fi\m7#-F
\]m6$-I'MatrixG6$%*protectedG%(_syslibG6$Fa]mw,6$%"xG%"yGF^jl6$%)operatorG%&arr
owGF^jl-&T'6#T%6#,&Ff\mF;*&,&9%F;F\ilF;F;&&T#F^_m6#F;F;F;F^jlF^jl6(FfjlFe[mFhjl
Fd]mFejlFd[m6#F[q6$7'Q!F^jlF\il"#P"#s"#O7'F]`mF\ilF^`m"#VF``mFe]m>8(-I$<,>GFb^m
6&-I$<|gr>GFb^m6&F%F)FCF0-Fi`m6&F)F-FDF4-Fi`m6&FCFD,(F[qF;F%F\ilF-F\ilFR-Fi`m6&
F0F4FRF7>8)7,-F\]m6$-&I.LinearAlgebraG6$Fa^mFb^m6#%,DeterminantG6#-I".G6$Fa^mFb
^m6%)&Fi\mFc]m%#%TGFd`mFcbm/Fd]m;F;Fc\mFjhlF]ilF_ilFailFcilFeilFgilFiilF\jl>8*-
%$mapG6$%'expandGFcam@$Fe\mOFhbm>8+-%&minusG6$-%'indetsG6#Fhbm-Fecm6#Fi\m>6$8,8
--%,poly2matrixG6$FhbmF`cm>8.-%$srtG6$F\dm-%%tdegG6#&F`cmF^jl6&7#-%/permuteColu
mnsG6%F[dmF\dmFadmFadmFd[mFe[mF^jlF^jlF^jl6#Fg\m607'F]`mF\il"#;""'F``m7'F]`mF\i
l""$"#hFb`m7'F]`mF\ilFdem""*"#X7'F]`mF\il""("#bFb`m7'F]`mF\ilFjem"#$*Fb`m7'F]`m
F\ilFdem"##)Fb`m7'F]`mF\ilFdem"#BFb`m7'F]`mF\ilFdem"#CFb`m7'F]`mF\ilFdem"#RFhem
7'F]`mF\il"#A"#J"#_7'F]`mF\ilFdem"#QFb`m7'F]`mF\ilFdemF``mFb`m7'F]`mF\ilFdemFhf
mFb`m7'F]`mF\ilFdem"#^FhfmF^jl
