M7R0
I2F_l2_3view_triang7*,,%#x1G""##!#P"$+""""*&%#x7GF*%#x3GF*#!"("#]*&F,F*%#x4GF*#
"$"R"$+&F,#!""""%,,%#x2GF&#"$*oF5F*F+#"$8*"%+5F1#"#")"$]#F,#!$*>"$+#,2F-F&#!$(H
F5F**&F,F*F%F*F.*&F,F*F:F*F=F,#!#BF5*&%#x8GF*%#x5GF*#"$t&F?*&FNF*%#x6GF*#!$,#FB
FN#"$`"F5,2F2F&#!#(*FBF*FIF3FJF@F,#!$,(F?FM#""$"")FR#!$B""$D"FN#!$d#F?,,FOF&#!$
.#F5F**&FNF*F-F*FP*&FNF*F2F*FgnFN#"$">FB,,FSF&#!$4$FBF*FboFTFcoFjnFN#"$"))F?,4*
&F-F*F%F*F.*&F-F*F:F*F=F-FK*&F2F*F%F*F3*&F2F*F:F*F@F2FenF%F6F:FC#!$,*F?F*,4*&FO
F*F-F*FP*&FOF*F2F*FgnFOFdo*&FSF*F-F*FT*&FSF*F2F*FjnFSFioF-FVF2F]o#!$>"F5F*6",
I2C_l2_3view_triangt+6#>%)symbolicGF*6,%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%
#V0G%"VG%#uhG%"fG6"FipC->6$8$8%6$7%%$E12G%$E23G%"uG7%7$FhnFhnFfr7$F&Fhn@%/9$F*>
8&-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F_r6#%"iGf*6$%"xG%"yGFi
p6$%)operatorG%&arrowGFip-&T%Fjs6#,&FjrF**&,&9%F*F7F*F*&&T#Fjs6#F*F*F*FipFip6&F
aqF_rF`qF^r/F[t;F*-%%nopsG6#F^r>F\s-F^s6$-%'rndMatG6#FfsF`u>8,-I$<,>GFds6%-I$<|
gr>GFds6%F%F-FO-Fav6%F:F2FS-Fav6%F*F*F*>8-,(-%$addG6$-F[w6$*$,&&F\v6$F[t%"jGF*&
&F\s6#FhnFbwF7F&/F[t;F*F&/Fcw;F*FhnF*-I".G6$FcsFds6%*&F,F*)&F\v6$;FipFipF*%#%TG
F*&F\sF^u&F\v6$FcxF&F*-F\x6%*&FNF*)FfxFdxF*&F\s6#F&&F\v6$FcxFhnF*>8'7#-F^s6$-%%
diffG6$Fhv(F^tF[t/F[t;F*Fin>Fay-%$mapG6$%'expandGFay@$0FjrF*OFay>8(-%&minusG6$-
%'indetsG6#Fay-Fiz6#7#F\s>6$8)8*-%,poly2matrixG6%Fay-FcuFjzFdz>8+-%$srtG6$Fa[l-
%%tdegG6#-Fgs6#Fdz6%7$%#cfG-%/permuteColumnsG6%F`[lFa[lFg[lF^rF_rFipFipFip6#""!
Fip
