M7R0
I2F_l2_3view_triang7*,,%#x1G""##"$Z&"$+&"""*&%#x7GF*%#x3GF*#""'"$D"*&F,F*%#x4GF
*#!$*R"%+5F,#"$d""$]#,,%#x2GF&#!#JF8F*F+#"$^)F5F1#!$J"F8F,#"$@%F5,2F-F&#!""""&F
**&F,F*F%F*F.*&F,F*F:F*F=F,#"#tF5*&%#x8GF*%#x5GF*#!$$**F5*&FLF*%#x6GF*#!$R'F5FL
#"$(>F5,2F2F&#!$F'F)F*FGF3FHF?F,#!$6$F)FK#!#hF5FP#!#wF0FL#"$<#F8,,FMF&#!$H""$+"
F**&FLF*F-F*FN*&FLF*F2F*FenFL#"#@F^o,,FQF&#"$4#F8F*F_oFRF`oFgnFL#"$z'F5,4*&F-F*
F%F*F.*&F-F*F:F*F=F-FI*&F2F*F%F*F3*&F2F*F:F*F?F2FYF%F6F:FA#"#**F)F*,4*&FMF*F-F*
FN*&FMF*F2F*FenFMFao*&FQF*F-F*FR*&FQF*F2F*FgnFQFfoF-FTF2Fin#!#8F0F*6",
I2C_l2_3view_triangw,6#>%)symbolicGF*6/%&_nameG%&_sizeG%#_AG%"iG%#uhG%"fG%"jG%$
eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FfpC->6$8$8%6$7%%$E12G%$E23G%"uG7%7$""$FgrF
fr7$F&Fgr@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F_r6#8'Ffp/Fis;F*-%%nopsG6#F^r>F^s
7#-Fas6$-I'MatrixG6$%*protectedG%(_syslibG6$Ffsw,6$%"xG%"yGFfp6$%)operatorG%&ar
rowGFfp-&T'6#T%6#,&F[sF**&,&9%F*FEF*F*&&T#Fcu6#F*F*F*FfpFfp6(F^qF_rF`qFisF]qF^r
6#F&6$7'Q!FfpFE"#P"#s"#O7'FbvFEFcv"#VFevFjs>8(-I$<,>GFgt6%-I$<|gr>GFgt6%F%F-FM-
F^w6%F:F2FQ-F^w6%F*F*F*>8),(-%$addG6$-Fhw6$*$,&&Fiv6$Fis8*F*&&F^s6#FgrF_xFEF&/F
is;F*F&/F`x;F*FgrF*-I".G6$FftFgt6%*&F,F*)&Fiv6$;FfpFfpF*%#%TGF*&F^sF]v&Fiv6$F`y
F&F*-Fix6%*&FLF*)FcyFayF*&F^s6#F&&Fiv6$F`yFgrF*>8+7#-Fas6$-%%diffG6$Few(F[uFis/
Fis;F*"")>8,-%$mapG6$%'expandGF^z@$FjrOFjz>8--%&minusG6$-%'indetsG6#Fjz-Fg[l6#F
^s>6$8.8/-%,poly2matrixG6$FjzFb[l>80-%$srtG6$F^\l-%%tdegG6#&Fb[lFfp6%7#-%/permu
teColumnsG6%F]\lF^\lFc\lF^rF_rFfpFfpFfp6#F\s617'FbvFE"#;F/Fev7'FbvFEFgr"#eFgv7'
FbvFEFgr""*"#X7'FbvFE""("#bFgv7'FbvFEFj]l"#$*Fgv7'FbvFEFgr"#NFgv7'FbvFEFgr"$<"F
gv7'FbvFEFgrFcvFgv7'FbvFEFgr"#CFgv7'FbvFEFgr"#RFh]l7'FbvFE"#A"#J"#_7'FbvFEFgr"#
QFgv7'FbvFEFgrFevFgv7'FbvFEFgrFi^lFgv7'FbvFEFgr"#ZFi^lFfp
