M7R0
I2F_l2_3view_triang7*,,%#x1G""##!#P"$+""""*&%#x7GF*%#x3GF*#!"("#]*&F,F*%#x4GF*#
"$"R"$+&F,#!""""%,,%#x2GF&#"$*oF5F*F+#"$8*"%+5F1#"#")"$]#F,#!$*>"$+#,2F-F&#!$(H
F5F**&F,F*F%F*F.*&F,F*F:F*F=F,#!#BF5*&%#x8GF*%#x5GF*#"$t&F?*&FNF*%#x6GF*#!$,#FB
FN#"$`"F5,2F2F&#!#(*FBF*FIF3FJF@F,#!$,(F?FM#""$"")FR#!$B""$D"FN#!$d#F?,,FOF&#!$
.#F5F**&FNF*F-F*FP*&FNF*F2F*FgnFN#"$">FB,,FSF&#!$4$FBF*FboFTFcoFjnFN#"$"))F?,4*
&F-F*F%F*F.*&F-F*F:F*F=F-FK*&F2F*F%F*F3*&F2F*F:F*F@F2FenF%F6F:FC#!$,*F?F*,4*&FO
F*F-F*FP*&FOF*F2F*FgnFOFdo*&FSF*F-F*FT*&FSF*F2F*FjnFSFioF-FVF2F]o#!$>"F5F*6",
I2C_l2_3view_triangw,6#>%)symbolicGF*6/%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G
%$_V0G%#_VG%"iG%#uhG%"fG%"jG%$eqsG6"FipC->6$8$8%6$7%%$E12G%$E23G%"uG7%7$FhnFhnF
ir7$F&Fhn@%/9$F*>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fbr6
#8,w,6$%"xG%"yGFip6$%)operatorG%&arrowGFip-&T'6#T%6#,&F]sF**&,&9%F*F7F*F*&&T#Fj
t6#F*F*F*FipFip6(FaqFbrFhqF_tF`qFar6#F&6$7'Q!FipF7"#R"#u"#O7'FiuF7Fju"#XF\v/F_t
;F*-%%nopsG6#Far>F_s7#-Fbs6$-%'rndMatG6#FjsF_v>8--I$<,>GFhs6%-I$<|gr>GFhs6%F%F-
FO-Faw6%F:F2FS-Faw6%F*F*F*>8.,(-%$addG6$-F[x6$*$,&&F\w6$F_t8/F*&&F_s6#FhnFbxF7F
&/F_t;F*F&/Fcx;F*FhnF*-I".G6$FgsFhs6%*&F,F*)&F\w6$;FipFipF*%#%TGF*&F_sFdu&F\w6$
FcyF&F*-F\y6%*&FNF*)FfyFdyF*&F_s6#F&&F\w6$FcyFhnF*>807#-Fbs6$-%%diffG6$Fhw(FbtF
_t/F_t;F*Fin>8'-%$mapG6$%'expandGFaz@$0F]sF*OF\[l>8(-%&minusG6$-%'indetsG6#F\[l
-Fj[l6#F_s>6$8)8*-%,poly2matrixG6$F\[lFe[l>8+-%$srtG6$Fa\l-%%tdegG6#-F[t6#Fe[l6
%7$%#cfG-%/permuteColumnsG6%F`\lFa\lFf\lFarFbrFipFipFip6#""!617'FiuF7"#;""'F\v7
'FiuF7Fhn"#e"#V7'FiuF7Fhn""*F^v7'FiuF7""("#&*F]^l7'FiuF7Fa^l"#dF]^l7'FiuF7Fhn"#
TF]^l7'FiuF7Fhn"$>"F]^l7'FiuF7Fhn"#PF]^l7'FiuF7Fhn"#CF]^l7'FiuF7Fhn"#SF^v7'FiuF
7"#B"#K"#_7'FiuF7Fhn"#QF]^l7'FiuF7FhnF\vF]^l7'FiuF7Fhn"#LF]^l7'FiuF7Fhn"#`"#JFi
p
