M7R0
I0F_opt_pnp_zheng7&,R#"(nW^#"'++]"""*(%#y1GF(%#x1GF(%#w1G""##"((p;D"'++D*(%#z1G
F(F+F(F,F-#!'ZN9"'+]7*(F+F(F,F(F*F(#!'P#4'F0*(F+F(F,F(F2F(#!'RTy"&+D'*(F*F-F+F(
F,F(#"(\q@"F5*(F2F-F+F(F,F(#"(jyV#F0*(F+F(F*F(F2F(#"($)p1"F0*(F2F(F*F-F+F(#!(R$
R;F0*(F2F-F*F(F+F(#!("3S=F0F+#"'@byF'*&F+F(F*F(#"',d9F'*&F+F(F2F(#"'p*o$F0*&F+F
(F*F-#!&j[&"&+D"*&F+F(F2F-#!(H=m#F'*&F*""$F+F(#!'f">%F<*&F+F(F2Ffn#"&3!f"&Dc"*&
F+F(F,Ffn#"(h8E""&++&*&F+F(F,F-#!&T^%FW*&F+F(F,F(#"(@H'GF0F*#"(,"H7F'F2#!'4<)*F
'F,#!&h^#"%]i**F2F(F*F(F+F(F,F(#"%4a"&+]#,R#!($3Z6F5F(F)#F8F'F1#F;F5F6#FPF0F9#F
SF5F=FUF@FYFC#!&`;#F\oFF#"'Z,rF0FI#"(.!yDF'F+#"(213*F0FN#!'*G\"F<FQ#"(\6.$F0FT#
"(F>e"F5FX#"(,En%F'Fen#"%@\"%+]Fin#!&8#=F5F]o#!&Z]"FWFaoFeoFdo#"(jlN#F'F*#!'^/>
"&]7$F2#"'^=JF5F,F%F^pFD,RFbrF(F)F>F1#F`pF`oF6#FVF]pF9FDF=#!(xuD"F<F@FJFC#F\qF5
FF#"&6,*F0FI#"(T=9*F'F+#!&j(\F<FNFeqFQ#FjpFdrFT#"&jZ"F[rFXF]qFen#"'()QM"&++"Fin
#!'x4?F5F]o#"'**)Q)F0FaoFepFdoFOF*#!'p&e$F0F2#!&2a&"'++5F,FgoF^p#FHF5,RFerF(F)F
hrF1FAF6FDF9#FZF0F=FGF@#"'Cq<F\oFC#F^qF0FFF_sFI#!'JHgF5F+#"($Q55F0FNFcsFQFgqFTF
[qFX#!&RY&F5Fen#"&P+$F0Fin#"((pfHF5F]o#!&\y%F5FaoFfpFdoFRF*F_tF2#!'@"p&F0F,FioF
^p#FKF56",
I0C_opt_pnp_zhengw,6#>%)symbolicGF(6/%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$
_V0G%#_VG%"iG%"mG%&alphaG%"fG%$eqsG6"FguC/>6$8$8%6$7#%"MG7#7$"#?"#6@%/9$F(>8&7#
-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F`w6#8,w,6$%"xG%"yGFgu6$%
)operatorG%&arrowGFgu-&T'6#T%6#,&FjwF(*&,&9%F(!""F(F(&&T#Fgy6#F(F(F(FguFgu6(F_v
F`wFfvF\yF^vF_w6#F-6$7'Q!FguF^z"#R"#u"#O7'FgzF^zFhz"#XFjz/F\y;F(-%%nopsG6#F_w>F
\x7#-F_x6$-%'rndMatG6#FgxF][l>8-&F\xFbz>8.-I$<,>GFex6-F(*$%"wGF-*&Fb\lF(F_yF(*&
Fb\lF(F`yF(*&Fb\lF(%"zGF(*$F_yF-*&F_yF(F`yF(*&F_yF(Ff\lF(*$F`yF-*&F`yF(Ff\lF(*$
Ff\lF->8/-I".G6$FdxFex6%)F]\l%#%TG-F`]l6$)Fj[lFd]lFj[lF]\l>807&-%%diffG6$F^]lFb
\l-F\^l6$F^]lF_y-F\^l6$F^]lF`y-F\^l6$F^]lFf\l>Fi]l-%%subsG6$/Fg\lF+-%$mapG6$w,6
#%#plGFgu6$FbyFcyFgu-%'expandG6#*&FjwF(F_yF^zFguFguFgu6#F(6$7'FgzF^z"#F"#UFjz7'
FgzF^zFg_l"#IFjz-Ff^l6$7%/F`y*&F_yF(F*F(/Ff\l*&F_yF(F2F(/Fb\l*&F_yF(F,F(Fi]l>8'
-Fj^l6$Fa_lFi]l@$0FjwF(OFe`l>8(-%&minusG6$-%'indetsG6#Fe`l-Faal6#F\x>6$8)8*-%,p
oly2matrixG6$Fe`lF\al>8+-%$srtG6$Fhal-%%tdegG6#-Fhx6#F\al6%7$%#cfG-%/permuteCol
umnsG6%FgalFhalF]blF_wF`wFguFguFgu6#""!637'FgzF^z"#;""'Fjz7'FgzF^zFfn"#M"#V7'Fg
zF^zFfn""*F\[l7'FgzF^z""("#&*Fdcl7'FgzF^zFhcl"#dFdcl7'FgzF^zFfn"#7Fdcl7'FgzF^zF
fn"#kFdcl7'FgzF^zFfn"#JFdcl7'FgzF^zFfnF[dlFdcl7'FgzF^zFfn"#")Fdcl7'FgzF^zFfn"#C
Fdcl7'FgzF^zFfn"#SF\[l7'FgzF^z"#B"#K"#_7'FgzF^zFfn"#QFdcl7'FgzF^zFfnFjzFdcl7'Fg
zF^zFfn"#LFdcl7'FgzF^zFfn"#`FadlFgu
