M7R0
I0F_optpose3pt_v27',H%"xG#"%29"%]i%"vG#!%6S"&+]#%"yG#!&hB$"(+]7$%"zG#"("f%G""(+
+D'*$F)""##"$t&"%+5*&F)"""F-F;#"%BY"&+D'*&F)F;F1F;#!'8N="'+]7*&F%F;F)F;#!$,#"$D
"*&F-F;F1F;#"*6,PJ""*+++]#*&F-F;%"wGF;#"'t!4&"'++]*&F-F;F%F;#"&$Q;"&]7$*&F1F;FL
F;#"&<#QF>*&F1F;F%F;#"'^kNFO*$FLF6F7*&F%F;FLF;#"$`""$]#*$F%F6#""$"")*$F-F6#"*hd
s_%"+++++5*$F1F6#"*>O]R$F`o#"&x!G"(++]#F;,HF%#!'([+""'++DF)#!&$4[FSF-#")(QT/(FJ
F1#!(Z%R")")++]iF5#!$B"FFF:#"'d,=FOF?#!&<3#FBFC#!$d#"$+&FG#!((=&)*)F4FK#!&>F%F,
FP#!&4S("'++5FT#!&"GbF>FW#"&88&FSFZFbpFen#"$">FFFin#"$"))F9F]o#!'.np")+++SFao#!
(d6]&"*+++D"#!)jV!)=")++DJF;,HF%#!#P"$+%F)#"$>"F9F-#"&PL$"'++SF1#"%jt"&++)F5#!$
>"FjpF:#!&PL$FaqF?#!%jt"&++#FC#"#P"$+"FG#"*BoG[%"*++++&FK#!&(yIFOFP#!'4#R#FjoFT
#!'`*4&FOFW#"&.k"FBFZF_sFen#"$(HFjpFin#"$.#F9F]o#"*$o(oh%F`oFao#!*$f^Z_F`o#F`s"
%+!)F;z)6$F-F1[[[[[_[[[[sF;][[[[[[[[[sF;!!"",\rF%#"2R'Hm7YsGr"5+++++++++5F)#!1R
FaU;A]Q"3++++++++]F-#"6@oo-$y@CC3;"8+++++++++++"FL#!2tKc+EAF#fFduF1#!6.841Y-[PS
?"FjuF5#"/*G2Q"f(R""1++++++]7F:#!4pkZnD#3T)*Q"5+++++++++]F?#"4(46Czkch0`Fdv*&F)
F;FLF;#"1*eTv"o+zQ"2++++++++&FC#!0(z#yrU)QEFjvFG#!8\-'\\Z9FWf+6"9+++++++++++DFK
#!4j9C!y>q3_W"6++++++++++&FP#!3ZfJ"\-1=c%FdvFT#!5Pi%H"4;dUR5"6+++++++++]#FW#!4*
QYtd:.5@5"4+++++++D"yFZ#!2LT'=W!3b4#FguFen#!2Hjt;[tFy""3+++++++]7Fin#!0\"R^===e
Fjv*&F)F6F-F;#!2.>DshQlJ""3++++++++?*&F)F6F1F;#"1hhAE%*>OBFex*&F)F6FLF;#!.")>?>
`Y&"0+++++++#*&F)F6F%F;#!.4J%GN)o'"/++++++S*&FLF6F)F;#!0f#QfzWgb"1+++++++5*&F)F
;F%F6#"/\3BOxvc"0+++++++&*&F)F;F-F6#!4>8sYinuhV#"5+++++++++?*&F)F;F1F6#!6\$RO3D
y*o$QJFbw*&F-F6F1F;#!9*fhp"e5gHthS5":++++++++++++"*&F-F6FLF;#"3F)o%4*=8!yXFgw*&
F-F6F%F;#!688o\))ev-!fM"7++++++++++5*&F-F;FLF6#!26"p/iq!zT&"4+++++++++"*&F-F;F%
F6#!2Bn,8a%y>uFex*&F-F;F1F6#"9`/8=d!)yV!4S4""9+++++++++++]F]o#"7*[lTqt;GI4r&"8+
++++++++++&Fao#!7$GfiAg<K'3$R$F_w*(F)F;F-F;F1F;#"5*\uWsz2g[q"Fbw*(F-F;FLF;F)F;#
"2^7k4&*3c+#Fex*(F)F;F-F;F%F;#"3@.Vz<BCfGFgu*(F)F;F1F;FLF;#!3^/pgkQ!*QjFgu*(F)F
;F1F;F%F;#"2J0U0@5dJ&"3++++++++D*(F)F;FLF;F%F;#"/`_^HnO")"0++++++]#*(F-F;F1F;FL
F;#"6$["ep!43Vp'4"Fbw*(F-F;F1F;F%F;#!3ptU"fu9l=)"4++++++DJ&>*(F-F;FLF;F%F;#!3\!
>KW56*ziF^[l*(F1F;FLF;F%F;#"3hj!**pTwXX&Fgu*$F)F[o#"-h2tA_G"/++++++5*$F-F[o#"8<
Gm=%)=pUrJP&"9+++++++++++?*$F1F[o#"8T7V1d\rC*3O\"9++++++++++]7*$FLF[o#"/J1:#>aF
)F^]l*$F%F[o#"/$)G+q?EVFdy#"0dG49Yl!yF^[lF;*&F1F6FLF;#"58WWg?[)**f2$"5+++++++++
D*&F1F6F%F;#"62utQ-qBR=]#Fbw*&F1F;FLF6#"3()4zLmXfw9F_x*&F1F;F%F6#"2z(oxIN>PEFex
*&FLF6F%F;#"0>&=ROH)R&Fdy*&FLF;F%F6#"0p,+_g@["Fdy6",
I0C_optpose3pt_v2t+6#>%)symbolicGF;6.%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%#V
0G%"VG%"CG%"tG%"RG%&boffaG6"Fc`lC1>6$8$8%6$7$%"UG%"uG7$7$F[oF[o7$"#7F;@%/9$F;>8
&-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F[bl6#%"iGf*6$F%F-Fc`l6$
%)operatorG%&arrowGFc`l-&T%Ffcl6#,&FfblF;*&,&9%F;F`uF;F;&&T#Ffcl6#F;F;F;Fc`lFc`
l6&F[alF[blFj`lFjal/Fgcl;F;-%%nopsG6#Fjal>Fhbl-Fjbl6$-%'rndMatG6#FbclFjdl>&8,Fh
dl-I$<,>GF`cl6%-I$<|gr>GF`cl6%&&Fhbl6#F6Fhdl""!&F_flF`fl-F\fl6%FaflF^fl&F_fl6#F
[o-F\fl6%FbflFefl&F_fl6#""%>&FgelF`fl-Fiel6%-F\fl6%&F_fl6#""&Fafl&F_fl6#""'-F\f
l6%FaflFbgl&F_fl6#""(-F\fl6%FeglFjgl&F_fl6#F\o>&FgelFffl-Fiel6%-F\fl6%&F_fl6#""
*Fafl&F_fl6#"#5-F\fl6%FaflFghl&F_fl6#"#6-F\fl6%FjhlF_il&F_fl6#Fcbl>6$8-8.6$-Fie
l6%F)FLF%-Fiel6%-F\fl6%F;FaflFafl-F\fl6%FaflF-,$F1F`u-F\fl6%FaflF1F->8'7$-Fjbl6
$-I".G6$F_clF`cl6%),&-F\[m6$Fiil&&FhblFhdl6$;Fc`lFc`lFgclF;FhilF;%#%TG&FgelFfcl
F`[m/Fgcl;F;F[oF^u>8/,$-Fiel6#-Fjbl6$)-Fiel6%-Fjbl6$-%%diffG6$&FgjlFfcl&Fhil6#%
"jG/F]]mFj[m-Fh\m6$Fj\mF--Fh\m6$Fj\mF1Fg[mFi[m#F;F6>Fgjl7$-Fccl6#Fgjl-&I.Linear
AlgebraG6$F_clF`cl6#_Fj]m%,DeterminantG6#&F\\m6$Ff[m;F[oFdgl>Fgjl-%$mapG6$%'exp
andGFgjl@$/FfblFaflOFgjl>8(-%&minusG6$-%'indetsGFg]m-Fa_m6#7#Fhbl>6$8)8*-%,poly
2matrixG6%Fgjl-F]elFg]mF\_m>8+-%$srtG6$Fh_m-%%tdegG6#-Fccl6#F\_m6%7$%#cfG-%/per
muteColumnsG6%Fg_mFh_mF^`mFjalF[blFc`lFc`lFc`l6#FaflFc`l
