M7R0
I2F_opt_pnp_nakanoC7(,bo%"xG#"$U#"$D"%"yG#!#p"#?%"zG#"$#GF(*&F%"""F)F1#"$'\F(*&
F%F1F-F1#!%dZ"$+&*&F)F1F-F1#!%7<F(*&F)""#F%F<#!%/=F(*&F%F<F-F<#!$.#"#]*&F)F<F-F
<#!$L$F7*&F)F1F%""$#!%^8"$]#*&F)FGF%F1#!#RFB*&F-F1F%F<#!%r9FJ*&F-F1F)F<#"$^)FJ*
&F-F1F%FG#"$p(F7*&F%F1F-FG#!$6"F7*&F)F1F%F<#!$j#F7*&F)F1F-F<#!%Z<F7*&F)FGF-F1#"
$4"F(*&F)F1F-FG#"$/#F(*&F%F1F)F<#!$='F(*&F%F1F-F<#""*"#D*$F%F<#!$"["$+"*$F)F<#"
$c"F(*$F-F<#!%p7FJ*(F%F1F)F1F-F<#"$>'F(*(F%F1F-F1F)F<#"%*H&F7*(F)F1F-F1F%F<#"$_
&F(*(F%F1F)F1F-F1#"#@Ffo*$F%""%#"%rI"%+5*$F)F^q#"%*)HFaq*$F-F^q#"#T"$+#*$F-FG#!
##)Ffo*$F)FG#!$t'F7*$F%FG#"#%)F(#"#V"#SF1,boF%#!%P@F7F)#"$V"FJF-#!$F#F7F0#"%(\#
F7F4#!$2#FBF8#!%JHF7F;#!%>@F7F?#!$(eF7FC#!$8"FJFF#"%Z6F7FK#!%(4"F7FN#"%6aF7FQ#"
$.(FjoFT#"$2$FJFW#!$Z$FJFZ#!%2:FJFgn#"%f=FJFjn#"%xBF7F]o#"$Z%F7F`o#!%P%)F7Fco#!
$6(F7Fgo#!$L%FJF[p#!%LEF7F^p#!$T)F7Fap#!$2(F7Fdp#!$h(FJFgp#!%tRF7Fjp#"%m;F(F]q#
!$^"F(Fbq#!#zFjoFeq#"$\&F7Fiq#!%zDF7F\r#!$J)FJF_r#"%TBF7#"#PFBF1,boF%#"%$G"F7F)
#!$F$F(F-#!%dAF7F0#!$.$FjoF4#!#PFJF8#!%n5F7F;#"%hHF7F?#"$H'F7FC#!$$[FjoFF#"$P%F
7FK#!$$oF7FN#!$P#FjoFQ#"%F:FjoFT#!$*>FBFW#"$R)FJFZ#"$e"F(Fgn#"%78F(Fjn#FatF7F]o
#!%J<F7F`o#"$d)F7Fco#!$4"F7Fgo#"$,%F7F[p#"%PCF7F^p#!"(F,Fap#!%(["F7Fdp#"$`*FJFg
p#"$^*FjoFjp#"$V*F(F]q#!$z$FaqFbq#"%8=FaqFeq#"%(R$FaqFiq#!$(\F7F\r#F1""&F_r#!$.
"F7#"$d*FaqF1,boF%#"#dF(F)#!%T8FJF-F.F0#!$x&FJF4#!%t;FJF8#!%P:FJF;#"%/=F(F?#"%@
6F7FC#!$e$F(FF#"%^8FJFK#"#RFBFN#"$x$F(FQ#"$_#F(FT#!$(GF(FW#"%V;FJFZ#!$8%F(Fgn#"
"(FJFjn#"$x"FJF]o#!$T"FJF`o#"%d6F(Fco#!$y%F(Fgo#"$(RFJF[p#"$L%FjoF^pF_pFap#"$,#
FJFdp#!$B$F(Fgp#!#jFJFjp#"%A?F(F]q#!%rIFaqFbq#!%*)HFaqFeqFfqFiqFjqF\r#!#dFfoF_r
#"$=#F(FbrF1,boF%#!$J&FJF)FhrF-#!$'HF(F0#!$">FBF4#!$>"FfoF8#!$R"FBF;#F[wF7F?#"$
(eF7FC#!#xF(FF#!$#>F(FK#!$"HFBFN#FinFJFQ#"$i(F(FT#!$2$FJFW#"$Z$FJFZ#!$Y&F(Fgn#"
$c(F(Fjn#!$`"F(F]o#!$j"F(F`o#!%79F(Fco#!$A"FfoFgo#"#LFBF[pFbuF^p#"%LHF7Fap#!$<'
F(Fdp#!$R$F(Fgp#"%TCFJFjp#!$c$F(F]q#"$^"F(FbqF`vFeq#!$\&F7Fiq#!$4%FJF\rFfvF_r#"
#tFBFjvF1,boF%F]wF)#!$L#F7F-#!%<:F7F0#!$>$F7F4#!%tKF7F8#"%h<F7F;#"$B&FJF?#"%t7F
JFC#"$$[FjoFF#"$H$FjoFK#"%t9F7FN#!%@<F7FQ#!%`vF7FT#"%"3"F7FW#!%t9F7FZ#!$z*F7Fgn
#!%\TF7Fjn#Fg`lF7F]o#"%J<F7F`o#"%(o"F7Fco#!%fXF7FgoFfyF[p#!$(>FBF^p#!$$zFJFap#"
%@?F7Fdp#!%rOF7Fgp#!%x=F7Fjp#!$O*F(F]qFdzFbq#!%8=FaqFeq#!%(R$FaqFiq#"$>$FjoF\r#
"%*)GF7F_rF^[lF`[lF16",
I2C_opt_pnp_nakanoCw,6#>%)symbolicGF165%&_nameG%&_sizeG%#_AG%"iG%"aG%"bG%"cG%"d
G%"RG%"rG%&matMrG%"PG%"QG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FfflC2>6$8$8%6$7
#%"MG7#7$FeoFeo@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fehl6#8'Fffl/F[jl;F1-%%nopsG
6#Fdhl>F`il7#-Fcil6$-I'MatrixG6$%*protectedG%(_syslibG6$Fhilw,6$F%F)Fffl6$%)ope
ratorG%&arrowGFffl-&T'6#T%6#,&F]ilF1*&,&9%F1!""F1F1&&T#Fc[m6#F1F1F1FfflFffl6(F^
glFehlF`glF[jlF]glFdhl6#F<6$7'Q!FfflFj[mF[w"#s"#O7'Fc\mFj[mF[wFcrFe\mF\jl>6&8(8
)8*8+6&F1F%F)F->8,-I$<,>GFijl6%-I$<|gr>GFijl6%,**$Fi\mF<F1*$Fj\mF<F1*$F[]mF<Fj[
m*$F\]mF<Fj[m,&*&Fj\mF1F[]mF1F<*&Fi\mF1F\]mF1!"#,&*&Fj\mF1F\]mF1F<*&Fi\mF1F[]mF
1F<-Fd]m6%,&F\^mF<F]^mF<,*Fg]mF1Fh]mFj[mFi]mF1Fj]mFj[m,&*&F[]mF1F\]mF1F<*&Fi\mF
1Fj\mF1F^^m-Fd]m6%,&F`^mF<Fa^mF^^m,&Fg^mF<Fh^mF<,*Fg]mF1Fh]mFj[mFi]mFj[mFj]mF1>
8--Fa]m6#-%(convertG6$F_]m%%listG>8.-I".G6$FhjlFijl6$&F`ilF^\mF__m>Fg_m-Fa]m6%-
Fd]m6%&Fg_mF^\m&Fg_m6#F^q&Fg_m6#Fb]l-Fd]m6%&Fg_m6#F<&Fg_m6#F][l&Fg_m6#"")-Fd]m6
%&Fg_m6#FG&Fg_m6#""'&Fg_m6#Feo>8/,&-Fi_m6$)F_]m%#%TGFg_mF1-Fi_m6$)Fg_mF_bmF_]mF
j[m>80,&-Fi_m6$Fg_mF^bmF1-Fi_m6$F_]mFbbmFj[m>817(&Fjam6$F1F<&Fjam6$F1FG&Fjam6$F
<FG&FdbmF^cm&FdbmF`cm&FdbmFbcm>82-%$mapG6$%'expandGF[cm@$F\ilOFgcm>83-%&minusG6
$-%'indetsG6#Fgcm-Fddm6#F`il>6$8485-%,poly2matrixG6$FgcmF_dm>86-%$srtG6$F[em-%%
tdegG6#&F_dmFffl6%7#-%/permuteColumnsG6%FjdmF[emF`emFdhlFehlFfflFfflFffl6#F^il6
67'Fc\mFj[m"#;FfamFe\m7'Fc\mFj[mFG"#KFcr7'Fc\mFj[mFGFeo"#X7'Fc\mFj[mFb]l"#bFcr7
'Fc\mFj[mFb]l"#$*Fcr7'Fc\mFj[mFG"#FFcr7'Fc\mFj[mFG"$I"Fcr7'Fc\mFj[mFGFfoFcr7'Fc
\mFj[mFG"#>Fcr7'Fc\mFj[mFG"$,"Fcr7'Fc\mFj[mFG"#HFcrFbgm7'Fc\mFj[mFGFd[lFcr7'Fc
\mFj[mFG"#CFcr7'Fc\mFj[mFGFf\lFdfm7'Fc\mFj[m"#A"#J"#_7'Fc\mFj[mFG"#QFcr7'Fc\mFj
[mFGFe\mFcr7'Fc\mFj[mFGFjgmFcr7'Fc\mFj[mFG"#ZFjgmFffl
