M7R0
I6F_opt_vanishingpoints7&,jq%"xG#!#R"#]%"wG#!$P$F(*&F%"""%"yGF-#"#9"$D"*&F%F-%"
zGF-#!%mHF1**F)F-F%F-F.F-F3F-#"$r&F1*(F%F-F.F-F3F-#"%U6F1*(F)F-F%F-F.F-#!$f#"#D
*(F)F-F%F-F3F-#"%\?F1*(F)F-F.F-F3F-#"%r=F1*(F)F-F%F-F.""##"%j5"$]#*(F)F-F%F-F3F
G#!$*GFJ*(F)F-F%FGF.F-#"%\WFJ*(F)F-F.F-F3FG#!%\?FJ*(F)F-F%FGF3F-#"#@FJ*(F)F-F.F
GF3F-#F>F(*(F%F-F.F-F3FG#!$=&F?*(F%F-F3F-F.FG#"%)4%F1*(F%FGF3F-F.F-#!%%[(F1*(F%
FGF.F-F3FGFgn*(F%FGF3F-F.FG#"$=&F?*(F%""$F3F-F.F-#!%U6F1*(F%F-F.FGF3FG#!$L$F?*(
F%F-F.FaoF3F-#"$u'F?*(F%F-F.F-F3Fao#!$u'F?*$F%FGFho*$F%FaoFeo*$F%""%F[p*$F%""&F
&*&F%F-F.FG#"$*GF1*&F%F-F3FG#!%j5F1*&F%FGF.F-#!%)4%F1*&F%FGF3F-FZ*&F)F-F%F-#"$L
$F(*&F)F-F.F-#FBFJ*&F)F-F3F-#"$f#F(*&F)F-F%FG#"%65F(*&F)F-F.FG#!$r&FJ*&F)F-F3FG
#F8FJ*&F)F-F%Fao#"#RF(*&F)F-F.Fao#!%$["FJ*&F)F-F3Fao#!"(FJ*&F%FGF.FGF:*&F%FGF3F
GFbo*&F%FaoF.F-F^o*&F%F-F.Fao#!#9F1*&F%FaoF3F-Fjp*&F%F-F3Fao#"%mHF1*&F%F-F.F`pF
&*&F%F-F3F`pF&*&F%FaoF.FGFgp*&F%FaoF3FGFdp*&F%F`pF.F-F4*&F%FGF.FaoF^s*&F%F`pF3F
-Fjr*&F%FGF3FaoF/,jqF.F&F)FdrF,Fho*&F.F-F3F-F4F6F=F9FZF<#FjqF1F@FDFC#FSF1FF#!%
\WFJFKFRFNFHFQF^qFTF\rFW#!%65F(FYFboFfnFjnFinFjpF\oFdpF]oFboF`oFjrFdoFgnFgoF^oF
joF/*$F.FGF/*$F.FaoFdp*$F.F`pFjr*$F.FbpF&FcpFjpFipFeo*&F.F-F3FGFgp*&F.FGF3F-F:F
]qFaqF`qFLFbqFiqFeqFXFhqFUF[rFcqF]r#"%$["FJF`rF^rFcr#"$P$F(FfrF^o*&F.FGF3FGFZFh
rF[pFirF:*&F.FaoF3F-Fgn*&F.F-F3FaoF^sF`sF^sFbsF4FdsF&FesFgp*&F.F-F3F`pF&*&F.Fao
F3FGFeo*&F.F`pF3F-Fho*&F.FGF3FaoF[p,jqF3F&F)FftF2FhoFisF/F6F[tF9FjpF<FDF@F7FC#F
dqF?FFFXFK#!#@FJFNF\rFQFfqFTFLFWF^qFYFjnFfnF:FinF^oF\oFboF]oFgpF`oF4FdoF^oFgoF^
sFjoFgn*$F3FGF4*$F3FaoFgp*$F3F`pF^s*$F3FbpF&FfpFZFdtF:F\qFeoFetFdpF]qFcqF`qFiqF
bqFHFeqFaqFhqFRF[rF\tF]r#""(FJF`rF*FcrF^rFgrFjpFjtFgnF\sF[pF]sFboF[uFjrF\uFZFas
F/FcsFjrFfsF&FgsFdpF]uF[pF^uFhoF_uF&F`uFeoz-6&F)F%F.F3[[[[[[][[[[[m!""[[[][[[[[
[[[mF]v][[[[[[[[[[[mF]v[[[[[[[[[\[[lF-!F]v6",
I6C_opt_vanishingpointsw,6#>%)symbolicGF-67%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$
_C0G%$_V0G%#_VG%"iG%$mm1G%$mm2G%$mm3G%'symMatG%$denG%"RG%#v1G%#v2G%#v3G%#JpG%$d
JpG%$eqsG6"F^vC4>6$8$8%6$7%%#M1G%#M2G%#M3G7%7$""'F-FfxFfx@%/9$F->8&7#-%$seqG6$-
I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F_x6#8,w,6$F%F.F^v6$%)operatorG%&ar
rowGF^v-&T'6#T%6#,&FjxF-*&,&9%F-F]vF-F-&&T#Fez6#F-F-F-F^vF^v6(FfvF_xF]wF\zFevF^
x6#FG6$7'Q!F^vF]vF_r"#u"#O7'Fd[lF]vF_r"#XFf[l/F\z;F--%%nopsG6#F^x>F\y7#-F_y6$-%
'rndMatG6#FgyFi[l>6%8-8.8/6%-%(convertG6$&F\yF_[lI'VectorG6$FdyFey-F\]l6$&F\y6#
FGF_]l-F\]l6$&F\y6#FaoF_]l>80w,6#%"vGF^v6$F`zFazF^v-I$<,>GFey6%-I$<|gr>GFey6%&F
jxF_[l&FjxFd]l&FjxFh]l-Fc^l6%Ff^l&Fjx6#F`p&Fjx6#Fbp-Fc^l6%Fg^lF\_l&Fjx6#FgxF^vF
^vF^v6#F-6$7'Fd[lF]v"#8"#pFf[l7'Fd[lF]vFe_l"#:Ff[l>Ff\l6%-Fj]l6#Fg\l-Fj]l6#Fh\l
-Fj]l6#Fi\l>81z+6%F%F.F3[[[[[[[[][[[mF-[[[[][[[[[[[mF-][[[[[[[[[[[mF-!F->82-F`^
l6%-Fc^l6%z+Fd`l[[[[[[[[][[[mF-[[[[][[[[[[[mF]v][[[[[[[[[[[mF]v!F-z'Fd`l[[[[\[[
[\[[[mFG\[[[[[[[[[[[lFGz'Fd`l\[[[[[[[\[[[mFG[[[[\[[[[[[[l!"#-Fc^l6%z'Fd`l[[[[\[
[[\[[[mFG\[[[[[[[[[[[lF^alz+Fd`l[[[[[[[[][[[mF]v[[[[][[[[[[[mF-][[[[[[[[[[[mF]v
!F-z'Fd`l\[[[\[[[[[[[mFG[[[[[[[[\[[[lFG-Fc^l6%z'Fd`l\[[[[[[[\[[[mFG[[[[\[[[[[[[
lFGz'Fd`l\[[[\[[[[[[[mFG[[[[[[[[\[[[lF^alz+Fd`l[[[[[[[[][[[mF]v[[[[][[[[[[[mF]v
][[[[[[[[[[[mF-!F->6%8384856%-F`^l6%F-""!Fabl-F`^l6%FablF-Fabl-F`^l6%FablFablF-
>86,(-I".G6$FdyFey6')F[bl%#%TGFf`lFg\l)Ff`lF^clF[blF--Fjbl6')F\blF^clFf`lFh\lF_
clF\blF--Fjbl6')F]blF^clFf`lFi\lF_clF]blF->87-F`^l6%-%%diffG6$FgblF%-F[dl6$Fgbl
F.-F[dl6$FgblF3>887%,&*&F)F-&FgclF_[lF-F-*&F%F-FgblF-!"%,&*&F)F-&FgclFd]lF-F-*&
F.F-FgblF-Fhdl,&*&F)F-&FgclFh]lF-F-*&F3F-FgblF-Fhdl>Fbdl7$-Fhy6#Fbdl,&F)F-Fb`lF
]v>8'-%$mapG6$%'expandGFbdl@$0FjxF-OFgel>8(-%&minusG6$-%'indetsG6#Fgel-Fefl6#F
\y>6$8)8*-%,poly2matrixG6$FgelF`fl>8+-%$srtG6$F\gl-%%tdegG6#-Fhy6#F`fl6%7$%#cfG
-%/permuteColumnsG6%F[glF\glFaglF^xF_xF^vF^vF^v6#Fabl687'Fd[lF]v"#;FgxFf[l7'Fd[
lF]vFao"#f"#V7'Fd[lF]vFao""*Fh[l7'Fd[lF]vFju"#&*Ffhl7'Fd[lF]vFju"#dFfhl7'Fd[lF]
vFao"#*)Ffhl7'Fd[lF]vFaoFf_lFfhl7'Fd[lF]vFao"#cFfhl7'Fd[lF]vFao"#BFfhl7'Fd[lF]v
Fao"$?"Ffhl7'Fd[lF]vFao"#ZFfhl7'Fd[lF]vFao"#oFfhl7'Fd[lF]vFao"#[Ffhl7'Fd[lF]vFa
o"#gFfhl7'Fd[lF]vFaoF?Ffhl7'Fd[lF]vFao"#CFfhl7'Fd[lF]vFao"#SFh[l7'Fd[lF]vFcil"#
K"#_7'Fd[lF]vFao"#QFfhl7'Fd[lF]vFaoFf[lFfhl7'Fd[lF]vFao"#LFfhl7'Fd[lF]vFao"#`"#
JF^v
