M7R0
I0F_optpose2pt_v27(,H%"vG#"$h""&+D"%"xG#"%2\"&+]#%"yG#"'nuR"(++D'%"zG#!%2\"'++5
*$F%""##!#B"$+&*&F%"""F-F;#!&"yc"'+]7*&F%F;F1F;#"$,("%+?*&F)F;F%F;#!$,(F9*&F-F;
F1F;#!(Jq'H"*+++D"*&F-F;%"wGF;#!&`]$"&+D'*&F-F;F)F;#"'^a?"'++D*&F1F;FKF;#"'x+7F
R*&F1F;F)F;#"&PV(FR*$FKF6F7*&F)F;FKF;#!$,*F9*$F)F6#"$t&"%+5*$F-F6#")"y/a#FI*$F1
F6#!)*fW(G"*+++]##!%F6"(++D"F;,HF%#!&"fyFNF)#"&B)fF>F-#!)xZ!>"")+++DF1#")*R=Y&F
IF5#!$,#"$]#F:#!&Z/$"&++&F?#"'*oR"FRFC#"$`"FapFF#"(t%[5"(+++&FJ#!(xr5""'++]FO#"
'"Hk#F4FS#!&@:*F4FV#!'n__F^qFYF_pFZ#""$""%Fgn#!$B""$D"F[o#!+j,&G;""*++++&F^o#!*
tGWn%F]r#!)"3H2$")++]iF;z)6$F-F1[[[[[_[[[[sF;][[[[[[[[[sF;!!"",LF%#",ZH"3TX"-++
+++DF)#!+LPEA#*"-++++]7F-#!/@JURc/E"/+++++]iFK#",rvhI,#F\sF1#!-z&3k&ep"0++++++D
"F5#"*2nYT"F]rF:#"-f!>fdr)"-+++++]F?#!,hlX3'eFir*&FKF;F%F;#"+"zR9A""+++++5FC#!+
$HF+X"F_tFF#!/6)[&e9`AFdsFJ#"-**H^e=CF\sFO#!-$QD*>jcFisFS#!-`')Qh4?FisFV#"-(fKY
<:"FirFY#"+xas-6F_tFZ#!+@W`F6F]rFgn#"+$G@:;"F_tF[o#!0B7fy701$"0++++++]#F^o#".tx
RL&QBFdu#!-fqP%>(Q"/+++++]7F;,LF%#!,><,S+%FirF)#"(6"=F"*+DJ&>F-#"-(z#*pIQ$".+++
++]#FK#!,Lja_i$F\sF1#!.j7!\H!e&FdsF5#!*R_tC"F]rF:#!+Bk3LP",+++++#F?#"-6f*=.1#Fi
rF\t#!)ZV9qF_tFC#"*<vCb'F_tFF#!/"GYcnU6""/++++++]FJ#!,H#>+xH",+++++&FO#!,J'**\>
=FgwFS#"-(\!)*z<ZFisFV#!-hq89WKFisFY#")r)[W'"*++++#FZ#")VgZCFbrFgn#!(6t='")+++S
F[o#".^K&yDQHFdwF^o#!/nl1XM#\#Fds#"-V"\.ST$FiuF;,LF%#!-.,GI,")FdsF)#"/H%[g?6w"F
dsF-#!0hY?L3rz$"2++++++]7$FK#!.nr$pFJ9"/+++++DJF1#!064nn(\D*)"2++++++Dc"F5#!+V.
xBDFirF:#"0Ta(G6L#4"FduF?#"-8ee*)>:"-++]il(*F\t#"-*o>1PY"FisFC#",ZDv*)Q#FisFF#!
2j7np#Hi<d"3+++++++]7FJ#"/FT0)psG&FdsFO#"/Lv!RP6'=F_sFS#"/z3T(H*Q9FdsFV#!/^p-X/
RgFduFY#"-*)[?3r>FisFZ#!,PO!)Qn*FisFgn#!+hf<Uk",+++Dc"F[o#!0`Z.(y*e'yFgzF^o#"18
kG#H9Q*GFgz#"."zG%fv!p"1++++++]iF;6",
I0C_optpose2pt_v2w,6#>%)symbolicGF;62%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$
_V0G%#_VG%"iG%#C1G%#C2G%"tG%"RG%$eqsG%&boffaG%"jG6"F^\lC0>6$8$8%6$7$%"UG%"uG7$7
$FfqF67$"")F;@%/9$F;>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&
Fj]l6#8,w,6$F)F-F^\l6$%)operatorG%&arrowGF^\l-&T'6#T%6#,&Fe^lF;*&,&9%F;FerF;F;&
&T#F``l6#F;F;F;F^\lF^\l6(Ff\lFj]lF]]lFg_lFe\lFi]l6#F66$7'Q!F^\lFer"#R"#u"#O7'F_
alFerF`al"#XFbal/Fg_l;F;-%%nopsG6#Fi]l>Fg^l7#-Fj^l6$-%'rndMatG6#Fb_lFeal>8--I$<
,>GF`_l6%-I$<|gr>GF`_l6%&&Fg^l6#F6Fj`l""!&FjblF[cl-Fgbl6%F\clFibl&Fjbl6#Ffq-Fgb
l6%F]clF`cl&Fjbl6#Fgq>8.-Fdbl6%-Fgbl6%&Fjbl6#""&F\cl&Fjbl6#""'-Fgbl6%F\clF\dl&F
jbl6#""(-Fgbl6%F_dlFddl&Fjbl6#Fb^l>6$8/806$-Fdbl6%F%FKF)-Fdbl6%-Fgbl6%F;F\clF\c
l-Fgbl6%F\clF-,$F1Fer-Fgbl6%F\clF1F->817%-I".G6$F__lF`_l6%),&-F_fl6$F^el&&Fg^lF
j`l6$;F^\lF^\lF;F;F]elF;%#%TGFbblFcfl-F_fl6%),&-F_fl6$F^el&Fgfl6$FiflF6F;F]elF;
FjflFgclF^glFcr>82,$-Fdbl6#-Fj^l6$)-Fdbl6%-Fj^l6$-%%diffG6$&F\flFf_l&F]el6#83/F
ehl;F;Ffq-F`hl6$FbhlF--F`hl6$FbhlF1Fjfl/Fg_l;F;F6#F;F6>F\fl7&-Fc_l6#F\fl-&I.Lin
earAlgebraG6$F__lF`_l6#_Feil%,DeterminantG6#&Fdgl6$Fifl7$FfqFgq-Fdil6#&Fdgl6$Fi
fl7$FfqF^dl-Fdil6#&Fdgl6$Fifl7$FgqF^dl>8'-%$mapG6$%'expandGF\fl@$0Fe^lF;OFijl>8
(-%&minusG6$-%'indetsG6#Fijl-Fg[m6#Fg^l>6$8)8*-%,poly2matrixG6$FijlFb[m>8+-%$sr
tG6$F^\m-%%tdegG6#-Fc_l6#Fb[m6%7$%#cfG-%/permuteColumnsG6%F]\mF^\mFc\mFi]lFj]lF
^\lF^\lF^\l6#F\cl647'F_alFer"#;FadlFbal7'F_alFerFfq"#VFg]m7'F_alFerFfq""*Fdal7'
F_alFerFfdl"#&*Fg]m7'F_alFerFfdl"#dFg]m7'F_alFerFfq"#%)Fg]mF^^m7'F_alFerFfq"#\F
g]m7'F_alFerFfq"$1"Fg]m7'F_alFerFfq"#**Fg]m7'F_alFerFfqFhpFg]m7'F_alFerFfq"#CFg
]m7'F_alFerFfq"#SFdal7'F_alFer"#B"#K"#_7'F_alFerFfq"#QFg]m7'F_alFerFfqFbalFg]m7
'F_alFerFfq"#LFg]m7'F_alFerFfq"#`"#JF^\l
