M7R0
I0F_optpose2pt_v27(,H%"vG#"$h""&+D"%"xG#"%2\"&+]#%"yG#"'nuR"(++D'%"zG#!%2\"'++5
*$F%""##!#B"$+&*&F%"""F-F;#!&"yc"'+]7*&F%F;F1F;#"$,("%+?*&F)F;F%F;#!$,(F9*&F-F;
F1F;#!(Jq'H"*+++D"*&F-F;%"wGF;#!&`]$"&+D'*&F-F;F)F;#"'^a?"'++D*&F1F;FKF;#"'x+7F
R*&F1F;F)F;#"&PV(FR*$FKF6F7*&F)F;FKF;#!$,*F9*$F)F6#"$t&"%+5*$F-F6#")"y/a#FI*$F1
F6#!)*fW(G"*+++]##!%F6"(++D"F;,HF%#!&"fyFNF)#"&B)fF>F-#!)xZ!>"")+++DF1#")*R=Y&F
IF5#!$,#"$]#F:#!&Z/$"&++&F?#"'*oR"FRFC#"$`"FapFF#"(t%[5"(+++&FJ#!(xr5""'++]FO#"
'"Hk#F4FS#!&@:*F4FV#!'n__F^qFYF_pFZ#""$""%Fgn#!$B""$D"F[o#!+j,&G;""*++++&F^o#!*
tGWn%F]r#!)"3H2$")++]iF;z)6$F-F1[[[[[_[[[[sF;][[[[[[[[[sF;!!"",LF%#",ZH"3TX"-++
+++DF)#!+LPEA#*"-++++]7F-#!/@JURc/E"/+++++]iFK#",rvhI,#F\sF1#!-z&3k&ep"0++++++D
"F5#"*2nYT"F]rF:#"-f!>fdr)"-+++++]F?#!,hlX3'eFir*&FKF;F%F;#"+"zR9A""+++++5FC#!+
$HF+X"F_tFF#!/6)[&e9`AFdsFJ#"-**H^e=CF\sFO#!-$QD*>jcFisFS#!-`')Qh4?FisFV#"-(fKY
<:"FirFY#"+xas-6F_tFZ#!+@W`F6F]rFgn#"+$G@:;"F_tF[o#!0B7fy701$"0++++++]#F^o#".tx
RL&QBFdu#!-fqP%>(Q"/+++++]7F;,LF%#!,><,S+%FirF)#"(6"=F"*+DJ&>F-#"-(z#*pIQ$".+++
++]#FK#!,Lja_i$F\sF1#!.j7!\H!e&FdsF5#!*R_tC"F]rF:#!+Bk3LP",+++++#F?#"-6f*=.1#Fi
rF\t#!)ZV9qF_tFC#"*<vCb'F_tFF#!/"GYcnU6""/++++++]FJ#!,H#>+xH",+++++&FO#!,J'**\>
=FgwFS#"-(\!)*z<ZFisFV#!-hq89WKFisFY#")r)[W'"*++++#FZ#")VgZCFbrFgn#!(6t='")+++S
F[o#".^K&yDQHFdwF^o#!/nl1XM#\#Fds#"-V"\.ST$FiuF;,LF%#!-.,GI,")FdsF)#"/H%[g?6w"F
dsF-#!0hY?L3rz$"2++++++]7$FK#!.nr$pFJ9"/+++++DJF1#!064nn(\D*)"2++++++Dc"F5#!+V.
xBDFirF:#"0Ta(G6L#4"FduF?#"-8ee*)>:"-++]il(*F\t#"-*o>1PY"FisFC#",ZDv*)Q#FisFF#!
2j7np#Hi<d"3+++++++]7FJ#"/FT0)psG&FdsFO#"/Lv!RP6'=F_sFS#"/z3T(H*Q9FdsFV#!/^p-X/
RgFduFY#"-*)[?3r>FisFZ#!,PO!)Qn*FisFgn#!+hf<Uk",+++Dc"F[o#!0`Z.(y*e'yFgzF^o#"18
kG#H9Q*GFgz#"."zG%fv!p"1++++++]iF;6",
I0C_optpose2pt_v2w,6#>%)symbolicGF;62%&_nameG%&_sizeG%#_AG%"iG%#C1G%#C2G%"tG%"R
G%$eqsG%&boffaG%"jG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F^\lC0>6$8$8%6$7$%"UG%"uG7$7
$FfqF67$"")F;@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fj]l6#8'F^\l/Fc_l;F;-%%nopsG6#
Fi]l>Fh^l7#-F[_l6$-I'MatrixG6$%*protectedG%(_syslibG6$F`_lw,6$F)F-F^\l6$%)opera
torG%&arrowGF^\l-&T'6#T%6#,&Fe^lF;*&,&9%F;FerF;F;&&T#F[al6#F;F;F;F^\lF^\l6(Ff\l
Fj]lFh\lFc_lFe\lFi]l6#F66$7'Q!F^\lFer"#P"#s"#O7'FjalFerF[bl"#VF]blFd_l>8(-I$<,>
GFa`l6%-I$<|gr>GFa`l6%&&Fh^l6#F6FealFf^l&FiblFjbl-Ffbl6%Ff^lFhbl&Fibl6#Ffq-Ffbl
6%F[clF^cl&Fibl6#Fgq>8)-Fcbl6%-Ffbl6%&Fibl6#""&Ff^l&Fibl6#""'-Ffbl6%Ff^lFjcl&Fi
bl6#""(-Ffbl6%F]dlFbdl&Fibl6#Fb^l>6$8*8+6$-Fcbl6%F%FKF)-Fcbl6%-Ffbl6%F;Ff^lFf^l
-Ffbl6%Ff^lF-,$F1Fer-Ffbl6%Ff^lF1F->8,7%-I".G6$F``lFa`l6%),&-F]fl6$F\el&&Fh^lFe
al6$;F^\lF^\lF;F;F[elF;%#%TGFablFafl-F]fl6%),&-F]fl6$F\el&Fefl6$FgflF6F;F[elF;F
hflFeclF\glFcr>8-,$-Fcbl6#-F[_l6$)-Fcbl6%-F[_l6$-%%diffG6$&FjelFb_l&F[el6#8./Fc
hl;F;Ffq-F^hl6$F`hlF--F^hl6$F`hlF1Fhfl/Fc_l;F;F6#F;F6>Fjel7&&FjelF^\l-&I.Linear
AlgebraG6$F``lFa`l6#%,DeterminantG6#&Fbgl6$Fgfl7$FfqFgq-Fail6#&Fbgl6$Fgfl7$FfqF
\dl-Fail6#&Fbgl6$Fgfl7$FgqF\dl>8/-%$mapG6$%'expandGFjel@$Fd^lOFejl>80-%&minusG6
$-%'indetsG6#Fejl-Fb[m6#Fh^l>6$8182-%,poly2matrixG6$FejlF][m>83-%$srtG6$Fi[m-%%
tdegG6#&F][mF^\l6%7#-%/permuteColumnsG6%Fh[mFi[mF^\mFi]lFj]lF^\lF^\lF^\l6#Ff^l6
47'FjalFer"#;F_dlF]bl7'FjalFerFfq"#WF_bl7'FjalFerFfq""*"#X7'FjalFerFddl"#bF_bl7
'FjalFerFddl"#$*F_bl7'FjalFerFfq"#yF_blFh]m7'FjalFerFfqF_blF_bl7'FjalFerFfq"$/"
F_bl7'FjalFerFfq"#)*F_bl7'FjalFerFfq"$^"F_bl7'FjalFerFfq"#CF_bl7'FjalFerFfq"#RF
c]m7'FjalFer"#A"#J"#_7'FjalFerFfq"#QF_bl7'FjalFerFfqF]blF_bl7'FjalFerFfqFg^mF_b
l7'FjalFerFfq"#ZFg^mF^\l
