M7R0
I0F_opt_pnp_hesch7%,J#"$"R"$+&"""%"xG#"#")"$D"%"yG#!$*>"$+#%"zG#!#BF'*$F)""##!$
.'"$]#*&F)F(F-F(#"$`"F8*&F)F(F1F(#""$""%*$F-F5#!$B"F,*&F-F(F1F(#!$d#"%+5*$F1F5#
"$">F8*$F)F>#"$.#F8*&F-F(F)F5#!%n?FF*&F)F5F1F(#"$"HF'*&F-F5F)F(#"$4$F8*(F)F(F-F
(F1F(#"#7F,*&F)F(F1F5#!$*RF'*$F-F>#"$d"F8*&F-F5F1F(#"$^)FF*&F-F(F1F5#!$J"F8*$F1
F>#"$@%FF,J#!""F?F(F)F.F-#!$,(F'F1#!$,*FFF4#F;F'F9#!$Y#F,F<FDF@#"%VEFFFC#!$>"F8
FG#"#PF0FJ#!$*oFFFMFTFP#""'F,FS#"$r%F8FV#F[oF'FYF]oFfn#"#tF8Fin#!$L*F'F\o#"#**F
8F_o#!$$**FF,J#"$8*FFF(F)F2F-FgoF1#"$t&F'F4#F>"")F9FDF<#FIF,F@#F_pF'FC#Fap"$+"F
G#"$"*)FFFJ#"#(*F'FMFdpFPFZFSFjnFV#F^oF,FY#"%j7FFFfn#!$6$F'FinF]qF\o#!%zHFFF_o#
!$R'F86",
I0C_opt_pnp_heschw,6#>%)symbolicGF(65%&_nameG%&_sizeG%#_AG%"iG%"CG%#xxG%#vvG%"j
G%"kG%"lG%#vxG%#vyG%#vzG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FirC3>6$8$8%6$7#%
"cG7#7$"#NF(@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fht6#8'Fir/F_v;F(-%%nopsG6#Fgt>
Fdu7#-Fgu6$-I'MatrixG6$%*protectedG%(_syslibG6$F\vw,6$F)F-Fir6$%)operatorG%&arr
owGFir-&T'6#T%6#,&FauF(*&,&9%F(FdoF(F(&&T#Fgw6#F(F(F(FirFir6(FasFhtFcsF_vF`sFgt
6#F56$7'Q!FirFdoFap"#s"#O7'FfxFdoFap"#VFhxF`v>8(-%(convertG6$&FduFaxI'VectorG6$
F\wF]w>8)7%F)F-F1>8*7,F(F)F-F1F4F9F<F@FCFG?(F_vF(F(F>%%trueG?(8+F_vF(F>Fjy?(8,F
\zF(F>Fjy>Fgy7$&FgyFir*(&FdyF^vF(&Fdy6#F\zF(&Fdy6#F^zF(?(F_vF(F(F>Fjy?(F\zF_vF(
F>Fjy?(F^zF\zF(F>Fjy?(8-F^zF(F>Fjy>Fgy7$Faz**FczF(FdzF(FfzF(&Fdy6#F\[lF(>8.7EFb
uF(FbuFbu,$F)F5F-F1FbuFbuFbu,$F4F>,$F9F5,$F<F5F@FCFGFbuFbuFbuFbu,$FJF?,$FMF>,$F
PF>,$FSF5,$FVF5,$FYF5FfnFinF\oF_oFbuFbuFbuFbuFbu>8/7EFbuFbuF(FbuFbuF)Fbu,$F-F5F
1FbuFbuF4FbuFg[lF<Fbu,$F@F>,$FCF5FGFbuFbuFJFbu,$FMF5FPFbu,$FSF>F]\lFYFbu,$FfnF?
,$FinF>,$F\oF5F_oFbu>807EFbuFbuFbuF(FbuFbuF)FbuF-,$F1F5FbuFbuF4FbuF9Fh[lFbuF@Fd
\l,$FGF>FbuFbuFJFbuFM,$FPF5FbuFSF]\l,$FYF>FbuFfn,$FinF5,$F\oF>,$F_oF?>817%-I".G
6$F\wF]w6$)-Fay6#Fc[l%#%TGF\y-Fh]l6$)-Fay6#F`\lF^^lF\y-Fh]l6$)-Fay6#F[]lF^^lF\y
>82-%$mapG6$%'expandGFe]l@$F`uOFj^l>83-%&minusG6$-%'indetsG6#Fj^l-Fg_l6#Fdu>6$8
485-%,poly2matrixG6$Fj^lFb_l>86-%$srtG6$F^`l-%%tdegG6#&Fb_lFir6&7#-%/permuteCol
umnsG6%F]`lF^`lFc`lFc`lFgtFhtFirFirFir6#Fbu6>7'FfxFdo"#;FepFhx7'FfxFdoF>"#LFjx7
'FfxFdoF>""*"#X7'FfxFdo""("#bFjx7'FfxFdoFjal"#$*Fjx7'FfxFdoF>"#HFjx7'FfxFdoF>"#
<Fjx7'FfxFdoF>"#]Fjx7'FfxFdoF>FgqFgq7'FfxFdoFjalFXFgq7'FfxFdo"#6FcalFgq7'FfxFdo
"#:FhalFjxFdblFeblFfbl7'FfxFdoFibl"#?Fgq7'FfxFdo"#>F[blFjx7'FfxFdoF>"$z"FjxF^cl
F^cl7'FfxFdoF>"#dFjx7'FfxFdoF>"#CFjx7'FfxFdoF>"#RFhal7'FfxFdo"#A"#J"#_7'FfxFdoF
>"#QFjx7'FfxFdoF>FhxFjx7'FfxFdoF>FhclFjx7'FfxFdoF>"#^FhclFir
