M7R0
I0F_optpose4pt_v27',H%"vG#!#@"$+#%"xG#"$h)"%DJ%"yG#!'hdx"(+]7$%"zG#"&T(p"']7y*$
F%""##""$"")*&F1"""F%F;#!%j**"&Dc"*&F-F;F%F;#"'B36"&+D'*&F)F;F%F;#!$Y#"$D"*&F-F
;F1F;#")*e&4o"*++++&*&F-F;%"wGF;#"'dIN"'++]*&F1F;FLF;#"'2YDFO*$FLF6F7*&F)F;F-F;
#!&F#["&]7$*&F)F;F1F;#"&zf"FO*&F)F;FLF;#!$d#"$+&*$F)F6#"$">"$]#*$F-F6#"(4j4)")+
++5*$F1F6#"*."yXB"+++++5#"$Z""&++#F;,HF%#"'rWM"'++DF)#!&Hl%"'+]7F-#!)<6mE"*+++D
"F1#"(r#f#*")+++DF5#"$"))"%+5F:#"&"oB"&++&F?#!&(=oF[pFC#!$>"F\oFG#"(joF#"(++]#F
K#!&fq(FjpFP#!&6h)FBFSFepFT#!%ZpF[pFX#!%>]"%]iFen#"#P"$+"Fin#"$(HFgpF]o#"*ZRp*=
"*+++]#Fao#")`1G**Fap#"*h")oM"FbrF;,HF%#!$.#"%+?F)#"$*oFjrF-#!'*[Q"FOF1#!&Ze""(
+++"F5#"$.#FgpF:#"&Ze"F[pF?#"'*[Q"F^pFC#!$*oFhnFG#!(t0P""(++D'FK#!&dE)F[pFP#"%V
'*FWFSFbsFT#!'\k7F^pFX#"&()=$F^pFen#"#(*F\oFin#"$4$FhnF]o#"*2hc."FbrFao#")VDx9F
ap#Fcs"&+g"F;,HF%#"%RFFWF)#!'(Gk$FOF-#!)6ftbFbrF1#"*(=l`DFJF5#""'FFF:#"'*pz#FOF
?#!&Z5'F[pFC#!$*RFhnFG#")^SxQFbrFK#"%jR"&+D"FP#!'HP6F^pFSFhuFT#!&6**)F[pFX#!'>(
)yFOFen#"$d"FFFin#"$^)FgpF]o#!)8q`TFbrFao#"*j#>%Q""*++++##"(22]#")++]iF;z)6$F-F
1[[[[[_[[[[sF;][[[[[[[[[sF;!!""6",
I0C_optpose4pt_v2w,6#>%)symbolicGF;6/%&_nameG%&_sizeG%#_AG%"iG%"CG%"tG%"RG%$eqs
G%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FjwC0>6$8$8%6$7$%"UG%"uG7$7$F8""%7$"#;F;@%/9$"
"!>8&7#-%$seqG6$-%'rndMatG6#&&Fcy6#8'Fjw/F][l;F;-%%nopsG6#Fby>Fbz7#-Fez6$-I'Mat
rixG6$%*protectedG%(_syslibG6$Fjzw,6$F)F-Fjw6$%)operatorG%&arrowGFjw-&T'6#T%6#,
&F_zF;*&,&9%F;FiwF;F;&&T#Fe\l6#F;F;F;FjwFjw6(FbxFcyFdxF][lFaxFby6#F66$7'Q!FjwFi
wF\r"#s"#O7'Fd]lFiwF\r"#VFf]lF^[l>&8(F_]l-I$<,>GF[\l6%-I$<|gr>GF[\l6%&&Fbz6#F6F
_]lF`z&Fc^lFd^l-F`^l6%F`zFb^l&Fc^l6#F8-F`^l6%Fe^lFh^l&Fc^l6#Fjy>&F[^lFd^l-F]^l6
%-F`^l6%&Fc^l6#""&F`z&Fc^l6#Fiu-F`^l6%F`zFd_l&Fc^l6#""(-F`^l6%Fg_lF[`l&Fc^l6#F9
>&F[^lFi^l-F]^l6%-F`^l6%&Fc^l6#""*F`z&Fc^l6#"#5-F`^l6%F`zFh`l&Fc^l6#"#6-F`^l6%F
[alF`al&Fc^l6#"#7>&F[^lF]_l-F]^l6%-F`^l6%&Fc^l6#"#8F`z&Fc^l6#"#9-F`^l6%F`zF^bl&
Fc^l6#"#:-F`^l6%FablFfbl&Fc^l6#F\z>6$8)8*6$-F]^l6%F%FLF)-F]^l6%-F`^l6%F;F`zF`z-
F`^l6%F`zF-,$F1Fiw-F`^l6%F`zF1F->8+7$-Fez6$-I".G6$Fj[lF[\l6%),&-Fcdl6$F`cl&&Fbz
F_]l6$;FjwFjwF][lF;F_clF;%#%TG&F[^lF\[lFgdl/F][l;F;FjyFgw>8,-%$mapG6$%'expandGF
^dl@$F^zOFcel>8--%&minusG6$-%'indetsG6#Fcel-F`fl6#Fbz>6$8.8/-%,poly2matrixG6$Fc
elF[fl>80-%$srtG6$Fgfl-%%tdegG6#&F[flFjw6&7#-%/permuteColumnsG6%FfflFgflF\glF\g
lFbyFcyFjwFjwFjw6#F`z647'Fd]lFiwF\zFiuFf]l7'Fd]lFiwF8"#XFh]l7'Fd]lFiwF8Fj`lF]hl
7'Fd]lFiwF]`l"#bFh]l7'Fd]lFiwF]`l"#$*Fh]l7'Fd]lFiwF8"#!)Fh]lFchl7'Fd]lFiwF8"#&)
Fh]l7'Fd]lFiwF8"#()Fh]l7'Fd]lFiwF8Fh]lFh]l7'Fd]lFiwF8"#xFh]l7'Fd]lFiwF8"#CFh]l7
'Fd]lFiwF8"#RF]hl7'Fd]lFiw"#A"#J"#_7'Fd]lFiwF8"#QFh]l7'Fd]lFiwF8Ff]lFh]l7'Fd]lF
iwF8FbilFh]l7'Fd]lFiwF8"#^FbilFjw
