M7R0
I0F_optpose4pt_v27',H%"vG#!#@"$+#%"xG#"$h)"%DJ%"yG#!'hdx"(+]7$%"zG#"&T(p"']7y*$
F%""##""$"")*&F1"""F%F;#!%j**"&Dc"*&F-F;F%F;#"'B36"&+D'*&F)F;F%F;#!$Y#"$D"*&F-F
;F1F;#")*e&4o"*++++&*&F-F;%"wGF;#"'dIN"'++]*&F1F;FLF;#"'2YDFO*$FLF6F7*&F)F;F-F;
#!&F#["&]7$*&F)F;F1F;#"&zf"FO*&F)F;FLF;#!$d#"$+&*$F)F6#"$">"$]#*$F-F6#"(4j4)")+
++5*$F1F6#"*."yXB"+++++5#"$Z""&++#F;,HF%#"'rWM"'++DF)#!&Hl%"'+]7F-#!)<6mE"*+++D
"F1#"(r#f#*")+++DF5#"$"))"%+5F:#"&"oB"&++&F?#!&(=oF[pFC#!$>"F\oFG#"(joF#"(++]#F
K#!&fq(FjpFP#!&6h)FBFSFepFT#!%ZpF[pFX#!%>]"%]iFen#"#P"$+"Fin#"$(HFgpF]o#"*ZRp*=
"*+++]#Fao#")`1G**Fap#"*h")oM"FbrF;,HF%#!$.#"%+?F)#"$*oFjrF-#!'*[Q"FOF1#!&Ze""(
+++"F5#"$.#FgpF:#"&Ze"F[pF?#"'*[Q"F^pFC#!$*oFhnFG#!(t0P""(++D'FK#!&dE)F[pFP#"%V
'*FWFSFbsFT#!'\k7F^pFX#"&()=$F^pFen#"#(*F\oFin#"$4$FhnF]o#"*2hc."FbrFao#")VDx9F
ap#Fcs"&+g"F;,HF%#"%RFFWF)#!'(Gk$FOF-#!)6ftbFbrF1#"*(=l`DFJF5#""'FFF:#"'*pz#FOF
?#!&Z5'F[pFC#!$*RFhnFG#")^SxQFbrFK#"%jR"&+D"FP#!'HP6F^pFSFhuFT#!&6**)F[pFX#!'>(
)yFOFen#"$d"FFFin#"$^)FgpF]o#!)8q`TFbrFao#"*j#>%Q""*++++##"(22]#")++]iF;z)6$F-F
1[[[[[_[[[[sF;][[[[[[[[[sF;!!""6",
I0C_optpose4pt_v2w,6#>%)symbolicGF;6/%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$
_V0G%#_VG%"iG%"CG%"tG%"RG%$eqsG6"FjwC0>6$8$8%6$7$%"UG%"uG7$7$F8""%7$"#;F;@%/9$F
;>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fcy6#8,w,6$F)F-Fjw6
$%)operatorG%&arrowGFjw-&T'6#T%6#,&F_zF;*&,&9%F;FiwF;F;&&T#Fj[l6#F;F;F;FjwFjw6(
FbxFcyFixFa[lFaxFby6#F66$7'Q!FjwFiw"#R"#u"#O7'Fi\lFiwFj\l"#XF\]l/Fa[l;F;-%%nops
G6#Fby>Faz7#-Fdz6$-%'rndMatG6#F\[lF_]l>&8-Fd\l-I$<,>GFjz6%-I$<|gr>GFjz6%&&Faz6#
F6Fd\l""!&Fe^lFf^l-Fb^l6%Fg^lFd^l&Fe^l6#F8-Fb^l6%Fh^lF[_l&Fe^l6#Fjy>&F]^lFf^l-F
_^l6%-Fb^l6%&Fe^l6#""&Fg^l&Fe^l6#Fiu-Fb^l6%Fg^lFg_l&Fe^l6#""(-Fb^l6%Fj_lF^`l&Fe
^l6#F9>&F]^lF\_l-F_^l6%-Fb^l6%&Fe^l6#""*Fg^l&Fe^l6#"#5-Fb^l6%Fg^lF[al&Fe^l6#"#6
-Fb^l6%F^alFcal&Fe^l6#"#7>&F]^lF`_l-F_^l6%-Fb^l6%&Fe^l6#"#8Fg^l&Fe^l6#"#9-Fb^l6
%Fg^lFabl&Fe^l6#"#:-Fb^l6%FdblFibl&Fe^l6#F\z>6$8.8/6$-F_^l6%F%FLF)-F_^l6%-Fb^l6
%F;Fg^lFg^l-Fb^l6%Fg^lF-,$F1Fiw-Fb^l6%Fg^lF1F->807$-Fdz6$-I".G6$FizFjz6%),&-Ffd
l6$Fccl&&FazFd\l6$;FjwFjwFa[lF;FbclF;%#%TG&F]^lF`[lFjdl/Fa[l;F;FjyFgw>8'-%$mapG
6$%'expandGFadl@$0F_zF;OFfel>8(-%&minusG6$-%'indetsG6#Ffel-Fdfl6#Faz>6$8)8*-%,p
oly2matrixG6$FfelF_fl>8+-%$srtG6$F[gl-%%tdegG6#-F][l6#F_fl6%7$%#cfG-%/permuteCo
lumnsG6%FjflF[glF`glFbyFcyFjwFjwFjw6#Fg^l647'Fi\lFiwF\zFiuF\]l7'Fi\lFiwF8F^]l"#
V7'Fi\lFiwF8F]alF^]l7'Fi\lFiwF``l"#&*Fchl7'Fi\lFiwF``l"#dFchl7'Fi\lFiwF8"#')Fch
lFihl7'Fi\lFiwF8"#"*Fchl7'Fi\lFiwF8"#$*Fchl7'Fi\lFiwF8"#\Fchl7'Fi\lFiwF8"#yFchl
7'Fi\lFiwF8"#CFchl7'Fi\lFiwF8"#SF^]l7'Fi\lFiw"#B"#K"#_7'Fi\lFiwF8"#QFchl7'Fi\lF
iwF8F\]lFchl7'Fi\lFiwF8"#LFchl7'Fi\lFiwF8"#`"#JFjw
