M7R0
I0F_optpose4pt_v27',H%"xG#"$h)"%DJ%"vG#!#@"$+#%"yG#!'hdx"(+]7$%"zG#"&T(p"']7y*$
F)""##""$"")*&F1"""F)F;#!%j**"&Dc"*&F-F;F)F;#"'B36"&+D'*&F%F;F)F;#!$Y#"$D"*&F-F
;F1F;#")*e&4o"*++++&*&F-F;%"wGF;#"'dIN"'++]*&F1F;FLF;#"'2YDFO*$FLF6F7*&F%F;F-F;
#!&F#["&]7$*&F%F;F1F;#"&zf"FO*&F%F;FLF;#!$d#"$+&*$F%F6#"$">"$]#*$F-F6#"(4j4)")+
++5*$F1F6#"*."yXB"+++++5#"$Z""&++#F;,HF%#!&Hl%"'+]7F)#"'rWM"'++DF-#!)<6mE"*+++D
"F1#"(r#f#*")+++DF5#"$"))"%+5F:#"&"oB"&++&F?#!&(=oF^pFC#!$>"F\oFG#"(joF#"(++]#F
K#!&fq(FjpFP#!&6h)FBFSFepFT#!%ZpF^pFX#!%>]"%]iFen#"#P"$+"Fin#"$(HFgpF]o#"*ZRp*=
"*+++]#Fao#")`1G**Fap#"*h")oM"FbrF;,HF%#"$*o"%+?F)#!$.#FjrF-#!'*[Q"FOF1#!&Ze""(
+++"F5#"$.#FgpF:#"&Ze"F^pF?#"'*[Q"F[pFC#!$*oFhnFG#!(t0P""(++D'FK#!&dE)F^pFP#"%V
'*FWFSFbsFT#!'\k7F[pFX#"&()=$F[pFen#"#(*F\oFin#"$4$FhnF]o#"*2hc."FbrFao#")VDx9F
ap#Fcs"&+g"F;,HF%#!'(Gk$FOF)#"%RFFWF-#!)6ftbFbrF1#"*(=l`DFJF5#""'FFF:#"'*pz#FOF
?#!&Z5'F^pFC#!$*RFhnFG#")^SxQFbrFK#"%jR"&+D"FP#!'HP6F[pFSFhuFT#!&6**)F^pFX#!'>(
)yFOFen#"$d"FFFin#"$^)FgpF]o#!)8q`TFbrFao#"*j#>%Q""*++++##"(22]#")++]iF;z)6$F-F
1[[[[[_[[[[sF;][[[[[[[[[sF;!!""6",
I0C_optpose4pt_v2t+6#>%)symbolicGF;6-%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%#V
0G%"VG%"CG%"tG%"RG6"FjwC0>6$8$8%6$7$%"UG%"uG7$7$F8""%7$"#;F;@%/9$F;>8&-%$seqG6$
-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fay6#%"iGf*6$F%F-Fjw6$%)operatorG%
&arrowGFjw-&T%F][l6#,&F]zF;*&,&9%F;FiwF;F;&&T#F][l6#F;F;F;FjwFjw6&FbxFayFaxF`y/
F^[l;F;-%%nopsG6#F`y>F_z-Faz6$-%'rndMatG6#FizFa\l>&8,F_\l-I$<,>GFgz6%-I$<|gr>GF
gz6%&&F_z6#F6F_\l""!&Ff]lFg]l-Fc]l6%Fh]lFe]l&Ff]l6#F8-Fc]l6%Fi]lF\^l&Ff]l6#Fhy>
&F^]lFg]l-F`]l6%-Fc]l6%&Ff]l6#""&Fh]l&Ff]l6#Fiu-Fc]l6%Fh]lFh^l&Ff]l6#""(-Fc]l6%
F[_lF__l&Ff]l6#F9>&F^]lF]^l-F`]l6%-Fc]l6%&Ff]l6#""*Fh]l&Ff]l6#"#5-Fc]l6%Fh]lF\`
l&Ff]l6#"#6-Fc]l6%F_`lFd`l&Ff]l6#"#7>&F^]lFa^l-F`]l6%-Fc]l6%&Ff]l6#"#8Fh]l&Ff]l
6#"#9-Fc]l6%Fh]lFbal&Ff]l6#"#:-Fc]l6%FealFjal&Ff]l6#Fjy>6$8-8.6$-F`]l6%F)FLF%-F
`]l6%-Fc]l6%F;Fh]lFh]l-Fc]l6%Fh]lF-,$F1Fiw-Fc]l6%Fh]lF1F->8'7$-Faz6$-I".G6$FfzF
gz6%),&-Fgcl6$Fdbl&&F_zF_\l6$;FjwFjwF^[lF;FcblF;%#%TG&F^]lF][lF[dl/F^[l;F;FhyFg
w>Fbcl-%$mapG6$%'expandGFbcl@$/F]zFh]lOFbcl>8(-%&minusG6$-%'indetsG6#Fbcl-Fdel6
#7#F_z>6$8)8*-%,poly2matrixG6%Fbcl-Fd\lFeelF_el>8+-%$srtG6$F\fl-%%tdegG6#-Fjz6#
F_el6%7$%#cfG-%/permuteColumnsG6%F[flF\flFbflF`yFayFjwFjwFjw6#Fh]lFjw
