M7R0
I0F_opt_pnp_hesch7%,J#"$"R"$+&"""%"xG#"#")"$D"%"yG#!$*>"$+#%"zG#!#BF'*$F)""##!$
.'"$]#*&F)F(F-F(#"$`"F8*&F)F(F1F(#""$""%*$F-F5#!$B"F,*&F-F(F1F(#!$d#"%+5*$F1F5#
"$">F8*$F)F>#"$.#F8*&F-F(F)F5#!%n?FF*&F)F5F1F(#"$"HF'*&F-F5F)F(#"$4$F8*(F)F(F-F
(F1F(#"#7F,*&F)F(F1F5#!$*RF'*$F-F>#"$d"F8*&F-F5F1F(#"$^)FF*&F-F(F1F5#!$J"F8*$F1
F>#"$@%FF,J#!""F?F(F)F.F-#!$,(F'F1#!$,*FFF4#F;F'F9#!$Y#F,F<FDF@#"%VEFFFC#!$>"F8
FG#"#PF0FJ#!$*oFFFMFTFP#""'F,FS#"$r%F8FV#F[oF'FYF]oFfn#"#tF8Fin#!$L*F'F\o#"#**F
8F_o#!$$**FF,J#"$8*FFF(F)F2F-FgoF1#"$t&F'F4#F>"")F9FDF<#FIF,F@#F_pF'FC#Fap"$+"F
G#"$"*)FFFJ#"#(*F'FMFdpFPFZFSFjnFV#F^oF,FY#"%j7FFFfn#!$6$F'FinF]qF\o#!%zHFFF_o#
!$R'F86",
I0C_opt_pnp_heschw,6#>%)symbolicGF(65%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$
_V0G%#_VG%"iG%"CG%#xxG%#vvG%"jG%"kG%"lG%#vxG%#vyG%#vzG%$eqsG6"FirC3>6$8$8%6$7#%
"cG7#7$"#NF(@%/9$F(>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F
ht6#8,w,6$F)F-Fir6$%)operatorG%&arrowGFir-&T'6#T%6#,&FauF(*&,&9%F(FdoF(F(&&T#F
\w6#F(F(F(FirFir6(FasFhtFhsFcvF`sFgt6#F56$7'Q!FirFdo"#R"#u"#O7'F[xFdoF\x"#XF^x/
Fcv;F(-%%nopsG6#Fgt>Fcu7#-Ffu6$-%'rndMatG6#F^vFax>8--%(convertG6$&FcuFfwI'Vecto
rG6$F[vF\v>8.7%F)F-F1>8/7,F(F)F-F1F4F9F<F@FCFG?(FcvF(F(F>%%trueG?(80FcvF(F>F\z?
(81F^zF(F>F\z>Fiy7$-F_v6#Fiy*(&FfyFbvF(&Ffy6#F^zF(&Ffy6#F`zF(?(FcvF(F(F>F\z?(F^
zFcvF(F>F\z?(F`zF^zF(F>F\z?(82F`zF(F>F\z>Fiy7$Fcz**FfzF(FgzF(FizF(&Ffy6#F_[lF(>
837E""!F(Fh[lFh[l,$F)F5F-F1Fh[lFh[lFh[l,$F4F>,$F9F5,$F<F5F@FCFGFh[lFh[lFh[lFh[l
,$FJF?,$FMF>,$FPF>,$FSF5,$FVF5,$FYF5FfnFinF\oF_oFh[lFh[lFh[lFh[lFh[l>847EFh[lFh
[lF(Fh[lFh[lF)Fh[l,$F-F5F1Fh[lFh[lF4Fh[lF[\lF<Fh[l,$F@F>,$FCF5FGFh[lFh[lFJFh[l,
$FMF5FPFh[l,$FSF>Fa\lFYFh[l,$FfnF?,$FinF>,$F\oF5F_oFh[l>857EFh[lFh[lFh[lF(Fh[lF
h[lF)Fh[lF-,$F1F5Fh[lFh[lF4Fh[lF9F\\lFh[lF@Fh\l,$FGF>Fh[lFh[lFJFh[lFM,$FPF5Fh[l
FSFa\l,$FYF>Fh[lFfn,$FinF5,$F\oF>,$F_oF?>867%-I".G6$F[vF\v6$)-Fcy6#Ff[l%#%TGF^y
-F\^l6$)-Fcy6#Fd\lFb^lF^y-F\^l6$)-Fcy6#F_]lFb^lF^y>8'-%$mapG6$%'expandGFi]l@$0F
auF(OF^_l>8(-%&minusG6$-%'indetsG6#F^_l-F\`l6#Fcu>6$8)8*-%,poly2matrixG6$F^_lFg
_l>8+-%$srtG6$Fc`l-%%tdegG6#-F_v6#Fg_l6%7$%#cfG-%/permuteColumnsG6%Fb`lFc`lFh`l
FgtFhtFirFirFir6#Fh[l6>7'F[xFdo"#;FepF^x7'F[xFdoF>"#L"#V7'F[xFdoF>""*F`x7'F[xFd
o""("#&*F]bl7'F[xFdoFabl"#dF]bl7'F[xFdoF>"#HF]bl7'F[xFdoF>"#<F]bl7'F[xFdoF>"#]F
]bl7'F[xFdoF>FgqFgq7'F[xFdoFablFXFgq7'F[xFdo"#6FjalFgq7'F[xFdo"#:"#ZF]blF[clF\c
lF]cl7'F[xFdoF`cl"#?Fgq7'F[xFdo"#>FdblF]bl7'F[xFdoF>"$z"F]blFfclFfcl7'F[xFdoF>"
#gF]bl7'F[xFdoF>"#CF]bl7'F[xFdoF>"#SF`x7'F[xFdo"#B"#K"#_7'F[xFdoF>"#QF]bl7'F[xF
doF>F^xF]blF[bl7'F[xFdoF>"#`"#JFir
