M7R0
I0F_p4p_fr_iccv177+,J%"xG#"%"G("'++?%"yG#"'BT\"'++]%"zG#"'fy`"(+++"%"wG#"&V#H"'
+]7*&F1"""F%F6#"&xd#"'++D*&F1F6F)F6#!(*>46F0*&F1F6F-F6#!'>0?F0*$F%""##"'Fr?F0*&
F)F6F%F6#!',$R"F(*&F%F6F-F6#!'>'["F9*&F1F6F%FA#!&zm#F,*$F)FA#"'6**GF,*&F)F6F-F6
#"'LZ?F(*&F)FAF1F6#!'R&o"F(*$F-FA#"'"=t#F0*&F-FAF1F6#!&Lh)F,*(F%F6F1F6F)F6#"'rH
8F9*(F-F6F%F6F1F6#!'"fu#F,*(F-F6F)F6F1F6#"(.76"F0#!&"Q5"&++&F6,JF%#"'6$)=F(F)#!
'VLAF9F-#!'\e6F,F1#"'"\z&F,F5#!&<:""&+D'F:#"'hb6"'++5F=#!'hI9F`pF@#!(\S7"F0FD#"
'(3!RF9FG#"'LQNF0FJ#!',XRF,FM#!'>JDF9FP#!'(RN#F,FS#"'j!H#F0FV#"'z*[$F,FY#!&*zOF
,Ffn#"&RF$F(Fin#!'*yM"F4F\o#!&,X'F`p#"&`w$F(F6,6F%#"'(3D%F0F)#!'Le$)F,F-#!'\Q>F
,F@#!&\b#F4FD#"',(4#F9FG#"&$)>$F,FM#!&(*)eFaoFP#"&x`)F4FV#"'4q7F,#!'$oA#F0F6,6F
%#!'*pE$F,F)#"(,()H"F,F-#!'>^PF,F@#"&ZD)F]pFD#!$B&F]pFG#"'Vr\F9FM#!',tGF(FP#!'2
EVF9FV#"&n=$Fao#!'2;WF0F6,\pF%#!*d`X#p"+++++5F)#"*$o5P8FjtF-#"($y@')")++]iF1#!)
t^OfF_uF5#"*Faox""*++++&F:#!(.u1""(+++%F=#"*j(p3VFduF@#"),Pt<")++DJFD#!+(GD]V"F
jtFG#!)2)**R&FduFJ#"*F)Q"4""*++++"FM#"+Br*)R8FjtFP#"*@Nn3#"*+++]#FS#!($o>!*"(++
+)FV#!'nzC"(++D'FY#!(T9c("*+++D"*&F%FAF)F6#"*$f$f=$Fhv*&F%FAF-F6#!(HtZ"Fhv*&F%"
"$F1F6#!)nB'3$F_u*&F%F6F)FA#!+Bt,(G"Fjt*&F-FAF%F6#"(B(zFFaw*&F-F6F)FA#"*<([E7"*
++++#*&F)FiwF1F6#!*Hhb(GFex*&F-FAF)F6#"*JdP(=Fdu*&F-FiwF1F6#!(>'Q&*")+++]**F%F6
F)F6F1F6F-F6#"),kRrF_uFfn#!*d1*o6FduFin#"*nX&)o&FduF\o#!*$y_K:Faw*(F%FAF1F6F)F6
#"*Tnn9"Faw*(F%FAF1F6F-F6#!)n]DiF_y*(F%F6F)F6F-F6#!*@/i*>Fdu*(F%F6F)FAF1F6#"*hN
_&=Fhv*(F%F6F-FAF1F6#!(fw#eF^w*(F)FAF1F6F-F6#!)(o7!yFdu*(F)F6F-FAF1F6#")xkgqFhv
*$F%Fiw#!'d2V")++]7*$F)Fiw#!*<%y<5Fdu*$F-Fiw#")H[0JFhv#")pRI))FduF6,\pF%#!)F!4;
$FduF)#"+$HqM."FjtF-#")4g5_FcvF1#")*eHi"")+++?F5#!)\7(y"FexF:#")(e]g#FexF=#!*.!
=#z"FduF@#")`Pm$*FjtFD#!*h=hc'FjtFG#!*`PyD)FjtFJ#!*r]#pEFhvFM#"*<8V+&FjtFP#"+xt
&QZ"FjtFS#")$efl"")+++SFV#"(fiz#"(+D"yFY#!*<+&[iFduFbw#!)fw<vFhvFew#"'VG"*FguFh
w#"(`O!o")+]i:F\x#!)*)H4^FhvF_x#!("=3\F_uFbx#"*Vol:%FduFfx#"(*p1**Fa[lFix#!)$*4
m$*FduF\y#"*JW+T"FhvF`y#!*B&[;')FduFfn#"*zGCj$FjtFin#!*Zu@V"F_uF\o#")(\Wt"F\vFi
y#!)\)o'[F_uF\z#")(zn!)*F_uF_z#!*zO8D"FcvFbz#!*Z@h+$FduFez#"*Fd#)H%FhvFhz#!*H"*
3V"FhvF[[l#!*")RrF&FduF^[l#!)`*\^"FawFb[l#"**QedyFjtFe[l#!*rg02"Fdu#")z9M"*FjtF
6,\pF%#!*"fS\AFjtF)#!).%*QMFjtF-#"**yzkEFduF1#")Hw-\FjtF5#"*4K`5%FduF:#!(8hd(Fd
^lF=#")*yoT*FjtF@#!(R$QMFduFD#"*Prb"oFduFG#!)8K`#)FexFJ#!)>+F>")+++DFM#!+d%*Q28
FjtFP#"*jQnv$FjtFS#!(^a[$FguFV#"*6'>hKFjtFY#!*>0;)RFduFbw#!*z>.)yFjtFew#!'zayF[
^lFhw#"(6oG#Fa[lF\x#")neoaFfblF_x#")d'f$HFduFbx#!*h\%RMFduFfx#!)<8*o%FexFix#"($
G(R*FawF\y#")2DU7F_uF`y#!*L$\z(*FduFfn#"+^M2VCFjtFin#!*Fr9!yFduF\o#"+$*fbo6FjtF
iy#!*8Dk9'FduF\z#")h_:\FawF_z#"*T5QP#FjtFbz#"+2c'\!>FjtFez#")fo]=F_yFhz#"*H_/*z
FduF[[l#!)hcg<F\vF^[l#"($epgF_uFb[l#!*Jeta&FduFe[l#!)j0_TFdu#"(hU4"F^wF6,\pF%#!
*x+CO'FjtF)#"*<5+G$FduF-#")Bz0ZFcvF1#!*.5LJ#FhvF5#!*"4**GAFduF:#"*@TpT"FexF=#"*
PZ;(**FjtF@#"*hriL&FjtFD#!*$y@1BFjtFG#")Bl%Q"FcvFJ#"*j^c<$FhvFM#!*<]W<"F_uFP#!*
\r/_$FexFS#!)"e'GDFawFV#!*6p2V%FjtFY#!)2v'*>FcvFbw#!*FTO7"FexFew#!*$RRRDFduFhw#
"(*o?aFawF\x#!*8x&))>FduF_x#!).ud5F_uFbx#"*">KlFFduFfx#"*V]#**=FhvFix#")\+<MFex
F\y#!(V>)HFawF`y#")`crkFawFfn#!)(*)e8'FcvFin#"*B`uN(FduF\o#!**y#f>'FduFiy#"),yZ
RF_uF\z#!*P!py9FhvF_z#!**>ii;FduFbz#!*tU=%>FexFez#!*,l%*["FhvFhz#"*2?)))eFjtF[[
l#")h>.:FfblF^[l#")2W7NFhvFb[l#")(RK)eF_uFe[l#")^pB>Fdu#"(Bq>'FjtF6,\pF%#")z%G@
%FcvF)#!*T$Gq()FjtF-#")(e()["FjtF1#"(Vf*RF^wF5#")(\6r(FcvF:#!*nF!3iFduF=#!)`I@X
FawF@#!*"*z&4LFduFD#"*`&3xbFduFG#!*(ybHYFjtFJ#!)hS_aFh]lFM#"(f3@)FhvFP#"+4x1O7F
jtFS#!*nTpv&FjtFV#"*T,>t"FduFY#!*tYG1%FduFbw#!)$\PJ#FcvFew#")"zU?(FhvFhw#"(Ja"f
FawF\x#"+F*[rs"FjtF_x#"*hbt[#FduFbx#!+$*\(y."FjtFfx#!*Ji"[HFduFix#")x*\W&FduF\y
#")@@t!)FhvF`y#!*$[%Gw%FhvFfn#")t%*)o)F_yFin#!+pss\7FduF\o#"(2W8)"(]i!RFiy#!*h'
>LcFduF\z#"*@L/U$FduF_z#")ZPUaF_yFbz#"*B$\&Q%FhvFez#"**p$)RVFduFhz#")$pA)HFfblF
[[l#!)R-<VF_uF^[l#!&BI#F]_mFb[l#!**f<%*>FawFe[l#"(49%oFdu#"*P&*y7"FduF66",
I0C_p4p_fr_iccv17w,6#>%)symbolicGF66/%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$
_V0G%#_VG%"iG%$P12G%#P3G%"PG%$eqsG6"Fd`mC/>6$8$8%6$7$%"NG%"BG7$7$"")""%7$FebmFd
bm@%/9$F6>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F]bm6#8,w,6
$F%F)Fd`m6$%)operatorG%&arrowGFd`m-&T'6#T%6#,&FibmF6*&,&9%F6!""F6F6&&T#Fddm6#F6
F6F6Fd`mFd`m6(F\amF]bmFcamF[dmF[amF\bm6#FA6$7'Q!Fd`mF[em"#R"#u"#O7'FdemF[emFeem
"#XFgem/F[dm;F6-%%nopsG6#F\bm>F[cm7#-F^cm6$-%'rndMatG6#FfcmFjem>8--I".G6$FccmFd
cm6$&F[cmF_em-I$<,>GFdcm6&F%F)F-F6>Fgfm-I$<|gr>GFdcm6&-F^gm6$&FgfmF_em&Fgfm6#FA
-F^gm6$&Fgfm6#Fiw&Fgfm6#Febm-F^gm6$&Fgfm6#""&&Fgfm6#""'-F^gm6$&Fgfm6#""(&Fgfm6#
Fdbm>8.-Fifm6$&F[cmFhgm-F^gm6*F%F)F-F5F:F=F1F6>8/-F^gm6$Fgfm)F_im%#%TG>807+z)6(
&Ffim6$FAF6&Ffim6$FAFA&Ffim6$FAFiw&Ffim6$FiwF6&Ffim6$FiwFA&Ffim6$FiwFiw[[[[_[[[
[[[][sF6[[][[[[[[\[[[sF6\[[[[[c[[[[[[sF6z)6(&Ffim6$F6F6&Ffim6$F6FA&Ffim6$F6FiwF
fjmFhjmFjjm[[[[_[[[[[[][sF6[[][[[[[[\[[[sF6\[[[[[c[[[[[[sF6z)6(F^[nF`[nFb[nF`jm
FbjmFdjm[[[[_[[[[[[][sF6[[][[[[[[\[[[sF6\[[[[[c[[[[[[sF6z/Fe[n[[[[[[[[[[[_[sF6[
[[[[[[[[][[[sF6[[[[[[[\[[[[[sF6[[[[c[[[[[[[[sF[em[[_[[[[[[[[[[sF[em][[[[[[[[[[[
[sF[emz-6)F`[nFb[nF`jmFbjmFdjmFhjmFjjm\[[[[[[[[[\[\[nF[em[[\[[[[[[[][[[nF6[[\[[
[[[][[[[[nF[em[[\[[[][[[[[[[nF[em\[[[\[\[[[[[[[nF[emz-Fh[n\[[[[[[[[[[[][nF[em[[
\[[[[[[[\[\[nF6\[[[[[[[][[[[[nF6[[\[\[\[[[[[[[nF6\[[[][[[[[[[[[nF6z+6*F^[nF`[nF
b[nF`jmFbjmFdjmFhjmFjjm\[[[[[[[[[_[][nF[em[c[[[[[[c[[[][nF6\[[[[][\[[[[[[nF[em[
c[_[[[\[[[[[[nF6z+6)F^[nFb[nF`jmFbjmFfjmFhjmFjjm\[[[[[[[[[\[\[nF[em[[[[\[[[[[][
[[nF6[[\[[[\[\[[[[[nF6[[[[\[][[[[[[[nF[emz+6*F^[nF`[nFb[nF`jmFbjmFdjmFfjmFjjm\[
[[[[[[[[_[][nF[em[c[[[[[[c[_[[[nF6\[[[[][\[[[[[[nF[em[c[_[][[[[[[[[nF6>8'-%$map
G6$%'expandGF\jm@$0FibmF6OFa\n>8(-%&minusG6$-%'indetsG6#Fa\n-F_]n6#F[cm>6$8)8*-
%,poly2matrixG6$Fa\nFj\n>8+-%$srtG6$Ff]n-%%tdegG6#-Fgcm6#Fj\n6%7$%#cfG-%/permut
eColumnsG6%Fe]nFf]nF[^nF\bmF]bmFd`mFd`mFd`m6#""!637'FdemF[em"#;FfhmFgem7'FdemF[
emFiw"#VF`_n7'FdemF[emFiw""*Fiem7'FdemF[emF[im"#&*F`_n7'FdemF[emF[im"#dF`_n7'Fd
emF[emFiw"#FF`_n7'FdemF[emFiw"#yF`_n7'FdemF[emFiw"#WF`_n7'FdemF[emFiw"#>F`_n7'F
demF[emFiw"#%*F`_n7'FdemF[emFiw"#CF`_n7'FdemF[emFiw"#SFiem7'FdemF[em"#B"#K"#_7'
FdemF[emFiw"#QF`_n7'FdemF[emFiwFgemF`_n7'FdemF[emFiw"#LF`_n7'FdemF[emFiw"#`"#JF
d`m
