M7R0
I)F_p4p_fr7&,6%"yG#!'xhM"(+++"*$%"zG""##!&je$"'++D*&F*"""F%F0#"'*o3""'++?*$F%F+
#!'Z)y&F(*$%"wGF+#!&HV(F.*&F8F0F*F0#"'2:FF3*&F%F0F8F0#!'4]jF(F8#!'Z\cF(F*#"&8"f
"&++&#!'foPF(F0,J%"xG#"'Pr8F3F%#"$^&"%+S*(F*F0FIF0F8F0#!$4("'+]7*(F8F0FIF0F%F0#
"("H>;F(*(F*F0F%F0FIF0#!'2#o&"'++]F)#!'L4rF(F/#!(tx0"F(F4#!'z#*[F(*&FIF0F8F+#"'
ddWF(*&FIF0F*F+#!&ZF#F3*&F%F+FIF0#"'f+CF.F7#"&Zz)FRF;#!'d;jFYF>#"'(>V"F(*&FIF0F
8F0#!'"*p**F(*&FIF0F*F0#!&z'="&++%*&FIF0F%F0#!'f*\%F.F8#!'4+NFYF*#!&"*H(FY#"'T`
eFYF0,JFI#"'F@5"'++5F%#!&$[zF3FO#"'.g>F(FS#!&h%H"&]7$FV#"'.itF(F)#"',-@F(F/#"(8
i,"F(F4#"&xz"F\qFjn#"',0]F(F]o#!'Vs9F3F`o#!'@w<F.F7#"'nQEF(F;#!%`')"%]iF>#!'zCm
FYFio#"&n%pF\qF\p#"%.tFEF`p#!%4&)FEF8#!'***Q"FYF*#"'HsNF(#!&*oeF3F0,6F%#!'Z/EF
\qF)#"(F..#F(F/#"&,+%FYF4#"'2bIF(F7#!$R&FcqF;#!&z4*"&+D'F>#"'LpAF.F8#!(P!)4"FYF
*#"'hk'*F.#"'r_5F.F06",
I)C_p4p_frw,6#>%)symbolicGF061%&_nameG%&_sizeG%#_AG%"iG%&alphaG%#P1G%#P2G%"vG%#
P3G%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F[uC2>6$8$8%6$7%%#M1G%#M2G%#M3G7$-%"$G
6$7$""%FawF+7$Faw"")@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Ffv6#8'F[u/Fdx;F0-%%nop
sG6#Fev>Fiw7#-F\x6$-I'MatrixG6$%*protectedG%(_syslibG6$Faxw,6$FIF%F[u6$%)operat
orG%&arrowGF[u-&T'6#T%6#,&FfwF0*&,&9%F0!""F0F0&&T#F\z6#F0F0F0F[uF[u6(FcuFfvFeuF
dxFbuFev6#F+6$7'Q!F[uFcz"#P"#s"#O7'F\[lFczF][l"#VF_[lFex>8(-I$<,>GFby6&F8F*F%F0
>6$8)8*6$-I".G6$FayFby6$&FiwFgzFc[l-F]\l6$&Fiw6#F+Fc[l>8+-I'VectorG6$FayFby6#7&
&Fc[l6#;F0""$*&FIF0F\]lF0FIF0>8,-F]\l6$&Fiw6#F_]lFf\l>8-7#-%$addG6$*&&Fi[lFcxF0
&Fj[lFcxF0/Fdx;F0Faw>Fh]l7$&Fh]lF[u-F[^l6$*&F^^lF0&Fb]lFcxF0F`^l>Fh]l7$Fd^l-F[^
l6$*&F_^lF0Fh^lF0F`^l>Fh]l7$Fd^l,&-F[^l6$*&F^^lF0F^^lF0F`^lF0-F[^l6$*&F_^lF0F_^
lF0F`^lFcz>8.-%$mapG6$%'expandGFh]l@$FewOFh_l>8/-%&minusG6$-%'indetsG6#Fh_l-Fe`
l6#Fiw>6$8081-%,poly2matrixG6$Fh_lF``l>82-%$srtG6$F\al-%%tdegG6#&F``lF[u6%7#-%/
permuteColumnsG6%F[alF\alFaalFevFfvF[uF[uF[u6#Fgw667'F\[lFcz"#;""'F_[l7'F\[lFcz
F_]l"#cFa[l7'F\[lFczF_]l""*"#X7'F\[lFcz""("#bFa[l7'F\[lFczFibl"#$*Fa[l7'F\[lFcz
F_]l"#BFa[l7'F\[lFczF_]lF][lFa[l7'F\[lFczF_]l"#\Fa[l7'F\[lFczF_]lFablFa[l7'F\[l
FczF_]l"#NFa[l7'F\[lFczF_]l"#UFa[lFecl7'F\[lFczF_]l"#nFa[l7'F\[lFczF_]l"#CFa[l7
'F\[lFczF_]l"#RFgbl7'F\[lFcz"#A"#J"#_7'F\[lFczF_]l"#QFa[l7'F\[lFczF_]lF_[lFa[l7
'F\[lFczF_]lF_dlFa[l7'F\[lFczF_]l"#ZF_dlF[u
