M7R0
I4F_parallel_robot_667(,**$%"uG""#"""*$%"vGF'F(*$%"wGF'F(#"#h"%+5F(,hpF*#"$^""$
]#F&#!#(*"$+"%"aG#!&.<#"'+]7%"bG#!&R&["&+D'%"cG#"'@Q5"'++DF,#"$"=F3*&F7F(F;F(#"
'VS5"&++&*&F7F(F?F(#"'jY>F>*&F&F(F7F'F4*&F&F(F;F'#!%z5"$+&*&F&F(F?F'FN*&F;F(F?F
(#!'>VTF:*&F*F(F7F'#"#6""&*&F*F(F;F'F1*&F*F(F?F'FV*&F,F(F7F'#"$.)F3*&F,F(F;F'Ff
n*&F,F(F?F'FC*&F7F'F&F'F(*&F;F'F&F'F(*&F?F'F&F'F(*&F;F(F&F(#"$6$"$D"*&F?F(F&F(#
!$*RF3*&F7F'F*F'F(*&F;F'F*F'F(*&F?F'F*F'F(*&F7F(F*F(#!$6$F`o*&F?F(F*F(#!$(HF3*&
F7F'F,F'F(*&F;F'F,F'F(*&F?F'F,F'F(*&F7F(F,F(#"$*RF3*&F;F(F,F(#"$(HF3F%F(F)F(F+F
(*$F7F'#"(hCj%"(+++"*$F;F'#"("oUWFip*$F?F'#"'dEi"'++?#"(ta1"FipF(*(F&F(F;F(F7F(
Fbo*(F&F(F?F(F7F(Fho*(F*F(F;F(F7F(Fdp*(F*F(F?F(F;F(Fho*(F,F(F?F(F7F(Fdp*(F,F(F?
F(F;F(Fbo,hpF*#"%H:FPF&#"$`%FPF7#"%,&)F:F;#"%rEFBF?#!&.f#FBF,#"#"*F6FE#"'.*R$FB
FI#"'r;5FBFLF\rFM#"#ZFPFQFjrFR#"'(*)p"F:FU#"$t#FPFYFjqFZF^sFen#"#fFPFhnF`sFinFd
rFjnF(F[oF(F\oF(F]o#!#**F`oFao#"$9$F`oFdoF(FeoF(FfoF(Fgo#"#**F`oFjo#!$.#F3F]pF(
F^pF(F_pF(F`p#!$9$F`oFcp#"$.#F3F%F(F)F(F+F(Ffp#!'"y%eFipFjp#"(JbZ"FipF]q#!'PUeF
ipFcqFdsFdqFfsFeqF\tFfqFfsFgqF\tFhqFds#"&$Gv"&++%F(,hpF*#"$R"F3F&#!$,)F3F7#"(`"
>7FBF;#!'8-QFBF?#!&ZY""%DJF,#!%d<FPFE#!'$3">F:FI#"',mGFHFLFjtFM#!#cF`oFQFiuFR#!
%ZK"&++"FU#!$c$F`oFYFhtFZF^vFen#"$H#FPFhnF`vFinFcuFjnF(F[oF(F\oF(F]o#"$$**F3Fao
#"$^)F3FdoF(FeoF(FfoF(Fgo#!$$**F3Fjo#"$*oF3F]pF(F^pF(F_pF(F`p#!$^)F3Fcp#!$*oF3F
%F(F)F(F+F(Ffp#"(@mV%FipFjp#!&*4IFipF]q#"(,]&\FipFcqFdvFdqFfvFeqF\wFfqFfvFgqF\w
FhqFdv#"(P2_&FipF(,hpF*#"#9"#DF&#!#8"#]F7#!%x["%]7F;#!%fv"%+]F?#"#pF_xF,#!#wFiw
FE#"&>2%"&]7$FI#"&h!=F:FLFjwFM#!$f#F3FQF\yFR#!%dK"&Dc"FU#"$K$F`oFYFgwFZFayFen#!
$@"F3FhnFcyFinFexFjnF(F[oF(F\oF(F]o#"$R'F3Fao#!$i#F`oFdoF(FeoF(FfoF(Fgo#!$R'F3F
jo#F5F`oF]pF(F^pF(F_pF(F`p#"$i#F`oFcp#"#(*F`oF%F(F)F(F+F(Ffp#"&.D(F>Fjp#!&2r"F>
F]q#"'Fe"*FBFcqFgyFdqFiyFeqF^zFfqFiyFgqF^zFhqFgy#"&ns"F]vF(,hpF*#"#BF6F&#"%8;FP
F7#!%1?FbuF;#!&J*[FBF?#"'.!3'FBF,#"#()F6FE#"'(yH#FBFI#"'*4V$FBFLF[[lFM#"$x$FPFQ
Fi[lFR#"%z**F>FU#!$F(FPFYFizFZF]\lFen#"#TFPFhnF_\lFinFc[lFjnF(F[oF(F\oF(F]o#!$(
>F3Fao#"$@%F3FdoF(FeoF(FfoF(Fgo#"$(>F3Fjo#!$4$F`oF]pF(F^pF(F_pF(F`p#!$@%F3Fcp#"
$4$F`oF%F(F)F(F+F(Ffp#"(zfB$FipFjp#"&2A&F`qF]q#"'$)Q'*FipFcqFc\lFdqFe\lFeqF[]lF
fqFe\lFgqF[]lFhqFc\l#"(>#3HFipF(6",
I4C_parallel_robot_66w,6#>%)symbolicGF(61%&_nameG%&_sizeG%#_AG%"iG%#xxG%#yyG%#l
lG%"RG%$eqsG%"AG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"Fe]lC/>6$8$8%6$7%%"XG%"YG%"LG7%
7$""$""'Fg_l7$F(Fi_l@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F`_l6#8'Fe]l/F[al;F(-%%
nopsG6#F__l>F``l7#-Fc`l6$-I'MatrixG6$%*protectedG%(_syslibG6$Fh`lw,6$%"xG%"yGFe
]l6$%)operatorG%&arrowGFe]l-&T'6#T%6#,&F]`lF(*&,&9%F(!""F(F(&&T#Febl6#F(F(F(Fe]
lFe]l6(F]^lF`_lF_^lF[alF\^lF__l6#F'6$7'Q!Fe]lF\cl"#P"#s"#O7'FeclF\clFfcl"#VFhcl
F\al>6%8(8)8*6%&F``lF`cl&F``l6#F'-%(convertG6$&F``l6#Fh_lI'VectorG6$FhalFial>6$
&F]dl6$;Fe]lFe]lF(&F^dlF^el6$-I$<,>G6$FhalFial6%F^`lF^`lF^`lFbel>8+-%-getRotMat
rixG6#-Fcel6%F7F;F?>8,7#z+6&F&F*F,&F_dlF`cl[[[[[[[[[][[mF([[[[[[][[[[[mF([[[][[
[[[[[[mF(\[[[[[[[[[[[lF\cl?(F[alF'F(Fi_l%%trueGC$>8-,(-I".G6$FhalFial6$Fgel&F^d
l6$F_elF[alF(-Fcel6%F&F*F,F(&F]dlF^glF\cl>F^fl7$&F^flFe]l*&-I'factorG6$FhalFial
6#z+6&&F_dlFj`l&FgflF`cl&FgflFcdl&FgflFhdl[[[[[[][[[[[mF([[[][[[[[[[[mF(][[[[[[
[[[[[mF([[[[[[[[[\[[lF\clF(z+F\fl[[[[[[[[][[[mF([[[[][[[[[[[mF(][[[[[[[[[[[mF(!
F(F(>8.-%$mapG6$%'expandGF^fl@$F\`lOFbhl>8/-%&minusG6$-%'indetsG6#Fbhl-F_il6#F`
`l>6$8081-%,poly2matrixG6$FbhlFjhl>82-%$srtG6$Ffil-%%tdegG6#&FjhlFe]l6&7#-%/per
muteColumnsG6%FeilFfilF[jlF[jlF__lF`_lFe]lFe]lFe]l6#F^`l657'FeclF\cl"#;Fi_lFhcl
7'FeclF\clFh_l"#_Fjcl7'FeclF\clFh_l""*"#X7'FeclF\cl""("#bFjcl7'FeclF\clFb[m"#$*
FjclF\[m7'FeclF\clFh_l"#SFjcl7'FeclF\clFh_l"#IFjcl7'FeclF\clFh_l"#MFjcl7'FeclF
\clFh_l"")F]\m7'FeclF\clFi_l"#RFjcl7'FeclF\clFi_l"#xFjcl7'FeclF\clFh_l"#CFjcl7'
FeclF\clFh_lF_\mF`[m7'FeclF\cl"#A"#JF][m7'FeclF\clFh_l"#QFjcl7'FeclF\clFh_lFhcl
Fjcl7'FeclF\clFh_lFg\mFjcl7'FeclF\clFh_l"#^Fg\mFe]l
