M7R0
I.F_pose_quiver7&,:*&%"wG"""%"xG""#F'#"-#[w>cO%"-nU_&3=%F'*&%"yGF)F&F'F'*&F&F'%
"zGF)!""F&F1*&F(F'F.F'#!-w)oUA&zF,*&F(F'F0F'#!-#)Q$y(*Q)F,F(#"-Kv'Q6m"F,*&F.F'F
0F'#!-Kv'Q6m"F,F.F6*$F0F)#!-#[w>cO%F,F0#".Sj@pV5"F,,6#",,">Iyc"-M&[5<O)F'*(F0F'
F(F'F&F'F'*&F&F'F.F'F1F2#!-d"zLg9)F,F5#!-ju'*4UoFEF(#"-Zrs")*)>FEF:#!-Zrs")*)>F
EF.FJF=#!,,">IycFEF0#!,AP<bX#F,,6#!-1r$f$GSF,F'*&F&F'F(F'F'*(F0F'F.F'F&F'F'F2#!
-![,j+0$F,F5#"-3Hic`>F,F(#!-3#RDE5#F,F:#"-3#RDE5#F,F.FenF=#"-1r$f$GSF,F0#!-S8PD
+7F,,6#!-d7ES)\&F,F'*$F(F)F'*$F.F)F1F2#!-M$)*[U#oF,F5#"-E!p*))=\F,F(#"-Q*e'32EF
,F:#!-Q*e'32EF,F.FfoF=#"-d7ES)\&F,F0#!,M%RB:iF,6",
I.C_pose_quivert+6#>%)symbolicGF'62%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%#V0G
%"VG%"RG%#KRG%%eqs0G%#A0G%#U0G%"UG%"AG%#tAG6"F`pC2>6$8$8%6$7#%"MG7#7$""%""*@%/9
$F'>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F\r6#%"iGf*6$F(F.
F`p6$%)operatorG%&arrowGF`p-&T%Fgs6#,&FfrF'*&,&9%F'F1F'F'&&T#Fgs6#F'F'F'F`pF`p6
&FhpF\rFgpF[r/Fhs;F'-%%nopsG6#F[r>Fhr7#-F[s6$-%'rndMatG6#FcsF[u>8,-I$<,>GFas6%-
I$<|gr>GFas6%z+6%F(F.F0[[[[[[[[][[[mF'[[[[][[[[[[[mF1][[[[[[[[[[[mF1!F'z'F`v[[[
[\[[[\[[[mF)\[[[[[[[[[[[l!"#z'F`v\[[[[[[[\[[[mF)[[[[\[[[[[[[lF)-F]v6%z'F`v[[[[
\[[[\[[[mF)\[[[[[[[[[[[lF)z+F`v[[[[[[[[][[[mF1[[[[][[[[[[[mF'][[[[[[[[[[[mF1!F'
z'F`v\[[[\[[[[[[[mF)[[[[[[[[\[[[lFbv-F]v6%z'F`v\[[[[[[[\[[[mF)[[[[\[[[[[[[lFbvz
'F`v\[[[\[[[[[[[mF)[[[[[[[[\[[[lF)z+F`v[[[[[[[[][[[mF1[[[[][[[[[[[mF1][[[[[[[[[
[[mF'!F'>8--I".G6$F`sFas6$-&I.LinearAlgebraG6$F`sFas6#_Ffw%/DiagonalMatrixG6#7%
F'F'F&Fhu>8.-%$mapG6$%'expandG-%(convertG6$-Faw6$&FhrFit-Fdx6$F_wI'VectorG6$F`s
Fas%%listG>6$8/80-%,poly2matrixG6%F^x-F^u6#F^x-%'indetsGFfy>81-F[y6#74F%FFFWFbo
F-FXFGF/F&FcoF2F5F(F:F.F=F0F'>82-%/permuteColumnsG6%F`yFayFjy@%/Ffr""!>83-&Ffw6
#_Ffw%6ReducedRowEchelonFormG6#F_z>Fgz-F]v6$-F^s6%Fbr"#57&7,F'FezFezFezF'FezFez
F1F1Fez7,FezF'FezFezFezFezF1FezFezFez7,FezFezF'FezFezF'FezFezFezFez7,FezFezFezF
'FezFezFezFezFezF1-F^s6%Fbr"")f*FjsF`p6$F\tF]tF`p-%"BG6#,(FfrF'FetFbr!"%F'F`pF`
pF`p>8'-Fdx6$-Faw6$FgzFjyF]y>Fd\l-F`x6$FbxFd\l@$FdzOFd\l>8(-%&minusG6$-Fhy6#Fd
\l-Fhy6#7#Fhr>6$8)8*-Fcy6%Fd\l-F^uFd]lF_]l>8+-%$srtG6$F[^l-%%tdegG6#-Fds6#F_]l6
%7(%#cfGF_z%%rrefGFgzF[_l-Faz6%Fj]lF[^lF`^lF[rF\rF`pF`pF`p6#FezF`p
