M7R0
I.F_pose_quiver7&,:*&%"wG"""%"xG""#F'#"+mZ&))p#","on;b:F'*&%"yGF)F&F'F'*&F&F'%"
zGF)!""F&F1*&F(F'F.F'#"-VX0HO:",i`L.6$*&F(F'F0F'#"-4"[fny"F5F(#!*4kMO""*dEEr%*&
F.F'F0F'#"*4kMO"F;F.F7*$F0F)#!+mZ&))p#F,F0#"+f8b&y(F5,6#","e$[*)>#",a%yxO5F'*(F
0F'F(F'F&F'F'*&F&F'F.F'F1F2#"+BrPdB",;Q6r9%F6#!-n$=7Dx"FLF(#"+p&4!H@"+G10&)=F<#
!+p&4!H@FQF.FMF?#!,"e$[*)>#FGF0#"-6e2YDFFL,6#"+p*GuY"FGF'*&F&F'F(F'F'*(F0F'F.F'
F&F'F'F2#!-Z`e+b>FLF6#!-08o9i=FLF(#"+z(pgX#FQF<#!+z(pgX#FQF.FinF?#!+p*GuY"FGF0#
"-,F!Q,4"FL,6#!,2"HwTLF,F'*$F(F)F'*$F.F)F1F2#",iHNd&[F,F6#"-'Q&)fh\"F,F(#!+%y<(
)H"F;F<#"+%y<()H"F;F.FjoF?#",2"HwTLF,F0#!-'[QkTE"F,6",
I.C_pose_quiverw,6#>%)symbolicGF'64%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V
0G%#_VG%"iG%"RG%#KRG%$eqsG%%varsG%#mmG%"VG%#V1G%#M1G%$tM1G6"FdpC3>6$8$8%6$7#%"M
G7#7$""%""*@%/9$F'>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fb
r6#8,w,6$F(F.Fdp6$%)operatorG%&arrowGFdp-&T'6#T%6#,&F\sF'*&,&9%F'F1F'F'&&T#Fgt6
#F'F'F'FdpFdp6(F\qFbrFcqF^tF[qFar6#F)6$7'Q!FdpF1"#R"#u"#O7'FfuF1Fgu"#XFiu/F^t;F
'-%%nopsG6#Far>F^s7#-Fas6$-%'rndMatG6#FisF\v>8--I$<,>GFgs6%-I$<|gr>GFgs6%z+6%F(
F.F0[[[[[[[[][[[mF'[[[[][[[[[[[mF1][[[[[[[[[[[mF1!F'z'Faw[[[[\[[[\[[[mF)\[[[[[[
[[[[[l!"#z'Faw\[[[[[[[\[[[mF)[[[[\[[[[[[[lF)-F^w6%z'Faw[[[[\[[[\[[[mF)\[[[[[[[[
[[[lF)z+Faw[[[[[[[[][[[mF1[[[[][[[[[[[mF'][[[[[[[[[[[mF1!F'z'Faw\[[[\[[[[[[[mF)
[[[[[[[[\[[[lFcw-F^w6%z'Faw\[[[[[[[\[[[mF)[[[[\[[[[[[[lFcwz'Faw\[[[\[[[[[[[mF)[
[[[[[[[\[[[lF)z+Faw[[[[[[[[][[[mF1[[[[][[[[[[[mF1][[[[[[[[[[[mF'!F'>8.-I".G6$Ff
sFgs6$-&I.LinearAlgebraG6$FfsFgs6#_Fgx%/DiagonalMatrixG6#7%F'F'F&Fiv>8/-%$mapG6
$%'expandG-%(convertG6$-Fbx6$&F^sFau-Fey6$F`xI'VectorG6$FfsFgs%%listG>807&F&F(F
.F0>6$8182-%,poly2matrixG6$F_yF`z>83-F\z6#74F%FHFenFfoF-FfnFIF/F&FgoF2F6F(F<F.F
?F0F'>84-%/permuteColumnsG6%FdzFezFjz@%/F\s""!>85-&Fgx6#_Fgx%6ReducedRowEchelon
FormG6#F_[l>Fg[l-Fds6#7&74F'Fe[lFe[lFe[lF'Fe[lFe[lF1F1Fe[l-%"AG6#"#D-Fd\l6#"#H-
Fd\l6#"#L-Fd\l6#"#P-Fd\l6#"#T-Fd\l6#F[v-Fd\l6#"#\-Fd\l6#"#`74Fe[lF'Fe[lFe[lFe[l
Fe[lF1Fe[lFe[lFe[l-Fd\l6#"#E-Fd\l6#"#I-Fd\l6#"#M-Fd\l6#"#Q-Fd\l6#"#U-Fd\l6#"#Y-
Fd\l6#"#]-Fd\l6#"#a74Fe[lFe[lF'Fe[lFe[lF'Fe[lFe[lFe[lFe[l-Fd\l6#"#F-Fd\l6#"#J-F
d\l6#"#N-Fd\l6#Fgu-Fd\l6#"#V-Fd\l6#"#Z-Fd\l6#"#^-Fd\l6#"#b74Fe[lFe[lFe[lF'Fe[lF
e[lFe[lFe[lFe[lF1-Fd\l6#"#G-Fd\l6#"#K-Fd\l6#Fiu-Fd\l6#"#S-Fd\l6#"#W-Fd\l6#"#[-F
d\l6#"#_-Fd\l6#"#c>F_y-Fey6$-Fbx6$Fg[lFjzF^z>8'-Fay6$FcyF_y@$0F\sF'OFjbl>8(-%&m
inusG6$-%'indetsG6#Fjbl-Ffcl6#F^s>6$8)8*-Fgz6$FjblFacl>8+-%$srtG6$F]dl-%%tdegG6
#-Fjs6#Facl6%7&%#cfGF_[l%%rrefG-Fa[l6%F\dlF]dlFadlFarFbrFdpFdpFdp6#Fe[l697'FfuF
1"#;""'Fiu7'FfuF1""$FbalFb`l7'FfuF1FfelFirF[v7'FfuF1""("#&*Fb`l7'FfuF1Fiel"#dFb
`l7'FfuF1Ffel"$="Fb`l7'FfuF1FfelFh`lFb`l7'FfuF1Ffel"#iFb`l7'FfuF1Ffel"#AFb`l7'F
fuF1FfelF\]lFb`l7'FfuF1Ffel"$1"Fb`lFdflFgel7'FfuF1FielFj]lFb`l7'FfuF1Fiel"$x$Fb
`l7'FfuF1FfelFa^lFb`l7'FfuF1Ffel"#CFb`l7'FfuF1FfelFgalF[v7'FfuF1"#BFbalF`bl7'Ff
uF1FfelFg^lFb`l7'FfuF1FfelFiuFb`lFdfl7'FfuF1Ffel"#lFj_lFdp
