M7R0
I,F_pose_35pt7&,T%"xG#!4`([;K*Ho&**f"5+++++++++]%"yG#"5^6ycjN-rwM"6+++++++++]#*
&F%"""F)F.#!56**))fF/"z"4V"6+++++++++D"*$F%""##"5"\kRD$3Xuv&*"6++++++++++&*$F)F
3#!5LM"4V4=)RcQF6*&F%F.F)F3#"5>[*)z643;x?"5++++++++]i*&F%F3F)F.#!5zK7=/gkw)>"F=
*&F)F.F%""$#"5xx2gK%f_*4QF1*&F)FBF%F.FC*&F)F3F%F3#!5$3pm_$HF:/BF,*&F%FBF)F3#!5F
dk2bFX[S^F1*&F%""%F)F.#"4`/,9"\_<CkF,*&F%F3F)FB#FOF1*&F%F3F)FM#"6BYEbZL];w6"F6*
&F)FMF%F.#FKF,*&F)F3F%FMFS*$F%FB#"46S4_a(\#[-""4++++++++]#*$F%FM#!6<'e&)Ry)Q2f/
"F6*$F)FB#!5R/ZmJ286;DF=*$F)FM#"5^/AX8H%o2&eF6*$F%""&FV*$F%""'#"5T:U=\W$)QDPF6*
$F)F`oFN*$F)FboFco#!4j](=+Q5;7(*F6F.,TF%#"4>A\EPCE.b""4+++++++D"yF)#"5n))GI=R1c
ReF=F-#!5*R*4<5zLiafF=F2#"46c^m`*yj)3""4++++++++D'F7#!5PtjN5Zq%y;#F=F:#"5pPI6Lg
PT5mF=F>#!5P&fTc8w0!G]F=FA#"5`I9Z=(4nUS&F=FEFjpFF#!5T0/oL@XiWE"5++++++++DJFI#!5
>mO"\(z([!\pF^qFL#!4<DUE`&*e-W""4++++++DJ&>FP#Fbq"3+++++]il(*FR#"5`U!*Q>#)GEa%)
F=FU#F`qF=FWFfqFX#"5P*)4EXZ$*otqF=Ffn#!62')[mu!fK8'H"F1Fin#!5(*o*R\db_/=*F=F\o#
"5VkK%*R0X$GQ#F1F_oFhqFao#"5^ZjzRFw3=GF=FeoFaqFfoFar#"4\D!*>+hz=%f"5+++++++++DF
.,TF%#!4B[$\J$)*4M=)"5++++++++]7F)#"5tVB\f*pXDf#F=F-#!5">m@p)o.h,SF=F2#"5*p_^`K
Z'*3"HF1F7#!54"Rk\6PZ*4GFerF:#"5*G>(*Hhl/)fN"5+++++++]i:F>#"4ne&>84!4Tm"F^qFA#"
4rthvs!*=69%F=FEFgsFF#"4`t-Y]'QL*Q$FdsFI#!46>Ju"[#*)y'zFcpFL#!4<*fdA-GK;DF=FP#F
^tF^qFR#"5R=CpKo3fQ')F1FU#F\tFirFWF`tFX#"4@8.'))="=c%="4++++++++D"Ffn#!5Ff%Qc'G
c=fRF=Fin#!3x\WO*p^lA"FeqF\o#"5R`&zuY<>\J&F=F_oFbtFao#"5813BW*GI&zGF1FeoF]tFfoF
\u#!4xF<&H[(zD*eF=F.,TF%#"5"e-%yItb$HA"FerF)#!5*GAHw$>?&H]"F1F-#"4<Qv/c)4G3ZFir
F2#!5L=o!R$RR;G8F1F7#"5j%[zFs^>G')*F1F:#!58e$\sf1>R!\F^qF>#!4.u0/qwN<6"F^qFA#!4
T^u6bLM>b'F=FEF_vFF#!5\dh@p4C8'p"F^qFI#"5fP!o-QY<`W'F=FL#"5"3%>R58b3REF1FP#FfvF
=FR#!4L_N$z"[2a!**FerFU#FdvF1FWFhvFX#!56"=7d)3ldrUF^qFfn#"4L+Y&\HAT]WF=Fin#"46@
jW*e=A9=FcpF\o#!5J:pQLUgIPQF=F_oFjvFao#!46%=6$R\-=I$FerFeoFevFfoFcw#"4(>IHpGt!Q
J&F=F.6",
I,C_pose_35ptw,6#>%)symbolicGF.68%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G
%#_VG%"iG%#xxG%$xx0G%$yy0G%"RG%#R1G%#R2G%#R3G%&iddesG%"FG%"lG%"jG%"kG%$eqsG6"Fg
wC1>6$8$8%6$7%%"XG%#x0G%#y0G7%7$FBFM7$FMF.7$FBF.@%/9$F.>8&7#-%$seqG6$-I'MatrixG
6$%*protectedG%(_syslibG6$-%#opG6#&Fiy6#8,w,6$F%F)Fgw6$%)operatorG%&arrowGFgw-&
T'6#T%6#,&FezF.*&,&9%F.!""F.F.&&T#F`\l6#F.F.F.FgwFgw6(F_xFiyFfxFg[lF^xFhy6#F36$
7'Q!FgwFg\l"#R"#u"#O7'F`]lFg\lFa]l"#XFc]l/Fg[l;F.-%%nopsG6#Fhy>Fgz7#-Fjz6$-%'rn
dMatG6#Fb[lFf]l>6%8-8.8/6%&FgzF[]l-%(convertG6$&Fgz6#F3I'VectorG6$F_[lF`[l-Fj^l
6$&Fgz6#FBF^_l>80-I$<,>GF`[l6%-I$<|gr>GF`[l6%z)Fi[l[[[[[_[[[[sF.][[[[[[[[[sFg\l
!F.,$F-F3,$F)F3-Fj_l6%F]`lz)Fi[l[[[[[_[[[[sFg\l][[[[[[[[[sF.!F.,$F%!"#-Fj_l6%,$
F)Fc`l,$F%F3z)Fi[l[[[[[_[[[[sFg\l][[[[[[[[[sFg\l!F.>6%8182836%&Fe_l6$F.;FgwFgw&
Fe_l6$F3Faal&Fe_l6$FBFaal>84-Fg_l6&-Fj_l6%F.F3FB-Fj_l6%F.FBF3-Fj_l6%F3FMFB-Fj_l
6%FBFMF3>85-F][l6$FMFB?(86F.F.FM%%trueGC&>6%Fg[l87886%&Fgal6$FgblF.&Fgal6$FgblF
3&Fgal6$FgblFB>&FcblF`cl,&-I".G6$F_[lF`[l6$*&,&&Ff^lFf[lF.&Ff^l6#F]clFg\lF.F[al
F.,&&Fd^l6$FaalF\clF.&Fd^l6$FaalFg[lFg\lF.-Ficl6$*&,&&Fe^lFf[lF.&Fe^l6#F\clFg\l
F.F\alF.,&&Fd^l6$FaalF]clF.FddlFg\lFg\l>&FcblFbcl,&-Ficl6$*&F]dlF.F\alF.FadlFg
\l-Ficl6$*&FidlF.F[alF.F]elFg\l>&FcblFdcl,&-Ficl6$*(F[elF.F]dlF.F]alF.FadlFg\l-
Ficl6$*(F_dlF.FidlF.F]alF.F]elF.>897#-Fjz6$-&I.LinearAlgebraG6$F_[lF`[l6#_Fifl%
,DeterminantG6#-&Fifl6#_Fifl%*DeleteRowG6$FcblFg[l/Fg[l;F.FM>8'-%$mapG6$%'expan
dGFcfl@$0FezF.OFhgl>8(-%&minusG6$-%'indetsG6#Fhgl-Ffhl6#Fgz>6$8)8*-%,poly2matri
xG6$FhglFahl>8+-%$srtG6$F]il-%%tdegG6#-Fc[l6#Fahl6%7$%#cfG-%/permuteColumnsG6%F
\ilF]ilFbilFhyFiyFgwFgwFgw6#""!697'F`]lFg\l"#;FboFc]l7'F`]lFg\lFB"#e"#V7'F`]lFg
\lFB""*Fe]l7'F`]lFg\l""("#&*Fhjl7'F`]lFg\lF\[m"#dFhjl7'F`]lFg\lFB"#rFhjl7'F`]lF
g\lFB"#wFhjl7'F`]lFg\lFB"#TFhjl7'F`]lFg\lFB"#ZFhjl7'F`]lFg\lFB"#=Fhjl7'F`]lFg\l
FB"")F[\m7'F`]lFg\lF\[m"#^Fhjl7'F`]lFg\lF\[m"#$*Fhjl7'F`]lFg\lF\[m"#%*Fhjl7'F`]
lFg\lF\[m"$3"Fhjl7'F`]lFg\lFB"##)Fhjl7'F`]lFg\lFB"#CFhjl7'F`]lFg\lFB"#SFe]l7'F`
]lFg\l"#B"#K"#_7'F`]lFg\lFB"#QFhjl7'F`]lFg\lFBFc]lFhjl7'F`]lFg\lFB"#LFhjl7'F`]l
Fg\lFB"#`"#JFgw
