M7R0
I,F_pose_35pt7&,T%"xG#!6H,'[d'Q5;*pN"6++++++++++&%"yG#"5jU-*z>mHIi*F(*&F%"""F)F
-#!5"QRq,G'>qwy"6+++++++++D"*$F%""##"3hQ)>v<')*Gc"3++++++]7y*$F)F2#!5z%4vx!HfBT
G"5++++++++]i#!56`<x/v?+z;F(F-*&F%F-F)F2#"6pP[bFD)Hw0<F0*&F%F2F)F-#!6h')z6,k-jX
">F0*&F)F-F%""$#"4<=gj"*)R'**=""4+++++++]7$*&F)FCF%F-FD*&F)F2F%F2#"42'Hu:%\kNF(
"5+++++++++]*&F%FCF)F2#"5*))f1"pnRQ,P"6+++++++++]#*&F%""%F)F-#"64Mf$)f$HhFtEF(*
&F%F2F)FC#FSFO*&F%F2F)FQ#"5V>IZijXe`'*FO*&F)FQF%F-#FNF(*&F)F2F%FQFW*$F%FC#"4Hv_
A&)="GA5"4+++++++++"*$F%FQ#"6x**)*Ro'\&GW>""6++++++++++"*$F)FC#!5<inV;&)*Gi"yF0
*$F)FQ#!6j28D&yfs&*[5F]o*$F%""&FZ*$F%""'#"5")RV#37_hy@$FO*$F)FeoFR*$F)FgoFho,TF
%#"5$ptI18Q&f(R'F]oF)#!54Aw\tE=PO#)F]oF,#"5rF/mtSrK*f(FKF1#!3(>n$R7ZY@YF5F6#"3<
hx]F8^^`"5+++++++++5F<#!6B;Qk%>G&GBO""5+++++++++DF?#"6z^R*>of!\ae"FjpFB#!5Jv5Yg
u8)[,*FKFGF]qFH#"48u:]X'Gjp_FKFL#!5"=xRG***ob&H"FKFP#!52;smUv'G&REF]oFT#FdqFKFV
#"58R-N%G=]Yw"FjpFY#FbqF]oFenFfqFfn#!6Zh`9\u,V/8"FjpFjn#!4^zJh0!Rp7N"4+++++++++
#F^o#"6Rt[Q$*o.-J4"FjpFao#"5ZlxXY4X<FB"5++++++++]7#!3HF)[cB]$\aF]rF-FdoFhqFfo#"
4rz+XhFn@)eFjpFjoFcqF[pFer,TF%#!58l'\._!fZxKF]oF)#"4Lp>-&fbvWjF]oF,#!4BFi[ucNVz
#"4++++++++]#F1#"4*R">JMU]/Z""4+++++++Dc"F6#!4JgT$zdYhL;"4++++++++D'F<#"5z)*[4]
C*434)FjpF?#!4^ml'=")yy?T"4++++++++D"FB#"4n/%**Gsw13zFbrFGFjsFH#"38J^43$e.D$Fds
FL#"4"y]kQwymntFgpFP#"4jrhW)**4>[@"5+++++++++?FT#FatFgpFV#"3>%o*[)ol=$H"3++++++
+]iFY#F_tFbtFenFdtFfn#"5VR+gZWk`8nFjpFjn#"4R45dQ];()e%FFF^o#!4j'f099BgKDFisFao#
!4`x$4QN%z/x"FisFdoFgtFfo#"2t%*)HGc)Gx*FftFjoF`tF[pF`u#!3niCLXaIYJFFF-,TF%#!4Fe
'z_je(RS%FjpF)#"4F5RS,CjKg"F]rF,#!4FV0*y*RzGq'"4+++++++++&F1#"5\<g`W_TYv7FdsF6#
"4@v)eEp$>`9*FdsF<#"4.\f?='><ZKF]rF?#!5xv!yzam.**z#FjpFB#"5@0v7'fDq%*f$FjpFGFdv
FH#!5(ft%>GN]?5))FjpFL#!5,EvV\vM9!f%FjpFP#!4z'))**[%o-pV%FgpFT#F[wF[vFV#!4@5bC*
Q!)fgMF[vFY#FivFKFenF]wFfn#"5RX(*G"G.9k."FgpFjn#!5f8ab&[3PN3%FKF^o#!3de6%z*H*Q<
(F[vFao#!5n6o;9(futq#FgpFdoF_wFfo#!42q^T'zE``6F[vFjoFjvF[pFhw#"4PW(Rjw(y3#GFKF-
6",
I,C_pose_35ptw,6#>%)symbolicGF-68%&_nameG%&_sizeG%#_AG%"iG%#xxG%$xx0G%$yy0G%"RG
%#R1G%#R2G%#R3G%&iddesG%"FG%"lG%"jG%"kG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F
\xC1>6$8$8%6$7%%"XG%#x0G%#y0G7%7$FCFQ7$FQF-7$FCF-@%/9$""!>8&7#-%$seqG6$-%'rndMa
tG6#&&F^z6#8'F\x/Fh[l;F--%%nopsG6#F]z>F][l7#-F`[l6$-I'MatrixG6$%*protectedG%(_s
yslibG6$Fe[lw,6$F%F)F\x6$%)operatorG%&arrowGF\x-&T'6#T%6#,&FjzF-*&,&9%F-!""F-F-
&&T#F`]l6#F-F-F-F\xF\x6(FdxF^zFfxFh[lFcxF]z6#F26$7'Q!F\xFg]l"#P"#s"#O7'F`^lFg]l
Fa^l"#VFc^lFi[l>6%8(8)8*6%&F][lF[^l-%(convertG6$&F][l6#F2I'VectorG6$Fe\lFf\l-F^
_l6$&F][l6#FCFb_l>8+-I$<,>GFf\l6%-I$<|gr>GFf\l6%z)Fi\l[[[[[_[[[[sF-][[[[[[[[[sF
g]l!F-,$F,F2,$F)F2-F^`l6%Fa`lz)Fi\l[[[[[_[[[[sFg]l][[[[[[[[[sF-!F-,$F%!"#-F^`l6
%,$F)Fg`l,$F%F2z)Fi\l[[[[[_[[[[sFg]l][[[[[[[[[sFg]l!F->6%8,8-8.6%&Fi_l6$F-;F\xF
\x&Fi_l6$F2Feal&Fi_l6$FCFeal>8/-F[`l6&-F^`l6%F-F2FC-F^`l6%F-FCF2-F^`l6%F2FQFC-F
^`l6%FCFQF2>80-Fc\l6$FQFC?(81F-F-FQ%%trueGC&>6%Fh[l82836%&F[bl6$F[clF-&F[bl6$F[
clF2&F[bl6$F[clFC>&FgblFdcl,&-I".G6$Fe\lFf\l6$*&,&&Fj^lFg[lF-&Fj^l6#FaclFg]lF-F
_alF-,&&Fh^l6$FealF`clF-&Fh^l6$FealFh[lFg]lF--F]dl6$*&,&&Fi^lFg[lF-&Fi^l6#F`clF
g]lF-F`alF-,&&Fh^l6$FealFaclF-FhdlFg]lFg]l>&FgblFfcl,&-F]dl6$*&FadlF-F`alF-Fedl
Fg]l-F]dl6$*&F]elF-F_alF-FaelFg]l>&FgblFhcl,&-F]dl6$*(F_elF-FadlF-FaalF-FedlFg]
l-F]dl6$*(FcdlF-F]elF-FaalF-FaelF->847#-F`[l6$-&I.LinearAlgebraG6$Fe\lFf\l6#%,D
eterminantG6#-&F]gl6#%*DeleteRowG6$FgblFh[l/Fh[l;F-FQ>85-%$mapG6$%'expandGFgfl@
$FizOFjgl>86-%&minusG6$-%'indetsG6#Fjgl-Fghl6#F][l>6$8788-%,poly2matrixG6$FjglF
bhl>89-%$srtG6$F^il-%%tdegG6#&FbhlF\x6%7#-%/permuteColumnsG6%F]ilF^ilFcilF]zF^z
F\xF\xF\x6#F[[l697'F`^lFg]l"#;FgoFc^l7'F`^lFg]lFC"#eFe^l7'F`^lFg]lFC""*"#X7'F`^
lFg]l""("#bFe^l7'F`^lFg]lFjjl"#$*Fe^l7'F`^lFg]lFC"#rFe^l7'F`^lFg]lFC"#qFe^l7'F`
^lFg]lFC"#TFe^l7'F`^lFg]lFC"#RFe^l7'F`^lFg]lFC"#=Fe^l7'F`^lFg]lFC"")Fi[m7'F`^lF
g]lFjjl"#^Fe^lF\[m7'F`^lFg]lFjjl"#%*Fe^l7'F`^lFg]lFjjl"$3"Fe^l7'F`^lFg]lFC"##)F
e^l7'F`^lFg]lFC"#CFe^l7'F`^lFg]lFCFe[mFhjl7'F`^lFg]l"#A"#J"#_7'F`^lFg]lFC"#QFe^
l7'F`^lFg]lFCFc^lFe^l7'F`^lFg]lFCFg\mFe^l7'F`^lFg]lFC"#ZFg\mF\x
