M7R0
I&F_r6p7(,B%"vG#")xswP")+++]%"xG#!)p6*\$F(%"uG#"(Z#3))")+++D%"yG#!'*\.*"']7y%"w
G#")8j+tF(%"zG#!)B#QC"F(*&F)"""F,F;#"("yYjF(*&F)F;F%F;#!(rBo*")++]7*&F)F;F4F;#"
)`%3:)F(*&F0F;F,F;#")"[(3XF(*&F0F;F%F;#!)@xsWF(*&F0F;F4F;#"(`_;#FA*&F,F;F7F;#!(
J`K"F/*&F%F;F7F;#!(2!)*GFA*&F4F;F7F;#"(<2a#F(#!)\j7>F/F;,BF%#!'(\B""(++]#F)#"(4
**o"FfnF,#"%j["&D"yF0#!'xk')"(++D"F4#"'d>")FfnF7#"(`*H5FfnF:#"(fx]"FfnF>#"&K['F
[oFB#!'L>ZFfnFE#"'f")oFfnFH#"'J&p#FfnFK#"'4LRF^oFN#!'<DY"'+]iFQ#"'z!e%F^oFT#"(8
%==Ffn#"&*)p(F^oF;,BF%#!)Pb#R$"*+++D"F)#!**Q*[/"")++]iF,#!*d([T7F^qF0#"(@')p)F[
qF4#"*ZAjS#F[qF7#"(8F1(F[qF:#")R.(R#F^qF>#")^glA")++DJFB#"(6o!\"(]i!RFE#"*R8_5#
F[qFH#!'ZwP"(+Dc"FK#")hgL%*F[qFN#!($Q:P"(+D"yFQ#"(nBa(F[rFT#!)xR^iF[q#")>lT6F^q
F;,BF%#!*$fP(R$"*+++]#F)#")(**)o5F^rF,#"*,"p'4"F^qF0#!*J80/%FbsF4#"*L:=1"FbsF7#
"*2%o_@FbsF:#")*f'yDF[rF>#")$)GB6FhrFB#!(rcD"FhrFE#!*HK#[\FbsFH#")6h!*>F/FK#!)r
J7pFbsFN#!*rmh4"F[qFQ#!("eVRF[rFT#"*(*fZ="Fbs#!(@!\VF[rF;,BF%#!'p$f*"'++!)F)#"'
p'Q#"'++SF,#!&d&R"&+]#F0#!&$)3#FduF4#"'H&="FduF7#"'6FEFduF:#"'()3&)FduF>#!%R))"
&++&FB#"$p%"'++5FE#"&>z(FduFH#"'*Q)pFduFK#!'TPHFduFN#"'4EhFguFQ#!'R=P"'++?FT#!'
()zfFdu#!'Rq:FcwF;,BF%#!%hv"&+g"F)#"%hW"%+!)F,#"#F"$+)F0#!%zB"%+KF4#"%LEFdxF7#"
%"*\F[xF:#"%"*pF[xF>#""%""&FB#!$(>"%+?FE#"%^iF[xFH#!%^[F[xFK#"%ziF[xFN#!%(z%F^x
FQ#"%`5F`yFT#"%8>Fdx#!$^(FaxF;6",
I&C_r6pw,6#>%)symbolicGF;69%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G%#_VG%
"iG%#q1G%#X1G%#A1G%#xxG%#vvG%#wwG%"MG%"CG%"tG%$eqsG%"kG%#drG%#sxG%#rhG6"F_zC2>6
$8$8%6$7%%"qG%"XG%"AG7%7$""#""$7$F[]lF[]l7$""'"#;@%/9$F;>8&7#-%$seqG6$-I'Matrix
G6$%*protectedG%(_syslibG6$-%#opG6#&Fb\l6#8,w,6$F)F0F_z6$%)operatorG%&arrowGF_z
-&T'6#T%6#,&Fb]lF;*&,&9%F;!""F;F;&&T#F]_l6#F;F;F;F_zF_z6(FgzFb\lF^[lFd^lFfzFa\l
6#Fj\l6$7'Q!F_zFd_l"#R"#u"#O7'F]`lFd_lF^`l"#XF``l/Fd^l;F;-%%nopsG6#Fa\l>Fd]l7#-
Fg]l6$-%'rndMatG6#F_^lFc`l>6%8-8.8/6%-I$<,>GF]^l6$&Fd]lFh_l-I$<|gr>GF]^l6%F;F;F
;&Fd]l6#Fj\l&Fd]l6#F[]l>807(F,F%F4F)F0F7>6$81826$&Fabl6#;F;F[]l&Fabl6#;F\yF^]l>
83-I'VectorG6$F\^lF]^l6#7-*&&FablFh_lF;&Fabl6#F\yF;*&&FablF]blF;FgclF;*&&FablF_
blF;FgclF;*&FfclF;&Fabl6#F]yF;*&FjclF;F^dlF;*&F\dlF;F^dlF;*&FfclF;&Fabl6#F^]lF;
*&FjclF;FcdlF;*&F\dlF;FcdlF;FablF;>84-I".G6$F\^lF]^l6$&Fcal6$Fjbl;F_zF_zF_cl>85
-Fjdl6$&Fcal6$F]clF_elF_cl>867"?(87F;F;F[]l%%trueGC&>88&Faal6$F;Fjel>89-Ffal6%-
Fjal6%""!,$&&Faal6$F_elFjelF_blFd_l&FjflF]bl-Fjal6%FiflFgfl,$&FjflFh_lFd_l-Fjal
6%,$F\glFd_lF`glFgfl>8:,(-Fjdl6%,&-&I.LinearAlgebraG6$F\^lF]^l6#_F\hl%/Identity
MatrixGF_blF;*&F^flF;-Ffal6%-Fjal6%Fgfl,$&FfblF_blFd_l&FfblF]bl-Fjal6%FghlFgfl,
$&FfblFh_lFd_l-Fjal6%,$FhhlFd_lF\ilFgflF;F;,&FjglF;-Ffal6%-Fjal6%Fgfl,$&FeblF_b
lFd_l&FeblF]bl-Fjal6%FfilFgfl,$&FeblFh_lFd_l-Fjal6%,$FgilFd_lF[jlFgflF;&FbalF[g
lF;FhdlF;*&F^flF;FaelF;F;>Fgel7$-F`^l6#Fgel-F`^l6#-%(convertG6$-Fjdl6$&Fbfl6$;F
;Fj\lF_elFegl%%listG>8'-%$mapG6$%'expandGFgel@$0Fb]lF;OFa[m>8(-%&minusG6$-%'ind
etsG6#Fa[m-F_\m6#Fd]l>6$8)8*-%,poly2matrixG6$Fa[mFj[m>8+-%$srtG6$Ff\m-%%tdegG6#
-F`^l6#Fj[m6%7$%#cfG-%/permuteColumnsG6%Fe\mFf\mF[]mFa\lFb\lF_zF_zF_z6#Fgfl6:7'
F]`lFd_lF_]lF^]lF``l7'F]`lFd_lF[]l"#d"#V7'F]`lFd_lF[]l""*Fb`l7'F]`lFd_l""("#&*F
_^m7'F]`lFd_lFc^mF^^mF_^m7'F]`lFd_lF[]l"#YF_^m7'F]`lFd_lF[]l"#EF_^m7'F]`lFd_lF[
]l"#IF_^m7'F]`lFd_lF[]l"$R"F_^m7'F]`lFd_lF[]l"#@F_^mF^_m7'F]`lFd_lF[]l"#6F_^m7'
F]`lFd_lF[]l"")Fc_m7'F]`lFd_lFc^m"#>F_^m7'F]`lFd_lFc^mF`xF_^m7'F]`lFd_lFc^m"$@"
F_^mFe^m7'F]`lFd_lF[]l"#CF_^m7'F]`lFd_lF[]l"#SFb`l7'F]`lFd_l"#B"#K"#_7'F]`lFd_l
F[]l"#QF_^m7'F]`lFd_lF[]lF``lF_^m7'F]`lFd_lF[]l"#LF_^m7'F]`lFd_lF[]l"#`"#JF_z
