M7R0
I;F_relpose_7p_fuv_angle_sat7&,N%"aG#!*L%*)HY".+++++g"%"bG#!-(4%*=%*R'"/+++++DJ
%"pG#!/*[7F=n$f"1+++++++5*$F%""##")<PEq"-+++++?*&F)"""F%F7#!+6c#)=8F(*$F)F2#!0*
[6Wn#pt"F0*(F%F7F)F7F-F7#"(P<i(")+++]*$F%""%#!$3""(DJ&>*$F%""$#"&fI""*++Dc"*$F)
FB#!)jM$G%"*+++]#*$F)FG#!-\3.mHY".++++++"*&F%F2F-F7#!'.kE")++]7*$F-F2#!)*pZ"[FN
*&F%FGF)F7#!%M?FE*&F-F7F%F7#"*^<zS&"+++++!)*&F)F2F%F2#"'">7(")++]i*&F)F2F-F7#!)
pO[X"*+++D"*&F)F7F%F2#")f>i;"+++++D*&F-F7F)F7#!-\'p2/o%FR*&F%F7F)FG#")P!p$QFN*&
F%F7F)F2#"+`WC:<",+++++%#!-6tYOEmF0F7,NF%#!/F&yui#\MF0F)#"0z=)H]a`D"0+++++++&F-
#"0$HD"*4rLFF0F1#!.x(*GSvI$"/++++++SF6#!0*oy0T9g_F0F:#"0f=b@MS;$FhpF=#"(\>M(FNF
A#"'>4)*F^oFF#"+T_.6;FRFK#"("4[A")++DJFO#",P2gx<#",++++D'FS#")$=5d'FNFW#")ZU&f"
F@FZF[pFgn#!-n95ko:FRF[o#!)2!*4JFNF_o#")(GKQ*FNFco#!-\78G$3$FRFgo#"-4sQ+>!*FRFj
o#!($>R>")+]i:F]p#!-J]Gj16"-+++++D#".2fw%o'y$"/+++++]iF7,NF%#!0J.tjK:F#"2++++++
++#F)#"2BOz'pgA2h"3++++++++]F-#"2V(R@ah+$Q(F[tF1#!/h)*Qzr3K"1+++++++;F6#!1FXwa!
p1`$FhsF:#"36mARCKRWQ"4+++++++++"F=#!**zE4L"*+Dcw*FA#")6g.h",+++Dc"FF#"*<qM#R"-
+++++SFK#",$>j-cM"-++++]7FO#"0(fhcMi#)QFhpFS#",r.d`d#FauFW#",pjQc\"",+++]7$FZ#"
+6X[jJF]rFgn#!/<3tnJ9a"0++++++D"F[o#"+ns(ob"",++++]#F_o#","e?v*Q*FauFco#!.jsge(
H<"/++++++?Fgo#"0heTFX/H#"0++++++]#Fjo#!,Z'*zUV#F]rF]p#!/rotas5IFds#"2RLN*e&p!o
6FetF7,NF%#"0>fwZ&Qv["2++++++++%F)#"3t2hF-%>RE%FetF-#"3$*yony4;(f"FetF1#!0ZTv+A
9P#"2+++++++g"F6#!1P)4w*H"zT#FbwF:#"4hT$Q[%Qr/b$"4+++++++++#F=#!,.4S1n#F]rFA#")
TW(y""+++]7yFF#!+(Hr_k)".+++++]#FK#",*)oe#3MFauFO#"0B@kAK;I$FhvFS#!,^VPe7"F5FW#
"-4\*339#FRFZ#"*61Ft'F[uFgn#"/<8Mc\rMF0F[o#"*td#H:"+++++5F_o#"-t:m`W[FRFco#!/r1
8B\QQFhvFgo#"1<]&fS&\'>"F0Fjo#!,ZL[*RHF]rF]p#!/>@dq*4s""/++++]i:#"2*Gt'fI6Xo&F^
xF76",
I;C_relpose_7p_fuv_angle_satw,6#>%)symbolicGF762%&_nameG%&_sizeG%#AAG%$eqsG%%va
rsG%#C0G%#V0G%"VG%"FG%$tauG%"KG%#KKG%"GG%$eq1G%"iG%"jG6"FczC1>6$8$8%6$7$8,8-7$7
$FGFG7$F7F7@%/9$F7>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F_
\l6#82w,6$%"xG%"yGFcz6$%)operatorG%&arrowGFcz-&T'6#T%6#,&Fi\lF7*&,&9%F7!""F7F7&
&T#Ff^l6#F7F7F7FczFcz6(F[[lF_\lFh[lF[^lFjzF^\l6#F26$7'Q!FczF]_l"#R"#u"#O7'Ff_lF
]_lFg_l"#XFi_l/F[^l;F7-%%nopsG6#F^\lC$>F[]l7#-F^]l6$-%'rndMatG6#Ff]lF\`l>&&F[]l
Fa_l6$;FczFczFG,&*&&F[al6$F]alF7F7-%$rndGFczF7F7*&&F[al6$F]alF2F7FbalF7F7>6$Fb
\lFc\l6$F[al&&F[]l6#F26$F7F7>8.-I$<,>GFd]l6%-I$<|gr>GFd]l6%%"fG""!F%-Fdbl6%Fgbl
FfblF)-Fdbl6%FgblFgblF7>8/-I(algsubsG6$Fc]lFd]l6$/*$FfblF2F--I".G6$Fc]lFd]l6$F_
bl)F_bl%#%TG>80,&*&-&I.LinearAlgebraG6$Fc]lFd]l6#_F`dl%&TraceG6#-Fecl6&Fb\lF]cl
)Fb\lFiclF]clF7Fb\lF7#F7F2-Fecl6'Fb\lF]clFhdlF]clFb\lF]_l>81,(*&,&*$Fc\lF2F7F]_
lF7F7F^dlF7Fidl*&,&Fc\lF7F7F7F7-F_dl6#-Fecl6&F]clFb\lF]clFb\lF7F7*&Fc\lF7-F_dl6
#-Fecl6$F]clFb\lF2F]_l>8'7$-F^]l6$-F^]l6$&F[dl6$F[^l83/F[^l;F7FG/FfflFhflF]el>F
^fl7&&F^flFa_l&F^fl6#""&,&&F^fl6#""*F7&F^fl6#"")F7&F^fl6#"#5>F^fl-%$mapG6$%'exp
andGF^fl@$/Fi\lFgblOF^fl>8(-%&minusG6$-%'indetsG6#F^fl-Fhhl6#7#F[]l>6$8)8*-%,po
ly2matrixG6%F^fl-F_`lFihlFchl>8+-%$srtG6$F`il-%%tdegG6#-Fg]l6#Fchl6%7$%#cfG-%/p
ermuteColumnsG6%F_ilF`ilFfilF^\lF_\lFczFczFcz6#Fgbl667'Ff_lF]_l"#;""'Fi_l7'Ff_l
F]_lFG"#Y"#V7'Ff_lF]_lFGFcglF[`l7'Ff_lF]_l""("#&*F\[m7'Ff_lF]_lF_[m"#dF\[m7'Ff_
lF]_lF_[m"#cF\[m7'Ff_lF]_lFG"#HF\[m7'Ff_lF]_lFG"#MF\[m7'Ff_lF]_lFG"#IF\[m7'Ff_l
F]_lFG"#jF\[m7'Ff_lF]_lFG"$J"F\[m7'Ff_lF]_lFG"#\F\[mF_\m7'Ff_lF]_lFG"#DF\[m7'Ff
_lF]_lFG"#SF[`l7'Ff_lF]_l"#A"#K"#_7'Ff_lF]_lFGFd\mF\[m7'Ff_lF]_lFGF[`lF\[mFi[m7
'Ff_lF]_lFG"#]"#JFcz
