M7R0
I4F_relpose_6p_rad_1s7,,\p%"xG#"*t))G_%"*+++]#%"yG#"),`\nF(%"zG#"*2b^\""*++++"*
&F,"""F%F1#!+B]e99F(*&F,F1F)F1#"*">uD]F(*$F%""##!)8XmO")+]i:*$F)F8#")ZyUv")++]i
*&F,F1F)F8#!+.:E95F(*&F)F1F%F1#")V_:uF(*&F,F8F%F8#!+xzX0@"*++++&*&F,F1F%F8#"+(p
vH<#FI*&F,F8F%F1#"+^n^PAFI*&F,F8F)F8#"*\+$>8"*+++D"*&F,F8F)F1#!+@5H-@FI*&F,F8F)
""$#"*d5&z[FI*&F,F1F)FX#"(ph"H")++DJ*(F)F1F,F1F%F1#!*@'3C@F/*(F,F8F%F1F)F1#!*@;
i*zFI*(F,F8F%F8F)F1#"*n9A3&F(*(F,F8F%F1F)F8#"*Rvq[%FI*(F,F1F)F1F%F8#!+8M([4"F(*
(F,F1F)F8F%F1#"*2zO3$FS*(F,FXF%F8F)F1#!)`X@5FI*(F,FXF)F1F%F1#")d")p?")+++D*(F,F
XF)F8F%F1#")Rb"f""+++++5*$F)FX#!(xqa$")++]7*$F%FX#").UVAFip*$F,FX#")dh16Fap*&F)
F1F%F8#")hyZUF(*&F%F1F)F8#!),^)G*Fap*$F,F8#!(\0o("(+]7$*&F,F8F%FX#!*plk<"F(*&F,
F1F%FX#!*44C>#FS*&F,FXF%FX#")jK:cFep*&F,FXF%F8#!)67yAFep*&F,FXF%F1#!+ZYK!G"FI*&
F,FXF)FX#!)"emb$FS*&F,FXF)F8#"*Z+Q3#"*++++#*&F,FXF)F1#"*J!f&Q&FI#!)$*)\O%FSF1,
\pF%#!*<U'>YFIF)#"*8X')o#F(F,#")\_OQF/F0#!+(f??7"F(F4#!**oI;GF?F7#!+j>P(R"FIF<#
"(`Un*FhnF@#!*8o(=eF(FC#!+T4uo:F(FF#"*$H7OFFIFJ#"*^qbC#FIFM#"+J9'zg"FIFP#"+x8WJ
<FIFT#"+tf))z6FIFW#!*6'pYCFIFen#")LD%o"FipFin#"+p<=9:F(F\o#!*pD**H"F?F_o#"*\ptO
$FIFbo#"*P)\#\"F_sFeo#!),58nF/Fho#"*^I7/"FhnF[p#!)f_"*RFIF^p#")(4@o#FapFbp#!*4u
,C$FepFfp#!)ju)*HF?Fjp#"*Z&fihFIF]q#")"4(y))")+++]F`q#"*V2</#F(Fcq#!)(40V*F?Ffq
#!("\tf"(DJ&>Fjq#!(t7A)FepF]r#!)Z'*RIFIF`r#!*T"**QYFepFcr#!*t)GfMFepFfr#!)B#*om
FIFir#!)**H5hF(F\s#!*>58o(FepF`s#"*^#\E6FI#"*F0R2"F(F1,hnF%#"%"4""&Dc"F)#"'hg<"
'+]7F,#"'JsA"'++]F0#"'@=UFayF4#!(xJ0#FayF7#!'>I:"'++DF<#!'P#G"FhyF@#!'h)y"FhyFC
#!(VwJ#FayFF#!'8%o$FhyFJ#!'z,:FayFM#!'xg<F^yFP#"'^l>F^yFT#"'r0aFhyFW#!'d@5F^yFe
n#"'rH<F^yFin#"(^H"GFayF\o#!&`j%F[yF_o#"'6n=FayFbo#!'J#)Q"(+++"Feo#!(Z(y=FayFho
#"(\b5"FayFfp#!$=)"%DJFjp#"'`uQFhyF`q#"',dCFhyFcq#!&,\""&++"Ffq#!'T]TFayFjq#!(z
=6"Fe[lF]r#!'H]7F^y#"&$RnFhyF1,\pF%#"*66/"\F(F)#"*"o\(3#F(F,#"*\dBH'F(F0#!+8@:^
<FIF4#"*zlJ["FSF7#!*ZxqY"F(F<#!)Z_zlFSF@#")p3W*)FSFC#"*R?=N&F(FF#"*L=b>"FIFJ#"*
n4mN(FIFM#"+"G*QT5FIFP#!+x#ok+"FIFT#!)B4"R""(+++&FW#!*@$pGNFIFen#"*tyL!>FSFin#!
)V'fM$")+++?F\o#!)6EA9FapF_o#!)f9WKF^wFbo#")ppLGF/Feo#"'n_nF/Fho#!+BzQ'4"F(F[p#
")PMhlFepF^p#"*>G9d"FIFbp#"(()*>VFapFfp#!*8q_9"F?Fjp#!)$zLt$FSF]q#"*R&*3Z'FIF`q
#"*R\"45F^wFcq#")$[yX&FhnFfq#!+HTCN;FIFjq#!(pm7$FhnF]r#")(y?=%FSF`r#"*n(>6BFIFc
r#")$QG]#F(Ffr#")2"z3"FSFir#"*\0%z^FepF\s#"*d#pPFFIF`s#"*heAe%FI#"'<`[FapF1,\pF
%#"+"o,:+"FIF)#")BdVzF(F,#"+RRTy7FIF0#!+Bj1h7F(F4#!*$*)HjMFIF7#!*no(QdFIF<#!)`=
K;F?F@#"(pbh&FapFC#!*`&Q1FF(FF#!+67s)p"FepFJ#"*z3'G()FIFM#")d**=UF;FP#"*zL]^'Fe
pFT#!*ziv%zF(FW#"*`@#eSFIFen#!*Zz&o;FSFin#!*Rn'4!)F(F\o#"*hS%*\"FapF_o#"*HDSh(F
(Fbo#!*dV7%HF(Feo#!*^YWJ"FIFho#"(21a*"(+++#F[p#!)n?\%)FepF^p#"(8Z`*FapFbp#"*T?u
s"FIFfp#")z%QH#FipFjp#"*f'e;6F(F]q#"*nH"\zFIF`q#!("*\b*F^wFcq#!(r-6%F?Ffq#!+VH/
e>FIFjq#")JQ^&)F/F]r#!)hN-PFapF`r#"(\U$R"(+D"yFcr#"+$Gy?E#FepFfr#"*nLW\%FIFir#"
)``g;FepF\s#"*xc_c(FepF`s#"*$*fK$oF(#!)rY`7F/F1,hnF%#"',HsFayF)#"%H!*F[yF,#"'@o
5FhyF0#!(nEi"FayF4#!'6lQF^yF7#!'tsC"'++5F<#!&3]$F[yF@#!&Hm'"&+D'FC#!'jv))FayFF#
!'\g#)FayFJ#"&**=*"&++&FM#!&Ls#F[ilFP#"((\Y8FayFT#"&.]&FayFW#"&8T'Fe[lFen#"%rhF
c\lFin#!'hWGFdhlF\o#"'jC<F^yF_o#!'RO=Fe[lFbo#!'j4AFayFeo#"&P,)FayFho#"(z6?#FayF
fp#"&BJ'F^yFjp#"'LWCFhyF`q#!'(p`$FayFcq#!'VgLF^yFfq#!',#\&FayFjq#!'VS9FhyF]r#!&
$ywFhy#!&tv"F_hlF1,\pF%#")JV**>F(F)#!*8yHM"F(F,#"*fy@."FSF0#"+@MI67FIF4#"*>mqO%
F/F7#"*^,Pl#FSF<#"*(oO"*=FSF@#"(FRf*FapFC#"*([-G()F(FF#!*JLu"**FIFJ#"(V_'eF^wFM
#!)^Y]dF(FP#!*`u9p&F(FT#!*6qM*>F?FW#"*>O&=VFIFen#!*Pw1D$FSFin#!+Ljh;<FIF\o#"+.9
Pc:FIF_o#"(`hu#FiqFbo#!+<sys5FIFeo#"*jNv!RF(Fho#"*hz8(>FSF[p#!*Ly`)GFIF^p#!*>@!
3mFIFbp#")L8#Q#F(Ffp#")4z@8FipFjp#!)$\'>!)FSF]q#!*ti"yQFIF`q#!)2MK8")+++5Fcq#")
Z`yNFSFfq#"*$Q*Q$HFIFjq#")PQhDF^wF]r#!*`0.m#FIF`r#"(8xv(FapFcr#"*\.:$pFIFfr#!*^
zx&>FIFir#"("ffhF/F\s#"*>vq;"F(F`s#")T#>;$F?#")$GVe"F(F1,\pF%#!*Fp8g&F(F)#!*>o=
@#F(F,#!*z2f2)FIF0#"*@7X0%FIF4#!*6l=!QFIF7#")n1\!)F?F<#"("fP`"(]i!RF@#!)$>4@(Fa
pFC#!**GV05F^wFF#!*P$oiZF_sFJ#!*4*z`7FIFM#"*Zr)*>"FIFP#"+*R14k"FepFT#!'Pe^FeflF
W#"*LrkS&FIFen#!'R'*)*FewFin#"*p^ea'F(F\o#!+V_KjAFIF_o#!)>\G6F`_lFbo#"*>L&=8F_s
Feo#!+RkO95F(Fho#!)r*\.#FapF[p#!)dzs=F_sF^p#!(\xT#F;Fbp#"*(=sk@FepFfp#!)rx[BF?F
jp#")V!**H*F/F]q#!**)3bh$FIF`q#"*<4h$GF(Fcq#!)<DDgF?Ffq#"*Ho2X%FIFjq#!+*RRA;"Fe
pF]r#")8(z1"F/F`r#!)Z(=q#")+++SFcr#!+L;Z!\"FepFfr#!*(f[&o#FSFir#!)$)oLjF_sF\s#"
*tc2:$FepF`s#!*hk7g"FI#")BelUFIF1,hnF%#"(4+L"FayF)#"'BS<FayF,#"'h(\"F[ilF0#!'jn
6FdhlF4#"&@j&"&]7$F7#"&r9%F_hlF<#"&h'=F^yF@#!'d[>F^yFC#"(<2X"FayFF#!(H))3"Fe[lF
J#"'8;>F_hlFM#"&t/#F^yFP#!'hUkFe[lFT#!'2ZAF_hlFW#"&**=(FayFen#"'F,GFhyFin#!(*)3
<"FayF\o#!'n^@F_hlF_o#!'$y&RFayFbo#!&^]%FayFeo#!'J[PFayFho#!(zUp"FayFfp#!&ZQ#"&
+D"Fjp#!&F`$F_hlF`q#"&\**)FhyFcq#"&LI#FhyFfq#!'$e>)FayFjq#"'"*)e%FayF]r#!'R1FFh
y#!&Z[#F^yF1,hnF%#"'<oAFhyF)#!'FTKFayF,#"'*=9#Fe[lF0#!'"R:'Fe[lF4#"(>hD#Fe[lF7#
"&"=^FayF<#!%@F"&++#F@#"'^#R%FayFC#"(P;Q"FayFF#"%.HF[ilFJ#"'Ri7F^yFM#"'6J#)Fe[l
FP#!'(3A#"'++?FT#!'TD`Fe[lFW#"%MWF[yFen#!'t&y#FayFin#!'$Rb$FhyF\o#"'zoZFe[lF_o#
!&zV"FbfmFbo#"&tt#FayFeo#"'8'f%FayFho#!'LwfFhyFfp#"%tb"&+]#Fjp#!&>V(FhyF`q#"'z'
>#FayFcq#"&H3%Fg\nFfq#"'JmSFe[lFjq#"'x\KFayF]r#!'"\9"Fay#!&\k"F[ilF16",
I4C_relpose_6p_rad_1sw,6#>%)symbolicGF165%&_nameG%&_sizeG%#_AG%"iG%#hhG%#vvG%#e
1G%#e2G%#e4G%#e5G%#e7G%#e8G%"EG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"Ff]nC4>6$8
$8%6$7#%"HG7#7$""'F[`n@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fe_n6#8'Ff]n/F\an;F1-
%%nopsG6#Fd_n>Fa`n7#-Fd`n6$-I'MatrixG6$%*protectedG%(_syslibG6$Fi`nw,6$F%F)Ff]n
6$%)operatorG%&arrowGFf]n-&T'6#T%6#,&F^`nF1*&,&9%F1!""F1F1&&T#Fdbn6#F1F1F1Ff]nF
f]n6(F^^nFe_nF`^nF\anF]^nFd_n6#F86$7'Q!Ff]nF[cn"#P"#s"#O7'FdcnF[cnFecn"#VFgcnF]
an>8(&Fa`nF_cn>8)-I$<,>GFjan6(F0F4F%F)F,F1>8*-I".G6$FianFjan6$&F[dn6$F1;Ff]nFf]
nF^dn>8+-Fedn6$&F[dn6$F8FjdnF^dn>8,-Fedn6$&F[dn6$FXFjdnF^dn>8--Fedn6$&F[dn6$""%
FjdnF^dn>8.-Fedn6$&F[dn6$""&FjdnF^dn>8/-Fedn6$&F[dn6$F[`nFjdnF^dn>80-F`dn6%-I$<
|gr>GFjan6%FcdnFbenF_fn-F`gn6%F\enFhenFffn-F`gn6%F%F)F1>817$&-%(convertG6$,&-Fe
dn6$,$-Fedn6$F\gn)F\gn%#%TGF8F\gnF1*&-&I.LinearAlgebraG6$FianFjan6#I&TraceG6$Fi
anFjan6#FahnF1F\gnF1F[cn%%listGFf]n-&Fhhn6#%,DeterminantG6#F\gn>82-%$mapG6$%'ex
pandGFggn@$F]`nOFein>83-%&minusG6$-%'indetsG6#Fein-Fbjn6#Fa`n>6$8485-%,poly2mat
rixG6$FeinF]jn>86-%$srtG6$Fijn-%%tdegG6#&F]jnFf]n6%7#-%/permuteColumnsG6%FhjnFi
jnF^[oFd_nFe_nFf]nFf]nFf]n6#F_`n687'FdcnF[cn"#;F[`nFgcn7'FdcnF[cnFX"#KFicn7'Fdc
nF[cnFX""*"#X7'FdcnF[cn""("#bFicn7'FdcnF[cnFe\o"#$*Ficn7'FdcnF[cnFX"#8Ficn7'Fdc
nF[cnFX"#IFicn7'FdcnF[cnFX"#?FicnF]]oF]]oF]]oF]]oF]]o7'FdcnF[cnFX"#MFicn7'FdcnF
[cnFX"$+"Ficn7'FdcnF[cnFX"#CFicn7'FdcnF[cnFX"#RFc\o7'FdcnF[cn"#A"#J"#_7'FdcnF[c
nFX"#QFicn7'FdcnF[cnFXFgcnFicn7'FdcnF[cnFXFi]oFicn7'FdcnF[cnFX"#ZFi]oFf]n
