M7R0
I.F_relpose_4pt7',X%"xG#!#9"$D"%"vG#"$`""%+]%"yG#"$i""$D'%"wG#"%$G#F,%"zG#!%">'
"&]7$*$F%""##!&")H("'+]i*&F%"""F-F>#!#H"&Dc"*&F%F>F4F>#"#")F0*$F-F9#"#@"%+5*&F-
F>F4F>#""(F(*(F4F>F%F>F1F>#!&$pV"'+]7*(F4F>F%F>F)F>#"&")H(F<*(F-F>F%F>F)F>#!$,*
"%+D*(F4F>F-F>F1F>#!#@FH*(F4F>F-F>F)F>#"%d<F,*(F-F>F%F>F1F>#!"$"#?#!&B7""&D"yF>
*&F1F>F-F>#!&2j&"&+D'*&F)F>F-F>#F;"'+DJ*&F1F>F%F9#"$,*FV*&F)F>F4F>#FU"%]7*&F1F>
F%F>#FY"$+&*&F)F>F%F>#!%VAFV*&F1F>F4F>#""$"#5*&F-F9F)F>#FcpFjn*&F4F9F1F>#!"(F(*
&F4F9F)F>#!#")F0,XF%#"$"RF0F)#"#LF,F-#!$*>"$]#F1#"$F'F,F4#!'$e8(F<F8#!'FS6"'++]
F=#"'(\l#"(++D"FB#FcqF]pFE#"&$4["']i:FI#!$"RFjoFL#!'dfFF^rFP#"'FS6F[rFS#"$t&FVF
W#!&$4[FbrFZ#"$B&FaoFgn#"$Y#F0#"'f!)f"(+++&F>F^o#!'VSsF<Fbo#Fjq"'++DFeo#!$t&FVF
ho#FjrFjoF[p#F\sF]oF^p#!&x%\F7Fap#!$#\F0Fep#!$Y#F0Fgp#F_qFjoFjp#"$*>F]p,XF%#!""
""&F)#!$L'F,F-#!#BF0F1#"$J)FVF4#!'6k5F<F8#"%BYFdoF=#!&*e%*F^rFB#F\uFjoFE#!$d#"&
++"FI#F>FdpFL#!$*zFVFP#!%BYFdoFS#!$,#F0FW#"$d#FhuFZ#"'*3%\F^rFgn#FavFVF^o#!%,7F
joFbo#FbuFbrFeo#"$,#F0Fho#!$-%F0F[p#FavF,F^p#!'6f]F<Fap#FguFjoFep#FguFVFgp#FgtF
dpFjp#"#BFjo#!&**3%"(++]#F>,XF%#"$8*FjoF)#"$z)FHF-#!$,(FjoF1#"%@=F,F4#"'$4G"F<F
8#!'`s5F^rF=#!'ruSF^rFB#F]xFVFE#!'$Qu"F<FI#!$8*FVFL#!'6.OF^rFP#"'`s5F^rFS#F+Fjo
FW#"'$Qu"F<FZ#"'"*QQF<Fgn#!$">F0F^o#!'*oR'F<Fbo#FcxF<Feo#!$`"FjoFho#F+F0F[p#Fay
FdoF^p#!'4h6FdoFap#"$#QF0Fep#"$">F0Fgp#FiwFVFjp#"$,(FV#!(d!o8FfwF>z+6%F%F-F4[[[
[[[[[][[[mF>[[[[][[[[[[[mF>][[[[[[[[[[[mF>!Fgt6",
I.C_relpose_4ptt+6#>%)symbolicGF>6/%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%#V0G
%"VG%$cthG%$sthG%#txG%"rG%"EG6"FjzC.>6$8$8%6$7%%#x1G%#x2G%#thG7%7$F9""%Fj\l7$F>
F>@%/9$F>>8&-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fc\l6#%"iGf*6
$F%F-Fjz6$%)operatorG%&arrowGFjz-&T%F_^l6#,&F_]lF>*&,&9%F>FgtF>F>&&T#F_^l6#F>F>
F>FjzFjz6&Fb[lFc\lFa[lFb\l/F`^l;F>-%%nopsG6#Fb\l>Fa]l6$-Fc]l6$-%'rndMatG6#F[^l/
F`^l;F>,&Fe_lF>FgtF>-I$<,>GFi]l6#-Fc`l6#-I'arccosG6$Fh]lFi]l6##FcpFht>6$8,8-6$-
I$cosG6$Fh]lFi]l6#&&Fa]l6#Fcp6$F>F>-I$sinG6$Fh]lFi]lFdal>6$8.8/6$-Fc`l6%-I$<|gr
>GFi]l6%""!FgtF1-Fdbl6%F>Ffbl,$F)Fgt-Fdbl6%,$F1FgtF)Ffbl-Fc`lFiz>80-I".G6$Fh]lF
i]l6$F^bl,(*&F^alF>-&I.LinearAlgebraG6$Fh]lFi]l6#_Fhcl%/IdentityMatrixGFgalF>F>
*&,&F>F>F^alFgtF>-Facl6$F_bl)F_bl%#%TGF>F>*&F_alF>-Fc`l6%-Fdbl6%Ffbl,$&F_blFgal
Fgt&F_bl6#F9-Fdbl6%FidlFfbl,$&F_blFa_lFgt-Fdbl6%,$FjdlFgtF_elFfblF>F>>8'7$-Fc]l
6$&-Facl6%)-Fc`l6$&&Fa]lFa_l6$;FjzFjzF`^lF>FbdlF_cl-Fc`l6$&&Fa]lF[elF`flF>Fhal/
F`^l;F>F[]l,&-Facl6$FadlF_blF>FgtF>>Fdel-%$mapG6$%'expandGFdel@$/F_]lFfblOFdel>
8(-%&minusG6$-%'indetsG6#Fdel-Figl6#7#Fa]l>6$8)8*-%,poly2matrixG6%Fdel-Ff_lFjgl
Fdgl>8+-%$srtG6$Fahl-%%tdegG6#-F\^l6#Fdgl6%7$%#cfG-%/permuteColumnsG6%F`hlFahlF
ghlFb\lFc\lFjzFjzFjz6#FfblFjz
