M7R0
I7F_relpose_7p_fuv_angle7&,N%"xG#"-()>/'pa""/+++++DJ%"yG#!-8#3=tA&"0++++++D"%"z
G#".8]-"y3y"/+++++]i*$F%""##",$e*3kn#".+++++D'*&F%"""F)F7#!.(*)Q(4&QPF0*$F)F2#"
/$o;L.jZ#F0*$F%""%#"$V$"'++D*$F%""$#!((oYP"*+++D'*$F)F>#!)jT$)H"*+++D"*$F)FC#"-
t-KX_6"-++++]7*(F%F7F)F7F-F7#!*P%RV7"*++++"#!-8g[,\jF,F7*&F%F2F-F7#")^+R5FR*$F-
F2#!)(Rs!o"*++++&*&F%FCF)F7#!&6m""'++]*&F%F7F-F7#!,Z(y$*yn"-+++++D*&F)F2F%F2#")
*p1,$FR*&F)F2F-F7#!*\]4)=Fen*&F)F7F%F2#"*2Nh^$"++++DJ*&F)F7F-F7#"-$*)\aK>"FN*&F
%F7F)FC#!*Ps,@"FR*&F%F7F)F2#!-j%oYZv"F]o,NF%#!/pI$=2<A#F0F)#"/zDEG3;PF0F-#"-J&[
)f"['F(F1#".jWjz&\<".++++]7$F6#!/R$*e(*3-rF(F:#!/\BXI6a8F(F=#"(h#yD")+++DFB#!,
\a6>*[FNFG#!'T9`")++DJFK#"+(4B7>#",+++Dc"FO#!*p1")Q"FR#".P7R'fGEF(F7FU#!)$4AR"F
enFX#!)p.*R(FenFfnF\pFjn#!+(yo5C$FNF^o#!*<vP[$FenFao#!)H<"o#FRFdo#"-"Q"RA+OFNFh
o#"+F;$G6""+++++5F[p#!(zTA#")++]7F^p#",*4@x')o",++++D',NF%#!0*>_*)G`e(*"2++++++
+D"F)#"1r)yusBJH"FfsF-#"0d.&\eVPL"1++++++]iF1#"1n=Q&oDK)=FfsF6#!1V!oB(z)*oMF[tF
:#"1Z)=L"pS+7Ffs#"0.a(R?u+k"2++++++++&F7F=#"*$>"e3"FgoFB#!.B*Qv40vF0FG#!+2:6cP"
,+++]7$FK#"/$=$p4E;IF0FO#!,V9"488",++++D"FU#",@l;z())".++++++"FX#!,jMQih'FcuFfn
#!,\8y&*4#",+++++&Fjn#!.F#=]_C8".++++D"yF^o#!,^@Mkw$FcuFao#!-ZM$R5@#FcuFdo#"-B"
4G#*\)"-++]il(*Fho#"/@%>?;7C%F0F[p#!,BW'y_JFhuF^p#!.Z5pI_\%F0,NF%#!1Z[C_!z_,*"3
+++++++]7F)#"28vgv3;x$RF\wF-#"2rkGvRq]_'"2+++++++D'F1#"2,%y6!*GG*="F\wF6#!2x6Mt
i7^%H"2++++++]7$F:#"3T5/SNX7'Q"F\wF=#")@")3l"+++++]FB#!-*GUh(4r"/+++++]7FG#"+pl
;:()FNFK#!/t!*3QT$f$F0FO#",87)pN5",++++]##"24G;7,El/""3++++++++]F7FU#".(RGEoxO"
.++++++#FX#".,^/!4"z$F[yFfn#!+<Z7_J",+++++"Fjn#!0f$zt%**3Z("0++++++]#F^o#"-pOGj
"R("-+++++SFao#"-hB\**3yFfyFdo#"/x\DOK&o%"/++++++]Fho#!.RD]fH0'F,F[p#",6geuk$Fh
uF^p#!0()zFtq/>(Fcy6",
I7C_relpose_7p_fuv_anglew,6#>%)symbolicGF763%&_nameG%&_sizeG%#_AG%"iG%#F1G%%tau
1G%"KG%#KKG%"GG%$eq1G%$eqsG%"jG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FbzC1>6$8$8%6$7$
%"fG%$tauG7$7$FCFC7$F7F7@%/9$""!C$>8&7#-%$seqG6$-%'rndMatG6#&&F_\l6#8'Fbz/Fh]l;
F7-%%nopsG6#F^\l>&&F]]l6#F76$;FbzFbzFC,&*&&F`^l6$Fc^lF7F7-%$rndGFbzF7F7*&&F`^l6
$Fc^lF2F7Fh^lF7F7>F]]l7#-F`]l6$-I'MatrixG6$%*protectedG%(_syslibG6$Fe]lw,6$F%F)
Fbz6$%)operatorG%&arrowGFbz-&T'6#T%6#,&Fi\lF7*&,&9%F7!""F7F7&&T#F_`lFa^lF7F7Fbz
Fbz6(FjzF_\lF\[lFh]lFizF^\l6#F26$7'Q!FbzFf`l"#P"#s"#O7'F^alFf`lF_al"#VFaalFi]l>
6$8(8)6$F`^l&&F]]l6#F26$F7F7>8*-I$<,>GFe_l6%-I$<|gr>GFe_l6%Fb\lFj\lF%-Fcbl6%Fj
\lFb\lF)-Fcbl6%Fj\lFj\lF7>8+-I(algsubsG6$Fd_lFe_l6$/*$Fb\lF2F--I".G6$Fd_lFe_l6$
F^bl)F^bl%#%TG>8,,&*&-&I.LinearAlgebraG6$Fd_lFe_l6#I&TraceG6$Fd_lFe_l6#-Fbcl6&F
falFjbl)FfalFfclFjblF7FfalF7#F7F2-Fbcl6'FfalFjblFedlFjblFfalFf`l>8-,(*&,&*$Fgal
F2F7Ff`lF7F7F[dlF7Ffdl*&,&FgalF7F7F7F7-F\dl6#-Fbcl6&FjblFfalFjblFfalF7F7*&FgalF
7-F\dl6#-Fbcl6$FjblFfalF2Ff`l>8.7$-F`]l6$-F`]l6$&Fhcl6$Fh]l8//Fh]l;F7FC/FcflFef
lFjdl>F[fl7&&F[flFa^l&F[fl6#""&,&&F[fl6#""*F7&F[fl6#"")F7&F[fl6#"#5>80-%$mapG6$
%'expandGF[fl@$Fh\lOFhgl>81-%&minusG6$-%'indetsG6#Fhgl-Fehl6#F]]l>6$8283-%,poly
2matrixG6$FhglF`hl>84-%$srtG6$F\il-%%tdegG6#&F`hlFbz6&7#-%/permuteColumnsG6%F[i
lF\ilFailFailF^\lF_\lFbzFbzFbz6#Fj\l667'F^alFf`l"#;""'Faal7'F^alFf`lFC"#YFcal7'
F^alFf`lFCF`gl"#X7'F^alFf`l""("#bFcal7'F^alFf`lFhjl"#cFcal7'F^alFf`lFhjl"#$*Fca
l7'F^alFf`lFC"#JFcal7'F^alFf`lFC"#GFcal7'F^alFf`lFC"#HFcal7'F^alFf`lFC"#nFcal7'
F^alFf`lFC"$Q"Fcal7'F^alFf`lFC"#[Fcal7'F^alFf`lFC"#\Fcal7'F^alFf`lFC"#CFcal7'F^
alFf`lFC"#RFfjl7'F^alFf`l"#AF_[m"#_7'F^alFf`lFC"#QFcal7'F^alFf`lFCFaalFcalF^[m7
'F^alFf`lFC"#^F_[mFbz
