M7R0
I.F_relpose_4pt7',X%"vG#"$`""%+]%"xG#!#9"$D"%"yG#"$i""$D'%"wG#"%$G#F(%"zG#!%">'
"&]7$*(F4"""F)F9F1F9#!&$pV"'+]7*(F4F9F)F9F%F9#"&")H("'+]i*(F-F9F)F9F%F9#!$,*"%+
D*(F4F9F-F9F1F9#!#@"%+5*(F4F9F-F9F%F9#"%d<F(*(F-F9F)F9F1F9#!"$"#?*$F)""##!&")H(
F@*&F)F9F-F9#!#H"&Dc"*&F)F9F4F9#"#")F0*$F-FQ#"#@FH*&F-F9F4F9#""(F,*&F1F9F-F9#!&
2j&"&+D'*&F%F9F-F9#FS"'+DJ*&F1F9F)FQ#"$,*FD*&F%F9F4F9#FC"%]7*&F1F9F)F9#FG"$+&*&
F%F9F)F9#!%VAFD*&F1F9F4F9#""$"#5*&F-FQF%F9#F`pFO*&F4FQF1F9#!"(F,*&F4FQF%F9#!#")
F0#!&B7""&D"yF9,XF%#"#LF(F)#"$"RF0F-#!$*>"$]#F1#"$F'F(F4#!'$e8(F@F8#!'dfF"(++D"
F=#"'FS6"'++]FA#"$t&FDFE#!&$4["']i:FI#"$B&F^oFL#"$Y#F0FP#!'FS6F^rFT#"'(\l#F[rFX
#FcqFjoFen#"&$4[FcrFhn#!$"RFgoF[o#!'VSsF@F_o#Fir"'++DFbo#!$t&FDFeo#F`rFgoFho#Fb
rF\qF[p#!&x%\F7F^p#!$#\F0Fbp#!$Y#F0Fdp#FaqFgoFgp#"$*>Fjo#"'f!)f"(+++&F9,XF%#!$L
'F(F)#!""""&F-#!#BF0F1#"$J)FDF4#!'6k5F@F8#!$*zFDF=#!%BYFaoFA#!$,#F0FE#"$d#"&++"
FI#"'*3%\F[rFL#FhuFDFP#"%BYFaoFT#!&*e%*F[rFX#F\uFgoFen#!$d#FiuFhn#F9FapF[o#!%,7
FgoF_o#F^vFcrFbo#"$,#F0Feo#!$-%F0Fho#FhuF(F[p#!'6f]F@F^p#FcvFgoFbp#FcvFDFdp#Fit
FapFgp#"#BFgo#!&**3%"(++]#F9,XF%#"$z)FHF)#"$8*FgoF-#!$,(FgoF1#"%@=F(F4#"'$4G"F@
F8#!'6.OF[rF=#"'`s5F[rFA#F'FgoFE#"'$Qu"F@FI#"'"*QQF@FL#!$">F0FP#!'`s5F[rFT#!'ru
SF[rFX#F]xFDFen#!'$Qu"F@Fhn#!$8*FDF[o#!'*oR'F@F_o#F^yF@Fbo#!$`"FgoFeo#F'F0Fho#F
hxFaoF[p#!'4h6FaoF^p#"$#QF0Fbp#"$">F0Fdp#F[xFDFgp#"$,(FD#!(d!o8FfwF9z+6%F)F-F4[
[[[[[[[][[[mF9[[[[][[[[[[[mF9][[[[[[[[[[[mF9!Fit6",
I.C_relpose_4ptw,6#>%)symbolicGF961%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V
0G%#_VG%"iG%$cthG%$sthG%#txG%"rG%"EG%$eqsG6"FjzC.>6$8$8%6$7%%#x1G%#x2G%#thG7%7$
FQ""%F\]l7$F9F9@%/9$F9>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6
#&Fe\l6#8,w,6$F)F-Fjz6$%)operatorG%&arrowGFjz-&T'6#T%6#,&Fa]lF9*&,&9%F9FitF9F9&
&T#F\_l6#F9F9F9FjzFjz6(Fb[lFe\lFi[lFc^lFa[lFd\l6#FQ6$7'Q!FjzFit"#R"#u"#O7'F[`lF
itF\`l"#XF^`l/Fc^l;F9-%%nopsG6#Fd\l>Fc]l7$-Ff]l6$-%'rndMatG6#F^^l/Fc^l;F9,&Fc`l
F9FitF9-I$<,>GF\^l6#-Faal6#-I'arccosG6$F[^lF\^l6##F`pFjt>6$8-8.6$-I$cosG6$F[^lF
\^l6#&&Fc]l6#F`p6$F9F9-I$sinG6$F[^lF\^lFbbl>6$8/806$-Faal6%-I$<|gr>GF\^l6%""!Fi
tF1-Fbcl6%F9Fdcl,$F%Fit-Fbcl6%,$F1FitF%Fdcl-FaalFiz>81-I".G6$F[^lF\^l6$F\cl,(*&
F\blF9-&I.LinearAlgebraG6$F[^lF\^l6#_Ffdl%/IdentityMatrixGFeblF9F9*&,&F9F9F\blF
itF9-F_dl6$F]cl)F]cl%#%TGF9F9*&F]blF9-Faal6%-Fbcl6%Fdcl,$&F]clFeblFit&F]cl6#FQ-
Fbcl6%FgelFdcl,$&F]clFf_lFit-Fbcl6%,$FhelFitF]flFdclF9F9>827$-Ff]l6$&-F_dl6%)-F
aal6$&&Fc]lFf_l6$;FjzFjzFc^lF9F`elF]dl-Faal6$&&Fc]lFielF^glF9Ffbl/Fc^l;F9F]]l,&
-F_dl6$F_elF]clF9FitF9>8'-%$mapG6$%'expandGFbfl@$0Fa]lF9OFjgl>8(-%&minusG6$-%'i
ndetsG6#Fjgl-Fhhl6#Fc]l>6$8)8*-%,poly2matrixG6$FjglFchl>8+-%$srtG6$F_il-%%tdegG
6#-F_^l6#Fchl6%7$%#cfG-%/permuteColumnsG6%F^ilF_ilFdilFd\lFe\lFjzFjzFjz6#Fdcl62
7'F[`lFit"#;""'F^`l7'F[`lFitF`p"#f"#V7'F[`lFitF`p""*F``l7'F[`lFitFjn"#&*Fjjl7'F
[`lFitFjn"#wFjjl7'F[`lFitF`p"#YFjjl7'F[`lFitF`p"#[Fjjl7'F[`lFitF`p"$="Fjjl7'F[`
lFitF`p"#zFjjl7'F[`lFitF`p"#CFjjl7'F[`lFitF`p"#SF``l7'F[`lFitFcw"#K"#_7'F[`lFit
F`p"#QFjjl7'F[`lFitF`pF^`lFjjl7'F[`lFitF`pF_qFjjl7'F[`lFitF`p"#`"#JFjz
