M7R0
I,F_refract5p7%zen6%%"xG%"yG%"zG\[[[[[[[^[[[o!62zJLLffXwh*\[[[\[[[][[[o!8WLT)oH
aD:Fv%*][[[[[[[][[[o"9RF[NUKb!R!>6A\[[[][[[\[[[oF)][[[\[[[\[[[o"9Q$fdI#et?vkzF^
[[[[[[[\[[[o"9&*p:)3hd_[0LY"\[[[^[[[[[[[oF*][[[][[[[[[[o!80w!H'eqm8tj=*^[[[\[[[
[[[[o!7QEu))f^%RZ."**_[[[[[[[[[[[o!8b6xeRg0oFs+#[[[[[[[[^[[[n"8WLT)oHaD:Fv%*[[[
[\[[[][[[nF)\[[[[[[[][[[n!9E*y@pw**zY,&p\[[[[][[[\[[[nF1][[[[[[[\[[[n!91k'G1x//
+J!)4#[[[[^[[[[[[[nF)\[[[][[[[[[[nF2][[[\[[[[[[[n!8t")GxV)[!zg(zT^[[[[[[[[[[[n"
8g4DWOA'e-)*zQ[[[[[[[[][[[m"80w!H'eqm8tj=*[[[[\[[[\[[[mF,\[[[[[[[\[[[mF4[[[[][[
[[[[[m!9RF[NUKb!R!>6A\[[[\[[[[[[[m"91k'G1x//+J!)4#[[[[[[[[\[[[l"7QEu))f^%RZ."**
[[[[\[[[[[[[lF-\[[[[[[[[[[[lF5!"8b6xeRg0oFs+#z3F%[[[[\[[[\[[[m"6'39wMQgD@27\[[[
[[[[\[[[m!5Fe_EL,0Gn")\[[[\[[[[[[[m!6_;sj6B'RJ%3#][[[[[[[[[[[m!6"o+T`uI&>EC"[[[
[[[[[\[[[l"6_;sj6B'RJ%3#[[[[\[[[[[[[lF=\[[[[[[[[[[[l"5E-,0&Hle9N)!"6"o+T`uI&>EC
"z5F%[[[[[[[[][[[m"5Vq!Q<>!G1Og\[[[[[[[\[[[m!47J'yQ5E^$=$[[[[][[[[[[[m!5Vq!Q<>!
G1Og\[[[\[[[[[[[m!5mB/R@SR$f-"][[[[[[[[[[[m!4``j*e^K[0E[[[[[[[[\[[[l"5mB/R@SR$f
-"[[[[\[[[[[[[lFE\[[[[[[[[[[[l"5[#QtW#HO0,Y!"4``j*e^K[0E6",
I,C_refract5pw,6#>%)symbolicG"""66%&_nameG%&_sizeG%#_AG%"iG%#rrG%#ccG%$eqsG%"kG
%%varsG%"MG%"VG%#V1G%#M1G%$tM1G%%solsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FLC6>6$8$
8%6$7$%#xxG%"XG7#-%"$G6$7$""$""&""#@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fgo6#8'F
L/Fdq;FR-%%nopsG6#Ffo>Fip7#-F\q6$-I'MatrixG6$%*protectedG%(_syslibG6$Faqw,6$F&F
'FL6$%)operatorG%&arrowGFL-&T'6#T%6#,&FfpFR*&,&9%FR!""FRFR&&T#F\s6#FRFRFRFLFL6(
FUFgoFWFdqFTFfo6#Fcp6$7'Q!FLFcs"#P"#s"#O7'F\tFcsF]t"#VF_tFeq>8(-%-getRotMatrixG
6#-I$<,>G6$FarFbrF%>8)-Fht6%%"vG%"wGFgp>8*7#-F\q6$*&-I'factorG6$FarFbr6#-I".G6$
FarFbr6$)-&I.LinearAlgebraG6$FarFbr6#%-CrossProductG6$-F[v6$)Fct%#%TG&&FipFgs6$
;FLFL8+,&&&Fip6#FcpF\wFRF[uFcsFiv-Fht6%FgpFgpFRFRz+F%[[[[[[[[][[[mFR[[[[][[[[[[
[mFR][[[[[[[[[[[mFR!FRFR/F^w;FRFbp>Fau-%$mapG6$%'expandGFau>8,7'F^uF_uF&F'F(>6$
8-8.-%,poly2matrixG6$FauF^x>8/-Fht6<*(F^uFRF'FRF(FR*(F^uFRF&FRF'FR*&F^uFRF(Fcp*
&F'FRF&FR*$F&Fcp*&F^uFRF&FR*(F_uFRF&FRF(FR*&F_uFRF'FR*&F^uFRF(FR*&F^uFRF&Fcp*&F
_uFRF&Fcp*&F^uFRF'Fcp*&F_uFRF'Fcp*$F'Fcp*&F_uFRF(Fcp*(F_uFRF&FRF'FR*&F_uFRF(FRF
^uF_uFR*$F(Fcp*&F&FRF(FR*&F'FRF(FRF&F'F(>80-%/permuteColumnsG6%FbxFcxFhx@%Fep>8
1-&Fav6#%6ReducedRowEchelonFormG6#F`z>Ffz-F_r6#7'7<FRFgpFgpFgpFgpFcsFcsFcsFgpFg
pFgpFgpFgpFgpFgpFgpFgpFgpFgp-%"AG6#"#r-Fb[l6#"#w-Fb[l6#"#")-Fb[l6#"#')-Fb[l6#"#
"*-Fb[l6#"#'*-Fb[l6#"$,"7<FgpFRFgpFgpFgpFgpFgpFgpFRFgp-Fb[l6#"#FFgp-Fb[l6#F]tFg
p-Fb[l6#"#ZFgpFgpFgp-Fb[l6#"#n-Fb[l6#F^t-Fb[l6#"#x-Fb[l6#"##)-Fb[l6#"#()-Fb[l6#
"##*-Fb[l6#"#(*-Fb[l6#"$-"7<FgpFgpFRFgpFgpFgpFgpFgpFgpFRFgpFcsFgpFgpFgp-Fb[l6#"
#`-Fb[l6#"#eFcsFgp-Fb[l6#"#t-Fb[l6#"#y-Fb[l6#"#$)-Fb[l6#"#))-Fb[l6#"#$*-Fb[l6#"
#)*-Fb[l6#"$."7<FgpFgpFgpFRFgpFgpFgpFgpFgpFgpFgpFgpFgpFgpFgpFgpFgpFgpFgp-Fb[l6#
"#u-Fb[l6#"#z-Fb[l6#"#%)-Fb[l6#"#*)-Fb[l6#"#%*-Fb[l6#"#**-Fb[l6#"$/"7<FgpFgpFgp
FgpFRFgpFgpFgpFgpFgpFgpFgpFgpFcsFgpFgpFgpFgpFgp-Fb[l6#"#v-Fb[l6#"#!)-Fb[l6#"#&)
-Fb[l6#"#!*-Fb[l6#"#&*-Fb[l6#"$+"-Fb[l6#"$0">Fau7#-F\q6$-F[v6$&Ffz6$FdqF]wFhx/F
dqFgw>82&-I&solveG6$FarFbr6$7$&FauFgs&FauFbw7$F^uF_uFgs>Fau-Fjw6$%&numerG7%-Fgu
6#-%%subsG6$Ficl&Fau6#Fap&Fau6#""%&Fau6#Fbp>83Fiw@$FepOFeel>84-%&minusG6$-%'ind
etsG6#Feel-F^fl6#Fip>6$8586-Fex6$FeelFiel>87-%$srtG6$Fefl-%%tdegG6#&FielFL6&7$F
`z-Fbz6%FdflFeflFiflFiflFfoFgoFLFLFL6#Fgp6<7'F\tFcs"#;""'F_t7'F\tFcsFap"#RFat7'
F\tFcsFap""*"#X7'F\tFcs""("#bFat7'F\tFcsF`hlF\`lFat7'F\tFcsFap"#JFat7'F\tFcsFap
"#<Fat7'F\tFcsFap"$@"Fat7'F\tFcsFap"#DFatFihl7'F\tFcsFap"#KFat7'F\tFcsFap"$Y"Fa
tF[ilF\hl7'F\tFcsF`hlFj^lFat7'F\tFcsF`hl"$(fFat7'F\tFcsFapF_tFat7'F\tFcsFap"#WF
at7'F\tFcsFap"#lFat7'F\tFcsFap"#CFat7'F\tFcsFapF[hlF^hl7'F\tFcs"#AFdhl"#_7'F\tF
csFap"#QFatFbilFchl7'F\tFcsFapFahlFdhlFL
