M7R0
I4F_relpose_6p_rad_1s7,,\p%"xG#")H=b*)"*+++D"%"yG#!)2!R0'"+++++5%"zG#"+`t:h5"*+
+++&*&F-"""F%F2#!*Jq/$[F0*&F-F2F)F2#!(tH&**")++DJ*$F%""##!+(eH)45F,*$F)F:#!)t!*
fd"*++++#*&F-F2F)F:#"'*[D#"']7y*&F)F2F%F2#"*@^%=?"*+++]#*&F-F:F%F:#!*Z]FU"F@*&F
-F2F%F:#"*Pwvb#FH*&F-F:F%F2#!*nnN(HFH*&F-F:F)F:#!+x#>cq$F,*&F-F:F)F2#"+2RI$G"F0
*&F-F:F)""$#!+")QI%R"F,*&F-F2F)FY#"*LqRf"FH*(F)F2F-F2F%F2#"+^exC7F0*(F-F:F%F2F)
F2#"*R7bG%F(*(F-F:F%F:F)F2#"*h.**=$F,*(F-F:F%F2F)F:#"*4B@A(F0*(F-F2F)F2F%F:#"+,
L#px"F0*(F-F2F)F:F%F2#!*V6.&>"*++++"*(F-FYF%F:F)F2#"(rv-(")+++]*(F-FYF)F2F%F2#"
)*oFa)F0*(F-FYF)F:F%F2#!)*))o,&")++]i*$F)FY#!+p#HMc"F,*$F%FY#!****3M<FH*$F-FY#!
(P.Y""(]i!R#"),JTjF,F2*&F)F2F%F:#"+8gU$)=F,*&F%F2F)F:#"*$eVGPF[p*$F-F:#!*.BXr%F
H*&F-F:F%FY#!)T\lRFH*&F-F2F%FY#!(He`$"(+D"y*&F-FYF%FY#!(,s-$F(*&F-FYF%F:#!'P$y#
"(+Dc"*&F-FYF%F2#!)663>Ffp*&F-FYF)FY#"*p5@<(F0*&F-FYF)F:#!)ZX0YFfp*&F-FYF)F2#!*
L!Q?AFH,\pF%#")J'*QnF,F)#!+$Rwmm"F,F-#!*Hc.*HF0F1#")">^)**FHF5#"+tBtI\F,F9#"),G
`lFfpF=#")xo]N")+++?FA#!+4$G$)G"F0FE#"*ry6W#FHFI#!(R*GXFHFL#!*6:"QWF(FO#!+peDq;
F0FR#")B<._F0FU#"*(fOP()F0FX#!+8.<i6F,Ffn#"+`U_D6F,Fin#"*.$)p'oF[pF\o#!+$*Q(Qg#
F0F_o#!*F4&>IF,Fbo#!+Rj$z_"F,Feo#"*.h\g*F,Fho#!+()Hv,9F0F\p#"*6^/y"F,F`p#!)f%>4
'FHFcp#!)\Xb#)F(Fgp#!+JQ)QK#F,Fjp#!+"oLCQ"F,F]q#"(6yb'F8Fcq#"+z2n7SF,Ffq#!+,(\m
#GF,Fiq#!*jI/i"FHF\r#!($pvUF,F_r#!*pn'3CF0Fcr#!(.\K)F0Ffr#"'J,'*")+++5Fjr#")*["
3IFfpF]s#!*T(oZQF,F`s#!**[G$>&FHFcs#!)rwj**F_p#")rqg_FHF2,hnF%#!&**H&"'++?F)#!'
JuA"'++]F-#"'J>:"'++DF1#"&$ol"&+D'F5#!&(4>"&+D"F9#!&tK&"&]7$F=#!&68$"&+]#FA#"(<
&3GF_yFE#"'j6!*F_yFI#!%ByFhyFL#"((yw6F_yFO#!'PIJF_yFR#"&P)H"'+]7FU#"'^%Q&F_yFX#
!'Pb>"'++5Ffn#"'8h<FbyFin#!'^ECFeyF\o#"'6i=F`[lF_o#"'p.CF_yFbo#"&,d("(+++"Feo#!
%VPF`[lFho#"'p(*>F`[lFgp#"&Z0'F`[lFjp#"'"pm#F\yFcq#!&"fM"&++#Ffq#"%LKF\yFiq#"&*
><F^zF\r#!'n2;F[\lF_r#"&nE#F[[l#!'8'e$F_yF2,\pF%#"*")*>C7F@F)#"*r1w!pF0F-#"*L$)
H@#F@F1#"+pd')*G#F,F5#!+"3#z#[#F0F9#")46qLF_pF=#!)z9^HF(FA#"+`7\.IF,FE#!*,xZV#F
[pFI#!*Z^G)GFHFL#"*LFXT'F,FO#!*jY%y_FHFR#!*6fns%F(FU#"*$*RI#eF0FX#"*p0Bd"FfpFfn
#!*nfW.%F(Fin#!+"=%p49F0F\o#"*LX$G")F0F_o#!)H=b)*F0Fbo#!+F&)pw9F,Feo#")$>())yF(
Fho#"*P#=4CF@F\p#!).N`7")+++DF`p#!*t3y-$F(Fcp#"+@*Q?4"F,Fgp#"*,!p_FF(Fjp#")"zJX
*F@F]q#")t-uPFHFcq#!+*3,kW"F0Ffq#"*Ts/@)F@Fiq#!)t)e")*F0F\r#!)*e"R5F,F_r#!*`')Q
\#F,Fcr#")JS$\"F@Ffr#"*TBL5%F,Fjr#"*xS>d"FHF]s#!)`wuMF8F`s#"+.3@IJF,Fcs#!*PC<D"
F_p#!)P"['QF[pF2,\pF%#!+*o$>&R"F,F)#"+tn!oJ"F,F-#!*,Ie7#FHF1#"+(yNR+#F,F5#"*.$*
z<(F,F9#!)`HZQF8F=#!*4;rd$FHFA#!*rq$)G&F(FE#"*L^;D$F(FI#"*Jb`,"FHFL#"*2()3M(F0F
O#"*Z.(R7FHFR#"*d`rp%F0FU#!*PWx)oF0FX#!+j$fHG"F,Ffn#")Bh[))")+++SFin#!)`b`v")++
]7F\o#")B$*3=F0F_o#!*P%o3=F@Fbo#"+^Q;JIF,Feo#!*hRJj*F,Fho#!+`=\UKF,F\p#!&L)o"(+
+g"F`p#!)83VCF(Fcp#!*dZ)Q8F,Fgp#!+diSU<F,Fjp#!*z8"4GF,F]q#"*(Ri\5FHFcq#!*8h8W(F
,Ffq#"+*zQiP"F,Fiq#"*4;NA*F0F\r#"*xa+Z"F,F_r#")*z?J%F,Fcr#"(ngU(F@Ffr#"*"=4T6F0
Fjr#"*V8yt#F0F]s#"*(HBh$*F,F`s#")(4-p#F0Fcs#!)"f=$>Ffp#!*Bt^S%F0F2,hnF%#"&`E)F[
[lF)#!'\VAF\yF-#"'H*Q"F_yF1#!'(G$GFbyF5#"&Z)QF^zF9#!'(o+$F_yF=#"'x&['FbyFA#"(fz
?"F_yFE#!&z7$"&Dc"FI#!'**z7F_yFL#!'n#R$FbyFO#!'(zG"F_yFR#!'"\-#"&++&FU#!%$G#"%+
DFX#!'4&="F\yFfn#!(*zY:F_y#"%(Q&F[[lF2Fin#"($)p>"F_yF\o#"&pd(FbyF_o#"'F3sF[\lFb
o#!'([(GF[[lFeo#!&`9#FeyFho#"'VRZFbyFgp#!'JP")F[\lFjp#!'`'="F_yFcq#"'.BUF[\lFfq
#"'HKPF_yFiq#!&h&eFcilF\r#!%,hFcilF_r#!'$zL#F_y,\pF%#!)Hx/")F0F)#"*`[^,$F@F-#!)
^PBWF[pF1#!*2+[9$F(F5#!+P/dt;F,F9#")4?HXF@F=#"*>t)eCF,FA#")FKz'*FfpFE#"*z">_XF0
FI#"*$f)zm"F,FL#!)j"[!>FgdlFO#"*$*elb&FHFR#!*4$4M")F,FU#!*<:f3"F[pFX#"+jsXA9F,F
fn#!*$e`%*\F,Fin#!)*eEY'F8F\o#"*n*zS[F0F_o#!+^cF'="F,Fbo#"*zn"R#)F0Feo#!+8_]e:F
,Fho#"+*fC(*G"F0F\p#!**oJ&3#F,F`p#!(>1z$F(Fcp#")Z5]YF[p#"*j;[u&F,F2Fgp#"+d#oN8"
F,Fjp#!(`">B"(+]7$F]q#!)$>cm)FHFcq#!**3,"y*F,Ffq#"*(e6XwFHFiq#!*@?4J$F0F\r#"(`0
)zFfpF_r#!)4KeXF0Fcr#"(.4p)F0Ffr#!'LRKF`_mFjr#!)R)z3"FetF]s#")n:9<FddlF`s#"*p>X
N%FHFcs#")`cx<Fgdl,\pF%#")"=]$yF(F)#"*>0c-"F@F-#"+z%\6E"F,F1#")**o?SF@F5#!)V?=g
F0F9#!*`%ou"*F,F=#!+$3b[w#F,FA#"*HBW7&F,FE#"+jtuA;F0FI#")^1<7F@FL#"*x@-R%F,FO#!
)"[;J"")+]i:FR#!+xE%\8%F,FU#")(y<)\F[pFX#!*dxVP#F@Ffn#"*T1EL%FHFin#!)RPfyFetF\o
#"*$)H-V#FHF_o#!)"*z'H%F,Fbo#!*$Hq*["F(Feo#!*Ts#yUFHFho#!*<#*y^%F,F\p#")ps2UF0F
`p#!(HgQ%FgdlFcp#!*^MVI(F,Fgp#!*\"*)35F,Fjp#"*j/MC"F0#!*"4bJDF,F2F]q#!)$)z8aFHF
cq#!)F"[Y#FddlFfq#!*\tYF"F[pFiq#!*,f3g(F0F\r#")LYedF0F_r#")P].iF@Fcr#!($337F,Ff
r#!(()Q#HF@Fjr#")*['35FHF]s#"),/J&*F[pF`s#!)Z`s>FddlFcs#!*46FS%FH,hnF%#!'$)[@F_
yF)#"(H\_"F_yF-#"'.<JF_yF1#!&x/*FeyF5#"'RtBF_yF9#!(4?C"F[\lF=#!'n1xF[\lFA#"&9t#
FjhlFE#"'(*)p'F_yFI#!&TR"F\yFL#"'nXoF_yFO#!&F9#F[[lFR#!(8g!>F[\lFU#"%>mFbyFX#"'
TR5FbyFfn#!($e35F_yFin#"&Z#HFcilF\o#"'\uZF_yF_o#"%<^F^zFbo#!&@J)FbyFeo#"'P'\'Fb
yFho#"%>cFjhlFgp#"(TVL"F_yFjp#!'*pn"Fby#!'zhIF[\lF2Fcq#"(fvC"F_yFfq#"&Hb'FbyFiq
#!'t0AFbyF\r#!%R]FbyF_r#!',[<F_y,hnF%#!'p)f"F\yF)#"&hQ(FcilF-#!&<n&F[[lF1#"'Hfx
F[\lF5#!'@E;F\yF9#!'FO&)F[\lF=#!'Vl')F_yFA#!'<xVF[\lFE#"'d;qF_yFI#!&n"[F_yFL#"&
@F$FeyFO#!&(\')F[\lFR#"'xk6F[[lFU#"'8FqF[\lFX#"'.hwF[\lFfn#"'<'f#F_yFin#!'>rGF`
[lF\o#"'Hp]F[\lF_o#!'6vBF[\lFbo#"'"4r&F[\lFeo#!'HwgF[\lFho#!&8M'F`[lFgp#"'zU<F[
[lFjp#!&Py"F`[l#!'T5FF_yF2Fcq#"&@v$FbyFfq#!'h?DFbyFiq#"&f&QFcilF\r#"%*p$F\yF_r#
!&(39F\y6",
I4C_relpose_6p_rad_1sw,6#>%)symbolicGF265%&_nameG%&_sizeG%#_AG%"iG%#hhG%#vvG%#e
1G%#e2G%#e4G%#e5G%#e7G%#e8G%"EG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"Fe]nC4>6$8
$8%6$7#%"HG7#7$""'Fj_n@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fd_n6#8'Fe]n/F[an;F2-
%%nopsG6#Fc_n>F``n7#-Fc`n6$-I'MatrixG6$%*protectedG%(_syslibG6$Fh`nw,6$F%F)Fe]n
6$%)operatorG%&arrowGFe]n-&T'6#T%6#,&F]`nF2*&,&9%F2!""F2F2&&T#Fcbn6#F2F2F2Fe]nF
e]n6(F]^nFd_nF_^nF[anF\^nFc_n6#F:6$7'Q!Fe]nFjbn"#P"#s"#O7'FccnFjbnFdcn"#VFfcnF
\an>8(&F``nF^cn>8)-I$<,>GFian6(F1F5F%F)F-F2>8*-I".G6$FhanFian6$&Fjcn6$F2;Fe]nFe
]nF]dn>8+-Fddn6$&Fjcn6$F:FidnF]dn>8,-Fddn6$&Fjcn6$FYFidnF]dn>8--Fddn6$&Fjcn6$""
%FidnF]dn>8.-Fddn6$&Fjcn6$""&FidnF]dn>8/-Fddn6$&Fjcn6$Fj_nFidnF]dn>80-F_dn6%-I$
<|gr>GFian6%FbdnFaenF^fn-F_gn6%F[enFgenFefn-F_gn6%F%F)F2>817$&-%(convertG6$,&-F
ddn6$,$-Fddn6$F[gn)F[gn%#%TGF:F[gnF2*&-&I.LinearAlgebraG6$FhanFian6#I&TraceG6$F
hanFian6#F`hnF2F[gnF2Fjbn%%listGFe]n-&Fghn6#%,DeterminantG6#F[gn>82-%$mapG6$%'e
xpandGFfgn@$F\`nOFdin>83-%&minusG6$-%'indetsG6#Fdin-Fajn6#F``n>6$8485-%,poly2ma
trixG6$FdinF\jn>86-%$srtG6$Fhjn-%%tdegG6#&F\jnFe]n6&7#-%/permuteColumnsG6%FgjnF
hjnF][oF][oFc_nFd_nFe]nFe]nFe]n6#F^`n687'FccnFjbn"#;Fj_nFfcn7'FccnFjbnFY"#KFhcn
7'FccnFjbnFY""*"#X7'FccnFjbn""("#bFhcn7'FccnFjbnFd\o"#$*Fhcn7'FccnFjbnFY"#8Fhcn
7'FccnFjbnFY"#IFhcn7'FccnFjbnFY"#?FhcnF\]oF\]oF\]oF\]oF\]o7'FccnFjbnFY"#MFhcn7'
FccnFjbnFY"$+"Fhcn7'FccnFjbnFY"#CFhcn7'FccnFjbnFY"#RFb\o7'FccnFjbn"#A"#J"#_7'Fc
cnFjbnFY"#QFhcn7'FccnFjbnFYFfcnFhcn7'FccnFjbnFYFh]oFhcn7'FccnFjbnFY"#^Fh]oFe]n
