M7R0
I1F_rollingshutter7,,L%"vG#"&x)o"&+]#%"xG#!'Hx9"'++5%"yG#!%.N"&]7$%"wG#"'2*=""'
+]7%"zG#!(L,3""'++]#!'F29"'++D"""*$F%""##!'tuhF8*&F1F<F%F<#!'hB`F;*&F)F<F%F<#"'
VtEF,*&F-F<F%F<#!'pAIF8*&F5F<F%F<#!'h&*fF;*$F1F>#!'\l5"(+++"*&F)F<F1F<#"&zr'"&+
D'*&F-F<F1F<#"&^h&FT*&F5F<F1F<#"'HkDF,*$F)F>#!'>`OF8*&F-F<F)F<#"'re8F8*&F5F<F)F
<#"&z:'F8*$F-F>#"',YuFP*&F-F<F5F<#"(4(f5F8*$F5F>#"'8F:F;,LF%#!&Rd"F;F)#"'@;!*F8
F-#!&2s("&++&F1#!'.g9F4F5#!'VaHF;#!(ZN1"FPF<F=#!'ZeIF8FA#!'hrMF8FD#"'TRWF8FG#!'
R^ZF;FJ#!&Ly&F8FM#!%.()F(FQ#"'Bo>F;FU#"(@J?"F;FX#"'h0CF,Fen#!'Bh>F8Fhn#!'VPCF8F
[o#!'hXNF8F^o#!'hrDFPFao#"&td#F8Fdo#"&jg""&++%,LF%#!'$Rm%F;F)#"'"[z"F8F-#"'pR!*
F;F1#"&xO"F^pF5#"'4m8F8#!'hO5F8F<F=#!&xS%F4FA#"'<SAFTFD#!'()fhF;FG#"%#*["&Dc"FJ
#"&PW$F0FM#!($=Q8FPFQ#"',J8F,FU#!'RSrF8FX#!'2HGF8Fen#"&^l&F;Fhn#"&43)F8F[o#!&"[
$*F8F^o#"'**GKF8Fao#"'f&o"F4Fdo#!&Z(>Fcr,LF%#!'hL6FTF)#"'hKNF;F-#"'2F5F^pF1#!&f
y""&+D"F5#"'<UmF;#!&jO#F^pF<F=#!(T!45FPFA#!&@L)F;FD#"'BVdF8FG#"&f&HF0FJ#"'(4?*F
8FM#"'@j$)FPFQ#"&P_'F;FU#!&x'oF4FX#!'PH^F8Fen#!'niIFPFhn#!'p?FF8F[o#!'B#*pF8F^o
#"&8%eFcrFao#"&*oMF8Fdo#!'Zm;"'++?,LF%#"'j&*fF8F)#"&>p%FPF-#!'(H]&F8F1#!'2shF8F
5#"'Bq_FPF=#"'\r=F8FA#!'6*f"F\xFD#"%,)*FTFG#!&HZ%F4FJ#!'n()eFPFM#"'pt#*FPFQ#!'4
njFPFU#"(\!H8FPFX#!'*30"FPFen#"&2c&FPFhn#!'8(R"F;F[o#"'^*R$F8F^o#"'49ZFPFao#"'<
ZKFPFdo#!'dzDF8#"'J"3#FPF<,LF%#"'*R$eFPF)#!'"pF(FPF-#!(Ptz"FPF1#!'Z;MFPF5#!'J!G
'F8F=#!&B"zF;FA#"'6:XF8FD#!'P)=#F;FG#!'r5YFPFJ#!&"))*)F;FM#!&pr"F^pFQ#"'^^*)FPF
U#"&rL*FPFX#!'(H&)*FPFen#"&hy"FPFhn#"&jh$F\xF[o#"&jF&FTF^o#!&FF%F,Fao#"'HPPFPFd
o#"'FC`FP#"'$>(HF8F<,LF%#!'pvfFPF)#"%B^F\xF-#!'^)3$FPF1#!&rQ'F\xF5#"&@:"FiuF=#"
'ttiFPFA#"(xQ7#FPFD#!'Vr8F,FG#!'(pF&F8FJ#!(@2]"FPFM#!'>'f#F8FQ#!'tm7F8FU#!'"ym"
F8FX#"',TJFPFen#"'8)Q"F8Fhn#"($)z0"FPF[o#"&PM#F^pF^o#"&fX"FcrFao#!&Lf"F(Fdo#!%"
G#"&++##"&p-#F,F<,LF%#"'f_(*FPF)#!&T+)F8F-#"&$p**F,F1#"&*z6FisF5#!'8LeFPF=#"'*G
4"F8FA#!&@&\FTFD#"&T3#F8FG#"'>S=F\xFJ#"'H!Q"F4FM#!%ZCFisFQ#"'>'4&FPFU#!(nDl#FPF
X#!'J%G$F8Fen#!&ty*FPFhn#"'J?[F8F[o#!&Fp'F\xF^o#"'(>V"FPFao#!&L&RF4Fdo#"&*[iF8#
!&//"FisF<,LF%#"'"yD#F4F)#!&z/%F0F-#"&*Q)*F;F1#!&<I&F4F5#"'(>Q"F8F=#!'*)>$)FPFA
#!'4R=F4FD#"($)H5"FPFG#"%8X"%]iFJ#"&,1"F\xFM#!'pG5FPFQ#"&`i#F(FU#"&(R%*F,FX#"'Z
V]F8Fen#!'."e$FPFhn#!'4uAF8F[o#"&xq$FPF^o#"&p5"FTFao#!%p7FPFdo#!'.wUFP#"&t1&F4F
<,LF%#!'$*RtFPF)#"(^#)="FPF-#"'$p#)*FPF1#!(hd6"FPF5#"'Z&>'F8F=#"'@P6FPFA#"'h"4(
FPFD#"&p4"FPFG#"'`/zF8FJ#!&x?%F,FM#!'295F8FQ#!%2#)F,FU#!'n"3#FPFX#!'@e?F8Fen#!&
*QqFPFhn#!'2OSF8F[o#"'j#R$FPF^o#!'V'p%FPFao#!%Ls"%+!)Fdo#!&$pEF^p#!'(=>"F8F<6",
I1C_rollingshutterw,6#>%)symbolicGF<69%&_nameG%&_sizeG%#_AG%"iG%#v1G%#v2G%#v3G%
#v4G%#v5G%#v6G%#rvG%#r1G%#r2G%#r3G%#c1G%#c2G%#c3G%$eqsG%#_FG%&_varsG%$_C0G%$_V0
G%#_VG6"FbhlC/>6$8$8%6$7(%#V1G%#V2G%#V3G%#V4G%#V5G%#V6G7#-%"$G6$7$""*F<""'@%/9$
""!>8&7#-%$seqG6$-%'rndMatG6#&&Fejl6#8'Fbhl/Fe\m;F<-%%nopsG6#Fdjl>Fj[m7#-F]\m6$
-I'MatrixG6$%*protectedG%(_syslibG6$Fb\mw,6$F)F-Fbhl6$%)operatorG%&arrowGFbhl-&
T'6#T%6#,&Fg[mF<*&,&9%F<!""F<F<&&T#F]^m6#F<F<F<FbhlFbhl6(FjhlFejlF\ilFe\mFihlFd
jl6#F>6$7'Q!FbhlFd^m"#P"#s"#O7'F]_mFd^mF^_m"#VF`_mFf\m>6(8(8)8*8+8,8--F]\m6$-%(
convertG6$&Fj[mFd\mI'VectorG6$Fb]mFc]m/Fe\m;F<Fd[m>8.,.*&F%F<Fe_mF<F<*&F1F<Ff_m
F<F<*&F)F<Fg_mF<F<*&F-F<Fh_mF<F<*&F5F<Fi_mF<F<Fj_mF<>6%8/80816%&Ff`m6#;F<""$&Ff
`m6#;""%Fd[m&Ff`m6#;""(Fc[m>6%8283846%&Ff`m6#7%F<FjamF^bm&Ff`m6#7%F>""&"")&Ff`m
6#7%FfamFd[mFc[m>857,,&-I".G6$Fb]mFc]m6$)F_am%#%TGF_amF<-Fecm6$)F`amFicmF`amFd^
m,&FdcmF<-Fecm6$)FaamFicmFaamFd^m,&-Fecm6$)FabmFicmFabmF<-Fecm6$)FbbmFicmFbbmFd
^m,&FbdmF<-Fecm6$)FcbmFicmFcbmFd^m-Fecm6$FhcmF`am-Fecm6$FhcmFaam-Fecm6$F\dmFaam
-Fecm6$FddmFbbm-Fecm6$FddmFcbm-Fecm6$FgdmFcbm>86-%$mapG6$%'expandGFacm@$Ff[mOFi
em>87-%&minusG6$-%'indetsG6#Fiem-Fffm6#Fj[m>6$8889-%,poly2matrixG6$FiemFafm>8:-
%$srtG6$F]gm-%%tdegG6#&FafmFbhl6&7#-%/permuteColumnsG6%F\gmF]gmFbgmFbgmFdjlFejl
FbhlFbhlFbhl6#Fh[m637'F]_mFd^m"#;Fd[mF`_m7'F]_mFd^mFfam"#nFb_m7'F]_mFd^mFfamFc[
m"#X7'F]_mFd^mF^bm"#bFb_m7'F]_mFd^mF^bm"#$*Fb_m7'F]_mFd^mFfam"#jFb_m7'F]_mFd^mF
famF`_mFb_m7'F]_mFd^mFfam"#WFb_m7'F]_mFd^mFfam"#`Fb_m7'F]_mFd^mFfam"$J"Fb_m7'F]
_mFd^mFfam"#CFb_m7'F]_mFd^mFfam"#RFfhm7'F]_mFd^m"#A"#J"#_7'F]_mFd^mFfam"#QFb_mF
]im7'F]_mFd^mFfamFjimFb_m7'F]_mFd^mFfam"#^FjimFbhl
