M7R0
I1F_rollingshutter7,,L%"vG#"&HI""&+]#%"xG#"(\g:""'++D%"yG#!(4D,#"'++]%"wG#!(Jf7
"F0%"zG#"'t`fF,*$F%""##!(Pl/""(+++"*&F1"""F%F=#!&LM$F,*&F)F=F%F=#"&>8'"'+]7*&F-
F=F%F=#!("Q$3"F0*&F4F=F%F=#!&n#pFC*$F1F8#!&2r*"'++?*&F)F=F1F=#"'j.EF,*&F-F=F1F=
#!(`bC"F0*&F4F=F1F=#"'pc9F0*$F)F8#"'z%)eF0*&F-F=F)F=#!'*HX'F0*&F4F=F)F=#!'(Hf#F
0*$F-F8#!%/**"&Dc"*&F-F=F4F=#"'HarF0*$F4F8#"'`O7F;#!&px#"&+D'F=,LF%#"'RdNF0F)#"
'*f2*F0F-#!'`[CF,F1#!'<p%*F0F4#"&xV'FfoF7#"'\5KF;F<#"%$o%"&]7$F@#"'x7AFCFD#!'P%
z$F,FG#!'j5fF0FJ#!'@@BF0FN#!'*y."F,FQ#"&^O(F0FT#!'()[MF,FW#"&LW#F(FZ#!'$H'>F,Fg
n#"(xC2"F0Fjn#"'JV8F;F^o#!'x#f*F0Fao#"&"\7FC#"'JK5F;F=,LF%#!%VS"&+D"F)#!'F!4(F0
F-#"%Lq"%+SF1#"'.!Q$FCF4#!($)G+"F0F7#!&HM%"'++5F<#!'L-;F0F@#!&^*oF,FD#!'*3F)F0F
G#"&xk(F,FJ#"(BKN"F;FN#!'PIUF0FQ#"&RQ""&++&FT#!%#)R"%DJFW#"%BYFfoFZ#!'J)z$F0Fgn
#!%LjF]oFjn#!',]YF;F^o#!&tT#F,Fao#"'4$e&F0#"'LlZF0F=,LF%#!%8d"&++"F)#!'h[eF,F-#
"(j!G5F0F1#"'\!>"FatF4#!'x^FF,F7#"'>SAF;F<#"&`$oF0F@#"'*z%\F,FD#!'*zK#FCFG#"%Rl
F]oFJ#"(zQF"F;FN#!&*RmF0FQ#"&fc)FfoFT#!&(yTF0FW#!',.pF;FZ#"'")HLF0Fgn#!&@&>F,Fj
n#!%fYFatF^o#!'zw<FCFao#"&(=?F,#!'n\[F;F=,LF%#"'Zn<F,F)#"',#=$F0F-#!&")y'F;F1#!
',q&*F;F4#"'BjpF0F7#"'r1lF;F<#!'jnJF;F@#"(,A9#F;FD#!'LHLF,FG#"&Jh%FfoFJ#!'2wUF0
FN#"'PuUF0FQ#!(*G58F;FT#"'Hf()F0FW#"&`)\FCFZ#"&@v"F,Fgn#!&.u&FCFjn#!'4aGF0F^o#"
(<!e6F;Fao#!'tT")F;#"&4+%FMF=,LF%#!(>*G6F;F)#"&2m&FCF-#!'Z.QF;F1#!(H8-"F;F4#!'r
PIF;F7#!$\$"%]7F<#!&Rd$"&++%F@#!'"4J&F;FD#"&hO*F;FG#!&"G7FMFJ#!'$)o<F,FN#!'<')o
F;FQ#"&>l#Fj[lFT#"'t79FMFW#"'n,rF;FZ#!'VkbF0Fgn#!'\bIF0Fjn#"'BXBF0F^o#!'4D9F;Fa
o#!'Lo=F;#!&`L#FMF=,LF%#!'8ePF;F)#!'nDAF;F-#!&tH(F,F1#"(Zae"F;F4#!'^B^F0F7#!'H*
="F,F<#!'`S8F,F@#"&Jb&F,FD#!'8IwF;FG#!&*eQFatFJ#"'@AKF0FN#!&<z)FCFQ#"&"RSFMFT#!
'V3#)F;FW#!&^&[F,FZ#"&4*RF;Fgn#!%(G#FMFjn#!&pn'FMF^o#"&dQ)F0Fao#!%p:F;#"(Tw4"F;
F=,LF%#"&*\DF0F)#"'BKBF0F-#!'J#Q"FCF1#"'<H9F,F4#"'Pu:F0F7#"'(["QF0F<#"&pq$F;F@#
"(zs^"F;FD#!&P_*FbsFG#"'$ow&F;FJ#!&*QaF;FN#"&@X$FfoFQ#!&n1)FfoFT#"'(R#=FMFW#"&^
L$FatFZ#!'LzfF;Fgn#!&(=`F;Fjn#!'nIQF;F^o#"($=$H"F;Fao#!'P<OF;#"'\.7FMF=,LF%#!%J
]F(F)#!(\ju"F;F-#"'V?pF0F1#"'6jMFMF4#!(`f:"F;F7#!'xt<F0F<#"'@B]F;F@#!&L"[FCFD#"
&*e$)F0FG#!'xo`F0FJ#"(RS1"F;FN#!'H%*=F0FQ#"'*z4%F;FT#!'T')[F,FW#!'FIeF;FZ#"'@e5
F0Fgn#"(8">7F;Fjn#"&"**>FCF^o#!'FhJF,Fao#"&f,"F(#"'de;F,F=,LF%#!((\F8F;F)#!%zO"
%]iF-#!'@ALF;F1#"&8:"FfpF4#!'BI=FMF7#!'ZtkF;F<#!'<*z"F,F@#!&\9$FMFD#!'P-_F0FG#"
$*))"%+!)FJ#!&^H"FCFN#"&2!GFfpFQ#!',#G$F,FT#!%dXF;FW#!'LyOF;FZ#"((>G5F;Fgn#!'**
=*)F;Fjn#!'d\QF0F^o#"'^kUF0Fao#!%BaFj[l#"%,:"&++#F=6",
I1C_rollingshutterw,6#>%)symbolicGF=69%&_nameG%&_sizeG%#_AG%"iG%#v1G%#v2G%#v3G%
#v4G%#v5G%#v6G%#rvG%#r1G%#r2G%#r3G%#c1G%#c2G%#c3G%$eqsG%#_FG%&_varsG%$_C0G%$_V0
G%#_VG6"FfhlC/>6$8$8%6$7(%#V1G%#V2G%#V3G%#V4G%#V5G%#V6G7#-%"$G6$7$""*F=""'@%/9$
""!>8&7#-%$seqG6$-%'rndMatG6#&&Fijl6#8'Ffhl/Fi\m;F=-%%nopsG6#Fhjl>F^\m7#-Fa\m6$
-I'MatrixG6$%*protectedG%(_syslibG6$Ff\mw,6$F)F-Ffhl6$%)operatorG%&arrowGFfhl-&
T'6#T%6#,&F[\mF=*&,&9%F=!""F=F=&&T#Fa^m6#F=F=F=FfhlFfhl6(F^ilFijlF`ilFi\mF]ilFh
jl6#F86$7'Q!FfhlFh^m"#P"#s"#O7'Fa_mFh^mFb_m"#VFd_mFj\m>6(8(8)8*8+8,8--Fa\m6$-%(
convertG6$&F^\mFh\mI'VectorG6$Ff]mFg]m/Fi\m;F=Fh[m>8.,.*&F%F=Fi_mF=F=*&F1F=Fj_m
F=F=*&F)F=F[`mF=F=*&F-F=F\`mF=F=*&F4F=F]`mF=F=F^`mF=>6%8/80816%&Fj`m6#;F=""$&Fj
`m6#;""%Fh[m&Fj`m6#;""(Fg[m>6%8283846%&Fj`m6#7%F=F^bmFbbm&Fj`m6#7%F8""&"")&Fj`m
6#7%FjamFh[mFg[m>857,,&-I".G6$Ff]mFg]m6$)Fcam%#%TGFcamF=-Ficm6$)FdamF]dmFdamFh^
m,&FhcmF=-Ficm6$)FeamF]dmFeamFh^m,&-Ficm6$)FebmF]dmFebmF=-Ficm6$)FfbmF]dmFfbmFh
^m,&FfdmF=-Ficm6$)FgbmF]dmFgbmFh^m-Ficm6$F\dmFdam-Ficm6$F\dmFeam-Ficm6$F`dmFeam
-Ficm6$FhdmFfbm-Ficm6$FhdmFgbm-Ficm6$F[emFgbm>86-%$mapG6$%'expandGFecm@$Fj[mOF]
fm>87-%&minusG6$-%'indetsG6#F]fm-Fjfm6#F^\m>6$8889-%,poly2matrixG6$F]fmFefm>8:-
%$srtG6$Fagm-%%tdegG6#&FefmFfhl6%7#-%/permuteColumnsG6%F`gmFagmFfgmFhjlFijlFfhl
FfhlFfhl6#F\\m637'Fa_mFh^m"#;Fh[mFd_m7'Fa_mFh^mFjam"#nFf_m7'Fa_mFh^mFjamFg[m"#X
7'Fa_mFh^mFbbm"#bFf_m7'Fa_mFh^mFbbm"#$*Ff_m7'Fa_mFh^mFjam"#jFf_m7'Fa_mFh^mFjamF
d_mFf_m7'Fa_mFh^mFjam"#WFf_m7'Fa_mFh^mFjam"#`Ff_m7'Fa_mFh^mFjam"$J"Ff_m7'Fa_mFh
^mFjam"#CFf_m7'Fa_mFh^mFjam"#RFjhm7'Fa_mFh^m"#A"#J"#_7'Fa_mFh^mFjam"#QFf_mFaim7
'Fa_mFh^mFjamF^jmFf_m7'Fa_mFh^mFjam"#ZF^jmFfhl
