M7R0
I1F_rollingshutter7,,L%"vG#"&>$**"'++]%"xG#"'t/KF(%"yG#"'p^6"'+]7%"wG#"&t'R"&++
&%"zG#"'h1;"'++5*$F%""##"&\R'"'++?*&F0"""F%F>#!'P'*))F(*&F)F>F%F>#"'r)Q"F7*&F,F
>F%F>#"'nQWF(*&F4F>F%F>#!'rqS"'++D*$F0F9#!%<'*"&+D'*&F)F>F0F>#!(L$H>F(*&F,F>F0F
>#!($e&Q"F(*&F4F>F0F>#"'P?;F(*$F)F9#!'*\:("(+++"*&F,F>F)F>#!'BRHF(*&F4F>F)F>#"&
LK$F/*$F,F9#!'L'G$Fen*&F,F>F4F>#!'RN@F(*$F4F9#!'$>O$Fen#!%fBFJF>,LF%#!'p<9FJF)#
"&<N(F7F,#!'2'G"F/F0#!'([1&FJF4#!&Vn(F3F8#"&>c)FenF=#!(d^/"F(FA#"(pe["F(FD#"'nX
VF(FG#!'<hiF(FK#"&Ra)FJFO#!'60UF(FR#!'2;AF/FU#!&pG'FNFX#!&$)p#FJFfn#"'\^7F7Fin#
"'Br=F7F\o#!'JU<FJF_o#!'>\;FJFbo#!&"e`F/#!'2<&)FenF>,LF%#"%fN"&Dc"F)#!%>TF/F,#!
%Hh"&+D"F0#!(r#[8F(F4#!'FS6F3F8#"&^'pF/F=#"&n6"F3FA#!&<2#FJFD#"&,l&F/FG#"'\%4"F
/FK#"'B!y%FenFO#"'*)R^FJFR#"'TZUF(FU#"&L!>F3FX#"&V!)*F/Ffn#!&F8""&]7$Fin#"&<\&F
etF\o#!'PWoFenF_o#"'$**)RF(Fbo#"&*)3&F(#!&6?""%+!)F>,LF%#!(d&H6F(F)#"'T-SF(F,#!
%nG"%+SF0#!'>%4"FJF4#!(Jt?"F(F8#!'>$H"F<F=#"'JyXF(FA#"'r!>)F(FD#"'.eRFJFG#!%tF"
%]7FK#"&4"oF7FO#"'PJ')F(FR#"'VM!*F(FU#"(hy$=F(FX#!'")4pF(Ffn#!(.(e5F(Fin#"(>4j"
F(F\o#"&><%FNF_o#"(j\X"F(Fbo#!&Vz"F/#!'^gHF(F>,LF%#"'B'3"FenF)#!'"yJ)FenF,#!'Pg
!)F(F0#!'")f6FJF4#"'t9AFenF8#"&VS"F/F=#!'6mzFenFA#!'TFDF(FD#"%VbF/FG#"%tXF`uFK#
"(^p:"FenFO#"'")4<F<FR#"&r'G"&++%FU#"'x[OFenFX#!&FE$FNFfn#"&>3#F(Fin#"'<6wFenF
\o#"'j*z"FJF_o#"&8W'F7Fbo#"'RFnFen#"&F"=FetF>,LF%#!("ff8FenF)#!'P+XFenF,#"&p_'F
enF0#"(([v;FenF4#"&t"zF<F8#!%'R$FerF=#!'\;oFenFA#!&fb)F<FD#!'L;<FenFG#!(jTW"Fen
FK#"'(*eJF(FO#!'(3J&FenFR#!'$=U(F(FU#"'L>>F<FX#"'zQ:F<Ffn#"'pgBFenFin#!'(zl"Fen
F\o#!'P?8F/F_o#!'*z&*)FenFbo#!&2'GFJ#"'(z!>FenF>,LF%#!'(*zJFenF)#"(2FG"FenF,#"&
x,(FNF0#"&\V'FiyF4#"&6)\F<F8#!'^T;FJF=#"'*oT#FenFA#"'V\_F(FD#"'Po=FenFG#!'x!G'F
(FK#"&j<$FJFO#!'2dEFenFR#!(dK#>FenFU#"'r'="FenFX#!'r08FJFfn#!'J#G*F(Fin#"(z1N"F
enF\o#!&$\rFiyF_o#!'.N_F(Fbo#!'potFen#"'*Gf%FenF>,LF%#!'$4%>F(F)#"&*Q@FerF,#"'$
Hs)FenF0#"'P`%)F(F4#"'$=.$FJF8#"%@MFjrF=#!'F`aF(FA#"%`()F(FD#!'Z.BF(FG#!'>9WF(F
K#"%<lFerFO#!&HH"FJFR#!(x*f5F(FU#"&T)HF7FX#!%TCFNFfn#!'>BcF(Fin#!&P&QF(F\o#!(j(
e>FenF_o#!&xs(FiyFbo#!&z5#FJ#"&"f@F(F>,LF%#"'8/<F(F)#!&`]$F7F,#!($[w7FenF0#!$(f
"%+5F4#"&rf%F(F8#!'pOCFenF=#!'doDFJFA#"'*y#))FenFD#!'J)e'FenFG#!',wgF(FK#"'*='f
F(FO#"'@/BFJFR#"&Fs#FiyFU#!%,uFJFX#"&Tl"FNFfn#"'R#H"F7Fin#"'@35FenF\o#"&x!HF3F_
o#!'`c5F7Fbo#!'L!z"F<#"'Z**=F(F>,LF%#!&F\$F<F)#!&"\CF7F,#"'d7BFJF0#"'fC()F(F4#"
&"GwFJF8#"'ha9FenF=#"&6,*FJFA#"'([r*FenFD#"'8TTF<FG#"'(f/'FenFK#"'p#e"F(FO#!(r#
)f"FenFR#!(tOo"FenFU#"'(R%pFenFX#"&FO&F(Ffn#!'F.!*FenFin#!&H9"FjrF\o#!'<?GF(F_o
#"'*)zUF(Fbo#"'F97FJ#"&"[SF/F>6",
I1C_rollingshutterw,6#>%)symbolicGF>69%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%
$_V0G%#_VG%"iG%#v1G%#v2G%#v3G%#v4G%#v5G%#v6G%#rvG%#r1G%#r2G%#r3G%#c1G%#c2G%#c3G
%$eqsG6"FbhlC/>6$8$8%6$7(%#V1G%#V2G%#V3G%#V4G%#V5G%#V6G7#-%"$G6$7$""*F>""'@%/9$
F>>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fejl6#8,w,6$F)F,Fb
hl6$%)operatorG%&arrowGFbhl-&T'6#T%6#,&Fg[mF>*&,&9%F>!""F>F>&&T#Fb]m6#F>F>F>Fbh
lFbhl6(FjhlFejlFailFi\mFihlFdjl6#F96$7'Q!FbhlFi]m"#R"#u"#O7'Fb^mFi]mFc^m"#XFe^m
/Fi\m;F>-%%nopsG6#Fdjl>Fi[m7#-F\\m6$-%'rndMatG6#Fd\mFh^m>6(8-8.8/808182-F\\m6$-
%(convertG6$&Fi[mFh\mI'VectorG6$Fa\mFb\m/Fi\m;F>Fd[m>83,.*&F%F>Ff_mF>F>*&F0F>Fg
_mF>F>*&F)F>Fh_mF>F>*&F,F>Fi_mF>F>*&F4F>Fj_mF>F>F[`mF>>6%8485866%&Fg`m6#;F>""$&
Fg`m6#;""%Fd[m&Fg`m6#;""(Fc[m>6%8788896%&Fg`m6#7%F>F[bmF_bm&Fg`m6#7%F9""&"")&Fg
`m6#7%FgamFd[mFc[m>8:7,,&-I".G6$Fa\mFb\m6$)F`am%#%TGF`amF>-Ffcm6$)FaamFjcmFaamF
i]m,&FecmF>-Ffcm6$)FbamFjcmFbamFi]m,&-Ffcm6$)FbbmFjcmFbbmF>-Ffcm6$)FcbmFjcmFcbm
Fi]m,&FcdmF>-Ffcm6$)FdbmFjcmFdbmFi]m-Ffcm6$FicmFaam-Ffcm6$FicmFbam-Ffcm6$F]dmFb
am-Ffcm6$FedmFcbm-Ffcm6$FedmFdbm-Ffcm6$FhdmFdbm>8'-%$mapG6$%'expandGFbcm@$0Fg[m
F>OFjem>8(-%&minusG6$-%'indetsG6#Fjem-Fhfm6#Fi[m>6$8)8*-%,poly2matrixG6$FjemFcf
m>8+-%$srtG6$F_gm-%%tdegG6#-Fe\m6#Fcfm6%7$%#cfG-%/permuteColumnsG6%F^gmF_gmFdgm
FdjlFejlFbhlFbhlFbhl6#""!637'Fb^mFi]m"#;Fd[mFe^m7'Fb^mFi]mFgam"#n"#V7'Fb^mFi]mF
gamFc[mFg^m7'Fb^mFi]mF_bm"#&*Fjhm7'Fb^mFi]mF_bm"#dFjhm7'Fb^mFi]mFgam"#jFjhm7'Fb
^mFi]mFgamFe^mFjhm7'Fb^mFi]mFgam"#WFjhm7'Fb^mFi]mFgam"#`Fjhm7'Fb^mFi]mFgam"$X"F
jhm7'Fb^mFi]mFgam"#CFjhm7'Fb^mFi]mFgam"#SFg^m7'Fb^mFi]m"#B"#K"#_7'Fb^mFi]mFgam"
#QFjhmFbim7'Fb^mFi]mFgam"#LFjhm7'Fb^mFi]mFgamFfim"#JFbhl
