M7R0
I3F_satellite_triang7%,J#!$z""$+&"""%"zG#!#B"$D"*$F)""##F(""&*$F)""$#"#t"$+"%"y
G#!#L"$]#*&F6F(F)F(#"#>"#]*&F6F(F)F.#!$*z"%+5*$F6F.#"$(\FA*&F6F.F)F(#!$V&FA*$F6
F2#!$B%F'%"xG#!$>&FA*&FKF(F)F(#!$<%FA*&FKF(F)F.#"$^'FA*&FKF(F6F(#"$(QF'*(FKF(F6
F(F)F(#!$r)FA*&F6F.FKF(#"#wF,*$FKF.#"#"*F9*&FKF.F)F(#"")"#D*&F6F(FKF.#"$F"F'*$F
KF2#!$H#FA,J#!$H)FAF(F)#!#6F=F-#!$F%F'F1#"$*GFAF6#!$H%F'F:#"$F(FAF>#!#7F]oFB#!$
R#FAFE#!$@#FAFH#"$(>F9FK#!$$pFAFN#"$z#FAFQ#!#uF,FT#"$"RF'FW#!$h"FAFZ#"#[F,Fgn#!
#ZF,Fjn#"$8"FAF^o#"$4)FAFao#"$`$F',J#"#z"$+#F(F)#!$4%F'F-#!$B#F9F1#"#jFAF6#!$B"
F,F:#!$Z&FAF>FipFB#!#$)F,FE#F2""%FH#"$`*FAFK#"#mF,FN#"#fF9FQ#F^sF]oFT#!#;F,FW#"
$J(FAFZ#"$"=F'Fgn#"#PF9Fjn#!$x#F'F^o#"$z$FAFaoFir6",
I3C_satellite_triangw,6#>%)symbolicGF(60%&_nameG%&_sizeG%#_AG%"iG%#C1G%#C2G%#C3
G%#mmG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FbtC->6$8$8%6$7%%$|\x|\s1G%$|\x|\s2
G%#c3G7#-%"$G6$7$"#?F(F2@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F\v6#8'Fbt/Fhw;F(-%
%nopsG6#F[v>F]w7#-F`w6$-I'MatrixG6$%*protectedG%(_syslibG6$Feww,6$FKF6Fbt6$%)op
eratorG%&arrowGFbt-&T'6#T%6#,&FjvF(*&,&9%F(!""F(F(&&T#F`y6#F(F(F(FbtFbt6(FjtF\v
F\uFhwFitF[v6#F.6$7'Q!FbtFgyF]t"#s"#O7'F`zFgyF]t"#VFbzFiw>6%8(8)8*6%-%(convertG
6$&F]wF[zI'VectorG6$FexFfx-F\[l6$&F]w6#F.F_[l-F\[l6$&F]w6#F2F_[l>8+7%76F[wF[wF[
wF[wF[wF[wF[wF[wF[wF[wF(F(F(F(F(F(F.F.F.F276F[wF[wF[wF[wF(F(F(F.F.F2F[wF[wF[wF(
F(F.F[wF[wF(F[w76F[wF(F.F2F[wF(F.F[wF(F[wF[wF(F.F[wF(F[wF[wF(F[wF[w>8,7%-%$addG
6#-&%"|irG6#%"*G6%-Ff\l6%-Ff\l6%Fgz%#~$G-&Fg\l6#%"^G6%FKF_]l&Fj[l6$F(;FbtFbtF_]
l-Fa]l6%F6F_]l&Fj[l6$F.Fg]lF_]l-Fa]l6%F)F_]l&Fj[l6$F2Fg]l-Fc\l6#-Ff\l6%-Ff\l6%-
Ff\l6%FhzF_]lF`]lF_]lFh]lF_]lF\^l-Fc\l6#-Ff\l6%-Ff\l6%-Ff\l6%FizF_]lF`]lF_]lFh]
lF_]lF\^l>8--%$mapG6$%'expandGF`\l@$FivOFa_l>8.-%&minusG6$-%'indetsG6#Fa_l-F^`l
6#F]w>6$8/80-%,poly2matrixG6$Fa_lFi_l>81-%$srtG6$Fe`l-%%tdegG6#&Fi_lFbt6%7#-%/p
ermuteColumnsG6%Fd`lFe`lFj`lF[vF\vFbtFbtFbt6#F[w617'F`zFgy"#;""'Fbz7'F`zFgyF2"#
_Fdz7'F`zFgyF2""*"#X7'F`zFgy""("#bFdz7'F`zFgyFbbl"#$*Fdz7'F`zFgyF2"#')Fdz7'F`zF
gyF2"#qFdz7'F`zFgyF2"$`"Fdz7'F`zFgyF2"#CFdz7'F`zFgyF2"#RF`bl7'F`zFgy"#A"#JF]bl7
'F`zFgyF2"#QFdz7'F`zFgyF2FbzFdz7'F`zFgyF2FbclFdz7'F`zFgyF2"#ZFbclFbt
