M7R0
I3F_satellite_triang7%,J#!"("#]"""%"zG#"$"R"$+&*$F)""##!""""%*$F)""$#"$8*"%+5%"
yG#"#")"$]#*&F7F(F)F(#!$*>"$+#*&F7F(F)F.#!#BF,*$F7F.#!$,(F6*&F7F.F)F(#!$,*F6*$F
7F3#"$t&F6%"xG#!$,#F:*&FKF(F)F(#"$`"F,*&FKF(F)F.#F3"")*&FKF(F7F(#!$B""$D"*(FKF(
F7F(F)F(#!$d#F6*&F7F.FKF(#"$">F:*$FKF.#"$"))F6*&FKF.F)F(#!$>"F,*&F7F(FKF.#"#PF>
*$FKF3#"$(HF6,J#"$.#F6F(F)#!$*oF6F-#"#(*F,F2#"$4$F,F7#""'FWF;#!$*RF6F?#"$d"F:FB
#"$^)F6FE#!$J"F:FH#"$@%F6FK#"#tF6FN#!$6$F,FQ#"#**F,FT#!$$**F6FX#!$R'F6Fen#"$(>F
6Fhn#!#hF6F[o#!#wFWF^o#"$<#F:Fao#"#@"$+",J#"$z'F6F(F)#!#8FWF-#!$Z&F6F2#F("#5F7#
"$H"F>F;#"#JF,F?#"$F'F6FB#!$4#F,FE#!#6"#?FH#"$T(F6FK#"$L"F:FN#!$"QF,FQ#"#RF]rFT
#!#>FasFX#"$Z"F:Fen#"$>%F6Fhn#F\rF,F[o#"#ZF]rF^o#"$f*F6Fao#FfpF>6",
I3C_satellite_triangw,6#>%)symbolicGF(60%&_nameG%&_sizeG%#_AG%"iG%#C1G%#C2G%#C3
G%#mmG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FftC->6$8$8%6$7%%$|\x|\s1G%$|\x|\s2
G%#c3G7#-%"$G6$7$FasF(F3@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F`v6#8'Fft/F[x;F(-%
%nopsG6#F_v>F`w7#-Fcw6$-I'MatrixG6$%*protectedG%(_syslibG6$Fhww,6$FKF7Fft6$%)op
eratorG%&arrowGFft-&T'6#T%6#,&F]wF(*&,&9%F(F0F(F(&&T#Fcy6#F(F(F(FftFft6(F^uF`vF
`uF[xF]uF_v6#F.6$7'Q!FftF0F`o"#s"#O7'FbzF0F`o"#VFdzF\x>6%8(8)8*6%-%(convertG6$&
F`wF]zI'VectorG6$FhxFix-F^[l6$&F`w6#F.Fa[l-F^[l6$&F`w6#F3Fa[l>8+7%76F^wF^wF^wF^
wF^wF^wF^wF^wF^wF^wF(F(F(F(F(F(F.F.F.F376F^wF^wF^wF^wF(F(F(F.F.F3F^wF^wF^wF(F(F
.F^wF^wF(F^w76F^wF(F.F3F^wF(F.F^wF(F^wF^wF(F.F^wF(F^wF^wF(F^wF^w>8,7%-%$addG6#-
&%"|irG6#%"*G6%-Fh\l6%-Fh\l6%Fiz%#~$G-&Fi\l6#%"^G6%FKFa]l&F\\l6$F(;FftFftFa]l-F
c]l6%F7Fa]l&F\\l6$F.Fi]lFa]l-Fc]l6%F)Fa]l&F\\l6$F3Fi]l-Fe\l6#-Fh\l6%-Fh\l6%-Fh
\l6%FjzFa]lFb]lFa]lFj]lFa]lF^^l-Fe\l6#-Fh\l6%-Fh\l6%-Fh\l6%F[[lFa]lFb]lFa]lFj]l
Fa]lF^^l>8--%$mapG6$%'expandGFb\l@$F\wOFc_l>8.-%&minusG6$-%'indetsG6#Fc_l-F``l6
#F`w>6$8/80-%,poly2matrixG6$Fc_lF[`l>81-%$srtG6$Fg`l-%%tdegG6#&F[`lFft6&7#-%/pe
rmuteColumnsG6%Ff`lFg`lF\alF\alF_vF`vFftFftFft6#F^w617'FbzF0"#;F^pFdz7'FbzF0F3"
#_Ffz7'FbzF0F3""*"#X7'FbzF0""("#bFfz7'FbzF0Fcbl"#$*Ffz7'FbzF0F3"#')Ffz7'FbzF0F3
"#qFfz7'FbzF0F3FPFfz7'FbzF0F3"#CFfz7'FbzF0F3FisFabl7'FbzF0"#AFjrF^bl7'FbzF0F3"#
QFfz7'FbzF0F3FdzFfz7'FbzF0F3FjrFfz7'FbzF0F3"#^FjrFft
