M7R0
I,F_stitching7$,B#!$4#"$+&"""*&%"xG""'%"yG""$#"#**F'*&F*""&F,F-#!$$**"%+5*&F*""
%F,F-#!$R'F4*&F*F6F,""##"$(>F4*&F*F-F,F-#!#hF4*&F,F:F*F-#!#w"$D"*&F*F:F,F-#"$<#
"$]#*&F*F:F,F:#"#@"$+"*&F*F:F,F(#"$z'F4*&F*F(F,F-#!#8FC*&F*F(F,F:#!$Z&F4*&F*F(F
,F(#F("#5*$F,F-#"$H""$+#*$F,F:#"#JF'F,#"$F'F4,B#"#tFKF(F)#!#6"#?F0#"$T(F4F5#"$L
"FGF9#!$"QF'F=#"#RFKF@#!#>F`oFD#"$Z"FGFH#"$>%F4FL#FJF'FO#"#ZFKFR#"$f*F4FU#!$J"F
enFX#!$z"F'Ffn#!#BFCF,#F(F16",
I,C_stitchingw,6#>%)symbolicGF(6/%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G
%#_VG%"iG%#C1G%#C2G%#mmG%$eqsG6"F[qC->6$8$8%6$7$%#c1G%#c2G7$7$"#;F(Fjr@%/9$F(>8
&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fdr6#8,w,6$F*F,F[q6$%)
operatorG%&arrowGF[q-&T'6#T%6#,&F^sF(*&,&9%F(!""F(F(&&T#Fit6#F(F(F(F[qF[q6(FcqF
drFjqF`tFbqFcr6#F:6$7'Q!F[qF`uFho"#u"#O7'FiuF`uFho"#XF[v/F`t;F(-%%nopsG6#Fcr>F`
s7#-Fcs6$-%'rndMatG6#F[tF^v>6$8-8.6$-%(convertG6$&F`sFduI'VectorG6$FhsFis-F`w6$
&F`s6#F:Fcw>8/)-I$<|gr>GFis6$-I$<,>GFis62F+F1F6F6F-F-F:F:F:F(F(F(""!FbxFbxFbx-F
`x62F-F-F-F:F-F:F-F:F(F-F:F(F-F:F(Fbx%#%TG>807$-%$addG6#-I".G6$FhsFis6$-&%"|irG
6#%"*G6%-&Fby6#%"^G6%F*%#~$G&FjwFduF[z-Fgy6%F,F[z&FjwFhwF\w-Fjx6#-F]y6$F`yF]w>8
'-%$mapG6$%'expandGFgx@$0F^sF(OFez>8(-%&minusG6$-%'indetsG6#Fez-Fc[l6#F`s>6$8)8
*-%,poly2matrixG6$FezF^[l>8+-%$srtG6$Fj[l-%%tdegG6#-F\t6#F^[l6%7$%#cfG-%/permut
eColumnsG6%Fi[lFj[lF_\lFcrFdrF[qF[qF[q6#Fbx617'FiuF`uF[sF+F[v7'FiuF`uF-Fap"#V7'
FiuF`uF-""*F]v7'FiuF`u""("#&*Fb]l7'FiuF`uFf]l"#dFb]l7'FiuF`uF-"#eFb]l7'FiuF`uF-
"$6"Fb]l7'FiuF`uF-"#pFb]l7'FiuF`uF-"#CFb]l7'FiuF`uF-"#SF]v7'FiuF`u"#B"#K"#_7'Fi
uF`uF-"#QFb]l7'FiuF`uF-F[vFb]l7'FiuF`uF-"#LFb]l7'FiuF`uF-"#`FhnF[q
