M7R0
I,F_stitching7$,B#"$">"$]#"""*&%"xG""'%"yG""$#!"("#]*&F*""&F,F-#"$"R"$+&*&F*""%
F,F-#!""F7*&F*F7F,""##"$8*"%+5*&F*F-F,F-#"#")F'*&F,F;F*F-#!$*>"$+#*&F*F;F,F-#!#
BF5*&F*F;F,F;#!$,(F>*&F*F;F,F(#!$,*F>*&F*F(F,F-#"$t&F>*&F*F(F,F;#!$,#F'*&F*F(F,
F(#"$`"F5*$F,F-#F-"")*$F,F;#!$B""$D"F,#!$d#F>,B#!$6$F5F(F)#"$"))F>F1#!$>"F5F6#"
#PFEF:#"$(HF>F?#"$.#F>FB#!$*oF>FF#"#(*F5FI#"$4$F5FL#F+FhnFO#!$*RF>FR#"$d"F'FU#"
$^)F>FX#!$J"F'Fen#"$@%F>F,#"#tF>6",
I,C_stitchingw,6#>%)symbolicGF(6/%&_nameG%&_sizeG%#_AG%"iG%#C1G%#C2G%#mmG%$eqsG
%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F[qC->6$8$8%6$7$%#c1G%#c2G7#-%"$G6$7$"#;F(F;@%/
9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fdr6#8'F[q/F_t;F(-%%nopsG6#Fcr>Fds7#-Fgs6$-I'M
atrixG6$%*protectedG%(_syslibG6$F\tw,6$F*F,F[q6$%)operatorG%&arrowGF[q-&T'6#T%6
#,&FasF(*&,&9%F(F9F(F(&&T#Fgu6#F(F(F(F[qF[q6(FcqFdrFeqF_tFbqFcr6#F;6$7'Q!F[qF9F
co"#s"#O7'FfvF9Fco"#VFhvF`t>6$8(8)6$-%(convertG6$&FdsFavI'VectorG6$F\uF]u-Faw6$
&Fds6#F;Fdw>8*)-I$<|gr>GF]u6$-I$<,>GF]u62F+F2F7F7F-F-F;F;F;F(F(F(FbsFbsFbsFbs-F
ax62F-F-F-F;F-F;F-F;F(F-F;F(F-F;F(Fbs%#%TG>8+7$-%$addG6#-I".G6$F\uF]u6$-&%"|irG
6#%"*G6%-&Fby6#%"^G6%F*%#~$G&F[xFavF[z-Fgy6%F,F[z&F[xFiwF]w-Fjx6#-F]y6$F`yF^w>8
,-%$mapG6$%'expandGFgx@$F`sOFez>8--%&minusG6$-%'indetsG6#Fez-Fb[l6#Fds>6$8.8/-%
,poly2matrixG6$FezF][l>80-%$srtG6$Fi[l-%%tdegG6#&F][lF[q6%7#-%/permuteColumnsG6
%Fh[lFi[lF^\lFcrFdrF[qF[qF[q6#Fbs617'FfvF9F^sF+Fhv7'FfvF9F-FjvFjv7'FfvF9F-""*"#
X7'FfvF9""("#bFjv7'FfvF9Fc]l"#$*Fjv7'FfvF9F-"#eFjv7'FfvF9F-"$4"Fjv7'FfvF9F-"#pF
jv7'FfvF9F-"#CFjv7'FfvF9F-"#RFa]l7'FfvF9"#A"#J"#_7'FfvF9F-"#QFjv7'FfvF9F-FhvFjv
7'FfvF9F-Fc^lFjv7'FfvF9F-"#ZFc^lF[q
