M7R0
I)F_toa_557(,\r%"vG#"-@a;jh9"-+++++]%"xG#!+.Tcup"-+++++5%"uG#"-Vs)yV-%F(%"yG#!,
r!yCe8"-++++]7%"wG#"-ZR&Rf)GF(#!-BbgNB6"-+++++D"""*(F-F:F%F:F4F:#"-hQT;$["F(*(F
-F:F%F:F)F:#!.j]:'pd8".++++++"*(F-F:F%F:F0F:#!-(Q95<K#F,*(F-F:F4F:F)F:#".^`8BD
\%FA*(F-F:F4F:F0F:#!+Hx?MD"*+Dcw**(F-F:F)F:F0F:#!-$ze6z.)F9*(F%F:F4F:F)F:#!,xQ9
v7*",++++D'*(F%F:F4F:F0F:#"-n(e#z%y"F9*(F%F:F)F:F0F:#"-<hxi5PF(*(F4F:F)F:F0F:#!
-\!Qx(49",+++++&*$F-""##!.BMK7c%=FA*&F-F:F%F:#"-BQca"\#F9*&F-F:F4F:#!-**ehH`6FR
*&F-F:F)F:#!-Hl:52<"-+++++?*&F-F:F0F:#"-4*[#QmJF,*$F%Fhn#!,B<^*y>F3*&F%F:F4F:#!
-,oU$f!HF(*&F%F:F)F:#!-4$33Vu#Fdo*&F%F:F0F:#!-hA!RXG#F(*$F4Fhn#!-fzu.$p#FA*&F4F
:F)F:#".R)z>RD6FA*&F4F:F0F:#"-6q)R#p#*F(*$F)Fhn#"-Tmjq)="Ffn*&F)F:F0F:#!-$34(*G
<"F(*$F0Fhn#!."\Qb,q?FA*&F-FhnF%F:#"-4#[==(eF9*&F-FhnF4F:#!,")fc=.$FR*&F-FhnF)F
:#"-t(H$y<bFdo*&F-FhnF0F:#"-(R)G3YVF3*&F-F:F%Fhn#!,r$>*=!R",+++++%*&F-F:F4Fhn#"
-z3e*f\)F(*&F-F:F)Fhn#!-*4d7<3%Fdo*&F-F:F0Fhn#!,ju!Q:T",++++]#*&F%FhnF4F:#"-VQY
[&)QFA*&F%FhnF)F:#"-dQ?l6LF9*&F%FhnF0F:#!,,Y[BO#F9*&F%F:F4Fhn#!-xa,KBPFA*&F%F:F
)Fhn#!,V0@D*yFdo*&F%F:F0Fhn#"-H%>9oF(FA*&F4FhnF)F:#"-@Q*['RGF9*&F4FhnF0F:#!-^6O
,GuF9*&F4F:F)Fhn#!.fG)e=CAFA*&F4F:F0Fhn#".r-CogZ#FA*&F)FhnF0F:#"."*H!fm\9F(*&F)
F:F0Fhn#"-nM$*\%=*FA*$F-""$#!.Fz<4&e@FA*$F%Feu#",d:$f%y)FA*$F4Feu#"-x6I")onFA*$
F)Feu#!.Z*\D!yG"FA*$F0Feu#",FUCGt$F,,\rF%#"-(*=e)QX$FAF)#"-n7Ak&="FdoF-#".HSw?$
Q_FAF0#!.dW)y;i5F(F4#"."zbil&\%FAF;#"-FN59J6F,F>#!-`<X$\9$FdoFB#!-2'fa'f7",+++]
7$FE#".f%)*\M>EFAFH#!.4GlaZV"F(FL#",tej)*=#F(FO#!,2/H&4xFfnFS#"-$fuU%*Q"F(FV#"-
psUgoUF(FY#",L7DQ]"F9#!,<:LW&[F_sF:Fgn#!-4i8YTxF(F[o#!-FX*Q&GYF(F^o#!.J+x%)=3"F
9Fao#!-jR'[-P&F(Feo#"-By">%*p)F(Fho#!,T5/@0%F,F[p#!,z;%H?vFewF^p#"+")Qh!R#FewFa
p#!-$3i+6^$F9Fdp#!.6e0j2,"F(Fgp#"-pazs!R"FRFjp#".f[9)Ru9F(F]q#",>%*z(=&*FfnF`q#
!+2&=Wl""++++DJFcq#!,RnZNg'F,Ffq#"-2T>PkCFRFiq#!-(\)R!pI%F(F\r#".HIz`pj"FAF_r#"
.nMMiPA$F(Fbr#!.xpP"Go9FAFfr#"-89ow(*=FfnFir#"-8IEAQEFAF\s#!,@I)obH"++++]iF`s#"
-p>)pna*FAFcs#",xCwj>%FRFfs#"-"zW8A]"F9Fis#!,>+#zRZFdoF\t#!-$4o*=jqFAF_t#".8^xB
]t"FAFbt#!,([KGuUF3Fet#!.Vxb5oD"F9Fht#!.nP2pd^#FAF[u#".$Q8Ok"3#FAF^u#",())eVULF
3Fau#"-.<BgGUFAFdu#!.zB8cL"QFAFhu#"-F[,L;LFAF[v#".\-%3fx;FAF^v#!-2!\fp*>FdoFav#
"-Bmp2S%)F(,\rF%#!+xc!>?""+++++!)F)#!-2yi!48$FdoF-#!.(pUe)Hx"FAF0#"-4/g8&*=F(F4
#!-R2!)*fw%FdoF;#!,"4jaeXF9F>#!-2(4>Q;"FAFB#".dLMpUB"F(FE#",jFr_s&FdoFH#"-RrNJ@
HF9FL#",.`f]?&F3FO#"-z6+J*R"F(FS#!-Z<[!)3BF(FV#!+HMW,iFfnFY#!,*QuRH8Few#",RR]qT
$FewF:Fgn#!->>HVwQF(F[o#".PWz"pL5FAF^o#!,L`q)p`FdoFao#",$*f8Ad$FRFeo#"-,6oOr\F(
Fho#!,^yI8Z*FAF[p#"-8cK>:EF3F^p#"-j+fLM&*FAFap#!,Va'H%H"F(Fdp#",H8*4'y$FRFgp#!-
BmMg%R%FAFjp#"-BsjR_;F9F]q#"+\l6SI",+++++#F`q#","[tyi$)F(Fcq#",,D6%*R#FAFfq#!-n
n&>KF#F3Fiq#"+P3@`oFfnF\r#!-4tc1y@FAF_r#!-p4]"*zyF9Fbr#"-t&GB6U)FAFfr#!-dm@U=#)
F(Fir#!,x*z,RKFdoF\s#"-P5k%QR"FRF`s#!-TZ<p!y&FAFcs#!,FB*\z]F(Ffs#!+@lk)Q""+++++
DFis#",2*eCh<FAF\t#"-Tvf2\>FAF_t#!..21z*\5FAFbt#"-R:EIMAF9Fet#"-jQUTF!*F(Fht#"-
**4bSwSFAF[u#!-H@*GG`*FAF^u#!-B.)>!*z"F9Fau#!-\vw&>;%FAFdu#".**\?$=H;FAFhu#!-x%
e$G(3#FAF[v#!-4%=F^L(FAF^v#!-<wjS#H"FAFav#!,*)3!RbkF,,\rF%#"-x"p`<A#F(F)#",R_]&
yfF,F-#!-,jg`3RF(F0#",@`8BN$FewF4#"-6k,J!R"F(F;#!,*[+Ji@FfnF>#!,xCf04#F,FB#!-Z+
M6'Q&F9FE#".HD9P2`"F(FH#!,4sq5A$",+++Dc"FL#!-T)H0%>gF3FO#!+(GJ_5*",++++D"FS#"-H
er+f9F3FV#"-R;8'=+"F9FY#!-Ht')H!y(F9Fgn#!+V<IcB"+++]i:F[o#"-\Byd!y(F(F^o#!-HQfA
t>F(Fao#"+\/Z%Q&FaflFeo#"-ZGTOuxF9Fho#!,f1GQN&F(F[p#!-8.`*3(>F9F^p#!.H5N'*y\"F(
Fap#"*2cCt%"++]7`>Fdp#!+"GO]T&FfnFgp#"-"*)yQTB&F(Fjp#"+rbHTtFaflF]q#",hL6>K#F_s
F`q#!,L,)3fUF3Fcq#!-V2m?UDF,Ffq#"-,GFEAQF9Fiq#!+Fk'zN&F9F\r#".pIp>!47F(F_r#"-<L
FFHbF9Fbr#!-<PR'RY%F(Ffr#",>@TrD$FfnFir#!.<@SK-F"F(F\s#!+tQ7\&)F_sF`s#"-4Nw8.;F
(Fcs#"-rV\BeHF9Ffs#!+.ox`NF9Fis#!,HQ]3b#F,F\t#!,8f/wW$F(F_t#"-$Hs.Im#F(Fbt#",nN
q%e5FaflFet#!-.!GB6l"F3Fht#!-Fq(4u=&F(F[u#"..Pj9&p6F(F^u#".LJ!40[5F9Fau#"-.9#[&
\oF(#!,()G^Pq$FfnF:Fdu#!-p-UUYgF(Fhu#",2NlU+$F(F[v#"-H/T!)z5F(F^v#!,fpe@z&F,Fav
#!,P>4mO)F9,hzF%#"-T&4M$*3"FdoF)#".Z74`!*)RFAF-#!-^&Gx/l"FdoF0#!,(fA$f#HFdalF4#
".jybsaN#FA*&F-FeuF%F:#"..u(GQTGFA*&F-FhnF%Fhn#!-`^V@`sF(*&F-FeuF4F:#"-xij\[LFd
o*&F-FhnF4Fhn#".d))eXP."F(*&F-FeuF)F:#".L['ei)H#FA*&F-FhnF)Fhn#!.p'*f#pH8F(*&F-
FeuF0F:#"-R)39'\LF,*&F-FhnF0Fhn#!-")=.TXxF9*&F-F:F%Feu#"-6S?/vKFA*&F-F:F4Feu#!-
f&yF#4bF(*&F-F:F)Feu#!-h2PR!H#Fdo*&F-F:F0Feu#",r"H%>"GF_s*&F%FeuF4F:#!*2Gs,$"*+
+++)*&F%FhnF4Fhn#!-8&)=%G["F9*&F%FeuF)F:#!,6u(RWIF3*&F%FhnF)Fhn#!,.,!>SjF(*&F%F
euF0F:#!+@.(p&GFfn*&F%FhnF0Fhn#!,h$>p#>%F9*&F%F:F4Feu#!**["z:&F_cl*&F%F:F)Feu#"
-nla3g?FA*&F%F:F0Feu#!,ty*Gz\FR*&F4FeuF)F:#!-nm%\(ecFA*&F4FhnF)Fhn#",r%pj\CFffl
*&F4FeuF0F:#".dJ-#)eN"F(*&F4FhnF0Fhn#!-([&oLkYF9*&F4F:F)Feu#"-HS+;C?Fdo*&F4F:F0
Feu#!,")3cJ"QF_s*&F)FeuF0F:#!,LCFT\(F,*&F)FhnF0Fhn#!-(p)>vTCFR*&F)F:F0Feu#"+@J$
)4[F_s**F-F:F%F:F4F:F)F:#!-T@\V`9F,**F-F:F%F:F4F:F0F:#".4?S$\$*>F(**F-F:F%F:F)F
:F0F:#"-`c_&Gh(F(**F-F:F4F:F)F:F0F:#"-L\Arf6Ffn**F%F:F4F:F)F:F0F:#!-([p&pVGF(F;
#!,tANVN"FdalF>#"-jO^1K#)FAFB#!+$=S=^)",+++++"FE#".B#)3p-e$FAFH#!+p@*ee#F_clFL#
!,Jbya%fFe[lFO#"-8E3L`jF3FS#!-n<#[(G5F3FV#"-j4>sLwF9FY#!.@rH%*oX"F(Fgn#".^:2DrX
"F(F[o#!+x5,*>#"+++++?F^o#!-j%y)o-8F(Fao#!-ZR17elF,Feo#",>SNYT&FdalFho#!,Vp8dq$
F9F[p#!-()\\-PCF3F^p#!-f\kSOZF(Fap#",.q*o8aF3Fdp#!.\R%Hw)R$FAFgp#!.r^x))o."F3Fj
p#".PLS#3(o"F(F]q#!.6vwij)[FAF`q#".FerwOQ"F9Fcq#!-"Gc4eg&F9Ffq#!-8&*p1_'*FAFiq#
!-h7yfF&)FAF\r#",RTU!ytFewF_r#"+F$G5k*F9Fbr#",t!\YIbF,Ffr#",z>h4h$F,Fir#"-tH2?4
=FewF\s#"-pU^13CF9F`s#"-Zk$3,6#F9Fcs#!-$Qnhb6"FdoFfs#"-*yExI%>F(Fis#",*ei9s^Fda
lF\t#".n&)4+!4;FAF_t#!.Fnc)z<;FAFbt#!+"o7,M#"+++]7yFet#!,BlS:;)F9Fht#"-Vu[&4c'F
AF[u#"..GS+9&>FAF^u#!-hPNcBAFRFau#"-f>Y,&o*Fdo*$F-""%#!,xoPBe(Fer*$F%Fdim#!,rh6
dQ"Fdo*$F4Fdim#!,rnf9m*F3*$F)Fdim#!,>ukQ9"FA*$F0Fdim#"+"*=/5MFR#!,*>TuXBFRF:Fdu
#!-@2:aXLF(Fhu#",(H3t_5F3F[v#",`QjxD#FewF^v#"-r,.0'Q&F(Fav#!,xQGPh"F,*(F-FhnF%F
:F4F:#!-Rje0FuF(*(F-F:F%FhnF4F:#",6[YtK%Fer*(F-F:F%F:F4Fhn#!-pH(*[CJF9*(F-FhnF%
F:F)F:#!.R,`>$[9F(*(F-F:F%FhnF)F:#".LjP(yg>FA*(F-F:F%F:F)Fhn#!-nCXT$)pFA*(F-Fhn
F%F:F0F:#!-J"\K;F%F3*(F-F:F%FhnF0F:#"-z0;'*4YF(*(F-F:F%F:F0Fhn#"-<?*4rZ'F9*(F-F
hnF4F:F)F:#"-Jy.`'\%F(*(F-F:F4FhnF)F:#!.P$4lok8F(*(F-F:F4F:F)Fhn#!.4sDzbZ"FA*(F
-FhnF4F:F0F:#!.*[Cy%[W"F9*(F-F:F4FhnF0F:#!-H'Q'3NCF(*(F-F:F4F:F0Fhn#"-(G&)f(GEF
R*(F-FhnF)F:F0F:#!,(H*\0K)Ffn*(F-F:F)FhnF0F:#".PSndB^"F9*(F-F:F)F:F0Fhn#"-">d$e
1;F3*(F%FhnF4F:F)F:#!-2*=S*obF(*(F%F:F4FhnF)F:#"-L)o]j"yFA*(F%F:F4F:F)Fhn#",2>1
XU"Fdal*(F%FhnF4F:F0F:#!,\]S&*G"F,*(F%F:F4FhnF0F:#",BthnA$FR*(F%F:F4F:F0Fhn#!-T
%ez)GCF3*(F%FhnF)F:F0F:#!-4k()*[2'F(*(F%F:F)FhnF0F:#!,^&QK"z"F,*(F%F:F)F:F0Fhn#
"+(*[\Q7F_s*(F4FhnF)F:F0F:#".z1<9T1"F(*(F4F:F)FhnF0F:#!-p-vTR?F,*(F4F:F)F:F0Fhn
#!,@*=X*f"Ffn,^rF%#!*zn&f9"+++++5F)#!)t\77"*++++#F-#!*z!oD*)F\anF0#!*zepC""*+++
+&F4#!+x-XT6F\an%"zG!""F;#"$6'"(++D"F>#!*8#f'>#F_anFB#"*Vv=;%FdanFE#"+`OqWJF\an
FH#!)><DE")+++]FL#!*RI&*f$"*+++D"FO#!*T'R[6FdanFS#!)6L*H&FdanFV#"*@I#e5FgbnFY#!
)RET"*FdbnFgn#!)f`yc"*++++"F[o#"*n`UZ"F_anF^o#!*2-9j&F\anFao#!).Z^f")++DJFeo#"+
B=)4+"FdanFho#"(JL^"")+++SF[p#")h7MYFdbnF^p#"(p&>QF\anFap#"("QNcFdanFdp#"'jrg")
+++5Fgp#!+L&*o5:F\anFjp#"*,nYR%"*+++]#F]q#")H"Qr&FbcnF`q#"*H2=z'FdanFcq#!*(Rg&4
*F\anFfq#!)2aL]F\enFiq#!)tb%y$FgbnF\r#"+deU#G#F\anF_r#!)Z5*e&")++]iFbr#"*$)R&>7
F\anFfr#!**pot;FdanFir#!*fSq6(F\anF\s#"*V*G)p"FgbnF`s#!*f*RZ9F\anFcs#"*$ek'3$Fd
anFfs#!*x7NB"F\enFis#!)jrX[F\anF\t#")"z`7(F\anF_t#!*d[UG(F\anFbt#"*fTt"HF\enFet
#!)*)R)="FbcnFht#!*Z"*o))*F\anF[u#"*H<yV%F\anF^u#")6()=>FicnFau#"*<NTP)F\anFdu#
"("3d^F\anFhu#!)$Gj%))F\anF[v#!)RA'>#F_anF^v#!*>*)Rh"F_anFav#!*^5#oFFdan#")r)H$
GFdbnF:6",
I)C_toa_55w,6#>%)symbolicGF:66%&_nameG%&_sizeG%#_AG%"iG%#M1G%#vvG%"HG%"bG%"kG%"
CG%%adjHG%%detHG%"SG%#ddG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FhhnC5>6$8$8%6$7
#%"MG7#7$"#rF:@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fhjn6#8'Fhhn/F_\o;F:-%%nopsG6
#Fgjn>Fd[o7#-Fg[o6$-I'MatrixG6$%*protectedG%(_syslibG6$F\\ow,6$F)F0Fhhn6$%)oper
atorG%&arrowGFhhn-&T'6#T%6#,&Fa[oF:*&,&9%F:FhanF:F:&&T#Fg]o6#F:F:F:FhhnFhhn6(F`
inFhjnFbinF_\oF_inFgjn6#Fhn6$7'Q!FhhnFhan"#P"#s"#O7'Ff^oFhanFg^o"#VFi^oF`\o>8(-
%(convertG6$&Fd[oFa^oI'VectorG6$F\]oF]]o>8)7(F:F-F%F4F)F0>6%8*8+8,6%Fb[oFb[oFb[
o?(F_\oF:F:""'%%trueGC&>8--I$<,>GF]]o6%-I$<|gr>GF]]o6%&F]_o6#,&F[`oF:F:F:&F]_o6
#,&F[`oF:FhnF:&F]_o6#,&F[`oF:FeuF:-Fg`o6%F\ao&F]_o6#,&F[`oF:FdimF:&F]_o6#,&F[`o
F:""&F:-Fg`o6%F_aoFgao&F]_o6#,&F[`oF:F^`oF:>Fi_o,&Fi_oF:*&&Fe_oF^\oF:Fb`oF:F:>F
j_o,&Fj_oF:*&&F]_o6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GF[`oF:FcboF:F:>F[`o,&F
[`oF:FecoF:>8.-%$adjG6#Fi_o>8/-&I.LinearAlgebraG6$F\]oF]]o6#%,DeterminantGF]do>
80&F]_o6#-Fjbo6%7#-Faco6#;F:"#7FfcoF[`o>Fgdo)-Fd`o6&-Fg`o6%&FgdoFa^o&Fgdo6#Fhn&
Fgdo6#Feu-Fg`o6%&Fgdo6#Fdim&Fgdo6#Fjao&Fgdo6#F^`o-Fg`o6%&Fgdo6#Fdco&Fgdo6#"")&F
gdo6#Feco-Fg`o6%&Fgdo6#"#5&Fgdo6#"#6&Fgdo6#F`eo%#%TG>81&F]_o6#-Fjbo6%7#-Faco6#;
"#8"#<FfcoF[`o>827$-Fg[o6$,&-I".G6$F\]oF]]o6$,&-F[io6$)&Fgdo6$;FhhnFhhnF_\oFggo
FjcoF:-F[io6$,$)Fj_oFggoFhnFjcoF:FbioF:*&&FigoF^\oF:F_doF:Fhan/F_\o;F:Fdim,&-F[
io6%FhioFjcoFj_oF:*&&FigoFafoF:F_doF:Fhan>Feho7$&FehoFhhn,&F_doF:FganFhan>83-%$
mapG6$%'expandGFeho@$F`[oOFgjo>84-%&minusG6$-%'indetsG6#Fgjo-Fd[p6#Fd[o>6$8586-
%,poly2matrixG6$FgjoF_[p>87-%$srtG6$F[\p-%%tdegG6#&F_[pFhhn6%7#-%/permuteColumn
sG6%Fj[pF[\pF`\pFgjnFhjnFhhnFhhnFhhn6#Fb[o6=7'Ff^oFhan"#;F^`oFi^o7'Ff^oFhanFeu"
#LF[_o7'Ff^oFhanFeuFeco"#X7'Ff^oFhanFdco"#bF[_o7'Ff^oFhanFdco"#$*F[_o7'Ff^oFhan
Feu"#IF[_o7'Ff^oFhanFeu"#EF[_o7'Ff^oFhanFeu"#@F[_o7'Ff^oFhanFeuFjfoFjfo7'Ff^oFh
anFdco"#')F[_o7'Ff^oFhanFdcoF^^pF[_o7'Ff^oFhanFdcoFi^oF[_o7'Ff^oFhanFdco"#:F[_o
7'Ff^oFhanFeuF`]pF[_o7'Ff^oFhanFeu"#RF[_o7'Ff^oFhanFeu"#BF[_o7'Ff^oFhanFeu"#wF[
_o7'Ff^oFhanFeu"#DF[_o7'Ff^oFhanFeuFh]pF[_o7'Ff^oFhanFeu"#CF[_oF`_p7'Ff^oFhanFe
uFh^pFd]p7'Ff^oFhan"#A"#J"#_7'Ff^oFhanFeu"#QF[_o7'Ff^oFhanFeuFi^oF[_o7'Ff^oFhan
FeuFe_pF[_o7'Ff^oFhanFeu"#ZFe_pFhhn
