M7R0
I/F_toa_55_w_sat7(,\r%"vG#"-@a;jh9"-+++++]%"xG#!+.Tcup"-+++++5%"uG#"-Vs)yV-%F(%
"yG#!,r!yCe8"-++++]7%"wG#"-ZR&Rf)GF(#!-BbgNB6"-+++++D"""*(F4F:F%F:F-F:#"-hQT;$[
"F(*(F)F:F%F:F-F:#!.j]:'pd8".++++++"*(F0F:F%F:F-F:#!-(Q95<K#F,*(F)F:F4F:F-F:#".
^`8BD\%FA*(F0F:F4F:F-F:#!+Hx?MD"*+Dcw**(F0F:F)F:F-F:#!-$ze6z.)F9*(F)F:F4F:F%F:#
!,xQ9v7*",++++D'*(F0F:F4F:F%F:#"-n(e#z%y"F9*(F0F:F)F:F%F:#"-<hxi5PF(*(F0F:F)F:F
4F:#!-\!Qx(49",+++++&*$F-""##!.BMK7c%=FA*&F-F:F%F:#"-BQca"\#F9*&F-F:F4F:#!-**eh
H`6FR*&F-F:F)F:#!-Hl:52<"-+++++?*&F-F:F0F:#"-4*[#QmJF,*$F%Fhn#!,B<^*y>F3*&F%F:F
4F:#!-,oU$f!HF(*&F%F:F)F:#!-4$33Vu#Fdo*&F%F:F0F:#!-hA!RXG#F(*$F4Fhn#!-fzu.$p#FA
*&F4F:F)F:#".R)z>RD6FA*&F4F:F0F:#"-6q)R#p#*F(*$F)Fhn#"-Tmjq)="Ffn*&F)F:F0F:#!-$
34(*G<"F(*$F0Fhn#!."\Qb,q?FA*&F%F:F-Fhn#"-4#[==(eF9*&F4F:F-Fhn#!,")fc=.$FR*&F)F
:F-Fhn#"-t(H$y<bFdo*&F0F:F-Fhn#"-(R)G3YVF3*&F%FhnF-F:#!,r$>*=!R",+++++%*&F4FhnF
-F:#"-z3e*f\)F(*&F)FhnF-F:#!-*4d7<3%Fdo*&F0FhnF-F:#!,ju!Q:T",++++]#*&F4F:F%Fhn#
"-VQY[&)QFA*&F)F:F%Fhn#"-dQ?l6LF9*&F0F:F%Fhn#!,,Y[BO#F9*&F4FhnF%F:#!-xa,KBPFA*&
F)FhnF%F:#!,V0@D*yFdo*&F0FhnF%F:#"-H%>9oF(FA*&F)F:F4Fhn#"-@Q*['RGF9*&F0F:F4Fhn#
!-^6O,GuF9*&F)FhnF4F:#!.fG)e=CAFA*&F0FhnF4F:#".r-CogZ#FA*&F0F:F)Fhn#"."*H!fm\9F
(*&F0FhnF)F:#"-nM$*\%=*FA*$F-""$#!.Fz<4&e@FA*$F%Feu#",d:$f%y)FA*$F4Feu#"-x6I")o
nFA*$F)Feu#!.Z*\D!yG"FA*$F0Feu#",FUCGt$F,,\rF%#"-(*=e)QX$FAF)#"-n7Ak&="FdoF-#".
HSw?$Q_FAF0#!.dW)y;i5F(F4#"."zbil&\%FAF;#"-FN59J6F,F>#!-`<X$\9$FdoFB#!-2'fa'f7"
,+++]7$FE#".f%)*\M>EFAFH#!.4GlaZV"F(FL#",tej)*=#F(FO#!,2/H&4xFfnFS#"-$fuU%*Q"F(
FV#"-psUgoUF(FY#",L7DQ]"F9#!,<:LW&[F_sF:Fgn#!-4i8YTxF(F[o#!-FX*Q&GYF(F^o#!.J+x%
)=3"F9Fao#!-jR'[-P&F(Feo#"-By">%*p)F(Fho#!,T5/@0%F,F[p#!,z;%H?vFewF^p#"+")Qh!R#
FewFap#!-$3i+6^$F9Fdp#!.6e0j2,"F(Fgp#"-pazs!R"FRFjp#".f[9)Ru9F(F]q#",>%*z(=&*Ff
nF`q#!+2&=Wl""++++DJFcq#!,RnZNg'F,Ffq#"-2T>PkCFRFiq#!-(\)R!pI%F(F\r#".HIz`pj"FA
F_r#".nMMiPA$F(Fbr#!.xpP"Go9FAFfr#"-89ow(*=FfnFir#"-8IEAQEFAF\s#!,@I)obH"++++]i
F`s#"-p>)pna*FAFcs#",xCwj>%FRFfs#"-"zW8A]"F9Fis#!,>+#zRZFdoF\t#!-$4o*=jqFAF_t#"
.8^xB]t"FAFbt#!,([KGuUF3Fet#!.Vxb5oD"F9Fht#!.nP2pd^#FAF[u#".$Q8Ok"3#FAF^u#",())
eVULF3Fau#"-.<BgGUFAFdu#!.zB8cL"QFAFhu#"-F[,L;LFAF[v#".\-%3fx;FAF^v#!-2!\fp*>Fd
oFav#"-Bmp2S%)F(,\rF%#!+xc!>?""+++++!)F)#!-2yi!48$FdoF-#!.(pUe)Hx"FAF0#"-4/g8&*
=F(F4#!-R2!)*fw%FdoF;#!,"4jaeXF9F>#!-2(4>Q;"FAFB#".dLMpUB"F(FE#",jFr_s&FdoFH#"-
RrNJ@HF9FL#",.`f]?&F3FO#"-z6+J*R"F(FS#!-Z<[!)3BF(FV#!+HMW,iFfnFY#!,*QuRH8Few#",
RR]qT$FewF:Fgn#!->>HVwQF(F[o#".PWz"pL5FAF^o#!,L`q)p`FdoFao#",$*f8Ad$FRFeo#"-,6o
Or\F(Fho#!,^yI8Z*FAF[p#"-8cK>:EF3F^p#"-j+fLM&*FAFap#!,Va'H%H"F(Fdp#",H8*4'y$FRF
gp#!-BmMg%R%FAFjp#"-BsjR_;F9F]q#"+\l6SI",+++++#F`q#","[tyi$)F(Fcq#",,D6%*R#FAFf
q#!-nn&>KF#F3Fiq#"+P3@`oFfnF\r#!-4tc1y@FAF_r#!-p4]"*zyF9Fbr#"-t&GB6U)FAFfr#!-dm
@U=#)F(Fir#!,x*z,RKFdoF\s#"-P5k%QR"FRF`s#!-TZ<p!y&FAFcs#!,FB*\z]F(Ffs#!+@lk)Q""
+++++DFis#",2*eCh<FAF\t#"-Tvf2\>FAF_t#!..21z*\5FAFbt#"-R:EIMAF9Fet#"-jQUTF!*F(F
ht#"-**4bSwSFAF[u#!-H@*GG`*FAF^u#!-B.)>!*z"F9Fau#!-\vw&>;%FAFdu#".**\?$=H;FAFhu
#!-x%e$G(3#FAF[v#!-4%=F^L(FAF^v#!-<wjS#H"FAFav#!,*)3!RbkF,,\rF%#"-x"p`<A#F(F)#"
,R_]&yfF,F-#!-,jg`3RF(F0#",@`8BN$FewF4#"-6k,J!R"F(F;#!,*[+Ji@FfnF>#!,xCf04#F,FB
#!-Z+M6'Q&F9FE#".HD9P2`"F(FH#!,4sq5A$",+++Dc"FL#!-T)H0%>gF3FO#!+(GJ_5*",++++D"F
S#"-Her+f9F3FV#"-R;8'=+"F9FY#!-Ht')H!y(F9Fgn#!+V<IcB"+++]i:F[o#"-\Byd!y(F(F^o#!
-HQfAt>F(Fao#"+\/Z%Q&FaflFeo#"-ZGTOuxF9Fho#!,f1GQN&F(F[p#!-8.`*3(>F9F^p#!.H5N'*
y\"F(Fap#"*2cCt%"++]7`>Fdp#!+"GO]T&FfnFgp#"-"*)yQTB&F(Fjp#"+rbHTtFaflF]q#",hL6>
K#F_sF`q#!,L,)3fUF3Fcq#!-V2m?UDF,Ffq#"-,GFEAQF9Fiq#!+Fk'zN&F9F\r#".pIp>!47F(F_r
#"-<LFFHbF9Fbr#!-<PR'RY%F(Ffr#",>@TrD$FfnFir#!.<@SK-F"F(F\s#!+tQ7\&)F_sF`s#"-4N
w8.;F(Fcs#"-rV\BeHF9Ffs#!+.ox`NF9Fis#!,HQ]3b#F,F\t#!,8f/wW$F(F_t#"-$Hs.Im#F(Fbt
#",nNq%e5FaflFet#!-.!GB6l"F3Fht#!-Fq(4u=&F(F[u#"..Pj9&p6F(F^u#".LJ!40[5F9Fau#"-
.9#[&\oF(#!,()G^Pq$FfnF:Fdu#!-p-UUYgF(Fhu#",2NlU+$F(F[v#"-H/T!)z5F(F^v#!,fpe@z&
F,Fav#!,P>4mO)F9,hzF%#"-T&4M$*3"FdoF)#".Z74`!*)RFAF-#!-^&Gx/l"FdoF0#!,(fA$f#HFd
alF4#".jybsaN#FA*&F-FeuF%F:#"..u(GQTGFA*&F-FhnF%Fhn#!-`^V@`sF(*&F-FeuF4F:#"-xij
\[LFdo*&F-FhnF4Fhn#".d))eXP."F(*&F-FeuF)F:#".L['ei)H#FA*&F-FhnF)Fhn#!.p'*f#pH8F
(*&F-FeuF0F:#"-R)39'\LF,*&F-FhnF0Fhn#!-")=.TXxF9*&F-F:F%Feu#"-6S?/vKFA*&F-F:F4F
eu#!-f&yF#4bF(*&F-F:F)Feu#!-h2PR!H#Fdo*&F-F:F0Feu#",r"H%>"GF_s*&F%FeuF4F:#!*2Gs
,$"*++++)*&F%FhnF4Fhn#!-8&)=%G["F9*&F%FeuF)F:#!,6u(RWIF3*&F%FhnF)Fhn#!,.,!>SjF(
*&F%FeuF0F:#!+@.(p&GFfn*&F%FhnF0Fhn#!,h$>p#>%F9*&F%F:F4Feu#!**["z:&F_cl*&F%F:F)
Feu#"-nla3g?FA*&F%F:F0Feu#!,ty*Gz\FR*&F4FeuF)F:#!-nm%\(ecFA*&F4FhnF)Fhn#",r%pj
\CFffl*&F4FeuF0F:#".dJ-#)eN"F(*&F4FhnF0Fhn#!-([&oLkYF9*&F4F:F)Feu#"-HS+;C?Fdo*&
F4F:F0Feu#!,")3cJ"QF_s*&F)FeuF0F:#!,LCFT\(F,*&F)FhnF0Fhn#!-(p)>vTCFR*&F)F:F0Feu
#"+@J$)4[F_s**F-F:F%F:F4F:F)F:#!-T@\V`9F,**F-F:F%F:F4F:F0F:#".4?S$\$*>F(**F-F:F
%F:F)F:F0F:#"-`c_&Gh(F(**F-F:F4F:F)F:F0F:#"-L\Arf6Ffn**F%F:F4F:F)F:F0F:#!-([p&p
VGF(F;#!,tANVN"FdalF>#"-jO^1K#)FAFB#!+$=S=^)",+++++"FE#".B#)3p-e$FAFH#!+p@*ee#F
_clFL#!,Jbya%fFe[lFO#"-8E3L`jF3FS#!-n<#[(G5F3FV#"-j4>sLwF9FY#!.@rH%*oX"F(Fgn#".
^:2DrX"F(F[o#!+x5,*>#"+++++?F^o#!-j%y)o-8F(Fao#!-ZR17elF,Feo#",>SNYT&FdalFho#!,
Vp8dq$F9F[p#!-()\\-PCF3F^p#!-f\kSOZF(Fap#",.q*o8aF3Fdp#!.\R%Hw)R$FAFgp#!.r^x))o
."F3Fjp#".PLS#3(o"F(F]q#!.6vwij)[FAF`q#".FerwOQ"F9Fcq#!-"Gc4eg&F9Ffq#!-8&*p1_'*
FAFiq#!-h7yfF&)FAF\r#",RTU!ytFewF_r#"+F$G5k*F9Fbr#",t!\YIbF,Ffr#",z>h4h$F,Fir#"
-tH2?4=FewF\s#"-pU^13CF9F`s#"-Zk$3,6#F9Fcs#!-$Qnhb6"FdoFfs#"-*yExI%>F(Fis#",*ei
9s^FdalF\t#".n&)4+!4;FAF_t#!.Fnc)z<;FAFbt#!+"o7,M#"+++]7yFet#!,BlS:;)F9Fht#"-Vu
[&4c'FAF[u#"..GS+9&>FAF^u#!-hPNcBAFRFau#"-f>Y,&o*Fdo*$F-""%#!,xoPBe(Fer*$F%Fdim
#!,rh6dQ"Fdo*$F4Fdim#!,rnf9m*F3*$F)Fdim#!,>ukQ9"FA*$F0Fdim#"+"*=/5MFR#!,*>TuXBF
RF:Fdu#!-@2:aXLF(Fhu#",(H3t_5F3F[v#",`QjxD#FewF^v#"-r,.0'Q&F(Fav#!,xQGPh"F,*(F-
FhnF%F:F4F:#!-Rje0FuF(*(F-F:F%FhnF4F:#",6[YtK%Fer*(F-F:F%F:F4Fhn#!-pH(*[CJF9*(F
-FhnF%F:F)F:#!.R,`>$[9F(*(F-F:F%FhnF)F:#".LjP(yg>FA*(F-F:F%F:F)Fhn#!-nCXT$)pFA*
(F-FhnF%F:F0F:#!-J"\K;F%F3*(F-F:F%FhnF0F:#"-z0;'*4YF(*(F-F:F%F:F0Fhn#"-<?*4rZ'F
9*(F-FhnF4F:F)F:#"-Jy.`'\%F(*(F-F:F4FhnF)F:#!.P$4lok8F(*(F-F:F4F:F)Fhn#!.4sDzbZ
"FA*(F-FhnF4F:F0F:#!.*[Cy%[W"F9*(F-F:F4FhnF0F:#!-H'Q'3NCF(*(F-F:F4F:F0Fhn#"-(G&
)f(GEFR*(F-FhnF)F:F0F:#!,(H*\0K)Ffn*(F-F:F)FhnF0F:#".PSndB^"F9*(F-F:F)F:F0Fhn#"
-">d$e1;F3*(F%FhnF4F:F)F:#!-2*=S*obF(*(F%F:F4FhnF)F:#"-L)o]j"yFA*(F%F:F4F:F)Fhn
#",2>1XU"Fdal*(F%FhnF4F:F0F:#!,\]S&*G"F,*(F%F:F4FhnF0F:#",BthnA$FR*(F%F:F4F:F0F
hn#!-T%ez)GCF3*(F%FhnF)F:F0F:#!-4k()*[2'F(*(F%F:F)FhnF0F:#!,^&QK"z"F,*(F%F:F)F:
F0Fhn#"+(*[\Q7F_s*(F4FhnF)F:F0F:#".z1<9T1"F(*(F4F:F)FhnF0F:#!-p-vTR?F,*(F4F:F)F
:F0Fhn#!,@*=X*f"Ffn,^r!""F:%"zG#")r)H$G")+++]**F[anF:F-F:F%F:F4F:#"$6'"(++D"**F
[anF:F-F:F%F:F)F:#!*8#f'>#"*++++#**F[anF:F-F:F%F:F0F:#"*Vv=;%"*++++&**F[anF:F-F
:F4F:F)F:#"+`OqWJ"+++++5**F[anF:F-F:F4F:F0F:#!)><DEF^an**F[anF:F-F:F)F:F0F:#!*R
I&*f$"*+++D"**F[anF:F%F:F4F:F)F:#!*T'R[6Fjan**F[anF:F%F:F4F:F0F:#!)6L*H&Fjan**F
[anF:F%F:F)F:F0F:#"*@I#e5Febn**F[anF:F4F:F)F:F0F:#!)RET"*F^an*&F[anF:F%F:#!*zn&
f9F^bn*&F[anF:F)F:#!)t\77Ffan*&F[anF:F-F:#!*z!oD*)F^bn*&F[anF:F0F:#!*zepC"Fjan*
&F[anF:F4F:#!+x-XT6F^bn*&F[anF:F-Fhn#!)f`yc"*++++"*&F[anF:F%Fhn#"(JL^"")+++S*&F
[anF:F4Fhn#"'jrg")+++5*&F[anF:F)Fhn#")H"Qr&Fddn*&F[anF:F0Fhn#!*(Rg&4*F^bn*&F[an
F:F-Feu#"("3d^F^bn*&F[anF:F%Feu#!)$Gj%))F^bn*&F[anF:F4Feu#!)RA'>#Ffan*&F[anF:F)
Feu#!*>*)Rh"Ffan*&F[anF:F0Feu#!*^5#oFFjan*(F[anF:F%F:F-F:#"*n`UZ"Ffan*(F[anF:F4
F:F-F:#!*2-9j&F^bn*(F[anF:F)F:F-F:#!).Z^f")++DJ*(F[anF:F-F:F0F:#"+B=)4+"Fjan*(F
[anF:F4F:F%F:#")h7MYF^an*(F[anF:F%F:F)F:#"(p&>QF^bn*(F[anF:F%F:F0F:#"("QNcFjan*
(F[anF:F4F:F)F:#!+L&*o5:F^bn*(F[anF:F4F:F0F:#"*,nYR%"*+++]#*(F[anF:F)F:F0F:#"*H
2=z'Fjan*(F[anF:F-FhnF%F:#!)2aL]F^hn*(F[anF:F-FhnF4F:#!)tb%y$Febn*(F[anF:F-FhnF
)F:#"+deU#G#F^bn*(F[anF:F-FhnF0F:#!)Z5*e&")++]i*(F[anF:F-F:F%Fhn#"*$)R&>7F^bn*(
F[anF:F-F:F4Fhn#!**pot;Fjan*(F[anF:F-F:F)Fhn#!*fSq6(F^bn*(F[anF:F-F:F0Fhn#"*V*G
)p"Febn*(F[anF:F%FhnF4F:#!*f*RZ9F^bn*(F[anF:F%FhnF)F:#"*$ek'3$Fjan*(F[anF:F%Fhn
F0F:#!*x7NB"F^hn*(F[anF:F%F:F4Fhn#!)jrX[F^bn*(F[anF:F%F:F)Fhn#")"z`7(F^bn*(F[an
F:F%F:F0Fhn#!*d[UG(F^bn*(F[anF:F4FhnF)F:#"*fTt"HF^hn*(F[anF:F4FhnF0F:#!)*)R)="F
ddn*(F[anF:F4F:F)Fhn#!*Z"*o))*F^bn*(F[anF:F4F:F0Fhn#"*H<yV%F^bn*(F[anF:F)FhnF0F
:#")6()=>F[gn*(F[anF:F)F:F0Fhn#"*<NTP)F^bn6",
I/C_toa_55_w_satw,6#>%)symbolicGF:66%&_nameG%&_sizeG%#_AG%"iG%#M1G%#vvG%"HG%"bG
%"kG%"CG%%adjHG%%detHG%"SG%#ddG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F_\oC5>6$8
$8%6$7#%"MG7#7$"#rF:@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F_^o6#8'F_\o/Ff_o;F:-%%
nopsG6#F^^o>F[_o7#-F^_o6$-I'MatrixG6$%*protectedG%(_syslibG6$Fc_ow,6$F)F0F_\o6$
%)operatorG%&arrowGF_\o-&T'6#T%6#,&Fh^oF:*&,&9%F:Fj`nF:F:&&T#F^ao6#F:F:F:F_\oF_
\o6(Fg\oF_^oFi\oFf_oFf\oF^^o6#Fhn6$7'Q!F_\oFj`n"#P"#s"#O7'F]boFj`nF^bo"#VF`boFg
_o>8(-%(convertG6$&F[_oFhaoI'VectorG6$Fc`oFd`o>8)7(F:F-F%F4F)F0>6%8*8+8,6%Fi^oF
i^oFi^o?(Ff_oF:F:""'%%trueGC&>8--I$<,>GFd`o6%-I$<|gr>GFd`o6%&Fdbo6#,&FbcoF:F:F:
&Fdbo6#,&FbcoF:FhnF:&Fdbo6#,&FbcoF:FeuF:-F^do6%Fcdo&Fdbo6#,&FbcoF:FdimF:&Fdbo6#
,&FbcoF:""&F:-F^do6%FfdoF^eo&Fdbo6#,&FbcoF:FecoF:>F`co,&F`coF:*&&F\coFe_oF:Fico
F:F:>Faco,&FacoF:*&&Fdbo6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GFbcoF:FjeoF:F:>F
bco,&FbcoF:F\goF:>8.-%$adjG6#F`co>8/-&I.LinearAlgebraG6$Fc`oFd`o6#%,Determinant
GFdgo>80&Fdbo6#-Fafo6%7#-Fhfo6#;F:"#7F]goFbco>F^ho)-F[do6&-F^do6%&F^hoFhao&F^ho
6#Fhn&F^ho6#Feu-F^do6%&F^ho6#Fdim&F^ho6#Faeo&F^ho6#Feco-F^do6%&F^ho6#F[go&F^ho6
#"")&F^ho6#F\go-F^do6%&F^ho6#"#5&F^ho6#"#6&F^ho6#Fgho%#%TG>81&Fdbo6#-Fafo6%7#-F
hfo6#;"#8"#<F]goFbco>827$-F^_o6$,&-I".G6$Fc`oFd`o6$,&-Fb\p6$)&F^ho6$;F_\oF_\oFf
_oF^[pFagoF:-Fb\p6$,$)FacoF^[pFhnFagoF:Fi\pF:*&&F`[pFe_oF:FfgoF:Fj`n/Ff_o;F:Fdi
m,&-Fb\p6%F_]pFagoFacoF:*&&F`[pFhioF:FfgoF:Fj`n>F\\p7$&F\\pF_\o,&*&F[anF:FfgoF:
F:Fj`nF:>83-%$mapG6$%'expandGF\\p@$Fg^oOF_^p>84-%&minusG6$-%'indetsG6#F_^p-F\_p
6#F[_o>6$8586-%,poly2matrixG6$F_^pFg^p>87-%$srtG6$Fc_p-%%tdegG6#&Fg^pF_\o6%7#-%
/permuteColumnsG6%Fb_pFc_pFh_pF^^oF_^oF_\oF_\oF_\o6#Fi^o6=7'F]boFj`n"#;FecoF`bo
7'F]boFj`nFeu"#LFbbo7'F]boFj`nFeuF\go"#X7'F]boFj`nF[go"#bFbbo7'F]boFj`nF[go"#$*
Fbbo7'F]boFj`nFeu"#IFbbo7'F]boFj`nFeu"#EFbbo7'F]boFj`nFeu"#@Fbbo7'F]boFj`nFeuFa
joFajo7'F]boFj`nF[go"#')Fbbo7'F]boFj`nF[goFfapFbbo7'F]boFj`nF[goF`boFbbo7'F]boF
j`nF[go"#:Fbbo7'F]boFj`nFeuFh`pFbbo7'F]boFj`nFeu"#RFbbo7'F]boFj`nFeu"#BFbbo7'F]
boFj`nFeu"#wFbbo7'F]boFj`nFeu"#DFbbo7'F]boFj`nFeuF`apFbboFcap7'F]boFj`nFeu"#CFb
bo7'F]boFj`nFeuF`bpF\ap7'F]boFj`n"#A"#J"#_7'F]boFj`nFeu"#QFbbo7'F]boFj`nFeuF`bo
Fbbo7'F]boFj`nFeuF]cpFbbo7'F]boFj`nFeu"#ZF]cpF_\o
