M7R0
I)F_toa_557(,\r%"vG#"-@a;jh9"-+++++]%"xG#!+.Tcup"-+++++5%"uG#"-Vs)yV-%F(%"yG#!,
r!yCe8"-++++]7%"wG#"-ZR&Rf)GF(*$F-""##!.BMK7c%=".++++++"*&F-"""F%F=#"-BQca"\#"-
+++++D*&F-F=F4F=#!-**ehH`6",++++D'*&F-F=F)F=#!-Hl:52<"-+++++?*&F-F=F0F=#"-4*[#Q
mJF,*$F%F8#!,B<^*y>F3*&F%F=F4F=#!-,oU$f!HF(*&F%F=F)F=#!-4$33Vu#FH*&F%F=F0F=#!-h
A!RXG#F(*$F4F8#!-fzu.$p#F;*&F4F=F)F=#".R)z>RD6F;*&F4F=F0F=#"-6q)R#p#*F(*$F)F8#"
-Tmjq)="",+++++&*&F)F=F0F=#!-$34(*G<"F(*$F0F8#!."\Qb,q?F;#!-BbgNB6F@F=*$F-""$#!
.Fz<4&e@F;*$F%Fho#",d:$f%y)F;*$F4Fho#"-x6I")onF;*$F)Fho#!.Z*\D!yG"F;*$F0Fho#",F
UCGt$F,*(F-F=F%F=F4F=#"-hQT;$["F(*(F-F=F%F=F)F=#!.j]:'pd8F;*(F-F=F%F=F0F=#!-(Q9
5<K#F,*(F-F=F4F=F)F=#".^`8BD\%F;*(F-F=F4F=F0F=#!+Hx?MD"*+Dcw**(F-F=F)F=F0F=#!-$
ze6z.)F@*(F%F=F4F=F)F=#!,xQ9v7*FD*(F%F=F4F=F0F=#"-n(e#z%y"F@*(F%F=F)F=F0F=#"-<h
xi5PF(*(F4F=F)F=F0F=#!-\!Qx(49F^o*&F-F8F%F=#"-4#[==(eF@*&F-F8F4F=#!,")fc=.$FD*&
F-F8F)F=#"-t(H$y<bFH*&F-F8F0F=#"-(R)G3YVF3*&F-F=F%F8#!,r$>*=!R",+++++%*&F-F=F4F
8#"-z3e*f\)F(*&F-F=F)F8#!-*4d7<3%FH*&F-F=F0F8#!,ju!Q:T",++++]#*&F%F8F4F=#"-VQY[
&)QF;*&F%F8F)F=#"-dQ?l6LF@*&F%F8F0F=#!,,Y[BO#F@*&F%F=F4F8#!-xa,KBPF;*&F%F=F)F8#
!,V0@D*yFH*&F%F=F0F8#"-H%>9oF(F;*&F4F8F)F=#"-@Q*['RGF@*&F4F8F0F=#!-^6O,GuF@*&F4
F=F)F8#!.fG)e=CAF;*&F4F=F0F8#".r-CogZ#F;*&F)F8F0F=#"."*H!fm\9F(*&F)F=F0F8#"-nM$
*\%=*F;,\rF%#"-(*=e)QX$F;F)#"-n7Ak&="FHF-#".HSw?$Q_F;F0#!.dW)y;i5F(F4#"."zbil&
\%F;F7#!-4i8YTxF(F<#!-FX*Q&GYF(FA#!.J+x%)=3"F@FE#!-jR'[-P&F(FI#"-By">%*p)F(FL#!
,T5/@0%F,FO#!,z;%H?v",+++]7$FR#"+")Qh!R#F]xFU#!-$3i+6^$F@FX#!.6e0j2,"F(Fen#"-pa
zs!R"FDFhn#".f[9)Ru9F(F[o#",>%*z(=&*F^oF_o#!+2&=Wl""++++DJFbo#!,RnZNg'F,#!,<:LW
&[F_tF=Fgo#!.zB8cL"QF;F[p#"-F[,L;LF;F^p#".\-%3fx;F;Fap#!-2!\fp*>FHFdp#"-Bmp2S%)
F(Fgp#"-FN59J6F,Fjp#!-`<X$\9$FHF]q#!-2'fa'f7F]xF`q#".f%)*\M>EF;Fcq#!.4GlaZV"F(F
gq#",tej)*=#F(Fjq#!,2/H&4xF^oF]r#"-$fuU%*Q"F(F`r#"-psUgoUF(Fcr#",L7DQ]"F@Ffr#"-
2T>PkCFDFir#!-(\)R!pI%F(F\s#".HIz`pj"F;F_s#".nMMiPA$F(Fbs#!.xpP"Go9F;Ffs#"-89ow
(*=F^oFis#"-8IEAQEF;F\t#!,@I)obH"++++]iF`t#"-p>)pna*F;Fct#",xCwj>%FDFft#"-"zW8A
]"F@Fit#!,>+#zRZFHF\u#!-$4o*=jqF;F_u#".8^xB]t"F;Fbu#!,([KGuUF3Feu#!.Vxb5oD"F@Fh
u#!.nP2pd^#F;F[v#".$Q8Ok"3#F;F^v#",())eVULF3Fav#"-.<BgGUF;,\rF%#!+xc!>?""+++++!
)F)#!-2yi!48$FHF-#!.(pUe)Hx"F;F0#"-4/g8&*=F(F4#!-R2!)*fw%FHF7#!->>HVwQF(F<#".PW
z"pL5F;FA#!,L`q)p`FHFE#",$*f8Ad$FDFI#"-,6oOr\F(FL#!,^yI8Z*F;FO#"-8cK>:EF3FR#"-j
+fLM&*F;FU#!,Va'H%H"F(FX#",H8*4'y$FDFen#!-BmMg%R%F;Fhn#"-BsjR_;F@F[o#"+\l6SI",+
++++#F_o#","[tyi$)F(Fbo#",,D6%*R#F;#",RR]qT$F]xF=Fgo#".**\?$=H;F;F[p#!-x%e$G(3#
F;F^p#!-4%=F^L(F;Fap#!-<wjS#H"F;Fdp#!,*)3!RbkF,Fgp#!,"4jaeXF@Fjp#!-2(4>Q;"F;F]q
#".dLMpUB"F(F`q#",jFr_s&FHFcq#"-RrNJ@HF@Fgq#",.`f]?&F3Fjq#"-z6+J*R"F(F]r#!-Z<[!
)3BF(F`r#!+HMW,iF^oFcr#!,*QuRH8F]xFfr#!-nn&>KF#F3Fir#"+P3@`oF^oF\s#!-4tc1y@F;F_
s#!-p4]"*zyF@Fbs#"-t&GB6U)F;Ffs#!-dm@U=#)F(Fis#!,x*z,RKFHF\t#"-P5k%QR"FDF`t#!-T
Z<p!y&F;Fct#!,FB*\z]F(Fft#!+@lk)Q""+++++DFit#",2*eCh<F;F\u#"-Tvf2\>F;F_u#!..21z
*\5F;Fbu#"-R:EIMAF@Feu#"-jQUTF!*F(Fhu#"-**4bSwSF;F[v#!-H@*GG`*F;F^v#!-B.)>!*z"F
@Fav#!-\vw&>;%F;,\rF%#"-x"p`<A#F(F)#",R_]&yfF,F-#!-,jg`3RF(F0#",@`8BN$F]xF4#"-6
k,J!R"F(F7#!+V<IcB"+++]i:F<#"-\Byd!y(F(FA#!-HQfAt>F(FE#"+\/Z%Q&",+++Dc"FI#"-ZGT
OuxF@FL#!,f1GQN&F(FO#!-8.`*3(>F@FR#!.H5N'*y\"F(FU#"*2cCt%"++]7`>FX#!+"GO]T&F^oF
en#"-"*)yQTB&F(Fhn#"+rbHTtF`flF[o#",hL6>K#F_tF_o#!,L,)3fUF3Fbo#!-V2m?UDF,#!,()G
^Pq$F^oF=Fgo#!-p-UUYgF(F[p#",2NlU+$F(F^p#"-H/T!)z5F(Fap#!,fpe@z&F,Fdp#!,P>4mO)F
@Fgp#!,*[+Ji@F^oFjp#!,xCf04#F,F]q#!-Z+M6'Q&F@F`q#".HD9P2`"F(Fcq#!,4sq5A$F`flFgq
#!-T)H0%>gF3Fjq#!+(GJ_5*",++++D"F]r#"-Her+f9F3F`r#"-R;8'=+"F@Fcr#!-Ht')H!y(F@Ff
r#"-,GFEAQF@Fir#!+Fk'zN&F@F\s#".pIp>!47F(F_s#"-<LFFHbF@Fbs#!-<PR'RY%F(Ffs#",>@T
rD$F^oFis#!.<@SK-F"F(F\t#!+tQ7\&)F_tF`t#"-4Nw8.;F(Fct#"-rV\BeHF@Fft#!+.ox`NF@Fi
t#!,HQ]3b#F,F\u#!,8f/wW$F(F_u#"-$Hs.Im#F(Fbu#",nNq%e5F`flFeu#!-.!GB6l"F3Fhu#!-F
q(4u=&F(F[v#"..Pj9&p6F(F^v#".LJ!40[5F@Fav#"-.9#[&\oF(,hzF%#"-T&4M$*3"FHF)#".Z74
`!*)RF;F-#!-^&Gx/l"FHF0#!,(fA$f#HF^`lF4#".jybsaN#F;**F-F=F%F=F4F=F)F=#!-T@\V`9F
,**F-F=F%F=F4F=F0F=#".4?S$\$*>F(**F-F=F%F=F)F=F0F=#"-`c_&Gh(F(**F-F=F4F=F)F=F0F
=#"-L\Arf6F^o**F%F=F4F=F)F=F0F=#!-([p&pVGF(*&F-FhoF%F=#"..u(GQTGF;*&F-FhoF4F=#"
-xij\[LFH*&F-FhoF)F=#".L['ei)H#F;*&F-FhoF0F=#"-R)39'\LF,*&F%FhoF-F=#"-6S?/vKF;*
&F%FhoF4F=#!*2Gs,$"*++++)*&F%FhoF)F=#!,6u(RWIF3*&F%FhoF0F=#!+@.(p&GF^o*&F4FhoF-
F=#!-f&yF#4bF(*&F4FhoF%F=#!**["z:&Ficl*&F4FhoF)F=#!-nm%\(ecF;*&F4FhoF0F=#".dJ-#
)eN"F(*&F)FhoF-F=#!-h2PR!H#FH*&F)FhoF%F=#"-nla3g?F;*&F)FhoF4F=#"-HS+;C?FH*&F)Fh
oF0F=#!,LCFT\(F,*&F0FhoF-F=#",r"H%>"GF_t*&F0FhoF%F=#!,ty*Gz\FD*&F0FhoF4F=#!,")3
cJ"QF_t*&F0FhoF)F=#"+@J$)4[F_t*&F-F8F%F8#!-`^V@`sF(*&F-F8F4F8#".d))eXP."F(*&F-F
8F)F8#!.p'*f#pH8F(*&F-F8F0F8#!-")=.TXxF@*&F%F8F4F8#!-8&)=%G["F@*&F%F8F)F8#!,.,!
>SjF(*&F%F8F0F8#!,h$>p#>%F@*&F4F8F)F8#",r%pj\CFbil*&F4F8F0F8#!-([&oLkYF@*&F)F8F
0F8#!-(p)>vTCFDF7#".^:2DrX"F(F<#!+x5,*>#"+++++?FA#!-j%y)o-8F(FE#!-ZR17elF,FI#",
>SNYT&F^`lFL#!,Vp8dq$F@FO#!-()\\-PCF3FR#!-f\kSOZF(FU#",.q*o8aF3FX#!.\R%Hw)R$F;F
en#!.r^x))o."F3Fhn#".PLS#3(o"F(F[o#!.6vwij)[F;F_o#".FerwOQ"F@Fbo#!-"Gc4eg&F@*$F
-""%#!,xoPBe(Fes*$F%Ffem#!,rh6dQ"FH*$F4Ffem#!,rnf9m*F3*$F)Ffem#!,>ukQ9"F;*$F0Ff
em#"+"*=/5MFDFgo#!-@2:aXLF(F[p#",(H3t_5F3F^p#",`QjxD#F]xFap#"-r,.0'Q&F(Fdp#!,xQ
GPh"F,Fgp#!,tANVN"F^`lFjp#"-jO^1K#)F;F]q#!+$=S=^)",+++++"F`q#".B#)3p-e$F;Fcq#!+
p@*ee#FiclFgq#!,Jbya%fF_\lFjq#"-8E3L`jF3F]r#!-n<#[(G5F3F`r#"-j4>sLwF@Fcr#!.@rH%
*oX"F(*(F-F8F%F=F4F=#!-Rje0FuF(*(F-F=F%F8F4F=#",6[YtK%Fes*(F-F=F%F=F4F8#!-pH(*[
CJF@*(F-F8F%F=F)F=#!.R,`>$[9F(*(F-F=F%F8F)F=#".LjP(yg>F;*(F-F=F%F=F)F8#!-nCXT$)
pF;*(F-F8F%F=F0F=#!-J"\K;F%F3*(F-F=F%F8F0F=#"-z0;'*4YF(*(F-F=F%F=F0F8#"-<?*4rZ'
F@*(F-F8F4F=F)F=#"-Jy.`'\%F(*(F-F=F4F8F)F=#!.P$4lok8F(*(F-F=F4F=F)F8#!.4sDzbZ"F
;*(F-F8F4F=F0F=#!.*[Cy%[W"F@*(F-F=F4F8F0F=#!-H'Q'3NCF(*(F-F=F4F=F0F8#"-(G&)f(GE
FD*(F-F8F)F=F0F=#!,(H*\0K)F^o*(F-F=F)F8F0F=#".PSndB^"F@*(F-F=F)F=F0F8#"-">d$e1;
F3*(F%F8F4F=F)F=#!-2*=S*obF(*(F%F=F4F8F)F=#"-L)o]j"yF;*(F%F=F4F=F)F8#",2>1XU"F^
`l*(F%F8F4F=F0F=#!,\]S&*G"F,*(F%F=F4F8F0F=#",BthnA$FD*(F%F=F4F=F0F8#!-T%ez)GCF3
*(F%F8F)F=F0F=#!-4k()*[2'F(*(F%F=F)F8F0F=#!,^&QK"z"F,*(F%F=F)F=F0F8#"+(*[\Q7F_t
*(F4F8F)F=F0F=#".z1<9T1"F(*(F4F=F)F8F0F=#!-p-vTR?F,*(F4F=F)F=F0F8#!,@*=X*f"F^oF
fr#!-8&*p1_'*F;Fir#!-h7yfF&)F;F\s#",RTU!ytF]xF_s#"+F$G5k*F@Fbs#",t!\YIbF,Ffs#",
z>h4h$F,Fis#"-tH2?4=F]xF\t#"-pU^13CF@F`t#"-Zk$3,6#F@Fct#!-$Qnhb6"FHFft#"-*yExI%
>F(Fit#",*ei9s^F^`lF\u#".n&)4+!4;F;F_u#!.Fnc)z<;F;Fbu#!+"o7,M#"+++]7yFeu#!,BlS:
;)F@Fhu#"-Vu[&4c'F;F[v#"..GS+9&>F;F^v#!-hPNcBAFDFav#"-f>Y,&o*FH#!,*>TuXBFDF=,^r
F%#!*zn&f9"+++++5F)#!)t\77"*++++#F-#!*z!oD*)F\anF0#!*zepC""*++++&F4#!+x-XT6F\an
%"zG!""F7#!)f`yc"*++++"F<#"*n`UZ"F_anFA#!*2-9j&F\anFE#!).Z^f")++DJFI#"+B=)4+"Fd
anFL#"(JL^"")+++SFO#")h7MY")+++]FR#"(p&>QF\anFU#"("QNcFdanFX#"'jrg")+++5Fen#!+L
&*o5:F\anFhn#"*,nYR%"*+++]#F[o#")H"Qr&F[bnF_o#"*H2=z'FdanFbo#!*(Rg&4*F\anFgo#"(
"3d^F\anF[p#!)$Gj%))F\anF^p#!)RA'>#F_anFap#!*>*)Rh"F_anFdp#!*^5#oFFdan#")r)H$GF
jbnF=Fgp#"$6'"(++D"Fjp#!*8#f'>#F_anF]q#"*Vv=;%FdanF`q#"+`OqWJF\anFcq#!)><DEFjbn
Fgq#!*RI&*f$"*+++D"Fjq#!*T'R[6FdanF]r#!)6L*H&FdanF`r#"*@I#e5FfenFcr#!)RET"*Fjbn
Ffr#!)2aL]FfcnFir#!)tb%y$FfenF\s#"+deU#G#F\anF_s#!)Z5*e&")++]iFbs#"*$)R&>7F\anF
fs#!**pot;FdanFis#!*fSq6(F\anF\t#"*V*G)p"FfenF`t#!*f*RZ9F\anFct#"*$ek'3$FdanFft
#!*x7NB"FfcnFit#!)jrX[F\anF\u#")"z`7(F\anF_u#!*d[UG(F\anFbu#"*fTt"HFfcnFeu#!)*)
R)="F[bnFhu#!*Z"*o))*F\anF[v#"*H<yV%F\anF^v#")6()=>FbbnFav#"*<NTP)F\an6",
I)C_toa_55w,6#>%)symbolicGF=66%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G%#_
VG%"iG%#M1G%#vvG%"HG%"bG%&countG%"CG%%adjHG%%detHG%"SG%#ddG%$eqsG6"FhhnC4>6$8$8
%6$7#%"MG7#7$"#rF=@%/9$F=>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#o
pG6#&Fhjn6#8,w,6$F)F0Fhhn6$%)operatorG%&arrowGFhhn-&T'6#T%6#,&Fa[oF=*&,&9%F=Fha
nF=F=&&T#F\]o6#F=F=F=FhhnFhhn6(F`inFhjnFginFc\oF_inFgjn6#F86$7'Q!FhhnFhan"#R"#u
"#O7'F[^oFhanF\^o"#XF^^o/Fc\o;F=-%%nopsG6#Fgjn>Fc[o7#-Ff[o6$-%'rndMatG6#F^\oFa^
o>8--%(convertG6$&Fc[oFf]oI'VectorG6$F[\oF\\o>8.7(F=F-F%F4F)F0>6%8/80816%""!F^`
oF^`o?(Fc\oF=F=""'%%trueGC&>82-I$<,>GF\\o6%-I$<|gr>GF\\o6%&F^_o6#,&F\`oF=F=F=&F
^_o6#,&F\`oF=F8F=&F^_o6#,&F\`oF=FhoF=-Fi`o6%F^ao&F^_o6#,&F\`oF=FfemF=&F^_o6#,&F
\`oF=""&F=-Fi`o6%FaaoFiao&F^_o6#,&F\`oF=F``oF=>Fj_o,&Fj_oF=*&&Ff_oFb\oF=Fd`oF=F
=>F[`o,&F[`oF=*&&F^_o6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GF\`oF=FeboF=F=>F\`o
,&F\`oF=FgcoF=>83-%$adjG6#Fj_o>84-&I.LinearAlgebraG6$F[\oF\\o6#_Fddo%,Determina
ntGF_do>85&F^_o6#-F\co6%7#-Fcco6#;F="#7FhcoF\`o>Fjdo)-Ff`o6&-Fi`o6%&FjdoFf]o&Fj
do6#F8&Fjdo6#Fho-Fi`o6%&Fjdo6#Ffem&Fjdo6#F\bo&Fjdo6#F``o-Fi`o6%&Fjdo6#Ffco&Fjdo
6#"")&Fjdo6#Fgco-Fi`o6%&Fjdo6#"#5&Fjdo6#"#6&Fjdo6#Fceo%#%TG>86&F^_o6#-F\co6%7#-
Fcco6#;"#8"#<FhcoF\`o>877%-Ff[o6$,&-I".G6$F[\oF\\o6$,&-F^io6$)&Fjdo6$;FhhnFhhnF
c\oFjgoF\doF=-F^io6$,$)F[`oFjgoF8F\doF=FeioF=*&&F\hoFb\oF=FadoF=Fhan/Fc\o;F=Ffe
m,&-F^io6%F[joF\doF[`oF=*&&F\hoFdfoF=FadoF=Fhan,&FadoF=FganFhan>8'-%$mapG6$%'ex
pandGFhho@$0Fa[oF=OFgjo>8(-%&minusG6$-%'indetsG6#Fgjo-Fe[p6#Fc[o>6$8)8*-%,poly2
matrixG6$FgjoF`[p>8+-%$srtG6$F\\p-%%tdegG6#-F_\o6#F`[p6%7$%#cfG-%/permuteColumn
sG6%F[\pF\\pFa\pFgjnFhjnFhhnFhhnFhhn6#F^`o6<7'F[^oFhan"#;F``oF^^o7'F[^oFhanFho"
#L"#V7'F[^oFhanFhoFgcoF`^o7'F[^oFhanFfco"#&*Ff]p7'F[^oFhanFfco"#dFf]p7'F[^oFhan
Fho"#IFf]p7'F[^oFhanFho"#EFf]p7'F[^oFhanFho"#DFf]p7'F[^oFhanFhoF]goF]go7'F[^oFh
anFfco"$G"Ff]p7'F[^oFhanFfco"#@Ff]p7'F[^oFhanFfco"#SFf]p7'F[^oFhanFfco"#BFf]p7'
F[^oFhanFhoFc]pFf]p7'F[^oFhanFhoF\^oFf]p7'F[^oFhanFho"#FFf]p7'F[^oFhanFho"#')Ff
]p7'F[^oFhanFho"#HFf]p7'F[^oFhanFho"$/"Ff]p7'F[^oFhanFho"#CFf]p7'F[^oFhanFhoFh^
pF`^o7'F[^oFhanFj^p"#K"#_7'F[^oFhanFho"#QFf]p7'F[^oFhanFhoF^^oFf]pFd]p7'F[^oFha
nFho"#`"#JFhhn
