M7R0
I)F_toa_557(,\r%"vG#!-dmWYT?".++++++"%"xG#"+2Kc]7",++++D"%"uG#!-`8uGWUF(%"yG#!.
(*=oj*Q9"-+++++]%"wG#!.JR-3UL"F3*$F-""##!,6ge<D"",+++]7$*&F-"""F%F=#!-,OK)yb#F(
*&F-F=F4F=#"-$\w@iN)"-+++++?*&F-F=F)F=#"-@1mGlpF3*&F-F=F0F=#"-^vJ,mr"-+++++D*$F
%F8#",j@wjy*"-++++]7*&F%F=F4F=#!.FRFb'))=F(*&F%F=F)F=#!-<^'3\D&FJ*&F%F=F0F=#!+*
Q%*QY&"+++]7y*$F4F8#!*$>!=\"FX*&F4F=F)F=#!.r8(G`4?F3*&F4F=F0F=#!-jt>A_8",+++++&
*$F)F8#",^&f&>4*FC*&F)F=F0F=#!.,&\*)))o@F3*$F0F8#!.,-W`oB#F(*$F-""$#",dPS?s#F3*
$F%Fgo#"-$oV'\ZCF3*$F4Fgo#"-tyJiEDFN*$F)Fgo#"-(pVKZF$F3*$F0Fgo#",,ulzR'F\o*&F-F
8F%F=#"-\#)3C"*QF3*&F-F8F4F=#!-()**=MvfF3*&F-F8F)F=#!-8)Gk.,""-+++++5*&F-F8F0F=
#"-t"H4@T"FJ*&F-F=F%F8#!-Tz(GMw"FN*&F-F=F4F8#".tN#\5];F3*&F-F=F)F8#!+"\V!=5F;*&
F-F=F0F8#!-TTe=P*)F3*&F%F8F4F=#"-na")\">#",++++D'*&F%F8F)F=#"*JsIn)F_q*&F%F8F0F
=#"-,nec\"*FJ*&F%F=F4F8#!.*foS_/GF3*&F%F=F)F8#!-Bf+&)[7F_q*&F%F=F0F8#"-"4r3dS&F
N*&F4F8F)F=#"-x33DjHFJ*&F4F8F0F=#!,4*)HYO*",++++]#*&F4F=F)F8#",pT&=@G",+++++#*&
F4F=F0F8#!-2mUwDOF3*&F)F8F0F=#!,`=buu$FJ*&F)F=F0F8#!.`MO()Ga"F3*(F-F=F%F=F4F=#!
,pG)["y"F,*(F-F=F%F=F)F=#"-2y@#)p))F3*(F-F=F%F=F0F=#!.6%*eb]1"FJ*(F-F=F4F=F)F=#
"-dW#[!f)*FJ*(F-F=F4F=F0F=#"-(=WA\%pF3*(F-F=F)F=F0F=#"."\8Tl"4#F3*(F%F=F4F=F)F=
#!-hD1#ew(FN*(F%F=F4F=F0F=#".4DQt.6"F3*(F%F=F)F=F0F=#!.H'oZ7H=F3*(F4F=F)F=F0F=#
!+xcmu$)"+++]i:#","[kB^#*F3F=,\rF%#"+Zq)Gd(",+++++"F)#"-p.+=EsFJF-#!-@*4JHr$FNF
0#"*ji"fo",+++Dc"F4#!-z0@%[D#FJF7#"-,l@)>W%FJF<#"-Vb(GBI"FNF@#!.pJ)zS[=F3FD#!.^
a')p\L"FJFG#!-ZSaKg>F3FK#!-J5_N5dF3FO#".`orO!e9F3FR#"-x2cpYRFJFU#!-JHm6V]F3FY#!
,$)yi%pFFhsFfn#!-8Ch36QFJFin#!-"HL0"=TFJF]o#".*)eze+G"F3F`o#"-<E#>a.$FJFco#!-`5
&H**="F_qFfo#!,HtsH:(F3Fjo#!-"ou$y7BF3F]p#!+VFXM:F,F`p#",RLv3,#FhsFcp#"-xSA$Rz#
F3Ffp#!-*=]ste)F3Fip#"-JOxF0SFNF\q#"-HxLB#3&FJF`q#!-,8A&>^$FJFcq#",*z&R!\[F;Ffq
#!,zxs&*z"FbrFiq#!.n)H;Q-;F3F\r#"-h`\2/5F_qF_r#".j_uJz1"F3Fcr#!-6L/4NGFJFfr#!-`
CAQ"["FNFir#!,$eHEY$*FNF\s#"+`P#Ht%"+++D1RF_s#",*>v#Rj$FNFbs#!,8nvXf#F,Fes#!,8+
)\tNFawFis#"-H=%*3.:FJF]t#",(e:>GKFbrF`t#"-rZ;"yE)F3Fct#!,8%)\A@'FbrFft#!.f1+'p
q9F3Fit#"-"y'4?(f#FJF\u#".$R+pAV;F3F_u#!-x'o`Su$FNFbu#!,8xV*\%)F_qFeu#!-"*)\U"*
H"FNFhu#",nOgoY$F\oF[v#".Pj"4Q")>F3F^v#!,F6N[(fF\oFav#!,>*=UgwFhs#",$pg`F=FawF=
,\rF%#!.H!fF[)p"F(F)#"-*)ePN[UF3F-#".@.A$)=&>F(F0#".$pW1I06F(F4#".ZC/+-C"F(F7#!
.t*R))\(o#F(F<#".*)eF#)y4&F(F@#!-V.n``CFbrFD#!-hxty"H$FJFG#!,(\8g)o#F(FK#!.z'yP
#)4FF(FO#"."*f***\M;F(FR#",<Ur9:)FNFU#!-6U;!G&GFNFY#!-jHvJ/aF3Ffn#",,@oaD(F\tFi
n#"-Fp['=v(F(F]o#"-HT/XIjF(F`o#".j>tFcQ"F3Fco#",xM<R8%FCFfo#!+x:-8eFJFjo#!+,Sp5
mFhsF]p#!+@#Rm%zFhsF`p#",V"G?M&*F3Fcp#!*$Qoi$)F3Ffp#!-*H**Gjy"FJFip#",j(pK[RF3F
\q#"-BWW,%p&F3F`q#!-"4I(p)=$F3Fcq#"-T=&y_O#FJFfq#!,TFQZ1%FbrFiq#!,,5w#HgFNF\r#"
-L(yxGc#FJF_r#!-folVP=FbrFcr#"+zwn?=FNFfr#!-F*pD'>bFJFir#"-LQQhO9FbrF\s#",*oLaD
dFNF_s#!-<:S$Q`(F3Fbs#!,B440@'FhsFes#"-@v*fz(>FJFis#!-L$3BG>"F3F]t#"+f3(f(R"+++
+]iF`t#",xz'3L**FJFct#"-n!GG%\NFJFft#"-8n'*e>&*FJFit#!-r8&zjU"FNF\u#",xjL?U""++
+++SF_u#!.rz%>2s9FJFbu#"->zY?CVF3Feu#!.nQDjM">F3Fhu#"-,Ci4(*eFNF[v#!-FTdt/5FNF^
v#".Vq$=Mv6F3Fav#"-fkw(4a'F3#",B43"RIFJF=,\rF%#"-")4t^jOF3F)#!.ZQ'>2R8FJF-#".`]
SZ#f6F3F0#!-(["HDq;FCF4#!*R3-#>F(F7#!-F5sm@JFCF<#!.(Gm-B(H"F3F@#"-t<4&3x*FCFD#"
-ry=/JnF_qFG#!-\NY]y)*F(FK#".L+sebq"F(FO#!-<&)>*Qb'FJFR#!,pV)fB(*F_qFU#"-Z;K#**
o(F3FY#",8&*=Qn$F\tFfn#!+n***Rl(FhsFin#"-F.^4/VFCF]o#!.jnS-fK#F3F`o#!-^^%ftc'FJ
Fco#!-(y,F*[HF3Ffo#",\r%)*zZF3Fjo#"-@#\@]4#F3F]p#!-d$*)G!45FbrF`p#!-h(QNr,#FJFc
p#!-tXar(e&F3Ffp#"-@6;JjzF3Fip#!,6Ee(3%*FbrF\q#!-(eOx)faFJF`q#"-*z/aJO(F3Fcq#!-
B>%ywl$FJFfq#!..+%z^%z"F3Fiq#"-jd$3q^$FNF\r#!,*>gV>XF_qF_r#!-d)G^;e"FJFcr#"-Rrh
;<SF3Ffr#"-2^LC#\$FJFir#"-*yUe))*HF_qF\s#!-*3CfPk&F3F_s#!,41lv2(F_qFbs#"-VqYO@s
FJFes#"-t1YqsjFJFis#!,x9+D7(FJF]t#!,r?"*["pF_qF`t#!-*pL.xc$FJFct#"-$*e9,*p"F3Ff
t#!,t=v%**HFJFit#!-"zOvcH"F3F\u#!.h"fLkz<F3F_u#".f%R9rs7FJFbu#!-">aIW$RFJFeu#",
Fd)zgwF;Fhu#!-xaR!yx&FJF[v#!-Tjt(yO#F_qF^v#!,VB=B"RFJFav#".(41%)=X8F3#!-R:8WgyF
3F=,hzF%#"-,9akEKFJF)#",<I,lJ"FbclF-#!-L#H/4G&FJF0#".,6==&=CF(F4#!+zc%3!QF(**F-
F=F%F=F4F=F)F=#!.J@3`Tb"F3**F-F=F%F=F4F=F0F=#".h(zr9=>F3**F-F=F%F=F)F=F0F=#!-4+
`'3R)F3**F-F=F4F=F)F=F0F=#!-$y,-aK%F_q**F%F=F4F=F)F=F0F=#"-x(*\-puF3*&F-FgoF%F=
#",nQ!y**eFC*&F-FgoF4F=#!-\*)[K`6FC*&F-FgoF)F=#!,"H5BpMF_q*&F-FgoF0F=#",(H()4^M
F_q*&F%FgoF-F=#"+2#\)3>Ff[l*&F%FgoF4F=#",")\q!=))FN*&F%FgoF)F=#!,PxS/p"F_q*&F%F
goF0F=#!+j621"*FN*&F4FgoF-F=#!.82M2)RZF(*&F4FgoF%F=#".F))oR'=]F(*&F4FgoF)F=#!,6
cn2f*F_q*&F4FgoF0F=#","eoy4?F;*&F)FgoF-F=#"-<k4O1:F3*&F)FgoF%F=#",*y^nUcF3*&F)F
goF4F=#!*RX%GGFhs*&F)FgoF0F=#",rZxVY#FJ*&F0FgoF-F=#"+,()R1:Fjv*&F0FgoF%F=#"-(Rp
0"oXF(*&F0FgoF4F=#!-T%*o*yY%F(*&F0FgoF)F=#!-RzhnG7F3*&F-F8F%F8#!-T,k2TrF(*&F-F8
F4F8#!-2%y#)zL$F_q*&F-F8F)F8#",ZJb()3'FJ*&F-F8F0F8#",fn:a#oFN*&F%F8F4F8#!.>A&G%
H9"FJ*&F%F8F)F8#"-<P;<"Q$F(*&F%F8F0F8#"-\@O<b5FJ*&F4F8F)F8#".@^lp\d"F(*&F4F8F0F
8#"-<$z-Z@#F(*&F)F8F0F8#!,VCV*4RFbrF7#".6+^dao#F(F<#",BjC#GTF3F@#","y4$\L"F3FD#
!.p+JRL<$F3FG#",@"H)Ri'FbrFK#!-,]C/q'*F3FO#".\bB%p"*>F(FR#"-j*oFWr"F;FU#!-^l&oH
<%FCFY#",`%*R9K(FbrFfn#!.***e<lw5F3Fin#".^;q"\fLF(F]o#",\_`n#))FCF`o#"-6&)e0D%*
FJFco#".Z0\Q3M"F(*$F-""%#"+zs96>Fbr*$F%Fbem#!,<t9nB#FC*$F4Fbem#!-$G#[XRPFJ*$F)F
bem#!,H/b"*y$FC*$F0Fbem#!,B4.<0#F(Ffo#!-ZDzOqNF3Fjo#!-$y?We;#FCF]p#!-8MX*[O"F3F
`p#!+P!*)zL(FXFcp#!-6f))[njF3Ffp#!-4k)))4P$FJFip#"-.n!>V+$F3F\q#"-hG9z#G%FNF`q#
!,2^@w4%F,Fcq#"+$R.zn#"*+Dcw*Ffq#!.,GevZ=#F(Fiq#!,"fmAOTF\tF\r#!-^%RA2g(F(F_r#"
-<.o;EWFJFcr#!,ZHjm_#FNFfr#!.zzXan-$F(Fir#",T$))f*Q$FCF\s#".x(o:#37$F(F_s#!-@FZ
l=`FJFbs#"."y?>s#)>F3Fes#"-"e$>**R[FJFis#!-ZfgT#R(FCF]t#!-(*\fyq7F(F`t#",PLh1*z
F3Fct#"-fjh?89FNFft#!.B>(\vA^F(Fit#!.>jIv)o:F3F\u#".8!H80>[F(F_u#".\2a(4=9FJFbu
#!.8"eU&z,(F(Feu#",HXmH.%F_qFhu#"-tA4*GA"FJF[v#".Bg**Grf"F(F^v#",>jz>@$F_qFav#"
-\9obb[F_q*(F-F8F%F=F4F=#"."3iPGMKF(*(F-F8F%F=F)F=#"-`Ia:?EF3*(F-F8F%F=F0F=#!+*
3S4$RFN*(F-F8F4F=F)F=#!-rgm')R5Fbr*(F-F8F4F=F0F=#!,nx\Rs"Fbr*(F-F8F)F=F0F=#!-$y
R\&eHF3*(F-F=F%F8F4F=#!.F+m&esAF(*(F-F=F%F8F)F=#",B%z'3`'F3*(F-F=F%F8F0F=#"-PuJ
pJNF(*(F-F=F4F8F%F=#".p)=D;w$)F(*(F-F=F4F8F)F=#!-j\&>_7%FN*(F-F=F4F8F0F=#!.@h"4
Z;5F3*(F-F=F)F8F%F=#!-`_'GyS*F(*(F-F=F)F8F4F=#".Va]9,F#F3*(F-F=F)F8F0F=#".J"3^q
J?F(*(F-F=F0F8F%F=#",8nb(\CF3*(F-F=F0F8F4F=#"-$\)zr0SF3*(F-F=F0F8F)F=#!,\*4QnEF
hs*(F%F8F4F=F)F=#"-L"H;?L&FJ*(F%F8F4F=F0F=#!."yvH:p9F(*(F%F8F)F=F0F=#",p#fc5**F
_q*(F%F=F4F8F)F=#",hA3.2%F\o*(F%F=F4F8F0F=#"*PX9P"Fdv*(F%F=F)F8F4F=#!.$\$)32kFF
(*(F%F=F)F8F0F=#!-t!Q=w=$FJ*(F%F=F0F8F4F=#!."pLaG/5F(*(F%F=F0F8F)F=#"-8BpJH6FJ*
(F4F8F)F=F0F=#",hX8*[MF_q*(F4F=F)F8F0F=#!+$\maJ"F(*(F4F=F0F8F)F=#",RYvvr$F3#",
\c<7(zF_qF=,^rF%#"*B/[&o"*++++&F)#"*$\x#*p"*+++]#F-#!+*y))3Y"Fg`nF0#"*8i;2#"*++
++"F4#!)$371'Fg`n%"zG!""F7#"+")eQP7Fg`nF<#"(zU(H")+]i:F@#!*<FFB&"*++++#FD#!*J&y
9N")++]iFG#!*db%f;"+++++5FK#!+>N!*z8FabnFO#"+<A=!R#FabnFR#"+$*[:Q=Fg`nFU#!+\wx"
G"FabnFY#"(H>u(")++DJFfn#!*<qvC#Fg`nFin#"*6')Qx$Fg`nF]o#"+6@cI7FabnF`o#"*x4.%="
)+++]Fco#"*6EGe%FabnFfo#!)F8XEF[bnFjo#!*.yw&eFabnF]p#!)2l;F")+++DF`p#!(Fj#RFhan
Fcp#!*dh0T'FabnFfp#!+6gU#R"FabnFip#"+,T2#f"Fg`nF\q#"*"y?0QFj`nF`q#!(B2I%"(+++%F
cq#"*^ad;%Fj`nFfq#!*RV+&fFg`nFiq#!+$*yIl>FabnF\r#"*"elhDF[bnF_r#"*^$Rt)*FabnFcr
#!*r%Qr5"*+++D"Ffr#!+2#eW="Fg`nFir#"*(GGDwFg`nF\s#"*xgW^%Fj`nF_s#!*F%HifFj`nFbs
#!)2O]'*Fj`nFes#")@$e"\FecnFis#!*HUKM%Fg`nF]t#"*n2(\EFg`nF`t#"*2<"))**FabnFct#"
*,DQ?&Fg`nFft#!+\;l*H%FabnFit#")*yc3"Fg`nF\u#"+"*f7+KFabnF_u#!*Rosy#Fg`nFbu#!+T
k3x@FabnFeu#!*$pq?oFg`nFhu#"*j@(GGFhenF[v#"+j?Yp7FabnF^v#"*T^;l"Fj`nFav#"*jFki)
Fg`n#"*8*\mJFj`nF=6",
I)C_toa_55w,6#>%)symbolicGF=66%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G%#_
VG%"iG%#M1G%#vvG%"HG%"bG%&countG%"CG%%adjHG%%detHG%"SG%#ddG%$eqsG6"FchnC4>6$8$8
%6$7#%"MG7#7$"#rF=@%/9$F=>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#o
pG6#&Fcjn6#8,w,6$F)F0Fchn6$%)operatorG%&arrowGFchn-&T'6#T%6#,&F\[oF=*&,&9%F=Fca
nF=F=&&T#Fg\o6#F=F=F=FchnFchn6(F[inFcjnFbinF^\oFjhnFbjn6#F86$7'Q!FchnFcan"#R"#u
"#O7'Ff]oFcanFg]o"#XFi]o/F^\o;F=-%%nopsG6#Fbjn>F^[o7#-Fa[o6$-%'rndMatG6#Fi[oF\^
o>8--%(convertG6$&F^[oFa]oI'VectorG6$Ff[oFg[o>8.7(F=F-F%F4F)F0>6%8/80816%""!Fi_
oFi_o?(F^\oF=F=""'%%trueGC&>82-I$<,>GFg[o6%-I$<|gr>GFg[o6%&Fi^o6#,&Fg_oF=F=F=&F
i^o6#,&Fg_oF=F8F=&Fi^o6#,&Fg_oF=FgoF=-Fd`o6%Fi`o&Fi^o6#,&Fg_oF=FbemF=&Fi^o6#,&F
g_oF=""&F=-Fd`o6%F\aoFdao&Fi^o6#,&Fg_oF=F[`oF=>Fe_o,&Fe_oF=*&&Fa_oF]\oF=F_`oF=F
=>Ff_o,&Ff_oF=*&&Fi^o6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GFg_oF=F`boF=F=>Fg_o
,&Fg_oF=FbcoF=>83-%$adjG6#Fe_o>84-&I.LinearAlgebraG6$Ff[oFg[o6#_F_do%,Determina
ntGFjco>85&Fi^o6#-Fgbo6%7#-F^co6#;F="#7FccoFg_o>Fedo)-Fa`o6&-Fd`o6%&FedoFa]o&Fe
do6#F8&Fedo6#Fgo-Fd`o6%&Fedo6#Fbem&Fedo6#Fgao&Fedo6#F[`o-Fd`o6%&Fedo6#Faco&Fedo
6#"")&Fedo6#Fbco-Fd`o6%&Fedo6#"#5&Fedo6#"#6&Fedo6#F^eo%#%TG>86&Fi^o6#-Fgbo6%7#-
F^co6#;"#8"#<FccoFg_o>877%-Fa[o6$,&-I".G6$Ff[oFg[o6$,&-Fiho6$)&Fedo6$;FchnFchnF
^\oFegoFgcoF=-Fiho6$,$)Ff_oFegoF8FgcoF=F`ioF=*&&FggoF]\oF=F\doF=Fcan/F^\o;F=Fbe
m,&-Fiho6%FfioFgcoFf_oF=*&&FggoF_foF=F\doF=Fcan,&F\doF=FbanFcan>8'-%$mapG6$%'ex
pandGFcho@$0F\[oF=OFbjo>8(-%&minusG6$-%'indetsG6#Fbjo-F`[p6#F^[o>6$8)8*-%,poly2
matrixG6$FbjoF[[p>8+-%$srtG6$Fg[p-%%tdegG6#-Fj[o6#F[[p6%7$%#cfG-%/permuteColumn
sG6%Ff[pFg[pF\\pFbjnFcjnFchnFchnFchn6#Fi_o6<7'Ff]oFcan"#;F[`oFi]o7'Ff]oFcanFgo"
#L"#V7'Ff]oFcanFgoFbcoF[^o7'Ff]oFcanFaco"#&*Fa]p7'Ff]oFcanFaco"#dFa]p7'Ff]oFcan
Fgo"#IFa]p7'Ff]oFcanFgo"#EFa]p7'Ff]oFcanFgo"#DFa]p7'Ff]oFcanFgoFhfoFhfo7'Ff]oFc
anFaco"$G"Fa]p7'Ff]oFcanFaco"#@Fa]p7'Ff]oFcanFaco"#SFa]p7'Ff]oFcanFaco"#BFa]p7'
Ff]oFcanFgoF^]pFa]p7'Ff]oFcanFgoFg]oFa]p7'Ff]oFcanFgo"#FFa]p7'Ff]oFcanFgo"#')Fa
]p7'Ff]oFcanFgo"#HFa]p7'Ff]oFcanFgo"$/"Fa]p7'Ff]oFcanFgo"#CFa]p7'Ff]oFcanFgoFc^
pF[^o7'Ff]oFcanFe^p"#K"#_7'Ff]oFcanFgo"#QFa]p7'Ff]oFcanFgoFi]oFa]pF_]p7'Ff]oFca
nFgo"#`"#JFchn
