M7R0
I+F_toy_dim17%,*#"$*e"$+&"""*&%"xGF(%"wGF(F(*&%"yGF(F*F(F(F-#"$(H"%+5,*#!'"z\""
(+++"F(*$F+""#F(*$F*F6F(*$F-F6F(,,#"#P"$+#F(*&F+F6F-F(F(*$F*""$F(F*#"&4#))F4*$F
-F?F(6",
I+C_toy_dim1w,6#>%)symbolicGF(62%&_nameG%&_sizeG%#_AG%"iG%#a1G%#a2G%#a3G%#v1G%#
v2G%#v3G%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FCC0>6$8$8%6$7#%"AG7#7$F?F(@%/9$"
"!>8&7#-%$seqG6$-%'rndMatG6#&&Fin6#8'FC/F_p;F(-%%nopsG6#Fhn>Fdo7#-Fgo6$-I'Matri
xG6$%*protectedG%(_syslibG6$F\pw,6$F*F-FC6$%)operatorG%&arrowGFC-&T'6#T%6#,&Fao
F(*&,&9%F(!""F(F(&&T#Fgq6#F(F(F(FCFC6(FKFinFMF_pFJFhn6#F66$7'Q!FCF^rF;"#s"#O7'F
grF^rF;"#VFirF`p>8(-%(convertG6$-I$<,>G6$F\qF]q6'F(F(F(F(&&FdoFbr6$F(F(I'Vector
G6$F\qF]q>8)-F_s6$-Fbs6'F(F(F(F(&Ffs6$F6F(Fhs>8*-F_s6$-Fbs6'F(F(F(F(&Ffs6$F?F(F
hs>6%8+8,8-6%-Fbs6'F,*&%"zGF(F-F(F)FcuF(-Fbs6'F7F8*$FcuF6F5F(-Fbs6'F>FB*&FcuF6F
*F(F=F(>8.7%-I".G6$F\qF]q6$)F]s%#%TGF\u-F^v6$)F[tFbvF]u-F^v6$)FctFbvF^u>F[v-%%s
ubsG6$/Fcu-%$rndGFCF[v>8/-%$mapG6$%'expandGF[v@$F`oOFaw>80-%&minusG6$-%'indetsG
6#Faw-F^x6#Fdo>6$8182-%,poly2matrixG6$FawFiw>83-%$srtG6$Fex-%%tdegG6#&FiwFC6&7#
-%/permuteColumnsG6%FdxFexFjxFjxFhnFinFCFCFC6#Fbo647'FgrF^r"#;""'Fir7'FgrF^rF?"
#KF[s7'FgrF^rF?""*"#X7'FgrF^r""("#bF[s7'FgrF^rFbz"#$*F[s7'FgrF^rF?"#\F[sFfzFfz7
'FgrF^rF?"#"*F[s7'FgrF^rF?FirF[s7'FgrF^rF?"#FF[s7'FgrF^rF?"#CF[s7'FgrF^rF?"#RF`
z7'FgrF^r"#A"#J"#_7'FgrF^rF?"#QF[sFjz7'FgrF^rF?Fc[lF[s7'FgrF^rF?"#^Fc[lFC
