M7R0
I/F_toa_46_w_sat7',bo%"vG#".JH)G7xF".++++++"%"xG#".4o\I/2#F(%"yG#!-6fDL6=F(%"wG
#"-*pT)>?:F(*(F)"""F/F3F%F3#"-ZO8+aR"-+++++]*(F,F3F/F3F%F3#!,nk5ol%",++++D'*(F,
F3F)F3F%F3#"-Bu@vR5"-+++++D*(F,F3F)F3F/F3#!-Bfi.bSF6*$F%""##"+VFy_$)F(*&F%F3F/F
3#!-Tz\<tD"-+++++?*&F%F3F)F3#!.r&*zin`"F(*&F%F3F,F3#"-Ve#eUV#F(*$F/FC#!,dco=.&F
(*&F/F3F)F3#!-H"Q)z'=""-+++++5*&F/F3F,F3#"-x/+446"-++++]7*$F)FC#!->Hc\YmF(*&F)F
3F,F3#"-B2.(3'zF6*$F,FC#"-t%*G$>7$F6*&F/F3F%FC#"-87/oPXF>*&F)F3F%FC#!-`FJL!3"F>
*&F,F3F%FC#!,^5S0D)F6*&F/FCF%F3#!-8\%Q,T"F>*&F)FCF%F3#",(o09aC",++++D"*&F,FCF%F
3#"-,<wQ/NF6*&F)F3F/FC#"-VsUK<5F>*&F,F3F/FC#",\tk:5#F6*&F)FCF/F3#!,<tug$HF>*&F,
FCF/F3#!,h;&[(>#",+++++&*&F,F3F)FC#!,T;**R-%FZ*&F)F3F,FC#!-Fi`65bF6*$F%""$#!-8f
ioy<FV*$F/Feq#",Baf$ezF6*$F)Feq#",rXAGb)FV*$F,Feq#!-jC:&\.#F6#!,nLCf+&F]qF3,boF
%#",`c7Fi'FZF)#!,ZGIDS(",++++]#F,#!.tbNg/B"F>F/#",t97?&=F>F2#"-\WFG8OF6F7#"*nRu
[&"+++++!)F;#!.Zq3yx^"F(F?#!-nl'zo:%F>FB#!.n:#Rt!3#F(FF#"-Rw\9vBF6FJ#!-4O3:*y#F
6FM#"."H@])4,)F(FP#!,t)eMw[F6FS#".")Q[Obf"F6FW#"."=/R(Gr"F(Fen#".@'Hb$Qz#F(Fhn#
".TV*)z?y&F(F[o#"-$)f=0bnF>F^o#!,\cSJ'R",+++]7$Fao#"+,bKO<"+++++]Fdo#!.H22Sn&[F
(Fgo#".r!e"HT1"F(Fjo#!-"G\#GoZF6F^p#!.T0e7#=6F(Fap#!->QWTT?FIFdp#!,\dS<j'F>Fgp#
!-^ofp\hF(Fjp#!-4'=Zvp'F(F^q#"-2VqilUF>Faq#",B`Jl\(F(Fdq#".j6'e><:F(Fhq#!-LnYGL
JF(F[r#!-TynD6xF(F^r#!-HgWR!e&F(#"+VNNb'*F:F3,boF%#"-r"e#G"*fF6F)#"-zLWC*>&F6F,
#!-Ta\w67F6F/#"-,!>ID(GF6F2#",dT&GOGF\uF7#!->"H$\v()F6F;#"-pi#ef"[F6F?#"-"RhIbX
"F>FB#"-*3nf#pWF>FF#!-nvRWm>FVFJ#!-z4DD/bF6FM#!-R9]VnZFZFP#!,@2t))\&F6FS#"+H7^f
sF\uFW#"-.fvdC\FVFen#!,.4RO&oF:Fhn#!.pbaiR`"F6F[o#!-ZSe*p/*F>F^o#!-<"*3xt;F>Fao
#!,H0=8#)*FZFdo#"-z"RWo7'F6Fgo#"-tU"HEA$F6Fjo#",6a>R+"F\uF^p#".L6yvhg"F6Fap#!,x
F2l%>F6Fdp#!,p`/F(QF:Fgp#"-$p!R*='=F6Fjp#",t[nW5%F6F^q#!+(\ctM%FZFaq#!,p0]!pvFV
Fdq#!,$eF-$[$F6Fhq#"+>lf(G"F6F[r#"+6W")yw",+++++#F^r#!-4!)pDVAF6#!->fX54BF>F3,h
sF%#"+6#\Wf$F:F)#"-F-'eaN%FZF,#".$oqFD75F>F/#",nxGFh)FZ**F%F3F/F3F)F3F,F3#!-T@
\V`9FVF2#!,P2-`N"Fa[lF7#"-([I`Nx%F>F;#"-.xey]BF6F?#".,at3\l#F6FB#"-.fLk*o)F>FF#
!-jcz/dOFIFJ#"-(z2zS'HF(FM#!.j%f'*HPBF6FP#!-ZnlXc=F(FS#!->c_ilrF>FW#!-fO%)e5&*F
(Fen#!.\YO6)eMF(Fhn#!.JKDQ5!oF(F[o#!.@L')e9X&F(F^o#!-@%H)zgwF(Fao#!-P:7l16FIFdo
#"**>N#H)FasFgo#"-V:+MCVF(Fjo#"-.;&y.t"F>F^p#".([\wJ$\'F(Fap#"-R_;">()*F(Fdp#!.
*3#Q>$o6F(Fgp#".dOE(*Rj#F(Fjp#"-<[_KYQF>F^q#!-V!*o3MOF>Faq#"-8p_ap")F6Fdq#!-^Xl
3UnF(Fhq#"-jKl3<<F(F[r#"-^^b(3J)F(F^r#".(z9xKv=F(*(F%FCF/F3F)F3#!-Rje0FuF6*(F%F
3F/FCF)F3#",6[YtK%",+++++%*(F%F3F/F3F)FC#!-pH(*[CJF>*(F%FCF/F3F,F3#!.R,`>$[9F6*
(F%F3F/FCF,F3#".LjP(yg>F(*(F%F3F/F3F,FC#!-nCXT$)pF(*(F%FCF)F3F,F3#"-Jy.`'\%F6*(
F%F3F)FCF,F3#!.P$4lok8F6*(F%F3F)F3F,FC#!.4sDzbZ"F(*(F/FCF)F3F,F3#!-2*=S*obF6*(F
/F3F)FCF,F3#"-L)o]j"yF(*(F/F3F)F3F,FC#",2>1XU"Fa[l*&F%FeqF/F3#"..u(GQTGF(*&F%FC
F/FC#!-`^V@`sF6*&F%FeqF)F3#"-xij\[LFI*&F%FCF)FC#".d))eXP."F6*&F%FeqF,F3#".L['ei
)H#F(*&F%FCF,FC#!.p'*f#pH8F6*&F%F3F/Feq#"-6S?/vKF(*&F%F3F)Feq#!-f&yF#4bF6*&F%F3
F,Feq#!-h2PR!H#FI*&F/FeqF)F3#!*2Gs,$"*++++)*&F/FCF)FC#!-8&)=%G["F>*&F/FeqF,F3#!
,6u(RWIFZ*&F/FCF,FC#!,.,!>SjF6*&F/F3F)Feq#!**["z:&"+++++D*&F/F3F,Feq#"-nla3g?F(
*&F)FeqF,F3#!-nm%\(ecF(*&F)FCF,FC#",r%pj\CF]p*&F,FeqF)F3#"-HS+;C?FI*$F%""%#!,xo
PBe(Fd`l*$F/F\fl#!,rh6dQ"FI*$F)F\fl#!,rnf9m*FZ*$F,F\fl#!,>ukQ9"F(#!-"*o(4#RBF>F
3,do!""F3%"zG#")r)H$G")+++]**F\glF3F%F3F/F3F)F3#"$6'"(++D"**F\glF3F%F3F/F3F,F3#
!*8#f'>#"*++++#**F\glF3F%F3F)F3F,F3#"+`OqWJ"+++++5**F\glF3F/F3F)F3F,F3#!*T'R[6"
*++++&*(F\glF3F%F3F/F3#"*n`UZ"Fggl*(F\glF3F%F3F)F3#!*2-9j&F[hl*(F\glF3F%F3F,F3#
!).Z^f")++DJ*(F\glF3F/F3F)F3#")h7MYF_gl*(F\glF3F/F3F,F3#"(p&>QF[hl*(F\glF3F)F3F
,F3#!+L&*o5:F[hl*(F\glF3F%FCF/F3#!)2aL]"*+++]#*(F\glF3F%FCF)F3#!)tb%y$"*+++D"*(
F\glF3F%FCF,F3#"+deU#G#F[hl*(F\glF3F%F3F/FC#"*$)R&>7F[hl*(F\glF3F%F3F)FC#!**pot
;F_hl*(F\glF3F%F3F,FC#!*fSq6(F[hl*(F\glF3F/FCF)F3#!*f*RZ9F[hl*(F\glF3F/FCF,F3#"
*$ek'3$F_hl*(F\glF3F/F3F)FC#!)jrX[F[hl*(F\glF3F/F3F,FC#")"z`7(F[hl*(F\glF3F)FCF
,F3#"*fTt"HFfil*(F\glF3F,FCF)F3#!*Z"*o))*F[hl*&F\glF3F%F3#!*z!oD*)F[hl*&F\glF3F
)F3#!+x-XT6F[hl*&F\glF3F,F3#!)t\77Fggl*&F\glF3F/F3#!*zn&f9F[hl*&F\glF3F%FC#!)f`
yc"*++++"*&F\glF3F/FC#"(JL^"")+++S*&F\glF3F)FC#"'jrg")+++5*&F\glF3F,FC#")H"Qr&F
h\m*&F\glF3F%Feq#"("3d^F[hl*&F\glF3F/Feq#!)$Gj%))F[hl*&F\glF3F)Feq#!)RA'>#Fggl*
&F\glF3F,Feq#!*>*)Rh"Fggl6",
I/C_toa_46_w_satw,6#>%)symbolicGF366%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_
V0G%#_VG%"iG%#M1G%#vvG%"HG%"bG%&countG%"CG%%adjHG%%detHG%"SG%#ddG%$eqsG6"F`^mC5
>6$8$8%6$7#%"MG7#7$"#eF3@%/9$F3>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG
6$-%#opG6#&F``m6#8,w,6$F)F,F`^m6$%)operatorG%&arrowGF`^m-&T'6#T%6#,&Fi`mF3*&,&9
%F3F[glF3F3&&T#Fdbm6#F3F3F3F`^mF`^m6(Fh^mF``mF__mF[bmFg^mF_`m6#FC6$7'Q!F`^mF[gl
"#R"#u"#O7'FccmF[glFdcm"#XFfcm/F[bm;F3-%%nopsG6#F_`m>F[am7#-F^am6$-%'rndMatG6#F
famFicm>8--%(convertG6$&F[amF^cmI'VectorG6$FcamFdam>8.7'F3F%F/F)F,>6%8/80816%""
!FfemFfem?(F[bmF3F3""&%%trueGC&>82-I$<,>GFdam6%-I$<|gr>GFdam6%&Ffdm6#,&FdemF3F3
F3&Ffdm6#,&FdemF3FCF3&Ffdm6#,&FdemF3FeqF3-Fafm6%Fffm&Ffdm6#,&FdemF3F\flF3&Ffdm6
#,&FdemF3FhemF3-Fafm6%FifmFagm&Ffdm6#,&FdemF3""'F3>Fbem,&FbemF3*&&F^emFjamF3F\f
mF3F3>Fcem,&FcemF3*&&Ffdm6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GFdemF3F]hmF3F3>
Fdem,&FdemF3F_imF3>83-%$adjG6#Fbem>84-&I.LinearAlgebraG6$FcamFdam6#_F\jm%,Deter
minantGFgim>85&Ffdm6#-Fdhm6%7#-F[im6#;F3F_imF`imFdem>Fbjm)-F^fm6%-Fafm6%&FbjmF^
cm&Fbjm6#FC&Fbjm6#Feq-Fafm6%&Fbjm6#F\fl&Fbjm6#Fhem&Fbjm6#Figm-Fafm6%&Fbjm6#F^im
&Fbjm6#"")&Fbjm6#F_im%#%TG>86&Ffdm6#-Fdhm6%7#-F[im6#;"#5"#8F`imFdem>877$-F^am6$
,&-I".G6$FcamFdam6$,&-F[^n6$)&Fbjm6$;F`^mF`^mF[bmFg\nFdimF3-F[^n6$,$)FcemFg\nFC
FdimF3Fb^nF3*&&Fi\nFjamF3FiimF3F[gl/F[bm;F3Feq,&-F[^n6%Fh^nFdimFcemF3*&&Fi\nFi[
nF3FiimF3F[gl>Fe]n7$-Fgam6#Fe]n,&*&F\glF3FiimF3F3F[glF3>8'-%$mapG6$%'expandGFe]
n@$0Fi`mF3OFi_n>8(-%&minusG6$-%'indetsG6#Fi_n-Fg`n6#F[am>6$8)8*-%,poly2matrixG6
$Fi_nFb`n>8+-%$srtG6$F^an-%%tdegG6#-Fgam6#Fb`n6%7$%#cfG-%/permuteColumnsG6%F]an
F^anFcanF_`mF``mF`^mF`^mF`^m6#Ffem6=7'FccmF[gl"#;FigmFfcm7'FccmF[glFeq"#L"#V7'F
ccmF[glFeqF_imFhcm7'FccmF[glF^im"#&*Fhbn7'FccmF[glF^im"#dFhbn7'FccmF[glFeq"#IFh
bn7'FccmF[glFeq"#BFhbn7'FccmF[glFeq"#DFhbn7'FccmF[glFeqFd\nFd\n7'FccmF[glF^im"$
G"Fhbn7'FccmF[glF^im"#@Fhbn7'FccmF[glF^im"#SFhbn7'FccmF[glF^imFacnFhbn7'FccmF[g
lFeqFebnFhbn7'FccmF[glFeqFdcmFhbn7'FccmF[glFeq"#EFhbn7'FccmF[glFeq"#lFhbn7'Fccm
F[glFeq"#HFhbn7'FccmF[glFeq"#'*Fhbn7'FccmF[glFeq"#GFhbn7'FccmF[glFeq"#CFhbn7'Fc
cmF[glFeqFjcnFhcm7'FccmF[glFacn"#K"#_7'FccmF[glFeq"#QFhbn7'FccmF[glFeqFfcmFhbnF
fbn7'FccmF[glFeq"#`"#JF`^m
