M7R0
I/F_toa_55_w_sat7(,\r%"vG#"-@a;jh9"-+++++]%"xG#!+.Tcup"-+++++5%"uG#"-Vs)yV-%F(%
"yG#!,r!yCe8"-++++]7%"wG#"-ZR&Rf)GF(*(F4"""F%F8F-F8#"-hQT;$["F(*(F)F8F%F8F-F8#!
.j]:'pd8".++++++"*(F0F8F%F8F-F8#!-(Q95<K#F,*(F)F8F4F8F-F8#".^`8BD\%F>*(F0F8F4F8
F-F8#!+Hx?MD"*+Dcw**(F0F8F)F8F-F8#!-$ze6z.)"-+++++D*(F)F8F4F8F%F8#!,xQ9v7*",+++
+D'*(F0F8F4F8F%F8#"-n(e#z%y"FL*(F0F8F)F8F%F8#"-<hxi5PF(*(F0F8F)F8F4F8#!-\!Qx(49
",+++++&*$F-""##!.BMK7c%=F>*&F-F8F%F8#"-BQca"\#FL*&F-F8F4F8#!-**ehH`6FP*&F-F8F)
F8#!-Hl:52<"-+++++?*&F-F8F0F8#"-4*[#QmJF,*$F%Ffn#!,B<^*y>F3*&F%F8F4F8#!-,oU$f!H
F(*&F%F8F)F8#!-4$33Vu#Fbo*&F%F8F0F8#!-hA!RXG#F(*$F4Ffn#!-fzu.$p#F>*&F4F8F)F8#".
R)z>RD6F>*&F4F8F0F8#"-6q)R#p#*F(*$F)Ffn#"-Tmjq)="FZ*&F)F8F0F8#!-$34(*G<"F(*$F0F
fn#!."\Qb,q?F>*&F%F8F-Ffn#"-4#[==(eFL*&F4F8F-Ffn#!,")fc=.$FP*&F)F8F-Ffn#"-t(H$y
<bFbo*&F0F8F-Ffn#"-(R)G3YVF3*&F%FfnF-F8#!,r$>*=!R",+++++%*&F4FfnF-F8#"-z3e*f\)F
(*&F)FfnF-F8#!-*4d7<3%Fbo*&F0FfnF-F8#!,ju!Q:T",++++]#*&F4F8F%Ffn#"-VQY[&)QF>*&F
)F8F%Ffn#"-dQ?l6LFL*&F0F8F%Ffn#!,,Y[BO#FL*&F4FfnF%F8#!-xa,KBPF>*&F)FfnF%F8#!,V0
@D*yFbo*&F0FfnF%F8#"-H%>9oF(F>*&F)F8F4Ffn#"-@Q*['RGFL*&F0F8F4Ffn#!-^6O,GuFL*&F)
FfnF4F8#!.fG)e=CAF>*&F0FfnF4F8#".r-CogZ#F>*&F0F8F)Ffn#"."*H!fm\9F(*&F0FfnF)F8#"
-nM$*\%=*F>*$F-""$#!.Fz<4&e@F>*$F%Fcu#",d:$f%y)F>*$F4Fcu#"-x6I")onF>*$F)Fcu#!.Z
*\D!yG"F>*$F0Fcu#",FUCGt$F,#!-BbgNB6FLF8,\rF%#"-(*=e)QX$F>F)#"-n7Ak&="FboF-#".H
Sw?$Q_F>F0#!.dW)y;i5F(F4#"."zbil&\%F>F7#"-FN59J6F,F;#!-`<X$\9$FboF?#!-2'fa'f7",
+++]7$FB#".f%)*\M>EF>FE#!.4GlaZV"F(FI#",tej)*=#F(FM#!,2/H&4xFZFQ#"-$fuU%*Q"F(FT
#"-psUgoUF(FW#",L7DQ]"FLFen#!-4i8YTxF(Fin#!-FX*Q&GYF(F\o#!.J+x%)=3"FLF_o#!-jR'[
-P&F(Fco#"-By">%*p)F(Ffo#!,T5/@0%F,Fio#!,z;%H?vFewF\p#"+")Qh!R#FewF_p#!-$3i+6^$
FLFbp#!.6e0j2,"F(Fep#"-pazs!R"FPFhp#".f[9)Ru9F(F[q#",>%*z(=&*FZF^q#!+2&=Wl""+++
+DJFaq#!,RnZNg'F,Fdq#"-2T>PkCFPFgq#!-(\)R!pI%F(Fjq#".HIz`pj"F>F]r#".nMMiPA$F(F`
r#!.xpP"Go9F>Fdr#"-89ow(*=FZFgr#"-8IEAQEF>Fjr#!,@I)obH"++++]iF^s#"-p>)pna*F>Fas
#",xCwj>%FPFds#"-"zW8A]"FLFgs#!,>+#zRZFboFjs#!-$4o*=jqF>F]t#".8^xB]t"F>F`t#!,([
KGuUF3Fct#!.Vxb5oD"FLFft#!.nP2pd^#F>Fit#".$Q8Ok"3#F>F\u#",())eVULF3F_u#"-.<BgGU
F>Fbu#!.zB8cL"QF>Ffu#"-F[,L;LF>Fiu#".\-%3fx;F>F\v#!-2!\fp*>FboF_v#"-Bmp2S%)F(#!
,<:LW&[F]sF8,\rF%#!+xc!>?""+++++!)F)#!-2yi!48$FboF-#!.(pUe)Hx"F>F0#"-4/g8&*=F(F
4#!-R2!)*fw%FboF7#!,"4jaeXFLF;#!-2(4>Q;"F>F?#".dLMpUB"F(FB#",jFr_s&FboFE#"-RrNJ
@HFLFI#",.`f]?&F3FM#"-z6+J*R"F(FQ#!-Z<[!)3BF(FT#!+HMW,iFZFW#!,*QuRH8FewFen#!->>
HVwQF(Fin#".PWz"pL5F>F\o#!,L`q)p`FboF_o#",$*f8Ad$FPFco#"-,6oOr\F(Ffo#!,^yI8Z*F>
Fio#"-8cK>:EF3F\p#"-j+fLM&*F>F_p#!,Va'H%H"F(Fbp#",H8*4'y$FPFep#!-BmMg%R%F>Fhp#"
-BsjR_;FLF[q#"+\l6SI",+++++#F^q#","[tyi$)F(Faq#",,D6%*R#F>Fdq#!-nn&>KF#F3Fgq#"+
P3@`oFZFjq#!-4tc1y@F>F]r#!-p4]"*zyFLF`r#"-t&GB6U)F>Fdr#!-dm@U=#)F(Fgr#!,x*z,RKF
boFjr#"-P5k%QR"FPF^s#!-TZ<p!y&F>Fas#!,FB*\z]F(Fds#!+@lk)Q""+++++DFgs#",2*eCh<F>
Fjs#"-Tvf2\>F>F]t#!..21z*\5F>F`t#"-R:EIMAFLFct#"-jQUTF!*F(Fft#"-**4bSwSF>Fit#!-
H@*GG`*F>F\u#!-B.)>!*z"FLF_u#!-\vw&>;%F>Fbu#".**\?$=H;F>Ffu#!-x%e$G(3#F>Fiu#!-4
%=F^L(F>F\v#!-<wjS#H"F>F_v#!,*)3!RbkF,#",RR]qT$FewF8,\rF%#"-x"p`<A#F(F)#",R_]&y
fF,F-#!-,jg`3RF(F0#",@`8BN$FewF4#"-6k,J!R"F(F7#!,*[+Ji@FZF;#!,xCf04#F,F?#!-Z+M6
'Q&FLFB#".HD9P2`"F(FE#!,4sq5A$",+++Dc"FI#!-T)H0%>gF3FM#!+(GJ_5*",++++D"FQ#"-Her
+f9F3FT#"-R;8'=+"FLFW#!-Ht')H!y(FLFen#!+V<IcB"+++]i:Fin#"-\Byd!y(F(F\o#!-HQfAt>
F(F_o#"+\/Z%Q&FaflFco#"-ZGTOuxFLFfo#!,f1GQN&F(Fio#!-8.`*3(>FLF\p#!.H5N'*y\"F(F_
p#"*2cCt%"++]7`>Fbp#!+"GO]T&FZFep#"-"*)yQTB&F(Fhp#"+rbHTtFaflF[q#",hL6>K#F]sF^q
#!,L,)3fUF3Faq#!-V2m?UDF,Fdq#"-,GFEAQFLFgq#!+Fk'zN&FLFjq#".pIp>!47F(F]r#"-<LFFH
bFLF`r#!-<PR'RY%F(Fdr#",>@TrD$FZFgr#!.<@SK-F"F(Fjr#!+tQ7\&)F]sF^s#"-4Nw8.;F(Fas
#"-rV\BeHFLFds#!+.ox`NFLFgs#!,HQ]3b#F,Fjs#!,8f/wW$F(F]t#"-$Hs.Im#F(F`t#",nNq%e5
FaflFct#!-.!GB6l"F3Fft#!-Fq(4u=&F(Fit#"..Pj9&p6F(F\u#".LJ!40[5FLF_u#"-.9#[&\oF(
Fbu#!-p-UUYgF(Ffu#",2NlU+$F(Fiu#"-H/T!)z5F(F\v#!,fpe@z&F,F_v#!,P>4mO)FL#!,()G^P
q$FZF8,hz*(F-FfnF%F8F4F8#!-Rje0FuF(*(F-F8F%FfnF4F8#",6[YtK%Fcr*(F-F8F%F8F4Ffn#!
-pH(*[CJFL*(F-FfnF%F8F)F8#!.R,`>$[9F(*(F-F8F%FfnF)F8#".LjP(yg>F>*(F-F8F%F8F)Ffn
#!-nCXT$)pF>*(F-FfnF%F8F0F8#!-J"\K;F%F3*(F-F8F%FfnF0F8#"-z0;'*4YF(*(F-F8F%F8F0F
fn#"-<?*4rZ'FL*(F-FfnF4F8F)F8#"-Jy.`'\%F(*(F-F8F4FfnF)F8#!.P$4lok8F(*(F-F8F4F8F
)Ffn#!.4sDzbZ"F>*(F-FfnF4F8F0F8#!.*[Cy%[W"FL*(F-F8F4FfnF0F8#!-H'Q'3NCF(*(F-F8F4
F8F0Ffn#"-(G&)f(GEFP*(F-FfnF)F8F0F8#!,(H*\0K)FZ*(F-F8F)FfnF0F8#".PSndB^"FL*(F-F
8F)F8F0Ffn#"-">d$e1;F3*(F%FfnF4F8F)F8#!-2*=S*obF(*(F%F8F4FfnF)F8#"-L)o]j"yF>*(F
%F8F4F8F)Ffn#",2>1XU"Fbal*(F%FfnF4F8F0F8#!,\]S&*G"F,*(F%F8F4FfnF0F8#",BthnA$FP*
(F%F8F4F8F0Ffn#!-T%ez)GCF3*(F%FfnF)F8F0F8#!-4k()*[2'F(*(F%F8F)FfnF0F8#!,^&QK"z"
F,*(F%F8F)F8F0Ffn#"+(*[\Q7F]s*(F4FfnF)F8F0F8#".z1<9T1"F(*(F4F8F)FfnF0F8#!-p-vTR
?F,*(F4F8F)F8F0Ffn#!,@*=X*f"FZF%#"-T&4M$*3"FboF)#".Z74`!*)RF>F-#!-^&Gx/l"FboF0#
!,(fA$f#HFbalF4#".jybsaN#F>**F-F8F%F8F4F8F)F8#!-T@\V`9F,**F-F8F%F8F4F8F0F8#".4?
S$\$*>F(**F-F8F%F8F)F8F0F8#"-`c_&Gh(F(**F-F8F4F8F)F8F0F8#"-L\Arf6FZ**F%F8F4F8F)
F8F0F8#!-([p&pVGF(F7#!,tANVN"FbalF;#"-jO^1K#)F>F?#!+$=S=^)",+++++"FB#".B#)3p-e$
F>FE#!+p@*ee#F]clFI#!,Jbya%fFc[lFM#"-8E3L`jF3FQ#!-n<#[(G5F3FT#"-j4>sLwFLFW#!.@r
H%*oX"F(Fen#".^:2DrX"F(Fin#!+x5,*>#"+++++?F\o#!-j%y)o-8F(F_o#!-ZR17elF,Fco#",>S
NYT&FbalFfo#!,Vp8dq$FLFio#!-()\\-PCF3F\p#!-f\kSOZF(F_p#",.q*o8aF3Fbp#!.\R%Hw)R$
F>Fep#!.r^x))o."F3Fhp#".PLS#3(o"F(F[q#!.6vwij)[F>F^q#".FerwOQ"FLFaq#!-"Gc4eg&FL
Fdq#!-8&*p1_'*F>Fgq#!-h7yfF&)F>Fjq#",RTU!ytFewF]r#"+F$G5k*FLF`r#",t!\YIbF,Fdr#"
,z>h4h$F,Fgr#"-tH2?4=FewFjr#"-pU^13CFLF^s#"-Zk$3,6#FLFas#!-$Qnhb6"FboFds#"-*yEx
I%>F(Fgs#",*ei9s^FbalFjs#".n&)4+!4;F>F]t#!.Fnc)z<;F>F`t#!+"o7,M#"+++]7yFct#!,Bl
S:;)FLFft#"-Vu[&4c'F>Fit#"..GS+9&>F>F\u#!-hPNcBAFPF_u#"-f>Y,&o*FboFbu#!-@2:aXLF
(Ffu#",(H3t_5F3Fiu#",`QjxD#FewF\v#"-r,.0'Q&F(F_v#!,xQGPh"F,#!,*>TuXBFPF8*&F-F8F
%Fcu#"-6S?/vKF>*&F-F8F4Fcu#!-f&yF#4bF(*&F-F8F)Fcu#!-h2PR!H#Fbo*&F-F8F0Fcu#",r"H
%>"GF]s*&F%FcuF4F8#!*2Gs,$"*++++)*&F%FfnF4Ffn#!-8&)=%G["FL*&F%FcuF)F8#!,6u(RWIF
3*&F%FfnF)Ffn#!,.,!>SjF(*&F%FcuF0F8#!+@.(p&GFZ*&F%FfnF0Ffn#!,h$>p#>%FL*&F%F8F4F
cu#!**["z:&F]cl*&F%F8F)Fcu#"-nla3g?F>*&F%F8F0Fcu#!,ty*Gz\FP*&F4FcuF)F8#!-nm%\(e
cF>*&F4FfnF)Ffn#",r%pj\CFffl*&F4FcuF0F8#".dJ-#)eN"F(*&F4FfnF0Ffn#!-([&oLkYFL*&F
4F8F)Fcu#"-HS+;C?Fbo*&F4F8F0Fcu#!,")3cJ"QF]s*&F)FcuF0F8#!,LCFT\(F,*&F)FfnF0Ffn#
!-(p)>vTCFP*&F)F8F0Fcu#"+@J$)4[F]s*&F-FcuF%F8#"..u(GQTGF>*&F-FfnF%Ffn#!-`^V@`sF
(*&F-FcuF4F8#"-xij\[LFbo*&F-FfnF4Ffn#".d))eXP."F(*&F-FcuF)F8#".L['ei)H#F>*&F-Ff
nF)Ffn#!.p'*f#pH8F(*&F-FcuF0F8#"-R)39'\LF,*&F-FfnF0Ffn#!-")=.TXxFL*$F-""%#!,xoP
Be(Fcr*$F%Fj_n#!,rh6dQ"Fbo*$F4Fj_n#!,rnf9m*F3*$F)Fj_n#!,>ukQ9"F>*$F0Fj_n#"+"*=/
5MFP,^r!""F8%"zG#")r)H$G")+++]**F[anF8F-F8F%F8F4F8#"$6'"(++D"**F[anF8F-F8F%F8F)
F8#!*8#f'>#"*++++#**F[anF8F-F8F%F8F0F8#"*Vv=;%"*++++&**F[anF8F-F8F4F8F)F8#"+`Oq
WJ"+++++5**F[anF8F-F8F4F8F0F8#!)><DEF^an**F[anF8F-F8F)F8F0F8#!*RI&*f$"*+++D"**F
[anF8F%F8F4F8F)F8#!*T'R[6Fjan**F[anF8F%F8F4F8F0F8#!)6L*H&Fjan**F[anF8F%F8F)F8F0
F8#"*@I#e5Febn**F[anF8F4F8F)F8F0F8#!)RET"*F^an*(F[anF8F%F8F-F8#"*n`UZ"Ffan*(F[a
nF8F4F8F-F8#!*2-9j&F^bn*(F[anF8F)F8F-F8#!).Z^f")++DJ*(F[anF8F-F8F0F8#"+B=)4+"Fj
an*(F[anF8F4F8F%F8#")h7MYF^an*(F[anF8F%F8F)F8#"(p&>QF^bn*(F[anF8F%F8F0F8#"("QNc
Fjan*(F[anF8F4F8F)F8#!+L&*o5:F^bn*(F[anF8F4F8F0F8#"*,nYR%"*+++]#*(F[anF8F)F8F0F
8#"*H2=z'Fjan*(F[anF8F-FfnF%F8#!)2aL]F^en*(F[anF8F-FfnF4F8#!)tb%y$Febn*(F[anF8F
-FfnF)F8#"+deU#G#F^bn*(F[anF8F-FfnF0F8#!)Z5*e&")++]i*(F[anF8F-F8F%Ffn#"*$)R&>7F
^bn*(F[anF8F-F8F4Ffn#!**pot;Fjan*(F[anF8F-F8F)Ffn#!*fSq6(F^bn*(F[anF8F-F8F0Ffn#
"*V*G)p"Febn*(F[anF8F%FfnF4F8#!*f*RZ9F^bn*(F[anF8F%FfnF)F8#"*$ek'3$Fjan*(F[anF8
F%FfnF0F8#!*x7NB"F^en*(F[anF8F%F8F4Ffn#!)jrX[F^bn*(F[anF8F%F8F)Ffn#")"z`7(F^bn*
(F[anF8F%F8F0Ffn#!*d[UG(F^bn*(F[anF8F4FfnF)F8#"*fTt"HF^en*(F[anF8F4FfnF0F8#!)*)
R)=""*++++"*(F[anF8F4F8F)Ffn#!*Z"*o))*F^bn*(F[anF8F4F8F0Ffn#"*H<yV%F^bn*(F[anF8
F)FfnF0F8#")6()=>F[dn*(F[anF8F)F8F0Ffn#"*<NTP)F^bn*&F[anF8F%F8#!*zn&f9F^bn*&F[a
nF8F)F8#!)t\77Ffan*&F[anF8F-F8#!*z!oD*)F^bn*&F[anF8F0F8#!*zepC"Fjan*&F[anF8F4F8
#!+x-XT6F^bn*&F[anF8F-Ffn#!)f`ycFchn*&F[anF8F%Ffn#"(JL^"")+++S*&F[anF8F4Ffn#"'j
rg")+++5*&F[anF8F)Ffn#")H"Qr&Fchn*&F[anF8F0Ffn#!*(Rg&4*F^bn*&F[anF8F-Fcu#"("3d^
F^bn*&F[anF8F%Fcu#!)$Gj%))F^bn*&F[anF8F4Fcu#!)RA'>#Ffan*&F[anF8F)Fcu#!*>*)Rh"Ff
an*&F[anF8F0Fcu#!*^5#oFFjan6",
I/C_toa_55_w_satw,6#>%)symbolicGF866%&_nameG%&_sizeG%#_AG%"iG%#M1G%#vvG%"HG%"bG
%"kG%"CG%%adjHG%%detHG%"SG%#ddG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F_\oC5>6$8
$8%6$7#%"MG7#7$"#rF8@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F_^o6#8'F_\o/Ff_o;F8-%%
nopsG6#F^^o>F[_o7#-F^_o6$-I'MatrixG6$%*protectedG%(_syslibG6$Fc_ow,6$F)F0F_\o6$
%)operatorG%&arrowGF_\o-&T'6#T%6#,&Fh^oF8*&,&9%F8Fj`nF8F8&&T#F^ao6#F8F8F8F_\oF_
\o6(Fg\oF_^oFi\oFf_oFf\oF^^o6#Ffn6$7'Q!F_\oFj`n"#P"#s"#O7'F]boFj`nF^bo"#VF`boFg
_o>8(-%(convertG6$&F[_oFhaoI'VectorG6$Fc`oFd`o>8)7(F8F-F%F4F)F0>6%8*8+8,6%Fi^oF
i^oFi^o?(Ff_oF8F8""'%%trueGC&>8--I$<,>GFd`o6%-I$<|gr>GFd`o6%&Fdbo6#,&FbcoF8F8F8
&Fdbo6#,&FbcoF8FfnF8&Fdbo6#,&FbcoF8FcuF8-F^do6%Fcdo&Fdbo6#,&FbcoF8Fj_nF8&Fdbo6#
,&FbcoF8""&F8-F^do6%FfdoF^eo&Fdbo6#,&FbcoF8FecoF8>F`co,&F`coF8*&&F\coFe_oF8Fico
F8F8>Faco,&FacoF8*&&Fdbo6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GFbcoF8FjeoF8F8>F
bco,&FbcoF8F\goF8>8.-&I.LinearAlgebraG6$Fc`oFd`o6#%(AdjointG6#F`co>8/-&Fdgo6#%,
DeterminantGFhgo>80&Fdbo6#-Fafo6%7#-Fhfo6#;F8"#7F]goFbco>F`ho)-F[do6&-F^do6%&F`
hoFhao&F`ho6#Ffn&F`ho6#Fcu-F^do6%&F`ho6#Fj_n&F`ho6#Faeo&F`ho6#Feco-F^do6%&F`ho6
#F[go&F`ho6#"")&F`ho6#F\go-F^do6%&F`ho6#"#5&F`ho6#"#6&F`ho6#Fiho%#%TG>81&Fdbo6#
-Fafo6%7#-Fhfo6#;"#8"#<F]goFbco>827$-F^_o6$,&-I".G6$Fc`oFd`o6$,&-Fd\p6$)&F`ho6$
;F_\oF_\oFf_oF`[pFagoF8-Fd\p6$,$)FacoF`[pFfnFagoF8F[]pF8*&&Fb[pFe_oF8FjgoF8Fj`n
/Ff_o;F8Fj_n,&-Fd\p6%Fa]pFagoFacoF8*&&Fb[pFjioF8FjgoF8Fj`n>F^\p7$&F^\pF_\o,&*&F
[anF8FjgoF8F8Fj`nF8>83-%$mapG6$%'expandGF^\p@$Fg^oOFa^p>84-%&minusG6$-%'indetsG
6#Fa^p-F^_p6#F[_o>6$8586-%,poly2matrixG6$Fa^pFi^p>87-%$srtG6$Fe_p-%%tdegG6#&Fi^
pF_\o6&7#-%/permuteColumnsG6%Fd_pFe_pFj_pFj_pF^^oF_^oF_\oF_\oF_\o6#Fi^o6=7'F]bo
Fj`n"#;FecoF`bo7'F]boFj`nFcu"#LFbbo7'F]boFj`nFcuF\go"#X7'F]boFj`nF[go"#bFbbo7'F
]boFj`nF[go"#$*Fbbo7'F]boFj`nFcu"#IFbbo7'F]boFj`nFcu"#EFbbo7'F]boFj`nFcu"#@Fbbo
7'F]boFj`nFcuFcjoFcjo7'F]boFj`nF[go"#')Fbbo7'F]boFj`nF[goFhapFbbo7'F]boFj`nF[go
F`boFbbo7'F]boFj`nF[go"#:Fbbo7'F]boFj`nFcu"#NFbbo7'F]boFj`nFcu"#RFbbo7'F]boFj`n
Fcu"#BFbbo7'F]boFj`nFcu"#wFbbo7'F]boFj`nFcu"#DFbbo7'F]boFj`nFcuFbapFbboFeap7'F]
boFj`nFcu"#CFbbo7'F]boFj`nFcuFcbpF^ap7'F]boFj`n"#A"#J"#_7'F]boFj`nFcu"#QFbbo7'F
]boFj`nFcuF`boFbbo7'F]boFj`nFcuF`cpFbbo7'F]boFj`nFcu"#^F`cpF_\o
