M7R0
I)F_toa_467',bo%"vG#".JH)G7xF".++++++"%"xG#".4o\I/2#F(%"yG#!-6fDL6=F(%"wG#"-*pT
)>?:F(*$F%""##"+VFy_$)F(*&F%"""F/F7#!-Tz\<tD"-+++++?*&F%F7F)F7#!.r&*zin`"F(*&F%
F7F,F7#"-Ve#eUV#F(*$F/F3#!,dco=.&F(*&F/F7F)F7#!-H"Q)z'=""-+++++5*&F/F7F,F7#"-x/
+446"-++++]7*$F)F3#!->Hc\YmF(*&F)F7F,F7#"-B2.(3'z"-+++++]*$F,F3#"-t%*G$>7$FR*(F
%F7F/F7F)F7#"-ZO8+aRFR*(F%F7F/F7F,F7#!,nk5ol%",++++D'*(F%F7F)F7F,F7#"-Bu@vR5"-+
++++D*(F/F7F)F7F,F7#!-Bfi.bSFR*&F%F3F/F7#"-87/oPXFjn*&F%F3F)F7#!-`FJL!3"Fjn*&F%
F3F,F7#!,^5S0D)FR*&F%F7F/F3#!-8\%Q,T"Fjn*&F%F7F)F3#",(o09aC",++++D"*&F%F7F,F3#"
-,<wQ/NFR*&F/F3F)F7#"-VsUK<5Fjn*&F/F3F,F7#",\tk:5#FR*&F/F7F)F3#!,<tug$HFjn*&F/F
7F,F3#!,h;&[(>#",+++++&*&F)F3F,F7#!,T;**R-%FK*&F)F7F,F3#!-Fi`65bFR#!,nLCf+&F]qF
7*$F%""$#!-8fioy<FG*$F/Fgq#",Baf$ezFR*$F)Fgq#",rXAGb)FG*$F,Fgq#!-jC:&\.#FR,boF%
#",`c7Fi'FKF)#!,ZGIDS(",++++]#F,#!.tbNg/B"FjnF/#",t97?&=FjnF2#!.n:#Rt!3#F(F6#"-
Rw\9vBFRF;#!-4O3:*y#FRF>#"."H@])4,)F(FA#!,t)eMw[FRFD#".")Q[Obf"FRFH#"."=/R(Gr"F
(FL#".@'Hb$Qz#F(FO#".TV*)z?y&F(FS#"-$)f=0bnFjnFV#"-\WFG8OFRFY#"*nRu[&"+++++!)Fg
n#!.Zq3yx^"F(F[o#!-nl'zo:%FjnF^o#!,\cSJ'R",+++]7$Fao#"+,bKO<"+++++]Fdo#!.H22Sn&
[F(Fgo#".r!e"HT1"F(Fjo#!-"G\#GoZFRF^p#!.T0e7#=6F(Fap#!->QWTT?F:Fdp#!,\dS<j'FjnF
gp#!-^ofp\hF(Fjp#!-4'=Zvp'F(F^q#"-2VqilUFjnFaq#",B`Jl\(F(Ffq#".j6'e><:F(Fjq#!-L
nYGLJF(F]r#!-TynD6xF(F`r#!-HgWR!e&F(#"+VNNb'*FfnF7,boF%#"-r"e#G"*fFRF)#"-zLWC*>
&FRF,#!-Ta\w67FRF/#"-,!>ID(GFRF2#"-*3nf#pWFjnF6#!-nvRWm>FGF;#!-z4DD/bFRF>#!-R9]
VnZFKFA#!,@2t))\&FRFD#"+H7^fsF\uFH#"-.fvdC\FGFL#!,.4RO&oFfnFO#!.pbaiR`"FRFS#!-Z
Se*p/*FjnFV#",dT&GOGF\uFY#!->"H$\v()FRFgn#"-pi#ef"[FRF[o#"-"RhIbX"FjnF^o#!-<"*3
xt;FjnFao#!,H0=8#)*FKFdo#"-z"RWo7'FRFgo#"-tU"HEA$FRFjo#",6a>R+"F\uF^p#".L6yvhg"
FRFap#!,xF2l%>FRFdp#!,p`/F(QFfnFgp#"-$p!R*='=FRFjp#",t[nW5%FRF^q#!+(\ctM%FKFaq#
!,p0]!pvFGFfq#!,$eF-$[$FRFjq#"+>lf(G"FRF]r#"+6W")yw",+++++#F`r#!-4!)pDVAFR#!->f
X54BFjnF7,hs*(F%F3F/F7F)F7#!-Rje0FuFR*(F%F7F/F3F)F7#",6[YtK%",+++++%*(F%F7F/F7F
)F3#!-pH(*[CJFjn*(F%F3F/F7F,F7#!.R,`>$[9FR*(F%F7F/F3F,F7#".LjP(yg>F(*(F%F7F/F7F
,F3#!-nCXT$)pF(*(F%F3F)F7F,F7#"-Jy.`'\%FR*(F%F7F)F3F,F7#!.P$4lok8FR*(F%F7F)F7F,
F3#!.4sDzbZ"F(*(F/F3F)F7F,F7#!-2*=S*obFR*(F/F7F)F3F,F7#"-L)o]j"yF(*(F/F7F)F7F,F
3#",2>1XU"Fa[lF%#"+6#\Wf$FfnF)#"-F-'eaN%FKF,#".$oqFD75FjnF/#",nxGFh)FKF2#"-.fLk
*o)FjnF6#!-jcz/dOF:F;#"-(z2zS'HF(F>#!.j%f'*HPBFRFA#!-ZnlXc=F(FD#!->c_ilrFjnFH#!
-fO%)e5&*F(FL#!.\YO6)eMF(FO#!.JKDQ5!oF(FS#!.@L')e9X&F(**F%F7F/F7F)F7F,F7#!-T@\V
`9FGFV#!,P2-`N"Fa[lFY#"-([I`Nx%FjnFgn#"-.xey]BFRF[o#".,at3\l#FRF^o#!-@%H)zgwF(F
ao#!-P:7l16F:Fdo#"**>N#H)FetFgo#"-V:+MCVF(Fjo#"-.;&y.t"FjnF^p#".([\wJ$\'F(Fap#"
-R_;">()*F(Fdp#!.*3#Q>$o6F(Fgp#".dOE(*Rj#F(Fjp#"-<[_KYQFjnF^q#!-V!*o3MOFjnFaq#"
-8p_ap")FR*&F%FgqF/F7#"..u(GQTGF(*&F%F3F/F3#!-`^V@`sFR*&F%FgqF)F7#"-xij\[LF:*&F
%F3F)F3#".d))eXP."FR*&F%FgqF,F7#".L['ei)H#F(*&F%F3F,F3#!.p'*f#pH8FR*&F%F7F/Fgq#
"-6S?/vKF(*&F%F7F)Fgq#!-f&yF#4bFR*&F%F7F,Fgq#!-h2PR!H#F:*&F/FgqF)F7#!*2Gs,$"*++
++)*&F/F3F)F3#!-8&)=%G["Fjn*&F/FgqF,F7#!,6u(RWIFK*&F/F3F,F3#!,.,!>SjFR*&F/F7F)F
gq#!**["z:&"+++++D*&F/F7F,Fgq#"-nla3g?F(*&F)FgqF,F7#!-nm%\(ecF(*&F)F3F,F3#",r%p
j\CF]p*&F)F7F,Fgq#"-HS+;C?F:Ffq#!-^Xl3UnF(Fjq#"-jKl3<<F(F]r#"-^^b(3J)F(F`r#".(z
9xKv=F(#!-"*o(4#RBFjnF7*$F%""%#!,xoPBe(F]\l*$F/F^fl#!,rh6dQ"F:*$F)F^fl#!,rnf9m*
FK*$F,F^fl#!,>ukQ9"F(,doF%#!*z!oD*)"+++++5F)#!+x-XT6F]glF,#!)t\77"*++++#F/#!*zn
&f9F]gl%"zG!""F2#!)f`yc"*++++"F6#"*n`UZ"FbglF;#!*2-9j&F]glF>#!).Z^f")++DJFA#"(J
L^"")+++SFD#")h7MY")+++]FH#"(p&>QF]glFL#"'jrg")+++5FO#!+L&*o5:F]glFS#")H"Qr&Fig
lFV#"$6'"(++D"FY#!*8#f'>#FbglFgn#"+`OqWJF]glF[o#!*T'R[6"*++++&F^o#!)2aL]"*+++]#
Fao#!)tb%y$"*+++D"Fdo#"+deU#G#F]glFgo#"*$)R&>7F]glFjo#!**pot;FiilF^p#!*fSq6(F]g
lFap#!*f*RZ9F]glFdp#"*$ek'3$FiilFgp#!)jrX[F]glFjp#")"z`7(F]glF^q#"*fTt"HF\jlFaq
#!*Z"*o))*F]glFfq#"("3d^F]glFjq#!)$Gj%))F]glF]r#!)RA'>#FbglF`r#!*>*)Rh"Fbgl#")r
)H$GFfhlF76",
I)C_toa_46w,6#>%)symbolicGF766%&_nameG%&_sizeG%#_AG%"iG%#M1G%#vvG%"HG%"bG%"kG%"
CG%%adjHG%%detHG%"SG%#ddG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F^\mC5>6$8$8%6$7
#%"MG7#7$"#eF7@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F^^m6#8'F^\m/Fe_m;F7-%%nopsG6
#F]^m>Fj^m7#-F]_m6$-I'MatrixG6$%*protectedG%(_syslibG6$Fb_mw,6$F)F,F^\m6$%)oper
atorG%&arrowGF^\m-&T'6#T%6#,&Fg^mF7*&,&9%F7FfglF7F7&&T#F]am6#F7F7F7F^\mF^\m6(Ff
\mF^^mFh\mFe_mFe\mF]^m6#F36$7'Q!F^\mFfgl"#P"#s"#O7'F\bmFfglF]bm"#VF_bmFf_m>8(-%
(convertG6$&Fj^mFgamI'VectorG6$Fb`mFc`m>8)7'F7F%F/F)F,>6%8*8+8,6%Fh^mFh^mFh^m?(
Fe_mF7F7""&%%trueGC&>8--I$<,>GFc`m6%-I$<|gr>GFc`m6%&Fcbm6#,&FacmF7F7F7&Fcbm6#,&
FacmF7F3F7&Fcbm6#,&FacmF7FgqF7-F]dm6%Fbdm&Fcbm6#,&FacmF7F^flF7&Fcbm6#,&FacmF7Fd
cmF7-F]dm6%FedmF]em&Fcbm6#,&FacmF7""'F7>F_cm,&F_cmF7*&&F[cmFd_mF7FhcmF7F7>F`cm,
&F`cmF7*&&Fcbm6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GFacmF7FiemF7F7>Facm,&FacmF
7F[gmF7>8.-&I.LinearAlgebraG6$Fb`mFc`m6#%(AdjointG6#F_cm>8/-&Fcgm6#%,Determinan
tGFggm>80&Fcbm6#-F`fm6%7#-Fgfm6#;F7F[gmF\gmFacm>F_hm)-Fjcm6%-F]dm6%&F_hmFgam&F_
hm6#F3&F_hm6#Fgq-F]dm6%&F_hm6#F^fl&F_hm6#Fdcm&F_hm6#Feem-F]dm6%&F_hm6#Fjfm&F_hm
6#"")&F_hm6#F[gm%#%TG>81&Fcbm6#-F`fm6%7#-Fgfm6#;"#5"#8F\gmFacm>827$-F]_m6$,&-I"
.G6$Fb`mFc`m6$,&-Fh[n6$)&F_hm6$;F^\mF^\mFe_mFdjmF`gmF7-Fh[n6$,$)F`cmFdjmF3F`gmF
7F_\nF7*&&FfjmFd_mF7FigmF7Ffgl/Fe_m;F7Fgq,&-Fh[n6%Fe\nF`gmF`cmF7*&&FfjmFfimF7Fi
gmF7Ffgl>Fb[n7$&Fb[nF^\m,&FigmF7FeglFfgl>83-%$mapG6$%'expandGFb[n@$Ff^mOFd]n>84
-%&minusG6$-%'indetsG6#Fd]n-Fa^n6#Fj^m>6$8586-%,poly2matrixG6$Fd]nF\^n>87-%$srt
G6$Fh^n-%%tdegG6#&F\^nF^\m6&7#-%/permuteColumnsG6%Fg^nFh^nF]_nF]_nF]^mF^^mF^\mF
^\mF^\m6#Fh^m6=7'F\bmFfgl"#;FeemF_bm7'F\bmFfglFgq"#LFabm7'F\bmFfglFgqF[gm"#X7'F
\bmFfglFjfm"#bFabm7'F\bmFfglFjfm"#$*Fabm7'F\bmFfglFgq"#IFabm7'F\bmFfglFgq"#BFab
m7'F\bmFfglFgq"#@Fabm7'F\bmFfglFgqFajmFajm7'F\bmFfglFjfm"#')Fabm7'F\bmFfglFjfmF
[anFabm7'F\bmFfglFjfm"#MFabm7'F\bmFfglFjfm"#:Fabm7'F\bmFfglFgq"#NFabm7'F\bmFfgl
Fgq"#RFabm7'F\bmFfglFgq"#AFabm7'F\bmFfglFgq"#dFabm7'F\bmFfglFgq"#DFabm7'F\bmFfg
lFgqFe`nFabm7'F\bmFfglFgq"#CFabmF_bn7'F\bmFfglFgqFganFa`n7'F\bmFfglFian"#J"#_7'
F\bmFfglFgq"#QFabm7'F\bmFfglFgqF_bmFabm7'F\bmFfglFgqFcbnFabm7'F\bmFfglFgq"#^Fcb
nF^\m
