M7R0
I/F_toa_55_w_sat7(,\r%"vG#"-@a;jh9"-+++++]%"xG#!+.Tcup"-+++++5%"uG#"-Vs)yV-%F(%
"yG#!,r!yCe8"-++++]7%"wG#"-ZR&Rf)GF(*$F-""##!.BMK7c%=".++++++"*&F-"""F%F=#"-BQc
a"\#"-+++++D*&F-F=F4F=#!-**ehH`6",++++D'*&F-F=F)F=#!-Hl:52<"-+++++?*&F-F=F0F=#"
-4*[#QmJF,*$F%F8#!,B<^*y>F3*&F%F=F4F=#!-,oU$f!HF(*&F%F=F)F=#!-4$33Vu#FH*&F%F=F0
F=#!-hA!RXG#F(*$F4F8#!-fzu.$p#F;*&F4F=F)F=#".R)z>RD6F;*&F4F=F0F=#"-6q)R#p#*F(*$
F)F8#"-Tmjq)="",+++++&*&F)F=F0F=#!-$34(*G<"F(*$F0F8#!."\Qb,q?F;#!-BbgNB6F@F=*$F
-""$#!.Fz<4&e@F;*$F%Fho#",d:$f%y)F;*$F4Fho#"-x6I")onF;*$F)Fho#!.Z*\D!yG"F;*$F0F
ho#",FUCGt$F,*(F4F=F%F=F-F=#"-hQT;$["F(*(F)F=F%F=F-F=#!.j]:'pd8F;*(F0F=F%F=F-F=
#!-(Q95<K#F,*(F)F=F4F=F-F=#".^`8BD\%F;*(F0F=F4F=F-F=#!+Hx?MD"*+Dcw**(F0F=F)F=F-
F=#!-$ze6z.)F@*(F)F=F4F=F%F=#!,xQ9v7*FD*(F0F=F4F=F%F=#"-n(e#z%y"F@*(F0F=F)F=F%F
=#"-<hxi5PF(*(F0F=F)F=F4F=#!-\!Qx(49F^o*&F%F=F-F8#"-4#[==(eF@*&F4F=F-F8#!,")fc=
.$FD*&F)F=F-F8#"-t(H$y<bFH*&F0F=F-F8#"-(R)G3YVF3*&F%F8F-F=#!,r$>*=!R",+++++%*&F
4F8F-F=#"-z3e*f\)F(*&F)F8F-F=#!-*4d7<3%FH*&F0F8F-F=#!,ju!Q:T",++++]#*&F4F=F%F8#
"-VQY[&)QF;*&F)F=F%F8#"-dQ?l6LF@*&F0F=F%F8#!,,Y[BO#F@*&F4F8F%F=#!-xa,KBPF;*&F)F
8F%F=#!,V0@D*yFH*&F0F8F%F=#"-H%>9oF(F;*&F)F=F4F8#"-@Q*['RGF@*&F0F=F4F8#!-^6O,Gu
F@*&F)F8F4F=#!.fG)e=CAF;*&F0F8F4F=#".r-CogZ#F;*&F0F=F)F8#"."*H!fm\9F(*&F0F8F)F=
#"-nM$*\%=*F;,\rF%#"-(*=e)QX$F;F)#"-n7Ak&="FHF-#".HSw?$Q_F;F0#!.dW)y;i5F(F4#"."
zbil&\%F;F7#!-4i8YTxF(F<#!-FX*Q&GYF(FA#!.J+x%)=3"F@FE#!-jR'[-P&F(FI#"-By">%*p)F
(FL#!,T5/@0%F,FO#!,z;%H?v",+++]7$FR#"+")Qh!R#F]xFU#!-$3i+6^$F@FX#!.6e0j2,"F(Fen
#"-pazs!R"FDFhn#".f[9)Ru9F(F[o#",>%*z(=&*F^oF_o#!+2&=Wl""++++DJFbo#!,RnZNg'F,#!
,<:LW&[F_tF=Fgo#!.zB8cL"QF;F[p#"-F[,L;LF;F^p#".\-%3fx;F;Fap#!-2!\fp*>FHFdp#"-Bm
p2S%)F(Fgp#"-FN59J6F,Fjp#!-`<X$\9$FHF]q#!-2'fa'f7F]xF`q#".f%)*\M>EF;Fcq#!.4GlaZ
V"F(Fgq#",tej)*=#F(Fjq#!,2/H&4xF^oF]r#"-$fuU%*Q"F(F`r#"-psUgoUF(Fcr#",L7DQ]"F@F
fr#"-2T>PkCFDFir#!-(\)R!pI%F(F\s#".HIz`pj"F;F_s#".nMMiPA$F(Fbs#!.xpP"Go9F;Ffs#"
-89ow(*=F^oFis#"-8IEAQEF;F\t#!,@I)obH"++++]iF`t#"-p>)pna*F;Fct#",xCwj>%FDFft#"-
"zW8A]"F@Fit#!,>+#zRZFHF\u#!-$4o*=jqF;F_u#".8^xB]t"F;Fbu#!,([KGuUF3Feu#!.Vxb5oD
"F@Fhu#!.nP2pd^#F;F[v#".$Q8Ok"3#F;F^v#",())eVULF3Fav#"-.<BgGUF;,\rF%#!+xc!>?""+
++++!)F)#!-2yi!48$FHF-#!.(pUe)Hx"F;F0#"-4/g8&*=F(F4#!-R2!)*fw%FHF7#!->>HVwQF(F<
#".PWz"pL5F;FA#!,L`q)p`FHFE#",$*f8Ad$FDFI#"-,6oOr\F(FL#!,^yI8Z*F;FO#"-8cK>:EF3F
R#"-j+fLM&*F;FU#!,Va'H%H"F(FX#",H8*4'y$FDFen#!-BmMg%R%F;Fhn#"-BsjR_;F@F[o#"+\l6
SI",+++++#F_o#","[tyi$)F(Fbo#",,D6%*R#F;#",RR]qT$F]xF=Fgo#".**\?$=H;F;F[p#!-x%e
$G(3#F;F^p#!-4%=F^L(F;Fap#!-<wjS#H"F;Fdp#!,*)3!RbkF,Fgp#!,"4jaeXF@Fjp#!-2(4>Q;"
F;F]q#".dLMpUB"F(F`q#",jFr_s&FHFcq#"-RrNJ@HF@Fgq#",.`f]?&F3Fjq#"-z6+J*R"F(F]r#!
-Z<[!)3BF(F`r#!+HMW,iF^oFcr#!,*QuRH8F]xFfr#!-nn&>KF#F3Fir#"+P3@`oF^oF\s#!-4tc1y
@F;F_s#!-p4]"*zyF@Fbs#"-t&GB6U)F;Ffs#!-dm@U=#)F(Fis#!,x*z,RKFHF\t#"-P5k%QR"FDF`
t#!-TZ<p!y&F;Fct#!,FB*\z]F(Fft#!+@lk)Q""+++++DFit#",2*eCh<F;F\u#"-Tvf2\>F;F_u#!
..21z*\5F;Fbu#"-R:EIMAF@Feu#"-jQUTF!*F(Fhu#"-**4bSwSF;F[v#!-H@*GG`*F;F^v#!-B.)>
!*z"F@Fav#!-\vw&>;%F;,\rF%#"-x"p`<A#F(F)#",R_]&yfF,F-#!-,jg`3RF(F0#",@`8BN$F]xF
4#"-6k,J!R"F(F7#!+V<IcB"+++]i:F<#"-\Byd!y(F(FA#!-HQfAt>F(FE#"+\/Z%Q&",+++Dc"FI#
"-ZGTOuxF@FL#!,f1GQN&F(FO#!-8.`*3(>F@FR#!.H5N'*y\"F(FU#"*2cCt%"++]7`>FX#!+"GO]T
&F^oFen#"-"*)yQTB&F(Fhn#"+rbHTtF`flF[o#",hL6>K#F_tF_o#!,L,)3fUF3Fbo#!-V2m?UDF,#
!,()G^Pq$F^oF=Fgo#!-p-UUYgF(F[p#",2NlU+$F(F^p#"-H/T!)z5F(Fap#!,fpe@z&F,Fdp#!,P>
4mO)F@Fgp#!,*[+Ji@F^oFjp#!,xCf04#F,F]q#!-Z+M6'Q&F@F`q#".HD9P2`"F(Fcq#!,4sq5A$F`
flFgq#!-T)H0%>gF3Fjq#!+(GJ_5*",++++D"F]r#"-Her+f9F3F`r#"-R;8'=+"F@Fcr#!-Ht')H!y
(F@Ffr#"-,GFEAQF@Fir#!+Fk'zN&F@F\s#".pIp>!47F(F_s#"-<LFFHbF@Fbs#!-<PR'RY%F(Ffs#
",>@TrD$F^oFis#!.<@SK-F"F(F\t#!+tQ7\&)F_tF`t#"-4Nw8.;F(Fct#"-rV\BeHF@Fft#!+.ox`
NF@Fit#!,HQ]3b#F,F\u#!,8f/wW$F(F_u#"-$Hs.Im#F(Fbu#",nNq%e5F`flFeu#!-.!GB6l"F3Fh
u#!-Fq(4u=&F(F[v#"..Pj9&p6F(F^v#".LJ!40[5F@Fav#"-.9#[&\oF(,hzF%#"-T&4M$*3"FHF)#
".Z74`!*)RF;F-#!-^&Gx/l"FHF0#!,(fA$f#HF^`lF4#".jybsaN#F;**F-F=F%F=F4F=F)F=#!-T@
\V`9F,**F-F=F%F=F4F=F0F=#".4?S$\$*>F(**F-F=F%F=F)F=F0F=#"-`c_&Gh(F(**F-F=F4F=F)
F=F0F=#"-L\Arf6F^o**F%F=F4F=F)F=F0F=#!-([p&pVGF(*&F-FhoF%F=#"..u(GQTGF;*&F-FhoF
4F=#"-xij\[LFH*&F-FhoF)F=#".L['ei)H#F;*&F-FhoF0F=#"-R)39'\LF,*&F%FhoF-F=#"-6S?/
vKF;*&F%FhoF4F=#!*2Gs,$"*++++)*&F%FhoF)F=#!,6u(RWIF3*&F%FhoF0F=#!+@.(p&GF^o*&F4
FhoF-F=#!-f&yF#4bF(*&F4FhoF%F=#!**["z:&Ficl*&F4FhoF)F=#!-nm%\(ecF;*&F4FhoF0F=#"
.dJ-#)eN"F(*&F)FhoF-F=#!-h2PR!H#FH*&F)FhoF%F=#"-nla3g?F;*&F)FhoF4F=#"-HS+;C?FH*
&F)FhoF0F=#!,LCFT\(F,*&F0FhoF-F=#",r"H%>"GF_t*&F0FhoF%F=#!,ty*Gz\FD*&F0FhoF4F=#
!,")3cJ"QF_t*&F0FhoF)F=#"+@J$)4[F_t*&F-F8F%F8#!-`^V@`sF(*&F-F8F4F8#".d))eXP."F(
*&F-F8F)F8#!.p'*f#pH8F(*&F-F8F0F8#!-")=.TXxF@*&F%F8F4F8#!-8&)=%G["F@*&F%F8F)F8#
!,.,!>SjF(*&F%F8F0F8#!,h$>p#>%F@*&F4F8F)F8#",r%pj\CFbil*&F4F8F0F8#!-([&oLkYF@*&
F)F8F0F8#!-(p)>vTCFDF7#".^:2DrX"F(F<#!+x5,*>#"+++++?FA#!-j%y)o-8F(FE#!-ZR17elF,
FI#",>SNYT&F^`lFL#!,Vp8dq$F@FO#!-()\\-PCF3FR#!-f\kSOZF(FU#",.q*o8aF3FX#!.\R%Hw)
R$F;Fen#!.r^x))o."F3Fhn#".PLS#3(o"F(F[o#!.6vwij)[F;F_o#".FerwOQ"F@Fbo#!-"Gc4eg&
F@*$F-""%#!,xoPBe(Fes*$F%Ffem#!,rh6dQ"FH*$F4Ffem#!,rnf9m*F3*$F)Ffem#!,>ukQ9"F;*
$F0Ffem#"+"*=/5MFDFgo#!-@2:aXLF(F[p#",(H3t_5F3F^p#",`QjxD#F]xFap#"-r,.0'Q&F(Fdp
#!,xQGPh"F,Fgp#!,tANVN"F^`lFjp#"-jO^1K#)F;F]q#!+$=S=^)",+++++"F`q#".B#)3p-e$F;F
cq#!+p@*ee#FiclFgq#!,Jbya%fF_\lFjq#"-8E3L`jF3F]r#!-n<#[(G5F3F`r#"-j4>sLwF@Fcr#!
.@rH%*oX"F(*(F-F8F%F=F4F=#!-Rje0FuF(*(F-F=F%F8F4F=#",6[YtK%Fes*(F-F=F%F=F4F8#!-
pH(*[CJF@*(F-F8F%F=F)F=#!.R,`>$[9F(*(F-F=F%F8F)F=#".LjP(yg>F;*(F-F=F%F=F)F8#!-n
CXT$)pF;*(F-F8F%F=F0F=#!-J"\K;F%F3*(F-F=F%F8F0F=#"-z0;'*4YF(*(F-F=F%F=F0F8#"-<?
*4rZ'F@*(F-F8F4F=F)F=#"-Jy.`'\%F(*(F-F=F4F8F)F=#!.P$4lok8F(*(F-F=F4F=F)F8#!.4sD
zbZ"F;*(F-F8F4F=F0F=#!.*[Cy%[W"F@*(F-F=F4F8F0F=#!-H'Q'3NCF(*(F-F=F4F=F0F8#"-(G&
)f(GEFD*(F-F8F)F=F0F=#!,(H*\0K)F^o*(F-F=F)F8F0F=#".PSndB^"F@*(F-F=F)F=F0F8#"-">
d$e1;F3*(F%F8F4F=F)F=#!-2*=S*obF(*(F%F=F4F8F)F=#"-L)o]j"yF;*(F%F=F4F=F)F8#",2>1
XU"F^`l*(F%F8F4F=F0F=#!,\]S&*G"F,*(F%F=F4F8F0F=#",BthnA$FD*(F%F=F4F=F0F8#!-T%ez
)GCF3*(F%F8F)F=F0F=#!-4k()*[2'F(*(F%F=F)F8F0F=#!,^&QK"z"F,*(F%F=F)F=F0F8#"+(*[
\Q7F_t*(F4F8F)F=F0F=#".z1<9T1"F(*(F4F=F)F8F0F=#!-p-vTR?F,*(F4F=F)F=F0F8#!,@*=X*
f"F^oFfr#!-8&*p1_'*F;Fir#!-h7yfF&)F;F\s#",RTU!ytF]xF_s#"+F$G5k*F@Fbs#",t!\YIbF,
Ffs#",z>h4h$F,Fis#"-tH2?4=F]xF\t#"-pU^13CF@F`t#"-Zk$3,6#F@Fct#!-$Qnhb6"FHFft#"-
*yExI%>F(Fit#",*ei9s^F^`lF\u#".n&)4+!4;F;F_u#!.Fnc)z<;F;Fbu#!+"o7,M#"+++]7yFeu#
!,BlS:;)F@Fhu#"-Vu[&4c'F;F[v#"..GS+9&>F;F^v#!-hPNcBAFDFav#"-f>Y,&o*FH#!,*>TuXBF
DF=,^r!""F=*(%"zGF=F%F=F-F=#"*n`UZ""*++++#*(F\anF=F4F=F-F=#!*2-9j&"+++++5*(F\an
F=F)F=F-F=#!).Z^f")++DJ*(F\anF=F-F=F0F=#"+B=)4+""*++++&*(F\anF=F4F=F%F=#")h7MY"
)+++]*(F\anF=F%F=F)F=#"(p&>QFcan*(F\anF=F%F=F0F=#"("QNcF[bn*(F\anF=F4F=F)F=#!+L
&*o5:Fcan*(F\anF=F4F=F0F=#"*,nYR%"*+++]#*(F\anF=F)F=F0F=#"*H2=z'F[bn*(F\anF=F-F
8F%F=#!)2aL]F\cn*(F\anF=F-F8F4F=#!)tb%y$"*+++D"*(F\anF=F-F8F)F=#"+deU#G#Fcan*(F
\anF=F-F8F0F=#!)Z5*e&")++]i*(F\anF=F-F=F%F8#"*$)R&>7Fcan*(F\anF=F-F=F4F8#!**pot
;F[bn*(F\anF=F-F=F)F8#!*fSq6(Fcan*(F\anF=F-F=F0F8#"*V*G)p"Ffcn*(F\anF=F%F8F4F=#
!*f*RZ9Fcan*(F\anF=F%F8F)F=#"*$ek'3$F[bn*(F\anF=F%F8F0F=#!*x7NB"F\cn*(F\anF=F%F
=F4F8#!)jrX[Fcan*(F\anF=F%F=F)F8#")"z`7(Fcan*(F\anF=F%F=F0F8#!*d[UG(Fcan*(F\anF
=F4F8F)F=#"*fTt"HF\cn*(F\anF=F4F8F0F=#!)*)R)=""*++++"*(F\anF=F4F=F)F8#!*Z"*o))*
Fcan*(F\anF=F4F=F0F8#"*H<yV%Fcan*(F\anF=F)F8F0F=#")6()=>Fgan*(F\anF=F)F=F0F8#"*
<NTP)FcanF\an#")r)H$GF_bn**F\anF=F-F=F%F=F4F=#"$6'"(++D"**F\anF=F-F=F%F=F)F=#!*
8#f'>#F_an**F\anF=F-F=F%F=F0F=#"*Vv=;%F[bn**F\anF=F-F=F4F=F)F=#"+`OqWJFcan**F\a
nF=F-F=F4F=F0F=#!)><DEF_bn**F\anF=F-F=F)F=F0F=#!*RI&*f$Ffcn**F\anF=F%F=F4F=F)F=
#!*T'R[6F[bn**F\anF=F%F=F4F=F0F=#!)6L*H&F[bn**F\anF=F%F=F)F=F0F=#"*@I#e5Ffcn**F
\anF=F4F=F)F=F0F=#!)RET"*F_bn*&F\anF=F%F=#!*zn&f9Fcan*&F\anF=F)F=#!)t\77F_an*&F
\anF=F-F=#!*z!oD*)Fcan*&F\anF=F0F=#!*zepC"F[bn*&F\anF=F4F=#!+x-XT6Fcan*&F\anF=F
-F8#!)f`ycFbfn*&F\anF=F%F8#"(JL^"")+++S*&F\anF=F4F8#"'jrg")+++5*&F\anF=F)F8#")H
"Qr&Fbfn*&F\anF=F0F8#!*(Rg&4*Fcan*&F\anF=F-Fho#"("3d^Fcan*&F\anF=F%Fho#!)$Gj%))
Fcan*&F\anF=F4Fho#!)RA'>#F_an*&F\anF=F)Fho#!*>*)Rh"F_an*&F\anF=F0Fho#!*^5#oFF[b
n6",
I/C_toa_55_w_satw,6#>%)symbolicGF=66%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_
V0G%#_VG%"iG%#M1G%#vvG%"HG%"bG%&countG%"CG%%adjHG%%detHG%"SG%#ddG%$eqsG6"F_\oC5
>6$8$8%6$7#%"MG7#7$"#rF=@%/9$F=>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG
6$-%#opG6#&F_^o6#8,w,6$F)F0F_\o6$%)operatorG%&arrowGF_\o-&T'6#T%6#,&Fh^oF=*&,&9
%F=Fj`nF=F=&&T#Fc`o6#F=F=F=F_\oF_\o6(Fg\oF_^oF^]oFj_oFf\oF^^o6#F86$7'Q!F_\oFj`n
"#R"#u"#O7'FbaoFj`nFcao"#XFeao/Fj_o;F=-%%nopsG6#F^^o>Fj^o7#-F]_o6$-%'rndMatG6#F
e_oFhao>8--%(convertG6$&Fj^oF]aoI'VectorG6$Fb_oFc_o>8.7(F=F-F%F4F)F0>6%8/80816%
""!FecoFeco?(Fj_oF=F=""'%%trueGC&>82-I$<,>GFc_o6%-I$<|gr>GFc_o6%&Febo6#,&FccoF=
F=F=&Febo6#,&FccoF=F8F=&Febo6#,&FccoF=FhoF=-F`do6%Fedo&Febo6#,&FccoF=FfemF=&Feb
o6#,&FccoF=""&F=-F`do6%FhdoF`eo&Febo6#,&FccoF=FgcoF=>Faco,&FacoF=*&&F]coFi_oF=F
[doF=F=>Fbco,&FbcoF=*&&Febo6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GFccoF=F\foF=F
=>Fcco,&FccoF=F^goF=>83-%$adjG6#Faco>84-&I.LinearAlgebraG6$Fb_oFc_o6#_F[ho%,Det
erminantGFfgo>85&Febo6#-Fcfo6%7#-Fjfo6#;F="#7F_goFcco>Faho)-F]do6&-F`do6%&FahoF
]ao&Faho6#F8&Faho6#Fho-F`do6%&Faho6#Ffem&Faho6#Fceo&Faho6#Fgco-F`do6%&Faho6#F]g
o&Faho6#"")&Faho6#F^go-F`do6%&Faho6#"#5&Faho6#"#6&Faho6#Fjho%#%TG>86&Febo6#-Fcf
o6%7#-Fjfo6#;"#8"#<F_goFcco>877$-F]_o6$,&-I".G6$Fb_oFc_o6$,&-Fe\p6$)&Faho6$;F_
\oF_\oFj_oFa[pFcgoF=-Fe\p6$,$)FbcoFa[pF8FcgoF=F\]pF=*&&Fc[pFi_oF=FhgoF=Fj`n/Fj_
o;F=Ffem,&-Fe\p6%Fb]pFcgoFbcoF=*&&Fc[pF[joF=FhgoF=Fj`n>F_\p7$-Ff_o6#F_\p,&*&F\a
nF=FhgoF=F=Fj`nF=>8'-%$mapG6$%'expandGF_\p@$0Fh^oF=OFc^p>8(-%&minusG6$-%'indets
G6#Fc^p-Fa_p6#Fj^o>6$8)8*-%,poly2matrixG6$Fc^pF\_p>8+-%$srtG6$Fh_p-%%tdegG6#-Ff
_o6#F\_p6%7$%#cfG-%/permuteColumnsG6%Fg_pFh_pF]`pF^^oF_^oF_\oF_\oF_\o6#Feco6=7'
FbaoFj`n"#;FgcoFeao7'FbaoFj`nFho"#L"#V7'FbaoFj`nFhoF^goFgao7'FbaoFj`nF]go"#&*Fb
ap7'FbaoFj`nF]go"#dFbap7'FbaoFj`nFho"#IFbap7'FbaoFj`nFho"#EFbap7'FbaoFj`nFho"#D
Fbap7'FbaoFj`nFhoFdjoFdjo7'FbaoFj`nF]go"$G"Fbap7'FbaoFj`nF]go"#@Fbap7'FbaoFj`nF
]go"#SFbap7'FbaoFj`nF]go"#BFbap7'FbaoFj`nFhoF_apFbap7'FbaoFj`nFhoFcaoFbap7'Fbao
Fj`nFho"#FFbap7'FbaoFj`nFho"#')Fbap7'FbaoFj`nFho"#HFbap7'FbaoFj`nFho"#'*Fbap7'F
baoFj`nFho"#GFbap7'FbaoFj`nFho"#CFbap7'FbaoFj`nFhoFdbpFgao7'FbaoFj`nFfbp"#K"#_7
'FbaoFj`nFho"#QFbap7'FbaoFj`nFhoFeaoFbapF`ap7'FbaoFj`nFho"#`"#JF_\o
