M7R0
I)F_toa_467',bo%"vG#".JH)G7xF".++++++"%"xG#".4o\I/2#F(%"yG#!-6fDL6=F(%"wG#"-*pT
)>?:F(*(F%"""F/F3F)F3#"-ZO8+aR"-+++++]*(F%F3F/F3F,F3#!,nk5ol%",++++D'*(F%F3F)F3
F,F3#"-Bu@vR5"-+++++D*(F/F3F)F3F,F3#!-Bfi.bSF6*$F%""##"+VFy_$)F(*&F%F3F/F3#!-Tz
\<tD"-+++++?*&F%F3F)F3#!.r&*zin`"F(*&F%F3F,F3#"-Ve#eUV#F(*$F/FC#!,dco=.&F(*&F/F
3F)F3#!-H"Q)z'=""-+++++5*&F/F3F,F3#"-x/+446"-++++]7*$F)FC#!->Hc\YmF(*&F)F3F,F3#
"-B2.(3'zF6*$F,FC#"-t%*G$>7$F6*&F%FCF/F3#"-87/oPXF>*&F%FCF)F3#!-`FJL!3"F>*&F%FC
F,F3#!,^5S0D)F6*&F%F3F/FC#!-8\%Q,T"F>*&F%F3F)FC#",(o09aC",++++D"*&F%F3F,FC#"-,<
wQ/NF6*&F/FCF)F3#"-VsUK<5F>*&F/FCF,F3#",\tk:5#F6*&F/F3F)FC#!,<tug$HF>*&F/F3F,FC
#!,h;&[(>#",+++++&*&F)FCF,F3#!,T;**R-%FZ*&F)F3F,FC#!-Fi`65bF6*$F%""$#!-8fioy<FV
*$F/Feq#",Baf$ezF6*$F)Feq#",rXAGb)FV*$F,Feq#!-jC:&\.#F6#!,nLCf+&F]qF3,boF%#",`c
7Fi'FZF)#!,ZGIDS(",++++]#F,#!.tbNg/B"F>F/#",t97?&=F>F2#"-\WFG8OF6F7#"*nRu[&"+++
++!)F;#!.Zq3yx^"F(F?#!-nl'zo:%F>FB#!.n:#Rt!3#F(FF#"-Rw\9vBF6FJ#!-4O3:*y#F6FM#".
"H@])4,)F(FP#!,t)eMw[F6FS#".")Q[Obf"F6FW#"."=/R(Gr"F(Fen#".@'Hb$Qz#F(Fhn#".TV*)
z?y&F(F[o#"-$)f=0bnF>F^o#!,\cSJ'R",+++]7$Fao#"+,bKO<"+++++]Fdo#!.H22Sn&[F(Fgo#"
.r!e"HT1"F(Fjo#!-"G\#GoZF6F^p#!.T0e7#=6F(Fap#!->QWTT?FIFdp#!,\dS<j'F>Fgp#!-^ofp
\hF(Fjp#!-4'=Zvp'F(F^q#"-2VqilUF>Faq#",B`Jl\(F(Fdq#".j6'e><:F(Fhq#!-LnYGLJF(F[r
#!-TynD6xF(F^r#!-HgWR!e&F(#"+VNNb'*F:F3,boF%#"-r"e#G"*fF6F)#"-zLWC*>&F6F,#!-Ta
\w67F6F/#"-,!>ID(GF6F2#",dT&GOGF\uF7#!->"H$\v()F6F;#"-pi#ef"[F6F?#"-"RhIbX"F>FB
#"-*3nf#pWF>FF#!-nvRWm>FVFJ#!-z4DD/bF6FM#!-R9]VnZFZFP#!,@2t))\&F6FS#"+H7^fsF\uF
W#"-.fvdC\FVFen#!,.4RO&oF:Fhn#!.pbaiR`"F6F[o#!-ZSe*p/*F>F^o#!-<"*3xt;F>Fao#!,H0
=8#)*FZFdo#"-z"RWo7'F6Fgo#"-tU"HEA$F6Fjo#",6a>R+"F\uF^p#".L6yvhg"F6Fap#!,xF2l%>
F6Fdp#!,p`/F(QF:Fgp#"-$p!R*='=F6Fjp#",t[nW5%F6F^q#!+(\ctM%FZFaq#!,p0]!pvFVFdq#!
,$eF-$[$F6Fhq#"+>lf(G"F6F[r#"+6W")yw",+++++#F^r#!-4!)pDVAF6#!->fX54BF>F3,hsF%#"
+6#\Wf$F:F)#"-F-'eaN%FZF,#".$oqFD75F>F/#",nxGFh)FZ**F%F3F/F3F)F3F,F3#!-T@\V`9FV
F2#!,P2-`N"Fa[lF7#"-([I`Nx%F>F;#"-.xey]BF6F?#".,at3\l#F6FB#"-.fLk*o)F>FF#!-jcz/
dOFIFJ#"-(z2zS'HF(FM#!.j%f'*HPBF6FP#!-ZnlXc=F(FS#!->c_ilrF>FW#!-fO%)e5&*F(Fen#!
.\YO6)eMF(Fhn#!.JKDQ5!oF(F[o#!.@L')e9X&F(F^o#!-@%H)zgwF(Fao#!-P:7l16FIFdo#"**>N
#H)FasFgo#"-V:+MCVF(Fjo#"-.;&y.t"F>F^p#".([\wJ$\'F(Fap#"-R_;">()*F(Fdp#!.*3#Q>$
o6F(Fgp#".dOE(*Rj#F(Fjp#"-<[_KYQF>F^q#!-V!*o3MOF>Faq#"-8p_ap")F6Fdq#!-^Xl3UnF(F
hq#"-jKl3<<F(F[r#"-^^b(3J)F(F^r#".(z9xKv=F(*(F%FCF/F3F)F3#!-Rje0FuF6*(F%F3F/FCF
)F3#",6[YtK%",+++++%*(F%F3F/F3F)FC#!-pH(*[CJF>*(F%FCF/F3F,F3#!.R,`>$[9F6*(F%F3F
/FCF,F3#".LjP(yg>F(*(F%F3F/F3F,FC#!-nCXT$)pF(*(F%FCF)F3F,F3#"-Jy.`'\%F6*(F%F3F)
FCF,F3#!.P$4lok8F6*(F%F3F)F3F,FC#!.4sDzbZ"F(*(F/FCF)F3F,F3#!-2*=S*obF6*(F/F3F)F
CF,F3#"-L)o]j"yF(*(F/F3F)F3F,FC#",2>1XU"Fa[l*&F%FeqF/F3#"..u(GQTGF(*&F%FCF/FC#!
-`^V@`sF6*&F%FeqF)F3#"-xij\[LFI*&F%FCF)FC#".d))eXP."F6*&F%FeqF,F3#".L['ei)H#F(*
&F%FCF,FC#!.p'*f#pH8F6*&F%F3F/Feq#"-6S?/vKF(*&F%F3F)Feq#!-f&yF#4bF6*&F%F3F,Feq#
!-h2PR!H#FI*&F/FeqF)F3#!*2Gs,$"*++++)*&F/FCF)FC#!-8&)=%G["F>*&F/FeqF,F3#!,6u(RW
IFZ*&F/FCF,FC#!,.,!>SjF6*&F/F3F)Feq#!**["z:&"+++++D*&F/F3F,Feq#"-nla3g?F(*&F)Fe
qF,F3#!-nm%\(ecF(*&F)FCF,FC#",r%pj\CF]p*&F)F3F,Feq#"-HS+;C?FI*$F%""%#!,xoPBe(Fd
`l*$F/F\fl#!,rh6dQ"FI*$F)F\fl#!,rnf9m*FZ*$F,F\fl#!,>ukQ9"F(#!-"*o(4#RBF>F3,doF%
#!*z!oD*)"+++++5F)#!+x-XT6F]glF,#!)t\77"*++++#F/#!*zn&f9F]gl%"zG!""F2#"$6'"(++D
"F7#!*8#f'>#FbglF;#"+`OqWJF]glF?#!*T'R[6"*++++&FB#!)f`yc"*++++"FF#"*n`UZ"FbglFJ
#!*2-9j&F]glFM#!).Z^f")++DJFP#"(JL^"")+++SFS#")h7MY")+++]FW#"(p&>QF]glFen#"'jrg
")+++5Fhn#!+L&*o5:F]glF[o#")H"Qr&FchlF^o#!)2aL]"*+++]#Fao#!)tb%y$"*+++D"Fdo#"+d
eU#G#F]glFgo#"*$)R&>7F]glFjo#!**pot;F`hlF^p#!*fSq6(F]glFap#!*f*RZ9F]glFdp#"*$ek
'3$F`hlFgp#!)jrX[F]glFjp#")"z`7(F]glF^q#"*fTt"HF\jlFaq#!*Z"*o))*F]glFdq#"("3d^F
]glFhq#!)$Gj%))F]glF[r#!)RA'>#FbglF^r#!*>*)Rh"Fbgl#")r)H$GF`ilF36",
I)C_toa_46w,6#>%)symbolicGF366%&_nameG%&_sizeG%#_AG%"iG%#M1G%#vvG%"HG%"bG%"kG%"
CG%%adjHG%%detHG%"SG%#ddG%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"F^\mC5>6$8$8%6$7
#%"MG7#7$"#eF3@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F^^m6#8'F^\m/Fe_m;F3-%%nopsG6
#F]^m>Fj^m7#-F]_m6$-I'MatrixG6$%*protectedG%(_syslibG6$Fb_mw,6$F)F,F^\m6$%)oper
atorG%&arrowGF^\m-&T'6#T%6#,&Fg^mF3*&,&9%F3FfglF3F3&&T#F]am6#F3F3F3F^\mF^\m6(Ff
\mF^^mFh\mFe_mFe\mF]^m6#FC6$7'Q!F^\mFfgl"#P"#s"#O7'F\bmFfglF]bm"#VF_bmFf_m>8(-%
(convertG6$&Fj^mFgamI'VectorG6$Fb`mFc`m>8)7'F3F%F/F)F,>6%8*8+8,6%Fh^mFh^mFh^m?(
Fe_mF3F3""&%%trueGC&>8--I$<,>GFc`m6%-I$<|gr>GFc`m6%&Fcbm6#,&FacmF3F3F3&Fcbm6#,&
FacmF3FCF3&Fcbm6#,&FacmF3FeqF3-F]dm6%Fbdm&Fcbm6#,&FacmF3F\flF3&Fcbm6#,&FacmF3Fd
cmF3-F]dm6%FedmF]em&Fcbm6#,&FacmF3""'F3>F_cm,&F_cmF3*&&F[cmFd_mF3FhcmF3F3>F`cm,
&F`cmF3*&&Fcbm6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GFacmF3FiemF3F3>Facm,&FacmF
3F[gmF3>8.-%$adjG6#F_cm>8/-&I.LinearAlgebraG6$Fb`mFc`m6#%,DeterminantGFcgm>80&F
cbm6#-F`fm6%7#-Fgfm6#;F3F[gmF\gmFacm>F]hm)-Fjcm6%-F]dm6%&F]hmFgam&F]hm6#FC&F]hm
6#Feq-F]dm6%&F]hm6#F\fl&F]hm6#Fdcm&F]hm6#Feem-F]dm6%&F]hm6#Fjfm&F]hm6#"")&F]hm6
#F[gm%#%TG>81&Fcbm6#-F`fm6%7#-Fgfm6#;"#5"#8F\gmFacm>827$-F]_m6$,&-I".G6$Fb`mFc`
m6$,&-Ff[n6$)&F]hm6$;F^\mF^\mFe_mFbjmF`gmF3-Ff[n6$,$)F`cmFbjmFCF`gmF3F]\nF3*&&F
djmFd_mF3FegmF3Ffgl/Fe_m;F3Feq,&-Ff[n6%Fc\nF`gmF`cmF3*&&FdjmFdimF3FegmF3Ffgl>F`
[n7$&F`[nF^\m,&FegmF3FeglFfgl>83-%$mapG6$%'expandGF`[n@$Ff^mOFb]n>84-%&minusG6$
-%'indetsG6#Fb]n-F_^n6#Fj^m>6$8586-%,poly2matrixG6$Fb]nFj]n>87-%$srtG6$Ff^n-%%t
degG6#&Fj]nF^\m6%7#-%/permuteColumnsG6%Fe^nFf^nF[_nF]^mF^^mF^\mF^\mF^\m6#Fh^m6=
7'F\bmFfgl"#;FeemF_bm7'F\bmFfglFeq"#LFabm7'F\bmFfglFeqF[gm"#X7'F\bmFfglFjfm"#bF
abm7'F\bmFfglFjfm"#$*Fabm7'F\bmFfglFeq"#IFabm7'F\bmFfglFeq"#BFabm7'F\bmFfglFeq"
#@Fabm7'F\bmFfglFeqF_jmF_jm7'F\bmFfglFjfm"#')Fabm7'F\bmFfglFjfmFi`nFabm7'F\bmFf
glFjfmF_bmFabm7'F\bmFfglFjfm"#:Fabm7'F\bmFfglFeqF[`nFabm7'F\bmFfglFeq"#RFabm7'F
\bmFfglFeq"#AFabm7'F\bmFfglFeq"#dFabm7'F\bmFfglFeq"#DFabm7'F\bmFfglFeqFc`nFabm7
'F\bmFfglFeq"#CFabmF[bn7'F\bmFfglFeqFcanF_`n7'F\bmFfglFean"#J"#_7'F\bmFfglFeq"#
QFabm7'F\bmFfglFeqF_bmFabm7'F\bmFfglFeqF_bnFabm7'F\bmFfglFeq"#ZF_bnF^\m
