M7R0
I2F_unsynch_relpose7&,:#!2(p>@A&Gt,$"1%>'4-(zX&f"""%"zG#"2N=_j,'[-H"2)Q#>/%f"4>
"*&F)""#%"wGF(#"3fXo#))yYkd%"2/"RNBvKF&**&F)F.%"xGF(#"2*eXJ$R$*[p$"2wZQ3)=$=Q#*
&F)F.%"yGF(#!2&\tO6/n&>(F2*&F/F(F)F(#!3:K`J[!fb^&F2*&F4F(F)F(#!3V^K/;av.6F2*&F9
F(F)F(#"3zhSS=!GSx"F2*$F)F.#!/nMH#*=;&)"0wy$\=*3;*F/#!2&Hy)GwMD`#"2_&pnhPmjZF4#
"2b'H*Gi1!*R"FKF9#"2&f65F4_*p'FK,:#!2<()>#[)*H"y"F,F(F)#!1v_0cV*Rj#F,F-#!2$RUZ#
p8d^(FKF3#!1hA^dTS?rF,F8#"2"[6GJCpEwFKF<#!3l(oi`u[>$>F2F?#"1V"3JLm6K(FKFB#!2Z<i
3^6K'QF2FE#"0D+PU%z87"0Q*oCfW!e%F/#"2t$GsdD6XOF2F4#!2tZa&RLj`zF2F9#"2nX,_LX8J(F
2,:#!2ht^n'\K`9F'F(F)#!2X64d,D4m#F'F-#!3p91be2VP:F7F3#!1V?G!yu!3xF'F8#"2DPYc"zq
:MF7F<#!3>)p$[l7S1:FKF?#"0Nr%*QWi'))"1_d()p$y@$=FB#"2J,6mP1E%)*FKFE#!0N\+2+!pB"
0pWB'HA!H#F/#!1*3d&e=!>1#FKF4#"2$f3!R-s_"RFKF9#"2H[DC:KYW%FK,\uF4#!enB,#Q@%[^2e
o")QsX&>jimnBQB-,5jrs""Y++++!oXdfCsqRIY#*Qjp#>jVV,'*3C;F9#!enT"H^=$)e"yX/z%3n4<
#)*[sYkM!=)Q(Q,u%"Y++++?F)HQ)*)G)e@&)pb`yqFXPdSej\'F/#"enn+Q24=0nAM&e%=t!z%4P%3
sm+!f!Q$Q&p#FbqF)#"en.j*pDE*)*pxDw_tV5-9eh&*RU2*=P^o$>FbqF<#"gnRY'[L>;84\+_2k^n
*>#3f9xS%RE%f>6#="Z++++Sa'fw'zdwJ/(R62dTb!\Z6or#*H"F?#"fn^d/(*)Gr)H5pAWomP9DH7,
/S(*zGBy@,%F\rFB#!fnTE]lZBDdt%Q7j*>HXWUD$[kee-'z-M=%F\r**F/F(F)""$F4F(F9F(#!gn
\#QB@'G#o**[b#4k&\7.TKt!)4)=1>_4edv"en++++SqWb#[Z_#3p_BQJ^m)[)f$)*oM)y?**F/F(F)
F.F4F(F9F(#!gn<5')p#z:Qyei^eR$='>/Iu-#o#G8^&Gm#Q#"en++++!3%*3^'\\];Q0Zwi-Lxp>nz
$pw:%**F/F(F)F(F4F(F9F(#"entzgP?zc;%**4O>X[u:9"frdn)GBfn:!=Feq*(F9F(F4F(F/F(#"f
n2S;x[x[o1R>Jv2CU$)[C&H5t.))=-$ou"Fir*(F/F(F)F.F4F(#"fn^'fl/4e$))pA>G-ZoBVjObl_
%=!Qs.vW$"Y++++g8\">\WTzg#\yn#R&QE(oG?z"[K*(F/F(F)F.F9F(#!hn.m'\aoi+D6EVJjJS<H#
e?/=#RUpWd*R/""en++++?NsFTPi7aMw6plDLW#*z"\M<%R5*(F)F(F4F(F/F(#!gnzxHHc8H*e$\r*
oV'>")ef6O[7`u$[L.x:#Fgs*(F)F(F9F(F/F(#!fn8"**e+ij8DUBe8^b-8nvCSHSsq9s,mR"Z++++
_Bx7uBETXj<"plDLW#*z"\M<%R5*(F4F(F)F.F9F(#!fn<oPN;&e157o&\+jI?_axi')*>T"eshdA""
Y++++whQ1(=J1F<)eXGGm@i**eCn3(>&*(F)F(F9F(F4F(#"enj2XMT**fwG"3I2=2!*35#zB&41o7(
QKrnFgs*(F/F.F)FbrF4F(#"hn"Q$34hc6WF2YTN-=Y&f:*\o#[Gh(Q<vag$Fir*(F/F(F)FbrF4F.#
"fnBCh)3*[M&>$yHD_nP(ppNbNBG"H.]`by#F\r*(F/F.F)F.F4F(#!gn@#\8kmP9\7Rh]Y<">ZH_?^
iKhCZ%\s.$"en++++g")y@I**)4Ij2THb_gY&RRMf(Q`J)*(F/F(F)F.F4F.#!gn4>lq#R6'pZ!QBN7
=JGT@e_Xl^=TS6/>#Fer*(F/F(F)FbrF4F(#"fn$\(f))Hn,m"p%><nbW4W-&*Q$zw'>rE"*Q4%"Z++
++!)3$>`$f:`j3%zA99$36)\HiLa)f#*(F/F.F)FbrF9F(#!hn(Ql%HiZfNGbo5*GEaO=\I]*\de"4]
P!G7'F_u*(F/F(F)FbrF9F.#"enhNf!QP*f#[#ey<O'yG#zK2$3Mac9&G<R!*"Y+++G0V<W>zS1hGNU
?%GP;:vu+rAl'*(F/F.F)F.F9F(#!hnP)fKn`ed*o$)eJpA!)[3'R0BYGncH&>R_\$F_u*(F/F(F)F.
F9F.#"gnj[AK;;onRv]q(GJYt8+F,;3"=dr()y1%*F_u*(F/F(F)FbrF9F(#!en2W/R@7Ot7B$z`jyd
$RZ_xA#\%p')p.hWFcs*(F/F.F)F(F4F(#!fn>hY;zA=)=PntY!Qo(y0()R5*p_d)pJ@@sFgs*(F/F(
F)F(F4F.#!fnjD38VT[/TU\Wq>2l_c)\[!za#G=8gPOF_u*(F/F.F)F(F9F(#!gnh!p>'Q/NuuudLio
Nd:vaR7C-)=(f%*=16"en++++KwN/')z>gE:#)e50@$4zyo=vnIm"*(F/F(F)F(F9F.#"gn(oo`uYEJ
+a"RlybN!*=Vk'H."\*3598'H=F_u*(F4F.F)FbrF9F(#!fnV&\*>F#*QFSNqf;UmEWi?**z4"fvN3z
k6Ffu*(F4F(F)FbrF9F.#"fnT7yr:)GHe)H:$ffWO#=Qv=pRVYcf'[aF"Z++++;)y@I**)4Ij2THb_g
Y&RRMf(Q`J)*(F4F.F)F.F9F(#"fnTE%**yXDQyK<Dhqha\t)e))***zp)3vZa^#Fer*(F4F(F)F.F9
F.#"gn"*fFT&GZV.)*48G.!Q^<xi.!yftIn=.;="F_u*(F4F(F)FbrF9F(#!en@&pTV'z$G4QZ>0hX&
H9#e@F'Hyq!*e;l))Ffu*(F4F.F)F(F9F(#"en`wK14S'pu.'HAz6x#ev'=b>x;k(=Hz;&F`w*(F4F(
F)F(F9F.#!en"4#G%ot30$4Bs%4cQ*3m:_QVhG"Q2;t.$Fgs*$F/F.#"fnzpTe@wxq!R;_uz&))pAR'
4*R,-mZZio4""Z++++3%*3^'\\];Q0Zwi-Lxp>nz$pw:%*&F/F(F4F(#!fnB==n82)\C0-]/vN[()Qn
"***)fk%)>o,/<&Fgs*&F/F(F9F(#!fn6@"*pBrCk1s")*)*G,xM%*)ec."Hu?X$\^>$Fgs*$F4F.#"
fn$eZosn%=PB)*G,X%*QYMb,FW2(oSXXC;@Fer*&F4F(F9F(#"fn$e@+7O2jTS>^1IV2(R.UBu&e^J/
z*pi"Fgs*$F9F.#"fn*RgL_P)HN5Y:)zDX+"e:?DKJEuU&>z#="Fer*&F4F(F/F.#!fnhFiXUnw8-Yf
Jx*[+<YRyaq%*ejy&\Bq%F_u*&F9F(F/F.#!fnff=veR(4X&)oQS#G%))\nJa0&z@<E5XV'=F_u*&F4
F.F/F(#"fnP@bN+%yY5!3>9`5$H&)e]H3$y.IwZaC%=F_u*&F9F.F/F(#"enHL_#RU*[ir"3nY)3C^(
H_'R/%\Lr`*>jNF`w*&F9F(F4F.#!en>0m7fX^;%))R=vNu,ibuKV"eq-`)pU'[F_u*&F9F.F4F(#"Z
>9(R'et>yxgj57t)**o'**ey7$)*[j@-&G%F_uF-#"en4of)yANfkz6=^;"oH^DG-Vl!*oanC%3&"Y+
+++Wlfw'zdwJ/(R62dTb!\Z6or#*H"F3#"fn<b4"*ykeUJC#=Tq(3>Z%G$)GI$Rvue!oW7F\rF8#!en
"G"zvTZU5o7"z"[k[BfRo\$et#*zf7)\GFcsFE#"Y^Jne#*[N3.Y5/CNo`XzA*ouy#QMgaS"X++++?Z
6Iw&\&*f"[6HG`>s4AoQ*f)\#*&F/F.F)F.#"hnn"[W_N2lW(\au`*e)3yi(QTPK(4)RpD)*4ZFer*&
F)F(F/F.#"gn$R:[Idi8QdUBu&p)oA"pfM8EV_j:oUcdFgs*&F4F.F)F.#"fnh%RT&H7/vm))*yB#og
H-`Xs(=,x*\O#4)>$Ffu*&F)F(F4F.#!fnrGf>!**R%p.%*oh-nRW]k#*Qi;w_>Vy.S%"Z++++g<'Q1
(=J1F<)eXGGm@i**eCn3(>&*&F9F.F)F.#"gnVP*pGV=Qt_h.*yC/%p>[Pm#p4ZQw?k1@Fer*&F)F(F
9F.#"fn8:4L0%=$y)4"zXi]#G&R))3\.RM!)y3$z*)eFgs*$F/Fbr#"enV!>N-xf[rq/C)\I%RQcQ"Q
3R')*ff%HLQF_u*$F4Fbr#!enf%f8T))>`qKXG#=?o`w(zs8CYcmx(**)=$F_u*$F9Fbr#"ZJ&[R]&>
g^j%p;`m<vw#*\ajaS&**3._d$F`w#"en2L$y\1euv&)\-jF;vh"4No2M,E&zz$=!*FcsF(*&F/FbrF
)F(#"gn(p()o+w$R=O&R'yo=Bq6sN$G(>*>VBhBRt$F_u*&F4FbrF)F(#"fn<P6-&yOEhn@K>-g.X!>
C"))f@jq#>/mu"Fir*&F9FbrF)F(#!en*>Kl3b%p>h/B3cOKMrkfF1C14I-OeYF_u*&F/F.F)Fbr#"g
n`FSE">;qy)pF1fQqZ$H*GcBh:kkVv*3j"Fe\l*&F/F(F)Fbr#"Z"zL+dvE-sX(>neHJj&GMf`ho6ta
5[E"X++++!))e/_I)>)REfkJJ"y))Q)GZvR%****&F4F.F)Fbr#"enn$R%y%>phKG&>ZVUnRhglrW%4
`x40XF"Feq*&F4F(F)Fbr#"YpG7(G0;'pID!fZ8i#[&zpjll)yb+)pW$"X++++S%H-E:*4*>jH#ec1R
W>WOx)>(*\*&F9F.F)Fbr#"enV9q71iW)pPC@69?#)>t?%)yvJzUay&H9F^t*&F9F(F)Fbr#!Yd=Ko!
QZ/@E-**Hk9XM?]#4%3(4/+]ghFf^l*&F/FbrF)Fbr#"hnRx<02,b$fHZw..s$\!\4b"yroVW(GT*\p
*F_u*&F/FbrF)F.#"hnts:GjerzexdQI$*)>Itrb[W<"*4gmL0*z$F_u*&F4FbrF)Fbr#"entLdSG;6
:nErW^V``4^!)z>8SQ(*GN$e%Ffu*&F4FbrF)F.#!en,cM@;hQ4"f^`*eS'G;#e?Bo2&e(*Q$=#>#F
\r*&F9FbrF)Fbr#!fn`7NMk!fHN"fb(*H/X/$*4jt<#RTtgr2&G&F_u*&F9FbrF)F.#!fn.1'Q:`L'4
PN^qk%RG%o6<O"ek+T(f:l`(F_u*$F)Fbr#"S\,n+)H%G'[V3z:%zMM/&**e%y8j*H#"S+]i!4CV<'3
Y8>o'p2'[g"f(G`!Rv$6",
I2C_unsynch_relposew,6#>%)symbolicGF(68%&_nameG%&_sizeG%#_AG%"iG%#wwG%$eqsG%%va
rsG%"MG%"VG%#V1G%#M1G%$tM1G%#stG%#suG%#svG%%condG%$eq1G%#_FG%&_varsG%$_C0G%$_V0
G%#_VG6"Fj`lC7>6$8$8%6$7#%"NG7#7$"#:""(@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F\cl
6#8'Fj`l/Fddl;F(-%%nopsG6#F[cl>Ficl7#-F\dl6$-I'MatrixG6$%*protectedG%(_syslibG6
$Fadlw,6$F4F9Fj`l6$%)operatorG%&arrowGFj`l-&T'6#T%6#,&FfclF(*&,&9%F(!""F(F(&&T#
F\fl6#F(F(F(Fj`lFj`l6(FbalF\clFdalFddlFaalF[cl6#F.6$7'Q!Fj`lFcfl"#P"#s"#O7'F\gl
FcflF]gl"#VF_glFedl>8(-I".G6$FaelFbel6$&FiclFgfl-I$<,>GFbel6)%"tG%"uG%"vGF/F4F9
F(>8)-%$mapG6$%'expandG7#-F\dl6$z'6%F)&Fcgl6#,&FddlF(""*F(&FcglFcdl\[[[[[[[\[[[
mF([[[[\[[[[[[[lFcfl/Fddl;F(""'>8*7)F\hlF]hlF^hlF/F4F9F)>6$8+8,-%,poly2matrixG6
$F`hlFcil>8--Fjgl60*&F\hlF(F)F(F\hl*&F]hlF(F)F(F]hl*&F^hlF(F)F(F^hlF<F?FBF/F4F9
F)F(>8.-%/permuteColumnsG6%FgilFhilF]jl@%Fecl>8/-&I.LinearAlgebraG6$FaelFbel6#%
6ReducedRowEchelonFormG6#Fdjl>Fjjl-F_el6#7(70F(FgclFgclFgclFgclFgcl-%"AGFgfl-Fh
[m6#Fccl-Fh[m6#"#8-Fh[m6#"#>-Fh[m6#"#D-Fh[m6#"#J-Fh[m6#F]gl-Fh[m6#Fagl70FgclF(F
gclFgclFgclFgcl-Fh[m6#F.-Fh[m6#"")-Fh[m6#"#9-Fh[m6#"#?-Fh[m6#"#E-Fh[m6#"#K-Fh[m
6#"#Q-Fh[m6#"#W70FgclFgclF(FgclFgclFgcl-Fh[m6#Fbr-Fh[m6#F]il-Fh[m6#Fbcl-Fh[m6#"
#@-Fh[m6#"#F-Fh[m6#"#L-Fh[m6#"#R-Fh[m6#"#X70FgclFgclFgclF(FgclFgcl-Fh[m6#""%-Fh
[m6#"#5-Fh[m6#"#;-Fh[m6#"#A-Fh[m6#"#G-Fh[m6#"#M-Fh[m6#"#S-Fh[m6#"#Y70FgclFgclFg
clFgclF(Fgcl-Fh[m6#""&-Fh[m6#"#6-Fh[m6#"#<-Fh[m6#"#B-Fh[m6#"#H-Fh[m6#"#N-Fh[m6#
"#T-Fh[m6#"#Z70FgclFgclFgclFgclFgclF(-Fh[m6#Fail-Fh[m6#"#7-Fh[m6#"#=-Fh[m6#"#C-
Fh[m6#"#I-Fh[m6#F_gl-Fh[m6#"#U-Fh[m6#"#[>80,&F\hlF(-Fegl6$&Fjjl6$F.;Fj`lFj`lF]j
lFcfl>81,&F]hlF(-Fegl6$&Fjjl6$F\`mFidmF]jlFcfl>82,&F^hlF(-Fegl6$&Fjjl6$FailFidm
F]jlFcfl>837%/F\hlFcdm/F]hlF[em/F^hlFbem>84-&F][m6#%,DeterminantG6#-Fjgl6%-I$<|
gr>GFbel6%&FcglFgfl&FcglF]]m&FcglFe^m-Fhfm6%&FcglF[`m&FcglFdam&FcglF]cm-Fhfm6%&
FcglFj[m&FcglF_]m&FcglFg^m>F`hl-%%subsG6$Fiem7&-Fegl6$&Fjjl6$F(FidmF]jl-Fegl6$&
Fjjl6$FbrFidmF]jl-Fegl6$&Fjjl6$FeamFidmF]jlF_fm>85-Fbhl6$FdhlF`hl@$FeclOFihm>86
-%&minusG6$-%'indetsG6#Fihm-Fdim6#Ficl>6$8788-Fjil6$FihmF_im>89-%$srtG6$F[jm-%%
tdegG6#&F_imFj`l6&7$Fdjl-Ffjl6%FjimF[jmF_jmF_jmF[clF\clFj`lFj`lFj`l6#Fgcl6=7'F
\glFcflFb`mFailF_gl7'F\glFcflFbrFb_mFagl7'F\glFcflFbrF]ilFh_m7'F\glFcflFccl"#bF
agl7'F\glFcflFccl"#$*Fagl7'F\glFcflFbrFabmFagl7'F\glFcflFbr"#_Fagl7'F\glFcflFbr
Ff\mFagl7'F\glFcflFbrF\^mFagl7'F\glFcflFbr"#iFaglFh[nF_[n7'F\glFcflFccl"#`Fagl7
'F\glFcflFccl"$o%Fagl7'F\glFcflFbrF^bmFaglF_\nF_\n7'F\glFcflFbrFh`mFagl7'F\glFc
flFbr"#%*Fagl7'F\glFcflFbr"#oFagl7'F\glFcflFbrFfcmFagl7'F\glFcflFbrFe_mFh_m7'F
\glFcflFe`mFf\mFf[n7'F\glFcflFbrF_^mFagl7'F\glFcflFbrF_glFaglFg[n7'F\glFcflFbrF
a[nFf\mFj`l
