M7R0
I.F_wpnp_2x2sym7&,.^$#"&@$R"&+D'#!&2#="&]7$"""*&^##"'FsIF+F,%#w1GF,F,*(%#z1GF,%
#y1GF,%#x1GF,#"&OO*"&Dc"*(F5F,F4""#F1F,#"'(3=$F+*(F5F,F3F:F1F,#"'\\>"%]iF1#!'*>
B*"'+]7,.^$#!'\M\FC#"&T$))F+F,**F5F,F4F,F3F,F1F,F6*&F4F:F5F,F>*&F3F:F5F,F;*&^#F
)F,F1F,F,F1F&,0*&F5F,F4F,F>*(F3F,F5F,F1F,F6*&^##"&2#=F+F,F3F,F,*&^##!&T$))F+F,F
4F,F,*(F5F,F1F:F4F,F;F4FFF3F&,0*&F5F,F3F,F;*(F5F,F1F:F3F,F>*(F4F,F5F,F1F,F6*&FS
F,F4F,F,*&^##!'FsIF+F,F3F,F,F4F&F3FA6",
I.C_wpnp_2x2symw,6#>%)symbolicGF,62%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V
0G%#_VG%"iG%#A1G%#B1G%#VVG%"qG%"RG%"LG%$eqsG6"F^oC1>6$8$8%6$7$%"AG%"BG7$7$""$F,
7$F:Faq@%/9$F,>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fjp6#8
,w,6$%"xG%"yGF^o6$%)operatorG%&arrowGF^o-&T'6#T%6#,&FeqF,*&,&9%F,!""F,F,&&T#Fbs
6#F,F,F,F^oF^o6(FfoFjpF]pFgrFeoFip6#F:6$7'Q!F^oFis"#R"#u"#O7'FbtFisFct"#XFet/Fg
r;F,-%%nopsG6#Fip>Fgq7#-Fjq6$-%'rndMatG6#FbrFht>6$8-8.6$-&I.LinearAlgebraG6$F_r
F`r6#_F[v%/DiagonalMatrixG6#&FgqF]t&Fgq6#F:>8/-I$<,>GF`r6&-I$<|gr>GF`r6&""!^#Fi
sF]wF\w-Fjv6&FisF\wF\wF,-Fjv6&^#F,F\wF\wFbw-Fjv6&F\wFisF,F\w>80-I".G6$F_rF`r6$F
ev-Fgv6&%"wGFjrF[s%"zG>81-%)quat2rotG6#Ffw>82-%$addG6#-Fgx6#-&%"|irG6#%"^G6%,&-
Fhw6$&F`x6$;F,F:;F^oF^oFfuF,FguFis%#~$GF:>837&-%%diffG6$FexF]x-F]z6$FexFjr-F]z6
$FexF[s-F]z6$FexF^x>Fjy-%%subsG6$/*$FjrF:F5-%$mapG6$w,6#%#plGF^o6$F]sF^sF^o-%'e
xpandG6#*&FeqF,FjrFisF^oF^oF^o6#F,6$7'FbtFis"#F"#UFet7'FbtFisFi[l"#IFet-Fgz6$7%
/F[s*&FjrF,F4F,/F^x*&FjrF,F3F,/F]x*&FjrF,F1F,Fjy>8'-F\[l6$Fc[lFjy@$0FeqF,OFg\l>
8(-%&minusG6$-%'indetsG6#Fg\l-Fc]l6#Fgq>6$8)8*-%,poly2matrixG6$Fg\lF^]l>8+-%$sr
tG6$Fj]l-%%tdegG6#-Fcr6#F^]l6%7$%#cfG-%/permuteColumnsG6%Fi]lFj]lF_^lFipFjpF^oF
^oF^o6#F\w657'FbtFis"#;""'Fet7'FbtFisFaq"#VFd_l7'FbtFisFaq""*Fgt7'FbtFis""("#&*
Fd_l7'FbtFisFh_l"#dFd_l7'FbtFisFaq"#bFd_l7'FbtFisFaq"#cFd_l7'FbtFisFaq"#AFd_l7'
FbtFisFaq"#=Fd_l7'FbtFisFaq"#QFd_l7'FbtFisFaqF[`lFd_l7'FbtFisFaq"#")Fd_l7'FbtFi
sFaq"#CFd_l7'FbtFisFaq"#SFgt7'FbtFis"#B"#K"#_Fd`l7'FbtFisFaqFetFd_l7'FbtFisFaq"
#LFd_l7'FbtFisFaq"#`"#JF^o
