M7R0
I'F_wpnp7&,4*&%#x1G"""%#w1G""$#"'\\>"&++&*&F&F'F(F'#!&jh#F,*(F&F'F(F'%#y1G""##"
'f`]"'++D*(F&F'F(F'%#z1GF2F*F(#"'\M\F5*(F7F'F1F'F&F'#!'(3=$"'+]7F7#"&T$))"&+D'F
1#"&@$RF=#!&2#=F@F',4*&F&F'F(F2F.F&F**&F1F2F&F'F**&F7F2F&F'F3#!'*>B*F5F'**F&F'F
1F'F(F'F7F'F;F1#!'FsIF@F7FAF(FC,4*(F&F'F1F'F(F2F3*&F&F'F1F'F**&F&F'F1F)F**(F&F'
F1F'F7F2F.F1#"'*>B*F5*(F7F'F&F'F(F'F;FLF'F(FAF7#"&2#=F@,4*(F&F'F7F'F(F2F**&F&F'
F7F'F3*(F&F'F7F'F1F2F.*&F&F'F7F)F*F7#!'\M\F5*(F1F'F&F'F(F'F;F(F>FAF'F1FV6",
I'C_wpnpw,6#>%)symbolicGF'61%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%#V0G%"VG%"i
G%)quat2rotG%#A1G%#B1G%"qG%"RG%"LG6"FjnC1>6$8$8%6$7$%"AG%"BG7$7$F)F'7$F2F)@%/9$
F'>8&-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fep6#8,w,6$%"xG%"yGF
jn6$%)operatorG%&arrowGFjn-&T'6#T%6#,&F_qF'*&,&9%F'!""F'F'&&T#F[s6#F'F'F'FjnFjn
6(FboFepFioF`rFaoFdp6#F26$7'Q!FjnFbs"#Q"#t"#O7'F[tFbsF\t"#WF^t/F`r;F'-%%nopsG6#
Fdp>Faq-Fcq6$-%'rndMatG6#F[rFat>8-w,6#F]pFjn6$FfrFgrFjn-I$<,>GFiq6%-I$<|gr>GFiq
6%z+6&&F_qFfs&F_q6#F2&F_q6#F)&F_q6#""%[[[[[[[[[][[mF'[[[[[[][[[[[mF'[[[][[[[[[[
[mFbs][[[[[[[[[[[mFbsz'Fhu\[[[[[[[[\[[m!"#[[[\[[\[[[[[mF2z'Fhu[[[\[[[[[\[[mF2\[
[[[[\[[[[[mF2-Feu6%z'Fhu\[[[[[[[[\[[mF2[[[\[[\[[[[[mF2z+Fhu[[[[[[[[[][[mF'[[[[[
[][[[[[mFbs[[[][[[[[[[[mF'][[[[[[[[[[[mFbsz'Fhu[[[[[[\[[\[[mFbv\[[\[[[[[[[[mF2-
Feu6%z'Fhu[[[\[[[[[\[[mFbv\[[[[[\[[[[[mF2z'Fhu[[[[[[\[[\[[mF2\[[\[[[[[[[[mF2z+F
hu[[[[[[[[[][[mF'[[[[[[][[[[[mFbs[[[][[[[[[[[mFbs][[[[[[[[[[[mF'FjnFjnFjn6#F'6$
7'F[tFbs"#:"#'*F^t7'F[tFbsFaw"#<F^t>6$8.8/6$-&I.LinearAlgebraG6$FhqFiq6#_F\x%/D
iagonalMatrixG6#&FaqFfs&FaqF[v>80-Fbu6&%"wGFcrFdr%"zG>81-F]u6#Fex>82-%$addG6#-F
ay6#-&%"|irG6#%"^G6%,&-I".G6$FhqFiq6$&F[y6$;F'F2;FjnFjnFgwF'FhwFbs%#~$GF2>8'7&-
%%diffG6$F_yFhx-Fiz6$F_yFcr-Fiz6$F_yFdr-Fiz6$F_yFix>Ffz-%%subsG6$/*$FcrF2F&-%$m
apG6$w,6#%#plGFjn6$FfrFgrFjn-%'expandG6#*&F_qF'FcrFbsFjnFjnFjn6#F'6$7'F[tFbs"#F
"#UF^t7'F[tFbsFe\l"#IF^t-Fc[l6$7%/Fdr*&FcrF'F1F'/Fix*&FcrF'F7F'/Fhx*&FcrF'F(F'F
fz>Ffz-Fh[l6$F_\lFfz@$0F_qF'OFfz>8(-%&minusG6$-%'indetsG6#Ffz-F^^l6#7#Faq>6$8)8
*-%,poly2matrixG6%Ffz-FdtF_^lFi]l>8+-%$srtG6$Ff^l-%%tdegG6#-F\r6#Fi]l6%7$%#cfG-
%/permuteColumnsG6%Fe^lFf^lF\_lFdpFepFjnFjnFjn6#""!657'F[tFbs"#;""'F^t7'F[tFbsF
)"#VFb`l7'F[tFbsF)""*"#X7'F[tFbs""("#$*Fb`l7'F[tFbsFg`l"#bFb`l7'F[tFbsF)FbwFb`l
7'F[tFbsF)Fj`lFb`l7'F[tFbsF)"#>Fb`l7'F[tFbsF)"#=Fb`l7'F[tFbsF)F\tFb`l7'F[tFbsF)
"#dFb`l7'F[tFbsF)"#")Fb`l7'F[tFbsF)"#DFb`l7'F[tFbsF)"#TFe`l7'F[tFbs"#B"#L"#_7'F
[tFbsF)"#SFb`l7'F[tFbsF)Fe`lFb`l7'F[tFbsF)Fh\lFb`l7'F[tFbsF)"#]"#JFjn
