M7R0
I'F_wpnp7&,4*&%#x1G"""%#w1G""$#"'"yd""&+D'*&F&F'F(F'#!'Jn6F,*(F&F'F(F'%#y1G""##
"'J#z"F,*(F&F'F(F'%#z1GF2F*F(#"',!Q$"'+]7*(F6F'F1F'F&F'#!'")z9"&]7$F6#"&La""&Dc
"F1#!$*>"$+##"$,*"%+5F',4*&F&F'F(F2F.F&F**&F1F2F&F'F**&F6F2F&F'F3#!'"=5#F9F'**F
&F'F1F'F(F'F6F'F;F1#!&Qi"F@F6FAF(FD,4*(F&F'F1F'F(F2F3*&F&F'F1F'F**&F&F'F1F)F**(
F&F'F1F'F6F2F.F1#"'"=5#F9*(F6F'F&F'F(F'F;FNF'F(FAF6#!$,*FF,4*(F&F'F6F'F(F2F**&F
&F'F6F'F3*(F&F'F6F'F1F2F.*&F&F'F6F)F*F6#!',!Q$F9*(F1F'F&F'F(F'F;F(F>FAF'F1FX6",
I'C_wpnpw,6#>%)symbolicGF'61%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_V0G%#_VG
%"iG%#A1G%#B1G%"qG%"RG%"LG%$eqsG6"F\oC0>6$8$8%6$7$%"AG%"BG7$7$F)F'7$F2F)@%/9$F'
>8&7#-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fgp6#8,w,6$%"xG%"yGF
\o6$%)operatorG%&arrowGF\o-&T'6#T%6#,&FaqF'*&,&9%F'!""F'F'&&T#F^s6#F'F'F'F\oF\o
6(FdoFgpF[pFcrFcoFfp6#F26$7'Q!F\oFes"#R"#u"#O7'F^tFesF_t"#XFat/Fcr;F'-%%nopsG6#
Ffp>Fcq7#-Ffq6$-%'rndMatG6#F^rFdt>6$8-8.6$-&I.LinearAlgebraG6$F[rF\r6#_Fgu%/Dia
gonalMatrixG6#&FcqFis&Fcq6#F2>8/-I$<,>GF\r6&%"wGFfrFgr%"zG>80-%)quat2rotG6#Fav>
81-%$addG6#-F_w6#-&%"|irG6#%"^G6%,&-I".G6$F[rF\r6$&Fhv6$;F'F2;F\oF\oFbuF'FcuFes
%#~$GF2>827&-%%diffG6$F]wFev-Fgx6$F]wFfr-Fgx6$F]wFgr-Fgx6$F]wFfv>Fdx-%%subsG6$/
*$FfrF2F&-%$mapG6$w,6#%#plGF\o6$FirFjrF\o-%'expandG6#*&FaqF'FfrFesF\oF\oF\o6#F'
6$7'F^tFes"#F"#UFat7'F^tFesFcz"#IFat-Fay6$7%/Fgr*&FfrF'F1F'/Ffv*&FfrF'F6F'/Fev*
&FfrF'F(F'Fdx>8'-Ffy6$F]zFdx@$0FaqF'OFa[l>8(-%&minusG6$-%'indetsG6#Fa[l-F]\l6#F
cq>6$8)8*-%,poly2matrixG6$Fa[lFh[l>8+-%$srtG6$Fd\l-%%tdegG6#-F_r6#Fh[l6%7$%#cfG
-%/permuteColumnsG6%Fc\lFd\lFi\lFfpFgpF\oF\oF\o6#""!647'F^tFes"#;""'Fat7'F^tFes
F)"#VF_^l7'F^tFesF)""*Fct7'F^tFes""("#&*F_^l7'F^tFesFc^l"#dF_^l7'F^tFesF)"#bF_^
l7'F^tFesF)"#>F_^l7'F^tFesF)"#=F_^l7'F^tFesF)"#QF_^l7'F^tFesF)Ff^lF_^l7'F^tFesF
)"#")F_^l7'F^tFesF)"#CF_^l7'F^tFesF)"#SFct7'F^tFes"#B"#K"#_F]_l7'F^tFesF)FatF_^
l7'F^tFesF)"#LF_^l7'F^tFesF)"#`"#JF\o
