M7R0
I.F_wpnp_2x2sym7&,0%"xG#!&FF'"&+D'%"wG#"%"[%F(*&%"yG""#F)"""#"&#*p#"&Dc"*&%"zGF
.F)F/#"&<7'F2*(F-F/F4F/F%F/#"&47%F2*&^##"&r=$"&]7$F/F%F/F/*&^##"&\K$F(F/F)F/F/,
0F%#!&Y2$F2F)F&*(F-F/F4F/F)F/F8*&F-F.F%F/F5*&F4F.F%F/F0*&F;F/F)F/F/*&^##"&pV#F(
F/F%F/F/,0F-FDF4F&*(F%F/F)F/F4F/F8*&F-F/F%F.F5*&F)F.F-F/F0*&^##!&r=$F>F/F4F/F/*
&^##!&pV#F(F/F-F/F/,0F-F&F4F**(F-F/F%F/F)F/F8*&F%F.F4F/F0*&F)F.F4F/F5*&FSF/F-F/
F/*&^##!&\K$F(F/F4F/F/6",
I.C_wpnp_2x2symw,6#>%)symbolicGF/62%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%#V0G
%"VG%"iG%)quat2rotG%#A1G%#B1G%#VVG%"qG%"RG%"LG6"F]oC1>6$8$8%6$7$%"AG%"BG7$7$""$
F/7$F.F`q@%/9$F/>8&-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fip6#8
,w,6$F%F-F]o6$%)operatorG%&arrowGF]o-&T'6#T%6#,&FdqF/*&,&9%F/!""F/F/&&T#F^s6#F/
F/F/F]oF]o6(FeoFipF\pFerFdoFhp6#F.6$7'Q!F]oFes"#Q"#t"#O7'F^tFesF_t"#WFat/Fer;F/
-%%nopsG6#Fhp>Ffq-Fhq6$-%'rndMatG6#F`rFdt>8-w,6#FapF]o6$FirFjrF]o-I$<,>GF^r6%-I
$<|gr>GF^r6%z+6&&FdqFis&Fdq6#F.&Fdq6#F`q&Fdq6#""%[[[[[[[[[][[mF/[[[[[[][[[[[mF/
[[[][[[[[[[[mFes][[[[[[[[[[[mFesz'F[v\[[[[[[[[\[[m!"#[[[\[[\[[[[[mF.z'F[v[[[\[[
[[[\[[mF.\[[[[[\[[[[[mF.-Fhu6%z'F[v\[[[[[[[[\[[mF.[[[\[[\[[[[[mF.z+F[v[[[[[[[[[
][[mF/[[[[[[][[[[[mFes[[[][[[[[[[[mF/][[[[[[[[[[[mFesz'F[v[[[[[[\[[\[[mFev\[[\[
[[[[[[[mF.-Fhu6%z'F[v[[[\[[[[[\[[mFev\[[[[[\[[[[[mF.z'F[v[[[[[[\[[\[[mF.\[[\[[[
[[[[[mF.z+F[v[[[[[[[[[][[mF/[[[[[[][[[[[mFes[[[][[[[[[[[mFes][[[[[[[[[[[mF/F]oF
]oF]o6#F/6$7'F^tFes"#:"#'*Fat7'F^tFesFdw"#<Fat>6$8.8/6$-&I.LinearAlgebraG6$F]rF
^r6#_F_x%/DiagonalMatrixG6#&FfqFis&FfqF^v>80-Feu6&-Fhu6&""!^#FesF^yF]y-Fhu6&Fes
F]yF]yF/-Fhu6&^#F/F]yF]yFcy-Fhu6&F]yFesF/F]y>81-I".G6$F]rF^r6$Fhx-Feu6&F)F%F-F4
>82-F`u6#Fgy>83-%$addG6#-Fez6#-&%"|irG6#%"^G6%,&-Fiy6$&F_z6$;F/F.;F]oF]oFjwF/F[
xFes%#~$GF.>8'7&-%%diffG6$FczF)-F[\l6$FczF%-F[\l6$FczF--F[\l6$FczF4>Fh[l-%$mapG
6$%'expandGFh[l@$0FdqF/OFh[l>8(-%&minusG6$-%'indetsG6#Fh[l-Fa]l6#7#Ffq>6$8)8*-%
,poly2matrixG6%Fh[l-FgtFb]lF\]l>8+-%$srtG6$Fi]l-%%tdegG6#-Far6#F\]l6%7$%#cfG-%/
permuteColumnsG6%Fh]lFi]lF_^lFhpFipF]oF]oF]o6#F]y657'F^tFes"#;""'Fat7'F^tFesF`q
"#VFd_l7'F^tFesF`q""*"#X7'F^tFes""("#$*Fd_l7'F^tFesFi_l"#bFd_l7'F^tFesF`qFewFd_
l7'F^tFesF`qF\`lFd_l7'F^tFesF`q"#cFd_l7'F^tFesF`q"#AFd_l7'F^tFesF`q"#=Fd_l7'F^t
FesF`qF_tFd_l7'F^tFesF`q"#dFd_l7'F^tFesF`q"#DFd_l7'F^tFesF`q"#TFg_l7'F^tFes"#B"
#L"#_7'F^tFesF`q"#SFd_l7'F^tFesF`qFg_lFd_l7'F^tFesF`q"#IFd_l7'F^tFesF`q"#]"#JF]
o
