folder = fileparts(which('test_num_all.m'));
load(strcat(folder, '\_results\Err_fl_relpose_7p_fr_c.mat'));
load(strcat(folder, '\_results\Err_z_relpose_7p_fr_c.mat'));
load(strcat(folder, '\_results\Err_F_relpose_7p_fr_c.mat'));
load(strcat(folder, '\_results\Err_z_relpose_7p_fr_sota_c.mat'));

bwd = 0.3;
nbins = 60;
clr1 = [1 0.3 0.3];
clr2 = [0.3 0.3 1];
clr3 = [0.6 0.6 0.6];
clr4 = clr2;
err_f = log10(Err_fl_relpose_7p_fr);
err_z = log10(Err_z_relpose_7p_fr);
err_F = log10(Err_F_relpose_7p_fr);
err_z_sota = log10(Err_z_relpose_7p_fr_sota);
disp([median(err_f), median(err_z), median(err_F)]);
[f1,xi1] = ksdensity(err_f);
h1 = plot(xi1,f1,'color',clr1,'linewidth',2);
%hr1 = histogram(err_f,nbins,'binwidth',bwd,'displaystyle','stairs','linewidth',2);
%hr1.FaceColor = clr1;
%hr1.EdgeColor = clr1;
hold on;
[f2,xi2] = ksdensity(err_z);
h2 = plot(xi2,f2,'color',clr2,'linewidth',2);
%hr2 = histogram(err_z,nbins,'binwidth',bwd,'displaystyle','stairs','linewidth',2);
%hr2.FaceColor = clr2;
%hr2.EdgeColor = clr2;
hold on;
[f3,xi3] = ksdensity(err_F);
h3 = plot(xi3,f3,'color',clr3,'linewidth',2);
%hr3 = histogram(err_F,nbins,'binwidth',bwd,'displaystyle','stairs','linewidth',2);
%hr3.FaceColor = clr3;
%hr3.EdgeColor = clr3;
hold on;
[f4,xi4] = ksdensity(err_z_sota);
h4 = plot(xi4,f4,'-.','color',clr4,'linewidth',2);
%hr4 = histogram(err_z_sota,nbins,'binwidth',bwd,'displaystyle','stairs','linewidth',2);
%hr4.FaceColor = clr4;
%hr4.EdgeColor = clr4;
%hold on;
%h1 = plot(1:1,'color',clr1);
%hold on;
%h2 = plot(1:1,'color',clr2);
%hold on;
%h3 = plot(1:1,'color',clr3);

[~,hobj] = legend([h1,h2,h3,h4],{'focal length $f$ (our)','rad. dist. $\lambda$ (our)','fund. matrix $F$ (our)~','rad. dist. $\lambda$ (SOTA)'},'fontsize',28,'fontname','Times New Roman','location','northwest');
hl = findobj(hobj,'type','line');
set(hl,'linewidth',3);
ht = findobj(hobj,'type','text');
set(ht,'interpreter','latex','fontsize',28,'fontname','Times New Roman');

axis([-15 1 0 0.32]);
xlabel('$\log_{10}$ of relative error','interpreter','latex');
ylabel('frequency');

set(gca,'fontsize',30,'fontname','Times New Roman');
set(gcf,'PaperPositionMode','auto');
set(gcf,'PaperOrientation','landscape');
set(gcf,'PaperPosition',[1 1 28 19]);
print(gcf,'-dpdf',strcat(folder,'\_results\fig3a.pdf'));