M7R0
I0F_tdoa_pose_5pt7',^o%"zG#!(6<O""(+D"y%"xG#")Z&HT%")++DJ%"uG#"'BK7"'+]7%"vG#"%
R;"&+D"%"yG#"'rpe"(+]7$*$F-""##!+*Q%)*pE",++++D"*$F1F:#!,*)o%y16F=*&F-F:F)F:#"%
R"*"&+D'*&F5"""F1F:#!'H05F8*&F1FFF%FF#!#6"#]*&F1F:F5F:FB*$F%F:FB*$F)F:#!&hL&FD*
$F5F:FP*&F)FFF1F:F**&F)F:F1F:FP*&F5FFF-F:F6*&F5F:F-F:FP*&F%FFF-F:#"(*y]zF(*&F%F
FF1F:FX*&F%F:F-F:FP*&F%F:F1F:FP*&F-FFF)FF#!$\""$D"*&F1FFF5FFFhn*&F)FFF-F:#!(`zb
(F,*&F-FFF1FF#"%(4*"&++&*&F-FFF%FF#!$F)"$+&*(F5FFF1FFF-FFFdo*(F)FFF1FFF-FFFJ*(F
%FFF)FFF-FFF:*(F%FFF5FFF1FFF:**F-FFF)FFF1FFF5FFF:#!+*)o*)ynF=FF,^oF%#!((4%*o")+
++]F)#")r^d5"*++++&F-#"%$*[FboF1#"%p6FboF5#"(Vl_#FdpF9#",p!*Gr!["-+++++5F>#"+p!
*3+?F]qFA#"'r[)*"(+++"FE#!*dMZk"FdpFI#!$n"FfoFMF`qFNF`qFO#!&H^"FbqFRFgqFSFbpFTF
gqFUFipFVFgqFW#"'.f5FapFZFiqFenFgqFfnFgqFgn#!"(FLF[oF[rF\o#!*H[U)oFdpF_o#"'Ln6"
'++]Fco#!$*pFfoFgoFbrFhoFeqFioF:FjoF:F[pF:#!*J4"))HF]qFF,^oF%#")()R2u"*+++D"F)#
!)$Gj:#")+++DF-#"'*R0""'++5F1#!'8ujFarF5#"*@lSI"FirF9#!,.FG1r#",+++++&F>#!,.F[,
Y"FfsFA#"'6L5"'++DFE#!)zM%=*FirFI#!$*))FfoFMFisFNFisFO#!'*oY"F[tFRF`tFSFjrFTF`t
FUFbsFVF`tFW#!*8g<0"FirFZFbtFenF`tFfnF`tFgn#"$<(FfoF[oFdtF\o#")<n=:F\sF_o#!'$oI
"F_sFco#"$Z""$+"FgoFjtFhoF^tFioF:FjoF:F[pF:#!,.F38%GFfsFF,^oF%#")h<g8")++]iF)#!
)pI<GF\sF-#"&6#QFboF1#"%,%)F0F5#!(zS>'FbuF9#!,(4v&=X$"-+++++DF>#!-(4DQ"y:F]vFA#
"&">]F[tFE#"(@fb"FbuFI#"#J"$]#FMF`vFNF`vFO#!'4)*>F[tFRFgvFSFcuFTFgvFUFiuFVFgvFW
#!)R#[T&FbuFZFivFenFgvFfnFgvFgn#"$r#FfvF[oF[wF\o#"(Jp2(F\sF_o#"%rVFboFco#"$T"F
\uFgoFawFhoFdvFioF:FjoF:F[pF:#!,(4DQL&)F]vFF,^oF%#")(*fvdFbuF)#!(2w0#FirF-#"&"e
SF[tF1#"&R?%FDF5#!(L:8#F,F9#!+HYi"=#F]vF>#"-r`7i06F]vFA#"'zwBF[tFE#")n%=6%F,FI#
"$t"FjnFMFdxFNFdxFO#!&@B"F[tFRFjxFSFhwFTFjxFUF^xFVFjxFW#!(.S*HFbuFZF\yFenFjxFfn
FjxFgn#"$V#FfvF[oF^yF\o#")$R#pRFirF_o#"&"*)GF0Fco#"$n"FfoFgoFdyFhoFhxFioF:FjoF:
F[pF:#",r`7&*)\F]vFF6",
I0C_tdoa_pose_5ptw,6#>%)symbolicGFF61%&_nameG%&_sizeG%#_AG%"iG%#uuG%#csG%"CG%"N
G%$eqsG%"kG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FhyC.>6$8$8%6$7$%"UG%*cosanglesG7$7$
""$""&7$FFF[\l@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&Fc[l6#8'Fhy/F]]l;FF-%%nopsG6#
Fb[l>Fb\l7#-Fe\l6$-I'MatrixG6$%*protectedG%(_syslibG6$Fj\lw,6$F)F5Fhy6$%)operat
orG%&arrowGFhy-&T'6#T%6#,&F_\lFF*&,&9%FF!""FFFF&&T#Fe^l6#FFFFFFFhyFhy6(F`zFc[lF
bzF]]lF_zFb[l6#F:6$7'Q!FhyF\_l"#P"#s"#O7'Fe_lF\_lFf_l"#VFh_lF^]l>6$8(8)6$&Fb\lF
`_l&Fb\l6#F:>8*-I$<,>G6$Fj]lF[^l6%F)F5F%>8+-Ff`l6%F-F1FF>8,7#-Fe\l6$,&*&-I".G6$
Fj]lF[^l6$),&&F]`l6$;FhyFhy8-FFFd`lF\_l%#%TGFj`lFF-Feal6$)Fj`lF^blFialFFFF*&-Fe
al6$*&&F^`l6$FFF]blF:FhalFFFialFF-Feal6$FablFj`lFFF\_l/F]bl;FFF[\l>8.-%$mapG6$%
'expandGF^al@$F^\lOF]cl>8/-%&minusG6$-%'indetsG6#F]cl-Fjcl6#Fb\l>6$8081-%,poly2
matrixG6$F]clFecl>82-%$srtG6$Fadl-%%tdegG6#&FeclFhy6&7#-%/permuteColumnsG6%F`dl
FadlFfdlFfdlFb[lFc[lFhyFhyFhy6#F`\l627'Fe_lF\_l"#;""'Fh_l7'Fe_lF\_lFj[lFLFj_l7'
Fe_lF\_lFj[l""*"#X7'Fe_lF\_l""("#bFj_l7'Fe_lF\_lF]fl"#$*Fj_l7'Fe_lF\_lFj[l"#CFj
_l7'Fe_lF\_lFj[lFfelFj_lFcfl7'Fe_lF\_lFj[l"$4"Fj_lFafl7'Fe_lF\_lFj[l"#RF[fl7'Fe
_lF\_l"#AFev"#_7'Fe_lF\_lFj[l"#QFj_l7'Fe_lF\_lFj[lFh_lFj_l7'Fe_lF\_lFj[lFevFj_l
7'Fe_lF\_lFj[l"#^FevFhy
