M7R0
I/F_toa_46_w_sat7',bo%"vG#".JH)G7xF".++++++"%"xG#".4o\I/2#F(%"yG#!-6fDL6=F(%"wG
#"-*pT)>?:F(*$F%""##"+VFy_$)F(*&F%"""F/F7#!-Tz\<tD"-+++++?*&F%F7F)F7#!.r&*zin`"
F(*&F%F7F,F7#"-Ve#eUV#F(*$F/F3#!,dco=.&F(*&F/F7F)F7#!-H"Q)z'=""-+++++5*&F/F7F,F
7#"-x/+446"-++++]7*(F)F7F/F7F%F7#"-ZO8+aR"-+++++]*(F,F7F/F7F%F7#!,nk5ol%",++++D
'*(F,F7F)F7F%F7#"-Bu@vR5"-+++++D*(F,F7F)F7F/F7#!-Bfi.bSFO*$F)F3#!->Hc\YmF(*&F)F
7F,F7#"-B2.(3'zFO*$F,F3#"-t%*G$>7$FO*&F/F7F%F3#"-87/oPXFW*&F)F7F%F3#!-`FJL!3"FW
*&F,F7F%F3#!,^5S0D)FO*&F/F3F%F7#!-8\%Q,T"FW*&F)F3F%F7#",(o09aC",++++D"*&F,F3F%F
7#"-,<wQ/NFO*&F)F7F/F3#"-VsUK<5FW*&F,F7F/F3#",\tk:5#FO*&F)F3F/F7#!,<tug$HFW*&F,
F3F/F7#!,h;&[(>#",+++++&*&F,F7F)F3#!,T;**R-%FK*&F)F7F,F3#!-Fi`65bFO*$F%""$#!-8f
ioy<FG*$F/Feq#",Baf$ezFO*$F)Feq#",rXAGb)FG*$F,Feq#!-jC:&\.#FO#!,nLCf+&F]qF7,boF
%#",`c7Fi'FKF)#!,ZGIDS(",++++]#F,#!.tbNg/B"FWF/#",t97?&=FWF2#!.n:#Rt!3#F(F6#"-R
w\9vBFOF;#!-4O3:*y#FOF>#"."H@])4,)F(FA#!,t)eMw[FOFD#".")Q[Obf"FOFH#"."=/R(Gr"F(
FL#"-\WFG8OFOFP#"*nRu[&"+++++!)FT#!.Zq3yx^"F(FX#!-nl'zo:%FWFen#".@'Hb$Qz#F(Fhn#
".TV*)z?y&F(F[o#"-$)f=0bnFWF^o#!,\cSJ'R",+++]7$Fao#"+,bKO<"+++++]Fdo#!.H22Sn&[F
(Fgo#".r!e"HT1"F(Fjo#!-"G\#GoZFOF^p#!.T0e7#=6F(Fap#!->QWTT?F:Fdp#!,\dS<j'FWFgp#
!-^ofp\hF(Fjp#!-4'=Zvp'F(F^q#"-2VqilUFWFaq#",B`Jl\(F(Fdq#".j6'e><:F(Fhq#!-LnYGL
JF(F[r#!-TynD6xF(F^r#!-HgWR!e&F(#"+VNNb'*FSF7,boF%#"-r"e#G"*fFOF)#"-zLWC*>&FOF,
#!-Ta\w67FOF/#"-,!>ID(GFOF2#"-*3nf#pWFWF6#!-nvRWm>FGF;#!-z4DD/bFOF>#!-R9]VnZFKF
A#!,@2t))\&FOFD#"+H7^fsF\uFH#"-.fvdC\FGFL#",dT&GOGF\uFP#!->"H$\v()FOFT#"-pi#ef"
[FOFX#"-"RhIbX"FWFen#!,.4RO&oFSFhn#!.pbaiR`"FOF[o#!-ZSe*p/*FWF^o#!-<"*3xt;FWFao
#!,H0=8#)*FKFdo#"-z"RWo7'FOFgo#"-tU"HEA$FOFjo#",6a>R+"F\uF^p#".L6yvhg"FOFap#!,x
F2l%>FOFdp#!,p`/F(QFSFgp#"-$p!R*='=FOFjp#",t[nW5%FOF^q#!+(\ctM%FKFaq#!,p0]!pvFG
Fdq#!,$eF-$[$FOFhq#"+>lf(G"FOF[r#"+6W")yw",+++++#F^r#!-4!)pDVAFO#!->fX54BFWF7,h
s*(F%F3F/F7F)F7#!-Rje0FuFO*(F%F7F/F3F)F7#",6[YtK%",+++++%*(F%F7F/F7F)F3#!-pH(*[
CJFW*(F%F3F/F7F,F7#!.R,`>$[9FO*(F%F7F/F3F,F7#".LjP(yg>F(*(F%F7F/F7F,F3#!-nCXT$)
pF(*(F%F3F)F7F,F7#"-Jy.`'\%FO*(F%F7F)F3F,F7#!.P$4lok8FO*(F%F7F)F7F,F3#!.4sDzbZ"
F(*(F/F3F)F7F,F7#!-2*=S*obFO*(F/F7F)F3F,F7#"-L)o]j"yF(*(F/F7F)F7F,F3#",2>1XU"Fa
[lF%#"+6#\Wf$FSF)#"-F-'eaN%FKF,#".$oqFD75FWF/#",nxGFh)FKF2#"-.fLk*o)FWF6#!-jcz/
dOF:F;#"-(z2zS'HF(F>#!.j%f'*HPBFOFA#!-ZnlXc=F(FD#!->c_ilrFWFH#!-fO%)e5&*F(**F%F
7F/F7F)F7F,F7#!-T@\V`9FGFL#!,P2-`N"Fa[lFP#"-([I`Nx%FWFT#"-.xey]BFOFX#".,at3\l#F
OFen#!.\YO6)eMF(Fhn#!.JKDQ5!oF(F[o#!.@L')e9X&F(F^o#!-@%H)zgwF(Fao#!-P:7l16F:Fdo
#"**>N#H)F_tFgo#"-V:+MCVF(Fjo#"-.;&y.t"FWF^p#".([\wJ$\'F(Fap#"-R_;">()*F(Fdp#!.
*3#Q>$o6F(Fgp#".dOE(*Rj#F(Fjp#"-<[_KYQFWF^q#!-V!*o3MOFWFaq#"-8p_ap")FO*&F%FeqF/
F7#"..u(GQTGF(*&F%F3F/F3#!-`^V@`sFO*&F%FeqF)F7#"-xij\[LF:*&F%F3F)F3#".d))eXP."F
O*&F%FeqF,F7#".L['ei)H#F(*&F%F3F,F3#!.p'*f#pH8FO*&F%F7F/Feq#"-6S?/vKF(*&F%F7F)F
eq#!-f&yF#4bFO*&F%F7F,Feq#!-h2PR!H#F:*&F/FeqF)F7#!*2Gs,$"*++++)*&F/F3F)F3#!-8&)
=%G["FW*&F/FeqF,F7#!,6u(RWIFK*&F/F3F,F3#!,.,!>SjFO*&F/F7F)Feq#!**["z:&"+++++D*&
F/F7F,Feq#"-nla3g?F(*&F)FeqF,F7#!-nm%\(ecF(*&F)F3F,F3#",r%pj\CF]p*&F,FeqF)F7#"-
HS+;C?F:Fdq#!-^Xl3UnF(Fhq#"-jKl3<<F(F[r#"-^^b(3J)F(F^r#".(z9xKv=F(#!-"*o(4#RBFW
F7*$F%""%#!,xoPBe(F]\l*$F/F^fl#!,rh6dQ"F:*$F)F^fl#!,rnf9m*FK*$F,F^fl#!,>ukQ9"F(
,do!""F7*(%"zGF7F%F7F/F7#"*n`UZ""*++++#*(F]glF7F%F7F)F7#!*2-9j&"+++++5*(F]glF7F
%F7F,F7#!).Z^f")++DJ*(F]glF7F/F7F)F7#")h7MY")+++]*(F]glF7F/F7F,F7#"(p&>QFdgl*(F
]glF7F)F7F,F7#!+L&*o5:Fdgl*(F]glF7F%F3F/F7#!)2aL]"*+++]#*(F]glF7F%F3F)F7#!)tb%y
$"*+++D"*(F]glF7F%F3F,F7#"+deU#G#Fdgl*(F]glF7F%F7F/F3#"*$)R&>7Fdgl*(F]glF7F%F7F
)F3#!**pot;"*++++&*(F]glF7F%F7F,F3#!*fSq6(Fdgl*(F]glF7F/F3F)F7#!*f*RZ9Fdgl*(F]g
lF7F/F3F,F7#"*$ek'3$Fdil*(F]glF7F/F7F)F3#!)jrX[Fdgl*(F]glF7F/F7F,F3#")"z`7(Fdgl
*(F]glF7F)F3F,F7#"*fTt"HFfhl*(F]glF7F,F3F)F7#!*Z"*o))*FdglF]gl#")r)H$GF\hl**F]g
lF7F%F7F/F7F)F7#"$6'"(++D"**F]glF7F%F7F/F7F,F7#!*8#f'>#F`gl**F]glF7F%F7F)F7F,F7
#"+`OqWJFdgl**F]glF7F/F7F)F7F,F7#!*T'R[6Fdil*&F]glF7F%F7#!*z!oD*)Fdgl*&F]glF7F)
F7#!+x-XT6Fdgl*&F]glF7F,F7#!)t\77F`gl*&F]glF7F/F7#!*zn&f9Fdgl*&F]glF7F%F3#!)f`y
c"*++++"*&F]glF7F/F3#"(JL^"")+++S*&F]glF7F)F3#"'jrg")+++5*&F]glF7F,F3#")H"Qr&Fh
\m*&F]glF7F%Feq#"("3d^Fdgl*&F]glF7F/Feq#!)$Gj%))Fdgl*&F]glF7F)Feq#!)RA'>#F`gl*&
F]glF7F,Feq#!*>*)Rh"F`gl6",
I/C_toa_46_w_satw,6#>%)symbolicGF766%&_nameG%&_sizeG%#_AG%#_FG%&_varsG%$_C0G%$_
V0G%#_VG%"iG%#M1G%#vvG%"HG%"bG%"kG%"CG%%adjHG%%detHG%"SG%#ddG%$eqsG6"F`^mC5>6$8
$8%6$7#%"MG7#7$"#eF7@%/9$""!>8&7#-%$seqG6$-%'rndMatG6#&&F``m6#8,F`^m/Fgam;F7-%%
nopsG6#F_`m>F\am7#-F_am6$-I'MatrixG6$%*protectedG%(_syslibG6$Fdamw,6$F)F,F`^m6$
%)operatorG%&arrowGF`^m-&T'6#T%6#,&Fi`mF7*&,&9%F7F[glF7F7&&T#F_cm6#F7F7F7F`^mF`
^m6(Fh^mF``mF__mFgamFg^mF_`m6#F36$7'Q!F`^mF[gl"#P"#s"#O7'F^dmF[glF_dm"#VFadmFha
m>8--%(convertG6$&F\amFicmI'VectorG6$FdbmFebm>8.7'F7F%F/F)F,>6%8/80816%Fj`mFj`m
Fj`m?(FgamF7F7""&%%trueGC&>82-I$<,>GFebm6%-I$<|gr>GFebm6%&Fedm6#,&FcemF7F7F7&Fe
dm6#,&FcemF7F3F7&Fedm6#,&FcemF7FeqF7-F_fm6%Fdfm&Fedm6#,&FcemF7F^flF7&Fedm6#,&Fc
emF7FfemF7-F_fm6%FgfmF_gm&Fedm6#,&FcemF7""'F7>Faem,&FaemF7*&&F]emFfamF7FjemF7F7
>Fbem,&FbemF7*&&Fedm6#-&%"|irG6#%"+G6%7#-%"$G6#;""(""*%#~$GFcemF7F[hmF7F7>Fcem,
&FcemF7F]imF7>83-&I.LinearAlgebraG6$FdbmFebm6#%(AdjointG6#Faem>84-&Feim6#%,Dete
rminantGFiim>85&Fedm6#-Fbhm6%7#-Fihm6#;F7F]imF^imFcem>Fajm)-F\fm6%-F_fm6%&FajmF
icm&Fajm6#F3&Fajm6#Feq-F_fm6%&Fajm6#F^fl&Fajm6#Ffem&Fajm6#Fggm-F_fm6%&Fajm6#F\i
m&Fajm6#"")&Fajm6#F]im%#%TG>86&Fedm6#-Fbhm6%7#-Fihm6#;"#5"#8F^imFcem>877$-F_am6
$,&-I".G6$FdbmFebm6$,&-Fj]n6$)&Fajm6$;F`^mF`^mFgamFf\nFbimF7-Fj]n6$,$)FbemFf\nF
3FbimF7Fa^nF7*&&Fh\nFfamF7F[jmF7F[gl/Fgam;F7Feq,&-Fj]n6%Fg^nFbimFbemF7*&&Fh\nFh
[nF7F[jmF7F[gl>Fd]n7$&Fd]nF`^m,&*&F]glF7F[jmF7F7F[glF7>8'-%$mapG6$%'expandGFd]n
@$Fh`mOFg_n>8(-%&minusG6$-%'indetsG6#Fg_n-Fd`n6#F\am>6$8)8*-%,poly2matrixG6$Fg_
nF_`n>8+-%$srtG6$F[an-%%tdegG6#&F_`nF`^m6&7#-%/permuteColumnsG6%Fj`nF[anF`anF`a
nF_`mF``mF`^mF`^mF`^m6#Fj`m6=7'F^dmF[gl"#;FggmFadm7'F^dmF[glFeq"#LFcdm7'F^dmF[g
lFeqF]im"#X7'F^dmF[glF\im"#bFcdm7'F^dmF[glF\im"#$*Fcdm7'F^dmF[glFeq"#IFcdm7'F^d
mF[glFeq"#BFcdm7'F^dmF[glFeq"#@Fcdm7'F^dmF[glFeqFc\nFc\n7'F^dmF[glF\im"#')Fcdm7
'F^dmF[glF\imF^cnFcdm7'F^dmF[glF\imFadmFcdm7'F^dmF[glF\im"#:Fcdm7'F^dmF[glFeq"#
NFcdm7'F^dmF[glFeq"#RFcdm7'F^dmF[glFeq"#AFcdm7'F^dmF[glFeq"#dFcdm7'F^dmF[glFeq"
#DFcdm7'F^dmF[glFeqFhbnFcdm7'F^dmF[glFeq"#EFcdm7'F^dmF[glFeq"#CFcdm7'F^dmF[glFe
qFicnFdbn7'F^dmF[glF[dn"#J"#_7'F^dmF[glFeq"#QFcdm7'F^dmF[glFeqFadmFcdm7'F^dmF[g
lFeqFgdnFcdm7'F^dmF[glFeq"#^FgdnF`^m
