M7R0
I+F_toa3d_467,,bo%"xG#")*psW""*++++&%"vG#")*e5C""*+++D"%"yG#")\,CYF(%"wG#!*2lir
)"+++++5*$F)""$#!*^<:i#F3*$F)""##!**p!fm"F(*$F0F5#"(t6o""(+++&*$F0F9#!*"o*Gr*F3
*$F%F5#!)Jb(H""*++++"*$F%F9#"(du!H")+]i:*$F-F5#!*\<b\#F(*$F-F9#")dknr"*++++#*(F
%"""F0FSF)FS#!*\pSX"F,*(F-FSF0FSF)FS#!*2#o*Q*F3*(F-FSF%FSF)FS#!)xq?X")+++S*(F-F
SF%FSF0FS#!*p'pJSF(*&F0FSF)F9#!*F,g`*F3*&F%FSF)F9#"*z`T<&F3*&F-FSF)F9#!*$e#3W""
*+++]#*&F)FSF0FS#"*B-E$[F(*&F)FSF%FS#!*ntE;"F,*&F)FSF-FS#!*"o'4P$F3*&F0F9F)FS#"
+(z7k?"F3*&F%FSF0F9#"*d5a$*)F3*&F-FSF0F9#!**egqkF3*&F0FSF%FS#"*8;$GKF(*&F0FSF-F
S#!*45!)*pF3*&F%F9F)FS#"(r)H%*")++]i*&F%F9F0FS#")Jd4XF(*&F-FSF%F9#"+@a!e7"F3*&F
%FSF-FS#!+2S#=;"F3*&F-F9F)FS#!*"z.&[$F(*&F-F9F0FS#"*@&)>e(F3*&F-F9F%FS#!+.BrR@F
3#!)ReY>FQFS,boF%#!).WvMF3F)#!)8B()=FQF-#!*p*=G9F(F0#!)`pmnFQF4#"(Tpz&")+++]F8#
!)hLt6FFF<#"*Z([#y"FcoF@#"'LC**")+++DFC#!(dt*yF(FG#")4K]?F(FK#!),<[]")++DJFN#!*
B+<*GF3FR#"*.mt"HF3FV#!*$Qk=BFcoFY#!)tS^yFcoFgn#"+TYjy7F3Fjn#!*<V?s"F(F]o#"*^%R
-5F3F`o#")VK!3&F3Fdo#!*\Xg&>FQFgo#"(B0M)FfnFjo#!)L%Gf"F_qF]p#!*h6*\bF(F`p#"*<gY
S'F3Fcp#!*p*GyCFcoFfp#"*(ptPQF3Fip#!*2N@b*F3F\q#!(4-.%FFF`q#!*@;c7"F(Fcq#")fI$H
*F3Ffq#!*2e)HSF3Fiq#!*J#H9OFcoF\r#!)`ke^F(F_r#"*`:\j"F3#!)rQ.&*F3FS,boF%#!)`&>[
)F(F)#!)FV^YF(F-#")`l'H%F3F0#!+z6=]9F3F4#!)jZEUF3F8#"*(\AqkF3F<#!*,4Q\#F(F@#!)@
h(z'F_qFC#"(,d"="(++]#FG#!+([tR;"F3FK#"'f_V"(++D"FN#"*x8!f;F3FR#"(tvn'F?FV#"+nq
V%R"F3FY#!*FWCd"F(Fgn#"*H[gs$FQFjn#"+4G*)=5F3F]o#!*`.l)>FcoF`o#!*zM\5&F3Fdo#")^
G0SF(Fgo#"*x'*pV)F3Fjo#"*@KP/'F(F]p#")"yQq(F3F`p#!)<#=$>")++]7Fcp#"***e1F#FcoFf
p#!+\=bk9F3Fip#"*<Jaf)F3F\q#!)">bU$FQF`q#!*J9`'RF(Fcq#!*RcCd)F3Ffq#"*fT4S&F(Fiq
#!*$3_Y6F(F\r#!*<"zL8F(F_r#"*$*>bX"F3#!*j))>1"FQFS,`qF%#")2@NQF3F)#!*VcSo"F(F-#
"(@Lp(Fco%"zG#"'"3\&"'++DF0#"*JM')o"F(F4#!*j?#oHF3F8#!*d$G1:FQF<#"*"yrVKFcoF@#"
*d]5v'F(FC#!)*pl;#F,FG#")Rp:NFcoFK#!*(4%=/#FcoFN#!)ZZ%>(F(FR#"*RBRf&F(FV#!+$R18
7"F(FY#!+()*335"F3Fgn#"*<?r=(F(Fjn#!*rq%>RFcoF]o#"*4\q,&F3F`o#!*\#3@YF(Fdo#!*fN
[8"F,Fgo#!)dh]9F,Fjo#!+^x:N7F3F]p#!*PsNf*F3F`p#")8P!G%F]tFcp#!*8YzM%FQFfp#")F8g
%)F,Fip#!*t*)4n"FFF\q#!),_ASFFF`q#!(V)>7F_qFcq#"*xB7J&F(Ffq#"(f(\rF(Fiq#!*2QaV$
FcoF\r#!($=9&)F_qF_r#!*.*y*Q)F(*&F_\lFSF)F9#"$h*"&+D'*&F_\lFSF)FS#"&rH#Fd`l*&F_
\lFSF0F9#"'HJRFb\l*&F_\lFSF0FS#"'2YY"'+]7*&F_\lFSF%F9#"&"oVFd`l*&F_\lFSF%FS#!'p
[:Fd`l*&F_\lFSF-F9#"$@""$+"*&F_\lFSF-FS#!%^")"%+D#"(B9(GFfnFS*(F_\lFSF)FSF0FS#"
&P%>Fd`l*(F_\lFSF)FSF%FS#!%zk"&]7$*(F_\lFSF)FSF-FS#!$T$"%]7*(F_\lFSF0FSF%FS#!'V
58Fd`l*(F_\lFSF0FSF-FS#!%(*oF\bl*(F_\lFSF%FSF-FS#"%*H#Fibl,`qF%#"*()*GB9F3F)#"*
.'otPF(F-#!*")Gj!=F3F_\l#"'F*3"Fd`lF0#"+"p"f+6F3F4#"*Lm<$GF3F8#"*L15a'F3F<#"*"o
we9F3F@#"*H%o^BFQFC#!*zA#HFF(FG#"*2'HV_F3FK#")x@."*F_qFN#"*xkJP)F(FR#!)RB+EFazF
V#"*HQM_'F3FY#!)*[v'[FQFgn#!+p+$oi"F(Fjn#"*@)pzTF(F]o#!)8$f;*F3F`o#"+Z6[D>F3Fdo
#"*hH3%zF(Fgo#!)LDWJFfsFjo#"*dGGN*F3F]p#"*\px^%F3F`p#"*"H,tCF3Fcp#!*j5)eUF(Ffp#
")`P5yFQFip#!)h^KGF,F\q#"*^$yvWF3F`q#"**)QaN$F(Fcq#!(PT%eFfsFfq#!*PY5<*F3Fiq#"*
`6@%yFcoF\r#"*p2gu"FcoF_r#!*RSNu#F(Fa`l#"%BTFeblFe`l#"'nw5Fd`lFh`l#!'())Q#F^alF
[al#!&$)z*F^alF_al#F[bl"&+D"Fbal#"&.;#F^alFeal#"$4#FhalFial#!&Z0#"%+]#"*h%y$R"F
(FSF_bl#"%zN"%DJFbbl#!&\&\Fd`lFfbl#!$.("$+&Fjbl#"'B:GF^alF]cl#!%JNFjhlF`cl#"$8*
Fibl,`qF%#!(L)eoF,F)#")6^IrF3F-#")H?byFQF_\l#!'*\t%Fb\lF0#"*x#zV5FQF4#")@BNJFco
F8#"*4i8r"F3F<#!(r84%F,F@#"*nzsx%F3FC#!)Fb")=F_qFG#"*FI[y"F(FK#"(j_f#FazFN#"(<.
C$")+++?FR#!*(o$)>?F(FV#"(^]T""(+++)FY#!*4)fFZF(Fgn#")24JLF(Fjn#!*.z93"F3F]o#")
jX!Q*F(F`o#"*rF!)>(F3Fdo#!).xO%)FcoFgo#!)(4)[!)FcoFjo#"*"e[**RF(F]p#!+\]945F3F`
p#"*dGHF"FcoFcp#!**e\NZF3Ffp#")zJiwF(Fip#"*h*4!f$F(F\q#"((zj&)FcoF`q#")(['))[F_
qFcq#")HYZlF_sFfq#!)8kwXFQFiq#"*t(*y>#FcoF\r#"*rrBK"F(F_r#!*H="=\F(Fa`l#"%jAF^a
lFe`l#"$z&"&++"Fh`l#!'(*\>F^alF[al#!'6B<"&++&F_al#!&"p?Fd`lFbal#"&"p?FchlFeal#"
&B4"FjhlFial#!'jVQFb\lF_bl#"%2sFb\lFbbl#!%>"*F^alFfbl#!&Ha#Fd`lFjbl#"'r?>F^alF]
cl#!'60GFb\lF`cl#"'(3`"F^al#")n!p9$FcoFS,`qF%#!*Fj+C"F3F)#")^\WTF_qF-#"**H$o,$F
3F_\l#"&hb""&+]#F0#")PB:&*FcoF4#!*$)\<>"FQF8#!*4TLk$F(F<#")h3=<Ff[mF@#"*LK-x%F(
FC#!)pzR@F_sFG#")fODpF,FK#!*FB%*G%FcoFN#")dX>?F_sFR#"+znf-=F3FV#!*fQ*3gFcoFY#")
dtrRFcoFgn#"+^uo35F3Fjn#!+*Qibp"F3F]o#"*()\Cp#F3F`o#!+TI+PDF3Fdo#"+B5YZ;F3Fgo#"
*rD77$F3Fjo#!)"fqA"FJF]p#")zq\@FfsF`p#"*B=LN)F(Fcp#!*f%H([#F3Ffp#")*Q9_$F_qFip#
!)j(f"**F3F\q#")**3Z!)FcoF`q#"*r9oH#FcoFcq#")$y[!fF_qFfq#!*(*fU[)F3Fiq#!+2PE@=F
(F\r#!)(yEp%F,F_r#!'2%\&F?Fa`l#"%2hF^alFe`l#"'(**e"Fb\lFh`l#!&Z#QFb\lF[al#"&pk)
Fb\lF_al#"&%)e""&Dc"Fbal#!'xX8Fd`lFeal#!%(Q#FiblFial#"&hf'FeblF_bl#"'P(>"Fb\lFb
bl#!&@+'F^alFfbl#!&ns#F^alFjbl#!'fy<F^alF]cl#"'$*))GF^alF`cl#!%`NFebl#"*ZjQ/"F3
FS,`qF%#!(4%4HFQF)#!(LFz'F(F-#"),-ZLF_qF_\l#"&*e&*F]_mF0#!)x-9>FFF4#!)n9oGF_qF8
#!*pbv$\F(F<#")<L\6FFF@#!)zY%)oFcoFC#")\7%H"F_sFG#"'*\<#"(+Dc"FK#!)RHlBFazFN#"(
(=v7F_qFR#"+.01$y"F3FV#!*Ps_Z(F(FY#"*dDC$pF3Fgn#"+6Of"p"F3Fjn#!+Ll#QP"F3F]o#"*6
=5-#F(F`o#!+HraD6F(Fdo#")FUl(*F3Fgo#")*QU.(F,Fjo#!+$G-$*>"F3F]p#"**pS6RF3F`p#!*
26/!HF(Fcp#!*@L5P"F(Ffp#!)h-PuFcoFip#")B17yF3F\q#!*$>%fD"F(F`q#!*\!zt=FcoFcq#"*
<WA@"F(Ffq#"*8zn7"F(Fiq#!*4ia-*FcoF\r#")pb<6F]tF_r#"(Vph*FfsFa`l#"&\5#F^alFe`l#
"'HJaFb\lFh`l#F[blFeblF[al#"'^tKFb\lF_al#"'BV6F^alFbal#!'P\nFb\lFeal#!#6"#]Fial
#!%8cFjhlF_bl#"&dQ)F]_mFbbl#!&<(RFeblFfbl#!%p9"%+5Fjbl#!'(\*HFb\lF]cl#"%*>"F\bl
F`cl#"%"=&Fjhl#")fZkwF3FS,hsF%#!-^')*zhq(".++++++"F)#!+*y+(e>",++++]#F-#!+L:ot=
",++++D'F0#"-xY66'z""-++++]7F4#!-$3N[oJ'Fe]nF8#"-J[$\Cs""-+++++]F<#",VkhD'o",++
+++&F@#".FutC[2#Fe]nFC#!->d3(f1$Fc^nFG#",4gZ@(z"-+++++5FK#!.")))pA80"Fc^nFN#!,$
yp5X<Fe]n**F)FSF0FSF%FSF-FS#!,jGu))4#",+++++#FR#!,pa@)yDFc^nFV#"-LJP%zY(Fc^nFY#
!-^9XVQZFc^nFgn#!-j9t!Gx)Fc^nFjn#"-h%4:IS#F]_nF]o#!,\C"pI<Fc^nF`o#!-hMJvKVFe]nF
do#!.Vt7+Nv"Fe]nFgo#!-Bz-8MBFe]nFjo#!+f]aLc",+++++"F]p#!.f,%>FuQFe]nF`p#!."[5kc
!e#Fe]nFcp#!-89/LG5"-+++++?Ffp#!-f'=-+"GF]_nFip#!-zfw%3?#"-+++++DF\q#"-4<]Iz5Ff
anF`q#",^&>6,A",++++D"Fcq#!.@2zyUM"Fe]nFfq#!.xjH9,A"Fe]nFiq#"-hyC)Gh$Fe]nF\r#!-
tM1\W8F^^nF_r#",*>(HaU#"+++++!)*$F)""%#"+(fH.O*Fc^n*$F0Fhbn#",@`OOS'Ffan*$F%Fhb
n#",2L=l@&Ffan*$F-Fhbn#"-dNk'[:"Ff^n*&F)F9F0F9#"..sz%>4@Fe]n*&F)F9F%F9#!+2eY>mF
e_n*&F)F9F-F9#!-`vo!>T'Faan*&F)F5F0FS#!,HGJAu#F[^n*&F)F5F%FS#!,L#*ox\"F^^n*&F)F
5F-FS#!-T!4fI\"F^^n*&F0F9F%F9#",jS/T(GFh]n*&F0F9F-F9#!.6/y(G!Q"Fe]n*&F0F5F)FS#!
.B8,d(QJFe]n*&F0F5F%FS#!-JJp:h7Fe]n*&F0F5F-FS#!.dNQl#z8Fe]n*&F%F9F-F9#",2/j2t"F
^^n*&F%F5F)FS#!,tQuAm$Ffan*&F%F5F0FS#!-T"o!H_SFc^n*&F%F5F-FS#",pX$y5LF[^n*&F-F5
F)FS#!+4*p)QyFaan*&F-F5F0FS#"-dcbr:DF^^n*&F-F5F%FS#!-2uWh8XF^^n*(F)F9F0FSF%FS#"
-Pt)H()e$Fe]n*(F)F9F0FSF-FS#".V%*GvQO"Fe]n*(F)F9F%FSF-FS#!-40Vd*=#Fe]n*(F0F9F)F
SF%FS#!-PH)\BB"Fe]n*(F0F9F)FSF-FS#"-JJJ&H+(Fc^n*(F0F9F%FSF-FS#!-<WCUjCFfan*(F%F
9F)FSF0FS#",*[K4'4*F^^n*(F%F9F)FSF-FS#!-^D?qzuFe]n*(F%F9F0FSF-FS#"-TIKjLmFc^n*(
F-F9F)FSF0FS#".$=.]N(z#Fc^n*(F-F9F)FSF%FS#!,JZ'zAa",+++]7$*(F-F9F0FSF%FS#"-*z2y
D]#F^^n#",R)\rN&*FfanFS,hsF%#"-*p]'[RJFe]nF)#!-j#fPx;%Fc^nF-#!-f'[S![=F]_nF0#"-
xM1Dp<Fc^nF4#!-<*egxG%FfanF8#!-(f#pP&)oFc^nF<#"-^X&ps-$Fc^nF@#"-^BE*o$GFfanFC#!
*6`j%GF]_nFG#!-$*zJb%>#Fc^nFK#!-*z;)pHqFe]nFN#!-*4+,G,#F^^nFb_n#!,4Eo?i&F^^nFR#
".Bwu+!*\"Fe]nFV#!.P,*[e-PFe]nFY#".8:-)[)*GFc^nFgn#"-*f([HYPFfanFjn#!-x>#G`-$Ff
anF]o#".h5')ehv#Fe]nF`o#!-4#3_"p&*Fc^nFdo#!,h!HN*)QFe_nFgo#".6)QXK0=Fe]nFjo#!-Z
yk9pTF^^nF]p#!-f.0Jp@Fc^nF`p#"-j7O!z)GFe]nFcp#!-jR&RD,"Fe]nFfp#",rA<4!>F[^nFip#
!."p*R8tV$Fe]nF\q#!-R[%)H^MFfanF`q#!,J9&*Gf"Fh]nFcq#!..ywB)QPFe]nFfq#"-H>V#=$HF
^^nFiq#"-,rXDV:Fc^nF\r#!.V8([$y^"Fe]nF_r#"-L'[=0k&F]_n#!,$yXoW]Fe]nFSFgbn#!-Fd#
>$\5Fc^nF[cn#!-F-`Dq6Fc^nF^cn#",.'*fXz(Fc^nFacn#!-F*>4h5"F^^nFdcn#".$z,wYJ6Fe]n
Fgcn#!,VU5=f*F^^nFjcn#!.RX0Jr@"Fe]nF]dn#!.`k*=419Fe]nF`dn#"-rT@=UHFe]nFcdn#!-2b
zC*)=FaanFfdn#"*(\.\))"*+Dcw*Fidn#"-,J^@ogFc^nF\en#",>>(Q*H"FaanF_en#".81t"*f2"
Fe]nFben#",HJS-I(FfanFeen#!)t$e\&"+++++SFhen#"-fE3#=S#Fc^nF[fn#!-$4r0hP$Fc^nF^f
n#"-Fk_$zc(Fe]nFafn#!,xZ*=3xF[^nFdfn#"-(3)f$)ogFc^nFgfn#!.Ff#48$R"Fe]nFjfn#"-V6
n,w9Ff^nF]gn#"-6RPe.QFfanF`gn#".$***G*el=Fe]nFcgn#!.41/j=z#Fe]nFfgn#"-*4%*oDd$F
c^nFign#!.`Zh#f)3#Fe]nF\hn#!,*p"\#4#*F]_nF_hn#!,>9ihE$Fj`nFbhn#".<JXEc#=Fe]nFeh
n#".V![.xfAFc^nFhhn#"+drA+#*F[^nF\in#",pIY1L$",+++++%6",
I+C_toa3d_46w,6#>%)symbolicGFS60%&_nameG%&_sizeG%#_AG%"iG%"TG%%condG%%eqs3G%%eq
s4G%$eqsG%#_FG%&_varsG%$_C0G%$_V0G%#_VG6"FaboC/>6$8$8%6$7#%"tG7#7$"#6""&@%/9$""
!>8&7#-%$seqG6$-%'rndMatG6#&&F[do6#8'Fabo/Fceo;FS-%%nopsG6#Fjco>Fhdo7#-F[eo6$-I
'MatrixG6$%*protectedG%(_syslibG6$F`eow,6$F%F-Fabo6$%)operatorG%&arrowGFabo-&T'
6#T%6#,&FedoFS*&,&9%FS!""FSFS&&T#F[go6#FSFSFSFaboFabo6(FiboF[doF[coFceoFhboFjco
6#F96$7'Q!FaboFbgo"#P"#s"#O7'F[hoFbgoF\ho"#VF^hoFdeo>8(-%(convertG6$,,*(&&FhdoF
fgo6$;FaboFaboFSFSF)FSF_\lFbgoFS*(&Fiho6$F[ioF9FSF0FSF_\lFbgoFS*(&Fiho6$F[ioF5F
SF%FSF_\lFbgoFS*(&Fiho6$F[ioFhbnFSF-FSF_\lFbgoFS*&&Fiho6$F[ioFbdoFSF_\lFbgoFSI'
VectorG6$F`foFafo>8)7-/%$T11G&FbhoFfgo/%$T12G&Fbho6#F9/%$T13G&Fbho6#F5/%$T14G&F
bho6#Fhbn/%$T15G&Fbho6#Fbdo/%$T16G&Fbho6#""'/%$T17G&Fbho6#""(/%$T18G&Fbho6#"")/
%$T19G&Fbho6#""*/%%T110G&Fbho6#"#5/%%T111G&Fbho6#Fado>8*-&%"|irG6#%"*G6%*$F_\lF
5%#~$G-%%subsG6$F[jo7*z36+F^joFe\pFajoFijoF][pFa[pFf[pF[\pF`\p[[[[[[[[[\_[\wFbg
o\[[[[[[[[\[[\wFS[_[[_[[[[[[[\wFbgo[[[[[[[c[[_[[wFS[[[\[[\[[\[[[wFbgo\[[[[[[c[[
[[[wFbgo[_[[[[\_[[[[[wFS[[[\_[[_[[[[[wFSz36+F^joFe\pFejoFijoF][pFa[pFf[pF[\pF`
\p[[[[[[[[[\_[\wFbgo[_[[[[[[[\[[\wFS\[[[_[[[[[[[\wFbgo[[[[[[][[[_[[wFS[[[\[[[_[
\[[[wFbgo\[[[[[\_[[[[[wFS[_[[[[][[[[[[wFbgo[[[\_[\[[[[[[wFSz36+Fe\pFajoFejoFijo
F][pFa[pFf[pF[\pF`\p[[[[[[[[[\_[\wFS[[[[c[[[[[[[\wFbgo[[[\[[[[[\_[[wFbgo\[[[[[
\[[[_[[wFS[_[[[[[_[\[[[wFS\[[[_[[_[[[[[wFbgo[_[[_[\[[[[[[wFbgo[[[\c[[[[[[[[wFSz
/6)F^joFe\pFajoFejoFijoF][pFa[p[[[[[[\[\[[[\[nFbgo][[[[[[[[[[[\[nFS[[][[[[[\[[[
[[nFS[[[[][\[[[[[[[nFS\[\[\[[[[[[[[[n!"#[[[[[[[[[[][[[mFhbnz96,F^joFe\pFj\pFajo
FejoFijoF][pFa[pF[\pF`\p\[[[[[[_[[[]wFbgo[][[[[][[[[]wFbgo[[[[[[]_[[\[wFbgo[[c[
[[[[[[\[wFS\[[c[[[_[[[[wFbgo[][[[\][[[[[wFbgo\[[[[][[[[[[wFS\[_[[\[[[[[[wFS[][[
\[[[[[[[wFS[]_c[[[[[[[[wFS[[[[[[[[c[\[sFhbnz16*F^joFe\pFajoFejoFijoF][pFa[pFf[p
[[[[[[[\c[[[][nFbgo[[[_[[[[c[[[][nFbgo[[[[[][\[[[[][nFbgo[[\[[[[[[[[[][nFS[[[_[
_[[[[[[[[nFS[[[c[][[[[[[[[nFS\[[[[[[[[[_[[[mFhbnz16*F^joFe\pFajoFejoFijoF][pFa[
pF[\p[[[[[[[\c[[[][nFbgo[c[[[[[[c[[[][nFbgo[[[[[][\c[[[[[nFbgo[[[c[[[[c[[[[[nFS
[c[[[_[[[[[[[[nFS[[\[[][[[[[[[[nFS\[[[[[[[[[_[[[mFhbnz16*F^joFe\pFajoFejoFijoF]
[pFa[pF`\p[[[[[[[\c[[[][nFbgo[c[[[[[\[[[[][nFbgo[[[_[[[\c[[[[[nFbgo[[[[[_[\[[[[
[[nFS[c[c[[[[[[[[[[nFS[[\_[[[[[[[[[[nFS\[[[[[[[[[_[[[mFhbn>8+-F`]p6%*$F_\lFhbnF
f]p-Fh]p6$F[jo7$z]o6-F^joFe\pFj\pFajoFejoFijoF][pFa[pFf[pF[\pF`\p[[[[[[[[c[[__[
mFS\[[[[[[[c[[]_[mFbgo[][[[[[_[[[]_[mFS[[[[[\[[c[\[_[mFS[[[c[[[[c[\[_[mFbgo[[[c
[[][[[\[_[mFbgo[[[[\[[[[[\[_[mFbgo\[_[[[[[c[[[_[mFbgo\][[[[[[c[[[_[mFS[_[[[[[_[
[[[_[mFbgo\][[[[][[[[[_[mFS[_[[[\[[[[[[_[mFbgo[]_c[[[[[[[[_[mFS\][c[[[[[[[[_[mF
9[[[[[[[_c[[_[[mFbgo[[[[[[_[[[[_[[mFbgo[[[[\[[[[[[_[[mFS[[_[[\[[c[[][[mF9\[[[[
\[[c[[][[mFbgo[][[[[]_[[[][[mFbgo\[[[[[_[[[[][[mFS[][[[\][[[[][[mFc^p\[[c[[][[[
[][[mFS[][[[][[[[[][[mFbgo[][c[\[[[[[][[mFS[[[[[\][c[\[[[mFS[[[[[][[c[\[[[mFS[[
c[[[[_c[[[[[mFS\[_[[[][c[[[[[mFbgo[]_[[\[[c[[[[[mFbgo\[_[[\[[c[[[[[mFc^p[[cc[[[
[c[[[[[mFSz]oFe_p[[[[[[[_[[[__[mFS\[[[[[[[c[[]_[mFS[][[[[[_[[[]_[mFbgo[[[[[[]_[
[\[_[mFS[[[c[[[_[[\[_[mFbgo[[[c[\[[[[\[_[mFbgo[[[[\[[[[[\[_[mFbgo][[[[[[[c[[[_[
mFbgo[]_[[[[_[[[[_[mFbgo\][[[[[_[[[[_[mFS][[[[[][[[[[_[mFbgo\][[[\[[[[[[_[mFS\[
_c[[[[[[[[_[mFS\][c[[[[[[[[_[mF9[[[[[[[_c[[_[[mFbgo[[[[[][[[[[_[[mFbgo[[[[\[[[[
[[_[[mFS\[[[[\[[c[[][[mFbgo[[_[[[]_[[[][[mF9[][[[[]_[[[][[mFbgo\[[[[[_[[[[][[mF
bgo\[[[[\][[[[][[mFc^p\[[c[[][[[[][[mFS[][[[][[[[[][[mFS[][c[\[[[[[][[mFS[[[[[[
__[[\[[[mFS[[[[[\]_[[\[[[mFS[[c[[[[_c[[[[[mFS[]_[[[]_[[[[[[mFc^p\[_[[[]_[[[[[[m
Fbgo[]_[[\[_[[[[[[mFbgo[[cc[[[_[[[[[[mFS>8,7$&F^]pFabo&F]_pFabo>8--%$mapG6$%'ex
pandGFh_p@$FddoOF]`p>8.-%&minusG6$-%'indetsG6#F]`p-Fj`p6#Fhdo>6$8/80-%,poly2mat
rixG6$F]`pFe`p>81-%$srtG6$Faap-%%tdegG6#&Fe`pFabo6&7#-%/permuteColumnsG6%F`apFa
apFfapFfapFjcoF[doFaboFaboFabo6#Ffdo637'F[hoFbgo"#;Fd[pF^ho7'F[hoFbgoF5"#LF`ho7
'F[hoFbgoF5Fc\p"#X7'F[hoFbgoFi[p"#bF`ho7'F[hoFbgoFi[p"#$*F`ho7'F[hoFbgoF5"$,"F`
ho7'F[hoFbgoF5"$C"F`ho7'F[hoFbgoF5"#*)F`ho7'F[hoFbgoF5"$t&F`ho7'F[hoFbgoF5"#DF`
ho7'F[hoFbgoF5"#CF`ho7'F[hoFbgoF5"#RFjbp7'F[hoFbgo"#A"#J"#_7'F[hoFbgoF5"#QF`ho7
'F[hoFbgoF5F^hoF`ho7'F[hoFbgoF5F_dpF`ho7'F[hoFbgoF5"#^F_dpFabo
