M7R0
I+F_toa2d_337%,6%#L3G#"'j"3&"'++]%#L1G#!',GM"'+]7*&F)"""F%F.#"$2)"$+&%#L2G#!'V=
?F,*&F%F.F2F.#!$p'F1*$F%""##"#hF1*&F2F.F)F.#"#8"#D*$F2F9#"$_""$D"*$F)F9#!$<#FC*
(F)F.F2F.F%F.!"#,6F%#"&LO("'++DF)#!'JH7FLF-#"#`"$]#F2#!'FsOF(F5#"$*))F1F8#!#@"#
]F<#"#B"#?F@#!$z'F1FD#"#EFCFGFH,6F%#!&.k*"&+D'F)#!&Ti""&+D"F-#"#\FQF2#"&B0("'++
5F5#!$Z%F1F8#"$Z&F1F<#"$\""$+"F@#!""""&FD#!$H"F\pFGFH6",
I+C_toa2d_33w,6#>%)symbolicGF.6-%&_nameG%&_sizeG%#_AG%"iG%$CM4G%$eqsG%#_FG%&_va
rsG%$_C0G%$_V0G%#_VG6"FbpC,>6$8$8%6$7#%#ddG7#7$""$F_r@%/9$""!>8&7#-%$seqG6$-%'r
ndMatG6#&&Fiq6#8'Fbp/F`s;F.-%%nopsG6#Fhq>Fer7#-Fhr6$-I'MatrixG6$%*protectedG%(_
syslibG6$F]sw,6$%"xG%"yGFbp6$%)operatorG%&arrowGFbp-&T'6#T%6#,&FbrF.*&,&9%F.F^p
F.F.&&T#Fjt6#F.F.F.FbpFbp6(FjpFiqF\qF`sFipFhq6#F96$7'Q!FbpF^p"#P"#s"#O7'FiuF^pF
ju"#VF\vFas>8(w,6#%#LLG6'%"nG%#VVGF\q%"jG%"LG6"FbpC)>Fhq""%>Fiq-F[t6%,&FhqF.F.F
.F`w/%&shapeG%*symmetricG>&FiqFdu-I$<,>G6$F]tF^t6$Fcr-Fhr6$F./Fer;F.Fhq>6%((F`v
F.F9(FaxF_r((F`vF9F_r&&Fbr6#;F.F_rFbp>6%(FaxF\w(FdxF\w((F`vF_rF\w&&Fbr6#;F\w""'
Fbp?(FerF.F.Fhq%%trueG?(F`s,&FerF.F.F.F.FhqFeyC$>&F`v6$FerF`s((F`vFerF`s>&Fiq6$
Fgy,&F`sF.F.F.FjyO-&I.LinearAlgebraG6$F]tF^t6#%,DeterminantG6#FiqFbpFbpFbp6#F.6
-7'FiuF^p"#5F][lF\v7'FiuF^pF>"#>"#J7'FiuF^p""("#XF^v7'FiuF^pFb[l"#MF^vFa[lFa[l7
'FiuF^pFb[l"#7"")7'FiuF^p"#6"#;Fh[l7'FiuF^p"#:"#KF^v7'FiuF^pF]\lFjuF^v7'FiuF^pF
b[lF^v"#_>8)7%-F`v6#7(F)F2F%&&FerFdu6$F.F.&Fi\l6$F.F9&Fi\l6$F.F_r-F`v6#7(F)F2F%
&Fi\l6$F9F.&Fi\l6$F9F9&Fi\l6$F9F_r-F`v6#7(F)F2F%&Fi\l6$F_rF.&Fi\l6$F_rF9&Fi\l6$
F_rF_r>8*-%$mapG6$%'expandGFc\l@$FarOFb^l>8+-%&minusG6$-%'indetsG6#Fb^l-F__l6#F
er>6$8,8--%,poly2matrixG6$Fb^lFj^l>8.-%$srtG6$Ff_l-%%tdegG6#&Fj^lFbp6&7#-%/perm
uteColumnsG6%Fe_lFf_lF[`lF[`lFhqFiqFbpFbpFbp6#Fcr607'FiuF^pF[\lFcyF\v7'FiuF^pF_
r"#LF^v7'FiuF^pF_r""*Fc[l7'FiuF^pFb[l"#bF^v7'FiuF^pFb[l"#$*F^v7'FiuF^pF_rF][lF^
v7'FiuF^pF_r"$u"F^v7'FiuF^pF_r"#CF^v7'FiuF^pF_r"#RFc[l7'FiuF^p"#AF`[lFa\l7'FiuF
^pF_r"#QF^v7'FiuF^pF_rF\vF^v7'FiuF^pF_rF`[lF^v7'FiuF^pF_r"#^F`[lFbp
