M7R0
I+isLinIndept+6&'%"MG%%listG'%"GGF''%%tordG%3ShortMonomialOrderG'%#ppG%'posintG
6$%%varsG%"SG6"6"C&>8$-%'indetsG6#9%@$/-%%nopsG6#9$"""O%%trueG>8%&-%,poly2matri
xG6%-%$mapG6$f*6#%"mGF46$%)operatorG%&arrowGF4-&%)GroebnerG6#%+NormalFormG6&FAT
$T&/%/characteristicGT(F4F46(F)F;F+9&F.9'FAF>F76#FB-%#isG6#0-&&%.LinearAlgebraG
6#%(ModularG6#%%RankG6$F[oFF-Fbo6$F[o&FF6$;FB!"#;F4F4F4F4F46#""%F4,
I*testBasist+6''F&%$setG'%$degGF/F(F*'F.%*nonnegintGF06"F4C&>F7-F96#Fjn@$2F>F;O
6$%&falseG-%$<,>G6#-Fgq6#""!>FF&-FI6%-FL6$f*FOF46$FRFSF4FTF4F46(F)FjnF+F[oF.9(F
AF>F7F\o6$-%#ifG6%0FerF[r-F^o6#/-Fbo6$FerFFF;-F^o6#/-&FdoFgo6#FFF;FFF4F4F46#""&
F4,
I*iniMonSett+6)'%"FG<%%'VectorGF'Fgp'%#B0GF''F1F'F(F*F->'%$domGF[qF[r6*%"EGF&%#
vrG%"dGFip%%flagGF2%&d_minG6"F4C*>8(-F?F:>8+F[r>F7-%(convertG6$-FL6$%#opG-&FV6#
%(SupportGF@Fgp-%&printG6#-%$catG6%%<Polynomial~system~contains~G-F?6#F7%+~mono
mialsG>FFF7?(8'F[rFBF41,&FivFBFau!""9*C&>8&-%'selectG6$f*6#%"xGF46$FRFSF41-%'de
greeG6$FAFZT%F4F46&F1FjnFhtFivFF>FF-FL6$f*6#%"tGF46$FRFSF4-Fhu6#-FL6$f*6#%"kGF4
6$FRFSF4*&FZFBFAFBF4F46$FcxFAT#F4F46$FgtF`wFF>6$8)8*-Fcp6'FFF^uF[oFer9)@$4Fcy>F
au,&FivFBFBFB-F^v6#-Fav6%%6Initial~set~contains~G-F?FesFfvO6$F7FFF4F4F46#""(F4,
I-neighborMonst+6%'%"BGFgp'%#MBGFgpFat6#%#nBG6"F4C&@$/F>F[rOF;>F7-Fbw6%%%typeG-
FL6$Fhu<#-%$seqG6$-F\\l6$<$*&%"bGFB%"vGF\w*&Fb\lFBFc\lFB-%#inG6$Fc\lFjn-Ff\l6$F
b\lFA%)monomialG>F7-%*intersectG6$-%&minusG6$F7FAF;-Fhr6%/FdvF[rF;F7F4F4F46#""$
F4,
I)genBasist+6)'FftFgpFfpF_tFatF(F*F-60%$rndGFjz%#EBGF\[lF^[l%$nB1G%#bvGF[y%"aG%
#nvG%#wtGFP%"iGFip6"F4C,>F7,$-%%randG6#;F[r"%+5#FBF\_l>FF<">FivF;>8--F?6#F[o>81
-F?F`q>Fdy7#-F\\l6$-%&roundG6#-F7F4/80;FBFb_l>Fau-&%$maxG6#%&indexG6#-FL6$f*Few
F46$FRFSF4,&FAFB*&-F_yF4FB$"$+"F[rF\wFBF4F46$F\^lF7Fdy>8,&F[o6#Fau?(F4FBFBF42Fa
zFf_lC*>Fiv-F`]l6$FivFF>F^u-Ffz6%FFFivF[o>F`w-%&unionG6$FAFF>8.f*FewF46$FRFSF4,
*-Fhr6%-Ff\lF[xFBF[rFB-Fhr6%-Ff\l6$*&F\xFBFAFBT'FBF[rFB-%$addG6$*&&T)6#T+FB-Fjw
6$FA&T.FiclFB/Fjcl;FBT/FB*&-T1F4FBFaalF\wFBF4F462FftFAF`^lFealF]^lF`wF_^lFdyFc^
lFa`lF1F[oFa^lFb_lF\^lF7>Fcy-%%sortG6$7#-Fhu6#F^uf*6$Ffw%"yGF46$FRFSF41-F_yF:-F
_yF@F4F46$Fb^lFfbl>6$8/Fa`l6$&FcyF\oFB?(F4FBFBF434-F"6&7$-FhuFesFgelFerFgyF]w2F
a`l-F?6#FcyC$>Fa`l,&Fa`lFBFBFB>Fgel&Fcy6#Fa`l>FF<$F`flFgelFFF4F4F46#FezF4,
I*saveBasest+6$'%%probG%'stringG'%$QBsG<$F'Fgp6#%#fdG6"F4C%>F7-%&fopenG6$-Fav6%
Q-nongb/nongb_F4FAQ%.txtF4%&WRITEG-FL6$f*FewF46$FRFSF4-%(fprintfG6%F_yQ$%a|+F4F
AF4F46$FgglF7F;-%'fcloseGFevF4F4F46#""#F4,
I*readBasest+6#F`gl6%%#stGFdgl%*nongbfileG6"F4C'>F7FB>FF7">F`wF^hl?(F4FBFBF40F7
F[rC$>F7-%)readlineG6#F`w@$F]jl>FF7$F`fl-%&parseGFevFFF4F4F46#FBF4,
I,BasisFindert+6&F`gl>'%-deg_over_minGF[qF[r>'%1numbers_of_basesGF/Fbal>'%-prim
e_numberGF/"&\F$6/F\tF1F+F)F`tFhtFftF&%#BBGFjz%#fnGFgglF.6"F4C2>FauFjil>FealFji
l>Fa`lF[oA-Fav6%Q,problems/F_F4FAQ#.mF4>F7-%%evalG6#-Fav6$%#F_GFA>FF7#-Fhu6#-F9
Fev>F`w-%%tdegG6#F`fl>Fiv-&FV6#%&BasisG6%F7F`w/FgnFa`l>F^u&-&FV6#%*NormalSetG6$
FivF`wF\o>6$FdyFau-Fhs6)F7F^uFFFivF`wFa`lF;>FfblF^hl>Fgel-F\hl6$FfblFbhl-F]il6#
Fgel>Fgel-F\hl6$Ffbl%'APPENDG?(F4FBFBF42-F?6#FealFjnC$>Fb_l-Fg]l6)FdyFauF^uFFFi
vF`wFa`l@$4-%'memberG6$Fb_lFealC%>Feal7$-FhuFb_mFb_l-Fhhl6%FgelFjhl-Fdu6$Fb_lF'
-F^v6#-%(sprintfG6%Q%%d%sF4-F]`l6#,$*&Fa_mFBFjnF\wFbalQ,%~completedF4Fi^mF4F4F4
6#FBF4,
I*writeGfant+6%'F\tFegl'F1FeglF-Ffgl6"F4C%>F7-F\hl6$Q/gfan/igfan.txtF4Fbhl-Fhhl
6'F7Q+Z/%aZ%a|+%aF4Fjn-Fdu6$F;F'-%$modG6$-FL6$%'expandG-Fdu6$FAFgpFjnF\ilF4F4F4
6#Ff]lF4,
I)readGfant+Fbil6'FitFdil%"nG%)gfanfileGF.6"F4C*>F7Feq>FFFB>F`wF[r>Fiv-Fav6%Q+g
fan/gfan_F4FAFahl>FF-Fajl6#Fiv>F^u-Fgjl6#-%*substringG6$FF;Ff]l,&-&%,StringTool
sG6#%.FirstFromLeftG6$Q"[F4FFFBF_pFB?(F4FBFBF40FFF[rC$>FFFhcm@(5/FFQ#|fr|frF4/F
FQ"|frF4C%>F7FD>F`w,&F`wFBFBFB>(%#GBGF`wFjil3F70-F^dm6$FFF\wQ"|hrF4>Fhem7$-Fhu6
#Fhem-F^dm6$FFF^p3F7/F\fmF^fmC$>FhemF`fm>F7FeqO6%F^u7#-F\\l6$-FL6$Fgjl(FiemFc^l
/Fc^l;FBF`w7#-F\\l6$-FL6$f*FewF46$FRFSF4-Fgjl6#-F^dm6$FA;FB,&-Fcdm6$Q"+F4FAFBF
\wFBF4F4F4FagmFbgmF4F4F46#FBF4,
I(writeCMt+6&F`gl'%$Ws0GF''F[yF/F-6&FgglF\tF1%#WsG6"F4C5>F7-F\hl6$-Fav6%Q'cm/ic
mF4FjnFahlFbhlAF_\m>FFFd\m>F`w-Fdu6$7#-Fhu6#-F9FesFbgl>Fiv-&Fddm6#%.SubstituteA
llG6%-F`jm6%-Fdu6$F;FbglFhdmQ"(F4Q"]F4Q")F4>FF-Fdu6$-Fabm6$-FL6$FebmFFF[oFbgl-F
hhl6'F7Q<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+F4FivF[oF`w-Fhhl6&F7Q=f~=~openOut~"cm_%s
_%a.txt";|+F4FAFjn-Fhhl6$F7Q<f~<<~toString(pp)~<<~endl;|+F4-Fhhl6$F7Q<f~<<~toSt
ring(vr)~<<~endl;|+F4-Fhhl6%F7Q9for~i~from~0~to~%a~do~(|+F4,&F_uFBF\wFB-Fhhl6$F
7Q>f~<<~toString(Ws#i)~<<~endl;|+F4-Fhhl6&F7Q.R~=~ZZ/%a%s,~F4F[o-F^dm6$F`wF^p-F
hhl6$F7QDMonomialOrder~=>~Weights~=>~Ws#i];|+F4-Fhhl6%F7Q0I~=~ideal(%s);|+F4-F^
dm6$FF;F_ilF_p-Fhhl6$F7QVG~=~gb(I,ChangeMatrix=>true);|+M~=~getChangeMatrix~G;|
+F4-Fhhl6$F7Q>f~<<~toString(M)~<<~endl;|+);|+F4-Fhhl6$F7Q,f~<<~close;F4F\ilF4F4
F46#FbpF4,
I'readCMt+Fbil6(Fdil%'cmfileGF.F1FPF\cm6"F4C*>F7FB>F^uF[r>FcyF[r>FF-Fav6%Q'cm/c
m_F4FAFahl>F`w-Fgjl6#-FajlFes>FivF[_n?(F4FBFBF4F]jlC$>F7F]_n@&3F]jl/-F^dm6$F7FB
FhjmC$>F^u,&F^uFBFBFB>(%"TGF^u-F^dm6$F7Fb]n3F]jl/-F^dm6$F7;FB""'Q'matrixF4C$>Fc
y,&FcyFBFBFB>(%#CMGFcy-F`jm6%-F`jm6%-F^dm6$F7;""*F_pFbemFhdmF^fmFijmO6%F`w7#-F
\\l6$-%%wdegG6$7#-Fgjl6#(F\`nFc^lFiv/Fc^l;FBF^u7#-F\\l6$)-%'MatrixG6#7#-FL6$Fgj
l(F[anFc^l%#%TG/Fc^l;FBFcyF4F4F46#FBF4,
I(getTordt+6$%#gbG%#lmG6+F1Fa^l%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG%$solG%&f
degsG6"F4C,>F77#-Fhu6#-F9F@>FFFdv>F`w/7#-%"$G6$F[rFF%%NULLG>Fiv7#-F\\l6$(FhtFc^
l/Fc^l;FBFF>F^u-FL6$f*6#%"zGF46$FRFSF4-FL6$f*FewF46$FRFSF47#-F\\l6$-Fjw6$FAF_el
-Ff\l6$F_elF_yF4F46$F1F_y-Fdu6$FAF'F4F46$F1F7FA>Fcy-FL6$f*FewF46$FRFSF4F_fnF4F4
FifnF;>Fdy-FL6$f*FjxF46$FRFSF4-Fhu6#-FL6$f*FewF46$FRFSF41FB-Fdcl6#-%$zipG6%f*6$
F_elFienF46$FRFSF4*&FAFBF;FBF4F4F4FAF_yF4F46$FhcnFhcl-%%subsG6$F_y7#-F\\l6$,&&F
\xF@FB%"gGF\w-Ff\l6$F]in&FbclF@F4F46*FgcnF`wFjcnFcyFicnF^uFhcnFiv<#-Fjdn6#;FBF>
>Fau&-&%-OptimizationG6#%)MinimizeG6&-FdclFicmFdy/%+depthlimitG"#S/%'assumeGF[q
6#F_il>Feal-Ffhn6$FauFiv6$Feal-Fjan6$FealF7F4F4F46#F_ilF4,
I)saveDatat+6,F`gl'%#mnG7$F/F/'%#spG%(numericGFjpFdam'%#avGFj\lF*'%#QBGF''%'shi
ftsGF''%$stdG%(booleanG6'Fh[mFggl%$mn0G%$sp0GFit6"F4C&>F7-Fhr6%9--Fav6%Q-optim/
o_std_F4FAFahl-Fav6%Q.optim/o_nstd_F4FAFahl>F^uFeq@%-&%*FileToolsG6#%'ExistsGFe
vC'>FF-F\hl6$F7%%READG>F`w-Fgjl6#-FajlFev>FivFj]o@$52&F;F\o&F`wF\o3/Fa^oFb^o2Fi
vFjn>F^uFD-F]ilFes>F^uFD@$F^uC%>FF-F\hl6$F7Fbhl-Fhhl6,FFQ8%a|+%a|+%a|+%a|+%a|+%
a|+%a|+%aF4F;FjnF[o-Fdu6$FerF'FgyF]w9+9,Fg^oF4F4F46#"#5F4,
I)readDatat+6$F`glF[\o6,Fh[mFgglF`[oFc[oF.F1Ff[oF+Fh[oFj[o6"F4C.>F7-Fhr6%F;Fg\o
Fj\o>FFFf]o>F`wFj]o>FivFj]o>F^uFj]o>FcyFj]o>FdyFj]o>FauFj]o>FealFj]o>Fb_lFj]oFg
^o6*F`wFivF^uFcyFdyFauFeal-FL6$Fe\mFb_lF4F4F46#F_ilF4,
I*eigSolvert+6%F[t>'%'actvarG%(integerGFB>'%'digitsGF/"#:6,%%fB2CGF1F`^lF+FjzFi
pF)F\`n%"VGF26"F4C/>FFFadn>F`w&FFF:>FivF`]m>F7t+6$%"fGFjzFbx6"F4C$>F7-%&tableG6
#-F^hn6%f*6$F`^lFb\lF46$FRFSF4/F;FAF4F4F47#-%'coeffsG6%FAF;.FP7#FP-FL6$f*6#Fb\l
F46$FRFSF4-Fhr6%-%)assignedG6#&F_yF@FadoF[rF4F46$FcxF7F;F4F4F46#F_il>%'DigitsGF
jn>Fdy-Fe]m6$FAFiv>F^u&-F]^m6$FdyFivF\o>Fcy-F?F\el-F^v6#-Fav6%%@The~system~is~e
xpected~to~have~GFcy%'~rootsG>Fau-&FV6#%5MultiplicationMatrixG6'F`wF^u-Fibo6#-%
'EquateG6$F^u7#-Fjdn6#F_cnFdyFiv>Feal&-&Fdo6#%-EigenvectorsG6#-%&evalfGFgalFdjn
>Feal-&%"|irG6#_F4%"/G6%Feal%#~$G-%".G6$-F^t6$Fcy/%%fillGFB&FealF\o>Fb_l-Ffgo6$
-Fgbn6#-FL6$f*6#Fc\lF46$FRFSF4-Fhcl6$-FU6%FAF_yF\xFbclF4F46*F)FdyF+FivFjzF^uFia
oF7FFFealF4F4F46#FBF4,
I$srtf*6$'Fc\lF]tF*F46$FRFSF4-Fhdl6$FAf*F^elF46$FRFSF4-&FV6#%*TestOrderG6%F;FAF
ZF4F46$F+F;F4F4F4F4,
I,poly2matrixt+6%F[t'%#nFGF/Fdam6$%%monsG%%cffsG6"F4C$>FF7#-Fcco6%-Febm6#-Fdcl6
$*&(%$q_qGFc^lFB&FA6#Fc^lFB/Fc^l;FBF;Fjn.F76$-Fgbn6%F;Fazf*6$Fc^l%"jGF46$FRFSF4
-%&coeffG6$&F_yF:(F`[pFAF4F46$FcjoFF-F^t6#7#F7F4F4F46#Ff]lF4,
I/permuteColumnst+6%'F&Fgbn'%#V1GF^t'%#V2GF^t6#F\cm6"F4C$>F7-Fhu6$FBF;-Ffgo6$FA
-Fgbn6$F7<#-F\\l6$/6$Fc^l-&%*ListToolsG6#%'SearchG6$&F;Fb[pFjnFB/Fc^l;FBF7F4F4F
46#Ff]lF4,
I)sparsityt+6#Fj\p6#%&numzrG6"F4C$>F7-F?6#-Fbw6$f*FewF46$FRFSF4-F^o6#/FAF[rF4F4
F4Fgfn*&F7FB-%$mulG6#-Fhu6$FBFAF\wF4F4F46#FBF4,
I(matrixSt+6''FjzF'F_tF(F*Fjp6%F2%#V0GFip6"F4C&>F`wF>@$0F_uF`wY%ILists~B0~and~B
~must~have~the~same~lengthG>Fcz-FI6%-FL6$f*FjcoF46$FRFSF4FTF4F4FdrFAF`wF_q@%/-F
hu6$FBFFF`wO-Fg\p6%F7FF-F^tF:Y%=Failed~to~construct~matrix~SGF4F4F46#FgsF4,
I*quotientst+6&'F]in%(polynomGF(F*FjpF46"F4C$-FU6'FAF;Fjn.%"QG/FgnF[oFibpF4F4F4
6#FbpF4,
I-monPartitiont+6'Fe[o'%#GrGF'F*Fjp>Fg[oFjil6-F`tFjz%#aBG%"RG%#B2G%#RBGF)%#nGGF
\`nF2Fc^l6"F4C->F7&-F]^m6$F;FjnF\o>FF-Fdu6$-Fhr6%/FerFjilF7FerFgp>F`w-FL6$f*Few
F46$FRFSF4F]yF4F46$Ff[oFAFF>Fiv-F]io6$-Fdu6$-F`]l6$F`wFFF'Fjn>Fau-F?Ficm>F^u-FL
6$f*FewF46$FRFSF4*&FAFBFZF\wF4F4Fidp-F]]lF`ep>FF7$-Fhu6#-F]io6$-Fdu6$-F`]l6$FFF
^uF'Fjn-Fhu6#-F]io6$-Fdu6$F^uF'Fjn>6$FcyF`w6$7$-FhuFicmF`fl-FL6$f*FewF46$FRFSF4
F]yF4F4FidpFF@%Fcdp>Feal-Fgeo6(FAFF-Fibo6#-F^fo6$FF7#-Fjdn6#;FBFazF;FjnFjbpC%>F
eal-Fgeo6(FAF7-Fibo6#-F^fo6$F77#-Fjdn6#;FBFdvF;FjnFjbp>Fb_l-F``p6'FFF7F;FjnF[o>
Feal-Fhr6%0F[oF[r-Fabm6$-Ffgo6%Fb_lFeal-&Fco6#%(InverseG6$F[oFb_lF[o-Ffgo6%Fb_l
Feal-&Fdo6#%.MatrixInverseG6#Fb_l>Fdy-Fdu6$,&-F^tFicmFB-Ffgo6$&Feal6$;FBFauF`p-
F^tFesF\wF'O6(F`wFFFcyFealFdy-Fgbn6#7#-F\\l6$-F_bp6&&Fdy6#FfblF;FjnF[o/FfblF[[q
F4F4F46#FgsF4,
I(matrixHt+6'F[tF(FdamFjpFct6/%*undetPolyG%#pvGF`joFgcp%#uHG%%leqsGF\dnFc^l%#dF
G%#dGGFhtFjt%"hG6"F4C)>FF-FdclF`q>F`wF>>FivF_u>Feal-FL6%FjwFAFjn>F7t+6&FdamF_\q
FhtF[\p6#Fbjo6"F4C%-Fcco6%-Febm6#,&FBFB-Fdcl6$)F;%"pG/F\^q;FBFjnFBFAFe[p>F7Fe\p
-Fdcl6$*&&F7FjxFB&%#_vG6$F[oF[yFB/F[yFjhpF4F4F46#Fbp?(FauFBFBFivFDC%>6$FgelFb_l
6$F[r-FL6$f*FewF46$FRFSF4-Ff`l6$F[rFAF4F4F4,&7#-Fjdn6$-Fjw6$&F;FgalFjnF`wFBFeal
F\w?(FfblF[rFBF41,&FfblFBFgelF\wFerC&>F^u7#-F\\l6$-F76&FjnFF,&&Fb_l6#F[\pFBFfbl
FBF[\p/F[\pFcgm>Fcy<#-Fcco6$-Febm6#,&Fj_qF\w-Fdcl6$*&&F^uFg`qFB&FAFg`qFBFh`qFBF
jn>Fdy-%'msolveG6$FcyF[o@$/-F?6#<#FdyF[r>Fgel,&FfblFBFBFB>&Fa`lFgal-Fabm6$-FL6%
-%"@G6$FebmFe\mF^uFdyF[oO-Fgq6#-F\\l6$-&F^t6#%$rowG6#Fabq/Fau;FBFivF4F4F46#FgsF
4,
I*matrixHnit+6(F[tF('%"CGFgbn'F[anFgbnFdamFjp6*%,undetPolyniGF`joFgcp%#H0GF`\qF
a\qF\dn%%parsG6"F4C+>FFF>>F`wF_u>F7t+6&'Fd\qFcbpFdam'Fc^lF/'F[\pF/Fa]q6"F4C%-Fc
co6%FAF;Fe[p>F7Fe\p-Fdcl6$*&Fc^qFB&Fe^q6%FjnF[oF[yFBFg^qF4F4F46#Fbp>Fiv-Fabm6$-
FL6$Febm-Ffgo6$FjnF[oFgy>F^u-Fgbn6%F`wFFf*Fj[pF46$FRFSF4-Fbcl6&&F_y6$FAF;FenFAF
;F4F46(F^dqFivF1FerF]dqF7>Fau<#-F\\l6$&%#_uGFb[p/Fc^l;FB-F?6#-F`]l6$-F9F\elFer>
Fcy-FL6%Fcco<#-F\\l6$-Fabm6$-Febm6#,&Fd^pF\w-Fdcl6$*&&F^uFj[pFBFdaqFB/F[\pFcenF
BFgyFbgmFer>Fdy-Fgaq6%FcyFauFgyO-Fabm6$FdbqFgyF4F4F46#Fd`nF4,
I*syzModulet+6'F[tF('%"AGFgbnF*Fjp6*F`joFgcp%"eG%"LG%#LtGF&F2Fjz6"F4C.>F7F>>FFF
_u>F`w-F\\l6$-F^t6$FF<#/Fc^lFBFben>Fiv7#-F\\l6$7#-&FV6#%,LeadingTermG6$Fd^pF[oF
ben>F^u-FL6$f*FewF46$FRFSF4*&&FAF\oFB&FAFdjnFBF4F4F4Fiv>Fcy-Fgbn6$FFf*Fj[pF46$F
RFSF4*&-%$lcmG6$&FadoFdjn&F`\pFdjnFBF\inF\wF4F46&FaiqFivFbiqF^u>Fdy7#-F\\l6$-F
\\l6$,(*&&FcyFj[pFB&F`wFb[pFBFB*&&Fcy6$F[\pFc^lFB&F`wFg`qFBF\w-Fgq6#-F_bp6&z'6&
Fd\rFg\rFd^p&F;Fg`q[[[\[[[[[\[[mFB\[[[[[\[[[[[mF\wF;F[oFerF\w/F[\p;,&Fc^lFBFBFB
FFFben>Fdy)-Fgbn6#FdyF]cn>Fau-Fgbn6#7#-F\\l6$-F_bp6&Fa[pF;F[oFerFe^p>Fdy-FL6$Fe
bm-Fgq6$-Ffgo6$FdyFjn,&-&Fdo6#%/IdentityMatrixGFevFB-Ffgo6$FauFjnF\w@$Fjr>Fdy-F
abm6$FdyFerO&Fdy6$-%'removeG6$f*Fb[pF46$FRFSF4-&%+ArrayToolsG6#%'IsZeroG6#&F_y6
$FAF`pF4F46$F2Fdy7#-Fjdn6#;FB-Fhu6$7$FBFBFdyF`pF4F4F46#FgsF4,
I+matrixHsyzt+6(F[tF(FicqF]iqF*Fjp6$F2%&ThetaG6"F4C%>F7-Fjhq6'FAF;F[oFerFgy>FF-
Fgbn6%-Fhu6$Fi`rFjn-Fhu6$Fi`rF7f*Fj[pF46$FRFSF4&FcxFdfqF4F4F4O-Fabm6$-FL6$Febm,
&FjeqFB-Ffgo6$FFF7FBFgyF4F4F46#Fd`nF4,
I(supportt+6$'FdboFcbpFdamF46"F4C$Fbco<#FPF4F4F46#F_ilF4,
I,fixTemplatet+6'%'admonsGF[tFdam'%$monGF''FfcpF'6/F`jo%%monFG%&admonGFc^lF[\pF
ibpFit%#xFGF&Fe`pFftFjao%%mon1G6"F4C.>F7F_u>FF-FL6$f*6#FdboF46$FRFSF4-FhbrF[xF4
F46$F1FjnF;>F`w7#-Fjdn6$F__lF7?(FivFBFBF>FDC%>FdyFeq?(F^uFBFBF7FDC$>Fcy-FL6$f*6
#%#mfGF46$FRFSF4-Fhr6%-%'divideG6%&FZ6#F\xFA.%"qGF_frF\enF4F46&FccrFAFc^lFiv&FF
F\el@$0FcyF__lC%>&F`wF\el<$Fiel-Fhu6#Fffr>FdyFD[@$4FdyY%;Failed~to~correct~temp
lateG>Fa`l7#-F\\l6$-Fdu6$-Fcbl6$-Fdu6$&F[oF\elFgpFffrF^t/F^uFf^p>Fau7#-F\\l6$-F
\\l6$*&&F;F\elFBF`[oFB-Ff\l6$F`[o&Fa`lF\elF[hr>6$FealFb_l-FI6%Fau-F?FgalFjn>Ffb
l-F`]l6$-Fdu6$Fb_lFgp-Fdu6$FerFgp>Ffbl-F]io6$7#-FhuFg[q-Fa]m6#-FhuF`q>Fgel-Fgq6
$Fgir-Fhu6#Fer-F^v6#%/Template~fixedGO6&Fa`lFealFb_lFgelF4F4F46#FgsF4,
I2constructTemplatet+6&'%"HG<$FgbnF'F[tFdamFfcr6)F`joFecrFjcrF&Fe`pFftFjao6"F4C
+>F7F_u>FF-Fhr6%-Fg[l6$FAFgbn7#-F\\l6$&-FI6%&FA6$F`pF[\p-Fhu6$Fi`rFAFjnFdjn/F[
\pFf^pFA>F`w7#-F\\l6$-F\\l6$*&F`]rFBF`[oFB-Ff\l6$F`[o&FFFg`qF_\s>6$FivF^u-FI6%F
`w-F?FbjlFjn>Fcy-F`]l6$-Fdu6$F^uFgp-Fdu6$F[oFgp>Fcy-F]io6$7#-FhuFcflFhir>Fdy-Fg
q6$Fj]s-FhuFd_l@$0-Fhu6$FBFdy-Fhu6$FBF^uC$-F^v6#%7Template~is~incompleteG>6&FFF
ivF^uFdy-F`cr6'-F`]l6$-Fdu6$FdyFgpFb]sF;FjnFFF[o6%FF-Fg\p6%FivF^uFdyFdyF4F4F46#
FbpF4,
I-adjustParamst+6'F[t'FjjrFgbnFfcr'F1FgpFjp63F`joFgcp%#H1G%#LmG%%colsGFaiqFecrF
e`pFftF`iq%#smG%#rmG%#npG%#ssG%$prmGFa\qF\dn6"F4C3>F7F>>FF-Fhu6$Fi`rF;>F`wF;>Fi
v-F\\l6$-FI6%&F;F\\sFFF[oF_\s>F^u7#-F\\l6$-Ff_r6$f*FewF46$FRFSF4-%+membertypeG6
$F/-Fdu6$&&F_y6#,&F[\pF_ilF\wFB6$F`pFAF'F4F46$F\`sFiv7#-Fjdn6#;FB-Fhu6$7$FBF_il
&FivF_bsF_\s>Fby6$7#-F\\l6$&Fjbs6$F`pFcaqF_\s7#-F\\l6$&&Fiv6#,$F[\pF_il6#FcaqF_
\s>Ffbl7#-F\\l6$-FL6$f*FbxF46$FRFSF4-Fhbr6$-Febm6#*&&FZFg`qFBFAFBFenF4F46&F\tFA
F1F[o&FdyFg`qF_\s>Fau-Fdu6$-FL6$Fhu-FL6%-Fgbq6$FhuFduFfblFgpFgp>Feal-Fdu6$-F`]l
6$Fau-Fdu6$FjnFgpF'>Ffbl-F^tFg[q>Fgel-FL6$f*6#F`iqF46$FRFSF4-Fbw6$f*Fb[pF46$FRF
SF4-Fj_m6$FZF\inF4F46&F`iqFAF^`sF_y<#-Fjdn6#;FB-Fhu6$FBF_yF4F46$F^`sFfblFeal>Fa
`l7#-F\\l6$-%"+G6#-F\\l6$-F?6#-Fbw6%%$hasGFgel&&FgelFg`qFb[p/Fc^l;FB-F?6#F_hs/F
[\p;FB-F?Fj^m>Ff_lf*6&Fc^lF[\pF_`sF``sF46$FRFSF452-F?6#&FjnF:-F?6#&FjnF@3/F`isF
]is2&F[oF:&F[oF@F4F4F4>82-Fhdl6$7#-Fjdn6#;FBFa_mf*Fj[pF46$FRFSF4-Fbcl6&FAF;F_yF
\xF4F46(F_`sFgelF``sFa`lFa`sFf_l>Feal&Feal6#Fiis?&Fb_lFealFDC+>Fiv-F\\l6$-FI6%&
F`wF\\sFFF[oF_\s>Fby6$7#-F\\l6$FjbsF_\s7#-F\\l6$FfcsF_\s@$/-F?6#-F9FcflF[rF[gr>
Ffbl7#-F\\l6$-FL6$f*FbxF46$FRFSF4FbdsF4F4FhdsFidsF_\s>Fgel-FL6$f*FewF46$FRFSF4<
#-&F`^p6#%*SearchAllG6$FB-FL6$f*6#F_elF46$FRFSF4-F?6#-F]]l6$FA<#F_yF4F46$F`iqF_
yFAF4F46$F`iqFb_lFfbl>83<#-F\\l6$-Fhu6#-FL6$f*FjxF46$FRFSF4-Fhu6#-Fdu6$&&F_yFg`
qFabsFgpF4F46$FaiqFcyF_hsF_\s>84-Fgaq6$F]^tFer@$/-F?6#<#F__tF[r\>F`w-Fabm6$-FL6
%FfbqF`wF__tFer-Ffjr6&F`wFAF[oFjnF4F4F46#FgsF4,
I4isActionMatrixFoundt+6('F\`nFgbnFj\p'FccpF'Fc`p'FgcpF/Fjp6'%#tMG%#T1GFipFP%"r
G6"F4C'>F`wFc_l>Fiv,&F`wFBFerF\w>F7-Fabm6$-%*GaussjordG6$F;.F^uFgy>FF-Fabm6$-Fg
q6$,$&F76$;,(F^uFBFerF\wFBFBF^u;,$F`wF\wF\wF\w-Fgbn6%FivF`w<#-F\\l6$/6$,(FivFBF
[yF\wFBFB-F_^p6$&Fjn6#,$F[yF\wF[oFB/F[yFdcqFgy-&Fdo6#%&EqualGFdblF4F4F46#Fd`nF4,
I/SchurReductiont+6'Fj\pFecr'%#nEGF[qFjp'%%polsGF'63%#rgG%$crgGFP%#M1G%#bsG%#M2
G%$tM2G%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GFecp%#B3G%#B4G%$iB1G6"F4C3@$FcdpOF
A>F77#-F\\l6$-Fhu6#7#-Fjdn6#;,&-Fdcl6$-Fhu6$FBFd^p/Fc^l;FB,&F\^qFBF\wFBFBFBFB-F
dcl6$F]ft/Fc^l;FBF\^q-Ff\l6$F\^qFer>F`wFdv>FF7#-Fhu6#-F`]l6$<#-Fjdn6#;FBF]\s<#-
FhuFev>Fiv-Fgq6$&FA6$F7F`p&FA6$FFF`p>Fcy&Fiv6$FcgmF^^q>Fdy-Fabm6$-Fcat6$)FcyF]c
n.Fi`tF[o>Ffbl-FL6$f*Fb[pF46$FRFSF4-F_^p6$FB-Fdu6$FadoF'F4F46$FbdtFdy<#-Fjdn6#;
FBFi`t>Fgel-Fdu6$-F`]l6$<#-Fjdn6#;FB-Fhu6$FibsFdyFfblF'>Fau-Fgq6%&Fiv6$FfirF`p&
Fiv6$7#-FhuFj^mF`p&Fiv6$;FfemF\wF`p>Feal-Fabm6$-Fcat6$&FauF^htFehtF[o>Ffbl-FL6$
f*Fb[pF46$FRFSF4F[itF4F46$FddtFealF`it>Fgel-Fdu6$-F`]l6$<#-Fjdn6#;FB-Fhu6$FibsF
ealFfblF'>Fb_l-%$<|gr>G6%&Fau6$F`pFfir&Fau6$F`pFfjt&Fau6$F`p;,&FjnFBFBFBF\w>6&F
a`lFf_lFiisF]^t6&&Fb_l6$FcitFcit&Fb_l6$Fcit;,&Fi`tFBFBFBF\w&Fb_l6$Fe]uFcit&Fb_l
6$Fe]uFe]u>F__t-Fgip6$F[oFa`l-Fabm6$,&F]^tFB-Ffgo6%FiisF__tFf_lF\wF[oF4F4F46#Fg
sF4,
I0LinDepReductiont+6$Fj\pFjp6)Fi`tFg`tF_dt%$tM1GFfdt%&r2delG%&c2delG6"F4C*>FF-F
abm6$-Fcat6$)FAF]cnFe[pF;>F^u-FL6$f*Fb[pF46$FRFSF4F[itF4F46$Fg`tFF<#-Fjdn6#Ff^p
>Fcy-Fdu6$-F`]l6$<#-Fjdn6#;FB-Fhu6$FibsFFF^uF'>F`w&FA6$-Ff_r6$f*Fb[pF46$FRFSF4-
F^o6#-Ff\l6$FAF_yF4F46$Fi^uFcy7#F`gtF`p>Fiv-Fabm6$-Fcat6$F`wFe[pF;>F^u-FL6$f*Fb
[pF46$FRFSF4F[itF4F46$Fh^uFivFi_u>Fdy-Fdu6$-F`]l6$<#-Fjdn6#;FB-Ff`lF\elF^uF'6%&
F`w6$F`p-Ff_r6$f*Fb[pF46$FRFSF4F^auF4F46$Fj^uFdy7#-Fjdn6#;FB-Fhu6$FibsF`wFcyFdy
F4F4F46#F_ilF4,
I)rectTordt+6&F[tFat'%#TsGF'Fjp6(F`jo%#dgGFb^l%#nnG%$GBsGF\im6"F4C+>F7F>>FF7#-F
\\l6$*&-Fdcl6#-FL6%FjwFAFgtFBF7F\w-Ff\l6$FgtF;>F`w-FL6$f*6#FhtF46$FRFSF4*$FAF\w
F4F4F4FF>Fiv-Fg[r6#-Fhu6#-FL6$%&denomGF`w>F`w*&FivFBF`wFB>F^u-FL6$f*FewF46$FRFS
F4-Fe]m6%FZFA/FgnFenF4F46&F\tFAF.F[oFjn>Fcy7#-Fhu6#<#-F\\l6$&-Facn6$&F^uFb[p-&F
V6#%0LeadingMonomialG6$Fcgu&FjnFb[pF\o/Fc^l;FBF^eo>Fcy-FL6$f*FhenF46$FRFSF4-F^h
n6%f*F^elF46$FRFSF4FchnF4F4F4FAF_yF4F46$Fb^lF`wFcy-FL6$f*FewF46$FRFSF4-FjanF[xF
4F46$F1F;FcyF4F4F46#FbpF4,
I,filterBasest+6&F[t'FdglF''%%nQBsGF/'%#ffGFd[o6&%#mFG%#BsGFb`sF\cm6"F4C(>Fiv-F
]`l6#*&F[oFBFjnFB>F7-Fdu6$&-FI6%FAF>FddnFdjnFgp>FF-FL6$f*FewF46$FRFSF4-F?6#-F]]
l6$FfbmF_yF4F46$FfiuF7F;>F`w-Fhdl6%FF%">G/%'outputG%,permutationG-F^v6#-Fav6$Fi
v%>~quotient~space~bases~removedG7#-Fhu6$;FB,&FjnFBFivF\wF`wF4F4F46#FbpF4,
I(iniProbt+6&F`gl'%#qbGF[qFciu'%#pnGF/60F\t%#vFGF.F1F`duF\du%#GCGFdgl%$CMsGF+F[
anF)F_frFbiu6"F4C*AF_\m>6$F7F`w6$Fd\mF[o>FF-F^tFev@$0-&FV6#%1HilbertDimensionG6
$F7/FgnF`wF[rYQZThe~problem~is~expected~to~have~infinitely~many~solutionsF4>Fiv
F^]m@'/F;FBC)>6%F`wFcyFeal-F]^nF@>Ff_lFa_m-F^v6#-Fav6$Ff_l%8~change~matrices~lo
adedG>F^u7#-F\\l6$-Fabm6$-FL6$Febm-Fdu6$-Ffgo6$&FealFb[pFFF'F`w/Fc^l;FBFf_l>Fau
7#-F\\l6$&-F]^m6$Fcgu&FcyFb[pF\oFg_v>Fa`l-F]iu6&F7FauFf_lFjn>6&FealF^uFcyFau6&7
#-F\\l6$Ff_v-Ff\l6$Fc^lFa`l7#-F\\l6$FcguFj`v7#-F\\l6$F``vFj`v7#-F\\l6$&FauFb[pF
j`v/F;F_ilC*>Fau-F`ilF@>Ff_lF[ir-F^v6#-Fav6$Ff_l%=~quotient~space~bases~loadedG
>Fb_l-Fa]m6#F^gp>Fdy-Fe]m6&F7Fb_lFj]v/Fc[v%)extendedG>6$FgelFfbl6$&FdyF\o-Fgbn6
#&FdyFdjn>Fa`lFb`v>Fe`v6&7#-F\\l6$FfblFj`v7#-F\\l6$FgelFj`v7#-F\\l6$Fb_lFj`vFba
vC+>Fcy-FL6$f*FewF46$FRFSF4-Fa]m6#-FhuF@F4F4F4-&%)combinatG6#%(permuteGFicm>Fcy
-Fhcu6&F77#F^gpFcyF`w>Fdy-FL6$f*FewF46$FRFSF47#-Fe]m6&F_yFA/FgnF\xFfbvF4F46&F\t
F7F.F`wFcy>6$F^uFeal6$-FL6$f*FewF46$FRFSF4F^[rF4F4F4Fdy-FL6$f*FewF46$FRFSF4-Fgb
n6#F_[rF4F4F4Fdy>Ff_lF^eo>FauFj_v>Fa`l<#-F\\l6$-F_^p6$FeavFauFg_v>Fe`vFf`v-F^v6
#-Fav6&F[ir%A~quotient~space~bases~computed~(GFf_l%")G-F^v6#-Fav6%%AThe~problem
~is~expected~to~have~G-F?6#&FauF\o%+~solutionsGO6)F`wF7FivF^uFcyFauFealF4F4F46#
FbpF4,
I/TemplateFindert+6*F`gl>'%,action_varsG-F'6#<$%'negintGF/Fjil>F][mF[r>'%,filte
r_fracGFd[oF[r>'%&partsGFa[oFi`r>Fc[mFe[m>'%*quo_basesGF[qF[r>'%+schur_polsGFeh
vFjil6KF\tF.F1%&avarsGFf[oF`duF\duFdglFj\vF`cpF+Fc^lF[\pF[yFjjrFecrF&FjaoFccpFj
zFfcpF\`nF)Fjcq%#flGFPF\cm%#moG%#noGFc[o%$spoG%"NGFa^lFgcpFipF_fr%%irngG%#nkGFh
[oF[an%&tord1G6"F4C,>8?"(+++">8BF\w>6)FFF7F`wFcyFdyFauFeal-F`\v6&FAF]wF[oFgy>Fi
v-Fhr6%/F_uF[rF`w-FL6$f*6#F`^lF46$FRFSF4FadoF4F46$F1F`wF;>8G-%%iquoG6$F[ir&FerF
\o>8H7#-Fjdn6#;,&FBFB*&,&&FerFdjnFBF\wFBFBFg[wFBFB-Fhr6%/Fe\wF[\wF[ir*&Fe\wFBFg
[wFB>6%8D8F8I6%FbepFhgv-F?6#F]\w>8C,$*&F^]wF\wF\]wF\wFbal?(Ff_lFBFBF^]wFDC&>Fge
l&F]\w6#Ff_l>6&Fb_lFfbl8J8K6&&FcyFj^m&FdyFj^m&FauFj^m&FealFj^m>8L-Fhu6$FBFfbl?(
Fa`lFBFBF\]wFDC.>F^u&FivFifl>6(868788898:8;-F\cp6'F^uFb_lFfblFFF]^w>8E-F?6#Fb_w
>Fiis-Fhr6%/F]wF_il-Fj[q6'F7Fb_wF`wFFFjn-Ffcq6(F7Fb_wFc_wF^^wF`wFF>6%F]^tF__t85
-Fe_s6'F7FiisF`_wF`wFF>F__t-Fect6'F__tF]^t,(-Fhu6$FibsF__tFBF]]wF\wFg_wF\wFFFc_
o>F__t&-Fd^u6$F__tFFF\o>8<-F``t6(Fa_wF__tF^_wF__wFg_wFF>6$8=8>-Fhu6$FBF__t>8A-F
h^p6#F__t@&3Fbaw52FgawFdjv3/FgawFdjv2FgjvF\bwC%>6%Fdjv8@Fgjv6%FgawFhawF\bw-F^v6
#-Fg`m6(QTSmaller~or~sparser~template~found:~[%d,%d],%a,%a,%aF4FgawFhaw-F[go6$F
\bwFf]lF^u-Fhr6%F]`wFgelFe^w-F\[o6,FA7$FgawFhaw-F[go6$F\bwFgsFFF`wF^uFfblF__wF]
^t-F^o6#0F]wF_il4FbawY6&Q@Invalid~action~matrix,~%1,%2,%3F4FgelF^uFfbl-F^v6#-Fg
`m6*Q6%d%s,[%d,%d],%a,%a,%aF4-F]`l6#*&,&*&,&Ff_lFBF\wFBFBF\]wFBFBFa`lFBFBFc]wFB
Q"%F4FgawFhawF`cwF^uFbcw-F^v6#-Fg`m6&Q:Best~template:~[%d,%d],%aF4FdjvFibw-F[go
6$FgjvFf]lF4F4F46#FBF4,
I-readTemplatet+Fi_o6?F_\oF`\oF.F1Ff[oF+Fh[oFj[oF\t%#M0G%#U0G%&tord0GFe`pF`cpFc
cpFjzFfcpF\`nF)FgcpF&Fg`t%#t1GFi^uFj^uFjaoFftF`[o%#E0G6"F4C8>6*F7FFF`wFivF^uFcy
FdyFau-Fg_oFdfqAF_\m>FealFd\m>6$Fb_lFfbl-FI6%FealFa_mFiv>FgelFabv>Fa`l-F]io6$Ff
blFgel>Fb_l-Fg\p6%Fb_lFfblFa`l>Ff_l-Fe]m6%FealFcyFj]v>6'FiisF]^tF__tFd`wF^_w&-F
\cp6'F^uFf_lFcyF`wFdy6#;FBFgs>F__w-F?6#F^_w>6$F`_wFgaw&-Ffjr6&FauFealFivF__t6#;
F_ilFf]l>6%F`_wFc_wFbaw-Fd^u6$F`_wF`w>Fdjv7#-Fhu6$FBF`_w-F^v6#-Fav6$%2Template'
s~size:~GFdjv@$50&F7F\o&FdjvF\o0&F7Fdjn&FdjvFdjnYQ/Wrong~templateF4>Fgaw&Fgaw6#
-Ff_r6$f*Fb[pF46$FRFSF4F^auF4F46$Fj^uFbaw7#-Fjdn6#;FB-Fhu6$FBFgaw>Fa_w-Fabm6$-F
cat6#F`_wF`w>Fb_w-FL6$f*FewF46$FRFSF4-Fhu6#-Fbw6$f*Fc]tF46$FRFSF40&F_y6$FAFenF[
rF4F46&Fg`tF_yFfwFA<#-Fjdn6#;FB-Fhu6$Fi`rF_yF4F46$Fg`tFa_w<#-Fhu6#Fbaw>Fibw-Fdu
6$&Fgaw6#7#-FhuFi_wFgp>Fhaw-F]io6$-Fdu6$-F`]l6$-Fdu6$FgawFgp-Fdu6$F__tFgpF'Fgel
-F^v6#-Fav6$%6Action~matrix~found:~G-F``t6(Fd`wF`_wFiisF]^tF__wF`w60FivF^uFb_lF
a`lFhawF__tFiisF]^tFauFc_wFbawFdjvF__wFibwF4F4F46#F_ilF4,
I'colpivt+6&'FjaoF^t'F[fwFgpFe[oF*6+%#VlG%"PGF`t%#aPGFdcp%#P0G%#RPGFftF16"F4C3>
FealFadn>F7-Fdu6$-F`]l6$FfbmF;F'>FF-Fdu6$-Fbw6$f*FOF46$FRFSF4-Fj_m6$F]yF\xF4F46
&Ff[oFjnFf^xF7F7Fgp>F`w-Fbw6$f*FOF46$FRFSF4-Fdu6$-FL6$f*6#FgtF46$FRFSF4Fj_xF4F4
6&FPFAFg^xF\xF_y%$andGF4F46&F1FealFg^xFFFF@$/F^]sF[rYQ>Can't~solve~for~all~vari
ablesF4>F`w-Fhdl6$F`wf*6$F\^qF_frF46$FRFSF42-FjwFaau-Fjw6$F;F_yF4F46$F1Feal>F`w
-F]io6$-FL6$f*Fg`xF46$FRFSF4*&FAFB&F_yF\oFBF4F46$F`tF`w7$F_`mFBF[o-F^vFbjl>Fiv-
FL6$f*FOF46$FRFSF4F]yF4F46$Ff[oFjnFF>F^u-F]io6$-Fdu6$F\blF'F[o>Fcy-F`]l6$FF-Fdu
6$F`wFgp>FF7$-Fhu6#-F]io6$-Fdu6$FcyF'F[o-FhuFbjl>Fdy7$F[elF`fl>Fau-F]io6$-Fdu6$
-Fcbl6$-F`]l6$-Fdu6$F7FgpF__sF;F'F[o-F^v6(Q&nE~=~F4F[irQ&nR~=~F4F^eoQ&nP~=~F4Fa
z-F^v6%F;-Fdu6$-Fgq6$-FhuFgal-FhuFg]rF'FF6'FfexFauF^uFF7#-Fhu6#-F9FbjlF4F4F46#F
bpF4,
I7SolverGenerator_colpivt+6%F`gl>'Ffdt%'symbolGF\\o>'%)root_dirGFbglQ0../solver
s_tempF46NF1Ff[oFgewFe`pFftFfcpFccpFjzFhdtFecrFi^uFj^uF`[o%#nRGF+FjaoF[fwF\]pFd
cpFg^x%&vars0GF`joFipFict%#nPG%$nv0G%$iM0G%$eM0G%#ncGF&%#MtG%#m1G%#m2G%#iMG%#eM
G%#kkG%#llG%#mmG%#vvG%$dirGFggl%#fbGFc^l%&vars1G6"F4CX>8MQ%~~~~F4>60F7FFF`wFivF
^uFcyFdyFauFb_lFfblFgelFa`lFf_lF__t-Fdew6$FA-%&evalbG6#/F;F\\o>Fiis-Fa]m6#Fdgt>
F]^t-Fgq6$F[elFj]s>6'Fd`wF^uF^_wF__wF`_w-F`^x6&F]^tF__tFFFiis>6(Fa_wFb_wFc_wFf_
lFbawFgaw6(-Fhu6$Fi`rF`wF[irF^eoFigw-F?6#F__w-F?F[[x>Feal&F__w6#;,$Fb_wF\wF\w>F
haw7#-%(indicesG6$-Fdu6$F`wFibo%+indexorderG>Fdjv-FL6$f*FewF46$FRFSF4-Fdu6$,&F^
[rFB*&,&F_[rFBF\wFBFBF_yFBFBFbglF4F46$F`joFa_wFhaw>Fibw-F?6#Fhaw>8O-Fdu6$-F`]l6
$-Fdu6$F`_wFgp<#FFF'>F\bw-Fgbn6$-Fhu6$FBF`w<#-Fhu6#-F^hn6%f*F^elF46$FRFSF4/Fcdv
F;F4F4F4FhawFdjv>F\bw&-Ffjr6&Fb_l-Fdu6$-Ffgo6$F\bwFivF'F7FcyFdjn>F\bw&F\bw6$-Ff
_r6$f*Fb[pF46$FRFSF4F^auF4F46$Fi^uFfbl7#-Fjdn6#;FB-Fhu6$Fi`rF\bw-Ff_r6$f*Fb[pF4
6$FRFSF4F^auF4F46$Fj^uFgel7#-Fjdn6#;FB-Fhu6$FibsF\bw>F\bw-Fg\p6%F\bwF]^tFd`w>Fa
`l-Fhu6$FBF\bw>Fc]w&Fa`lF\o>F\]w,&Fc]wFBFc_wF\w>Fgjv-Fdu6$F\bwFibo>6$Fg_wF]]w6$
7#-Fejx6$FgjvFijx-FL6$Fhu7#-%(entriesGFa`y>Fg[w7#-F\\l6$,&&&Fg_w6#8NF\oFB*&Ff_y
FB,&&F]ayFdjnFBF\wFBFBFB/F_ay;FB-F?6#Fg_w>F]\w-FL6$f*6#%"cGF46$FRFSF4<#-F\]tFaa
uF4F46$FfgxF]]wFdjv>F^]w-FL6$f*FewF46$FRFSF4-FL6$f*Fc]tF46$FRFSF4FadoF4F46$Fggx
F_yFAF4F46$FggxFg[wF]\w>F]^w7#-F\\l6$-F_^p6$*&&Fi[yF^ayFB&FealFi_wFBFeal/F_ay;F
B,&FgawFBF\wFB>F^^w-Fav6%FjnQ"/F4FA@$4-F`]o6#F^^w-&Fa]o6#%.MakeDirectoryGF_dy>F
e^w-F\hl6$-Fav6+F^^wF[dy-Fhr6%FghxQ%std_F4Q&nstd_F4Ff_yQ"xF4&Fa`lFdjnQ)_colpiv_
F4FAFb\mFbhl-Fhhl6$Fe^w-Fav6'QH%%~Input:~coefficient~matrix~C~of~size~F4Fa_wF]e
yFecuQ#|+|+F4-Fhhl6$Fe^w-Fav6%Q5%%~Monomial~vector:~F4-Fdu6$FivF'Feey-Fhhl6$Fe^
w-Fav6,Q*function~F4F`_wQ$~=~F4FidyFf_yF]eyF^eyF_eyFAQ&(C)|+|+F4-Fhhl6$Fe^w-Fav
6&FahxQ(i_dx~=~F4-FL6$f*Fb[pF46$FRFSF4F^[rF4F4F4Fg_wQ#;|+F4-Fhhl6$Fe^w-Fav6&Fah
xQ(j_dx~=~F4-FL6$f*Fb[pF46$FRFSF4F_[rF4F4F4Fg_wF]gy-Fhhl6$Fe^w-Fav6&FahxQ(C_dx~
=~F4F]]wF]gy-Fhhl6$Fe^w-Fav6(FahxQ>M~=~sparse(i_dx,j_dx,C(C_dx),F4Ff_yQ",F4F^ey
Q$);|+F4@$0Fc_wF[rC&-Fhhl6$Fe^w-Fav6'Q"|+F4FahxQ5[L,|ir,Pi]~=~lu(M(:,1:F4Fc_wQ%
));|+F4-Fhhl6$Fe^w-Fav6$FahxQ+Pi~=~Pi';|+F4-Fhhl6$Fe^w-Fav6(FahxQ0M~=~[Pi*L~Pi(
:,F4,&Fc_wFBFBFBQ,:end)]\M(:,F4FgiyQ(:end);|+F4-Fhhl6$Fe^w-Fav6&FahxQ,M~=~full(
M(F4FgiyQ+:end,:));|+F4@$0Ff_lF[rC%-Fhhl6$Fe^w-Fav6'FjhyFahxQ6[L,UR,Pi]~=~lu(M(
:,1:F4Ff_lF\iyF]iy-Fhhl6$Fe^w-Fav6(FahxFfiy,&Ff_lFBFBFBFhiyF\[zFiiy-Fhhl6$Fe^w-
Fav6&FahxQ*MP~=~M(1:F4Ff_lQ&,:);|+F4-Fhhl6$Fe^w-Fav6&FahxQ(NP~=~M(F4F\[zQ+:end,
:);|+|+F4-Fhhl6$Fe^w-Fav6&FahxQ:[Q,U,Pi]~=~qr(NP(:,1:end-F4,&FgawFBFBFBF\iy-Fhh
l6$Fe^w-Fav6(FahxQ4A~=~UR\[MP(:,1:end-F4F^\zQ/)*Pi~MP(:,end-F4FgawQ):end)];|+F4
-Fhhl6$Fe^w-Fav6*FahxQ+B~=~U(:,1:F4,&F\]wFBFf_lF\wQ()\[U(:,F4,(F\]wFBFf_lF\wFBF
BQ3:end)~Q'*NP(:,end-F4FgawFe\z-Fhhl6$Fe^w-Fav6(FahxQ/M~=~[-A(:,end-F4,&Fb_wFBF
\wFBQ1:end)+A(:,1:end-F4Fb_wQ,)*B;~-B];|+|+F4-Fhhl6$Fe^w-Fav6&FahxQ&xP~=~F4-FL6
$f*FjcoF46$FRFSF4-F_^p6$*&FAFBF_yFB7$-FhuF]fr-Fhu6#FbclF4F46(Ff[oFFFg^xF__wFdcp
F^_wF__wF]gy-Fhhl6$Fe^w-Fav6*FahxQ*P1~=~[(1:F4,(FbawFBFgawF\wF\wFBQ&)*Pi~F4,&Fb
awFBFgawF\wQ":F4FbawQ$];|+F4-Fhhl6$Fe^w-Fav6-FahxQ-T~=~getT(M,[F4,&FbawFBFBFBF`
_z,&FbawFBFf_lFBQ+~P1(1:end-F4Fb_wQ+)],P1(end-F4Fd]zQ&:end)F4Q',xP);|+F4-Fhhl6$
Fe^w-Fav6%FjhyFahxQ1[V,D]~=~eig(T);|+F4-Fhhl6$Fe^w-Fav6*FahxQ*sol~=~[V(F4-Fdu6$
F]^wFbglQ/,:)./repmat(V(F4Fb_wQ%,:),F4FgcyQ3,1);~diag(D).'];|+|+F4-Fhhl6$Fe^w-F
av6$FahxQXI~=~find(not(isnan(sol(1,:)))~&~not(isinf(sol(1,:))));|+F4-Fhhl6$Fe^w
-Fav6$FahxQjo%%I~=~find(not(isnan(sol(1,:)))~&~not(isinf(sol(1,:)))~&~not(imag(
sol(1,:))));|+F4?(F_ayFBFBFgcyFD-Fhhl6$Fe^w-Fav6'FahxFccyQ(~=~sol(F4F_ayQ&,I);|
+F4-Fhhl6$Fe^w-Fav6'FahxFFF[bzFgawQ',I);|+|+F4-Fhhl6$Fe^wQ$endF4-F]il6#Fe^w6&Fb
_w7#Fa`lF7FivF4F4F46#FBF4,
I0SolverGeneratort+6%F`gl>FdfxF\\o>FgfxFifx6DF1Ff[oFgewFe`pFftFfcpFccpFjzFj[oFi
^uFj^uF`[oFgcpF[fwF`joFipFictFa^lF_gxF`gxFagxF&FbgxFegxFfgxFggxFhgxFigxFjgxF[hx
FgglF\hxFc^lF]hx6"F4CL>Fc]wFbhx>60F7FFF`wFivF^uFcyFdyFauFealFb_lFfblFgelFa`lFf_
lFehx>6&FiisF]^tF__tFd`w6&FhixF[irF^eoFdv>F^_wFcjx>F__w-FL6$f*FewF46$FRFSF4F_[y
F4F46$F`joFiisF^_w>F`_wFigw>Fg_w-Fdu6$-F`]l6$F[exF`\yF'>Fa_w-Fgbn6$Fd\y<#-Fhu6#
-F^hn6%f*F^elF46$FRFSF4F]]yF4F4F4F^_wF__w>Fa_w&-Ffjr6&Feal-Fdu6$-Ffgo6$Fa_wFivF
'F7FcyFdjn>Fa_w&Fa_w6$-Ff_r6$f*Fb[pF46$FRFSF4F^auF4F46$Fi^uFb_l7#-Fjdn6#;FB-Fhu
6$Fi`rFa_w-Ff_r6$f*Fb[pF46$FRFSF4F^auF4F46$Fj^uFfbl7#-Fjdn6#;FB-Fhu6$FibsFa_w>F
b_w-Fdu6$Fa_wFibo>6$Fc_wFbaw6$7#-Fejx6$Fb_wFijx-FL6$Fhu7#-Ff`yFhgz>Fgaw7#-F\\l6
$,&&&Fc_w6#F\]wF\oFB*&&FgelF\oFB,&&FchzFdjnFBF\wFBFBFB/F\]w;FB-F?6#Fc_w>Fhaw-FL
6$f*F[byF46$FRFSF4F^byF4F46$FfgxFbawF__w>Fdjv-FL6$f*FewF46$FRFSF4-FL6$f*Fc]tF46
$FRFSF4FadoF4F4FjbyFAF4F46$FggxFgawFhaw>Fibw7#-F\\l6$-F_^p6$*&&Fg_wFdhzFB&Fau6#
F]^tFBFau/F\]w;FB,&Fd`wFBF\wFB>F\bwFicy@$4-F`]o6#F\bw-FadyF^[[l>Fgjv-F\hl6$-Fav
6+F\bwF[dyFidyFfhzF]ey&FgelFdjnQ"_F4FAFb\mFbhl-Fhhl6$Fgjv-Fav6'FdeyFiisF]eyFecu
Feey-Fhhl6$FgjvFhey-Fhhl6$Fgjv-Fav6,FafyF7FbfyFidyFfhzF]eyFe[[lFf[[lFAFcfy-Fhhl
6$Fgjv-Fav6&Fc]wFhfy-FL6$f*Fb[pF46$FRFSF4F^[rF4F4F4Fc_wF]gy-Fhhl6$Fgjv-Fav6&Fc]
wFbgy-FL6$f*Fb[pF46$FRFSF4F_[rF4F4F4Fc_wF]gy-Fhhl6$Fgjv-Fav6&Fc]wF[hyFbawF]gy-F
hhl6$Fgjv-Fav6(Fc]wF`hyFfhzFahyFe[[lFbhy-Fhhl6$Fgjv-Fav6'FjhyFc]wF[iyF__tF\iy-F
hhl6$Fgjv-Fav6$Fc]wFaiy-Fhhl6$Fgjv-Fav6(Fc]wFfiy,&F__tFBFBFBFhiyFe^[lFiiy-Fhhl6
$Fgjv-Fav6&Fc]wQ+M~=~M(end-F4,&Fa`lFBF\wFBQ*:end,:);|+F4-Fhhl6$Fgjv-Fav6'FjhyFc
]wQ+T~=~zeros(F4F]^tFbhy-Fhhl6$Fgjv-Fav6*Fc]wQ%T(1:F4Fa`lQ.,:)~=~-M(:,1:F4Fa`lQ
')\M(:,F4FfflFiiy@&/,&F]^tFBFa`lF\wFB-Fhhl6$Fgjv-Fav6&Fc]wQ#T(F4*&F]^tFB-F_^p6$
&Fdy6#F\wFauFBQ()~=~1;|+F42FBF[`[l-Fhhl6$Fgjv-Fav6&Fc]wQ$T([F4&-Fdu6$7#-F\\l6$,
&*&F]^tFB,&-F_^p6$&Fdy6#,(F\]wFBF]^tF\wF\wFBFauFBF\wFBFBFBF\]wFB/F\]w;FfflF]^tF
bgl6#Fb]nQ)])~=~1;|+F4-Fhhl6$Fgjv-Fav6%FjhyFc]wFa`z-Fhhl6$Fgjv-Fav6*Fc]wFf`z-Fd
u6$FibwFbglFi`zF]^tFj`zFijzF[az-Fhhl6$Fgjv-Fav6$Fc]wF`az-Fhhl6$Fgjv-Fav6$Fc]wFe
az?(F\]wFBFBFijzFD-Fhhl6$Fgjv-Fav6'Fc]wFdjzF[bzF\]wF\bz-Fhhl6$Fgjv-Fav6'Fc]wFFF
[bzFd`wFabz-Fhhl6$FgjvFdbz-F]il6#Fgjv6&F]^tFgelF7FivF4F4F46#FBF4,
I.write_inidatat+6$Fagl>FgfxFifx6%F[hxFgglF\hx6"F4C,>F7-Fav6%F;F[dyFA>F`wFbhx@$
4F_]o-FadyFev>FF-F\hl6$-Fav6&F7Q*/inidata_F4FAFb\mFbhl-Fhhl6$FF-Fav6%Q9function
~data~=~inidata_F4FAQ$()|+F4-Fhhl6$FF-Fav6$F`wQ5data~=~cell([1,2]);|+F4-Fhhl6$F
F-Fav6$F`wQ7data|fr1|hr~=~randn(3,6);|+F4-Fhhl6$FF-Fav6$F`wQ7data|fr2|hr~=~rand
n(3,6);|+F4-Fhhl6$FFFdbzFg^oF4F4F46#FBF4,
I/write_test_numt+6)FaglFhpF_[oFat'Fe`pF^t>FdfxF\\o>FgfxFifx6(F[hxFgglF[\pF\hx%
$fb2G%&vars2G6"F4CG>F7-Fav6%F]wF[dyFA>FivFbhx>F^u-Fav6$FivFiv>Fcy-FL6$f*Fg`xF46
$FRFSF4-Fav6$FAFAF4F4F4F[o@$F\e[lF]e[l>FF-F\hl6$-Fav6&F7Q+/test_num_F4FAFb\mFbh
l-Fhhl6$FFQ+rng(23);|+|+F4-Fhhl6$FFQ-N~=~10000;|+|+F4-Fhhl6$FF-Fav6'Q%Err_F4FAQ
+~=~[];|+Tm_F4FAQ)~=~[];|+|+F4-Fhhl6$FFQ.for~i~=~1:N|+|+F4-Fhhl6$FF-Fav6&FivQ0d
ata~=~inidata_F4FAQN();~%%~generate~initial~data~of~the~problem|+|+F4-Fhhl6$FF-
Fav6$FivQ%try|+F4-Fhhl6$FF-Fav6$F^uQ&tic;|+F4-Fhhl6$FF-Fav6&F^uQ+C~=~coefs_F4FA
QV(data);~%%~compute~coefficients~of~polynomial~system|+F4-Fhhl6$FF-Fav6,F^uFcy
Fbfy-Fhr6%-Fhhx6#/FgyF\\oF[eyF\ey&FjnF\oF]ey&FjnFdjnFf[[lFAQA(C);~%%~solve~poly
nomial~system|+F4@$/FAQ1relpose_7p_fr_1sF4-Fhhl6$FF-Fav6$F^uQinww~=~arrayfun(@(
j)~get_w(C,xx(j),yy(j),zz(j)),~1:length(xx));|+F4-Fhhl6$FF-Fav6$F^uQ+tm~=~toc;|
+F4-Fhhl6$FF-Fav6&F^uQ,if~isempty(F4FielQ2);~continue;~end|+F4-Fhhl6$FF-Fav6$Fi
vQ*catch~ME|+F4-Fhhl6$FF-Fav6$F^uQ+continue;|+F4-Fhhl6$FF-Fav6$FivQ&end|+|+F4-F
hhl6$FF-Fav6$FivQ)M~=~[];|+F4-Fhhl6$FF-Fav6&FivQ0for~j=1:length(F4FielQ#)|+F4?(
F`wFBFBFc_lFD-Fhhl6$FF-Fav6'F^u&F[oFbjlFbfy&FcyFbjlQ&(j);|+F4-Fhhl6$FF-Fav6&F^u
Q%m~=~F4Fa_oF]gy-Fhhl6$FF-Fav6$F^uQ6m~=~m/norm(m,'fro');|+F4-Fhhl6$FF-Fav6$F^uQ
=M~=~[M;~norm(C*m.','fro')];|+F4-Fhhl6$FF-Fav6$FivQ%end|+F4-Fhhl6$FF-Fav6$FivQ.
M~=~sort(M);|+F4-Fhhl6$FF-Fav6&FivQ0err~=~norm(M(1:F4F;Q,),'fro');|+|+F4-Fhhl6$
FF-Fav6.FivFfi[lFAQ)~=~[Err_F4FAQ(~err];|+F4FivQ$Tm_F4FAQ(~=~[Tm_F4FAQ(~tm];|+|
+F4-Fhhl6$FFF_^\l-Fhhl6$FFQIfolder~=~fileparts(which('add_all.m'));|+F4-Fhhl6$F
F-Fav6'QCsave(strcat(folder,'\_results\Err_F4FAQ-.mat'),'Err_F4FAQ%');|+F4-Fhhl
6$FF-Fav6'QBsave(strcat(folder,'\_results\Tm_F4FAQ,.mat'),'Tm_F4FAQ&');|+|+F4-F
hhl6$FF-Fav6)Q3fprintf('Problem:~F4FAQin.~Ave.~runtime:~%%0.1f~ms.~Med.~error:~
%%0.2e\n',10^3*mean(Tm_F4FAQ.),median(Err_F4FAF\iyFg^oF4F4F46#FgsF4,
I0write_histo_numt+6$Fagl>FgfxFifxFdd[l6"F4C6>F7Fhd[l>F`wFbhx@$F\e[lF]e[l>FF-F
\hl6$-Fav6&F7Q,/histo_num_F4FAFb\mFbhlF]b\l-Fhhl6$FF-Fav6%QDload(strcat(folder,
~'\_results\Err_F4FAQ+.mat'));|+|+F4-Fhhl6$FFQ-bwd~=~3e-1;|+F4-Fhhl6$FFQ-nbins~
=~60;|+F4-Fhhl6$FFQ9clr~=~[70~100~160]/255;|+F4-Fhhl6$FF-Fav6%Q1err~=~log10(Err
_F4FAFbhy-Fhhl6$FFQLhr1~=~histogram(err,nbins,'BinWidth',bwd);|+F4-Fhhl6$FFQ6hr
1.FaceColor~=~clr;|+F4-Fhhl6$FFQ7hr1.EdgeColor~=~clr;|+|+F4-Fhhl6$FFQ8axis([-17
~1~0~1150]);|+|+F4-Fhhl6$FFQVset(gca,'fontsize',54,'fontname','Times~New~Roman'
);|+F4-Fhhl6$FFQFset(gcf,'PaperPositionMode','auto');|+F4-Fhhl6$FFQJset(gcf,'Pa
perOrientation','landscape');|+F4-Fhhl6$FFQGset(gcf,'PaperPosition',[1~1~28~19]
);|+F4-Fhhl6$FF-Fav6%QPprint(gcf,'-dpdf',strcat(folder,'\_results\fig-F4FAQ).pd
f'));F4Fg^oF4F4F46#FBF4
