M7R0
I*eigSolvert+6%'%"FG<%%'VectorG%%listG%$setG>'%'actvarG%(integerG""">'%'digitsG
%'posintG"#:6,%%fB2CG%%varsG%"aG%%tordG%"BG%$degG%"GG%"TG%"VG%"SG6"6"C/>8%7#-%#
opG6#-%'indetsG6#9$>8&&FD6#9%>8'-%%tdegG6#-FG6#FD>8$t+6$%"fGF:6#%"tG6"FAC$>FZ-%
&tableG6#-%$zipG6%f*6$F8%"bGFA6$%)operatorG%&arrowGFA/FQFLFAFAFA7#-%'coeffsG6%F
LFQ.%"mG7#F_p-%$mapG6$f*6#FeoFA6$FgoFhoFA-%#ifG6%-%)assignedG6#&T#FKF]q""!FAFA6
$FinFZFQFAFAFA6#""#>%'DigitsG9&>8*-&%)GroebnerG6#%&BasisG6$FLFS>8(&-&Fjq6#%*Nor
malSetG6$FgqFS6#F/>8)-%%nopsG6#F_r-%&printG6#-%$catG6%%@The~system~is~expected~
to~have~GFhr%'~rootsG>8+-&Fjq6#%5MultiplicationMatrixG6'FNF_r-F^o6#-%'EquateG6$
F_r7#-%"$G6#;F/FhrFgqFS>8,&-&%.LinearAlgebraG6#%-EigenvectorsG6#-%&evalfG6#Fes6
#Fbq>Fft-&%"|irG6#_FA%"/G6%Fft%#~$G-%".G6$-F(6$Fhr/%%fillGF/&FftFfr>8--F\v6$-%'
MatrixG6#-Fbp6$f*6#%"vGFA6$FgoFhoFA-T)6$-&Fjq6#%+NormalFormG6%FLF^qT%T'FAFA6*F<
FgqF9FSF:F_rF6FZFDFftFAFAFA6#F/FA,
I+isLinIndept+6&'%"MGF)'F<F)'F9%3ShortMonomialOrderG'%#ppGF36$F7F?6"FAC&>FZ-FJF
P@$/-FjrFKF/O%%trueG>FD&-%,poly2matrixG6%-Fbp6$f*6#F_pFA6$FgoFhoFA-Fdw6&FLT$T&/
%/characteristicGT(FAFA6(F<FQF9FeqFex9'FLF]yFZFfr-%#isG6#0-&&Fjt6#%(ModularG6#%
%RankG6$FbzFD-Fhz6$Fbz&FD6$;F/!"#;FAFAFAFAFA6#""%FA,
I*testBasist+6''F`xF*'F;F3FaxFbx'Fex%*nonnegintGFfx6"FAC&>FZ-FJ6#Feq@$2F]yFQO6$
%&falseG-%$<,>G6#-Fj\l6#F_q>FD&-Fcy6%-Fbp6$f*FhyFA6$FgoFhoFAFjyFAFA6(F<FeqF9Fbz
Fex9(FLF]yFZFfr6$-Fhp6%0Fg]lF_q-Fdz6#/-Fhz6$Fg]lFDFQ-Fdz6#/-&FjtF\[lFXFQFDFAFAF
A6#""&FA,
I*iniMonSett+6)F%'%#B0GF)'F7F)FaxFbxFdx>'%$domGF^\lF_q6*%"EGF`x%#vrG%"dGF;%%fla
gGF?%&d_minG6"FAC*>F_r-FjrFP>FesF_q>FZ-%(convertG6$-Fbp6$FG-&Fjq6#%(SupportGFKF
*-F]s6#-F`s6%%<Polynomial~system~contains~G-Fjr6#FZ%+~monomialsG>FDFZ?(FSF_qF/F
A1,&FSF/Fes!""9*C&>FN-%'selectG6$f*6#%"xGFA6$FgoFhoFA1-%'degreeG6$FLF\zFhwFAFA6
&F7FeqFd_lFSFD>FD-Fbp6$f*FhnFA6$FgoFhoFA-FG6#-Fbp6$f*6#%"kGFA6$FgoFhoFA*&F\zF/F
LF/FAFA6$FinFLF^qFAFA6$Fc_lFNFD>6$FhrFgq-Fh[l6'FDF_rFbzFg]l9)@$4Fhr>Fes,&FSF/F/
F/-F]s6#-F`s6%%6Initial~set~contains~G-FjrFXF]alO6$FZFDFAFAFA6#""(FA,
I-neighborMonst+6%'F:F*'%#MBGF*F]_l6#%#nBG6"FAC&@$/F]yF_qOFQ>FZ-Fgal6%%%typeG-F
bp6$FG<#-%$seqG6$-Fjel6$<$*&FeoF/F^wFbal*&FeoF/F^wF/-%#inG6$F^wFeq-Fbfl6$FeoFL%
)monomialG>FZ-%*intersectG6$-%&minusG6$FZFLFQ-Fhp6%/F[alF_qFQFZFAFAFA6#""$FA,
I)genBasist+6)'Fb_lF*F[\lF[_lF]_lFaxFbxFdx60%$rndGF:%#EBGFjdlF\el%$nB1G%#bvGF]c
lF8%#nvG%#wtGF_p%"iGF;6"FAC,>FZ,$-%%randG6#;F_q"%+5#F/Fghl>FD<">FSFQ>Fdv-Fjr6#F
bz>81-FjrFc\l>Fgq7#-Fjel6$-%&roundG6#-FZFA/80;F/Fdv>Fes-&%$maxG6#%&indexG6#-Fbp
6$f*FjalFA6$FgoFhoFA,&FLF/*&-F^qFAF/$"$+"F_qFbalF/FAFA6$FhglFZFgq>Fft&FbzF`u?(F
AF/F/FA2F`dlF`ilC*>FS-F\gl6$FSFD>F_r-Fedl6%FDFSFbz>FN-%&unionG6$FLFD>8.f*FjalFA
6$FgoFhoFA,*-Fhp6%-FbflF`blF/F_qF/-Fhp6%-Fbfl6$*&FhwF/FLF/FiwF/F_qF/-%$addG6$*&
&Faw6#T+F/-F_bl6$FL&T.F_]mF//F`]m;F/T/F/*&-T1FAF/F[[mFbalF/FAFA62Fb_lFLF8FftFig
lFNF[hlFgqF^hlF[jlF7FbzF\hlFdvFhglFZ>Fhr-%%sortG6$7#-FGF[sf*6$F[bl%"yGFA6$FgoFh
oFA1-F^qFP-F^qFKFAFA6$F]hlF^\m>6$8/F[jl6$&FhrFfrF/?(FAF/F/FA34-F\x6&7$FWF\_mFg]
lFfclFcal2F[jl-Fjr6#FhrC$>F[jl,&F[jlF/F/F/>F\_m&Fhr6#F[jl>FD<$FWF\_mFDFAFAFA6#F
ddlFA,
I*saveBasest+6$'%%probG%'stringG'%$QBsG<$F)F*6#%#fdG6"FAC%>FZ-%&fopenG6$-F`s6%Q
-nongb/nongb_FAFLQ%.txtFA%&WRITEG-Fbp6$f*FjalFA6$FgoFhoFA-%(fprintfG6%F^qQ$%a|+
FAFLFAFA6$F[amFZFQ-%'fcloseGF\alFAFAFA6#FbqFA,
I*readBasest+6#Fd`m6%%#stGFh`m%*nongbfileG6"FAC'>FZF/>FD7">FNFbam?(FAF/F/FA0FZF
_qC$>FZ-%)readlineG6#FN@$F`cm>FD7$FW-%&parseGF\alFDFAFAFA6#F/FA,
I,BasisFindert+6&Fd`m>'%-deg_over_minGF^\lF_q>'%1numbers_of_basesGF3F\[m>'%-pri
me_numberGF3"&\F$6/F&F7F9F<F\_lFd_lFb_lF`x%#BBGF:%#fnGF[amFex6"FAC2>FesF]cm>Fft
F]cm>F[jlFbzA-F`s6%Q,problems/F_FAFLQ#.mFA>FZ-%%evalG6#-F`s6$%#F_GFL>FD7#-FG6#-
FJF\al>FNFT>FS-Fiq6%FZFN/F_zF[jl>F_r&-Fbr6$FSFNFfr>6$FgqFes-Fh^l6)FZF_rFDFSFNF[
jlFQ>F^\mFbam>F\_m-F`am6$F^\mFfam-Fabm6#F\_m>F\_m-F`am6$F^\m%'APPENDG?(FAF/F/FA
2-Fjr6#FftFeqC$>Fdv-Fcgl6)FgqFesF_rFDFSFNF[jl@$4-%'memberG6$FdvFftC%>Fft7$-FGF
\hmFdv-F\bm6%F\_mF^bm-F^`l6$FdvF)-F]s6#-%(sprintfG6%Q%%d%sFA-Fgil6#,$*&F[hmF/Fe
qFbalF\[mQ,%~completedFAFcgmFAFAFA6#F/FA,
I*writeGfant+6%'F&Fi`m'F7Fi`mFdxFj`m6"FAC%>FZ-F`am6$Q/gfan/igfan.txtFAFfam-F\bm
6'FZQ+Z/%aZ%a|+%aFAFeq-F^`l6$FQF)-%$modG6$-Fbp6$%'expandG-F^`l6$FLF*FeqF`bmFAFA
FA6#FbglFA,
I)readGfant+Febm6'Fe_lFgbm%"nG%)gfanfileGFex6"FAC*>FZFh\l>FDF/>FNF_q>FS-F`s6%Q+
gfan/gfan_FAFLFeam>FD-Fdcm6#FS>F_r-Fjcm6#-%*substringG6$FD;Fbgl,&-&%,StringTool
sG6#%.FirstFromLeftG6$Q"[FAFDF/Fd[lF/?(FAF/F/FA0FDF_qC$>FDFb\n@(5/FDQ#|fr|frFA/
FDQ"|frFAC%>FZF_y>FN,&FNF/F/F/>(%#GBGFNF]cm3FZ0-Fh\n6$FDFbalQ"|hrFA>Fb^n7$-FG6#
Fb^n-Fh\n6$FDFc[l3FZ/Ff^nFh^nC$>Fb^nFj^n>FZFh\lO6%F_r7#-Fjel6$-Fbp6$Fjcm(Fc^nF^
hl/F^hl;F/FN7#-Fjel6$-Fbp6$f*FjalFA6$FgoFhoFA-Fjcm6#-Fh\n6$FL;F/,&-F]]n6$Q"+FAF
LF/FbalF/FAFAFAF[`nF\`nFAFAFA6#F/FA,
I(writeCMt+6&Fd`m'%$Ws0GF)'F]clF3Fdx6&F[amF&F7%#WsG6"FAC5>FZ-F`am6$-F`s6%Q'cm/i
cmFAFeqFeamFfamAFbem>FDFgem>FN-F^`l6$7#-FG6#-FJFXFf`m>FS-&F^]n6#%.SubstituteAll
G6%-Fjbn6%-F^`l6$FQFf`mFb]nQ"(FAQ"]FAQ")FA>FD-F^`l6$-F[[n6$-Fbp6$F_[nFDFbzFf`m-
F\bm6'FZQ<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+FAFSFbzFN-F\bm6&FZQ=f~=~openOut~"cm_%s_
%a.txt";|+FAFLFeq-F\bm6$FZQ<f~<<~toString(pp)~<<~endl;|+FA-F\bm6$FZQ<f~<<~toStr
ing(vr)~<<~endl;|+FA-F\bm6%FZQ9for~i~from~0~to~%a~do~(|+FA,&Fj_lF/FbalF/-F\bm6$
FZQ>f~<<~toString(Ws#i)~<<~endl;|+FA-F\bm6&FZQ.R~=~ZZ/%a%s,~FAFbz-Fh\n6$FNFc[l-
F\bm6$FZQDMonomialOrder~=>~Weights~=>~Ws#i];|+FA-F\bm6%FZQ0I~=~ideal(%s);|+FA-F
h\n6$FD;FbqFd[l-F\bm6$FZQVG~=~gb(I,ChangeMatrix=>true);|+M~=~getChangeMatrix~G;
|+FA-F\bm6$FZQ>f~<<~toString(M)~<<~endl;|+);|+FA-F\bm6$FZQ,f~<<~close;FAF`bmFAF
AFA6#Fg[lFA,
I'readCMt+Febm6(Fgbm%'cmfileGFexF7F_pFf[n6"FAC*>FZF/>F_rF_q>FhrF_q>FD-F`s6%Q'cm
/cm_FAFLFeam>FN-Fjcm6#-FdcmFX>FSFegn?(FAF/F/FAF`cmC$>FZFggn@&3F`cm/-Fh\n6$FZF/F
bcnC$>F_r,&F_rF/F/F/>(F=F_r-Fh\n6$FZF\fn3F`cm/-Fh\n6$FZ;F/""'Q'matrixFAC$>Fhr,&
FhrF/F/F/>(%#CMGFhr-Fjbn6%-Fjbn6%-Fh\n6$FZ;""*Fd[lF\^nFb]nFh^nFccnO6%FN7#-Fjel6
$-%%wdegG6$7#-Fjcm6#(F=F^hlFS/F^hl;F/F_r7#-Fjel6$)-Fhv6#7#-Fbp6$Fjcm(FdinF^hl%#
%TG/F^hlFdtFAFAFA6#F/FA,
I(getTordt+6$%#gbG%#lmG6+F7F\hl%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG%$solG%&f
degsG6"FAC,>FZFE>FDF[al>FN/7#-Fbt6$F_qFD%%NULLG>FS7#-Fjel6$(Fd_lF^hl/F^hl;F/FD>
F_r-Fbp6$f*6#%"zGFA6$FgoFhoFA-Fbp6$f*FjalFA6$FgoFhoFA7#-Fjel6$-F_bl6$FLFd^m-Fbf
l6$Fd^mF^qFAFA6$F7F^q-F^`l6$FLF)FAFA6$F7FZFL>Fhr-Fbp6$f*FjalFA6$FgoFhoFAFa^oFAF
AF[_oFQ>Fgq-Fbp6$f*F\clFA6$FgoFhoFA-FG6#-Fbp6$f*FjalFA6$FgoFhoFA1F/-F[]m6#-Fao6
%f*6$Fd^mF[^oFA6$FgoFhoFA*&FLF/FQF/FAFAFAFLF^qFAFA6$F_\oFaw-%%subsG6$F^q7#-Fjel
6$,&&FhwFKF/%"gGFbal-Fbfl6$F^ao&FiwFKFAFA6*F^\oFNFa\oFhrF`\oF_rF_\oFS<#-Fbt6#;F
/F]y>Fes&-&%-OptimizationG6#%)MinimizeG6&-F[]mFc\nFgq/%+depthlimitG"#S/%'assume
GF^\lFau>Fft-Fg`o6$FesFS6$Fft-Fcjn6$FftFZFAFAFA6#FbqFA,
I)saveDatat+6,Fd`m'%#mnG7$F3F3'%#spG%(numericGF]\lF^jm'%#avGFfflFbx'%#QBGF)'%'s
hiftsGF)'%$stdG%(booleanG6'F[emF[am%$mn0G%$sp0GFe_l6"FAC&>FZ-Fhp6%9--F`s6%Q-opt
im/o_std_FAFLFeam-F`s6%Q.optim/o_nstd_FAFLFeam>F_rFh\l@%-&%*FileToolsG6#%'Exist
sGF\alC'>FD-F`am6$FZ%%READG>FN-Fjcm6#-FdcmF\al>FSFjeo@$52&FQFfr&FNFfr3/FafoFbfo
2FSFeq>F_rF_y-FabmFX>F_rF_y@$F_rC%>FD-F`am6$FZFfam-F\bm6,FDQ8%a|+%a|+%a|+%a|+%a
|+%a|+%a|+%aFAFQFeqFbz-F^`l6$Fg]lF)FfclFcal9+9,FgfoFAFAFA6#"#5FA,
I)readDatat+6$Fd`mF[do6,F[emF[amF`coFccoFexF7FfcoF9FhcoFjco6"FAC.>FZ-Fhp6%FQFgd
oFjdo>FDFfeo>FNFjeo>FSFjeo>F_rFjeo>FhrFjeo>FgqFjeo>FesFjeo>FftFjeo>FdvFjeoFgfo6
*FNFSF_rFhrFgqFesFft-Fbp6$FhemFdvFAFAFA6#FbqFA,
I$srtf*6$'F^wF'FbxFA6$FgoFhoFA-F^^m6$FLf*Fc^mFA6$FgoFhoFA-&Fjq6#%*TestOrderG6%F
QFLF\zFAFA6$F9FQFAFAFAFA,
I,poly2matrixt+6%F%'%#nFGF3F^jm6$%%monsG%%cffsG6"FAC$>FD7#-F\p6%-F_[n6#-F[]m6$*
&(%$q_qGF^hlF/&FL6#F^hlF//F^hl;F/FQFeq.FZ6$-Fhv6%FQF`dlf*6$F^hl%"jGFA6$FgoFhoFA
-%&coeffG6$&F^qFP(F`[pFLFAFA6$FcjoFD-F(6#7#FZFAFAFA6#FbglFA,
I/permuteColumnst+6%'F`xFhv'%#V1GF('%#V2GF(6#Ff[n6"FAC$>FZ-FG6$F/FQ-F\v6$FL-Fhv
6$FZ<#-Fjel6$/6$F^hl-&%*ListToolsG6#%'SearchG6$&FQFb[pFeqF//F^hl;F/FZFAFAFA6#Fb
glFA,
I)sparsityt+6#Fj\p6#%&numzrG6"FAC$>FZ-Fjr6#-Fgal6$f*FjalFA6$FgoFhoFA-Fdz6#/FLF_
qFAFAFAFi^o*&FZF/-%$mulG6#-FG6$F/FLFbalFAFAFA6#F/FA,
I(matrixSt+6''F:F)F[_lFaxFbxF]\l6%F?%#V0GF;6"FAC&>FNF]y@$0Fj_lFNY%ILists~B0~and
~B~must~have~the~same~lengthG>Fbdl-Fcy6%-Fbp6$f*FepFA6$FgoFhoFAFjyFAFAFf]lFLFNF
b\l@%/-FG6$F/FDFNO-Fg\p6%FZFD-F(FPY%=Failed~to~construct~matrix~SGFAFAFA6#Fg^lF
A,
I*quotientst+6&'F^ao%(polynomGFaxFbxF]\lFA6"FAC$-Fdw6'FLFQFeq.%"QG/F_zFbzFibpFA
FAFA6#Fg[lFA,
I-monPartitiont+6'Feco'%#GrGF)FbxF]\l>FgcoF]cm6-F\_lF:%#aBG%"RG%#B2G%#RBGF<%#nG
GF=F?F^hl6"FAC->FZ&-Fbr6$FQFeqFfr>FD-F^`l6$-Fhp6%/Fg]lF]cmFZFg]lF*>FN-Fbp6$f*Fj
alFA6$FgoFhoFAF_clFAFA6$FfcoFLFD>FS-F]io6$-F^`l6$-F\gl6$FNFDF)Feq>Fes-FjrFc\n>F
_r-Fbp6$f*FjalFA6$FgoFhoFA*&FLF/F\zFbalFAFAFidp-FiflF`ep>FD7$-FG6#-F]io6$-F^`l6
$-F\gl6$FDF_rF)Feq-FG6#-F]io6$-F^`l6$F_rF)Feq>6$FhrFN6$7$-FGFc\nFW-Fbp6$f*FjalF
A6$FgoFhoFAF_clFAFAFidpFD@%Fcdp>Fft-Fgs6(FLFD-F^o6#-F^t6$FD7#-Fbt6#;F/F`dlFQFeq
FjbpC%>Fft-Fgs6(FLFZ-F^o6#-F^t6$FZ7#-Fbt6#;F/F[alFQFeqFjbp>Fdv-F``p6'FDFZFQFeqF
bz>Fft-Fhp6%0FbzF_q-F[[n6$-F\v6%FdvFft-&Fiz6#%(InverseG6$FbzFdvFbz-F\v6%FdvFft-
&Fjt6#%.MatrixInverseG6#Fdv>Fgq-F^`l6$,&-F(Fc\nF/-F\v6$&Fft6$;F/FesFe[l-F(FXFba
lF)O6(FNFDFhrFftFgq-Fhv6#7#-Fjel6$-F_bp6&&Fgq6#F^\mFQFeqFbz/F^\mF[[qFAFAFA6#Fg^
lFA,
I(matrixHt+6'F%FaxF^jmF]\lF__l6/%*undetPolyG%#pvGF`joFgcp%#uHG%%leqsGFc\oF^hl%#
dFG%#dGGFd_lFf_l%"hG6"FAC)>FD-F[]mFc\l>FNF]y>FSFj_l>Fft-Fbp6%F_blFLFeq>FZt+6&F^
jmF_\qFd_lF[\p6#Fbjo6"FAC%-F\p6%-F_[n6#,&F/F/-F[]m6$)FQ%"pG/F\^q;F/FeqF/FLFe[p>
FZFe\p-F[]m6$*&&FZF\clF/&%#_vG6$FbzF]clF//F]clFjhpFAFAFA6#Fg[l?(FesF/F/FSF_yC%>
6$F\_mFdv6$F_q-Fbp6$f*FjalFA6$FgoFhoFA-F`jl6$F_qFLFAFAFA,&7#-Fbt6$-F_bl6$&FQF`u
FeqFNF/FftFbal?(F^\mF_qF/FA1,&F^\mF/F\_mFbalFg]lC&>F_r7#-Fjel6$-FZ6&FeqFD,&&Fdv
6#F[\pF/F^\mF/F[\p/F[\pF]`n>Fhr<#-F\p6$-F_[n6#,&Fj_qFbal-F[]m6$*&&F_rFg`qF/&FLF
g`qF/Fh`qF/Feq>Fgq-%'msolveG6$FhrFbz@$/-Fjr6#<#FgqF_q>F\_m,&F^\mF/F/F/>&F[jlF`u
-F[[n6$-Fbp6%-%"@G6$F_[nFhemF_rFgqFbzO-Fj\l6#-Fjel6$-&F(6#%$rowG6#Fabq/Fes;F/FS
FAFAFA6#Fg^lFA,
I*matrixHnit+6(F%Fax'%"CGFhv'FdinFhvF^jmF]\l6*%,undetPolyniGF`joFgcp%#H0GF`\qFa
\qFc\o%%parsG6"FAC+>FDF]y>FNFj_l>FZt+6&'Fd\qFcbpF^jm'F^hlF3'F[\pF3Fa]q6"FAC%-F
\p6%FLFQFe[p>FZFe\p-F[]m6$*&Fc^qF/&Fe^q6%FeqFbzF]clF/Fg^qFAFAFA6#Fg[l>FS-F[[n6$
-Fbp6$F_[n-F\v6$FeqFbzFfcl>F_r-Fhv6%FNFDf*Fj[pFA6$FgoFhoFA-Fiw6&&F^q6$FLFQF]zFL
FQFAFA6(F^dqFSF7Fg]lF]dqFZ>Fes<#-Fjel6$&%#_uGFb[p/F^hl;F/-Fjr6#-F\gl6$-FJF[sFg]
l>Fhr-Fbp6%F\p<#-Fjel6$-F[[n6$-F_[n6#,&Fd^pFbal-F[]m6$*&&F_rFj[pF/FdaqF//F[\pFe
]oF/FfclF\`nFg]l>Fgq-Fgaq6%FhrFesFfclO-F[[n6$FdbqFfclFAFAFA6#F]inFA,
I*syzModulet+6'F%Fax'%"AGFhvFbxF]\l6*F`joFgcp%"eG%"LG%#LtGF`xF?F:6"FAC.>FZF]y>F
DFj_l>FN-Fjel6$-F(6$FD<#/F^hlF/Fd]o>FS7#-Fjel6$7#-&Fjq6#%,LeadingTermG6$Fd^pFbz
Fd]o>F_r-Fbp6$f*FjalFA6$FgoFhoFA*&&FLFfrF/&FLFauF/FAFAFAFS>Fhr-Fhv6$FDf*Fj[pFA6
$FgoFhoFA*&-%$lcmG6$&F]qFau&F`\pFauF/F]aoFbalFAFA6&FaiqFSFbiqF_r>Fgq7#-Fjel6$-F
jel6$,(*&&FhrFj[pF/&FNFb[pF/F/*&&Fhr6$F[\pF^hlF/&FNFg`qF/Fbal-Fj\l6#-F_bp6&z'6&
Fd\rFg\rFd^p&FQFg`q[[[\[[[[[\[[mF/\[[[[[\[[[[[mFbalFQFbzFg]lFbal/F[\p;,&F^hlF/F
/F/FDFd]o>Fgq)-Fhv6#FgqFe[o>Fes-Fhv6#7#-Fjel6$-F_bp6&Fa[pFQFbzFg]lFe^p>Fgq-Fbp6
$F_[n-Fj\l6$-F\v6$FgqFeq,&-&Fjt6#%/IdentityMatrixGF\alF/-F\v6$FesFeqFbal@$F[^l>
Fgq-F[[n6$FgqFg]lO&Fgq6$-%'removeG6$f*Fb[pFA6$FgoFhoFA-&%+ArrayToolsG6#%'IsZero
G6#&F^q6$FLFe[lFAFA6$F?Fgq7#-Fbt6#;F/-FG6$7$F/F/FgqFe[lFAFAFA6#Fg^lFA,
I+matrixHsyzt+6(F%FaxFicqF]iqFbxF]\l6$F?%&ThetaG6"FAC%>FZ-Fjhq6'FLFQFbzFg]lFfcl
>FD-Fhv6%-FG6$Fi`rFeq-FG6$Fi`rFZf*Fj[pFA6$FgoFhoFA&FinFdfqFAFAFAO-F[[n6$-Fbp6$F
_[n,&FjeqF/-F\v6$FDFZF/FfclFAFAFA6#F]inFA,
I(supportt+6$'FgnFcbpF^jmFA6"FAC$F[p<#F_pFAFAFA6#FbqFA,
I,fixTemplatet+6'%'admonsGF%F^jm'%$monGF)'FfcpF)6/F`jo%%monFG%&admonGF^hlF[\pFi
bpFe_l%#xFGF`xFe`pFb_lF>%%mon1G6"FAC.>FZFj_l>FD-Fbp6$f*6#FgnFA6$FgoFhoFA-FhbrF`
blFAFA6$F7FeqFQ>FN7#-Fbt6$FjhlFZ?(FSF/F/F]yF_yC%>FgqFh\l?(F_rF/F/FZF_yC$>Fhr-Fb
p6$f*6#%#mfGFA6$FgoFhoFA-Fhp6%-%'divideG6%&F\z6#FhwFL.%"qGF_frF^]oFAFA6&FccrFLF
^hlFS&FDF[s@$0FhrFjhlC%>&FNF[s<$F^_m-FG6#Fffr>FgqF_y[@$4FgqY%;Failed~to~correct
~templateG>F[jl7#-Fjel6$-F^`l6$-F[\m6$-F^`l6$&FbzF[sF*FffrF(/F_rFf^p>Fes7#-Fjel
6$-Fjel6$*&&FQF[sF/F`coF/-Fbfl6$F`co&F[jlF[sF[hr>6$FftFdv-Fcy6%Fes-FjrF`uFeq>F^
\m-F\gl6$-F^`l6$FdvF*-F^`l6$Fg]lF*>F^\m-F]io6$7#-FGFg[q-FU6#-FGFc\l>F\_m-Fj\l6$
Fgir-FG6#Fg]l-F]s6#%/Template~fixedGO6&F[jlFftFdvF\_mFAFAFA6#Fg^lFA,
I2constructTemplatet+6&'%"HG<$FhvF)F%F^jmFfcr6)F`joFecrFjcrF`xFe`pFb_lF>6"FAC+>
FZFj_l>FD-Fhp6%-Feel6$FLFhv7#-Fjel6$&-Fcy6%&FL6$Fe[lF[\p-FG6$Fi`rFLFeqFau/F[\pF
f^pFL>FN7#-Fjel6$-Fjel6$*&F`]rF/F`coF/-Fbfl6$F`co&FDFg`qF_\s>6$FSF_r-Fcy6%FN-Fj
rFecmFeq>Fhr-F\gl6$-F^`l6$F_rF*-F^`l6$FbzF*>Fhr-F]io6$7#-FGFg_mFhir>Fgq-Fj\l6$F
j]s-FGF^il@$0-FG6$F/Fgq-FG6$F/F_rC$-F]s6#%7Template~is~incompleteG>6&FDFSF_rFgq
-F`cr6'-F\gl6$-F^`l6$FgqF*Fb]sFQFeqFDFbz6%FD-Fg\p6%FSF_rFgqFgqFAFAFA6#Fg[lFA,
I-adjustParamst+6'F%'FjjrFhvFfcr'F7F*F]\l63F`joFgcp%#H1G%#LmG%%colsGFaiqFecrFe`
pFb_lF`iq%#smG%#rmG%#npG%#ssG%$prmGFa\qFc\o6"FAC3>FZF]y>FD-FG6$Fi`rFQ>FNFQ>FS-F
jel6$-Fcy6%&FQF\\sFDFbzF_\s>F_r7#-Fjel6$-Ff_r6$f*FjalFA6$FgoFhoFA-%+membertypeG
6$F3-F^`l6$&&F^q6#,&F[\pFbqFbalF/6$Fe[lFLF)FAFA6$F\`sFS7#-Fbt6#;F/-FG6$7$F/Fbq&
FSF_bsF_\s>Fccl6$7#-Fjel6$&Fjbs6$Fe[lFcaqF_\s7#-Fjel6$&&FS6#,$F[\pFbq6#FcaqF_\s
>F^\m7#-Fjel6$-Fbp6$f*FhnFA6$FgoFhoFA-Fhbr6$-F_[n6#*&&F\zFg`qF/FLF/F]zFAFA6&F&F
LF7Fbz&FgqFg`qF_\s>Fes-F^`l6$-Fbp6$FG-Fbp6%-Fgbq6$FGF^`lF^\mF*F*>Fft-F^`l6$-F\g
l6$Fes-F^`l6$FeqF*F)>F^\m-F(Fg[q>F\_m-Fbp6$f*6#F`iqFA6$FgoFhoFA-Fgal6$f*Fb[pFA6
$FgoFhoFA-Fdhm6$F\zF]aoFAFA6&F`iqFLF^`sF^q<#-Fbt6#;F/-FG6$F/F^qFAFA6$F^`sF^\mFf
t>F[jl7#-Fjel6$-%"+G6#-Fjel6$-Fjr6#-Fgal6%%$hasGF\_m&&F\_mFg`qFb[p/F^hl;F/-Fjr6
#F_hs/F[\p;F/-FjrFdgm>F`ilf*6&F^hlF[\pF_`sF``sFA6$FgoFhoFA52-Fjr6#&FeqFP-Fjr6#&
FeqFK3/F`isF]is2&FbzFP&FbzFKFAFAFA>82-F^^m6$7#-Fbt6#;F/F[hmf*Fj[pFA6$FgoFhoFA-F
iw6&FLFQF^qFhwFAFA6(F_`sF\_mF``sF[jlFa`sF`il>Fft&Fft6#Fiis?&FdvFftF_yC+>FS-Fjel
6$-Fcy6%&FNF\\sFDFbzF_\s>Fccl6$7#-Fjel6$FjbsF_\s7#-Fjel6$FfcsF_\s@$/-Fjr6#-FJFg
_mF_qF[gr>F^\m7#-Fjel6$-Fbp6$f*FhnFA6$FgoFhoFAFbdsFAFAFhdsFidsF_\s>F\_m-Fbp6$f*
FjalFA6$FgoFhoFA<#-&F`^p6#%*SearchAllG6$F/-Fbp6$f*6#Fd^mFA6$FgoFhoFA-Fjr6#-Fifl
6$FL<#F^qFAFA6$F`iqF^qFLFAFA6$F`iqFdvF^\m>83<#-Fjel6$-FG6#-Fbp6$f*F\clFA6$FgoFh
oFA-FG6#-F^`l6$&&F^qFg`qFabsF*FAFA6$FaiqFhrF_hsF_\s>84-Fgaq6$F]^tFg]l@$/-Fjr6#<
#F__tF_q\>FN-F[[n6$-Fbp6%FfbqFNF__tFg]l-Ffjr6&FNFLFbzFeqFAFAFA6#Fg^lFA,
I4isActionMatrixFoundt+6('F=FhvFj\p'FccpF)Fc`p'FgcpF3F]\l6'%#tMG%#T1GF;F_p%"rG6
"FAC'>FNF]il>FS,&FNF/Fg]lFbal>FZ-F[[n6$-%*GaussjordG6$FQ.F_rFfcl>FD-F[[n6$-Fj\l
6$,$&FZ6$;,(F_rF/Fg]lFbalF/F/F_r;,$FNFbalFbalFbal-Fhv6%FSFN<#-Fjel6$/6$,(FSF/F]
clFbalF/F/-F_^p6$&Feq6#,$F]clFbalFbzF//F]clFdcqFfcl-&Fjt6#%&EqualGF\\mFAFAFA6#F
]inFA,
I/SchurReductiont+6'Fj\pFecr'%#nEGF^\lF]\l'%%polsGF)63%#rgG%$crgGF_p%#M1G%#bsG%
#M2G%$tM2G%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GFecp%#B3G%#B4G%$iB1G6"FAC3@$Fcd
pOFL>FZ7#-Fjel6$-FG6#7#-Fbt6#;,&-F[]m6$-FG6$F/Fd^p/F^hl;F/,&F\^qF/FbalF/F/F/F/-
F[]m6$F]ft/F^hl;F/F\^q-Fbfl6$F\^qFg]l>FNF[al>FD7#-FG6#-F\gl6$<#-Fbt6#;F/F]\s<#-
FGF\al>FS-Fj\l6$&FL6$FZFe[l&FL6$FDFe[l>Fhr&FS6$F]`nF^^q>Fgq-F[[n6$-Fcat6$)FhrFe
[o.Fi`tFbz>F^\m-Fbp6$f*Fb[pFA6$FgoFhoFA-F_^p6$F/-F^`l6$F]qF)FAFA6$FbdtFgq<#-Fbt
6#;F/Fi`t>F\_m-F^`l6$-F\gl6$<#-Fbt6#;F/-FG6$FibsFgqF^\mF)>Fes-Fj\l6%&FS6$FfirFe
[l&FS6$7#-FGFdgmFe[l&FS6$;F`^nFbalFe[l>Fft-F[[n6$-Fcat6$&FesF^htFehtFbz>F^\m-Fb
p6$f*Fb[pFA6$FgoFhoFAF[itFAFA6$FddtFftF`it>F\_m-F^`l6$-F\gl6$<#-Fbt6#;F/-FG6$Fi
bsFftF^\mF)>Fdv-%$<|gr>G6%&Fes6$Fe[lFfir&Fes6$Fe[lFfjt&Fes6$Fe[l;,&FeqF/F/F/Fba
l>6&F[jlF`ilFiisF]^t6&&Fdv6$FcitFcit&Fdv6$Fcit;,&Fi`tF/F/F/Fbal&Fdv6$Fe]uFcit&F
dv6$Fe]uFe]u>F__t-Fgip6$FbzF[jl-F[[n6$,&F]^tF/-F\v6%FiisF__tF`ilFbalFbzFAFAFA6#
Fg^lFA,
I0LinDepReductiont+6$Fj\pF]\l6)Fi`tFg`tF_dt%$tM1GFfdt%&r2delG%&c2delG6"FAC*>FD-
F[[n6$-Fcat6$)FLFe[oFe[pFQ>F_r-Fbp6$f*Fb[pFA6$FgoFhoFAF[itFAFA6$Fg`tFD<#-Fbt6#F
f^p>Fhr-F^`l6$-F\gl6$<#-Fbt6#;F/-FG6$FibsFDF_rF)>FN&FL6$-Ff_r6$f*Fb[pFA6$FgoFho
FA-Fdz6#-Fbfl6$FLF^qFAFA6$Fi^uFhr7#F`gtFe[l>FS-F[[n6$-Fcat6$FNFe[pFQ>F_r-Fbp6$f
*Fb[pFA6$FgoFhoFAF[itFAFA6$Fh^uFSFi_u>Fgq-F^`l6$-F\gl6$<#-Fbt6#;F/-F`jlF[sF_rF)
6%&FN6$Fe[l-Ff_r6$f*Fb[pFA6$FgoFhoFAF^auFAFA6$Fj^uFgq7#-Fbt6#;F/-FG6$FibsFNFhrF
gqFAFAFA6#FbqFA,
I)rectTordt+6&F%F]_l'%#TsGF)F]\l6(F`jo%#dgGF]hl%#nnG%$GBsGFfan6"FAC+>FZF]y>FD7#
-Fjel6$*&-F[]m6#-Fbp6%F_blFLFc_lF/FZFbal-Fbfl6$Fc_lFQ>FN-Fbp6$f*6#Fd_lFA6$FgoFh
oFA*$FLFbalFAFAFAFD>FS-Fg[r6#-FG6#-Fbp6$%&denomGFN>FN*&FSF/FNF/>F_r-Fbp6$f*Fjal
FA6$FgoFhoFA-Fiq6%F\zFL/F_zF]zFAFA6&F&FLFexFbzFeq>Fhr7#-FG6#<#-Fjel6$&-Fh[o6$&F
_rFb[p-&Fjq6#%0LeadingMonomialG6$Fcgu&FeqFb[pFfr/F^hl;F/Fir>Fhr-Fbp6$f*Fj]oFA6$
FgoFhoFA-Fao6%f*Fc^mFA6$FgoFhoFAFd`oFAFAFAFLF^qFAFA6$F]hlFNFhr-Fbp6$f*FjalFA6$F
goFhoFA-FcjnF`blFAFA6$F7FQFhrFAFAFA6#Fg[lFA,
I,filterBasest+6&F%'Fh`mF)'%%nQBsGF3'%#ffGFdco6&%#mFG%#BsGFb`sFf[n6"FAC(>FS-Fgi
l6#*&FbzF/FeqF/>FZ-F^`l6$&-Fcy6%FLF]yFIFauF*>FD-Fbp6$f*FjalFA6$FgoFhoFA-Fjr6#-F
ifl6$F`[nF^qFAFA6$FfiuFZFQ>FN-F^^m6%FD%">G/%'outputG%,permutationG-F]s6#-F`s6$F
S%>~quotient~space~bases~removedG7#-FG6$;F/,&FeqF/FSFbalFNFAFAFA6#Fg[lFA,
I(iniProbt+6&Fd`m'%#qbGF^\lFciu'%#pnGF360F&%#vFGFexF7F`duF\du%#GCGFh`m%$CMsGF9F
dinF<F_frFbiu6"FAC*AFbem>6$FZFN6$FgemFbz>FD-F(F\al@$0-&Fjq6#%1HilbertDimensionG
6$FZ/F_zFNF_qYQZThe~problem~is~expected~to~have~infinitely~many~solutionsFA>FSF
afm@'/FQF/C)>6%FNFhrFft-FgfnFK>F`ilF[hm-F]s6#-F`s6$F`il%8~change~matrices~loade
dG>F_r7#-Fjel6$-F[[n6$-Fbp6$F_[n-F^`l6$-F\v6$&FftFb[pFDF)FN/F^hl;F/F`il>Fes7#-F
jel6$&-Fbr6$Fcgu&FhrFb[pFfrFg_v>F[jl-F]iu6&FZFesF`ilFeq>6&FftF_rFhrFes6&7#-Fjel
6$Ff_v-Fbfl6$F^hlF[jl7#-Fjel6$FcguFj`v7#-Fjel6$F``vFj`v7#-Fjel6$&FesFb[pFj`v/FQ
FbqC*>Fes-FcbmFK>F`ilF[ir-F]s6#-F`s6$F`il%=~quotient~space~bases~loadedG>Fdv-FU
6#F^gp>Fgq-Fiq6&FZFdvFj]v/Fc[v%)extendedG>6$F\_mF^\m6$&FgqFfr-Fhv6#&FgqFau>F[jl
Fb`v>Fe`v6&7#-Fjel6$F^\mFj`v7#-Fjel6$F\_mFj`v7#-Fjel6$FdvFj`vFbavC+>Fhr-Fbp6$f*
FjalFA6$FgoFhoFA-FU6#-FGFKFAFAFA-&%)combinatG6#%(permuteGFc\n>Fhr-Fhcu6&FZ7#F^g
pFhrFN>Fgq-Fbp6$f*FjalFA6$FgoFhoFA7#-Fiq6&F^qFL/F_zFhwFfbvFAFA6&F&FZFexFNFhr>6$
F_rFft6$-Fbp6$f*FjalFA6$FgoFhoFAF^[rFAFAFAFgq-Fbp6$f*FjalFA6$FgoFhoFA-Fhv6#F_[r
FAFAFAFgq>F`ilFir>FesFj_v>F[jl<#-Fjel6$-F_^p6$FeavFesFg_v>Fe`vFf`v-F]s6#-F`s6&F
[ir%A~quotient~space~bases~computed~(GF`il%")G-F]s6#-F`s6%%AThe~problem~is~expe
cted~to~have~G-Fjr6#&FesFfr%+~solutionsGO6)FNFZFSF_rFhrFesFftFAFAFA6#Fg[lFA,
I/TemplateFindert+6*Fd`m>'%,action_varsG-F)6#<$%'negintGF3F]cm>F`dmF_q>'%,filte
r_fracGFdcoF_q>'%&partsGFacoFi`r>FfdmFhdm>'%*quo_basesGF^\lF_q>'%+schur_polsGFe
hvF]cm6KF&FexF7%&avarsGFfcoF`duF\duFh`mFj\vF`cpF9F^hlF[\pF]clFjjrFecrF`xF>FccpF
:FfcpF=F<Fjcq%#flGF_pFf[n%#moG%#noGFcco%$spoG%"NGF\hlFgcpF;F_fr%%irngG%#nkGFhco
Fdin%&tord1G6"FAC,>8?"(+++">8BFbal>6)FDFZFNFhrFgqFesFft-F`\v6&FLFcalFbzFfcl>FS-
Fhp6%/Fj_lF_qFN-Fbp6$f*6#F8FA6$FgoFhoFAF]qFAFA6$F7FNFQ>8G-%%iquoG6$F[ir&Fg]lFfr
>8H7#-Fbt6#;,&F/F/*&,&&Fg]lFauF/FbalF/F/Fg[wF/F/-Fhp6%/Fe\wF[\wF[ir*&Fe\wF/Fg[w
F/>6%8D8F8I6%FbepFhgv-Fjr6#F]\w>8C,$*&F^]wFbalF\]wFbalF\[m?(F`ilF/F/F^]wF_yC&>F
\_m&F]\w6#F`il>6&FdvF^\m8J8K6&&FhrFdgm&FgqFdgm&FesFdgm&FftFdgm>8L-FG6$F/F^\m?(F
[jlF/F/F\]wF_yC.>F_r&FSF]`m>6(868788898:8;-F\cp6'F_rFdvF^\mFDF]^w>8E-Fjr6#Fb_w>
Fiis-Fhp6%/FcalFbq-Fj[q6'FZFb_wFNFDFeq-Ffcq6(FZFb_wFc_wF^^wFNFD>6%F]^tF__t85-Fe
_s6'FZFiisF`_wFNFD>F__t-Fect6'F__tF]^t,(-FG6$FibsF__tF/F]]wFbalFg_wFbalFDFcgo>F
__t&-Fd^u6$F__tFDFfr>8<-F``t6(Fa_wF__tF^_wF__wFg_wFD>6$8=8>-FG6$F/F__t>8A-Fh^p6
#F__t@&3Fbaw52FgawFdjv3/FgawFdjv2FgjvF\bwC%>6%Fdjv8@Fgjv6%FgawFhawF\bw-F]s6#-Fa
im6(QTSmaller~or~sparser~template~found:~[%d,%d],%a,%a,%aFAFgawFhaw-F_u6$F\bwFb
glF_r-Fhp6%F]`wF\_mFe^w-F\co6,FL7$FgawFhaw-F_u6$F\bwFg^lFDFNF_rF^\mF__wF]^t-Fdz
6#0FcalFbq4FbawY6&Q@Invalid~action~matrix,~%1,%2,%3FAF\_mF_rF^\m-F]s6#-Faim6*Q6
%d%s,[%d,%d],%a,%a,%aFA-Fgil6#*&,&*&,&F`ilF/FbalF/F/F\]wF/F/F[jlF/F/Fc]wF/Q"%FA
FgawFhawF`cwF_rFbcw-F]s6#-Faim6&Q:Best~template:~[%d,%d],%aFAFdjvFibw-F_u6$Fgjv
FbglFAFAFA6#F/FA
