M7R0
I*eigSolvert+6%'%"FG<%%'VectorG%%listG%$setG>'%'actvarG%(integerG""">'%'digitsG
%'posintG"#:6,%%fB2CG%%varsG%"aG%%tordG%"BG%$degG%"GG%"TG%"VG%"SG6"6"C/>8%7#-%#
opG6#-%'indetsG6#9$>8&&FD6#9%>8'-%%tdegG6#-FG6#FD>8$t+6$%"fGF:6#%"tG6"FAC$>FZ-%
&tableG6#-%$zipG6%f*6$F8%"bGFA6$%)operatorG%&arrowGFA/FQFLFAFAFA7#-%'coeffsG6%F
LFQ.%"mG7#F_p-%$mapG6$f*6#FeoFA6$FgoFhoFA-%#ifG6%-%)assignedG6#&T#FKF]q""!FAFA6
$FinFZFQFAFAFA6#""#>%'DigitsG9&>8*-&%)GroebnerG6#%&BasisG6$FLFS>8(&-&Fjq6#%*Nor
malSetG6$FgqFS6#F/>8)-%%nopsG6#F_r-%&printG6#-%$catG6%%@The~system~is~expected~
to~have~GFhr%'~rootsG>8+-&Fjq6#%5MultiplicationMatrixG6'FNF_r-F^o6#-%'EquateG6$
F_r7#-%"$G6#;F/FhrFgqFS>8,&-&%.LinearAlgebraG6#%-EigenvectorsG6#-%&evalfG6#Fes6
#Fbq>Fft-&%"|irG6#_FA%"/G6%Fft%#~$G-%".G6$-F(6$Fhr/%%fillGF/&FftFfr>8--F\v6$-%'
MatrixG6#-Fbp6$f*6#%"vGFA6$FgoFhoFA-T)6$-&Fjq6#%+NormalFormG6%FLF^qT%T'FAFA6*F<
FgqF9FSF:F_rF6FZFDFftFAFAFA6#F/FA,
I+isLinIndept+6&'%"MGF)'F<F)'F9%3ShortMonomialOrderG'%#ppGF36$F7F?6"FAC&>FZ-FJF
P@$/-FjrFKF/O%%trueG>FD&-%,poly2matrixG6%-Fbp6$f*6#F_pFA6$FgoFhoFA-Fdw6&FLT$T&/
%/characteristicGT(FAFA6(F<FQF9FeqFex9'FLF]yFZFfr-%#isG6#0-&&Fjt6#%(ModularG6#%
%RankG6$FbzFD-Fhz6$Fbz&FD6$;F/!"#;FAFAFAFAFA6#""%FA,
I*testBasist+6''F`xF*'F;F3FaxFbxFdxFfx6"FAC&>FZ-FJ6#Feq@$2F]yFQO6$%&falseG-%$<,
>G6#-Fh\l6#F_q>FD&-Fcy6%-Fbp6$f*FhyFA6$FgoFhoFAFjyFAFA6(F<FeqF9FbzFex9(FLF]yFZF
fr6$-Fhp6%0Fe]lF_q-Fdz6#/-Fhz6$Fe]lFDFQ-Fdz6#/-&FjtF\[lFXFQFDFAFAFA6#""&FA,
I*iniMonSett+6)F%'%#B0GF)'F7F)FaxFbxFdx>'%$domG%*nonnegintGF_q6*%"EGF`x%#vrG%"d
GF;%%flagGF?%&d_minG6"FAC(>F_r-FjrFP>FesF_q>FZ-%(convertG6$-Fbp6$FG-&Fjq6#%(Sup
portGFKF*>FDFZ?(FSF_qF/FA1,&FSF/Fes!""9*C&>FN-%'selectG6$f*6#%"xGFA6$FgoFhoFA1-
%'degreeG6$FLF\zFhwFAFA6&F7FeqFc_lFSFD>FD-Fbp6$f*FhnFA6$FgoFhoFA-FG6#-Fbp6$f*6#
%"kGFA6$FgoFhoFA*&F\zF/FLF/FAFA6$FinFLF^qFAFA6$Fb_lFNFD>6$FhrFgq-Fh[l6'FDF_rFbz
Fe]l9)@$4Fhr>Fes,&FSF/F/F/O6$FZFDFAFAFA6#""(FA,
I-neighborMonst+6%'F:F*'%#MBGF*F[_l6#%#nBG6"FAC&@$/F]yF_qOFQ>FZ-F^al6%%%typeG-F
bp6$FG<#-%$seqG6$-F[el6$<$*&FeoF/F^wFi`l*&FeoF/F^wF/-%#inG6$F^wFeq-Fcel6$FeoFL%
)monomialG>FZ-%*intersectG6$-%&minusG6$FZFLFQ-Fhp6%/-Fjr6#FZF_qFQFZFAFAFA6#""$F
A,
I)genBasist+6)'Fa_lF*F[\lFi^lF[_lFaxFbxFdx60%$rndGF:%#EBGF[dlF]dl%$nB1G%#bvGFdb
lF8%#nvG%#wtGF_p%"iGF;6"FAC,>FZ,$-%%randG6#;F_q"%+5#F/Fjgl>FD<">FSFQ>Fdv-Fjr6#F
bz>81-FjrFa\l>Fgq7#-F[el6$-%&roundG6#-FZFA/80;F/Fdv>Fes-&%$maxG6#%&indexG6#-Fbp
6$f*FaalFA6$FgoFhoFA,&FLF/*&-F^qFAF/$"$+"F_qFi`lF/FAFA6$F[glFZFgq>Fft&FbzF`u?(F
AF/F/FA2-FjrFXFchlC*>FS-F]fl6$FSFD>F_r-Ffcl6%FDFSFbz>FN-%&unionG6$FLFD>8.f*Faal
FA6$FgoFhoFA,*-Fhp6%-FcelFgalF/F_qF/-Fhp6%-Fcel6$*&FhwF/FLF/FiwF/F_qF/-%$addG6$
*&&Faw6#T+F/-Ffal6$FL&T.Fc\mF//Fd\m;F/T/F/*&-T1FAF/F^jlFi`lF/FAFA62Fa_lFLF8FftF
\glFNF^glFgqFaglF^ilF7FbzF_glFdvF[glFZ>Fhr-%%sortG6$7#-FGF[sf*6$Fbal%"yGFA6$Fgo
FhoFA1-F^qFP-F^qFKFAFA6$F`glFb[m>6$8/F^il6$&FhrFfrF/?(FAF/F/FA34-F\x6&7$FWF`^mF
e]lF]clFj`l2F^il-Fjr6#FhrC$>F^il,&F^ilF/F/F/>F`^m&Fhr6#F^il>FD<$FWF`^mFDFAFAFA6
#FeclFA,
I*saveBasest+6$'%%probG%'stringG'%$QBsG<$F)F*6#%#fdG6"FAC%>FZ-%&fopenG6$-F`s6%Q
-nongb/nongb_FAFLQ%.txtFA%&WRITEG-Fbp6$f*FaalFA6$FgoFhoFA-%(fprintfG6%F^qQ$%a|+
FAFLFAFA6$F_`mFZFQ-%'fcloseGFcflFAFAFA6#FbqFA,
I*readBasest+6#Fh_m6%%#stGF\`m%*nongbfileG6"FAC'>FZF/>FD7">FNFf`m?(FAF/F/FA0FZF
_qC$>FZ-%)readlineG6#FN@$Fdbm>FD7$FW-%&parseGFcflFDFAFAFA6#F/FA,
I,BasisFindert+6%Fh_m>'%"NGF3F_jl>Fdx"&\F$6.F&F7F9F<Fj^lFc_lFa_lF`x%#BBGF:%#fnG
F_`m6"FAC1>FesFabm>FftFabmA-F`s6%Q,problems/F_FAFLQ#.mFA>FZ-%%evalG6#-F`s6$%#F_
GFL>FD7#-FG6#-FJFcfl>FNFT>FS-Fiq6%FZFN/F_zFeq>F_r&-Fbr6$FSFNFfr?(FhrF_qF/FA1-Fj
rF`uFir>6$FgqFes-Ff^l6)FZF_rFDFSFNFeqFhr>Fb[mFf`m>F`^m-Fd`m6$Fb[mFj`m-Feam6#F`^
m>F`^m-Fd`m6$Fb[m%'APPENDG?(FAF/F/FA2-Fjr6#FftFQC$>Fdv-Fffl6)FgqFesF_rFDFSFNFeq
@$4-%'memberG6$FdvFftC%>Fft7$-FGF]gmFdv-F`am6%F`^mFbam-F]`l6$FdvF)-F]s6#-%(spri
ntfG6%Q%%d%sFA-Fjhl6#,$*&F\gmF/FQFi`lF_jlQ,%~completedFAFdfmFAFAFA6#FeflFA,
I*writeGfant+6%'F&F]`m'F7F]`mFdxF^`m6"FAC%>FZ-Fd`m6$Q/gfan/igfan.txtFAFj`m-F`am
6'FZQ+Z/%aZ%a|+%aFAFeq-F]`l6$FQF)-%$modG6$-Fbp6$%'expandG-F]`l6$FLF*FeqFdamFAFA
FA6#FeflFA,
I)readGfant+Fiam6'Fd_lF[bm%"nG%)gfanfileGFex6"FAC*>FZFf\l>FDF/>FNF_q>FS-F`s6%Q+
gfan/gfan_FAFLFi`m>FD-Fhbm6#FS>F_r-F^cm6#-%*substringG6$FD;Fefl,&-&%,StringTool
sG6#%.FirstFromLeftG6$Q"[FAFDF/Fd[lF/?(FAF/F/FA0FDF_qC$>FDFc[n@(5/FDQ#|fr|frFA/
FDQ"|frFAC%>FZF_y>FN,&FNF/F/F/>(%#GBGFNFabm3FZ0-Fi[n6$FDFi`lQ"|hrFA>Fc]n7$-FG6#
Fc]n-Fi[n6$FDFc[l3FZ/Fg]nFi]nC$>Fc]nF[^n>FZFf\lO6%F_r7#-F[el6$-Fbp6$F^cm(Fd]nFa
gl/Fagl;F/FN7#-F[el6$-Fbp6$f*FaalFA6$FgoFhoFA-F^cm6#-Fi[n6$FL;F/,&-F^\n6$Q"+FAF
LF/Fi`lF/FAFAFAF\_nF]_nFAFAFA6#F/FA,
I(writeCMt+6&Fh_m'%$Ws0GF)'FdblF3Fdx6&F_`mF&F7%#WsG6"FAC5>FZ-Fd`m6$-F`s6%Q'cm/i
cmFAFeqFi`mFj`mAF`dm>FDFedm>FN-F]`l6$7#-FG6#-FJFXFj_m>FS-&F_\n6#%.SubstituteAll
G6%-F[bn6%-F]`l6$FQFj_mFc\nQ"(FAQ"]FAQ")FA>FD-F]`l6$-F\jm6$-Fbp6$F`jmFDFbzFj_m-
F`am6'FZQ<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+FAFSFbzFN-F`am6&FZQ=f~=~openOut~"cm_%s_
%a.txt";|+FAFLFeq-F`am6$FZQ<f~<<~toString(pp)~<<~endl;|+FA-F`am6$FZQ<f~<<~toStr
ing(vr)~<<~endl;|+FA-F`am6%FZQ9for~i~from~0~to~%a~do~(|+FA,&Fi_lF/Fi`lF/-F`am6$
FZQ>f~<<~toString(Ws#i)~<<~endl;|+FA-F`am6&FZQ.R~=~ZZ/%a%s,~FAFbz-Fi[n6$FNFc[l-
F`am6$FZQDMonomialOrder~=>~Weights~=>~Ws#i];|+FA-F`am6%FZQ0I~=~ideal(%s);|+FA-F
i[n6$FD;FbqFd[l-F`am6$FZQVG~=~gb(I,ChangeMatrix=>true);|+M~=~getChangeMatrix~G;
|+FA-F`am6$FZQ>f~<<~toString(M)~<<~endl;|+);|+FA-F`am6$FZQ,f~<<~close;FAFdamFAF
AFA6#Fg[lFA,
I'readCMt+Fiam6(F[bm%'cmfileGFexF7F_pFgjm6"FAC*>FZF/>F_rF_q>FhrF_q>FD-F`s6%Q'cm
/cm_FAFLFi`m>FN-F^cm6#-FhbmFX>FSFffn?(FAF/F/FAFdbmC$>FZFhfn@&3Fdbm/-Fi[n6$FZF/F
cbnC$>F_r,&F_rF/F/F/>(F=F_r-Fi[n6$FZF]en3Fdbm/-Fi[n6$FZ;F/""'Q'matrixFAC$>Fhr,&
FhrF/F/F/>(%#CMGFhr-F[bn6%-F[bn6%-Fi[n6$FZ;""*Fd[lF]]nFc\nFi]nFdbnO6%FN7#-F[el6
$-%%wdegG6$7#-F^cm6#(F=FaglFS/Fagl;F/F_r7#-F[el6$)-Fhv6#7#-Fbp6$F^cm(FehnFagl%#
%TG/FaglFdtFAFAFA6#F/FA,
I(getTordt+6$%#gbG%#lmG6+F7F_gl%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG%$solG%&f
degsG6"FAC,>FZFE>FDFbfl>FN/7#-Fbt6$F_qFD%%NULLG>FS7#-F[el6$(Fc_lFagl/Fagl;F/FD>
F_r-Fbp6$f*6#%"zGFA6$FgoFhoFA-Fbp6$f*FaalFA6$FgoFhoFA7#-F[el6$-Ffal6$FLFh]m-Fce
l6$Fh]mF^qFAFA6$F7F^q-F]`l6$FLF)FAFA6$F7FZFL>Fhr-Fbp6$f*FaalFA6$FgoFhoFAFb]oFAF
AF\^oFQ>Fgq-Fbp6$f*FcblFA6$FgoFhoFA-FG6#-Fbp6$f*FaalFA6$FgoFhoFA1F/-F_\m6#-Fao6
%f*6$Fh]mF\]oFA6$FgoFhoFA*&FLF/FQF/FAFAFAFLF^qFAFA6$F`[oFaw-%%subsG6$F^q7#-F[el
6$,&&FhwFKF/%"gGFi`l-Fcel6$F_`o&FiwFKFAFA6*F_[oFNFb[oFhrFa[oF_rF`[oFS<#-Fbt6#;F
/F]y>Fes&-&%-OptimizationG6#%)MinimizeG6&-F_\mFd[nFgq/%+depthlimitG"#S/%'assume
GF__lFau>Fft-Fh_o6$FesFS6$Fft-Fdin6$FftFZFAFAFA6#FbqFA,
I)saveDatat+6,Fh_m'%#mnG7$F3F3'%#spG%(numericG'FexF__lF_im'%#avGFgelFbx'%#QBGF)
'%'shiftsGF)'%$stdG%(booleanG6'FjcmF_`m%$mn0G%$sp0GFd_l6"FAC&>FZ-Fhp6%9--F`s6%Q
-optim/o_std_FAFLFi`m-F`s6%Q.optim/o_nstd_FAFLFi`m>F_rFf\l@%-&%*FileToolsG6#%'E
xistsGFcflC'>FD-Fd`m6$FZ%%READG>FN-F^cm6#-FhbmFcfl>FSF\eo@$52&FQFfr&FNFfr3/Fceo
Fdeo2FSFeq>F_rF_y-FeamFX>F_rF_y@$F_rC%>FD-Fd`m6$FZFj`m-F`am6,FDQ8%a|+%a|+%a|+%a
|+%a|+%a|+%a|+%aFAFQFeqFbz-F]`l6$Fe]lF)F]clFj`l9+9,FieoFAFAFA6#"#5FA,
I)readDatat+6$Fh_mF]co6,FjcmF_`mFaboFdboFexF7FhboF9FjboF\co6"FAC.>FZ-Fhp6%FQFic
oF\do>FDFhdo>FNF\eo>FSF\eo>F_rF\eo>FhrF\eo>FgqF\eo>FesF\eo>FftF\eo>FdvF\eoFieo6
*FNFSF_rFhrFgqFesFft-Fbp6$FfdmFdvFAFAFA6#FbqFA,
I$srtf*6$'F^wF'FbxFA6$FgoFhoFA-Fb]m6$FLf*Fg]mFA6$FgoFhoFA-&Fjq6#%*TestOrderG6%F
QFLF\zFAFA6$F9FQFAFAFAFA,
I,poly2matrixt+6%F%'%#nFGF3F_im6$%%monsG%%cffsG6"FAC$>FD7#-F\p6%-F`jm6#-F_\m6$*
&(%$q_qGFaglF/&FL6#FaglF//Fagl;F/FQFeq.FZ6$-Fhv6%FQFejlf*6$Fagl%"jGFA6$FgoFhoFA
-%&coeffG6$&F^qFP(FbjoFLFAFA6$FeioFD-F(6#7#FZFAFAFA6#FeflFA,
I/permuteColumnst+6%'F`xFhv'%#V1GF('%#V2GF(6#Fgjm6"FAC$>FZ-FG6$F/FQ-F\v6$FL-Fhv
6$FZ<#-F[el6$/6$Fagl-&%*ListToolsG6#%'SearchG6$&FQFdjoFeqF//Fagl;F/FZFAFAFA6#Fe
flFA,
I)sparsityt+6#F\\p6#%&numzrG6"FAC$>FZ-Fjr6#-F^al6$f*FaalFA6$FgoFhoFA-Fdz6#/FLF_
qFAFAFAFj]o*&FZF/-%$mulG6#-FG6$F/FLFi`lFAFAFA6#F/FA,
I(matrixSt+6''F:F)Fi^lFaxFbxFfbo6%F?%#V0GF;6"FAC&>FNF]y@$0Fi_lFNY%ILists~B0~and
~B~must~have~the~same~lengthG>Fccl-Fcy6%-Fbp6$f*FepFA6$FgoFhoFAFjyFAFAFd]lFLFNF
`\l@%/-FG6$F/FDFNO-Fi[p6%FZFD-F(FPY%=Failed~to~construct~matrix~SGFAFAFA6#Fe^lF
A,
I*quotientst+6&'F_`o%(polynomGFaxFbxFfboFA6"FAC$-Fdw6'FLFQFeq.%"QG/F_zFbzF[bpFA
FAFA6#Fg[lFA,
I-monPartitiont+6'Fgbo'%#GrGF)FbxFfbo>FiboFabm6-Fj^lF:%#aBG%"RG%#B2G%#RBGF<%#nG
GF=F?Fagl6"FAC->FZ&-Fbr6$FQFeqFfr>FD-F]`l6$-Fhp6%/Fe]lFabmFZFe]lF*>FN-Fbp6$f*Fa
alFA6$FgoFhoFAFfblFAFA6$FhboFLFD>FS-F_ho6$-F]`l6$-F]fl6$FNFDF)Feq>Fes-FjrFd[n>F
_r-Fbp6$f*FaalFA6$FgoFhoFA*&FLF/F\zFi`lFAFAF[dp-FjelFbdp>FD7$-FG6#-F_ho6$-F]`l6
$-F]fl6$FDF_rF)Feq-FG6#-F_ho6$-F]`l6$F_rF)Feq>6$FhrFN6$7$-FGFd[nFW-Fbp6$f*FaalF
A6$FgoFhoFAFfblFAFAF[dpFD@%Fecp>Fft-Fgs6(FLFD-F^o6#-F^t6$FD7#-Fbt6#;F/FejlFQFeq
F\bpC%>Fft-Fgs6(FLFZ-F^o6#-F^t6$FZ7#-Fbt6#;F/FbflFQFeqF\bp>Fdv-Fb_p6'FDFZFQFeqF
bz>Fft-Fhp6%0FbzF_q-F\jm6$-F\v6%FdvFft-&Fiz6#%(InverseG6$FbzFdvFbz-F\v6%FdvFft-
&Fjt6#%.MatrixInverseG6#Fdv>Fgq-F]`l6$,&-F(Fd[nF/-F\v6$&Fft6$;F/FesFe[l-F(FXFi`
lF)O6(FNFDFhrFftFgq-Fhv6#7#-F[el6$-Faap6&&Fgq6#Fb[mFQFeqFbz/Fb[mF]jpFAFAFA6#Fe^
lFA,
I(matrixHt+6'F%FaxF_imFfboF]_l6/%*undetPolyG%#pvGFbioFibp%#uHG%%leqsGFd[oFagl%#
dFG%#dGGFc_lFe_l%"hG6"FAC)>FD-F_\mFa\l>FNF]y>FSFi_l>Fft-Fbp6%FfalFLFeq>FZt+6&F_
imFa[qFc_lF][p6#Fdio6"FAC%-F\p6%-F`jm6#,&F/F/-F_\m6$)FQ%"pG/F^]q;F/FeqF/FLFgjo>
FZFg[p-F_\m6$*&&FZFcblF/&%#_vG6$FbzFdblF//FdblF\hpFAFAFA6#Fg[l?(FesF/F/FSF_yC%>
6$F`^mFdv6$F_q-Fbp6$f*FaalFA6$FgoFhoFA-Fcil6$F_qFLFAFAFA,&7#-Fbt6$-Ffal6$&FQF`u
FeqFNF/FftFi`l?(Fb[mF_qF/FA1,&Fb[mF/F`^mFi`lFe]lC&>F_r7#-F[el6$-FZ6&FeqFD,&&Fdv
6#F][pF/Fb[mF/F][p/F][pF^_n>Fhr<#-F\p6$-F`jm6#,&F\_qFi`l-F_\m6$*&&F_rFi_qF/&FLF
i_qF/Fj_qF/Feq>Fgq-%'msolveG6$FhrFbz@$/-Fjr6#<#FgqF_q>F`^m,&Fb[mF/F/F/>&F^ilF`u
-F\jm6$-Fbp6%-%"@G6$F`jmFfdmF_rFgqFbzO-Fh\l6#-F[el6$-&F(6#%$rowG6#Fcaq/Fes;F/FS
FAFAFA6#Fe^lFA,
I*matrixHnit+6(F%Fax'%"CGFhv'FehnFhvF_imFfbo6*%,undetPolyniGFbioFibp%#H0GFb[qFc
[qFd[o%%parsG6"FAC+>FDF]y>FNFi_l>FZt+6&'Ff[qFeapF_im'FaglF3'F][pF3Fc\q6"FAC%-F
\p6%FLFQFgjo>FZFg[p-F_\m6$*&Fe]qF/&Fg]q6%FeqFbzFdblF/Fi]qFAFAFA6#Fg[l>FS-F\jm6$
-Fbp6$F`jm-F\v6$FeqFbzF]cl>F_r-Fhv6%FNFDf*F\[pFA6$FgoFhoFA-Fiw6&&F^q6$FLFQF]zFL
FQFAFA6(F`cqFSF7Fe]lF_cqFZ>Fes<#-F[el6$&%#_uGFdjo/Fagl;F/-Fjr6#-F]fl6$-FJF[sFe]
l>Fhr-Fbp6%F\p<#-F[el6$-F\jm6$-F`jm6#,&Ff]pFi`l-F_\m6$*&&F_rF\[pF/Ff`qF//F][pFf
\oF/F]clF]_nFe]l>Fgq-Fi`q6%FhrFesF]clO-F\jm6$FfaqF]clFAFAFA6#F^hnFA,
I*syzModulet+6'F%Fax'%"AGFhvFbxFfbo6*FbioFibp%"eG%"LG%#LtGF`xF?F:6"FAC.>FZF]y>F
DFi_l>FN-F[el6$-F(6$FD<#/FaglF/Fe\o>FS7#-F[el6$7#-&Fjq6#%,LeadingTermG6$Ff]pFbz
Fe\o>F_r-Fbp6$f*FaalFA6$FgoFhoFA*&&FLFfrF/&FLFauF/FAFAFAFS>Fhr-Fhv6$FDf*F\[pFA6
$FgoFhoFA*&-%$lcmG6$&F]qFau&Fb[pFauF/F^`oFi`lFAFA6&FchqFSFdhqF_r>Fgq7#-F[el6$-F
[el6$,(*&&FhrF\[pF/&FNFdjoF/F/*&&Fhr6$F][pFaglF/&FNFi_qF/Fi`l-Fh\l6#-Faap6&z'6&
Ff[rFi[rFf]p&FQFi_q[[[\[[[[[\[[mF/\[[[[[\[[[[[mFi`lFQFbzFe]lFi`l/F][p;,&FaglF/F
/F/FDFe\o>Fgq)-Fhv6#FgqFfjn>Fes-Fhv6#7#-F[el6$-Faap6&FcjoFQFbzFe]lFg]p>Fgq-Fbp6
$F`jm-Fh\l6$-F\v6$FgqFeq,&-&Fjt6#%/IdentityMatrixGFcflF/-F\v6$FesFeqFi`l@$Fi]l>
Fgq-F\jm6$FgqFe]lO&Fgq6$-%'removeG6$f*FdjoFA6$FgoFhoFA-&%+ArrayToolsG6#%'IsZero
G6#&F^q6$FLFe[lFAFA6$F?Fgq7#-Fbt6#;F/-FG6$7$F/F/FgqFe[lFAFAFA6#Fe^lFA,
I+matrixHsyzt+6(F%FaxF[cqF_hqFbxFfbo6$F?%&ThetaG6"FAC%>FZ-F\hq6'FLFQFbzFe]lF]cl
>FD-Fhv6%-FG6$F[`rFeq-FG6$F[`rFZf*F\[pFA6$FgoFhoFA&FinFfeqFAFAFAO-F\jm6$-Fbp6$F
`jm,&F\eqF/-F\v6$FDFZF/F]clFAFAFA6#F^hnFA,
I(supportt+6$'FgnFeapF_imFA6"FAC$F[p<#F_pFAFAFA6#FbqFA,
I,fixTemplatet+6'%'admonsGF%F_im'%$monGF)'FhbpF)6/Fbio%%monFG%&admonGFaglF][pF[
bpFd_l%#xFGF`xFg_pFa_lF>%%mon1G6"FAC.>FZFi_l>FD-Fbp6$f*6#FgnFA6$FgoFhoFA-FjarFg
alFAFA6$F7FeqFQ>FN7#-Fbt6$F]hlFZ?(FSF/F/F]yF_yC%>FgqFf\l?(F_rF/F/FZF_yC$>Fhr-Fb
p6$f*6#%#mfGFA6$FgoFhoFA-Fhp6%-%'divideG6%&F\z6#FhwFL.%"qGFaerF_\oFAFA6&FebrFLF
aglFS&FDF[s@$0FhrF]hlC%>&FNF[s<$Fb^m-FG6#Fher>FgqF_y[@$4FgqY%;Failed~to~correct
~templateG>F^il7#-F[el6$-F]`l6$-F_[m6$-F]`l6$&FbzF[sF*FherF(/F_rFh]p>Fes7#-F[el
6$-F[el6$*&&FQF[sF/FaboF/-Fcel6$Fabo&F^ilF[sF]gr>6$FftFdv-Fcy6%FesF[fmFeq>Fb[m-
F]fl6$-F]`l6$FdvF*-F]`l6$Fe]lF*>Fb[m-F_ho6$7#-FGFijp-FU6#-FGFa\l>F`^m-Fh\l6$Fhh
r-FG6#Fe]l-F]s6#%/Template~fixedGO6&F^ilFftFdvF`^mFAFAFA6#Fe^lFA,
I2constructTemplatet+6&'%"HG<$FhvF)F%F_imFhbr6)FbioFgbrF\crF`xFg_pFa_lF>6"FAC+>
FZFi_l>FD-Fhp6%-Ffdl6$FLFhv7#-F[el6$&-Fcy6%&FL6$Fe[lF][p-FG6$F[`rFLFeqFau/F][pF
h]pFL>FN7#-F[el6$-F[el6$*&Fb\rF/FaboF/-Fcel6$Fabo&FDFi_qF`[s>6$FSF_r-Fcy6%FN-Fj
rFibmFeq>Fhr-F]fl6$-F]`l6$F_rF*-F]`l6$FbzF*>Fhr-F_ho6$7#-FGF[_mFihr>Fgq-Fh\l6$F
[]s-FGFahl@$0-FG6$F/Fgq-FG6$F/F_rC$-F]s6#%7Template~is~incompleteG>6&FDFSF_rFgq
-Fbbr6'-F]fl6$-F]`l6$FgqF*Fc\sFQFeqFDFbz6%FD-Fi[p6%FSF_rFgqFgqFAFAFA6#Fg[lFA,
I-adjustParamst+6'F%'F[jrFhvFhbr'F7F*Ffbo63FbioFibp%#H1G%#LmG%%colsGFchqFgbrFg_
pFa_lFbhq%#smG%#rmG%#npG%#ssG%$prmGFc[qFd[o6"FAC3>FZF]y>FD-FG6$F[`rFQ>FNFQ>FS-F
[el6$-Fcy6%&FQF][sFDFbzF`[s>F_r7#-F[el6$-Fh^r6$f*FaalFA6$FgoFhoFA-%+membertypeG
6$F3-F]`l6$&&F^q6#,&F][pFbqFi`lF/6$Fe[lFLF)FAFA6$F]_sFS7#-Fbt6#;F/-FG6$7$F/Fbq&
FSF`asF`[s>Fjbl6$7#-F[el6$&F[bs6$Fe[lFe`qF`[s7#-F[el6$&&FS6#,$F][pFbq6#Fe`qF`[s
>Fb[m7#-F[el6$-Fbp6$f*FhnFA6$FgoFhoFA-Fjar6$-F`jm6#*&&F\zFi_qF/FLF/F]zFAFA6&F&F
LF7Fbz&FgqFi_qF`[s>Fes-F]`l6$-Fbp6$FG-Fbp6%-Fiaq6$FGF]`lFb[mF*F*>Fft-F]`l6$-F]f
l6$Fes-F]`l6$FeqF*F)>Fb[m-F(Fijp>F`^m-Fbp6$f*6#FbhqFA6$FgoFhoFA-F^al6$f*FdjoFA6
$FgoFhoFA-Fegm6$F\zF^`oFAFA6&FbhqFLF__sF^q<#-Fbt6#;F/-FG6$F/F^qFAFA6$F__sFb[mFf
t>F^il7#-F[el6$-%"+G6#-F[el6$-Fjr6#-F^al6%%$hasGF`^m&&F`^mFi_qFdjo/Fagl;F/-Fjr6
#F`gs/F][p;F/-FjrFefm>Fchlf*6&FaglF][pF`_sFa_sFA6$FgoFhoFA52-Fjr6#&FeqFP-Fjr6#&
FeqFK3/FahsF^hs2&FbzFP&FbzFKFAFAFA>82-Fb]m6$7#-Fbt6#;F/F\gmf*F\[pFA6$FgoFhoFA-F
iw6&FLFQF^qFhwFAFA6(F`_sF`^mFa_sF^ilFb_sFchl>Fft&Fft6#Fjhs?&FdvFftF_yC+>FS-F[el
6$-Fcy6%&FNF][sFDFbzF`[s>Fjbl6$7#-F[el6$F[bsF`[s7#-F[el6$FgbsF`[s@$/-Fjr6#-FJF[
_mF_qF]fr>Fb[m7#-F[el6$-Fbp6$f*FhnFA6$FgoFhoFAFccsFAFAFicsFjcsF`[s>F`^m-Fbp6$f*
FaalFA6$FgoFhoFA<#-&Fb]p6#%*SearchAllG6$F/-Fbp6$f*6#Fh]mFA6$FgoFhoFA-Fjr6#-Fjel
6$FL<#F^qFAFA6$FbhqF^qFLFAFA6$FbhqFdvFb[m>83<#-F[el6$-FG6#-Fbp6$f*FcblFA6$FgoFh
oFA-FG6#-F]`l6$&&F^qFi_qFbasF*FAFA6$FchqFhrF`gsF`[s>84-Fi`q6$F^]tFe]l@$/-Fjr6#<
#F`^tF_q\>FN-F\jm6$-Fbp6%FhaqFNF`^tFe]l-Fgir6&FNFLFbzFeqFAFAFA6#Fe^lFA,
I4isActionMatrixFoundt+6('F=FhvF\\p'FebpF)Fe_p'FibpF3Ffbo6'%#tMG%#T1GF;F_p%"rG6
"FAC'>FNF`hl>FS,&FNF/Fe]lFi`l>FZ-F\jm6$-%*GaussjordG6$FQ.F_rF]cl>FD-F\jm6$-Fh\l
6$,$&FZ6$;,(F_rF/Fe]lFi`lF/F/F_r;,$FNFi`lFi`lFi`l-Fhv6%FSFN<#-F[el6$/6$,(FSF/Fd
blFi`lF/F/-Fa]p6$&Feq6#,$FdblFi`lFbzF//FdblFfbqF]cl-&Fjt6#%&EqualGF`[mFAFAFA6#F
^hnFA,
I/SchurReductiont+6'F\\pFgbr'%#nEGF__lFfbo'%%polsGF)63%#rgG%$crgGF_p%#M1G%#bsG%
#M2G%$tM2G%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GFgbp%#B3G%#B4G%$iB1G6"FAC3@$Fec
pOFL>FZ7#-F[el6$-FG6#7#-Fbt6#;,&-F_\m6$-FG6$F/Ff]p/Fagl;F/,&F^]qF/Fi`lF/F/F/F/-
F_\m6$F^et/Fagl;F/F^]q-Fcel6$F^]qFe]l>FNFbfl>FD7#-FG6#-F]fl6$<#-Fbt6#;F/F^[s<#-
FGFcfl>FS-Fh\l6$&FL6$FZFe[l&FL6$FDFe[l>Fhr&FS6$F^_nF`]q>Fgq-F\jm6$-Fd`t6$)FhrFf
jn.Fj_tFbz>Fb[m-Fbp6$f*FdjoFA6$FgoFhoFA-Fa]p6$F/-F]`l6$F]qF)FAFA6$FcctFgq<#-Fbt
6#;F/Fj_t>F`^m-F]`l6$-F]fl6$<#-Fbt6#;F/-FG6$FjasFgqFb[mF)>Fes-Fh\l6%&FS6$FghrFe
[l&FS6$7#-FGFefmFe[l&FS6$;Fa]nFi`lFe[l>Fft-F\jm6$-Fd`t6$&FesF_gtFfgtFbz>Fb[m-Fb
p6$f*FdjoFA6$FgoFhoFAF\htFAFA6$FectFftFaht>F`^m-F]`l6$-F]fl6$<#-Fbt6#;F/-FG6$Fj
asFftFb[mF)>Fdv-%$<|gr>G6%&Fes6$Fe[lFghr&Fes6$Fe[lFgit&Fes6$Fe[l;,&FeqF/F/F/Fi`
l>6&F^ilFchlFjhsF^]t6&&Fdv6$FdhtFdht&Fdv6$Fdht;,&Fj_tF/F/F/Fi`l&Fdv6$Ff\uFdht&F
dv6$Ff\uFf\u>F`^t-Fihp6$FbzF^il-F\jm6$,&F^]tF/-F\v6%FjhsF`^tFchlFi`lFbzFAFAFA6#
Fe^lFA,
I0LinDepReductiont+6$F\\pFfbo6)Fj_tFh_tF`ct%$tM1GFgct%&r2delG%&c2delG6"FAC*>FD-
F\jm6$-Fd`t6$)FLFfjnFgjoFQ>F_r-Fbp6$f*FdjoFA6$FgoFhoFAF\htFAFA6$Fh_tFD<#-Fbt6#F
h]p>Fhr-F]`l6$-F]fl6$<#-Fbt6#;F/-FG6$FjasFDF_rF)>FN&FL6$-Fh^r6$f*FdjoFA6$FgoFho
FA-Fdz6#-Fcel6$FLF^qFAFA6$Fj]uFhr7#FaftFe[l>FS-F\jm6$-Fd`t6$FNFgjoFQ>F_r-Fbp6$f
*FdjoFA6$FgoFhoFAF\htFAFA6$Fi]uFSFj^u>Fgq-F]`l6$-F]fl6$<#-Fbt6#;F/-FcilF[sF_rF)
6%&FN6$Fe[l-Fh^r6$f*FdjoFA6$FgoFhoFAF_`uFAFA6$F[^uFgq7#-Fbt6#;F/-FG6$FjasFNFhrF
gqFAFAFA6#FbqFA,
I)rectTordt+6&F%F[_l'%#TsGF)Ffbo6(Fbio%#dgGF`gl%#nnG%$GBsGFg`n6"FAC+>FZF]y>FD7#
-F[el6$*&-F_\m6#-Fbp6%FfalFLFb_lF/FZFi`l-Fcel6$Fb_lFQ>FN-Fbp6$f*6#Fc_lFA6$FgoFh
oFA*$FLFi`lFAFAFAFD>FS-Fijq6#-FG6#-Fbp6$%&denomGFN>FN*&FSF/FNF/>F_r-Fbp6$f*Faal
FA6$FgoFhoFA-Fiq6%F\zFL/F_zF]zFAFA6&F&FLFexFbzFeq>Fhr7#-FG6#<#-F[el6$&-Fijn6$&F
_rFdjo-&Fjq6#%0LeadingMonomialG6$Fdfu&FeqFdjoFfr/Fagl;F/Fir>Fhr-Fbp6$f*F[]oFA6$
FgoFhoFA-Fao6%f*Fg]mFA6$FgoFhoFAFe_oFAFAFAFLF^qFAFA6$F`glFNFhr-Fbp6$f*FaalFA6$F
goFhoFA-FdinFgalFAFA6$F7FQFhrFAFAFA6#Fg[lFA,
I,filterBasest+6&F%'F\`mF)'%%nQBsGF3'%#ffGFebo6&%#mFG%#BsGFc_sFgjm6"FAC(>FS-Fjh
l6#*&FbzF/FeqF/>FZ-F]`l6$&-Fcy6%FLF]yFIFauF*>FD-Fbp6$f*FaalFA6$FgoFhoFA-Fjr6#-F
jel6$FajmF^qFAFA6$FghuFZFQ>FN-Fb]m6%FD%">G/%'outputG%,permutationG-F]s6#-F`s6$F
S%>~quotient~space~bases~removedG7#-FG6$;F/,&FeqF/FSFi`lFNFAFAFA6#Fg[lFA,
I(iniProbt+6&Fh_m'%#qbGF__lFdhu'%#pnGF360F&%#vFGFexF7FacuF]cu%#GCGF\`m%$CMsGF9F
ehnF<FaerFchu6"FAC*AF`dm>6$FZFN6$FedmFbz>FD-F(Fcfl@$0-&Fjq6#%1HilbertDimensionG
6$FZ/F_zFNF_qYQZThe~problem~is~expected~to~have~infinitely~many~solutionsFA>FSF
_em@'/FQF/C)>6%FNFhrFft-FhenFK>FchlF\gm-F]s6#-F`s6$Fchl%8~change~matrices~loade
dG>F_r7#-F[el6$-F\jm6$-Fbp6$F`jm-F]`l6$-F\v6$&FftFdjoFDF)FN/Fagl;F/Fchl>Fes7#-F
[el6$&-Fbr6$Fdfu&FhrFdjoFfrFh^v>F^il-F^hu6&FZFesFchlFeq>6&FftF_rFhrFes6&7#-F[el
6$Fg^v-Fcel6$FaglF^il7#-F[el6$FdfuF[`v7#-F[el6$Fa_vF[`v7#-F[el6$&FesFdjoF[`v/FQ
FbqC*>Fes-FgamFK>FchlF[fm-F]s6#-F`s6$Fchl%=~quotient~space~bases~loadedG>Fdv-FU
6#F`fp>Fgq-Fiq6&FZFdvF[]v/Fdju%)extendedG>6$F`^mFb[m6$&FgqFfr-Fhv6#&FgqFau>F^il
Fc_v>Ff_v6&7#-F[el6$Fb[mF[`v7#-F[el6$F`^mF[`v7#-F[el6$FdvF[`vFc`vC+>Fhr-Fbp6$f*
FaalFA6$FgoFhoFA-FU6#-FGFKFAFAFA-&%)combinatG6#%(permuteGFd[n>Fhr-Fibu6&FZ7#F`f
pFhrFN>Fgq-Fbp6$f*FaalFA6$FgoFhoFA7#-Fiq6&F^qFL/F_zFhwFgavFAFA6&F&FZFexFNFhr>6$
F_rFft6$-Fbp6$f*FaalFA6$FgoFhoFAF`jqFAFAFAFgq-Fbp6$f*FaalFA6$FgoFhoFA-Fhv6#Fajq
FAFAFAFgq>FchlFir>FesF[_v>F^il<#-F[el6$-Fa]p6$Ff`vFesFh^v>Ff_vFg_v-F]s6#-F`s6&F
[fm%A~quotient~space~bases~computed~(GFchl%")G-F]s6#-F`s6%%AThe~problem~is~expe
cted~to~have~G-Fjr6#&FesFfr%+~solutionsGO6)FNFZFSF_rFhrFesFftFAFAFA6#Fg[lFA,
I/TemplateFindert+6*Fh_m>'%,action_varsG-F)6#<$%'negintGF3Fabm>'%-deg_over_minG
F__lF_q>'%,filter_fracGFeboF_q>'%&partsGFbboF[`r>%-prime_numberGFgcm>'%*quo_bas
esGF__lF_q>'%+schur_polsGFfgvFabm6KF&FexF7%&avarsGFhboFacuF]cuF\`mF[\vFbbpF9Fag
lF][pFdblF[jrFgbrF`xF>FebpF:FhbpF=F<F\cq%#flGF_pFgjm%#moG%#noGFdbo%$spoGFecmF_g
lFibpF;Faer%%irngG%#nkGFjboFehn%&tord1G6"FAC,>8?"(+++">8BFi`l>6)FDFZFNFhrFgqFes
Fft-Fa[v6&FLFj`lFbzF]cl>FS-Fhp6%/Fi_lF_qFN-Fbp6$f*6#F8FA6$FgoFhoFAF]qFAFA6$F7FN
FQ>8G-%%iquoG6$F[fm&Fe]lFfr>8H7#-Fbt6#;,&F/F/*&,&&Fe]lFauF/Fi`lF/F/FjjvF/F/-Fhp
6%/Fh[wF^[wF[fm*&Fh[wF/FjjvF/>6%8D8F8I6%FddpFifv-Fjr6#F`[w>8C,$*&Fa\wFi`lF_\wFi
`lF_jl?(FchlF/F/Fa\wF_yC&>F`^m&F`[w6#Fchl>6&FdvFb[m8J8K6&&FhrFefm&FgqFefm&FesFe
fm&FftFefm>8L-FG6$F/Fb[m?(F^ilF/F/F_\wF_yC.>F_r&FSFa_m>6(868788898:8;-F^bp6'F_r
FdvFb[mFDF`]w>8E-Fjr6#Fe^w>Fjhs-Fhp6%/Fj`lFbq-F\[q6'FZFe^wFNFDFeq-Fhbq6(FZFe^wF
f^wFa]wFNFD>6%F^]tF`^t85-Ff^s6'FZFjhsFc^wFNFD>F`^t-Ffbt6'F`^tF^]t,(-FG6$FjasF`^
tF/F`\wFi`lFj^wFi`lFDFefo>F`^t&-Fe]u6$F`^tFDFfr>8<-Fa_t6(Fd^wF`^tFa^wFb^wFj^wFD
>6$8=8>-FG6$F/F`^t>8A-Fj]p6#F`^t@&3Fe`w52Fj`wFgiv3/Fj`wFgiv2FjivF_awC%>6%Fgiv8@
Fjiv6%Fj`wF[awF_aw-F]s6#-Fbhm6(QTSmaller~or~sparser~template~found:~[%d,%d],%a,
%a,%aFAFj`wF[aw-F_u6$F_awFeflF_r-Fhp6%F`_wF`^mFh]w-F]bo6,FL7$Fj`wF[aw-F_u6$F_aw
Fe^lFDFNF_rFb[mFb^wF^]t-Fdz6#0Fj`lFbq4Fe`wY6&Q@Invalid~action~matrix,~%1,%2,%3F
AF`^mF_rFb[m-F]s6#-Fbhm6*Q6%d%s,[%d,%d],%a,%a,%aFA-Fjhl6#*&,&*&,&FchlF/Fi`lF/F/
F_\wF/F/F^ilF/F/Ff\wF/Q"%FAFj`wF[awFcbwF_rFebw-F]s6#-Fbhm6&Q:Best~template:~[%d
,%d],%aFAFgivF\bw-F_u6$FjivFeflFAFAFA6#F/FA
