M7R0
I,readProblemt+6#'%%probG%'stringG6$%#fnG%"FG6"6"C'>8$-%$catG6%Q,problems/F_F,9
$Q#.mF,@$4-&%*FileToolsG6#%'ExistsG6#F/Y-F16%%&File~GF/%+~not~foundGAF/>8%-%$ma
pG6$%'expandG-%%evalG6#-F16$%#F_GF46$FE7#-%#opG6#-%'indetsG6#FEF,F,F,6#"""F,,
I+isLinIndept+6&'%"MG%%listG'%"GGFin'%%tordG%3ShortMonomialOrderG'%#ppG%'posint
G6$%%varsG%"SG6"F,C&>F/-FV6#9%@$/-%%nopsG6#F4FYO%%trueG>FE&-%,poly2matrixG6%-FG
6$f*6#%"mGF,6$%)operatorG%&arrowGF,-&%)GroebnerG6#%+NormalFormG6&F4T$T&/%/chara
cteristicGT(F,F,6(F[oFjoF]o9&F`o9'F4F]pF/6#FY-%#isG6#0-&&%.LinearAlgebraG6#%(Mo
dularG6#%%RankG6$F\rFE-Fcr6$F\r&FE6$;FY!"#;F,F,F,F,F,6#""%F,,
I*testBasist+6''Fhn%$setG'%$degGFaoFjnF\o'F`o%*nonnegintGFbo6"F,C&>F/-FV6#F[r@$
2F]pFjoO6$%&falseG-%$<,>G6#-Fht6#""!>FE&-Fep6%-FG6$f*FjpF,6$F]qF^qF,F_qF,F,6(F[
oF[rF]oF\rF`o9(F4F]pF/F]r6$-%#ifG6%0FfuF\u-F_r6#/-Fcr6$FfuFEFjo-F_r6#/-&FerFhrF
WFjoFEF,F,F,6#""&F,,
I*iniMonSett+6)'F*<%%'VectorGFinFhs'%#B0GFin'FcoFinFjnF\oF_o>'%$domGF\tF\u6*%"E
GFhn%#vrG%"dGFjs%%flagGFdo%&d_minG6"F,C*>8(-F^pFio>8+F\u>F/-%(convertG6$-FG6$FS
-&Faq6#%(SupportGF_pFhs-%&printG6#-F16%%<Polynomial~system~contains~G-F^pF=%+~m
onomialsG>FEF/?(8'F\uFYF,1,&FeyFYF`x!""9*C&>8&-%'selectG6$f*6#%"xGF,6$F]qF^qF,1
-%'degreeG6$F4FeqT%F,F,6&FcoF[rFgwFeyFE>FE-FG6$f*6#%"tGF,6$F]qF^qF,-FS6#-FG6$f*
6#%"kGF,6$F]qF^qF,*&FeqFYF4FYF,F,6$F_[lF4T#F,F,6$FfwF\zFE>6$8)8*-Fds6'FEF]xF\rF
fu9)@$4F_\l>F`x,&FeyFYFYFY-F\y6#-F16%%6Initial~set~contains~G-F^pFWFbyO6$F/FEF,
F,F,6#""(F,,
I-neighborMonst+6%'%"BGFhs'%#MBGFhsF`w6#%#nBG6"F,C&@$/F]pF\uOFjo>F/-F^z6%%%type
G-FG6$FS<#-%$seqG6$-Fh^l6$<$*&%"bGFY%"vGFhy*&F^_lFYF__lFY-%#inG6$F__lF[r-Fb_l6$
F^_lF4%)monomialG>F/-%*intersectG6$-%&minusG6$F/F4Fjo-Fiu6%/FayF\uFjoF/F,F,F,6#
""$F,,
I)genBasist+6)'FewFhsFgsF^wF`wFjnF\oF_o60%$rndGFf]l%#EBGFh]lFj]l%$nB1G%#bvGFg[l
%"aG%#nvG%#wtGF[q%"iGFjs6"F,C->F/,$-I%randG6$%*protectedG%(_syslibG6#;F\u"%+5#F
YF[bl>FE<">FeyFjo>8--F^p6#F\r>81-F^pFat-%*randomizeGF,>F`\l7#-Fh^l6$-%&roundG6#
-F/F,/80;FYFabl>F`x-&%$maxG6#%&indexG6#-FG6$f*FazF,6$F]qF^qF,,&F4FY*&-F[\lF,FY$
"$+"F\uFhyFYF,F,6$Fh`lF/F`\l>8,&F\r6#F`x?(F,FYFYF,2F]]lFeblC*>Fey-F\`l6$FeyFE>F
]x-Fb]l6%FEFeyF\r>F\z-%&unionG6$F4FE>8.f*FazF,6$F]qF^qF,,*-Fiu6%-Fb_lFgzFYF\uFY
-Fiu6%-Fb_l6$*&FhzFYF4FYT'FYF\uFY-%$addG6$*&&T)6#T+FY-Ffz6$F4&T.FjflFY/F[gl;FYT
/FY*&-T1F,FYFbdlFhyFYF,F,62FewF4F\alFfdlFi`lF\zF[alF`\lF_alFbclFcoF\rF]alFablFh
`lF/>F_\l-%%sortG6$7#-FS6#F]xf*6$Fbz%"yGF,6$F]qF^qF,1-F[\lFio-F[\lF_pF,F,6$F^al
Fgel>6$8/Fbcl6$&F_\lF]rFY?(F,FYFYF,34-FZ6&7$-FSFWFhhlFfuFc\lFiy2Fbcl-F^p6#F_\lC
$>Fbcl,&FbclFYFYFY>Fhhl&F_\l6#Fbcl>FE<$FailFhhlFEF,F,F,6#Fa]lF,,
I*readBasest+F$6%%#stG%$QBsGF)6"F,C)>F/FY>FE7">F\z-F16$Q)bases/b_F,F4@$4-F96#F
\zY-F16%FAF\zFB?(F,FYFYF,0F/F\uC$>F/-%)readlineGF_[m@$Fd[m>FE7$Fail-%&parseGF=-
F\y6#-F16$F]]l%=~quotient~space~bases~loadedGFEF,F,F,6#FYF,,
I,BasisFindert+6'F%>'%-deg_over_minGF\tF\u>%%modeG%'APPENDG>'%0number_of_basesG
FaoFcdl>'%-prime_numberGFao"&\F$6/F`oF*FcoF]oF[oF_wFgwFewFhn%#BBGFf]lF)%#fdG6"F
,C.>F/-%*prevprimeG6#,&FfuFYFYFY>FfdlFgjl>FhhlFijl>6$FEF\z-F"F_p>Fey-%%tdegG6#-
FSF_[m>F]x-&Faq6#%&BasisG6%FEFey/FhqF/>F_\l&-&Faq6#%*NormalSetG6$F]xFeyF]r>6$F`
xFfdl-Fhv6)FEF_\lF\zF]xFeyF/Fjo>Fabl-Fiu6%/F[rF\]m-F^jlF_pFgjl>Fbcl-%&fopenG6$F
hhlF[r?(F,FYFYF,2-F^p6#FablF\rC$>Fgel-Fc`l6)F`xFfdlF_\lF\zF]xFeyF/@$4-%'memberG
6$FgelFablC%>Fabl7$-FSFf`mFgel-%(fprintfG6%FbclQ$%a|+F,-Fcx6$FgelFin-F\y6#-%(sp
rintfG6%Q%%d%sF,-F^cl6#,$*&Fe`mFYF\rFhyFcdlQ,%~completedF,-%'fcloseGFjilF,F,F,6
#FYF,,
I*writeGfant+6$F%>Fa]mFc]m6&F`oF*FcoFf]m6"F,C(>F/-F[^m6#,&FjoFYFYFY>Fey-Fa`m6$Q
)gfan/igfF,%&WRITEG>Fa^mFb^m>FE-%$modG6$-FG6$FI-Fcx6$FEFhsF/-Feam6'FeyQ+Z/%aZ%a
|+%aF,F/F\zFE-Ffbm6#FeyF,F,F,6#FYF,,
I)readGfant+6#'F)F'6&FhwFajl%"nGF`o6"F,C*>F/Fft>FEFY>F\zF\u@$4-F9F_pY-F16%FAF4F
B>FE-Fh[mF_p>Fey-F]\m6#-%*substringG6$FE;Fb`l,&-&%,StringToolsG6#%.FirstFromLef
tG6$Q"[F,FEFYF`sFY?(F,FYFYF,0FEF\uC$>FEFiem@(5/FEQ#|fr|frF,/FEQ"|frF,C%>F/Fap>F
\z,&F\zFYFYFY>(F[oF\zFgjl3F/0-F^fm6$FEFhyQ"|hrF,>Fhgm7$-FS6#Fhgm-F^fm6$FEF_s3F/
/F[hmF]hmC$>FhgmF_hm>F/FftO6%Fey7#-Fh^l6$-FG6$F]\m(F[oF_al/F_al;FYF\z7#-Fh^l6$-
FG6$f*FazF,6$F]qF^qF,-F]\m6#-F^fm6$F4;FY,&-Fcfm6$Q"+F,F4FYFhyFYF,F,F,F`imFaimF,
F,F,6#FYF,,
I(writeCMt+6$F%>Fa]mFc]m6)%$Ws0GF`oF)Ff]mF*Fco%#WsG6"F,C7>FEF`cm>F\z-F16$Q+weig
hts/w_F,F4>F/-%,readWeightsGF_[m>F`\l-&Fdfm6#%.SubstituteAllG6%-Fg[n6%-Fcx6$F/F
'FhfmQ"(F,Q"]F,Q")F,>6$F]xF_\lFb^m>F_\l-Fcx6$F_\lF'>F]x-Fcx6$-F[dm6$-FG6$FIF]xF
EF'>Fey-Fa`m6$Q'cm/icmF,Fgcm-Feam6'FeyQ<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+F,F`\lFEF
_\l-Feam6%FeyQ6f~=~openOut~"cm_%s";|+F,F4-Feam6$FeyQ<f~<<~toString(pp)~<<~endl;
|+F,-Feam6$FeyQ<f~<<~toString(vr)~<<~endl;|+F,-Feam6%FeyQ9for~i~from~0~to~%a~do
~(|+F,,&FayFYFhyFY-Feam6$FeyQ>f~<<~toString(Ws#i)~<<~endl;|+F,-Feam6&FeyQ.R~=~Z
Z/%a%s,~F,FE-F^fm6$F_\lF_s-Feam6$FeyQDMonomialOrder~=>~Weights~=>~Ws#i];|+F,-Fe
am6%FeyQ0I~=~ideal(%s);|+F,-F^fm6$F]x;""#F`s-Feam6$FeyQVG~=~gb(I,ChangeMatrix=>
true);|+M~=~getChangeMatrix~G;|+F,-Feam6$FeyQ>f~<<~toString(M)~<<~endl;|+);|+F,
-Feam6$FeyQ,f~<<~close;F,FddmF,F,F,6#FYF,,
I'readCMt+F$6(FajlF)F`oFcoF[qF\em6"F,C,>F/FY>FE-F16$Q'cm/cm_F,F4>F]xF\u>F_\lF\u
@$4-F9FWY-F16%FAFEFB>F\z-F]\m6#-Fh[mFW>FeyFaan?(F,FYFYF,Fd[mC$>F/Fcan@&3Fd[m/-F
^fm6$F/FYF_\nC$>F]x,&F]xFYFYFY>(%"TGF]x-F^fm6$F/Fb_n3Fd[m/-F^fm6$F/;FY""'Q'matr
ixF,C$>F_\l,&F_\lFYFYFY>(%#CMGF_\l-Fg[n6%-Fg[n6%-F^fm6$F/;""*F`sFbgmFhfmF]hmF`
\n-F\y6#-F16$F_\l%8~change~matrices~loadedGO6%F\z7#-Fh^l6$-%%wdegG6$7#-F]\m6#(F
bbnF_alFey/F_al;FYF]x7#-Fh^l6$)-%'MatrixG6#7#-FG6$F]\m(FacnF_al%#%TG/F_al;FYF_
\lF,F,F,6#FYF,,
I(getTordt+6$%#gbG%#lmG6+FcoF]al%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG%$solG%(
weightsG6"F,C,>F/7#-FS6#-FVF_p>FEFay>F\z/7#-%"$G6$F\uFE%%NULLG>Fey7#-Fh^l6$(Fgw
F_al/F_al;FYFE>F]x-FG6$f*6#%"zGF,6$F]qF^qF,-FG6$f*FazF,6$F]qF^qF,7#-Fh^l6$-Ffz6
$F4F`hl-Fb_l6$F`hlF[\lF,F,6$FcoF[\l-Fcx6$F4FinF,F,6$FcoF/F4>F_\l-FG6$f*FazF,6$F
]qF^qF,FjhnF,F,FdinFjo>F`\l-FG6$f*Ff[lF,6$F]qF^qF,-FS6#-FG6$f*FazF,6$F]qF^qF,1F
Y-Fefl6#-%$zipG6%f*6$F`hlFdhnF,6$F]qF^qF,*&F4FYFjoFYF,F,F,F4F[\lF,F,6$FcfnFifl-
%%subsG6$F[\l7#-Fh^l6$,&&FhzF_pFY%"gGFhy-Fb_l6$Fh[o&FcflF_pF,F,6*FbfnF\zFefnF_
\lFdfnF]xFcfnFey<#-Fegn6#;FYF]p>F`x&-&%-OptimizationG6#%)MinimizeG6&-FeflFedmF`
\l/%+depthlimitG"#S/%'assumeGF\t6#Fc_n>Ffdl-Fa[o6$F`xFey6$Ffdl-Fedn6$FfdlF/F,F,
F,6#Fc_nF,,
I,readWeightst+Fidm6$FajlFjjm6"F,C(>F/FY>FEFgjl@$FcemYFfem?(F,FYFYF,Fd[mC$>F/Fi
em@$Fd[m>FEF[\m-F\y6#-F16$F]]l%7~weight~vectors~loadedGFEF,F,F,6#FYF,,
I-writeWeightst+6'F%>F[]mF\]m>'%2number_of_weightsGFaoFcdl>Fa]mFc]m>'%+rand_ran
geG7$FaoFao7$"$+#"$+)60F`o%#GsG%$LMsG%#WWG%%gffnGF)Ff]mF_al%"WGF*FcoFh`lF]oF[o6
"F,C&>F/-F[^m6#,&F\rFYFYFY>F]x-F16$Q)gfan/gf_F,F4>F_\lF_[n@%-F9F]hlC(-F\y6#%IGe
nerating~weight~vectors~from~Gfan~fileG>6%F/FEF\z-FgdmF]hl>Fey7#-Fh^l6$&-F\fn6$
&FEFhdl&F\zFhdlF]r/F`x;FYF]]l>F`\l-Fa`m6$F_\lFgcm?&FfdlFeyFap-Feam6%F`\lFgamFfd
l-Ffbm6#F`\lC+-F\y6#%4Gfan~file~not~foundG-F\y6#-F16%%,Generating~GF[r%7~random
~weight~vectorsG>6$FablFgelFb^m>Fhhl-Feal6#;&FfuF]r&FfuF_]oFgbl>Fey-Fiu6%/FjoF
\]m-Fd[nFdilFgjl>F`\l-Fa`m6$F_\lFjo?(F,FYFYF,2-F^pFedmF[rC&>Fbcl-Fedn6$7#-Fh^l6
$-FhhlF,/F`x;FY-F^p6#FgelFgel>Febl-Fj^m6%FablFbclF^_m>Ffdl&-F\fn6$Febl-&Faq6#%0
LeadingMonomialG6$FeblFbclF]r@$4-F^am6$FfdlFeyC%>Fey7$-FSFedmFfdlFcbo-F\y6#-F]b
m6%F_bm-F^cl6#,$*&FcdoFYF[rFhyFcdlFdbmFeboF,F,F,6#FYF,,
I)saveDatat+6-F%'%#mnGFf_o'%#spG%(numericGF_o'Fco<$FinFhs'%#avGFf_lF\o'%#QBGFin
'%'shiftsGFin'%%polsGFin'%$stdG%(booleanG6'F)Ff]m%$mn0G%$sp0GFhw6"F,C&>F/-Fiu6%
9.-F16$Q-optim/o_std_F,F4-F16$Q.optim/o_nstd_F,F4>F]xFft@%F8C'>FE-Fa`m6$F/%%REA
DG>F\z-F]\m6#-Fh[mF=>FeyFiio@$52&FjoF]r&F\zF]r3/F`joFajo2FeyF[r>F]xFap-FfbmFW>F
]xFap@$F]xC%>FE-Fa`m6$F/Fgcm-Feam6.FEQ>%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%aF,
FjoF[rF\r-Fcx6$FfuFinFc\lFiy9+9,9-FgjlFfjoF,F,F,6#"#6F,,
I)readDatat+6$F%F_ho6.F)Ff]mFagoFcgoF`oFcoFhgoF]oFjgoF\hoF^ho%$xE0G6"F,C1>F/-Fi
u6%FjoF[ioF^io@$F7YF?>FEFeio>F\zFiio>FeyFiio>F]xFiio>F_\lFiio>F`\lFiio>F`xFiio>
FfdlFiio>FablFiio>FgelFiio>FhhlFiioFfjo6,F\zFeyF]xF_\lF`\lF`xFfdl-FG6$FKFablFge
lFhhlF,F,F,6#Fc_nF,,
I,EigenSolvert+6$'F*-F\w6#%(polynomG>'%'digitsGFao"#:6,%%fB2CGFcoF]oF[oFf]lFjs%
%irndGF\alFbbn%"VG6"F,C0>FEF\gn>F\z-Fe^m6#Fail>F/t+6$'%"fGFh]p'Ff]l-Fin6#Ff_lF^
[l6"F,C$>F/-%&tableG6#-Fijn6%f*6$F\alF^_lF,6$F]qF^qF,/FjoF4F,F,F,7#-%'coeffsG6%
F4Fjo.F[q7#F[qO-FG6$f*6#F^_lF,6$F]qF^qF,-Fiu6%-%)assignedG6#&F[\lF_pF\apF\uF,F,
6$F_[lF/FjoF,F,F,6#Fc_n>%'DigitsGFjo>Fey-Fj^m6$F4F\z>F]x&-Fb_m6$FeyF\zF]r>F_\l-
F^pF]hl-F\y6#-F16%%<System~is~expected~to~have~GF_\l%'~rootsG>F`\l,$-Feal6#;!%+
5F[blF\bl>F`x-Fefl6$*&FfwFY-F`\lF,FY-Fb_l6$FfwFE>Ffdl-&Faq6#%5MultiplicationMat
rixG6'F`xF]x-Fc_p6#-%'EquateG6$F]x7#-Fegn6#FjenFeyF\z>Fabl&-&Fer6#%-Eigenvector
sG6#-%&evalfG6#FfdlF_]o>Fabl-&%"|irG6#_F,%"/G6%Fabl%#~$G-%".G6$-F]w6$F_\l/%%fil
lGFY&FablF]rO-F_ep6$-Fben6#-FG6$f*6#F__lF,6$F]qF^qF,-Fifl6$-F`q6%F4F[\lFhzFcflF
,F,6*F[oFeyF]oF\zFf]lF]xF^^pF/FEFablF,F,F,6#FYF,,
I$srtf*6$'F__lF\wF\oF,6$F]qF^qF,-Figl6$F4f*F_hlF,6$F]qF^qF,-&Faq6#%*TestOrderG6
%FjoF4FeqF,F,6$F]oFjoF,F,F,F,,
I,poly2matrixt+6%F[w'%#nFGFaoFego6$%%monsG%%cffsG6"F,C$>FE7#-F]`p6%-FI6#-Fefl6$
*&(%$q_qGF_alFY&F46#F_alFY/F_al;FYFjoF[r.F/6$-Fben6%FjoF]]lf*6$F_al%"jGF,6$F]qF
^qF,-%&coeffG6$&F[\lFio(FihpF4F,F,6$F\hpFE-F]w6#7#F/F,F,F,6#Fb`lF,,
I/permuteColumnst+6%'FhnFben'%#V1GF]w'%#V2GF]w6#F\em6"F,C$>F/-FS6$FYFjo-F_ep6$F
4-Fben6$F/<#-Fh^l6$/6$F_al-&%*ListToolsG6#%'SearchG6$&FjoF[ipF[rFY/F_al;FYF/F,F
,F,6#Fb`lF,,
I)sparsityt+6#Fcjp6#%&numzrG6"F,C$>F/-F^p6#-F^z6$f*FazF,6$F]qF^qF,-F_r6#/F4F\uF
,F,F,Fbin*&F/FY-%$mulG6#-FS6$FYF4FhyF,F,F,6#FYF,,
I(matrixSt+6''Ff]lFinF^wFjnF\oF[t6%Fdo%#V0GFjs6"F,C&>F\zF]p@$0F^xF\zY%ILists~B0
~and~B~must~have~the~same~lengthG>F_]l-Fep6%-FG6$f*Fe`pF,6$F]qF^qF,F_qF,F,FeuF4
F\zF`t@%/-FS6$FYFEF\zO-F`jp6%F/FE-F]wFioY%=Failed~to~construct~matrix~SGF,F,F,6
#FgvF,,
I*quotientst+6&'Fh[oFh]pFjnF\oF[tF,6"F,C$-F`q6'F4FjoF[r.%"QG/FhqF\rFa`qF,F,F,6#
FcsF,,
I-monPartitiont+6'Fggo'%#GrGFinF\oF[t>FigoFgjl6,F_wFf]l%#aBG%"RG%#B2G%#RBGF[o%#
nGGFbbnFdo6"F,C->F/&-Fb_m6$FjoF[rF]r>FE-Fcx6$-Fiu6%/FfuFgjlF/FfuFhs>F\z-FG6$f*F
azF,6$F]qF^qF,Fi[lF,F,6$FhgoF4FE>Fey-Fffp6$-Fcx6$-F\`l6$F\zFEFinF[r>F`xFcdo>F]x
-FG6$f*FazF,6$F]qF^qF,*&F4FYFeqFhyF,F,Fabq-Fi_lFhbq>FE7$-FS6#-Fffp6$-Fcx6$-F\`l
6$FEF]xFinF[r-FS6#-Fffp6$-Fcx6$F]xFinF[r>6$F_\lF\z6$7$FcfoFail-FG6$f*FazF,6$F]q
F^qF,Fi[lF,F,FabqFE@%F[bq>Ffdl-F_cp6(F4FE-Fc_p6#-Ffcp6$FE7#-Fegn6#F^boFjoF[rFb`
qC%>Ffdl-F_cp6(F4F/-Fc_p6#-Ffcp6$F/7#-Fegn6#;FYFayFjoF[rFb`q>Fabl-Fi]q6'FEF/Fjo
F[rF\r>Ffdl-Fiu6%0F\rF\u-F[dm6$-F_ep6%FablFfdl-&Fdr6#%(InverseG6$F\rFablF\r-F_e
p6%FablFfdl-&Fer6#%.MatrixInverseGFf`m>F`\l-Fcx6$,&-F]wFedmFY-F_ep6$&Ffdl6$;FYF
`xFas-F]wFWFhyFinO6(F\zFEF_\lFfdlF`\l-Fben6#7#-Fh^l6$-Fh_q6&&F`\lF[ipFjoF[rF\r/
F_alF_hqF,F,F,6#FgvF,,
I)matrixHit+6&F[wFjnFegoF[t6/%*undetPolyG%#pvGFigpF_aq%#uHG%%leqsGFgfnF_al%#dFG
%#dGGFgwFiw%"hG6"F,C)>FE-FeflFat>F\zF]p>FeyF^x>Ffdl-FG6%FfzF4F[r>F/t+6&FegoFbiq
FgwFdip6#F[hp6"F,C%-F]`p6%-FI6#,&FYFY-Fefl6$)Fjo%"pG/F_[r;FYF[rFYF4F^ip>F/F^jp-
Fefl6$*&&F/Ff[lFY&%#_vG6$F\rFg[lFY/Fg[lF_fqF,F,F,6#Fcs?(F`xFYFYFeyFapC%>6$FhhlF
abl6$F\u-FG6$f*FazF,6$F]qF^qF,-Fgcl6$F\uF4F,F,F,,&7#-Fegn6$-Ffz6$&FjoFhdlF[rF\z
FYFfdlFhy?(FgelF\uFYF,1,&FgelFYFhhlFhyF\uC&>F]x7#-Fh^l6$-F/6&F[rFE,&&Fabl6#Fdip
FYFgelFYFdip/FdipFbim>F_\l<#-F]`p6$-FI6#,&F]]rFhy-Fefl6$*&&F]xFj]rFY&F4Fj]rFYF[
^rFYF[r>F`\l-%'msolveG6$F_\lF\r@$/-F^p6#<#F`\lF\u>Fhhl,&FgelFYFYFY>&FbclFhdl-F[
dm6$-FG6%-%"@G6$FIFKF]xF`\lF\rO-Fht6#-Fh^l6$-&F]w6#%$rowG6#Fd_r/F`x;FYFeyF,F,F,
6#FcsF,,
I*matrixHnit+6(F[wFjn'%"CGFben'FacnFbenFegoF[t6*%,undetPolyniGFigpF_aq%#H0GFciq
FdiqFgfn%%parsG6"F,C+>FEF]p>F\zF^x>F/t+6&'FgiqFh]pFego'F_alFao'FdipFaoFdjq6"F,C
%-F]`p6%F4FjoF^ip>F/F^jp-Fefl6$*&Ff[rFY&Fh[r6%F[rF\rFg[lFYFj[rF,F,F,6#Fcs>Fey-F
[dm6$-FG6$FI-F_ep6$F[rF\rFc\l>F]x-Fben6%F\zFEf*FcipF,6$F]qF^qF,-Fcfl6&&F[\l6$F4
FjoFfqF4FjoF,F,6(FaarFeyFcoFfuF`arF/>F`x<#-Fh^l6$&%#_uGF[ip/F_al;FY-F^p6#-F\`l6
$-FVF]hlFfu>F_\l-FG6%F]`p<#-Fh^l6$-F[dm6$-FI6#,&F]\qFhy-Fefl6$*&&F]xFcipFYFg^rF
Y/FdipF^hnFYFc\lFaimFfu>F`\l-Fj^r6%F_\lF`xFc\lO-F[dm6$Fg_rFc\lF,F,F,6#FjbnF,,
I*syzModulet+6'F[wFjn'%"AGFbenF\oF[t6*FigpF_aq%"eG%"LG%#LtGFhnFdoFf]l6"F,C.>F/F
]p>FEF^x>F\z-Fh^l6$-F]w6$FE<#/F_alFYF]hn>Fey7#-Fh^l6$7#-&Faq6#%,LeadingTermG6$F
]\qF\rF]hn>F]x-FG6$f*FazF,6$F]qF^qF,*&&F4F]rFY&F4F_]oFYF,F,F,Fey>F_\l-Fben6$FEf
*FcipF,6$F]qF^qF,*&-%$lcmG6$&F\apF_]o&FiipF_]oFYFg[oFhyF,F,6&FdfrFeyFefrF]x>F`
\l7#-Fh^l6$-Fh^l6$,(*&&F_\lFcipFY&F\zF[ipFYFY*&&F_\l6$FdipF_alFY&F\zFj]rFYFhy-F
ht6#-Fh_q6&z'6&FgirFjirF]\q&FjoFj]r[[[\[[[[[\[[mFY\[[[[[\[[[[[mFhyFjoF\rFfuFhy/
Fdip;,&F_alFYFYFYFEF]hn>F`\l)-FbenFfboFhen>F`x-Fben6#7#-Fh^l6$-Fh_q6&FjhpFjoF\r
FfuF^\q>F`\l-FG6$FI-Fht6$-F_ep6$F`\lF[r,&-&Fer6#%/IdentityMatrixGF=FY-F_ep6$F`x
F[rFhy@$F[v>F`\l-F[dm6$F`\lFfuO&F`\l6$-%'removeG6$f*F[ipF,6$F]qF^qF,-&%+ArrayTo
olsG6#%'IsZeroG6#&F[\l6$F4FasF,F,6$FdoF`\l7#-Fegn6#;FY-FS6$7$FYFYF`\lFasF,F,F,6
#FgvF,,
I+matrixHsyzt+6(F[wFjnF\arF`frF\oF[t6$Fdo%&ThetaG6"F,C%>F/-F]fr6'F4FjoF\rFfuFc
\l>FE-Fben6%-FS6$F[^sF[r-FS6$F[^sF/f*FcipF,6$F]qF^qF,&F_[lFgcrF,F,F,O-F[dm6$-FG
6$FI,&F]crFY-F_ep6$FEF/FYFc\lF,F,F,6#FjbnF,,
I(supportt+6$Fj^pFegoF,6"F,C$F\`p<#F[qF,F,F,6#Fc_nF,,
I,fixTemplatet+6'%'admonsGF[wFego'%$monGFin'F^aqFin6/Figp%%monFG%&admonGF_alFdi
pFa`qFhw%#xFGFhnF^^qFewF`^p%%mon1G6"F,C.>F/F^x>FE-FG6$f*6#F[_pF,6$F]qF^qF,-Fj_s
FgzF,F,6$FcoF[rFjo>F\z7#-Fegn6$F^blF/?(FeyFYFYF]pFapC%>F`\lFft?(F]xFYFYF/FapC$>
F_\l-FG6$f*6#%#mfGF,6$F]qF^qF,-Fiu6%-%'divideG6%&Feq6#FhzF4.%"qGF`csFggnF,F,6&F
d`sF4F_alFey&FEF]hl@$0F_\lF^blC%>&F\zF]hl<$Fjhl-FS6#Fgcs>F`\lFap[@$4F`\lY%;Fail
ed~to~correct~templateG>Fbcl7#-Fh^l6$-Fcx6$-Fdel6$-Fcx6$&F\rF]hlFhsFgcsF]w/F]xF
_\q>F`x7#-Fh^l6$-Fh^l6$*&&FjoF]hlFYFagoFY-Fb_l6$Fago&FbclF]hlF\es>6$FfdlFabl-Fe
p6%F`x-F^pFhdlF[r>Fgel-F\`l6$-Fcx6$FablFhs-Fcx6$FfuFhs>Fgel-Fffp6$7#-FSF_eo-Fe^
m6#-FSFat>Fhhl-Fht6$Fhfs-FS6#Ffu-F\y6#%/Template~fixedGO6&FbclFfdlFablFhhlF,F,F
,6#FgvF,,
I2constructTemplatet+6&'%"HG<$FbenFinF[wFegoFg`s6)FigpFf`sF[asFhnF^^qFewF`^p6"F
,C+>F/F^x>FE-Fiu6%-Fc^l6$F4Fben7#-Fh^l6$&-Fep6%&F46$FasFdip-FS6$F[^sF4F[rF_]o/F
dipF_\qF4>F\z7#-Fh^l6$-Fh^l6$*&FcjrFYFagoFY-Fb_l6$Fago&FEFj]rF`is>6$FeyF]x-Fep6
%F\z-F^pF_[mF[r>F_\l-F\`l6$-Fcx6$F]xFhs-Fcx6$F\rFhs>F_\l-Fffp6$7#-FSFdilFifs>F`
\l-Fht6$F[[t-FSFcbl@$0-FS6$FYF`\l-FS6$FYF]xC$-F\y6#%7Template~is~incompleteG>6&
FEFeyF]xF`\l-Fa`s6'-F\`l6$-Fcx6$F`\lFhsFcjsFjoF[rFEF\r6%FE-F`jp6%FeyF]xF`\lF`\l
F,F,F,6#FcsF,,
I-adjustParamst+6'F[w'F[hsFbenFg`s'FcoFhsF[t63FigpF_aq%#H1G%#LmG%%colsGFdfrFf`s
F^^qFewFcfr%#smG%#rmG%#npG%#ssG%$prmGFdiqFgfn6"F,C3>F/F]p>FE-FS6$F[^sFjo>F\zFjo
>Fey-Fh^l6$-Fep6%&FjoF]isFEF\rF`is>F]x7#-Fh^l6$-Fh\s6$f*FazF,6$F]qF^qF,-%+membe
rtypeG6$Fao-Fcx6$&&F[\l6#,&FdipFc_nFhyFY6$FasF4FinF,F,6$F]]tFey7#-Fegn6#;FY-FS6
$7$FYFc_n&FeyF`_tF`is>F^\l6$7#-Fh^l6$&F[`t6$FasFf^rF`is7#-Fh^l6$&&Fey6#,$FdipFc
_n6#Ff^rF`is>Fgel7#-Fh^l6$-FG6$f*F^[lF,6$F]qF^qF,-Fj_s6$-FI6#*&&FeqFj]rFYF4FYFf
qF,F,6&F*F4FcoF\r&F`\lFj]rF`is>F`x-Fcx6$-FG6$FS-FG6%-Fj_r6$FSFcxFgelFhsFhs>Ffdl
-Fcx6$-F\`l6$F`x-Fcx6$F[rFhsFin>Fgel-F]wF_eo>Fhhl-FG6$f*6#FcfrF,6$F]qF^qF,-F^z6
$f*F[ipF,6$F]qF^qF,-F^am6$FeqFg[oF,F,6&FcfrF4F_]tF[\l<#-Fegn6#;FY-FS6$FYF[\lF,F
,6$F_]tFgelFfdl>Fbcl7#-Fh^l6$-%"+G6#-Fh^l6$-F^p6#-F^z6%%$hasGFhhl&&FhhlFj]rF[ip
/F_al;FY-F^p6#F`et/Fdip;FY-F^p6#Fhhl>Feblf*6&F_alFdipF`]tFa]tF,6$F]qF^qF,52-F^p
6#&F[rFio-F^p6#&F[rF_p3/FbftF_ft2&F\rFio&F\rF_pF,F,F,>82-Figl6$7#-Fegn6#;FY-F^p
Fddpf*FcipF,6$F]qF^qF,-Fcfl6&F4FjoF[\lFhzF,F,6(F`]tFhhlFa]tFbclFb]tFebl>Ffdl&Ff
dl6#F[gt?&FablFfdlFapC+>Fey-Fh^l6$-Fep6%&F\zF]isFEF\rF`is>F^\l6$7#-Fh^l6$F[`tF`
is7#-Fh^l6$Fg`tF`is@$/-F^p6#-FVFdilF\uF\ds>Fgel7#-Fh^l6$-FG6$f*F^[lF,6$F]qF^qF,
FcatF,F,FiatFjatF`is>Fhhl-FG6$f*FazF,6$F]qF^qF,<#-&Fi[q6#%*SearchAllG6$FY-FG6$f
*6#F`hlF,6$F]qF^qF,-F^p6#-Fi_l6$F4<#F[\lF,F,6$FcfrF[\lF4F,F,6$FcfrFablFgel>83<#
-Fh^l6$-FS6#-FG6$f*Ff[lF,6$F]qF^qF,-FS6#-Fcx6$&&F[\lFj]rFb_tFhsF,F,6$FdfrF_\lF`
etF`is>84-Fj^r6$F`[uFfu@$/-F^p6#<#Fb\uF\u\>F\z-F[dm6$-FG6%Fi_rF\zFb\uFfu-Fggs6&
F\zF4F\rF[rF,F,F,6#FgvF,,
I4isActionMatrixFoundt+6('FbbnFbenFcjp'F[aqFinF\^q'F_aqFaoF[t6'%#tMG%#T1GFjsF[q
%"rG6"F,C'>F\zFbbl>Fey,&F\zFYFfuFhy>F/-F[dm6$-%*GaussjordG6$Fjo.F]xFc\l>FE-F[dm
6$-Fht6$,$&F/6$;,(F]xFYFfuFhyFYFYF]x;,$F\zFhyFhyFhy-Fben6%FeyF\z<#-Fh^l6$/6$,(F
eyFYFg[lFhyFYFY-Fh[q6$&F[r6#,$Fg[lFhyF\rFY/Fg[lFg`rFc\l-&Fer6#%&EqualGFeelF,F,F
,6#FjbnF,,
I/SchurReductiont+6(Fcjp'F`^pF]wF\ho'%#nEGF\tF_oF]ho66%#rgG%$crgGF[q%#M1G%#bsG%
#M2G%$tM2GF\^u%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GF]aq%#B3G%#B4G%$iB1G%&rperm
G%&cpermG6"F,C6@$/-F^p6#Fc\lF\uO6'F4FjoF\uFgjlFgjl>F/7#-Fh^l6$-FS6#7#-Fegn6#;,&
-Fefl6$-FS6$FY&F[rF[ip/F_al;FY,&F_[rFYFhyFYFYFYFY-Fefl6$Fecu/F_al;FYF_[r-Fb_l6$
F_[rFc\l>F\zFay>FE7#-FS6#-F\`l6$<#-Fegn6#;FYF^is<#-FSF=>Fey-Fht6$&F46$F/Fas&F46
$FEFas>F_\l&Fey6$Fbim;FYF\r>F`\l-F[dm6$-Ff^u6$)F_\lFhen.F`xFfu>Fhhl-FG6$f*F[ipF
,6$F]qF^qF,-Fh[q6$FY-Fcx6$F\apFinF,F,6$FdauF`\l<#-Fegn6#F_hq>Fbcl-Fcx6$-F\`l6$<
#-Fegn6#;FY-FS6$Fj_tF`\lFhhlFin>86-Fcx6$7%-FSFhet-FSFjil-Fegn6#;Ffgm-FS6$F[^sFe
yFin>Figu&7$F]euFail6#Figu>Ffdl-Fht6%&Fey6$7#F]huFas&Fey6$7#F^huFas&Fey6$;FfgmF
hyFas>Fabl-F[dm6$-Ff^u6$&FfdlFgeuF_fuFfu>Fhhl-FG6$f*F[ipF,6$F]qF^qF,FefuF,F,6$F
fauFablFjfu>Fbcl-Fcx6$-F\`l6$<#-Fegn6#;FY-FS6$Fj_tFablFhhlFin>877%F]huF^hu-Fegn
6#;Fe`o-FS6$Fj_tFfdl>Fgel-%$<|gr>G6%&Ffdl6$FasF]iu&Ffdl6$FasF`iu&Ffdl6$Fas;Fe`o
Fhy>6&FeblF[gtF`[uFb\u6&&Fgel6$F_hqF_hq&Fgel6$F_hq;,&F`xFYFYFYFhy&Fgel6$Fe\vF_h
q&Fgel6$Fe\vFe\v>85-F\gq6$FfuFebl6'-F[dm6$,&Fb\uFY-F_ep6%F`[uF\]vF[gtFhyFfu&Fjo
6#7$F^hu-Fegn6#;Fe`oF\[qF`xFiguF\[vF,F,F,6#FjbnF,,
I0LinDepReductiont+6$FcjpF[t6)F\^uFj]uFaau%$tM1GFhau%&r2delG%&c2delG6"F,C*>FE-F
[dm6$-Ff^u6$)F4FhenF^ipFjo>F]x-FG6$f*F[ipF,6$F]qF^qF,FefuF,F,6$Fj]uFE<#-Fegn6#F
_\q>F_\l-Fcx6$-F\`l6$<#-Fegn6#;FY-FS6$Fj_tFEF]xFin>F\z&F46$-Fh\s6$f*F[ipF,6$F]q
F^qF,-F_r6#-Fb_l6$F4F[\lF,F,6$Fa^vF_\l7#FiduFas>Fey-F[dm6$-Ff^u6$F\zF^ipFjo>F]x
-FG6$f*F[ipF,6$F]qF^qF,FefuF,F,6$F`^vFeyFa_v>F`\l-Fcx6$-F\`l6$<#-Fegn6#;FY-Fgcl
F]hlF]xFin6%&F\z6$Fas-Fh\s6$f*F[ipF,6$F]qF^qF,Ff`vF,F,6$Fb^vF`\l7#-Fegn6#;FY-FS
6$Fj_tF\zF_\lF`\lF,F,F,6#Fc_nF,,
I)rectTordt+6&F[wF`w'%#TsGFinF[t6(Figp%#dgGF^al%#nnG%$GBsGFjjm6"F,C+>F/F]p>FE7#
-Fh^l6$*&-Fefl6#-FG6%FfzF4FfwFYF/Fhy-Fb_l6$FfwFjo>F\z-FG6$f*6#FgwF,6$F]qF^qF,*$
F4FhyF,F,F,FE>Fey-Fjhr6#-FS6#-FG6$%&denomGF\z>F\z*&FeyFYF\zFY>F]x-FG6$f*FazF,6$
F]qF^qF,-Fj^m6%FeqF4/FhqFfqF,F,6&F*F4F`oF\rF[r>F_\l7#-FS6#<#-Fh^l6$&-F\fn6$&F]x
F[ip-Fheo6$F[gvFgcuF]r/F_al;FYFiap>F_\l-FG6$f*FchnF,6$F]qF^qF,-Fijn6%f*F_hlF,6$
F]qF^qF,F^[oF,F,F,F4F[\lF,F,6$F^alF\zF_\l-FG6$f*FazF,6$F]qF^qF,-FednFgzF,F,6$Fc
oFjoF_\lF,F,F,6#FcsF,,
I,filterBasest+6&F[w'FbjlFin'%%nQBsGFao'%#ffGFdgo6&%#mFG%#BsGFc]t%"NG6"F,C(>Fey
-F^cl6#*&F\rFYF[rFY>F/-Fcx6$&-Fep6%F4F]pF_gnF_]oFhs>FE-FG6$f*FazF,6$F]qF^qF,-F^
p6#-Fi_l6$-Fcx6$F4FhsF[\lF,F,6$FjhvF/Fjo>F\z-Figl6%FE%">G/%'outputG%,permutatio
nG-F\y6#-F16$Fey%>~quotient~space~bases~removedG7#-FS6$;FY,&F[rFYFeyFhyF\zF,F,F
,6#FcsF,,
I-filterBases2t+6*FhgpFego%$CMsGFhcvFdcvFbjlF_oFghv69Fh`qF]oFf]lFacnFfhvFjsF_al
%#vBG%#tBG%#mpGFhgoF[aqFbbnF[oF]arF[hs%$cHsGF[q%$avoG%#msG%#moGFc]tF\iv6"F,C+>F
]xFfbl>F_\l-F^p6#&Fc\lF]r>F\[vFgjl>88"(+++">8:-F^cl6#*&Fb[pFYF]xFY?(F`\lFYFYF]x
FapC(>6&F/FEF\zFey6&&F\rFfbo&FfuFfbo&Fc\lFfbo&F[rFfbo@$0F_jsF_\lFj\u>6%F`xFfdlF
abl6%-F]wF_[m-Fc_p6#-Ffcp6$F\zFhcpF]]w?&FgelFjoFapC*>Fhhl-FG6$f*6#FagoF,6$F]qF^
qF,*&F4FYF[\lFYF,F,6$FhgoFgelF\z>Fbcl-F_cp6(FgelF\zFfdlF/FE/FhqFiy>Febl,&-F]wFh
etFY-F_ep6$FbclF`xFhy>F[gt-Fben6#7#-Fh^l6$-Fh_q6&&FeblFf[lF/FEFiy/Fg[lFjen>F`[u
-F[dm6$-FG6$FI-F_ep6$F[gtFeyFiy>Fb\u7#-Fh^l6$-Fefl6#&F`[u6$FasFg[l/Fg[l;FYF4>F
\]v-Fefl6$-Fiu6%-Fc^l6$%"cGFfdt-F^p6#F[bwFY-Fb_l6$F[bwFb\u@$2F\]vFablC$>FablF\]
v>FiguFgel@$2FablF\]wC$>F\]wFabl-F\y6#-F]bm6%Q>Smaller~template~found:~%d,%aF,F
\]wFigu>F\[v7$-FS6#F\[vFabl>89-Figl6%F\[v%"<GFijv-F\y6#-F16$F_]wF`[w7#-FS6$;FY,
&F]xFYF_]wFhyFccwF,F,F,6#"")F,,
I(iniProbt+6&F%F_hoFghv'%#pnGFao60F*%#vFGF`oFcoFhcvFdcv%#GCGFbjlFj[wF]oFacnF[oF
`csFfhv6"F,C,>F\zF\r>6$F/FeyFb^m>6$FEFey6$-F]wF=<#Fcfo>Fabl-Fe^m6#Fcfo-F\y6#-F1
6%%;The~problem~is~defined~by~GFay%-~polynomialsG>Fhhl-Fj^m6%F/Fabl/FhqF\z@$0-&
Faq6#%1HilbertDimensionG6$FhhlF`fwF\uYQZThe~problem~is~expected~to~have~infinit
ely~many~solutionsF,-F\y6#-F16(%,Variables:~G7#Fcfo%,;~degrees:~G-FG6$FfzF/%8;~
number~of~solutions:~G-F^p6#&-Fb_mF_\rF]r@%FjoC(>6%F\zF_\lFfdl-F^`nF_p>FeblFbgt
>F]x7#-Fh^l6$-F[dm6$-FG6$FI-Fcx6$-F_ep6$&FfdlF[ipFEFinF\z/F_al;FYFebl>F`x7#-Fh^
l6$&-Fb_m6$F[gv&F_\lF[ipF]rF[iw>Fbcl-Fg[w6*FayFeyFfdlF]xF_\lF`xF\zF[r>6&FfdlF]x
F_\lF`x6&7#-Fh^l6$Fjhw-Fb_l6$F_alFbcl7#-Fh^l6$F[gvF^jw7#-Fh^l6$FdiwF^jw7#-Fh^l6
$&F`xF[ipF^jwC(>F`xF^`m>6$FeblFabl6$F\fsFeew>F`\l-Fj^m6&F/FablF`fw/Fjjv%)extend
edG>6$FhhlFgel6$&F`\lF]r-Fben6#&F`\lF_]o>Fbcl-Fahv6&F/F`xFeblF[r>Fiiw6&7#-Fh^l6
$FgelF^jw7#-Fh^l6$FhhlF^jw7#-Fh^l6$FablF^jwFfjwO6)F\zF/FeyF]xF_\lF`xFfdlF,F,F,6
#FcsF,,
I/TemplateFindert+6(F%>'%,action_varsG-Fin6#<$%'negintGFaoFgjl>'Fhau%'symbolGF`
ho>'%,filter_fracGFdgoF\u>Fa]mFc]m>'%+schur_polsGFb]xFgjl6HF`oF*FcoFhcvFdcvFbjl
Fj[w%&avarsGF]alFjsFfhvF\ivF_alFdipFh`qF]oFjgoFacn%&tord1GFhgoF[aqFf]lF^aqFbbnF
[oF]arF_aqF[hsF\hoFhnF`^p%#flGF[qF\emFcgoFb\w%#noG%$spoG6"F,C+>F/Fj]m>8GF]]w>8I
Fhy>6)F/FEF\zFeyF]xF_\lF`\l-Fbdw6&F4-%&evalbG6#/F[rF`hoF\rF/>F`x-Fiu6%/F^xF\uF
\z-FG6$f*6#F\alF,6$F]qF^qF,F\apF,F,6$FcoF\zFjo>6%FfdlFablFgel6%F\fs-F^p6#FjhlFc
il>Fhhl,$*&FgelFhyFfdlFhyFcdl?(FbclFYFYFgelFapC%>6&F[gtF`[uFb\uF\]v6&&FeyFjil&F
]xFjilFiil&F`\lFjil>Figu-FS6$FYF`[u?(FeblFYFYFfdlFapC.>F\[v&F`x6#Febl>6(F\]wFcc
wF_]w8;8<8=-Fd`q6'F\[vF[gtF`[uF/Fb\u>8>-F^p6#Fjax>8?-Fiu6%/F[r%%nstdG-F]iq6&FEF
jaxF\zF/-Fi`r6(FEFjaxF[bxF\]vF\zF/>6%8@8A8B-Ff\t6'FEFcbxF_]wF\zF/>F_cx&-Fh`u6(F
_cxF`cxF^cx,(-FS6$Fj_tF_cxFYFablFhyF_bxFhyF/Fc\lF]r>F_cx&-F\^v6$F_cxF/F]r>8C-Fc
]u6(FiaxF_cxF\]wFccwF_bxF/>6$8D8E-FS6$FYF_cx>8F-Fa\q6#F_cx@&3F_dx52FddxFj^x3/Fd
dxFj^x2F\_xFidxC%>6%Fj^x8HF\_x6%FddxFedxFidx-F\y6#-F]bm6(QTSmaller~or~sparser~t
emplate~found:~[%d,%d],%a,%a,%aF,FddxFedx-Fcdp6$FidxFb`lF\[v-Fiu6%FfbxFbclFigu-
F]go6-F47$FddxFedx-Fcdp6$FidxFgvF/F\zF\[vF`[uFccwF^cxFc\lFa_x4F_dxY6&Q@Invalid~
action~matrix,~%1,%2,%3F,FbclF\[vF`[u-F\y6#-F]bm6*Q6%d%s,[%d,%d],%a,%a,%aF,-F^c
l6#*&,&*&,&FbclFYFhyFYFYFfdlFYFYFeblFYFYFhhlFYQ"%F,FddxFedxF]fxF\[vF_fx-F\y6#-F
]bm6&Q:Best~template:~[%d,%d],%aF,Fj^xFfex-Fcdp6$F\_xFb`lF,F,F,6#FYF,,
I$rnd,$f*F,F,6"F,,&-f*F,F,6#/%(builtinG%4RandNumberInterfaceGF,F,F,F,F,6%Fjbn"%
,?Ff[pFYFebpFYF,F,6$%6_thismoduledefinitionGF,F\blF,,
I'rndMatf*6$'F[qFao'F\emFaoF,6$F]qF^qF,-Fben6%F4Fjof*F_hlF,6$F]qF^qF,-Fh`lF,F,F
,F,F,F,F,F,,
I'rndVecf*6#F`ixF,6$F]qF^qF,-F]w6$F4f*FazF,6$F]qF^qF,FgixF,F,F,F,F,F,F,,
I&crossf*6#'F__lF]wF,6$F]qF^qF,-Fht6%-Fe[v6%F\u,$&F46#Fb`lFhyFbhr-Fe[v6%FjjxF\u
,$FahrFhy-Fe[v6%,$FbhrFhyFahrF\uF,F,F,F,,
I-readTemplatet+Fi[p6LFchoFdhoF`oFcoFhgoF]oF\hoF_^xF*F]ar%#U0G%&tord0G%"UGFh`qF
[aqFjauFf]lF\aqF]aqF_wF^aqFbbnF[oFdoFjs%#nRGFaauF`^pFejpF\^uF^buF_buFhnF`^v%#t1
GFa^vFb^vFewFago%#xEG%#xVGF[\p6"F,CE>6,F/FEF\zFeyF]xF_\lFb\uF`\lF`x8M-Fg[pFgcr>
Ffdl&Fb^mF]r>Fbco-Fep6%FfdlFbgtFey>FhhlFeew>Fbcl-Fffp6$FgelFhhl>Fabl-F`jp6%Fabl
FgelFbcl>Febl-Fj^m6%FfdlF_\lF`fw>F`[u&-Fb_m6$FeblF_\lF]r>Fb\u-Fcx6$Fb\uFhs>F[gt
-FG6$f*FazF,6$F]qF^qF,F^_wF,F,6$FhgoF]xFb\u>F\]v-Fffp6$-Fcx6$-F\`l6$F[gtFb\uFin
F_\l>6$FjaxF[bx6$-F^p6#Fb\u-F^p6#F\]v>Figu-FG6$f*FazF,6$F]qF^qF,*&F4FYF[\lFhyF,
F,F]^y-Fi_lFd^y>F\[v-%&getB0G6$FiguFey>Figu7$-FS6#-Fffp6$-Fcx6$-F\`l6$FiguF\[vF
inF_\l-FS6#-Fffp6$-Fcx6$F\[vFinF_\l>Fb\u7$-FS6#-Fffp6$-Fcx6$-F\`l6$Fb\u-Fcx6$Fi
guFhsFinF_\l-FSFghu>6$F\]wF[gt6$7$-FSF[_y-FSFi^y-FG6$f*FazF,6$F]qF^qF,F^_wF,F,F
]^yFb\u>Fccw-F_cp6(F]xF`[u-Fc_p6#-Ffcp6$F`[u7#-Fegn6#;FY-F^p6#F`[uFeblF_\lF`fw>
Fiax-Fi]q6'Fb\uF`[uFeblF_\lF\z>Fccw-F[dm6$-F_ep6%FiaxFccw-F\gq6$F\zFiaxF\z>F_]w
-Fcx6$,&-F]wF[_yFY-F_ep6$&Fccw6$;FYF[bxFas-F]wFi^yFhyFin>6$F_bxF^cx&-Fggs6&F`\l
FfdlFeyF\]w6#;Fc_nFb`l>6'F_bxFcbxF_cxF`cxF_dx-Fh`u6(F_bxF^cxF`\l,(-FS6$Fj_tF_bx
FYFjaxFhyF[bxFhyF\zF`x>6%FddxFj^xFfex-F\^v6$F_bxF\z-F\y6#-F16$%6Action~matrix~f
ound:~G-Fc]u6(FccwFddxF[gtFb\uF[bxF\z>8J7#-FS6$FYFddx-F\y6#-F16$%2Template's~si
ze:~GFjey@$50&F/F]r&FjeyF]r0&F/F_]o&FjeyF_]oYQ/Wrong~templateF,>8L-F\`l6$-Fcx6$
F^cxFhs-Fcx6$FcbxFhs>Fcbx&Fcbx6#-Fh\s6$f*F[ipF,6$F]qF^qF,Ff`vF,F,6$Fb^vFfex7#-F
egn6#;FY-FS6$FYFcbx>Fedx-F[dm6$-Ff^u6#&F_bx6$-Fh\s6$f*F[ipF,6$F]qF^qF,Ff`vF,F,6
$Fa^vFj^x7#-Fegn6#;FY-FS6$F[^sF_bxFasF\z>Fidx-FG6$f*FazF,6$F]qF^qF,-FS6#-F^z6$f
*FfjtF,6$F]qF^qF,0&F[\l6$F4FfqF\uF,F,6&F`^vF[\lFbzF4<#-Fegn6#;FY-FS6$F[^sF[\lF,
F,6$F`^vFedx<#-FS6#Ffex>8K-Fdel6$-Fcx6$F`\yFhs-Fcx6$&Fcbx6#7#-FS6#FidxFhs>F\_x-
Fffp6$-Fcx6$-F\`l6$Fcgy-Fcx6$F\]wFhsFinFhhl64FeyF]xFablFbclF\_xF\]wFb\uF[gtF`\l
Fj^xFfexFjeyF[bxF_[zF_cxF`cxF_dxF^gyF,F,F,6#Fc_nF,,
I&getB0t+6$'%"PGFhsFego6'F]alF_al%$VrsG%$vrsGF_w6"F,C$>F/F^x?(FEF\uFY,&F/FYFhyF
YFapC$>F\z-&%)combinatG6#%'chooseG6$Fjo,&F/FYFEFhy?&FeyF\zFapC$>F]x-F^z6$f*FjpF
,6$F]qF^qF,-Fcx6$-FG6$f*6#FfwF,6$F]qF^qF,-F^am6$Fi[lFfqF,F,6&F[qF4Fj\zFfqF[\l%$
andGF,F,6&F]]zFeyFj\zF4F4@%0FiapF\uO-Fcx6$-FG6$f*Fh^zF,6$F]qF^qF,*&F4FY&F[\lF]r
FYF,F,6$F_wF]x7$FcfoFYFhs>F]xF^blF,F,F,6#Fc_nF,,
I*iniColpivt+6&F[au'Fj[yFhsFggoF`w6*%#VlGFj\zF_w%#aPGF\aq%#RPGFewF]o6"F,C0>F`x-
Fe^m6#F_[t>F/-Fcx6$-F\`l6$FbjvFjoFin>FE-Fcx6$-F^z6$f*FjpF,6$F]qF^qF,-F^am6$Fi[l
FhzF,F,6&FhgoF[rFc`zF/F/Fhs>F\z-Fe_y6$FEF\r>Fey-FG6$f*FjpF,6$F]qF^qF,Fi[lF,F,6$
FhgoF[rFE>F]x-Fffp6$-Fcx6$F]elFinF`x>FE7$-FS6#-Fffp6$-Fcx6$-F\`lFa^mFinF`x-FS6#
-Fffp6$-Fcx6$F\zFinF`x-F\y6#%?List~of~permissible~monomials:G-F\yFW-F\y6#-F16$%
BNumber~of~permissible~monomials:~GF]]l>Fey-FG6$f*FjpF,6$F]qF^qF,-Fh[q6$Fi[l7$-
FSF^cs-FS6#FcflF,F,6(FhgoF[rFj\zFEF\aqF]xFE>F_\l7$F\hlFail>F`\l-Fffp6$-Fcx6$-Fd
el6$-F\`l6$-Fcx6$F/Fhs-Fcx6$F_\lFhsFjoFinF`x6'-Fht6$-FSFfboF[[tFEFeyFiap-F^pFfb
oF,F,F,6#FcsF,,
I,alter_commaf*6#'F__lFinF,6$F]qF^qF,-F16%Fhfm-FS6#-&Fi[q6#%+InterleaveG6$F47#-
Fegn6$Q",F,,&F]pFYFhyFYF`\nF,F,F,F,,
I-write_solvert+6/'%$dirGF'Fcho%&vars0GFhgo%#iMG%#eMGFf]lF[aqFagoF]auFh[yF\^uF`
ho6)%&vars1G%#vvGFf]m%$nv0GFjsF_al%#fbG6"F,C>>FeyFfbl>F]x-F^p6#Fiy>F`\lQ%~~~~F,
>F/-Fcx6$-F\`l6$Fibt<#F\rFin>FE7#-Fh^l6$-Fh[q6$*&&F/FdilFY&Fiy6#FhyFYFiy/F_\l;F
Y,&FeyFYFhyFY>F\z-Fa`m6$-F16+F4Q"/F,-Fiu6%90Q%std_F,Q&nstd_F,,&&Fc[pF]rFY9/FhyQ
"xF,,&&Fc[pF_]oFYFijzFhyQ"_F,F&F5Fgcm-Feam6$F\z-F16'QH%%~Input:~coefficient~mat
rix~C~of~size~F,F`joFjjz&FjoF_]oQ#|+|+F,-Feam6$F\z-F16,Q*function~F,-FafzFatQ$~
=~F,FbjzFgjzFjjzF[[[lF][[lF&Q&(C)|+|+F,-Feam6$F\z-F16&F`\lQ(i_dx~=~F,-Fafz6#-FG
6$f*F[ipF,6$F]qF^qF,FahrF,F,F,FfuQ#;|+F,-Feam6$F\z-F16&F`\lQ(j_dx~=~F,-Fafz6#-F
G6$f*F[ipF,6$F]qF^qF,FbhrF,F,F,FfuFh\[l-Feam6$F\z-F16&F`\lQ(C_dx~=~F,-FafzFebuF
h\[l-Feam6$F\z-F16(F`\lQ>M~=~sparse(i_dx,j_dx,C(C_dx),F,FhjzFbgzF\[[lQ$);|+F,@$
0FijzF\u-Feam6$F\z-F165Q"|+F,F`\lQ'M~=~M(F,,&FijzFYFYFYQ&:end,F,Fh^[lQ*:end)-(M
(F,Fh^[lQ(:end,1:F,FijzQ')/M(1:F,FijzQ$,1:F,FijzQ())*M(1:F,FijzFbgzFh^[lQF:end)
;~%%~Schur~complement~reduction|+F,-Feam6$F\z-F16'Ff^[lF`\lQ5[L,|ir,Pi]~=~lu(M(
:,1:F,Fd[pQ%));|+F,-Feam6$F\z-F16$F`\lQ+Pi~=~Pi';|+F,-Feam6$F\z-F16(F`\lQ0M~=~[
Pi*L~Pi(:,F,,&Fd[pFYFYFYQ,:end)]\M(:,F,F``[lQ(:end);|+F,-Feam6$F\z-F16&F`\lQ+M~
=~M(end-F,,&FjhoFYFhyFYQ*:end,:);|+F,-Feam6$F\z-F16'Ff^[lF`\lQ+T~=~zeros(F,F]xF
_^[l-Feam6$F\z-F16*F`\lQ%T(1:F,FjhoQ.,:)~=~-M(:,1:F,FjhoQ')\M(:,F,,&FjhoFYFYFYF
b`[l@&/,&F]xFYFjhoFhyFY-Feam6$F\z-F16&F`\lQ#T(F,*&F]xFY-Fh[q6$&Fb[pFhizFiyFYQ()
~=~1;|+F,2FYFia[l-Feam6$F\z-F16&F`\lF^b[l-Fafz6#7#-Fh^l6$,&*&F]xFY,&-Fh[q6$&Fb[
p6#,(F_\lFYF]xFhyFhyFYFiyFYFhyFYFYFYF_\lFY/F_\l;Ffa[lF]xFcb[l-Feam6$F\z-F16%Ff^
[lF`\lQ1[V,D]~=~eig(T);|+F,@%/F]]lFY-Feam6$F\z-F16(F`\lQ*sol~=~[V(F,&FEF]rQ(,:)
./V(F,F]xQ3,:);~diag(D).'];|+|+F,-Feam6$F\z-F16*F`\lFcd[l-FafzFWQ/,:)./repmat(V
(F,F]xQ%,:),F,F[jzQ3,1);~diag(D).'];|+|+F,-Feam6$F\z-F16$F`\lQXI~=~find(not(isn
an(sol(1,:)))~&~not(isinf(sol(1,:))));|+F,-Feam6$F\z-F16$F`\lQdo%%I~=~I(not(ima
g(sol(1,:))));~%%~uncomment~this~line~for~real~roots~only|+F,?(F_\lFYFYF[jzFap-
Feam6$F\z-F16'F`\lFfizQ(~=~sol(F,F_\lQ&,I);|+F,-Feam6$F\z-F16'F`\lF\rF^f[lFeyQ'
,I);|+|+F,-Feam6$F\zQ$endF,-FfbmF_[mF,F,F,6#"#8F,,
I4write_solver_colpivt+60FggzFchoFigzFhgoFjgzF[hzFj\zFd`zFagoF]auFh[yFjsF\^uF`h
o6)F]hzF^hzFf]mF_hz%#nPGF_alF`hz6"F,CB>FeyFfbl>F]xFehz>F`\lFhhz>F/Fjhz>FE7#-Fh^
l6$-Fh[q6$Feiz&Fiy6#;,$FijzFhyFhyFiiz>F\z-Fa`m6$-F16+F4Fajz-Fiu6%91FejzFfjz,&Fh
jzFYFdjzFhyFjjz,&F\[[lFYFdjzFhyQ)_colpiv_F,F&F5FgcmF^[[l-Feam6$F\z-F16,Fi[[lFj[
[lF[\[lFeh[lFhh[lFjjzFih[lFjh[lF&F\\[l-Feam6$F\z-F16&F`\lFa\[l-Fafz6#-FG6$f*F[i
pF,6$F]qF^qF,FahrF,F,F,FfuFh\[l-Feam6$F\z-F16&F`\lF]][l-Fafz6#-FG6$f*F[ipF,6$F]
qF^qF,FbhrF,F,F,FfuFh\[lFd][lFj][l@$0FdjzF\u-Feam6$F\z-F165Ff^[lF`\lFg^[l,&Fdjz
FYFYFYFi^[lFij[lFj^[lFij[lF[_[lFdjzF\_[lFdjzF]_[lFdjzF^_[lFdjzFbgzFij[lF__[l@%0
Fd[pF\uC&F`_[lFf_[lF[`[l-Feam6$F\z-F16&F`\lQ,M~=~full(M(F,F``[lQ+:end,:));|+F,-
Feam6$F\z-F16$F`\lQ.M~=~full(M);|+F,@$0FjhoF\uC%-Feam6$F\z-F16'Ff^[lF`\lQ6[L,UR
,Pi]~=~lu(M(:,1:F,FjhoFe_[lFf_[l-Feam6$F\z-F16(F`\lF_`[lFfa[lFa`[lFfa[lFb`[l-Fe
am6$F\z-F16&F`\lQ*MP~=~M(1:F,FjhoQ&,:);|+F,-Feam6$F\z-F16&F`\lQ(NP~=~M(F,Ffa[lQ
+:end,:);|+|+F,-Feam6$F\z-F16&F`\lQ:[Q,U,Pi]~=~qr(NP(:,1:end-F,Fg\lFe_[l-Feam6$
F\z-F16(F`\lQ4A~=~UR\[MP(:,1:end-F,Fg\lQ/)*Pi~MP(:,end-F,FeyQ):end)];|+F,-Feam6
$F\z-F16*F`\lQ+B~=~U(:,1:F,,*FhjzFYFdjzFhyFd[pFhyFjhoFhyQ()\[U(:,F,,,FhjzFYFdjz
FhyFd[pFhyFjhoFhyFYFYQ3:end)~Q'*NP(:,end-F,FeyF[^\l-Feam6$F\z-F16(F`\lQ/M~=~[-A
(:,end-F,,&FijzFYFhyFYQ1:end)+A(:,1:end-F,FijzQ,)*B;~-B];|+|+F,-Feam6$F\z-F16&F
`\lQ&xP~=~F,-Fafz6#Fb[pFh\[l-Feam6$F\z-F16*F`\lQ*P1~=~[(1:F,,(F]xFYFeyFhyFhyFYQ
&)*Pi~F,,&F]xFYFeyFhyQ":F,F]xQ$];|+F,-Feam6$F\z-F16-F`\lQ-T~=~getT(M,[F,F_bnF\`
\l,&F]xFYFjhoFYQ+~P1(1:end-F,FijzQ+)],P1(end-F,Fj^\lQ&:end)F,Q',xP);|+F,Fhc[l@%
F^d[l-Feam6$F\z-F16(F`\lFcd[lFdd[lFed[lFijzFfd[l-Feam6$F\z-F16*F`\lFcd[lF[e[lF
\e[lFijzF]e[lF[jzF^e[lF_e[lFde[l?(F_\lFYFYF[jzFapFje[lF`f[lFef[lFhf[lF,F,F,6#"#
9F,,
I4write_inidata_coefst+6$F%'%)root_dirGF'6.%*proc_nameG%#_CG%&_nameG%&_sizeG%#C
sG%#ClGFhgzFf]mF_alFcfr%$idxGF`hz6"F,C6>FhhlFhhzAF0>F/-FK6#-F16$%#C_GF4>6%FEF\z
FeyF`cl>F`\l-F16%FjoFajzF4@$4-F9Ffbo-&F:6#%.MakeDirectoryGFfbo>F`x-Fa`m6$-F16&F
`\lQ*/inidata_F,F4F5Fgcm-Feam6$F`x-F16%Q9function~data~=~inidata_F,F4Q$()|+F,-F
eam6$F`x-F16&FhhlQ0data~=~cell([1,F,FcdoQ%]);|+F,?(FfdlFYFYFcdoFap-Feam6$F`x-F1
6(FhhlQ&data|frF,FfdlQ+|hr~=~randn(F,-F^fm6$-Fafz6#&FeyFddpFb_nF_^[l-Feam6$F`xF
gf[l-FfbmFhdl>F`x-Fa`m6$-F16&F`\lQ(/coefs_F,F4F5Fgcm-Feam6$F`x-F16%Q4function~C
~=~coefs_F,F4Q)(data)|+|+F,?(FfdlFYFYF_jsFap-Feam6$F`x-F16'Fhhl&F\zFddpQ)~=~dat
a|frF,FfdlQ$|hr;|+F,-Feam6$F`xFf^[l?(FfdlFYFY,$F]]l#FYFc_nFap@$/&FE6#,&FfdlFc_n
FhyFY%#cfGC%-Feam6$F`x-F16(FhhlQ+C~=~zeros(F,-FS6$F[^s&FEFhizFbgz-FS6$Fj_tF_h\l
Q%);|+|+F,>Fc\n6$-F\`l6$-Fcx6$&FE6#,$FfdlFc_nFhs<#F\u-Fcx6$Fih\lFin?&FablF]xFap
C$>Fgel7#-F_jt6$FablF_\l-Feam6$F`x-F16(FhhlQ#C(F,-Fiu6%/F^eoFY&FgelF]r-FafzF_eo
Q%)~=~F,-Fcx6$FablF'Fh\[l-Feam6$F`x-F16%Ff^[lFhhlQPC~=~C./repmat(sqrt(sum(C.^2,
2)),1,size(C,2));|+|+F,Fee\lFge\lF,F,F,6#Fc_nF,,
I/write_test_numt+6+F%FisF`goF`w'FigzFin'Fg[yF]wFhauFha\l%#cpG6+FhgzFf]mFdipF`h
z%$fb2GF^hz%$vv0G%&xvarsG%$xvvG6"F,CI>F/-F16%Fb[pFajzF4>FeyFhhz>F]x-F16$FeyFey>
F_\l-FG6$f*Fh^zF,6$F]qF^qF,-F16$F4F4F,F,F,F\r>F`\l-FG6$f*Fh^zF,6$F]qF^qF,Fa\]lF
,F,F,Ffu>F`x-Fcx6$-F\`l6$FejsFbfsFin>Ffdl-FG6$f*Fh^zF,6$F]qF^qF,Fa\]lF,F,F,F`x@
$F7-Fdc\lF=>FE-Fa`m6$-F16&F/Q+/test_num_F,F4F5Fgcm-Feam6$FEQ+rng(23);|+|+F,-Fea
m6$FEQ-N~=~10000;|+|+F,-Feam6$FE-F16'Q%Err_F,F4Q+~=~[];|+Tm_F,F4Q)~=~[];|+|+F,-
Feam6$FEQ.for~i~=~1:N|+|+F,-Feam6$FE-F16&FeyQ0data~=~inidata_F,F4QN();~%%~gener
ate~initial~data~of~the~problem|+|+F,-Feam6$FE-F16$FeyQ%try|+F,-Feam6$FE-F16$F]
xQ&tic;|+F,-Feam6$FE-F16&F]xQ+C~=~coefs_F,F4QV(data);~%%~compute~coefficients~o
f~polynomial~system|+F,-Feam6$FE-F16,F]x-FafzFfboF[\[l-Fiu6%-Fb_x6#/FiyF`hoFejz
Ffjz&F[rF]rFjjz&F[rF_]o-Fiu6%Fc[pFjh[lF][[lF4QA(C);~%%~solve~polynomial~system|
+F,@$0FbgtF\u-Feam6$FE-F16+F]x-Fiu6%/FbgtFY&FfdlF]r-FafzFddpQ6~=~arrayfun(@(j)~
get_F,-F16#-FSFhdlQ$(C,F,-F^fm6$-Fafz6#7#-Fh^l6$-F16$&F`\lF_[mQ$(j)F,/F\z;FYF_f
zFb_nQ-),~1:length(F,Fg[xFe_[l-Feam6$FE-F16$F]xQ+tm~=~toc;|+F,-Feam6$FE-F16&F]x
Q,if~isempty(F,FjhlQ2);~continue;~end|+F,-Feam6$FE-F16$FeyQ*catch~ME|+F,-Feam6$
FE-F16$F]xQ+continue;|+F,-Feam6$FE-F16$FeyQ&end|+|+F,-Feam6$FE-F16$FeyQ)M~=~[];
|+F,-Feam6$FE-F16&FeyQ0for~j=1:length(F,FjhlQ#)|+F,?(F\zFYFYFbblFap-Feam6$FE-F1
6'F]x&F\rF_[mF[\[l&F_\lF_[mQ&(j);|+F,-Feam6$FE-F16&F]xQ%m~=~F,-Fafz6#-Fcx6$Fc\l
FinFh\[l-Feam6$FE-F16$F]xQ6m~=~m/norm(m,'fro');|+F,-Feam6$FE-F16$F]xQ=M~=~[M;~n
orm(C*m.','fro')];|+F,-Feam6$FE-F16$FeyQ%end|+F,-Feam6$FE-F16$FeyQ.M~=~sort(M);
|+F,-Feam6$FE-F16&FeyQ4err~=~norm(M(1:min(F,FjoQ7,length(M))),'fro');|+|+F,-Fea
m6$FE-F16.FeyFd^]lF4Q)~=~[Err_F,F4Q(~err];|+F,FeyQ$Tm_F,F4Q(~=~[Tm_F,F4Q(~tm];|
+|+F,-Feam6$FEFfd]l-Feam6$FEQIfolder~=~fileparts(which('add_all.m'));|+F,-Feam6
$FE-F16'QCsave(strcat(folder,'\_results\Err_F,F4Q-.mat'),'Err_F,F4Q&');|+|+F,-F
eam6$FE-F16)Q3fprintf('Problem:~F,F4Qin.~Ave.~runtime:~%%0.1f~ms.~Med.~error:~%
%0.2e\n',10^3*mean(Tm_F,F4Q.),median(Err_F,F4Fe_[lFfjoF,F,F,6#FicnF,,
I0write_histo_numt+Ffa\l6%FhgzFf]mF`hz6"F,C6>F/F^c\l>F\zFhhz@$F7Fc]]l>FE-Fa`m6$
-F16&F/Q,/histo_num_F,F4F5FgcmFhh]l-Feam6$FE-F16%QDload(strcat(folder,~'\_resul
ts\Err_F,F4Q+.mat'));|+|+F,-Feam6$FEQ,bwd~=~0.3;|+F,-Feam6$FEQ-nbins~=~60;|+F,-
Feam6$FEQ9clr~=~[70~100~160]/255;|+F,-Feam6$FE-F16%Q1err~=~log10(Err_F,F4F_^[l-
Feam6$FEQLhr1~=~histogram(err,nbins,'BinWidth',bwd);|+F,-Feam6$FEQ6hr1.FaceColo
r~=~clr;|+F,-Feam6$FEQ7hr1.EdgeColor~=~clr;|+|+F,-Feam6$FEQ8axis([-17~1~0~1150]
);|+|+F,-Feam6$FEQVset(gca,'FontSize',54,'FontName','Times~New~Roman');|+F,-Fea
m6$FEQFset(gcf,'PaperPositionMode','auto');|+F,-Feam6$FEQJset(gcf,'PaperOrienta
tion','landscape');|+F,-Feam6$FEQGset(gcf,'PaperPosition',[1~1~28~19]);|+F,-Fea
m6$FE-F16%QPprint(gcf,'-dpdf',strcat(folder,'\_results\fig_F,F4Q).pdf'));F,Ffjo
F,F,F,6#Fc_nF,,
I0SolverGeneratort+6)F%>Fg]xF`ho>%'colpivGFY>%2create_coefs_fileGFY>%2create_hi
sto_fileGFY>%1create_test_fileGFY>Fga\lQ(solversF,6FFcoFhgoF]arFg[yFewF^aqFf]lF
[aqF\hoFa^vFb^vFagoFh[yFj[yF\^uF^buF_buF[\yF`^pFejpFj\zFd`z%$nR1G%$nE1GFj]lF_g[
lF]auF][]lFigz%#iCG%#eCGFhn%#MtGFjgzF[hzFhgz6"F,C9>64F/FEF\zFeyF]xF_\lF`\lF`xFf
dlFablFgelFhhlFbclFeblF[gtF`[uFb\uF\]v-Fb[y6$F4-Fb_x6#/FjoF`ho>Figu-Fht6$F\hlF[
[t>6'F\[vF\]wFccwF_]wFiax-F^`z6&FiguFeblFEF/>6%FjaxF[bxF_bx6%F_fz-F^p6#F\]wFiap
>Fcbx-Fiu6%51F[bxFjax/F[rF\uFftFap>F^cx-Fiu6%Fcbx-F^z6$f*Fh^zF,6$F]qF^qF,-F^am6
$*&F4FY&F[\lFhizFY&F[\l6#;,$FhzFhyFhyF,F,6&Fj\zF\]wFj]lFjaxF/-F^z6$f*Fh^zF,6$F]
qF^qF,-F^am6$Fca^lF[\lF,F,6$Ff]lF`\lF/-F\y6#-F16$%OVariables~that~can~not~be~ev
aluated~at~roots:~G7#-FS6#-F\`l6$FgezFagy>F_cx7#-%(indicesG6$-Fcx6$F\zFc_p%+ind
exorderG>F`cx-FG6$f*FazF,6$F]qF^qF,-Fcx6$,&FahrFY*&,&FbhrFYFhyFYFYFhjyFYFYF'F,F
,6$F]arF\zF_cx>F\z-Fben6$-FS6$FYF\z<#-FS6#-Fijn6%f*F_hlF,6$F]qF^qF,/-FSF_pFjoF,
F,F,F_cxF`cx>F_dx&-Fggs6&Ffdl-Fcx6$-F_ep6$F\zFeyFinF/F_\lF_]o@$0F[gtF\u>F_dx&F_
dx6$F`[uFb\u>F_dx&F_dx6$-Fh\s6$f*F[ipF,6$F]qF^qF,-F_r6#-Fb_l6$F4-FG6$f*FazF,6$F
]qF^qF,,&F4FYF[\lFYF,F,6$F\^uFhzF[\lF,F,6&Fa^vFablF\^uF[gt7#-Fegn6#;FY-FS6$F[^s
F_dx-Fh\s6$f*F[ipF,6$F]qF^qF,-F_r6#-Fb_l6$F4-FG6$f*FazF,6$F]qF^qF,Fhf^lF,F,Fif^
lF[\lF,F,6&Fb^vFgelF\^uF[gt7#-Fegn6#;FY-FS6$Fj_tF_dx@$Fcbx>F_dx-F`jp6%F_dx-Fcx6
$-Fht6$FhayFiguF]w-Fcx6$-Fht6$FhayF\[vF]w>Fddx-Fcx6$F_dxFc_p>6$FedxFidx6$7#-F^c
^l6$FddxFbc^l-FG6$FS7#-%(entriesGFhi^l@$4-F9Ffhz-Fdc\lFfhz>Fj^x-F16%FiyFajzF4@$
4-F96#Fj^x-Fdc\lFhj^l@%Fcbx-F[g[l60Fj^x7#Fad^lF^cxFEFedxFidxF\]wFccw7#-FS6$FYF_
dxFiaxF_]wFjaxF[gtFe_^l-Fdgz6/Fj^xF][_lF^cxFEFedxFidxF`\lF`xF^[_lF_bxFbclF[gtFe
_^l@$/F\rFY-Fda\l6$F4Fiy@$/Fc\lFY-Fhj\l6+F4FjaxFhhlF/F^cxFeyFjoFiyFcbx@$/FfuFY-
Fji]lFf[_lF,F,F,6#FYF,
