M7R0
I+isLinIndept+6&'%"MG%%listG'%"GGF''%%tordG%3ShortMonomialOrderG'%#ppG%'posintG
6$%%varsG%"SG6"6"C&>8$-%'indetsG6#9%@$/-%%nopsG6#9$"""O%%trueG>8%&-%,poly2matri
xG6%-%$mapG6$f*6#%"mGF46$%)operatorG%&arrowGF4-&%)GroebnerG6#%+NormalFormG6&FAT
$T&/%/characteristicGT(F4F46(F)F;F+9&F.9'FAF>F76#FB-%#isG6#0-&&%.LinearAlgebraG
6#%(ModularG6#%%RankG6$F[oFF-Fbo6$F[o&FF6$;FB!"#;F4F4F4F4F46#""%F4,
I*testBasist+6''F&%$setG'%$degGF/F(F*'F.%*nonnegintGF06"F4C&>F7-F96#Fjn@$2F>F;O
6$%&falseG-%$<,>G6#-Fgq6#""!>FF&-FI6%-FL6$f*FOF46$FRFSF4FTF4F46(F)FjnF+F[oF.9(F
AF>F7F\o6$-%#ifG6%0FerF[r-F^o6#/-Fbo6$FerFFF;-F^o6#/-&FdoFgo6#FFF;FFF4F4F46#""&
F4,
I*iniMonSett+6)'%"FG<%%'VectorGF'Fgp'%#B0GF''F1F'F(F*F->'%$domGF[qF[r6*%"EGF&%#
vrG%"dGFip%%flagGF2%&d_minG6"F4C*>8(-F?F:>8+F[r>F7-%(convertG6$-FL6$%#opG-&FV6#
%(SupportGF@Fgp-%&printG6#-%$catG6%%<Polynomial~system~contains~G-F?6#F7%+~mono
mialsG>FFF7?(8'F[rFBF41,&FivFBFau!""9*C&>8&-%'selectG6$f*6#%"xGF46$FRFSF41-%'de
greeG6$FAFZT%F4F46&F1FjnFhtFivFF>FF-FL6$f*6#%"tGF46$FRFSF4-Fhu6#-FL6$f*6#%"kGF4
6$FRFSF4*&FZFBFAFBF4F46$FcxFAT#F4F46$FgtF`wFF>6$8)8*-Fcp6'FFF^uF[oFer9)@$4Fcy>F
au,&FivFBFBFB-F^v6#-Fav6%%6Initial~set~contains~G-F?FesFfvO6$F7FFF4F4F46#""(F4,
I-neighborMonst+6%'%"BGFgp'%#MBGFgpFat6#%#nBG6"F4C&@$/F>F[rOF;>F7-Fbw6%%%typeG-
FL6$Fhu<#-%$seqG6$-F\\l6$<$*&%"bGFB%"vGF\w*&Fb\lFBFc\lFB-%#inG6$Fc\lFjn-Ff\l6$F
b\lFA%)monomialG>F7-%*intersectG6$-%&minusG6$F7FAF;-Fhr6%/FdvF[rF;F7F4F4F46#""$
F4,
I)genBasist+6)'FftFgpFfpF_tFatF(F*F-60%$rndGFjz%#EBGF\[lF^[l%$nB1G%#bvGF[y%"aG%
#nvG%#wtGFP%"iGFip6"F4C,>F7,$-%%randG6#;F[r"%+5#FBF\_l>FF<">FivF;>8--F?6#F[o>81
-F?F`q>Fdy7#-F\\l6$-%&roundG6#-F7F4/80;FBFb_l>Fau-&%$maxG6#%&indexG6#-FL6$f*Few
F46$FRFSF4,&FAFB*&-F_yF4FB$"$+"F[rF\wFBF4F46$F\^lF7Fdy>8,&F[o6#Fau?(F4FBFBF42Fa
zFf_lC*>Fiv-F`]l6$FivFF>F^u-Ffz6%FFFivF[o>F`w-%&unionG6$FAFF>8.f*FewF46$FRFSF4,
*-Fhr6%-Ff\lF[xFBF[rFB-Fhr6%-Ff\l6$*&F\xFBFAFBT'FBF[rFB-%$addG6$*&&T)6#T+FB-Fjw
6$FA&T.FiclFB/Fjcl;FBT/FB*&-T1F4FBFaalF\wFBF4F462FftFAF`^lFealF]^lF`wF_^lFdyFc^
lFa`lF1F[oFa^lFb_lF\^lF7>Fcy-%%sortG6$7#-Fhu6#F^uf*6$Ffw%"yGF46$FRFSF41-F_yF:-F
_yF@F4F46$Fb^lFfbl>6$8/Fa`l6$&FcyF\oFB?(F4FBFBF434-F"6&7$-FhuFesFgelFerFgyF]w2F
a`l-F?6#FcyC$>Fa`l,&Fa`lFBFBFB>Fgel&Fcy6#Fa`l>FF<$F`flFgelFFF4F4F46#FezF4,
I*saveBasest+6$'%%probG%'stringG'%$QBsG<$F'Fgp6#%#fdG6"F4C%>F7-%&fopenG6$-Fav6$
Q)bases/b_F4FA%&WRITEG-FL6$f*FewF46$FRFSF4-%(fprintfG6%F_yQ$%a|+F4FAF4F46$FgglF
7F;-%'fcloseGFevF4F4F46#""#F4,
I*readBasest+6#F`gl6%%#stGFdgl%*nongbfileG6"F4C'>F7FB>FF7">F`wF^hl?(F4FBFBF40F7
F[rC$>F7-%)readlineG6#F`w@$F\jl>FF7$F`fl-%&parseGFevFFF4F4F46#FBF4,
I,BasisFindert+6&F`gl>'%-deg_over_minGF[qF[r>'%1numbers_of_basesGF/Fbal>'%-prim
e_numberGF/"&\F$6/F\tF1F+F)F`tFhtFftF&%#BBGFjz%#fnGFgglF.6"F4C2>FauFiil>FealFii
l>FfblF^hl>Fa`lF[oA-Fav6%Q,problems/F_F4FAQ#.mF4>F7-%%evalG6#-Fav6$%#F_GFA>FF7#
-Fhu6#-F9Fev>F`w-%%tdegG6#F`fl>Fiv-&FV6#%&BasisG6%F7F`w/FgnFa`l>F^u&-&FV6#%*Nor
malSetG6$FivF`wF\o>6$FdyFau-Fhs6)F7F^uFFFivF`wFa`lF;>Fgel-F\hl6$FfblFahl-F\il6#
Fgel>Fgel-F\hl6$Ffbl%'APPENDG?(F4FBFBF42-F?6#FealFjnC$>Fb_l-Fg]l6)FdyFauF^uFFFi
vF`wFa`l@$4-%'memberG6$Fb_lFealC%>Feal7$-FhuFa_mFb_l-Fghl6%FgelFihl-Fdu6$Fb_lF'
-F^v6#-%(sprintfG6%Q%%d%sF4-F]`l6#,$*&F`_mFBFjnF\wFbalQ,%~completedF4Fh^mF4F4F4
6#FBF4,
I*writeGfant+6$F`gl>Fb[mFd[m6$F\tFggl6"F4C(>FF-F\hl6$Q)gfan/igfF4FahlAF_\m>F7Fd
\m>F7-%$modG6$-FL6$%'expandG-Fdu6$F7FgpF;-Fghl6'FFQ+Z/%aZ%a|+%aF4F;F[]mF7-F\ilF
esF4F4F46#FBF4,
I)readGfant+6#'%)gfanfileGFbgl6&FitFcil%"nGF.6"F4C)>F7Feq>FFFB>F`wF[r>FF-F`jlF@
>Fiv-Ffjl6#-%*substringG6$FF;Ff]l,&-&%,StringToolsG6#%.FirstFromLeftG6$Q"[F4FFF
BF_pFB?(F4FBFBF40FFF[rC$>FFFgcm@(5/FFQ#|fr|frF4/FFQ"|frF4C%>F7FD>F`w,&F`wFBFBFB
>(F)F`wFiil3F70-F\dm6$FFF\wQ"|hrF4>Ffem7$-Fhu6#Ffem-F\dm6$FFF^p3F7/FiemF[fmC$>F
femF]fm>F7FeqO6%Fiv7#-F\\l6$-FL6$Ffjl(F)Fc^l/Fc^l;FBF`w7#-F\\l6$-FL6$f*FewF46$F
RFSF4-Ffjl6#-F\dm6$FA;FB,&-Fadm6$Q"+F4FAFBF\wFBF4F4F4F^gmF_gmF4F4F46#FBF4,
I(writeCMt+6&F`gl'%$Ws0GF''F[yF/F-6&FgglF\tF1%#WsG6"F4C5>F7-F\hl6$-Fav6$Q(cm/ic
m_F4FjnFahlAF_\m>FFFd\m>F`w-Fdu6$7#-Fhu6#-F9FesFbgl>Fiv-&Fbdm6#%.SubstituteAllG
6%-F]jm6%-Fdu6$F;FbglFfdmQ"(F4Q"]F4Q")F4>FF-Fdu6$-F^bm6$-FL6$FbbmFFF[oFbgl-Fghl
6'F7Q<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+F4FivF[oF`w-Fghl6&F7Q9f~=~openOut~"cm_%s_%a
";|+F4FAFjn-Fghl6$F7Q<f~<<~toString(pp)~<<~endl;|+F4-Fghl6$F7Q<f~<<~toString(vr
)~<<~endl;|+F4-Fghl6%F7Q9for~i~from~0~to~%a~do~(|+F4,&F_uFBF\wFB-Fghl6$F7Q>f~<<
~toString(Ws#i)~<<~endl;|+F4-Fghl6&F7Q.R~=~ZZ/%a%s,~F4F[o-F\dm6$F`wF^p-Fghl6$F7
QDMonomialOrder~=>~Weights~=>~Ws#i];|+F4-Fghl6%F7Q0I~=~ideal(%s);|+F4-F\dm6$FF;
F^ilF_p-Fghl6$F7QVG~=~gb(I,ChangeMatrix=>true);|+M~=~getChangeMatrix~G;|+F4-Fgh
l6$F7Q>f~<<~toString(M)~<<~endl;|+);|+F4-Fghl6$F7Q,f~<<~close;F4F[ilF4F4F46#Fbp
F4,
I'readCMt+Fail6(Fcil%'cmfileGF.F1FPF`cm6"F4C*>F7FB>F^uF[r>FcyF[r>FF-Fav6$Q'cm/c
m_F4FA>F`w-Ffjl6#-F`jlFes>FivFh^n?(F4FBFBF4F\jlC$>F7Fj^n@&3F\jl/-F\dm6$F7FBFejm
C$>F^u,&F^uFBFBFB>(%"TGF^u-F\dm6$F7F_]n3F\jl/-F\dm6$F7;FB""'Q'matrixF4C$>Fcy,&F
cyFBFBFB>(%#CMGFcy-F]jm6%-F]jm6%-F\dm6$F7;""*F_pF`emFfdmF[fmFfjmO6%F`w7#-F\\l6$
-%%wdegG6$7#-Ffjl6#(Fi_nFc^lFiv/Fc^l;FBF^u7#-F\\l6$)-%'MatrixG6#7#-FL6$Ffjl(Fh`
nFc^l%#%TG/Fc^l;FBFcyF4F4F46#FBF4,
I(getTordt+6$%#gbG%#lmG6+F1Fa^l%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG%$solG%(w
eightsG6"F4C,>F77#-Fhu6#-F9F@>FFFdv>F`w/7#-%"$G6$F[rFF%%NULLG>Fiv7#-F\\l6$(FhtF
c^l/Fc^l;FBFF>F^u-FL6$f*6#%"zGF46$FRFSF4-FL6$f*FewF46$FRFSF47#-F\\l6$-Fjw6$FAF_
el-Ff\l6$F_elF_yF4F46$F1F_y-Fdu6$FAF'F4F46$F1F7FA>Fcy-FL6$f*FewF46$FRFSF4F\fnF4
F4FffnF;>Fdy-FL6$f*FjxF46$FRFSF4-Fhu6#-FL6$f*FewF46$FRFSF41FB-Fdcl6#-%$zipG6%f*
6$F_elFfenF46$FRFSF4*&FAFBF;FBF4F4F4FAF_yF4F46$FecnFhcl-%%subsG6$F_y7#-F\\l6$,&
&F\xF@FB%"gGF\w-Ff\l6$Fjhn&FbclF@F4F46*FdcnF`wFgcnFcyFfcnF^uFecnFiv<#-Fgdn6#;FB
F>>Fau&-&%-OptimizationG6#%)MinimizeG6&-Fdcl6#FivFdy/%+depthlimitG"#S/%'assumeG
F[q6#F^il>Feal-Fchn6$FauFiv6$Feal-Fgan6$FealF7F4F4F46#F^ilF4,
I-writeWeightst+Fail6*F.%#GsG%$LMsGFihm%%gffnGFg[mFggl%"wG6"F4C%>F^u-Fav6$Q)gfa
n/gf_F4FA>Fcy-Fav6$Q+weights/w_F4FA@%-&%*FileToolsG6#%'ExistsGF\elC'>6%F7FFF`w-
FjbmF\el>Fiv7#-F\\l6$&-F^cn6$&FF6#Fc^l&F`wF]]oF\o/Fc^l;FBFaz>Fdy-F\hl6$FcyFahl?
&FauFivFD-Fghl6%FdyFihlFau-F\il6#FdyFBF4F4F46#FBF4,
I)saveDatat+6,F`gl'%#mnG7$F/F/'%#spG%(numericGFjp'F1Fegl'%#avGFj\lF*'%#QBGF''%'
shiftsGF''%$stdG%(booleanG6'Fg[mFggl%$mn0G%$sp0GFit6"F4C&>F7-Fhr6%9--Fav6%Q-opt
im/o_std_F4FAQ%.txtF4-Fav6%Q.optim/o_nstd_F4FAFi_o>F^uFeq@%-F]\oFevC'>FF-F\hl6$
F7%%READG>F`w-Ffjl6#-F`jlFev>FivFf`o@$52&F;F\o&F`wF\o3/F]aoF^ao2FivFjn>F^uFDFhb
m>F^uFD@$F^uC%>FF-F\hl6$F7Fahl-Fghl6,FFQ8%a|+%a|+%a|+%a|+%a|+%a|+%a|+%aF4F;FjnF
[o-Fdu6$FerF'FgyF]w9+9,FhbmF4F4F46#"#5F4,
I)readDatat+6$F`glFj^o6,Fg[mFgglF^^oFa^oF.F1Fe^oF+Fg^oFi^o6"F4C.>F7-Fhr6%F;Ff_o
Fj_o>FFFb`o>F`wFf`o>FivFf`o>F^uFf`o>FcyFf`o>FdyFf`o>FauFf`o>FealFf`o>Fb_lFf`oFh
bm6*F`wFivF^uFcyFdyFauFeal-FL6$Fe\mFb_lF4F4F46#F^ilF4,
I*eigSolvert+6%F[t>'%'actvarG%(integerGFB>'%'digitsGF/"#:6,%%fB2CGF1F`^lF+FjzFi
pF)Fi_n%"VGF26"F4C/>FFF^dn>F`w&FFF:>FivF`]m>F7t+6$%"fGFjzFbx6"F4C$>F7-%&tableG6
#-F[hn6%f*6$F`^lFb\lF46$FRFSF4/F;FAF4F4F47#-%'coeffsG6%FAF;.FP7#FP-FL6$f*6#Fb\l
F46$FRFSF4-Fhr6%-%)assignedG6#&F_yF@F\goF[rF4F46$FcxF7F;F4F4F46#F^il>%'DigitsGF
jn>Fdy-Fe]m6$FAFiv>F^u&-F]^m6$FdyFivF\o>Fcy-F?F\el-F^v6#-Fav6%%@The~system~is~e
xpected~to~have~GFcy%'~rootsG>Fau-&FV6#%5MultiplicationMatrixG6'F`wF^u-Fdeo6#-%
'EquateG6$F^u7#-Fgdn6#F\cnFdyFiv>Feal&-&Fdo6#%-EigenvectorsG6#-%&evalfGFgalFbjn
>Feal-&%"|irG6#_F4%"/G6%Feal%#~$G-%".G6$-F^t6$Fcy/%%fillGFB&FealF\o>Fb_l-Fajo6$
-Fdbn6#-FL6$f*6#Fc\lF46$FRFSF4-Fhcl6$-FU6%FAF_yF\xFbclF4F46*F)FdyF+FivFjzF^uFdd
oF7FFFealF4F4F46#FBF4,
I$srtf*6$'Fc\lF]tF*F46$FRFSF4-Fhdl6$FAf*F^elF46$FRFSF4-&FV6#%*TestOrderG6%F;FAF
ZF4F46$F+F;F4F4F4F4,
I,poly2matrixt+6%F[t'%#nFGF/Fc^o6$%%monsG%%cffsG6"F4C$>FF7#-F^fo6%-Fbbm6#-Fdcl6
$*&(%$q_qGFc^lFB&FAF]]oFB/Fc^l;FBF;Fjn.F76$-Fdbn6%F;Fazf*6$Fc^l%"jGF46$FRFSF4-%
&coeffG6$&F_yF:(F[^pFAF4F46$F^]pFF-F^t6#7#F7F4F4F46#Ff]lF4,
I/permuteColumnst+6%'F&Fdbn'%#V1GF^t'%#V2GF^t6#F`cm6"F4C$>F7-Fhu6$FBF;-Fajo6$FA
-Fdbn6$F7<#-F\\l6$/6$Fc^l-&%*ListToolsG6#%'SearchG6$&F;F]]oFjnFB/Fc^l;FBF7F4F4F
46#Ff]lF4,
I)sparsityt+6#Fd_p6#%&numzrG6"F4C$>F7-F?6#-Fbw6$f*FewF46$FRFSF4-F^o6#/FAF[rF4F4
F4Fdfn*&F7FB-%$mulG6#-Fhu6$FBFAF\wF4F4F46#FBF4,
I(matrixSt+6''FjzF'F_tF(F*Fjp6%F2%#V0GFip6"F4C&>F`wF>@$0F_uF`wY%ILists~B0~and~B
~must~have~the~same~lengthG>Fcz-FI6%-FL6$f*FefoF46$FRFSF4FTF4F4FdrFAF`wF_q@%/-F
hu6$FBFFF`wO-Fa_p6%F7FF-F^tF:Y%=Failed~to~construct~matrix~SGF4F4F46#FgsF4,
I*quotientst+6&'Fjhn%(polynomGF(F*FjpF46"F4C$-FU6'FAF;Fjn.%"QG/FgnF[oFcepF4F4F4
6#FbpF4,
I-monPartitiont+6'Fd^o'%#GrGF'F*Fjp>Ff^oFiil6,F`tFjz%#aBG%"RG%#B2G%#RBGF)%#nGGF
i_nF26"F4C->F7&-F]^m6$F;FjnF\o>FF-Fdu6$-Fhr6%/FerFiilF7FerFgp>F`w-FL6$f*FewF46$
FRFSF4F]yF4F46$Fe^oFAFF>Fiv-Fh[p6$-Fdu6$-F`]l6$F`wFFF'Fjn>Fau-F?F\jn>F^u-FL6$f*
FewF46$FRFSF4*&FAFBFZF\wF4F4Fcgp-F]]lFjgp>FF7$-Fhu6#-Fh[p6$-Fdu6$-F`]l6$FFF^uF'
Fjn-Fhu6#-Fh[p6$-Fdu6$F^uF'Fjn>6$FcyF`w6$7$-FhuF\jnF`fl-FL6$f*FewF46$FRFSF4F]yF
4F4FcgpFF@%F]gp>Feal-Fbho6(FAFF-Fdeo6#-Fiho6$FF7#-Fgdn6#F`]oF;FjnFdepC%>Feal-Fb
ho6(FAF7-Fdeo6#-Fiho6$F77#-Fgdn6#;FBFdvF;FjnFdep>Fb_l-Fjbp6'FFF7F;FjnF[o>Feal-F
hr6%0F[oF[r-F^bm6$-Fajo6%Fb_lFeal-&Fco6#%(InverseG6$F[oFb_lF[o-Fajo6%Fb_lFeal-&
Fdo6#%.MatrixInverseG6#Fb_l>Fdy-Fdu6$,&-F^tF\jnFB-Fajo6$&Feal6$;FBFauF`p-F^tFes
F\wF'O6(F`wFFFcyFealFdy-Fdbn6#7#-F\\l6$-Fidp6&&FdyF]]oF;FjnF[o/Fc^lFd]qF4F4F46#
FgsF4,
I(matrixHt+6'F[tF(Fc^oFjpFct6/%*undetPolyG%#pvGF[]pFafp%#uHG%%leqsGFicnFc^l%#dF
G%#dGGFhtFjt%"hG6"F4C)>FF-FdclF`q>F`wF>>FivF_u>Feal-FL6%FjwFAFjn>F7t+6&Fc^oFg^q
FhtFe^p6#F]]p6"F4C%-F^fo6%-Fbbm6#,&FBFB-Fdcl6$)F;%"pG/Fd`q;FBFjnFBFAF_^p>F7F__p
-Fdcl6$*&&F7FjxFB&%#_vG6$F[oF[yFB/F[yFc[qF4F4F46#Fbp?(FauFBFBFivFDC%>6$FgelFb_l
6$F[r-FL6$f*FewF46$FRFSF4-Ff`l6$F[rFAF4F4F4,&7#-Fgdn6$-Fjw6$&F;FgalFjnF`wFBFeal
F\w?(FfblF[rFBF41,&FfblFBFgelF\wFerC&>F^u7#-F\\l6$-F76&FjnFF,&&Fb_l6#Fe^pFBFfbl
FBFe^p/Fe^pF`gm>Fcy<#-F^fo6$-Fbbm6#,&FbbqF\w-Fdcl6$*&&F^uF_cqFB&FAF_cqFBF`cqFBF
jn>Fdy-%'msolveG6$FcyF[o@$/-F?6#<#FdyF[r>Fgel,&FfblFBFBFB>&Fa`lFgal-F^bm6$-FL6%
-%"@G6$FbbmFe\mF^uFdyF[oO-Fgq6#-F\\l6$-&F^t6#%$rowG6#Fidq/Fau;FBFivF4F4F46#FgsF
4,
I*matrixHnit+6(F[tF('%"CGFdbn'Fh`nFdbnFc^oFjp6*%,undetPolyniGF[]pFafp%#H0GFh^qF
i^qFicn%%parsG6"F4C+>FFF>>F`wF_u>F7t+6&'F\_qF]epFc^o'Fc^lF/'Fe^pF/Fi_q6"F4C%-F^
fo6%FAF;F_^p>F7F__p-Fdcl6$*&F[aqFB&F]aq6%FjnF[oF[yFBF_aqF4F4F46#Fbp>Fiv-F^bm6$-
FL6$Fbbm-Fajo6$FjnF[oFgy>F^u-Fdbn6%F`wFFf*Fd^pF46$FRFSF4-Fbcl6&&F_y6$FAF;FenFAF
;F4F46(FffqFivF1FerFefqF7>Fau<#-F\\l6$&%#_uGF]]o/Fc^l;FB-F?6#-F`]l6$-F9F\elFer>
Fcy-FL6%F^fo<#-F\\l6$-F^bm6$-Fbbm6#,&F^apF\w-Fdcl6$*&&F^uFd^pFBF\dqFB/Fe^pF`enF
BFgyF_gmFer>Fdy-F_dq6%FcyFauFgyO-F^bm6$F\eqFgyF4F4F46#Fa`nF4,
I*syzModulet+6'F[tF('%"AGFdbnF*Fjp6*F[]pFafp%"eG%"LG%#LtGF&F2Fjz6"F4C.>F7F>>FFF
_u>F`w-F\\l6$-F^t6$FF<#/Fc^lFBF_en>Fiv7#-F\\l6$7#-&FV6#%,LeadingTermG6$F^apF[oF
_en>F^u-FL6$f*FewF46$FRFSF4*&&FAF\oFB&FAFbjnFBF4F4F4Fiv>Fcy-Fdbn6$FFf*Fd^pF46$F
RFSF4*&-%$lcmG6$&F\goFbjn&Fj^pFbjnFBFihnF\wF4F46&Fi[rFivFj[rF^u>Fdy7#-F\\l6$-F
\\l6$,(*&&FcyFd^pFBF^]oFBFB*&&Fcy6$Fe^pFc^lFB&F`wF_cqFBF\w-Fgq6#-Fidp6&z'6&F\_r
F^_rF^ap&F;F_cq[[[\[[[[[\[[mFB\[[[[[\[[[[[mF\wF;F[oFerF\w/Fe^p;,&Fc^lFBFBFBFFF_
en>Fdy)-FdbnFh]oFjbn>Fau-Fdbn6#7#-F\\l6$-Fidp6&F\^pF;F[oFerF_ap>Fdy-FL6$Fbbm-Fg
q6$-Fajo6$FdyFjn,&-&Fdo6#%/IdentityMatrixGFevFB-Fajo6$FauFjnF\w@$Fjr>Fdy-F^bm6$
FdyFerO&Fdy6$-%'removeG6$f*F]]oF46$FRFSF4-&%+ArrayToolsG6#%'IsZeroG6#&F_y6$FAF`
pF4F46$F2Fdy7#-Fgdn6#;FB-Fhu6$7$FBFBFdyF`pF4F4F46#FgsF4,
I+matrixHsyzt+6(F[tF(FafqFe[rF*Fjp6$F2%&ThetaG6"F4C%>F7-Fb[r6'FAF;F[oFerFgy>FF-
Fdbn6%-Fhu6$F_crFjn-Fhu6$F_crF7f*Fd^pF46$FRFSF4&FcxF\iqF4F4F4O-F^bm6$-FL6$Fbbm,
&FbhqFB-Fajo6$FFF7FBFgyF4F4F46#Fa`nF4,
I(supportt+6$'F_eoF]epFc^oF46"F4C$F]fo<#FPF4F4F46#F^ilF4,
I,fixTemplatet+6'%'admonsGF[tFc^o'%$monGF''F`fpF'6/F[]p%%monFG%&admonGFc^lFe^pF
cepFit%#xFGF&F_cpFftFedo%%mon1G6"F4C.>F7F_u>FF-FL6$f*6#F_eoF46$FRFSF4-F^erF[xF4
F46$F1FjnF;>F`w7#-Fgdn6$F__lF7?(FivFBFBF>FDC%>FdyFeq?(F^uFBFBF7FDC$>Fcy-FL6$f*6
#%#mfGF46$FRFSF4-Fhr6%-%'divideG6%&FZ6#F\xFA.%"qGFehrFidnF4F46&FierFAFc^lFiv&FF
F\el@$0FcyF__lC%>&F`wF\el<$Fiel-Fhu6#F\ir>FdyFD[@$4FdyY%;Failed~to~correct~temp
lateG>Fa`l7#-F\\l6$-Fdu6$-Fcbl6$-Fdu6$&F[oF\elFgpF\irF^t/F^uF`ap>Fau7#-F\\l6$-F
\\l6$*&&F;F\elFBF^^oFB-Ff\l6$F^^o&Fa`lF\elFajr>6$FealFb_l-FI6%Fau-F?FgalFjn>Ffb
l-F`]l6$-Fdu6$Fb_lFgp-Fdu6$FerFgp>Ffbl-Fh[p6$7#-Fhu6#Ffbl-Fa]m6#-FhuF`q>Fgel-Fg
q6$F]\s-Fhu6#Fer-F^v6#%/Template~fixedGO6&Fa`lFealFb_lFgelF4F4F46#FgsF4,
I2constructTemplatet+6&'%"HG<$FdbnF'F[tFc^oF\fr6)F[]pF[frF`frF&F_cpFftFedo6"F4C
+>F7F_u>FF-Fhr6%-Fg[l6$FAFdbn7#-F\\l6$&-FI6%&FA6$F`pFe^p-Fhu6$F_crFAFjnFbjn/Fe^
pF`apFA>F`w7#-F\\l6$-F\\l6$*&Fg_rFBF^^oFB-Ff\l6$F^^o&FFF_cqFf^s>6$FivF^u-FI6%F`
w-F?FajlFjn>Fcy-F`]l6$-Fdu6$F^uFgp-Fdu6$F[oFgp>Fcy-Fh[p6$7#-FhuFcflF_\s>Fdy-Fgq
6$Fa`s-FhuFd_l@$0-Fhu6$FBFdy-Fhu6$FBF^uC$-F^v6#%7Template~is~incompleteG>6&FFFi
vF^uFdy-Ffer6'-F`]l6$-Fdu6$FdyFgpFi_sF;FjnFFF[o6%FF-Fa_p6%FivF^uFdyFdyF4F4F46#F
bpF4,
I-adjustParamst+6'F[t'Fa]sFdbnF\fr'F1FgpFjp63F[]pFafp%#H1G%#LmG%%colsGFi[rF[frF
_cpFftFh[r%#smG%#rmG%#npG%#ssG%$prmGFi^qFicn6"F4C3>F7F>>FF-Fhu6$F_crF;>F`wF;>Fi
v-F\\l6$-FI6%&F;Fc^sFFF[oFf^s>F^u7#-F\\l6$-F\br6$f*FewF46$FRFSF4-%+membertypeG6
$F/-Fdu6$&&F_y6#,&Fe^pF^ilF\wFB6$F`pFAF'F4F46$FcbsFiv7#-Fgdn6#;FB-Fhu6$7$FBF^il
&FivFfdsFf^s>Fby6$7#-F\\l6$&Faes6$F`pF[dqFf^s7#-F\\l6$&&Fiv6#,$Fe^pF^il6#F[dqFf
^s>Ffbl7#-F\\l6$-FL6$f*FbxF46$FRFSF4-F^er6$-Fbbm6#*&&FZF_cqFBFAFBFenF4F46&F\tFA
F1F[o&FdyF_cqFf^s>Fau-Fdu6$-FL6$Fhu-FL6%-F_eq6$FhuFduFfblFgpFgp>Feal-Fdu6$-F`]l
6$Fau-Fdu6$FjnFgpF'>Ffbl-F^tF^\s>Fgel-FL6$f*6#Fh[rF46$FRFSF4-Fbw6$f*F]]oF46$FRF
SF4-Fi_m6$FZFihnF4F46&Fh[rFAFebsF_y<#-Fgdn6#;FB-Fhu6$FBF_yF4F46$FebsFfblFeal>Fa
`l7#-F\\l6$-%"+G6#-F\\l6$-F?6#-Fbw6%%$hasGFgel&&FgelF_cqF]]o/Fc^l;FB-F?6#Ffjs/F
e^p;FB-F?Fi^m>Ff_lf*6&Fc^lFe^pFfbsFgbsF46$FRFSF452-F?6#&FjnF:-F?6#&FjnF@3/Fg[tF
d[t2&F[oF:&F[oF@F4F4F4>82-Fhdl6$7#-Fgdn6#;FBF`_mf*Fd^pF46$FRFSF4-Fbcl6&FAF;F_yF
\xF4F46(FfbsFgelFgbsFa`lFhbsFf_l>Feal&Feal6#F`\t?&Fb_lFealFDC+>Fiv-F\\l6$-FI6%&
F`wFc^sFFF[oFf^s>Fby6$7#-F\\l6$FaesFf^s7#-F\\l6$F]fsFf^s@$/-F?6#-F9FcflF[rFair>
Ffbl7#-F\\l6$-FL6$f*FbxF46$FRFSF4FifsF4F4F_gsF`gsFf^s>Fgel-FL6$f*FewF46$FRFSF4<
#-&Fj`p6#%*SearchAllG6$FB-FL6$f*6#F_elF46$FRFSF4-F?6#-F]]l6$FA<#F_yF4F46$Fh[rF_
yFAF4F46$Fh[rFb_lFfbl>83<#-F\\l6$-Fhu6#-FL6$f*FjxF46$FRFSF4-Fhu6#-Fdu6$&&F_yF_c
qFhdsFgpF4F46$Fi[rFcyFfjsFf^s>84-F_dq6$Fd`tFer@$/-F?6#<#FfatF[r\>F`w-F^bm6$-FL6
%F^eqF`wFfatFer-F]]s6&F`wFAF[oFjnF4F4F46#FgsF4,
I4isActionMatrixFoundt+6('Fi_nFdbnFd_p'F]fpF'F]cp'FafpF/Fjp6'%#tMG%#T1GFipFP%"r
G6"F4C'>F`wFc_l>Fiv,&F`wFBFerF\w>F7-F^bm6$-%*GaussjordG6$F;.F^uFgy>FF-F^bm6$-Fg
q6$,$&F76$;,(F^uFBFerF\wFBFBF^u;,$F`wF\wF\wF\w-Fdbn6%FivF`w<#-F\\l6$/6$,(FivFBF
[yF\wFBFB-Fi`p6$&Fjn6#,$F[yF\wF[oFB/F[yF\fqFgy-&Fdo6#%&EqualGFdblF4F4F46#Fa`nF4,
I/SchurReductiont+6'Fd_pF[fr'%#nEGF[qFjp'%%polsGF'63%#rgG%$crgGFP%#M1G%#bsG%#M2
G%$tM2G%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GF_fp%#B3G%#B4G%$iB1G6"F4C3@$F]gpOF
A>F77#-F\\l6$-Fhu6#7#-Fgdn6#;,&-Fdcl6$-Fhu6$FBF^ap/Fc^l;FB,&Fd`qFBF\wFBFBFBFB-F
dcl6$Fdht/Fc^l;FBFd`q-Ff\l6$Fd`qFer>F`wFdv>FF7#-Fhu6#-F`]l6$<#-Fgdn6#;FBFd^s<#-
FhuFev>Fiv-Fgq6$&FA6$F7F`p&FA6$FFF`p>Fcy&Fiv6$F`gmFf`q>Fdy-F^bm6$-Fjct6$)FcyFjb
n.F`ctF[o>Ffbl-FL6$f*F]]oF46$FRFSF4-Fi`p6$FB-Fdu6$F\goF'F4F46$FiftFdy<#-Fgdn6#;
FBF`ct>Fgel-Fdu6$-F`]l6$<#-Fgdn6#;FB-Fhu6$F`esFdyFfblF'>Fau-Fgq6%&Fiv6$F\\sF`p&
Fiv6$7#-FhuFi^mF`p&Fiv6$;FdemF\wF`p>Feal-F^bm6$-Fjct6$&FauFejtF\[uF[o>Ffbl-FL6$
f*F]]oF46$FRFSF4Fb[uF4F46$F[gtFealFg[u>Fgel-Fdu6$-F`]l6$<#-Fgdn6#;FB-Fhu6$F`esF
ealFfblF'>Fb_l-%$<|gr>G6%&Fau6$F`pF\\s&Fau6$F`pF]]u&Fau6$F`p;,&FjnFBFBFBF\w>6&F
a`lFf_lF`\tFd`t6&&Fb_l6$Fj[uFj[u&Fb_l6$Fj[u;,&F`ctFBFBFBF\w&Fb_l6$F\`uFj[u&Fb_l
6$F\`uF\`u>Ffat-F`\q6$F[oFa`l-F^bm6$,&Fd`tFB-Fajo6%F`\tFfatFf_lF\wF[oF4F4F46#Fg
sF4,
I0LinDepReductiont+6%Fd_pFjp>%(show_tMGFeq6)F`ctF^ctFfft%$tM1GF]gt%&r2delG%&c2d
elG6"F4C+>FF-F^bm6$-Fjct6$)FAFjbnF_^pF;>F^u-FL6$f*F]]oF46$FRFSF4Fb[uF4F46$F^ctF
F<#-Fgdn6#F`ap>Fcy-Fdu6$-F`]l6$<#-Fgdn6#;FB-Fhu6$F`esFFF^uF'>F`w&FA6$-F\br6$f*F
]]oF46$FRFSF4-F^o6#-Ff\l6$FAF_yF4F46$FbauFcy7#FgitF`p>Fiv-F^bm6$-Fjct6$F`wF_^pF
;>F^u-FL6$f*F]]oF46$FRFSF4Fb[uF4F46$FaauFivFbbu>Fdy-Fdu6$-F`]l6$<#-Fgdn6#;FB-Ff
`lF\elF^uF'@$FjnOFiv6%&F`w6$F`p-F\br6$f*F]]oF46$FRFSF4FgcuF4F46$FcauFdy7#-Fgdn6
#;FB-Fhu6$F`esF`wFcyFdyF4F4F46#Ff]lF4,
I)rectTordt+6&F[tFat'%#TsGF'Fjp6(F[]p%#dgGFb^l%#nnG%$GBsGFihm6"F4C+>F7F>>FF7#-F
\\l6$*&-Fdcl6#-FL6%FjwFAFgtFBF7F\w-Ff\l6$FgtF;>F`w-FL6$f*6#FhtF46$FRFSF4*$FAF\w
F4F4F4FF>Fiv-F_^r6#-Fhu6#-FL6$%&denomGF`w>F`w*&FivFBF`wFB>F^u-FL6$f*FewF46$FRFS
F4-Fe]m6%FZFA/FgnFenF4F46&F\tFAF.F[oFjn>Fcy7#-Fhu6#<#-F\\l6$&-F^cn6$&F^uF]]o-&F
V6#%0LeadingMonomialG6$F^ju&FjnF]]oF\o/Fc^l;FBFigo>Fcy-FL6$f*FeenF46$FRFSF4-F[h
n6%f*F^elF46$FRFSF4F`hnF4F4F4FAF_yF4F46$Fb^lF`wFcy-FL6$f*FewF46$FRFSF4-FganF[xF
4F46$F1F;FcyF4F4F46#FbpF4,
I,filterBasest+6&F[t'FdglF''%%nQBsGF/'%#ffGFb^o6&%#mFG%#BsGFibsF`cm6"F4C(>Fiv-F
]`l6#*&F[oFBFjnFB>F7-Fdu6$&-FI6%FAF>FadnFbjnFgp>FF-FL6$f*FewF46$FRFSF4-F?6#-F]]
l6$-Fdu6$FAFgpF_yF4F46$Fa\vF7F;>F`w-Fhdl6%FF%">G/%'outputG%,permutationG-F^v6#-
Fav6$Fiv%>~quotient~space~bases~removedG7#-Fhu6$;FB,&FjnFBFivF\wF`wF4F4F46#FbpF
4,
I(iniProbt+6&F`gl'%#qbGF[qF^\v'%#pnGF/60F\t%#vFGF.F1F[guFgfu%#GCGFdgl%$CMsGF+Fh
`nF)FehrF]\v6"F4C*AF_\m>6$F7F`w6$Fd\mF[o>FF-F^tFev@$0-&FV6#%1HilbertDimensionG6
$F7/FgnF`wF[rYQZThe~problem~is~expected~to~have~infinitely~many~solutionsF4>Fiv
F^]m@'/F;FBC)>6%F`wFcyFeal-Fj]nF@>Ff_lF`_m-F^v6#-Fav6$Ff_l%8~change~matrices~lo
adedG>F^u7#-F\\l6$-F^bm6$-FL6$Fbbm-Fdu6$-Fajo6$&FealF]]oFFF'F`w/Fc^l;FBFf_l>Fau
7#-F\\l6$&-F]^m6$F^ju&FcyF]]oF\oFdbv>Fa`l-Fh[v6&F7FauFf_lFjn>6&FealF^uFcyFau6&7
#-F\\l6$Fcbv-Ff\l6$Fc^lFa`l7#-F\\l6$F^juFgcv7#-F\\l6$F]cvFgcv7#-F\\l6$&FauF]]oF
gcv/F;F^ilC*>Fau-F_ilF@>Ff_lFa[s-F^v6#-Fav6$Ff_l%=~quotient~space~bases~loadedG
>Fb_l-Fa]m6#Fhip>Fdy-Fe]m6&F7Fb_lFg`v/F`^v%)extendedG>6$FgelFfbl6$&FdyF\o-Fdbn6
#&FdyFbjn>Fa`lF_cv>Fbcv6&7#-F\\l6$FfblFgcv7#-F\\l6$FgelFgcv7#-F\\l6$Fb_lFgcvF_d
vC+>Fcy-FL6$f*FewF46$FRFSF4-Fa]m6#-FhuF@F4F4F4-&%)combinatG6#%(permuteGF\jn>Fcy
-Fcfu6&F77#FhipFcyF`w>Fdy-FL6$f*FewF46$FRFSF47#-Fe]m6&F_yFA/FgnF\xFcevF4F46&F\t
F7F.F`wFcy>6$F^uFeal6$-FL6$f*FewF46$FRFSF4Ff]rF4F4F4Fdy-FL6$f*FewF46$FRFSF4-Fdb
n6#Fg]rF4F4F4Fdy>Ff_lFigo>FauFgbv>Fa`l<#-F\\l6$-Fi`p6$FbdvFauFdbv>FbcvFccv-F^v6
#-Fav6&Fa[s%A~quotient~space~bases~computed~(GFf_l%")G-F^v6#-Fav6%%AThe~problem
~is~expected~to~have~G-F?6#&FauF\o%+~solutionsGO6)F`wF7FivF^uFcyFauFealF4F4F46#
FbpF4,
I/TemplateFindert+6*F`gl>'%,action_varsG-F'6#<$%'negintGF/Fiil>F\[mF[r>'%,filte
r_fracGFb^oF[r>'%&partsGF_^oF_cr>Fb[mFd[m>'%*quo_basesGF[qF[r>'%+schur_polsGFb[
wFiil6KF\tF.F1%&avarsGFe^oF[guFgfuFdglFg_vFjepF+Fc^lFe^pF[yFa]sF[frF&FedoF]fpFj
zF`fpFi_nF)Fbfq%#flGFPF`cm%#moG%#noGFa^o%$spoG%"NGFa^lFafpFipFehr%%irngG%#nkGFg
^oFh`n%&tord1G6"F4C,>8?"(+++">8BF\w>6)FFF7F`wFcyFdyFauFeal-F]_v6&FAF]wF[oFgy>Fi
v-Fhr6%/F_uF[rF`w-FL6$f*6#F`^lF46$FRFSF4F\goF4F46$F1F`wF;>8G-%%iquoG6$Fa[s&FerF
\o>8H7#-Fgdn6#;,&FBFB*&,&&FerFbjnFBF\wFBFBFd^wFBFB-Fhr6%/Fb_wFh^wFa[s*&Fb_wFBFd
^wFB>6%8D8F8I6%F\hpFejv-F?6#Fj^w>8C,$*&F[`wF\wFi_wF\wFbal?(Ff_lFBFBF[`wFDC&>Fge
l&Fj^w6#Ff_l>6&Fb_lFfbl8J8K6&&FcyFi^m&FdyFi^m&FauFi^m&FealFi^m>8L-Fhu6$FBFfbl?(
Fa`lFBFBFi_wFDC.>F^u&FivFifl>6(868788898:8;-Ffep6'F^uFb_lFfblFFFj`w>8E-F?6#F_bw
>F`\t-Fhr6%/F]wF^il-Fb^q6'F7F_bwF`wFFFjn-F^fq6(F7F_bwF`bwF[awF`wFF>6%Fd`tFfat85
-F\bs6'F7F`\tF]bwF`wFF>Ffat-F\ft6'FfatFd`t,(-Fhu6$F`esFfatFBFj_wF\wFdbwF\wFFF^b
o>Ffat&-F[au6$FfatFFF\o>8<-Fgbt6(F^bwFfatF[bwF\bwFdbwFF>6$8=8>-Fhu6$FBFfat>8A-F
bap6#Ffat@&3F_dw52FddwFa]w3/FddwFa]w2Fd]wFidwC%>6%Fa]w8@Fd]w6%FddwFedwFidw-F^v6
#-Ff`m6(QTSmaller~or~sparser~template~found:~[%d,%d],%a,%a,%aF4FddwFedw-Ffio6$F
idwFf]lF^u-Fhr6%FjbwFgelFbaw-Fj]o6,FA7$FddwFedw-Ffio6$FidwFgsFFF`wF^uFfblF\bwFd
`t-F^o6#0F]wF^il4F_dwY6&Q@Invalid~action~matrix,~%1,%2,%3F4FgelF^uFfbl-F^v6#-Ff
`m6*Q6%d%s,[%d,%d],%a,%a,%aF4-F]`l6#*&,&*&,&Ff_lFBF\wFBFBFi_wFBFBFa`lFBFBF``wFB
Q"%F4FddwFedwF]fwF^uF_fw-F^v6#-Ff`m6&Q:Best~template:~[%d,%d],%aF4Fa]wFfew-Ffio
6$Fd]wFf]lF4F4F46#FBF4,
I-readTemplatet+Fdbo6?F^_oF__oF.F1Fe^oF+Fg^oFi^oF\t%#M0G%#U0G%&tord0GF_cpFjepF]
fpFjzF`fpFi_nF)FafpF&F^ct%#t1GFbauFcauFedoFftF^^o%#xEG6"F4C8>6*F7FFF`wFivF^uFcy
FdyFau-FbboF\iqAF_\m>FealFd\m>6$Fb_lFfbl-FI6%FealF`_mFiv>FgelF^ev>Fa`l-Fh[p6$Ff
blFgel>Fb_l-Fa_p6%Fb_lFfblFa`l>Ff_l-Fe]m6%FealFcyFg`v>6'F`\tFd`tFfatFacwF[bw&-F
fep6'F^uFf_lFcyF`wFdy6#;FBFgs>F\bw-F?6#F[bw>6$F]bwFddw&-F]]s6&FauFealFivFfat6#;
F^ilFf]l>F^bw-F[au6%F]bwF`wFD>6%F]bwF`bwF_dw-F[au6$F]bwF`w>F_bw-FL6$f*FewF46$FR
FSF4-Fhu6#-Fbw6$f*Fj_tF46$FRFSF40&F_y6$FAFenF[rF4F46&F^ctF_yFfwFA<#-Fgdn6#;FB-F
hu6$F_crF_yF4F46$F^ctF^bw<#-Fhu6#F_dw>Fa]w7#-Fhu6$FBF]bw-F^v6#-Fav6$%2Template'
s~size:~GFa]w@$50&F7F\o&Fa]wF\o0&F7Fbjn&Fa]wFbjnYQ/Wrong~templateF4>Fddw&Fddw6#
-F\br6$f*F]]oF46$FRFSF4FgcuF4F46$FcauF_dw7#-Fgdn6#;FB-Fhu6$FBFddw>Ffew-Fdu6$&Fd
dw6#7#-FhuFfbwFgp>Fedw-Fh[p6$-Fdu6$-F`]l6$-Fdu6$FddwFgp-Fdu6$FfatFgpF'Fgel-F^v6
#-Fav6$%6Action~matrix~found:~G-Fgbt6(FacwF]bwF`\tFd`tF\bwF`w60FivF^uFb_lFa`lFe
dwFfatF`\tFd`tFauF`bwF_dwFa]wF\bwFfewF4F4F46#F^ilF4,
I*iniColpivt+6&'FedoF^t'FhhwFgpFd^oF*6+%#VlG%"PGF`t%#aPGF^fp%#P0G%#RPGFftF16"F4
C2>FealF^dn>F7-Fdu6$-F`]l6$Fh]vF;F'>FF-Fdu6$-Fbw6$f*FOF46$FRFSF4-Fi_m6$F]yF\xF4
F46&Fe^oFjnFaaxF7F7Fgp>F`w-Fbw6$f*FOF46$FRFSF4-Fdu6$-FL6$f*6#FgtF46$FRFSF4FebxF
4F46&FPFAFbaxF\xF_y%$andGF4F46&F1FealFbaxFFFF@$/Fe_sF[rYQ=Can't~solve~for~any~v
ariableF4>F`w-Fhdl6$F`wf*6$Fd`qFehrF46$FRFSF42-FjwFjcu-Fjw6$F;F_yF4F46$F1Feal>F
`w-Fh[p6$-FL6$f*FbcxF46$FRFSF4*&FAFB&F_yF\oFBF4F46$F`tF`w7$F^`mFBF[o-F^vFajl>Fi
v-FL6$f*FOF46$FRFSF4F]yF4F46$Fe^oFjnFF>F^u-Fh[p6$-Fdu6$F\blF'F[o>Fcy-F`]l6$FF-F
du6$F`wFgp>FF7$-Fhu6#-Fh[p6$-Fdu6$FcyF'F[o-FhuFajl>Fdy7$F[elF`fl>Fau-Fh[p6$-Fdu
6$-Fcbl6$-F`]l6$FcbmFfasF;F'F[o-F^v6#-Fav6$%BNumber~of~permissible~monomials:~G
Faz6'-Fgq6$-FhuFgal-FhuFh]oFauF^uFF7#-Fhu6#-F9FajlF4F4F46#FbpF4,
I,writeSolvert+60%$dirGFdhwF_cpF1%&vars1GFe^o%#iMG%#eMGFjzF]fpF^^oF`ft%#nRGF[_o
6(%#vvGFgglFa^lFipFc^l%#fbG6"F4C=>F`wFc_l>Fiv-F?6#F_bo>FcyQ%~~~~F4>F77#-F\\l6$-
Fi`p6$*&&FerF\elFB&F_bo6#F\wFBF_bo/F^u;FB,&F`wFBF\wFB>FF-F\hl6$-Fav6+FAQ"/F4-Fh
r6%91Q%std_F4Q&nstd_F4&9.F\oQ"xF4&Fa[yFbjnQ"_F4FaglFb\mFahl-Fghl6$FF-Fav6'QH%%~
Input:~coefficient~matrix~C~of~size~F4F[]pFb[y-Fhu6$F`esF;Q#|+|+F4-Fghl6$FF-Fav
6%Q5%%~Monomial~vector:~F4-Fdu6$FjnF'F\\y-Fghl6$FF-Fav6,Q*function~F4F[oQ$~=~F4
F[[yF`[yFb[yFc[yFd[yFaglQ&(C)|+|+F4-Fghl6$FF-Fav6&FcyQ(i_dx~=~F4-FL6$f*F]]oF46$
FRFSF4Ff]rF4F4F4F]wQ#;|+F4-Fghl6$FF-Fav6&FcyQ(j_dx~=~F4-FL6$f*F]]oF46$FRFSF4Fg]
rF4F4F4F]wFd]y-Fghl6$FF-Fav6&FcyQ(C_dx~=~F4F^boFd]y-Fghl6$FF-Fav6(FcyQ>M~=~spar
se(i_dx,j_dx,C(C_dx),F4F`[yQ",F4Fc[yQ$);|+F4-Fghl6$FF-Fav6'Q"|+F4FcyQ5[L,|ir,Pi
]~=~lu(M(:,1:F49/Q%));|+F4-Fghl6$FF-Fav6$FcyQ+Pi~=~Pi';|+F4-Fghl6$FF-Fav6(FcyQ0
M~=~[Pi*L~Pi(:,F4,&F`_yFBFBFBQ,:end)]\M(:,F4F\`yQ(:end);|+F4-Fghl6$FF-Fav6&FcyQ
+M~=~M(end-F4,&90FBF\wFBQ*:end,:);|+F4-Fghl6$FF-Fav6'F^_yFcyQ+T~=~zeros(F4FivFi
^y-Fghl6$FF-Fav6*FcyQ%T(1:F4Fe`yQ.,:)~=~-M(:,1:F4Fe`yQ')\M(:,F4,&Fe`yFBFBFBF^`y
@&/,&FivFBFe`yF\wFB-Fghl6$FF-Fav6&FcyQ#T(F4*&FivFB-Fi`p6$&Fe_oFajxF_boFBQ()~=~1
;|+F42FBFfay-Fghl6$FF-Fav6&FcyQ$T([F4&-Fdu6$7#-F\\l6$,&*&FivFB,&-Fi`p6$&Fe_o6#,
(F^uFBFivF\wF\wFBF_boFBF\wFBFBFBF^uFB/F^u;FcayFivFbgl6#F_]nQ)])~=~1;|+F4-Fghl6$
FF-Fav6%F^_yFcyQ1[V,D]~=~eig(T);|+F4-Fghl6$FF-Fav6*FcyQ*sol~=~[V(F4-Fdu6$F7Fbgl
Q/,:)./repmat(V(F4FivQ%,:),F4FdjxQ3,1);~diag(D).'];|+|+F4-Fghl6$FF-Fav6$FcyQXI~
=~find(not(isnan(sol(1,:)))~&~not(isinf(sol(1,:))));|+F4-Fghl6$FF-Fav6$FcyQjo%%
I~=~find(not(isnan(sol(1,:)))~&~not(isinf(sol(1,:)))~&~not(imag(sol(1,:))));|+F
4?(F^uFBFBFdjxFD-Fghl6$FF-Fav6'FcyF_jxQ(~=~sol(F4F^uQ&,I);|+F4-Fghl6$FF-Fav6'Fc
yFgyFgeyF`wQ',I);|+|+F4-Fghl6$FFQ$endF4FhbmF4F4F46#"#9F4,
I3writeSolver_colpivt+61FhhxFdhwF_cp%&vars0GFihxFe^oFjhxF[ixFbaxFcaxF^^oF`ftF\i
xFipF[_o6(F^ixFggl%$nv0G%#nPGFc^lF_ix6"F4CA>F`wFc_l>FivFdix>FcyFgix>F77#-F\\l6$
-Fi`p6$F^jx&F_bo6#;,$F][yF\wF\wFbjx>FF-F\hl6$-Fav6+FAFjjx-Fhr6%92F^[yF_[yF`[yFb
[yFc[yQ)_colpiv_F4FaglFb\mFahl-Fghl6$FF-Fav6'Fi[yF^csFb[yFj[yF\\yF]\y-Fghl6$FF-
Fav6,Fh\yF[oFi\yF^hyF`[yFb[yFc[yFahyFaglFj\y-Fghl6$FF-Fav6&FcyF_]y-FL6$f*F]]oF4
6$FRFSF4Ff]rF4F4F4F]wFd]y-Fghl6$FF-Fav6&FcyFi]y-FL6$f*F]]oF46$FRFSF4Fg]rF4F4F4F
]wFd]yF^^yFc^y@$0F`_yF[rC&Fj^yFb_yFg_y-Fghl6$FF-Fav6&FcyQ,M~=~full(M(F4F\`yQ+:e
nd,:));|+F4@$0Fe`yF[rC%-Fghl6$FF-Fav6'F^_yFcyQ6[L,UR,Pi]~=~lu(M(:,1:F4Fe`yFa_yF
b_y-Fghl6$FF-Fav6(FcyF[`yFcayF]`yFcayF^`y-Fghl6$FF-Fav6&FcyQ*MP~=~M(1:F4Fe`yQ&,
:);|+F4-Fghl6$FF-Fav6&FcyQ(NP~=~M(F4FcayQ+:end,:);|+|+F4-Fghl6$FF-Fav6&FcyQ:[Q,
U,Pi]~=~qr(NP(:,1:end-F4FdemFa_y-Fghl6$FF-Fav6(FcyQ4A~=~UR\[MP(:,1:end-F4FdemQ/
)*Pi~MP(:,end-F4F`wQ):end)];|+F4-Fghl6$FF-Fav6*FcyQ+B~=~U(:,1:F4,(F`[yFBF`_yF\w
Fe`yF\wQ()\[U(:,F4,*F`[yFBF`_yF\wFe`yF\wFBFBQ3:end)~Q'*NP(:,end-F4F`wFf\z-Fghl6
$FF-Fav6(FcyQ/M~=~[-A(:,end-F4,&F][yFBF\wFBQ1:end)+A(:,1:end-F4F][yQ,)*B;~-B];|
+|+F4-Fghl6$FF-Fav6&FcyQ&xP~=~F4Fe_oFd]y-Fghl6$FF-Fav6*FcyQ*P1~=~[(1:F4,(FivFBF
`wF\wF\wFBQ&)*Pi~F4,&FivFBF`wF\wQ":F4FivQ$];|+F4-Fghl6$FF-Fav6-FcyQ-T~=~getT(M,
[F4F[zFe^z,&FivFBFe`yFBQ+~P1(1:end-F4F][yQ+)],P1(end-F4Fe]zQ&:end)F4Q',xP);|+F4
Ficy-Fghl6$FF-Fav6*FcyFbdyFcdyFedyF][yFfdyFdjxFgdyFhdyF]ey?(F^uFBFBFdjxFDFceyFi
eyF^fyFhbmF4F4F46#FbdoF4,
I0SolverGeneratort+6&F`gl>'F]gt%'symbolGF[_o>'%'colpivGF\_oFD>'%)root_dirGFbglQ
(solversF46DF1Fe^oFdhwF_cpFftF`fpF]fpFjzFi^oFbauFcauF^^oF\ixFhhwFedo%#E0GFf_p%#
R0GFbaxFcaxFffyFipF`ft%$nE0G%$nR0GFify%$iM0G%$eM0GF&%#MtGFjhxF[ixFhhxFihx6"F4C4
>60F7FFF`wFivF^uFcyFdyFauFealFb_lFfblFgelFa`lFf_l-Fahw6$FA-%&evalbG6#/F;F[_o>F`
\t-Fgq6$F[elFa`s>6'FfatFd`tFacwF[bwF]bw-F[ax6&F`\tFf_lFF-Fa]m6#F[jt>F\bw-FL6$f*
FefoF46$FRFSF4-Fi`p6$*&FAFBF_yFB7$-FhuFchr-Fhu6#FbclF4F46(Fe^oFFFbaxF[bwFf`zFac
wF[bw>6'F^bwF_bwF`bwF_dwFddw6'Fa[sFigo-F?6#Fd`t-F?6#FacwFfjw>Fedw7#-%(indicesG6
$-Fdu6$F`wFdeo%+indexorderG>Fa]w-FL6$f*FewF46$FRFSF4-Fdu6$,&Ff]rFB*&,&Fg]rFBF\w
FBFBFi\xFBFBFbglF4F46$FdhwF`wFedw>Fdbw-Fdu6$-F`]l6$-Fdu6$-Fhr6%FjnF]bwF7Fgp<#FF
F'>Ffew-Fdbn6$-Fhu6$FBF`w<#-Fhu6#-F[hn6%f*F^elF46$FRFSF4/F`gvF;F4F4F4FedwFa]w>F
few&-F]]s6&Feal-Fdu6$-Fajo6$FfewFivF'F7FcyFbjn>Ffew&Ffew6$-F\br6$f*F]]oF46$FRFS
F4FgcuF4F46$FbauFb_l7#-Fgdn6#;FB-Fhu6$F_crFfew-F\br6$f*F]]oF46$FRFSF4FgcuF4F46$
FcauFfbl7#-Fgdn6#;FB-Fhu6$F`esFfew@$Fjn>Ffew-Fa_p6%FfewF`\tFfat>Fidw-Fdu6$FfewF
deo>6$Fd]wF``w6$7#-Ffcz6$FidwFjcz-FL6$Fhu7#-%(entriesGFjhz>Fi_w-Fav6%F[oFjjxFA@
$4-F]\o6#Fi_w-&F^\o6#%.MakeDirectoryGFfiz@%Fjn-Fcfy61Fi_wF`wFivF]bwFdbwFFFd]wF`
`wF[bwF\bwFgelF`bwF_dwF^bwFbaz-Fehx60Fi_wF`wFivF7FdbwFFFd]wF``wFauFdyFgelF_bwFa
`lFbaz6&F^bwFgelF7FivF4F4F46#FBF4,
I.write_inidatat+6$Fagl>Fa`zFc`z6%FhhxFgglF_ix6"F4C,>F7-Fav6%F;FjjxFA>F`wFgix@$
4F_`o-FhizFev>FF-F\hl6$-Fav6&F7Q*/inidata_F4FAFb\mFahl-Fghl6$FF-Fav6%Q9function
~data~=~inidata_F4FAQ$()|+F4-Fghl6$FF-Fav6$F`wQ5data~=~cell([1,2]);|+F4-Fghl6$F
F-Fav6$F`wQ7data|fr1|hr~=~randn(3,6);|+F4-Fghl6$FF-Fav6$F`wQ7data|fr2|hr~=~rand
n(3,6);|+F4F^fyFhbmF4F4F46#FBF4,
I/write_test_numt+6)FaglFhpF]^oFat'F_cpF^t>F[`zF[_o>Fa`zFc`z6(FhhxFgglFe^pF_ix%
$fb2G%&vars2G6"F4CG>F7-Fav6%F]wFjjxFA>FivFgix>F^u-Fav6$FivFiv>Fcy-FL6$f*FbcxF46
$FRFSF4-Fav6$FAFAF4F4F4F[o@$F^[[lF_[[l>FF-F\hl6$-Fav6&F7Q+/test_num_F4FAFb\mFah
l-Fghl6$FFQ+rng(23);|+|+F4-Fghl6$FFQ-N~=~10000;|+|+F4-Fghl6$FF-Fav6'Q%Err_F4FAQ
+~=~[];|+Tm_F4FAQ)~=~[];|+|+F4-Fghl6$FFQ.for~i~=~1:N|+|+F4-Fghl6$FF-Fav6&FivQ0d
ata~=~inidata_F4FAQN();~%%~generate~initial~data~of~the~problem|+|+F4-Fghl6$FF-
Fav6$FivQ%try|+F4-Fghl6$FF-Fav6$F^uQ&tic;|+F4-Fghl6$FF-Fav6&F^uQ+C~=~coefs_F4FA
QV(data);~%%~compute~coefficients~of~polynomial~system|+F4-Fghl6$FF-Fav6,F^uFcy
Fi\y-Fhr6%-Fcaz6#/FgyF[_oF^[yF_[y&FjnF\oFb[y&FjnFbjnFd[yFAQA(C);~%%~solve~polyn
omial~system|+F4@$/FAQ1relpose_7p_fr_1sF4-Fghl6$FF-Fav6$F^uQinww~=~arrayfun(@(j
)~get_w(C,xx(j),yy(j),zz(j)),~1:length(xx));|+F4-Fghl6$FF-Fav6$F^uQ+tm~=~toc;|+
F4-Fghl6$FF-Fav6&F^uQ,if~isempty(F4FielQ2);~continue;~end|+F4-Fghl6$FF-Fav6$Fiv
Q*catch~ME|+F4-Fghl6$FF-Fav6$F^uQ+continue;|+F4-Fghl6$FF-Fav6$FivQ&end|+|+F4-Fg
hl6$FF-Fav6$FivQ)M~=~[];|+F4-Fghl6$FF-Fav6&FivQ0for~j=1:length(F4FielQ#)|+F4?(F
`wFBFBFc_lFD-Fghl6$FF-Fav6'F^u&F[oFajlFi\y&FcyFajlQ&(j);|+F4-Fghl6$FF-Fav6&F^uQ
%m~=~F4F\boFd]y-Fghl6$FF-Fav6$F^uQ6m~=~m/norm(m,'fro');|+F4-Fghl6$FF-Fav6$F^uQ=
M~=~[M;~norm(C*m.','fro')];|+F4-Fghl6$FF-Fav6$FivQ%end|+F4-Fghl6$FF-Fav6$FivQ.M
~=~sort(M);|+F4-Fghl6$FF-Fav6&FivQ0err~=~norm(M(1:F4F;Q,),'fro');|+|+F4-Fghl6$F
F-Fav6.FivFf_[lFAQ)~=~[Err_F4FAQ(~err];|+F4FivQ$Tm_F4FAQ(~=~[Tm_F4FAQ(~tm];|+|+
F4-Fghl6$FFF_d[l-Fghl6$FFQIfolder~=~fileparts(which('add_all.m'));|+F4-Fghl6$FF
-Fav6'QCsave(strcat(folder,'\_results\Err_F4FAQ-.mat'),'Err_F4FAQ%');|+F4-Fghl6
$FF-Fav6'QBsave(strcat(folder,'\_results\Tm_F4FAQ,.mat'),'Tm_F4FAQ&');|+|+F4-Fg
hl6$FF-Fav6)Q3fprintf('Problem:~F4FAQin.~Ave.~runtime:~%%0.1f~ms.~Med.~error:~%
%0.2e\n',10^3*mean(Tm_F4FAQ.),median(Err_F4FAFa_yFhbmF4F4F46#FgsF4,
I0write_histo_numt+6$Fagl>Fa`zFc`zFfjz6"F4C6>F7Fjjz>F`wFgix@$F^[[lF_[[l>FF-F\hl
6$-Fav6&F7Q,/histo_num_F4FAFb\mFahlF]h[l-Fghl6$FF-Fav6%QDload(strcat(folder,~'
\_results\Err_F4FAQ+.mat'));|+|+F4-Fghl6$FFQ-bwd~=~3e-1;|+F4-Fghl6$FFQ-nbins~=~
60;|+F4-Fghl6$FFQ9clr~=~[70~100~160]/255;|+F4-Fghl6$FF-Fav6%Q1err~=~log10(Err_F
4FAFi^y-Fghl6$FFQLhr1~=~histogram(err,nbins,'BinWidth',bwd);|+F4-Fghl6$FFQ6hr1.
FaceColor~=~clr;|+F4-Fghl6$FFQ7hr1.EdgeColor~=~clr;|+|+F4-Fghl6$FFQ8axis([-17~1
~0~1150]);|+|+F4-Fghl6$FFQVset(gca,'fontsize',54,'fontname','Times~New~Roman');
|+F4-Fghl6$FFQFset(gcf,'PaperPositionMode','auto');|+F4-Fghl6$FFQJset(gcf,'Pape
rOrientation','landscape');|+F4-Fghl6$FFQGset(gcf,'PaperPosition',[1~1~28~19]);
|+F4-Fghl6$FF-Fav6%QPprint(gcf,'-dpdf',strcat(folder,'\_results\fig-F4FAQ).pdf'
));F4FhbmF4F4F46#FBF4
