M7R0
I,readProblemt+6#'%%probG%'stringG6$%#fnG%"FG6"6"C'>8$-%$catG6%Q,problems/F_F,9
$Q#.mF,@$4-&%*FileToolsG6#%'ExistsG6#F/Y-F16%%&File~GF/%+~not~foundGAF/>8%-%$ma
pG6$%'expandG-%%evalG6#-F16$%#F_GF46$FE7#-%#opG6#-%'indetsG6#FEF,F,F,6#"""F,,
I+isLinIndept+6&'%"MG%%listG'%"GGFin'%%tordG%3ShortMonomialOrderG'%#ppG%'posint
G6$%%varsG%"SG6"F,C&>F/-FV6#9%@$/-%%nopsG6#F4FYO%%trueG>FE&-%,poly2matrixG6%-FG
6$f*6#%"mGF,6$%)operatorG%&arrowGF,-&%)GroebnerG6#%+NormalFormG6&F4T$T&/%/chara
cteristicGT(F,F,6(F[oFjoF]o9&F`o9'F4F]pF/6#FY-%#isG6#0-&&%.LinearAlgebraG6#%(Mo
dularG6#%%RankG6$F\rFE-Fcr6$F\r&FE6$;FY!"#;F,F,F,F,F,6#""%F,,
I*testBasist+6''Fhn%$setG'%$degGFaoFjnF\o'F`o%*nonnegintGFbo6"F,C&>F/-FV6#F[r@$
2F]pFjoO6$%&falseG-%$<,>G6#-Fht6#""!>FE&-Fep6%-FG6$f*FjpF,6$F]qF^qF,F_qF,F,6(F[
oF[rF]oF\rF`o9(F4F]pF/F]r6$-%#ifG6%0FfuF\u-F_r6#/-Fcr6$FfuFEFjo-F_r6#/-&FerFhrF
WFjoFEF,F,F,6#""&F,,
I*iniMonSett+6)'F*<%%'VectorGFinFhs'%#B0GFin'FcoFinFjnF\oF_o>'%$domGF\tF\u6*%"E
GFhn%#vrG%"dGFjs%%flagGFdo%&d_minG6"F,C*>8(-F^pFio>8+F\u>F/-%(convertG6$-FG6$FS
-&Faq6#%(SupportGF_pFhs-%&printG6#-F16%%<Polynomial~system~contains~G-F^pF=%+~m
onomialsG>FEF/?(8'F\uFYF,1,&FeyFYF`x!""9*C&>8&-%'selectG6$f*6#%"xGF,6$F]qF^qF,1
-%'degreeG6$F4FeqT%F,F,6&FcoF[rFgwFeyFE>FE-FG6$f*6#%"tGF,6$F]qF^qF,-FS6#-FG6$f*
6#%"kGF,6$F]qF^qF,*&FeqFYF4FYF,F,6$F_[lF4T#F,F,6$FfwF\zFE>6$8)8*-Fds6'FEF]xF\rF
fu9)@$4F_\l>F`x,&FeyFYFYFY-F\y6#-F16%%6Initial~set~contains~G-F^pFWFbyO6$F/FEF,
F,F,6#""(F,,
I-neighborMonst+6%'%"BGFhs'%#MBGFhsF`w6#%#nBG6"F,C&@$/F]pF\uOFjo>F/-F^z6%%%type
G-FG6$FS<#-%$seqG6$-Fh^l6$<$*&%"bGFY%"vGFhy*&F^_lFYF__lFY-%#inG6$F__lF[r-Fb_l6$
F^_lF4%)monomialG>F/-%*intersectG6$-%&minusG6$F/F4Fjo-Fiu6%/FayF\uFjoF/F,F,F,6#
""$F,,
I)genBasist+6)'FewFhsFgsF^wF`wFjnF\oF_o60%$rndGFf]l%#EBGFh]lFj]l%$nB1G%#bvGFg[l
%"aG%#nvG%#wtGF[q%"iGFjs6"F,C,>F/,$-I%randG6$%*protectedG%(_syslibG6#;F\u"%+5#F
YF[bl>FE<">FeyFjo>8--F^p6#F\r>81-F^pFat>F`\l7#-Fh^l6$-%&roundG6#-F/F,/80;FYFabl
>F`x-&%$maxG6#%&indexG6#-FG6$f*FazF,6$F]qF^qF,,&F4FY*&-F[\lF,FY$"$+"F\uFhyFYF,F
,6$Fh`lF/F`\l>8,&F\r6#F`x?(F,FYFYF,2F]]lFeblC*>Fey-F\`l6$FeyFE>F]x-Fb]l6%FEFeyF
\r>F\z-%&unionG6$F4FE>8.f*FazF,6$F]qF^qF,,*-Fiu6%-Fb_lFgzFYF\uFY-Fiu6%-Fb_l6$*&
FhzFYF4FYT'FYF\uFY-%$addG6$*&&T)6#T+FY-Ffz6$F4&T.FhflFY/Fifl;FYT/FY*&-T1F,FYF`d
lFhyFYF,F,62FewF4F\alFddlFi`lF\zF[alF`\lF_alF`clFcoF\rF]alFablFh`lF/>F_\l-%%sor
tG6$7#-FS6#F]xf*6$Fbz%"yGF,6$F]qF^qF,1-F[\lFio-F[\lF_pF,F,6$F^alFeel>6$8/F`cl6$
&F_\lF]rFY?(F,FYFYF,34-FZ6&7$-FSFWFfhlFfuFc\lFiy2F`cl-F^p6#F_\lC$>F`cl,&F`clFYF
YFY>Ffhl&F_\l6#F`cl>FE<$F_ilFfhlFEF,F,F,6#Fa]lF,,
I*saveBasest+6$F%'%$QBsG<$FinFhs6#%#fdG6"F,C%>F/-%&fopenG6$-F16$Q)bases/b_F,F4%
&WRITEG-FG6$f*FazF,6$F]qF^qF,-%(fprintfG6%F[\lQ$%a|+F,F4F,F,6$FcjlF/Fjo-%'fclos
eGF=F,F,F,6#""#F,,
I*readBasest+F$6%%#stGF`jlF)6"F,C(>F/FY>FE7">F\zFjjl@$4-F96#F\zY-F16%FAF\zFB?(F
,FYFYF,0F/F\uC$>F/-%)readlineGFh\m@$F]]m>FE7$F_il-%&parseGF=FEF,F,F,6#FYF,,
I,BasisFindert+6&F%>'%-deg_over_minGF\tF\u>'%1numbers_of_basesGFaoFadl>'%-prime
_numberGFao"&\F$6/F`oF*FcoF]oF[oF_wFgwFewFhn%#BBGFf]lF)Fcjl6"F,C0>F/-%*prevprim
eG6#,&F\rFYFYFY>FddlFc\m>FablFc\m>FfhlFjjl>6$FEF\z-F"F_p>Fey-%%tdegG6#-FSFh\m>F
]x-&Faq6#%&BasisG6%FEFey/FhqF/>F_\l&-&Faq6#%*NormalSetG6$F]xFeyF]r>6$F`xFddl-Fh
v6)FEF_\lF\zF]xFeyF/Fjo>F`cl-Fhjl6$FfhlF][m-Fh[mFhil>F`cl-Fhjl6$Ffhl%'APPENDG?(
F,FYFYF,2-F^p6#FablF[rC$>Feel-Fc`l6)F`xFddlF_\lF\zF]xFeyF/@$4-%'memberG6$FeelFa
blC%>Fabl7$-FSFfamFeel-Fc[m6%F`clFe[m-Fcx6$FeelFin-F\y6#-%(sprintfG6%Q%%d%sF,-F
\cl6#,$*&FeamFYF[rFhyFadlQ,%~completedF,F^amF,F,F,6#FYF,,
I*writeGfant+6$F%>Fb^mFd^m6&F`oF*FcoFcjl6"F,C(>F/-F[_m6#,&FjoFYFYFY>Fey-Fhjl6$Q
)gfan/igfF,F][m>Fb_mFc_m>FE-%$modG6$-FG6$FI-Fcx6$FEFhsF/-Fc[m6'FeyQ+Z/%aZ%a|+%a
F,F/F\zFE-Fh[m6#FeyF,F,F,6#FYF,,
I)readGfant+6#'F)F'6&FhwF^\m%"nGF`o6"F,C*>F/Fft>FEFY>F\zF\u@$4-F9F_pY-F16%FAF4F
B>FE-Fa]mF_p>Fey-Ff]m6#-%*substringG6$FE;Fb`l,&-&%,StringToolsG6#%.FirstFromLef
tG6$Q"[F,FEFYF`sFY?(F,FYFYF,0FEF\uC$>FEFdfm@(5/FEQ#|fr|frF,/FEQ"|frF,C%>F/Fap>F
\z,&F\zFYFYFY>(F[oF\zFc\m3F/0-Fifm6$FEFhyQ"|hrF,>Fchm7$-FS6#Fchm-Fifm6$FEF_s3F/
/FfhmFhhmC$>FchmFjhm>F/FftO6%Fey7#-Fh^l6$-FG6$Ff]m(F[oF_al/F_al;FYF\z7#-Fh^l6$-
FG6$f*FazF,6$F]qF^qF,-Ff]m6#-Fifm6$F4;FY,&-F^gm6$Q"+F,F4FYFhyFYF,F,F,F[jmF\jmF,
F,F,6#FYF,,
I(writeCMt+6$F%>Fb^mFd^m6*F`oF^\m%$Ws0GF)FcjlF*Fco%#WsG6"F,C:>F/F\dm>FEFY>F\zFc
\m>Fey-F16$Q+weights/w_F,F4@$4-F9F`emY-F16%FAFeyFB?(F,FYFYF,FegmC$>FE-Fa]mF`em@
$Fegm>F\z7$Fh_m-Ff]mFW>F`x-&F_gm6#%.SubstituteAllG6%-F_]n6%-Fcx6$F\zF'FcgmQ"(F,
Q"]F,Q")F,>F^\lFc_m>F`\l-Fcx6$F`\lF'>F_\l-Fcx6$-Ffdm6$-FG6$FIF_\lF/F'>F]x-Fhjl6
$Q'cm/icmF,F][m-Fc[m6'F]xQ<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+F,F`xF/F`\l-Fc[m6%F]xQ
6f~=~openOut~"cm_%s";|+F,F4-Fc[m6$F]xQ<f~<<~toString(pp)~<<~endl;|+F,-Fc[m6$F]x
Q<f~<<~toString(vr)~<<~endl;|+F,-Fc[m6%F]xQ9for~i~from~0~to~%a~do~(|+F,,&-F^pFh
\mFYFhyFY-Fc[m6$F]xQ>f~<<~toString(Ws#i)~<<~endl;|+F,-Fc[m6&F]xQ.R~=~ZZ/%a%s,~F
,F/-Fifm6$F`\lF_s-Fc[m6$F]xQDMonomialOrder~=>~Weights~=>~Ws#i];|+F,-Fc[m6%F]xQ0
I~=~ideal(%s);|+F,-Fifm6$F_\l;Fj[mF`s-Fc[m6$F]xQVG~=~gb(I,ChangeMatrix=>true);|
+M~=~getChangeMatrix~G;|+F,-Fc[m6$F]xQ>f~<<~toString(M)~<<~endl;|+);|+F,-Fc[m6$
F]xQ,f~<<~close;F,-Fh[mF[hlF,F,F,6#FYF,,
I'readCMt+F$6(F^\mF)F`oFcoF[qFgem6"F,C+>F/FY>FE-F16$Q'cm/cm_F,F4>F]xF\u>F_\lF\u
@$4-F9FWY-F16%FAFEFB>F\z-Ff]m6#-Fa]mFW>FeyFibn?(F,FYFYF,F]]mC$>F/F[cn@&3F]]m/-F
ifm6$F/FYFg]nC$>F]x,&F]xFYFYFY>(%"TGF]x-Fifm6$F/Fj`n3F]]m/-Fifm6$F/;FY""'Q'matr
ixF,C$>F_\l,&F_\lFYFYFY>(%#CMGF_\l-F_]n6%-F_]n6%-Fifm6$F/;""*F`sF]hmFcgmFhhmFh]
nO6%F\z7#-Fh^l6$-%%wdegG6$7#-Ff]m6#(FjcnF_alFey/F_al;FYF]x7#-Fh^l6$)-%'MatrixG6
#7#-FG6$Ff]m(FidnF_al%#%TG/F_al;FYF_\lF,F,F,6#FYF,,
I(getTordt+6$%#gbG%#lmG6+FcoF]al%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG%$solG%(
weightsG6"F,C,>F/7#-FS6#-FVF_p>FEFay>F\z/7#-%"$G6$F\uFE%%NULLG>Fey7#-Fh^l6$(Fgw
F_al/F_al;FYFE>F]x-FG6$f*6#%"zGF,6$F]qF^qF,-FG6$f*FazF,6$F]qF^qF,7#-Fh^l6$-Ffz6
$F4F^hl-Fb_l6$F^hlF[\lF,F,6$FcoF[\l-Fcx6$F4FinF,F,6$FcoF/F4>F_\l-FG6$f*FazF,6$F
]qF^qF,F]jnF,F,FgjnFjo>F`\l-FG6$f*Ff[lF,6$F]qF^qF,-FS6#-FG6$f*FazF,6$F]qF^qF,1F
Y-Fcfl6#-%$zipG6%f*6$F^hlFginF,6$F]qF^qF,*&F4FYFjoFYF,F,F,F4F[\lF,F,6$FfgnFgfl-
%%subsG6$F[\l7#-Fh^l6$,&&FhzF_pFY%"gGFhy-Fb_l6$F[]o&FaflF_pF,F,6*FegnF\zFhgnF_
\lFggnF]xFfgnFey<#-Fhhn6#;FYF]p>F`x&-&%-OptimizationG6#%)MinimizeG6&-FcflF`emF`
\l/%+depthlimitG"#S/%'assumeGF\t6#Fj[m>Fddl-Fd\o6$F`xFey6$Fddl-Fhen6$FddlF/F,F,
F,6#Fj[mF,,
I-writeWeightst+6&F%>'%3numbers_of_weightsGFaoFadl>Fb^mFd^m>'%+rand_rangeG7$Fao
Fao7$"$+#"$+)6/F`o%#GsG%$LMsG%#WWG%%gffnGF)Fcjl%"WGF*FcoFh`lF]oF[o6"F,C&>F/-F[_
m6#,&F[rFYFYFY>F]x-F16$Q)gfan/gf_F,F4>F_\lF\\n@%-F9F[hlC(-F\y6#%IGenerating~wei
ght~vectors~from~Gfan~fileG>6%F/FEF\z-FbemF[hl>Fey7#-Fh^l6$&-F_gn6$&FE6#F_al&F
\zFjaoF]r/F_al;FYF]]l>F`\l-Fhjl6$F_\lF][m?&F`xFeyFap-Fc[m6%F`\lFe[mF`x-Fh[m6#F`
\lC+-F\y6#-F16%%AGfan~file~not~found.~Generating~GFjo%7~random~weight~vectorsG>
6$FddlFablFc_m>FeyFc\m>Feel-Feal6#;&F\rF]r&F\rFb^o>F`\lF_boFdbo>F`\l-Fhjl6$F_\l
Fbam?(F,FYFYF,2-F^pF`emFjoC&>Ffhl-Fhen6$7#-Fh^l6$-FeelF,/F_al;FYFeamFabl>F`cl-F
[`m6%FddlFfhlF_`m>F`x&-F_gn6$F`cl-&Faq6#%0LeadingMonomialG6$F`clFfhlF]r@$4-F^bm
Fe^oC%>Fey7$-FSF`emF`xFbbo-F\y6#-F[cm6%F]cm-F\cl6#,$*&F\doFYFjoFhyFadlFbcmFdboF
,F,F,6#FYF,,
I)saveDatat+6-F%'%#mnGFd_o'%#spG%(numericGF_o'FcoFajl'%#avGFf_lF\o'%#QBGFin'%'s
hiftsGFin'%%polsGFin'%$stdG%(booleanG6'F)Fcjl%$mn0G%$sp0GFhw6"F,C&>F/-Fiu6%9.-F
16$Q-optim/o_std_F,F4-F16$Q.optim/o_nstd_F,F4>F]xFft@%F8C'>FE-Fhjl6$F/%%READG>F
\z-Ff]m6#-Fa]mF=>FeyF^io@$52&FjoF]r&F\zF]r3/FeioFfio2FeyF[r>F]xFap-Fh[mFW>F]xFa
p@$F]xC%>FE-Fhjl6$F/F][m-Fc[m6.FEQ>%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%aF,FjoF
[rF\r-Fcx6$FfuFinFc\lFiy9+9,9-Fc\mF[joF,F,F,6#"#6F,,
I)readDatat+6$F%Fdgo6.F)FcjlFgfoFifoF`oFcoF]goF]oF_goFagoFcgo%$xE0G6"F,C1>F/-Fi
u6%FjoF`hoFcho@$F7YF?>FEFjho>F\zF^io>FeyF^io>F]xF^io>F_\lF^io>F`\lF^io>F`xF^io>
FddlF^io>FablF^io>FeelF^io>FfhlF^ioF[jo6,F\zFeyF]xF_\lF`\lF`xFddl-FG6$FKFablFee
lFfhlF,F,F,6#Fj[mF,,
I*eigSolvert+6%F[w>'%'actvarG%(integerGFY>'%'digitsGFao"#:6,%%fB2CGFcoF\alF]oFf
]lFjsF[oFjcn%"VGFdo6"F,C/>FEF_hn>F\z&FEFio>Fey-Ff_m6#F_il>F/t+6$%"fGFf]lF^[l6"F
,C$>F/-%&tableG6#-F\\o6%f*6$F\alF^_lF,6$F]qF^qF,/FjoF4F,F,F,7#-%'coeffsG6%F4Fjo
.F[q7#F[q-FG6$f*6#F^_lF,6$F]qF^qF,-Fiu6%-%)assignedG6#&F[\lF_pF]`pF\uF,F,6$F_[l
F/FjoF,F,F,6#Fj[m>%'DigitsGF[r>F`\l-F[`m6$F4Fey>F]x&-Fc`m6$F`\lFeyF]r>F_\l-F^pF
[hl-F\y6#-F16%%@The~system~is~expected~to~have~GF_\l%'~rootsG>F`x-&Faq6#%5Multi
plicationMatrixG6'F\zF]x-Fe^p6#-%'EquateG6$F]x7#-Fhhn6#F]gnF`\lFey>Fddl&-&Fer6#
%-EigenvectorsG6#-%&evalfGFfdlFb^o>Fddl-&%"|irG6#_F,%"/G6%Fddl%#~$G-%".G6$-F]w6
$F_\l/%%fillGFY&FddlF]r>Fabl-Fbcp6$-Fefn6#-FG6$f*6#F__lF,6$F]qF^qF,-Fgfl6$-F`q6
%F4F[\lFhzFaflF,F,6*F[oF`\lF]oFeyFf]lF]xFc]pF/FEFddlF,F,F,6#FYF,,
I$srtf*6$'F__lF\wF\oF,6$F]qF^qF,-Fggl6$F4f*F]hlF,6$F]qF^qF,-&Faq6#%*TestOrderG6
%FjoF4FeqF,F,6$F]oFjoF,F,F,F,,
I,poly2matrixt+6%F[w'%#nFGFaoF[go6$%%monsG%%cffsG6"F,C$>FE7#-F__p6%-FI6#-Fcfl6$
*&(%$q_qGF_alFY&F4FjaoFY/F_al;FYFjoF[r.F/6$-Fefn6%FjoF]]lf*6$F_al%"jGF,6$F]qF^q
F,-%&coeffG6$&F[\lFio(F\gpF4F,F,6$F_fpFE-F]w6#7#F/F,F,F,6#Fb`lF,,
I/permuteColumnst+6%'FhnFefn'%#V1GF]w'%#V2GF]w6#Fgem6"F,C$>F/-FS6$FYFjo-Fbcp6$F
4-Fefn6$F/<#-Fh^l6$/6$F_al-&%*ListToolsG6#%'SearchG6$&FjoFjaoF[rFY/F_al;FYF/F,F
,F,6#Fb`lF,,
I)sparsityt+6#Fehp6#%&numzrG6"F,C$>F/-F^p6#-F^z6$f*FazF,6$F]qF^qF,-F_r6#/F4F\uF
,F,F,Fejn*&F/FY-%$mulG6#-FS6$FYF4FhyF,F,F,6#FYF,,
I(matrixSt+6''Ff]lFinF^wFjnF\oF[t6%Fdo%#V0GFjs6"F,C&>F\zF]p@$0F^xF\zY%ILists~B0
~and~B~must~have~the~same~lengthG>F_]l-Fep6%-FG6$f*Ff_pF,6$F]qF^qF,F_qF,F,FeuF4
F\zF`t@%/-FS6$FYFEF\zO-Fbhp6%F/FE-F]wFioY%=Failed~to~construct~matrix~SGF,F,F,6
#FgvF,,
I*quotientst+6&'F[]o%(polynomGFjnF\oF[tF,6"F,C$-F`q6'F4FjoF[r.%"QG/FhqF\rFd^qF,
F,F,6#FcsF,,
I-monPartitiont+6'F\go'%#GrGFinF\oF[t>F^goFc\m6,F_wFf]l%#aBG%"RG%#B2G%#RBGF[o%#
nGGFjcnFdo6"F,C->F/&-Fc`m6$FjoF[rF]r>FE-Fcx6$-Fiu6%/FfuFc\mF/FfuFhs>F\z-FG6$f*F
azF,6$F]qF^qF,Fi[lF,F,6$F]goF4FE>Fey-Fidp6$-Fcx6$-F\`l6$F\zFEFinF[r>F`xF\do>F]x
-FG6$f*FazF,6$F]qF^qF,*&F4FYFeqFhyF,F,Fd`q-Fi_lF[aq>FE7$-FS6#-Fidp6$-Fcx6$-F\`l
6$FEF]xFinF[r-FS6#-Fidp6$-Fcx6$F]xFinF[r>6$F_\lF\z6$7$FieoF_il-FG6$f*FazF,6$F]q
F^qF,Fi[lF,F,Fd`qFE@%F^`q>Fddl-Fcap6(F4FE-Fe^p6#-Fjap6$FE7#-Fhhn6#F]boFjoF[rFe^
qC%>Fddl-Fcap6(F4F/-Fe^p6#-Fjap6$F/7#-Fhhn6#;FYFayFjoF[rFe^q>Fabl-F[\q6'FEF/Fjo
F[rF\r>Fddl-Fiu6%0F\rF\u-Ffdm6$-Fbcp6%FablFddl-&Fdr6#%(InverseG6$F\rFablF\r-Fbc
p6%FablFddl-&Fer6#%.MatrixInverseGFfam>F`\l-Fcx6$,&-F]wF`emFY-Fbcp6$&Fddl6$;FYF
`xFas-F]wFWFhyFinO6(F\zFEF_\lFddlF`\l-Fefn6#7#-Fh^l6$-Fj]q6&&F`\lFjaoFjoF[rF\r/
F_alFbfqF,F,F,6#FgvF,,
I)matrixHit+6&F[wFjnF[goF[t6/%*undetPolyG%#pvGF\fpFb_q%#uHG%%leqsGFjgnF_al%#dFG
%#dGGFgwFiw%"hG6"F,C)>FE-FcflFat>F\zF]p>FeyF^x>Fddl-FG6%FfzF4F[r>F/t+6&F[goFegq
FgwFfgp6#F^fp6"F,C%-F__p6%-FI6#,&FYFY-Fcfl6$)Fjo%"pG/Fbiq;FYF[rFYF4F`gp>F/F`hp-
Fcfl6$*&&F/Ff[lFY&%#_vG6$F\rFg[lFY/Fg[lFbdqF,F,F,6#Fcs?(F`xFYFYFeyFapC%>6$FfhlF
abl6$F\u-FG6$f*FazF,6$F]qF^qF,-Fecl6$F\uF4F,F,F,,&7#-Fhhn6$-Ffz6$&FjoFfdlF[rF\z
FYFddlFhy?(FeelF\uFYF,1,&FeelFYFfhlFhyF\uC&>F]x7#-Fh^l6$-F/6&F[rFE,&&Fabl6#Ffgp
FYFeelFYFfgp/FfgpF]jm>F_\l<#-F__p6$-FI6#,&F`[rFhy-Fcfl6$*&&F]xF]\rFY&F4F]\rFYF^
\rFYF[r>F`\l-%'msolveG6$F_\lF\r@$/-F^p6#<#F`\lF\u>Ffhl,&FeelFYFYFY>&F`clFfdl-Ff
dm6$-FG6%-%"@G6$FIFKF]xF`\lF\rO-Fht6#-Fh^l6$-&F]w6#%$rowG6#Fg]r/F`x;FYFeyF,F,F,
6#FcsF,,
I*matrixHnit+6(F[wFjn'%"CGFefn'FidnFefnF[goF[t6*%,undetPolyniGF\fpFb_q%#H0GFfgq
FggqFjgn%%parsG6"F,C+>FEF]p>F\zF^x>F/t+6&'FjgqF^^qF[go'F_alFao'FfgpFaoFghq6"F,C
%-F__p6%F4FjoF`gp>F/F`hp-Fcfl6$*&FiiqFY&F[jq6%F[rF\rFg[lFYF]jqF,F,F,6#Fcs>Fey-F
fdm6$-FG6$FI-Fbcp6$F[rF\rFc\l>F]x-Fefn6%F\zFEf*FegpF,6$F]qF^qF,-Fafl6&&F[\l6$F4
FjoFfqF4FjoF,F,6(Fd_rFeyFcoFfuFc_rF/>F`x<#-Fh^l6$&%#_uGFjao/F_al;FY-F^p6#-F\`l6
$-FVF[hlFfu>F_\l-FG6%F__p<#-Fh^l6$-Ffdm6$-FI6#,&F_jpFhy-Fcfl6$*&&F]xFegpFYFj\rF
Y/FfgpFainFYFc\lF\jmFfu>F`\l-F]]r6%F_\lF`xFc\lO-Ffdm6$Fj]rFc\lF,F,F,6#FbdnF,,
I*syzModulet+6'F[wFjn'%"AGFefnF\oF[t6*F\fpFb_q%"eG%"LG%#LtGFhnFdoFf]l6"F,C.>F/F
]p>FEF^x>F\z-Fh^l6$-F]w6$FE<#/F_alFYF`in>Fey7#-Fh^l6$7#-&Faq6#%,LeadingTermG6$F
_jpF\rF`in>F]x-FG6$f*FazF,6$F]qF^qF,*&&F4F]rFY&F4Fb^oFYF,F,F,Fey>F_\l-Fefn6$FEf
*FegpF,6$F]qF^qF,*&-%$lcmG6$&F]`pFb^o&F[hpFb^oFYFj\oFhyF,F,6&FgdrFeyFhdrF]x>F`
\l7#-Fh^l6$-Fh^l6$,(*&&F_\lFegpFYF[boFYFY*&&F_\l6$FfgpF_alFY&F\zF]\rFYFhy-Fht6#
-Fj]q6&z'6&FjgrF\hrF_jp&FjoF]\r[[[\[[[[[\[[mFY\[[[[[\[[[[[mFhyFjoF\rFfuFhy/Ffgp
;,&F_alFYFYFYFEF`in>F`\l)-FefnFeboF[gn>F`x-Fefn6#7#-Fh^l6$-Fj]q6&F]gpFjoF\rFfuF
`jp>F`\l-FG6$FI-Fht6$-Fbcp6$F`\lF[r,&-&Fer6#%/IdentityMatrixGF=FY-Fbcp6$F`xF[rF
hy@$F[v>F`\l-Ffdm6$F`\lFfuO&F`\l6$-%'removeG6$f*FjaoF,6$F]qF^qF,-&%+ArrayToolsG
6#%'IsZeroG6#&F[\l6$F4FasF,F,6$FdoF`\l7#-Fhhn6#;FY-FS6$7$FYFYF`\lFasF,F,F,6#Fgv
F,,
I+matrixHsyzt+6(F[wFjnF__rFcdrF\oF[t6$Fdo%&ThetaG6"F,C%>F/-F`dr6'F4FjoF\rFfuFc
\l>FE-Fefn6%-FS6$F]\sF[r-FS6$F]\sF/f*FegpF,6$F]qF^qF,&F_[lFjarF,F,F,O-Ffdm6$-FG
6$FI,&F`arFY-Fbcp6$FEF/FYFc\lF,F,F,6#FbdnF,,
I(supportt+6$'F`^pF^^qF[goF,6"F,C$F^_p<#F[qF,F,F,6#Fj[mF,,
I,fixTemplatet+6'%'admonsGF[wF[go'%$monGFin'Fa_qFin6/F\fp%%monFG%&admonGF_alFfg
pFd^qFhw%#xFGFhnF`\qFewFd]p%%mon1G6"F,C.>F/F^x>FE-FG6$f*6#F`^pF,6$F]qF^qF,-F\^s
FgzF,F,6$FcoF[rFjo>F\z7#-Fhhn6$F^blF/?(FeyFYFYF]pFapC%>F`\lFft?(F]xFYFYF/FapC$>
F_\l-FG6$f*6#%#mfGF,6$F]qF^qF,-Fiu6%-%'divideG6%&Feq6#FhzF4.%"qGFcasFjhnF,F,6&F
g^sF4F_alFey&FEF[hl@$0F_\lF^blC%>&F\zF[hl<$Fhhl-FS6#Fjas>F`\lFap[@$4F`\lY%;Fail
ed~to~correct~templateG>F`cl7#-Fh^l6$-Fcx6$-Fbel6$-Fcx6$&F\rF[hlFhsFjasF]w/F]xF
ajp>F`x7#-Fh^l6$-Fh^l6$*&&FjoF[hlFYFgfoFY-Fb_l6$Fgfo&F`clF[hlF_cs>F^co-Fep6%F`x
-F^pFfdlF[r>Feel-F\`l6$-Fcx6$FablFhs-Fcx6$FfuFhs>Feel-Fidp6$7#-FS6#Feel-Ff_m6#-
FSFat>Ffhl-Fht6$Fjds-FS6#Ffu-F\y6#%/Template~fixedGO6&F`clFddlFablFfhlF,F,F,6#F
gvF,,
I2constructTemplatet+6&'%"HG<$FefnFinF[wF[goFj^s6)F\fpFi^sF^_sFhnF`\qFewFd]p6"F
,C+>F/F^x>FE-Fiu6%-Fc^l6$F4Fefn7#-Fh^l6$&-Fep6%&F46$FasFfgp-FS6$F]\sF4F[rFb^o/F
fgpFajpF4>F\z7#-Fh^l6$-Fh^l6$*&FehrFYFgfoFY-Fb_l6$Fgfo&FEF]\rFcgs>6$FeyF]x-Fep6
%F\zFi_nF[r>F_\l-F\`l6$-Fcx6$F]xFhs-Fcx6$F\rFhs>F_\l-Fidp6$7#-FSFbilF\es>F`\l-F
ht6$F]is-FSFcbl@$0-FS6$FYF`\l-FS6$FYF]xC$-F\y6#%7Template~is~incompleteG>6&FEFe
yF]xF`\l-Fd^s6'-F\`l6$-Fcx6$F`\lFhsFehsFjoF[rFEF\r6%FE-Fbhp6%FeyF]xF`\lF`\lF,F,
F,6#FcsF,,
I-adjustParamst+6'F[w'F^fsFefnFj^s'FcoFhsF[t63F\fpFb_q%#H1G%#LmG%%colsGFgdrFi^s
F`\qFewFfdr%#smG%#rmG%#npG%#ssG%$prmGFggqFjgn6"F,C3>F/F]p>FE-FS6$F]\sFjo>F\zFjo
>Fey-Fh^l6$-Fep6%&FjoF`gsFEF\rFcgs>F]x7#-Fh^l6$-Fjjr6$f*FazF,6$F]qF^qF,-%+membe
rtypeG6$Fao-Fcx6$&&F[\l6#,&FfgpFj[mFhyFY6$FasF4FinF,F,6$F_[tFey7#-Fhhn6#;FY-FS6
$7$FYFj[m&FeyFb]tFcgs>F^\l6$7#-Fh^l6$&F]^t6$FasFi\rFcgs7#-Fh^l6$&&Fey6#,$FfgpFj
[m6#Fi\rFcgs>Feel7#-Fh^l6$-FG6$f*F^[lF,6$F]qF^qF,-F\^s6$-FI6#*&&FeqF]\rFYF4FYFf
qF,F,6&F*F4FcoF\r&F`\lF]\rFcgs>F`x-Fcx6$-FG6$FS-FG6%-F]^r6$FSFcxFeelFhsFhs>Fddl
-Fcx6$-F\`l6$F`x-Fcx6$F[rFhsFin>Feel-F]wF[es>Ffhl-FG6$f*6#FfdrF,6$F]qF^qF,-F^z6
$f*FjaoF,6$F]qF^qF,-F^bm6$FeqFj\oF,F,6&FfdrF4Fa[tF[\l<#-Fhhn6#;FY-FS6$FYF[\lF,F
,6$Fa[tFeelFddl>F`cl7#-Fh^l6$-%"+G6#-Fh^l6$-F^p6#-F^z6%%$hasGFfhl&&FfhlF]\rFjao
/F_al;FY-F^p6#Fbct/Ffgp;FY-F^p6#Ffhl>Feblf*6&F_alFfgpFb[tFc[tF,6$F]qF^qF,52-F^p
6#&F[rFio-F^p6#&F[rF_p3/FddtFadt2&F\rFio&F\rF_pF,F,F,>82-Fggl6$7#-Fhhn6#;FY-F^p
6#Fddlf*FegpF,6$F]qF^qF,-Fafl6&F4FjoF[\lFhzF,F,6(Fb[tFfhlFc[tF`clFd[tFebl>Fddl&
Fddl6#F]et?&FablFddlFapC+>Fey-Fh^l6$-Fep6%&F\zF`gsFEF\rFcgs>F^\l6$7#-Fh^l6$F]^t
Fcgs7#-Fh^l6$Fi^tFcgs@$/-F^p6#-FVFbilF\uF_bs>Feel7#-Fh^l6$-FG6$f*F^[lF,6$F]qF^q
F,Fe_tF,F,F[`tF\`tFcgs>Ffhl-FG6$f*FazF,6$F]qF^qF,<#-&F[jp6#%*SearchAllG6$FY-FG6
$f*6#F^hlF,6$F]qF^qF,-F^p6#-Fi_l6$F4<#F[\lF,F,6$FfdrF[\lF4F,F,6$FfdrFablFeel>83
<#-Fh^l6$-FS6#-FG6$f*Ff[lF,6$F]qF^qF,-FS6#-Fcx6$&&F[\lF]\rFd]tFhsF,F,6$FgdrF_\l
FbctFcgs>84-F]]r6$FcitFfu@$/-F^p6#<#FejtF\u\>F\z-Ffdm6$-FG6%F\^rF\zFejtFfu-Fjes
6&F\zF4F\rF[rF,F,F,6#FgvF,,
I4isActionMatrixFoundt+6('FjcnFefnFehp'F^_qFinF^\q'Fb_qFaoF[t6'%#tMG%#T1GFjsF[q
%"rG6"F,C'>F\zFbbl>Fey,&F\zFYFfuFhy>F/-Ffdm6$-%*GaussjordG6$Fjo.F]xFc\l>FE-Ffdm
6$-Fht6$,$&F/6$;,(F]xFYFfuFhyFYFYF]x;,$F\zFhyFhyFhy-Fefn6%FeyF\z<#-Fh^l6$/6$,(F
eyFYFg[lFhyFYFY-Fjip6$&F[r6#,$Fg[lFhyF\rFY/Fg[lFj^rFc\l-&Fer6#%&EqualGFcelF,F,F
,6#FbdnF,,
I/SchurReductiont+6(Fehp'Fd]pF]wFago'%#nEGF\tF_oFbgo66%#rgG%$crgGF[q%#M1G%#bsG%
#M2G%$tM2GF_\u%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GF`_q%#B3G%#B4G%$iB1G%&rperm
G%&cpermG6"F,C6@$/-F^p6#Fc\lF\uO6'F4FjoF\uFc\mFc\m>F/7#-Fh^l6$-FS6#7#-Fhhn6#;,&
-Fcfl6$-FS6$FY&F[rFjao/F_al;FY,&FbiqFYFhyFYFYFYFY-Fcfl6$Fhau/F_al;FYFbiq-Fb_l6$
FbiqFc\l>F\zFay>FE7#-FS6#-F\`l6$<#-Fhhn6#;FYFags<#-FSF=>Fey-Fht6$&F46$F/Fas&F46
$FEFas>F_\l&Fey6$F]jm;FYF\r>F`\l-Ffdm6$-Fi\u6$)F_\lF[gn.F`xFfu>Ffhl-FG6$f*FjaoF
,6$F]qF^qF,-Fjip6$FY-Fcx6$F]`pFinF,F,6$Fg_uF`\l<#-Fhhn6#Fbfq>F`cl-Fcx6$-F\`l6$<
#-Fhhn6#;FY-FS6$F\^tF`\lFfhlFin>86-Fcx6$7%-FSFjct-FSFhil-Fhhn6#;Fahm-FS6$F]\sFe
yFin>F\fu&7$F`cuF_il6#F\fu>Fddl-Fht6%&Fey6$7#F`fuFas&Fey6$7#FafuFas&Fey6$;FahmF
hyFas>Fabl-Ffdm6$-Fi\u6$&FddlFjcuFbduFfu>Ffhl-FG6$f*FjaoF,6$F]qF^qF,FhduF,F,6$F
i_uFablF]eu>F`cl-Fcx6$-F\`l6$<#-Fhhn6#;FY-FS6$F\^tFablFfhlFin>877%F`fuFafu-Fhhn
6#;F]_m-FS6$F\^tFddl>Feel-%$<|gr>G6%&Fddl6$FasF`gu&Fddl6$FasFcgu&Fddl6$Fas;F]_m
Fhy>6&FeblF]etFcitFejt6&&Feel6$FbfqFbfq&Feel6$Fbfq;,&F`xFYFYFYFhy&Feel6$FhjuFbf
q&Feel6$FhjuFhju>85-F_eq6$FfuFebl6'-Ffdm6$,&FejtFY-Fbcp6%FcitF_[vF]etFhyFfu&Fjo
6#7$Fafu-Fhhn6#;F]_mF^ipF`xF\fuF_iuF,F,F,6#FbdnF,,
I0LinDepReductiont+6$FehpF[t6)F_\uF]\uFd_u%$tM1GF[`u%&r2delG%&c2delG6"F,C*>FE-F
fdm6$-Fi\u6$)F4F[gnF`gpFjo>F]x-FG6$f*FjaoF,6$F]qF^qF,FhduF,F,6$F]\uFE<#-Fhhn6#F
ajp>F_\l-Fcx6$-F\`l6$<#-Fhhn6#;FY-FS6$F\^tFEF]xFin>F\z&F46$-Fjjr6$f*FjaoF,6$F]q
F^qF,-F_r6#-Fb_l6$F4F[\lF,F,6$Fd\vF_\l7#F\cuFas>Fey-Ffdm6$-Fi\u6$F\zF`gpFjo>F]x
-FG6$f*FjaoF,6$F]qF^qF,FhduF,F,6$Fc\vFeyFd]v>F`\l-Fcx6$-F\`l6$<#-Fhhn6#;FY-Fecl
F[hlF]xFin6%&F\z6$Fas-Fjjr6$f*FjaoF,6$F]qF^qF,Fi^vF,F,6$Fe\vF`\l7#-Fhhn6#;FY-FS
6$F\^tF\zF_\lF`\lF,F,F,6#Fj[mF,,
I)rectTordt+6&F[wF`w'%#TsGFinF[t6(F\fp%#dgGF^al%#nnG%$GBsGFe[n6"F,C+>F/F]p>FE7#
-Fh^l6$*&-Fcfl6#-FG6%FfzF4FfwFYF/Fhy-Fb_l6$FfwFjo>F\z-FG6$f*6#FgwF,6$F]qF^qF,*$
F4FhyF,F,F,FE>Fey-F]gr6#-FS6#-FG6$%&denomGF\z>F\z*&FeyFYF\zFY>F]x-FG6$f*FazF,6$
F]qF^qF,-F[`m6%FeqF4/FhqFfqF,F,6&F*F4F`oF\rF[r>F_\l7#-FS6#<#-Fh^l6$&-F_gn6$&F]x
Fjao-F_eo6$F^evFjauF]r/F_al;FYFj`p>F_\l-FG6$f*FfinF,6$F]qF^qF,-F\\o6%f*F]hlF,6$
F]qF^qF,Fa\oF,F,F,F4F[\lF,F,6$F^alF\zF_\l-FG6$f*FazF,6$F]qF^qF,-FhenFgzF,F,6$Fc
oFjoF_\lF,F,F,6#FcsF,,
I,filterBasest+6&F[w'F`jlFin'%%nQBsGFao'%#ffGFjfo6&%#mFG%#BsGFe[t%"NG6"F,C(>Fey
-F\cl6#*&F\rFYF[rFY>F/-Fcx6$&-Fep6%F4F]pFbhnFb^oFhs>FE-FG6$f*FazF,6$F]qF^qF,-F^
p6#-Fi_l6$-Fcx6$F4FhsF[\lF,F,6$F]gvF/Fjo>F\z-Fggl6%FE%">G/%'outputG%,permutatio
nG-F\y6#-F16$Fey%>~quotient~space~bases~removedG7#-FS6$;FY,&F[rFYFeyFhyF\zF,F,F
,6#FcsF,,
I-filterBases2t+6*F[fpF[go%$CMsGF[bvFgavF`jlF_oFjfv69F[_qF]oFf]lFidnFifvFjsF_al
%#vBG%#tBG%#mpGF]goF^_qFjcnF[oF`_rF^fs%$cHsGF[q%$avoG%#msG%#moGFe[tF_gv6"F,C+>F
]xFfbl>F_\l-F^p6#&Fc\lF]r>F_iuFc\m>88"(+++">8:-F\cl6#*&FgjoFYF]xFY?(F`\lFYFYF]x
FapC(>6&F/FEF\zFey6&&F\rFebo&FfuFebo&Fc\lFebo&F[rFebo@$0Fi_nF_\lF][u>6%F`xFddlF
abl6%-F]wFh\m-Fe^p6#-Fjap6$F\zF\bpF`[w?&FeelFjoFapC*>Ffhl-FG6$f*6#FgfoF,6$F]qF^
qF,*&F4FYF[\lFYF,F,6$F]goFeelF\z>F`cl-Fcap6(FeelF\zFddlF/FE/FhqFiy>Febl,&-F]wFj
ctFY-Fbcp6$F`clF`xFhy>F]et-Fefn6#7#-Fh^l6$-Fj]q6&&FeblFf[lF/FEFiy/Fg[lF]gn>Fcit
-Ffdm6$-FG6$FI-Fbcp6$F]etFeyFiy>Fejt7#-Fh^l6$-Fcfl6#&Fcit6$FasFg[l/Fg[l;FYF4>F_
[v-Fcfl6$-Fiu6%-Fc^l6$%"cGFhbt-F^p6#F^`wFY-Fb_l6$F^`wFejt@$2F_[vFablC$>FablF_[v
>F\fuFeel@$2FablF_[wC$>F_[wFabl-F\y6#-F[cm6%Q>Smaller~template~found:~%d,%aF,F_
[wF\fu>F_iu7$-FS6#F_iuFabl>89-Fggl6%F_iu%"<GF\iv-F\y6#-F16$Fb[wFciv7#-FS6$;FY,&
F]xFYFb[wFhyFfawF,F,F,6#"")F,,
I(iniProbt+6&F%FdgoFjfv'%#pnGFao60F*%#vFGF`oFcoF[bvFgav%#GCGF`jlF]jvF]oFidnF[oF
casFifv6"F,C,>F\zF\r>6$F/FeyFc_m>6$FEFey6$-F]wF=<#Fieo>Fabl-Ff_m6#Fieo-F\y6#-F1
6%%;The~problem~is~defined~by~GFay%-~polynomialsG>Ffhl-F[`m6%F/Fabl/FhqF\z@$0-&
Faq6#%1HilbertDimensionG6$FfhlFcdwF\uYQZThe~problem~is~expected~to~have~infinit
ely~many~solutionsF,-F\y6#-F16(%,Variables:~G7#Fieo%,;~degrees:~G-FG6$FfzF/%8;~
number~of~solutions:~G-F^p6#&-Fc`mFbjqF]r@%FjoC)>6%F\zF_\lFddl-FfanF_p>FeblFdet
-F\y6#-F16$Febl%8~change~matrices~loadedG>F]x7#-Fh^l6$-Ffdm6$-FG6$FI-Fcx6$-Fbcp
6$&FddlFjaoFEFinF\z/F_al;FYFebl>F`x7#-Fh^l6$&-Fc`m6$F^ev&F_\lFjaoF]rFcgw>F`cl-F
jiv6*FayFeyFddlF]xF_\lF`xF\zF[r>6&FddlF]xF_\lF`x6&7#-Fh^l6$Fbgw-Fb_l6$F_alF`cl7
#-Fh^l6$F^evFfhw7#-Fh^l6$F\hwFfhw7#-Fh^l6$&F`xFjaoFfhwC*>F`x-F[\mF_p>FeblF^ds-F
\y6#-F16$Febl%=~quotient~space~bases~loadedG>FablFhcw>F`\l-F[`m6&F/FablFcdw/F]i
v%)extendedG>6$FfhlFeel6$&F`\lF]r-Fefn6#&F`\lFb^o>F`cl-Fdfv6&F/F`xFeblF[r>Fahw6
&7#-Fh^l6$FeelFfhw7#-Fh^l6$FfhlFfhw7#-Fh^l6$FablFfhwF^iwO6)F\zF/FeyF]xF_\lF`xFd
dlF,F,F,6#FcsF,,
I/TemplateFindert+6(F%>'%,action_varsG-Fin6#<$%'negintGFaoFc\m>'F[`u%'symbolGFe
go>'%,filter_fracGFjfoF\u>Fb^mFd^m>'%+schur_polsGF_\xFc\m6HF`oF*FcoF[bvFgavF`jl
F]jv%&avarsGF]alFjsFifvF_gvF_alFfgpF[_qF]oF_goFidn%&tord1GF]goF^_qFf]lFa_qFjcnF
[oF`_rFb_qF^fsFagoFhnFd]p%#flGF[qFgemFifoFejv%#noG%$spoG6"F,C+>F/-F[_m6#,&FfuFY
FYFY>8GF`[w>8IFhy>6)F/FEF\zFeyF]xF_\lF`\l-Febw6&F4-%&evalbG6#/F[rFegoF\rF/>F`x-
Fiu6%/F^xF\uF\z-FG6$f*6#F\alF,6$F]qF^qF,F]`pF,F,6$FcoF\zFjo>6%FddlFablFeel6%F^d
s-F^p6#FhhlFail>Ffhl,$*&FeelFhyFddlFhyFadl?(F`clFYFYFeelFapC%>6&F]etFcitFejtF_[
v6&&FeyFhil&F]xFhilFgil&F`\lFhil>F\fu-FS6$FYFcit?(FeblFYFYFddlFapC.>F_iu&F`x6#F
ebl>6(F_[wFfawFb[w8;8<8=-Fg^q6'F_iuF]etFcitF/Fejt>8>-F^p6#Fj`x>8?-Fiu6%/F[r%%ns
tdG-F`gq6&FEFj`xF\zF/-F\_r6(FEFj`xF[axF_[vF\zF/>6%8@8A8B-Fhjs6'FEFcaxFb[wF\zF/>
F_bx&-F[_u6(F_bxF`bxF^bx,(-FS6$F\^tF_bxFYFablFhyF_axFhyF/Fc\lF]r>F_bx&-F_\v6$F_
bxF/F]r>8C-Ff[u6(Fi`xF_bxF_[wFfawF_axF/>6$8D8E-FS6$FYF_bx>8F-Fcjp6#F_bx@&3F_cx5
2FdcxFj]x3/FdcxFj]x2F\^xFicxC%>6%Fj]x8HF\^x6%FdcxFecxFicx-F\y6#-F[cm6(QTSmaller
~or~sparser~template~found:~[%d,%d],%a,%a,%aF,FdcxFecx-Fgbp6$FicxFb`lF_iu-Fiu6%
FfaxF`clF\fu-Fcfo6-F47$FdcxFecx-Fgbp6$FicxFgvF/F\zF_iuFcitFfawF^bxFc\lFa^x4F_cx
Y6&Q@Invalid~action~matrix,~%1,%2,%3F,F`clF_iuFcit-F\y6#-F[cm6*Q6%d%s,[%d,%d],%
a,%a,%aF,-F\cl6#*&,&*&,&F`clFYFhyFYFYFddlFYFYFeblFYFYFfhlFYQ"%F,FdcxFecxF]exF_i
uF_ex-F\y6#-F[cm6&Q:Best~template:~[%d,%d],%aF,Fj]xFfdx-Fgbp6$F\^xFb`lF,F,F,6#F
YF,,
I$rnd,$f*F,F,6"F,,&-f*F,F,6#/%(builtinG%4RandNumberInterfaceGF,F,F,F,F,6%Fbdn"%
,?F[[pFY!%+5FYF,F,6$%6_thismoduledefinitionGF,F\blF,,
I'rndMatf*6$'F[qFao'FgemFaoF,6$F]qF^qF,-Fefn6%F4Fjof*F]hlF,6$F]qF^qF,-Fh`lF,F,F
,F,F,F,F,F,,
I&crossf*6#'F__lF]wF,6$F]qF^qF,-Fht6%-Fhiu6%F\u,$&F46#Fb`lFhyFefr-Fhiu6%FcixF\u
,$FdfrFhy-Fhiu6%,$FefrFhyFdfrF\uF,F,F,F,,
I-readTemplatet+F^[p6LFhgoFigoF`oFcoF]goF]oFagoF\]xF*F`_r%#U0G%&tord0G%"UGF[_qF
^_qF]`uFf]lF__qF`_qF_wFa_qFjcnF[oFdoFjs%#nRGFd_uFd]pFghpF_\uFa`uFb`uFhnFc\v%#t1
GFd\vFe\vFewFgfo%#xEG%#xVGF`[p6"F,CE>6,F/FEF\zFeyF]xF_\lFejtF`\lF`x8M-F\[pFjar>
Fddl&Fc_mF]r>6$FablFeel-Fep6%FddlFdetFey>FfhlFhcw>F`cl-Fidp6$FeelFfhl>Fabl-Fbhp
6%FablFeelF`cl>Febl-F[`m6%FddlF_\lFcdw>Fcit&-Fc`m6$FeblF_\lF]r>Fejt-Fcx6$FejtFh
s>F]et-FG6$f*FazF,6$F]qF^qF,Fa]wF,F,6$F]goF]xFejt>F_[v-Fidp6$-Fcx6$-F\`l6$F]etF
ejtFinF_\l>6$Fj`xF[ax6$-F^p6#Fejt-F^p6#F_[v>F\fu-FG6$f*FazF,6$F]qF^qF,*&F4FYF[
\lFhyF,F,Fg\y-Fi_lF^]y>F_iu-%&getB0G6$F\fuFey>F\fu7$-FS6#-Fidp6$-Fcx6$-F\`l6$F
\fuF_iuFinF_\l-FS6#-Fidp6$-Fcx6$F_iuFinF_\l>Fejt7$-FS6#-Fidp6$-Fcx6$-F\`l6$Fejt
-Fcx6$F\fuFhsFinF_\l-FSFjfu>6$F_[wF]et6$7$-FSFe]y-FSFc]y-FG6$f*FazF,6$F]qF^qF,F
a]wF,F,Fg\yFejt>Ffaw-Fcap6(F]xFcit-Fe^p6#-Fjap6$Fcit7#-Fhhn6#;FY-F^p6#FcitFeblF
_\lFcdw>Fi`x-F[\q6'FejtFcitFeblF_\lF\z>Ffaw-Ffdm6$-Fbcp6%Fi`xFfaw-F_eq6$F\zFi`x
F\z>Fb[w-Fcx6$,&-F]wFe]yFY-Fbcp6$&Ffaw6$;FYF[axFas-F]wFc]yFhyFin>6$F_axF^bx&-Fj
es6&F`\lFddlFeyF_[w6#;Fj[mFb`l>6'F_axFcaxF_bxF`bxF_cx-F[_u6(F_axF^bxF`\l,(-FS6$
F\^tF_axFYFj`xFhyF[axFhyF\zF`x>6%FdcxFj]xFfdx-F_\v6$F_axF\z-F\y6#-F16$%6Action~
matrix~found:~G-Ff[u6(FfawFdcxF]etFejtF[axF\z>8J7#-FS6$FYFdcx-F\y6#-F16$%2Templ
ate's~size:~GFddy@$50&F/F]r&FddyF]r0&F/Fb^o&FddyFb^oYQ/Wrong~templateF,>8L-F\`l
6$-Fcx6$F^bxFhs-Fcx6$FcaxFhs>Fcax&Fcax6#-Fjjr6$f*FjaoF,6$F]qF^qF,Fi^vF,F,6$Fe\v
Ffdx7#-Fhhn6#;FY-FS6$FYFcax>Fecx-Ffdm6$-Fi\u6#&F_ax6$-Fjjr6$f*FjaoF,6$F]qF^qF,F
i^vF,F,6$Fd\vFj]x7#-Fhhn6#;FY-FS6$F]\sF_axFasF\z>Ficx-FG6$f*FazF,6$F]qF^qF,-FS6
#-F^z6$f*FihtF,6$F]qF^qF,0&F[\l6$F4FfqF\uF,F,6&Fc\vF[\lFbzF4<#-Fhhn6#;FY-FS6$F]
\sF[\lF,F,6$Fc\vFecx<#-FS6#Ffdx>8K-Fbel6$-Fcx6$FijxFhs-Fcx6$&Fcax6#7#-FS6#FicxF
hs>F\^x-Fidp6$-Fcx6$-F\`l6$F]fy-Fcx6$F_[wFhsFinFfhl64FeyF]xFablF`clF\^xF_[wFejt
F]etF`\lFj]xFfdxFddyF[axFiiyF_bxF`bxF_cxFheyF,F,F,6#Fj[mF,,
I&getB0t+6$'%"PGFhsF[go6'F]alF_al%$VrsG%$vrsGF_w6"F,C$>F/F^x?(FEF\uFY,&F/FYFhyF
YFapC$>F\z-&%)combinatG6#%'chooseG6$Fjo,&F/FYFEFhy?&FeyF\zFapC$>F]x-F^z6$f*FjpF
,6$F]qF^qF,-Fcx6$-FG6$f*6#FfwF,6$F]qF^qF,-F^bm6$Fi[lFfqF,F,6&F[qF4Fd[zFfqF[\l%$
andGF,F,6&Fg[zFeyFd[zF4F4@%0Fj`pF\uO-Fcx6$-FG6$f*Fb]zF,6$F]qF^qF,*&F4FY&F[\lF]r
FYF,F,6$F_wF]x7$FieoFYFhs>F]xF^blF,F,F,6#Fj[mF,,
I*iniColpivt+6&F^_u'FcjxFhsF\goF`w6*%#VlGFd[zF_w%#aPGF__q%#RPGFewF]o6"F,C0>F`x-
Ff_m6#Fais>F/-Fcx6$-F\`l6$FehvFjoFin>FE-Fcx6$-F^z6$f*FjpF,6$F]qF^qF,-F^bm6$Fi[l
FhzF,F,6&F]goF[rF]_zF/F/Fhs>F\z-F_^y6$FEF\r>Fey-FG6$f*FjpF,6$F]qF^qF,Fi[lF,F,6$
F]goF[rFE>F]x-Fidp6$-Fcx6$F[elFinF`x>FE7$-FS6#-Fidp6$-Fcx6$-F\`lFb_mFinF`x-FS6#
-Fidp6$-Fcx6$F\zFinF`x-F\y6#%?List~of~permissible~monomials:G-F\yFW-F\y6#-F16$%
BNumber~of~permissible~monomials:~GF]]l>Fey-FG6$f*FjpF,6$F]qF^qF,-Fjip6$Fi[l7$-
FSFaas-FS6#FaflF,F,6(F]goF[rFd[zFEF__qF]xFE>F_\l7$FjglF_il>F`\l-Fidp6$-Fcx6$-Fb
el6$-F\`l6$-Fcx6$F/Fhs-Fcx6$F_\lFhsFjoFinF`x6'-Fht6$-FSFeboF]isFEFeyFj`p-F^pFeb
oF,F,F,6#FcsF,,
I,alter_commaf*6#'F__lFinF,6$F]qF^qF,-F16%Fcgm-FS6#-&F[jp6#%+InterleaveG6$F47#-
Fhhn6$Q",F,,&F]pFYFhyFYFh]nF,F,F,F,,
I-write_solvert+6/'%$dirGF'Fhgo%&vars0GF]go%#iMG%#eMGFf]lF^_qFgfoF`_uFajxF_\uFe
go6)%&vars1G%#vvGFcjl%$nv0GFjsF_al%#fbG6"F,C>>FeyFfbl>F]x-F^p6#Fiy>F`\lQ%~~~~F,
>F/-Fcx6$-F\`l6$F[at<#F\rFin>FE7#-Fh^l6$-Fjip6$*&&F/FbilFY&Fiy6#FhyFYFiy/F_\l;F
Y,&FeyFYFhyFY>F\z-Fhjl6$-F16+F4Q"/F,-Fiu6%90Q%std_F,Q&nstd_F,,&&FhjoF]rFY9/FhyQ
"xF,,&&FhjoFb^oFYFcizFhyQ"_F,F&F5F][m-Fc[m6$F\z-F16'QH%%~Input:~coefficient~mat
rix~C~of~size~F,FeioFdiz&FjoFb^oQ#|+|+F,-Fc[m6$F\z-F16,Q*function~F,-F[ezFatQ$~
=~F,F\izFaizFdizFeizFgizF&Q&(C)|+|+F,-Fc[m6$F\z-F16&F`\lQ(i_dx~=~F,-F[ez6#-FG6$
f*FjaoF,6$F]qF^qF,FdfrF,F,F,FfuQ#;|+F,-Fc[m6$F\z-F16&F`\lQ(j_dx~=~F,-F[ez6#-FG6
$f*FjaoF,6$F]qF^qF,FefrF,F,F,FfuFb[[l-Fc[m6$F\z-F16&F`\lQ(C_dx~=~F,-F[ezFh`uFb[
[l-Fc[m6$F\z-F16(F`\lQ>M~=~sparse(i_dx,j_dx,C(C_dx),F,FbizF\fzFfizQ$);|+F,@$0Fc
izF\u-Fc[m6$F\z-F165Q"|+F,F`\lQ'M~=~M(F,,&FcizFYFYFYQ&:end,F,Fb][lQ*:end)-(M(F,
Fb][lQ(:end,1:F,FcizQ')/M(1:F,FcizQ$,1:F,FcizQ())*M(1:F,FcizF\fzFb][lQF:end);~%
%~Schur~complement~reduction|+F,-Fc[m6$F\z-F16'F`][lF`\lQ5[L,|ir,Pi]~=~lu(M(:,1
:F,FijoQ%));|+F,-Fc[m6$F\z-F16$F`\lQ+Pi~=~Pi';|+F,-Fc[m6$F\z-F16(F`\lQ0M~=~[Pi*
L~Pi(:,F,,&FijoFYFYFYQ,:end)]\M(:,F,Fj^[lQ(:end);|+F,-Fc[m6$F\z-F16&F`\lQ+M~=~M
(end-F,,&F_hoFYFhyFYQ*:end,:);|+F,-Fc[m6$F\z-F16'F`][lF`\lQ+T~=~zeros(F,F]xFi\[
l-Fc[m6$F\z-F16*F`\lQ%T(1:F,F_hoQ.,:)~=~-M(:,1:F,F_hoQ')\M(:,F,,&F_hoFYFYFYF\_[
l@&/,&F]xFYF_hoFhyFY-Fc[m6$F\z-F16&F`\lQ#T(F,*&F]xFY-Fjip6$&FgjoFbhzFiyFYQ()~=~
1;|+F,2FYFc`[l-Fc[m6$F\z-F16&F`\lFh`[l-F[ez6#7#-Fh^l6$,&*&F]xFY,&-Fjip6$&Fgjo6#
,(F_\lFYF]xFhyFhyFYFiyFYFhyFYFYFYF_\lFY/F_\l;F``[lF]xF]a[l-Fc[m6$F\z-F16%F`][lF
`\lQ1[V,D]~=~eig(T);|+F,@%/F]]lFY-Fc[m6$F\z-F16(F`\lQ*sol~=~[V(F,&FEF]rQ(,:)./V
(F,F]xQ3,:);~diag(D).'];|+|+F,-Fc[m6$F\z-F16*F`\lF]c[l-F[ezFWQ/,:)./repmat(V(F,
F]xQ%,:),F,FehzQ3,1);~diag(D).'];|+|+F,-Fc[m6$F\z-F16$F`\lQXI~=~find(not(isnan(
sol(1,:)))~&~not(isinf(sol(1,:))));|+F,-Fc[m6$F\z-F16$F`\lQdo%%I~=~I(not(imag(s
ol(1,:))));~%%~uncomment~this~line~for~real~roots~only|+F,?(F_\lFYFYFehzFap-Fc[
m6$F\z-F16'F`\lF`hzQ(~=~sol(F,F_\lQ&,I);|+F,-Fc[m6$F\z-F16'F`\lF\rFhd[lFeyQ',I)
;|+|+F,-Fc[m6$F\zQ$endF,-Fh[mFh\mF,F,F,6#"#8F,,
I4write_solver_colpivt+60FafzFhgoFcfzF]goFdfzFefzFd[zF^_zFgfoF`_uFajxFjsF_\uFeg
o6)FgfzFhfzFcjlFifz%#nPGF_alFjfz6"F,CB>FeyFfbl>F]xF_gz>F`\lFbgz>F/Fdgz>FE7#-Fh^
l6$-Fjip6$F_hz&Fiy6#;,$FcizFhyFhyFchz>F\z-Fhjl6$-F16+F4F[iz-Fiu6%91F_izF`iz,&Fb
izFYF^izFhyFdiz,&FfizFYF^izFhyQ)_colpiv_F,F&F5F][mFhiz-Fc[m6$F\z-F16,FcjzFdjzFe
jzF_g[lFbg[lFdizFcg[lFdg[lF&Ffjz-Fc[m6$F\z-F16&F`\lF[[[l-F[ez6#-FG6$f*FjaoF,6$F
]qF^qF,FdfrF,F,F,FfuFb[[l-Fc[m6$F\z-F16&F`\lFg[[l-F[ez6#-FG6$f*FjaoF,6$F]qF^qF,
FefrF,F,F,FfuFb[[lF^\[lFd\[l@$0F^izF\u-Fc[m6$F\z-F165F`][lF`\lFa][l,&F^izFYFYFY
Fc][lFci[lFd][lFci[lFe][lF^izFf][lF^izFg][lF^izFh][lF^izF\fzFci[lFi][l@%0FijoF
\uC&Fj][lF`^[lFe^[l-Fc[m6$F\z-F16&F`\lQ,M~=~full(M(F,Fj^[lQ+:end,:));|+F,-Fc[m6
$F\z-F16$F`\lQ.M~=~full(M);|+F,@$0F_hoF\uC%-Fc[m6$F\z-F16'F`][lF`\lQ6[L,UR,Pi]~
=~lu(M(:,1:F,F_hoF_^[lF`^[l-Fc[m6$F\z-F16(F`\lFi^[lF``[lF[_[lF``[lF\_[l-Fc[m6$F
\z-F16&F`\lQ*MP~=~M(1:F,F_hoQ&,:);|+F,-Fc[m6$F\z-F16&F`\lQ(NP~=~M(F,F``[lQ+:end
,:);|+|+F,-Fc[m6$F\z-F16&F`\lQ:[Q,U,Pi]~=~qr(NP(:,1:end-F,Fg\lF_^[l-Fc[m6$F\z-F
16(F`\lQ4A~=~UR\[MP(:,1:end-F,Fg\lQ/)*Pi~MP(:,end-F,FeyQ):end)];|+F,-Fc[m6$F\z-
F16*F`\lQ+B~=~U(:,1:F,,*FbizFYF^izFhyFijoFhyF_hoFhyQ()\[U(:,F,,,FbizFYF^izFhyFi
joFhyF_hoFhyFYFYQ3:end)~Q'*NP(:,end-F,FeyFe\\l-Fc[m6$F\z-F16(F`\lQ/M~=~[-A(:,en
d-F,,&FcizFYFhyFYQ1:end)+A(:,1:end-F,FcizQ,)*B;~-B];|+|+F,-Fc[m6$F\z-F16&F`\lQ&
xP~=~F,-F[ez6#FgjoFb[[l-Fc[m6$F\z-F16*F`\lQ*P1~=~[(1:F,,(F]xFYFeyFhyFhyFYQ&)*Pi
~F,,&F]xFYFeyFhyQ":F,F]xQ$];|+F,-Fc[m6$F\z-F16-F`\lQ-T~=~getT(M,[F,FgcnFf^\l,&F
]xFYF_hoFYQ+~P1(1:end-F,FcizQ+)],P1(end-F,Fd]\lQ&:end)F,Q',xP);|+F,Fbb[l@%Fhb[l
-Fc[m6$F\z-F16(F`\lF]c[lF^c[lF_c[lFcizF`c[l-Fc[m6$F\z-F16*F`\lF]c[lFec[lFfc[lFc
izFgc[lFehzFhc[lFic[lF^d[l?(F_\lFYFYFehzFapFdd[lFjd[lF_e[lFbe[lF,F,F,6#"#9F,,
I4write_inidata_coefst+6$F%'%)root_dirGF'6.%*proc_nameG%#_CG%&_nameG%&_sizeG%#C
sG%#ClGFbfzFcjlF_alFfdr%$idxGFjfz6"F,C6>FfhlFbgzAF0>F/-FK6#-F16$%#C_GF4>6%FEF\z
FeyF^cl>F`\l-F16%FjoF[izF4@$4-F9Febo-&F:6#%.MakeDirectoryGFebo>F`x-Fhjl6$-F16&F
`\lQ*/inidata_F,F4F5F][m-Fc[m6$F`x-F16%Q9function~data~=~inidata_F,F4Q$()|+F,-F
c[m6$F`x-F16&FfhlQ0data~=~cell([1,F,F\doQ%]);|+F,?(FddlFYFYF\doFap-Fc[m6$F`x-F1
6(FfhlQ&data|frF,FddlQ+|hr~=~randn(F,-Fifm6$-F[ez6#&FeyFeetFj`nFi\[l-Fc[m6$F`xF
ae[l-Fh[mFfdl>F`x-Fhjl6$-F16&F`\lQ(/coefs_F,F4F5F][m-Fc[m6$F`x-F16%Q4function~C
~=~coefs_F,F4Q)(data)|+|+F,?(FddlFYFYFi_nFap-Fc[m6$F`x-F16'Ffhl&F\zFeetQ)~=~dat
a|frF,FddlQ$|hr;|+F,-Fc[m6$F`xF`][l?(FddlFYFY,$F]]l#FYFj[mFap@$/&FE6#,&FddlFj[m
FhyFY%#cfGC%-Fc[m6$F`x-F16(FfhlQ+C~=~zeros(F,-FS6$F]\s&FEFbhzF\fz-FS6$F\^tFif\l
Q%);|+|+F,>6$F]xF_\l6$-F\`l6$-Fcx6$&FE6#,$FddlFj[mFhs<#F\u-Fcx6$Fdg\lFin?&FablF
]xFapC$>Feel7#-Fbht6$FablF_\l-Fc[m6$F`x-F16(FfhlQ#C(F,-Fiu6%/-F^pF[esFY&FeelF]r
-F[ezF[esQ%)~=~F,-Fcx6$FablF'Fb[[l-Fc[m6$F`x-F16%F`][lFfhlQPC~=~C./repmat(sqrt(
sum(C.^2,2)),1,size(C,2));|+|+F,F_d\lFad\lF,F,F,6#Fj[mF,,
I/write_test_numt+6+F%FisFffoF`w'FcfzFin'F`jxF]wF[`uFb`\l%#cpG6+FbfzFcjlFfgpFjf
z%$fb2GFhfz%$vv0G%&xvarsG%$xvvG6"F,CI>F/-F16%FgjoF[izF4>FeyFbgz>F]x-F16$FeyFey>
F_\l-FG6$f*Fb]zF,6$F]qF^qF,-F16$F4F4F,F,F,F\r>F`\l-FG6$f*Fb]zF,6$F]qF^qF,F][]lF
,F,F,Ffu>F`x-Fcx6$-F\`l6$FghsFddsFin>Fddl-FG6$f*Fb]zF,6$F]qF^qF,F][]lF,F,F,F`x@
$F7-F^b\lF=>FE-Fhjl6$-F16&F/Q+/test_num_F,F4F5F][m-Fc[m6$FEQ+rng(23);|+|+F,-Fc[
m6$FEQ-N~=~10000;|+|+F,-Fc[m6$FE-F16'Q%Err_F,F4Q+~=~[];|+Tm_F,F4Q)~=~[];|+|+F,-
Fc[m6$FEQ.for~i~=~1:N|+|+F,-Fc[m6$FE-F16&FeyQ0data~=~inidata_F,F4QN();~%%~gener
ate~initial~data~of~the~problem|+|+F,-Fc[m6$FE-F16$FeyQ%try|+F,-Fc[m6$FE-F16$F]
xQ&tic;|+F,-Fc[m6$FE-F16&F]xQ+C~=~coefs_F,F4QV(data);~%%~compute~coefficients~o
f~polynomial~system|+F,-Fc[m6$FE-F16,F]x-F[ezFeboFejz-Fiu6%-Fb^x6#/FiyFegoF_izF
`iz&F[rF]rFdiz&F[rFb^o-Fiu6%FhjoFdg[lFgizF4QA(C);~%%~solve~polynomial~system|+F
,@$0FdetF\u-Fc[m6$FE-F16+F]x-Fiu6%/FdetFYFhcp-F[ezFeetQ6~=~arrayfun(@(j)~get_F,
-F16#-FSFfdlQ$(C,F,-Fifm6$-F[ez6#7#-Fh^l6$-F16$&F`\lFh\mQ$(j)F,/F\z;FYFidzFj`nQ
-),~1:length(F,FdjwF_^[l-Fc[m6$FE-F16$F]xQ+tm~=~toc;|+F,-Fc[m6$FE-F16&F]xQ,if~i
sempty(F,FhhlQ2);~continue;~end|+F,-Fc[m6$FE-F16$FeyQ*catch~ME|+F,-Fc[m6$FE-F16
$F]xQ+continue;|+F,-Fc[m6$FE-F16$FeyQ&end|+|+F,-Fc[m6$FE-F16$FeyQ)M~=~[];|+F,-F
c[m6$FE-F16&FeyQ0for~j=1:length(F,FhhlQ#)|+F,?(F\zFYFYFbblFap-Fc[m6$FE-F16'F]x&
F\rFh\mFejz&F_\lFh\mQ&(j);|+F,-Fc[m6$FE-F16&F]xQ%m~=~F,-F[ez6#-Fcx6$Fc\lFinFb[[
l-Fc[m6$FE-F16$F]xQ6m~=~m/norm(m,'fro');|+F,-Fc[m6$FE-F16$F]xQ=M~=~[M;~norm(C*m
.','fro')];|+F,-Fc[m6$FE-F16$FeyQ%end|+F,-Fc[m6$FE-F16$FeyQ.M~=~sort(M);|+F,-Fc
[m6$FE-F16&FeyQ4err~=~norm(M(1:min(F,FjoQ7,length(M))),'fro');|+|+F,-Fc[m6$FE-F
16.FeyF`]]lF4Q)~=~[Err_F,F4Q(~err];|+F,FeyQ$Tm_F,F4Q(~=~[Tm_F,F4Q(~tm];|+|+F,-F
c[m6$FEFac]l-Fc[m6$FEQIfolder~=~fileparts(which('add_all.m'));|+F,-Fc[m6$FE-F16
'QCsave(strcat(folder,'\_results\Err_F,F4Q-.mat'),'Err_F,F4Q&');|+|+F,-Fc[m6$FE
-F16)Q3fprintf('Problem:~F,F4Qin.~Ave.~runtime:~%%0.1f~ms.~Med.~error:~%%0.2e\n
',10^3*mean(Tm_F,F4Q.),median(Err_F,F4F_^[lF[joF,F,F,6#FaenF,,
I0write_histo_numt+F``\l6%FbfzFcjlFjfz6"F,C6>F/Fha\l>F\zFbgz@$F7F_\]l>FE-Fhjl6$
-F16&F/Q,/histo_num_F,F4F5F][mFcg]l-Fc[m6$FE-F16%QDload(strcat(folder,~'\_resul
ts\Err_F,F4Q+.mat'));|+|+F,-Fc[m6$FEQ,bwd~=~0.3;|+F,-Fc[m6$FEQ-nbins~=~60;|+F,-
Fc[m6$FEQ9clr~=~[70~100~160]/255;|+F,-Fc[m6$FE-F16%Q1err~=~log10(Err_F,F4Fi\[l-
Fc[m6$FEQLhr1~=~histogram(err,nbins,'BinWidth',bwd);|+F,-Fc[m6$FEQ6hr1.FaceColo
r~=~clr;|+F,-Fc[m6$FEQ7hr1.EdgeColor~=~clr;|+|+F,-Fc[m6$FEQ8axis([-17~1~0~1150]
);|+|+F,-Fc[m6$FEQVset(gca,'FontSize',54,'FontName','Times~New~Roman');|+F,-Fc[
m6$FEQFset(gcf,'PaperPositionMode','auto');|+F,-Fc[m6$FEQJset(gcf,'PaperOrienta
tion','landscape');|+F,-Fc[m6$FEQGset(gcf,'PaperPosition',[1~1~28~19]);|+F,-Fc[
m6$FE-F16%QPprint(gcf,'-dpdf',strcat(folder,'\_results\fig_F,F4Q).pdf'));F,F[jo
F,F,F,6#Fj[mF,,
I0SolverGeneratort+6)F%>Fd\xFego>%'colpivGFY>%2create_coefs_fileGFY>%2create_hi
sto_fileGFY>%1create_test_fileGFY>Fa`\lQ(solversF,6FFcoF]goF`_rF`jxFewFa_qFf]lF
^_qFagoFd\vFe\vFgfoFajxFcjxF_\uFa`uFb`uFdjxFd]pFghpFd[zF^_z%$nR1G%$nE1GFj]lFie[
lF`_uFii\lFcfz%#iCG%#eCGFhn%#MtGFdfzFefzFbfz6"F,C9>64F/FEF\zFeyF]xF_\lF`\lF`xFd
dlFablFeelFfhlF`clFeblF]etFcitFejtF_[v-F[jx6$F4-Fb^x6#/FjoFego>F\fu-Fht6$FjglF]
is>6'F_iuF_[wFfawFb[wFi`x-Fh^z6&F\fuFeblFEF/>6%Fj`xF[axF_ax6%Fidz-F^p6#F_[wFj`p
>Fcax-Fiu6%51F[axFj`x/F[rF\uFftFap>F^bx-Fiu6%Fcax-F^z6$f*Fb]zF,6$F]qF^qF,-F^bm6
$*&F4FY&F[\lFbhzFY&F[\l6#;,$FhzFhyFhyF,F,6&Fd[zF_[wFj]lFj`xF/-F^z6$f*Fb]zF,6$F]
qF^qF,-F^bm6$F^`^lF[\lF,F,6$Ff]lF`\lF/-F\y6#-F16$%OVariables~that~can~not~be~ev
aluated~at~roots:~G7#-FS6#-F\`l6$FadzF[fy>F_bx7#-%(indicesG6$-Fcx6$F\zFe^p%+ind
exorderG>F`bx-FG6$f*FazF,6$F]qF^qF,-Fcx6$,&FdfrFY*&,&FefrFYFhyFYFYFbiyFYFYF'F,F
,6$F`_rF\zF_bx>F\z-Fefn6$-FS6$FYF\z<#-FS6#-F\\o6%f*F]hlF,6$F]qF^qF,/-FSF_pFjoF,
F,F,F_bxF`bx>F_cx&-Fjes6&Fddl-Fcx6$-Fbcp6$F\zFeyFinF/F_\lFb^o@$0F]etF\u>F_cx&F_
cx6$FcitFejt>F_cx&F_cx6$-Fjjr6$f*FjaoF,6$F]qF^qF,-F_r6#-Fb_l6$F4-FG6$f*FazF,6$F
]qF^qF,,&F4FYF[\lFYF,F,6$F_\uFhzF[\lF,F,6&Fd\vFablF_\uF]et7#-Fhhn6#;FY-FS6$F]\s
F_cx-Fjjr6$f*FjaoF,6$F]qF^qF,-F_r6#-Fb_l6$F4-FG6$f*FazF,6$F]qF^qF,Fce^lF,F,Fde^
lF[\lF,F,6&Fe\vFeelF_\uF]et7#-Fhhn6#;FY-FS6$F\^tF_cx@$Fcax>F_cx-Fbhp6%F_cx-Fcx6
$-Fht6$Fb`yF\fuF]w-Fcx6$-Fht6$Fb`yF_iuF]w>Fdcx-Fcx6$F_cxFe^p>6$FecxFicx6$7#-Fia
^l6$FdcxF]b^l-FG6$FS7#-%(entriesGFch^l@$4-F9F`gz-F^b\lF`gz>Fj]x-F16%FiyF[izF4@$
4-F96#Fj]x-F^b\lFci^l@%Fcax-Fee[l60Fj]x7#F\c^lF^bxFEFecxFicxF_[wFfaw7#-FS6$FYF_
cxFi`xFb[wFj`xF]etF`^^l-F^fz6/Fj]xFhi^lF^bxFEFecxFicxF`\lF`xFii^lF_axF`clF]etF`
^^l@$/F\rFY-F^`\l6$F4Fiy@$/Fc\lFY-Fdi\l6+F4Fj`xFfhlF/F^bxFeyFjoFiyFcax@$/FfuFY-
Feh]lFaj^lF,F,F,6#FYF,
