M7R0
I,readProblemw,6#'%%probG%'stringG6$%#fnG%"FG6"6"C'>8$-%$catG6%Q/../problems/F_
F,9$Q#.mF,@$4-&%*FileToolsG6#%'ExistsG6#F/Y6$Q2file~%1~not~foundF,F/AF/>8%-%$ma
pG6$%'expandG-%%evalG6#-F16$%#F_GF46$FC7#-%#opG6#-%'indetsG6#FCF,F,F,6#"""6)7'Q
!F,!"""#9""'"#O7'FZFen""*"#Z"#J7'FZFen""$"#v"#X7'FZFen"#P"#m"#]7'FZFenF^o"#5"#Y
7'FZFenF^o"#R"#V7'FZFenF^o"#?F\oF,,
I+isLinIndepw,6&'%"MG%%listG'%"GGFbp'%%tordG%3ShortMonomialOrderG'%#ppG%'posint
G6$%%varsG%"SG6"F,C&>F/-FT6#9%@$/-%%nopsG6#F4FWO%%trueG>FC&-%,poly2matrixG6%-FE
6$w,6#%"mGF,6$%)operatorG%&arrowGF,-&%)GroebnerG6#%+NormalFormG6&F4T$T&/%/chara
cteristicGT(F,F,6(FdpFcqFfp9&Fip9'6#FW6$7'FZFen"#C"#xFhn7'FZFenFis"#EFhnF4FfqF/
6#FW-%#isG6#0-&&%.LinearAlgebraG6#%(ModularG6#%%RankG6$FesFC-Fct6$Fes&FC6$;FW!"
#;F,F,F,F,F,6#""%6(7'FZFen"#8FgnFhn7'FZFenFjn"#DF\o7'FZFenF^o"#UF`o7'FZFen"#B"#
M"#_7'FZFenF^o"$+"Fjo7'FZFenF^o"#"*F\pF,,
I*testBasisw,6''Fap%$setG'%$degGFjpFcpFep'Fip%*nonnegintGF[q6"F,C&>F/-FT6#Fds@$
2FfqFcqO6$%&falseG-%$<,>G6#-Fgw6#""!>FC&-F^r6%-FE6$w,FcrF,6$FfrFgrF,FhrF,F,6(Fd
pFdsFfpFesFip9(6#FWFgsF4FfqF/F]t6$-%#ifG6%0FexF[x-F_t6#/-Fct6$FexFCFcq-F_t6#/-&
FetFhtFUFcqFCF,F,F,6#""&6(7'FZFen"#7FgnFhnFgu7'FZFenF^oF^vF`o7'FZFenFhuFjoF^vF_
v7'FZFenF^oF`vF\oF,,
I*iniMonSetw,6)'F*<%%'VectorGFbpFgv'%#B0GFbp'F\qFbpFcpFepFhp>'%$domGF[wF[x6*%"E
GFap%#vrG%"dGFiv%%flagGF]q%&d_minG6"F,C*>8(-FgqFbq>8+F[x>F/-%(convertG6$-FE6$FQ
-&Fjr6#%(SupportGFhqFgv-%'printfG6$QWSupport~of~polynomial~system~consists~of~%
a~monomials|+F,-FgqF=>FCF/?(8'F[xFWF,1,&Fh\lFWFf[lFen9*C&>8&-%'selectG6$w,6#%"x
GF,6$FfrFgrF,1-%'degreeG6$F4F^sT%F,F,6&F\qFdsF][lFh\l6#FW6$7'FZFenF\pFjoFhn7'FZ
FenF\p"#AFhnFC>FC-FE6$w,6#%"tGF,6$FfrFgrF,-FQ6#-FE6$w,6#%"kGF,6$FfrFgrF,*&F^sFW
F4FWF,F,6$Ff^lF46#FW6$7'FZFenF\t"#KFhn7'FZFenF\t"#GFhnT#F,F,6$F\[lF^]l6#FW6$7'F
ZFen"#;FboFhn7'FZFenF]`l"#=FhnFC>6$8)8*-Fcv6'FCFc[lFesFex9)@$4Fb`l>Ff[l,&Fh\lFW
FWFW-Fb\l6$QFInitial~set~consists~of~%a~monomials|+F,-FgqFUO6$F/FCF,F,F,6#""(60
Fiy7'FZFenF`^lFhnFjo7'FZFen"#["#eFjo7'FZFenF^oFdoFjo7'FZFenF^o"#wF\p7'FZFenF^oF
jnFjo7'FZFenF^o"")F]bl7'FZFenFbalFgoFjo7'FZFenFbal"#TFjo7'FZFenFbalF[oFjo7'FZFe
nFbal"#WF`o7'FZFenFisFhnFjo7'FZFenF^o"#fF\p7'FZFenF^oFfnF^vF,,
I-neighborMonsw,6%'%"BGFgv'%#MBGFgvFfz6%%#nBG%"bG%"vG6"F,C&@$/FfqF[xOFcq>F/-F`]
l6%%%typeG-FE6$FQ<#-%$seqG6$-F`dl6$<$*&FCFWF^]lFen*&FCFWF^]lFW-%#inG6$F^]lFds-F
hdl6$FCF4%)monomialG>F/-%*intersectG6$-%&minusG6$F/F4Fcq-Fix6%/Fe\lF[xFcqF/F,F,
F,6#F^o6(7'FZFen"#:FgnFhn7'FZFenF^o"#SF`o7'FZFenF\vFe_lF^v7'FZFenF^o"##)Fjo7'FZ
FenF^oF]vFjo7'FZFenF^oFg_lF\pF,,
I)genBasisw,6)'F[[lFgvFfvFdzFfzFcpFepFhp60%$rndGF\cl%#EBGF^clF`cl%$nB1G%#bvGF^_
l%"aG%#nvG%#wtGFdr%"iGFiv6"F,C->F/,$-I%randG6$%*protectedG%(_syslibG6#;F[x"%+5#
FWFjgl>FC<">Fh\lFcq>8--Fgq6#Fes>81-FgqF`w-%*randomizeGF,>Fc`l7#-F`dl6$-%&roundG
6#-F/F,/80;FWF`hl>Ff[l-&%$maxG6#%&indexG6#-FE6$w,Fc]lF,6$FfrFgrF,,&F4FW*&-Fh_lF
,FW$F`vF[xFenFWF,F,6$FgflF/6#FW6$7'FZFenF\v"#QFhn7'FZFenF\vFhuFhnFc`l>8,&Fes6#F
f[l?(F,FWFWF,2F^alFdhlC*>Fh\l-Fbel6$Fh\lFC>Fc[l-Fhbl6%FCFh\lFes>F^]l-%&unionG6$
F4FC>8.w,Fc]lF,6$FfrFgrF,,*-Fix6%-FhdlFi]lFWF[xFW-Fix6%-Fhdl6$*&Fj]lFWF4FWT'FWF
[xFW-%$addG6$*&&T)6#T+FW-Fh]l6$F4&T.F]]mFW/F^]m;FWT/FW*&-T1F,FWFajlFenFWF,F,62F
[[lF4F[glFijlFhflF^]lFjflFc`lF^glFailF\qFesF\glF`hlFgflF/6#FW6$7'FZFenFfuF`vFhn
7'FZFenFfuFjelFhn>Fb`l-%%sortG6$7#-FQ6#Fc[lw,6$Fd]l%"yGF,6$FfrFgrF,1-Fh_lFbq-Fh
_lFhqF,F,6$F]glFj[m6#""#6$7'FZFen"#HF[oFhn7'FZFenFa_m"#NFhn>6$8/Fail6$&Fb`lF]tF
W?(F,FWFWF,34-F]p6&7$-FQFUFf_mFexFf`lF[]l2Fail-Fgq6#Fb`lC$>Fail,&FailFWFWFW>Ff_
m&Fb`l6#Fail>FC<$F_`mFf_mFCF,F,F,6#Fbal687'FZFen"#6FgnFhn7'FZFenFjnF]vF\o7'FZFe
nFhnFjuFjo7'FZFen"#\"#cFjo7'FZFenFjs"##*Fjo7'FZFen"$0""$>"Fjo7'FZFenF^oFfuF\p7'
FZFenF^oFhnFjo7'FZFenF^oFjoFjo7'FZFenF^oFfnFjo7'FZFenF^oF]blFcbl7'FZFenFbalF\vF
jo7'FZFenFbalFboFjo7'FZFenFbalF`^lFjo7'FZFenFbalF`vFjo7'FZFenFbalFfalFjo7'FZFen
FbalFisFjo7'FZFenFbalFjyFcbl7'FZFenF^am"#@FjoFebm7'FZFenFbalFfbmFjo7'FZFenF^oFc
uF]blF,,
I*readBasesw,F$6%%#stG%$QBsGF)6"F,C)>F/FW>FC7">F^]l-F16$Q)bases/b_F,F4@$4-F96#F
^]lY6$F@F^]l?(F,FWFWF,0F/F[xC$>F/-%)readlineGFjcm@$F^dm>FC7$F_`m-%&parseGF=-Fb
\l6$Q@%a~quotient~space~bases~loaded|+F,F^alFCF,F,F,6#FW6.Fiy7'FZFenFjnF]`lF\o7
'FZFenF_`lF\tFjo7'FZFenFa_m"#bFjoF]oFaoF]bmFcbm7'FZFenFbalFgalF`o7'FZFenF\vFbam
Fjo7'FZFenF^oF`emF\p7'FZFenF^oFgnF]blF,,
I,BasisFinderw,6'F%>'%-deg_over_minGF[wF[x>%%modeG%'APPENDG>'%0number_of_basesG
FjpF`v>'%-prime_numberGFjp"&\F$6/FipF*F\qFfpFdpFezF][lF[[lFap%#BBGF\clF)%#fdG6"
F,C.>F/-%*prevprimeG6#,&FexFWFWFW>FijlFbcm>Ff_mFdcm>6$FCF^]l-F"Fhq>Fh\l-%%tdegG
6#-FQFjcm>Fc[l-&Fjr6#%&BasisG6%FCFh\l/FasF/>Fb`l&-&Fjr6#%*NormalSetG6$Fc[lFh\lF
]t>6$Ff[lFijl-F^z6)FCFb`lF^]lFc[lFh\lF/Fcq>F`hl-Fix6%/FdsF]fm-FibmFhqFbcm>Fail-
%&fopenG6$Ff_mFds?(F,FWFWF,2-Fgq6#F`hlFesC$>Fj[m-Fbfl6)Ff[lFijlFb`lF^]lFc[lFh\l
F/@$4-%'memberG6$Fj[mF`hlC%>F`hl7$-FQFgimFj[m-%(fprintfG6%FailQ$%a|+F,-Fi[l6$Fj
[mFbp-Fb\l6$Q0%d%%~completed|+F,-F]il6#,$*&FfimFWFesFenF`v-%'fcloseGFh`mF,F,F,6
#FW64FY7'FZFenFjnFioF\o7'FZFen"#qFjalFjo7'FZFen"#')"$7"Fjo7'FZFenF^o"#IFjo7'FZF
enF^oFisFjoFhalFho7'FZFenF^oFfblFjo7'FZFenF^oFgoFjo7'FZFenF^oF\vFjoF]bmFbbm7'FZ
FenFbalFfuF`o7'FZFenF^am"#FFjo7'FZFenF^amF[oF\p7'FZFenF^am"#tF\p7'FZFenF^oFjyF
\pF,,
I*writeGfanw,6$F%>FbfmFdfm6&FipF*F\qFgfm6"F,C(>F/-F\gm6#,&FcqFWFWFW>Fh\l-Fbim6$
Q)gfan/igfF,%&WRITEG>FbgmFcgm>FC-%$modG6$-FE6$FG-Fi[l6$FCFgvF/-Ffjm6'Fh\lQ+Z/%a
Z%a|+%aF,F/F^]lFC-Fc[n6#Fh\lF,F,F,6#FW6)FiyFf[n7'FZFen"#^"#!)FjoF\\nF[bm7'FZFen
F^oF`blF\pFh\nF,,
I)readGfanw,6#'F)F'6'F^[lF\cm%"nGFipF^gl6"F,C*>F/Few>FCFW>F^]lF[x@$4-F9FhqY6$F@
F4>FC-FbdmFhq>Fh\l-Fgdm6#-%*substringG6$FC;F^o,&-&%,StringToolsG6#%.FirstFromLe
ftG6$Q"[F,FCFWF`uFW?(F,FWFWF,0FCF[xC$>FCF^`n@(5/FCQ#|fr|frF,/FCQ"|frF,C%>F/Fjq>
F^]l,&F^]lFWFWFW>(FdpF^]lFbcm3F/0-Fc`n6$FCFenQ"|hrF,>F]bn7$-FQ6#F]bn-Fc`n6$FCF_
u3F//F`bnFbbnC$>F]bnFdbn>F/FewO6%Fh\l7#-F`dl6$-FE6$Fgdm(FdpFc[l/Fc[l;FWF^]l7#-F
`dl6$-FE6$w,Fc]lF,6$FfrFgrF,-Fgdm6#-Fc`n6$F4;FW,&-Fh`n6$Q"+F,F4FWFenFWF,F,F,6#F
W6$7'FZFenFcam"$="Fhn7'FZFenFcamFgalFhnFecnFfcnF,F,F,6#FW64F]am7'FZFenFjnF`^lF
\o7'FZFenFisF\oFjo7'FZFen"#LFioFjoF]oFao7'FZFenF^oF\pFjo7'FZFenF^oFh[nFjoF]bmFc
bmFb\n7'FZFenF^amF\vFjoFebm7'FZFenF^amF\pFjo7'FZFenF^amFdoFjoFgen7'FZFenF^amFis
Fjo7'FZFenF^o"$N"F^vF,,
I(writeCMw,6$F%>FbfmFdfm6)%$Ws0GFipF)FgfmF*F\q%#WsG6"F,C7>FCFa]n>F^]l-F16$Q+wei
ghts/w_F,F4>F/-%,readWeightsGFjcm>Fc`l-&Fi`n6#%.SubstituteAllG6%-F^gn6%-Fi[l6$F
/F'F]anQ"(F,Q"]F,Q")F,>6$Fc[lFb`lFcgm>Fb`l-Fi[l6$Fb`lF'>Fc[l-Fi[l6$-F\^n6$-FE6$
FGFc[lFCF'>Fh\l-Fbim6$Q'cm/icmF,Fh]n-Ffjm6'Fh\lQ<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+
F,Fc`lFCFb`l-Ffjm6%Fh\lQ6f~=~openOut~"cm_%s";|+F,F4-Ffjm6$Fh\lQ<f~<<~toString(p
p)~<<~endl;|+F,-Ffjm6$Fh\lQ<f~<<~toString(vr)~<<~endl;|+F,-Ffjm6%Fh\lQ9for~i~fr
om~0~to~%a~do~(|+F,,&Fe\lFWFenFW-Ffjm6$Fh\lQ>f~<<~toString(Ws#i)~<<~endl;|+F,-F
fjm6&Fh\lQ.R~=~ZZ/%a%s,~F,FC-Fc`n6$Fb`lF_u-Ffjm6$Fh\lQDMonomialOrder~=>~Weights
~=>~Ws#i];|+F,-Ffjm6%Fh\lQ0I~=~ideal(%s);|+F,-Fc`n6$Fc[l;F^_mF`u-Ffjm6$Fh\lQVG~
=~gb(I,ChangeMatrix=>true);|+M~=~getChangeMatrix~G;|+F,-Ffjm6$Fh\lQ>f~<<~toStri
ng(M)~<<~endl;|+);|+F,-Ffjm6$Fh\lQ,f~<<~close;F,Fe^nF,F,F,6#FW687'FZFenFfoFgnFh
n7'FZFenFfnFcblFjo7'FZFenF[oF_oFjoF^\n7'FZFenF^o"$/"FjoF\\n7'FZFenF^oF\oFjo7'FZ
FenF^oF`oFjoF\\n7'FZFenF^o"#hF\p7'FZFenF^oF[oF\p7'FZFenF^oF`oF\pF_\oFcemF^\o7'F
ZFenF^oFgalF\p7'FZFenF^o"#`F\p7'FZFenF^o"#aF\p7'FZFenF^o"#sF\p7'FZFenF^oFfalF\p
FaflFh\nF,,
I'readCMw,F$6)F\cmF)FipF\qFdrFb_nF^gl6"F,C,>F/FW>FC-F16$Q'cm/cm_F,F4>Fc[lF[x>Fb
`lF[x@$4-F9FUY6$F@FC>F^]l-Fgdm6#-FbdmFU>Fh\lFj]o?(F,FWFWF,F^dmC$>F/F\^o@&3F^dm/
-Fc`n6$F/FWFfgnC$>Fc[l,&Fc[lFWFWFW>(%"TGFc[l-Fc`n6$F/Fijn3F^dm/-Fc`n6$F/;FWFgnQ
'matrixF,C$>Fb`l,&Fb`lFWFWFW>(%#CMGFb`l-F^gn6%-F^gn6%-Fc`n6$F/;FjnF`uFganF]anFb
bnFggn-Fb\l6$Q;%d~change~matrices~loaded|+F,Fb`lO6%F^]l7#-F`dl6$-%%wdegG6$7#-Fg
dm6#(F[_oFc`lFh\l/Fc`l;FWFc[l7#-F`dl6$)-%'MatrixG6#7#-FE6$Fgdm(Fi_oFc`l%#%TG/Fc
`l;FWFb`lF,F,F,6#FW647'FZFenFjnFgnFhnF]em7'FZFenF_`lFjuFjo7'FZFenF`emF]\oFjo7'F
ZFen"#j"#pFjoF]oFao7'FZFenF^oFd\nFjo7'FZFenF^oFa_mFjoF]bmFcbmFb\nFebm7'FZFenF^a
mFfjlFjoFebm7'FZFenF^am"$:"Fjo7'FZFenF^oFjuF\p7'FZFenF^oF`vF^vF,,
I(getTordw,6$%#gbG%#lmG6.F\qF\glF^gl%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG%$so
lG%(weightsGFg^m%"gG6"F,C,>F/7#-FQ6#-FTFhq>FCFe\l>Fh\l/7#-%"$G6$F[xFC%%NULLG>Fc
[l7#-F`dl6$(F][lF^]l/F^]l;FWFC>Fb`l-FE6$w,6#%"zGF,6$FfrFgrF,-FE6$w,Fc]lF,6$FfrF
grF,7#-F`dl6$-Fh]l6$F4Fh_l-Fhdl6$Fh_lFj]lF,F,6&Fg^mFh_lF\qFj]l6#FW6$7'FZFenFisF
camFhnF[t-Fi[l6$F4FbpF,F,6&Fg^mFj[mF\qF/6#FW6$7'FZFen"#<F_oFhn7'FZFenF_go"#>Fhn
F4>Fc`l-FE6$w,Fc]lF,6$FfrFgrF,F^foF,F,F[go6#FW6$7'FZFenF_goFbamFhnF`goFcq>Ff[l-
FE6$w,F]_lF,6$FfrFgrF,-FQ6#-FE6$w,Fc]lF,6$FfrFgrF,1FW-Fh\m6#-%$zipG6%w,6$Fg^mFh
eoF,6$FfrFgrF,*&F4FWFcqFWF,F,F,6#F^_m6$7'FZFenFboFfalFhn7'FZFenFboFcblFhnF4Fh_l
F,F,6$FfcoF^]m6#FW6$7'FZFenF\t"#kFhnFf_l-%%subsG6$Fh_l7#-F`dl6$,&&Fj]lFhqFWFf\m
Fen-Fhdl6$Ff\m&F\]mFhqF,F,6,FecoFh\lFhcoFc`lF\doFf_mFgcoFb`lFfcoFc[l6#FW6$7'FZF
enF]`l"$9"FhnF^`l<#-Fido6#;FWFfq>Fijl&-&%-OptimizationG6#%)MinimizeG6&-Fh\mFd^m
Ff[l/%+depthlimitGF\fl/%'assumeGF[w6#F^_m>F`hl-Fiio6$FijlFc[l6$F`hl-Fj`o6$F`hlF
/F,F,F,6#F^_m6-Fe[o7'FZFenFjnFe_lF\o7'FZFenFc_mFdoFjo7'FZFenFcamFjalFjo7'FZFen"
#yFgamFjo7'FZFenF^oF[_nFjo7'FZFenF^oFd\oFjo7'FZFenF^o"$K"Fjo7'FZFenF^o"#&)Fjo7'
FZFenF^oFg_lFjo7'FZFenF^oF]\nF\oF,,
I,readWeightsw,F__n6$F\cmFafn6"F,C(>F/FW>FCFbcm@$Fi_nYF\`n?(F,FWFWF,F^dmC$>F/F^
`n@$F^dm>FCFedm-Fb\l6$Q:%a~weight~vectors~loaded|+F,F^alFCF,F,F,6#FW6-FYF]em7'F
ZFenF_`lFhuFjoF]oFaoF]bmFcbm7'FZFenFbalFcamF`o7'FZFenF\vF[oFjoFg\o7'FZFenF^oFgy
F]blF,,
I-writeWeightsw,6'F%>F\fmF]fm>'%2number_of_weightsGFjpF`v>FbfmFdfm>'%+rand_rang
eG7$FjpFjp7$"$+#"$+)60Fip%#GsG%$LMsG%#WWG%%gffnGF)FgfmF^gl%"WGF*F\qFgflFfpFdp6"
F,C&>F/-F\gm6#,&FesFWFWFW>Fc[l-F16$Q)gfan/gf_F,F4>Fb`lFffn@%-F9Fd^mC(-Fb\l6#QJG
enerating~weight~vectors~from~Gfan~file|+F,>6%F/FCF^]l-F]_nFd^m>Fh\l7#-F`dl6$&-
F_co6$&FCF[[m&F^]lF[[mF]t/Ff[l;FWF^al>Fc`l-Fbim6$Fb`lFh]n?&FijlFh\lFjq-Ffjm6%Fc
`lFhjmFijl-Fc[n6#Fc`lC+-Fb\l6#Q5Gfan~file~not~found|+F,-Fb\l6$QEGenerating~%a~r
andom~weight~vectors|+F,Fds>6$F`hlFj[mFcgm>Ff_m-Fdgl6#;&FexF]t&FexFi[pFfhl>Fh\l
-Fix6%/FcqF]fm-F[gnFb`mFbcm>Fc`l-Fbim6$Fb`lFcq?(F,FWFWF,2-FgqFf^nFdsC&>Fail-Fj`
o6$7#-F`dl6$-Ff_mF,/Ff[l;FW-Fgq6#Fj[mFj[m>Fdhl-F[hm6%F`hlFailF_hm>Fijl&-F_co6$F
dhl-&Fjr6#%0LeadingMonomialG6$FdhlFailF]t@$4-F_jm6$FijlFh\lC%>Fh\l7$-FQFf^nFijl
F^bp-Fb\l6$F][n-F]il6#,$*&F[dpFWFdsFenF`vF`bpF,F,F,6#FW6>FielFf[n7'FZFenF`em"#$
)Fjo7'FZFenFj[nFgjoFjo7'FZFenF^oFjnF`o7'FZFenFbalFgalF\p7'FZFenFbalFc_mFjo7'FZF
enFbalFfblFjo7'FZFenFbalFg_lFjo7'FZFenFbalFj^nF]bl7'FZFenF`^lFjoF\p7'FZFenFbalF
]`lF\p7'FZFenFbalFboF\p7'FZFenFbalFf\oF\p7'FZFenFbalF]vFjoFabl7'FZFenFbalF_goF
\p7'FZFenFbalFdoFjo7'FZFenFbalFd\nFjoFdbm7'FZFenF^amFfblFjo7'FZFenF^amFgalFjo7'
FZFenF^amFgioFjo7'FZFenF^amF_goF`o7'FZFenFjelF\oFjo7'FZFenFjelFhnF\p7'FZFenFjel
"#zF\pF^gpF,,
I)saveDataw,6-F%'%#mnGFa_p'%#spG%(numericGFhp'F\q<$FbpFgv'%#avGF\elFep'%#QBGFbp
'%'shiftsGFbp'%%polsGFbp'%$stdG%(booleanG6'F)Fgfm%$mn0G%$sp0GF^[l6"F,C&>F/-Fix6
%9.-F16$Q-optim/o_std_F,F4-F16$Q.optim/o_nstd_F,F4>Fc[lFew@%F8C'>FC-Fbim6$F/%%R
EADG>F^]l-Fgdm6#-FbdmF=>Fh\lFijp@$52&FcqF]t&F^]lF]t3/F`[qFa[q2Fh\lFds>Fc[lFjq-F
c[nFU>Fc[lFjq@$Fc[lC%>FC-Fbim6$F/Fh]n-Ffjm6.FCQ>%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|
+%a|+%aF,FcqFdsFes-Fi[l6$FexFbpFf`lF[]l9+9,9-FbcmFf[qF,F,F,6#F^am61F]am7'FZFenF
jnFf\pF\o7'FZFen"#&*"$3"FjoFgfpFdgp7'FZFenFbalFe_lFjoF[]q7'FZFenFbalFefpF`o7'FZ
FenFfboF_oFjoF^gp7'FZFenFbalFagoFjoFgfpF[gp7'FZFenFbal"$C"F\pF^gpF,,
I)readDataw,6$F%F_ip6.F)FgfmFahpFchpFipF\qFhhpFfpFjhpF\ipF^ip%$xE0G6"F,C1>F/-Fi
x6%FcqF[jpF^jp@$F7YF?>FCFejp>F^]lFijp>Fh\lFijp>Fc[lFijp>Fb`lFijp>Fc`lFijp>Ff[lF
ijp>FijlFijp>F`hlFijp>Fj[mFijp>Ff_mFijpFf[q6,F^]lFh\lFc[lFb`lFc`lFf[lFijl-FE6$F
IF`hlFj[mFf_mF,F,F,6#F^_m63F]amFg\qF]oFaoFa\nFhboFhboFhboFiboFhboFiboFhboFj[oFi
boF]]pFh\n7'FZFenF^oFfboF\oF,,
I,EigenSolverw,6$'F*-Fbz6#%(polynomG>'%'digitsGFjpFjel6-%%fB2CGF\qFfpFdpF\clFiv
%%irndGF[glF[_o%"VGF\[l6"F,C0>FCF`do>F^]l-Ffgm6#F_`m>F/w,6$'%"fGFd_q'F\cl-Fbp6#
F\elFe^l6"F,C$>F/-%&tableG6#-Fiho6%w,6$F[glFaclF,6$FfrFgrF,/FcqF4F,F,F,6#F^_m6$
7'FZFenFg_lFfjlFhn7'FZFenFg_lF]vFhn7#-%'coeffsG6%F4Fcq.Fdr7#FdrO-FE6$w,6#FaclF,
6$FfrFgrF,-Fix6%-%)assignedG6#&Fh_lFhqF[cqF[xF,F,6$Ff^lF/6#FW6$7'FZFenF_`lFbamF
hn7'FZFenF_`lF\pFhnFcqF,F,F,6#F^_m6%7'FZFenF^amFfoFhn7'FZFenFfu"#lF\o7'FZFenFba
lFb\oF^v>%'DigitsGFcq>Fh\l-F[hm6$F4F^]l>Fc[l&-Fchm6$Fh\lF^]lF]t>Fb`l-FgqFd^m-Fb
\l6$Q5System~has~%d~roots|+F,Fb`l>Fc`l,$-Fdgl6#;!%+5FjglF[hl>Ff[l-Fh\m6$*&Fj[mF
W-Fc`lF,FW-Fhdl6$Fj[mFC>Fijl-&Fjr6#%5MultiplicationMatrixG6'Ff[lFc[l-F^aq6#-%'E
quateG6$Fc[l7#-Fido6#F_boFh\lF^]l>F`hl&-&Fet6#%-EigenvectorsG6#-%&evalfG6#FijlF
i[p>F`hl-&%"|irG6#%"/G6%F`hl%#~$G-%".G6$-Fcz6$Fb`l/%%fillGFW&F`hlF]tO-Fcgq6$-Fg
ao6#-FE6$w,6#FbclF,6$FfrFgrF,-F\]m6$-Fir6%F4Fh_lFj]lFf\mF,F,6*FdpFh\lFfpF^]lF\c
lFc[lFi_qF/6#FW6$7'FZFenFfbmFgioFhn7'FZFenFfbmF\vFhnFCF`hlF,F,F,6#FW61FY7'FZFen
FjelFboFjo7'FZFenF\flF]\oFjo7'FZFenF^oFfoFjo7'FZFenF^oFagoFjoFj[o7'FZFenF^oFfjl
Fjo7'FZFenF^oF]`lFjo7'FZFenF^oFfjlF\p7'FZFenF^oFbenFjoFfiqF^fl7'FZFenF^oF[oFjoF
jam7'FZFenF^oF_oF^vF,,
I$srtw,6$'FbclFbzFepF,6$FfrFgrF,-F`^m6$F4w,Ff^mF,6$FfrFgrF,-&Fjr6#%*TestOrderG6
%FcqF4F^sF,F,6$FfpFcq6#F^_m6$7'FZFenFgio"$-"Fhn7'FZFenFgio"#rFhnF,F,F,6#F^_m6$7
'FZFenFgn"$."Fhn7'FZFenFgnF`emFhnF,,
I,poly2matrixw,6%Faz'%#nFGFjpFehp6%%%monsGF^gl%%cffsG6"F,C$>F^]l7#-F\bq6%-FG6#-
Fh\m6$*&(%$q_qGFCFW&F4FUFW/FC;FWFcqFds.F/6$-Fgao6%Fcq-FgqFjcmw,6$F^gl%"jGF,6$Ff
rFgrF,-%&coeffG6$&Fh_lFbq(Fg\rF4F,F,6$Fj[rF^]l6#F^_m6$7'FZFenF\tF`emFhn7'FZFenF
\tFbenFhn-Fcz6#7#F/F,F,F,6#F^o6%FY7'FZFenF_`lF_flFjo7'FZFenF^oFf\oF\oF,,
I/permuteColumnsw,6%FapF[`q%#V1G6#Fahp6$FfrFgrF,&F46$Fau7#-F`dl6$-&%*ListToolsG
6#%'SearchG6$F/Fcq-Fhdl6$F/FdsF,F,F,6#F^o6&7'FZFenF_goFj[nFhn7'FZFenFa_mFc_mF]b
l7'FZFenF_goFg_lFhnF[`rF,,
I)sparsityw,6#'FapFgao6#%&numzrG6"F,C$>F/-Fgq6#-F`]l6$w,Fc]lF,6$FfrFgrF,-F_t6#/
F4F[xF,F,F,6#FW6$7'FZFenF]\nFioFhn7'FZFenF]\nFe_lFhnFifo*&F/FW-%$mulG6#-FQ6$FWF
4FenF,F,F,6#FW6%F]am7'FZFenFjnFfblF\o7'FZFenF^oFfbmFfnF,,
I(matrixSw,6''F\clFbpFdzFcpFepFjv6%F]q%#V0GFiv6"F,C&>F^]lFfq@$0Fd[lF^]lYQIlists
~B0~and~B~must~have~the~same~lengthF,>F`al-F^r6%-FE6$w,FdbqF,6$FfrFgrF,FhrF,F,F
dx6#FW6$7'FZFenFg_l"#")Fhn7'FZFenFg_lF]\nFhnF4F^]lF_w@%/-FQ6$FWFCF^]lO-Fe^r6%F/
FC-FczFbqYQ=failed~to~construct~matrix~SF,F,F,F,6#Fgy6*Fe[o7'FZFenF]`lFa_mFjo7'
FZFenF^o"#%)F`o7'FZFenFd\nF_oFdo7'FZFenF^oF[[rFjoFgfp7'FZFenFbalFgoF^v7'FZFenFb
alFjoFdoF,,
I*quotientsw,6&'F\doFd_qFcpFepFjvF,6"F,C$-Fir6'F4FcqFds.%"QG/FasFesFberF,F,F,6#
Fcu6%FiyF`\oFhbmF,,
I-monPartitionw,6'Fghp'%#GrGFbpFepFjv>FihpFbcm6-FezF\cl%#aBG%"RG%#B2G%#RBGFdp%#
nGGF[_oF]qF^gl6"F,C->F/&-Fchm6$FcqFdsF]t>FC-Fi[l6$-Fix6%/FexFbcmF/FexFgv>F^]l-F
E6$w,Fc]lF,6$FfrFgrF,F`_lF,F,6$FhhpF46#FW6$7'FZFenFfuF\pFhnF]^mFC>Fh\l-Fiiq6$-F
i[l6$-Fbel6$F^]lFCFbpFds>Ff[lF[dp>Fc[l-FE6$w,Fc]lF,6$FfrFgrF,*&F4FWF^sFenF,F,Fc
gr6#FWFegr-F_elF]hr>FC7$-FQ6#-Fiiq6$-Fi[l6$-Fbel6$FCFc[lFbpFds-FQ6#-Fiiq6$-Fi[l
6$Fc[lFbpFds>6$Fb`lF^]l6$7$F[fpF_`m-FE6$w,Fc]lF,6$FfrFgrF,F`_lF,F,Fcgr6#FW6$7'F
ZFenFbenF\flFhn7'FZFenFbenFc_mFhnFC@%F]gr>Fijl-Fdeq6(F4FC-F^aq6#-F[fq6$FC7#-Fid
o6#FiapFcqFdsFcerC%>Fijl-Fdeq6(F4F/-F^aq6#-F[fq6$F/7#-Fido6#;FWFe\lFcqFdsFcer>F
`hl-F]br6'FCF/FcqFdsFes>Fijl-Fix6%0FesF[x-F\^n6$-Fcgq6%F`hlFijl-&Fdt6#%(Inverse
G6$FesF`hlFes-Fcgq6%F`hlFijl-&Fet6#%.MatrixInverseGFgim>Fc`l-Fi[l6$,&-FczFf^nFW
-Fcgq6$&Fijl6$;FWFf[lFau-FczFUFenFbpO6(F^]lFCFb`lFijlFc`l-Fgao6#7#-F`dl6$-Fidr6
&&Fc`lFgdpFcqFdsFes/Fj[mFi]sF,F,F,6#Fgy62Fiel7'FZFenF^oF\flFjo7'FZFenF^oFjuFjoF
a\nF[bm7'FZFenF^oFjelFjoFjam7'FZFenF^oFefpFjoF[bmFgfp7'FZFenFbal"$6"Fjo7'FZFenF
balFgjoFjo7'FZFenFbalFioFjo7'FZFenFbalF[\nFjo7'FZFenF^oFcamFjo7'FZFenF^oF\hpF^v
F,,
I)matrixHiw,6&FazFcpFehpFjv62%*undetPolyG%#pvGFg[rFafr%#uHG%%leqsGFjcoF^gl%#dFG
%#dGGF][lF_[l%"hGFb]r%"pGF^_l6"F,C)>FC-Fh\mF`w>F^]lFfq>Fh\lFd[l>Fijl-FE6%Fh]lF4
Fds>F/w,6&FehpFh_sF][lFb]r6#Fi[r6"F,C%-F\bq6%-FG6#,&FWFW-Fh\m6$)FcqFh_l/Fh_l;FW
FdsFWF4F[]r>F/F`^r-Fh\m6$*&&F/6#Fj]lFW&%#_vG6$FesFj]lFW/Fj]lFi[sF,F,6&F^`s82F^_
l836#Fcu6&7'FZFenF]`lFfoFhn7'FZFenFbal"#dF\p7'FZFenFbalF\pFjo7'FZFenFbalFcblF\p
?(Ff[lFWFWFh\lFjqC%>6$Ff_mF`hl6$F[x-FE6$w,Fc]lF,6$FfrFgrF,-Ffil6$F[xF4F,F,F,6#F
W6$7'FZFenFd\nFfjlFhn7'FZFenFd\nFa_mFhn,&7#-Fido6$-Fh]l6$&FcqF[[mFdsF^]lFWFijlF
en?(Fj[mF[xFWF,1,&Fj[mFWFf_mFenF[xC&>Fc[l7#-F`dl6$-F/6&FdsFC,&&F`hl6#FdhlFWFj[m
FWFdhl/FdhlFgcn>Fb`l<#-F\bq6$-FG6#,&FadsFen-Fh\m6$*&&Fc[lF^esFW&F4F^esFWF_esFWF
ds>Fc`l-%'msolveG6$Fb`lFes@$/-Fgq6#<#Fc`lF[x>Ff_m,&Fj[mFWFWFW>&FailF[[m-F\^n6$-
FE6%-%"@G6$FGFIFc[lFc`lFesO-Fgw6#-F`dl6$-&Fcz6#%$rowG6#Fhfs/Ff[l;FWFh\lF,F,F,6#
Fcu62F]am7'FZFenF\pF]vFjo7'FZFenFboFbamFjo7'FZFenF^vFgioFjo7'FZFenF\]p"$5"FjoFa
iqF\bl7'FZFenFbalF][rFjo7'FZFenFbalFjyF]bl7'FZFenF^amFecqFjo7'FZFenF^am"#uFjo7'
FZFenF^amFbenFjo7'FZFenF^amFibsF`o7'FZFenFc_mFbamFjoFabl7'FZFenF^oFjuF^vF,,
I*matrixHniw,6(FazFcp'%"CGFgao'Fi_oFgaoFehpFjv6-%,undetPolyniGFg[rFafr%#H0GFi_s
Fj_sFjco%%parsGF^glFb]rF^_l6"F,C+>FCFfq>F^]lFd[l>F/w,6&'F]`sFd_qFehp'F^glFjp'Fb
]rFjpF[as6"F,C%-F\bq6%F4FcqF[]r>F/F`^r-Fh\m6$*&&F/6#Fh_lFW&F_bs6%FdsFesFh_lFW/F
h_lFi[sF,F,6$F^_lFj[m6#Fcu6&7'FZFenF_`lFfoFhn7'FZFenFbalFa_mF\pFjbs7'FZFenFbalF
[oF\p>Fh\l-F\^n6$-FE6$FG-Fcgq6$FdsFesFf`l>Fc[l-Fgao6%F^]lFCw,Fa]rF,6$FfrFgrF,-F
f\m6&&Fh_l6$F4FcqF_sF4FcqF,F,6(FdisFh\lF\qFexFcisF/6#F^_m6$7'FZFenFisFgioFhn7'F
ZFenFisF\oFhn>Ff[l<#-F`dl6$&%#_uGFifq/Fijl;FW-Fgq6#-Fbel6$-FTFd^mFex>Fb`l-FE6%F
\bq<#-F`dl6$-F\^n6$-FG6#,&&FcqFifqFen-Fh\m6$*&&Fc[l6$FijlF`hlFW&F4FgimFW/F`hlFb
eoFWFf`l/FijlFgcnFex>Fc`l-F^fs6%Fb`lFf[lFf`lO-F\^n6$F[gsFf`lF,F,F,6#Fgn6,Fiy7'F
ZFenF`^lF]vFjoF_hsFaiqFfiq7'FZFenF^oFecqFjoFa_s7'FZFenF^oFi\qFjoFj[oF[isF,,
I*syzModulew,6'FazFcp'%"AGFgaoFepFjv6,Fg[rFafr%"eG%"LG%#LtGFapF]qF\clF^glFb]r6"
F,C.>F/Ffq>FCFd[l>F^]l-F`dl6$-Fcz6$FC<#/FijlFW/FijlFbeo>Fh\l7#-F`dl6$7#-&Fjr6#%
,LeadingTermG6$F`^tFesFh`t>Fc[l-FE6$w,Fc]lF,6$FfrFgrF,*&&F4F]tFW&F4Fi[pFWF,F,F,
6#FW6$7'FZFenFfuFisFhnF]^mFh\l>Fb`l-Fgao6$FCw,Fa]rF,6$FfrFgrF,*&-%$lcmG6$&F[cqF
i[p&Fg]rFi[pFWF_joFenF,F,6&F[`tFh\lF\`tFc[l6#F^_m6$7'FZFenFagoFb\oFhn7'FZFenFag
oF\tFhn>Fc`l7#-F`dl6$-F`dl6$,(*&&Fb`lFe^tFW&F^]lFifqFWFW*&&Fb`l6$F`hlFijlFW&F^]
lFgimFWFen-Fgw6#-Fidr6&z'6&FfctFictF`^t&FcqFgim[[[\[[[[[\[[mFW\[[[[[\[[[[[mFenF
cqFesFexFen/F`hl;,&FijlFWFWFWFCFh`t>Fc`l)-FgaoFabpF]bo>Ff[l-Fgao6#7#-F`dl6$-Fid
r6&&F4FifqFcqFesFex/Fijl;FWF/>Fc`l-FE6$FG-Fgw6$-Fcgq6$Fc`lFds,&-&Fet6#%/Identit
yMatrixGF=FW-Fcgq6$Ff[lFdsFen@$F[y>Fc`l-F\^n6$Fc`lFexO&Fc`l6$-%'removeG6$w,6#F^
glF,6$FfrFgrF,-&%+ArrayToolsG6#%'IsZeroG6#&Fh_l6$F4FauF,F,6$F]qFc`l6#FW6$7'FZFe
nFagoFbamFhn7'FZFenFagoFfbmFhn7#-Fido6#;FW-FQ6$7$FWFWFc`lFauF,F,F,6#Fgy60Fiy7'F
ZFenFjnFfbmF\oFdblFciq7'FZFenF^oFgalFjoF]]pFh\p7'FZFenF^o"$A"FjoFcenF_\n7'FZFen
F^oFcoFjoF[fl7'FZFenFagoFe_lFjo7'FZFenF^oFjalF^vF,,
I+matrixHsyzw,6(FazFcpF_isFg_tFepFjv6$F]q%&ThetaG6"F,C%>F/-Fd_t6'F4FcqFesFexFf`
l>FC-Fgao6%-FQ6$FbhtFds-FQ6$FbhtF/w,Fa]rF,6$FfrFgrF,&Ff^lFb\tF,F,F,6#F^_m6$7'FZ
FenF`oFibsFhn7'FZFenF`oFj^nFhnO-F\^n6$-FE6$FG,&Fh[tFW-Fcgq6$FCF/FWFf`lF,F,F,6#F
gn6&Feu7'FZFenF^oFc_mFjoFfht7'FZFenF^oFjoF^vF,,
I(supportw,6$Fe`qFehpF,6"F,C$F[bq<#FdrF,F,F,6#F^_m6%7'FZFenFfoF\hpFhn7'FZFenF`o
FgioF\p7'FZFen"#nFgboFfjlF,,
I,fixTemplatew,6'%'admonsGFazFehp'%$monGFbp'F`frFbp60Fg[r%%monFG%&admonGF^glFb]
rFberF^[l%#xFGFapFbbrF[[lF[`q%%mon1GFahp6"F,C.>F/Fd[l>FC-FE6$w,6#Ff`qF,6$FfrFgr
F,-F`[uFi]lF,F,6$F\qFds6#FW6$7'FZFenFhnFd\oFhn7'FZFenFhnFfjlFhnFcq>F^]l7#-Fido6
$F]hlF/?(Fh\lFWFWFfqFjqC%>Fc`lFew?(Fc[lFWFWF/FjqC$>Fb`l-FE6$w,6#%#mfGF,6$FfrFgr
F,-Fix6%-%'divideG6%&F^sF]bsF4.%"qGF^_uF[eoF,F,6&F_\uF4F^glFh\l6#FW6$7'FZFenF\p
FgioFhn7'FZFenF\pF\vFhn&FCFd^m@$0Fb`lF]hlC%>&F^]lFd^m<$Fh_m-FQ6#Fi_u>Fc`lFjq[@$
4Fc`lYQ;failed~to~correct~templateF,>Fail7#-F`dl6$-Fi[l6$-Fg[m6$-Fi[l6$&FesFd^m
FgvFi_uFcz/Fc[lFcet>Ff[l7#-F`dl6$-F`dl6$*&&FcqFd^mFWFdhlFW-Fhdl6$Fdhl&FailFd^mF
^au>Fe^t-F^r6%Ff[l-FgqF[[mFds>Fj[m-Fbel6$-Fi[l6$F`hlFgv-Fi[l6$FexFgv>Fj[m-Fiiq6
$7#-FQFgdp-Ffgm6#-FQF`w>Ff_m-Fgw6$Fibu-FQ6#Fex-Fb\l6#Q0Template~fixed|+F,O6&Fai
lFijlF`hlFf_mF,F,F,6#Fgy68FYFeht7'FZFenFisFgalFjo7'FZFenF]\oFf\pFjoF\blFjbsFdhs
Ffhs7'FZFenF^am"#))F`o7'FZFenFd\nFgalFjo7'FZFenF]\oFg\nFjo7'FZFenF_oF[xFb\o7'FZ
FenFbalF[\uF`o7'FZFenFisFgalFdo7'FZFenF^oFf\pFjo7'FZFenF^oFj^nFjoFi^sF`\nF^[u7'
FZFenF^oF`^lFjoFafl7'FZFenF^oFisF^vF,,
I2constructTemplatew,6&'%"HG<$FgaoFbpFazFehpFb\u6+Fg[rFa\uFf\uFapFbbrF[[lF[`qFb
]rFahp6"F,C+>F/Fd[l>FC-Fix6%-F[dl6$F4Fgao7#-F`dl6$&-F^r6%&F46$FauFf[l-FQ6$FbhtF
4FdsFi[p/Ff[lFcetF4>F^]l7#-F`dl6$-F`dl6$*&FadsFWFijlFW-Fhdl6$FijlFfapF_fu>6$Fh
\lFc[l-F^r6%F^]lF_]rFds>Fb`l-Fbel6$-Fi[l6$Fc[lFgv-Fi[l6$FesFgv>Fb`l-Fiiq6$7#-FQ
Fb`mFjbu>Fc`l-Fgw6$Fhgu-FQFbhl@$0-FQ6$FWFc`l-FQ6$FWFc[lC$-Fb\l6#Q8Template~is~i
ncomplete|+F,>6&FCFh\lFc[lFc`l-F\\u6'-Fbel6$-Fi[l6$Fc`lFgvF`guFcqFdsFCFes6%FC-F
e^r6%Fh\lFc[lFc`lFc`lF,F,F,6#Fcu6.7'FZFenF\pFgnFhnFehtFc_tFhalFi^sF`\nF^[uFdduF
gfp7'FZFenFbalF\flF\p7'FZFenFbalFeamFjo7'FZFenF^oFc_mF\oF,,
I-adjustParamsw,6'Faz'FjduFgaoFb\u'F\qFgvFjv65Fg[rFafr%#H1G%#LmG%%colsGF[`tFa\u
FbbrF[[lFj_t%#smG%#rmG%#npG%#ssG%$prmGFj_sFjcoFb]rF^gl6"F,C3>F/Ffq>FC-FQ6$FbhtF
cq>F^]lFcq>Fh\l-F`dl6$-F^r6%&Fcq6$Fau85FCFes/Fd[vFcet>Fc[l7#-F`dl6$-Fjft6$w,Fc]
lF,6$FfrFgrF,-%+membertypeG6$Fjp-Fi[l6$&&Fh_l6#,&Fj]lF^_mFenFW6$FauF4FbpF,F,6&F
_juFh\lFb]rFd[v6#FW6$7'FZFenF\vFjalFhnFgjl7#-Fido6#;FW-FQ6$7$FWF^_m&Fh\l6#,&Fd[
vF^_mFenFWFe[v>Fa`l6$7#-F`dl6$&Fc]v6$Fau&Fc[l6#Fd[vFe[v7#-F`dl6$&&Fh\l6#,$Fd[vF
^_m6#F]^vFe[v>Fj[m7#-F`dl6$-FE6$w,Fe^lF,6$FfrFgrF,-F`[u6$-FG6#*&F\_uFWF4FWFbsF,
F,6(F*F4Fb]rFd[vF\qFes6#FWF^cq&Fc`lF^^vFe[v>Ff[l-Fi[l6$-FE6$FQ-FE6%-F^gs6$FQFi[
lFj[mFgvFgv>Fijl-Fi[l6$-Fbel6$Ff[l-Fi[l6$FdsFgvFbp>Fj[m-FczFgdp>Ff_m-FE6$w,6#Fj
_tF,6$FfrFgrF,-F`]l6$w,F]gtF,6$FfrFgrF,-F_jm6$F^sF_joF,F,6&Fj_tF4FajuFh_l6#FW6$
7'FZFenF\vF`blFhnFgjl<#-Fido6#;FW-FQ6$FWFh_lF,F,6$FajuFj[m6#FW6$7'FZFenFfu"#gFh
nF]^mFijl>Fail7#-F`dl6$-%"+G6#-F`dl6$-Fgq6#-F`]l6%%$hasGFf_m&&Ff_mF^^v6#86/Fecv
;FW-Fgq6#Fccv/Fd[v;FW-Fgq6#Ff_m>Fdhlw,6&F^glFb]rFbjuFcjuF,6$FfrFgrF,52-Fgq6#&Fd
sFbq-Fgq6#&FdsFhq3/FgdvFddv2&FesFbq&FesFhqF,F,F,6#Fcu6$7'FZFenFjnF`vFhn7'FZFenF
jnFisFhn>Fcbs-F`^m6$7#-Fido6#;FW-FgqFifqw,Fa]rF,6$FfrFgrF,-Ff\m6&F4FcqFh_lFj]lF
,F,6(FbjuFf_mFcjuFailFdjuFdhl6#F^_m6$7'FZFenF\oFd\oFhn7'FZFenF\oFfjlFhn>Fijl&Fi
jl6#Fcbs?&F`hlFijlFjqC+>Fh\l-F`dl6$-F^r6%&F^]lFc[vFCFesFe[v>Fa`l6$7#-F`dl6$Fc]v
Fe[v7#-F`dl6$Fc^vFe[v@$/-Fgq6#-FTFb`mF[x[>Fj[m7#-F`dl6$-FE6$w,Fe^lF,6$FfrFgrF,F
__vF,F,Fd_v6#FW6$7'FZFenF`^lFb\oFhn7'FZFenF`^lFisFhnFf_vFe[v>Ff_m-FE6$w,Fc]lF,6
$FfrFgrF,<#-&Fb_r6#%*SearchAllG6$FW-FE6$w,6#Fg^mF,6$FfrFgrF,-Fgq6#-F_el6$F4<#Fh
_lF,F,6$Fj_tFh_l6#FW6$7'FZFenFbamFf\oFhn7'FZFenFbamFj^nFhnF4F,F,6$Fj_tF`hl6#FW6
$7'FZFenF_goFf\pFhnF`goFj[m>Fdbs<#-F`dl6$-FQ6#-FE6$w,F]_lF,6$FfrFgrF,-FQ6#-Fi[l
6$&&Fh_lF]bsFg\vFgvF,F,6&F[`tFb`lFb]rFd[v6#FW6$7'FZFenFd\nFgalFhnFjcsFccvFe[v>8
4-F^fs6$FdbsFex@$/-Fgq6#<#F\\wF[x\>F^]l-F\^n6$-FE6%F]gsF^]lF\\wFex-Ffdu6&F^]lF4
FesFdsF,F,F,6#Fgy6?FielFeht7'FZFenFisF`blFjo7'FZFenFcblFj^nFjo7'FZFenF^oFb\oFjo
7'FZFenF^o"$<"Fjo7'FZFenF^oFddrFjo7'FZFenF^oFgboFjo7'FZFenF^oF`emFjoFgiq7'FZFen
F^oF_`lFjo7'FZFenF^oFgioFjo7'FZFenF^o"#*)FjoF_vFe]w7'FZFenF^oFfuFjoF\bl7'FZFenF
balFgalFjo7'FZFenFbalFcoFjo7'FZFenFbalFfalF`o7'FZFenFc_mF[xFb\o7'FZFenFbalFg\nF
jo7'FZFenFbalFefpFjo7'FZFenFbalFf\pFjo7'FZFenFbalFa_mFjo7'FZFenFbalFjoF`o7'FZFe
nF\oF[xFd\o7'FZFenFbalF`oFjo7'FZFenF^oFhnF\pF,,
I4isActionMatrixFoundw,6('F[_oFgaoF``r'F]frFbpF`br'FafrFjpFjv6(%#tMG%#T1GFivFdr
%"rGF^_l6"F,C'>F^]lFahl>Fh\l,&F^]lFWFexFen>F/-F\^n6$-%*GaussjordG6$Fcq.Fc[lFf`l
>FC-F\^n6$-Fgw6$,$&F/6$;,(Fc[lFWFexFenFWFWFc[l;,$F^]lFenFenFen-Fgao6%Fh\lF^]l<#
-F`dl6$/6$,(Fh\lFWFb`lFenFWFW-Fa_r6$&Fds6#,$Fb`lFenFesFW/Fb`lF[hsFf`l-&Fet6#%&E
qualGFh[mF,F,F,6#Fgn6(7'FZFenF`^lFgnFhn7'FZFenF_goF]\nFjo7'FZFenFbenFgoFjoFfiq7
'FZFenF^o"$;"Fjo7'FZFenF^oFa_mF\pF,,
I/SchurReductionw,6(F``r'F[`qFczF\ip'%#nEGF[wFhpF]ip68%#rgG%$crgGFdr%#M1G%#bsG%
#M2G%$tM2GF`_w%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GF_fr%#B3G%#B4G%$iB1G%&rperm
G%&cpermGF^`sF^gl6"F,C6@$/-Fgq6#Ff`lF[xO6'F4FcqF[xFbcmFbcm>F/7#-F`dl6$-FQ6#7#-F
ido6#;,&-Fh\m6$-FQ6$FW&Fds6#89/Fdew;FW,&88FWFenFWFWFWFW-Fh\m6$F`ew/Fdew;FWFhew-
Fhdl6$FhewFf`l>F^]lFe\l>FC7#-FQ6#-Fbel6$<#-Fido6#;FWF]fu<#-FQF=>Fh\l-Fgw6$&F46$
F/Fau&F46$FCFau>Fb`l&Fh\l6$Fgcn;FWFes>Fc`l-F\^n6$-Fj_w6$)Fb`lF]bo.Ff[lFex>Ff_m-
FE6$w,F]gtF,6$FfrFgrF,-Fa_r6$FW-Fi[l6$F[cqFbpF,F,6$F_cwFc`l6#FW6$7'FZFenF]`lF]
\oFhnF^`l<#-Fido6#Fi]s>Fail-Fi[l6$-Fbel6$<#-Fido6#;FW-FQ6$Fb]vFc`lFf_mFbp>Fecv-
Fi[l6$7%-FQF]dv-FQFh`m-Fido6#;F[bn-FQ6$FbhtFh\lFbp>Fecv&7$F[gwF_`mFdcv>Fijl-Fgw
6%&Fh\l6$7#F]jwFau&Fh\l6$7#F^jwFau&Fh\l6$;F[bnFenFau>F`hl-F\^n6$-Fj_w6$&FijlFeg
wF]hwFex>Ff_m-FE6$w,F]gtF,6$FfrFgrF,FchwF,F,6$FacwF`hl6#FWFihwF[iw>Fail-Fi[l6$-
Fbel6$<#-Fido6#;FW-FQ6$Fb]vF`hlFf_mFbp>877%F]jwF^jw-Fido6#;F``p-FQ6$Fb]vFijl>Fj
[m-%$<|gr>G6%&Fijl6$FauF\[x&Fijl6$FauF_[x&Fijl6$Fau;F``pFen>6&FdhlFcbsFdbsF\\w6
&&Fj[m6$Fi]sFi]s&Fj[m6$Fi]s;,&Ff[lFWFWFWFen&Fj[m6$Fe^xFi]s&Fj[m6$Fe^xFe^x>Fd[v-
Ff\s6$FexFdhl6'-F\^n6$,&F\\wFW-Fcgq6%FdbsFd[vFcbsFenFex&Fcq6#7$F^jw-Fido6#;F``p
-FQ6$FWFcqFf[lFecvF\]xF,F,F,6#Fgn687'FZFenF_goFgnFhn7'FZFenF^oFd\oF`o7'FZFenFis
F`oF^v7'FZFenF^o"#)*FjoFj^sFhalFj[oFa\nFciq7'FZFenF^oFf\oFjo7'FZFenF^oF]\oFjo7'
FZFenF^oF][rFjo7'FZFenF^oFboFjo7'FZFenF^o"#oFjo7'FZFenF^oFfalFjoFc`xFd`x7'FZFen
F^oFibsFjo7'FZFenF^oF[\uFjo7'FZFenF^o"#%*FjoFi`x7'FZFenF^oFjalF\oF,,
I0LinDepReductionw,6$F``rFjv6)F`_wF^_wF\cw%$tM1GFccw%&r2delG%&c2delG6"F,C*>FC-F
\^n6$-Fj_w6$)F4F]boF[]rFcq>Fc[l-FE6$w,F]gtF,6$FfrFgrF,FchwF,F,6$F^_wFC6#FW6$7'F
ZFenF]`lFcbvFhnF^`l<#-Fido6#Fcet>Fb`l-Fi[l6$-Fbel6$<#-Fido6#;FW-FQ6$Fb]vFCFc[lF
bp>F^]l&F46$-Fjft6$w,F]gtF,6$FfrFgrF,-F_t6#-FhdlFbfoF,F,6$FdaxFb`l6#FW6$7'FZFen
F_`lF]vFhnF`cq7#FgfwFau>Fh\l-F\^n6$-Fj_w6$F^]lF[]rFcq>Fc[l-FE6$w,F]gtF,6$FfrFgr
F,FchwF,F,6$FcaxFh\l6#FWFihwFgbx>Fc`l-Fi[l6$-Fbel6$<#-Fido6#;FW-FfilFd^mFc[lFbp
6%&F^]l6$Fau-Fjft6$w,F]gtF,6$FfrFgrF,F\dxF,F,6$FeaxFc`l6#FW6$7'FZFenF_goFbenFhn
F`go7#-Fido6#;FW-FQ6$Fb]vF^]lFb`lFc`lF,F,F,6#F^_m6+7'FZFenF_`lFgnFhnFjamFe`xFfh
tFd`xF^[uFc`xFe]wFd^rF,,
I)rectTordw,6&FazFfz'%#TsGFbpFjv6*Fg[r%#dgGF]gl%#nnG%$GBsGFafnF\[lF^gl6"F,C+>F/
Ffq>FC7#-F`dl6$*&-Fh\m6#-FE6%Fh]lF4Fc`lFWF/Fen-Fhdl6$Fc`lFcq>F^]l-FE6$w,6#F][lF
,6$FfrFgrF,*$F4FenF,F,F,6#FW6$7'FZFenFfuFagoFhnF]^mFC>Fh\l-Febt6#-FQ6#-FE6$%&de
nomGF^]l>F^]l*&Fh\lFWF^]lFW>Fc[l-FE6$w,Fc]lF,6$FfrFgrF,-F[hm6%F^sF4/FasF_sF,F,6
&F*F4FipFes6#FW6$7'FZFenFfnFcamFhn7'FZFenFfnF]`lFhnFds>Fb`l7#-FQ6#<#-F`dl6$&-F_
co6$&Fc[lF[[m-F`ep6$F`[y&FdsF[[mF]t/Ff[l;FWFadq>Fb`l-FE6$w,FgeoF,6$FfrFgrF,-Fih
o6%w,Ff^mF,6$FfrFgrF,F^ioF,F,F,6#F^_m6$7'FZFenF\pF\oFhn7'FZFenF\pFd\nFhnF4Fh_lF
,F,6$F]glF^]l6#FW6$7'FZFenFfuFfjlFhnF]^mFb`l-FE6$w,Fc]lF,6$FfrFgrF,-Fj`oFi]lF,F
,6$F\qFcq6#FW6$7'FZFenFbalF`^lFhn7'FZFenFbalFjnFhnFb`lF,F,F,6#Fcu6,F]amFehtF`]w
Fa\nFj[oF\bmFd`x7'FZFenF^o"#(*FjoF[bm7'FZFenF^oFd\nF\pF,,
I,filterBasesw,6&Faz'F]cmFbp'%%nQBsGFjp'%#ffGFdhp6&%#mFG%#BsGFeju%"NG6"F,C(>Fh
\l-F]il6#*&FesFWFdsFW>F/-Fi[l6$&-F^r6%F4FfqFcdoFi[pFgv>FC-FE6$w,Fc]lF,6$FfrFgrF
,-Fgq6#-F_el6$-Fi[l6$F4FgvFh_lF,F,6$F_^yF/6#FW6$7'FZFenFfuFbamFhnF]^mFcq>F^]l-F
`^m6%FC%">G/%'outputG%,permutationG-Fb\l6$QA%d~quotient~space~bases~removed|+F,
Fh\l7#-FQ6$;FW,&FdsFWFh\lFenF^]lF,F,F,6#Fcu6)FY7'FZFenF`^lF\flFjoF_\nFe]wFi^sFg
\o7'FZFenF^oF`^lFe_lF,,
I-filterBases2w,6*Ff[rFehp%$CMsGFfgxFbgxF]cmFhpF\^y6;FjerFfpF\clFi_oF[^yFivF^gl
%#vBG%#tBG%#mpGFhhpF]frF[_oFdpF`isFjdu%$cHsGFdr%$avoG%#msG%#moGFejuFa^yF^_l%"cG
6"F,C+>Fc[lFehl>Fb`l-Fgq6#&Ff`lF]t>F\]xFbcm>Fhew"(+++">8:-F]il6#*&Fb\qFWFc[lFW?
(Fc`lFWFWFc[lFjqC(>6&F/FCF^]lFh\l6&&FesFabp&FexFabp&Ff`lFabp&FdsFabp@$0F_]rFb`l
\>6%Ff[lFijlF`hl6%-FczFjcm-F^aq6#-F[fq6$F^]lF]fqFfby?&Fj[mFcqFjqC*>Ff_m-FE6$w,F
i^rF,6$FfrFgrF,*&F4FWFh_lFWF,F,6$FhhpFj[m6#FW6$7'FZFenFfbmF]\nFhn7'FZFenFfbmFis
FhnF^]l>Fail-Fdeq6(Fj[mF^]lFijlF/FC/FasF[]l>Fdhl,&-FczF]dvFW-Fcgq6$FailFf[lFen>
Fcbs-Fgao6#7#-F`dl6$-Fidr6&&Fdhl6#8;F/FCF[]l/F`fyF_bo>Fdbs-F\^n6$-FE6$FG-Fcgq6$
FcbsFh\lF[]l>F\\w7#-F`dl6$-Fh\m6#&Fdbs6$FauF`fy/F`fy;FWF4>Fd[v-Fh\m6$-Fix6%-F[d
l6$8<Fibv-Fgq6#FjgyFW-Fhdl6$FjgyF\\w@$2Fd[vF`hlC$>F`hlFd[v>FecvFj[m@$2F`hlFhewC
$>FhewF`hl-Fb\l6%Q?Smaller~template~found:~%d,%a|+F,FhewFecv>F\]x7$-FQ6#F\]xF`h
l>Fdew-F`^m6%F\]x%"<GFa`y-Fb\l6$Ff`yFhby7#-FQ6$;FW,&Fc[lFWFhbyFenFdewF,F,F,6#F]
bl6?Fiel7'FZFenF\tFjuFjo7'FZFenF`oFfboFjo7'FZFenFgjo"$@"Fjo7'FZFenF`]q"$M"Fjo7'
FZFen"$T""$f"FjoF\bl7'FZFenFbalFd\oFjo7'FZFenFbalFjuF`o7'FZFenF]\nF[xFd\oF\^wFd
hsFhhs7'FZFenF^amF\]pFjoFhhs7'FZFenF^amFgboFjo7'FZFenF^amF\flFjo7'FZFenF^amFgoF
jo7'FZFenF^amFcbvFjo7'FZFenF^amF^vF`o7'FZFenF\tFbenFjo7'FZFenFc_mFcblFjo7'FZFen
FbalFbvF`o7'FZFenF\vF\oFjo7'FZFenFbenF_flF\pFcbmFi^sFg\oF_ayF,,
I(iniProbw,6&F%F_ipF\^y'%#pnGFjp61F*%#vFGFipF\qFfgxFbgx%#GCGF]cmFcayFfpFi_oFdpF
^_uF[^yF^gl6"F,C,>F^]lFes>6$F/Fh\lFcgm>6$FCFh\l6$-FczF=<#F[fp>F`hl-Ffgm6#F[fp-F
b\l6$QJThe~problem~is~defined~by~%d~polynomials|+F,Fe\l>Ff_m-F[hm6%F/F`hl/FasF^
]l@$0-&Fjr6#%1HilbertDimensionG6$Ff_mF^]zF[xYQJthe~problem~has~infinitely~many~
solutionsF,-Fb\l6&QQVariables:~%a;~degrees:~%a;~number~of~roots:~%d|+F,7#F[fp-F
E6$Fh]lF/-Fgq6#&-FchmF_csF]t@%FcqC(>6%F^]lFb`lFijl-Fh\oFhq>FdhlFjev>Fc[l7#-F`dl
6$-F\^n6$-FE6$FG-Fi[l6$-Fcgq6$FefvFCFbpF^]l/Fcbs;FWFdhl>Ff[l7#-F`dl6$&-Fchm6$&F
c[lFffv&Fb`lFffvF]tFd_z>Fail-F`ay6*Fe\lFh\lFijlFc[lFb`lFf[lF^]lFds>6&FijlFc[lFb
`lFf[l6&7#-F`dl6$Fefv-Fhdl6$FcbsFail7#-F`dl6$F]`zFh`z7#-F`dl6$F^`zFh`z7#-F`dl6$
&Ff[lFffvFh`zC(>Ff[lF_im>6$FdhlF`hl6$F]buFf\z>Fc`l-F[hm6&F/F`hlF^]z/Fb`y%)exten
dedG>6$Ff_mFj[m6$&Fc`lF]t-Fgao6#&Fc`lFi[p>Fail-Ff]y6&F/Ff[lFdhlFds>Fc`z6&7#-F`d
l6$Fj[mFh`z7#-F`dl6$Ff_mFh`z7#-F`dl6$F`hlFh`zF`azO6)F^]lF/Fh\lFc[lFb`lFf[lFijlF
,F,F,6#Fcu6:Fe[o7'FZFenF]`lFisFjoF\\nF^[uF^\n7'FZFenF^oFfboF\pFhal7'FZFenF^oF_j
yF`o7'FZFenFfboF[\nFdo7'FZFenF^o"$G"F\pFgfp7'FZFenFbalFbenFjoF^bm7'FZFenFbalF_o
Fjo7'FZFenFbalFh`xFjo7'FZFenFbalFecqFjo7'FZFenFbalFabwFjoF[gpFe^w7'FZFenFbalFf
\oFjoFifp7'FZFenFbalF\flFjo7'FZFenFbal"$1"Fjo7'FZFenF^oF\flF^vF,,
I/TemplateFinderw,6(F%>'%,action_varsG-Fbp6#<$%'negintGFjpFbcm>'Fccw%'symbolGF`
ip>'%,filter_fracGFdhpF[x>FbfmFdfm>'%+schur_polsGF]ezFbcm6HFipF*F\qFfgxFbgxF]cm
Fcay%&avarsGF\glFivF[^yFa^yF^glFb]rFjerFfpFjhpFi_o%&tord1GFhhpF]frF\clF`frF[_oF
dpF`isFafrFjduF\ipFapF[`q%#flGFdrFb_nFchpF[by%#noG%$spoG6"F,C+>F/F[gm>8GFfby>8I
Fen>6)F/FCF^]lFh\lFc[lFb`lFc`l-Fc[z6&F4-%&evalbG6#/FdsF`ipFesF/>Ff[l-Fix6%/Fd[l
F[xF^]l-FE6$w,6#F[glF,6$FfrFgrF,F[cqF,F,6$F\qF^]l6#FW6$7'FZFenFfalFibsFhn7'FZFe
nFfalFdoFhnFcq>6%FijlF`hlFj[m6%F]bu-Fgq6#Fh_mFa`m>Ff_m,$*&Fj[mFenFijlFenF`v?(Fa
ilFWFWFj[mFjqC%>6&FcbsFdbsF\\wFd[v6&&Fh\lFh`m&Fc[lFh`mFg`m&Fc`lFh`m>Fecv-FQ6$FW
Fdbs?(FdhlFWFWFijlFjqC.>F\]x&Ff[lF^es>6(FhewFdewFhbyF`fyFjgy8=-Ffer6'F\]xFcbsFd
bsF/F\\w>8>F[hy>8?-Fix6%/Fds%%nstdG-Fc_s6&FCFjgyF^]lF/-F\is6(FCFjgyFgizFd[vF^]l
F/>6%8@8A8B-Fhiu6'FCF]jzFhbyF^]lF/>Fijz&-Fcbw6(FijzFjjzFhjz,(-FQ6$Fb]vFijzFWF`h
lFenF[jzFenF/Ff`lF]t>Fijz&-F_ax6$FijzF/F]t>8C-Fg^w6(F`fyFijzFhewFdewF[jzF/>6$8D
8E-FQ6$FWFijz>8F-F]`r6#Fijz@&3Fi[[l52F^\[lFefz3/F^\[lFefz2FgfzFc\[lC%>6%Fefz8HF
gfz6%F^\[lF_\[lFc\[l-Fb\l6(QUSmaller~or~sparser~template~found:~[%d,%d],%a,%a,%
a|+F,F^\[lF_\[l-Fhfq6$Fc\[lF^oF\]x-Fix6%F`jzFailFecv-F]hp6-F47$F^\[lF_\[l-Fhfq6
$Fc\[lFgyF/F^]lF\]xFdbsFdewFhjzFf`lF\gz4Fi[[lY6&Q@invalid~action~matrix:~%1,%2,
%3F,FailF\]xFdbs-Fb\l6*Q7%d%s,[%d,%d],%a,%a,%a|+F,-F]il6#*&,&*&,&FailFWFenFWFWF
ijlFWFWFdhlFWFWFf_mFWQ"%F,F^\[lF_\[lFe][lF\]xFg][l-Fb\l6&Q<Best~template:~[%d,%
d],~%a|+F,FefzF`][l-Fhfq6$FgfzF^oF,F,F,6#FW6?F^`xFf[n7'FZFen"$&="$&>Fjo7'FZFen"
$,#"$5#FjoFc]wFc`xFe]wFcenF\bl7'FZFenFbalF`emFjo7'FZFenFbalF\tFjoFdhsFhen7'FZFe
nF^amFcoFjoFeen7'FZFenF^amFbvFjoFfgp7'FZFenF^amFefpFjoFjjy7'FZFenF^amFcamFjo7'F
ZFenF^amF\tFjoFc\nFhgp7'FZFenFjelFfjlFjo7'FZFenFjelF\dzF\p7'FZFenFjelFbhsF\p7'F
ZFenFjelF[\uFdo7'FZFenF^amFhhtF\p7'FZFenF^o"#iF\pF,,
I$rnd,$f*F,F,6"F,,&-f*F,F,6#/%(builtinG%4RandNumberInterfaceGF,F,F,F,F,6%Fgn"%,
?F^amFWFjdqFWF,F,6$%6_thismoduledefinitionGF,F[hlF,,
I'rndMatw,6$'FdrFjp'Fb_nFjpF,6$FfrFgrF,-Fgao6%F4Fcqw,Ff^mF,6$FfrFgrF,-FgflF,F,F
,F,6#F^_m6$7'FZFenFgoFgalFhn7'FZFenFgoFb\oFhnF,F,F,6#F^_m6$7'FZFenFjnFfblFhn7'F
ZFenFjnFe_lFhnF,,
I'rndVecw,6#Fia[lF,6$FfrFgrF,-Fcz6$F4w,Fc]lF,6$FfrFgrF,F`b[lF,F,F,6#FW6$7'FZFen
Fe_lFioFhn7'FZFenFe_lF]vFhnF,F,F,6#FW6$7'FZFenFjnF\flFhn7'FZFenFjnFfbmFhnF,,
I&crossw,6#'FbclFczF,6$FfrFgrF,-Fgw6%-Fe]x6%F[x,$&F46#F^oFenFjat-Fe]x6%Fcd[lF[x
,$FiatFen-Fe]x6%,$FjatFenFiatF[xF,F,F,6#FW6$7'FZFenF]blFh`xFhn7'FZFenF]blF\pFhn
F,,
I-readTemplatew,Fc]q6LFcipFdipFipF\qFhhpFfpF\ipFjezF*F`is%#U0G%&tord0G%"UGFjerF
]frFecwF\clF^frF_frFezF`frF[_oFdpF]qFiv%#nRGF\cwF[`qFh^rF`_wFicwFjcwFapFcax%#t1
GFdaxFeaxF[[lFahp%#xEG%#xVGFe]q6"F,CE>6,F/FCF^]lFh\lFc[lFb`lF\\wFc`lFf[l8M-Fa]q
Fb\t>Fijl&FcgmF]t>Fjbp-F^r6%FijlFjevFh\l>Ff_mFf\z>Fail-Fiiq6$Fj[mFf_m>F`hl-Fe^r
6%F`hlFj[mFail>Fdhl-F[hm6%FijlFb`lF^]z>Fdbs&-Fchm6$FdhlFb`lF]t>F\\w-Fi[l6$F\\wF
gv>Fcbs-FE6$w,Fc]lF,6$FfrFgrF,FgdyF,F,6$FhhpFc[l6#FWFegrF\\w>Fd[v-Fiiq6$-Fi[l6$
-Fbel6$FcbsF\\wFbpFb`l>6$FjgyFgiz6$-Fgq6#F\\w-FgqF^^v>Fecv-FE6$w,Fc]lF,6$FfrFgr
F,*&F4FWFh_lFenF,F,Fjg[l6#FWFegr-F_elFbh[l>F\]x-%&getB0G6$FecvFh\l>Fecv7$-FQ6#-
Fiiq6$-Fi[l6$-Fbel6$FecvF\]xFbpFb`l-FQ6#-Fiiq6$-Fi[l6$F\]xFbpFb`l>F\\w7$-FQ6#-F
iiq6$-Fi[l6$-Fbel6$F\\w-Fi[l6$FecvFgvFbpFb`l-FQFdcv>6$FhewFcbs6$7$-FQF^^v-FQFgh
[l-FE6$w,Fc]lF,6$FfrFgrF,FgdyF,F,Fjg[l6#FWF`jrF\\w>Fdew-Fdeq6(Fc[lFdbs-F^aq6#-F
[fq6$Fdbs7#-Fido6#;FW-Fgq6#FdbsFdhlFb`lF^]z>F`fy-F]br6'F\\wFdbsFdhlFb`lF^]l>Fde
w-F\^n6$-Fcgq6%F`fyFdew-Ff\s6$F^]lF`fyF^]l>Fhby-Fi[l6$,&-FczF^^vFW-Fcgq6$&Fdew6
$;FWFgizFau-FczFgh[lFenFbp>6$F[jzFhjz&-Ffdu6&Fc`lFijlFh\lFhew6#;F^_mF^o>6'F[jzF
]jzFijzFjjzFi[[l-Fcbw6(F[jzFhjzFc`l,(-FQ6$Fb]vF[jzFWFjgyFenFgizFenF^]lFf[l>6%F^
\[lFefzF`][l-F_ax6$F[jzF^]l-Fb\l6$Q9Action~matrix~found:~%a|+F,-Fg^w6(FdewF^\[l
FcbsF\\wFgizF^]l>8J7#-FQ6$FWF^\[l-Fb\l6$Q3Template~size:~%a|+F,Fg_\l@$50&F/F]t&
Fg_\lF]t0&F/Fi[p&Fg_\lFi[pYQ/wrong~templateF,>8L-Fbel6$-Fi[l6$FhjzFgv-Fi[l6$F]j
zFgv>F]jz&F]jz6#-Fjft6$w,F]gtF,6$FfrFgrF,F\dxF,F,6$FeaxF`][l6#FWFcfx7#-Fido6#;F
W-FQ6$FWF]jz>F_\[l-F\^n6$-Fj_w6#&F[jz6$-Fjft6$w,F]gtF,6$FfrFgrF,F\dxF,F,6$FdaxF
efz6#FW6$7'FZFenF]\nFgoFhnFbar7#-Fido6#;FW-FQ6$FbhtF[jzFauF^]l>Fc\[l-FE6$w,Fc]l
F,6$FfrFgrF,-FQ6#-F`]l6$w,FgivF,6$FfrFgrF,0&Fh_l6$F4F_sF[xF,F,6&FcaxFh_lFd]lF46
#FW6$7'FZFenF\tF\flFhnFf_l<#-Fido6#;FW-FQ6$FbhtFh_lF,F,6$FcaxF_\[l6#FW6$7'FZFen
FfuFgioFhnF]^m<#-FQ6#F`][l>8K-Fg[m6$-Fi[l6$F]f[lFgv-Fi[l6$&F]jz6#7#-FQ6#Fc\[lFg
v>Fgfz-Fiiq6$-Fi[l6$-Fbel6$F^a\l-Fi[l6$FhewFgvFbpFf_m64Fh\lFc[lF`hlFailFgfzFhew
F\\wFcbsFc`lFefzF`][lFg_\lFgizFde\lFijzFjjzFi[[lFi`\lF,F,F,6#F^_m6GFiel7'FZFenF
^oFdcrFjoFhboFh^s7'FZFenF^oFhuFjo7'FZFenF^oFfbmFjoFj[oFcduFh^sFdduFa\nF[bmFiboF
jamFa\nF[]pFe`xF[bm7'FZFenF^oFbhsFjoF^[uFj`xFa_sFa_s7'FZFenF^o"#'*Fjo7'FZFenF^o
FcblFjo7'FZFenF^oF\hpF\pFf]w7'FZFenF^oFc_mF\p7'FZFenF^oFg\nF`o7'FZFenFjuFgioFdo
F`\n7'FZFenF^oF^vFjoF[_sFbduFj`xFc`x7'FZFenF^oFj[nF\oF,,
I&getB0w,6$'%"PGFgvFehp6'F\glF^gl%$VrsG%$vrsGFez6"F,C$>F/Fd[l?(FCF[xFW,&F/FWFen
FWFjqC$>F^]l-&%)combinatG6#%'chooseG6$Fcq,&F/FWFCFen?&Fh\lF^]lFjqC$>Fc[l-F`]l6$
w,FcrF,6$FfrFgrF,-Fi[l6$-FE6$w,6#F\[lF,6$FfrFgrF,-F_jm6$F`_lF_sF,F,6&FdrF4F]h\l
F_s6#FW6$7'FZFenFioFibsFhn7'FZFenFioFjuFhnFh_l%$andGF,F,6&F`h\lFh\lF]h\lF46#FW6
$7'FZFenFisF][rFhnF[tF4@%0FadqF[xO-Fi[l6$-FE6$w,F[j\lF,6$FfrFgrF,*&F4FW&Fh_lF]t
FWF,F,6$FezFc[l6#FW6$7'FZFenFdoF]\oFhn7'FZFenFdoFb\oFhn7$F[fpFWFgv>Fc[lF]hlF,F,
F,6#F^_m6+7'FZFenF]blFgnFhn7'FZFenFjnFisF\oF\blF_blFdhs7'FZFenF^amF_oFjo7'FZFen
F^amFedzF`o7'FZFenF\oF_flF^v7'FZFen"#!*Fd]yFjoF,,
I*iniColpivw,6&Ffbw'Fge[lFgvFghpFfz6*%#VlGF]h\lFez%#aPGF^fr%#RPGF[[lFfp6"F,C/>F
f[l-Ffgm6#F\hu>F/-Fi[l6$-Fbel6$Fg_yFcqFbp>FC-Fi[l6$-F`]l6$w,FcrF,6$FfrFgrF,-F_j
m6$F`_lFj]lF,F,6&FhhpFdsFi\]lF/6#FWFgavF/Fgv>F^]l-Fci[l6$FCFes>Fh\l-FE6$w,FcrF,
6$FfrFgrF,F`_lF,F,6$FhhpFds6#FWFegrFC>Fc[l-Fiiq6$-Fi[l6$F`[mFbpFf[l>FC7$-FQ6#-F
iiq6$-Fi[l6$-FbelFbgmFbpFf[l-FQ6#-Fiiq6$-Fi[l6$F^]lFbpFf[l-Fb\l6$QCList~of~perm
issible~monomials:|+%a|+F,FC-Fb\l6$QENumber~of~permissible~monomials:~%d|+F,F^a
l>Fh\l-FE6$w,FcrF,6$FfrFgrF,-Fa_r6$F`_l7$-FQF]bs-FQ6#Ff\mF,F,6(FhhpFdsF]h\lFCF^
frFc[l6#FW6$7'FZFenFfuFd\oFhnF]^mFC>Fb`l7$Fc^mF_`m>Fc`l-Fiiq6$-Fi[l6$-Fg[m6$-Fb
el6$-Fi[l6$F/Fgv-Fi[l6$Fb`lFgvFcqFbpFf[l6'-Fgw6$-FQFabpFhguFCFh\lFadq-FgqFabpF,
F,F,6#Fcu60Fiy7'FZFenF]vF`emFjoFgiqFgg\lFdduFa\nF[bmF[_s7'FZFenF^oFj^nF\pF`\oFf
htFdduF\g\l7'FZFenF^oFjuF\oF,,
I,alter_commaw,6#'FbclFbpF,6$FfrFgrF,-F16%F]an-FQ6#-&Fb_r6#%+InterleaveG6$F47#-
Fido6$Q",F,,&FfqFWFenFWFggnF,F,F,6#FW6$7'FZFenFfnFj[nFhn7'FZFenFfnFisFhnF,,
I-write_solverw,6/'%$dirGF'Fcip%&vars0GFhhp%#iMG%#eMGF\clF]frFahpFhbwFee[lF`_wF
`ip6)%&vars1G%#vvGFgfm%$nv0GFivF^gl%#fbG6"F,C>>Fh\lFehl>Fc[l-Fgq6#F[]l>Fc`lQ%~~
~~F,>F/-Fi[l6$-Fbel6$Fe`v<#FesFbp>FC7#-F`dl6$-Fa_r6$*&&F/Fb`mFW&F[]l6#FenFWF[]l
/Fb`l;FW,&Fh\lFWFenFW>F^]l-Fbim6$-F16+F4Q"/F,-Fix6%90Q%std_F,Q&nstd_F,,&&Fc\qF]
tFW9/FenQ"xF,,&&Fc\qFi[pFWFig]lFenQ"_F,F&F5Fh]n-Ffjm6$F^]l-F16'QH%%~Input:~coef
ficient~matrix~C~of~size~F,F`[qFjg]l&FcqFi[pQ#|+|+F,-Ffjm6$F^]l-F16,Q*function~
F,-F]c]lF`wQ$~=~F,Fbg]lFgg]lFjg]lF[h]lF]h]lF&Q&(C)|+|+F,-Ffjm6$F^]l-F16&Fc`lQ(i
_dx~=~F,-F]c]l6#-FE6$w,F]gtF,6$FfrFgrF,FiatF,F,F,6#FW6$7'FZFenFdoFcamFhn7'FZFen
FdoF^vFhnFexQ#;|+F,-Ffjm6$F^]l-F16&Fc`lQ(j_dx~=~F,-F]c]l6#-FE6$w,F]gtF,6$FfrFgr
F,FjatF,F,F,6#FWFii]lFexF\j]l-Ffjm6$F^]l-F16&Fc`lQ(C_dx~=~F,-F]c]lF`dwF\j]l-Ffj
m6$F^]l-F16(Fc`lQ>M~=~sparse(i_dx,j_dx,C(C_dx),F,Fhg]lF^d]lF\h]lQ$);|+F,@$0Fig]
lF[x-Ffjm6$F^]l-F165Q"|+F,Fc`lQ'M~=~M(F,,&Fig]lFWFWFWQ&:end,F,F]\^lQ*:end)-(M(F
,F]\^lQ(:end,1:F,Fig]lQ')/M(1:F,Fig]lQ$,1:F,Fig]lQ())*M(1:F,Fig]lF^d]lF]\^lQF:e
nd);~%%~Schur~complement~reduction|+F,-Ffjm6$F^]l-F16'F[\^lFc`lQ5[L,|ir,Pi]~=~l
u(M(:,1:F,Fd\qQ%));|+F,-Ffjm6$F^]l-F16$Fc`lQ+Pi~=~Pi';|+F,-Ffjm6$F^]l-F16(Fc`lQ
0M~=~[Pi*L~Pi(:,F,,&Fd\qFWFWFWQ,:end)]\M(:,F,Fe]^lQ(:end);|+F,-Ffjm6$F^]l-F16&F
c`lQ+M~=~M(end-F,,&FjipFWFenFWQ*:end,:);|+F,-Ffjm6$F^]l-F16'F[\^lFc`lQ+T~=~zero
s(F,Fc[lFd[^l-Ffjm6$F^]l-F16*Fc`lQ%T(1:F,FjipQ.,:)~=~-M(:,1:F,FjipQ')\M(:,F,,&F
jipFWFWFWFg]^l@&/,&Fc[lFWFjipFenFW-Ffjm6$F^]l-F16&Fc`lQ#T(F,*&Fc[lFW-Fa_r6$&Fb
\qFhf]lF[]lFWQ()~=~1;|+F,2FWF^_^l-Ffjm6$F^]l-F16&Fc`lFc_^l-F]c]l6#7#-F`dl6$,&*&
Fc[lFW,&-Fa_r6$&Fb\q6#,(Fb`lFWFc[lFenFenFWF[]lFWFenFWFWFWFb`lFW/Fb`l;F[_^lFc[lF
h_^l-Ffjm6$F^]l-F16%F[\^lFc`lQ1[V,D]~=~eig(T);|+F,@%/F^alFW-Ffjm6$F^]l-F16(Fc`l
Q*sol~=~[V(F,&FCF]tQ(,:)./V(F,Fc[lQ3,:);~diag(D).'];|+|+F,-Ffjm6$F^]l-F16*Fc`lF
ha^l-F]c]lFUQ/,:)./repmat(V(F,Fc[lQ%,:),F,F[g]lQ3,1);~diag(D).'];|+|+F,-Ffjm6$F
^]l-F16$Fc`lQXI~=~find(not(isnan(sol(1,:)))~&~not(isinf(sol(1,:))));|+F,-Ffjm6$
F^]l-F16$Fc`lQdo%%I~=~I(not(imag(sol(1,:))));~%%~uncomment~this~line~for~real~r
oots~only|+F,?(Fb`lFWFWF[g]lFjq-Ffjm6$F^]l-F16'Fc`lFff]lQ(~=~sol(F,Fb`lQ&,I);|+
F,-Ffjm6$F^]l-F16'Fc`lFesFcc^lFh\lQ',I);|+|+F,-Ffjm6$F^]lQ$endF,-Fc[nFjcmF,F,F,
6#Ffu6EFielF^]w7'FZFenFcblFibsFjoF]]qFa_s7'FZFenF^oFfboFjo7'FZFenF^oFa[rFjo7'FZ
FenF^oFc\]lF\p7'FZFenF^o"$J"F\p7'FZFenF^oF][rF\pFfd^l7'FZFenF^oFibsF\p7'FZFenF^
oF_flF\pFgfp7'FZFenFbal"$#=F\p7'FZFenF^oFecqF\p7'FZFenF^oFboF\p7'FZFenF^oFdcrF
\p7'FZFenF^oFcamF\pFcem7'FZFenF^oFddrF\pFgfp7'FZFenFbalFf\pF\p7'FZFenFbalFhhtF
\p7'FZFenF^oFbamF\pFgfp7'FZFenFbalFj[nF\p7'FZFenFbalF[enF\pFhd^l7'FZFenF^oF`vF
\pF\bl7'FZFenFbalFcbvF\pFc\o7'FZFenF^oF\pF\pFh\nF,,
I4write_solver_colpivw,60Fgd]lFcipFid]lFhhpFjd]lF[e]lF]h\lFj\]lFahpFhbwFee[lFiv
F`_wF`ip6)F]e]lF^e]lFgfmF_e]l%#nPGF^glF`e]l6"F,CB>Fh\lFehl>Fc[lFee]l>Fc`lFhe]l>
F/Fje]l>FC7#-F`dl6$-Fa_r6$Fef]l&F[]l6#;,$Fig]lFenFenFif]l>F^]l-Fbim6$-F16+F4Fag
]l-Fix6%91Feg]lFfg]l,&Fhg]lFWFdg]lFenFjg]l,&F\h]lFWFdg]lFenQ)_colpiv_F,F&F5Fh]n
F^h]l-Ffjm6$F^]l-F16,Fih]lFjh]lF[i]lFbg^lFeg^lFjg]lFfg^lFgg^lF&F\i]l-Ffjm6$F^]l
-F16&Fc`lFai]l-F]c]l6#-FE6$w,F]gtF,6$FfrFgrF,FiatF,F,F,6#FWFii]lFexF\j]l-Ffjm6$
F^]l-F16&Fc`lFaj]l-F]c]l6#-FE6$w,F]gtF,6$FfrFgrF,FjatF,F,F,6#FWFii]lFexF\j]lFij
]lF_[^l@$0Fdg]lF[x-Ffjm6$F^]l-F165F[\^lFc`lF\\^l,&Fdg]lFWFWFWF^\^lFhi^lF_\^lFhi
^lF`\^lFdg]lFa\^lFdg]lFb\^lFdg]lFc\^lFdg]lF^d]lFhi^lFd\^l@%0Fd\qF[xC&Fe\^lF[]^l
F`]^l-Ffjm6$F^]l-F16&Fc`lQ,M~=~full(M(F,Fe]^lQ+:end,:));|+F,-Ffjm6$F^]l-F16$Fc`
lQ.M~=~full(M);|+F,@$0FjipF[xC%-Ffjm6$F^]l-F16'F[\^lFc`lQ6[L,UR,Pi]~=~lu(M(:,1:
F,FjipFj\^lF[]^l-Ffjm6$F^]l-F16(Fc`lFd]^lF[_^lFf]^lF[_^lFg]^l-Ffjm6$F^]l-F16&Fc
`lQ*MP~=~M(1:F,FjipQ&,:);|+F,-Ffjm6$F^]l-F16&Fc`lQ(NP~=~M(F,F[_^lQ+:end,:);|+|+
F,-Ffjm6$F^]l-F16&Fc`lQ:[Q,U,Pi]~=~qr(NP(:,1:end-F,Fj`lFj\^l-Ffjm6$F^]l-F16(Fc`
lQ4A~=~UR\[MP(:,1:end-F,Fj`lQ/)*Pi~MP(:,end-F,Fh\lQ):end)];|+F,-Ffjm6$F^]l-F16*
Fc`lQ+B~=~U(:,1:F,,*Fhg]lFWFdg]lFenFd\qFenFjipFenQ()\[U(:,F,,,Fhg]lFWFdg]lFenFd
\qFenFjipFenFWFWQ3:end)~Q'*NP(:,end-F,Fh\lFj\_l-Ffjm6$F^]l-F16(Fc`lQ/M~=~[-A(:,
end-F,,&Fig]lFWFenFWQ1:end)+A(:,1:end-F,Fig]lQ,)*B;~-B];|+|+F,-Ffjm6$F^]l-F16&F
c`lQ&xP~=~F,-F]c]l6#Fb\qF\j]l-Ffjm6$F^]l-F16*Fc`lQ*P1~=~[(1:F,,(Fc[lFWFh\lFenFe
nFWQ&)*Pi~F,,&Fc[lFWFh\lFenQ":F,Fc[lQ$];|+F,-Ffjm6$F^]l-F16-Fc`lQ-T~=~getT(M,[F
,Fh^oF[__l,&Fc[lFWFjipFWQ+~P1(1:end-F,Fig]lQ+)],P1(end-F,Fi]_lQ&:end)F,Q',xP);|
+F,F]a^l@%Fca^l-Ffjm6$F^]l-F16(Fc`lFha^lFia^lFja^lFig]lF[b^l-Ffjm6$F^]l-F16*Fc`
lFha^lF`b^lFab^lFig]lFbb^lF[g]lFcb^lFdb^lFib^l?(Fb`lFWFWF[g]lFjqF_c^lFec^lFjc^l
F]d^lF,F,F,6#Ffn6OF]bwF^]w7'FZFenFcblFcamFjo7'FZFenFf`[lFghsFjoFa_s7'FZFenF^oFg
\nFjoF_g\lFcd^l7'FZFenF^o"$Q"F\pFfd^lFfd^lFgd^lFhd^lFgfpFid^lFgfp7'FZFenFbalFgb
oF\p7'FZFenFbalF`blF\p7'FZFenFbalF\]pF\p7'FZFenFbalFf`[lF\pF[csFgfp7'FZFenFbalF
h[nF\pFi`_lFj`_lFbe^lFcem7'FZFenF^oF[\uF\p7'FZFenF^oFi]wF\p7'FZFenF^o"$?"F\pF^a
_lFcemFcg\l7'FZFenF^oFabwF\pFbe^lFgfpFce^lFde^lFhd^lFee^lF\blFfe^lFc\oFge^lFh\n
F,,
I4write_inidata_coefsw,6$F%'%)root_dirGF'6.%*proc_nameG%#_CG%&_nameG%&_sizeG%#C
sG%#ClGFhd]lFgfmF^glFj_t%$idxGF`e]l6"F,C6>Ff_mFhe]lAF0>F/-FI6#-F16$%#C_GF4>6%FC
F^]lFh\lF_il>Fc`l-F16%FcqFag]lF4@$4-F9Fabp-&F:6#%.MakeDirectoryGFabp>Ff[l-Fbim6
$-F16&Fc`lQ*/inidata_F,F4F5Fh]n-Ffjm6$Ff[l-F16%Q9function~data~=~inidata_F,F4Q$
()|+F,-Ffjm6$Ff[l-F16&Ff_mQ0data~=~cell([1,F,F[dpQ%]);|+F,?(FijlFWFWF[dpFjq-Ffj
m6$Ff[l-F16(Ff_mQ&data|frF,FijlQ+|hr~=~randn(F,-Fc`n6$-F]c]l6#&Fh\lFifqFijnFd[^
l-Ffjm6$Ff[lF\d^l-Fc[nF[[m>Ff[l-Fbim6$-F16&Fc`lQ(/coefs_F,F4F5Fh]n-Ffjm6$Ff[l-F
16%Q4function~C~=~coefs_F,F4Q)(data)|+|+F,?(FijlFWFWF_]rFjq-Ffjm6$Ff[l-F16'Ff_m
FgctQ)~=~data|frF,FijlQ$|hr;|+F,-Ffjm6$Ff[lF[\^l?(FijlFWFW,$F^al#FWF^_mFjq@$/&F
C6#,&FijlF^_mFenFW%#cfGC%-Ffjm6$Ff[l-F16(Ff_mQ+C~=~zeros(F,-FQ6$Fbht&FCFhf]lF^d
]l-FQ6$Fb]vF\h_lQ%);|+|+F,>Fjgn6$-Fbel6$-Fi[l6$&FC6#,$FijlF^_mFgv<#F[x-Fi[l6$Ff
h_lFbp?&F`hlFc[lFjqC$>Fj[m7#-F`iv6$F`hlFb`l-Ffjm6$Ff[l-F16(Ff_mQ#C(F,-Fix6%/Ffd
pFW&Fj[mF]t-F]c]lFgdpQ%)~=~F,-Fi[l6$F`hlF'F\j]l-Ffjm6$Ff[l-F16%F[\^lFf_mQPC~=~C
./repmat(sqrt(sum(C.^2,2)),1,size(C,2));|+|+F,Fce_lFee_lF,F,F,6#F^_m6@F]bw7'FZF
enFcoFf\pFjo7'FZFenF^oF\flFgoF`flFfiqFfiqF]o7'FZFenFfjlFcoF\pFe]w7'FZFenF^oFcbv
F\pFhczF\bl7'FZFenFbal"$,"F\pFge^lFh\nF`]wF\\oF\bl7'FZFenFbalFfblF\p7'FZFenF^oF
agoF\pF\blFb\n7'FZFenF^amFd]yF\pF_\]l7'FZFenF^amF]`lF]bl7'FZFenFjelFdoFjo7'FZFe
nFjelF`a_lF\pF]e^lFge^lFh\nF,,
I/write_test_numw,6+F%FhvF`hpFfz'Fid]lFbp'Fde[lFczFccwFfa_l%#cpG6+Fhd]lFgfmFb]r
F`e]l%$fb2GF^e]l%$vv0G%&xvarsG%$xvvG6"F,CI>F/-F16%Fb\qFag]lF4>Fh\lFhe]l>Fc[l-F1
6$Fh\lFh\l>Fb`l-FE6$w,F[j\lF,6$FfrFgrF,-F16$F4F4F,F,F,6#FW6$7'FZFen"#$*"$2"Fhn7
'FZFenF`]`lFag\lFhnFes>Fc`l-FE6$w,F[j\lF,6$FfrFgrF,F[]`lF,F,F,6#FW6$7'FZFenF\dz
"$U"Fhn7'FZFenF\dzFed^lFhnFex>Ff[l-Fi[l6$-Fbel6$FbguFcbuFbp>Fijl-FE6$w,F[j\lF,6
$FfrFgrF,F[]`lF,F,F,6#FW6$7'FZFen"$M#"$[#Fhn7'FZFenFj^`l"$P#FhnFf[l@$F7-Fbc_lF=
>FC-Fbim6$-F16&F/Q+/test_num_F,F4F5Fh]n-Ffjm6$FCQ+rng(23);|+|+F,-Ffjm6$FCQ-N~=~
10000;|+|+F,-Ffjm6$FC-F16'Q%Err_F,F4Q+~=~[];|+Tm_F,F4Q)~=~[];|+|+F,-Ffjm6$FCQ.f
or~i~=~1:N|+|+F,-Ffjm6$FC-F16&Fh\lQ0data~=~inidata_F,F4QN();~%%~generate~initia
l~data~of~the~problem|+|+F,-Ffjm6$FC-F16$Fh\lQ%try|+F,-Ffjm6$FC-F16$Fc[lQ&tic;|
+F,-Ffjm6$FC-F16&Fc[lQ+C~=~coefs_F,F4QV(data);~%%~compute~coefficients~of~polyn
omial~system|+F,-Ffjm6$FC-F16,Fc[l-F]c]lFabpF[i]l-Fix6%-F]gz6#/F[]lF`ipFeg]lFfg
]l&FdsF]tFjg]l&FdsFi[p-Fix6%Fc\qFgg^lF]h]lF4QA(C);~%%~solve~polynomial~system|+
F,@$0FjevF[x-Ffjm6$FC-F16+Fc[l-Fix6%/FjevFW&FijlF]t-F]c]lFifqQ6~=~arrayfun(@(j)
~get_F,-F16#-FQF[[mQ$(C,F,-Fc`n6$-F]c]l6#7#-F`dl6$-F16$&Fc`lFjcmQ$(j)F,/F^]l;FW
Fgb]lFijnQ-),~1:length(F,FabzFj\^l-Ffjm6$FC-F16$Fc[lQ+tm~=~toc;|+F,-Ffjm6$FC-F1
6&Fc[lQ,if~isempty(F,Fh_mQ2);~continue;~end|+F,-Ffjm6$FC-F16$Fh\lQ*catch~ME|+F,
-Ffjm6$FC-F16$Fc[lQ+continue;|+F,-Ffjm6$FC-F16$Fh\lQ&end|+|+F,-Ffjm6$FC-F16$Fh
\lQ)M~=~[];|+F,-Ffjm6$FC-F16&Fh\lQ0for~j=1:length(F,Fh_mQ#)|+F,?(F^]lFWFWFahlFj
q-Ffjm6$FC-F16'Fc[l&FesFjcmF[i]l&Fb`lFjcmQ&(j);|+F,-Ffjm6$FC-F16&Fc[lQ%m~=~F,-F
]c]l6#-Fi[l6$Ff`lFbpF\j]l-Ffjm6$FC-F16$Fc[lQ6m~=~m/norm(m,'fro');|+F,-Ffjm6$FC-
F16$Fc[lQ=M~=~[M;~norm(C*m.','fro')];|+F,-Ffjm6$FC-F16$Fh\lQ%end|+F,-Ffjm6$FC-F
16$Fh\lQ.M~=~sort(M);|+F,-Ffjm6$FC-F16&Fh\lQ4err~=~norm(M(1:min(F,FcqQ7,length(
M))),'fro');|+|+F,-Ffjm6$FC-F16.Fh\lF```lF4Q)~=~[Err_F,F4Q(~err];|+F,Fh\lQ$Tm_F
,F4Q(~=~[Tm_F,F4Q(~tm];|+|+F,-Ffjm6$FCFbf`l-Ffjm6$FCQIfolder~=~fileparts(which(
'add_all.m'));|+F,-Ffjm6$FC-F16'QCsave(strcat(folder,'\_results\Err_F,F4Q-.mat'
),'Err_F,F4Q&');|+|+F,-Ffjm6$FC-F16)Q3fprintf('Problem:~F,F4Qin.~Ave.~runtime:~
%%0.1f~ms.~Med.~error:~%%0.2e\n',10^3*mean(Tm_F,F4Q.),median(Err_F,F4Fj\^lFf[qF
,F,F,6#Fjn6MF^`xFf[n7'FZFenFbamF]\oFjo7'FZFenFfboF[_nFjo7'FZFenFefpFgjoFjo7'FZF
enFb]w"$]"Fjo7'FZFen"$`""$?#Fjo7'FZFen"$B#"$c#FjoF]oFhj_lFa_sFbbw7'FZFenF^oF\oF
\pF]a_l7'FZFenF^oFe_lF\p7'FZFenF^oFb`xF\pFb\al7'FZFenF^oFbenF\p7'FZFenF^oF[[`lF
\p7'FZFenF^o"$y"F\pFgfp7'FZFenFbal"$F#F\pFeiqF]a_lFf^wFeiqFe\alFdg\lFcemF\blFfe
^l7'FZFenF^oFgboF\pFbe^lF^e^lFb\al7'FZFenF^oF\flF\p7'FZFenF^oFf\pF\p7'FZFenF^o"
$8"F\p7'FZFenF^oFisF\pF`\o7'FZFenF^oFd]yF\p7'FZFenF^o"$^"F\pFh\nF,,
I0write_histo_numw,Fda_l6%Fhd]lFgfmF`e]l6"F,C6>F/F\c_l>F^]lFhe]l@$F7F__`l>FC-Fb
im6$-F16&F/Q,/histo_num_F,F4F5Fh]nFdj`l-Ffjm6$FC-F16%QDload(strcat(folder,~'\_r
esults\Err_F,F4Q+.mat'));|+|+F,-Ffjm6$FCQ,bwd~=~0.3;|+F,-Ffjm6$FCQ-nbins~=~60;|
+F,-Ffjm6$FCQ9clr~=~[70~100~160]/255;|+F,-Ffjm6$FC-F16%Q1err~=~log10(Err_F,F4Fd
[^l-Ffjm6$FCQLhr1~=~histogram(err,nbins,'BinWidth',bwd);|+F,-Ffjm6$FCQ6hr1.Face
Color~=~clr;|+F,-Ffjm6$FCQ7hr1.EdgeColor~=~clr;|+|+F,-Ffjm6$FCQ8axis([-17~1~0~1
150]);|+|+F,-Ffjm6$FCQVset(gca,'FontSize',54,'FontName','Times~New~Roman');|+F,
-Ffjm6$FCQFset(gcf,'PaperPositionMode','auto');|+F,-Ffjm6$FCQJset(gcf,'PaperOri
entation','landscape');|+F,-Ffjm6$FCQGset(gcf,'PaperPosition',[1~1~28~19]);|+F,
-Ffjm6$FC-F16%QPprint(gcf,'-dpdf',strcat(folder,'\_results\fig_F,F4Q).pdf'));F,
Ff[qF,F,F,6#F^_m68F]gxFf[n7'FZFenFgoFgalFjoF]oFhj_lFj`xF`\oF]e^lFbbw7'FZFenF^oF
]\nF\pF]co7'FZFenF^oF^vF\pF\\o7'FZFenF^oFioF\pF\_nF]coFfd^lFcemFeblF^e^lF^a_lFh
\nF,,
I0SolverGeneratorw,6)F%>FbezF`ip>%'colpivGFW>%2create_coefs_fileGFW>%2create_hi
sto_fileGFW>%1create_test_fileGFW>Fea_lQ(solversF,6FF\qFhhpF`isFde[lF[[lF`frF\c
lF]frF\ipFdaxFeaxFahpFee[lFge[lF`_wFicwFjcwFhe[lF[`qFh^rF]h\lFj\]l%$nR1G%$nE1GF
`clF\f^lFhbwFg[`lFid]l%#iCG%#eCGFap%#MtGFjd]lF[e]lFhd]l6"F,C9>64F/FCF^]lFh\lFc[
lFb`lFc`lFf[lFijlF`hlFj[mFf_mFailFdhlFcbsFdbsF\\wFd[v-F_e[l6$F4-F]gz6#/FcqF`ip>
Fecv-Fgw6$Fc^mFhgu>6'F\]xFhewFdewFhbyF`fy-Fd\]l6&FecvFdhlFCF/>6%FjgyFgizF[jz6%F
gb]l-Fgq6#FhewFadq>F]jz-Fix6%51FgizFjgy/FdsF[xFewFjq>Fhjz-Fix6%F]jz-F`]l6$w,F[j
\lF,6$FfrFgrF,-F_jm6$*&F4FW&Fh_lFhf]lFW&Fh_l6#;,$Fj]lFenFenF,F,6&F]h\lFhewF`clF
jgy6#FW6$7'FZFenFg_lFfblFhn7'FZFenFg_lF\oFhnF/-F`]l6$w,F[j\lF,6$FfrFgrF,-F_jm6$
FbealFh_lF,F,6$F\clFc`l6#FW6$7'FZFenFjalFb`xFhn7'FZFenFjalF\hpFhnF/-Fb\l6$QRVar
iables~that~can~not~be~evaluated~at~roots:~%a|+F,7#-FQ6#-Fbel6$F_b]lF\a\l>Fijz7
#-%(indicesG6$-Fi[l6$F^]lF^aq%+indexorderG>Fjjz-FE6$w,Fc]lF,6$FfrFgrF,-Fi[l6$,&
FiatFW*&,&FjatFWFenFWFWFjd\lFWFWF'F,F,6$F`isF^]l6#FW6$7'FZFenFfuFgalFhnF]^mFijz
>F^]l-Fgao6$-FQ6$FWF^]l<#-FQ6#-Fiho6%w,Ff^mF,6$FfrFgrF,/-FQFhqFcqF,F,F,6#F^_m6$
7'FZFenFbenFdoFhnFajrFijzFjjz>Fi[[l&-Ffdu6&Fijl-Fi[l6$-Fcgq6$F^]lFh\lFbpF/Fb`lF
i[p@$0FcbsF[x>Fi[[l&Fi[[l6$FdbsF\\w>Fi[[l&Fi[[l6$-Fjft6$w,F]gtF,6$FfrFgrF,-F_t6
#-Fhdl6$F4-FE6$w,Fc]lF,6$FfrFgrF,,&F4FWFh_lFWF,F,6$F`_wFj]l6#FW6$7'FZFenFe_lFfj
lFhnFdc[lFh_lF,F,6&FdaxF`hlF`_wFcbs6#FW6$7'FZFenF_goFgoFhnF`go7#-Fido6#;FW-FQ6$
FbhtFi[[l-Fjft6$w,F]gtF,6$FfrFgrF,-F_t6#-Fhdl6$F4-FE6$w,Fc]lF,6$FfrFgrF,Fc[blF,
F,Fd[bl6#FW6$7'FZFenF`]`l"#**Fhn7'FZFenF`]`lFi\qFhnFh_lF,F,6&FeaxFj[mF`_wFcbs6#
FW6$7'FZFenFf\pFa]`lFhn7'FZFenFf\pF[_nFhn7#-Fido6#;FW-FQ6$Fb]vFi[[l@$F]jz>Fi[[l
-Fe^r6%Fi[[l-Fi[l6$-Fgw6$Ff[\lFecvFcz-Fi[l6$-Fgw6$Ff[\lF\]xFcz>F^\[l-Fi[l6$Fi[[
lF^aq>6$F_\[lFc\[l6$7#-Fcgal6$F^\[lFggal-FE6$FQ7#-%(entriesGFb_bl@$4-F9Ffe]l-Fb
c_lFfe]l>Fefz-F16%F[]lFag]lF4@$4-F96#Fefz-Fbc_lFb`bl@%F]jz-Fhe^l60Fefz7#FihalFh
jzFCF_\[lFc\[lFhewFdew7#-FQ6$FWFi[[lF`fyFhbyFjgyFcbsFdcal-Fdd]l6/FefzFg`blFhjzF
CF_\[lFc\[lFc`lFf[lFh`blF[jzFailFcbsFdcal@$/FesFW-Fba_l6$F4F[]l@$/Ff`lFW-Fb[`l6
+F4FjgyFf_mF/FhjzFh\lFcqF[]lF]jz@$/FexFW-Fd]alF`ablF,F,F,6#FW6CF]gx7'FZFenF^o"$
D"FjoFdduFcdu7'FZFenF^oF`blFjoFgiq7'FZFenF^oFedzFjo7'FZFenF^oFgjoF\pFi`xFad^lFd
`xFb_t7'FZFenF^oFcblF`o7'FZFenF]`lFc_mFjo7'FZFenF^o"$I"Fjo7'FZFenF^oFgamF`o7'FZ
FenFfnFag\lFjoF]g\lFe`_l7'FZFenF^oF\]pF`o7'FZFenFjoFjalF\pFfiqF]oFhj_lFgfp7'FZF
enFbalF\coF\p7'FZFenFbalF[[rF\p7'FZFenF^oFghsF`o7'FZFenF\oFecqF\p7'FZFenF^oFa[r
F`o7'FZFenF]\nF]axF\p7'FZFenF^oFh[nF`o7'FZFenF\oF]\oF\pF,
