M7R0
I,readProblemt+6#'%%probG%'stringG6$%#fnG%"FG6"6"C'>8$-%$catG6%Q/../problems/F_
F,9$Q#.mF,@$4-&%*FileToolsG6#%'ExistsG6#F/Y-F16%%&File~GF/%+~not~foundGAF/>8%-%
$mapG6$%'expandG-%%evalG6#-F16$%#F_GF46$FE7#-%#opG6#-%'indetsG6#FEF,F,F,6#"""F,,
I+isLinIndept+6&'%"MG%%listG'%"GGFin'%%tordG%3ShortMonomialOrderG'%#ppG%'posint
G6$%%varsG%"SG6"F,C&>F/-FV6#9%@$/-%%nopsG6#F4FYO%%trueG>FE&-%,poly2matrixG6%-FG
6$f*6#%"mGF,6$%)operatorG%&arrowGF,-&%)GroebnerG6#%+NormalFormG6&F4T$T&/%/chara
cteristicGT(F,F,6(F[oFjoF]o9&F`o9'F4F]pF/6#FY-%#isG6#0-&&%.LinearAlgebraG6#%(Mo
dularG6#%%RankG6$F\rFE-Fcr6$F\r&FE6$;FY!"#;F,F,F,F,F,6#""%F,,
I*testBasist+6''Fhn%$setG'%$degGFaoFjnF\o'F`o%*nonnegintGFbo6"F,C&>F/-FV6#F[r@$
2F]pFjoO6$%&falseG-%$<,>G6#-Fht6#""!>FE&-Fep6%-FG6$f*FjpF,6$F]qF^qF,F_qF,F,6(F[
oF[rF]oF\rF`o9(F4F]pF/F]r6$-%#ifG6%0FfuF\u-F_r6#/-Fcr6$FfuFEFjo-F_r6#/-&FerFhrF
WFjoFEF,F,F,6#""&F,,
I*iniMonSett+6)'F*<%%'VectorGFinFhs'%#B0GFin'FcoFinFjnF\oF_o>'%$domGF\tF\u6*%"E
GFhn%#vrG%"dGFjs%%flagGFdo%&d_minG6"F,C*>8(-F^pFio>8+F\u>F/-%(convertG6$-FG6$FS
-&Faq6#%(SupportGF_pFhs-%&printG6#-F16%%<Polynomial~system~contains~G-F^pF=%+~m
onomialsG>FEF/?(8'F\uFYF,1,&FeyFYF`x!""9*C&>8&-%'selectG6$f*6#%"xGF,6$F]qF^qF,1
-%'degreeG6$F4FeqT%F,F,6&FcoF[rFgwFeyFE>FE-FG6$f*6#%"tGF,6$F]qF^qF,-FS6#-FG6$f*
6#%"kGF,6$F]qF^qF,*&FeqFYF4FYF,F,6$F_[lF4T#F,F,6$FfwF\zFE>6$8)8*-Fds6'FEF]xF\rF
fu9)@$4F_\l>F`x,&FeyFYFYFY-F\y6#-F16%%6Initial~set~contains~G-F^pFWFbyO6$F/FEF,
F,F,6#""(F,,
I-neighborMonst+6%'%"BGFhs'%#MBGFhsF`w6#%#nBG6"F,C&@$/F]pF\uOFjo>F/-F^z6%%%type
G-FG6$FS<#-%$seqG6$-Fh^l6$<$*&%"bGFY%"vGFhy*&F^_lFYF__lFY-%#inG6$F__lF[r-Fb_l6$
F^_lF4%)monomialG>F/-%*intersectG6$-%&minusG6$F/F4Fjo-Fiu6%/FayF\uFjoF/F,F,F,6#
""$F,,
I)genBasist+6)'FewFhsFgsF^wF`wFjnF\oF_o60%$rndGFf]l%#EBGFh]lFj]l%$nB1G%#bvGFg[l
%"aG%#nvG%#wtGF[q%"iGFjs6"F,C->F/,$-I%randG6$%*protectedG%(_syslibG6#;F\u"%+5#F
YF[bl>FE<">FeyFjo>8--F^p6#F\r>81-F^pFat-%*randomizeGF,>F`\l7#-Fh^l6$-%&roundG6#
-F/F,/80;FYFabl>F`x-&%$maxG6#%&indexG6#-FG6$f*FazF,6$F]qF^qF,,&F4FY*&-F[\lF,FY$
"$+"F\uFhyFYF,F,6$Fh`lF/F`\l>8,&F\r6#F`x?(F,FYFYF,2F]]lFeblC*>Fey-F\`l6$FeyFE>F
]x-Fb]l6%FEFeyF\r>F\z-%&unionG6$F4FE>8.f*FazF,6$F]qF^qF,,*-Fiu6%-Fb_lFgzFYF\uFY
-Fiu6%-Fb_l6$*&FhzFYF4FYT'FYF\uFY-%$addG6$*&&T)6#T+FY-Ffz6$F4&T.FjflFY/F[gl;FYT
/FY*&-T1F,FYFbdlFhyFYF,F,62FewF4F\alFfdlFi`lF\zF[alF`\lF_alFbclFcoF\rF]alFablFh
`lF/>F_\l-%%sortG6$7#-FS6#F]xf*6$Fbz%"yGF,6$F]qF^qF,1-F[\lFio-F[\lF_pF,F,6$F^al
Fgel>6$8/Fbcl6$&F_\lF]rFY?(F,FYFYF,34-FZ6&7$-FSFWFhhlFfuFc\lFiy2Fbcl-F^p6#F_\lC
$>Fbcl,&FbclFYFYFY>Fhhl&F_\l6#Fbcl>FE<$FailFhhlFEF,F,F,6#Fa]lF,,
I*readBasest+F$6%%#stG%$QBsGF)6"F,C)>F/FY>FE7">F\z-F16$Q)bases/b_F,F4@$4-F96#F
\zY-F16%FAF\zFB?(F,FYFYF,0F/F\uC$>F/-%)readlineGF_[m@$Fd[m>FE7$Fail-%&parseGF=-
F\y6#-F16$F]]l%=~quotient~space~bases~loadedGFEF,F,F,6#FYF,,
I,BasisFindert+6'F%>'%-deg_over_minGF\tF\u>%%modeG%'APPENDG>'%0number_of_basesG
FaoFcdl>'%-prime_numberGFao"&\F$6/F`oF*FcoF]oF[oF_wFgwFewFhn%#BBGFf]lF)%#fdG6"F
,C.>F/-%*prevprimeG6#,&FfuFYFYFY>FfdlFgjl>FhhlFijl>6$FEF\z-F"F_p>Fey-%%tdegG6#-
FSF_[m>F]x-&Faq6#%&BasisG6%FEFey/FhqF/>F_\l&-&Faq6#%*NormalSetG6$F]xFeyF]r>6$F`
xFfdl-Fhv6)FEF_\lF\zF]xFeyF/Fjo>Fabl-Fiu6%/F[rF\]m-F^jlF_pFgjl>Fbcl-%&fopenG6$F
hhlF[r?(F,FYFYF,2-F^p6#FablF\rC$>Fgel-Fc`l6)F`xFfdlF_\lF\zF]xFeyF/@$4-%'memberG
6$FgelFablC%>Fabl7$-FSFf`mFgel-%(fprintfG6%FbclQ$%a|+F,-Fcx6$FgelFin-F\y6#-I(sp
rintfG6$FgalFhal6%Q%%d%sF,-F^cl6#,$*&Fe`mFYF\rFhyFcdlQ,%~completedF,-%'fcloseGF
jilF,F,F,6#FYF,,
I*writeGfant+6$F%>Fa]mFc]m6&F`oF*FcoFf]m6"F,C(>F/-F[^m6#,&FjoFYFYFY>Fey-Fa`m6$Q
)gfan/igfF,%&WRITEG>Fa^mFb^m>FE-%$modG6$-FG6$FI-Fcx6$FEFhsF/-Feam6'FeyQ+Z/%aZ%a
|+%aF,F/F\zFE-Fgbm6#FeyF,F,F,6#FYF,,
I)readGfant+6#'F)F'6&FhwFajl%"nGF`o6"F,C*>F/Fft>FEFY>F\zF\u@$4-F9F_pY-F16%FAF4F
B>FE-Fh[mF_p>Fey-F]\m6#-%*substringG6$FE;Fb`l,&-&%,StringToolsG6#%.FirstFromLef
tG6$Q"[F,FEFYF`sFY?(F,FYFYF,0FEF\uC$>FEFjem@(5/FEQ#|fr|frF,/FEQ"|frF,C%>F/Fap>F
\z,&F\zFYFYFY>(F[oF\zFgjl3F/0-F_fm6$FEFhyQ"|hrF,>Figm7$-FS6#Figm-F_fm6$FEF_s3F/
/F\hmF^hmC$>FigmF`hm>F/FftO6%Fey7#-Fh^l6$-FG6$F]\m(F[oF_al/F_al;FYF\z7#-Fh^l6$-
FG6$f*FazF,6$F]qF^qF,-F]\m6#-F_fm6$F4;FY,&-Fdfm6$Q"+F,F4FYFhyFYF,F,F,FaimFbimF,
F,F,6#FYF,,
I(writeCMt+6$F%>Fa]mFc]m6)%$Ws0GF`oF)Ff]mF*Fco%#WsG6"F,C7>FEFacm>F\z-F16$Q+weig
hts/w_F,F4>F/-%,readWeightsGF_[m>F`\l-&Fefm6#%.SubstituteAllG6%-Fh[n6%-Fcx6$F/F
'FifmQ"(F,Q"]F,Q")F,>6$F]xF_\lFb^m>F_\l-Fcx6$F_\lF'>F]x-Fcx6$-F\dm6$-FG6$FIF]xF
EF'>Fey-Fa`m6$Q'cm/icmF,Fhcm-Feam6'FeyQ<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+F,F`\lFEF
_\l-Feam6%FeyQ6f~=~openOut~"cm_%s";|+F,F4-Feam6$FeyQ<f~<<~toString(pp)~<<~endl;
|+F,-Feam6$FeyQ<f~<<~toString(vr)~<<~endl;|+F,-Feam6%FeyQ9for~i~from~0~to~%a~do
~(|+F,,&FayFYFhyFY-Feam6$FeyQ>f~<<~toString(Ws#i)~<<~endl;|+F,-Feam6&FeyQ.R~=~Z
Z/%a%s,~F,FE-F_fm6$F_\lF_s-Feam6$FeyQDMonomialOrder~=>~Weights~=>~Ws#i];|+F,-Fe
am6%FeyQ0I~=~ideal(%s);|+F,-F_fm6$F]x;""#F`s-Feam6$FeyQVG~=~gb(I,ChangeMatrix=>
true);|+M~=~getChangeMatrix~G;|+F,-Feam6$FeyQ>f~<<~toString(M)~<<~endl;|+);|+F,
-Feam6$FeyQ,f~<<~close;F,FedmF,F,F,6#FYF,,
I'readCMt+F$6(FajlF)F`oFcoF[qF]em6"F,C,>F/FY>FE-F16$Q'cm/cm_F,F4>F]xF\u>F_\lF\u
@$4-F9FWY-F16%FAFEFB>F\z-F]\m6#-Fh[mFW>FeyFban?(F,FYFYF,Fd[mC$>F/Fdan@&3Fd[m/-F
_fm6$F/FYF`\nC$>F]x,&F]xFYFYFY>(%"TGF]x-F_fm6$F/Fc_n3Fd[m/-F_fm6$F/;FY""'Q'matr
ixF,C$>F_\l,&F_\lFYFYFY>(%#CMGF_\l-Fh[n6%-Fh[n6%-F_fm6$F/;""*F`sFcgmFifmF^hmFa
\n-F\y6#-F16$F_\l%8~change~matrices~loadedGO6%F\z7#-Fh^l6$-%%wdegG6$7#-F]\m6#(F
cbnF_alFey/F_al;FYF]x7#-Fh^l6$)-%'MatrixG6#7#-FG6$F]\m(FbcnF_al%#%TG/F_al;FYF_
\lF,F,F,6#FYF,,
I(getTordt+6$%#gbG%#lmG6+FcoF]al%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG%$solG%(
weightsG6"F,C,>F/7#-FS6#-FVF_p>FEFay>F\z/7#-%"$G6$F\uFE%%NULLG>Fey7#-Fh^l6$(Fgw
F_al/F_al;FYFE>F]x-FG6$f*6#%"zGF,6$F]qF^qF,-FG6$f*FazF,6$F]qF^qF,7#-Fh^l6$-Ffz6
$F4F`hl-Fb_l6$F`hlF[\lF,F,6$FcoF[\l-Fcx6$F4FinF,F,6$FcoF/F4>F_\l-FG6$f*FazF,6$F
]qF^qF,F[inF,F,FeinFjo>F`\l-FG6$f*Ff[lF,6$F]qF^qF,-FS6#-FG6$f*FazF,6$F]qF^qF,1F
Y-Fefl6#-%$zipG6%f*6$F`hlFehnF,6$F]qF^qF,*&F4FYFjoFYF,F,F,F4F[\lF,F,6$FdfnFifl-
%%subsG6$F[\l7#-Fh^l6$,&&FhzF_pFY%"gGFhy-Fb_l6$Fi[o&FcflF_pF,F,6*FcfnF\zFffnF_
\lFefnF]xFdfnFey<#-Ffgn6#;FYF]p>F`x&-&%-OptimizationG6#%)MinimizeG6&-FeflFfdmF`
\l/%+depthlimitG"#S/%'assumeGF\t6#Fd_n>Ffdl-Fb[o6$F`xFey6$Ffdl-Ffdn6$FfdlF/F,F,
F,6#Fd_nF,,
I,readWeightst+Fjdm6$FajlF[[n6"F,C(>F/FY>FEFgjl@$FdemYFgem?(F,FYFYF,Fd[mC$>F/Fj
em@$Fd[m>FEF[\m-F\y6#-F16$F]]l%7~weight~vectors~loadedGFEF,F,F,6#FYF,,
I-writeWeightst+6'F%>F[]mF\]m>'%2number_of_weightsGFaoFcdl>Fa]mFc]m>'%+rand_ran
geG7$FaoFao7$"$+#"$+)60F`o%#GsG%$LMsG%#WWG%%gffnGF)Ff]mF_al%"WGF*FcoFh`lF]oF[o6
"F,C&>F/-F[^m6#,&F\rFYFYFY>F]x-F16$Q)gfan/gf_F,F4>F_\lF`[n@%-F9F]hlC(-F\y6#%IGe
nerating~weight~vectors~from~Gfan~fileG>6%F/FEF\z-FhdmF]hl>Fey7#-Fh^l6$&-F]fn6$
&FEFhdl&F\zFhdlF]r/F`x;FYF]]l>F`\l-Fa`m6$F_\lFhcm?&FfdlFeyFap-Feam6%F`\lFgamFfd
l-Fgbm6#F`\lC+-F\y6#%4Gfan~file~not~foundG-F\y6#-F16%%,Generating~GF[r%7~random
~weight~vectorsG>6$FablFgelFb^m>Fhhl-Feal6#;&FfuF]r&FfuF`]oFgbl>Fey-Fiu6%/FjoF
\]m-Fe[nFdilFgjl>F`\l-Fa`m6$F_\lFjo?(F,FYFYF,2-F^pFfdmF[rC&>Fbcl-Ffdn6$7#-Fh^l6
$-FhhlF,/F`x;FY-F^p6#FgelFgel>Febl-Fj^m6%FablFbclF^_m>Ffdl&-F]fn6$Febl-&Faq6#%0
LeadingMonomialG6$FeblFbclF]r@$4-F^am6$FfdlFeyC%>Fey7$-FSFfdmFfdlFdbo-F\y6#-F]b
m6%F`bm-F^cl6#,$*&FddoFYF[rFhyFcdlFebmFfboF,F,F,6#FYF,,
I)saveDatat+6-F%'%#mnGFg_o'%#spG%(numericGF_o'Fco<$FinFhs'%#avGFf_lF\o'%#QBGFin
'%'shiftsGFin'%%polsGFin'%$stdG%(booleanG6'F)Ff]m%$mn0G%$sp0GFhw6"F,C&>F/-Fiu6%
9.-F16$Q-optim/o_std_F,F4-F16$Q.optim/o_nstd_F,F4>F]xFft@%F8C'>FE-Fa`m6$F/%%REA
DG>F\z-F]\m6#-Fh[mF=>FeyFjio@$52&FjoF]r&F\zF]r3/FajoFbjo2FeyF[r>F]xFap-FgbmFW>F
]xFap@$F]xC%>FE-Fa`m6$F/Fhcm-Feam6.FEQ>%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%aF,
FjoF[rF\r-Fcx6$FfuFinFc\lFiy9+9,9-FgjlFgjoF,F,F,6#"#6F,,
I)readDatat+6$F%F`ho6.F)Ff]mFbgoFdgoF`oFcoFigoF]oF[hoF]hoF_ho%$xE0G6"F,C1>F/-Fi
u6%FjoF\ioF_io@$F7YF?>FEFfio>F\zFjio>FeyFjio>F]xFjio>F_\lFjio>F`\lFjio>F`xFjio>
FfdlFjio>FablFjio>FgelFjio>FhhlFjioFgjo6,F\zFeyF]xF_\lF`\lF`xFfdl-FG6$FKFablFge
lFhhlF,F,F,6#Fd_nF,,
I,EigenSolvert+6$'F*-F\w6#%(polynomG>'%'digitsGFao"#:6,%%fB2CGFcoF]oF[oFf]lFjs%
%irndGF\alFcbn%"VG6"F,C0>FEF]gn>F\z-Fe^m6#Fail>F/t+6$'%"fGFi]p'Ff]l-Fin6#Ff_lF^
[l6"F,C$>F/-%&tableG6#-Fjjn6%f*6$F\alF^_lF,6$F]qF^qF,/FjoF4F,F,F,7#-%'coeffsG6%
F4Fjo.F[q7#F[qO-FG6$f*6#F^_lF,6$F]qF^qF,-Fiu6%-%)assignedG6#&F[\lF_pF]apF\uF,F,
6$F_[lF/FjoF,F,F,6#Fd_n>%'DigitsGFjo>Fey-Fj^m6$F4F\z>F]x&-Fb_m6$FeyF\zF]r>F_\l-
F^pF]hl-F\y6#-F16%%<System~is~expected~to~have~GF_\l%'~rootsG>F`\l,$-Feal6#;!%+
5F[blF\bl>F`x-Fefl6$*&FfwFY-F`\lF,FY-Fb_l6$FfwFE>Ffdl-&Faq6#%5MultiplicationMat
rixG6'F`xF]x-Fd_p6#-%'EquateG6$F]x7#-Ffgn6#F[fnFeyF\z>Fabl&-&Fer6#%-Eigenvector
sG6#-%&evalfG6#FfdlF`]o>Fabl-&%"|irG6#_F,%"/G6%Fabl%#~$G-%".G6$-F]w6$F_\l/%%fil
lGFY&FablF]rO-F`ep6$-Fcen6#-FG6$f*6#F__lF,6$F]qF^qF,-Fifl6$-F`q6%F4F[\lFhzFcflF
,F,6*F[oFeyF]oF\zFf]lF]xF_^pF/FEFablF,F,F,6#FYF,,
I$srtf*6$'F__lF\wF\oF,6$F]qF^qF,-Figl6$F4f*F_hlF,6$F]qF^qF,-&Faq6#%*TestOrderG6
%FjoF4FeqF,F,6$F]oFjoF,F,F,F,,
I,poly2matrixt+6%F[w'%#nFGFaoFfgo6$%%monsG%%cffsG6"F,C$>FE7#-F^`p6%-FI6#-Fefl6$
*&(%$q_qGF_alFY&F46#F_alFY/F_al;FYFjoF[r.F/6$-Fcen6%FjoF]]lf*6$F_al%"jGF,6$F]qF
^qF,-%&coeffG6$&F[\lFio(FjhpF4F,F,6$F]hpFE-F]w6#7#F/F,F,F,6#Fb`lF,,
I/permuteColumnst+6%'FhnFcen'%#V1GF]w'%#V2GF]w6#F]em6"F,C$>F/-FS6$FYFjo-F`ep6$F
4-Fcen6$F/<#-Fh^l6$/6$F_al-&%*ListToolsG6#%'SearchG6$&FjoF\ipF[rFY/F_al;FYF/F,F
,F,6#Fb`lF,,
I)sparsityt+6#Fdjp6#%&numzrG6"F,C$>F/-F^p6#-F^z6$f*FazF,6$F]qF^qF,-F_r6#/F4F\uF
,F,F,Fcin*&F/FY-%$mulG6#-FS6$FYF4FhyF,F,F,6#FYF,,
I(matrixSt+6''Ff]lFinF^wFjnF\oF[t6%Fdo%#V0GFjs6"F,C&>F\zF]p@$0F^xF\zY%ILists~B0
~and~B~must~have~the~same~lengthG>F_]l-Fep6%-FG6$f*Ff`pF,6$F]qF^qF,F_qF,F,FeuF4
F\zF`t@%/-FS6$FYFEF\zO-Fajp6%F/FE-F]wFioY%=Failed~to~construct~matrix~SGF,F,F,6
#FgvF,,
I*quotientst+6&'Fi[oFi]pFjnF\oF[tF,6"F,C$-F`q6'F4FjoF[r.%"QG/FhqF\rFb`qF,F,F,6#
FcsF,,
I-monPartitiont+6'Fhgo'%#GrGFinF\oF[t>FjgoFgjl6,F_wFf]l%#aBG%"RG%#B2G%#RBGF[o%#
nGGFcbnFdo6"F,C->F/&-Fb_m6$FjoF[rF]r>FE-Fcx6$-Fiu6%/FfuFgjlF/FfuFhs>F\z-FG6$f*F
azF,6$F]qF^qF,Fi[lF,F,6$FigoF4FE>Fey-Fgfp6$-Fcx6$-F\`l6$F\zFEFinF[r>F`xFddo>F]x
-FG6$f*FazF,6$F]qF^qF,*&F4FYFeqFhyF,F,Fbbq-Fi_lFibq>FE7$-FS6#-Fgfp6$-Fcx6$-F\`l
6$FEF]xFinF[r-FS6#-Fgfp6$-Fcx6$F]xFinF[r>6$F_\lF\z6$7$FdfoFail-FG6$f*FazF,6$F]q
F^qF,Fi[lF,F,FbbqFE@%F\bq>Ffdl-F`cp6(F4FE-Fd_p6#-Fgcp6$FE7#-Ffgn6#F_boFjoF[rFc`
qC%>Ffdl-F`cp6(F4F/-Fd_p6#-Fgcp6$F/7#-Ffgn6#;FYFayFjoF[rFc`q>Fabl-Fj]q6'FEF/Fjo
F[rF\r>Ffdl-Fiu6%0F\rF\u-F\dm6$-F`ep6%FablFfdl-&Fdr6#%(InverseG6$F\rFablF\r-F`e
p6%FablFfdl-&Fer6#%.MatrixInverseGFf`m>F`\l-Fcx6$,&-F]wFfdmFY-F`ep6$&Ffdl6$;FYF
`xFas-F]wFWFhyFinO6(F\zFEF_\lFfdlF`\l-Fcen6#7#-Fh^l6$-Fi_q6&&F`\lF\ipFjoF[rF\r/
F_alF`hqF,F,F,6#FgvF,,
I)matrixHit+6&F[wFjnFfgoF[t6/%*undetPolyG%#pvGFjgpF`aq%#uHG%%leqsGFhfnF_al%#dFG
%#dGGFgwFiw%"hG6"F,C)>FE-FeflFat>F\zF]p>FeyF^x>Ffdl-FG6%FfzF4F[r>F/t+6&FfgoFciq
FgwFeip6#F\hp6"F,C%-F^`p6%-FI6#,&FYFY-Fefl6$)Fjo%"pG/F`[r;FYF[rFYF4F_ip>F/F_jp-
Fefl6$*&&F/Ff[lFY&%#_vG6$F\rFg[lFY/Fg[lF`fqF,F,F,6#Fcs?(F`xFYFYFeyFapC%>6$FhhlF
abl6$F\u-FG6$f*FazF,6$F]qF^qF,-Fgcl6$F\uF4F,F,F,,&7#-Ffgn6$-Ffz6$&FjoFhdlF[rF\z
FYFfdlFhy?(FgelF\uFYF,1,&FgelFYFhhlFhyF\uC&>F]x7#-Fh^l6$-F/6&F[rFE,&&Fabl6#Feip
FYFgelFYFeip/FeipFcim>F_\l<#-F^`p6$-FI6#,&F^]rFhy-Fefl6$*&&F]xF[^rFY&F4F[^rFYF
\^rFYF[r>F`\l-%'msolveG6$F_\lF\r@$/-F^p6#<#F`\lF\u>Fhhl,&FgelFYFYFY>&FbclFhdl-F
\dm6$-FG6%-%"@G6$FIFKF]xF`\lF\rO-Fht6#-Fh^l6$-&F]w6#%$rowG6#Fe_r/F`x;FYFeyF,F,F
,6#FcsF,,
I*matrixHnit+6(F[wFjn'%"CGFcen'FbcnFcenFfgoF[t6*%,undetPolyniGFjgpF`aq%#H0GFdiq
FeiqFhfn%%parsG6"F,C+>FEF]p>F\zF^x>F/t+6&'FhiqFi]pFfgo'F_alFao'FeipFaoFejq6"F,C
%-F^`p6%F4FjoF_ip>F/F_jp-Fefl6$*&Fg[rFY&Fi[r6%F[rF\rFg[lFYF[\rF,F,F,6#Fcs>Fey-F
\dm6$-FG6$FI-F`ep6$F[rF\rFc\l>F]x-Fcen6%F\zFEf*FdipF,6$F]qF^qF,-Fcfl6&&F[\l6$F4
FjoFfqF4FjoF,F,6(FbarFeyFcoFfuFaarF/>F`x<#-Fh^l6$&%#_uGF\ip/F_al;FY-F^p6#-F\`l6
$-FVF]hlFfu>F_\l-FG6%F^`p<#-Fh^l6$-F\dm6$-FI6#,&F^\qFhy-Fefl6$*&&F]xFdipFYFh^rF
Y/FeipF_hnFYFc\lFbimFfu>F`\l-F[_r6%F_\lF`xFc\lO-F\dm6$Fh_rFc\lF,F,F,6#F[cnF,,
I*syzModulet+6'F[wFjn'%"AGFcenF\oF[t6*FjgpF`aq%"eG%"LG%#LtGFhnFdoFf]l6"F,C.>F/F
]p>FEF^x>F\z-Fh^l6$-F]w6$FE<#/F_alFYF^hn>Fey7#-Fh^l6$7#-&Faq6#%,LeadingTermG6$F
^\qF\rF^hn>F]x-FG6$f*FazF,6$F]qF^qF,*&&F4F]rFY&F4F`]oFYF,F,F,Fey>F_\l-Fcen6$FEf
*FdipF,6$F]qF^qF,*&-%$lcmG6$&F]apF`]o&FjipF`]oFYFh[oFhyF,F,6&FefrFeyFffrF]x>F`
\l7#-Fh^l6$-Fh^l6$,(*&&F_\lFdipFY&F\zF\ipFYFY*&&F_\l6$FeipF_alFY&F\zF[^rFYFhy-F
ht6#-Fi_q6&z'6&FhirF[jrF^\q&FjoF[^r[[[\[[[[[\[[mFY\[[[[[\[[[[[mFhyFjoF\rFfuFhy/
Feip;,&F_alFYFYFYFEF^hn>F`\l)-FcenFgboFien>F`x-Fcen6#7#-Fh^l6$-Fi_q6&F[ipFjoF\r
FfuF_\q>F`\l-FG6$FI-Fht6$-F`ep6$F`\lF[r,&-&Fer6#%/IdentityMatrixGF=FY-F`ep6$F`x
F[rFhy@$F[v>F`\l-F\dm6$F`\lFfuO&F`\l6$-%'removeG6$f*F\ipF,6$F]qF^qF,-&%+ArrayTo
olsG6#%'IsZeroG6#&F[\l6$F4FasF,F,6$FdoF`\l7#-Ffgn6#;FY-FS6$7$FYFYF`\lFasF,F,F,6
#FgvF,,
I+matrixHsyzt+6(F[wFjnF]arFafrF\oF[t6$Fdo%&ThetaG6"F,C%>F/-F^fr6'F4FjoF\rFfuFc
\l>FE-Fcen6%-FS6$F\^sF[r-FS6$F\^sF/f*FdipF,6$F]qF^qF,&F_[lFhcrF,F,F,O-F\dm6$-FG
6$FI,&F^crFY-F`ep6$FEF/FYFc\lF,F,F,6#F[cnF,,
I(supportt+6$F[_pFfgoF,6"F,C$F]`p<#F[qF,F,F,6#Fd_nF,,
I,fixTemplatet+6'%'admonsGF[wFfgo'%$monGFin'F_aqFin6/Fjgp%%monFG%&admonGF_alFei
pFb`qFhw%#xFGFhnF_^qFewFa^p%%mon1G6"F,C.>F/F^x>FE-FG6$f*6#F\_pF,6$F]qF^qF,-F[`s
FgzF,F,6$FcoF[rFjo>F\z7#-Ffgn6$F^blF/?(FeyFYFYF]pFapC%>F`\lFft?(F]xFYFYF/FapC$>
F_\l-FG6$f*6#%#mfGF,6$F]qF^qF,-Fiu6%-%'divideG6%&Feq6#FhzF4.%"qGFacsFhgnF,F,6&F
e`sF4F_alFey&FEF]hl@$0F_\lF^blC%>&F\zF]hl<$Fjhl-FS6#Fhcs>F`\lFap[@$4F`\lY%;Fail
ed~to~correct~templateG>Fbcl7#-Fh^l6$-Fcx6$-Fdel6$-Fcx6$&F\rF]hlFhsFhcsF]w/F]xF
`\q>F`x7#-Fh^l6$-Fh^l6$*&&FjoF]hlFYFbgoFY-Fb_l6$Fbgo&FbclF]hlF]es>6$FfdlFabl-Fe
p6%F`x-F^pFhdlF[r>Fgel-F\`l6$-Fcx6$FablFhs-Fcx6$FfuFhs>Fgel-Fgfp6$7#-FSF`eo-Fe^
m6#-FSFat>Fhhl-Fht6$Fifs-FS6#Ffu-F\y6#%/Template~fixedGO6&FbclFfdlFablFhhlF,F,F
,6#FgvF,,
I2constructTemplatet+6&'%"HG<$FcenFinF[wFfgoFh`s6)FjgpFg`sF\asFhnF_^qFewFa^p6"F
,C+>F/F^x>FE-Fiu6%-Fc^l6$F4Fcen7#-Fh^l6$&-Fep6%&F46$FasFeip-FS6$F\^sF4F[rF`]o/F
eipF`\qF4>F\z7#-Fh^l6$-Fh^l6$*&FdjrFYFbgoFY-Fb_l6$Fbgo&FEF[^rFais>6$FeyF]x-Fep6
%F\z-F^pF_[mF[r>F_\l-F\`l6$-Fcx6$F]xFhs-Fcx6$F\rFhs>F_\l-Fgfp6$7#-FSFdilFjfs>F`
\l-Fht6$F\[t-FSFcbl@$0-FS6$FYF`\l-FS6$FYF]xC$-F\y6#%7Template~is~incompleteG>6&
FEFeyF]xF`\l-Fb`s6'-F\`l6$-Fcx6$F`\lFhsFdjsFjoF[rFEF\r6%FE-Fajp6%FeyF]xF`\lF`\l
F,F,F,6#FcsF,,
I-adjustParamst+6'F[w'F\hsFcenFh`s'FcoFhsF[t63FjgpF`aq%#H1G%#LmG%%colsGFefrFg`s
F_^qFewFdfr%#smG%#rmG%#npG%#ssG%$prmGFeiqFhfn6"F,C3>F/F]p>FE-FS6$F\^sFjo>F\zFjo
>Fey-Fh^l6$-Fep6%&FjoF^isFEF\rFais>F]x7#-Fh^l6$-Fi\s6$f*FazF,6$F]qF^qF,-%+membe
rtypeG6$Fao-Fcx6$&&F[\l6#,&FeipFd_nFhyFY6$FasF4FinF,F,6$F^]tFey7#-Ffgn6#;FY-FS6
$7$FYFd_n&FeyFa_tFais>F^\l6$7#-Fh^l6$&F\`t6$FasFg^rFais7#-Fh^l6$&&Fey6#,$FeipFd
_n6#Fg^rFais>Fgel7#-Fh^l6$-FG6$f*F^[lF,6$F]qF^qF,-F[`s6$-FI6#*&&FeqF[^rFYF4FYFf
qF,F,6&F*F4FcoF\r&F`\lF[^rFais>F`x-Fcx6$-FG6$FS-FG6%-F[`r6$FSFcxFgelFhsFhs>Ffdl
-Fcx6$-F\`l6$F`x-Fcx6$F[rFhsFin>Fgel-F]wF`eo>Fhhl-FG6$f*6#FdfrF,6$F]qF^qF,-F^z6
$f*F\ipF,6$F]qF^qF,-F^am6$FeqFh[oF,F,6&FdfrF4F`]tF[\l<#-Ffgn6#;FY-FS6$FYF[\lF,F
,6$F`]tFgelFfdl>Fbcl7#-Fh^l6$-%"+G6#-Fh^l6$-F^p6#-F^z6%%$hasGFhhl&&FhhlF[^rF\ip
/F_al;FY-F^p6#Faet/Feip;FY-F^p6#Fhhl>Feblf*6&F_alFeipFa]tFb]tF,6$F]qF^qF,52-F^p
6#&F[rFio-F^p6#&F[rF_p3/FcftF`ft2&F\rFio&F\rF_pF,F,F,>82-Figl6$7#-Ffgn6#;FY-F^p
Fedpf*FdipF,6$F]qF^qF,-Fcfl6&F4FjoF[\lFhzF,F,6(Fa]tFhhlFb]tFbclFc]tFebl>Ffdl&Ff
dl6#F\gt?&FablFfdlFapC+>Fey-Fh^l6$-Fep6%&F\zF^isFEF\rFais>F^\l6$7#-Fh^l6$F\`tFa
is7#-Fh^l6$Fh`tFais@$/-F^p6#-FVFdilF\uF]ds>Fgel7#-Fh^l6$-FG6$f*F^[lF,6$F]qF^qF,
FdatF,F,FjatF[btFais>Fhhl-FG6$f*FazF,6$F]qF^qF,<#-&Fj[q6#%*SearchAllG6$FY-FG6$f
*6#F`hlF,6$F]qF^qF,-F^p6#-Fi_l6$F4<#F[\lF,F,6$FdfrF[\lF4F,F,6$FdfrFablFgel>83<#
-Fh^l6$-FS6#-FG6$f*Ff[lF,6$F]qF^qF,-FS6#-Fcx6$&&F[\lF[^rFc_tFhsF,F,6$FefrF_\lFa
etFais>84-F[_r6$Fa[uFfu@$/-F^p6#<#Fc\uF\u\>F\z-F\dm6$-FG6%Fj_rF\zFc\uFfu-Fhgs6&
F\zF4F\rF[rF,F,F,6#FgvF,,
I4isActionMatrixFoundt+6('FcbnFcenFdjp'F\aqFinF]^q'F`aqFaoF[t6'%#tMG%#T1GFjsF[q
%"rG6"F,C'>F\zFbbl>Fey,&F\zFYFfuFhy>F/-F\dm6$-%*GaussjordG6$Fjo.F]xFc\l>FE-F\dm
6$-Fht6$,$&F/6$;,(F]xFYFfuFhyFYFYF]x;,$F\zFhyFhyFhy-Fcen6%FeyF\z<#-Fh^l6$/6$,(F
eyFYFg[lFhyFYFY-Fi[q6$&F[r6#,$Fg[lFhyF\rFY/Fg[lFh`rFc\l-&Fer6#%&EqualGFeelF,F,F
,6#F[cnF,,
I/SchurReductiont+6(Fdjp'Fa^pF]wF]ho'%#nEGF\tF_oF^ho66%#rgG%$crgGF[q%#M1G%#bsG%
#M2G%$tM2GF]^u%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GF^aq%#B3G%#B4G%$iB1G%&rperm
G%&cpermG6"F,C6@$/-F^p6#Fc\lF\uO6'F4FjoF\uFgjlFgjl>F/7#-Fh^l6$-FS6#7#-Ffgn6#;,&
-Fefl6$-FS6$FY&F[rF\ip/F_al;FY,&F`[rFYFhyFYFYFYFY-Fefl6$Ffcu/F_al;FYF`[r-Fb_l6$
F`[rFc\l>F\zFay>FE7#-FS6#-F\`l6$<#-Ffgn6#;FYF_is<#-FSF=>Fey-Fht6$&F46$F/Fas&F46
$FEFas>F_\l&Fey6$Fcim;FYF\r>F`\l-F\dm6$-Fg^u6$)F_\lFien.F`xFfu>Fhhl-FG6$f*F\ipF
,6$F]qF^qF,-Fi[q6$FY-Fcx6$F]apFinF,F,6$FeauF`\l<#-Ffgn6#F`hq>Fbcl-Fcx6$-F\`l6$<
#-Ffgn6#;FY-FS6$F[`tF`\lFhhlFin>86-Fcx6$7%-FSFiet-FSFjil-Ffgn6#;Fggm-FS6$F\^sFe
yFin>Fjgu&7$F^euFail6#Fjgu>Ffdl-Fht6%&Fey6$7#F^huFas&Fey6$7#F_huFas&Fey6$;FggmF
hyFas>Fabl-F\dm6$-Fg^u6$&FfdlFheuF`fuFfu>Fhhl-FG6$f*F\ipF,6$F]qF^qF,FffuF,F,6$F
gauFablF[gu>Fbcl-Fcx6$-F\`l6$<#-Ffgn6#;FY-FS6$F[`tFablFhhlFin>877%F^huF_hu-Ffgn
6#;Ff`o-FS6$F[`tFfdl>Fgel-%$<|gr>G6%&Ffdl6$FasF^iu&Ffdl6$FasFaiu&Ffdl6$Fas;Ff`o
Fhy>6&FeblF\gtFa[uFc\u6&&Fgel6$F`hqF`hq&Fgel6$F`hq;,&F`xFYFYFYFhy&Fgel6$Ff\vF`h
q&Fgel6$Ff\vFf\v>85-F]gq6$FfuFebl6'-F\dm6$,&Fc\uFY-F`ep6%Fa[uF]]vF\gtFhyFfu&Fjo
6#7$F_hu-Ffgn6#;Ff`oF][qF`xFjguF][vF,F,F,6#F[cnF,,
I0LinDepReductiont+6$FdjpF[t6)F]^uF[^uFbau%$tM1GFiau%&r2delG%&c2delG6"F,C*>FE-F
\dm6$-Fg^u6$)F4FienF_ipFjo>F]x-FG6$f*F\ipF,6$F]qF^qF,FffuF,F,6$F[^uFE<#-Ffgn6#F
`\q>F_\l-Fcx6$-F\`l6$<#-Ffgn6#;FY-FS6$F[`tFEF]xFin>F\z&F46$-Fi\s6$f*F\ipF,6$F]q
F^qF,-F_r6#-Fb_l6$F4F[\lF,F,6$Fb^vF_\l7#FjduFas>Fey-F\dm6$-Fg^u6$F\zF_ipFjo>F]x
-FG6$f*F\ipF,6$F]qF^qF,FffuF,F,6$Fa^vFeyFb_v>F`\l-Fcx6$-F\`l6$<#-Ffgn6#;FY-Fgcl
F]hlF]xFin6%&F\z6$Fas-Fi\s6$f*F\ipF,6$F]qF^qF,Fg`vF,F,6$Fc^vF`\l7#-Ffgn6#;FY-FS
6$F[`tF\zF_\lF`\lF,F,F,6#Fd_nF,,
I)rectTordt+6&F[wF`w'%#TsGFinF[t6(Fjgp%#dgGF^al%#nnG%$GBsGF[[n6"F,C+>F/F]p>FE7#
-Fh^l6$*&-Fefl6#-FG6%FfzF4FfwFYF/Fhy-Fb_l6$FfwFjo>F\z-FG6$f*6#FgwF,6$F]qF^qF,*$
F4FhyF,F,F,FE>Fey-F[ir6#-FS6#-FG6$%&denomGF\z>F\z*&FeyFYF\zFY>F]x-FG6$f*FazF,6$
F]qF^qF,-Fj^m6%FeqF4/FhqFfqF,F,6&F*F4F`oF\rF[r>F_\l7#-FS6#<#-Fh^l6$&-F]fn6$&F]x
F\ip-Fieo6$F\gvFhcuF]r/F_al;FYFjap>F_\l-FG6$f*FdhnF,6$F]qF^qF,-Fjjn6%f*F_hlF,6$
F]qF^qF,F_[oF,F,F,F4F[\lF,F,6$F^alF\zF_\l-FG6$f*FazF,6$F]qF^qF,-FfdnFgzF,F,6$Fc
oFjoF_\lF,F,F,6#FcsF,,
I,filterBasest+6&F[w'FbjlFin'%%nQBsGFao'%#ffGFego6&%#mFG%#BsGFd]t%"NG6"F,C(>Fey
-F^cl6#*&F\rFYF[rFY>F/-Fcx6$&-Fep6%F4F]pF`gnF`]oFhs>FE-FG6$f*FazF,6$F]qF^qF,-F^
p6#-Fi_l6$-Fcx6$F4FhsF[\lF,F,6$F[ivF/Fjo>F\z-Figl6%FE%">G/%'outputG%,permutatio
nG-F\y6#-F16$Fey%>~quotient~space~bases~removedG7#-FS6$;FY,&F[rFYFeyFhyF\zF,F,F
,6#FcsF,,
I-filterBases2t+6*FigpFfgo%$CMsGFicvFecvFbjlF_oFhhv69Fi`qF]oFf]lFbcnFghvFjsF_al
%#vBG%#tBG%#mpGFigoF\aqFcbnF[oF^arF\hs%$cHsGF[q%$avoG%#msG%#moGFd]tF]iv6"F,C+>F
]xFfbl>F_\l-F^p6#&Fc\lF]r>F][vFgjl>88"(+++">8:-F^cl6#*&Fc[pFYF]xFY?(F`\lFYFYF]x
FapC(>6&F/FEF\zFey6&&F\rFgbo&FfuFgbo&Fc\lFgbo&F[rFgbo@$0F`jsF_\lF[]u>6%F`xFfdlF
abl6%-F]wF_[m-Fd_p6#-Fgcp6$F\zFicpF^]w?&FgelFjoFapC*>Fhhl-FG6$f*6#FbgoF,6$F]qF^
qF,*&F4FYF[\lFYF,F,6$FigoFgelF\z>Fbcl-F`cp6(FgelF\zFfdlF/FE/FhqFiy>Febl,&-F]wFi
etFY-F`ep6$FbclF`xFhy>F\gt-Fcen6#7#-Fh^l6$-Fi_q6&&FeblFf[lF/FEFiy/Fg[lF[fn>Fa[u
-F\dm6$-FG6$FI-F`ep6$F\gtFeyFiy>Fc\u7#-Fh^l6$-Fefl6#&Fa[u6$FasFg[l/Fg[l;FYF4>F]
]v-Fefl6$-Fiu6%-Fc^l6$%"cGFgdt-F^p6#F\bwFY-Fb_l6$F\bwFc\u@$2F]]vFablC$>FablF]]v
>FjguFgel@$2FablF]]wC$>F]]wFabl-F\y6#-F]bm6%Q>Smaller~template~found:~%d,%aF,F]
]wFjgu>F][v7$-FS6#F][vFabl>89-Figl6%F][v%"<GFjjv-F\y6#-F16$F`]wFa[w7#-FS6$;FY,&
F]xFYF`]wFhyFdcwF,F,F,6#"")F,,
I(iniProbt+6&F%F`hoFhhv'%#pnGFao60F*%#vFGF`oFcoFicvFecv%#GCGFbjlF[\wF]oFbcnF[oF
acsFghv6"F,C,>F\zF\r>6$F/FeyFb^m>6$FEFey6$-F]wF=<#Fdfo>Fabl-Fe^m6#Fdfo-F\y6#-F1
6%%;The~problem~is~defined~by~GFay%-~polynomialsG>Fhhl-Fj^m6%F/Fabl/FhqF\z@$0-&
Faq6#%1HilbertDimensionG6$FhhlFafwF\uYQZThe~problem~is~expected~to~have~infinit
ely~many~solutionsF,-F\y6#-F16(%,Variables:~G7#Fdfo%,;~degrees:~G-FG6$FfzF/%8;~
number~of~solutions:~G-F^p6#&-Fb_mF`\rF]r@%FjoC(>6%F\zF_\lFfdl-F_`nF_p>FeblFcgt
>F]x7#-Fh^l6$-F\dm6$-FG6$FI-Fcx6$-F`ep6$&FfdlF\ipFEFinF\z/F_al;FYFebl>F`x7#-Fh^
l6$&-Fb_m6$F\gv&F_\lF\ipF]rF\iw>Fbcl-Fh[w6*FayFeyFfdlF]xF_\lF`xF\zF[r>6&FfdlF]x
F_\lF`x6&7#-Fh^l6$F[iw-Fb_l6$F_alFbcl7#-Fh^l6$F\gvF_jw7#-Fh^l6$FeiwF_jw7#-Fh^l6
$&F`xF\ipF_jwC(>F`xF^`m>6$FeblFabl6$F]fsFfew>F`\l-Fj^m6&F/FablFafw/F[[w%)extend
edG>6$FhhlFgel6$&F`\lF]r-Fcen6#&F`\lF`]o>Fbcl-Fbhv6&F/F`xFeblF[r>Fjiw6&7#-Fh^l6
$FgelF_jw7#-Fh^l6$FhhlF_jw7#-Fh^l6$FablF_jwFgjwO6)F\zF/FeyF]xF_\lF`xFfdlF,F,F,6
#FcsF,,
I/TemplateFindert+6(F%>'%,action_varsG-Fin6#<$%'negintGFaoFgjl>'Fiau%'symbolGFa
ho>'%,filter_fracGFegoF\u>Fa]mFc]m>'%+schur_polsGFc]xFgjl6HF`oF*FcoFicvFecvFbjl
F[\w%&avarsGF]alFjsFghvF]ivF_alFeipFi`qF]oF[hoFbcn%&tord1GFigoF\aqFf]lF_aqFcbnF
[oF^arF`aqF\hsF]hoFhnFa^p%#flGF[qF]emFdgoFc\w%#noG%$spoG6"F,C+>F/Fj]m>8GF^]w>8I
Fhy>6)F/FEF\zFeyF]xF_\lF`\l-Fcdw6&F4-%&evalbG6#/F[rFahoF\rF/>F`x-Fiu6%/F^xF\uF
\z-FG6$f*6#F\alF,6$F]qF^qF,F]apF,F,6$FcoF\zFjo>6%FfdlFablFgel6%F]fs-F^p6#FjhlFc
il>Fhhl,$*&FgelFhyFfdlFhyFcdl?(FbclFYFYFgelFapC%>6&F\gtFa[uFc\uF]]v6&&FeyFjil&F
]xFjilFiil&F`\lFjil>Fjgu-FS6$FYFa[u?(FeblFYFYFfdlFapC.>F][v&F`x6#Febl>6(F]]wFdc
wF`]w8;8<8=-Fe`q6'F][vF\gtFa[uF/Fc\u>8>-F^p6#F[bx>8?-Fiu6%/F[r%%nstdG-F^iq6&FEF
[bxF\zF/-Fj`r6(FEF[bxF\bxF]]vF\zF/>6%8@8A8B-Fg\t6'FEFdbxF`]wF\zF/>F`cx&-Fi`u6(F
`cxFacxF_cx,(-FS6$F[`tF`cxFYFablFhyF`bxFhyF/Fc\lF]r>F`cx&-F]^v6$F`cxF/F]r>8C-Fd
]u6(FjaxF`cxF]]wFdcwF`bxF/>6$8D8E-FS6$FYF`cx>8F-Fb\q6#F`cx@&3F`dx52FedxF[_x3/Fe
dxF[_x2F]_xFjdxC%>6%F[_x8HF]_x6%FedxFfdxFjdx-F\y6#-F]bm6(QTSmaller~or~sparser~t
emplate~found:~[%d,%d],%a,%a,%aF,FedxFfdx-Fddp6$FjdxFb`lF][v-Fiu6%FgbxFbclFjgu-
F^go6-F47$FedxFfdx-Fddp6$FjdxFgvF/F\zF][vFa[uFdcwF_cxFc\lFb_x4F`dxY6&Q@Invalid~
action~matrix,~%1,%2,%3F,FbclF][vFa[u-F\y6#-F]bm6*Q6%d%s,[%d,%d],%a,%a,%aF,-F^c
l6#*&,&*&,&FbclFYFhyFYFYFfdlFYFYFeblFYFYFhhlFYQ"%F,FedxFfdxF^fxF][vF`fx-F\y6#-F
]bm6&Q:Best~template:~[%d,%d],%aF,F[_xFgex-Fddp6$F]_xFb`lF,F,F,6#FYF,,
I$rnd,$f*F,F,6"F,,&-f*F,F,6#/%(builtinG%4RandNumberInterfaceGF,F,F,F,F,6%F[cn"%
,?Fg[pFYFfbpFYF,F,6$%6_thismoduledefinitionGF,F\blF,,
I'rndMatf*6$'F[qFao'F]emFaoF,6$F]qF^qF,-Fcen6%F4Fjof*F_hlF,6$F]qF^qF,-Fh`lF,F,F
,F,F,F,F,F,,
I'rndVecf*6#FaixF,6$F]qF^qF,-F]w6$F4f*FazF,6$F]qF^qF,FhixF,F,F,F,F,F,F,,
I&crossf*6#'F__lF]wF,6$F]qF^qF,-Fht6%-Ff[v6%F\u,$&F46#Fb`lFhyFchr-Ff[v6%F[[yF\u
,$FbhrFhy-Ff[v6%,$FchrFhyFbhrF\uF,F,F,F,,
I-readTemplatet+Fj[p6LFdhoFehoF`oFcoFigoF]oF]hoF`^xF*F^ar%#U0G%&tord0G%"UGFi`qF
\aqF[buFf]lF]aqF^aqF_wF_aqFcbnF[oFdoFjs%#nRGFbauFa^pFfjpF]^uF_buF`buFhnFa^v%#t1
GFb^vFc^vFewFbgo%#xEG%#xVGF\\p6"F,CE>6,F/FEF\zFeyF]xF_\lFc\uF`\lF`x8M-Fh[pFhcr>
Ffdl&Fb^mF]r>Fcco-Fep6%FfdlFcgtFey>FhhlFfew>Fbcl-Fgfp6$FgelFhhl>Fabl-Fajp6%Fabl
FgelFbcl>Febl-Fj^m6%FfdlF_\lFafw>Fa[u&-Fb_m6$FeblF_\lF]r>Fc\u-Fcx6$Fc\uFhs>F\gt
-FG6$f*FazF,6$F]qF^qF,F__wF,F,6$FigoF]xFc\u>F]]v-Fgfp6$-Fcx6$-F\`l6$F\gtFc\uFin
F_\l>6$F[bxF\bx6$-F^p6#Fc\u-F^p6#F]]v>Fjgu-FG6$f*FazF,6$F]qF^qF,*&F4FYF[\lFhyF,
F,F^^y-Fi_lFe^y>F][v-%&getB0G6$FjguFey>Fjgu7$-FS6#-Fgfp6$-Fcx6$-F\`l6$FjguF][vF
inF_\l-FS6#-Fgfp6$-Fcx6$F][vFinF_\l>Fc\u7$-FS6#-Fgfp6$-Fcx6$-F\`l6$Fc\u-Fcx6$Fj
guFhsFinF_\l-FSFhhu>6$F]]wF\gt6$7$-FSF\_y-FSFj^y-FG6$f*FazF,6$F]qF^qF,F__wF,F,F
^^yFc\u>Fdcw-F`cp6(F]xFa[u-Fd_p6#-Fgcp6$Fa[u7#-Ffgn6#;FY-F^p6#Fa[uFeblF_\lFafw>
Fjax-Fj]q6'Fc\uFa[uFeblF_\lF\z>Fdcw-F\dm6$-F`ep6%FjaxFdcw-F]gq6$F\zFjaxF\z>F`]w
-Fcx6$,&-F]wF\_yFY-F`ep6$&Fdcw6$;FYF\bxFas-F]wFj^yFhyFin>6$F`bxF_cx&-Fhgs6&F`\l
FfdlFeyF]]w6#;Fd_nFb`l>6'F`bxFdbxF`cxFacxF`dx-Fi`u6(F`bxF_cxF`\l,(-FS6$F[`tF`bx
FYF[bxFhyF\bxFhyF\zF`x>6%FedxF[_xFgex-F]^v6$F`bxF\z-F\y6#-F16$%6Action~matrix~f
ound:~G-Fd]u6(FdcwFedxF\gtFc\uF\bxF\z>8J7#-FS6$FYFedx-F\y6#-F16$%2Template's~si
ze:~GF[fy@$50&F/F]r&F[fyF]r0&F/F`]o&F[fyF`]oYQ/Wrong~templateF,>8L-F\`l6$-Fcx6$
F_cxFhs-Fcx6$FdbxFhs>Fdbx&Fdbx6#-Fi\s6$f*F\ipF,6$F]qF^qF,Fg`vF,F,6$Fc^vFgex7#-F
fgn6#;FY-FS6$FYFdbx>Ffdx-F\dm6$-Fg^u6#&F`bx6$-Fi\s6$f*F\ipF,6$F]qF^qF,Fg`vF,F,6
$Fb^vF[_x7#-Ffgn6#;FY-FS6$F\^sF`bxFasF\z>Fjdx-FG6$f*FazF,6$F]qF^qF,-FS6#-F^z6$f
*FgjtF,6$F]qF^qF,0&F[\l6$F4FfqF\uF,F,6&Fa^vF[\lFbzF4<#-Ffgn6#;FY-FS6$F\^sF[\lF,
F,6$Fa^vFfdx<#-FS6#Fgex>8K-Fdel6$-Fcx6$Fa\yFhs-Fcx6$&Fdbx6#7#-FS6#FjdxFhs>F]_x-
Fgfp6$-Fcx6$-F\`l6$Fdgy-Fcx6$F]]wFhsFinFhhl64FeyF]xFablFbclF]_xF]]wFc\uF\gtF`\l
F[_xFgexF[fyF\bxF`[zF`cxFacxF`dxF_gyF,F,F,6#Fd_nF,,
I&getB0t+6$'%"PGFhsFfgo6'F]alF_al%$VrsG%$vrsGF_w6"F,C$>F/F^x?(FEF\uFY,&F/FYFhyF
YFapC$>F\z-&%)combinatG6#%'chooseG6$Fjo,&F/FYFEFhy?&FeyF\zFapC$>F]x-F^z6$f*FjpF
,6$F]qF^qF,-Fcx6$-FG6$f*6#FfwF,6$F]qF^qF,-F^am6$Fi[lFfqF,F,6&F[qF4F[]zFfqF[\l%$
andGF,F,6&F^]zFeyF[]zF4F4@%0FjapF\uO-Fcx6$-FG6$f*Fi^zF,6$F]qF^qF,*&F4FY&F[\lF]r
FYF,F,6$F_wF]x7$FdfoFYFhs>F]xF^blF,F,F,6#Fd_nF,,
I*iniColpivt+6&F\au'F[\yFhsFhgoF`w6*%#VlGF[]zF_w%#aPGF]aq%#RPGFewF]o6"F,C0>F`x-
Fe^m6#F`[t>F/-Fcx6$-F\`l6$FcjvFjoFin>FE-Fcx6$-F^z6$f*FjpF,6$F]qF^qF,-F^am6$Fi[l
FhzF,F,6&FigoF[rFd`zF/F/Fhs>F\z-Ff_y6$FEF\r>Fey-FG6$f*FjpF,6$F]qF^qF,Fi[lF,F,6$
FigoF[rFE>F]x-Fgfp6$-Fcx6$F]elFinF`x>FE7$-FS6#-Fgfp6$-Fcx6$-F\`lFa^mFinF`x-FS6#
-Fgfp6$-Fcx6$F\zFinF`x-F\y6#%?List~of~permissible~monomials:G-F\yFW-F\y6#-F16$%
BNumber~of~permissible~monomials:~GF]]l>Fey-FG6$f*FjpF,6$F]qF^qF,-Fi[q6$Fi[l7$-
FSF_cs-FS6#FcflF,F,6(FigoF[rF[]zFEF]aqF]xFE>F_\l7$F\hlFail>F`\l-Fgfp6$-Fcx6$-Fd
el6$-F\`l6$-Fcx6$F/Fhs-Fcx6$F_\lFhsFjoFinF`x6'-Fht6$-FSFgboF\[tFEFeyFjap-F^pFgb
oF,F,F,6#FcsF,,
I,alter_commaf*6#'F__lFinF,6$F]qF^qF,-F16%Fifm-FS6#-&Fj[q6#%+InterleaveG6$F47#-
Ffgn6$Q",F,,&F]pFYFhyFYFa\nF,F,F,F,,
I-write_solvert+6/'%$dirGF'Fdho%&vars0GFigo%#iMG%#eMGFf]lF\aqFbgoF^auFi[yF]^uFa
ho6)%&vars1G%#vvGFf]m%$nv0GFjsF_al%#fbG6"F,C>>FeyFfbl>F]x-F^p6#Fiy>F`\lQ%~~~~F,
>F/-Fcx6$-F\`l6$Fjbt<#F\rFin>FE7#-Fh^l6$-Fi[q6$*&&F/FdilFY&Fiy6#FhyFYFiy/F_\l;F
Y,&FeyFYFhyFY>F\z-Fa`m6$-F16+F4Q"/F,-Fiu6%90Q%std_F,Q&nstd_F,,&&Fd[pF]rFY9/FhyQ
"xF,,&&Fd[pF`]oFYFjjzFhyQ"_F,F&F5Fhcm-Feam6$F\z-F16'QH%%~Input:~coefficient~mat
rix~C~of~size~F,FajoF[[[l&FjoF`]oQ#|+|+F,-Feam6$F\z-F16,Q*function~F,-FbfzFatQ$
~=~F,FcjzFhjzF[[[lF\[[lF^[[lF&Q&(C)|+|+F,-Feam6$F\z-F16&F`\lQ(i_dx~=~F,-Fbfz6#-
FG6$f*F\ipF,6$F]qF^qF,FbhrF,F,F,FfuQ#;|+F,-Feam6$F\z-F16&F`\lQ(j_dx~=~F,-Fbfz6#
-FG6$f*F\ipF,6$F]qF^qF,FchrF,F,F,FfuFi\[l-Feam6$F\z-F16&F`\lQ(C_dx~=~F,-FbfzFfb
uFi\[l-Feam6$F\z-F16(F`\lQ>M~=~sparse(i_dx,j_dx,C(C_dx),F,FijzFcgzF][[lQ$);|+F,
@$0FjjzF\u-Feam6$F\z-F165Q"|+F,F`\lQ'M~=~M(F,,&FjjzFYFYFYQ&:end,F,Fi^[lQ*:end)-
(M(F,Fi^[lQ(:end,1:F,FjjzQ')/M(1:F,FjjzQ$,1:F,FjjzQ())*M(1:F,FjjzFcgzFi^[lQF:en
d);~%%~Schur~complement~reduction|+F,-Feam6$F\z-F16'Fg^[lF`\lQ5[L,|ir,Pi]~=~lu(
M(:,1:F,Fe[pQ%));|+F,-Feam6$F\z-F16$F`\lQ+Pi~=~Pi';|+F,-Feam6$F\z-F16(F`\lQ0M~=
~[Pi*L~Pi(:,F,,&Fe[pFYFYFYQ,:end)]\M(:,F,Fa`[lQ(:end);|+F,-Feam6$F\z-F16&F`\lQ+
M~=~M(end-F,,&F[ioFYFhyFYQ*:end,:);|+F,-Feam6$F\z-F16'Fg^[lF`\lQ+T~=~zeros(F,F]
xF`^[l-Feam6$F\z-F16*F`\lQ%T(1:F,F[ioQ.,:)~=~-M(:,1:F,F[ioQ')\M(:,F,,&F[ioFYFYF
YFc`[l@&/,&F]xFYF[ioFhyFY-Feam6$F\z-F16&F`\lQ#T(F,*&F]xFY-Fi[q6$&Fc[pFiizFiyFYQ
()~=~1;|+F,2FYFja[l-Feam6$F\z-F16&F`\lF_b[l-Fbfz6#7#-Fh^l6$,&*&F]xFY,&-Fi[q6$&F
c[p6#,(F_\lFYF]xFhyFhyFYFiyFYFhyFYFYFYF_\lFY/F_\l;Fga[lF]xFdb[l-Feam6$F\z-F16%F
g^[lF`\lQ1[V,D]~=~eig(T);|+F,@%/F]]lFY-Feam6$F\z-F16(F`\lQ*sol~=~[V(F,&FEF]rQ(,
:)./V(F,F]xQ3,:);~diag(D).'];|+|+F,-Feam6$F\z-F16*F`\lFdd[l-FbfzFWQ/,:)./repmat
(V(F,F]xQ%,:),F,F\jzQ3,1);~diag(D).'];|+|+F,-Feam6$F\z-F16$F`\lQXI~=~find(not(i
snan(sol(1,:)))~&~not(isinf(sol(1,:))));|+F,-Feam6$F\z-F16$F`\lQdo%%I~=~I(not(i
mag(sol(1,:))));~%%~uncomment~this~line~for~real~roots~only|+F,?(F_\lFYFYF\jzFa
p-Feam6$F\z-F16'F`\lFgizQ(~=~sol(F,F_\lQ&,I);|+F,-Feam6$F\z-F16'F`\lF\rF_f[lFey
Q',I);|+|+F,-Feam6$F\zQ$endF,-FgbmF_[mF,F,F,6#"#8F,,
I4write_solver_colpivt+60FhgzFdhoFjgzFigoF[hzF\hzF[]zFe`zFbgoF^auFi[yFjsF]^uFah
o6)F^hzF_hzFf]mF`hz%#nPGF_alFahz6"F,CB>FeyFfbl>F]xFfhz>F`\lFihz>F/F[iz>FE7#-Fh^
l6$-Fi[q6$Ffiz&Fiy6#;,$FjjzFhyFhyFjiz>F\z-Fa`m6$-F16+F4Fbjz-Fiu6%91FfjzFgjz,&Fi
jzFYFejzFhyF[[[l,&F][[lFYFejzFhyQ)_colpiv_F,F&F5FhcmF_[[l-Feam6$F\z-F16,Fj[[lF[
\[lF\\[lFfh[lFih[lF[[[lFjh[lF[i[lF&F]\[l-Feam6$F\z-F16&F`\lFb\[l-Fbfz6#-FG6$f*F
\ipF,6$F]qF^qF,FbhrF,F,F,FfuFi\[l-Feam6$F\z-F16&F`\lF^][l-Fbfz6#-FG6$f*F\ipF,6$
F]qF^qF,FchrF,F,F,FfuFi\[lFe][lF[^[l@$0FejzF\u-Feam6$F\z-F165Fg^[lF`\lFh^[l,&Fe
jzFYFYFYFj^[lFjj[lF[_[lFjj[lF\_[lFejzF]_[lFejzF^_[lFejzF__[lFejzFcgzFjj[lF`_[l@
%0Fe[pF\uC&Fa_[lFg_[lF\`[l-Feam6$F\z-F16&F`\lQ,M~=~full(M(F,Fa`[lQ+:end,:));|+F
,-Feam6$F\z-F16$F`\lQ.M~=~full(M);|+F,@$0F[ioF\uC%-Feam6$F\z-F16'Fg^[lF`\lQ6[L,
UR,Pi]~=~lu(M(:,1:F,F[ioFf_[lFg_[l-Feam6$F\z-F16(F`\lF``[lFga[lFb`[lFga[lFc`[l-
Feam6$F\z-F16&F`\lQ*MP~=~M(1:F,F[ioQ&,:);|+F,-Feam6$F\z-F16&F`\lQ(NP~=~M(F,Fga[
lQ+:end,:);|+|+F,-Feam6$F\z-F16&F`\lQ:[Q,U,Pi]~=~qr(NP(:,1:end-F,Fg\lFf_[l-Feam
6$F\z-F16(F`\lQ4A~=~UR\[MP(:,1:end-F,Fg\lQ/)*Pi~MP(:,end-F,FeyQ):end)];|+F,-Fea
m6$F\z-F16*F`\lQ+B~=~U(:,1:F,,*FijzFYFejzFhyFe[pFhyF[ioFhyQ()\[U(:,F,,,FijzFYFe
jzFhyFe[pFhyF[ioFhyFYFYQ3:end)~Q'*NP(:,end-F,FeyF\^\l-Feam6$F\z-F16(F`\lQ/M~=~[
-A(:,end-F,,&FjjzFYFhyFYQ1:end)+A(:,1:end-F,FjjzQ,)*B;~-B];|+|+F,-Feam6$F\z-F16
&F`\lQ&xP~=~F,-Fbfz6#Fc[pFi\[l-Feam6$F\z-F16*F`\lQ*P1~=~[(1:F,,(F]xFYFeyFhyFhyF
YQ&)*Pi~F,,&F]xFYFeyFhyQ":F,F]xQ$];|+F,-Feam6$F\z-F16-F`\lQ-T~=~getT(M,[F,F`bnF
]`\l,&F]xFYF[ioFYQ+~P1(1:end-F,FjjzQ+)],P1(end-F,F[_\lQ&:end)F,Q',xP);|+F,Fic[l
@%F_d[l-Feam6$F\z-F16(F`\lFdd[lFed[lFfd[lFjjzFgd[l-Feam6$F\z-F16*F`\lFdd[lF\e[l
F]e[lFjjzF^e[lF\jzF_e[lF`e[lFee[l?(F_\lFYFYF\jzFapF[f[lFaf[lFff[lFif[lF,F,F,6#"
#9F,,
I4write_inidata_coefst+6$F%'%)root_dirGF'6.%*proc_nameG%#_CG%&_nameG%&_sizeG%#C
sG%#ClGFigzFf]mF_alFdfr%$idxGFahz6"F,C6>FhhlFihzAF0>F/-FK6#-F16$%#C_GF4>6%FEF\z
FeyF`cl>F`\l-F16%FjoFbjzF4@$4-F9Fgbo-&F:6#%.MakeDirectoryGFgbo>F`x-Fa`m6$-F16&F
`\lQ*/inidata_F,F4F5Fhcm-Feam6$F`x-F16%Q9function~data~=~inidata_F,F4Q$()|+F,-F
eam6$F`x-F16&FhhlQ0data~=~cell([1,F,FddoQ%]);|+F,?(FfdlFYFYFddoFap-Feam6$F`x-F1
6(FhhlQ&data|frF,FfdlQ+|hr~=~randn(F,-F_fm6$-Fbfz6#&FeyFedpFc_nF`^[l-Feam6$F`xF
hf[l-FgbmFhdl>F`x-Fa`m6$-F16&F`\lQ(/coefs_F,F4F5Fhcm-Feam6$F`x-F16%Q4function~C
~=~coefs_F,F4Q)(data)|+|+F,?(FfdlFYFYF`jsFap-Feam6$F`x-F16'Fhhl&F\zFedpQ)~=~dat
a|frF,FfdlQ$|hr;|+F,-Feam6$F`xFg^[l?(FfdlFYFY,$F]]l#FYFd_nFap@$/&FE6#,&FfdlFd_n
FhyFY%#cfGC%-Feam6$F`x-F16(FhhlQ+C~=~zeros(F,-FS6$F\^s&FEFiizFcgz-FS6$F[`tF`h\l
Q%);|+|+F,>Fd\n6$-F\`l6$-Fcx6$&FE6#,$FfdlFd_nFhs<#F\u-Fcx6$Fjh\lFin?&FablF]xFap
C$>Fgel7#-F`jt6$FablF_\l-Feam6$F`x-F16(FhhlQ#C(F,-Fiu6%/F_eoFY&FgelF]r-FbfzF`eo
Q%)~=~F,-Fcx6$FablF'Fi\[l-Feam6$F`x-F16%Fg^[lFhhlQPC~=~C./repmat(sqrt(sum(C.^2,
2)),1,size(C,2));|+|+F,Ffe\lFhe\lF,F,F,6#Fd_nF,,
I/write_test_numt+6+F%FisFagoF`w'FjgzFin'Fh[yF]wFiauFia\l%#cpG6+FigzFf]mFeipFah
z%$fb2GF_hz%$vv0G%&xvarsG%$xvvG6"F,CI>F/-F16%Fc[pFbjzF4>FeyFihz>F]x-F16$FeyFey>
F_\l-FG6$f*Fi^zF,6$F]qF^qF,-F16$F4F4F,F,F,F\r>F`\l-FG6$f*Fi^zF,6$F]qF^qF,Fb\]lF
,F,F,Ffu>F`x-Fcx6$-F\`l6$FfjsFcfsFin>Ffdl-FG6$f*Fi^zF,6$F]qF^qF,Fb\]lF,F,F,F`x@
$F7-Fec\lF=>FE-Fa`m6$-F16&F/Q+/test_num_F,F4F5Fhcm-Feam6$FEQ+rng(23);|+|+F,-Fea
m6$FEQ-N~=~10000;|+|+F,-Feam6$FE-F16'Q%Err_F,F4Q+~=~[];|+Tm_F,F4Q)~=~[];|+|+F,-
Feam6$FEQ.for~i~=~1:N|+|+F,-Feam6$FE-F16&FeyQ0data~=~inidata_F,F4QN();~%%~gener
ate~initial~data~of~the~problem|+|+F,-Feam6$FE-F16$FeyQ%try|+F,-Feam6$FE-F16$F]
xQ&tic;|+F,-Feam6$FE-F16&F]xQ+C~=~coefs_F,F4QV(data);~%%~compute~coefficients~o
f~polynomial~system|+F,-Feam6$FE-F16,F]x-FbfzFgboF\\[l-Fiu6%-Fc_x6#/FiyFahoFfjz
Fgjz&F[rF]rF[[[l&F[rF`]o-Fiu6%Fd[pF[i[lF^[[lF4QA(C);~%%~solve~polynomial~system
|+F,@$0FcgtF\u-Feam6$FE-F16+F]x-Fiu6%/FcgtFY&FfdlF]r-FbfzFedpQ6~=~arrayfun(@(j)
~get_F,-F16#-FSFhdlQ$(C,F,-F_fm6$-Fbfz6#7#-Fh^l6$-F16$&F`\lF_[mQ$(j)F,/F\z;FYF`
fzFc_nQ-),~1:length(F,Fh[xFf_[l-Feam6$FE-F16$F]xQ+tm~=~toc;|+F,-Feam6$FE-F16&F]
xQ,if~isempty(F,FjhlQ2);~continue;~end|+F,-Feam6$FE-F16$FeyQ*catch~ME|+F,-Feam6
$FE-F16$F]xQ+continue;|+F,-Feam6$FE-F16$FeyQ&end|+|+F,-Feam6$FE-F16$FeyQ)M~=~[]
;|+F,-Feam6$FE-F16&FeyQ0for~j=1:length(F,FjhlQ#)|+F,?(F\zFYFYFbblFap-Feam6$FE-F
16'F]x&F\rF_[mF\\[l&F_\lF_[mQ&(j);|+F,-Feam6$FE-F16&F]xQ%m~=~F,-Fbfz6#-Fcx6$Fc
\lFinFi\[l-Feam6$FE-F16$F]xQ6m~=~m/norm(m,'fro');|+F,-Feam6$FE-F16$F]xQ=M~=~[M;
~norm(C*m.','fro')];|+F,-Feam6$FE-F16$FeyQ%end|+F,-Feam6$FE-F16$FeyQ.M~=~sort(M
);|+F,-Feam6$FE-F16&FeyQ4err~=~norm(M(1:min(F,FjoQ7,length(M))),'fro');|+|+F,-F
eam6$FE-F16.FeyFe^]lF4Q)~=~[Err_F,F4Q(~err];|+F,FeyQ$Tm_F,F4Q(~=~[Tm_F,F4Q(~tm]
;|+|+F,-Feam6$FEFgd]l-Feam6$FEQIfolder~=~fileparts(which('add_all.m'));|+F,-Fea
m6$FE-F16'QCsave(strcat(folder,'\_results\Err_F,F4Q-.mat'),'Err_F,F4Q&');|+|+F,
-Feam6$FE-F16)Q3fprintf('Problem:~F,F4Qin.~Ave.~runtime:~%%0.1f~ms.~Med.~error:
~%%0.2e\n',10^3*mean(Tm_F,F4Q.),median(Err_F,F4Ff_[lFgjoF,F,F,6#FjcnF,,
I0write_histo_numt+Fga\l6%FigzFf]mFahz6"F,C6>F/F_c\l>F\zFihz@$F7Fd]]l>FE-Fa`m6$
-F16&F/Q,/histo_num_F,F4F5FhcmFih]l-Feam6$FE-F16%QDload(strcat(folder,~'\_resul
ts\Err_F,F4Q+.mat'));|+|+F,-Feam6$FEQ,bwd~=~0.3;|+F,-Feam6$FEQ-nbins~=~60;|+F,-
Feam6$FEQ9clr~=~[70~100~160]/255;|+F,-Feam6$FE-F16%Q1err~=~log10(Err_F,F4F`^[l-
Feam6$FEQLhr1~=~histogram(err,nbins,'BinWidth',bwd);|+F,-Feam6$FEQ6hr1.FaceColo
r~=~clr;|+F,-Feam6$FEQ7hr1.EdgeColor~=~clr;|+|+F,-Feam6$FEQ8axis([-17~1~0~1150]
);|+|+F,-Feam6$FEQVset(gca,'FontSize',54,'FontName','Times~New~Roman');|+F,-Fea
m6$FEQFset(gcf,'PaperPositionMode','auto');|+F,-Feam6$FEQJset(gcf,'PaperOrienta
tion','landscape');|+F,-Feam6$FEQGset(gcf,'PaperPosition',[1~1~28~19]);|+F,-Fea
m6$FE-F16%QPprint(gcf,'-dpdf',strcat(folder,'\_results\fig_F,F4Q).pdf'));F,Fgjo
F,F,F,6#Fd_nF,,
I0SolverGeneratort+6)F%>Fh]xFaho>%'colpivGFY>%2create_coefs_fileGFY>%2create_hi
sto_fileGFY>%1create_test_fileGFY>Fha\lQ(solversF,6FFcoFigoF^arFh[yFewF_aqFf]lF
\aqF]hoFb^vFc^vFbgoFi[yF[\yF]^uF_buF`buF\\yFa^pFfjpF[]zFe`z%$nR1G%$nE1GFj]lF`g[
lF^auF^[]lFjgz%#iCG%#eCGFhn%#MtGF[hzF\hzFigz6"F,C9>64F/FEF\zFeyF]xF_\lF`\lF`xFf
dlFablFgelFhhlFbclFeblF\gtFa[uFc\uF]]v-Fc[y6$F4-Fc_x6#/FjoFaho>Fjgu-Fht6$F\hlF
\[t>6'F][vF]]wFdcwF`]wFjax-F_`z6&FjguFeblFEF/>6%F[bxF\bxF`bx6%F`fz-F^p6#F]]wFja
p>Fdbx-Fiu6%51F\bxF[bx/F[rF\uFftFap>F_cx-Fiu6%Fdbx-F^z6$f*Fi^zF,6$F]qF^qF,-F^am
6$*&F4FY&F[\lFiizFY&F[\l6#;,$FhzFhyFhyF,F,6&F[]zF]]wFj]lF[bxF/-F^z6$f*Fi^zF,6$F
]qF^qF,-F^am6$Fda^lF[\lF,F,6$Ff]lF`\lF/-F\y6#-F16$%OVariables~that~can~not~be~e
valuated~at~roots:~G7#-FS6#-F\`l6$FhezFbgy>F`cx7#-%(indicesG6$-Fcx6$F\zFd_p%+in
dexorderG>Facx-FG6$f*FazF,6$F]qF^qF,-Fcx6$,&FbhrFY*&,&FchrFYFhyFYFYFijyFYFYF'F,
F,6$F^arF\zF`cx>F\z-Fcen6$-FS6$FYF\z<#-FS6#-Fjjn6%f*F_hlF,6$F]qF^qF,/-FSF_pFjoF
,F,F,F`cxFacx>F`dx&-Fhgs6&Ffdl-Fcx6$-F`ep6$F\zFeyFinF/F_\lF`]o@$0F\gtF\u>F`dx&F
`dx6$Fa[uFc\u>F`dx&F`dx6$-Fi\s6$f*F\ipF,6$F]qF^qF,-F_r6#-Fb_l6$F4-FG6$f*FazF,6$
F]qF^qF,,&F4FYF[\lFYF,F,6$F]^uFhzF[\lF,F,6&Fb^vFablF]^uF\gt7#-Ffgn6#;FY-FS6$F\^
sF`dx-Fi\s6$f*F\ipF,6$F]qF^qF,-F_r6#-Fb_l6$F4-FG6$f*FazF,6$F]qF^qF,Fif^lF,F,Fjf
^lF[\lF,F,6&Fc^vFgelF]^uF\gt7#-Ffgn6#;FY-FS6$F[`tF`dx@$Fdbx>F`dx-Fajp6%F`dx-Fcx
6$-Fht6$FiayFjguF]w-Fcx6$-Fht6$FiayF][vF]w>Fedx-Fcx6$F`dxFd_p>6$FfdxFjdx6$7#-F_
c^l6$FedxFcc^l-FG6$FS7#-%(entriesGFii^l@$4-F9Fghz-Fec\lFghz>F[_x-F16%FiyFbjzF4@
$4-F96#F[_x-Fec\lFij^l@%Fdbx-F\g[l60F[_x7#Fbd^lF_cxFEFfdxFjdxF]]wFdcw7#-FS6$FYF
`dxFjaxF`]wF[bxF\gtFf_^l-Fegz6/F[_xF^[_lF_cxFEFfdxFjdxF`\lF`xF_[_lF`bxFbclF\gtF
f_^l@$/F\rFY-Fea\l6$F4Fiy@$/Fc\lFY-Fij\l6+F4F[bxFhhlF/F_cxFeyFjoFiyFdbx@$/FfuFY
-F[j]lFg[_lF,F,F,6#FYF,
