M7R0
I,readProblemw,6#'%%probG%'stringG6$%#fnG%"FG6"6"C'>8$-%$catG6%Q/../problems/F_
F,9$Q#.mF,@$4-&%*FileToolsG6#%'ExistsG6#F/Y6$Q2file~%1~not~foundF,F/AF/>8%-%$ma
pG6$%'expandG-%%evalG6#-F16$%#F_GF46$FC7#-%#opG6#-%'indetsG6#FCF,F,F,6#"""6)7'Q
!F,!"""#9""'"#O7'FZFen""*"#Z"#J7'FZFen""$"#v"#X7'FZFen"#P"#m"#]7'FZFenF^o"#5"#Y
7'FZFenF^o"#R"#V7'FZFenF^o"#?F\oF,,
I+isLinIndepw,6&%"MG%"GG%%tordG%#ppG6$%%varsG%"SG6"F,C&>F/-FT6#9%@$/-%%nopsG6#F
4FWO%%trueG>FC&-%,poly2matrixG6$-%(convertG6$-FE6$w,6#%"mGF,6$%)operatorG%&arro
wGF,-&%)GroebnerG6#%+NormalFormG6&F4T$T&/%/characteristicGT(F,F,6(FapF\qFbp9&Fc
p9'6#FW6$7'FZFen"#K"#&)Fhn7'FZFenFes"#MFhnF4%%listGF/6#FW-%#isG6#0-&&%.LinearAl
gebraG6#%(ModularG6#%%RankG6$FasFC-F`t6$Fas&FC6$;FW!"#;F,F,F,F,F,6#""%6(7'FZFen
"#8FgnFhn7'FZFenFjn"#DF\o7'FZFenF^o"#UF`o7'FZFen"#BFhs"#_7'FZFenF^o"$1"Fjo7'FZF
enF^o"#"*F\pF,,
I*testBasisw,6'F`p%$degGFapFbpFcpFdp6"F,C&>F/-FT6#F`s@$2F_qF\qO6$%&falseG-%$<,>
G6#-F^w6#""!>FC&-Fgq6$-Fjq6$-FE6$w,F_rF,6$FbrFcrF,FdrF,F,6(FapF`sFbpFasFcp9(6#F
WFcsF4FisF/Fjs6$-%#ifG6%0F^xFbw-F\t6#/-F`t6$F^xFCF\q-F\t6#/-&FbtFetFUF\qFCF,F,F
,6#""&6(7'FZFen"#7FgnFhnFdu7'FZFenF^oFjuF`o7'FZFenFeuFjoFjuF[v7'FZFenF^o"$+"F\o
F,,
I*iniMonSetw,6)F*FbvFepFapFbpFcp%$domG6)%"EGF`p%#vrG%"dG%%flagGFfp%&d_minG6"F,C
)>8*Fbw>F/-Fjq6$-FE6$FQ-&Ffr6#%(SupportGFaq%$setG-%'printfG6$Q7Support:~%a~mono
mials|+F,-F`qF=>FCF/?(8'FbwFWF,1,&Fg[lFWFezFen9*C&>8&-%'selectG6$w,6#%"xGF,6$Fb
rFcrF,1-%'degreeG6$F4FjrT%F,F,6&FepF`sF_zFg[l6#FW6$7'FZFenF\pFjoFhn7'FZFenF\p"#
AFhnFC>FC-FE6$w,6#%"tGF,6$FbrFcrF,-FQ6#-&%"|irG6#%"*G6%F4%#~$GT#F,F,6$F^zF]\l6#
FW6$7'FZFen"#;"#FFhn7'FZFenFe^l"#=FhnFC>6$8(8)-F_v6'FCF\qFasF^x9)@$4F[_l>Fez,&F
g[lFWFWFW-Fa[l6$Q;Initial~set:~%a~monomials|+F,-F`qFUO6$F/FCF,F,F,6#""(6/Fby7'F
ZFenF\o"#TFjo7'FZFenF^oFdoFjo7'FZFenF^o"#WF\p7'FZFenF^oFjnFjo7'FZFenF^o"")Fd`l7
'FZFenF[`lFgoFjo7'FZFenF[`lF\oFjo7'FZFenF[`lF[oFjo7'FZFenF[`lFa`lF`o7'FZFen"#CF
hnFjo7'FZFenF^o"#[F\p7'FZFenF^oFfnFjuF,,
I-neighborMonsw,6%%"BG%#MBGFep6%%#nBG%"bG%"vG6"F,C&@$/F_qFbwOF\q>F/-F_\l6%%%typ
eG-FE6$FQ-FE6%-%"@G6$FQ<$Fj]l&F[^l6#%"/GF4F`s%)monomialG>F/-%*intersectG6$-%&mi
nusG6$F/F4F\q-Fbx6%/Fd[lFbwF\qF/F,F,F,6#F^o6(7'FZFen"#:FgnFhn7'FZFenF^o"#SF`o7'
FZFenFiuFesFju7'FZFenF^o"#qFjo7'FZFenF^oFhsFjo7'FZFenF^o"#GF\pF,,
I)genBasisw,6)F]zF`pFbvFepFapFbpFcp6/%$rndGFaal%#EBGFbalFdal%$nB1G%#bvG%"kG%"aG
%#nvG%#wtGF`r%"iG6"F,C,>F/,$-%%randG6#;Fbw"%+5#FWFgel>FC<">Fg[lF\q>8--F`q6#Fas-
%*randomizeGF,>Fez7#-%$seqG6$-%&roundG6#-F/F,/80;FWF]fl>8+-&%$maxG6#%&indexG6#-
FE6$w,Fb\lF,6$FbrFcrF,,&F4FW*&-F`^lF,FW$FgyFbwFenFWF,F,6$FfdlF/6#FW6$7'FZFenFiu
"#QFhn7'FZFenFiuFeuFhnFez>8,&Fas6#F_gl?(F,FWFWF,2Fg_lF`sC*-%'minus=G6$Fg[lFC>F[
_l-F^al6%FCFg[lFas>F]\l-%&unionG6$F4FC>8.w,Fb\lF,6$FbrFcrF,,*-Fbx6%-%#inGFh\lFW
FbwFW-Fbx6%-F]jl6$*&Fi\lFWF4FWT'FWFbwFW-%$addG6$*&&T)6#T+FW-Fg\l6$F4&T.FjjlFW/F
[[m;FWT/FW*&-T1F,FWF]hlFenFWF,F,62F]zF4F[elFehlFgdlF]\lFidlFezF^elF\glFepFasF\e
lF]flFfdlF/6#FW6$7'FZFenFcuFgyFhn7'FZFenFcuFiclFhn>F\_l-%%sortG6$7#-FQ6#F[_lw,6
$Fc\l%"yGF,6$FbrFcrF,1-F`^lF[q-F`^lFaqF,F,6$F]elFfil6#""#6$7'FZFen"#HF[oFhn7'FZ
FenF^]m"#NFhn>6$8/F\gl6$&F\_lFjsFW?(F,FWFWF,34-F]p6&7$-FQFUFc]mF^xF__lFj[l2F\gl
-F`q6#F\_lC$-%#+=G6$F\glFW>Fc]m&F\_l6#F\gl>FC<$F\^mFc]mOFCF,F,F,6#F[`l677'FZFen
"#6FgnFhn7'FZFenFjnFhsF\o7'FZFenFhnFguFjo7'FZFen"#\"#cFjo7'FZFen"#x"##*Fjo7'FZF
enF^oFcuF\p7'FZFenF^oFhnFjo7'FZFenF^oFjoFjo7'FZFenF^oFfnFjo7'FZFenF^oFd`lFa`l7'
FZFenF[`lFh^lF\p7'FZFenF[`lFboFjo7'FZFenF[`lF_]lFjo7'FZFenF[`lFgyFjo7'FZFenF[`l
F\alFjo7'FZFenF[`lFj`lFjo7'FZFenF[`lFcyFa`l7'FZFenF]_m"#<F\p7'FZFenF]_m"#@Fjo7'
FZFenF[`lFe`mFjo7'FZFenF^oF]_mFjuF,,
I*readBasesw,F$6%%#stG%$QBsGF)6"F,C)>F/FW>FC7">F]\l-F16$Q)bases/b_F,F4@$4-F96#F
]\lY6$F@F]\l?(F,FWFWF,0F/FbwC$>F/-%)readlineGFiam@$F]bm>FC7$F\^m-%&parseGF=-Fa[
l6$Q@%a~quotient~space~bases~loaded|+F,Fg_lOFCF,F,F,6#FW6.Fby7'FZFenFjnFe^lF\o7
'FZFenFh^l"#EFjo7'FZFenF^]m"#bFjoF]oFaoFj_mF``m7'FZFenF[`l"#eF`o7'FZFenFiuFa_mF
jo7'FZFenF^oFacmF\p7'FZFenF^oFcuFjuF,,
I,basisFinderw,6'F%>'%-deg_over_minG%*nonnegintGFbw>%%modeG%'APPENDG>'%0number_
of_basesG%'posintGFgy>'%-prime_numberGFddm"&\F$6.FcpF*FepFbpFapFbvF]zF`p%#BBGFa
alF)%#fdG6"F,C.>F/-%*prevprimeG6#,&F^xFWFWFW>F_glFaam>FfilFcam>6$FCF]\l-F"Faq>F
g[l-%%tdegG6#-FQFiam>F[_l-&Ffr6#%&BasisG6%FCFg[l/F]sF/>F\_l-F`q6#&-&Ffr6#%*Norm
alSetG6$F[_lFg[lFjs>6$FezF_gl-Fhy6)FCF\_lF]\lF[_lFg[lF/F\q>Fehl-Fbx6%/F`sF`dm-F
h`mFaqFaam>Fc]m-%&fopenG6$FfilF`s?(F,FWFWF,2-F`q6#FehlFasC$>F]fl-Fbdl6)FezF_glF
\_lF]\lF[_lFg[lF/@$4-%'memberG6$F]flFehlC%>Fehl7$-FQF]hmF]fl-%(fprintfG6%Fc]mQ$
%a|+F,-Fjq6$F]flFis-Fa[l6$Q0%d%%~completed|+F,-Fhfl6#,$*&F\hmFWFasFenFgy-%'fclo
seG6#Fc]mF,F,F,6#FW64FY7'FZFenFjnFioF\o7'FZFen"#o"#uFjo7'FZFen"#%)"$5"Fjo7'FZFe
nF^o"#IFjo7'FZFenF^oFj`lFjoF_`l7'FZFenF^oFgoFjo7'FZFenF^o"#gFjoFgjm7'FZFenF^oFi
uFjoFj_m7'FZFenF[`lFa_mFjo7'FZFenF[`lFcuF`o7'FZFenF]_mFf^lFjo7'FZFenF]_mF[oF\p7
'FZFenF]_m"#tF\p7'FZFenF^oFcyF\pF,,
I*writeGfanw,6$F%>FfdmFhdm6&FcpF*FepF[em6"F,C(>F/-F`em6#,&F\qFWFWFW>Fg[l-Fhgm6$
Q)gfan/igfF,%&WRITEG>FfemFgem>FC-%$modG6$-FE6$FG-Fjq6$FCF_[lF/-F\im6'Fg[lQ+Z/%a
Z%a|+%aF,F/F]\lFC-Fiim6#Fg[lF,F,F,6#FW6)FbyF]jm7'FZFen"#^"#!)FjoFdjmFh_m7'FZFen
F^oF^`lF\pFa[nF,,
I)readGfanw,6#'F)F'6'F`zF[am%"nGFcpF^el6"F,C*>F/F\w>FCFW>F]\lFbw@$4-F9FaqY6$F@F
4>FC-FabmFaq>Fg[l-Ffbm6#&FC6#;F^o,&-&%,StringToolsG6#%.FirstFromLeftG6$Q"[F,FCF
WF]uFW?(F,FWFWF,0FCFbwC$>FCFg^n@(5/FCQ#|fr|frF,/FCQ"|frF,C%>F/Fcq-Fb^m6$F]\lFW>
(FapF]\lFaam3F/0&FC6#FenQ"|hrF,>Fe`n7$-FQ6#Fe`n&FC6#F\u3F//Fh`nFj`nC$>Fe`nF\an>
F/F\wO6%Fg[l7#-Fefl6$-FE6$Ffbm(FapF[_l/F[_l;FWF]\l7#-Fefl6$-FE6$w,Fb\lF,6$FbrFc
rF,-Ffbm6#&F46#;FW,&-F`_n6$Q"+F,F4FWFenFWF,F,F,6#FW6$7'FZFenFb_m"$2"Fhn7'FZFenF
b_mFccmFhnF]bnF^bnF,F,F,6#FW64F\_m7'FZFenFjnF_]lF\o7'FZFenFj`lF\oFjo7'FZFen"#LF
ioFjoF]oFao7'FZFenF^oF\pFjo7'FZFenF^o"#fFjoFj_mF``mF\[n7'FZFenF]_mFiuFjoFb`m7'F
ZFenF]_mF\pFjo7'FZFenF]_mFioFjoF`dn7'FZFenF]_mFj`lFjo7'FZFenF^o"$C"FjuF,,
I(writeCMw,6$F%>FfdmFhdm6*%$Ws0GFcpF)F[emF*%#sFGFep%#WsG6"F,C7>FCFj[n>F]\l-F16$
Q+weights/w_F,F4>F/-%,readWeightsGFiam>F_gl-&Fa_n6#%.SubstituteAllG6%-Fhen6%-Fj
q6$F/F'Fe_nQ"(F,Q"]F,Q")F,>6$F[_lFezFgem>Fez-Fjq6$FezF'>F\_l-Fjq6$-Fe\n6$-FE6$F
GF[_lFCF'>Fg[l-Fhgm6$Q'cm/icmF,Fa\n-F\im6'Fg[lQ<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+F
,F_glFCFez-F\im6%Fg[lQ6f~=~openOut~"cm_%s";|+F,F4-F\im6$Fg[lQ<f~<<~toString(pp)
~<<~endl;|+F,-F\im6$Fg[lQ<f~<<~toString(vr)~<<~endl;|+F,-F\im6%Fg[lQ9for~i~from
~0~to~%a~do~(|+F,,&Fd[lFWFenFW-F\im6$Fg[lQ>f~<<~toString(Ws#i)~<<~endl;|+F,@%-%
$hasG6$F[_l^#FW-F\im6%Fg[lQ9R~=~ZZ/pp[I]/(I^2+1)%s,~F,&FezF`an-F\im6%Fg[lQ.R~=~
ZZ/pp%s,~F,F^in-F\im6$Fg[lQDMonomialOrder~=>~Weights~=>~Ws#i];|+F,-F\im6%Fg[lQ0
J~=~ideal(%s);|+F,&F\_l6#;F[]mF]u-F\im6$Fg[lQVG~=~gb(J,ChangeMatrix=>true);|+M~
=~getChangeMatrix~G;|+F,-F\im6$Fg[lQ>f~<<~toString(M)~<<~endl;|+);|+F,-F\im6$Fg
[lQ,f~<<~close;F,F^]nF,F,F,6#FW6:7'FZFenFfoFgnFhn7'FZFenFfnFa`lFjo7'FZFenF[oF_o
FjoFfjm7'FZFenF^o"$/"FjoFdjm7'FZFenF^oF\oFjoFgjmFdjm7'FZFenF^o"#hF\p7'FZFenF^oF
[oF\p7'FZFenF^oF`oF\pF_[oFecmF^[o7'FZFenF^oFjnF`o7'FZFenFe`m"#sF\p7'FZFenFd`lF
\alF\p7'FZFenF^o"#`F\pF``l7'FZFenF^oFb[oF\pF[alF`dlFa[nF,,
I'readCMw,F$6)F[amF)FcpFepF`rF[^nF^el6"F,C,>F/FW>FC-F16$Q'cm/cm_F,F4>F[_lFbw>F
\_lFbw@$4-F9FUY6$F@FC>F]\l-Ffbm6#-FabmFU>Fg[lFi\o?(F,FWFWF,F]bmC$>F/F[]o@&3F]bm
/&F/FjsF`fnC$-Fb^m6$F[_lFW>(%"TGF[_l&F/Fiin3F]bm/&F/6#;FWFgnQ'matrixF,C$-Fb^m6$
F\_lFW>(%#CMGF\_l-Fhen6%-Fhen6%&F/6#;FjnF]uF_`nFe_nFj`nFafn-Fa[l6$Q;%d~change~m
atrices~loaded|+F,F\_lO6%F]\l7#-Fefl6$-%%wdegG6$7#-Ffbm6#(Fi]oFezFg[l/Fez;FWF[_
l7#-Fefl6$)-%'MatrixG6#7#-FE6$Ffbm(Ff^oFez%#%TG/Fez;FWF\_lF,F,F,6#FW647'FZFenFj
nFgnFhnF]cm7'FZFenFh^lFguFjo7'FZFenFacmF][oFjo7'FZFen"#j"#pFjoF]oFao7'FZFenF^oF
f^lFjo7'FZFenF^oF^]mFjoFj_mF``mF\[nFb`mF][nFb`m7'FZFenF]_mFjjnFjo7'FZFenF^oFguF
\p7'FZFenF^o"#**FjuF,,
I(getTordw,6$%#gbG%#lmG6.FepF\elF^elFjdl%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG
%$solG%(weightsG%"gG6"F,C,>F/7#-FQ6#-FTFaq>FCFd[l>F[_l/7#-%"$G6$FbwFC%%NULLG>F
\_l7#-Fefl6$(F_zF]\l/F]\l;FWFC>Fez-FE6$w,6#%"zGF,6$FbrFcrF,-FE6$w,Fb\lF,6$FbrFc
rF,-FE6$w,6#F^zF,6$FbrFcrF,-Fg\l6$FjrF4F,F,6$Fc\lF46#FW6$7'FZFenF\oF[oFhn7'FZFe
nF\oFhsFhnF`^lF,F,6$FepF`^l6#FW6$7'FZFenFj`l"#aFhn7'FZFenFj`lF_cmFhn-Fjq6$F4Fis
F,F,6$FepF/6#FW6$7'FZFenFc`mF`[nFhn7'FZFenFc`m"#>FhnF4>F_gl-FE6$w,Fb\lF,6$FbrFc
rF,-FE6$w,F]eoF,6$FbrFcrF,F_eoF,F,Faeo6#FW6$7'FZFenFj`lF[dlFhn7'FZFenFj`lFf^lFh
nF`^lF,F,F^fo6#FW6$7'FZFenFc`mF[oFhnFbfoF\q>Fehl<#-Fefl6$-FQ6#-FE6$w,Fb\lF,6$Fb
rFcrF,1FW-FejlFh]lF,F,6$FbboF\_l6#FW6$7'FZFenFj`lFguFhnF[fo-%%subsG6$F[_l7#-Fef
l6$,&&F_glF_]nFWFc]mFen-F]jl6$Fc]m&FezF_]n/Fg[l;FWF_q>F]fl&-&%-OptimizationG6#%
)MinimizeG6&-FejlF_^mFehl/%+depthlimitGF[dl/%'assumeGF]dm6#F[]m>Ffil-Feho6$F]fl
F\_l6$Ffil-Fg_o6$FfilF/F,F,F,6#F[]m6-Ffjn7'FZFenFjnFesF\o7'FZFenF`]mFdoFjo7'FZF
enF]dn"#zFjo7'FZFen"#")"$3"Fjo7'FZFenF^o"#yFjo7'FZFenF^oFjuFjo7'FZFenF^oFccnFjo
7'FZFenF^oFfsFjo7'FZFenF^oFadlFjo7'FZFenF^oFejmF\oF,,
I,readWeightsw,Fh]n6$F[amF[en6"F,C(>F/FW>FCFaam@$Fb^nYFe^n?(F,FWFWF,F]bmC$>F/Fg
^n@$F]bm>FCFdbm-Fa[l6$Q:%a~weight~vectors~loaded|+F,Fg_lFCF,F,F,6#FW6-FYF]cm7'F
ZFenFh^lFeuFjoF]oFaoFj_mF``m7'FZFenF[`lFb_mF`o7'FZFenFiuF[oFjoF[al7'FZFenF^oF`y
Fd`lF,,
I-writeWeightsw,6'F%>F_dmF`dm>'%2number_of_weightsGFddmFgy>FfdmFhdm>'%+rand_ran
geG7$FddmFddm7$"$+#"$+)60Fcp%#GsG%$LMsG%#WWG%%gffnGF)F[emF^el%"WGF*FepFfdlFbpFa
p6"F,C&>F/-F`em6#,&FasFWFWFW>F[_l-F16$Q)gfan/gf_F,F4>F\_lF`en@%-F9Fa\mC(-Fa[l6#
QJGenerating~weight~vectors~from~Gfan~file|+F,>6%F/FCF]\l-Ff]nFa\m>Fg[l7#-Fefl6
$&-F[bo6$&FCFghl&F]\lFghlFjs/F_gl;FWFg_l>Fez-Fhgm6$F\_lFa\n?&FehlFg[lFcq-F\im6%
FezF^imFehl-Fiim6#FezC+-Fa[l6#Q5Gfan~file~not~found|+F,-Fa[l6$QEGenerating~%a~r
andom~weight~vectors|+F,F`s>6$F]flFfilFgem>Fc]m-Fdel6#;&F^xFjs&F^xF^joF`fl>Fg[l
-Fbx6%/F\qF`dm-FeenF_^mFaam>Fez-Fhgm6$F\_lF\q?(F,FWFWF,2-F`qF_]nF`sC&>F\gl-Fg_o
6$7#-Fefl6$-Fc]mF,/F_gl;FW-F`q6#FfilFfil>81-F_fm6%F]flF\glFcfm>Fehl&-F[bo6$F_cp
-&Ffr6#%0LeadingMonomialG6$F_cpF\glFjs@$4-Fehm6$FehlFg[lC%>Fg[l7$-FQF_]nFehlFd`
p-Fa[l6$Fcim-Fhfl6#,$*&FabpFWF`sFenFgyFf`pF,F,F,6#FW6>FhclF]jm7'FZFenFacm"#$)Fj
o7'FZFen"#')"$9"FjoF`[o7'FZFenF[`lFccmF\p7'FZFenF[`lF`]mFjo7'FZFenF[`lF]dnFjo7'
FZFenF[`lFadlFjo7'FZFenF[`lFc]nFd`l7'FZFenF_]lFjoF\p7'FZFenF[`lFe^lF\p7'FZFenF[
`lFboF\p7'FZFenF[`lFb[oF\p7'FZFenF[`lFhsFjoFg`l7'FZFenF[`lFc`mF\p7'FZFenF[`lFdo
Fjo7'FZFenF[`lFf^lFjoFa`m7'FZFenF]_mF]dnFjo7'FZFenF]_mFccmFjo7'FZFenF]_m"#kFjo7
'FZFenF]_mFc`mF`o7'FZFenFiclF\oFjo7'FZFenFiclFhnF\p7'FZFenFiclFjjoF\pFfepF,,
I)saveDataw,6-F%'%#mnGFg]p'%#spG%(numericG'FcpFddm'Fep<$FisF_[l'%#avGF[cl'Fbp%3
ShortMonomialOrderG'%#QBGFis'%'shiftsGFis'%%polsGFis'%$stdG%(booleanG6'F)F[em%$
mn0G%$sp0GF`z6"F,C&>F/-Fbx6%9.-F16$Q-optim/o_std_F,F4-F16$Q.optim/o_nstd_F,F4>F
[_lF\w@%F8C'>FC-Fhgm6$F/%%READG>F]\l-Ffbm6#-FabmF=>Fg[lFdip@$52&F\qFjs&F]\lFjs3
/F[jpF\jp2Fg[lF`s>F[_lFcq-FiimFU>F[_lFcq@$F[_lC%>FC-Fhgm6$F/Fa\n-F\im6.FCQ>%a|+
%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%aF,F\qF`sFas-Fjq6$F^xFisF__lFj[l9+9,9-FaamFajp
F,F,F,6#F]_m61F\_m7'FZFenFjnF_[pF\o7'FZFen"#&*F][pFjoF`[oF\fp7'FZFenF[`lFesFjoF
e[q7'FZFenF[`lF\epF`o7'FZFenFcaoF_oFjoFfep7'FZFenF[`lFcfoFjoF`[oFcep7'FZFenF[`l
FcdnF\pFfepF,,
I)readDataw,6$F%Fjgp6.F)F[emFifpF[gpFcpFepFagpFbpFegpFggpFigp%$xE0G6"F,C1>F/-Fb
x6%F\qFfhpFihp@$F7YF?>FCF`ip>F]\lFdip>Fg[lFdip>F[_lFdip>F\_lFdip>FezFdip>F_glFd
ip>FehlFdip>F]flFdip>FfilFdip>Fc]mFdipFajp6,F]\lFg[lF[_lF\_lFezF_glFehl-FE6$FIF
]flFfilFc]mF,F,F,6#F[]m63F\_mFb[qF]oFaoFjjmFeaoFeaoFeaoFfaoFeaoFfaoFeaoF[[oFfao
Fc[pFa[n7'FZFenF^oFcaoF\oF,,
I,eigenSolverw,6#'F*-Fis6#%(polynomG6/Ffdl%%fB2CGFepFbpFapFaalFbvFagpF^zFi]o%"V
GFfp%#SrG6"F,C1>F]\lF\co>Fg[lFiem>F/,$-Fdel6#;!%+5FgelFhel>FCw,6%'%"fGF]^q'FepF
is'FaalFisFd]l6"F,C$>F/-%&tableG6#-%$zipG6%w,6$F[elFealF,6$FbrFcrF,/F\qF4F,F,F,
6#F[]m6$7'FZFenFadlFbhlFhn7'FZFenFadlFhsFhn7#-%'coeffsG6%F4F\q.F`r7#F`rO-FE6$w,
6#FealF,6$FbrFcrF,-Fbx6%-%)assignedG6#&F`^lFaqFeaqFbwF,F,6$Fe]lF/6#FW6$7'FZFenF
h^lFa_mFhn7'FZFenFh^lF\pFhnF`sF,F,F,6#F^o6%7'FZFenF]_mFfoFhn7'FZFenFcuF_jmF\o7'
FZFenF[`lFe[oFju@$4-F_bl6$F4F[^qYQQThe~case~of~non-polynomial~system~is~not~han
dledF,>F[_l-F_fm6$F4Fg[l>F\_lFgfm>FezF^^m>F_gl-Fejl6$*&FehlFWFjflFW-F]jl6$FehlF
]\l>F]fl-&Ffr6#%5MultiplicationMatrixG6'F_glF\_l-Fg_q6#-&F[^l6#%"=G6%F\_lF_^l7#
-Feco6#;FWFezF[_lFg[l>Ffil&-&Fbt6#%-EigenvectorsG6#-%&evalfG6#F]flF^jo>Ffil-Fhb
l6%FfilF_^l-%".G6$-%'VectorG6$Fez/%%fillGFW&FfilFjs>Fc]m-F`eq6$-Fd`o6#-FE6$w,F]
eoF,6$FbrFcrF,-F[[m6%-Fer6%F4F`^lFi\lFcjlFijlF,F,6,FapF[_lFbpFg[lFepF]\lFaalF\_
lF_^qFC6#FW6$7'FZFenFcfoF^dlFhn7'FZFenFcfoF_]lFhnF]\lFfil>F\gl-%#ReG6#&Fc]m6$F^
u-F_\l6$w,6#%"cGF,6$FbrFcrF,-%'andseqG6$-F\t6$&F`^l6$F^elF4%%realG/F^el;FW-FQ6$
7$FWFWF`^lF,F,6$FfpFc]m6#FW6$7'FZFenFeuF^dlFhn7'FZFenFeuFf^lFhn7#-Feco6#;FW-FQ6
$7$FWF[]mFc]mOFb]mF,F,F,6#FW63FY7'FZFenF\pFguFjo7'FZFenF`oFcoFjo7'FZFenF^oFesFj
o7'FZFenF^oFfoFjo7'FZFenF^o"$."F`o7'FZFenFbhl"#%*FdoF[[o7'FZFenF^oFbhlFjo7'FZFe
nF^oFe^lFjo7'FZFenF^oFjcnFjo7'FZFenF^oF`jmFjo7'FZFenF^oF[oFjoFg_m7'FZFenF^oF\[p
Fjo7'FZFenF^o"#$*Fjo7'FZFenF^oFiclFjuF,,
I$srtw,6$'Ffal<%FceqFisF_[lFbgpF,6$FbrFcrF,-F]\m6$F4w,Fc\mF,6$FbrFcrF,-&Ffr6#%*
TestOrderG6%F\qF4FjrF,F,6$FbpF\q6#F[]m6$7'FZFenF`fp"$-"Fhn7'FZFenF`fp"#rFhnF,F,
F,6#F[]m6$7'FZFenFgnFgiqFhn7'FZFenFgnFacmFhnF,,
I%suppw,6$F`_qFepF,6$FbrFcrF,<#-FQ6#-F\[l6$-FGFaqF\qF,F,F,6#F[]m6$7'FZFenF[`l"#
dFhn7'FZFenF[`lFc`mFhnF,,
I%Suppw,6$F*FepF,6$FbrFcrF,<#-FQ6#-FE6$FQ-F\[l6$F4F\qF,F,F,6#F[]m6$7'FZFenF[`lF
ccmFhnF[]rF,,
I,poly2matrixw,F^]r6$Fi]oFaal6"F,C%>F/-FE6$w,6#%#plGF,6$FbrFcrF,-Fg_q6#-Fj_q6%w
,F]`qF,6$FbrFcrF,F_`qF,F,F,6#F[]m6$7'FZFenFesFguFhn7'FZFenFesFbhlFhn7#-Ff`q6%F4
Fjr.Fifp7#FifpF,F,6$FepF\q6#FW6$7'FZFenFh^lF_oFhn7'FZFenFh^lFe`mFhnF4>FC7#-FQ6#
-F\]rFf]rO6$-Fd`o6#-FE6$w,Fd]lF,6$FbrFcrF,-FE6$w,F^aqF,6$FbrFcrF,-Fbx6%-Fcaq6#&
FjrFaqF_arFbwF,F,6$Fe]lF46#FW6$7'FZFenFadlF]dnFhn7'FZFenFadlFejmFhnF`^lF,F,6$Fa
alFC6#FW6$7'FZFenFe`mFcaoFhn7'FZFenFe`mFiuFhnF/-FceqFUF,F,F,6#F[]m6&FY7'FZFenFj
nFjjoF\o7'FZFen"##)"$0"Fjo7'FZFenF^oFjjoFjuF,,
I/permuteColumnsw,6%F`pF`^q%#V1G6#Fifp6$FbrFcrF,&F46$F^u7#-Fefl6$-&%*ListToolsG
6#%'SearchG6$F/F\q-F]jl6$F/F`sF,F,F,6#F^o6&7'FZFenFc`mF^epFhn7'FZFenF^]mF`]mFd`
l7'FZFenFc`mFadlFhnFhcrF,,
I)sparsityw,6#'F`pFd`o6#%&numzrG6"F,C$>F/-F`q6#-F_\l6%F\dqF\foFbwO*&F/FW-%$mulG
6#-FQ6$FWF4FenF,F,F,6#FW6%F\_m7'FZFenFjnFacmF\o7'FZFenF^oFadlFjuF,,
I(matrixSw,6'Faal%#B0GFapFbpFcp6%Ffp%#V0GFbv6"F,C&>F]\lF_q@$0-F`qF[qF]\lYQIlist
s~B0~and~B~must~have~the~same~lengthF,>Fi_l-Fgq6$-FE6$w,F^aqF,6$FbrFcrF,FdrF,F,
F]x6#FW6$7'FZFenFadlF\[pFhnFdarF4Ffv@%/-FQ6$FWFCF]\lO-Fbbr6%F/FC-FceqF[qYQ=fail
ed~to~construct~matrix~SF,F,F,F,6#F`y6*Ffjn7'FZFenFe^lF^]mFjo7'FZFenF^oFbjmF`o7
'FZFenFf^lF_oFdo7'FZFenF^o"#(*FjoF`[o7'FZFenF[`lFgoFju7'FZFenF[`lFjoFdoF,,
I*quotientsw,6&FhboFapFbpFcpF,6"F,C$-Fer6'F4F\qF`s.%"QG/F]sFasOFehrF,F,F,6#F`u6
%Fby7'FZFenF^oFccmF\pFg`mF,,
I-monPartitionw,6'Fagp%#GrGFbpFcp>FegpFaam6-FeerFaal%#aBG%"RG%#B2G%#RBGFap%#nGG
Fi]oFfpF^el6"F,C->F/&-Fifm6$F\qF`sFjs>FC-Fjq6$-Fbx6%/F^xFaamF/F^xF_[l>F]\l-Fj]l
6%F4F_^lFC>Fg[l-Fcjq6$-Fjq6$-Facl6$F]\lFCFisF`s>F_glFabp>F[_l-Fhbl6%-F^clF[[sF_
^lF4>FC7$-FQ6#-Fcjq6$-Fjq6$-Facl6$FCF[_lFisF`s-FQ6#-Fcjq6$-Fjq6$F[_lFisF`s>6$F
\_lF]\l6$7$FbdpF\^mFcjr@%Fajr>Fehl-Fccq6(F4FC-Fg_q6#-%'EquateG6$FC7#-Feco6#F_`p
F\qF`sFfhrC%>Fehl-Fccq6(F4F/-Fg_q6#-F\]s6$F/7#-Feco6#;FWFd[lF\qF`sFfhr>F]fl-Fbe
r6'FCF/F\qF`sFas>Fehl-Fbx6%0FasFbw-Fe\n6$-F`eq6%F]flFehl-&Fat6#%(InverseG6$FasF
]flFas-F`eq6%F]flFehl-&Fbt6#%.MatrixInverseGF[eq>Fez-Fjq6$,&-FceqF_]nFW-F`eq6$&
Fehl6$;FWF_glF^uFjarFenFisO6(F]\lFCF\_lFehlFez-Fd`o6#7#-Fefl6$-F]hr6&&FezF]cpF
\qF`sFas/FfilF\`sF,F,F,6#F`y62Fhcl7'FZFenF^oF[dlFjo7'FZFenF^oFguFjoFi_mFh_m7'FZ
FenF^oFiclFjoFfao7'FZFenF^oF\epFjoF_dlF`[o7'FZFenF[`l"$6"Fjo7'FZFenF[`lF_epFjo7
'FZFenF[`lFioFjo7'FZFenF[`l"$7"Fjo7'FZFenF^oFb_mFjoFabrF,,
I)matrixHiw,6&F*FapFepFcp62%*undetPolyG%#pvG%#nFGFeir%#uHG%%leqsGFfboF^el%#dFG%
#dGGF_zFaz%"hG%"jG%"pGFjdl6"F,C)>FC-FejlFgv>F]\lF_q>Fg[lF]fr>Fehl-FE6%Fg\lF4F`s
>F/w,6&FepFjasF_zFabs6#%%monsG6"F,C%-Ff`q6%-FG6#,&FWFW-Fejl6$)F\qF`^l/F`^l;FWF`
sFWF4.F/>F/7#F/-Fejl6$*&&F/6#Fi\lFW&%#_vG6$FasFi\lFW/Fi\lF\^sF,F,6&Fbbs82Fjdl83
6#F`u6&7'FZFenFe^lFfoFhn7'FZFenF[`lFj\rF\p7'FZFenF[`lF\pFjo7'FZFenF[`lFa`lF\p?(
F_glFWFWFg[lFcqC%>6$Fc]mF]fl6$Fbw-FE6$w,Fb\lF,6$FbrFcrF,-Fbgl6$FbwF4F,F,F,6#FW6
$7'FZFenFf^lFbhlFhn7'FZFenFf^lF^]mFhn,&7#-Feco6$-Fg\l6$&F\qFghlF`sF]\lFWFehlFen
?(FfilFbwFWF,1,&FfilFWFc]mFenFbwC&>F[_l7#-Fefl6$-F/6&F`sFC,&&F]fl6#F_cpFWFfilFW
F_cp/F_cpF_bn>F\_l<#-Ff`q6$-FG6#,&FgfsFen-Fejl6$*&&F[_lFdgsFW&F4FdgsFWFegsFWF`s
>Fez-%'msolveG6$F\_lFas@$/-F`q6#<#FezFbw>Fc]m,&FfilFWFWFW>&F\glFghl-Fe\n6$-FE6%
-Febl6$FGFIF[_lFezFasO-F^w6#-Fefl6$-&Fceq6#%$rowG6#F^is/F_gl;FWFg[lF,F,F,6#F`u6
2F\_m7'FZFenF\pFhsFjo7'FZFenFboFa_mFjo7'FZFenFjuF`fpFjo7'FZFenFfsFcjmFjoFeiqFc`
l7'FZFenF[`lFh[rFjo7'FZFenF[`lFcyFd`l7'FZFenF]_mFcaoFjo7'FZFenF]_mFb[oFjo7'FZFe
nF]_mFjcnFjo7'FZFenF]_mFe[oF`o7'FZFenFjcnF`oFjoFg`l7'FZFenF^oFguFjuF,,
I*matrixHniw,6(F*Fap%"CGFf^oFepFcp6-%,undetPolyniGF[bsFeir%#H0GF\bsF]bsFfbo%%pa
rsGF^elFabsFjdl6"F,C+>FCF_q>F]\lF]fr>F/w,6&F`bsFepF^elFabsF_cs6"F,C%-Ff`q6%F4F
\qF]ds>F/F_ds-Fejl6$*&&F/6#F`^lFW&Ffds6%F`sFasF`^lFW/F`^lF\^sF,F,6$FjdlFfil6#F`
u6&7'FZFenFh^lFfoFhn7'FZFenF[`lF^]mF\pF`es7'FZFenF[`lF[oF\p>Fg[l-Fe\n6$-FE6$FG-
F`eq6$F`sFasF__l>F[_l-Fd`o6%F]\lFCw,6$F^elFabsF,6$FbrFcrF,-Fcjl6&&F`^lFf]rF[sF4
F\qF,F,6(Fe[tFg[lFepF^xFd[tF/6#F[]m6$7'FZFenFj`l"#iFhn7'FZFenFj`lFejmFhn>F_gl<#
-Fefl6$&%#_uGF]hm/Fehl;FW-F`q6#-Facl6$-FTFa\mF^x>F\_l-FE6%Ff`q<#-Fefl6$-Fe\n6$-
FG6#,&&F\qF]hmFen-Fejl6$*&&F[_l6$FehlF]flFW&F4F[eqFW/F]flF^doFWF__l/FehlF_bnF^x
>Fez-Fdhs6%F\_lF_glF__lO-Fe\n6$FaisF__lF,F,F,6#Fgn6,Fby7'FZFenF_]lFhsFjoFdjsFei
qF\jq7'FZFenF^oFcaoFjoFdas7'FZFenF^oFd[qFjoF[[oF^[tF,,
I*syzModulew,6''F*Fgjq'FapFis'%"AGFd`oFbgp'FcpF]dm6,F[bsFeir%"eG%"LG%#LtGF`pFfp
FaalF^elFabs6"F,C.>F/F_q>FCF]fr>F]\l-Fefl6$-Fceq6$FC<#/FehlFW/FehlF^do>Fg[l7#-F
efl6$7#-&Ffr6#%,LeadingTermG6$F_`tFasFjbt>F[_l-FE6$w,Fb\lF,6$FbrFcrF,*&&F4FjsFW
&F4F^joFWF,F,F,6#FW6$7'FZFenFcuFj`lFhnFj[mFg[l>F\_l-Fd`o6$FCw,F\^tF,6$FbrFcrF,*
&-%$lcmG6$&FeaqF^jo&&F`^lF[qF^joFW&Fi\lFaqFenF,F,6&F]btFg[lF^btF[_l6#F[]m6$7'FZ
FenFcfoFe[oFhn7'FZFenFcfoF_cmFhn>Fez7#-Fefl6$-Fefl6$,(*&&F\_lFd`tFW&F]\lF]hmFWF
W*&&F\_lFfhmFW&F]\lF[eqFWFen-F^w6#-F]hr6&z'6&FjetF]ftF_`t&F\qF[eq[[[\[[[[[\[[mF
W\[[[[[\[[[[[mFenF\qFasF^xFen/F]fl;,&FehlFWFWFWFCFjbt>Fez)-Fd`oFg`pFj`o>F_gl-Fd
`o6#7#-Fefl6$-F]hr6&&F4F]hmF\qFasF^x/Fehl;FWF/>Fez-FE6$FG-F^w6$-F`eq6$FezF`s,&-
&Fbt6#%/IdentityMatrixGF=FW-F`eq6$F_glF`sFen@$Fdx>Fez-Fe\n6$FezF^xO&Fez6$-%'rem
oveG6$w,6#F^elF,6$FbrFcrF,-&%+ArrayToolsG6#%'IsZeroG6#&F`^l6$F4F^uF,F,6$FfpFez6
#FW6$7'FZFenFcfoFa_mFhn7'FZFenFcfoFe`mFhn7#-Feco6#;FW-FQ6$FbhqFezF^uF,F,F,6#F`y
60Fby7'FZFenFjnFe`mF\oFi`lFjiq7'FZFenF^oFccmFjoFc[p7'FZFenF^oFjeoFjo7'FZFenF^o"
$A"Fjo7'FZFenF^oFh^lFjoF\dn7'FZFenF^oFcoFjoFjcl7'FZFenFcfoFesFjo7'FZFenF^o"#wFj
uF,,
I+matrixHsyzw,6(FfatFgat'Fb[tFd`oFhatFbgpFjat6$Ffp%&ThetaG6"F,C%>F/-Fcat6'F4F\q
FasF^xF__l>FC-Fd`o6%-FQ6$FbhqF`s-FQ6$FbhqF/w,F\^tF,6$FbrFcrF,&Fe]lFf]rF,F,F,6#F
[]m6$7'FZFenF`oFj\rFhn7'FZFenF`oFc]nFhnO-Fe\n6$-FE6$FG,&Ff]tFW-F`eq6$FCF/FWF__l
F,F,F,6#Fgn6&Fbu7'FZFenF^oF`]mFjoFhjt7'FZFenF^oFjoFjuF,,
I,fixTemplatew,6'%'admonsGF*Fep%$monGFdir60F[bs%%monFG%&admonGF^elFabsFehrF`z%#
xFGF`pFgerF]zF`^q%%mon1GFifp6"F,C.>F/F]fr>FC-FE6$w,6#F`_qF,6$FbrFcrF,-F]\rFh\lF
,F,6$FepF`s6#FW6$7'FZFenFhnFc]nFhn7'FZFenFhnFbhlFhnF\q>F]\l7#-Feco6$FjelF/?(Fg[
lFWFWF_qFcqC%>FezF\w?(F[_lFWFWF/FcqC$>F\_l-FE6$w,6#%#mfGF,6$FbrFcrF,-Fbx6%-%'di
videG6%&FjrFddsF4.%"qGFf`uFgcoF,F,6&Fi]uF4F^elFg[l6#FW6$7'FZFenF\pF`fpFhn7'FZFe
nF\pFiuFhn&FCFa\m@$0F\_lFjelC%>&F]\lFa\m<$Fe]m-FQ6#Faau>FezFcq[@$4FezYQ;failed~
to~correct~templateF,>F\gl7#-Fefl6$-Fjq6$-Fcil6$-Fjq6$&FasFa\mF_[lFaauFceq/F[_l
Ffgt>F_gl7#-Fefl6$-Fefl6$-FG6#*&&F\qFa\mFWF_cpFW-F]jl6$F_cp&F\glFa\mFfbu>Fd`t-F
gqFdht>Ffil-Facl6$-Fjq6$F]flF_[l-Fjq6$F^xF_[l>Ffil-Fcjq6$7#-FQF]cp-Fjem6#-FQFgv
>Fc]m-F^w6$Fadu-FQ6#F^x-Fa[l6#Q0Template~fixed|+F,O6&F\glFehlF]flFc]mF,F,F,6#F`
y68FYFgjt7'FZFenFj`lFacmFjo7'FZFenFccmF_oFjoFc`lF`esFhjs7'FZFenF]_mF`jmFjo7'FZF
enF]_m"#))F`o7'FZFenFf^lFccmFjo7'FZFenF][oF`[nFjo7'FZFenF_oFbwFe[o7'FZFenF[`l"#
nF`o7'FZFenFj`lFccmFdoF^[pF\dnFdiqFgjmFd]u7'FZFenF^oF_]lFjoF`dl7'FZFenF^oFj`lFj
uF,,
I2constructTemplatew,6&%"HGF*FepFdir6+F[bsFj]uF^^uF`pFgerF]zF`^qFabsFifp6"F,C+>
F/F]fr>FC-Fbx6%-F_bl6$F4Fd`o7#-Fefl6$-F^w6#-FQ6#-F\]r6$-Fjq6$&F46$F^uF_glFisF`s
/F_glFfgtF4>F]\l7#-Fefl6$-Fefl6$-FG6#*&FgfsFWFehlFW-F]jl6$FehlF\`pFhgu>6$Fg[lF[
_l-Fgq6$F]\lF`s>F\_l-Facl6$-Fjq6$F[_lF_[l-Fjq6$FasF_[l>F\_l-Fcjq6$7#-FQF_^mFbdu
>Fez-F^w6$Fciu-FQF_fl@$0-FQ6$FWFez-FQ6$FWF[_lC$-Fa[l6#Q8Template~is~incomplete|
+F,>6&FCFg[lF[_lFez-Ff]u6'-Facl6$-Fjq6$FezF_[lF[iuF\qF`sFCFas6%FC-Fbbr6%Fg[lF[_
lFezFezF,F,F,6#F`u6.7'FZFenF\pFgnFhnFgjt7'FZFenF^oFe_mFjoFhjtFdiqFgjmFd]uF\fuF`
[o7'FZFenF[`lF[dlF\p7'FZFenF[`lFe_mFjo7'FZFenF^oF`]mF\oF,,
I-adjustParamsw,6'F*FafuFdirFepFcp65F[bsFeir%#H1G%#LmG%%colsGF]btFj]uFgerF]zF\b
t%#smG%#rmG%#npG%#ssG%$prmGF]bsFfboFabsF^el6"F,C3>F/F_q>FC-FQ6$FbhqF\q>F]\lF\q>
Fg[l-Fefl6$-Fgq6$-Fjq6$&F\q6$F^u85FisFas/F`]vFfgt>F[_l7#-Fefl6$-F]it6$w,Fb\lF,6
$FbrFcrF,-%+membertypeG6$Fddm-Fjq6$&&F`^l6#,&Fi\lF[]mFenFW6$F^uF4FisF,F,6&Fi[vF
g[lFabsF`]v6#FW6$7'FZFenFiuF`[uFhnFchl7#-Feco6#;FW-FQ6$F^iq&Fg[l6#,&F`]vF[]mFen
FWFa]v>6$F\_lFez6$7#-Fefl6$&F^_v6$F^u&F[_l6#F`]vFa]v7#-Fefl6$&&Fg[l6#,$F`]vF[]m
6#Fi_vFa]v>Ffil7#-Fefl6$-FE6$w,Fd]lF,6$FbrFcrF,-F]\r6$-FG6#*&Fd`uFWF4FWF^sF,F,6
(F*F4FabsF`]vFepFas6#FW6$7'FZFenFh^lFgoFhnFjaq&FezFj_vFa]v>F_gl-Fjq6$-FE6$FQ-FE
6%-Febl6$FQFjqFfilF_[lF_[l>Fehl-Fjq6$-Facl6$F_gl-Fjq6$F`sF_[lFis>Ffil-FceqF]cp>
Fc]m-FE6$w,6#F\btF,6$FbrFcrF,-F_\l6$w,F`itF,6$FbrFcrF,-Fehm6$FjrF\etF,F,6&F\btF
4F[\vF`^l6#FW6$7'FZFenFiuF^`lFhnFchl<#-Feco6#;FW-FQ6$FWF`^lF,F,6$F[\vFfil6#FW6$
7'FZFenFcuFijmFhnFj[mFehl>F\gl7#-Fefl6$-%"+G6#-Fefl6$-F`q6#-F_\l6%FhhnFc]m&&Fc]
mFj_v6#86/Faev;FW-F`q6#F_ev/F`]v;FW-F`qFjim>F_cpw,6&F^elFabsF\\vF]\vF,6$FbrFcrF
,52-F`q6#&F`sF[q-F`q6#&F`sFaq3/FbfvF_fv2&FasF[q&FasFaqF,F,F,6#F`u6$7'FZFenFjnFg
yFhn7'FZFenFjnFj`lFhn>Fjds-F]\m6$7#-Feco6#;FWF\hmw,F\^tF,6$FbrFcrF,-Fcjl6&F4F\q
F`^lFi\lF,F,6(F\\vFc]mF]\vF\glF^\vF_cp6#F[]m6$7'FZFenF\oFjeoFhn7'FZFenF\oFbhlFh
n>Fehl&Fehl6#Fjds?&F]flFehlFcqC+>Fg[l-Fefl6$-Fgq6$-Fjq6$&F]\lF_]vFisFasFa]v>Fb_
v6$7#-Fefl6$F^_vFa]v7#-Fefl6$F_`vFa]v@$/-F`q6#-FTF_^mFbw[>Ffil7#-Fefl6$-FE6$w,F
d]lF,6$FbrFcrF,F[avF,F,F`av6#FW6$7'FZFenF_]lFdoFhn7'FZFenF_]lFj`lFhnFdavFa]v>Fc
]m-FE6$w,Fb\lF,6$FbrFcrF,<#-&F_cr6#%*SearchAllG6$FW-FE6$w,6#Fd\mF,6$FbrFcrF,-F`
q6#-F^cl6$F4<#F`^lF,F,6$F\btF`^l6#FW6$7'FZFenFa_mFb[oFhn7'FZFenFa_mFc]nFhnF4F,F
,6$F\btF]fl6#FW6$7'FZFenFc`mF_[pFhnFbfoFfil>F[es<#-Fefl6$-FQ6#-FE6$w,6#FjdlF,6$
FbrFcrF,-FQ6#-Fjq6$&&F`^lFddsFc^vF_[lF,F,6&F]btF\_lFabsF`]v6#FW6$7'FZFenFf^lFcc
mFhnF`fsF_evFa]v>84-Fdhs6$F[esF^x@$/-F`q6#<#Fi]wFbw\>F]\l-Fe\n6$-FE6%FcisF]\lFi
]wF^x-F^fu6&F]\lF4FasF`sF,F,F,6#F`y6?FhclFgjt7'FZFenFj`lF^`lFjo7'FZFenFa`lFc]nF
jo7'FZFenF^oF`fpFjo7'FZFenF^o"$<"Fjo7'FZFenF^oFbjmFjoF][u7'FZFenF^oFacmFjoF^jqF
\[uF]_w7'FZFenF^o"#*)Fjo7'FZFenF^oFgyFjoFa_w7'FZFenF^oFcuFjoFc`l7'FZFenF[`lFdao
Fjo7'FZFenF[`lFcoFjo7'FZFenF[`lFgoF`o7'FZFenFjcnFbwFe[o7'FZFenF[`lF^dlFjo7'FZFe
nF[`lF\epFjo7'FZFenF[`lF_[pFjo7'FZFenF[`lF^]mFjo7'FZFenF[`lF^`lF`o7'FZFenF^]mFb
wFjeo7'FZFenF[`lF`oFjo7'FZFenF^oFhnF\pF,,
I4isActionMatrixFoundw,6('Fi]oFd`oF]dr'FairFisFb_q'FeirFddmFjat6(%#tMG%#T1GFbvF
`r%"rGFjdl6"F,C'>F]\lF^fl>Fg[l,&F]\lFWF^xFen>F/-Fe\n6$-%*GaussjordG6$F\q.F[_lF_
_l>FC-Fe\n6$-F^w6$,$&F/6$;,(F[_lFWF^xFenFWFWF[_l;,$F]\lFenFenFen-Fd`o6%Fg[lF]\l
<#-Fefl6$/6$,(Fg[lFWF\_lFenFWFW-F^cr6$&F`s6#,$F\_lFenFasFW/F\_lF`jsF__l-&Fbt6#%
&EqualGFdilF,F,F,6#Fgn6(7'FZFenF_]lFgnFhn7'FZFenFc`mFejmFjo7'FZFenFjcnFgoFjoF\j
q7'FZFenF^o"$;"Fjo7'FZFenF^oF^]mF\pF,,
I/SchurReductionw,6(F]dr'F`^qFceqFggp'%#nEGF]dmF]gpFhgp68%#rgG%$crgGF`r%#M1G%#b
sG%#M2G%$tM2GF[aw%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GFcir%#B3G%#B4G%$iB1G%&rp
ermG%&cpermGFbbsF^el6"F,C6@$/-F`q6#F__lFbwO6'F4F\qFbwFaamFaam>F/7#-Fefl6$-FQ6#7
#-Feco6#;,&-Fejl6$-FQ6$FW&F`s6#89/F_gw;FW,&88FWFenFWFWFWFW-Fejl6$F[gw/F_gw;FWFc
gw-F]jl6$FcgwF__l>F]\lFd[l>FC7#-FQ6#-Facl6$<#-Feco6#;FW-FQ6$FbhqF4<#-FQF=>Fg[l-
F^w6$&F46$F/F^u&F46$FCF^u>F\_l&Fg[l6$F_bn;FWFas>Fez-Fe\n6$-Feaw6$)F\_lFj`o.F_gl
F^x>Fc]m-FE6$w,F`itF,6$FbrFcrF,-F^cr6$FW-Fjq6$FeaqFisF,F,6$FjdwFez6#FW6$7'FZFen
Fe^lF][oFhnFg^l<#-Feco6#F\`s>F\gl-Fjq6$-Facl6$<#-Feco6#;FW-FQ6$F^iqFezFc]mFis>F
aev-Fjq6$7%-FQFjim-FQFf^m-Feco6#;,&F]\lFWFWFW-FQ6$FbhqFg[lFis>Faev&7$FhhwF\^mF`
ev>Fehl-F^w6%&Fg[l6$7#Fj[xF^u&Fg[l6$7#F[\xF^u&Fg[l6$;F_\xFenF^u>F]fl-Fe\n6$-Fea
w6$&FehlFbiwFjiwF^x>Fc]m-FE6$w,F`itF,6$FbrFcrF,F`jwF,F,6$F\ewF]fl6#FWFfjwFhjw>F
\gl-Fjq6$-Facl6$<#-Feco6#;FW-FQ6$F^iqF]flFc]mFis>877%Fj[xF[\x-Feco6#;Ff^p-FQ6$F
^iqFehl>Ffil-%$<|gr>G6%&Fehl6$F^uFj\x&Fehl6$F^uF]]x&Fehl6$F^u;Ff^pFen>6&F_cpFjd
sF[esFi]w6&&Ffil6$F\`sF\`s&Ffil6$F\`s;,&F_glFWFWFWFen&Ffil6$Fc`xF\`s&Ffil6$Fc`x
Fc`x>F`]v-Fi^s6$F^xF_cp6'-Fe\n6$,&Fi]wFW-F`eq6%F[esF`]vFjdsFenF^x&F\q6#7$F[\x-F
eco6#;Ff^p-FQ6$FWF\qF_glFaevFj^xF,F,F,6#Fgn687'FZFenFc`mFgnFhn7'FZFenF^oFjeoF`o
7'FZFenFj`lF`oFju7'FZFenF^o"#)*FjoF\asF_`lF[[oFjjm7'FZFenF^oFboFjo7'FZFenF^oFb[
oFjo7'FZFenF^oF][oFjo7'FZFenF^oFh[rFjoFabx7'FZFenF^oF_jmFjo7'FZFenF^oF\alFjoFbb
xFcbx7'FZFenF^oFj\rFjo7'FZFenF^oFjeuFjo7'FZFenF^oFiiqFjoFfbx7'FZFenF^oF`[uF\oF,,
I0linDepReductionw,6$F]drFjat6)F[awFi`wFgdw%$tM1GF^ew%&r2delG%&c2delG6"F,C*>FC-
Fe\n6$-Feaw6$)F4Fj`oF]dsF\q>F[_l-FE6$w,F`itF,6$FbrFcrF,F`jwF,F,6$Fi`wFC6#FW6$7'
FZFenFe^lFijmFhnFg^l<#-Feco6#Ffgt>F\_l-Fjq6$-Facl6$<#-Feco6#;FW-FQ6$F^iqFCF[_lF
is>F]\l&F46$-F]it6%F]jl7#FbhwF\_lF^u>Fg[l-Fe\n6$-Feaw6$F]\lF]dsF\q>F[_l-FE6$w,F
`itF,6$FbrFcrF,F`jwF,F,6$F_cxFg[l6#FWFfjwFcdx>Fez-Fjq6$-Facl6$<#-Feco6#;FW-Fbgl
Fa\mF[_lFisO6%&F]\l6$F^u-F]it6%F]jl7#-Feco6#;FW-FQ6$F^iqF]\lFezF\_lFezF,F,F,6#F
[]m6+7'FZFenFh^lFgnFhnFd]uFdbxFhjtFa_wFd]uFbbxFa_w7'FZFenF^oF`[nFjuF,,
I)rectTordw,6&FfatFa_q'%#TsGFisFjat6*F[bs%#dgGF]el%#nnG%$GBsGF[enF^zF^el6"F,C+>
F/F_q>FC7#-Fefl6$*&-Fejl6#-FE6%Fg\lF4FezFWF/Fen-F]jl6$FezF\q>F]\l-Fhbl6%FWF_^lF
C>Fg[l-Fgdt6#-FQ6#-FE6$%&denomGF]\l>F]\l*&Fg[lFWF]\lFW>F[_l-FE6$w,Fb\lF,6$FbrFc
rF,-F_fm6%FjrF4/F]sF[sF,F,6&F*F4FcpFas6#FW6$7'FZFenFfnFb_mFhn7'FZFenFfnFe^lFhnF
`s>F\_l7#-FQ6#<#-Fefl6$&-F[bo6$&F[_lFghl-Fgcp6$Fh[y&F`sFghlFjs/F_gl;FW-F`qFa\m>
F\_l-FE6$w,FcdoF,6$FbrFcrF,Fi]lF,F,6$F]elF]\l6#FW6$7'FZFenFcuFe`mFhnFj[mF\_l-FE
6$w,Fb\lF,6$FbrFcrF,-Fg_oFh\lF,F,Fe_r6#FW6$7'FZFenF[`lF_]lFhn7'FZFenF[`lFjnFhnF
\_lF,F,F,6#F`u6,F\_mFgjt7'FZFenF^oFe[oFjoFi_mF[[oFi_mFcbxFigr7'FZFenF^oFeuFjo7'
FZFenF^oFf^lF\pF,,
I,filterBasesw,6&F*F\am%%nQBsG%#ffG6&%#mFG%#BsGF_\v%"NG6"F,C(>Fg[l-Fhfl6#*&FasF
WF`sFW>F/-F\]r6$F4F_co>FC-FE6$w,Fb\lF,6$FbrFcrF,-F`q6#-F^cl6$-Fjq6$F4F_[lF`^lF,
F,6$F\^yF/6#FW6$7'FZFenFcuFa_mFhnFj[mF\q>F]\l-F]\m6%FC%">G/%'outputG%,permutati
onG-Fa[l6$QA%d~quotient~space~bases~removed|+F,Fg[l7#-FQ6$;FW,&F`sFWFg[lFenF]\l
F,F,F,6#F`u6)FY7'FZFenF_]lF[dlFjo7'FZFenF^oF_cmFjoFa_wF[asF[al7'FZFenF^oF_]lFes
F,,
I-filterBases2w,6*F[bsFep%$CMsGFehxFahxF\amFcpFj]y6;F^irFbpFaalFf^oFi]yFbvF^el%
#vBG%#tBG%#mpGFagpFairFi]oFapFb[tFafu%$cHsGF`r%$avoG%#msG%#moGF_\vF^^yFjdlFdgq6
"F,C+>F[_l-F`qFgv>F\_l-F`q6#&F__lFjs>Fj^xFaam>Fcgw"(+++">8:-Fhfl6#*&F][qFWF[_lF
W?(FezFWFWF[_lFcqC(>6&F/FCF]\lFg[l6&&FasFg`p&F^xFg`p&F__lFg`p&F`sFg`p@$0-F`qFia
mF\_l\>6%F_glFehlF]fl6%-FceqFiam-Fg_q6#-Fjcq6%F]\lF_^l7#-Feco6#F\aoFaby?&FfilF
\qFcqC*>Fc]m-Fj]l6%FfilF_^lF]\l>F\gl-Fccq6(FfilF]\lFehlF/FC/F]sFj[l>F_cp,&-Fceq
FjimFW-F`eq6$F\glF_glFen>Fjds-Fd`o6#7#-Fefl6$-F]hr6&&F_cp6#8;F/FCFj[l/FgeyF\ao>
F[es-Fe\n6$-FE6$FG-F`eq6$FjdsFg[lFj[l>Fi]w7#-Fefl6$-Fejl6#&F[es6$F^uFgey/Fgey;F
WF4>F`]v-Fejl6$-Fbx6%-F_bl6$8<Ffdv-F`q6#FagyFW-F]jl6$FagyFi]w@$2F`]vF]flC$>F]fl
F`]v>FaevFfil@$2F]flFcgwC$>FcgwF]fl-Fa[l6%Q?Smaller~template~found:~%d,%a|+F,Fc
gwFaev>Fj^x7$-FQ6#Fj^xF]fl>F_gw-F]\m6%Fj^x%"<GF[`y-Fa[l6$F``yFcby7#-FQ6$;FW,&F[
_lFWFcbyFenF_gwF,F,F,6#Fd`l6?Fhcl7'FZFenF_cmFguFjo7'FZFenF`oFcaoFjo7'FZFenF_ep"
$@"Fjo7'FZFenFcdn"$M"Fjo7'FZFen"$T""$f"FjoFc`l7'FZFenF[`lFjeoFjo7'FZFenF[`lFguF
`o7'FZFenFejmFbwFjeo7'FZFenF[`lFj\rFjoFhjs7'FZFenF]_mF_]lFjo7'FZFenF]_mFfsFjo7'
FZFenF]_mF\oFjo7'FZFenF]_mFdaoFjo7'FZFenF]_mF[dlFjo7'FZFenF]_mFgoFjo7'FZFenF]_m
FijmFjo7'FZFenF]_mFdoF`oFhcn7'FZFenFjcnFguFjo7'FZFenF[`lF^vF`o7'FZFenFiuF\oFjo7
'FZFenFjcnF_brF\pF``mF[asF[alFj`yF,,
I(iniProbw,6&F%Fjgp'Fj]yF\gp'%#pnGFddm61F*%#vFGFcpFepFehxFahx%#GCGF\amF^ayFbpFf
^oFapFf`uFi]yF^el6"F,C,>F]\lFas>6$F/Fg[lFgem>6$FCFg[l6$-FceqF=<#Fbdp>F]fl-Fjem6
#Fbdp-Fa[l6$QJThe~problem~is~defined~by~%d~polynomials|+F,Fd[l>Fc]m-F_fm6%F/F]f
l/F]sF]\l@$0-&Ffr6#%1HilbertDimensionG6$Fc]mFh\zFbwYQJthe~problem~has~infinitel
y~many~solutionsF,-Fa[l6&QQVariables:~%a;~degrees:~%a;~number~of~roots:~%d|+F,7
#Fbdp-FE6$Fg\lF/-F`q6#&-FifmFeesFjs@%F\qC(>6%F]\lF\_lFehl-Fg[oFaq>F_cpF\hm>F[_l
7#-Fefl6$-Fe\n6$-FE6$FG-Fjq6$-F`eq6$F_hvFCFisF]\l/Fjds;FWF_cp>F_gl7#-Fefl6$&-Fi
fm6$&F[_lF`hv&F\_lF`hvFjsF^_z>F\gl-F[ay6*Fd[lFg[lFehlF[_lF\_lF_glF]\lF`s>6&Fehl
F[_lF\_lF_gl6&7#-Fefl6$F_hv-F]jl6$FjdsF\gl7#-Fefl6$Fg_zFb`z7#-Fefl6$Fh_zFb`z7#-
Fefl6$&F_glF`hvFb`zC(>F_glFegm>6$F_cpF]fl6$-F`qFghlF`\z>Fez-F_fm6&F/F]flFh\z/F
\`y%)extendedG>6$Fc]mFfil6$&FezFjs-Fd`o6#&FezF^jo>F\gl-Ff]y6&F/F_glF_cpF`s>F]`z
6&7#-Fefl6$FfilFb`z7#-Fefl6$Fc]mFb`z7#-Fefl6$F]flFb`zFj`zO6)F]\lF/Fg[lF[_lF\_lF
_glFehlF,F,F,6#F`u6:Ffjn7'FZFenFe^lFj`lFjoFdjmFd]uFfjm7'FZFenF^oFcaoF\pF_`l7'FZ
FenF^oFfiyF`o7'FZFenFcaoFcasFdo7'FZFenF^o"$G"F\pF`[o7'FZFenF[`lFjcnFjo7'FZFenF[
`lFiuFjo7'FZFenF[`lF_oFjo7'FZFenF[`lF_jmFjo7'FZFenF[`l"#lFjo7'FZFenF[`lF\dwFjoF
cepF``w7'FZFenF[`lFb[oFjoFaep7'FZFenF[`lF[dlFjo7'FZFenF[`lF\vFjo7'FZFenF^oF[dlF
juF,,
I/templateFinderw,6(F%>'%,action_varsG-Fis6#<$%'negintGFddmFaam>'F^ew%'symbolGF
[hp>'%,filter_fracGF\gpFbw>FfdmFhdm>'%+schur_polsGFidzFaam6HFcpF*FepFehxFahxF\a
mF^ay%&avarsGF\elFbvFi]yF^^yF^elFabsF^irFbpFegpFf^o%&tord1GFagpFairFaalFdirFi]o
FapFb[tFeirFafuFggpF`pF`^q%#flGF`rF[^nF[gpFfay%#noG%$spoG6"F,C+>F/F_em>8GFaby>8
IFen>6)F/FCF]\lFg[lF[_lF\_lFez-F\[z6&F4-%&evalbG6#/F`sF[hpFasF/>F_gl-Fbx6%/F]fr
FbwF]\l-FE6$w,6#F[elF,6$FbrFcrF,FeaqF,F,6$FepF]\l6#FW6$7'FZFenF\alFj\rFhn7'FZFe
nF\alFdoFhnF\q>6%FehlF]flFfil6%Fcaz-F`q6#Fe]mF^^m>Fc]m,$*&FfilFenFehlFenFgy?(F
\glFWFWFfilFcqC%>6&FjdsF[esFi]wF`]v6&&Fg[lFf^m&F[_lFf^mFe^m&FezFf^m>Faev-FQ6$FW
F[es?(F_cpFWFWFehlFcqC.>Fj^x&F_glFdgs>6(FcgwF_gwFcbyFgeyFagy8=-F[ir6'Fj^xFjdsF[
esF/Fi]w>8>Fbgy>8?-Fbx6%/F`s%%nstdG-Feas6&FCFagyF]\lF/-F_[t6(FCFagyFcizF`]vF]\l
F/>6%8@8A8B-Fd[v6'FCFiizFcbyF]\lF/>Fejz&-F^dw6(FejzFfjzFdjz,(-FQ6$F^iqFejzFWF]f
lFenFgizFenF/F__lFjs>Fejz&-F[cx6$FejzF/Fjs>8C-Fb`w6(FgeyFejzFcgwF_gwFgizF/>6$8D
8E-FQ6$FWFejz>8F-Fjcr6#Fejz@&3Fe[[l52Fj[[lFafz3/Fj[[lFafz2FcfzF_\[lC%>6%Fafz8HF
cfz6%Fj[[lF[\[lF_\[l-Fa[l6(QUSmaller~or~sparser~template~found:~[%d,%d],%a,%a,%
a|+F,Fj[[lF[\[l-Fjdq6$F_\[lF^oFj^x-Fbx6%F\jzF\glFaev-Fefp6-F47$Fj[[lF[\[l-Fjdq6
$F_\[lF`yF/F]\lFj^xF[esF_gwFdjzF__lFhfz4Fe[[lY6&Q@invalid~action~matrix:~%1,%2,
%3F,F\glFj^xF[es-Fa[l6*Q7%d%s,[%d,%d],%a,%a,%a|+F,-Fhfl6#*&,&*&,&F\glFWFenFWFWF
ehlFWFWF_cpFWFWFc]mFWQ"%F,Fj[[lF[\[lFa][lFj^xFc][l-Fa[l6&Q<Best~template:~[%d,%
d],~%a|+F,FafzF\][l-Fjdq6$FcfzF^oF,F,F,6#FW6?F\bxF]jm7'FZFen"$&="$&>Fjo7'FZFen"
$,#"$5#FjoF`_wFbbxFa_wF[dnFc`l7'FZFenF[`lFacmFjo7'FZFenF[`lF_cmFjoFhjsFadn7'FZF
enF]_mFcoFjoF^dn7'FZFenF]_mF^vFjoF^fp7'FZFenF]_mF\epFjoFdjy7'FZFenF]_mFb_mFjo7'
FZFenF]_mF_cmFjoF][nFafp7'FZFenFiclFbhlFjo7'FZFenFiclFgczF\p7'FZFenFiclFcjmF\p7
'FZFenFiclFjeuFdo7'FZFenF]_mF[[uF\p7'FZFenF^oFe^tF\pF,,
I-readTemplatew,F\\q6LF^hpF_hpFcpFepFagpFbpFggpFfezF*Fb[t%#U0G%&tord0G%"UGF^irF
airF`ewFaalFbirFcirFeerFdirFi]oFapFfpFbv%#nRGFgdwF`^qFebrF[awFdewFeewF`pF_cx%#t
1GF`cxFacxF]zFifp%#xEG%#xVGF^\q6"F,CE>6,F/FCF]\lFg[lF[_lF\_lFi]wFezF_gl8M-Fj[qF
f]r>Fehl&FgemFjs>F`ap-FgqF^dp>Fc]mF`\z>F\gl-Fcjq6$FfilFc]m>F]fl-Fbbr6%F]flFfilF
\gl>F_cp-F_fm6%FehlF\_lFh\z>F[es&-Fifm6$F_cpF\_lFjs>Fi]w-Fjq6$Fi]wF_[l>Fjds-Fj]
l6%F[_lF_^lFi]w>F`]v-Fcjq6$-Fjq6$-Facl6$FjdsFi]wFisF\_l>6$FagyFciz6$-F`q6#Fi]w-
F`qFj_v>Faev-Fhbl6%-F^clF`c[lF_^lF[_l>Fj^x-%&getB0G6$FaevFg[l>Faev7$-FQ6#-Fcjq6
$-Fjq6$-Facl6$FaevFj^xFisF\_l-FQ6#-Fcjq6$-Fjq6$Fj^xFisF\_l>Fi]w7$-FQ6#-Fcjq6$-F
jq6$-Facl6$Fi]w-Fjq6$FaevF_[lFisF\_l-FQF`ev>6$FcgwFjds6$7$-FQFj_v-FQFec[lFhb[l>
F_gw-Fccq6(F[_lF[es-Fg_q6#-F\]s6$F[es7#-Feco6#;FW-F`q6#F[esF_cpF\_lFh\z>Fgey-Fb
er6'Fi]wF[esF_cpF\_lF]\l>F_gw-Fe\n6$-F`eq6%FgeyF_gw-Fi^s6$F]\lFgeyF]\l>Fcby-Fjq
6$,&-FceqFj_vFW-F`eq6$&F_gw6$;FWFcizF^u-FceqFec[lFenFis>6$FgizFdjz&-F^fu6&FezFe
hlFg[lFcgw6#;F[]mF^o>6'FgizFiizFejzFfjzFe[[l-F^dw6(FgizFdjzFez,(-FQ6$F^iqFgizFW
FagyFenFcizFenF]\lF_gl>6%Fj[[lFafzF\][l-F[cx6$FgizF]\l-Fa[l6$Q9Action~matrix~fo
und:~%a|+F,-Fb`w6(F_gwFj[[lFjdsFi]wFcizF]\l>8J7#-FQ6$FWFj[[l-Fa[l6$Q3Template~s
ize:~%a|+F,F\j[l@$50Fc]o&F\j[lFjs0&F/F^jo&F\j[lF^joYQ/wrong~templateF,>8L-Facl6
$-Fjq6$FdjzF_[l-Fjq6$FiizF_[l>Fiiz&Fiiz6#-F]it6%F]jl7#-Feco6#;FW-FQ6$FWFiizF\][
l>F[\[l-Fe\n6$-Feaw6#&Fgiz6$-F]it6%F]jl7#-Feco6#;FW-FQ6$FbhqFgizFafzF^uF]\l>F_
\[l-FE6$w,Fb\lF,6$FbrFcrF,-FQ6#-F_\l6$w,Fc[wF,6$FbrFcrF,0&F`^l6$F4F[sFbwF,F,6&F
_cxF`^lFc\lF46#FW6$7'FZFenF_cmF[dlFhn7'FZFenF_cmFadlFhn<#-Feco6#F_hqF,F,6$F_cxF
[\[l6#FW6$7'FZFenFcuF`fpFhnFj[m<#-FQ6#F\][l>8K-Fcil6$-Fjq6$F`a[lF_[l-Fjq6$&Fiiz
6#7#-FQ6#F_\[lF_[l>Fcfz-Fcjq6$-Fjq6$-Facl6$Fb[\l-Fjq6$FcgwF_[lFisFc]m64Fg[lF[_l
F]flF\glFcfzFcgwFi]wFjdsFezFafzF\][lF\j[lFcizF\_\lFejzFfjzFe[[lF][\lF,F,F,6#F[]
m6GFhclF_jqFeaoF[[oFd]y7'FZFenF^oFe`mFjoF[[o7'FZFenF^oFc]nFjoFj`sF\fuFi_mFh_mFf
aoFfaoFjjmFb[pFdbxF_dl7'FZFenF^oFcjmFjoFd]uFgbxFdasFdas7'FZFenF^o"#'*Fjo7'FZFen
F^oFa`lFjo7'FZFenF^oFjjoF\pF\[u7'FZFenF^oF`]mF\p7'FZFenF^oF`[nF`o7'FZFenFguF`fp
FdoFgjmFgjm7'FZFenF^oFd_mFjoF^[pFgbxFbbx7'FZFenF^oF^epF\oF,,
I&getB0w,6$'%"PGF_[lF^gp6'F\elF^el%$VrsG%$vrsGFeer6"F,C$>F/F]fr?(FCFbwFW,&F/FWF
enFWFcqC$>F]\l-&%)combinatG6#%'chooseG6$F\q,&F/FWFCFen?&Fg[lF]\lFcqC$>F[_l-F_\l
6$w,F_rF,6$FbrFcrF,-Fjq6$-FE6$w,F]eoF,6$FbrFcrF,-Fehm6$*&F4FWFjrFWF[sF,F,6&F`rF
4Fda\lF[s6#FW6$7'FZFenFioFj\rFhn7'FZFenFioFguFhnF`^l%$andGF,F,6&Fga\lFg[lFda\lF
46#FW6$7'FZFenFj`lFh[rFhnF[foF4@%0F^\yFbwO-Fjq6$-FE6$w,F]eoF,6$FbrFcrF,*&F4FW&F
`^lFjsFWF,F,6$FeerF[_l6#FW6$7'FZFenFdoF][oFhn7'FZFenFdoFe[oFhn7$FbdpFWF_[l>F[_l
FjelF,F,F,6#F[]m6+7'FZFenFd`lFgnFhn7'FZFenFjnFj`lF\oFc`l7'FZFenF[`lF^`lFjoFhjs7
'FZFenF]_mF_oFjo7'FZFenF]_mF\vF`o7'FZFenF\oF_brFju7'FZFen"#!*FjgrFjoF,,
I*iniColpivw,6&Fadw'Fj`[lF_[lF`gpFa_q6*%#VlGFda\lFeer%#aPGFbir%#RPGF]zFbp6"F,C/
>F_gl-Fjem6#Fgiu>F/-Fjq6$-Facl6$Fa_yF\qFis>FC-Fjq6$-F_\l6$w,F_rF,6$FbrFcrF,-Feh
m6$Fec\lFi\lF,F,6&FagpF`sFaf\lF/6#FWFecvF/F_[l>F]\l-F]d[l6$FCFas>Fg[l-Fj]l6%F`s
F_^lFC>F[_l-Fcjq6$-Fjq6$-FaclF]ilFisF_gl>FC7$-FQ6#-Fcjq6$-Fjq6$-FaclFfemFisF_gl
-FQ6#-Fcjq6$-Fjq6$F]\lFisF_gl-Fa[l6$QCList~of~permissible~monomials:|+%a|+F,FC-
Fa[l6$QENumber~of~permissible~monomials:~%d|+F,Fg_l>Fg[l-FE6$w,F_rF,6$FbrFcrF,-
F^cr6$Fec\l7$-FQFdds-FQ6#FcjlF,F,6(FagpF`sFda\lFCFbirF[_l6#FW6$7'FZFenFcuFjeoFh
nFj[mFC>F\_l7$F`\mF\^m>Fez-Fcjq6$-Fjq6$-Fcil6$-Facl6$-Fjq6$F/F_[l-Fjq6$F\_lF_[l
F\qFisF_gl6'-F^w6$-FQFg`pFciuFCFg[lF^\y-F`qFg`pF,F,F,6#F`u60Fby7'FZFenFhsFacmFj
oF^jqF`[pF\fuFi_mFh_mF]as7'FZFenF^oFc]nF\pFjhrFhjtF\fuF_jq7'FZFenF^oFguF\oF,,
I+alterCommaw,6#'FfalFisF,6$FbrFcrF,-F16%Fe_n-FQ6#-&F_cr6#%+InterleaveG6$F47#-F
eco6$Q",F,,&F_qFWFenFWFafnF,F,F,6#FW6$7'FZFenFcuFfsFhn7'FZFenFcuFiuFhnF,,
I,writeSolverw,6/'%$dirGF'F^hp%&vars0GFagp%#iMG%#eMGFaalFairFifpFcdwFh`[lF[awF[
hp6)%&vars1G%#vvGF[em%$nv0GFbvF^el%#fbG6"F,C>>Fg[lFjay>F[_l-F`q6#Fj[l>FezQ%~~~~
F,>F/-Fjq6$-Facl6$Fcbv<#FasFis>FC7#-Fefl6$-F^cr6$*&&F/F_^mFW&Fj[lFi`nFWFj[l/F\_
l;FW,&Fg[lFWFenFW>F]\l-Fhgm6$-F16+F4Q"/F,-Fbx6%90Q%std_F,Q&nstd_F,,&&F^[qFjsFW9
/FenQ"xF,,&&F^[qF^joFWF]a]lFenQ"_F,F&F5Fa\n-F\im6$F]\l-F16'QH%%~Input:~coeffici
ent~matrix~C~of~size~F,F[jpF^a]l&F\qF^joQ#|+|+F,-F\im6$F]\l-F16,Q*function~F,-F
b\]lFgvQ$~=~F,Ff`]lF[a]lF^a]lF_a]lFaa]lF&Q&(C)|+|+F,-F\im6$F]\l-F16&FezQ(i_dx~=
~F,-Fb\]l6#-FE6$w,F`itF,6$FbrFcrF,F[dtF,F,F,6#FW6$7'FZFenFa_mFacmFhnF^\wF^xQ#;|
+F,-F\im6$F]\l-F16&FezQ(j_dx~=~F,-Fb\]l6#-FE6$w,F`itF,6$FbrFcrF,F\dtF,F,F,6#FWF
]c]lF^xF_c]l-F\im6$F]\l-F16&FezQ(C_dx~=~F,-Fb\]lF[fwF_c]l-F\im6$F]\l-F16(FezQ>M
~=~sparse(i_dx,j_dx,C(C_dx),F,F\a]lFc]]lF`a]lQ$);|+F,@$0F]a]lFbw-F\im6$F]\l-F16
5Q"|+F,FezQ'M~=~M(F,,&F]a]lFWFWFWQ&:end,F,F`e]lQ*:end)-(M(F,F`e]lQ(:end,1:F,F]a
]lQ')/M(1:F,F]a]lQ$,1:F,F]a]lQ())*M(1:F,F]a]lFc]]lF`e]lQF:end);~%%~Schur~comple
ment~reduction|+F,-F\im6$F]\l-F16'F^e]lFezQ5[L,|ir,Pi]~=~lu(M(:,1:F,F_[qQ%));|+
F,-F\im6$F]\l-F16$FezQ+Pi~=~Pi';|+F,-F\im6$F]\l-F16(FezQ0M~=~[Pi*L~Pi(:,F,,&F_[
qFWFWFWQ,:end)]\M(:,F,Fhf]lQ(:end);|+F,-F\im6$F]\l-F16&FezQ+M~=~M(end-F,,&FehpF
WFenFWQ*:end,:);|+F,-F\im6$F]\l-F16'F^e]lFezQ+T~=~zeros(F,F[_lFgd]l-F\im6$F]\l-
F16*FezQ%T(1:F,FehpQ.,:)~=~-M(:,1:F,FehpQ')\M(:,F,,&FehpFWFWFWFjf]l@&/,&F[_lFWF
ehpFenFW-F\im6$F]\l-F16&FezQ#T(F,*&F[_lFW-F^cr6$&F][qFi`nFj[lFWQ()~=~1;|+F,2FWF
ah]l-F\im6$F]\l-F16&FezFfh]l-Fb\]l6#7#-Fefl6$,&*&F[_lFW,&-F^cr6$&F][q6#,(F\_lFW
F[_lFenFenFWFj[lFWFenFWFWFWF\_lFW/F\_l;F^h]lF[_lF[i]l-F\im6$F]\l-F16%F^e]lFezQ1
[V,D]~=~eig(T);|+F,@%/Fg_lFW-F\im6$F]\l-F16(FezQ*sol~=~[V(F,&FCFjsQ(,:)./V(F,F[
_lQ3,:);~diag(D).'];|+|+F,-F\im6$F]\l-F16*FezF[[^l-Fb\]lFUQ/,:)./repmat(V(F,F[_
lQ%,:),F,F_`]lQ3,1);~diag(D).'];|+|+F,-F\im6$F]\l-F16$FezQXI~=~find(not(isnan(s
ol(1,:)))~&~not(isinf(sol(1,:))));|+F,-F\im6$F]\l-F16$FezQdo%%I~=~I(not(imag(so
l(1,:))));~%%~uncomment~this~line~for~real~roots~only|+F,?(F\_lFWFWF_`]lFcq-F\i
m6$F]\l-F16'FezF[`]lQ(~=~sol(F,F\_lQ&,I);|+F,-F\im6$F]\l-F16'FezFasFf\^lFg[lQ',
I);|+|+F,-F\im6$F]\lQ$endF,-FiimFiamF,F,F,6#Fcu6EFYF[_w7'FZFenFa`lFj\rFjoFg[qFd
asFaat7'FZFenF^oFgiqFjo7'FZFenF^oF[f\lF\p7'FZFenF^o"$I"F\p7'FZFenF^oF^dlF\pFh]^
l7'FZFenF^oFb_mF\p7'FZFenF^oF_brF\pF`[o7'FZFenF[`l"$#=F\p7'FZFenF^oF]dzF\p7'FZF
enF^oFboF\p7'FZFenF^oF\[pF\pFi]^lFecm7'FZFenF^oFbjmF\pF`[o7'FZFenF[`lF_[pF\p7'F
ZFenF[`lFfiyF\p7'FZFenF^oFa_mF\pF`[o7'FZFenF[`lF^epF\p7'FZFenF[`lF__wF\pFj]^l7'
FZFenF^oFgyF\pFc`l7'FZFenF[`lFijmF\p7'FZFenF^oFjeoF\p7'FZFenF^oF\pF\pFa[nF,,
I2writeSolverColpivw,60F\^]lF^hpF^^]lFagpF_^]lF`^]lFda\lFbf\lFifpFcdwFh`[lFbvF[
awF[hp6)Fb^]lFc^]lF[emFd^]l%#nPGF^elFe^]l6"F,CB>Fg[lFjay>F[_lFj^]l>FezF]_]l>F/F
__]l>FC7#-Fefl6$-F^cr6$Fj_]l&Fj[l6#;,$F]a]lFenFenF]`]l>F]\l-Fhgm6$-F16+F4Fe`]l-
Fbx6%91Fi`]lFj`]l,&F\a]lFWFh`]lFenF^a]l,&F`a]lFWFh`]lFenQ)_colpiv_F,F&F5Fa\nFba
]l-F\im6$F]\l-F16,F]b]lF^b]lF_b]lFd`^lFg`^lF^a]lFh`^lFi`^lF&F`b]l-F\im6$F]\l-F1
6&FezFeb]l-Fb\]l6#-FE6$w,F`itF,6$FbrFcrF,F[dtF,F,F,6#FWF]c]lF^xF_c]l-F\im6$F]\l
-F16&FezFdc]l-Fb\]l6#-FE6$w,F`itF,6$FbrFcrF,F\dtF,F,F,6#FWF]c]lF^xF_c]lF\d]lFbd
]l@$0Fh`]lFbw-F\im6$F]\l-F165F^e]lFezF_e]l,&Fh`]lFWFWFWFae]lFjb^lFbe]lFjb^lFce]
lFh`]lFde]lFh`]lFee]lFh`]lFfe]lFh`]lFc]]lFjb^lFge]l@%0F_[qFbwC&Fhe]lF^f]lFcf]l-
F\im6$F]\l-F16&FezQ,M~=~full(M(F,Fhf]lQ+:end,:));|+F,-F\im6$F]\l-F16$FezQ.M~=~f
ull(M);|+F,@$0FehpFbwC%-F\im6$F]\l-F16'F^e]lFezQ6[L,UR,Pi]~=~lu(M(:,1:F,FehpF]f
]lF^f]l-F\im6$F]\l-F16(FezFgf]lF^h]lFif]lF^h]lFjf]l-F\im6$F]\l-F16&FezQ*MP~=~M(
1:F,FehpQ&,:);|+F,-F\im6$F]\l-F16&FezQ(NP~=~M(F,F^h]lQ+:end,:);|+|+F,-F\im6$F]
\l-F16&FezQ:[Q,U,Pi]~=~qr(NP(:,1:end-F,Fc_lF]f]l-F\im6$F]\l-F16(FezQ4A~=~UR\[MP
(:,1:end-F,Fc_lQ/)*Pi~MP(:,end-F,Fg[lQ):end)];|+F,-F\im6$F]\l-F16*FezQ+B~=~U(:,
1:F,,*F\a]lFWFh`]lFenF_[qFenFehpFenQ()\[U(:,F,,,F\a]lFWFh`]lFenF_[qFenFehpFenFW
FWQ3:end)~Q'*NP(:,end-F,Fg[lF\f^l-F\im6$F]\l-F16(FezQ/M~=~[-A(:,end-F,,&F]a]lFW
FenFWQ1:end)+A(:,1:end-F,F]a]lQ,)*B;~-B];|+|+F,-F\im6$F]\l-F16&FezQ&xP~=~F,-Fb
\]l6#F][qF_c]l-F\im6$F]\l-F16*FezQ*P1~=~[(1:F,,(F[_lFWFg[lFenFenFWQ&)*Pi~F,,&F[
_lFWFg[lFenQ":F,F[_lQ$];|+F,-F\im6$F]\l-F16-FezQ-T~=~getT(M,[F,,&F[_lFWFWFWF]h^
l,&F[_lFWFehpFWQ+~P1(1:end-F,F]a]lQ+)],P1(end-F,F[g^lQ&:end)F,Q',xP);|+F,F`j]l@
%Ffj]l-F\im6$F]\l-F16(FezF[[^lF\[^lF][^lF]a]lF^[^l-F\im6$F]\l-F16*FezF[[^lFc[^l
Fd[^lF]a]lFe[^lF_`]lFf[^lFg[^lF\\^l?(F\_lFWFWF_`]lFcqFb\^lFh\^lF]]^lF`]^lF,F,F,
6#Ffn6OF_[vF[_w7'FZFenFa`lFb_mFjo7'FZFenFe^tF`jmFjoFdas7'FZFenF^oF`[nFjoFf`\lFe
]^l7'FZFenF^o"$P"F\pFh]^lFh]^lFi]^lFj]^lF`[oF[^^lF`[o7'FZFenF[`lFdaoF\p7'FZFenF
[`lF^`lF\p7'FZFenF[`lFfsF\p7'FZFenF[`lFe^tF\pFaesF`[o7'FZFenF[`lF^dlF\pF\j^lF]j
^lFc^^lFecm7'FZFenF^oFjeuF\p7'FZFenF^oFc_wF\p7'FZFenF^o"$?"F\pFaj^lFh^^lFj`\l7'
FZFenF^oF\dwF\pFc^^lF`[oFd^^lFe^^lFj]^lFf^^lFc`lFg^^lFh^^lFi^^lFa[nF,,
I2writeInidataCoefsw,6$F%'%)root_dirGF'6.%*proc_nameG%#_CG%&_nameG%&_sizeG%#CsG
%#ClGF]^]lF[emF^elF\bt%$idxGFe^]l6"F,C8>Fc]mF]_]lAQ6../problems/_common.mF,AF0>
F/-FI6#-F16$%#C_GF4>6%FCF]\lFg[lFjfl>Fez-F16%F\qFe`]lF4@$4-F9Fg`p-&F:6#%.MakeDi
rectoryGFg`p>F_gl-Fhgm6$-F16&FezQ*/inidata_F,F4F5Fa\n-F\im6$F_gl-F16%Q9function
~data~=~inidata_F,F4Q$()|+F,-F\im6$F_gl-F16&Fc]mQ0data~=~cell([1,F,FabpQ%]);|+F
,?(FehlFWFWFabpFcq-F\im6$F_gl-F16(Fc]mQ&data|frF,FehlQ+|hr~=~randn(F,&-Fb\]l6#&
Fg[lF]hmFiinFgd]l-F\im6$F_glF_]^l-FiimFghl>F_gl-Fhgm6$-F16&FezQ(/coefs_F,F4F5Fa
\n-F\im6$F_gl-F16%Q4function~C~=~coefs_F,F4Q)(data)|+|+F,?(FehlFWFWFbcyFcq-F\im
6$F_gl-F16'Fc]mF[ftQ)~=~data|frF,FehlQ$|hr;|+F,-F\im6$F_glF^e]l?(FehlFWF[]mFg_l
Fcq@$/&FCF]hm%#cfGC%-F\im6$F_gl-F16(Fc]mQ+C~=~zeros(F,-FQ6$FbhqFh`nFc]]l-FQ6$F^
iqFh`nQ%);|+|+F,>Fj^l6$-Facl6$-Fjq6$&FC6#FhftF_[l<#Fbw-Fjq6$Fea_lFis?&F]flF[_lF
cqC$>Ffil7#-F\[wFajo-F\im6$F_gl-F16(Fc]mQ#C(F,-Fbx6%/F\cpFWFgeq-Fb\]lF]cpQ%)~=~
F,-Fjq6$F]flF'F_c]l-F\im6$F_gl-F16%F^e]lFc]mQVC~=~C./repmat(sqrt(sum(C.*conj(C)
,2)),1,size(C,2));|+|+F,Fg^_lFi^_lAQ+greedyAG.mF,F,F,F,6#F[]m6BF_[v7'FZFenFcoF_
[pFjo7'FZFenF^oF\oFgo7'FZFenF^oF[dlFgoF_dlF\jqF\jqF]o7'FZFenFbhlFcoF\pFa_w7'FZF
enF^oFijmF\pFcczFc`l7'FZFenF[`lFc_wF\pFi^^lFa[nFc]yF\[oFc`l7'FZFenF[`lF]dnF\p7'
FZFenF^oFcfoF\pFc`lF\[n7'FZFenF]_mFjgrF\pFge\l7'FZFenF]_mFe^lFd`l7'FZFenFiclFdo
Fjo7'FZFenFicl"$>"F\p7'FZFenF^o"#()F\pFi^^lFa[n7'FZFenF^oF\pFgoF,,
I-writeTestNumw,6+F%'FbvFddmFhfpFa_q'F^^]lFis'Fg`[lFceqF^ewFij^l%#cpG6+F]^]lF[e
mFabsFe^]l%$fb2GFc^]l%$vv0G%&xvarsG%$xvvG6"F,CI>F/-F16%F][qFe`]lF4>Fg[lF]_]l>F[
_l-F16$Fg[lFg[l>F\_l-FE6$w,F]eoF,6$FbrFcrF,-F16$F4F4F,F,F,6#FW6$7'FZFenFajqFccn
Fhn7'FZFenFajqFh`\lFhnFas>Fez-FE6$w,F]eoF,6$FbrFcrF,F^f_lF,F,F,6#FW6$7'FZFenFgc
z"$U"Fhn7'FZFenFgcz"$J"FhnF^x>F_gl-Fjq6$-Facl6$F]iuF[duFis>Fehl-FE6$w,F]eoF,6$F
brFcrF,F^f_lF,F,F,6#FW6$7'FZFen"$M#"$[#Fhn7'FZFenF\h_l"$P#FhnF_gl@$F7-Fg\_lF=>F
C-Fhgm6$-F16&F/Q+/test_num_F,F4F5Fa\n-F\im6$FCQ+rng(23);|+|+F,-F\im6$FCQ-N~=~10
000;|+|+F,-F\im6$FC-F16'Q%Err_F,F4Q+~=~[];|+Tm_F,F4Q)~=~[];|+|+F,-F\im6$FCQ.for
~i~=~1:N|+|+F,-F\im6$FC-F16&Fg[lQ0data~=~inidata_F,F4QN();~%%~generate~initial~
data~of~the~problem|+|+F,-F\im6$FC-F16$Fg[lQ%try|+F,-F\im6$FC-F16$F[_lQ&tic;|+F
,-F\im6$FC-F16&F[_lQ+C~=~coefs_F,F4QV(data);~%%~compute~coefficients~of~polynom
ial~system|+F,-F\im6$FC-F16,F[_l-Fb\]lFg`pF_b]l-Fbx6%-Fifz6#/Fj[lF[hpFi`]lFj`]l
&F`sFjsF^a]l&F`sF^jo-Fbx6%F^[qFi`^lFaa]lF4QA(C);~%%~solve~polynomial~system|+F,
@$0F\hmFbw-F\im6$FC-F16+F[_l-Fbx6%/F\hmFW&FehlFjs-Fb\]lF]hmQ6~=~arrayfun(@(j)~g
et_F,-F16#-FQFghlQ$(C,F,&-Fb\]l6#7#-Fefl6$-F16$&FezFiamQ$(j)F,/F]\l;FWF\\]lFiin
Q-),~1:length(F,F\bzF]f]l-F\im6$FC-F16$F[_lQ+tm~=~toc;|+F,-F\im6$FC-F16&F[_lQ,i
f~isempty(F,Fe]mQ2);~continue;~end|+F,-F\im6$FC-F16$Fg[lQ*catch~ME|+F,-F\im6$FC
-F16$F[_lQ+continue;|+F,-F\im6$FC-F16$Fg[lQ&end|+|+F,-F\im6$FC-F16$Fg[lQ)M~=~[]
;|+F,-F\im6$FC-F16&Fg[lQ0for~j=1:length(F,Fe]mQ#)|+F,?(F]\lFWFWF^flFcq-F\im6$FC
-F16'F[_l&FasFiamF_b]l&F\_lFiamQ&(j);|+F,-F\im6$FC-F16&F[_lQ%m~=~F,-Fb\]l6#-Fjq
6$F__lFisF_c]l-F\im6$FC-F16$F[_lQ6m~=~m/norm(m,'fro');|+F,-F\im6$FC-F16$F[_lQ=M
~=~[M;~norm(C*m.','fro')];|+F,-F\im6$FC-F16$Fg[lQ%end|+F,-F\im6$FC-F16$Fg[lQ.M~
=~sort(M);|+F,-F\im6$FC-F16&Fg[lQ4err~=~norm(M(1:min(F,F\qQ7,length(M))),'fro')
;|+|+F,-F\im6$FC-F16.Fg[lFbi_lF4Q)~=~[Err_F,F4Q(~err];|+F,Fg[lQ$Tm_F,F4Q(~=~[Tm
_F,F4Q(~tm];|+|+F,-F\im6$FCFc_`l-F\im6$FCQIfolder~=~fileparts(which('add_all.m'
));|+F,-F\im6$FC-F16'QCsave(strcat(folder,'\_results\Err_F,F4Q-.mat'),'Err_F,F4
Q&');|+|+F,-F\im6$FC-F16)Q3fprintf('Problem:~F,F4Qin.~Ave.~runtime:~%%0.1f~ms.~
Med.~error:~%%0.2e\n',10^3*mean(Tm_F,F4Q.),median(Err_F,F4F]f]lFajpF,F,F,6#Fjn6
MFhclF]jm7'FZFenFa_mF][oFjo7'FZFenFcaoFd]nFjo7'FZFenF\epF_epFjo7'FZFenF__w"$]"F
jo7'FZFen"$`""$?#Fjo7'FZFen"$B#"$c#FjoF]oFgc_lFdasF]dw7'FZFenF^oF\oF\pF`j^l7'FZ
FenF^oFesF\p7'FZFenF^oF`bxF\pFce`l7'FZFenF^oFjcnF\p7'FZFenF^o"$,"F\p7'FZFenF^o"
$x"F\pF`[o7'FZFenF[`l"$9#F\p7'FZFenF^oFbhlF\pF`j^lFa`wF]f`lFfe`lF[a\lFecmFc`lFg
^^l7'FZFenF^oF_jmF\pFc^^lFi]^lFce`l7'FZFenF^oF[dlF\p7'FZFenF^oF_[pF\p7'FZFenF^o
"$8"F\p7'FZFenF^oFj`lF\pFjhr7'FZFenF^oFjgrF\p7'FZFenF^o"$^"F\pFa[nF,,
I.writeHistoNumw,Fgj^l6%F]^]lF[emFe^]l6"F,C6>F/Fa\_l>F]\lF]_]l@$F7Fah_l>FC-Fhgm
6$-F16&F/Q,/histo_num_F,F4F5Fa\nFec`l-F\im6$FC-F16%QDload(strcat(folder,~'\_res
ults\Err_F,F4Q+.mat'));|+|+F,-F\im6$FCQ,bwd~=~0.3;|+F,-F\im6$FCQ-nbins~=~60;|+F
,-F\im6$FCQ9clr~=~[70~100~160]/255;|+F,-F\im6$FC-F16%Q1err~=~log10(Err_F,F4Fgd]
l-F\im6$FCQLhr1~=~histogram(err,nbins,'BinWidth',bwd);|+F,-F\im6$FCQ6hr1.FaceCo
lor~=~clr;|+F,-F\im6$FCQ7hr1.EdgeColor~=~clr;|+|+F,-F\im6$FCQ8axis([-17~1~0~115
0]);|+|+F,-F\im6$FCQVset(gca,'FontSize',54,'FontName','Times~New~Roman');|+F,-F
\im6$FCQFset(gcf,'PaperPositionMode','auto');|+F,-F\im6$FCQJset(gcf,'PaperOrien
tation','landscape');|+F,-F\im6$FCQGset(gcf,'PaperPosition',[1~1~28~19]);|+F,-F
\im6$FC-F16%QPprint(gcf,'-dpdf',strcat(folder,'\_results\fig_F,F4Q).pdf'));F,Fa
jpF,F,F,6#F[]m687'FZFenFe^lFgnFhnF]jm7'FZFenFgoFccmFjoF]oFgc_lFgbxFjhrF_^^lF]dw
7'FZFenF^oFejmF\pFhao7'FZFenF^oFjuF\pF\[o7'FZFenF^oFioF\pFe]nFhao7'FZFenF^oFh[r
F\pFecm7'FZFenF^oF]dnF\pFi]^lFaj^lFa[nF,,
I0solverGeneratorw,6)F%>F^ezF[hp>%'colpivGFW>%2create_coefs_fileGFW>%2create_hi
sto_fileGFW>%1create_test_fileGFW>Fhj^lQ(solversF,6FFepFagpFb[tFg`[lF]zFdirFaal
FairFggpF`cxFacxFifpFh`[lFj`[lF[awFdewFeewF[a[lF`^qFebrFda\lFbf\l%$nR1G%$nE1GFd
alF^_^lFcdwFjd_lF^^]l%#iCG%#eCGF`p%#MtGF_^]lF`^]lF]^]l6"F,C9>64F/FCF]\lFg[lF[_l
F\_lFezF_glFehlF]flFfilFc]mF\glF_cpFjdsF[esFi]wF`]v-Fb`[l6$F4-Fifz6#/F\qF[hp>Fa
ev-F^w6$F`\mFciu>6'Fj^xFcgwF_gwFcbyFgey-F\f\l6&FaevF_cpFCF/>6%FagyFcizFgiz6%F\\
]l-F`q6#FcgwF^\y>Fiiz-Fbx6%51FcizFagy/F`sFbwF\wFcq>Fdjz-Fbx6%Fiiz-F_\l6$w,F]eoF
,6$FbrFcrF,-Fehm6$*&F4FW&F`^lFi`nFW&F`^l6#;,$Fi\lFenFenF,F,6&Fda\lFcgwFdalFagy6
#FW6$Fcar7'FZFenFadlF\oFhnF/-F_\l6$w,F]eoF,6$FbrFcrF,-Fehm6$Fh^alF`^lF,F,6$Faal
Fez6#FW6$7'FZFenF`[uF`bxFhn7'FZFenF`[uFjjoFhnF/-Fa[l6$QRVariables~that~can~not~
be~evaluated~at~roots:~%a|+F,7#-FQ6#-Facl6$Fd[]lF`[\l>Fejz7#-%(indicesG6$-Fjq6$
F]\lFg_q%+indexorderG>Ffjz-FE6$w,Fb\lF,6$FbrFcrF,,&F[dtFW*&,&F\dtFWFenFWFWF`hqF
WFWF,F,6$Fb[tF]\l6#FW6$7'FZFenFcuF^`lFhnFj[mFejz>F]\l-Fd`o6$-FQ6$FWF]\l<#-FQ6#-
Fj_q6%w,Fc\mF,6$FbrFcrF,/-FQFaqF\qF,F,F,6#F[]m6$7'FZFenFjcnFdoFhn7'FZFenFjcnF[d
lFhnFejzFfjz>Fe[[l&-F^fu6&Fehl-Fjq6$-F`eq6$F]\lFg[lFisF/F\_lF^jo@$0FjdsFbw>Fe[[
l&Fe[[l6$F[esFi]w>Fe[[l&Fe[[l6$-F]it6%F]jl7#-Feco6#;FW-FQ6$FbhqFe[[l-&F[^l6#Ffd
v6%F]flF_^lFjds-F]it6%F]jl7#-Feco6#;FW-FQ6$F^iqFe[[l-Fddal6%FfilF_^lFjds@$Fiiz>
Fe[[l-Fbbr6%Fe[[l-Fjq6$-F^w6$F`f[lFaevFceq-Fjq6$-F^w6$F`f[lFj^xFceq>Fj[[l-Fjq6$
Fe[[lFg_q>6$F[\[lF_\[l6$7#-Fh`al6$Fj[[lF\aal-FE6$FQ7#-%(entriesGFefal@$4-F9F[_]
l-Fg\_lF[_]l>Fafz-F16%Fj[lFe`]lF4@$4-F96#Fafz-Fg\_lFegal@%Fiiz-Fj^^l60Fafz7#F\b
alFdjzFCF[\[lF_\[lFcgwF_gw7#-FQ6$FWFe[[lFgeyFcbyFagyFjdsFj\al-Fi]]l6/FafzFjgalF
djzFCF[\[lF_\[lFezF_glF[halFgizF\glFjdsFj\al@$/FasFW-Fej^l6$F4Fj[l@$/F__lFW-Fdd
_l6+F4FagyFc]mF/FdjzFg[lF\qFj[lFiiz@$/F^xFW-Fgf`lFchalF,F,F,6#FW6CF[hx7'FZFenF^
o"$D"FjoF\fuFe`\l7'FZFenF^oF^`lFjoF^jqF[v7'FZFenF^oF_epF\pFfbxFgjmFcbx7'FZFenF^
oF]dzFjo7'FZFenF^oFa`lF`o7'FZFenFe^lF`]mFjoF_bx7'FZFenF^oF`brF`o7'FZFenFfnFh`\l
FjoFd]yFhi^l7'FZFenF^oFfsF`o7'FZFenFjoF`[uF\pF\jqF]oFgc_lF`[o7'FZFenF[`lFbf`lF
\p7'FZFenF[`lFhe`lF\p7'FZFenF^oFb[oF`o7'FZFenF\oFcaoF\p7'FZFenF^oFhe`lF`o7'FZFe
nFejmFe_mF\p7'FZFenF^oF_jmF`o7'FZFenF\oF]dnF\pF,
