M7R0
I,readProblemw,6#'%%probG%'stringG6$%#fnG%"FG6"6"C'>8$-%$catG6%Q/../problems/F_
F,9$Q#.mF,@$4-&%*FileToolsG6#%'ExistsG6#F/Y6$Q2file~%1~not~foundF,F/AF/>8%-%$ma
pG6$%'expandG-%%evalG6#-F16$%#F_GF46$FC7#-%#opG6#-%'indetsG6#FCF,F,F,6#"""6)7'Q
!F,!"""#9""'"#O7'FZFen""*"#Z"#J7'FZFen""$"#v"#X7'FZFen"#P"#m"#]7'FZFenF^o"#5"#Y
7'FZFenF^o"#R"#V7'FZFenF^o"#?F\oF,,
I+isLinIndepw,6&%"MG%"GG%%tordG%#ppG6$%%varsG%"SG6"F,C&>F/-FT6#9%@$/-%%nopsG6#F
4FWO%%trueG>FC&-%,poly2matrixG6$-%(convertG6$-FE6$w,6#%"mGF,6$%)operatorG%&arro
wGF,-&%)GroebnerG6#%+NormalFormG6&F4T$T&/%/characteristicGT(F,F,6(FapF\qFbp9&Fc
p9'6#FW6$7'FZFen"#K"#&)Fhn7'FZFenFes"#MFhnF4%%listGF/6#FW-%#isG6#0-&&%.LinearAl
gebraG6#%(ModularG6#%%RankG6$FasFC-F`t6$Fas&FC6$;FW!"#;F,F,F,F,F,6#""%6(7'FZFen
"#8FgnFhn7'FZFenFjn"#DF\o7'FZFenF^o"#UF`o7'FZFen"#BFhs"#_7'FZFenF^o"$1"Fjo7'FZF
enF^o"#"*F\pF,,
I*testBasisw,6'F`p%$degGFapFbpFcpFdp6"F,C&>F/-FT6#F`s@$2F_qF\qO6$%&falseG-%$<,>
G6#-F^w6#""!>FC&-Fgq6$-Fjq6$-FE6$w,F_rF,6$FbrFcrF,FdrF,F,6(FapF`sFbpFasFcp9(6#F
WFcsF4FisF/Fjs6$-%#ifG6%0F^xFbw-F\t6#/-F`t6$F^xFCF\q-F\t6#/-&FbtFetFUF\qFCF,F,F
,6#""&6(7'FZFen"#7FgnFhnFdu7'FZFenF^oFjuF`o7'FZFenFeuFjoFjuF[v7'FZFenF^o"$+"F\o
F,,
I*iniMonSetw,6)F*FbvFepFapFbpFcp%$domG6)%"EGF`p%#vrG%"dG%%flagGFfp%&d_minG6"F,C
)>8*Fbw>F/-Fjq6$-FE6$FQ-&Ffr6#%(SupportGFaq%$setG-%'printfG6$Q7Support:~%a~mono
mials|+F,-F`qF=>FCF/?(8'FbwFWF,1,&Fg[lFWFezFen9*C&>8&-%'selectG6$w,6#%"xGF,6$Fb
rFcrF,1-%'degreeG6$F4FjrT%F,F,6&FepF`sF_zFg[l6#FW6$7'FZFenF\pFjoFhn7'FZFenF\p"#
AFhnFC>FC-FE6$w,6#%"tGF,6$FbrFcrF,-FQ6#-&%"|irG6#%"*G6%F4%#~$GT#F,F,6$F^zF]\l6#
FW6$7'FZFen"#;"#FFhn7'FZFenFe^l"#=FhnFC>6$8(8)-F_v6'FCF\qFasF^x9)@$4F[_l>Fez,&F
g[lFWFWFW-Fa[l6$Q;Initial~set:~%a~monomials|+F,-F`qFUO6$F/FCF,F,F,6#""(6/Fby7'F
ZFenF\o"#TFjo7'FZFenF^oFdoFjo7'FZFenF^o"#WF\p7'FZFenF^oFjnFjo7'FZFenF^o"")Fd`l7
'FZFenF[`lFgoFjo7'FZFenF[`lF\oFjo7'FZFenF[`lF[oFjo7'FZFenF[`lFa`lF`o7'FZFen"#CF
hnFjo7'FZFenF^o"#[F\p7'FZFenF^oFfnFjuF,,
I-neighborMonsw,6%%"BG%#MBGFep6%%#nBG%"bG%"vG6"F,C&@$/F_qFbwOF\q>F/-F_\l6%%%typ
eG-FE6$FQ-FE6%-%"@G6$FQ<$Fj]l&F[^l6#%"/GF4F`s%)monomialG>F/-%*intersectG6$-%&mi
nusG6$F/F4F\q-Fbx6%/Fd[lFbwF\qF/F,F,F,6#F^o6(7'FZFen"#:FgnFhn7'FZFenF^o"#SF`o7'
FZFenFiuFesFju7'FZFenF^o"#qFjo7'FZFenF^oFhsFjo7'FZFenF^o"#GF\pF,,
I)genBasisw,6)F]zF`pFbvFepFapFbpFcp6/%$rndGFaal%#EBGFbalFdal%$nB1G%#bvG%"kG%"aG
%#nvG%#wtGF`r%"iG6"F,C,>F/,$-%%randG6#;Fbw"%+5#FWFgel>FC<">Fg[lF\q>8--F`q6#Fas-
%*randomizeGF,>Fez7#-%$seqG6$-%&roundG6#-F/F,/80;FWF]fl>8+-&%$maxG6#%&indexG6#-
FE6$w,Fb\lF,6$FbrFcrF,,&F4FW*&-F`^lF,FW$FgyFbwFenFWF,F,6$FfdlF/6#FW6$7'FZFenFiu
"#QFhn7'FZFenFiuFeuFhnFez>8,&Fas6#F_gl?(F,FWFWF,2Fg_lF`sC*-%'minus=G6$Fg[lFC>F[
_l-F^al6%FCFg[lFas>F]\l-%&unionG6$F4FC>8.w,Fb\lF,6$FbrFcrF,,*-Fbx6%-%#inGFh\lFW
FbwFW-Fbx6%-F]jl6$*&Fi\lFWF4FWT'FWFbwFW-%$addG6$*&&T)6#T+FW-Fg\l6$F4&T.FjjlFW/F
[[m;FWT/FW*&-T1F,FWF]hlFenFWF,F,62F]zF4F[elFehlFgdlF]\lFidlFezF^elF\glFepFasF\e
lF]flFfdlF/6#FW6$7'FZFenFcuFgyFhn7'FZFenFcuFiclFhn>F\_l-%%sortG6$7#-FQ6#F[_lw,6
$Fc\l%"yGF,6$FbrFcrF,1-F`^lF[q-F`^lFaqF,F,6$F]elFfil6#""#6$7'FZFen"#HF[oFhn7'FZ
FenF^]m"#NFhn>6$8/F\gl6$&F\_lFjsFW?(F,FWFWF,34-F]p6&7$-FQFUFc]mF^xF__lFj[l2F\gl
-F`q6#F\_lC$-%#+=G6$F\glFW>Fc]m&F\_l6#F\gl>FC<$F\^mFc]mOFCF,F,F,6#F[`l677'FZFen
"#6FgnFhn7'FZFenFjnFhsF\o7'FZFenFhnFguFjo7'FZFen"#\"#cFjo7'FZFen"#x"##*Fjo7'FZF
enF^oFcuF\p7'FZFenF^oFhnFjo7'FZFenF^oFjoFjo7'FZFenF^oFfnFjo7'FZFenF^oFd`lFa`l7'
FZFenF[`lFh^lF\p7'FZFenF[`lFboFjo7'FZFenF[`lF_]lFjo7'FZFenF[`lFgyFjo7'FZFenF[`l
F\alFjo7'FZFenF[`lFj`lFjo7'FZFenF[`lFcyFa`l7'FZFenF]_m"#<F\p7'FZFenF]_m"#@Fjo7'
FZFenF[`lFe`mFjo7'FZFenF^oF]_mFjuF,,
I*readBasesw,F$6%%#stG%$QBsGF)6"F,C)>F/FW>FC7">F]\l-F16$Q)bases/b_F,F4@$4-F96#F
]\lY6$F@F]\l?(F,FWFWF,0F/FbwC$>F/-%)readlineGFiam@$F]bm>FC7$F\^m-%&parseGF=-Fa[
l6$Q@%a~quotient~space~bases~loaded|+F,Fg_lOFCF,F,F,6#FW6.Fby7'FZFenFjnFe^lF\o7
'FZFenFh^l"#EFjo7'FZFenF^]m"#bFjoF]oFaoFj_mF``m7'FZFenF[`l"#eF`o7'FZFenFiuFa_mF
jo7'FZFenF^oFacmF\p7'FZFenF^oFcuFjuF,,
I,basisFinderw,6'F%>'%-deg_over_minG%*nonnegintGFbw>%%modeG%'APPENDG>'%0number_
of_basesG%'posintGFgy>'%-prime_numberGFddm"&\F$6.FcpF*FepFbpFapFbvF]zF`p%#BBGFa
alF)%#fdG6"F,C.>F/-%*prevprimeG6#,&F^xFWFWFW>F_glFaam>FfilFcam>6$FCF]\l-F"Faq>F
g[l-%%tdegG6#-FQFiam>F[_l-&Ffr6#%&BasisG6%FCFg[l/F]sF/>F\_l-F`q6#&-&Ffr6#%*Norm
alSetG6$F[_lFg[lFjs>6$FezF_gl-Fhy6)FCF\_lF]\lF[_lFg[lF/F\q>Fehl-Fbx6%/F`sF`dm-F
h`mFaqFaam>Fc]m-%&fopenG6$FfilF`s?(F,FWFWF,2-F`q6#FehlFasC$>F]fl-Fbdl6)FezF_glF
\_lF]\lF[_lFg[lF/@$4-%'memberG6$F]flFehlC%>Fehl7$-FQF]hmF]fl-%(fprintfG6%Fc]mQ$
%a|+F,-Fjq6$F]flFis-Fa[l6$Q0%d%%~completed|+F,-Fhfl6#,$*&F\hmFWFasFenFgy-%'fclo
seG6#Fc]mF,F,F,6#FW64FY7'FZFenFjnFioF\o7'FZFen"#o"#uFjo7'FZFen"#%)"$5"Fjo7'FZFe
nF^o"#IFjo7'FZFenF^oFj`lFjoF_`l7'FZFenF^oFgoFjo7'FZFenF^o"#gFjoFgjm7'FZFenF^oFi
uFjoFj_m7'FZFenF[`lFa_mFjo7'FZFenF[`lFcuF`o7'FZFenF]_mFf^lFjo7'FZFenF]_mF[oF\p7
'FZFenF]_m"#tF\p7'FZFenF^oFcyF\pF,,
I*writeGfanw,6$F%>FfdmFhdm6&FcpF*FepF[em6"F,C(>F/-F`em6#,&F\qFWFWFW>Fg[l-Fhgm6$
Q)gfan/igfF,%&WRITEG>FfemFgem>FC-%$modG6$-FE6$FG-Fjq6$FCF_[lF/-F\im6'Fg[lQ+Z/%a
Z%a|+%aF,F/F]\lFC-Fiim6#Fg[lF,F,F,6#FW6)FbyF]jm7'FZFen"#^"#!)FjoFdjmFh_m7'FZFen
F^oF^`lF\pFa[nF,,
I)readGfanw,6#'F)F'6'F`zF[am%"nGFcpF^el6"F,C*>F/F\w>FCFW>F]\lFbw@$4-F9FaqY6$F@F
4>FC-FabmFaq>Fg[l-Ffbm6#&FC6#;F^o,&-&%,StringToolsG6#%.FirstFromLeftG6$Q"[F,FCF
WF]uFW?(F,FWFWF,0FCFbwC$>FCFg^n@(5/FCQ#|fr|frF,/FCQ"|frF,C%>F/Fcq-Fb^m6$F]\lFW>
(FapF]\lFaam3F/0&FC6#FenQ"|hrF,>Fe`n7$-FQ6#Fe`n&FC6#F\u3F//Fh`nFj`nC$>Fe`nF\an>
F/F\wO6%Fg[l7#-Fefl6$-FE6$Ffbm(FapF[_l/F[_l;FWF]\l7#-Fefl6$-FE6$w,Fb\lF,6$FbrFc
rF,-Ffbm6#&F46#;FW,&-F`_n6$Q"+F,F4FWFenFWF,F,F,6#FW6$7'FZFenFb_m"$2"Fhn7'FZFenF
b_mFccmFhnF]bnF^bnF,F,F,6#FW64F\_m7'FZFenFjnF_]lF\o7'FZFenFj`lF\oFjo7'FZFen"#LF
ioFjoF]oFao7'FZFenF^oF\pFjo7'FZFenF^o"#fFjoFj_mF``mF\[n7'FZFenF]_mFiuFjoFb`m7'F
ZFenF]_mF\pFjo7'FZFenF]_mFioFjoF`dn7'FZFenF]_mFj`lFjo7'FZFenF^o"$C"FjuF,,
I(writeCMw,6$F%>FfdmFhdm6*%$Ws0GFcpF)F[emF*%#sFGFep%#WsG6"F,C7>FCFj[n>F]\l-F16$
Q+weights/w_F,F4>F/-%,readWeightsGFiam>F_gl-&Fa_n6#%.SubstituteAllG6%-Fhen6%-Fj
q6$F/F'Fe_nQ"(F,Q"]F,Q")F,>6$F[_lFezFgem>Fez-Fjq6$FezF'>F\_l-Fjq6$-Fe\n6$-FE6$F
GF[_lFCF'>Fg[l-Fhgm6$Q'cm/icmF,Fa\n-F\im6'Fg[lQ<Ws~=~%s;|+pp~=~%a;|+vr~=~%s;|+F
,F_glFCFez-F\im6%Fg[lQ6f~=~openOut~"cm_%s";|+F,F4-F\im6$Fg[lQ<f~<<~toString(pp)
~<<~endl;|+F,-F\im6$Fg[lQ<f~<<~toString(vr)~<<~endl;|+F,-F\im6%Fg[lQ9for~i~from
~0~to~%a~do~(|+F,,&Fd[lFWFenFW-F\im6$Fg[lQ>f~<<~toString(Ws#i)~<<~endl;|+F,@%-%
$hasG6$F[_l^#FW-F\im6%Fg[lQ9R~=~ZZ/pp[I]/(I^2+1)%s,~F,&FezF`an-F\im6%Fg[lQ.R~=~
ZZ/pp%s,~F,F^in-F\im6$Fg[lQDMonomialOrder~=>~Weights~=>~Ws#i];|+F,-F\im6%Fg[lQ0
J~=~ideal(%s);|+F,&F\_l6#;F[]mF]u-F\im6$Fg[lQVG~=~gb(J,ChangeMatrix=>true);|+M~
=~getChangeMatrix~G;|+F,-F\im6$Fg[lQ>f~<<~toString(M)~<<~endl;|+);|+F,-F\im6$Fg
[lQ,f~<<~close;F,F^]nF,F,F,6#FW6:7'FZFenFfoFgnFhn7'FZFenFfnFa`lFjo7'FZFenF[oF_o
FjoFfjm7'FZFenF^o"$/"FjoFdjm7'FZFenF^oF\oFjoFgjmFdjm7'FZFenF^o"#hF\p7'FZFenF^oF
[oF\p7'FZFenF^oF`oF\pF_[oFecmF^[o7'FZFenF^oFjnF`o7'FZFenFe`m"#sF\p7'FZFenFd`lF
\alF\p7'FZFenF^o"#`F\pF``l7'FZFenF^oFb[oF\pF[alF`dlFa[nF,,
I'readCMw,F$6)F[amF)FcpFepF`rF[^nF^el6"F,C,>F/FW>FC-F16$Q'cm/cm_F,F4>F[_lFbw>F
\_lFbw@$4-F9FUY6$F@FC>F]\l-Ffbm6#-FabmFU>Fg[lFi\o?(F,FWFWF,F]bmC$>F/F[]o@&3F]bm
/&F/FjsF`fnC$-Fb^m6$F[_lFW>(%"TGF[_l&F/Fiin3F]bm/&F/6#;FWFgnQ'matrixF,C$-Fb^m6$
F\_lFW>(%#CMGF\_l-Fhen6%-Fhen6%&F/6#;FjnF]uF_`nFe_nFj`nFafn-Fa[l6$Q;%d~change~m
atrices~loaded|+F,F\_lO6%F]\l7#-Fefl6$-%%wdegG6$7#-Ffbm6#(Fi]oFezFg[l/Fez;FWF[_
l7#-Fefl6$)-%'MatrixG6#7#-FE6$Ffbm(Ff^oFez%#%TG/Fez;FWF\_lF,F,F,6#FW647'FZFenFj
nFgnFhnF]cm7'FZFenFh^lFguFjo7'FZFenFacmF][oFjo7'FZFen"#j"#pFjoF]oFao7'FZFenF^oF
f^lFjo7'FZFenF^oF^]mFjoFj_mF``mF\[nFb`mF][nFb`m7'FZFenF]_mFjjnFjo7'FZFenF^oFguF
\p7'FZFenF^o"#**FjuF,,
I(getTordw,6$%#gbG%#lmG6.FepF\elF^elFjdl%$sbtG%%degsG%'gbdegsG%'lmdegsG%&ineqsG
%$solG%(weightsG%"gG6"F,C,>F/7#-FQ6#-FTFaq>FCFd[l>F[_l/7#-%"$G6$FbwFC%%NULLG>F
\_l7#-Fefl6$(F_zF]\l/F]\l;FWFC>Fez-FE6$w,6#%"zGF,6$FbrFcrF,-FE6$w,Fb\lF,6$FbrFc
rF,-FE6$w,6#F^zF,6$FbrFcrF,-Fg\l6$FjrF4F,F,6$Fc\lF46#FW6$7'FZFenF\oF[oFhn7'FZFe
nF\oFhsFhnF`^lF,F,6$FepF`^l6#FW6$7'FZFenFj`l"#aFhn7'FZFenFj`lF_cmFhn-Fjq6$F4Fis
F,F,6$FepF/6#FW6$7'FZFenFc`mF`[nFhn7'FZFenFc`m"#>FhnF4>F_gl-FE6$w,Fb\lF,6$FbrFc
rF,-FE6$w,F]eoF,6$FbrFcrF,F_eoF,F,Faeo6#FW6$7'FZFenFj`lF[dlFhn7'FZFenFj`lFf^lFh
nF`^lF,F,F^fo6#FW6$7'FZFenFc`mF[oFhnFbfoF\q>Fehl<#-Fefl6$-FQ6#-FE6$w,Fb\lF,6$Fb
rFcrF,1FW-FejlFh]lF,F,6$FbboF\_l6#FW6$7'FZFenFj`lFguFhnF[fo-%%subsG6$F[_l7#-Fef
l6$,&&F_glF_]nFWFc]mFen-F]jl6$Fc]m&FezF_]n/Fg[l;FWF_q>F]fl&-&%-OptimizationG6#%
)MinimizeG6&-FejlF_^mFehl/%+depthlimitGF[dl/%'assumeGF]dm6#F[]m>Ffil-Feho6$F]fl
F\_l6$Ffil-Fg_o6$FfilF/F,F,F,6#F[]m6-Ffjn7'FZFenFjnFesF\o7'FZFenF`]mFdoFjo7'FZF
enF]dn"#zFjo7'FZFen"#")"$3"Fjo7'FZFenF^o"#yFjo7'FZFenF^oFjuFjo7'FZFenF^oFccnFjo
7'FZFenF^oFfsFjo7'FZFenF^oFadlFjo7'FZFenF^oFejmF\oF,,
I,readWeightsw,Fh]n6$F[amF[en6"F,C(>F/FW>FCFaam@$Fb^nYFe^n?(F,FWFWF,F]bmC$>F/Fg
^n@$F]bm>FCFdbm-Fa[l6$Q:%a~weight~vectors~loaded|+F,Fg_lFCF,F,F,6#FW6-FYF]cm7'F
ZFenFh^lFeuFjoF]oFaoFj_mF``m7'FZFenF[`lFb_mF`o7'FZFenFiuF[oFjoF[al7'FZFenF^oF`y
Fd`lF,,
I-writeWeightsw,6'F%>F_dmF`dm>'%2number_of_weightsGFddmFgy>FfdmFhdm>'%+rand_ran
geG7$FddmFddm7$"$+#"$+)60Fcp%#GsG%$LMsG%#WWG%%gffnGF)F[emF^el%"WGF*FepFfdlFbpFa
p6"F,C&>F/-F`em6#,&FasFWFWFW>F[_l-F16$Q)gfan/gf_F,F4>F\_lF`en@%-F9Fa\mC(-Fa[l6#
QJGenerating~weight~vectors~from~Gfan~file|+F,>6%F/FCF]\l-Ff]nFa\m>Fg[l7#-Fefl6
$&-F[bo6$&FCFghl&F]\lFghlFjs/F_gl;FWFg_l>Fez-Fhgm6$F\_lFa\n?&FehlFg[lFcq-F\im6%
FezF^imFehl-Fiim6#FezC+-Fa[l6#Q5Gfan~file~not~found|+F,-Fa[l6$QEGenerating~%a~r
andom~weight~vectors|+F,F`s>6$F]flFfilFgem>Fc]m-Fdel6#;&F^xFjs&F^xF^joF`fl>Fg[l
-Fbx6%/F\qF`dm-FeenF_^mFaam>Fez-Fhgm6$F\_lF\q?(F,FWFWF,2-F`qF_]nF`sC&>F\gl-Fg_o
6$7#-Fefl6$-Fc]mF,/F_gl;FW-F`q6#FfilFfil>81-F_fm6%F]flF\glFcfm>Fehl&-F[bo6$F_cp
-&Ffr6#%0LeadingMonomialG6$F_cpF\glFjs@$4-Fehm6$FehlFg[lC%>Fg[l7$-FQF_]nFehlFd`
p-Fa[l6$Fcim-Fhfl6#,$*&FabpFWF`sFenFgyFf`pF,F,F,6#FW6>FhclF]jm7'FZFenFacm"#$)Fj
o7'FZFen"#')"$9"FjoF`[o7'FZFenF[`lFccmF\p7'FZFenF[`lF`]mFjo7'FZFenF[`lF]dnFjo7'
FZFenF[`lFadlFjo7'FZFenF[`lFc]nFd`l7'FZFenF_]lFjoF\p7'FZFenF[`lFe^lF\p7'FZFenF[
`lFboF\p7'FZFenF[`lFb[oF\p7'FZFenF[`lFhsFjoFg`l7'FZFenF[`lFc`mF\p7'FZFenF[`lFdo
Fjo7'FZFenF[`lFf^lFjoFa`m7'FZFenF]_mF]dnFjo7'FZFenF]_mFccmFjo7'FZFenF]_m"#kFjo7
'FZFenF]_mFc`mF`o7'FZFenFiclF\oFjo7'FZFenFiclFhnF\p7'FZFenFiclFjjoF\pFfepF,,
I)saveDataw,6-F%'%$mxnGFg]p'%#spG%(numericG'FcpFddm'Fep<$FisF_[l'%#avGF[cl'Fbp%
3ShortMonomialOrderG'%#QBGFis'%'shiftsGFis'%%polsGFis'%$stdG%(booleanG6'F)F[em%
%mxn0G%$sp0GF`z6"F,C&>F/-Fbx6%9.-F16$Q1templates/t_std_F,F4-F16$Q2templates/t_n
std_F,F4>F[_lF\w@%F8C'>FC-Fhgm6$F/%%READG>F]\l-Ffbm6#-FabmF=>Fg[lFdip@$52&F\qFj
s&F]\lFjs3/F[jpF\jp2Fg[lF`s>F[_lFcq-FiimFU>F[_lFcq@$F[_lC%>FC-Fhgm6$F/Fa\n-F\im
6.FCQ>%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%aF,F\qF`sFas-Fjq6$F^xFisF__lFj[l9+9,
9-FaamFajpF,F,F,6#F]_m61F\_m7'FZFenFjnF^epF\o7'FZFenFjjn"$<"FjoF`[oF\fp7'FZFenF
[`lFjcnFjo7'FZFenF[`lFesFjo7'FZFenF[`l"#()F`o7'FZFen"#nFjjoFjoFfep7'FZFenF[`lFc
foFjoF`[oFcep7'FZFenF[`l"$D"F\pFfepF,,
I)readDataw,6$F%Fjgp6.F)F[emFifpF[gpFcpFepFagpFbpFegpFggpFigp%$xE0G6"F,C1>F/-Fb
x6%F\qFfhpFihp@$F7YF?>FCF`ip>F]\lFdip>Fg[lFdip>F[_lFdip>F\_lFdip>FezFdip>F_glFd
ip>FehlFdip>F]flFdip>FfilFdip>Fc]mFdipFajp6,F]\lFg[lF[_lF\_lFezF_glFehl-FE6$FIF
]flFfilFc]mF,F,F,6#F[]m63F\_mFb[qF]oFaoFjjmFc[pFeaoFeaoFfaoFeaoFfaoFeaoF[[oFfao
Fc[pFa[n7'FZFenF^oF`fpF\oF,,
I,eigenSolverw,6#'F*-Fis6#%(polynomG6/Ffdl%%fB2CGFepFbpFapFaalFbvFagpF^zFi]o%"V
GFfp%#SrG6"F,C1>F]\lF\co>Fg[lFiem>F/,$-Fdel6#;!%+5FgelFhel>FCw,6%'%"fGFa^q'FepF
is'FaalFisFd]l6"F,C$>F/-%&tableG6#-%$zipG6%w,6$F[elFealF,6$FbrFcrF,/F\qF4F,F,F,
6#F[]m6$7'FZFenFadlFbhlFhn7'FZFenFadlFhsFhn7#-%'coeffsG6%F4F\q.F`r7#F`rO-FE6$w,
6#FealF,6$FbrFcrF,-Fbx6%-%)assignedG6#&F`^lFaqFiaqFbwF,F,6$Fe]lF/6#FW6$7'FZFenF
h^lFa_mFhn7'FZFenFh^lF\pFhnF`sF,F,F,6#F^o6%7'FZFenF]_mFfoFhn7'FZFenFcuF_jmF\o7'
FZFenF[`lFe[oFju@$4-F_bl6$F4F_^qYQQThe~case~of~non-polynomial~system~is~not~han
dledF,>F[_l-F_fm6$F4Fg[l>F\_lFgfm>FezF^^m>F_gl-Fejl6$*&FehlFWFjflFW-F]jl6$FehlF
]\l>F]fl-&Ffr6#%5MultiplicationMatrixG6'F_glF\_l-F[`q6#-&F[^l6#%"=G6%F\_lF_^l7#
-Feco6#;FWFezF[_lFg[l>Ffil&-&Fbt6#%-EigenvectorsG6#-%&evalfG6#F]flF^jo>Ffil-Fhb
l6%FfilF_^l-%".G6$-%'VectorG6$Fez/%%fillGFW&FfilFjs>Fc]m-Fdeq6$-Fd`o6#-FE6$w,F]
eoF,6$FbrFcrF,-F[[m6%-Fer6%F4F`^lFi\lFcjlFijlF,F,6,FapF[_lFbpFg[lFepF]\lFaalF\_
lFc^qFC6#FW6$7'FZFenFcfoF^dlFhn7'FZFenFcfoF_]lFhnF]\lFfil>F\gl-%#ReG6#&Fc]m6$F^
u-F_\l6$w,6#%"cGF,6$FbrFcrF,-%'andseqG6$-F\t6$&F`^l6$F^elF4%%realG/F^el;FW-FQ6$
7$FWFWF`^lF,F,6$FfpFc]m6#FW6$7'FZFenFeuF^dlFhn7'FZFenFeuFf^lFhn7#-Feco6#;FW-FQ6
$7$FWF[]mFc]mOFb]mF,F,F,6#FW63FY7'FZFenF\pFguFjo7'FZFenF`oFcoFjo7'FZFenF^oFesFj
o7'FZFenF^oFfoFjo7'FZFenF^o"$."F`o7'FZFenFbhl"#%*FdoF[[o7'FZFenF^oFbhlFjo7'FZFe
nF^oFe^lFjo7'FZFenF^oFjcnFjo7'FZFenF^oF`jmFjo7'FZFenF^oF[oFjoFg_m7'FZFenF^oF\[p
Fjo7'FZFenF^o"#$*Fjo7'FZFenF^oFiclFjuF,,
I$srtw,6$'Ffal<%FgeqFisF_[lFbgpF,6$FbrFcrF,-F]\m6$F4w,Fc\mF,6$FbrFcrF,-&Ffr6#%*
TestOrderG6%F\qF4FjrF,F,6$FbpF\q6#F[]m6$7'FZFenF`fp"$-"Fhn7'FZFenF`fp"#rFhnF,F,
F,6#F[]m6$7'FZFenFgnF[jqFhn7'FZFenFgnFacmFhnF,,
I%suppw,6$Fd_qFepF,6$FbrFcrF,<#-FQ6#-F\[l6$-FGFaqF\qF,F,F,6#F[]m6$7'FZFenF[`l"#
dFhn7'FZFenF[`lFc`mFhnF,,
I%Suppw,6$F*FepF,6$FbrFcrF,<#-FQ6#-FE6$FQ-F\[l6$F4F\qF,F,F,6#F[]m6$7'FZFenF[`lF
ccmFhnF_]rF,,
I,poly2matrixw,Fb]r6$Fi]oFaal6"F,C%>F/-FE6$w,6#%#plGF,6$FbrFcrF,-F[`q6#-F^`q6%w
,Fa`qF,6$FbrFcrF,Fc`qF,F,F,6#F[]m6$7'FZFenFesFguFhn7'FZFenFesFbhlFhn7#-Fj`q6%F4
Fjr.%#mnG7#Fh_rF,F,6$FepF\q6#FW6$7'FZFenFh^lF_oFhn7'FZFenFh^lFe`mFhnF4>FC7#-FQ6
#-F`]rFj]rO6$-Fd`o6#-FE6$w,Fd]lF,6$FbrFcrF,-FE6$w,FbaqF,6$FbrFcrF,-Fbx6%-Fgaq6#
&FjrFaqFdarFbwF,F,6$Fe]lF46#FW6$7'FZFenFadlF]dnFhn7'FZFenFadlFejmFhnF`^lF,F,6$F
aalFC6#FW6$7'FZFenFe`mFcaoFhn7'FZFenFe`mFiuFhnF/-FgeqFUF,F,F,6#F[]m6&FY7'FZFenF
jnFjjoF\o7'FZFen"##)"$0"Fjo7'FZFenF^oFjjoFjuF,,
I/permuteColumnsw,6%F`pFd^q%#V1G6#Fh_r6$FbrFcrF,&F46$F^u7#-Fefl6$-&%*ListToolsG
6#%'SearchG6$F/F\q-F]jl6$F/F`sF,F,F,6#F^o6&7'FZFenFc`mF^epFhn7'FZFenF^]mF`]mFd`
l7'FZFenFc`mFadlFhnF]drF,,
I)sparsityw,6#'F`pFd`o6#%&numzrG6"F,C$>F/-F`q6#-F_\l6%F`dqF\foFbwO*&F/FW-%$mulG
6#-FQ6$FWF4FenF,F,F,6#FW6%F\_m7'FZFenFjnFacmF\o7'FZFenF^oFadlFjuF,,
I(matrixSw,6'Faal%#B0GFapFbpFcp6%Ffp%#V0GFbv6"F,C&>F]\lF_q@$0-F`qF[qF]\lYQIlist
s~B0~and~B~must~have~the~same~lengthF,>Fi_l-Fgq6$-FE6$w,FbaqF,6$FbrFcrF,FdrF,F,
F]x6#FW6$7'FZFenFadlF\[pFhnFiarF4Ffv@%/-FQ6$FWFCF]\lO-Fgbr6%F/FC-FgeqF[qYQ=fail
ed~to~construct~matrix~SF,F,F,F,6#F`y6*Ffjn7'FZFenFe^lF^]mFjo7'FZFenF^oFbjmF`o7
'FZFenFf^lF_oFdo7'FZFenF^o"#(*FjoF`[o7'FZFenF[`lFgoFju7'FZFenF[`lFjoFdoF,,
I*quotientsw,6&FhboFapFbpFcpF,6"F,C$-Fer6'F4F\qF`s.%"QG/F]sFasOFjhrF,F,F,6#F`u6
%Fby7'FZFenF^oFccmF\pFg`mF,,
I-monPartitionw,6'Fagp%#GrGFbpFcp>FegpFaam6-FjerFaal%#aBG%"RG%#B2G%#RBGFap%#nGG
Fi]oFfpF^el6"F,C->F/&-Fifm6$F\qF`sFjs>FC-Fjq6$-Fbx6%/F^xFaamF/F^xF_[l>F]\l-Fj]l
6%F4F_^lFC>Fg[l-Fgjq6$-Fjq6$-Facl6$F]\lFCFisF`s>F_glFabp>F[_l-Fhbl6%-F^clF`[sF_
^lF4>FC7$-FQ6#-Fgjq6$-Fjq6$-Facl6$FCF[_lFisF`s-FQ6#-Fgjq6$-Fjq6$F[_lFisF`s>6$F
\_lF]\l6$7$FbdpF\^mFhjr@%Ffjr>Fehl-Fgcq6(F4FC-F[`q6#-%'EquateG6$FC7#-Feco6#F_`p
F\qF`sF[irC%>Fehl-Fgcq6(F4F/-F[`q6#-Fa]s6$F/7#-Feco6#;FWFd[lF\qF`sF[ir>F]fl-Fge
r6'FCF/F\qF`sFas>Fehl-Fbx6%0FasFbw-Fe\n6$-Fdeq6%F]flFehl-&Fat6#%(InverseG6$FasF
]flFas-Fdeq6%F]flFehl-&Fbt6#%.MatrixInverseGF_eq>Fez-Fjq6$,&-FgeqF_]nFW-Fdeq6$&
Fehl6$;FWF_glF^uF_brFenFisO6(F]\lFCF\_lFehlFez-Fd`o6#7#-Fefl6$-Fbhr6&&FezF]cpF
\qF`sFas/FfilFa`sF,F,F,6#F`y62Fhcl7'FZFenF^oF[dlFjo7'FZFenF^oFguFjoFi_mFh_m7'FZ
FenF^oFiclFjoFfao7'FZFenF^oF\epFjoF_dlF`[o7'FZFenF[`l"$6"Fjo7'FZFenF[`lF_epFjo7
'FZFenF[`lFioFjo7'FZFenF[`l"$7"Fjo7'FZFenF^oFb_mFjoFfbrF,,
I)matrixHiw,6&F*FapFepFcp62%*undetPolyG%#pvG%#nFGFjir%#uHG%%leqsGFfboF^el%#dFG%
#dGGF_zFaz%"hG%"jG%"pGFjdl6"F,C)>FC-FejlFgv>F]\lF_q>Fg[lFbfr>Fehl-FE6%Fg\lF4F`s
>F/w,6&FepF_bsF_zFfbs6#%%monsG6"F,C%-Fj`q6%-FG6#,&FWFW-Fejl6$)F\qF`^l/F`^l;FWF`
sFWF4.F/>F/7#F/-Fejl6$*&&F/6#Fi\lFW&%#_vG6$FasFi\lFW/Fi\lFa^sF,F,6&Fgbs82Fjdl83
6#F`u6&7'FZFenFe^lFfoFhn7'FZFenF[`lF^]rF\p7'FZFenF[`lF\pFjo7'FZFenF[`lFa`lF\p?(
F_glFWFWFg[lFcqC%>6$Fc]mF]fl6$Fbw-FE6$w,Fb\lF,6$FbrFcrF,-Fbgl6$FbwF4F,F,F,6#FW6
$7'FZFenFf^lFbhlFhn7'FZFenFf^lF^]mFhn,&7#-Feco6$-Fg\l6$&F\qFghlF`sF]\lFWFehlFen
?(FfilFbwFWF,1,&FfilFWFc]mFenFbwC&>F[_l7#-Fefl6$-F/6&F`sFC,&&F]fl6#F_cpFWFfilFW
F_cp/F_cpF_bn>F\_l<#-Fj`q6$-FG6#,&F\gsFen-Fejl6$*&&F[_lFigsFW&F4FigsFWFjgsFWF`s
>Fez-%'msolveG6$F\_lFas@$/-F`q6#<#FezFbw>Fc]m,&FfilFWFWFW>&F\glFghl-Fe\n6$-FE6%
-Febl6$FGFIF[_lFezFasO-F^w6#-Fefl6$-&Fgeq6#%$rowG6#Fcis/F_gl;FWFg[lF,F,F,6#F`u6
2F\_m7'FZFenF\pFhsFjo7'FZFenFboFa_mFjo7'FZFenFjuF`fpFjo7'FZFenFfsFcjmFjoFiiqFc`
l7'FZFenF[`lF\\rFjo7'FZFenF[`lFcyFd`l7'FZFenF]_mFcaoFjo7'FZFenF]_mFb[oFjo7'FZFe
nF]_mFjcnFjo7'FZFenF]_mFe[oF`o7'FZFenFjcnF`oFjoFg`l7'FZFenF^oFguFjuF,,
I*matrixHniw,6(F*Fap%"CGFf^oFepFcp6-%,undetPolyniGF`bsFjir%#H0GFabsFbbsFfbo%%pa
rsGF^elFfbsFjdl6"F,C+>FCF_q>F]\lFbfr>F/w,6&FebsFepF^elFfbsFdcs6"F,C%-Fj`q6%F4F
\qFbds>F/Fdds-Fejl6$*&&F/6#F`^lFW&F[es6%F`sFasF`^lFW/F`^lFa^sF,F,6$FjdlFfil6#F`
u6&7'FZFenFh^lFfoFhn7'FZFenF[`lF^]mF\pFees7'FZFenF[`lF[oF\p>Fg[l-Fe\n6$-FE6$FG-
Fdeq6$F`sFasF__l>F[_l-Fd`o6%F]\lFCw,6$F^elFfbsF,6$FbrFcrF,-Fcjl6&&F`^lFj]rF[sF4
F\qF,F,6(Fj[tFg[lFepF^xFi[tF/6#F[]m6$7'FZFenFj`l"#iFhn7'FZFenFj`lFejmFhn>F_gl<#
-Fefl6$&%#_uGF]hm/Fehl;FW-F`q6#-Facl6$-FTFa\mF^x>F\_l-FE6%Fj`q<#-Fefl6$-Fe\n6$-
FG6#,&&F\qF]hmFen-Fejl6$*&&F[_l6$FehlF]flFW&F4F_eqFW/F]flF^doFWF__l/FehlF_bnF^x
>Fez-Fihs6%F\_lF_glF__lO-Fe\n6$FfisF__lF,F,F,6#Fgn6,Fby7'FZFenF_]lFhsFjoFijsFii
qF`jq7'FZFenF^oFcaoFjoFias7'FZFenF^o"#&*FjoF[[oFc[tF,,
I*syzModulew,6''F*F[[r'FapFis'%"AGFd`oFbgp'FcpF]dm6,F`bsFjir%"eG%"LG%#LtGF`pFfp
FaalF^elFfbs6"F,C.>F/F_q>FCFbfr>F]\l-Fefl6$-Fgeq6$FC<#/FehlFW/FehlF^do>Fg[l7#-F
efl6$7#-&Ffr6#%,LeadingTermG6$Fd`tFasF`ct>F[_l-FE6$w,Fb\lF,6$FbrFcrF,*&&F4FjsFW
&F4F^joFWF,F,F,6#FW6$7'FZFenFcuFj`lFhnFj[mFg[l>F\_l-Fd`o6$FCw,Fa^tF,6$FbrFcrF,*
&-%$lcmG6$&FiaqF^jo&&F`^lF[qF^joFW&Fi\lFaqFenF,F,6&FcbtFg[lFdbtF[_l6#F[]m6$7'FZ
FenFcfoFe[oFhn7'FZFenFcfoF_cmFhn>Fez7#-Fefl6$-Fefl6$,(*&&F\_lFi`tFW&F]\lF]hmFWF
W*&&F\_lFfhmFW&F]\lF_eqFWFen-F^w6#-Fbhr6&z'6&F`ftFcftFd`t&F\qF_eq[[[\[[[[[\[[mF
W\[[[[[\[[[[[mFenF\qFasF^xFen/F]fl;,&FehlFWFWFWFCF`ct>Fez)-Fd`oFg`pFj`o>F_gl-Fd
`o6#7#-Fefl6$-Fbhr6&&F4F]hmF\qFasF^x/Fehl;FWF/>Fez-FE6$FG-F^w6$-Fdeq6$FezF`s,&-
&Fbt6#%/IdentityMatrixGF=FW-Fdeq6$F_glF`sFen@$Fdx>Fez-Fe\n6$FezF^xO&Fez6$-%'rem
oveG6$w,6#F^elF,6$FbrFcrF,-&%+ArrayToolsG6#%'IsZeroG6#&F`^l6$F4F^uF,F,6$FfpFez6
#FW6$7'FZFenFcfoFa_mFhn7'FZFenFcfoFe`mFhn7#-Feco6#;FW-FQ6$FfhqFezF^uF,F,F,6#F`y
60Fby7'FZFenFjnFe`mF\oFi`lF^jq7'FZFenF^oFccmFjoFc[p7'FZFenF^oFjeoFjo7'FZFenF^o"
$A"Fjo7'FZFenF^oFh^lFjoF\dn7'FZFenF^oFcoFjoFjcl7'FZFenFcfoFesFjo7'FZFenF^o"#wFj
uF,,
I+matrixHsyzw,6(F\btF]bt'Fg[tFd`oF^btFbgpF`bt6$Ffp%&ThetaG6"F,C%>F/-Fiat6'F4F\q
FasF^xF__l>FC-Fd`o6%-FQ6$FfhqF`s-FQ6$FfhqF/w,Fa^tF,6$FbrFcrF,&Fe]lFj]rF,F,F,6#F
[]m6$7'FZFenF`oF^]rFhn7'FZFenF`oFc]nFhnO-Fe\n6$-FE6$FG,&F[^tFW-Fdeq6$FCF/FWF__l
F,F,F,6#Fgn6&Fbu7'FZFenF^oF`]mFjoF^[u7'FZFenF^oFjoFjuF,,
I,fixTemplatew,6'%'admonsGF*Fep%$monGFiir60F`bs%%monFG%&admonGF^elFfbsFjhrF`z%#
xFGF`pF\frF]zFd^q%%mon1GFh_r6"F,C.>F/Fbfr>FC-FE6$w,6#Fd_qF,6$FbrFcrF,-Fa\rFh\lF
,F,6$FepF`s6#FW6$7'FZFenFhnFc]nFhn7'FZFenFhnFbhlFhnF\q>F]\l7#-Feco6$FjelF/?(Fg[
lFWFWF_qFcqC%>FezF\w?(F[_lFWFWF/FcqC$>F\_l-FE6$w,6#%#mfGF,6$FbrFcrF,-Fbx6%-%'di
videG6%&FjrFidsF4.%"qGF\auFgcoF,F,6&F_^uF4F^elFg[l6#FW6$7'FZFenF\pF`fpFhn7'FZFe
nF\pFiuFhn&FCFa\m@$0F\_lFjelC%>&F]\lFa\m<$Fe]m-FQ6#Fgau>FezFcq[@$4FezYQ;failed~
to~correct~templateF,>F\gl7#-Fefl6$-Fjq6$-Fcil6$-Fjq6$&FasFa\mF_[lFgauFgeq/F[_l
F\ht>F_gl7#-Fefl6$-Fefl6$-FG6#*&&F\qFa\mFWF_cpFW-F]jl6$F_cp&F\glFa\mF\cu>Fi`t-F
gqFjht>Ffil-Facl6$-Fjq6$F]flF_[l-Fjq6$F^xF_[l>Ffil-Fgjq6$7#-FQF]cp-Fjem6#-FQFgv
>Fc]m-F^w6$Fgdu-FQ6#F^x-Fa[l6#Q0Template~fixed|+F,O6&F\glFehlF]flFc]mF,F,F,6#F`
y68FYF][u7'FZFenFj`lFacmFjo7'FZFenFccmF_oFjoFc`lFeesF][t7'FZFenF]_mF`jmFjo7'FZF
enF]_m"#))F`o7'FZFenFf^lFccmFjo7'FZFenF][oF`[nFjo7'FZFenF_oFbwFe[o7'FZFenF[`lFj
[qF`o7'FZFenFj`lFccmFdoF^[pF\dnFhiqFgjmFj]u7'FZFenF^oF_]lFjoF`dl7'FZFenF^oFj`lF
juF,,
I2constructTemplatew,6&%"HGF*FepFiir6+F`bsF`^uFd^uF`pF\frF]zFd^qFfbsFh_r6"F,C+>
F/Fbfr>FC-Fbx6%-F_bl6$F4Fd`o7#-Fefl6$-F^w6#-FQ6#-F`]r6$-Fjq6$&F46$F^uF_glFisF`s
/F_glF\htF4>F]\l7#-Fefl6$-Fefl6$-FG6#*&F\gsFWFehlFW-F]jl6$FehlF\`pF]hu>6$Fg[lF[
_l-Fgq6$F]\lF`s>F\_l-Facl6$-Fjq6$F[_lF_[l-Fjq6$FasF_[l>F\_l-Fgjq6$7#-FQF_^mFhdu
>Fez-F^w6$Fhiu-FQF_fl@$0-FQ6$FWFez-FQ6$FWF[_lC$-Fa[l6#Q8Template~is~incomplete|
+F,>6&FCFg[lF[_lFez-F\^u6'-Facl6$-Fjq6$FezF_[lF`iuF\qF`sFCFas6%FC-Fgbr6%Fg[lF[_
lFezFezF,F,F,6#F`u6.7'FZFenF\pFgnFhnF][u7'FZFenF^oFe_mFjoF^[uFhiqFgjmFj]uFafuF`
[o7'FZFenF[`lF[dlF\p7'FZFenF[`lFe_mFjo7'FZFenF^oF`]mF\oF,,
I-adjustParamsw,6'F*FffuFiirFepFcp65F`bsFjir%#H1G%#LmG%%colsGFcbtF`^uF\frF]zFbb
t%#smG%#rmG%#npG%#ssG%$prmGFbbsFfboFfbsF^el6"F,C3>F/F_q>FC-FQ6$FfhqF\q>F]\lF\q>
Fg[l-Fefl6$-Fgq6$-Fjq6$&F\q6$F^u85FisFas/Fe]vF\ht>F[_l7#-Fefl6$-Fcit6$w,Fb\lF,6
$FbrFcrF,-%+membertypeG6$Fddm-Fjq6$&&F`^l6#,&Fi\lF[]mFenFW6$F^uF4FisF,F,6&F^\vF
g[lFfbsFe]v6#FW6$7'FZFenFiuFf[uFhnFchl7#-Feco6#;FW-FQ6$Fbiq&Fg[l6#,&Fe]vF[]mFen
FWFf]v>6$F\_lFez6$7#-Fefl6$&Fc_v6$F^u&F[_l6#Fe]vFf]v7#-Fefl6$&&Fg[l6#,$Fe]vF[]m
6#F^`vFf]v>Ffil7#-Fefl6$-FE6$w,Fd]lF,6$FbrFcrF,-Fa\r6$-FG6#*&Fj`uFWF4FWF^sF,F,6
(F*F4FfbsFe]vFepFas6#FW6$7'FZFenFh^lFgoFhnF^bq&FezF_`vFf]v>F_gl-Fjq6$-FE6$FQ-FE
6%-Febl6$FQFjqFfilF_[lF_[l>Fehl-Fjq6$-Facl6$F_gl-Fjq6$F`sF_[lFis>Ffil-FgeqF]cp>
Fc]m-FE6$w,6#FbbtF,6$FbrFcrF,-F_\l6$w,FfitF,6$FbrFcrF,-Fehm6$FjrFbetF,F,6&FbbtF
4F`\vF`^l6#FW6$7'FZFenFiuF^`lFhnFchl<#-Feco6#;FW-FQ6$FWF`^lF,F,6$F`\vFfil6#FW6$
7'FZFenFcuFijmFhnFj[mFehl>F\gl7#-Fefl6$-%"+G6#-Fefl6$-F`q6#-F_\l6%FhhnFc]m&&Fc]
mF_`v6#86/Ffev;FW-F`q6#Fdev/Fe]v;FW-F`qFjim>F_cpw,6&F^elFfbsFa\vFb\vF,6$FbrFcrF
,52-F`q6#&F`sF[q-F`q6#&F`sFaq3/FgfvFdfv2&FasF[q&FasFaqF,F,F,6#F`u6$7'FZFenFjnFg
yFhn7'FZFenFjnFj`lFhn>F_es-F]\m6$7#-Feco6#;FWF\hmw,Fa^tF,6$FbrFcrF,-Fcjl6&F4F\q
F`^lFi\lF,F,6(Fa\vFc]mFb\vF\glFc\vF_cp6#F[]m6$7'FZFenF\oFjeoFhn7'FZFenF\oFbhlFh
n>Fehl&Fehl6#F_es?&F]flFehlFcqC+>Fg[l-Fefl6$-Fgq6$-Fjq6$&F]\lFd]vFisFasFf]v>Fg_
v6$7#-Fefl6$Fc_vFf]v7#-Fefl6$Fd`vFf]v@$/-F`q6#-FTF_^mFbw[>Ffil7#-Fefl6$-FE6$w,F
d]lF,6$FbrFcrF,F`avF,F,Feav6#FW6$7'FZFenF_]lFdoFhn7'FZFenF_]lFj`lFhnFiavFf]v>Fc
]m-FE6$w,Fb\lF,6$FbrFcrF,<#-&Fdcr6#%*SearchAllG6$FW-FE6$w,6#Fd\mF,6$FbrFcrF,-F`
q6#-F^cl6$F4<#F`^lF,F,6$FbbtF`^l6#FW6$7'FZFenFa_mFb[oFhn7'FZFenFa_mFc]nFhnF4F,F
,6$FbbtF]fl6#FW6$7'FZFenFc`mF_[pFhnFbfoFfil>F`es<#-Fefl6$-FQ6#-FE6$w,6#FjdlF,6$
FbrFcrF,-FQ6#-Fjq6$&&F`^lFidsFh^vF_[lF,F,6&FcbtF\_lFfbsFe]v6#FW6$7'FZFenFf^lFcc
mFhnFefsFdevFf]v>84-Fihs6$F`esF^x@$/-F`q6#<#F^^wFbw\>F]\l-Fe\n6$-FE6%FhisF]\lF^
^wF^x-Fcfu6&F]\lF4FasF`sF,F,F,6#F`y6?FhclF][u7'FZFenFj`lF^`lFjo7'FZFenFa`lFc]nF
jo7'FZFenF^oF`fpFjo7'FZFenF^oFd[qFjo7'FZFenF^oFbjmFjoFc[u7'FZFenF^oFacmFjoFbjqF
b[uFb_w7'FZFenF^o"#*)Fjo7'FZFenF^oFgyFjoFe_w7'FZFenF^oFcuFjoFc`l7'FZFenF[`lFdao
Fjo7'FZFenF[`lFcoFjo7'FZFenF[`lFgoF`o7'FZFenFjcnFbwFe[o7'FZFenF[`lF^dlFjo7'FZFe
nF[`lF\epFjo7'FZFenF[`lF_[pFjo7'FZFenF[`lF^]mFjo7'FZFenF[`lF^`lF`o7'FZFenF^]mFb
wFjeo7'FZFenF[`lF`oFjo7'FZFenF^oFhnF\pF,,
I4isActionMatrixFoundw,6('Fi]oFd`oFbdr'FfirFisFf_q'FjirFddmF`bt6(%#tMG%#T1GFbvF
`r%"rGFjdl6"F,C'>F]\lF^fl>Fg[l,&F]\lFWF^xFen>F/-Fe\n6$-%*GaussjordG6$F\q.F[_lF_
_l>FC-Fe\n6$-F^w6$,$&F/6$;,(F[_lFWF^xFenFWFWF[_l;,$F]\lFenF,Fen-Fd`o6%Fg[lF]\l<
#-Fefl6$/6$,(Fg[lFWF\_lFenFWFW-Fccr6$&F`s6#,$F\_lFenFasFW/F\_lFejsF__l-&Fbt6#%&
EqualGFdilF,F,F,6#Fgn6(7'FZFenF_]lFgnFhn7'FZFenFc`mFejmFjo7'FZFenFjcnFgoFjoF`jq
7'FZFenF^oF_epFjo7'FZFenF^oF^]mF\pF,,
I0sparseReductionw,6(Fbdr'Fd^qFgeqFggp'%#nEGF]dmF]gpFhgp68%#rgG%$crgGF`r%#M1G%#
bsG%#M2G%$tM2GF_aw%#M3G%$tM3G%#M4G%&basisG%'lindepG%#B1GFhir%#B3G%#B4G%$iB1G%&r
permG%&cpermGFgbsF^el6"F,C6@$/-F`q6#F__lFbwO6'F4F\qFbwFaamFaam>F/7#-Fefl6$-FQ6#
7#-Feco6#;,&-Fejl6$-FQ6$FW&F`s6#89/Fbgw;FW,&88FWFenFWFWFWFW-Fejl6$F^gw/Fbgw;FWF
fgw-F]jl6$FfgwF__l>F]\lFd[l>FC7#-FQ6#-Facl6$<#-Feco6#;FW-FQ6$FfhqF4<#-FQF=>Fg[l
-F^w6$&F46$F/F^u&F46$FCF^u>F\_l&Fg[l6$F_bn;FWFas>Fez-Fe\n6$-Fiaw6$)F\_lFj`o.F_g
lF^x>Fc]m-FE6$w,FfitF,6$FbrFcrF,-Fccr6$FW-Fjq6$FiaqFisF,F,6$F]ewFez6#FW6$7'FZFe
nFe^lF][oFhnFg^l<#-Feco6#Fa`s>F\gl-Fjq6$-Facl6$<#-Feco6#;FW-FQ6$FbiqFezFc]mFis>
Ffev-Fjq6$7%-FQFjim-FQFf^m-Feco6#;,&F]\lFWFWFW-FQ6$FfhqFg[lFis>Ffev&7$F[iwF\^mF
eev>Fehl-F^w6%&Fg[l6$7#F]\xF^u&Fg[l6$7#F^\xF^u&Fg[l6$;Fb\xF,F^u>F]fl-Fe\n6$-Fia
w6$&FehlFeiwF]jwF^x>Fc]m-FE6$w,FfitF,6$FbrFcrF,FcjwF,F,6$F_ewF]fl6#FWFijwF[[x>F
\gl-Fjq6$-Facl6$<#-Feco6#;FW-FQ6$FbiqF]flFc]mFis>877%F]\xF^\x-Feco6#;Ff^p-FQ6$F
biqFehl>Ffil-%$<|gr>G6%&Fehl6$F^uF]]x&Fehl6$F^uF`]x&Fehl6$F^u;Ff^pF,>6&F_cpF_es
F`esF^^w6&&Ffil6$Fa`sFa`s&Ffil6$Fa`s;,&F_glFWFWFWF,&Ffil6$Ff`xFa`s&Ffil6$Ff`xFf
`x>Fe]v-F^_s6$F^xF_cp6'-Fe\n6$,&F^^wFW-Fdeq6%F`esFe]vF_esFenF^x&F\q6#7$F^\x-Fec
o6#;Ff^p-FQ6$FWF\qF_glFfevF]_xF,F,F,6#Fgn687'FZFenFh^lFgnFhn7'FZFenF^oFjeoF`o7'
FZFenFj`lF`oFju7'FZFenF^o"#)*FjoFaasF_`lF[[oFjjm7'FZFenF^oFboFjo7'FZFenF^oFb[oF
jo7'FZFenF^oF][oFjo7'FZFenF^oF\\rFjoFdbxFc[u7'FZFenF^oF\alFjoFebxFfbx7'FZFenF^o
F^]rFjo7'FZFenF^o"#lFjo7'FZFenF^oF^epFjoFhbx7'FZFenF^oFf[uF\oF,,
I0linDepReductionw,6$FbdrF`bt6)F_awF]awFjdw%$tM1GFaew%&r2delG%&c2delG6"F,C*>FC-
Fe\n6$-Fiaw6$)F4Fj`oFbdsF\q>F[_l-FE6$w,FfitF,6$FbrFcrF,FcjwF,F,6$F]awFC6#FW6$7'
FZFenFe^lFijmFhnFg^l<#-Feco6#F\ht>F\_l-Fjq6$-Facl6$<#-Feco6#;FW-FQ6$FbiqFCF[_lF
is>F]\l&F46$-Fcit6%F]jl7#FehwF\_lF^u>Fg[l-Fe\n6$-Fiaw6$F]\lFbdsF\q>F[_l-FE6$w,F
fitF,6$FbrFcrF,FcjwF,F,6$FbcxFg[l6#FWFijwFfdx>Fez-Fjq6$-Facl6$<#-Feco6#;FW-Fbgl
Fa\mF[_lFisO6%&F]\l6$F^u-Fcit6%F]jl7#-Feco6#;FW-FQ6$FbiqF]\lFezF\_lFezF,F,F,6#F
[]m6+F_bxFj]uFgbxF^[uFe_wFj]uFebxFe_w7'FZFenF^oF`[nFjuF,,
I)rectTordw,6&F\btFe_q'%#TsGFisF`bt6*F`bs%#dgGF]el%#nnG%$GBsGF[enF^zF^el6"F,C+>
F/F_q>FC7#-Fefl6$*&-Fejl6#-FE6%Fg\lF4FezFWF/Fen-F]jl6$FezF\q>F]\l-Fhbl6%FWF_^lF
C>Fg[l-F]et6#-FQ6#-FE6$%&denomGF]\l>F]\l*&Fg[lFWF]\lFW>F[_l-FE6$w,Fb\lF,6$FbrFc
rF,-F_fm6%FjrF4/F]sF[sF,F,6&F*F4FcpFas6#FW6$7'FZFenFfnFb_mFhn7'FZFenFfnFe^lFhnF
`s>F\_l7#-FQ6#<#-Fefl6$&-F[bo6$&F[_lFghl-Fgcp6$Fj[y&F`sFghlFjs/F_gl;FW-F`qFa\m>
F\_l-FE6$w,FcdoF,6$FbrFcrF,Fi]lF,F,6$F]elF]\l6#FW6$7'FZFenFcuFe`mFhnFj[mF\_l-FE
6$w,Fb\lF,6$FbrFcrF,-Fg_oFh\lF,F,Fj_r6#FW6$7'FZFenF[`lF_]lFhn7'FZFenF[`lFjnFhnF
\_lF,F,F,6#F`u6,F\_mF][u7'FZFenF^oFe[oFjoFi_mF[[oFi_mFfbxF^hr7'FZFenF^oFeuFjo7'
FZFenF^oFf^lF\pF,,
I,filterBasesw,6&F*F\am%%nQBsG%#ffG6&%#mFG%#BsGFd\v%"NG6"F,C(>Fg[l-Fhfl6#*&FasF
WF`sFW>F/-F`]r6$F4F_co>FC-FE6$w,Fb\lF,6$FbrFcrF,-F`q6#-F^cl6$-Fjq6$F4F_[lF`^lF,
F,6$F^^yF/6#FW6$7'FZFenFcuFa_mFhnFj[mF\q>F]\l-F]\m6%FC%">G/%'outputG%,permutati
onG-Fa[l6$QA%d~quotient~space~bases~removed|+F,Fg[l7#-FQ6$;FW,&F`sFWFg[lFenF]\l
F,F,F,6#F`u6)FY7'FZFenF_]lF[dlFjo7'FZFenF^oF_cmFjoFe_wF`asF[al7'FZFenF^oF_]lFes
F,,
I-filterBases2w,6*F`bsFep%$CMsGFghxFchxF\amFcpF\^y6;FcirFbpFaalFf^oF[^yFbvF^el%
#vBG%#tBG%#mpGFagpFfirFi]oFapFg[tFffu%$cHsGF`r%$avoG%#msG%#moGFd\vF`^yFjdlFhgq6
"F,C+>F[_l-F`qFgv>F\_l-F`q6#&F__lFjs>F]_xFaam>Ffgw"(+++">8:-Fhfl6#*&F][qFWF[_lF
W?(FezFWFWF[_lFcqC(>6&F/FCF]\lFg[l6&&FasFg`p&F^xFg`p&F__lFg`p&F`sFg`p@$0-F`qFia
mF\_l\>6%F_glFehlF]fl6%-FgeqFiam-F[`q6#-F^dq6%F]\lF_^l7#-Feco6#F\aoFcby?&FfilF
\qFcqC*>Fc]m-Fj]l6%FfilF_^lF]\l>F\gl-Fgcq6(FfilF]\lFehlF/FC/F]sFj[l>F_cp,&-Fgeq
FjimFW-Fdeq6$F\glF_glFen>F_es-Fd`o6#7#-Fefl6$-Fbhr6&&F_cp6#8;F/FCFj[l/FieyF\ao>
F`es-Fe\n6$-FE6$FG-Fdeq6$F_esFg[lFj[l>F^^w7#-Fefl6$-Fejl6#&F`es6$F^uFiey/Fiey;F
WF4>Fe]v-Fejl6$-Fbx6%-F_bl6$8<F[ev-F`q6#FcgyFW-F]jl6$FcgyF^^w@$2Fe]vF]flC$>F]fl
Fe]v>FfevFfil@$2F]flFfgwC$>FfgwF]fl-Fa[l6%Q?Smaller~template~found:~%d,%a|+F,Ff
gwFfev>F]_x7$-FQ6#F]_xF]fl>Fbgw-F]\m6%F]_x%"<GF]`y-Fa[l6$Fb`yFeby7#-FQ6$;FW,&F[
_lFWFebyFenFbgwF,F,F,6#Fd`l6?Fhcl7'FZFenF_cmFguFjo7'FZFenF`oFcaoFjo7'FZFenF_ep"
$@"Fjo7'FZFenFcdn"$M"Fjo7'FZFen"$T""$f"FjoFc`l7'FZFenF[`lFjeoFjo7'FZFenF[`lFguF
`o7'FZFenFejmFbwFjeo7'FZFenF[`lF^]rFjoF][t7'FZFenF]_mF_]lFjo7'FZFenF]_mFfsFjo7'
FZFenF]_mF\oFjo7'FZFenF]_mFdaoFjo7'FZFenF]_mF[dlFjo7'FZFenF]_mFgoFjo7'FZFenF]_m
FijmFjo7'FZFenF]_mFdoF`oFhcn7'FZFenFjcnFguFjo7'FZFenF[`lF^vF`o7'FZFenFiuF\oFjo7
'FZFenFjcnFdbrF\pF``mF`asF[alF\ayF,,
I(iniProbw,6&F%Fjgp'F\^yF\gp'%#pnGFddm61F*%#vFGFcpFepFghxFchx%#GCGF\amF`ayFbpFf
^oFapF\auF[^yF^el6"F,C,>F]\lFas>6$F/Fg[lFgem>6$FCFg[l6$-FgeqF=<#Fbdp>F]fl-Fjem6
#Fbdp-Fa[l6$QJThe~problem~is~defined~by~%d~polynomials|+F,Fd[l>Fc]m-F_fm6%F/F]f
l/F]sF]\l@$0-&Ffr6#%1HilbertDimensionG6$Fc]mFj\zFbwYQJthe~problem~has~infinitel
y~many~solutionsF,-Fa[l6&QQVariables:~%a;~degrees:~%a;~number~of~roots:~%d|+F,7
#Fbdp-FE6$Fg\lF/-F`q6#&-FifmFjesFjs@%F\qC(>6%F]\lF\_lFehl-Fg[oFaq>F_cpF\hm>F[_l
7#-Fefl6$-Fe\n6$-FE6$FG-Fjq6$-Fdeq6$FdhvFCFisF]\l/F_es;FWF_cp>F_gl7#-Fefl6$&-Fi
fm6$&F[_lFehv&F\_lFehvFjsF`_z>F\gl-F]ay6*Fd[lFg[lFehlF[_lF\_lF_glF]\lF`s>6&Fehl
F[_lF\_lF_gl6&7#-Fefl6$Fdhv-F]jl6$F_esF\gl7#-Fefl6$Fi_zFd`z7#-Fefl6$Fj_zFd`z7#-
Fefl6$&F_glFehvFd`zC(>F_glFegm>6$F_cpF]fl6$-F`qFghlFb\z>Fez-F_fm6&F/F]flFj\z/F^
`y%)extendedG>6$Fc]mFfil6$&FezFjs-Fd`o6#&FezF^jo>F\gl-Fh]y6&F/F_glF_cpF`s>F_`z6
&7#-Fefl6$FfilFd`z7#-Fefl6$Fc]mFd`z7#-Fefl6$F]flFd`zF\azO6)F]\lF/Fg[lF[_lF\_lF_
glFehlF,F,F,6#F`u6:Ffjn7'FZFenFe^lFj`lFjoFdjmFj]uFfjm7'FZFenF^oFcaoF\pF_`l7'FZF
enF^oFhiyF`o7'FZFenFcaoFhasFdo7'FZFenF^o"$G"F\pF`[oFe[q7'FZFenF[`lFiuFjo7'FZFen
F[`lF_oFjo7'FZFenF[`lF_jmFjo7'FZFenF[`lF[cxFjo7'FZFenF[`l"$;"FjoFcepFd`w7'FZFen
F[`lFb[oFjoFaep7'FZFenF[`lF[dlFjo7'FZFenF[`lF\vFjo7'FZFenF^oF[dlFjuF,,
I/templateFinderw,6(F%>'%,action_varsG-Fis6#<$%'negintGFddmFaam>'Faew%'symbolGF
[hp>'%,filter_fracGF\gpFbw>FfdmFhdm>'%+schur_polsGFjdzFaam6HFcpF*FepFghxFchxF\a
mF`ay%&avarsGF\elFbvF[^yF`^yF^elFfbsFcirFbpFegpFf^o%&tord1GFagpFfirFaalFiirFi]o
FapFg[tFjirFffuFggpF`pFd^q%#flGF`rF[^nF[gpFhay%#noG%$spoG6"F,C+>F/F_em>8GFcby>8
IFen>6)F/FCF]\lFg[lF[_lF\_lFez-F^[z6&F4-%&evalbG6#/F`sF[hpFasF/>F_gl-Fbx6%/Fbfr
FbwF]\l-FE6$w,6#F[elF,6$FbrFcrF,FiaqF,F,6$FepF]\l6#FW6$7'FZFenF\alF^]rFhn7'FZFe
nF\alFdoFhnF\q>6%FehlF]flFfil6%Feaz-F`q6#Fe]mF^^m>Fc]m,$*&FfilFenFehlFenFgy?(F
\glFWFWFfilFcqC%>6&F_esF`esF^^wFe]v6&&Fg[lFf^m&F[_lFf^mFe^m&FezFf^m>Ffev-FQ6$FW
F`es?(F_cpFWFWFehlFcqC.>F]_x&F_glFigs>6(FfgwFbgwFebyFieyFcgy8=-F`ir6'F]_xF_esF`
esF/F^^w>8>Fdgy>8?-Fbx6%/F`s%%nstdG-Fjas6&FCFcgyF]\lF/-Fd[t6(FCFcgyFdizFe]vF]\l
F/>6%8@8A8B-Fi[v6'FCFjizFebyF]\lF/>Ffjz&-Fadw6(FfjzFgjzFejz,(-FQ6$FbiqFfjzFWF]f
lFenFhizFenF/F__lFjs>Ffjz&-F^cx6$FfjzF/Fjs>8C-Ff`w6(FieyFfjzFfgwFbgwFhizF/>6$8D
8E-FQ6$FWFfjz>8F-F_dr6#Ffjz@&3Ff[[l52F[\[lFbfz3/F[\[lFbfz2FdfzF`\[lC%>6%Fbfz8HF
dfz6%F[\[lF\\[lF`\[l-Fa[l6(QUSmaller~or~sparser~template~found:~[%d,%d],%a,%a,%
a|+F,F[\[lF\\[l-F^eq6$F`\[lF^oF]_x-Fbx6%F]jzF\glFfev-Fefp6-F47$F[\[lF\\[l-F^eq6
$F`\[lF`yF/F]\lF]_xF`esFbgwFejzF__lFifz4Ff[[lY6&Q@invalid~action~matrix:~%1,%2,
%3F,F\glF]_xF`es-Fa[l6*Q7%d%s,[%d,%d],%a,%a,%a|+F,-Fhfl6#*&,&*&,&F\glFWFenFWFWF
ehlFWFWF_cpFWFWFc]mFWQ"%F,F[\[lF\\[lFb][lF]_xFd][l-Fa[l6&Q<Best~template:~[%d,%
d],~%a|+F,FbfzF]][l-F^eq6$FdfzF^oF,F,F,6#FW6?7'FZFenFc`mFgnFhnF]jm7'FZFen"$&="$
&>Fjo7'FZFen"$,#"$5#FjoFd_wFebxFe_wF[dnFc`l7'FZFenF[`lFacmFjo7'FZFenF[`lF_cmFjo
F][tFadn7'FZFenF]_mFcoFjoF^dn7'FZFenF]_mF^vFjoF^fp7'FZFenF]_mFbjmFjoFfjy7'FZFen
F]_mFb_mFjo7'FZFenF]_mF_cmFjoF][nFafp7'FZFenFiclFbhlFjo7'FZFenFiclFiczF\p7'FZFe
nFiclFcjmF\p7'FZFenFiclFj[qFdo7'FZFenF]_mFa[uF\p7'FZFenF^oFj^tF\pF,,
I-readTemplatew,F`\q6LF^hpF_hpFcpFepFagpFbpFggpFgezF*Fg[t%#U0G%&tord0G%"UGFcirF
firFcewFaalFgirFhirFjerFiirFi]oFapFfpFbv%#nRGFjdwFd^qFjbrF_awFgewFhewF`pFbcx%#t
1GFccxFdcxF]zFifp%#xEG%#xVGFb\q6"F,CE>6,F/FCF]\lFg[lF[_lF\_lF^^wFezF_gl8M-F^\qF
j]r>Fehl&FgemFjs>F`ap-FgqF^dp>Fc]mFb\z>F\gl-Fgjq6$FfilFc]m>F]fl-Fgbr6%F]flFfilF
\gl>F_cp-F_fm6%FehlF\_lFj\z>F`es&-Fifm6$F_cpF\_lFjs>F^^w-Fjq6$F^^wF_[l>F_es-Fj]
l6%F[_lF_^lF^^w>Fe]v-Fgjq6$-Fjq6$-Facl6$F_esF^^wFisF\_l>6$FcgyFdiz6$-F`q6#F^^w-
F`qF_`v>Ffev-Fhbl6%-F^clFbc[lF_^lF[_l>F]_x-%&getB0G6$FfevFg[l>Ffev7$-FQ6#-Fgjq6
$-Fjq6$-Facl6$FfevF]_xFisF\_l-FQ6#-Fgjq6$-Fjq6$F]_xFisF\_l>F^^w7$-FQ6#-Fgjq6$-F
jq6$-Facl6$F^^w-Fjq6$FfevF_[lFisF\_l-FQFeev>6$FfgwF_es6$7$-FQF_`v-FQFgc[lFjb[l>
Fbgw-Fgcq6(F[_lF`es-F[`q6#-Fa]s6$F`es7#-Feco6#;FW-F`q6#F`esF_cpF\_lFj\z>Fiey-Fg
er6'F^^wF`esF_cpF\_lF]\l>Fbgw-Fe\n6$-Fdeq6%FieyFbgw-F^_s6$F]\lFieyF]\l>Feby-Fjq
6$,&-FgeqF_`vFW-Fdeq6$&Fbgw6$;FWFdizF^u-FgeqFgc[lFenFis>6$FhizFejz&-Fcfu6&FezFe
hlFg[lFfgw6#;F[]mF^o>6'FhizFjizFfjzFgjzFf[[l-Fadw6(FhizFejzFez,(-FQ6$FbiqFhizFW
FcgyFenFdizFenF]\lF_gl>6%F[\[lFbfzF]][l-F^cx6$FhizF]\l-Fa[l6$Q9Action~matrix~fo
und:~%a|+F,-Ff`w6(FbgwF[\[lF_esF^^wFdizF]\l>8J7#-FQ6$FWF[\[l-Fa[l6$Q3Template~s
ize:~%a|+F,F^j[l@$50Fc]o&F^j[lFjs0&F/F^jo&F^j[lF^joYQ/wrong~templateF,>8L-Facl6
$-Fjq6$FejzF_[l-Fjq6$FjizF_[l>Fjiz&Fjiz6#-Fcit6%F]jl7#-Feco6#;FW-FQ6$FWFjizF]][
l>F\\[l-Fe\n6$-Fiaw6#&Fhiz6$-Fcit6%F]jl7#-Feco6#;FW-FQ6$FfhqFhizFbfzF^uF]\l>F`
\[l-FE6$w,Fb\lF,6$FbrFcrF,-FQ6#-F_\l6$w,Fh[wF,6$FbrFcrF,0&F`^l6$F4F[sFbwF,F,6&F
bcxF`^lFc\lF46#FW6$7'FZFenF_cmF[dlFhn7'FZFenF_cmFadlFhn<#-Feco6#FchqF,F,6$FbcxF
\\[l6#FW6$7'FZFenFcuF`fpFhnFj[m<#-FQ6#F]][l>8K-Fcil6$-Fjq6$Fba[lF_[l-Fjq6$&Fjiz
6#7#-FQ6#F`\[lF_[l>Fdfz-Fgjq6$-Fjq6$-Facl6$Fd[\l-Fjq6$FfgwF_[lFisFc]m64Fg[lF[_l
F]flF\glFdfzFfgwF^^wF_esFezFbfzF]][lF^j[lFdizF^_\lFfjzFgjzFf[[lF_[\lF,F,F,6#F[]
m6GFhcl7'FZFenF^oFdbrFjoFeaoF[[oFf]y7'FZFenF^oFe`mFjoF[[o7'FZFenF^oFc]nFjoF_asF
afuFi_mFh_mFfaoFfaoFjjmFb[pFgbxF_dl7'FZFenF^oFcjmFjoFj]uFibxFiasFiasF^hr7'FZFen
F^oFa`lFjo7'FZFenF^oFjjoF\p7'FZFenF^oFcfoFjoFe`w7'FZFenF^oFd_mF`o7'FZFenFgoF_jm
FdoFgjmFgjm7'FZFenF^oFd_mFjoF^[pFibxFebx7'FZFenF^oFh[qF\oF,,
I&getB0w,6$'%"PGF_[lF^gp6'F\elF^el%$VrsG%$vrsGFjer6"F,C$>F/Fbfr?(FCFbwFW,&F/FWF
enFWFcqC$>F]\l-&%)combinatG6#%'chooseG6$F\q,&F/FWFCFen?&Fg[lF]\lFcqC$>F[_l-F_\l
6$w,F_rF,6$FbrFcrF,-Fjq6$-FE6$w,F]eoF,6$FbrFcrF,-Fehm6$*&F4FWFjrFWF[sF,F,6&F`rF
4Fea\lF[s6#FW6$7'FZFenFioF^]rFhn7'FZFenFioFguFhnF`^l%$andGF,F,6&Fha\lFg[lFea\lF
46#FW6$7'FZFenFj`lF\\rFhnF[foF4@%0F`\yFbwO-Fjq6$-FE6$w,F]eoF,6$FbrFcrF,*&F4FW&F
`^lFjsFWF,F,6$FjerF[_l6#FW6$7'FZFenFdoF][oFhn7'FZFenFdoFe[oFhn7$FbdpFWF_[l>F[_l
FjelF,F,F,6#F[]m6+7'FZFenFd`lFgnFhn7'FZFenFjnFj`lF\oFc`l7'FZFenF[`lF^`lFjoF][t7
'FZFenF]_mF_oFjo7'FZFenF]_mF\vF`o7'FZFenF\oFdbrFju7'FZFen"#!*F_hrFjoF,,
I+alterCommaw,6#'FfalFisF,6$FbrFcrF,-F16%Fe_n&-&Fdcr6#%+InterleaveG6$F47#-Feco6
$Q",F,,&F_qFWFenFWF,FafnF,F,F,6#FW6$7'FZFenFcuFdbrFhn7'FZFenFcuFiuFhnF,,
I*printLinew,6#'%%lineGF'F,6$FbrFcrF,-Fa[l6$Q.%-60swritten|+F,F4F,F,F,6#FW6$7'F
ZFenFcyF^]rFhn7'FZFenFcyFf^lFhnF,,
I*iniColpivw,6&Fddw'F\a[lF_[lF`gpFe_q6*%#VlGFea\lFjer%#aPGFgir%#RPGF]zFbp6"F,C/
>F_gl-Fjem6#F\ju>F/-Fjq6$-Facl6$Fc_yF\qFis>FC-Fjq6$-F_\l6$w,F_rF,6$FbrFcrF,-Feh
m6$Ffc\lFi\lF,F,6&FagpF`sFeh\lF/6#FWFjcvF/F_[l>F]\l-F_d[l6$FCFas>Fg[l-Fj]l6%F`s
F_^lFC>F[_l-Fgjq6$-Fjq6$-FaclF]ilFisF_gl>FC7$-FQ6#-Fgjq6$-Fjq6$-FaclFfemFisF_gl
-FQ6#-Fgjq6$-Fjq6$F]\lFisF_gl-Fa[l6$QCList~of~permissible~monomials:|+%a|+F,FC-
Fa[l6$QENumber~of~permissible~monomials:~%d|+F,Fg_l>Fg[l-FE6$w,F_rF,6$FbrFcrF,-
Fccr6$Ffc\l7$-FQFids-FQ6#FcjlF,F,6(FagpF`sFea\lFCFgirF[_l6#FW6$7'FZFenFcuFjeoFh
nFj[mFC>F\_l7$F`\mF\^m>Fez-Fgjq6$-Fjq6$-Fcil6$-Facl6$-Fjq6$F/F_[l-Fjq6$F\_lF_[l
F\qFisF_gl6'-F^w6$-FQFg`pFhiuFCFg[lF`\y-F`qFg`pF,F,F,6#F`u60Fby7'FZFenFhsFacmFj
oFbjqF`[pFafuFi_mFh_mFbas7'FZFenF^oFc]nF\pF_irF^[uFafuFcjq7'FZFenF^oFguF\oF,,
I,commonCode2w,6&'F[em%(integerG'%#fbGF'Fbv%$nv0GF,6"F,C(-F\im6$F4-F16%Q"|+F,F
\qQ1[V,|ir]~=~eig(T);|+F,-F\im6$F4-F16,F\qQ'S~=~V(F,,&F`sFWFasFenQ":F,,&F`sFWFe
nFWQ/,:)./repmat(V(F,F`sQ%,:),F,FasQ',1);|+|+F,-F\im6$F4-F16$F\qQFI~=~|irisnan(
S(1,:))~&~|irisinf(S(1,:));|+F,-F\im6$F4-F16$F\qQ_o%%I~=~I~&~|irimag(S(1,:));~%
%~uncomment~this~line~for~real~roots~only|+F,-F\im6$F4-F16$F\qQ.S~=~S(:,I);|+|+
F,-F\im6$F4Q$endF,F,F,F,6#F`u6)FY7'FZFenF^oFa_mF\p7'FZFenF^o"$,"F\p7'FZFenF^oF`
fpF\p7'FZFenF^oFhatF\pFe]n7'FZFenF^oF\pF\pF,,
I,writeSolverw,6/'%$dirGF'F^hp%&vars0GFagp%#iMG%#eMGFaalFfirFifpFfdwFj`[lF_awF[
hp6)%&vars1G%#vvGF[emF]_]lFbvF^elF\_]l6"F,C7>Fg[lF\by>F[_l-F`q6#Fj[l>FezQ%~~~~F
,>F/-Fjq6$-Facl6$Fhbv<#FasFis>FC7#-Fefl6$-Fccr6$*&&F/F_^mFW&Fj[lFi`nFWFj[l/F\_l
;FW,&Fg[lFWFenFW>F]\l-Fhgm6$-F16+F4Q"/F,-Fbx6%90Q%std_F,Q&nstd_F,,&&F^[qFjsFW9/
FenQ"xF,,&&F^[qF^joFWF]e]lFenQ"_F,F&F5Fa\n-F\im6$F]\l-F16'QH%%~Input:~coefficie
nt~matrix~C~of~size~F,F[jpF^e]l&F\qF^joFd_]l-F\im6$F]\l-F16'QF%%~Output:~soluti
on~matrix~S~of~size~F,Fg[lF^e]lF[_lQ#|+|+F,-F\im6$F]\l-F16*Q.function~S~=~F,Ffd
]lF[e]lF^e]lF_e]lFae]lF&Q&(C)|+|+F,-F\im6$F]\l-F16.FezQ,M~=~sparse(F,-F]f\l6#-F
E6$w,FfitF,6$FbrFcrF,FadtF,F,F,6#FW6$7'FZFenFe[oF]dnFhn7'FZFenFe[oFacmFhnF^xF]g
\l-F]f\l6#-FE6$w,FfitF,6$FbrFcrF,FbdtF,F,F,6#FW6$7'FZFenF[fuF]jqFhn7'FZFenF[fuF
\f\lFhnF^xQ$,C(F,-F]f\lF^fwQ#),F,F\e]lF]g\lF`e]lQ$);|+F,@$0F]e]lFbw-F\im6$F]\l-
F165Fd_]lFezQ'M~=~M(F,,&F]e]lFWFWFWQ&:end,F,Fhh]lQ*:end)-(M(F,Fhh]lQ(:end,1:F,F
]e]lQ')/M(1:F,F]e]lQ$,1:F,F]e]lQ())*M(1:F,F]e]lF]g\lFhh]lQF:end);~%%~Schur~comp
lement~reduction|+F,-F\im6$F]\l-F16'Fd_]lFezQ5[L,|ir,Pi]~=~lu(M(:,1:F,F_[qQ%));
|+F,-F\im6$F]\l-F16$FezQ+Pi~=~Pi';|+F,-F\im6$F]\l-F16(FezQ0M~=~[Pi*L~Pi(:,F,,&F
_[qFWFWFWQ,:end)]\M(:,F,F`j]lQ(:end);|+F,-F\im6$F]\l-F16&FezQ+M~=~M(end-F,,&Feh
pFWFenFWQ*:end,:);|+F,-F\im6$F]\l-F16'Fd_]lFezQ+T~=~zeros(F,F[_lF`h]l-F\im6$F]
\l-F16*FezQ%T(1:F,FehpQ.,:)~=~-M(:,1:F,FehpQ')\M(:,F,,&FehpFWFWFWFbj]l@&/,&F[_l
FWFehpFenFW-F\im6$F]\l-F16&FezQ#T(F,*&F[_lFW-Fccr6$&F][qFi`nFj[lFWQ()~=~1;|+F,2
FWFi[^l-F\im6$F]\l-F16&FezF^\^l-F]f\l6#7#-Fefl6$,&*&F[_lFW,&-Fccr6$&F][q6#,(F\_
lFWF[_lFenFenFWFj[lFWFenFWFWFWF\_lFW/F\_l;Ff[^lF[_lFc\^l-Ff^]l6&F]\lFezF[_lFg[l
-FiimFiam-Fcg\l6#-F16)Ffd]lF[e]lF^e]lF_e]lFae]lF&F5F,F,F,6#Fcu6;FYF`_w7'FZFenFa
`lF^]rFjo7'FZFenFcaoF_oFjoFiasFfat7'FZFenF^oFebrFjo7'FZFenF^oF\f\lF\p7'FZFenF^o
FdbrF\p7'FZFenF^oFcjmF\p7'FZFenF^o"$g"F\pF`[o7'FZFenF[`l"$#=F\p7'FZFenF^oF[cxF
\p7'FZFenF^oFboF\p7'FZFenF^oF\[pF\p7'FZFenF^oFb_mF\pFecm7'FZFenF^oFbjmF\pF`[o7'
FZFenF[`lF_[pF\p7'FZFenF[`lFhiyF\p7'FZFenF^oF\oF\pFa[n7'FZFenF^oF^epF\pF,,
I2writeSolverColpivw,60F^b]lF^hpF`b]lFagpFab]lFbb]lFea\lFfh\lFifpFfdwFj`[lFbvF_
awF[hp6)Fdb]lFeb]lF[emF]_]l%#nPGF^elF\_]l6"F,C;>Fg[lF\by>F[_lFjb]l>FezF]c]l>F/F
_c]l>FC7#-Fefl6$-Fccr6$Fjc]l&Fj[l6#;,$F]e]lFenF,F]d]l>F]\l-Fhgm6$-F16+F4Fed]l-F
bx6%91Fid]lFjd]l,&F\e]lFWFhd]lFenF^e]l,&F`e]lFWFhd]lFenQ)_colpiv_F,F&F5Fa\nFbe]
l-F\im6$F]\l-F16'F\f]lFg[lF^e]lF]e]lF]f]l-F\im6$F]\l-F16*Fbf]lF^a^lFaa^lF^e]lFb
a^lFca^lF&Fcf]l-F\im6$F]\l-F16.FezFhf]l-F]f\l6#-FE6$w,FfitF,6$FbrFcrF,FadtF,F,F
,6#FWF`g]lF^xF]g\l-F]f\l6#-FE6$w,FfitF,6$FbrFcrF,FbdtF,F,F,6#FWFjg]lF^xF]h]lF^h
]lF_h]lF\e]lF]g\lF`e]lF`h]l@$0Fhd]lFbw-F\im6$F]\l-F165Fd_]lFezFgh]l,&Fhd]lFWFWF
WFih]lFdc^lFjh]lFdc^lF[i]lFhd]lF\i]lFhd]lF]i]lFhd]lF^i]lFhd]lF]g\lFdc^lF_i]l@%0
F_[qFbwC&F`i]lFfi]lF[j]l-F\im6$F]\l-F16&FezQ,M~=~full(M(F,F`j]lQ+:end,:));|+F,-
F\im6$F]\l-F16$FezQ.M~=~full(M);|+F,@$0FehpFbwC%-F\im6$F]\l-F16'Fd_]lFezQ6[L,UR
,Pi]~=~lu(M(:,1:F,FehpFei]lFfi]l-F\im6$F]\l-F16(FezF_j]lFf[^lFaj]lFf[^lFbj]l-F
\im6$F]\l-F16&FezQ*MP~=~M(1:F,FehpQ&,:);|+F,-F\im6$F]\l-F16&FezQ(NP~=~M(F,Ff[^l
Q+:end,:);|+|+F,-F\im6$F]\l-F16&FezQ:[Q,U,Pi]~=~qr(NP(:,1:end-F,Fc_lFei]l-F\im6
$F]\l-F16(FezQ4A~=~UR\[MP(:,1:end-F,Fc_lQ/)*Pi~MP(:,end-F,Fg[lQ):end)];|+F,-F\i
m6$F]\l-F16*FezQ+B~=~U(:,1:F,,*F\e]lFWFhd]lFenF_[qFenFehpFenQ()\[U(:,F,,,F\e]lF
WFhd]lFenF_[qFenFehpFenFWFWQ3:end)~Q'*NP(:,end-F,Fg[lFff^l-F\im6$F]\l-F16(FezQ/
M~=~[-A(:,end-F,,&F]e]lFWFenFWQ1:end)+A(:,1:end-F,F]e]lQ,)*B;~-B];|+|+F,-F\im6$
F]\l-F16&FezQ&xP~=~F,-F]f\l6#F][qQ#;|+F,-F\im6$F]\l-F16*FezQ*P1~=~[(1:F,,(F[_lF
WFg[lFenFenFWQ&)*Pi~F,,&F[_lFWFg[lFenF\`]lF[_lQ$];|+F,-F\im6$F]\l-F16-FezQ-T~=~
getT(M,[F,,&F[_lFWFWFWF\`]l,&F[_lFWFehpFWQ+~P1(1:end-F,F]e]lQ+)],P1(end-F,Feg^l
Q&:end)F,Q',xP);|+F,-Ff^]l6&F]\lFezF]e]lFg[lFj]^l-Fcg\l6#-F16)F^a^lFaa^lF^e]lFb
a^lFca^lF&F5F,F,F,6#Ffn6EFd[vF`_w7'FZFenFa`lFb_mFjo7'FZFenFj^tF`jmFjoFiasFgbx7'
FZFenF^oFhasFjoFd^^lFe^^l7'FZFenF^oFd[qF\pFg^^lF`[oFi^^lF`[o7'FZFenF[`lFdaoF\p7
'FZFenF[`lF^`lF\p7'FZFenF[`lFfsF\p7'FZFenF[`lFj^tF\pFfesF`[o7'FZFenF[`lF^dlF\pF
aj^lFbj^lFea]lFecm7'FZFenF^oFj[qF\p7'FZFenF^oFg_wF\p7'FZFenF^oFa[uF\pFfj^l7'FZF
enF^oFjeoF\pF[a\l7'FZFenF^oF_dzF\pFb_^lFa[n7'FZFenF^oFejqF\pF,,
I2writeInidataCoefsw,6$F%F^b]l6.%*proc_nameG%#_CG%&_nameG%&_sizeG%#AsG%#CsG%#Cl
GF[emF^elFbbt%$idxGF\_]l6"F,C:>Fc]mF]c]lAQ6../problems/_common.mF,AF0>F/-FI6#-F
16$%#C_GF4@$4-F_bl6$F/%*procedureGC$-Fa[l6#QUCoefficient~file~cannot~be~created
~for~this~problem|+F,OFbw>6%FCF]\lFg[lFjfl@$4-F9F[q-&F:6#%.MakeDirectoryGF[q>F_
gl-Fhgm6$-F16&F\qQ./inidata_num_F,F4F5Fa\n-F\im6$F_gl-F16%Q=function~data~=~ini
data_num_F,F4Q$()|+F,-F\im6$F_gl-F16&Fc]mQ0data~=~cell([1,F,FabpQ%]);|+F,?(Fehl
FWFWFabpFcq@%/&Fg[lF]hmFfhq-F\im6$F_gl-F16&Fc]mQ&data|frF,FehlQ,|hr~=~randn;|+F
,-F\im6$F_gl-F16(Fc]mF`__lFehlQ+|hr~=~randn(F,&-F]f\l6#F[__lFiinF`h]l-F\im6$F_g
lFba]l-FiimFghl-Fcg\l6#-F16%Q-inidata_num_F,F4F5>F_gl-Fhgm6$-F16&F\qQ(/coefs_F,
F4F5Fa\n-F\im6$F_gl-F16%Q4function~C~=~coefs_F,F4Q)(data)|+|+F,?(FehlFWFWFdcyFc
q-F\im6$F_gl-F16'Fc]mFaftQ)~=~data|frF,FehlQ$|hr;|+F,-F\im6$F_glFd_]l?(FehlFWFW
Fg_lFcqC&@$/FehlF[]mC$>F[_l-Fjq6$&-%%map2G6%FQFbw-F_\l6%F_bl-Fjq6$&FCF^joF_[l%)
functionGFjsF'-F\im6$F_gl-F16*Fd_]lFc]mF[_lQ*~=~C(:,1:F,-FQ6$Ffhq&FCFjsQ')\C(:,
F,,&F^c_lFWFWFWQ):end);|+|+F,-F\im6$F_gl-F16(Fc]mQ+C~=~zeros(F,-FQ6$Ffhq&FCF]hm
F]g\l-FQ6$FbiqF[d_lQ%);|+|+F,>Fg_v6$-Facl6$-Fjq6$F[d_lF_[l<#Fbw-Fjq6$F[d_lFis?&
F]flF\_lFcqC$>Ffil7#-Fa[w6$F]flFez-F\im6$F_gl-F16(Fc]mQ#C(F,-Fbx6%/F\cpFWF[fq-F
]f\lF]cpQ%)~=~F,-Fjq6$F]flF'F_h^l-F\im6$F_gl-F16%Fd_]lFc]mQVC~=~C./repmat(sqrt(
sum(C.*conj(C),2)),1,size(C,2));|+|+F,Fj__lF\`_l-Fcg\l6#-F16%Q'coefs_F,F4F5AQ+g
reedyAG.mF,F,F,F,6#F[]m6JFd[v7'FZFenF[cxFd_mFjo7'FZFenF^oF\oFgo7'FZFenF^oF[dlFg
oF_dl7'FZFenF^o"$B"F`o7'FZFenFguFjjnF\p7'FZFenFccn"$:"FjuF`jqF]o7'FZFenFbhlFcoF
\pF\dnFha]lFeczFc`lF\[n7'FZFenFejmFd_mF\p7'FZFenFcyF]jqF\pFja]lFa[nF``lFe]yF\[o
Fc`l7'FZFenF[`lF]dnF\p7'FZFenF^oFcfoF\pFc`lF\[n7'FZFenF]_mFe_mFjo7'FZFenF]_mF_d
zF\p7'FZFenF[`lF^vF\p7'FZFenF[`lFj[qFjoF][tFgjy7'FZFenF]_mF_g_lF\p7'FZFenF^oFh[
qF\pFja]lFa[n7'FZFenF^oFbhlF\p7'FZFenF^oF\pFgoF,,
I-writeTestNumw,6*F%F^b]l'Fi`[lFgeqFe_q'Fifp-Fis6#Fddm'%%deg0GFddm'%#cpGF\hpFae
w6%F[emF\_]l%$fb2G6"F,C<>FCF]c]l>F]\l-F16$FCFC@$F`]_lFb]_l>F/-Fhgm6$-F16&F\qQ+/
test_num_F,F4F5Fa\n-F\im6$F/Q*rng(23);|+F,-F\im6$F/Q,N~=~10000;|+F,-F\im6$F/-F1
6%Q%d~=~F,F__lQ$;|+|+F,-F\im6$F/-F16%Q;stats~=~struct('problem','F,F4QL','tm',[
],'err',[],'k',[],'kr',[],'N',N);|+|+F,-F\im6$F/Q.for~i~=~1:N|+|+F,-F\im6$F/-F1
6&FCQ4data~=~inidata_num_F,F4Q?();~%%~generate~initial~data|+|+F,-F\im6$F/-F16$
FCQ%try|+F,-F\im6$F/-F16&F]\lQ+C~=~coefs_F,F4QV(data);~%%~compute~coefficients~
of~polynomial~system|+F,-F\im6$F/-F16$F]\lQ&tic;|+F,-F\im6$F/-F16+F]\lQ%S~=~F,-
Fbx6%-Fjfz6#/F][qF[hpFid]lFjd]lFeapF^e]lFfap-Fbx6%Fj[lFca^lFae]lF4QA(C);~%%~sol
ve~polynomial~system|+F,-F\im6$F/-F16$F]\lQ<stats.tm~=~[stats.tm~toc];|+F,-F\im
6$F/-F16$F]\lQ>if~isempty(S);~continue;~end|+F,-F\im6$F/-F16(FCQ*catch~ME|+F,F]
\lQ+continue;|+F,FCQ&end|+|+F,-F\im6$F/-F16(FCQ)mon~=~@(F,&-F]f\lF_flFiinQ#)~F,
-F]f\l6#-Fjq6$F`sFisF_h^l-F\im6$F/-F16$FCQfn[err,k,kr]~=~numerr(C,mon,S,d);~%%~
compute~numerical~error|+F,-F\im6$F/-F16$FCQ>stats.err~=~[stats.err~err];|+F,-F
\im6$F/-F16$FCQ8stats.k~=~[stats.k~k];|+F,-F\im6$F/-F16$FCQ<stats.kr~=~[stats.k
r~kr];|+|+F,-F\im6$F/F_^`l-F\im6$F/Q5disp_stats(stats,1);F,-FiimF=-Fcg\l6#-F16%
Q*test_num_F,F4F5F,F,F,6#Fd`l6>Fhcl7'FZFenFcuFeuFjo7'FZFenFf^lFa`lFjoF]oF`g_lFi
asFg]yF`dwFe]n7'FZFenF^oF[jqF\p7'FZFenF^oFesF\pFjg_lFb_^lFfa]l7'FZFenF^oFjcnF\p
7'FZFenF^o"$j"F\pFecm7'FZFenF^oF^]rF\p7'FZFenF^oF\\rF\p7'FZFenF^oFj[rF\pFc_^lF^
_^l7'FZFenF^oFdoF\pFecm7'FZFenF^oFj`lF\pF\_^lFa[nFe]nF,,
I0solverGeneratorw,6)F%>F_ezF[hp>%'colpivGFW>%0createCoefsFileGFbw>%1createSolv
erFileGFW>%/createTestFileGFbw>'%(rootDirGF'Q(solversF,6FFepFagpFg[tFi`[lF]zFii
rFaalFfirFggpFccxFdcxFifpFj`[lF\a[lF_awFgewFhewF]a[lFd^qFjbrFea\lFfh\l%$nR1G%$n
E1GFdalFh_^lFfdwFgh_lF`b]l%#iCG%#eCGF`p%#MtGFab]lFbb]lF_b]l6"F,C8>64F/FCF]\lFg[
lF[_lF\_lFezF_glFehlF]flFfilFc]mF\glF_cpF_esF`esF^^wFe]v-Fd`[l6$F4-Fjfz6#/F\qF[
hp>Ffev-F^w6$F`\mFhiu>6'F]_xFfgwFbgwFebyFiey-F`h\l6&FfevF_cpFCF/>6%FcgyFdizFhiz
6%F`^]l-F`q6#FfgwF`\y>Fjiz-Fbx6%51FdizFcgy/F`sFbwF\wFcq>Fejz-Fbx6%Fjiz-F_\l6$w,
F]eoF,6$FbrFcrF,-Fehm6$*&F4FW&F`^lFi`nFW&F`^l6#;,$Fi\lFenF,F,F,6&Fea\lFfgwFdalF
cgy6#FW6$7'FZFenFadlF^]rFhn7'FZFenFadlF\oFhnF/-F_\l6$w,F]eoF,6$FbrFcrF,-Fehm6$F
ce`lF`^lF,F,6$FaalFez6#FW6$7'FZFenF`jm"#'*Fhn7'FZFenF`jmFd_mFhnF/-Fa[l6$QRVaria
bles~that~can~not~be~evaluated~at~roots:~%a|+F,7#-FQ6#-Facl6$Fh]]lFb[\l>Ffjz7#-
%(indicesG6$-Fjq6$F]\lF[`q%+indexorderG>Fgjz-FE6$w,Fb\lF,6$FbrFcrF,,&FadtFW*&,&
FbdtFWFenFWFWFdhqFWFWF,F,6$Fg[tF]\l6#FW6$7'FZFenFcuF^`lFhnFj[mFfjz>F]\l-Fd`o6$-
FQ6$FWF]\l<#-FQ6#-F^`q6%w,Fc\mF,6$FbrFcrF,/-FQFaqF\qF,F,F,6#F[]m6$7'FZFenFjcnFd
oFhn7'FZFenFjcnF[dlFhnFfjzFgjz>Ff[[l&-Fcfu6&Fehl-Fjq6$-Fdeq6$F]\lFg[lFisF/F\_lF
^jo@$0F_esFbw>Ff[[l&Ff[[l6$F`esF^^w>Ff[[l&Ff[[l6$-Fcit6%F]jl7#-Feco6#;FW-FQ6$Ff
hqFf[[l-&F[^l6#F[ev6%F]flF_^lF_es-Fcit6%F]jl7#-Feco6#;FW-FQ6$FbiqFf[[l-Fa[al6%F
filF_^lF_es@$Fjiz>Ff[[l-Fgbr6%Ff[[l-Fjq6$-F^w6$Fbf[lFfevFgeq-Fjq6$-F^w6$Fbf[lF]
_xFgeq>F[\[l-Fjq6$Ff[[lF[`q>6$F\\[lF`\[l6$7#-Feg`l6$F[\[lFig`l-FE6$FQ7#-%(entri
esGFb]al@$4-F9F[c]l-Fc]_lF[c]l>Fbfz-F16%Fj[lFed]lF4@$4-F96#Fbfz-Fc]_lFb^al@$/F^
xFW@%Fjiz-Fd_^l60Fbfz7#Fih`lFejzFCF\\[lF`\[lFfgwFbgw7#-FQ6$FWFf[[lFieyFebyFcgyF
_esFec`l-F[b]l6/FbfzFi^alFejzFCF\\[lF`\[lFezF_glFj^alFhizF\glF_esFec`l@$/FasFW-
F[[_l6$F4Fbfz@$/F__lFW-F]h_l6*F4FbfzFg[lF/Fc]mFcgyFjizF\qF,F,F,6#FW6BF_bx7'FZFe
nF^o"$E"FjoFafuFh`\l7'FZFenF^oF^`lFjoFbjqFijn7'FZFenF^oF_epF\pFhbxFgjmFfbxFjbx7
'FZFenF^oFa`lF`o7'FZFenFe^lF`]mFjoFbbx7'FZFenF^oFebrF`o7'FZFenFfnFhf`lFjoFf]y7'
FZFenF^oF`[nFjo7'FZFenF^oF\epF`o7'FZFenFguF`jmF\pFhiqF]oF`g_lF`[oF\[n7'FZFenFh^
lFcdnF\p7'FZFenFcyF\vF\p7'FZFenF^oF[cxF`o7'FZFenF^]mFb_mF\p7'FZFenF^oF[fuF`o7'F
ZFenFadlFjjoF\pF,
