M7R0
I,eigenSolverw,6$'%%probG%'stringG>%'showAPG""!60%%fB2CG%"FG%%varsG%%tordG%"GG%
"BG%$degG%$rndG%#avG%#vrG%"TG%"VG%"SG%#SrG6"6"C2>8$w,6%%"fGF.'F1%%listG6#%"tG6"
F;C$>F>-%&tableG6$%'sparseG-%$zipG6%w,6$%"aG%"bGF;6$%)operatorG%&arrowGF;/9%9$F
;F;F;6#""#6$7'Q!F;!"""#O"#YFjn7'FhnFinFjn"#UFjn7#-%'coeffsG6%FYFX.%"mG7#FcoO-%$
mapG6$w,6#FSF;6$FUFVF;&T#6#FYF;F;6$FEF>6#"""6$7'FhnFin"#="#CFjn7'FhnFinFdp"#?Fj
n9&F;F;F;6#""$6%7'FhnFin"#6"#5Fjn7'FhnFin"#8"#w"#J7'FhnFin""("#G"#_>6%8%8&8'&-%
,readProblemG6'FYF*7"F*Fap6#7%FapFjp""%>Fiq-Fgo6$%&numerGFiq@$4-%%typeG6$Fiq-FC
6#%(polynomGYQQThe~case~of~non-polynomial~system~is~not~handledF;>8(-&%)Groebne
rG6#%&BasisG6$FiqF[r>8)&-&Ffs6#%*NormalSetG6$FcsF[r6#Fap>8*-%%nopsG6#F[t>8+,$-%
%randG6#;!%+5"%+5#FapF`u>8,-%$addG6$*&8-Fap-FitF;Fap-%#inG6$FhuFjq@$/FXFap-%'pr
intfG6$Q7Action~polynomial:~%a|+F;Fcu>8.-&Ffs6#%5MultiplicationMatrixG6'FcuF[t-
FJ6#-&%"|irG6#%"=G6%F[t%#~$G7#-%"$G6#;FapFdtFcsF[r>8/&-&%.LinearAlgebraG6#%-Eig
envectorsG6#-%&evalfG6#Fdv6#Fen>Fiw-&F^w6#%"/G6%FiwFbw-%".G6$-%'VectorG6$Fdt/%%
fillGFap&FiwFbt>80-F\y6$-%'MatrixG6#-Fgo6$w,6#F5F;6$FUFVF;-T+6%-&Ffs6#%+NormalF
ormG6%FYF]pT%T'T)F;F;6,F0FcsF/F[rF.FjqF1F[tF,F>6#Fap6$7'FhnFin"#>"#qFjn7'FhnFin
F_[l"#AFjnFjqFiw>81-%#ReG6#&Fey6$;F;F;-%'selectG6$w,6#%"cGF;6$FUFVF;-%'andseqG6
$-%#isG6$&F]p6$%"iGFY%%realG/Fj\l;Fap-%#opG6$7$FapFapF]pF;F;6$F8Fey6#Fap6$7'Fhn
Fin"#DF`[lFjn7'FhnFinFf]l"#FFjn7#-Few6#;Fap-F_]l6$7$FapFenFeyO6%FeyFd[l-%.backw
ardErrorG6&FiqFjqFeyFdtF;F;F;6#Fap657'FhnFin"#9""'Fjn7'FhnFinFjpF^q"#V7'FhnFinF
jp"#eF[_l7'FhnFinFjpFgpF[_l7'FhnFinFjp"$.""#X7'FhnFin"#Q"#%*"#]7'FhnFinFjpFbqF[
_l7'FhnFinFjpFc_lF[_l7'FhnFinFjp"#;F[_l7'FhnFinFjp"#KF[_l7'FhnFinFjp"#LF[_l7'Fh
nFinFjp"#lFa_l7'FhnFinFgp"#cFgp7'FhnFinFjp"#uF[_l7'FhnFinFjp"#ZF[_l7'FhnFinFjpF
jnF[_l7'FhnFinFjp"#")F[_l7'FhnFinFjp"#$*F[_l7'FhnFinFjpF[oFfqF;,
I&dlinew,6#%"nGF;6$FUFVF;-%$catG6#-Few6$Q"-F;FYF;F;F;6#Fap6$7'FhnFin"")"#@Fjn7'
FhnFinFjalF^qFjnF;,
I%suppw,6$FAF.F;6"F;C$-F`o6%-%'expandGF^pFX.%#mnGO<#FgblF;F;F;6#Fen6%7'FhnFinFd
q"#sFjn7'FhnFinF[bl"#\Fgp7'FhnFinFfq"#iFfqF;,
I%Suppw,6$F-F.6#F86"F;C$>F>-Fgo6%F]blFYFXO6$F>-%&unionG6#&F>F;F;F;F;6#Fen6%7'Fh
nFinFdqFi^lFjn7'FhnFin""*FbqFbq7'FhnFinFjpFepFfqF;,
I(degree1w,F_bl6#%$vrsG6"F;C$>F><#&FXF;O-%$maxG6#-Fgo6$w,6#FgblF;6$FUFVF;,&-%'d
egreeG6$-FgrF^pF]pFap-F[fl6$-%&denomGF^pF]pFapF;F;6$FjdlF>6#Fap6$7'FhnFinFdp"#m
Fjn7'FhnFinFdpF[blFjn-F]bl6$FYFXF;F;F;6#Fen6%7'FhnFinF^qFi^lFjn7'FhnFinFedl"#BF
bq7'FhnFinFjp"#$)FfqF;,
I+TestOrder1w,6%%"xG%"yGF/6%Fjdl%#dxG%#dyG6"F;C&>F>-%&minusG6$-%'indetsG6#Fhp<#
Fhp>Fiq-Fgdl6$FYF>>Fjq-Fgdl6$FXF>O52FiqFjq3/FiqFjq-&Ffs6#%*TestOrderG6%FYFXFhpF
;F;F;6#Fjp6'7'FhnFinF`qFi^lFjn7'FhnFinFedl"#SFbq7'FhnFinF[_l"#jF[_l7'FhnFinFffl
"#')F[_l7'FhnFinFjp"#hFfqF;,
I$srtw,6$F7F/F;6$FUFVF;-%%sortG6$FYw,6$FdglFeglF;6$FUFVF;-F_il6%FXFYT$F;F;6$F/F
X6#Fen6$7'FhnFinFf]lFiilFjn7'FhnFinFf]lF[`lFjnF;F;F;6#Fen6$7'FhnFinFi^l"#kFjn7'
FhnFinFi^lFi_lFjnF;,
I,poly2matrixw,6%F-F.>%#ppGF*6$F6F16"F;C&>F>-Fgo6$w,6#%#plGF;6$FUFVF;-FJ6$FL-FN
6%w,FQF;6$FUFVF;FWF;F;F;6#Fen6$7'FhnFin"#M"#WFjn7'FhnFinF]]mFgilFjn7#-F`o6%FYFj
jlFfbl7#FgblF;F;6$F.FX6#Fap6$7'FhnFin"#7"#xFjn7'FhnFinFh]m"#:FjnFY>Fiq-&%*ListT
oolsG6#%+MakeUniqueG6#-Fgo6%%(indicesGF>.%'nolistG>F>-Fiy6#-Fgo6$w,FDF;6$FUFVF;
-Fgo6$w,FjoF;6$FUFVF;&FjjlF^pF;F;6$FEFY6#Fap6$7'FhnFin"#EF[`lFjn7'FhnFinFh_mFeq
FjnF]pF;F;6$F1Fiq6#Fap6$7'FhnFinF_[lFjnFjn7'FhnFinF_[lF[blFjnF>O6$-%#ifG6%/FhpF
*F>-&&F]x6#%(ModularG6#%$ModG6%FhpF>&%(integerG6#Fjal-F_y6#FiqF;F;F;6#Fjp6'Fg^l
Fg`l7'FhnFinFjp"#bF[_l7'FhnFinFjp"#TF[_l7'FhnFinFjpFh`lFfqF;,
I/permuteColumnsw,6%%"MGF7%#V1GFgel6$FUFVF;&FY6$Fj[l7#-%$seqG6$-&F_^m6#%'Search
G6$F>FX-F[v6$F>FhpF;F;F;6#Fjp6&7'FhnFin"#<"#&)Fjn7'FhnFin"#H"#NFjal7'FhnFinF_cm
FeqFjnFacmF;,
I%expFw,6$F-%"AGF;6$FUFVF;-Fgo6$w,6#%#sfGF;6$FUFVF;-Febl6#*&&Fjjl6#&FYFbtFap&FY
FdxFapF;F;6$F-FY6#Fap6$7'FhnFinF_[lF^]mFjnFa[lFXF;F;F;6#Fen6$7'FhnFinFdq"#[Fjn7
'FhnFinFdqFh^lFjnF;,
I-iniReductionw,6%'F-FC'F.FC'Fi[m%'posintG6+%#F1G%#F2G%$nF1G%"sG%#J1G%$FF2G%$JJ
2G%"XG%#s1G6"F;C(>F>-&F^w6#FgrF^p>FiqF>>Fjq-Fft6#F>>F[r,&-Fft6#&-FbclFibmFdxFap
FjqFin?(F;FapFapF;%%trueGC->Fcs-&%1PolynomialIdealsG6#%0PolynomialIdealG6$F>/%/
characteristicGFhp>F[t-&Fgo6#Fe^m6$w,6#%"jGF;6$FUFVF;-%'subsopG6$/FY%%NULLGF]pF
;F;6$FhemF>6#Fap6$7'FhnFinFh]lFe`lFjn7'FhnFinFh]lFbcmFjnF>>Fdt-Fgo6$w,6#FiemF;6
$FUFVF;-Ffgm6$FY/F\hmFjjlF;F;6$Fi[mFhp6#Fap6$7'FhnFinFdpFi]mFjnFgflF[t>Fit-F\\l
6$w,FchmF;6$FUFVF;-&Fggm6#%1IdealContainmentG6%F]p&FhzF^pF]pF;F;6&F\fmFcsF^fmFd
t6#Fap6$7'FhnFinF_[l"#rFjnF^`m7#-Few6#;FapFjq@$/-Fft6#FitF*[>Fit-Fgo6$w,FchmF;6
$FUFVF;7%F\p-Fft6#&-Fbcl6$&Fhz6#F\pT(Fdx-Fgdl6$&FjzFb\nFc\nF;F;6*F_fmFitF]fmF[t
F.FXFhemF>6#Fap6$7'FhnFinFi_lFh`lFjn7'FhnFinFi_lFdpFjn7#-Few6#;FapFc[n>Fit-&F_^
m6#%3FindMinimalElementG6$Fitw,FfjlF;6$FUFVF;52Ffdm&FXFdx3/FfdmFj]n2&FX6#Fjp&FY
F_^nF;F;F;6#Fen6$7'FhnFinFa_l"#*)Fjn7'FhnFinFa_l"#^Fjn>F>&F[t6#&FitFbt>FjqFifm>
FcuF\gm@$2FcuF[rC$>FiqF>>F[rFcuO-%'removeG6%F[v7#-Few6#;Fap-FftF^p-Fgo6$w,Fa\mF
;6$FUFVF;-Ffbm6$FY-Fefm6#FjjlF;F;Fgdm6#Fap6$7'FhnFinF]oFi]mFjn7'FhnFinF]oFa_lFj
nFiqF;F;F;6#Fjp677'FhnFinF[^mFi^lFjnF]gl7'FhnFinFh_mF]]mF[_l7'FhnFinFjnFe_lF[_l
7'FhnFinFjpFccmF[_l7'FhnFinFjpFjalF^]m7'FhnFinFdq"#oF[_l7'FhnFinFdqFfqF[_l7'Fhn
FinFdqF`glF[_lFaan7'FhnFinFdqFc_lFa_l7'FhnFinFf]lF*"#`7'FhnFinFdq"#(*F[_l7'FhnF
inFdq"#!*F[_l7'FhnFinFdqF[blF[_lFian7'FhnFinFdqFgilF[_l7'FhnFinFdqFa_lFa_l7'Fhn
FinFgpFeqF[_l7'FhnFin"#I"#PF[_lF_glF;,
I/shiftExpansionw,Fdcl6(%#SPG%#sFGFdhmFEFgblF66"F;C&>F[tF`r>6$F>Fiq-FbclFifl?(F
jqFapFapFj_nFbgmC%>F[r-Fgx6%FiqFbw&&F>6#FjqFbt?&Fcs&Facn6#;FenF;0-Fft6#F[rFap-%
+intersect=G6$F[r-Fgx6%FiqFbwFcs>F[t7$&F[tF;-Fcbm6$7$FjqFcs-F[vFatOF[tF;F;F;6#F
en6+7'FhnFinF_cmFi^lFjn7'FhnFinFh]lF]`lF[_l7'FhnFinFjpFf]lF[_l7'FhnFinFjpFjalFj
al7'FhnFinFdqF^glF[_l7'FhnFinFdqFc`lFjal7'FhnFinF^em"#nFgp7'FhnFinFdq"#RF[_l7'F
hnFinFjpF]qFfqF;,
I-neighborMonsw,6%%#BsGF.%(sShiftsG6#%$vBsG6"F;C$@(/FhpFap>F>-Fgo6%-%"@G6$F_]l&
F^w6#%"*GFYFX/FhpFin>F>-Fgo6%-Fcfn6$F_]lFgxFYFXFd`m>F>-Fgo6$F_]l-Fgo6%-Fcfn6$F_
]l<$FefnFgxFYFXO-F]hl6$F>FYF;F;F;6#Fjp6(Fi`n7'FhnFinFjpFedlFa_l7'FhnFinF[blF_cl
F[_l7'FhnFinFepFfqF[_l7'FhnFinF^glF_anF[_l7'FhnFinFjpFb[lFfqF;,
I-rowReductionw,6$F\bmFi[m6$%#bsG%&r2delG6"F;C%>F>-&Fg`m6#%,RankProfileG6$FX)FY
%#%TG>Fiq-Fd_n6%F[v7#-Few6#;Fap-F_]l6$Fa]lFYF>O6$&FY6$F>Fj[lFiqF;F;F;6#Fen6&Fi`
n7'FhnFinFjpFfqF[_lFd`l7'FhnFinFjpFf]lFfqF;,
I.scoreFunctionw,6'F^dm%#nFGFdbnFcbn%#NAG6'FdhmFEFgbl%#A1G%#nrG6"F;C&>F[rF`r?(F
>FapFapFXFbgmC%>Fiq-Fgx6%FhpFbw&&9'FjfmFbt?&Fjq&Fb[oFecn0-FftFaam&9(Fjfm-F[dn6$
Fiq-Fgx6%FhpFbwFjq>F[r7$&F[rF;-Fcbm6$7$F>Fjq-F[v6$FjqFiq>FcsFhcnO7&,&-FftFahlFa
pFcsFinFcsF[rFYF;F;F;6#""&6+7'FhnFinFi_lFi^lFjn7'FhnFinF_[lFh_mF[_lF\enF]en7'Fh
nFinFdq"#yFjal7'FhnFinFfqF\[nFgp7'FhnFinFdqFgamF[_lFh_l7'FhnFinFjpF]]mFfqF;,
I'shiftsw,6)F-Fhcm%#_AGF.Fi[mFhen%*manShiftsG6.%#nAGFdjn%#tmGFgjnF8%$sf1GFdhmFg
blF\bmF7Fehn%$_A1G6"F;C*>F>-Fft6#FX>FiqFj_n>Fjq-%%timeGF;@'3/F>F*0-Fft6#9*F*>F[
r-F_hm6$w,FchmF;6$FUFVF;-Fcbm6$7$FYF]p-F[v6$F]p&T&F^pF;F;6&FgblFitFi]oF^_o6#Fap
6$7'FhnFinF]_l"##*Fjn7'FhnFinF]_l"#gFjnF^_oFj^o>F[r-F`bn6$FYFc[oC%>Fcs7#-Fcbm6$
-Fden6%<#-Fcbm6$&F[tFdx-F[v6$F[t-F\\l6$w,F]dmF;6$FUFVF;/FedmF]pF;F;6$FdhmFdt6#F
ap6$7'FhnFin"#dF_anFjn7'FhnFinF[boFa`oFjnFXFc[o9)/Fdt;FapFiq>F[r7$F_el-Fcbm6$-F
cbm6$7$FdtFit-F[v6$Fit&Fcs6#FdtF^bo>F[r-Fd_n6%F[vF[rFhp>6$FcuFhu-Fe[m6%-Fecm6$F
YF[rFc[oFi[o>6$FcuFdv-F`hn6$FcuFi[o>6$F[rFiw6$-&Fd_nF`hm6%F[vF[rFdv<$&&F[rFcxF;
&FhpF;O6(FcuFhuF[rFiw-Fbel6#-Fgo6$w,F]dmF;6$FUFVF;-Fgdl6$FfdmFjjlF;F;6$F.Fc[o6#
Fap6$7'FhnFinF]`lFa`lFjn7'FhnFinF]`lFjnFjnF[r,&Ff^oFapFjqFinF;F;F;6#Fdq607'FhnF
inFedlFi^lFjn7'FhnFinFedlF[blFbq7'FhnFinFepFjnF[_l7'FhnFinFjpFh^lF[_lF[hn7'FhnF
inFben"$/"F[_l7'FhnFinFdpF[oF[_l7'FhnFinFdq"$+"F[_l7'FhnFinFdqF[boF[_l7'FhnFinF
dqF[`lF[_l7'FhnFinFjpF^]mF[_lF\`l7'FhnFinFjpFfflF[_l7'FhnFinFjpFc`lFfqF;,
I(shifts1w,6)F-FhcmFh]oF.F/Fi[mFhen6-FdjnF\^oF8F]^oFdhmFgblFcbn%#spGFejn%$SCsGF
gjn6"F;C->F>Fj_n>FiqFf^o>Fjq7#-Fcbm6$-Fden6%<#-Fcbm6$&F[rFdx-F[v6$F[r-F\\l6$w,F
]dmF;6$FUFVF;FfaoF;F;6$FdhmFcs6#Fap6$7'FhnFinFdanFc[mFjn7'FhnFinFdanFa`lFjnFXFc
[oF^_o/Fcs;FapF>>Fjq7#-Fcbm6$-Fcbm6$7$FcsF[t-F[v6$F[t&Fjq6#FcsFaho>Fjq-Fd_n6%F[
vFjqFhp>6$FdtFit6$&-FbclFd`oFbt&-Fbcl6$-FecmFiflFc[oFdx>Fcu-&F^w6#Fft6#7#-Fcbm6
$-F\\l6$w,F]dmF;6$FUFVF;FfaoF;F;F\ho6#Fap6$7'FhnFinFh]lFc_lFjn7'FhnFinFh]lF^bnF
jnFXFaho>Fhu-Fgo6$w,F]dmF;6$FUFVF;-Fajn6'FYF]p-F^dl6$Fhz-Fefn6%&FizFddmFbwFfdmF
izFjzF;F;6*FdjnF>FffoFitFcbnFdtFejnFcu6#Fap6$7'FhnFinFh^lFi]mFjn7'FhnFinFh^lF_c
mFjnFjq>Fhu-Fcjl6$Fhuw,FfjlF;6$FUFVF;552Fedm&FXFbt3/FedmFc\pFi]n3F\^n-%(testOrd
G6%&&FY6#FcrFdx&&FXF\]pFdxFjjlF;F;6$F/Fi[o6#Fen6$7'FhnFinFgp"$:"Fjn7'FhnFinFgpF
h_mFjn>Fdv&&FhuFbtF_^nO6'-Fe[m6%-Fecm6$FYFdvFc[oF]boFdvFhp-Fgdl6$&&Fg]pF\]pFdxF
c[o,&Ff^oFapFiqFinF;F;F;6#Fdq6.F\glFeeoFgeo7'FhnFinFjp"#'*F[_lFd`l7'FhnFinFjpFh
_mF[_lFdam7'FhnFinFjpFdanF[_lFg`l7'FhnFinFjp"$;"F[_l7'FhnFinFjpF_cmF[_l7'FhnFin
FjpF_`oFfqF;,
I+actionMonsw,6$Fdem'%)sActMonsG<$FCFfem6$%#aMGF56"F;C%@%-F[s6$FXFC>F>FX@*F^v>F
>FY/FXFen>F>-Fgx6%FapFbwFY/FXFjp>F>7$&F_`pF;&FYF;/FXFcr>F>7%Fd`pFe`p-Fcbm6$&-Fg
x6%FiqFbw-%%subsG6$/FiqFjhmFYF;-F[v6$FiqFY-F`v6%Q+|+%-40s%a|+|+F;Q2Action~monom
ials:F;F>O-Fgo6$w,6#%#amGF;6$FUFVF;-Fb`m6%-F[s6$FYFCFY7#FYF;F;F;6#Fap6$7'FhnFin
Fh^lF[oFjnFj[pF>F;F;F;6#Fen6,FeilF[hn7'FhnFinFbqFa_lF[_l7'FhnFinFdqF`qFa_l7'Fhn
FinFh_mFjnF[_l7'FhnFinFeqFgamF[_l7'FhnFinFeq"#aF[_l7'FhnFinFeqF\foF[_l7'FhnFinF
jpFe_lFgp7'FhnFinFjpFf^nFfqF;,
I4solvingSetReductionw,6(F]bm%#PsGFgen%#AVG%#nEG%"JG6&%$B1sG%%nB1sG%%aB1sG%"KG6
"F;C&>F>Fhp>FiqFin?(F;FapFapF;0FifmFiqC&>6$FiqFjq6$Fifm-F^dl6#-Fcbm6$-Fefn6%F4F
bwF>-F[v6$F4Fc[o-%'union=G6$F>-%*intersectG6$FjqFX>F[r-Fgo6$w,FgelF;6$FUFVF;,&-
Ffbm6$FYFjjlFapFj_oFinF;F;6&F]bmFYFgcpFi[o6#Fap6$7'FhnFinFi_lF^emFjn7'FhnFinFi_
lF_[lFjn-F]hlFeep-Faep6$F>-Fgo6$w,6#FdglF;6$FUFVF;&Fc_mF;F;F;6$FhcpF]bo6#Fap6$7
'FhnFinFb[lF^bnFjn7'FhnFinFb[lFepFjnF[rOF>F;F;F;6#Fi^l6+7'FhnFinFb[lFi^lFjn7'Fh
nFinFedlFdpFbq7'FhnFinFgpF^bnF[_lF]an7'FhnFinFdqFaclF[_l7'FhnFinFdqFccmFgp7'Fhn
FinFdqFiilF[_l7'FhnFinFdqF]]mFgp7'FhnFinFjpF`qFfqF;,
I0completeSetTestw,6$FgenF.6'%#vvGF5%#ttGFgbl%&vars1G6"F;C%>FcsFX>F>-F\\l6$w,Fg
elF;6$FUFVF;-%'andmapG6$w,F^zF;6$FUFVF;5-F[v6$*&FjjlFapFYFapFj_o-F[v6$*&FjjlFap
FYFinFj_oF;F;6&FgblFYFgenFj_o6#Fap6$7'FhnFinFh]lF[boFjnFijoF]pF;F;6&FbhpFcsFgen
FY6#Fap6$7'FhnFinFi_lFc[mFjnFbfpFY@%0FifmF*C$>Fjq-Fgo6$w,F^zF;6$FUFVF;-Fb`m6%-F
[v6$*&&F]pFbtFapFYFapFj_o7$F[[qFap7$*&F\[qFapFYFinFinF;F;6&F`hpF>FgenFY6#Fap6$7
'FhnFinF_cmF\[nFjn7'FhnFinF_cmFgpFjnFcsO6$7$-Fcbm6$&F[rFbt-F[v6$F[rFjq&F>Fbt7#-
Fcbm6$FegoF[\qOF*F;F;F;6#Fen6)7'FhnFinFdpFi^lFjn7'FhnFinFf]lFc_lF[_l7'FhnFinFjp
"#pF[_lF[hn7'FhnFinFdq"#zF[_l7'FhnFinFdqFfflFfq7'FhnFinFjalFi_lFfqF;,
I,solvingSetsw,6(F\bmF7FfcpF/%%deg0GFi[m64%#VsGFcoF_alF4Fecp%#RsG%#EsGF]bm%#tMG
%$rnkGFgcp%$nERG%"rG%"CG%$PRsG%#mRGFhcpFgen6"F;C/>F>-%(convertG6$FX%$setG>Fdt<"
>FdvFin>Ffdp-F_]l6$FapFY?(F;FapFapF;0-FftFjboFdvC/-%'minus=G6$F>Fdt>Fcs-Fdep6#-
Fcbm6$-F\\l6$w,FgelF;6$FUFVF;-F[v6$*&F]pFapFYFapFhzF;F;6&F4F[rFa]qF>6#Fap6$7'Fh
nFinFjnFf^nFjn7'FhnFinFjnFbenFjnF>-F[v6$F[rFhp@$2-FftF]ioFi[oOF*>F[t-F]hl6$-F^d
l6#-Fcbm6$-Fefn6%F[rFbwFcsF``qFcs-Faep6$Fdt-F]hl6$F>-F^dl6$F[tFcs>Fit-F_y6#7%&-
F^jl6$7#&FdtF;Fc[oF;&-F^jl6$7#FadnFc[oF;&-F^jl6$7#&FcsF;Fc[oF;>Fcu-Fiam6%FYFXFi
t-&Fg`m6#%*RowReduceG6-F]boFcuFiqFjqFjqF*F*.FhuF*F*Fbgm>FdvFj^q>Fiw,&FdvFapFetF
ap>Fd[l-F\\l6$w,FchmF;6$FUFVF;2F]pFfdmF;F;6$FgcpFdv6#Fap6$7'FhnFinF_[lFbcmFjnF^
`m7#-Fcbm6$7$Fey-Ffbm6$Fap&Fcu6$Fey;F;Fiw/Fey;FapFhu>Fd[l-F\\l6$w,FchmF;6$FUFVF
;-&%+ArrayToolsG6#%'IsZeroG6#&F]p6$Fedm;,&FfdmFapFapFapFhzF;F;6&Fd]qFcuFf]qFiw6
#Fap6$7'FhnFinF_[lF]jlFjnF^`mFd[l-Faep6$Fdt-F]hl6$F[t-F_^q6$&Fit6#-%%map2G6%F_]
lFenFd[lFa^q>82-F_^q6$&Fit6#-F\\l6$w,FchmF;6$FUFVF;2F]pFYF;F;6$Ff]qFiw6#Fap6$7'
FhnFinFeqFjnFjn7'FhnFinFeqF^bnFjn7#-Fcbm6$-Ffbm6$Fap&Fcu6$FeyFj[lFfdqFa^q>6%F[t
FcsFiw6%-F^dl6$F[tFgfq-F]hl6$FcsFgfq,&FiwFap-Fft6#FgfqFap>FitFfaq>FcuFhbq-F[cq6
-F]boFcuFiqFjqFjqF*F*F*F*F*Fbgm>83-Ffbm6$Fap&Fcu6$Fj[l,&FdvFapFapFap>847#-Fcbm6
$-F_^q6$&Fit6#-&F^w6#%"+G6%-F_^q6$-&F_eq6#%,SearchArrayG6#&Fcu6$Fey;,&FiwFapFap
FapF;FCFbwFiwFa^q/Fey;F\iq,(F\iqFapFetFapFinFapO<#-Fcbm6$-Fbcp6(FitFcs85FhpFdvF
ciq-F[v6$Fd[rFciqF;F;F;6#Fi^l6>Fg^l7'FhnFinFedlFbcmFbq7'FhnFinFe_lF[boF[_l7'Fhn
Fin"#tFh`lF[_l7'FhnFinFjpFdpF[_lF]an7'FhnFinFdqF_[lFgp7'FhnFinFdqF`enF[_lF[bn7'
FhnFinFbcmF_bnFfqF`an7'FhnFinFdqFc_lFgpFaan7'FhnFinFdqFjnF[_l7'FhnFinFdqFh`lFgp
7'FhnFinFdqFgpF[_l7'FhnFinFdqFepF[_l7'FhnFinFdqF`cmF[_l7'FhnFinFdqF_`lF[_l7'Fhn
FinFdqF[boFgp7'FhnFinFjpF_`oF[_lF\_l7'FhnFinFjpFi\qF[_lFj_l7'FhnFinFjpF\\rFgp7'
FhnFinFjpF]oF[_l7'FhnFinFjp"$7"F[_l7'FhnFinFjpF`enFfqF;,
I&getTDw,6*FgenFfcpF_]q%$mxnGF7FhcmF/%%cmplG6&F4Fb]qFc]qF]bm6"F;C&>Fiq-F]hl6$-F
^dl6#-Fcbm6$-Fefn6%F>FbwFY-F[vFibmFY>Fjq-F]hl6$-F_^q6$Fi[oFa^q-F^dlFcap>F[r-F_y
6#7%&-F^jl6$7#&FjqF;F^_oF;&-F^jl6$7#&FiqF;F^_oF;&-F^jl6$7#Fe`pF^_oF;O7)FXFhp7%-
FftFbcnFg[oFj_nFc[oF[rF]bo9+F;F;F;6#Fjal6'7'FhnFinFjalFi^lFjn7'FhnFinFjpF^emF[_
l7'FhnFinFjpF[_lF[_lFj\r7'FhnFinFjpFg\qFfqF;,
I-templateTestw,6*F\bmF7FhcmFfcpF.F/F_]qFi[m6(F\^o%$OutG%$BBsG%%BB1sGFgenFd]r6"
F;C*>F>Ff^o>Fiq-F\]q6(FYFXFc[oF]boF^_oF^`r@$/FiqF*O6$F*,&Ff^oFapF>Fin>6$FjqF[r-
%-selectremoveG6$w,6#FgenF;6$FUFVF;0-F\hpF]fpF*F;F;6$F.Fi[o6#Fap6$7'FhnFinFbcmF
]jlFjn7'FhnFinFbcmF[`lFjnFiq@%0F]`rF*>F[tFap>6$F[tFjq6$F*F[r>Fjq-Fd_n6$w,F]brF;
6$FUFVF;-%&orseqG6$-%'subsetG6$%$Bs1GFY-F[v6$Fgcr-F]hl6$F]p<#FYF;F;6$Fj`rFjq6#F
ap6$7'FhnFinF_cmFiilFjnFd[qFjq>Fjq-Fgo6+F`]rFjqFc[oF^_o7#Ff^qFXFhpF]boF[tO6$-Fb
]n6$F__rw,FfjlF;6$FUFVF;52&FX6#Fdq&FYF^er3/F_erF]er2&F`^n6#Fin&F^^nFderF;F;F;6#
Fen6$7'FhnFinF_cl"$,"Fjn7'FhnFinF_clFeamFjnFfarF;F;F;6#Fjal6.Fi`nFgeo7'FhnFinFj
pF[oF[_l7'FhnFinFjpF^]mFa_l7'FhnFinF_cmFjnFfqF`foF[hn7'FhnFinFepF]`lF[_l7'FhnFi
nFjalFeqF[_lFf\q7'FhnFinFjpFc[mF[_l7'FhnFinFjp"$9"FfqF;,
I-colReductionw,6%F\bmFgcpFi[m6&Fd]qFdhnFg]q%&c2delG6"F;C'>F>-&Fg`m6#%%CopyG6$F
hpFY-F[cq6-FhpF>Fgin-F_]l6$F_^lFYFdgrF*F*.Fe]qF*F*Fbgm>Fiq7#-Fcbm6$-Ffbm6$Fap&F
>6$FjqFj[l/Fjq;FapFe]q>F[r-Fd_n6%F[v7#-Few6#;FapFXFiqO6%&FY6$Fj[l-Fd_n6%F[v7#-F
ew6#;FapFdgrF[rF>F[rF;F;F;6#Fjp6(Fi`nFc`r7'FhnFinFjp"$5"FgpFdam7'FhnFinFjpF_bnF
[_l7'FhnFinFjpFfflFfqF;,
I0sparseReductionw,6''F\bmFiy'Fhcm-FC6#FC'Fgcp%*nonnegintG'%&spolsGFCFeem6-%#rg
GFj\l%"kGFcoF_al%$crgG%#M1GFdhn%#ldG%$rpnG%$cpnG6"F;C.>F>-Fgo6$w,FchmF;6$FUFVF;
-Few6#;,&-Feu6$-Fft6#&Fjjl6#Fhz/Fhz;Fap,&FYFapFinFapFapFapFap-Feu6$Fh[s/Fhz;Fap
FYF;F;6&FhcmFXFj\lFiq6#Fap6$7'FhnFinF`qF_anFjn7'FhnFinF`qF[^mFjnFc[o@$/FifmF*O6
%F*F`rF`r>6%FjqF[rFcs6$FifmFf^q>F[t-Fd_n6%F[v7#-Few6#;FapF[rF>>Fdt-%$<,>G6$F[jn
&FY6$F[tFj[l>Fit-Fjhn6$Fi[o)&Fdt6$F`[n;FapFhpF_in>Fcu-Fd_n6%F[vF][nFit>Fhu&7$F`
dlFadn6#7%&FitF;&FcuF;-Few6#;,&FjqFapFapFapF[r>Fit-Fjhn6$Fi[o&Fdt6$FitFb^s>Fcu-
Fd_n6%F[v7#-Few6#Fb^sFit>Fdv7%F[_sF\_s-Few6#;,&FhpFapFapFapFcsO6%Fc[nFhuFdvF;F;
F;6#F\]o60Fd\q7'FhnFinFjpFaqF[_l7'FhnFinFjpF[oFa_l7'FhnFinFb[lF_bnFfqFf_l7'FhnF
inFjpF]]mF[_l7'FhnFinFjpFbcmF[_l7'FhnFinFjpF_`lF[_lF\`l7'FhnFinFjpFa_lF[_l7'Fhn
FinFjpF]jlF[_lFi`sFf_l7'FhnFinFjpFeqFfqF;,
I*checkDataw,6%F-Fi[m%&iVarsG6#%#nvG6"F;C'@$4-F[s6$FYF]sC$-F`v6#QHF~is~not~a~li
st~of~Laurent~polynomials|+F;OF*@$30FXF*4-%(isprimeGFc^oC$-F`v6%QA%a~is~not~pri
me,~use~%a~instead|+F;FX-%*nextprimeGFc^oOF*>F>-Fft6#-F`hlF^p@$4-Fc\l6$31FapFj
\l1Fj\lF>-F[v6$Fj\lFhpC$-F`v6#Q:Invalid~indices~in~iVars|+F;OF*OFapF;F;F;6#Fjp6
.7'FhnFinFh]mFi^lFjn7'FhnFinFjp"$1"Fa_l7'FhnFinFc_l"#()Fgp7'FhnFinFhan"#)*Ffq7'
FhnFinFjp"$<"Fa_l7'FhnFinF_bnFhdsFgp7'FhnFinFier"$4"FfqFi[r7'FhnFinFjpFieoFa_l7
'FhnFinFe_lF`cmFgp7'FhnFin"#))Ff^pFfqFcenF;,
I,readProblemw,6'F%'Fi[mF`jr'FbasFC'%,delHardPolyGF`jr'FhenF^am6(%*proc_nameG%$
ff1G%$ff2G%'spols0GF-%&p2delG6"F;C1>F[rF`rAQ6../problems/_common.mF;A-Fbal6%Q/.
./problems/F_F;FYQ#.mF;>F>-%%evalG6#-Fbal6$%#C_GFY@$-F[s6$F>%*procedureGC$>Ffdp
6$-F>6#/%)symbolicGF*Fhgs>F[r7#-&F_^m6#%*SearchAllG6$F*-&F^w6#Febl6#-&F^w6#%"-G
6%FiqFbwFjq>Fcs-F_^q6$-Fdhs6#-F\gs6#-Fbal6$%#F_GFYFC@$/-F_as6%-FefmF]ioFXFhpF*Y
Q-Invalid~dataF;>6$FdjnF.6$Fd`q7#&-F`hlF]ioF;>F/-%%tdegG6#&F.F;@$/Fc[oFapC$>F[t
-F`em6%FcsF.FX>Fcs-F_ap6$-Fgo6$w,6#Fj\lF;6$FUFVF;/F\pF*F;F;6$F-Fcs6#Fap6$7'FhnF
inF[blF^bnFjn7'FhnFinF[blF^glFjnF[tFcs>Fcs-F_ap6$-F]w6%&F.FahlFbw-Fgx6%FapFbwFa
\tFcs@%3-F[s6$FcsF]s/Fi[oFap-%'assignG6$.Fh\pF_il-Fj\t6$F\]tFagl@%Fbbs@%-%$hasG
6$Fcs^#FapC$-%&aliasG6#/%#iUG-%$modG6$-%'RootOfG6#z'Fifp#Fap!FapFX>Fhem-F\^t6$-
F_ap6$/Fd]tFj]tFcsFX>Fhem-F\^t6$FcsFX>FhemFcsAQ.redundantAG.mF;O6(FcsFdjnF.F/Fh
emF[rF;6(FdjnF.F/FhemFj]tFh\pF;6#F\]o6>Fg^l7'FhnFinF^bnFgamF[_l7'FhnFinFjpFbqF[
o7'FhnFinFjpFgilF[oFi`sF[hnFggp7'FhnFinFdqFa`oF[_l7'FhnFinFjpFe_lF[_l7'FhnFinFj
pFc`lFa_l7'FhnFinFa_lF_`lFe_lFf`l7'FhnFinFjpFb[lF[_lF[hnFjanFc]oFc`r7'FhnFinFjp
"$I"Fa_l7'FhnFinF^emF`cmFgp7'FhnFinFj`l"$@"FgpF[hn7'FhnFinFdqF^]rFa_l7'FhnFinFf
]lF^cpFgp7'FhnFinF[boF`glF[_l7'FhnFinFhanFieoF[_l7'FhnFinFjalF[^mF[_l7'FhnFinFj
pF^glF[o7'FhnFinFjpFbenFfqF;,
I(getDataw,6'F-FdjnF.F/%#tdG6@FfcpF_]q%$ptnGF7FhcmFd]rFbjrFi[mFbasF\bm%#V0GFehn
Fc]rFgcpF2Fgen%#iqG%#B0GF1FdhmFg]qFijrFjjrFd]qFifrF4%#r1G%#r2G%#iTGFE6"F;C6>6+F
>FiqFjqF[rFcsF[tFdtFitFcu&&Fi[o6#7$-Few6#;FapFjp-Few6#;F\]oF^qF;>Fcs-Fcjl6$Fcsw
,FfjlF;6$FUFVF;Fb\pF;F;F;6#Fen6$7'FhnFinFi_lFbqFjn7'FhnFinFi_lFb[lFjn>6$FhuFdv-
Fe[m6%-Fecm6$FYFcsFhpFit>6$FhuFiw-F`hn6$FhuFit>6$FeyFcs6$7#-F_]l6$FapFhu-Fghm6$
&-F]w6%FiwFbwFjhmF;Fcs>6$Fd[lFgfq6$&FjqFbt&FjqFder>F\iq-F_^q6$&F[r6#;,$FgfqFinF
;Fa^q@%/F[tFap>Ff[r-F\hp6$F\iqFhp>Ff[r6$F`r7#-Few6$F*Fj\o>86-Fd_n6%F[v7#&F\iqF;
Fd[r>Ffet7$&-F^jl6$FfetFc[oF;&Fd[rF;>F[r-F_y6#7$&F[r6#;Fap,&FgfqFinFinFap&FfetF
;>Fhu-Fiam6%FhuFdvF[r>Fcs7#-Fcbm6$-Fgo6$w,6#F]^oF;6$FUFVF;FfdmF;F;F;6#Fap6$7'Fh
nFinF_cmFh]lFjn7'FhnFinF_cmF[blFjn-F\\l6$w,F]dmF;6$FUFVF;FfaoF;F;6$Fdhm876#Fap6
$7'FhnFinF_bnF^emFjn7'FhnFinF_bnFgilFjnFcs/F_htFghr>6%88898:-Fhir6'FhuFcsFd[lFd
tFit@$0FghtF*>6$FhuF[r6$&Fhu6$FhhtFiht&F[r6#Fiht>6%Fhu8;8<-Fefr6%FhuFd[lFit-%#-
=G6$Fd[l-Fft6#Fhit?&8=F>FbgmC%>6$8?8>-Fjar6$w,F_\lF;6$FUFVF;-F[v6$*&F]pFapFgjmF
apFhzF;F;6&F4FajtF1Ffet6#Fap6$7'FhnFinF^bnFa_lFjn7'FhnFinF^bnF[`lFjn7#-Few6#;Fa
pFgfq>8A-Fgo6$w,F_\lF;6$FUFVF;-Fb`m6%F[[uFjhm,&-Ffbm6$Fap&Fiz6$Fj[l-Ffbm6$F][uF
jzFapFazFinF;F;6,F4FajtF1FfetFd]qFgitF7F[rFgcpFd[l6#Fap6$7'FhnFinFi_l"$0"FjnF[]
nFc[u>8@7$7#-Fcbm6$&Ffjt6#-Ffbm6$F_htFh[u/F_ht;Fap-Fft6#Ffjt-Fgo6$w,F_\lF;6$FUF
VF;,&*&F]pFap,&-Ffbm6$*&FhzFap&FizF^pFapFizFapFinFapFapFapFYFapF;F;6(F2FgfqF4Fa
jtF1Ffet6#Fap6$7'FhnFinFg\q"$6"Fjn7'FhnFinFg\qF\[nFjnFejt>Fh[u-Fgo6$w,FchmF;6$F
UFVF;&-Fd_n6$w,Fd[tF;6$FUFVF;/&F]p6$FYFj_oF*F;F;6&Fd]qF]pFdhmFY6#Fap6$7'FhnFinF
b[lF]]mFjnF`gp<#-Few6#F]]lF;F;F;6$Fd]qFgit6#Fap6$7'FhnFinFh]mF[boFjn7'FhnFinFh]
mFh^lFjn<#&FhitF;O62-Fhhs6%FgctFbwFghtFiqF>FjqF[rFcsFhitFh[uFghtFhhtF\]uFciqF[t
FdtFitFcuF;F;F;6#F\]o6=F\glFf\qFj_lF_foF\`lFg_t7'FhnFinFjpFeqF[_lFf_lF[hn7'FhnF
inFdpFfqF[_l7'FhnFinFjalFjnF[_lFf_lFj`sFi`sFf_l7'FhnFinFjpFiilF[_lFh^p7'FhnFinF
jpFf^nFa_l7'FhnFinFi_lF]oF[_lFfam7'FhnFinFjpF_[lFgpF\en7'FhnFinFdqFa`lF[_l7'Fhn
FinFdqFjdsF[_l7'FhnFinFdqFj^pF[_lFf\q7'FhnFinFjpFd_lFfqF;,
I-dispTemplatew,6)'Fj`tFC'%$nTDGFfemFcemFdem'F/%3ShortMonomialOrderG'F\^o%&floa
tG'%'headerGF^am6+FdjnFc]rFfcpF\atF7FifrFEFg]qFd]r6"F;C'>F>Fj\o>6*FiqFjqF[rFcsF
[tFdtFitFcu&-Fg`t6'FhpF>Fc[oFi[oFY6#7*FapFjpFcrF\]oFdqFjalFedlF`q@$/F^_oFapC$-F
`v6$-Fbal6%Q"|+F;-Fb`m6%/FcuFapQ*Template~F;Q5INCOMPLETE~template~F;Q&#%g:|+F;F
X-F`v6'Q3%-20s%-20s%-20s%s|+F;Q0action~monomialF;Q+[#E,#R,#B]F;Q%sizeF;Q%timeF;
-F`v6'Q3%-20a%-20s%-20s%g|+F;Fjq-%+alterCommaG6#7$,&Fj[qFapFetFin&&F[r6#7$FenFj
pF;-FfduFaamF]bo@$F^cu-F`v6#FdcuF;F;F;6#Fdq6+Fi`nFeeo7'FhnFinFjpFhanF[_lF[hn7'F
hnFinFdqFhanFgp7'FhnFinFdqFfdsFgp7'FhnFinFjpFieoFgp7'FhnFinFjpFgilFa_l7'FhnFinF
gpFbqFgpF;,
I-saveTemplatew,6$F%Fiau64Fc]rF_]qFfcpF\atF7FhcmFifrFEFg]qFijrFbatF^atFd]rFbjrF
i[mFbas%#fdG%#fnG6"F;C'>Fd[r-Fbal6$Q-templates/t_F;FY>62F>FiqFjqF[rFcsF[tFdtFit
FcuFhuFdvFiwFeyFd[lFgfqF\iq-Fg`t6'FhemFdjnF.F/FX>Fciq-%&fopenG6$Fd[r%&WRITEG-%(
fprintfG61FciqQG%a|+%a|+%s|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%aF;F>Fiq&-F_^q
6$FjqF'6#;Fen!"#F[r-F_^q6$FcsFCF[tFdtFit7%Fd[lFcuFhuFdv7$F\iqFiwFgfqF`r-%'fclos
eG6#FciqF;F;F;6#Fen6(Fi`n7'FhnFinFd^n"$>"F[_l7'FhnFinFjpFh^uF[_l7'FhnFinFjpFepF
[_l7'FhnFinFjp"$%=Fgp7'FhnFinFjpFh]mFgpF;,
I-readTemplatew,6#F%64F_fuF^fuFc]rF_]qFfcpF\atF7FhcmFifrFE%'xspolsGFbatFbasF^at
Fi[m%$xE0GFj`tFgbl6"F;C6>F>Fcfu@$4-&%*FileToolsG6#%'ExistsGFjfmY6$Q2File~%1~not
~foundF;F>>Fiq-F\gu6$F>%%READG>Fjq-%&parseG6#-%)readlineGFjfm>F[rFaju>Fcs7#Faju
>F[tFaju>Fdt-F\gs6#-F_^q6$FajuF_y>Fit-&F^w6#F\gs6#Faju>FcuFaju>FhuFaju>FdvFaju>
FiwFaju>6$FeyFd[l&FajuF;>FgfqFaju>F\iqFaju-F^huFaam>Fit-F_hm6$w,FchmF;6$FUFVF;-
Fcbm6$Ff_o-F[v6$F]pFgjmF;F;6&FgblFd[rFhcmFit6#Fap6$7'FhnFinF[blFe`lFjnF[\tFit>F
ciq7,FcsF[rF[t7$Fbdt-FeuFgtFdtFit-Fb`m6%-F[v6$F*Fd[lF*Fap&FdvFbtFgfqFeyO60FjqF[
rFcsF[tFdtFitFcuFhuFdvFiwFeyFd[lF\iqFciqF;F;F;6#Fap68Fi`n7'FhnFinFedlFbenFbq7'F
hnFinFjp"#vFa_l7'FhnFinF_bnFfflFe_l7'FhnFinFjpF^glF[_lF[auFj`sFj`sF[au7'FhnFinF
jpF_clF[_lF\`l7'FhnFinFjpF^bnF[_lFg^pFf_l7'FhnFinFjpFh]lF[_lFf`lF_^vF[auFhhu7'F
hnFinFjpFf^nF[_lFi\r7'FhnFinFjpFaqFfqF;,
I.backwardErrorw,6&FcemFdem'F8FiyF_]q6+FdjnFhem%$solGFdhmFejr%$bweG%#nSG%"dG%#b
bG6"F;C+>F>Fj_n>Fiq-FdhsF^p>Fdt-F_]l6$F_^lFhp>Fit-%$minG6$Fc[oFdt>Fjq7#-Fcbm6$-
F]w6%FXFbw-F_^q6$&Fhp6$Fj[lFcsFC/FcsFgw>F[t-Fh]s6#-Fcbm6$*&F>Fin-Feu6$*&-%$absG
6#-F_ap6$F\io&FiqFicnFap-F\gs6#,&-F_ap6$F\io-Fgo6$F]avFaavFapFapFapFin/F[rFbhoF
apFb`v>F[t-Fcjl6#-FbxFgt@$FijsC%>Fcu-Fgx6%&F[t6#;FapFhguFbw&F[tFecn>Fit-&Ff_v6#
%&indexG6#Fcu>Fit-Fb`m6%2&FcuFd[n,$%'DigitsG#FapFenFitFdtO7&&F[t6#;FapFit&F[t6#
;,&FitFapFapFapF;-Fbel6#Fgcv-&%+StatisticsG6#%.GeometricMeanGF_dvF;F;F;6#Fcr6/F
^]oFeeo7'FhnFinFepFbenF[_l7'FhnFinF]_lFj]vF[_l7'FhnFinFa]oFd_lF[_lFh^p7'FhnFinF
jpFddsF[_lF[enF[hnF^fo7'FhnFinFdqFf]lF[_l7'FhnFinFdqFc_lF[_l7'FhnFinFjpF[jlFfqF
;,
I/templateSolverw,6&F%>%'showAMGF*>%'showCPGF*>%)showRREFGF*6>F_]qFfcpF\atF7Fhc
mFifrF]iuFbasF^atF-F.F2Fg]qFijrF1F\bmFh]qFd]qF3F4F6%#evG%#cpGFdasFj\lFdhmF8F96"
F;C7>Ffat&-FihuF^p6#7&-Few6#;FenFdqFedlF]qFh]m@$-Fb]t6$F*FcuYQOThe~case~of~inco
mplete~template~is~not~handledF;>F[ct&-F^r6'FYF*FitF*Fap6#7$FapFjp>6%FiwFeyFd[l
6$Fcdt-F_]l6$;FenFjpFdt>Fgfq-F_^q6$&F[r6#;,$FiwFinF;FC>F\iq-Fiam6$-Fe[m6$-Fecm6
$FhuFcsFdvF[r>Fciq-Fd_n6%F[v7#-Few6#;Fap-F_]l6$F_^lF\iqF[t>6$F\iqF[r6$&F\iq6$Fj
[lFciq&F[rF_hu@$0FeyF*C$>F\iq&F\iq6$Fd[lFj[l>F]iv6$,&&F\iq6$;,&FeyFapFapFapF;F]
jvFap-F\y6$&F\iq6$F]jv;FapFey-F\y6$-&F]x6#%.MatrixInverseG6#&F\iq6$FcjvFcjv&F\i
q6$FcjvF]jvFin&F[r6#F]jv>Fd[r-&F]x6#%6ReducedRowEchelonFormG6#-Fbx6#F\iq@$FijsC
$-F`v6#QFReduced~row~echelon~form~of~template:F;-%&printG6#-Fbx6#Fd[r>FfetFjt>F
ght-&F]x6#%+ZeroMatrixG6#Fiw?&F_htFiqFbgm-%#+=G6$Fght*&-FfetF;Fap)-Fiy6#-Fgo6$w
,FgelF;6$FUFVF;-Fb`m6%Fh_q-&F_y6#%'columnG6$Fiz<#/-FfbmFi_qFap,$)&Fjz6$-Ffbm6$$
FapF*&Fjz6$Fj[l-Ffbm6$Fj_qFaz7#;,$FizFinF;F_inFinF;F;6,F4F_htF1FgfqF2FiwFd]qFd[
rF7F[r6#Fap6$7'FhnFinFbcm"$y"FjnFebrFgfqF_inFap@$F^vC$-F`v6#Q.Action~matix:F;-F
_\w6#-Fbx6#Fght>Fhht&-F\xFj_wFdx@$F^fnC%>Fiht-%'factorG6#-&F]x6#%9Characteristi
cPolynomialG6$Fght%'lambdaG-F`v6#QFFactorized~characteristic~polynomial:F;-F_\w
6#-FbxFdit>Fgit-FftFcx>Ffjt)-Fiy6#7#-Fcbm6$7#-Fcbm6$-Fb`m6%/&FcuF_jtFap*&&&Fhht
6#,(FgitFinFhitFapFhguFap6#FajtFap&&FhhtFderFgbwFin*&FhbwFapFcbwFin/Fhit;FapFgi
t/Fajt;FapFiwF_in>Fejt-Ff[l6#&Ffjt6$Fj[l-F\\l6$w,FchmF;6$FUFVF;-Fc\l6$-Ff\l6$&F
]p6$FhzFYF[]l/Fhz;FapFizF;F;6(F8FfjtFj\lFhitFdasFgit6#Fap6$7'FhnFinFf]lFa`oFjnF
g]l7#-Few6#F^cwO6%FfjtFejt-Fc^l6&FhuFdvFfjtF>F;F;F;6#Fap6CFidn7'FhnFinFjpF[jlF[
_l7'FhnFinFjpF`cmFa_l7'FhnFinFb[lFaqFe_lFh^pF\]rFf_lFdamF]frF\^vF[hnFd\r7'FhnFi
nFdqFh^uF[_l7'FhnFinFjpF^cpF[_l7'FhnFinFjp"#&*Fa_l7'FhnFinFb[lF_anFgp7'FhnFinF
\[nF[jlFgpFj_lFfirF\en7'FhnFinFdq"$'=Fgp7'FhnFinFjpF_anFa_l7'FhnFinFgpF]oFgp7'F
hnFinFa_l"#fFgpFb`rF[hn7'FhnFinFdqF`[lF[_l7'FhnFinFdqFdanFgp7'FhnFinFa`lF\[nFgp
F]\r7'FhnFinFjpFc]pF[_lFb`l7'FhnFinFjpFe`lFfqF;,
I+iniProblemw,6)F%'%+sparsePolsGFCFeem'Fbas-FC6#Ffem'%$symGF`jrFgesFies61F-Fdjn
F.F/FhemF^fsFbjrF_fs%$nuFGF0%#dmG%#d0G%#UPG%#v1G%#v2G6"F;C1>6(F>FiqFjqF[rFcsF[t
-F^r6'FYFhpFc[oF]boF^_o@%/Fb^oF*>FdtF[t>FdtFX>Fit7#-F_hs6$F*Fcs>Fcu-FefmFjfm-F`
v6%Q)%-40s%a|+F;Q7Number~of~polynomials:F;Fiq-F`v6%FdhwQ=Sparse~constant~polyno
mials:F;Fdt-F`v6%FdhwQ5Polynomials~removed:F;Fit-F`v6%FdhwQ5Number~of~monomials
:F;-Fft6#&-Fbcl6$F>FjqFdx-F`v6%FdhwQ+Variables:F;Fjq-F`v6%FdhwQ)Degrees:F;-Fgo6
%FgdlF>Fjq-F`v6%FdhwQ6Degrees~by~variables:F;-F_hm6$w,Fd[tF;6$FUFVF;-Fgo6$w,F^z
F;6$FUFVF;-Fgdl6$&F]p6#Fj_oF\drF;F;6&F-FhzFj\lFY6#Fap6$7'FhnFinF_anFhanFjn7'Fhn
FinF_anF\[nFjnF]pF;F;6&F.FjqF-F>6#Fap6$7'FhnFinF]jlFfanFjn7'FhnFinF]jlFiilFjnF>
>Fhu-Fes6%FcuF[rF[hm>Fdv-&Ffs6#%1HilbertDimensionG6$FhuF[hm@%0FdvF*C'-F`v6%Q)%-
40s%s|+F;Q1Number~of~roots:F;Q$infF;>Fey-Fgo6&&Ffs6#%5UnivariatePolynomialGFjqF
cuF[hm>F`dt-Fjar6$w,Fd[tF;6$FUFVF;-%&evalbG6#Ff[tF;F;6$F_gwFey6#Fap6$7'FhnFinF^
bnF[oFjnFb[u7#-Few6#;FapF]`r-F`v6'Q-%s%a%-25s%a|+F;Q/Variables~for~F;FdvQ1-dim.
~component:F;&Fjq6#Fd[l@%/FehqF*>FiwFapC$>Fiw-Ff_v6#-Fgo6$w,6#%"vGF;6$FUFVF;,&-
F[flFb\nFap-%(ldegreeGFb\nFinF;F;Fd]x6#Fap6$7'FhnFinFf]lFeamFjnFg]lFgfq-F`v6%Fd
hwQ8Number~of~roots~(sat.):F;FiwC$>Fiw-Fft6#&-F^tF_itFbt-F`v6%FdhwFd\xFiwO6(Fcs
FiqFjqF[r-Fb`m6%/Fi[oF*FiwFapFdtF;F;F;6#Fdq6>Feil7'FhnFinFjpF`cmF[_l7'FhnFinFjp
Fi\qFa_l7'FhnFinF^bnFa_lF[_l7'FhnFinFfqF\[nF[_l7'FhnFinFjpFgilF[_lF]\r7'FhnFinF
jpFf^nFgp7'FhnFinFjpFa`oFgp7'FhnFinFjpFfqFgp7'FhnFinFjpFg\qFgp7'FhnFinFjpFgamFg
p7'FhnFinFjpFa`lFgp7'FhnFinFjp"$-"FgpF_jn7'FhnFinFjpFa`lF[_lF[hn7'FhnFinFdqFfqF
gp7'FhnFinFdqFi]mF[_lFg\rFc\rFjbp7'FhnFinFh_mF]`lF[_l7'FhnFinF]qF]jlF[_l7'FhnFi
nF]qFa`oFgp7'FhnFinFdqF_clF[_l7'FhnFinFdqF_clFgp7'FhnFinFjpFeamFfqF;,
I/templateFinderw,6,F%>'%(dChangeGF`jrF*>FhesF*>FbasF`r>Fi]oF`r>%,primeNumberG"
&4+%>Fa_pFjp>FhenFap>FefwF`r>FjfwF*64F[bu%#TMGFhemFdjnF.F/F_]qFbjrFd_pFj^vF\bmF
7FhcmFh]o%#mdGF\^oFfcpFi`r6"F;C+>%#TDG-%&ArrayG6#F`r>F>F*>FeyF`r>Fd[lFc^q>FiqFf
^o>6(FjqF[rFcsF[tFdtFit-Fafw6)FY9,F]boFc[o9-FhpF^`r>Fcu-F]_p6$FcsF^_o?(FhuF*Fap
F;555Fj^o30FdtFap4-F[v6$Fdt-Fgo6$w,6#Fj`tF;6$FUFVF;FcerF;F;F;6#Fap6$7'FhnFinFa`
oF]clFjn7'FhnFinFa`oFiilFjnFecx4-F[v6$Fap-Fgo6$w,FbexF;6$FUFVF;F_erF;F;F;6#Fap6
$7'FhnFinFfanFj\uFjn7'FhnFinFfanF\foFjnFecx3/FdtFap2F>,$Fd`qFenC&@$/FhuF*-F`v6)
Q;%-15s%-15s%-15s%-15s%s|+%s|+F;Q"dF;Q,#cols-#rowsF;Q&#rowsF;Q'degreeF;Fadu-F\a
l6#F`en>6(FdvFiwFeyFd[lFgfqF\iq-Fb`m6%1FhuFX-Fe]o6)FjqFeyFd[lFcsF]boF^`rFi[o-Fb
fo6)FjqFeyFd[lFcsF[tF]boF^`r-F`v6(Q8%-15g%-15g%-15g%-15g%g|+F;Fhu,&-F_]l6$F_^lF
dvFap-F_]l6$Fa]lFdvFinFbhxFgfqF\iq?&FciqFcuFbgmC'>6$Fd[rF\iq-Fe`r6*FdvFiwFeyFci
qFcsF[tFdtF]bo@$/Fd[rF*\-F\]w6$F>Fap>-FecxFjfm7&F`ftFitF]boFc[o-Ffau6)-FecxFder
F>FjqFcsF[tF\iqFap-F`v6%Q*|+%-12s%g|+F;Q,Total~time:F;Fb^pF;6#FecxF;6#Fap67Fidn
7'FhnFinF^qFepFbq7'FhnFinFedlF_cmFbq7'FhnFinFg\qFj]vF[_l7'FhnFinFa]oF`cmF[_lFge
oF]]rFi`sF\en7'FhnFinFdq"$B"Fa_l7'FhnFinF_[lFdfrFgp7'FhnFinFdq"$d"F[_l7'FhnFinF
dqF_`oFgp7'FhnFinFdqFh]mFjal7'FhnFinF]qFi]mF[_l7'FhnFinF]qF_bnFa_l7'FhnFinFf]lF
*F^cp7'FhnFinF]qF_[lFgp7'FhnFinF]qFeamF[_l7'FhnFinF]qF]_lFgp7'FhnFinFjpF_clFgpF
;,
I.templateTest1w,6-F\bmF7FhcmFfcpF_]qFi[m%$nE1G%#nRGF2Fd]rFh]q6'F\^o%#C1G%#C2GF
gcpFd]q6"F;C*>F>Ff^o>Ffdp-Fjar6$w,F_\lF;6$FUFVF;1FYFjjlF;F;6$Fa[yF^_o6#Fap6$7'F
hnFinFh_mFccmFjnFi_m9.@$FgbrOFear>F[r,&F^_oFapFg[oFin>Fcs-F^gr6$F]boFY-F[cq6-F]
boFcsFginFdgrFdgrF*F*FfgrF*F*Fbgm@$-Fbcr6$0-Ffbm6$Fap&Fcs6$,(Fe]qFapF^`rFinFj\l
FapFj[l,&F[rFapFj\lFap/Fj\l;FapF^`rOFearO6$7)Fc[oFi[o7%F[rF^`rFadxFddrFXFhpFbdx
FfarF;F;F;6#F]q6-F^]oFgeoFg_l7'FhnFinFjpFe_lFa_l7'FhnFinF^glF]oFfqF^_lFc`rFdir7
'FhnFinFjpFhdsFa_l7'FhnFinF\[nFhanFfq7'FhnFinFjpF`[lFfqF;,
I2templateReductionw,6(F%Fiau>%*autoBckUpGF*>%)nRootTolGF*>%%sRedGF*>%)showInfo
GFap6?F`cxFa[yFb[yF2FfcpF_]qF]bmFhcmFd]rFbjrFi[mFbasF.F/FhemFgjn%#A2GFgjrF[^oFc
oFejrF^dm%#M2GFh]qFd[y%#V2GFi`rF\^o%#k0G6"F;C/>%$td1GFX>F>Ff^o>6-FiqFjqF[rFcsF[
tFdtFitFcuFhuFdvFiw6$&F^^nF;&&FX6#7%FapFenF^btF;>6%FeyFd[lFgfq&-F^r6'FYFdvFiwF*
Fap6#7%FjpFcrF\]o>6$FciqF\iq-Fjar6$w,F]dmF;6$FUFVF;-F[v6$FedmF]pF;F;6$FbjrFhu6#
Fap6$7'FhnFinFh_mF^]mFjn7'FhnFinFh_mFbcmFjnFit>6$F\iqFciq6$-Fcjl6$F\iqw,FfjlF;6
$FUFVF;-Fh\p6%Fj]nFfdmF]pF;F;6$F/Fd[l6#Fen6$7'FhnFinFb[lFdanFjn7'FhnFinFb[lFeqF
jn-Fcjl6$Fciqw,FfjlF;6$FUFVF;F]byF;F;F_by6#Fen6$7'FhnFinFfflFfanFjn7'FhnFinFffl
F]clFjn>Fit7$Fjet&FciqF;>Fghx6$-Fiam6$-Fe[m6%-Fecm6$FgfqFitFeyFdvFdtFit>FfetFc[
n>F_ht-Fb`m6%1F^qFfet-%%ceilG6#,$Ffet#FapF^qF^q@%/F]boFap-F`v6(Q7|+%-20s%-20s%-
20s%s|+%s|+F;F^duF_duF`duFaduFagx-F`v6(FedyF^duQ0[#E,#R,#B](raw)F;Q*size(raw)F;
FaduFagx?(FghtFapFapFfetFbgmC0>Fhht&FitF\`w>Fciq-F_ap6$/FhhtFjhmF\iq>Fiht&Fd[r6
$-F_ap6$/-Ffbm6$FhhtF\iqFjhm7#-Few6#;Fap-F_]l6$Fa]lFd[rFj[l>Fgit-Fgo6$w,FgelF;6
$FUFVF;-Ffbm6$FYF]pF;F;6$F]bmFdt6#Fap6$7'FhnFinFi_lF^]mFjnFbfp-F]bl6$*&&Fgfq6#&
FhhtFbtFap&FhhtFdxFapFey>Fgit-F\\l6$w,F_\lF;6$FUFVF;-F^eq6#&F]p6$Fj[lFYF;F;6$Fb
_yFiht6#Fap6$7'FhnFinF_[lF_clFjnF^`mFgit>Fhit-Fd_n6%F[v7#-Few6#;Fap-F_]l6$FapFd
tFgit>6$FajtFiht6$&FdtF_jt&Fiht6$Fj[lFhit>6$FfjtFejt-Fb`m6%Ff`x-F^[y6-FihtFajtF
ciqFcsF[tFdvFiqFjqF[rFcuFgit-Fe`r6*FihtFajtFciqFcsFeyFd[lF[tFdv@$/-F\^t6$FghtF_
htF*-F`v6$Q0%d%%~completed|+F;,$*&FghtFapF_htFinF^q@$5/FfjtF*2,&F[rFapFc[oFap&&
FfjtF_^nFder\@$2FdjyF[r>F[rFdjy>6'FiqFd[rFdtF\iqFh_y6'&FejyFbtFihtFajtFciq7&&Ff
jtF;FhuFdvFiw@$F^fnC$>F\]u,*FghtFapFfetFin-FftFh[wFapFapFapB6%Fh_yF\]uQ1templat
es/bak_tdF;@%Fbdy-Ffau6)Fh_yFapFgfqFeyFd[lFejtF*-F`v6'Fddu&Fh_yFbt-Ffdu6#&Fh_yF
_^n-Ffdu6#&Fh_yF\]pFejt-F`v6%FgixFhixFfarF;6#Fh_yF;6#Fen6G7'FhnFinFgpFi^lFjn7'F
hnFinF^qF_[lFbqFgeoF]ewF^auFd`l7'FhnFinFjpFhdsF[_l7'FhnFinFjpF_[lF[_l7'FhnFinFj
pF`[lF[_l7'FhnFinFjpF[^mF[_lFf`lF[hn7'FhnFinFb[lFchuFgp7'FhnFinFjalFc]pFgpF\en7
'FhnFinFdqFi_lF[_l7'FhnFinFdqFbcmF[_l7'FhnFinFdqFaqF[_l7'FhnFinFdqFc`lF[_l7'Fhn
FinFdqFdanF[_l7'FhnFinFdqF^]mF[_l7'FhnFinFdqF]`lF[_l7'FhnFinFdq"$X"F[_l7'FhnFin
FdqFg\qFa_l7'FhnFinFh]lFa`oFgp7'FhnFinFdqFa`oFa_l7'FhnFinF^emF*F^cp7'FhnFinFdqF
eamFa_l7'FhnFinF^bnF[oF[_l7'FhnFinFdqFa]oF[_l7'FhnFinFdqF_`oFa_l7'FhnFinFh]lFe_
lF[_l7'FhnFinFfq"#%)Fe`lFjbp7'FhnFinFh_mF_anFgp7'FhnFinFh]mF_`oFgpF][yF;,
I+alterCommaw,6#'F^_xFCF;6$FUFVF;-Fbal6%Q"[F;&-&F_^m6#%+InterleaveG6$FY7#-Few6$
Q",F;,&Fj_nFapFinFapF;Q"]F;F;F;F;6#Fap6$7'FhnFinF`q"##)Fjn7'FhnFinF`qF^glFjnF;,
I*printLinew,6#'%%lineGF'F;6$FUFVF;-F`v6$Q.%-60swritten|+F;FYF;F;F;6#Fap6$Fa`u7
'FhnFinFh]mFh]lFjnF;,
I,commonCode1w,6('F^fuF^am'%#fbGF'Fh]qF\bmFc]rFg]q6*%#MtG%#iMG%#eMGF`\l%#M0G%$M
0tG%$iM0G%$eM0G6"F;C&>F>-F_^q6$&Fc[o6$;,&F]boFapFapFapF;Fj[lFJ>Ffdp6$7#-Fe^m6$F
>%+indexorderG7#-%(entriesG6%F>FhbzFf^m-F`gu6$FY-Fbal6.FXQ,M~=~sparse(F;-Ffdu6#
-Fgo6$w,Fd[tF;6$FUFVF;FedmF;F;F;6#Fap6$7'FhnFinFdanF[fwFjn7'FhnFinFdanFeamFjnFi
qFh_z-Ffdu6#-Fgo6$w,Fd[tF;6$FUFVF;FfdmF;F;F;6#Fap6$7'FhnFinFaesFd_lFjn7'FhnFinF
aesFhanFjnFiqQ$,C(F;-FfduFbcnQ#),F;&Fi[oFbtFh_z,&&Fi[oFdxFapF]boFapQ$);|+F;@$0F
]boF*C(>F[rw,FifpF;6$FUFVF;-Fb`m6%0FYF*-FjjlF^pF*F;F;6$Fh]qFhp6#Fap6$7'FhnFinFh
]mF]`lFjnFb`u>Fcs-F\y6$-Fgjv6#-Fgo6$w,FifpF;6$FUFVF;-F]pF^pF;F;6$F`\lF[r6#Fap6$
7'FhnFinF[oFfqFjn7'FhnFinF[oF^emFjn&Fc[o6$;FapF]boF\gz-Fgo6$w,FifpF;6$FUFVF;Fdf
zF;F;Fefz6#Fap6$7'FhnFinFc`l"#!)Fjn7'FhnFinFc`lFaqFjn&Fc[o6$F\gzFabz>F[t-F_^q6$
FcsFJ>Fbio6$7#-Fe^m6$F[tFhbz7#-F[cz6%F[tFhbzFf^m-F`gu6$FY-Fbal6/FdcuFXQ-M0~=~sp
arse(F;-Ffdu6#-Fgo6$w,Fd[tF;6$FUFVF;FedmF;F;F;6#Fap6$7'FhnFinFc[mF`[lFjn7'FhnFi
nFc[mFfflFjnFdtFh_z-Ffdu6#-Fgo6$w,Fd[tF;6$FUFVF;FfdmF;F;F;6#Fap6$7'FhnFinF\foFd
dsFjn7'FhnFinF\foFeaxFjnFdtFh_z-FfduFd[nFh_zF]boFh_zF[ezF\ez-F`gu6$FY-Fbal6(FXQ
)M~=~M(:,F;FbbzQ-:end)-M(:,1:F;F]boQE)*M0;~%%~Schur~complement~reduction|+F;F;F
;F;6#Fi^l6-Fg^lF\anFb`l7'FhnFinFjp"$i"FgpF[hnFg]z7'FhnFinFdqFf^pF[_l7'FhnFinFdq
FbqF[_l7'FhnFinFdqF^`zF[_l7'FhnFinFdq"$m"Fgp7'FhnFinFdqF`_lFgpF;,
I,commonCode2w,6'F_azF`azF2Fdas%$iiqG6$%%iiq1G%%iiq2G6"F;C*>Fibn-Fjar6$w,Fd[tF;
6$FUFVF;/Fc_mFapF;F;6$Fa[[lFi[o6#Fap6$7'FhnFinF^bnFgamFjnFb[u7#-Few6#;FapFc[o@&
32F*Fifm2FifmFc[o@%/FifmFap-F`gu6$FY-Fbal6*FXQ#S(F;F]\qQ),:)~=~V(F;,*FhpFapFc[o
FinFinFapF]\qFapQ(,:)./V(F;FhpQ&,:);|+F;-F`gu6$FY-Fbal6,FXF_][l-FfduFjfmF`][l-F
fdu6#-F\jq6%,(FhpFapFc[oFinFinFapFbwF>Q/,:)./repmat(V(F;FhpQ%,:),F;FifmQ&,1);|+
F;/FifmFc[o-F`gu6$FY-Fbal6,FXQ'S~=~V(F;,&FhpFapFc[oFinQ":F;,&FhpFapFinFapF^^[lF
hpF_^[lFc[oF`^[l@&32F*Fg[o2Fg[oFc[o@%/Fg[oFap-F`gu6$FY-Fbal6*FXF_][l&FiqFbtF`][
lFhpFb][l,*FhpFapFc[oFinFinFapFd_[lFapFc][l-F`gu6$FY-Fbal6,FXF_][lF^euQ0,:)~=~r
epmat(V(F;FhpF_^[lFg[oQ(,1)./V(F;-Ffdu6#-F\jq6%F]^[lFbwFiqFc][l/Fg[oFc[o-F`gu6$
FY-Fbal6,FXQ.S~=~repmat(V(F;FhpF_^[lFc[oF[`[lFg^[lFh^[lFi^[lFc][l-F`gu6$FYFdcu-
F`gu6$FY-Fbal6$FXQFI~=~|irany(isnan(S))~&~|irany(isinf(S));|+F;-F`gu6$FY-Fbal6$
FXQ_o%%I~=~I~&~|irany(imag(S));~%%~uncomment~this~line~for~real~roots~only|+F;-
F`gu6$FY-Fbal6$FXQ.S~=~S(:,I);|+|+F;-F`gu6$FYQ$endF;F;F;F;6#F\]o63Fg^lF`^vF[hnF
jbp7'FhnFinF]qFierFgp7'FhnFinF]q"$Z"Fgp7'FhnFinFdqFierFgpF[hnFjbpF\b[lF]b[lF_b[
lFaau7'FhnFinFjpFc[mFgp7'FhnFinFjpFcewFgpFbax7'FhnFinFjpFgpFgpF;,
I,writeSolverw,6,F%'%$dirGF''Fh]qFiy'FdasFfemF[jr'Fc]rFgfw'F\at-FC6#F`jr'FbatF]
jr'Fg]qF`jr'Fa[[lFC6(%%mxn0GFgcpFb[yF2F^fuFaaz6"F;C:>F>7#-F_]l6$FapFhp>Fiq,&&F^
_oFbtFapFadxFin>Fjq&F^_oFdx>F[r&F^_oF_^n>F[tQ%~~~~F;>Fcs-F\gu6$-Fbal6*FXQ&/red_
F;&F]boFbtQ"xF;&F]boFdxQ"_F;FYFifsF^gu-F`gu6$Fcs-Fbal6'QH%%~Input:~coefficient~
matrix~C~of~size~F;F]\qFid[l&F>FdxFdcu-F`gu6$Fcs-Fbal6'QF%%~Output:~solution~ma
trix~S~of~size~F;Fc[oFid[lF[rQ#|+|+F;-F`gu6$Fcs-Fbal6)Q2function~S~=~red_F;Fhd[
lFid[lFjd[lF[e[lFYQ&(C)|+|+F;-F\az6(FcsF[tFhpFi[oF]boFadx-F`gu6$Fcs-Fbal6'FdcuF
[tQ4[L,|ir,P]~=~lu(M(:,1:F;FiqQ%));|+F;-F`gu6$Fcs-Fbal6$F[tQ)P~=~P';|+F;-F`gu6$
Fcs-Fbal6(F[tQ.M~=~[P*L~P(:,F;,&FiqFapFapFapQ,:end)]\M(:,F;F`g[lQ(:end);|+F;-F`
gu6$Fcs-Fbal6&F[tQ+M~=~M(end-F;,&FjqFapFinFapQ+:end,:);|+|+F;-F`gu6$Fcs-Fbal6&F
[tQ,T0~=~zeros(F;F[rF\ez-F`gu6$Fcs-Fbal6(F[tQ$T0(F;-Ffdu6#&F^`rFbtQ,,:)~=~-M(:,
F;F`_sFbg[l-F`gu6$Fcs-Fbal6&F[tFch[l-Ffdu6#&F^`rFdxQ()~=~1;|+F;-F`gu6$Fcs-Fbal6
&F[tQ,T1~=~zeros(F;F[rF\ez-F`gu6$Fcs-Fbal6*F[tQ$T1(F;Fdh[lFh_zFdh[lQ+)~=~M(:,1:
F;FjqF\ez-F`gu6$Fcs-Fbal6&F[tFii[l-Ffdu6#&F^`rF_^nQ))~=~1;|+|+F;-F`gu6$Fcs-Fbal
6$F[tQ5[V,|ir]~=~eig(T0,T1);|+F;-F^[[l6'FcsF[tF[rFc[oFbdx-F^huF]io-F``z6#-Fbal6
)Q%red_F;Fhd[lFid[lFjd[lF[e[lFYFifsF;F;F;6#F^q6;Fg^l7'FhnFinFedlFh_mFbq7'FhnFin
FbcmF[_lF[_l7'FhnFinFa_lFa`lF[_l7'FhnFinF[fwF\[nF[_l7'FhnFinFa]oFhanF[_l7'FhnFi
nFjpFi]mF[_l7'FhnFinFjpFhanFgp7'FhnFinFjpFh`lFgp7'FhnFinFjpF^`zFgp7'FhnFinFjpFc
cmFgpF`b[lF[\\l7'FhnFinFjpFi\qFgp7'FhnFinFjpF]_lFgpF`cpFi[\lF_axF`cp7'FhnFinFjp
FhdsFgp7'FhnFinFjpFaclFgp7'FhnFinFjpFe`lFgpF[\\lFhhuF_\\lF;,
I2writeSolverColpivw,6-F%Ffb[lFhb[lFib[lF[jrFjb[lF[c[l'FbatFCF2F_c[lF`c[l6(Fbc[
lFgcpFb[y%#nPGF^fuFaaz6"F;C;>F>Ffc[l>Fiq,&F[d[lFapFbdxFin>FjqF]d[l>F[r&F^_oFder
>F[tFad[l>Fcs-F\gu6$-Fbal6+FXQ"/F;F_[\lFhd[lFid[lFjd[lQ)_colpiv_F;FYFifsF^guF\e
[l-F`gu6$Fcs-Fbal6'Ffe[lFc[oFid[lFadxFge[l-F`gu6$Fcs-Fbal6)F\f[lFhd[lFid[lFjd[l
Ff]\lFYF]f[l-F\az6(FcsF[tFhpFi[oF]boFbdx@%0FiqF*C&F`f[lFff[lF[g[l-F`gu6$Fcs-Fba
l6&F[tQ,M~=~full(M(F;F`g[lQ+:end,:));|+F;-F`gu6$Fcs-Fbal6%FdcuF[tQ.M~=~full(M);
|+F;@$0FjqF*C%-F`gu6$Fcs-Fbal6'FdcuF[tQ4[L,U,P]~=~lu(M(:,1:F;FjqFef[lFff[l-F`gu
6$Fcs-Fbal6(F[tF_g[lF`_sFag[lF`_sFbg[l-F`gu6$Fcs-Fbal6&F[tQ*M1~=~M(1:F;FjqFc][l
-F`gu6$Fcs-Fbal6&F[tQ(M2~=~M(F;F`_sFig[l-F`gu6$Fcs-Fbal6&F[tQ9[Q,R,P]~=~qr(M2(:
,1:end-F;,&Fc[oFapFapFapFef[l-F`gu6$Fcs-Fbal6(F[tQ3A~=~U\[M1(:,1:end-F;Fj`\lQ.)
*P~M1(:,end-F;Fc[oQ):end)];|+F;-F`gu6$Fcs-Fbal6*F[tQ+B~=~R(:,1:F;,(Fhd[lFapFiqF
inFjqFinQ()\[R(:,F;,*Fhd[lFapFiqFinFjqFinFapFapQ3:end)~Q'*M2(:,end-F;Fc[oFaa\l-
F`gu6$Fcs-Fbal6(F[tQ/M~=~[-A(:,end-F;,&FadxFapFinFapQ1:end)+A(:,1:end-F;FadxQ,)
*B;~-B];|+|+F;-F`gu6$Fcs-Fbal6.F[tQ'P1~=~[F;,&F[rFapFapFapFh^[l,&F[rFapFjqFapQ%
~(1:F;,(F[rFapFc[oFinFinFapQ%)*P~F;,&F[rFapFc[oFinFh^[lF[rQ$];|+F;-F`gu6$Fcs-Fb
al6&F[tQ&P2~=~F;-Ffdu6#F^`rQ#;|+F;-F`gu6$Fcs-Fbal6)F[tQ5T~=~getT(M,P1(1:end-F;F
adxQ*),P1(end-F;F`b\lQ&:end)F;Q(,P2);|+|+F;-F`gu6$Fcs-Fbal6$F[tQ1[V,|ir]~=~eig(
T);|+F;-F^[[l6'FcsF[tFadxFc[oFc\yFjj[l-F``z6#-Fbal6)F_[\lFhd[lFid[lFjd[lFf]\lFY
FifsF;F;F;6#F]q6DFi\zFb[\lFc[\lFd[\lFe[\lFf[\l7'FhnFinFjpFaesF[_lFh[\lFi[\l7'Fh
nFinFjpFd^nFgpF[\\lF[hn7'FhnFinFdqF_anFgp7'FhnFinFdqFbenFgp7'FhnFinFdqF`glFgp7'
FhnFinFdqFaclFgp7'FhnFinFdqFe_lFgpF[hnF^e\lF_e\lF`e\lF][y7'FhnFinFjpFeamFgp7'Fh
nFinFjpF_`lFgp7'FhnFinFjpF`cmFgp7'FhnFinFjpFjdsFgpF]e\l7'FhnFinFjp"#**Fgp7'FhnF
inFjpF^cpFgp7'FhnFinFjpFj`lFgp7'FhnFinFjpF[_lFgpF[\\lFhhuFaaxF;,
I2writeInidataCoefsw,6$F%Ffb[l6.F[fs%#_CG%&_nameG%&_sizeG%#AsG%#CsG%#ClGF^fuFj
\l%"eG%$idxGFaaz6"F;C:>FiwFad[lAFdfsAFffs>F>F[gs@$4FbgsC$-F`v6#QUCoefficient~fi
le~cannot~be~created~for~this~problem|+F;OF*>Fhq&-F>F;Far@$4-FeiuFc^o-&Ffiu6#%.
MakeDirectoryGFc^o>Fit-F\gu6$-Fbal6&FXQ./inidata_num_F;FYFifsF^gu-F`gu6$Fit-Fba
l6%Q=function~data~=~inidata_num_F;FYQ$()|+F;-F`gu6$Fit-Fbal6&FiwQ0data~=~cell(
[1,F;FhcnQ%]);|+F;?(FcuFapFapFhcnFbgm@%/&F[rF\cvFa]l-F`gu6$Fit-Fbal6&FiwQ&data|
frF;FcuQ,|hr~=~randn;|+F;-F`gu6$Fit-Fbal6(FiwFii\lFcuQ+|hr~=~randn(F;&-Ffdu6#Fd
i\lFfguF\ez-F`gu6$FitFia[l-F^huFd[n-F``z6#-Fbal6%Q-inidata_num_F;FYFifs>Fit-F\g
u6$-Fbal6&FXQ(/coefs_F;FYFifsF^gu-F`gu6$Fit-Fbal6%Q4function~C~=~coefs_F;FYQ)(d
ata)|+|+F;?(FcuFapFapF]`rFbgm-F`gu6$Fit-Fbal6'Fiw&FjqF\cvQ)~=~data|frF;FcuQ$|hr
;|+F;-F`gu6$FitFdcu?(FcuFapFapFg[oFbgmC&@$/FcuFenC$>Fcs-F_^q6$&-Fdfq6%F_]lF*-F
\\l6%F[s-F_^q6$&FiqFdxFa^q%)functionGFbtF'-F`gu6$Fit-Fbal6*FdcuFiwFcsQ*~=~C(:,1
:F;-F_]l6$Fa]lFd_[lQ')\C(:,F;,&Fg]]lFapFapFapQ):end);|+|+F;-F`gu6$Fit-Fbal6(Fiw
Q+C~=~zeros(F;-F_]l6$Fa]l&FiqF\cvFh_z-F_]l6$F_^lFc^]lQ%);|+|+F;>6$F[tFdt6$-F]hl
6$-F_^q6$Fc^]lFa^q<#F*-F_^q6$Fc^]lFC?&FhuF[tFbgmC$>Fdv7#-F_hs6$FhuFdt-F`gu6$Fit
-Fbal6(FiwQ#C(F;-Fb`m6%/FcawFapFc]v-FfduFcxQ%)~=~F;-F_^q6$FhuF'Ffc\l-F`gu6$Fit-
Fbal6%FdcuFiwQVC~=~C./repmat(sqrt(sum(C.*conj(C),2)),1,size(C,2));|+|+F;Fcj\lFe
j\l-F``z6#-Fbal6%Q'coefs_F;FYFifsAF]_tF;F;F;6#Fen6JFi\z7'FhnFinF_`lFi]mF[_lFd_t
Fe_tFi`s7'FhnFinFjpFajxFa_l7'FhnFinF]oFieoFgp7'FhnFin"$2"Fc]pFfqF\]rFi]v7'FhnFi
nFc_lFfflFgp7'FhnFinFjpF[fwF[_lF`b[l7'FhnFinFjpFiilFgpF\enFjbp7'FhnFinF^bnFi]mF
gp7'FhnFinFh]mFd_lFgpFbb[lFhhu7'FhnFinFjpF^]mFgpFh^p7'FhnFinFjpF]jlFgpF\en7'Fhn
FinFdqF[fwFgpFaauF\enFjbp7'FhnFinF]qF_`oF[_l7'FhnFinF]qFj^pFgp7'FhnFinFdq"#"*Fg
pF_\rFfjx7'FhnFinF]qF[oF[_l7'FhnFinF]qFc]pFgp7'FhnFinFjpFfdsFgpFbb[lFhhu7'FhnFi
nFjpFc_lFgpFe`tF;,
I-writeTestNumw,6)F%Ffb[l'%"UGF_yFdemFjb[l'F_]qFfem'Fiev%(booleanG6%F^fuFaaz%$f
b2G6"F;C<>FiqFad[l>Fjq-Fbal6$FiqFiq@$Fig\lF[h\l>F>-F\gu6$-Fbal6&FXQ+/test_num_F
;FYFifsF^gu-F`gu6$F>Q*rng(23);|+F;-F`gu6$F>Q,N~=~10000;|+F;-F`gu6$F>-Fbal6%Q%d~
=~F;F]boQ$;|+|+F;-F`gu6$F>-Fbal6%Q;stats~=~struct('problem','F;FYQL','tm',[],'e
rr',[],'k',[],'kr',[],'N',N);|+|+F;-F`gu6$F>Q.for~i~=~1:N|+|+F;-F`gu6$F>-Fbal6&
FiqQ4data~=~inidata_num_F;FYQ?();~%%~generate~initial~data|+|+F;-F`gu6$F>-Fbal6
$FiqQ%try|+F;-F`gu6$F>-Fbal6&FjqQ+C~=~coefs_F;FYQV(data);~%%~compute~coefficien
ts~of~polynomial~system|+F;-F`gu6$F>-Fbal6$FjqQ&tic;|+F;-F`gu6$F>-Fbal6*FjqQ)S~
=~red_F;FidzFid[lF[ez-Fb`m6%F^_oFf]\lF[e[lFYQA(C);~%%~solve~polynomial~system|+
F;-F`gu6$F>-Fbal6$FjqQ<stats.tm~=~[stats.tm~toc];|+F;-F`gu6$F>-Fbal6$FjqQ>if~is
empty(S);~continue;~end|+F;-F`gu6$F>-Fbal6(FiqQ*catch~ME|+F;FjqQ+continue;|+F;F
iqQ&end|+|+F;-F`gu6$F>-Fbal6(FiqQ)mon~=~@(F;&-Ffdu6#Fc[oFfguQ#)~F;-Ffdu6#-F_^q6
$FhpFCFfc\l-F`gu6$F>-Fbal6$FiqQfn[err,k,kr]~=~numerr(C,mon,S,d);~%%~compute~num
erical~error|+F;-F`gu6$F>-Fbal6$FiqQ>stats.err~=~[stats.err~err];|+F;-F`gu6$F>-
Fbal6$FiqQ8stats.k~=~[stats.k~k];|+F;-F`gu6$F>-Fbal6$FiqQ<stats.kr~=~[stats.kr~
kr];|+|+F;-F`gu6$F>F_h]l-F`gu6$F>Q5disp_stats(stats,1);F;-F^huFjfm-F``z6#-Fbal6
%Q*test_num_F;FYFifsF;F;F;6#Fdq6>Fi`n7'FhnFinF`qFf]lF[_l7'FhnFinFh]lF^]mF[_lFi]
vFea]lFfax7'FhnFinFjpFh]lFgp7'FhnFinFjpFbcmFgpFbax7'FhnFinFjpF`_lFgp7'FhnFinFjp
F[`lFgpFcb]l7'FhnFinFjpFbqFgp7'FhnFinFjpFierFgp7'FhnFinFjpF]`lFgp7'FhnFinFjp"$E
"FgpFce\l7'FhnFinFjpF[boFgp7'FhnFinFjpF\[nFgpFdax7'FhnFinFjpF[jlFgpFcaxF`cpFce
\l7'FhnFinFjpFepFgp7'FhnFinFjpF_bnFgpFhhuFbaxF;,
I,iniTemplatew,F[iu6>F-F.F/Fc]rF_]qFfcpF\atF7FhcmFifrFEF]iuFbatFbasF^atF^iuFa[[
lFhemFh]q%#U1GFib]lF]bmFgcpFb[yF2Fg]qFj\l%$xEsG6"F;C.>6%F>FiqFjqF\r>6/F[rFcsF[t
FdtFitFcuFhuFdvFiwFeyFd[lFgfqF\iq&F^fv6#7#-Few6#;FapF`q>Fciq-Fefn6%-Fgo6$w,Fd[t
F;6$FUFVF;-Fb`m6%-F[vFffyFinFapF;F;6$FbasFd[l6#Fap6$7'FhnFinFh^lFbenFjn7'FhnFin
Fh^lFi_lFjn7#-Few6#;FapFg[oFbwFgfq>6$FfetF_ht-Fe[mFibn>Fght-F^jl6$F_htFjq>Ffet-
Fiam6%FfetF_htFght>F_ht-F_ap6$-F]w6%&FiqFb^xFbw-Fgx6%FapFbwF`_^lFght>Fhht&Fit6#
-Fd_n6%F[v7#-Few6#;Fap-F_]l6$FapFitFhu>6&FihtFgitFhitFajt6$F]bq&FiwFdx>Fey7$&Fe
yF;-Fgo6$w,6#FejrF;6$FUFVF;,&*&F^\sFapF]pFapFapFYFapF;F;6$F2Fhit6#Fap6$7'FhnFin
FgpF]]mFjn7'FhnFinFgpFb[lFjn-Fd_n6%F[v7#-Few6#;FapFhit&FeyFbt>Fejt7$-F^dl6$-F_^
q6$F\iqFa^q-Fgo6$w,F_\lF;6$FUFVF;F\pF;F;6$F]bmFhht6#Fap6$7'FhnFinFbenF[oFjn7'Fh
nFinFbenFgamFjnFdv-F_^q6$&Fit6#;FapFajtFa^qO62FiqFjqF[tFfetFghtF_htFit7%,&FihtF
ap-Fft6#FhuFinFgitFhitFeyFcuFhuF[rFcsFiwFejtFciqF;F;F;6#Fap6/Fg^lF\_lFe^pF^auFf
_lF^_lFf_lF_foF]frFf`l7'FhnFinFjpF`enF[_lFb`l7'FhnFinFjpFda]lFfqF;,
I*iniColpivw,6'F7FfcpF.F/'Fb\^l-FC6#Fa^q6+F_atFa]qF4FecpFb]qFc]q%"PG%"RG%"EG6"F
;C+>F>-F_^q6$&FY6#;,&Fj\oFinFinFapF;FC>Fiq-F]hl6$-F_^q6$FYFa^q-F^dl6#&Fi[oF;>F[
r-Fdep6#-Fcbm6$-F\\l6$w,FgelF;6$FUFVF;Fh_qF;F;6&F4FjqFa]qFiq6#Fap6$7'FhnFinF[`l
Fe`lFjn7'FhnFinF[`lFccmFjnFiq-F[vFeep>Fcs-F]hl6$-F^dl6#-Fcbm6$-Fefn6%FjqFbwF[rF
_f^lF[r>F[t-F]hl6$Fiq-F^dlFat>Fdt7$&-F^jl6$7#&-F]hl6$F[r<#F`dlF;Fc[oF;F`dl>FitF
cbq>Fcu7%&F[ezF;&-F]hlF_e^lF;F^bqO6$7%FcuFitFdt7%-FftF\cvFc[nFj^qF;F;F;6#F\]o6,
FbdsFfamF_foF^auFb`rF^^vF]^vFehuFfaxF`fwF;,
I0solverGeneratorw,6)F%>%'colpivGFap>%0createCoefsFileGF*>%1createSolverFileGFa
p>%/createTestFileGF*>'%(rootDirGF'Q+../solversF;>%'showPMGFap6@Fgb[lF.F/FfcpFh
]qFib]lFa\^lF7F\atFbatFhcmFifrFc]rF_]qF]iuFb\^lFa[[lFg]qFijr%#VrGF]bm%%ptn1GFie
v%#iCG%#jCGFd[yF-F\bm%$iT1GFgbl6"F;C9@$4-Feiu6#F]bo-F\h\lF`j^l>F>-Fbal6%F]boFe]
\lFY@$Fciu-F\h\lFjfm@$F^fn-F\f\lFehl@$3Ff`x/Fc[oF*OF;>62FiqFjqF[rFcsF[tFdtFitFc
uFhuFdvFiwFeyFd[lFgfqF\iqFciq-F^\^lF^p>6$Fd[rFfet-F_]l6$FdgvFgfq>F_ht&Fit6#-Fd_
n6%F[vFh_^lFiw>6$FghtFhht-Ffc^l6'F_htF[rFiqFjqF\iq@$F^cu-F`v6%Q@|+%a~permissibl
e~monomials:|+%a|+|+F;Fibw&FghtFder>Fiht-Fb]x6#32&FcuFderFibwF^v@$Fh\t-Feb]l6)F
YF>F[tFiqFeyFd[lFiht@$F[[_lOF;@$-Fb]t6$F*FciqYQWSolver~file~cannot~be~created~f
or~incomplete~templatesF;>Fgit7#-Fe^m6$FigzFhbz>Fhit-Fgo6$w,FifpF;6$FUFVF;,&Fed
mFap*&,&FfdmFapFinFapFapF^]lFapFapF;F;6$Fh]qFcs6#Fap6$7'FhnFinF`qFgamFjnFg\sFgi
t>Fajt-Fiy6$-F_]l6$FapFcs<#&-FN6%w,FfjlF;6$FUFVF;/Fe`pFXF;F;F;6#Fen6$7'FhnFinFb
qF[_lFjn7'FhnFinFbqF_bnFjnFgitFhitF;>Ffjt-F_^q6$-F\y6$FajtFdtFC>Fejt-Fiam6$-Fe[
m6$-Fecm6$FfjtFdvFiqFit@$0Fd[rF*>Fejt&Fejt6$FfetFj[l>Fejt&Fejt6$Fj[l-Fd_n6%F[v7
#-Few6#;Fap-F_]l6$F_^lFejtFiw@$FihtC%>F\]u-Fgo6$w,FgelF;6$FUFVF;-Ffbm6$F[[q7$&&
FhzFderF;&&FhzFdxF;F;F;6&FfcpF[rF]bmFght6#Fap6$7'FhnFinFdpFg\qFjnFgflFa\_l>Fght
-Fh]s6#-Fgo6$F_]lFght>Fejt-Fiam6%FejtF_htFght@$Fijs@%Fiht-Fa\\l6-FYF>FcsFg[oFej
tFeyFhhtF\]uFg\_lFd[rFciq-Fcb[l6,FYF>FcsFg[oFejtFeyFcuFhuFd[rFciqF;F;F;6#Fap6IF
d\q7'FhnFinFjpF`glFa_l7'FhnFinF]oFc`lFgpFj_lFi]vFea]lF^`l7'FhnFinFbcmFa`lFgpF^`
l7'FhnFinFf^nF*FfqF[]zF[auF]frFb`r7'FhnFinFjpF`b]lFa_l7'FhnFinFgpF^`zFgpF_foF`c
_l7'FhnFinFeqFc`lFgpF^fr7'FhnFinF^bnF*Ffq7'FhnFinFjpFd_lFa_l7'FhnFinF^glF`cmFe_
lFb`rF]frFdamF_^vFdam7'FhnFinFjpFc_lFa_l7'FhnFinFi_lFbcmF[_lF_jnF[hnF`^zF[evFb
\rF[hnFjbp7'FhnFinFdpFf^pFgp7'FhnFinFh]mF\\rFgpF;
