M7R0
I$rnd,$f*6"F%6"F%,&-f*F%F%6#/%(builtinG%4RandNumberInterfaceGF%F%F%F%F%6%""'"&,
+""#9""""&++"F2F%F%6$%6_thismoduledefinitionGF%#F2F3F%,
I(gsolverw,6&%%probG>%(nDigitsG"#I>%'showAMG""!>%'showAPGF@6.%"FG%%varsG%%tordG
%"GG%"BG%$degG%#avG%#vrG%"TG%"VG%"SG%#SrG6"F%C3-%*interfaceG6#/%+rtablesizeG""$
>%'DigitsG9%>6%8$8%8&&-%,readProblemG6)9$F@7"F_oF@F2F_o6#7%F2FW""%>Fgn-%$mapG6$
%&numerGFgn@$4-%%typeG6$Fgn-%%listG6#%(polynomGYQQthe~case~of~non-polynomial~sy
stem~is~not~handledF%>8'-&%)GroebnerG6#%&BasisG6$FgnFin>8(&-&Fgp6#%*NormalSetG6
$FdpFin6#F2>8)-%)numelemsG6#F\q>8*-%$addG6$*&8+F2-F"F%F2-%#inG6$F_rFhn@$/9'F2-%
'printfG6$Q7Action~polynomial:~%a|+F%Fjq>8,-&Fgp6#%5MultiplicationMatrixG6'FjqF
\q-%&tableG6#-&%"|irG6#%"=G6%F\q%#~$G7#-%"$G6#;F2FeqFdpFin@$/9&F2C$-Fhr6#Q.Acti
on~matix:F%-%&printG6#-%&evalfG6#F\s>8-&-&%.LinearAlgebraG6#%-EigenvectorsGFjt6
#""#>F_u-&Fgs6#%"/G6%F_uF[t-%".G6$-%'VectorG6$Feq/%%fillGF2&F_uFcq>8.-F_v6$&-%,
poly2matrixG6&-Feo6$w,6#FKF%6$%)operatorG%&arrowGF%-&Fgp6#%+NormalFormG6%F^oT#T
%F%F%6&FGFdpFFFin6#F26$7'Q!F%!"""#C"#g"#O7'FaxFbxFcx"#FFexFhnFhnF@F\qFcqF_u>8/-
%#ReG6#&Fhv6$;F%F%-%'selectG6$w,6#%"cGF%6$FdwFewF%-%'andseqG6$-%#isG6$&F[x6$%"i
GF^o%%realG/F_z;F2-%#opG6$7$F2F2F[xF%F%6$FNFhv6#F26$7'FaxFbx"#D"#qFex7'FaxFbxF[
[lFgxFex7#-F^t6#;F2-Fdz6$7$F2FguFhvO6%FhvFix-%.backwardErrorG6&FgnFhnFhvFeqF%F%
F%6#F2687'FaxFbx"#5F/Fex7'FaxFbxFWF[[l"#?7'FaxFbxFWF_\l"#V7'FaxFbxFW"#mFa\lF`\l
7'FaxFbxFW"$.""#X7'FaxFbx"#Q"#%*"#]7'FaxFbxFW"#JFa\l7'FaxFbxFWFh\lFa\lF`\l7'Fax
FbxFW"#LFa\l7'FaxFbxFW"#lFf\l7'FaxFbxF_\l"#cF_\l7'FaxFbxFW"#uFa\l7'FaxFbxFW"#oF
f\l7'FaxFbxF_\l"#UF_\l7'FaxFbxFf\l"#fF_\l7'FaxFbxFW"#ZFa\l7'FaxFbxFWFexFa\l7'Fa
xFbxFW"#')Fa\l7'FaxFbxFW"#$*Fa\l7'FaxFbxFW"#Y"#_F%,
I&dlinew,6#%"nGF%6$FdwFewF%-%$catG6#-F^t6$Q"-F%F^oF%F%F%6#F26$7'FaxFbx"")"#@Fex
7'FaxFbxFd_lF]\lFexF%,
I%suppw,6$%"fGFEF%6"F%C$-%'coeffsG6%-%'expandG6#F^oFZ.%#mnGO<#Fd`lF%F%F%6#Fgu6%
7'FaxFbx""("#sFex7'FaxFbxFe_l"#\F_\l7'FaxFbxFe^l"#iFe^lF%,
I%Suppw,6$FDFE6#FN6"F%C$>Fgn-Feo6%Fg_lF^oFZO6$Fgn-%&unionG6#&FgnF%F%F%F%6#Fgu6%
7'FaxFbxFj`lF/Fex7'FaxFbx""*F\]lF\]l7'FaxFbxFWFcxFe^lF%,
I(degree1w,Fi_l6#%$vrsG6"F%C$>Fgn<#&FZF%O-%$maxG6#-Feo6$w,6#Fd`lF%6$FdwFewF%,&-
%'degreeG6$-FgoFb`lF[xF2-Ficl6$-%&denomGFb`lF[xF2F%F%6$FhblFgn6#F26$7'FaxFbx"#=
Fc\lFex7'FaxFbxFddlFe_lFex-Fg_l6$F^oFZF%F%F%6#Fgu6%F\\l7'FaxFbxFcbl"#BF\]l7'Fax
FbxFW"#$)Fe^lF%,
I+TestOrder1w,6%%"xG%"yGFF6%Fhbl%#dxG%#dyG6"F%C&>Fgn-%&minusG6$-%'indetsG6#Fct<
#Fct>Fhn-Febl6$F^oFgn>Fin-Febl6$FZFgnO52FhnFin3/FhnFin-&Fgp6#%*TestOrderG6%F^oF
ZFctF%F%F%6#FW6'7'FaxFbx"#8F/Fex7'FaxFbxFcbl"#SF\]l7'FaxFbxFa\l"#jFa\l7'FaxFbxF
c\lF`^lFa\l7'FaxFbxFW"#hFe^lF%,
I$srtw,6$FMFFF%6$FdwFewF%-%%sortG6$F^ow,6$FaelFbelF%6$FdwFewF%-F\gl6%FZF^oT$F%F
%6$FFFZ6#Fgu6$7'FaxFbxF[[lFgglFex7'FaxFbxF[[l"#KFexF%F%F%6#Fgu6$7'FaxFbxF/"#kFe
x7'FaxFbxF/"#;FexF%,
I,poly2matrixw,6&FDFE>%#ppGF@>%#B0GF_o6$FLFH6"F%C&>Fgn-Feo6$w,6#%#plGF%6$FdwFew
F%-Fcs6$%'sparseG-%$zipG6%w,6$%"aG%"bGF%6$FdwFewF%/FZF^oF%F%F%6#Fgu6$7'FaxFbx"#
M"#WFex7'FaxFbxFd[mFeglFex7#-F^`l6%F^oFghlFc`l7#Fd`lF%F%6$FEFZ6#F26$7'FaxFbx"#7
"#xFex7'FaxFbxF_\m"#:FexF^o>Fhn-%#ifG6%/-Fgq6#FfrF@-&%*ListToolsG6#%+MakeUnique
G6#-Feo6%%(indicesGFgn.%'nolistGFfr>Fgn-%'MatrixG6#-Feo6$w,6#%"tGF%6$FdwFewF%-F
eo6$w,6#F^[mF%6$FdwFewF%&FghlFb`lF%F%6$F]^mF^o6#F26$7'FaxFbx"#EF]ilFex7'FaxFbxF
i^m"#GFexF[xF%F%6$FHFhn6#F26$7'FaxFbx"#>FexFex7'FaxFbxF`_mFe_lFexFgnO6$-Fe\m6%5
/FctF@%)_complexGFgn-&&Fcu6#%(ModularG6#%$ModG6%FctFgn&%(integerG6#Fd_l-Fbv6#Fh
nF%F%F%6#Fbo6'7'FaxFbxF1F/Fex7'FaxFbxFW"#")Fa\lFi`m7'FaxFbxFW"#TFa\l7'FaxFbxFWF
b^lFe^lF%,
I/permuteColumnsw,6%%"MGFM%#V1GFecl6$FdwFewF%&F^o6$F_y7#-%$seqG6$-&F\]m6#%'Sear
chG6$FgnFZ-Fbr6$FgnFctF%F%F%6#FW6&7'FaxFbx"#<"#&)Fex7'FaxFbx"#H"#NFd_l7'FaxFbxF
dbmF[_mFexFfbmF%,
I%expFw,6$FD%"AGF%6$FdwFewF%-Feo6$w,6#%#sfGF%6$FdwFewF%-Fa`l6#*&&Fghl6#&F^oFcqF
2&F^oFfuF2F%F%6$FDF^o6#F26$7'FaxFbxF`_mFe[mFex7'FaxFbxF`_m"#AFexFZF%F%F%6#Fgu6$
7'FaxFbxFj`l"#[Fex7'FaxFbxFj`lF1FexF%,
I-iniReductionw,6%FDFE'Fhil%'posintG6+%#F1G%#F2G%$nF1G%"sG%#J1G%$FF2G%$JJ2G%"XG
%#s1G6"F%C(>Fgn-&Fgs6#FgoFb`l>FhnFgn>Fin-Fgq6#Fgn>Fdp,&-Fgq6#&-F`alF^bmFfuF2Fin
Fbx?(F%F2F2F%%%trueGC->F\q-&%1PolynomialIdealsG6#%0PolynomialIdealG6$Fgn/%/char
acteristicGFct>Feq-&Feo6#Fb]m6$w,6#%"jGF%6$FdwFewF%-%'subsopG6$/F^o%%NULLGF[xF%
F%6$F]emFgn6#F26$7'FaxFbxFgxF]^lFex7'FaxFbxFgxFgbmFexFgn>Fjq-Feo6$w,6#F^emF%6$F
dwFewF%-F[gm6$F^o/FagmFghlF%F%6$FhilFct6#F26$7'FaxFbxFddlF`\mFexFedlFeq>F_r-Fay
6$w,FhgmF%6$FdwFewF%-&F\gm6#%1IdealContainmentG6%F[x&F\xFb`lF[xF%F%6&FaemF\qFce
mFjq6#F26$7'FaxFbxF`_m"#rFexFa_m7#-F^t6#;F2Fin@$/-Fgq6#F_rF@[>F_r-Feo6$w,FhgmF%
6$FdwFewF%7%&F[xFb`l-Fgq6#&-F`al6$&F\x6#Fa[nT(Ffu-Febl6$&T)Fh[nFi[nF%F%6*FdemF_
rFbemFeqFEFZF]emFgn6#F26$7'FaxFbxFcilFebmFex7'FaxFbxFcilFddlFex7#-F^t6#;F2Fhjm>
F_r-&F\]m6#%3FindMinimalElementG6$F_rw,FchlF%6$FdwFewF%52F[dm&FZFfu3/F[dmFa]n2&
FZ6#FW&F^oFf]nF%F%F%6#Fgu6$7'FaxFbxFf\l"#*)Fex7'FaxFbxFf\l"#^Fex>Fgn&Feq6#&F_rF
cq>FinF^fm>F\sFafm@$2F\sFdpC$>FhnFgn>FdpF\sO-%'removeG6%Fbr7#-F^t6#;F2-FgqFb`l-
Feo6$w,FbjlF%6$FdwFewF%-F[bm6$F^o-Fjem6#FghlF%F%F\dm6#F26$7'FaxFbxFd^lFj`mFex7'
FaxFbxFd^lF]alFexFhnF%F%F%6#FW677'FaxFbxFb\mF/FexFjdl7'FaxFbxFi^mFd[mFa\l7'FaxF
bxFex"#aFa\l7'FaxFbxFW"#RFa\l7'FaxFbxFWFd_lFe[m7'FaxFbxFj`lFg]lFa\l7'FaxFbxFj`l
Fe^lFa\l7'FaxFbxFj`lF]elFa\lFi`n7'FaxFbxFj`lFi]lFf\l7'FaxFbxFgbmF@"#`7'FaxFbxFj
`l"$0"Fa\l7'FaxFbxFj`l"#!*Fa\l7'FaxFbxFj`lFe_lFa\l7'FaxFbxFj`lF[[lFa\l7'FaxFbxF
j`lFe[mFa\l7'FaxFbxFj`lFf\lFf\l7'FaxFbxF_\lF[_mFa\l7'FaxFbxF="#PFa\l7'FaxFbxFW"
#()Fe^lF%,
I/shiftExpansionw,Fbal6(%#SPG%#sFGFigmF]^mFd`lFL6"F%C&>FeqF_o>6$FgnFhn-F`alFgdl
?(FinF2F2Fa_nFgfmC%>Fdp-Fju6%FhnF[t&&Fgn6#FinFcq?&F\q&F[cn6#;FguF%0-Fgq6#FdpF2-
%+intersect=G6$Fdp-Fju6%FhnF[tF\q>Feq7$&FeqF%-Fham6$7$FinF\q-Fbr6$F\qFdpOFeqF%F
%F%6#Fgu6+7'FaxFbxFdbmF/Fex7'FaxFbxFgxF_]lFa\l7'FaxFbxFWF[[lFa\l7'FaxFbxFWFd_lF
d_l7'FaxFbxFj`lF[elFa\l7'FaxFbxFj`l"#yFd_l7'FaxFbxFe^lFajmF_\l7'FaxFbxFj`lFe`nF
a\l7'FaxFbxFW"#6Fe^lF%,
I-neighborMonsw,6%%#BsGFE%(sShiftsG6#%$vBsG6"F%C$@(Fbt>Fgn-Feo6%-%"@G6$Fdz&Fgs6
#%"*GF^oFZ/FctFbx>Fgn-Feo6%-F]fn6$FdzFjuF^oFZFg_m>Fgn-Feo6$Fdz-Feo6%-F]fn6$Fdz<
$F_fnFjuF^oFZO-Fjel6$FgnF^oF%F%F%6#FW6(F``n7'FaxFbxFWFcblFf\l7'FaxFbxFe_lF]alFa
\l7'FaxFbxFcxFe^lFa\l7'FaxFbxF[elFg]lFa\l7'FaxFbxFWFadmFe^lF%,
I)rprofilew,6%FaamFhil%&cmplxG6%%#tMG%#bsG%"rG6"F%C$@%FctC$>Fgn-%$modG6$-%*Gaus
sjordG6$F^o.%$rnkGFZ>Fhn7#-Fham6$-F[bm6$F2&Fgn6$FinF_y/Fin;F2F^in>Fhn-&F[`m6#%,
RankProfileG6$FZF^oOFhnF%F%F%6#FW6(7'FaxFbxF^enF/FexFegnF\en7'FaxFbxFj`lF[^lFa
\l7'FaxFbxFj`lFc`nFa\l7'FaxFbxFWF_\mFe^lF%,
I-rowReductionw,6$FaamFhil6$F`hn%&r2delG6"F%C%>Fgn-Fjgn6%)F^o%#%TGFZFh_m>Fhn-F[
_n6%Fbr7#-F^t6#;F2-Fdz6$FfzF^oFgnO6$&F^o6$FgnF_yFhnF%F%F%6#Fgu6&F``n7'FaxFbxFWF
hbmFa\lF\^l7'FaxFbxFWF[[lFe^lF%,
I.scoreFunctionw,6'Fccm%#nFGF^bnF]bn%#NAG6'FigmF]^mFd`l%#A1G%#nrG6"F%C&>FdpF_o?
(FgnF2F2FZFgfmC%>Fhn-Fju6%FctF[t&&FfrF_fmFcq?&Fin&Fd]oF_cn0-FgqFe`m&9(F_fm-Fecn
6$Fhn-Fju6%FctF[tFin>Fdp7$&FdpF%-Fham6$7$FgnFin-Fbr6$FinFhn>F\qFbcnO7&,&-FgqF^f
lF2F\qFbxF\qFdpF^oF%F%F%6#""&6+7'FaxFbxFcilF/Fex7'FaxFbxF`_mFi^mFa\lFgdnFhdn7'F
axFbxFj`l"##)Fd_l7'FaxFbxFc]l"#vF_\l7'FaxFbxFj`lF\amFa\lF`\l7'FaxFbxFWFh\lFe^lF
%,
I0manShiftCheckerw,6%Ff\oFE%*manShiftsG6$%$nShG%(mshiftsG6"F%C'>FgnF[_o@$/FgnF@
OFct@(4-Fhy6$-Fhy6$3-F[p6$-FgoFecl%)monomialG-F[p6$-F_dlFeclF^ao-Fbr6$Fd`l%#msG
-Fbr6$FdaoFctYQiomanShifts~must~be~either~an~empty~list~or~a~list~of~lists~of~L
aurent~monomialsF%4-%'subsetG6$F\flF\clYQHmanShifts~contains~extraneous~variabl
esF%/<#&FctF%<#F_oYQSat~least~one~sublist~in~manShifts~must~be~nonemptyF%@%0Fgn
F^oC$-%(WARNINGG6#Qhothe~number~of~sublists~in~manShifts~is~not~equal~to~the~nu
mber~of~polynomialsF%@&2FgnF^o>Fhn7$Fabo-F^t6$F_o,&F^oF2FgnFbx2F^oFgn>Fhn&Fct6#
;F2F^o>FhnFctOFhnF%F%F%6#FW617'FaxFbxFddlF/Fex7'FaxFbxFcblFd[mF\]l7'FaxFbxFWF\a
mFf\l7'FaxFbxFdbmF_]lFe^lFegn7'FaxFbxFj`lFb^lFj\l7'FaxFbxFj`lFc`nFj\l7'FaxFbxFj
`lFa]lFj\lFegn7'FaxFbxFj`lFi\lF_\l7'FaxFbxFj`lFcglFf\l7'FaxFbxF^enF]^lFa\l7'Fax
FbxF^enFganFa\l7'FaxFbxFj`lFgxFa\l7'FaxFbxFWFdbmFe^lF%,
I'shiftsw,6)FDF]cm%#_AGFEFhilFcenFj_o6/%#tmGF]`o%#nAGFf\oFi\oFN%$sf1GFigmFd`lFa
amFMFjjn%$_A1G6"F%C+>Fin-Fgq6#FZ>FdpFa_n>Fgn-%%timeGF%@%/FinF@C$>Fhn-Fg_o6%FdpF
fr9*@%0-%%nopsGFe`mF@>F\q-Fdgm6$w,FhgmF%6$FdwFewF%-Fham6$7$F^oF[x-Fbr6$F[xF\jmF
%F%6&Fd`lF\sF]`oFhn6#F26$7'FaxFbxF=F_alFex7'FaxFbxF=F]ilFexFhn>F\q-Fjan6$F^oFfr
C%>Feq7#-Fham6$-F_en6%<#-Fham6$&FjqFfu-Fbr6$Fjq-Fay6$w,FbcmF%6$FdwFewF%/FjcmF[x
F%F%6$FigmF_r6#F26$7'FaxFbx"#dFg]lFex7'FaxFbxF^ioFdxFexFZFfr9)/F_r;F2Fdp>F\q7$F
]cl-Fham6$-Fham6$7$F_rF\s-Fbr6$F\s&FeqFijmFaio>F\q-F[_n6%FbrF\qFct>F\q-F[_n6$w,
FbcmF%6$FdwFewF%/FhcmF@F%F%F\dm6#F26$7'FaxFbxFcilF=Fex7'FaxFbxFcilF`_mFexF\q>6$
F_uFhv-F]w6%-Fjbm6$F^oF\qFfrFj]o>6$F_uFix-Ffjn6$F_uFj]o>6$F\q806$-&F[_nFegm6%Fb
rF\qFix<$&&F\q6#FixF%FaboO6(F_uFhvF\qFf[p-F`cl6#-Feo6$w,FbcmF%6$FdwFewF%-Febl6$
F[dmFghlF%F%6$FEFfr6#F26$7'FaxFbxF_]lFc]lFex7'FaxFbxF_]lFexFexF\q,&FieoF2FgnFbx
F%F%F%6#Fj`l637'FaxFbxFcblF/Fex7'FaxFbxFadmFh\lFa\l7'FaxFbxF\amF^ioFa\l7'FaxFbx
FWF1Fa\lFegn7'FaxFbxFj`lF\anFa\lFddo7'FaxFbxF^enF[alFa\l7'FaxFbxF^enFe`nFa\l7'F
axFbxFj`l"$+"Fa\l7'FaxFbxFj`lF^ioFa\l7'FaxFbxFj`lF]ilFa\l7'FaxFbxFWFd[mFa\l7'Fa
xFbxFWFe[mFa\lF^]lFb\l7'FaxFbxFWFe]lFe^lF%,
I(shifts1w,6)FDF]cmF\eoFEFFFhilFcen6-Ff\oF^eoFNF`eoFigmFd`lF]bn%#spGFg\o%$SCsGF
i\o6"F%C->FgnFa_n>FhnFieo>Fin7#-Fham6$-F_en6%<#-Fham6$&FdpFfu-Fbr6$Fdp-Fay6$w,F
bcmF%6$FdwFewF%FihoF%F%6$FigmF\q6#F26$7'FaxFbxF\anFailFex7'FaxFbxF\anFc]lFexFZF
frFafo/F\q;F2Fgn>Fin7#-Fham6$-Fham6$7$F\qFeq-Fbr6$Feq&FinFhqF^`p>Fin-F[_n6%FbrF
inFct>6$FjqF_r6$&-F`alFggoFcq&-F`al6$-FjbmFgdlFfrFfu>F\s-&Fgs6#Fgq6#7#-Fham6$-F
ay6$w,FbcmF%6$FdwFewF%FihoF%F%Fi_p6#F26$7'FaxFbxF\]lFi]lFex7'FaxFbxF\]lFd[mFexF
ZF^`p>F_u-Feo6$w,FbcmF%6$FdwFewF%-Fc\o6'F^oF[x-F\bl6$F\x-F_fn6%&T'FicmF[tF[dmFb
cpF]\nF%F%6*Ff\oFgnFc^pF_rF]bnFjqFg\oF\s6#F26$7'FaxFbxF1F`\mFex7'FaxFbxF1FdbmFe
xFin>F_u-F`hl6$F_uw,FchlF%6$FdwFewF%552Fjcm&FZFcq3/FjcmF`dpF`]n3Fc]n-%(testOrdG
6%&&F^o6#FboFfu&&FZFidpFfuFghlF%F%6$FFFj]o6#Fgu6$7'FaxFbxF_\l"$:"Fex7'FaxFbxF_
\lFi^mFex>Fhv-F[_n6$w,FbcmF%6$FdwFewF%FejoF%F%F\dm6#F2Fgjo&FfvFf]nO6'-F]w6%-Fjb
m6$F^oFhvFfrF`ioFhvFct-Febl6$&&FfvFidpFfuFfr,&FieoF2FhnFbxF%F%F%6#Fj`l6.F\\l7'F
axFbxFcblF[[lF\]lFd]p7'FaxFbxFW"#'*Fa\lF\^l7'FaxFbxFWFi^mFa\l7'FaxFbxFW"#bFa\l7
'FaxFbxFWF^ioFa\lFi`m7'FaxFbxFW"$;"Fa\lF[am7'FaxFbxFW"##*Fe^lF%,
I.actMonCheckerw,6%FEFF%)sActMonsG6#%&amonsG6"F%C$@%3-F[p6$FctF^p4-F[p6$Fct-F^p
6#F^pC&>Fgn-Fay6$w,FeclF%6$FdwFewF%3-F[p6$F[dlF^ao-F[p6$F^dlF^aoF%F%F%6#F26$7'F
axFbxF[elFj`mFex7'FaxFbxF[elFi^mFexFct>Fgn-Feo6$w,FeclF%6$FdwFewF%*&-&Fgp6#%0Le
adingMonomialG6$F[dlFghlF2-Fhip6$F^dlFghlFbxF%F%Fhhl6#F26$7'FaxFbxF_\l"$1"Fex7'
FaxFbxF_\lF[elFexFgn>Fgn-F[]m6#-F[_n6%FbrFgn7#F2@&/F^fmF@YQ<no~valid~values~in~
sActMonsF%0F^fmF[_o-Fibo6#QMinvalid~values~in~sActMons~have~been~removedF%>FgnF
ctOFgnF%F%F%6#FW6,F__oFegn7'FaxFbxFj`lF`gpFa\l7'FaxFbxFj`l"$9"Fa\l7'FaxFbxFj`lF
_alFa\lFddo7'FaxFbxF^enFd^lFj\l7'FaxFbxF^enFa]lF_\l7'FaxFbxFj`lFcxFa\l7'FaxFbxF
WFb\mFe^lF%,
I+actionMonsw,Fcgp6%Ffgp%#aMGFK6"F%C&>Fgn-FagpF_gl@,-F[p6$FgnF^p>FhnFgn/FgnF2>F
hnF^o/FgnFgu>Fhn-Fju6%F2F[tF^o/FgnFW>Fhn7$&F]]qF%&F^oF%/FgnFbo>Fhn7%Fb]qFc]q-Fh
am6$&-Fju6%FinF[t-%%subsG6$/FinF_hmF^oF%-Fbr6$FinF^o-Fhr6%Q+|+%-40s%a|+|+F%Q2Ac
tion~monomials:F%FhnO-Feo6$w,6#%#amGF%6$FdwFewF%-Fe\m6%-F[p6$F^oF^pF^o7#F^oF%F%
F%6#F26$7'FaxFbxF1F]^lFexFgcpFhnF%F%F%6#FW6,Fbgl7'FaxFbxFWFd^lFa\lFegn7'FaxFbxF
gbmFeglFa\l7'FaxFbxFe_lF\]lFa\l7'FaxFbxFe_lFd[mFa\l7'FaxFbxFe_lF]^lFa\l7'FaxFbx
Fe_lFb^lFa\l7'FaxFbxFWFj\lF_\l7'FaxFbxFWFe^lFe^lF%,
I4solvingSetReductionw,6(Fbam%#PsGFben%#AVG%#nEG%"JG6&%$B1sG%%nB1sG%%aB1sG%"KG6
"F%C&>FgnFct>FhnFbx?(F%F2F2F%0F^fmFhnC&>6$FhnFin6$F^fm-F\bl6#-Fham6$-F_fn6%FJF[
tFgn-Fbr6$FJFfr-%'union=G6$Fgn-%*intersectG6$FinFZ>Fdp-Feo6$w,FeclF%6$FdwFewF%,
&-F[bm6$F^oFghlF2T&FbxF%F%6&FbamF^oFd`qFj]o6#F26$7'FaxFbxFcilFedmFexFijo-FjelFb
bq-F^bq6$Fgn-Feo6$w,6#FaelF%6$FdwFewF%&Fd^mF%F%F%6$Fe`qF`io6#F26$7'FaxFbxFadmF=
Fex7'FaxFbxFadmFcxFexFdpOFgnF%F%F%6#F/6+7'FaxFbxFadmF/Fex7'FaxFbxFcblFddlF\]l7'
FaxFbxF_\lF=Fa\lFf`n7'FaxFbxFj`lFc\lFa\l7'FaxFbxFj`lFhbmF_\l7'FaxFbxFj`lFgglFa
\l7'FaxFbxFj`lFd[mF_\l7'FaxFbxFWFcglFe^lF%,
I0completeSetTestw,6$FbenFE6'%#vvGFK%#ttGFd`l%&vars1G6"F%C%>F\qFZ>Fgn-Fay6$w,Fe
clF%6$FdwFewF%-%'andmapG6$w,FbwF%6$FdwFewF%5-Fbr6$*&FghlF2F^oF2F[cq-Fbr6$*&Fghl
F2F^oFbxF[cqF%F%6&Fd`lF^oFbenF[cq6#F26$7'FaxFbxFgxF^ioFex7'FaxFbxFgxF=FexF[xF%F
%6&F_eqF\qFbenF^o6#F26$7'FaxFbxFcilFailFexFijoF^o@%0F^fmF@C$>Fin-Feo6$w,FbwF%6$
FdwFewF%-Fe\m6%-Fbr6$*&&F[xFcqF2F^oF2F[cq7$FigqF27$*&FjgqF2F^oFbxFbxF%F%6&F]eqF
gnFbenF^o6#F26$7'FaxFbxFdbmFajmFex7'FaxFbxFdbmF_\lFexF\qO6$7$-Fham6$&FdpFcq-Fbr
Fbq&FgnFcq7#-Fham6$Fb_pFihqOF@F%F%F%6#Fgu6)F\do7'FaxFbxF[[lFh\lFa\l7'FaxFbxFW"#
pFa\lFegn7'FaxFbxFj`l"#zFa\l7'FaxFbxFj`lFc\lFe^l7'FaxFbxFj`lFb\mFe^lF%,
I&gjordw,6'Faam%"mGFi^lFhilF]hn6$F_hnF^in6"F%C$@%Fj]o>Fgn-Fhhn6$-F[in6$F^o.FhnF
frC$>Fgn-&F[`m6#%%CopyG6$FfrF^o-&F[`m6#%*RowReduceG6-FfrFgnFZFctFctF@F@FejqF@F@
FgfmOFcbnF%F%F%6#F]_o6(7'FaxFbxFd_lF/FexFegnF\en7'FaxFbxFj`lF]^lFa\l7'FaxFbxFj`
lFj`mF_\lFhdoF%,
I,solvingSetsw,6'FaamFMFc`qFFFhil64%#VsGF[jqFi^lFJFb`q%#RsG%#EsGFbamF_hnF^inFd`
q%$nERGFahn%"CG%$PRsG%#mRGFe`qFben6"F%C.>Fgn-%(convertG6$FZ%$setG>Fjq<">FhvFbx>
Fcaq-Fdz6$F2F^o?(F%F2F2F%0-Fgq6#FjqFhvC.-%'minus=G6$FgnFjq>F\q-Fabq6#-Fham6$-Fa
y6$w,FeclF%6$FdwFewF%-Fbr6$*&F[xF2F^oF2F\xF%F%6&FJFdpF\\rFgn6#F26$7'FaxFbxFexF]
^nFex7'FaxFbxFexFe`nFexFgn-Fbr6$FdpFct@$/FfqF@OF@>Feq-Fjel6$-F\bl6#-Fham6$-F_fn
6%FdpF[tF\qFi^rF\q-F^bq6$Fjq-Fjel6$Fgn-F\bl6$FeqF\q>F_r-Fbv6#7%&-F[hl6$7#&FjqF%
FfrF%&-F[hl6$7#F[dnFfrF%&-F[hl6$7#&F\qF%FfrF%>6$F\sF_u-Fhiq6'-F^am6%F^oFZF_rFhn
FinFj]oFh_m>FhvFb]r>Fix,&FhvF2-Fgq6#FeqF2>81-Fay6$w,FhgmF%6$FdwFewF%2F[xF[dmF%F
%6$Fd`qFhv6#F26$7'FaxFbxF`_mFgbmFexFa_m7#-Fham6$7$Ff[p-F[bm6$F2&F\s6$Ff[p;F%Fix
/Ff[p;F2F_u>F[br-Fay6$w,FhgmF%6$FdwFewF%-&%+ArrayToolsG6#%'IsZeroG6#&F[x6$Fjcm;
,&F[dmF2F2F2F\xF%F%6&F_hnF\sF_\rFix6#F26$7'FaxFbxF`_mFjglFexFa_mF[br-F^bq6$Fjq-
Fjel6$Feq-Fg\r6$&F_r6#-%%map2G6%FdzFguF[brFi\r>82-Fg\r6$&F_r6#-Fay6$w,FhgmF%6$F
dwFewF%2F[xF^oF%F%6$F_\rFix6#F26$7'FaxFbxF[_mFexFex7'FaxFbxF[_mF=Fex7#-Fham6$-F
[bm6$F2&F\s6$Ff[pF_yF^crFi\r>6%FeqF\qFix6%-F\bl6$FeqF_er-Fjel6$F\qF_er,&FixF2-F
gq6#F_erF2>F_rF^`r>F\s&FaarFcq>83-F[bm6$F2&F\s6$F_y,&FhvF2F2F2>847#-Fham6$-Fg\r
6$&F_r6#-&Fgs6#%"+G6%-Fg\r6$-&Fgcr6#%,SearchArrayG6#&F\s6$Ff[p;,&FixF2F2F2F%F^p
F[tFixFi\r/Ff[p;Fcgr,(FcgrF2FharF2FbxF2O<#-Fham6$-F_`q6(F_rF\q85FctFhvFjgr-Fbr6
$F[jrFjgrF%F%F%6#F]_o6<Fh`m7'FaxFbxFcblFgbmF\]l7'FaxFbxFj\lF^ioFa\l7'FaxFbx"#tF
j`mFa\l7'FaxFbxFWFddlFa\lFf`n7'FaxFbxFj`lF`_mF_\l7'FaxFbxFj`l"#nFa\l7'FaxFbxFj`
lFd^lFf\l7'FaxFbxF=Fh\lFe^lFh`n7'FaxFbxFj`lFh\lF_\lFi`nFg`nF[\q7'FaxFbxFj`lF[_m
Fa\l7'FaxFbxFj`lFebmFa\l7'FaxFbxFj`lFa]lFa\l7'FaxFbxFj`lF^ioF_\l7'FaxFbxFWF`gpF
a\l7'FaxFbxFWF_alFa\l7'FaxFbxFWFeiqFa\lF`[s7'FaxFbxFWFi]lFa\lF]gp7'FaxFbxFWFgjr
Fe^lF%,
I&getTDw,6*FbenFc`q%%deg0G%$mxnGFMF]cmFF%%cmplG6&FJF]\rF^\rFbam6"F%C&>Fhn-Fjel6
$-F\bl6#-Fham6$-F_fn6%FgnF[tF^o-FbrF^bmF^o>Fin-Fjel6$-Fg\r6$Fj]oFi\r-F\bl6$FhnF
^o>Fdp-Fbv6#7%&-F[hl6$7#&FinF%FafoF%&-F[hl6$7#&FhnF%FafoF%&-F[hl6$7#Fc]qFafoF%O
7)FZFct7%-FgqF\cnFh]oFa_nFfrFdpF`io9+F%F%F%6#Fd_l6'Fe[r7'FaxFbxFWFedmFa\l7'FaxF
bxFWFa\lFa\lFa[s7'FaxFbxFWFj`mFe^lF%,
I-templateTestw,6*FaamFMF]cmFc`qFEFFFg[sFhil6(F^eo%$OutG%$BBsG%%BB1sGFbenFi[s6"
F%C*>FgnFieo>Fhn-Fh[r6'F^oFZFfrF`ioFd^s@$/FhnF@O6$F@F^]p>6$FinFdp-%-selectremov
eG6$w,6#FbenF%6$FdwFewF%0-FidqFjbqF@F%F%6$FEFj]o6#F26$7'FaxFbxFgbmFjglFex7'FaxF
bxFgbmF]ilFexFhn@%0Fc^sF@>FeqF2>6$FeqFin6$F@Fdp>Fin-F[_n6$w,Fa`sF%6$FdwFewF%-%&
orseqG6$-F[bo6$%$Bs1GF^o-Fbr6$Fjas-Fjel6$F[x<#F^oF%F%6$F__sFin6#F26$7'FaxFbxFdb
mFgglFexFbhqFin>Fin-Feo6+Fd[sFinFfrFafo7#F^]rFZFctF`ioFeqO6$-Fi\n6$Fe]sw,FchlF%
6$FdwFewF%52&FZ6#Fj`l&F^oFacs3/FbcsF`cs2&Fg]n6#Fbx&Fe]nFgcsF%F%F%6#Fgu6$7'FaxFb
xF]al"$,"Fex7'FaxFbxF]alF[gpFexF^]pF%F%F%6#Fd_l6.F``nFd]p7'FaxFbxFWFeglFa\l7'Fa
xFbxFWFe[mFf\l7'FaxFbxFdbmFexFe^lFb\lFegn7'FaxFbxFj`lFcilFa\lFgdoFbiq7'FaxFbxFW
FailFa\l7'FaxFbxFWFg[qFe^lF%,
I-colReductionw,6%FaamFd`qFhil6'F_hnF^inF`hnFahn%&c2delG6"F%C&>Fcbn-Fhiq6&F^oF^
]rFctFh_m>Fin7#-Fham6$-F[bm6$F2&Fgn6$FdpF_y/Fdp;F2Fhn>F\q-F[_n6%Fbr7#-F^t6#;F2F
ZFinO6%&F^o6$F_y-F[_n6%Fbr7#-F^t6#;F2-Fdz6$Fd[lF^oF\qFgnF\qF%F%F%6#FW6'F``n7'Fa
xFbxFWFf\lFa\lFjfp7'FaxFbxFWFganFa\l7'FaxFbxFWFc\lFe^lF%,
I0sparseReductionw,6''FaamFg]m'F]cmF`hp'Fd`q%*nonnegintG'%&spolsGF^pFjdm6-%#rgG
F_z%"kGF[jqFi^l%$crgG%#M1GF`hn%#ldG%$rpnG%$cpnG6"F%C/>Fgn-Feo6$w,FhgmF%6$FdwFew
F%-F^t6#;,&-F\r6$-Fgq6#&Fghl6#F\x/F\x;F2,&F^oF2FbxF2F2F2F2-F\r6$F`is/F\xFgcoF%F
%6&F]cmFZF_zFhn6#F26$7'FaxFbxFcgl"#wFex7'FaxFbxFcglFb\mFexFfr@$FjjpO6%F@F_oF_o>
6%FinFdpF\q6$F^fmF^]r>Feq-F[_n6%Fbr7#-F^t6#FbioFgn>Fjq-%$<,>G6$F]\o&F^o6$FeqF_y
>F_r-Fjgn6%)&Fjq6$Fejm;F2FctFa[oFj]oFh_m@$FgjmOFbjs>F\s-F[_n6%FbrFbjmF_r>F_u&7$
F^blF[dn6#7%&F_rF%&F\sF%-F^t6#;,&FinF2F2F2Fdp>F_r-Fjgn6%&Fjq6$F_rFh[tFj]oFh_m>F
\s-F[_n6%Fbr7#-F^t6#Fh[tF_r>Fhv7%Fc\tFd\t-F^t6#;,&FctF2F2F2F\qO6%FhjmF_uFhvF%F%
F%6#F]_o62F\do7'FaxFbxFW"#%)Fa\l7'FaxFbxFWFj\lFf\l7'FaxFbxFi^mF\amFe^lFa\oF\^p7
'FaxFbxFWFgbmFa\lFg^sF`^tFa^tF^]lF_gsF]^pF\^pF[]l7'FaxFbxFWF]ilFe^lF%,
I)readprobw,6#F:6)%$dirG%'subdirG%#fnG%$fn1GFael%*proc_nameGFD6"F%C+>FgnQ-../pr
oblems/F%>Fhn-Fay6$w,FfcqF%6$FdwFewF%-&%*FileToolsG6#%,IsDirectoryG6#-F\_l6$F[x
F^oF%F%6$Fh^tFgn6#F26$7'FaxFbxF_\lF^ioFex7'FaxFbxF_\lFadmFex-&Fh_t6#%.ListDirec
toryGF_fm>F\`s6$-F\_l6%Q#F_F%F^oQ#.mF%Fax@%-&Fh_t6#%'ExistsG6#-F\_lFjp>FdpFcat?
&F\qFhnFgfm@$-F_at6#-F\_l6&FgnF\qQ"/F%FinC$>FdpFiat[@$/FdpFaxY6$Q2file~%1~not~f
oundF%FinAFdp>Fjq-Fg\r6$-&Fgs6#Fa`l6#-%%evalG6#-F\_l6$%#F_GF^oF^p>Feq-F]ct6#-F
\_l6$%#C_GF^oO6%FinFjqFeqF%F%F%6#F262Fbjn7'FaxFbxFWFcxFa\l7'FaxFbxFWF[^nFa\lFd`
nFegnFban7'FaxFbxFj`lF_\mFd_l7'FaxFbxF^enF\dsFf\l7'FaxFbxF[^lFebmFa\l7'FaxFbx"#
))F@F\an7'FaxFbxFWFc]lFf\l7'FaxFbxFddlF]^lFj\l7'FaxFbxFWF^enFd^l7'FaxFbxFWFj\lF
a\lF\^p7'FaxFbxFWFi^mFe^lF%,
I,probCheckerw,6*Fj^t%#F0GF\_tFhil%*constPolsG%&iVarsG%+removePolsG%*indepVarsG
60FD%(indvarsGFf\oFEFjgs%$ff1G%$ff2G%$dffG%&ivarsG%&p2remGFFFG%#dmGFg[s6"F%C1>F
gnFZ>Fhn-Fay6%FbrFd^s-F]flF_fm@$0Fh]o-Fgq6#Fd^s-Fibo6#QNinvalid~values~in~indep
Vars~have~been~removedF%@$0Fh]oF@>Fgn-F]^q6$-Feo6$w,FbwF%6$FdwFewF%/F^oF`rF%F%F
%6#F26$7'FaxFbxFd^lF^ioFexF]`nFhnFgn>F\`s6$F^fm7#&F^ftF%@&5543-F[p6$-FjemF_fmF]
p-F[p6$-&Fgs6#F_dlF_fm-F^p6#F^aoF\fo/FbcnF@Y6$QWfile~%1~does~not~contain~a~list
~of~Laurent~polynomialsF%F^o4-F[p6$-Feo6$F^`lFgn-F^p6#-%(complexG6#%)rationalGY
Qhothe~coefficients~of~Laurent~polynomials~must~be~rational~or~Gaussian~rationa
lF%@$-F[p6$Ffr&Fb`m6#;Fgu"%+5-Fibo6#Q[oprime~number~is~too~small,~which~may~res
ult~in~invalid~templatesF%@)/Fj]oF@>F\qF_o/Fj]oF2@%-F[p6$Fct%*procedureGC)AQ6..
/problems/_common.mF%>6$FeqFjq6$-Fct6#/%)symbolicGF@F_[uAQ.redundantAG.mF%>F_r-
Fjem6#-Fibt6#-&Fgs6#%"-G6%FeqF[tFjq>F\q7#-&F\]m6#%*SearchAllG6$F@F_r>F_r-Fay6$w
,6#F_zF%6$FdwFewF%30Fa[nF@-F[p6$Fa[n-F^ao6$%)anythingGF\xF%F%6&FdetF_rFEFdp6#F2
6$7'FaxFbxF[[lFjdnFexF][lFbjm@$0FhjmF@-Fibo6$QJthere~are~almost~constant~polyno
mials:~%1F%F_r>F\qF_o4-F[p6$Fj]o-F^p6#&Fb`mFdjmC$-Fibo6#QNinvalid~values~in~con
stPols~have~been~removedF%>F\q-Fay6$w,Fj\uF%6$FdwFewF%1F^oF[xF%F%6$Ff\oFin6#F26
$7'FaxFbxF[elF\]lFex7'FaxFbxF[elF[[lFexFj]o>F\qFj]o@%4-F[p6$F`io-F^p6#&Fb`m6#;F
2FbcnC$-Fibo6#QJinvalid~values~in~iVars~have~been~removedF%>F\s-Fay6$w,Fj\uF%6$
FdwFewF%1F^o-Fgq6#F[xF%F%6$FEFdp6#F26$7'FaxFbxF[elFi]lFexFa_uF`io>F\sF`io@)/Faf
oF@>F_uF_o/FafoF2>F_u-Fgdm6%FgnFdpFfr4-F[p6$FafoF`^uC$-Fibo6#QOinvalid~values~i
n~removePols~have~been~removedF%>F_u-Fay6$w,Fj\uF%6$FdwFewF%F\_uF%F%F]_u6#F2F__
uFafo>F_uFafo>Fgn-F]^q6$-Ffs6%&Fgn6#F_uF[tF@Fgn>Fgn-F]^q6$-Ffs6%&FdpF]uF[t-Fju6
%F2F[tF^cuFgn>Fhv-%%tdegG6#Fa^o@$0FfrF@C%>Fix-Ffp6%F^htFhv/FagmFfr>Ff[p-&Fgp6#%
1HilbertDimensionG6%FixFhvF[du@%/Ff[pF@C$>F[br-Fgq6#&-F_q6$FixFhvFcq@$/F[brF@YQ
8the~system~has~no~rootsF%>F[brF2O6,FgnFinFdpFhvF\qF\sF_uFf[pF[brFhnF%F%F%6#Fd_
l6TFh`m7'FaxFbxFcblFcilF\]lF\^lFegn7'FaxFbxFj`lF_alF_\l7'FaxFbxFW"#!)Ff\l7'FaxF
bxF]ilFajmFa\lF`dsFegn7'FaxFbxFj`lFcjrFj\l7'FaxFbxFj`lF`gpFj\lFegnFg[rFegn7'Fax
FbxFj`lFdbmFa\lFddo7'FaxFbxF^enFe`nFd^l7'FaxFbxF^enFc\lFa\l7'FaxFbxF^enF\]lFd^l
7'FaxFbxF^enFi]lFa\l7'FaxFbxF^enF]alFa\l7'FaxFbxF^enF[^nFa\l7'FaxFbxF^enFdbmFf
\l7'FaxFbxFb\mFajmF_\l7'FaxFbxF^enFe_lFa\lFeeu7'FaxFbxFj`lFi]lFa\lFbanFegn7'Fax
FbxFj`l"#eF_\l7'FaxFbxFj`lFj\lFa\lFaanFegnF[fu7'FaxFbxFj`lFeglFa\l7'FaxFbxFj`lF
gglF_\l7'FaxFbxFj`lFa\lFa\l7'FaxFbxFj`lFi^mFa\l7'FaxFbxFWFgxFa\lFh^s7'FaxFbxFWF
admFa\lFegnFh[qFddqFddo7'FaxFbxF^enF[^lFa\l7'FaxFbxF^enFc\lFf\l7'FaxFbxFi^mF^io
Fj\l7'FaxFbxF^enF_\lFa\lFc[sF%,
I,readProblemw,6)'F:%'stringG'FhilFhgsF\etF]etF^etFcenF_et6+Fj^tFDF\_tFjgsFeetF
fetFgetFg[sFaet6"F%C(>Ffn-Fd^tFb`l>6,FhnFf\oFEFFFdpF\qFeqFjqF_rF\s-Fhdt6*FgnFhn
FinFZFctFfrFj]oFafo@%3-F[p6$FhnF]p/F`ioF2-%'assignG6$.FedpF\gl-Fhhu6$FjhuF^el>F
h_m-%$hasG6$Fhn^#F2@%0FZF@@%Fh_mC%-Fibo6#QRcalculations~over~complex~numbers~ar
e~much~slowerF%-%&aliasG6#/%$_iiG-%'RootOfG6#z'Ffcq#F2!F2>F]em-Fhhn6$-F]^q6$/Fa
iuF]juFhnFZ>F]em-Fhhn6$FhnFZ>F]emFhnO6-FhnFf\oFEFFFdpF\qFeqFjqF_rF\sF]emF%6)F]e
mFf\oFEFFF]juFh_mFedpF%6#Fj`l61Fh`mF^^l7'FaxFbxFW"$P"Fa\l7'FaxFbxFW"$I"Ff\l7'Fa
xFbxFedmFebmF_\l7'FaxFbxFb^l"$@"F_\l7'FaxFbxFWF[elFa\lFegnFddo7'FaxFbxF^enF\[lF
_\l7'FaxFbxF^enFd[mF_\l7'FaxFbxF^enFh\lFa\l7'FaxFbxF^enF[[lFa\l7'FaxFbxFj`lF1Fa
\l7'FaxFbxFWFajmFe^lF%,
I(getDataw,6'FDFf\oFEFF%#tdG6AFc`qFg[s%$ptnGFMF]cmFi[sFjgsFhilFeetFaetFaam%#V0G
FjjnFh[sFd`qFIFben%#iqGFjilFHFigmFahnFahsFbhsF_hnFjdsFJ%#r1G%#r2G%#iTGF]^m6"F%C
6>6,FgnFhnFinFdpF\qFeqFjqF_rF\sF_u&&Fj]o6#7$-F^t6#;F2FW-F^t6#;F]_oF^enF%>F\q-F`
hl6$F\qw,FchlF%6$FdwFewF%F_dpF%F%F%6#Fgu6$7'FaxFbxFcilF\]lFex7'FaxFbxFcilFadmFe
x>6$FhvFix-F]w6%F^[pFctF_r>6$FhvFf[p-Ffjn6$FhvF_r>6$F[brF\q6$7#-Fdz6$F2Fhv-F\hm
6$&-Ffs6%Ff[pF[tF_hmF%F\q>6$F_erFcgr6$&FinFcq&FinFgcs>Fjgr-Fg\r6$&Fdp6#;,$FcgrF
bxF%Fi\r@%/FeqF2>6$86F[jr-Fidq6$FjgrFct>Fc`v6$F_o7#-F^t6$F@F[_o>87-F[_n6%Fbr7#&
FjgrF%Fd`v>F]av7$&-F[hl6$F]avFfrF%&Fd`vF%>Fdp-Fbv6#7$&Fdp6#;F2,&FcgrFbxFbxF2&F]
avF%>Fhv-F^am6%FhvFixFdp>F\q7#-Fham6$-Feo6$w,6#F`eoF%6$FdwFewF%F[dmF%F%F%6#F26$
7'FaxFbxFdbmFgxFex7'FaxFbxFdbmFe_lFex-Fay6$w,FbcmF%6$FdwFewF%FihoF%F%6$Figm886#
F26$7'FaxFbxFganFedmFex7'FaxFbxFganFeglFexF\q/FfcvF`fs>6%898:8;-Fbgs6'FhvF\qF_e
rFjqF_r@$0F^dvF@>6$FhvFdp6$&Fhv6$F_dvF`dv&Fdp6#F`dv>6%Fhv8<8=-Ffds6%FhvF_erF_r-
%#-=G6$F_er-Fgq6#F_ev?&8>FgnFgfmC%>6$8@8?-F^`s6$w,FdyF%6$FdwFewF%-Fbr6$*&F[xF2F
\jmF2F\xF%F%6&FJFhevFHF]av6#F26$7'FaxFbxF=Ff\lFexFdgo7#-F^t6#;F2Fcgr>8B-Feo6$w,
FdyF%6$FdwFewF%-Fe\m6%FbfvF_hm,&-F[bm6$F2&Fbcp6$F_y-F[bm6$FdfvF]\nF2T+FbxF%F%6,
FJFhevFHF]avF_hnF^evFMFdpFd`qF_er6#F26$7'FaxFbxFcilF^anFexFb\nFifv>8A7$7#-Fham6
$&F]fv6#-F[bm6$FfcvF^gv/Ffcv;F2-Fgq6#F]fv-Feo6$w,FdyF%6$FdwFewF%,&*&F[xF2,&-F[b
m6$*&F\xF2&FbcpFb`lF2FbcpF2FbxF2F2F2F^oF2F%F%6(FIFcgrFJFhevFHF]av6#F26$7'FaxFbx
FcjrF`epFex7'FaxFbxFcjrFd_oFexF\fv>F^gv-Feo6$w,FhgmF%6$FdwFewF%&-F[_n6$w,Fj\uF%
6$FdwFewF%/&F[x6$F^oF[cqF@F%F%6&F_hnF[xFigmF^o6#F26$7'FaxFbxFadmFd[mFexF]dq<#-F
^t6#FbzF%F%F%6$F_hnF^ev6#F26$7'FaxFbxF_\mF^ioFex7'FaxFbxF_\mF1Fex<#&F_evF%O63-F
[\u6%F\_vF[tF^dvFhnFgnFinFdpF\qF_evF^gvF^dvF_dvFbhvF[jrFeqFjqF_rF\sF_uF%F%F%6#F
]_o6=F\\l7'FaxFbxFWFjdnFa\l7'FaxFbxFWF]ilFa\lF]^pF^]lFfdt7'FaxFbxFWF[_mFa\lF[]l
FegnFe_o7'FaxFbxFj`lFh\lFa\lF[]lFb^tF\^pF[]l7'FaxFbxFWFgglFa\l7'FaxFbxFWF\anFa
\l7'FaxFbxFWF]^nFf\l7'FaxFbxFcilFi]lFa\lF[am7'FaxFbxFWF[elF_\lFgdn7'FaxFbxFj`lF
c]lFa\l7'FaxFbxFj`l"$<"Fa\l7'FaxFbxFj`l"$?"Fa\lFbiq7'FaxFbxFWFe\lFe^lF%,
I-dispTemplatew,6+'Fb\vF^p'%$nTDGF[em'FDF^p'FEF^pFF'F^eo%&floatG%'headerG%(head
er2G%)showInfoG6(Ff\oFh[sFc`qFd\vFjdsFi[s6"F%C)@$/Fd^sF2C$@%/9,F2-Fhr6(Q7|+%-20
s%-20s%-20s%s|+%s|+F%Q0action~monomialF%Q+[#E,#R,#B]F%Q%sizeF%Q%timeF%-Ff^l6#Fg
jr-Fhr6(Fg^wFh^wQ0[#E,#R,#B](raw)F%Q*size(raw)F%F[_wF\_wOF%@$/Fd^wF@C$-Fhr6'Q3%
-20a%-20s%-20s%g|+F%Fjcm-%+alterCommaG6#Fg]n-Fj_w6#FhdpF`ioOF%>FgnF[_o>6'FhnFin
FdpF\qFeq&-F_\v6'FctFgnFfrFj]oF^o6#7'F2FWFboFj`lFcgl@$F`auC$-Fhr6$-F\_l6%Q"|+F%
-Fe\m6%Fa`vQ*Template~F%Q5INCOMPLETE~template~F%Q&#%g:|+F%FZ-Fhr6'Q3%-20s%-20s%
-20s%s|+F%Fh^wFi^wFj^wF[_w-Fhr6'Fh_wFin-Fj_w6#7$,&FhhqF2FfqFbx&&Fdp6#7$FguFWF%-
Fj_wFe`mF`io@$F`au-Fhr6#F]awF%F%F%6#Fcbl63F``nFegnFddo7'FaxFbxF^en"$3"F_\l7'Fax
FbxF^en"$="F_\l7'FaxFbxFj`lF@Fe^l7'FaxFbxFWF^gpFf\l7'FaxFbxFadm"#**F_\l7'FaxFbx
"$-"F@Fe^lFffp7'FaxFbxFWFd_oFa\lFegn7'FaxFbxFj`lF`anF_\l7'FaxFbxFj`lFianF_\l7'F
axFbxFWFgbwF_\l7'FaxFbxFWFeglFf\l7'FaxFbxF_\lF\]lF_\lF%,
I-saveTemplatew,6$FfguFb]w65Fh[sFg[sFc`qFd\vFMF]cmFjdsF]^mFahnFahsFi\vFf\vFi[sF
jgsFhilFeetFaet%#fdGFj^t6"F%C'>Fd`v-F\_l6$Q-templates/t_F%F^o>63FgnFhnFinFdpF\q
FeqFjqF_rF\sF_uFhvFixFf[pF[brF_erFcgrFjgr-F_\v6'F]emFf\oFEFFFZ>F[jr-%&fopenG6$F
d`v%&WRITEG-%(fprintfG62F[jrQJ%a|+%a|+%s|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%
a|+%aF%FgnFhn&-Fg\r6$FinFggu6#;Fgu!"#Fdp-Fg\r6$F\qF^pFeqFjqF_r7%F[brF\sF_uFhv7$
FcgrFixF_erFjgrF_o-%'fcloseG6#F[jrF%F%F%6#Fgu6(F``n7'FaxFbx"#)*"$G"Fa\l7'FaxFbx
FWF]]wFa\lF\dt7'FaxFbxFW"$(>F_\l7'FaxFbxFWF_\mF_\lF%,
I-readTemplatew,6#Ffgu65Fj^tFjcwFh[sFg[sFc`qFd\vFMF]cmFjdsF]^m%'xspolsGFi\vFeet
Ff\vFhilFaet%$xE0GFb\vFd`l6"F%C7>FgnF^dw@$4-F_atF_fmY6$FcbtFgn>Fhn-Fgdw6$Fgn%%R
EADG>Fin-%&parseG6#-%)readlineGF_fm>FdpFggw>F\q7#Fggw>FeqFggw>Fjq-F]ct6#-Fg\r6$
FggwFbv>F_r-&Fgs6#F]ct6#Fggw>F\sFggw>F_uFggw>FhvFggw>FixFggw>6$Ff[pF[br&FggwF%>
F_erFggw>FcgrFggw>FjgrFggw-FiewFe`m>F_r-Fdgm6$w,FhgmF%6$FdwFewF%F[goF%F%6&Fd`lF
d`vF]cmF_r6#F26$7'FaxFbxFe_lF]^lFex7'FaxFbxFe_lF[elFexF_r>F[jr7-F\qFdpFeq7$Fg_v
-F\rFiarFjqF_r-Fe\m6%-Fbr6$F@F[brF@F2&FhvFcqF_erFf[pFcgrO61FinFdpF\qFeqFjqF_rF
\sF_uFhvFixFf[pF[brFcgrFjgrF[jrF%F%F%6#F269F``n7'FaxFbxFcblFe`nF\]l7'FaxFbxFWFd
_oFf\l7'FaxFbxFganFc\lFj\lFh[vFb\wFb^tFb^tFb\w7'FaxFbxFWF]alFa\lF^]l7'FaxFbxFWF
=Fa\lFifpF[]lF]guF^^lF]guFa\wFb\wFcfw7'FaxFbxFWF]^nFa\l7'FaxFbxFWF\dsFa\l7'FaxF
bxFWFebmFe^lF%,
I.backwardErrorw,6&FDFEFNFg[s6+Ff\oF]em%$solGFigmF]hs%$bweG%#nSG%"dG%#bbG6"F%C+
>FgnFa_n>Fhn-FibtFb`l>Fjq-Fdz6$Fd[lFct>F_r-%$minG6$FfrFjq>Fin7#-Fham6$-Ffs6%FZF
[t-Fg\r6$&Fct6$F_yF\qF^p/F\q;F2Fjq>Feq-F^[t6#-Fham6$*&FgnFbx-F\r6$*&-%$absG6#-F
]^q6$Fi`p&FhnFccnF2-F]ct6#,&-F]^q6$Fi`p-Feo6$F_^xFc^xF2F2F2Fbx/FdpF_`pF2Fc]x>Fe
q-F`hl6#-F\uFiar@$FerC%>F\s-Fju6%&Feq6#;F2FcewF[t&FeqF_cn>F_r-&Fg\x6#%&indexGF]
u>F_r-Fe\m6%2&F\sFijm,$FY#F2FguF_rFjqO7&&Feq6#;F2F_r&Feq6#;,&F_rF2F2F2F%-F`cl6#
Fg`x-&%+StatisticsG6#%.GeometricMeanGF_axF%F%F%6#Fbo6/F__oFffp7'FaxFbxF[_mFa\lF
a\l7'FaxFbxF_alFeiqFa\l7'FaxFbxFb_oF^fwFa\lFe\w7'FaxFbxFWFajpFa\lFfdnFegnF[^pFb
anFc\w7'FaxFbxFWF`^lFe^lF%,
I+rootFinderw,Fffw6(%#TMG%%optsG%&toptsGFNFOFi[x6"F%C(>FgnFieo>Fhn-%+optChecker
GFidp>Fin-Fg\r6$7#FhnFcs>6%FdpF\qFeq-Fe\m6%54-%)assignedG6#&Fin6#%&mRootG/FecxF
2-%(tsolverG6$F^oFhn-F7F[dx-Fhr6%Q*|+%-12s%g|+F%Q,Total~time:F%F^]pOF]cxF%F%F%6
#F26)FbglFd]pFh[vF^]l7'FaxFbxFWFgbwFa\l7'FaxFbxFWF]alF_\l7'FaxFbxFWF_\lFe^lF%,
I(tsolverw,6'F:>F<F=>F?F@>%'showCPGF@>%)showRREFGF@6>Fg[sFc`qFd\vFMF]cmFjdsFhfw
FeetFf\vFaetFDFEFIFahnFahsFHFaamF`\rF_hnFJFL%#evG%#cpG%#nvGF_zFigmFNFO6"F%C8FR>
FYFZ>F]]v&-FdfwFb`l6#7'-F^t6#;FguFj`lFcblF^enF_\mFcgl@$-F_iu6$F@F\sYQOthe~case~
of~incomplete~template~is~not~handledF%>Fb^v&-F\o6)F^oF@F_oF_rF@F2F_u6#7$F2FW>6
%Ff[pF[brF_er6$Fh_v-Fdz6$;FguFWFjq>Fcgr-Fg\r6$&Fdp6#;,$Ff[pFbxF%F^p>Fjgr-F^am6$
-F]w6$-Fjbm6$FhvF\qFixFdp>F[jr-F[_n6%Fbr7#-F^t6#;F2-Fdz6$Fd[lFjgrFeq>6$FjgrFdp6
$&Fjgr6$F_yF[jr&FdpFjew@$0F[brF@C$>Fjgr&Fjgr6$F_erF_y>Fhhx6$,&&Fjgr6$;,&F[brF2F
2F2F%FhixF2-F_v6$&Fjgr6$Fhix;F2F[br-F_v6$-&Fcu6#%.MatrixInverseG6#&Fjgr6$F^jxF^
jx&Fjgr6$F^jxFhixFbx&Fdp6#Fhix>Fd`v-&Fcu6#%6ReducedRowEchelonFormG6#-F\u6#Fjgr@
$FdjtC$-Fhr6#QFReduced~row~echelon~form~of~template:F%-Fit6#-F\u6#Fd`v>Ffcv-&Fc
u6#%+ZeroMatrixG6#Ff[p?&F]avFhnFgfm-%#+=G6$Ffcv*&F`rF2)-Fg]m6#-Feo6$w,FeclF%6$F
dwFewF%-Fe\m6%Fa^r-&Fbv6#%'columnG6$Fbcp<#/-F[bmFb^rF2,$)&F]\n6$-F[bm6$$F2F@&F]
\n6$F_y-F[bm6$Fc^rF\hv7#;,$FbcpFbxF%Fa[oFbxF%F%6,FJF]avFHFcgrFIFf[pF_hnFd`vFMFd
p6#F26$7'FaxFbxFgbm"$y"FexFi`sFcgrFa[oF2@$FbtC$Fet-Fit6#-F\u6#Ffcv>F^dv&-FbuF__
yFfu@$FerC%>F_dv-%'factorG6#-&Fcu6#%9CharacteristicPolynomialG6$Ffcv%'lambdaG-F
hr6#QFFactorized~characteristic~polynomial:F%-Fit6#-F\u6#F_dv>F`dv-FgqF^\p>Fhev
)-Fg]m6#7#-Fham6$7#-Fham6$-Fe\m6%/&F\s6#F^evF2*&&&F^dv6#,(F`dvFbxF^evF2FcewF2Ff
evF2&&F^dvFgcsFfevFbx*&F^byF2FjayFbx/F^ev;F2F`dv/F_ev;F2Ff[pFa[o>F]fv-F[y6#&Fhe
v6$F_y-Fay6$w,FhgmF%6$FdwFewF%-Fhy6$-F[z6$&F[x6$F\xF^oF`z/F\x;F2FbcpF%F%6(FNFhe
vF_zF^evFcexF`dv6#F26$7'FaxFbxF[[lFdxFexF][l7#-F^t6#FdbyO6%FhevF]fv-Fh[l6&FhvFi
xFhevFgnF%F%F%6#F26DF\\lF^\lF`\l7'FaxFbxFWF^fwFa\l7'FaxFbxFWFebmFf\l7'FaxFbxFad
mF^jsFj\lFb\lFb[sF[]lFjfpFg_qFh[vFegn7'FaxFbxFj`lF_\lFa\l7'FaxFbxFj`l"$6"Fa\l7'
FaxFbxFWFc`nFa\l7'FaxFbxFW"#&*Ff\l7'FaxFbxFadmFg]lF_\l7'FaxFbxFajmF`^lF_\lF`gsF
gdn7'FaxFbxFj`l"$'=F_\lFf]lFh]lFj]lFg^sFegn7'FaxFbxFj`lF\[lFa\l7'FaxFbxFj`lF\an
F_\l7'FaxFbxFc]lFajmF_\lF^gu7'FaxFbxFWF`epFa\lFd]l7'FaxFbxFWF]^lFe^lF%,
I+iniProblemw,6)F:FhilF\etF]etF^etFcenF_et6-FDFf\oFEFFFjgsFeetFfetFgetFg[sFaetF
]em6"F%C->6-FgnFhnFinFdpF\qFeqFjqF_rF\sF_uFhv-F\o6)F^oFZFctFfrFj]oF`ioFafo-Fhr6
%Q)%-40s%a|+F%Q7Number~of~polynomials:F%Fhn-Fhr6%FafyQ=Sparse~constant~polynomi
als:F%F\q-Fhr6%FafyQ5Polynomials~removed:F%Fjq-Fhr6%FafyQ5Number~of~monomials:F
%-Fgq6#&-F`alFjpFfu-Fhr6%FafyQ+Variables:F%Fin-Fhr6%FafyQ)Degrees:F%-Feo6%FeblF
gnFin-Fhr6%Q*%-40s%a|+|+F%Q6Degrees~by~variables:F%-Fdgm6$w,Fj\uF%6$FdwFewF%-Fe
o6$w,FbwF%6$FdwFewF%-Febl6$&F[x6#F[cqF_bsF%F%6&FDF\xF_zF^o6#F26$7'FaxFbxF\[lF`g
pFex7'FaxFbxF\[lFcjrFexF[xF%F%6&FEFinFDFgn6#F26$7'FaxFbxFgglF]cwFex7'FaxFbxFggl
Fa]lFexFgn-Fhr6%FafyQ+Dimension:F%F_r-Fhr6%FafyQ1Number~of~roots:F%-Fe\m6%/F_rF
@F\s.%$infGO6*FhvFhnFinFdpF\sF\qFeqF_uF%F%F%6#Fj`l6.Fbgl7'FaxFbxFW"$Q"Fa\l7'Fax
FbxFWF]^nF_\l7'FaxFbxFWFdxF_\l7'FaxFbxFWFe^lF_\l7'FaxFbxFWFcjrF_\l7'FaxFbxFWF\a
mF_\l7'FaxFbxFWFc]lF_\l7'FaxFbxFW"$/"F_\l7'FaxFbxFWFe`nF_\l7'FaxFbxFWFc\lF_\l7'
FaxFbxFWF^ioFe^lF%,
I+optCheckerw,6#F]hs6%%(inifileGFabx%(checkerG6"F%C*>FgnQ0redundantAG.iniF%@$F^
gwC$-Fibo6$QLfile~%1~not~found,~default~settings~appliedF%FgnOF%AFgn@$4-Fccx6#F
`bxC$-Fibo6$Qhnvariable~opts~in~%1~is~not~assigned,~default~settings~appliedF%F
gnOF%>Fhn-Fg\r6$7#F`bxFcs>Finw,6$%$optG%$typGF%6"F%@$43-FccxFh[n-F[p6$Fa[nFZC$-
Fibo6$Qapparameter~%1~is~either~not~assigned~or~has~a~wrong~value,~default~valu
e~for~%1~appliedF%F^o-%)unassignG6#.Fa[nF%F%6$FabxFhn6#Fgu6&7'FaxFbxF1F]\lFexFd
do7'FaxFbxF^en"$7"F_\l7'FaxFbxF^enF]ilF_\l@*/F^oF2C,-Fin6$%,primeNumberG%&prime
G-Fin6$F\et<$&Fb`m6#;F@F2-%-nonemptylistG6#F[em-Fin6$F]et-F^pFf_z-Fin6$F^etF`_z
-Fin6$Fj_oF`hp-Fin6$Fcen&Fb`m6#;FbxF2-Fin6$Fdgp<$Fe_z&Fb`m6#;F2Fbo-Fin6$%(dChan
geGFhgs-Fin6$%&maxTDGF[em-Fin6$F_etF^p/F^oFguC%-Fin6$%%mRedG&Fb`m6#;F2Fgu-Fin6$
%)nRootTolGFhgs-Fin6$F[^wFa_z/F^oFWC(-Fin6$%)languageG&Fb`mFc]v-Fin6$%'showPMGF
a_z-Fin6$%'colpivGFa_z-Fin6$%0createCoefsFileGFa_z-Fin6$%/createTestFileGFa_z-F
in6$%1createSolverFileGFa_z/F^oFboC(-Fin6$FgcxFfaz-Fin6$F<F[em-Fin6$F_exFa_z-Fi
n6$F?Fa_z-Fin6$F]exFa_z-Fin6$FBFa_zO-Fb]m6$Fhn.%&pairsGF%F%F%6#F26HFbgl7'FaxFbx
FcblFganF\]l7'FaxFbxFWFg[vFf\l7'FaxFbxFi]lFjjyF_\l7'FaxFbx"$2"F@Fe^l7'FaxFbxFWF
b\mFd^l7'FaxFbxFW"$F"Ff\l7'FaxFbxF="$5"F_\l7'FaxFbx"$8"F@Fe^lF^]l7'FaxFbxFWF]\l
Fa\lFegn7'FaxFbxFj`lF_]lF_\lFeeuFgdqFjfu7'FaxFbxFj`lFexF_\lFjjrFaeyFeez7'FaxFbx
Fj`lF[_mF_\l7'FaxFbxFj`lF=F_\lFgdqFgdqFjjrFjjrFfezFfez7'FaxFbxFj`lFf\lF_\l7'Fax
FbxFj`lFe[mF_\l7'FaxFbxFj`lFd^lF_\lFedqFhezFjjrFfezFfezFfezFc^tF%,
I/templateFinderw,Fffw6$F_bxF`bx6"F%C&>FgnFieo>Fhn-FgbxFcq-%(tfinderGF[dxF]dxF%
F%F%6#F26'FddnFd]pFh[v7'FaxFbxFWFe_lF_\lFedxF%,
I(tfinderw,6-F:>F\etF2>F[azFi]p>F]etF_o>F_etF_o>Fj_oF_o>F^azFi]p>F\_z"&4+%>F^et
F@>FdgpFW>FcenF265Fd]wF]emFf\oFEFFFg[sFjgsFeetFaetF`\qF[\xFaamFMF]cmF\eo%#mdGF^
eoFc`qF^_s6"F%C*>%#TDG-%&ArrayG6#F_o>FgnF@>F[brF_o>F_erF[]r>6*FhnFinFdpF\qFeqFj
qF_rF\s-Feey6)F^oFd^sFZFfrFd^w9.Fj]o>F_u-F]\q6%FdpF\q9--Fhr6)Q;%-15s%-15s%-15s%
-15s%s|+%s|+F%Q"dF%Q,#cols-#rowsF%Q&#rowsF%Q'degreeF%F[_wF\_w?(FhvF@F2F%3-%#orG
6&Fb`o30FeqF24-Fbr6$Feq-Feo6$w,6#Fb\vF%6$FdwFewF%FfcsF%F%F%6#F26$7'FaxFbxF_alFe
]lFex7'FaxFbxF_alFa]lFexF\hz3Fa`v2FgnFafo4-Fbr6$F2-Feo6$w,F`jzF%6$FdwFewF%FbcsF
%F%F%6#F26$7'FaxFbxF[]w"$D"Fex7'FaxFbxF[]wF]]wFexF\hzFgjzC%>6(FixFf[pF[brF_erFc
grFjgr-Fe\m6%1FhvFct-Fido6)FhnF[brF_erFdpFd^sFghzF`io-F_^p6)FhnF[brF_erFdpF\qFd
^sFghz-Fhr6(Q8%-15g%-15g%-15g%-15g%g|+F%Fhv,&-Fdz6$Fd[lFixF2-Fdz6$FfzFixFbxFd\[
lFcgrFjgr?&F[jrF_uFgfmC'>6$Fd`vFjgr-Fj^s6*FixFf[pF[brF[jrFdpF\qFeqFd^s@$/Fd`vF@
\-Fe\y6$FgnF2>-F\hzF_fm7'FgavFjqFd^sF_rF\s-F_]w6+-F\hzFgcsFgnFhnFdpF\qFjgrF2F@F
2F%6#F\hzF%6#F264F\\l7'FaxFbxF]\lFcxF\]l7'FaxFbxFcblFdbmF\]l7'FaxFbxFj`mFianFa
\l7'FaxFbxF`an"#(*Fa\l7'FaxFbxFW"$K"Fa\lF`ds7'FaxFbxFWF^fwF_\lFgdn7'FaxFbxFj`l"
$d"Fa\l7'FaxFbxFj`lF`gpF_\lF^dt7'FaxFbxF^enF`\mFa\l7'FaxFbxF^enFganFf\l7'FaxFbx
F[[lF@Fc`n7'FaxFbxF^enF`_mF_\l7'FaxFbxF^enFailFa\l7'FaxFbxF^enFailF_\lF%,
I.templateTest1w,6-FaamFMF]cmFc`qFg[sFhil%$nE1G%#nRGFIFi[sF`\r6(F^eo%#C1G%#C2GF
d`qF_hnF^in6"F%C)>FgnFieo>Fcaq-F^`s6$w,FdyF%6$FdwFewF%1F^oFghlF%F%6$F^_[lFafo6#
F26$7'FaxFbxFi^mFhbmFexFj^mFghz@$F[asOFj_s>Fdp,&FafoF2Fh]oFbx>6$F\qFeq-Fhiq6&F^
oF^]rF`ioFh_m@$-Ffas6$0-F[bm6$F2&F\q6$,(FeqF2Fd^sFbxF_zF2F_y,&FdpF2F_zF2/F_z;F2
Fd^sOFj_sO6$7)FfrFj]o7%FdpFd^sFd^wFgbsFZFctF[izF^]pF%F%F%6#F^en6,F__oFd]pF]]l7'
FaxFbxFWFc`nFf\l7'FaxFbxFgxFd^lFe^lF\dtF_gs7'FaxFbxFWF^fwFf\l7'FaxFbxFajmF`anFe
^l7'FaxFbxFWF\[lFe^lF%,
I2templateReductionw,FhcwF^fz6"F%C&>FgnFieo>Fhn-FgbxFfu-%(treduceG6%F^oFZFhnF]d
xF%F%F%6#Fgu6'7'FaxFbxF_\lF/FexFd]pFh[vF^\lFedxF%,
I(treducew,6'F:Fb\v>FeazF2>F[bzF@>F[^wF26>F^_[lF__[lFIFc`qFg[sFbamF]cmFi[sFjgsF
hilFeetFaetFEFFF]emFi\o%#A2GF_hsF_eoF[jqF]hsFccm%#M2GF`\rFa_[l%#V2GF^_sF^eo6"F%
C->%$td1GFZ>6.FgnFhnFinFdpF\qFeqFjqF_rF\sF_uFhvFix6$&Fe]nF%&&FZ6#7%F2FguFe]vF%>
F[gx&-F\o6)F^oF_uF\sFhvF@F2Fix6#7%FWFboF^en>6$FjgrFcgr-F^`s6$w,FbcmF%6$FdwFewF%
-Fbr6$FjcmF[xF%F%6$FjgsF\s6#F26$7'FaxFbxFi^mFe[mFex7'FaxFbxFi^mFgbmFexFjq>6$Fcg
rFjgr6$-F`hl6$Fcgrw,FchlF%6$FdwFewF%-Fedp6%Fa]nF[dmF[xF%F%6$FFF[br6#Fgu6$7'FaxF
bxFadmF\anFex7'FaxFbxFadmF[_mFex-F`hl6$Fjgrw,FchlF%6$FdwFewF%F]f[lF%F%F_f[l6#Fg
u6$7'FaxFbxFc\lF^^[lFex7'FaxFbxFc\lF[alFex>Fjq7$&FcgrF%Faav>6$F[jrFcgr6$-F^am6$
-F]w6%-Fjbm6$F_erFjqFf[pF_uFeqFjq>Fd`vFb]r>F]av-Fe\m6%1F]\lFd`v-%%ceilG6#,$Fd`v
#F2F]\lF]\l-F_]w6+F_oF2F_oF_oF_o$F@F@F@F2Fj]o?(FfcvF2F2Fd`vFgfmC/>F^dv&FjqFa_y>
Fjgr-F]^q6$/F^dvF_hmFcgr>F_dv&F[jr6$-F]^q6$/-F[bm6$F^dvFcgrF_hm7#-F^t6#;F2-Fdz6
$FfzF[jrF_y>F`dv-Feo6$w,FeclF%6$FdwFewF%-F[bm6$F^oF[xF%F%6$FbamFeq6#F26$7'FaxFb
xFcilFe[mFexFijo-Fg_l6$*&&F_er6#&F^dvFcqF2&F^dvFfuF2Ff[p>F`dv-Fay6$w,FdyF%6$Fdw
FewF%-Ffcr6#&F[x6$F_yF^oF%F%6$Fec[lF_dv6#F26$7'FaxFbxF`_mF]alFexFa_mF`dv>F^ev-F
[_n6%Fbr7#-F^t6#;F2-Fdz6$F2FeqF`dv>6$F_evF_dv6$&FeqFhay&F_dv6$F_yF^ev>6$FhevF]f
v-Fe\m6%Fbt-Fj^s6*F_dvF_evFjgrFdpFf[pF[brF\qF_u-F[_[l6-F_dvF_evFjgrFdpF\qF_uFgn
FhnFinF_rF`dv@$/-Fhhn6$FfcvF]avF@-Fhr6$Q0%d%%~completed|+F%,$*&FfcvF2F]avFbxF]
\l@$5/FhevF@2,&FinF2FfrF2&&FhevFf]nFgcs\@$2F_^\lFin>FinF_^\l>6'FgnF[jrFeqFcgrFj
c[l6'&F`^\lFcqF_dvF_evFjgr7'&FhevF%F\sF_uFhvFix-F_]w6+Fjc[lF2F_erFf[pF[brF]fvF@
F@Fj]oF%6#Fjc[lF%6#Fgu6>F\\l7'FaxFbxF]\lF`_mF\]l7'FaxFbxFWF[eyFa\l7'FaxFbxFWFge
uFa\lF\^lFcdy7'FaxFbxFWF`_mFa\l7'FaxFbxFWF\[lFa\lFc_\lF^^l7'FaxFbxFWF\anF_\lFgd
nFcds7'FaxFbxFj`lFgbmFa\l7'FaxFbxFj`lF^jsFa\l7'FaxFbxFj`lFe]lFa\lFe]pFcan7'FaxF
bxFj`lF_]lFa\l7'FaxFbxFj`l"$X"Fa\l7'FaxFbxFj`lFciqFf\l7'FaxFbxFgxFdxF_\l7'FaxFb
xFj`lFdxFf\l7'FaxFbxFedmF@Fc`n7'FaxFbxFj`lF[gpFf\l7'FaxFbxF=Fd^lFa\l7'FaxFbxFj`
lFianFa\lFeeuF%,
I,iniTemplatew,Ff^t6FFDFEFFF]hnFh[sFg[sFc`qFd\vFMF]cmFjdsF]^mFhfwFi\vFeetFf\vFa
etFifw%$iiqGF]emF`\r%#U1G%"UGFbamFd`qF__[lFIFahnFahsF_z%$xEsG%&indU1G%%indUG%#C
CG%%indCGF]hs6"F%C5>60F\qFeqFjqF_rF\sF_uFhvFixFf[pF[brF_erFcgrFjgrF[jr&Fiex6#7#
-F^t6#;F2F1>FfnFjn>Fdp-F_iu6$FgnFaiu>Fhn-F[_n6%FbrFhnFjgr>Fin-Fccu6#F[^s>Fd`v-F
_fn6%-Feo6$w,Fj\uF%6$FdwFewF%-Fe\m6%-FbrFaj[lFbxF2F%F%6$FeetF_er6#F26$7'FaxFbxF
1Fe`nFex7'FaxFbxF1FcilFex7#-F^t6#;F2Fh]oF[tFcgr>6$FfcvF^dv-F]wFcbn>F_dv-F[hl6$F
^dvFin>Ffcv-F^am6%FfcvF^dvF_dv>6$8F8C-F]w6$FgnFjgr>8D-F`hl6$Fad\lw,FchlF%6$FdwF
ewF%-F\gl6%F^oFZ-Fccu6#&F[xF%F%F%6$FaetFjgr6#Fgu6$7'FaxFbxF[elF[alFex7'FaxFbxF[
elF=Fex>F`d\l-F^am6%F`d\lFad\lFed\l>8E7#-Fham6$&-F]w6&-Fg\r6$&F`d\l6$F_y8GF^pFh
nF@-Fg\r6$F_dvF^pFcq/Fcf\l;F2-Fdz6$F2Fed\l>F^dv-F]^q6$-Ffs6%&FhnF^grF[t-Fju6%F2
F[tF_g\lF_dv>F`dv&F\s6#-F[_n6%Fbr7#-F^t6#;F2-Fdz6$F2F\sFhv>6'F^evF_evFhevF]fvF
\fv6$Fc\t&&Ff[pF^bwF%>F[br7$&F[brF%-Feo6$w,F`[zF%6$FdwFewF%,&*&FfisF2F[xF2F2F^o
F2F%F%6$FIFhev6#F26$7'FaxFbxF_\lFd[mFexFb`t-F[_n6%Fbr7#-F^t6#;F2Fhev&F[brFcq>F^
gv7$-F\bl6$-Fg\r6$F[jrFi\r-Feo6$w,FdyF%6$FdwFewF%Fa[nF%F%6$FbamF`dv6#F26$7'FaxF
bxFe`nFd^lFex7'FaxFbxFe`nF\amFexFix-Fg\r6$&F\s6#;F2F]fvFi\rO67FhnFinFjqFfcvF_dv
F^dvF\s7%,&F^evF2-Fgq6#FhvFbxF_evFhevF[brF_uFhvF\qFeqF]fvF\fvF^gvFd`vFed\lFjgrF
he\lFdpF%F%F%6#F266Fh`m7'FaxFbxFWF^anFa\lFb\lF`\lF`gsF^gu7'FaxFbxFWFgjrFa\lF[]l
F`\lF[]lF`ds7'FaxFbxFWFcjrFa\lFh^sFb[xF]^pFg_qF\^lFc[]lFd]l7'FaxFbxFWFb[vFe^lF%,
I*iniColpivw,6'FMFc`qFEFF'Fi`\l-F^p6#Fi\r6+FjilF\\rFJFb`qF]\rF^\r%"PG%"RG%"EG6"
F%C+>Fgn-Fg\r6$&F^o6#;,&F[_oFbxFbxF2F%F^p>Fhn-Fjel6$-Fg\r6$F^oFi\r-F\bl6#&Fj]oF
%>Fdp-Fabq6#-Fham6$-Fay6$w,FeclF%6$FdwFewF%Fa^rF%F%6&FJFinF\\rFhn6#F26$7'FaxFbx
F]ilF]^lFex7'FaxFbxF]ilFhbmFexFhn-FbrFbbq>F\q-Fjel6$-F\bl6#-Fham6$-F_fn6%FinF[t
FdpF_^]lFdp>Feq-Fjel6$Fhn-F\blF`dn>Fjq7$&-F[hl6$7#&-Fjel6$Fdp<#F^blF%FfrF%F^bl>
F_rF[ar>F\s7%&&Fj]oFfuF%&-FjelF_]]lF%Ff`rO6$7%F\sF_rFjq7%-FgqF]uFhjmFb]rF%F%F%6
#F]_o6,7'FaxFbxF_\mF/FexF_gsF]^pFd\wFg^sF`[xF_[xF\dt7'FaxFbxFWFc]lFa\l7'FaxFbxF
WF[^lFe^lF%,
I0solverGeneratorw,FffwF^fz6"F%C&>FgnFieo>Fhn-FgbxFf]n-%*solvergenGF[dxF]dxF%F%
F%6#F26'F\doFd]pFh[vFh\wFedxF%,
I*solvergenw,6)F:>FibzF@>F\czF2>FbczF2>F_czF2>FbbzF2>FfbzF@6KFEFFFc`qF`\rFh`\lF
g`\lFMFd\vFi\vF]cmFjdsFh[sFg[sFahnFahsFi`\lFf`\lF[a\lFaetF\a\lF]hn%#pdGFh^t%#Vr
GFbam%%ptn1GFbex%"qGF_z%$iCCG%$jCCG%$CC1GFa_[lFD%%indMGFj`\l%#MMGFaam%$iT1GFd`l
%$MM1G6"F%C=>67FgnFhnFinFdpF\qFeqFjqF_rF\sF_uFhvFixFf[pF[brF_erFcgrFjgrF[jrFd`v
F]avFfcv-Fc`\lFb`l>F^dv-%&evalbG6#0-FgqF\\yF@@(5FfhuF^dv>F_dv-F\_l6$Q3../solver
s.matlab/F%F^o/F`ioFgu>F_dv-F\_l6$Q2../solvers.julia/F%F^o/F`ioFW>F_dv-F\_l6$Q6
../solvers.python/py_F%F^o@$4-F_atFg`y-&Fh_t6#%.MakeDirectoryG6$F_dv/%(recurseG
Fgfm@$Fbt@(Fdc]l-%8writeInidataCoefsMatlabG6(F^oF_dvFgnFhnFd`vFfcvFic]l-%7write
InidataCoefsJuliaG6&F^oF_dvFgnFfcvF^d]l-%8writeInidataCoefsPythonGFde]l@$3Fbjt/
FfrF@OF%>F`dv&Fjq6#-F[_n6%Fbr7#-F^t6#;F2-Fdz6$F2FjqFhv>6$F^evF_ev-Ff[]l6'F`dvFi
nFgnFhnFcgr@$F`au-Fhr6%Q@|+%a~permissible~monomials:|+%a|+|+F%&F_evFgcs&F^evFgc
s>Fhev-F_c]l6#334F^dv2&F_rFgcsF^g]l/FZF2@$Fdjt@%F^dv-%9writeTestNumPosdimMatlab
G6(F^oF_dvFixFf[pF[jrFd`v@(Ffhu-%3writeTestNumMatlabG6'F^oF_dvFixFf[pFhevFic]l-
%2writeTestNumJuliaGFah]lF^d]l-%3writeTestNumPythonGFah]l@$Fie]lOF%@$-F_iu6$F@F
jgrYQWsolver~file~cannot~be~created~for~incomplete~templatesF%>F]fv-Fdz6$F2F[jr
>Fbhv7#-Fham6$7#-Fb]m6$-Fg\r6$&F]av6#F\fvFcs%+indexorderG/F\fvFij\l>F^gv7#-Fham
6$-Feo6$w,FfcqF%6$FdwFewF%,&FjcmF2*&,&F[dmF2FbxF2F2-Fdz6$Ffz&F[xFcisF2F2F%F%6&F
\a\lF]avF_zF\fv6#F26$7'FaxFbxF`_mF]^nFexFa_m&FbhvFji]lF\j]l>Fad\l7#-Fham6$-Fg]m
6$-Fdz6$F2Fii]l<#&-Fijl6%w,FchlF%6$FdwFewF%/Fc]qFZF%F%F%6#Fgu6$7'FaxFbxF\amF\an
Fex7'FaxFbxF\amF]^lFexF_[^l&F^gvFji]lF%F\j]l>Fed\l-F\r6$*&&Fad\lFji]lF2&F[jrFji
]lF2F\j]l>Fhe\l-Fg\r6$-F_v6$Fed\lFeqF^p>6$F`d\lFcf\l-F]w6$-Fjbm6$Fhe\lF_uFd`v>F
[jr-&Fay6#%(flattenG6%FbrF[jrFcf\l@$0&F[jrFcqF2YQPsolver~file~cannot~be~created
~for~this~templateF%>F`d\l-F^am6%F`d\lFcf\lF[jr>8H7#-Fham6$&-F]w6&-Fg\r6$&F`d\l
6$F_yF\fvF^pFgnF@-Fg\r6$FjqF^pFcq/F\fv;F2F^i]l@$F^ix>Fd^^l-Feo6$w,6#FaamF%6$Fdw
FewF%&F^o6$F[xF_yF%F%6$FahsF_er6#F26$7'FaxFbxFi^mFganFexFj^mFd^^l>Fd^^l-Feo6$w,
Fh_^lF%6$FdwFewF%&F^o6$F_y-F[_n6%FbrFgfsF[xF%F%6$FjdsFhv6#F26$7'FaxFbxFcglFdxFe
xF_jsFd^^l@$Fer@'F^dv-%8writeSolverPosdimMatlabG6.F^oF_dvFdpF^fmFd^^lFixF_rF\sF
[brFjgrF[jrFd`vFhevC%>8J-Feo6$w,FeclF%6$FdwFewF%-F[bm6$Figq7$&&F\xFgcsF%&&F\xFf
uF%F%F%6&Fc`qFinFbamF^ev6#F26$7'FaxFbxFadmFcjrFex7'FaxFbxFadmF[[lFexF_g]l>8L-F^
am6%&Fd^^lFcqF`dv-F^[t6#-Feo6$FdzF^ev@(Ffhu-%8writeSolverColpivMatlabG6-F^oF_dv
FdpF^fmFfb^lFixF_evFda^lFgg]lF[brFjgrFic]l-%7writeSolverColpivJuliaG6.F^oF_dvFd
pF^fmFfb^lFixF_evFda^lFgg]lF[brFjgrFfcvF^d]l-%2writeSolverPythonG6-F^oF_dvFdpF^
fmFib^lFixF_rF\sF[brFjgrFfcv@(Ffhu-%2writeSolverMatlabG6,F^oF_dvFdpF^fmFib^lFix
F_rF\sF[brFjgrFic]l-%1writeSolverJuliaGFgc^lF^d]lFec^lF%F%F%6#F26hnFe`]l7'FaxFb
xFW"$C"Fa\lFa\oFegnFcanF[guFf[r7'FaxFbxFWF[^nFf\l7'FaxFbxFh\lFgeuF_\lFegnFddo7'
FaxFbxF^enF[alF_\l7'FaxFbxF^enFc]lF_\l7'FaxFbxF^enF^ioF_\lF`]l7'FaxFbxF]^nF@Fe^
lFg_qFg^s7'FaxFbxFW"#"*Ff\l7'FaxFbxF_\lFb_oF_\lFjfpFegnFddo7'FaxFbxF^enFajmF_\l
Fbfu7'FaxFbxFb\mFgfuF_\l7'FaxFbxFb\mF^ioF_\lF\e^lFads7'FaxFbxF=F@Fe^l7'FaxFbxFW
Fi\lFf\l7'FaxFbxF[elFebmFj\lFdjr7'FaxFbxFWFg]lFa\lFd_\l7'FaxFbxFWF]elFa\lFa\oF]
guF_[xF]^p7'FaxFbxFWF`^lFf\l7'FaxFbxFadmF`\mFj\lFh^sFb[xFf\wFg\w7'FaxFbxFWFa]lF
a\lFegnFddo7'FaxFbxF^enFjjyF_\l7'FaxFbxF^enFb_oFa\l7'FaxFbxF^enF^ioFa\lFbfu7'Fa
xFbxFb\mF^anF_\l7'FaxFbxFb\mFhdyF_\l7'FaxFbxFb\mF^^[lF_\lFbfu7'FaxFbxFb\mF`anF_
\l7'FaxFbxFb\mFhfpF_\lF[f^lF%,
I+alterCommaw,6$'%"vGF^p>'F[\xFgguQ",F%F%6"F%O-F\_l6%Q"[F%&-&F\]m6#%+Interleave
G6$F^o7#-F^t6$FZ,&Fa_nF2FbxF2F%Q"]F%F%F%F%6#Fgu6$FbglF_b[lF%,
I*printLinew,6#'%%lineGFgguF%6$FdwFewF%-Fhr6$Q.%-60swritten|+F%F^oF%F%F%6#F26$F
f[w7'FaxFbxF_\mFgxFexF%,
I2commonCode1Matlabw,6('FjcwFb`m'%#fbGFgguF`\rFaamFh[sFahn6*%#MtG%#iMG%#eMGFey%
#M0G%$M0tG%$iM0G%$eM0G6"F%C&>Fgn-Fg\r6$&Ffr6$;,&F`ioF2F2F2F%F_yFcs>Fcaq6$7#-Fb]
m6$FgnF[j]l7#-%(entriesG6%FgnF[j]lFc]m-F[ew6$F^o-F\_l6.FZQ,M~=~sparse(F%-Fj_w6#
-Feo6$w,Fj\uF%6$FdwFewF%FjcmF%F%F%6#F26$7'FaxFbxF\anF[^lFex7'FaxFbxF\anF[gpFexF
hnFef^l-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%F[dmF%F%F%6#F26$7'FaxFbxFbdtFi\lFex7'FaxF
bxFbdtF`anFexFhnQ$,C(F%-Fj_wF\cnQ#),F%&Fj]oFcqFef^l,&F[`]lF2F`ioF2Q$);|+F%@$0F`
ioF@C(>Fdpw,FfcqF%6$FdwFewF%-Fe\m6%0F^oF@-FghlFb`lF@F%F%6$F`\rFct6#F26$7'FaxFbx
F_\mF_]lFexFg[w>F\q-F_v6$-Fbjx6#-Feo6$w,FfcqF%6$FdwFewF%-F[xFb`lF%F%6$FeyFdp6#F
26$7'FaxFbxFd^lFe^lFex7'FaxFbxFd^lFedmFex&Ffr6$;F2F`ioFb^_l-Feo6$w,FfcqF%6$FdwF
ewF%Fj]_lF%F%F[^_l6#F26$7'FaxFbxFe]lFgeuFex7'FaxFbxFe]lF^jsFex&Ffr6$Fb^_lFii^l>
Feq-Fg\r6$F\qFcs>F^ap6$7#-Fb]m6$FeqF[j]l7#-Fbj^l6%FeqF[j]lFc]m-F[ew6$F^o-F\_l6/
F]awFZQ-M0~=~sparse(F%-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%FjcmF%F%F%6#F26$7'FaxFbxFa
ilF\[lFex7'FaxFbxFailFc\lFexFjqFef^l-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%F[dmF%F%F%6#
F26$7'FaxFbxFi]pFajpFex7'FaxFbxFi]pF_cwFexFjqFef^l-Fj_wFijmFef^lF`ioFef^lF[`]lF
b\_l-F[ew6$F^o-F\_l6(FZQ)M~=~M(:,F%Fji^lQ-:end)-M(:,1:F%F`ioQE)*M0;~%%~Schur~co
mplement~reduction|+F%F%F%F%6#F/6-F\c[lFa\oFd]l7'FaxFbxFW"$i"F_\lFegnFi_\l7'Fax
FbxFj`lFhfpFa\l7'FaxFbxFj`lF\]lFa\l7'FaxFbxFj`lFb_oFa\l7'FaxFbxFj`l"$m"F_\l7'Fa
xFbxFj`lFe\lF_\lF%,
I2commonCode2Matlabw,6'Fgh^lFhh^lFIFcexFf`\l6$%%iiq1G%%iiq2G6"F%C'>Fcbn-F^`s6$w
,Fj\uF%6$FdwFewF%/Fd^mF2F%F%6$Ff`\lFj]o6#F26$7'FaxFbxF=F\amFexFdgo7#-F^t6#;F2Ff
r@&32F@F^fm2F^fmFfr@%/F^fmF2-F[ew6$F^o-F\_l6*FZQ#S(F%FjhqQ),:)~=~V(F%,*FctF2Ffr
FbxFbxF2FjhqF2Q(,:)./V(F%FctQ&,:);|+F%-F[ew6$F^o-F\_l6,FZFcd_l-Fj_wF_fmFdd_l-Fj
_w6#-Fchr6%,(FctF2FfrFbxFbxF2F[tFgnQ/,:)./repmat(V(F%FctQ%,:),F%F^fmQ&,1);|+F%/
F^fmFfr-F[ew6$F^o-F\_l6,FZQ'S~=~V(F%,&FctF2FfrFbxQ":F%,&FctF2FbxF2Fbe_lFctFce_l
FfrFde_l@&32F@Fh]o2Fh]oFfr@%/Fh]oF2-F[ew6$F^o-F\_l6*FZFcd_l&FhnFcqFdd_lFctFfd_l
,*FctF2FfrFbxFbxF2Fhf_lF2Fgd_l-F[ew6$F^o-F\_l6,FZFcd_lF`bwQ0,:)~=~repmat(V(F%Fc
tFce_lFh]oQ(,1)./V(F%-Fj_w6#-Fchr6%Fae_lF[tFhnFgd_l/Fh]oFfr-F[ew6$F^o-F\_l6,FZQ
.S~=~repmat(V(F%FctFce_lFfrF_g_lF[f_lF\f_lF]f_lFgd_l-F[ew6$F^o-F\_l6$FZQ=S~=~S(
:,all(isfinite(S)));|+|+F%-F[ew6$F^oQ$endF%F%F%F%6#F]_o60F\c[lFa[xFegnFddo7'Fax
FbxF^enF\dsF_\l7'FaxFbxF^en"$^"F_\l7'FaxFbxFj`lF\dsF_\lFegnFddoFdh_lFeh_lFgh_lF
hjy7'FaxFbxFWF_\lF_\lF%,
I2writeSolverMatlabw,6,Ffgu'Fh^tFggu'F`\rFg]m'FcexF[emFegs'Fh[sFi_z'Fd\v-F^p6#F
hgs'Fi\vF`hp'FahnFhgs'Ff`\lF^p6(%%mxn0GFd`qF__[lFIFjcwFih^l6"F%C:>Fgn7#-Fdz6$F2
Fct>Fhn,&&FafoFcqF2Fd^wFbx>Fin&FafoFfu>Fdp&FafoFf]n>FeqQ%~~~~F%>F\q-Fgdw6$-F\_l
6*FZQ&/red_F%&F`ioFcqQ"xF%&F`ioFfuQ"_F%F^oF\atFidw-F[ew6$F\q-F\_l6'QH%%~Input:~
coefficient~matrix~C~of~size~F%FjhqF^[`l&FgnFfuF]aw-F[ew6$F\q-F\_l6'QF%%~Output
:~solution~matrix~S~of~size~F%FfrF^[`lFdpQ#|+|+F%-F[ew6$F\q-F\_l6)Q2function~S~
=~red_F%F][`lF^[`lF_[`lF`[`lF^oQ&(C)|+|+F%-Fdh^l6(F\qFeqFctFj]oF`ioFd^w-F[ew6$F
\q-F\_l6'F]awFeqQ4[L,|ir,P]~=~lu(M(:,1:F%FhnQ%));|+F%-F[ew6$F\q-F\_l6$FeqQ)P~=~
P';|+F%-F[ew6$F\q-F\_l6(FeqQ.M~=~[P*L~P(:,F%,&FhnF2F2F2Q,:end)]\M(:,F%Fe]`lQ(:e
nd);|+F%-F[ew6$F\q-F\_l6&FeqQ+M~=~M(end-F%,&FinF2FbxF2Q+:end,:);|+|+F%-F[ew6$F
\q-F\_l6&FeqQ,T0~=~zeros(F%FdpFb\_l-F[ew6$F\q-F\_l6(FeqQ$T0(F%-Fj_w6#&Fd^sFcqQ,
,:)~=~-M(:,F%Fh\tFg]`l-F[ew6$F\q-F\_l6&FeqFh^`l-Fj_w6#&Fd^sFfuQ()~=~1;|+F%-F[ew
6$F\q-F\_l6&FeqQ,T1~=~zeros(F%FdpFb\_l-F[ew6$F\q-F\_l6*FeqQ$T1(F%Fi^`lFef^lFi^`
lQ+)~=~M(:,1:F%FinFb\_l-F[ew6$F\q-F\_l6&FeqF^``l-Fj_w6#&Fd^sFf]nQ))~=~1;|+|+F%-
F[ew6$F\q-F\_l6$FeqQ5[V,|ir]~=~eig(T0,T1);|+F%-Fcb_l6'F\qFeqFdpFfrF[iz-FiewFhq-
Fhg^l6#-F\_l6)Q%red_F%F][`lF^[`lF_[`lF`[`lF^oF\atF%F%F%6#F]\l6;F\c[l7'FaxFbxFcb
lFi^mF\]l7'FaxFbxFgbmFa\lFa\l7'FaxFbxFf\lFc]lFa\l7'FaxFbxF[^lFajmFa\l7'FaxFbxFj
dnF`anFa\l7'FaxFbxFWF`\mFa\l7'FaxFbxFWF`anF_\l7'FaxFbxFWFj`mF_\l7'FaxFbxFWFb_oF
_\lFgjy7'FaxFbxFWFailF_\l7'FaxFbxFWFhbmF_\l7'FaxFbxFWFeiqF_\l7'FaxFbxFWFgfuF_\l
F]`qF^b`lFdjyF]`qFa^[l7'FaxFbxFWF_alF_\l7'FaxFbxFWF]^lF_\lFgjyFcfwFdb`lF%,
I8writeSolverPosdimMatlabw,6.FfguF\i_lF]i_lF^i_l'Feb]l-F^p6#Fg]mF_i_lF`i_lFci_l
Fdi_lFei_l'F[a\lFbv'FaetF^p6.Fgi_lFd`qF__[lFIFjcwFih^l%$fb2GF]hsF[i^lF\i^lF]i^l
F`b]l6"F%CM>FgnF[j_l>FhnF_j_l>FinFbj_l>FdpFdj_l>FeqFfj_l>Fjq-F\_l6$FeqFeq>Fix-F
dz6$F2Fghz>F\q-Fgdw6$-F\_l6*FZQ'/red1_F%F][`lF^[`lF_[`lF`[`lF^oF\atFidw-F[ew6$F
\q-F\_l6)Q<%%~Input:~cell~array~CC~of~F%FixQ?~coefficient~matrices~of~size~F%Fj
hqF^[`lFf[`lF]aw-F[ew6$F\q-F\_l6)QU%%~Output:~cell~arrays~TT0~and~TT1,~each~con
taining~F%FixQ3~matrices~of~size~F%FdpF^[`lFdpF\\`l-F[ew6$F\q-F\_l6)Q;function~
[TT0,TT1]~=~red1_F%F][`lF^[`lF_[`lF`[`lF^oQ'(CC)|+|+F%-F[ew6$F\q-F\_l6&FeqQ.MM~
=~cell([1,F%FixQ%]);|+F%?(F_rF2F2FixFgfmC%>F\s-Fg\r6$&&Fj]oFijm6$;,&Fd^wF2F2F2F
%F_yFcs>F[[p6$7#-Fb]m6$F\sF[j]l7#-Fbj^l6%F\sF[j]lFc]m-F[ew6$F\q-F\_l62FeqQ$MM|f
rF%F_rQ,|hr~=~sparse(F%-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%FjcmF%F%F%6#F26$7'FaxFbxF
gjrFcjrFex7'FaxFbxFgjrFciqFexF_uFef^l-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%F[dmF%F%F%6
#F26$7'FaxFbxF_cwFgbwFex7'FaxFbxF_cwFjjyFexF_uQ%,CC|frF%F_rQ#|hr(F%-Fj_wF_[]lF_
\_lF][`lFef^l,&F_[`lF2Fd^wF2Fb\_l@$0Fd^wF@F%-F[ew6$F\q-F\_l6/F]awFeqQ=TT0~=~mat
2cell(repmat(zeros(F%FdpQ%),1,F%FixF_\_lFdpQ),repmat(F%FdpQ$,1,F%FixFj\`l-F[ew6
$F\q-F\_l6.FeqQ=TT1~=~mat2cell(repmat(zeros(F%FdpFbi`lFixF_\_lFdpFci`lFdpFdi`lF
ixFj\`l-F[ew6$F\q-F\_l6&FeqQ(TT0|fr1|hr(F%Fa_`lFd_`l-F[ew6$F\q-F\_l6&FeqQ(TT1|f
r1|hr(F%Fd``lFd_`l-F[ew6$F\q-F\_l6&FeqQ8[L,|ir,P]~=~lu(MM|fr1|hr(:,1:F%FhnFj\`l
F[]`l-F[ew6$F\q-F\_l6&FeqQ.P~=~[P*L~P(:,F%Fe]`lQ):end)];|+F%-F[ew6$F\q-F\_l6&Fe
qQ+for~i~=~1:F%FixF]aw-F[ew6$F\q-F\_l6&FjqQ/M~=~P\MM|fri|hr(:,F%Fe]`lFg]`l-F[ew
6$F\q-F\_l6&FjqF\^`lF]^`lQ*:end,:);|+F%-F[ew6$F\q-F\_l6(FjqQ(TT0|fri|hr(F%Fi^`l
F\_`lFh\tFg]`l-F[ew6$F\q-F\_l6*FjqQ(TT1|fri|hr(F%Fi^`lFef^lFi^`lF_``lFinFb\_l-F
[ew6$F\q-F\_l6$FeqQ&end|+|+F%-F[ew6$F\qFah_lF_a`l-Fhg^l6#-F\_l6)Q&red1_F%F][`lF
^[`lF_[`lF`[`lF^oF\at>F\q-Fgdw6$-F\_l6*FZQ'/red2_F%F][`lF^[`lF_[`lF`[`lF^oF\atF
idw-F[ew6$F\q-F\_l6(QD%%~Input:~cell~arrays~TT0~and~TT1,~F%-Fe\m6%/-Fgq6#9/F2Q'
value~F%Q(values~F%Q)of~free~F%-Fe\m6%Fa^alQ*variable~F%Q+variables~F%&-Fg\r6$F
d^alFgguFaewF]awFg[`l-F[ew6$F\q-F\_l6+Q3function~S~=~red2_F%F][`lF^[`lF_[`lF`[`
lF^oQ*(TT0,TT1,F%&-Fj_wFc^alFaewQ$)|+|+F%-F[ew6$F\q-F\_l6$FeqQ,T0~=~TT0|fr1|hrF
%?(F_rFguF2FixFgfm-F[ew6$F\q-F\_l6&Q&+TT0|frF%F_rQ#|hr*F%&FghzFijm-F[ew6$F\q-F
\_l6%Q#;|+F%FeqQ,T1~=~TT1|fr1|hrF%?(F_rFguF2FixFgfm-F[ew6$F\q-F\_l6&Q&+TT1|frF%
F_rFc`alFd`al-F[ew6$F\qQ$;|+|+F%Fh``lF]a`lF_a`l-Fhg^l6#-F\_l6)Q&red2_F%F][`lF^[
`lF_[`lF`[`lF^oF\atF%F%F%6#F_\m6T7'FaxFbxFi^mF/FexFga`lFha`lFia`lFja`lF[b`l7'Fa
xFbxF`gp"$4"Fa\l7'FaxFbxF_ez"$U"Fa\lF`\w7'FaxFbxFWF`epF_\l7'FaxFbxFW"$A"F_\l7'F
axFbxFWF`gpF_\lFcjyFgdnF[gu7'FaxFbxFj`lFjdnFa\lF^eyFegn7'F@F@F@F@F\]l7'FaxFbxFW
"$B"F_\l7'FaxFbxFWF[]wF_\lF`b`lF`b`lFdb`lFab`lFcb`l7'FaxFbxFWFf\lF_\lFdjy7'FaxF
bxFWF^ioF_\l7'FaxFbxFWF`^lF_\l7'FaxFbxFWFe\lF_\l7'FaxFbxFWF_]lF_\lFhh_lFcfw7'Fa
xFbxFWFgglF_\lF`\w7'FaxFbxFW"$5#F_\lF^b`lFabal7'FaxFbxFWFganF_\lFgdn7'FaxFbxFj`
lF]alF_\l7'FaxFbxFWFe[mF_\lFgdnFbcal7'FaxFbxFWFadmF_\lFeb`lFgjyFcfwF^calF%,
I8writeSolverColpivMatlabw,6-FfguF\i_lF]i_lF^i_lFegsF_i_lF`i_l'Fi\vF^pFIFdi_lFe
i_l6(Fgi_lFd`qF__[l%#nPGFjcwFih^l6"F%C;>FgnF[j_l>Fhn,&F`j_lF2F[izFbx>FinFbj_l>F
dp&FafoFgcs>FeqFfj_l>F\q-Fgdw6$-F\_l6+FZF[btFda`lF][`lF^[`lF_[`lQ)_colpiv_F%F^o
F\atFidwFa[`l-F[ew6$F\q-F\_l6'F[\`lFfrF^[`lFd^wF\\`l-F[ew6$F\q-F\_l6)Fa\`lF][`l
F^[`lF_[`lFidalF^oFb\`l-Fdh^l6(F\qFeqFctFj]oF`ioF[iz@%0FhnF@C&Fe\`lF[]`lF`]`l-F
[ew6$F\q-F\_l6&FeqQ,M~=~full(M(F%Fe]`lQ+:end,:));|+F%-F[ew6$F\q-F\_l6%F]awFeqQ.
M~=~full(M);|+F%@$0FinF@C%-F[ew6$F\q-F\_l6'F]awFeqQ4[L,U,P]~=~lu(M(:,1:F%FinFj
\`lF[]`l-F[ew6$F\q-F\_l6(FeqFd]`lFh\tFf]`lFh\tFg]`l-F[ew6$F\q-F\_l6&FeqQ*M1~=~M
(1:F%FinFgd_l-F[ew6$F\q-F\_l6&FeqQ(M2~=~M(F%Fh\tF^^`l-F[ew6$F\q-F\_l6&FeqQ9[Q,R
,P]~=~qr(M2(:,1:end-F%,&FfrF2F2F2Fj\`l-F[ew6$F\q-F\_l6(FeqQ3A~=~U\[M1(:,1:end-F
%F]halQ.)*P~M1(:,end-F%FfrF^[al-F[ew6$F\q-F\_l6*FeqQ+B~=~R(:,1:F%,(F][`lF2FhnFb
xFinFbxQ()\[R(:,F%,*F][`lF2FhnFbxFinFbxF2F2Q3:end)~Q'*M2(:,end-F%FfrF^[al-F[ew6
$F\q-F\_l6(FeqQ/M~=~[-A(:,end-F%,&Fd^wF2FbxF2Q1:end)+A(:,1:end-F%Fd^wQ,)*B;~-B]
;|+|+F%-F[ew6$F\q-F\_l6.FeqQ'P1~=~[F%,&FdpF2F2F2F\f_l,&FdpF2FinF2Q%~(1:F%,(FdpF
2FfrFbxFbxF2Q%)*P~F%,&FdpF2FfrFbxF\f_lFdpQ$];|+F%-F[ew6$F\q-F\_l6&FeqQ&P2~=~F%-
Fj_wFbftFi`al-F[ew6$F\q-F\_l6(FeqQ5T~=~getT(M,P1(1:end-F%Fd^wQ*),P1(end-F%Fbial
Q-:end),P2);|+|+F%-F[ew6$F\q-F\_l6$FeqQ1[V,|ir]~=~eig(T);|+F%-Fcb_l6'F\qFeqFd^w
FfrFghzF_a`l-Fhg^l6#-F\_l6)Fda`lF][`lF^[`lF_[`lFidalF^oF\atF%F%F%6#F^en6DF[balF
ga`lFha`lFia`lFja`lF[b`l7'FaxFbxFWFbdtFa\lF]b`lF^b`l7'FaxFbxFWF[^nF_\lFgjyFegn7
'FaxFbxFj`lFg]lF_\l7'FaxFbxFj`lFe`nF_\l7'FaxFbxFj`lF]elF_\lFeeu7'FaxFbxFj`lFj\l
F_\lFegnF]\blF^\blF_\blFedx7'FaxFbxFWF[gpF_\l7'FaxFbxFWFa]lF_\l7'FaxFbxFWFebmF_
\lFhbalF\\bl7'FaxFbxFWF]cwF_\l7'FaxFbxFWFc`nF_\lF\\bl7'FaxFbxFWFa\lF_\lFgjyFcfw
7'FaxFbxFWFciqF_\lF%,
I8writeInidataCoefsMatlabw,6(FfguF\i_lFEFFFaetF]hn6<F\_t%#_CG%#_VG%&_nameG%&_si
zeGFDF`\rFg`\lFh`\l%#UlG%$dUlGF]a\lFj`\lF[a\lF`b]lF\a\lFjcwF_z%#AsG%#CsG%#ClG%"
eG%#esG%$idxGF]hsFih^l6"F%CF>F_evFfj_l>Fgn&F]huFf]n@$4-F[p6$FgnFhjtC$-Fibo6#Q[o
inidata~and~coefficient~files~cannot~be~created~for~this~problemF%OF%AF[[u>6&Fh
nFinFdpF\q-FgnF%AFd[u>Feq-Fg\r6$-F_v6$&FhnFgcsFinF^p>F^ap-F]w6$FeqFct>F\s-F[hl6
$F_rFfr>F_u-Fg\r6$F\sF^p>Fhv-Feo6$w,FbwF%6$FdwFewF%-Fj_w6#-Feo6$w,FeclF%6$FdwFe
wF%-%%diffGFjbqF%F%6$FKF^o6#F26$7'FaxFbxF_]lFedmFexF]]pF[xF%F%6$F`]blF_u6#F26$7
'FaxFbxF1Fc`nFexFgcpFct>Fjq-F^am6%FjqF_rF\s>6$FixFf[p-F]w6$FeqFj]o>F[br-F`hl6$F
f[pw,FchlF%6$FdwFewF%-F\gl6%F^oFZ-Fccu6#&FghlF%F%F%6$FaetFj]o6#FguFae\l>Fix-F^a
m6%FixFf[pF[br>F_er-Fdz6$F2F[br>Fcgr7#-Fham6$&-F]w6&-Fg\r6$&FixFh\\lF^pFctF@Fh_
blFcq/F^ev;F2F_er>Fjgr-Fgdw6$-F\_l6&FZQ./inidata_num_F%F^oF\atFidw-F[ew6$Fjgr-F
\_l6%Q=function~data~=~inidata_num_F%F^oQ%()|+|+F%-F[ew6$Fjgr-F\_l6&F_evQ0data~
=~cell([1,F%FfqFje`l?(F[jrF2F2FfqFgfm@%/&F\qFjewFfz-F[ew6$Fjgr-F\_l6&F_evQ&data
|frF%F[jrQ,|hr~=~randn;|+F%-F[ew6$Fjgr-F\_l6(F_evF]eblF[jrQ+|hr~=~randn(F%&-Fj_
w6#FhdblFaewFb\_l-F[ew6$FjgrQ%|+endF%-FiewFc[y-Fhg^l6#-F\_l6%Q-inidata_num_F%F^
oF\at>Fjgr-Fgdw6$-F\_l6&FZQ(/coefs_F%F^oF\atFidw-F[ew6$Fjgr-F\_l6%Q;function~[C
,U,dU]~=~coefs_F%F^oQ)(data)|+|+F%?(F[jrF2F2FbcnFgfm-F[ew6$Fjgr-F\_l6'F_evF\ixQ
)~=~data|frF%F[jrQ$|hr;|+F%-F[ew6$FjgrF]aw@%/F_erF2?(F[jrF2F2Fh]oFgfmC&@$/F[jrF
guC$>Fd`v-Fg\r6$&-F\er6%FdzF@-Fay6%F[p-Fg\r6$&FhnFfuFi\r%)functionGFcqFggu-F[ew
6$Fjgr-F\_l6*F]awF_evFd`vQ*~=~C(:,1:F%-Fdz6$FfzFhf_lQ')\C(:,F%,&F]iblF2F2F2Q):e
nd);|+|+F%-F[ew6$Fjgr-F\_l6(F_evQ+C~=~zeros(F%-Fdz6$Ffz&FhnFjewFef^l-Fdz6$Fd[lF
iiblQ%);|+|+F%>6$F]avFfcv6$-Fjel6$-Fg\r6$FiiblFi\r<#F@-Fg\r6$FiiblF^p?&F^dvF]av
FgfmC%>F`dv7#-Fb\u6$F^dvFfcv>F_dv-Fe\m6%F`io-&%,StringToolsG6#%.SubstituteAllG6
%-Fg\r6$F^dvFgguQ"IF%Q#1iF%Ff[cl-F[ew6$Fjgr-F\_l6(F_evQ#C(F%-Fe\m6%/-FgqF[evF2&
F`dvFcq-Fj_wF[evQ%)~=~F%F_dvFi`alC$-F[ew6$Fjgr-F\_l6(F_evFfibl-Fdz6$FfzFjqFef^l
*&-Fdz6$Fd[lFjqF2F_erF2Fb\_l?(F^evF2F2F_erFgfmC$>F^jbl6$-Fjel6$-Fg\r6$&FcgrFhay
Fi\rFdjbl-Fg\r6$Fh]clF^p?&F^dvF]avFgfmC%>F`dv-Feo6$w,Fj\uF%6$FdwFewF%,&F^oF2*(F
czF2-Fdz6$Fd[lF[xF2,&F\xF2FbxF2F2F2F%F%6&F`\rFjqF]hsF^ev6#F26$7'FaxFbxFi^mFjglF
exFj^mFjjbl>F_dvF^[clFj[cl-F[ew6$Fjgr-F\_l6%F]awF_evQUC~=~C./repmat(sqrt(sum(C.
*conj(C),2)),1,size(C,2));|+F%@$0F_erF2-F[ew6$Fjgr-F\_l6*F_evQ0C~=~mat2cell(C,F
%F[]clFci`lF^]clFdi`lF_erFj\`l-F[ew6$Fjgr-F\_l6)F]awF_evQ'U~=~@(F%&-Fj_wF^flFae
wQ")F%-Fj_wFhbuFi`al-F[ew6$Fjgr-F\_l6(F_evQ(dU~=~@(F%F]`clF_`cl-Fj_w6$FhvQ";F%F
caal-F[ew6$FjgrFah_lFjebl-Fhg^l6#-F\_l6%Q'coefs_F%F^oF\atF%F%F%6#F/6inF[bal7'Fa
xFbxFad^l"$O"Fa\lFa\wFegnFg[rFjbw7'FaxFbxFWF\]lFd^lF`gs7'FaxFbxFWF[elFd^lF[]lF[
]lF`\lF\dt7'FaxFbxFWFjglFa\lF[]lF`dsFd[]lFh^sFdjr7'FaxFbxFWFid^lFa\l7'FaxFbxFWF
[^lFa\lF\[z7'FaxFbxFWFgjrF_\lFgdnFddo7'FaxFbxF^enFgfuF_\l7'FaxFbxF^enFb^lF_\lFd
calFcfwFccalFe\w7'FaxFbxFWFg]lF_\lFgdn7'FaxFbxFj`lF[^lF_\l7'FaxFbxFWF`_mF_\lFeg
nF^dtFbfu7'FaxFbxFb\mFhfpFa\l7'FaxFbxFb\mF]]wF_\l7'FaxFbxF^enF[eyF_\l7'FaxFbxF^
enFajmFa\l7'FaxFbxF^enFcilFd_l7'FaxFbxFb\mFj\lFa\l7'FaxFbxFb\mFaezFa\l7'FaxFbxF
b\mF\ezF_\lF_\blF^dtFbbclFcbcl7'FaxFbxFb\mFb^lFa\lFebclFfbclFc\bl7'FaxFbxFWFbba
lFf\l7'FaxFbxFcilFcezF_\l7'FaxFbxFWFid^lF_\l7'FaxFbxFWFb^lF_\lFhh_lFcfw7'FaxFbx
FWFh\lF_\lF%,
I3writeTestNumMatlabw,6'FfguF\i_lF_i_l'Fg[sF[em'Fbex%(booleanG6$FjcwFih^l6"F%C4
>FhnFfj_l>Fgn-Fgdw6$-F\_l6&FZQ+/test_num_F%F^oF\atFidw-F[ew6$FgnQ*rng(23);|+F%-
F[ew6$FgnQ,N~=~10000;|+F%-F[ew6$Fgn-F\_l6%Q%d~=~F%FfrFcaal-F[ew6$Fgn-F\_l6%Q4st
ats~=~ini_stats('F%F^oQ&');|+|+F%-F[ew6$FgnQ.for~i~=~1:N|+|+F%-F[ew6$Fgn-F\_l6&
FhnQ4data~=~inidata_num_F%F^oQ%();|+F%-F[ew6$Fgn-F\_l6&FhnQ2[C,U,dU]~=~coefs_F%
F^oQ*(data);|+|+F%-F[ew6$Fgn-F\_l6$FhnQ&tic;|+F%-F[ew6$Fgn-F\_l6*FhnQ)S~=~red_F
%&FctFcqF^[`l&FctFfu-Fe\m6%Fj]oFidalF`[`lF^oQ&(C);|+F%-F[ew6$Fgn-F\_l6$FhnQ<sta
ts.tm~=~[stats.tm~toc];|+F%-F[ew6$Fgn-F\_l6$FhnQ?if~isempty(S);~continue;~end|+
|+F%-F[ew6$Fgn-F\_l6$FhnQZ[stats,|ir]~=~update_stats(stats,S,C,U,dU,d,'iterRef'
,0);|+|+F%-F[ew6$FgnF\]al-F[ew6$FgnQMdisp_stats(stats,'plotHist',1,'saveHist',1
);F%-FiewF_fm-Fhg^l6#-F\_l6%Q*test_num_F%F^oF\atF%F%F%6#F]_o657'FaxFbxFe_lF/Fex
7'FaxFbxFcglF[[lFa\lFf`]l7'FaxFbxFWFgxF_\l7'FaxFbxFWFgbmF_\lFgjyFcb`l7'FaxFbxFW
F]ilF_\lFdjyF`b`lF\iclFa^[lFe\blFcb`lFc\bl7'FaxFbxFWFcxF_\l7'FaxFbxFWFjglF_\lFc
fwFgjyF%,
I9writeTestNumPosdimMatlabw,6(FfguF\i_lF_i_lF`cclF\c`lF]c`l6&FjcwFih^lF]hsFK6"F
%C9>FhnFfj_l>FgnFhcclF]dclF`dclFcdclFhdclF^eclFaecl-F[ew6$Fgn-F\_l6&FhnQ3[CC,U,
dU]~=~coefs_F%F^oQ)(data);|+F%-F[ew6$Fgn-F\_l6*FhnQ2[TT0,TT1]~=~red1_F%FgfclF^[
`lFhfclF`[`lF^oQ((CC);|+|+F%F]fcl?&FdpF`ioFgfm-F[ew6$Fgn-F\_l6%FhnFdpQ+~=~randn
;|+F%-F[ew6$Fgn-F\_l6,FhnQ*S~=~red2_F%FgfclF^[`lFhfclF`[`lF^oFd_al&-Fj_w6#F`ioF
aewFb\_lF\gclFagcl-F[ew6$Fgn-F\_l6$FhnQ*C~=~CC|fr1|hrF%?(FinFguF2-Fdz6$F2Fj]oFg
fm-F[ew6$Fgn-F\_l6&Q%+CC|frF%FinFc`al&Fj]oF\cn-F[ew6$FgnFi`alFfgclF[hclF]hclF`h
clFahclF%F%F%6#F/6<7'FaxFbxFgxF/FexFihclFf`]lFjhclF[iclFgjyFcb`lF\iclFdjyF^cal7
'FaxFbxFWFbdtF_\lF\iclFgdnFiez7'FaxFbxFWF^gpF_\lFe\blFcb`lFab`lFgdn7'FaxFbxFj`l
FedmF_\lFhh_lFc\blF]iclF^iclFcfwFgjyF%,
I1commonCode1Juliaw,Ffh^lFjh^l6"F%C'>FgnFei^l>FcaqF\j^l-F[ew6$F^o-F\_l6.FZFhj^l
-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%FjcmF%F%F%6#F2F`[_lFhnFef^l-Fj_w6#-Feo6$w,Fj\uF%
6$FdwFewF%F[dmF%F%F%6#F2Fj[_lFhnQ$,C[F%F^\_lQ#],F%F`\_lFef^lFa\_lQ#)|+F%@$Fd\_l
C(>Fdpw,FfcqF%6$FdwFewF%Fi\_lF%F%F]]_l6#F2F_]_l>F\q-F_v6$-Fbjx6#-Feo6$w,FfcqF%6
$FdwFewF%Fj]_lF%F%F[^_l6#F2F]^_lF`^_l-Feo6$w,FfcqF%6$FdwFewF%Fj]_lF%F%F[^_l6#F2
Fh^_lF[__l>FeqF^__l>F^apFa__l-F[ew6$F^o-F\_l6/F]awFZF\`_l-Fj_w6#-Feo6$w,Fj\uF%6
$FdwFewF%FjcmF%F%F%6#F2Fd`_lFjqFef^l-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%F[dmF%F%F%6#
F2F^a_lFjqFef^lFaa_lFef^lF`ioFef^lF[`]lFa^dl-F[ew6$F^o-F\_l6(FZQ)M~=~M[:,F%Fji^
lQ-:end]-M[:,1:F%F`ioQC]*M0~#~Schur~complement~reduction|+F%-F[ew6$F^o-F\_l6$FZ
Q/M~=~Matrix(M)|+F%F%F%F%6#F/6.7'FaxFbxF`_mF/FexFa\oFd]l7'FaxFbxFW"$h"F_\lFegnF
i_\lF]b_lF^b_lF_b_l7'FaxFbxFj`l"$l"F_\lFgh_lFgjyF%,
I1commonCode2Juliaw,Feb_lFfb_l6"F%C(>Fcbn-F^`s6$w,Fj\uF%6$FdwFewF%F`c_lF%F%Fac_
l6#F2Fcc_lFec_l@&Fjc_lC$-F[ew6$F^o-F\_l6(FZQ>S~=~Matrix|frComplexF64|hr(undef,F
%FfrFef^lFctFa^dl@%F^d_l-F[ew6$F^o-F\_l6*FZQ#S[F%FjhqQ),:]~=~V[F%Fed_lQ(,:]./V[
F%FctQ%,:]|+F%-F[ew6$F^o-F\_l6.FZFdcdlF\e_lFecdlF]e_lQ/,:]./repeat(V[F%FctF\f_l
FctQ%,:],F%F^fmFa^dlFee_l-F[ew6$F^o-F\_l6.FZQ'S~=~V[F%F[f_lF\f_lF]f_lF\ddlFctF
\f_lFctF]ddlFfrFa^dl@&F_f_l@%Fcf_l-F[ew6$F^o-F\_l6*FZFdcdlFhf_lFecdlFctFfcdlFif
_lFgcdl-F[ew6$F^o-F\_l6.FZFdcdlF`bwQ0,:]~=~repeat(V[F%FctF\f_lFctF]ddlFh]oQ&)./
V[F%F`g_lFgcdlFdg_l-F[ew6$F^o-F\_l6.FZQ.S~=~repeat(V[F%FctF\f_lFctF]ddlFfrF^edl
F[f_lF\f_lF]f_lFgcdl-F[ew6$F^o-F\_l6$FZQfnS~=~S[:,vec(all(c~->~!isinf(c)~&&~!is
nan(c),~S;~dims=1))]|+|+F%-F[ew6$F^o-F\_l6$FZQ+return~S|+|+F%F_h_lF%F%F%6#F]_o6
2FiadlFa[xFegn7'FaxFbxFj`lFgeuF_\lFddo7'FaxFbxF^enFi]pF_\l7'FaxFbxF^en"$e"F_\l7
'FaxFbxFj`lFgbwF_\lFegnFddoFafdlFbfdlFdfdl7'FaxFbxFWFianF_\lF\cclFhh_lF%,
I1writeSolverJuliaw,6-FfguF\i_lF]i_lF^i_lFegsF_i_lF`i_lFci_lFdi_lFei_lF]hnFfi_l
6"F%C:>FgnF[j_l>FhnF_j_l>FinFbj_l>FdpFdj_l>FeqFfj_l>F\q-Fgdw6$-F\_l6*FZF\[`lF][
`lF^[`lF_[`lF`[`lF^oQ$.jlF%Fidw-F[ew6$F\q-F\_l6'QG#~Input:~coefficient~matrix~C
~of~size~F%FjhqF^[`lFf[`lF]aw-F[ew6$F\q-F\_l6'QE#~Output:~solution~matrix~S~of~
size~F%FfrF^[`lFdpF\\`l-F[ew6$F\q-F\_l6)Q.function~red_F%F][`lF^[`lF_[`lF`[`lF^
oQ6(C::Array|frFloat64|hr)|+|+F%-Fg\dlFd\`l-F[ew6$F\q-F\_l6'F]awFeqQ2L,_,p~=~lu
(M[:,1:F%FhnQ$])|+F%-F[ew6$F\q-F\_l6(FeqQ8Id~=~Matrix|frFloat64|hr(I,F%F][`lFef
^lF][`lFa^dl-F[ew6$F\q-F\_l6(FeqQ-M~=~[L~Id[:,F%Fe]`lQ::end]][invperm(p),:]\M[:
,F%Fe]`lQ':end]|+F%-F[ew6$F\q-F\_l6&FeqQ+M~=~M[end-F%F]^`lQ*:end,:]|+|+F%-F[ew6
$F\q-F\_l6)FeqFc^`l-Fe\m6%FghzQ,ComplexF64,F%FaxFdpFef^lFdpFa^dl-F[ew6$F\q-F\_l
6(FeqQ$T0[F%Fi^`lQ,,:]~=~-M[:,F%Fh\tFhidl-F[ew6$F\q-F\_l6&FeqFjjdlFa_`lQ(]~.=~1
|+F%-F[ew6$F\q-F\_l6)FeqFi_`lFcjdlFdpFef^lFdpFa^dl-F[ew6$F\q-F\_l6*FeqQ$T1[F%Fi
^`lFef^lFi^`lQ+]~=~M[:,1:F%FinQ#]|+F%-F[ew6$F\q-F\_l6&FeqFi[elFd``lQ)]~.=~1|+|+
F%-F[ew6$F\q-F\_l6$FeqQ4_,V~=~eigen(T0,T1)|+F%-F^bdlF^a`lF_a`l-Fhg^l6#-F\_l6)Fd
a`lF][`lF^[`lF_[`lF`[`lF^oFegdlF%F%F%6#F^en6;FiadlFga`lFha`lFia`lFja`lF[b`lF`\w
F\\bl7'FaxFbxFWFgeuF_\l7'FaxFbxFWFi\lF_\l7'FaxFbxFWFeglF_\lF^icl7'FaxFbxFWF`\mF
_\lFjbclFjbalFjbclF]]elFdjyFjbcl7'FaxFbxFWF^^[lF_\lFdb`l7'FaxFbxFWFd^lF_\lF_]el
FcfwF^calF%,
I7writeSolverColpivJuliaw,6.FfguF\i_lF]i_lF^i_lFegsF_i_lF`i_lFhcalFIFdi_lFei_lF
]hnFical6"F%C;>FgnF[j_l>FhnF_dal>FinFbj_l>FdpFbdal>FeqFfj_l>F\q-Fgdw6$-F\_l6+FZ
F[btFda`lF][`lF^[`lF_[`lFidalF^oFegdlFidwFfgdl-F[ew6$F\q-F\_l6'F_hdlFfrF^[`lFd^
wF\\`l-F[ew6$F\q-F\_l6)FdhdlF][`lF^[`lF_[`lFidalF^oFehdl-Fg\dlFceal@$FeealC&Fgh
dlF]idlFbidl-F[ew6$F\q-F\_l6&FeqQ'M~=~M[F%Fe]`lQ):end,:]|+F%@$FcfalC%-F[ew6$F\q
-F\_l6'F]awFeqQ2L,U,p~=~lu(M[:,1:F%FinF\idl-F[ew6$F\q-F\_l6(FeqFaidl,&F][`lF2Fh
nFbxFef^lF^`elFa^dl-F[ew6$F\q-F\_l6(FeqFfidlFh\tFgidlFh\tFhidl-F[ew6$F\q-F\_l6&
FeqQ*M1~=~M[1:F%FinFgcdl-F[ew6$F\q-F\_l6&FeqQ(M2~=~M[F%Fh\tF^jdl-F[ew6$F\q-F\_l
6&FeqQ7Q,R,p~=~qr(M2[:,1:end-F%F]halQ1],ColumnNorm())|+F%-F[ew6$F\q-F\_l6&FeqQ9
A~=~U\[M1[:,p]~M1[:,end-F%FfrQ(:end]]|+F%-F[ew6$F\q-F\_l6*FeqQ+B~=~R[:,1:F%Fiha
lQ(]\[R[:,F%F[ialQ=:end]~transpose(Q)*M2[:,end-F%FfrFhael-F[ew6$F\q-F\_l6(FeqQ/
M~=~[-A[:,end-F%FbialQ1:end]+A[:,1:end-F%Fd^wQ+]*B;~-B]|+|+F%-F[ew6$F\q-F\_l6,F
eqQ3P1~=~Vector|frInt|hr([F%FjialF\f_lF[jalQ&;~p;~F%F_jalF\f_lFdpF\idl-F[ew6$F
\q-F\_l6&FeqQ2P2~=~Vector|frInt|hr(F%FfjalFa^dl-F[ew6$F\q-F\_l6(FeqQ5T~=~getT(M
,P1[1:end-F%Fd^wQ*],P1[end-F%FbialQ,:end],P2)|+|+F%-F[ew6$F\q-F\_l6$FeqQ0_,V~=~
eigen(T)|+F%-F^bdlFd[blF_a`l-Fhg^l6#-F\_l6)Fda`lF][`lF^[`lF_[`lFidalF^oFegdlF%F
%F%6#F_\m6C7'FaxFbxF[[lF/FexFga`lFha`lFia`lFja`lF[b`lF]dtF\\blF]]el7'FaxFbxFWF
\dsF_\lF_]elFegn7'FaxFbxFj`lFa]lF_\lFg[r7'FaxFbxFj`lF[eyF_\l7'FaxFbxFj`lF[gpF_
\lFegnFgdelFbcwFhdel7'FaxFbxFWFedmF_\lFe\bl7'FaxFbxFWFd_oF_\lFiacl7'FaxFbxFW"$E
"F_\lFd\dl7'FaxFbxFWF[eyF_\lF\[zFd\dl7'FaxFbxFWFi]lF_\lF_]elFcfw7'FaxFbxFWF\[lF
_\lF%,
I7writeInidataCoefsJuliaw,6&FfguF\i_lFEF]hn65F\_tF\]blF]]blF^]blF_]blF`]blFa]bl
FjcwF_zFb]bl%#rsGF]hsFigmFc]blFd]blFe]blFg]blFf]blFih^l6"F%C=>Fd`vFfj_l>FgnF\^b
l@$F^^blC$Fb^blOF%AF[[u>Fh^blFi^blAFd[u>Feq-Fg\r6$FinF^p>Fjq-Feo6$w,FbwF%6$FdwF
ewF%-Fj_w6#-Feo6$w,FeclF%6$FdwFewF%Fe`blF%F%Fg`bl6#F2Fi`blF[xF%F%6$F`]blFeq6#F2
F]ablFct>F_r-Fgdw6$-F\_l6&FZFicblF^oFegdlFidw-F[ew6$F_r-F\_l6%Q6function~inidat
a_num_F%F^oF_dbl-F[ew6$F_r-F\_l6$Fd`vQBdata~=~Vector|frMatrix|frFloat64|hr|hr()
|+F%?(F\sF2F2FfqFgfm-F[ew6$F_r-F\_l6&Fd`vQ2push!(data,randn(F%&-Fj_w6#&F\qF]uFa
ewQ$))|+F%-F[ew6$F_r-F\_l6$Fd`vQ.return~data|+|+F%-F[ew6$F_rFah_l-FiewFijm-Fhg^
l6#-F\_l6%F_fblF^oFegdl>F_r-Fgdw6$-F\_l6&FZFefblF^oFegdlFidw-F[ew6$F_r-F\_l6%Q0
function~coefs_F%F^oQB(data::Vector|frMatrix|frFloat64|hr|hr)|+|+F%?(F\sF2F2Fbc
nFgfm-F[ew6$F_r-F\_l6'Fd`vF^cuQ)~=~data[F%F\sF[\el-F[ew6$F_rF]aw?(F\sF2F2Fh]oFg
fmC'@$/F\sFguC&>F_uF]hbl>Fhv7#-F^t6#-Fafn6$F]ibl,&-Fdz6$Fd[lFhf_lF2F]iblFbx?&Fi
xFhvFgfm>Ffhbl-F]^q6$/--Fg\r6$F_u%%nameGF^\p&F_\flF^\pFfhbl-F[ew6$F_r-F\_l6*F]a
wFd`vF_uQ*~=~C[:,1:F%F]iblQ']\C[:,F%F`iblQ(:end]|+|+F%-F[ew6$F_r-F\_l6)Fd`vFfib
l-Fe\m6%FfrFejdlFax-Fdz6$Ffz&FhnF]uFef^l-Fdz6$Fd[lFb]flFg_al?(Ff[pF2F2FfqFgfm?(
FixF2F2-Fafn6#&&F\qFb\yF%Fgfm>Fb]fl-F]^q6$/-&FdpFb\yF^\p&F`^flF^\pFb]fl>6$F[brF
_er6$-Fjel6$-Fg\r6$Fb]flFi\rFdjbl-Fg\r6$Fb]flF^p?&FcgrF[brFgfmC%>Fjgr7#-Fb\u6$F
cgrF_er>F[jr-Fe\m6%Ffr-Fa[cl6%-Fg\r6$FcgrFgguFh[clQ#imF%Ff_fl-F[ew6$F_r-F\_l6)F
d`vQ#C[F%-Fe\m6%/-FgqFc[yF2&FjgrFcq-Fj_wFc[yFeg^l-Fe\m6%F``flQ$~=~F%Q%~.=~F%F[j
rF]aw-F[ew6$F_r-F\_l6%F]awFd`vQZC~=~C./repeat(sqrt.(sum(C.*conj(C),dims=2)),1,s
ize(C,2))|+F%-F[ew6$F_r-F\_l6)F]awFd`vQ#U(F%F]`clFe\cl-Fj_wFiarF\\`l-F[ew6$F_r-
F\_l6$Fd`vQ-return~C,U|+|+F%F`ielFbiel-Fhg^l6#-F\_l6%F_aclF^oFegdlF%F%F%6#Fbo6Q
Fedel7'FaxFbxF`gpFjjyFa\lFa\wFegnFg[rFjbwFdaclF`gsFeaclFfdnFfacl7'FaxFbxFWFdxFa
\l7'FaxFbxFWF[^lF_\lFdjyFgdn7'FaxFbxFj`lF_^tF_\lFgjyFhh_lFcfwFibalFidyF_b`lFgdn
FffuF^bclFgdnFddo7'FaxFbxF^enF`gpFa\lFbbcl7'FaxFbxF^enFhfpFd_l7'FaxFbxFi^mFbdtF
a\l7'FaxFbxF^enF`epF_\l7'FaxFbxFj`lFbbalF_\l7'FaxFbxFj`lFb[vFd_l7'FaxFbxFi]l"$H
"Fd_l7'FaxFbxF`\mFg[vFa\lFfjrF^dt7'FaxFbxF^enFd^lFa\l7'FaxFbxF^enFajpFa\l7'FaxF
bxF^enFb[vF_\lF]b`lFjbclF_]elFhh_lFcfwF[[zF%,
I2writeTestNumJuliaw,F_ccl6%FjcwFih^lF_c`l6"F%C;>FhnFfj_l>Fin-F\_l6$FhnFhn>Fgn-
Fgdw6$-F\_l6&FZF\dclF^oFegdlFidw-F[ew6$FgnQAinclude("../_common/header.jl")|+F%
-F[ew6$Fgn-F\_l6%Q6include("inidata_num_F%F^oQ'.jl")|+F%-F[ew6$Fgn-F\_l6%Q0incl
ude("coefs_F%F^oFddfl-F[ew6$Fgn-F\_l6)Q.include("red_F%FgfclF^[`lFhfclFifclF^oQ
(.jl")|+|+F%-F[ew6$Fgn-F\_l6%Q3function~test_num_F%F^oF_dbl-F[ew6$Fgn-F\_l6$Fhn
Q2Random.seed!(23)|+F%-F[ew6$Fgn-F\_l6$FhnQ+N~=~10000|+F%-F[ew6$Fgn-F\_l6&FhnFg
dclFfrF\\`l-F[ew6$Fgn-F\_l6&FhnQ4stats~=~ini_stats("F%F^oQ%")|+|+F%-F[ew6$Fgn-F
\_l6$FhnQ.for~i~in~1:N|+F%-F[ew6$Fgn-F\_l6&FinFeeclF^oQ$()|+F%-F[ew6$Fgn-F\_l6&
FinQ-C,U~=~coefs_F%F^oF[gbl-F[ew6$Fgn-F\_l6*FinQ8toc~=~@elapsed~S~=~red_F%Fgfcl
F^[`lFhfclFifclF^oQ%(C)|+F%-F[ew6$Fgn-F\_l6$FinQ<stats.tm~=~[stats.tm;~toc]|+F%
-F[ew6$Fgn-F\_l6$FinFegcl-F[ew6$Fgn-F\_l6$FinQEstats~=~update_stats(stats,S,C,U
,d)|+F%-F[ew6$Fgn-F\_l6$FhnF\]al-F[ew6$Fgn-F\_l6$FhnQ4disp_stats(stats)|+|+F%F[
hcl-F[ew6$Fgn-F\_l6%FehclF^oQ#()F%F`hcl-Fhg^l6#-F\_l6%FehclF^oFegdlF%F%F%6#F]_o
6<F\c[lFihcl7'FaxFbxFgxFe[mFa\lF\gpFejyFdb`lFhjyFijyFhjyFccalFacalFccalF^calF_]
elFdjyF`bfl7'FaxFbxFWFcezF_\lFa\blF`bflF`b`lF]calFeb`lF]iclFf\blFcfwF_eelF%,
I+convPythonw,6%%#idGF[jqFi^lF%6$FdwFewF%-Feo6$w,F`[zF%6$FdwFewF%,&FjcmF2*&F[dm
F2FghlF2F2F%F%6$Fi^lFct6#F26$7'FaxFbxFgxF\amFexFdhm-Feo6$w,Fj\uF%6$FdwFewF%7$-%
%iquoG6$FfisFghl-%%iremGFh[glF%F%6$F[jqFZ6#F26$7'FaxFbxF]^lFe]lFex7'FaxFbxF]^lF
]alFexF^oF%F%F%6#FW6$7'FaxFbxFcglFgeuFex7'FaxFbxFcglFadmFexF%,
I2commonCode1Pythonw,Ffh^l6+F[i^lF\i^lF]i^lFeyF^i^lF_i^lF`i^lFai^lFf]bl6"F%C(>F
gnFei^l>FcaqF\j^l>Fin-Fbjfl6$FinF\j_l-F[ew6$F^o-F\_l6.FZQ8M~=~csr_matrix((C.fla
t[F%F^\_lQ$],(F%-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%-F[\u6%FjcmF[tF2F%F%F%6#F26$7'Fa
xFbxFbdtF^fwFexF\\_lFhnFef^l-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%-F[\u6%F[dmF[tF2F%F%
F%6#F26$7'FaxFbxF]eelFcaclFex7'FaxFbxF]eelF_fwFexFhnQ+)),shape=(F%F`\_lFef^lFa
\_lFjhel@$Fd\_lC*>Fdpw,FfcqF%6$FdwFewF%Fi\_lF%F%F]]_l6#F2F_]_l>F\q-F_v6$-Fbjx6#
-Feo6$w,FfcqF%6$FdwFewF%Fj]_lF%F%F[^_l6#F2F]^_lF`^_l-Feo6$w,FfcqF%6$FdwFewF%Fj]
_lF%F%F[^_l6#F2Fh^_lF[__l>FeqF^__l>F^apFa__l>F\sFaa_l>F\s-Fa[cl6%F\sQ"^F%Q#**F%
-F[ew6$F^o-F\_l6/F]awFZQ;M0~=~csr_matrix((np.array(F%F\sQ$),(F%-Fj_w6#-Feo6$w,F
j\uF%6$FdwFewF%Fj]glF%F%F%6#F26$7'FaxFbxF[^nF]cwFex7'FaxFbxF[^nFid^lFexFjqFef^l
-Fj_w6#-Feo6$w,Fj\uF%6$FdwFewF%Fe^glF%F%F%6#F26$7'FaxFbxF_fwFbjyFex7'FaxFbxF_fw
Fd[vFexFjqF[_glF`ioFef^lF[`]lFjhel-F[ew6$F^o-F\_l6(FZF_adlF`ioQ):]-M[:,:F%F`ioQ
C]@M0~#~Schur~complement~reduction|+F%-F[ew6$F^o-F\_l6$FZQ1M~=~M.toarray()|+F%F
%F%F%6#F/61F\c[lFa\oFd]lF`[x7'FaxFbxFW"$)=F_\lFegnFi_\lF]b_lF^b_lF_b_lFgdoFe]p7
'FaxFbxFj`l"$%=F_\lFhdelFf\blF%,
I2commonCode2Pythonw,Feb_lFfb_l6"F%C'>Fcbn-F^`s6$w,Fj\uF%6$FdwFewF%F`c_lF%F%Fac
_l6#F2Fcc_lFec_l@&Fjc_lC$-F[ew6$F^o-F\_l6(FZQ/S~=~np.zeros((F%FfrFef^lFctQ2),dt
ype=complex)|+F%@%F^d_l-F[ew6$F^o-F\_l6*FZFdcdl,&FjhqF2FbxF2Fecdl,*FctF2FfrFbxF
cewF2FjhqF2Q',:]/V[F%F]f_lFgcdl-F[ew6$F^o-F\_l6,FZFdcdl-Fj_w6#-F[\u6%FgnF[tF2Fe
cdl-Fj_w6#-Fchr6%,(FctF2FfrFbxFcewF2F[tFgnQ/,:]/np.tile(V[F%F]f_lQ&,:],(F%F^fmQ
&,1))|+F%Fee_l-F[ew6$F^o-F\_l6,FZFbddlFae_lF\f_lF]f_lF[fglF]f_lF\fglFfrF]fgl@&F
_f_l@%Fcf_l-F[ew6$F^o-F\_l6*FZFdcdl,&Fhf_lF2FbxF2FecdlF]f_lF]egl,*FctF2FfrFbxFc
ewF2Fhf_lF2Fgcdl-F[ew6$F^o-F\_l6,FZFdcdl-Fj_w6#-F[\u6%FhnF[tF2Q1,:]~=~np.tile(V
[F%F]f_lF\fglFh]oQ(,1))/V[F%-Fj_w6#-Fchr6%FjeglF[tFhnFgcdlFdg_l-F[ew6$F^o-F\_l6
,FZQ/S~=~np.tile(V[F%F]f_lF\fglFfrFcgglFae_lF\f_lF]f_lFgcdl-F[ew6$F^o-F\_l6$FZQ
IS~=~S[:,np.all(np.isfinite(S),axis=0)]|+|+F%-F[ew6$F^o-F\_l6$FZQ)return~SF%F%F
%F%6#F]_o61F\c[lFa[xFegnF`fdlFddo7'FaxFbxF^enFe\lF_\l7'FaxFbxF^enFc^[lF_\l7'Fax
FbxFj`lFajpF_\lFegnFddoFihglFjhglF[iglF\bcl7'FaxFbxFWFd[mF_\lF%,
I2writeSolverPythonw,FhfdlFfi_l6"F%C<>FgnF[j_l>FhnF_j_l>FinFbj_l>FdpFdj_l>FeqFf
j_l>F\q-Fgdw6$-F\_l6*FZF\[`lF][`lF^[`lF_[`lF`[`lF^oQ$.pyF%Fidw-F[ew6$F\qQ4impor
t~numpy~as~np|+F%-F[ew6$F\qQEfrom~scipy.sparse~import~csr_matrix|+F%-F[ew6$F\qQ
Jfrom~scipy.linalg~import~lu,~solve,~eig|+|+F%FfgdlF[hdl-F[ew6$F\q-F\_l6)Q)def~
red_F%F][`lF^[`lF_[`lF`[`lF^oQ&(C):|+F%-Fd\glFd\`l-F[ew6$F\q-F\_l6'F]awFeqQ1P,L
,_~=~lu(M[:,:F%FhnF\idl-F[ew6$F\q-F\_l6(FeqQCM~=~solve(np.concatenate((P@L,P[:,
F%FhnQ1:]),axis=1),M[:,F%FhnQ%:])|+F%-F[ew6$F\q-F\_l6&FeqQ(M~=~M[-F%FinQ':,:]|+
|+F%-F[ew6$F\q-F\_l6*FeqQ0T0~=~np.zeros((F%FdpFef^lFdpF_`cl-Fe\m6%FghzQ/,dtype=
complexF%FaxFa^dl-F[ew6$F\q-F\_l6(FeqFjjdl-Fj_w6#-F[\u6%F[_`lF[tF2F[[elFinQ$:]|
+F%-F[ew6$F\q-F\_l6&FeqQ)T0.flat[F%-Fj_w6#-Fbjfl6%Fc_`lFdpFdpQ']~=~1|+F%-F[ew6$
F\q-F\_l6*FeqQ0T1~=~np.zeros((F%FdpFef^lFdpF_`clFc\hlFa^dl-F[ew6$F\q-F\_l6*FeqQ
+T1[np.ix_(F%Fj\hlFef^lFj\hlQ+)]~=~M[:,:F%FinF[\el-F[ew6$F\q-F\_l6&FeqQ)T1.flat
[F%-Fj_w6#-Fbjfl6%Ff``lFdpFdpQ(]~=~1|+|+F%-F[ew6$F\q-F\_l6$FeqQ2_,V~=~eig(T0,T1
)|+F%-FdcglF^a`lF_a`l-Fhg^l6#-F\_l6)Fda`lF][`lF^[`lF_[`lF`[`lF^oF[jglF%F%F%6#F^
en6=F\c[lFga`lFha`lFia`lFja`lF[b`lF`\wFacalFe\blFdjyF\\blF]]el7'FaxFbxFWF[alF_
\lFgjyFdjyFa]elFedxF\cal7'FaxFbxFWFjdnF_\l7'FaxFbxFWF_^tF_\lF\cal7'FaxFbxFWFaez
F_\lF[calFccalFgjyFcfwF^calF%,
I8writeInidataCoefsPythonw,Fceel66F\_tF\]blF]]blF^]blF_]blF`]blFa]blFjcwF_zFigm
F]hsFb]blFeeel%$rs1GFc]blFd]blFe]blFg]blFf]blFih^l6"F%C?>F]avFfj_l>FgnF\^bl@$F^
^blC$Fb^blOF%AF[[u>Fh^blFi^blAFd[u>FeqFafel>Fjq-Feo6$w,FbwF%6$FdwFewF%-Fj_w6#-F
eo6$w,FeclF%6$FdwFewF%Fe`blF%F%Fg`bl6#F2Fi`blF[xF%F%F_gel6#F2F]ablFct>Feq-Feo6$
w,FeclF%6$FdwFewF%-Fa[cl6%-Fg\r6$F^oFgguFg`glFh`glF%F%F%6#F26$7'FaxFbxFcglFe]lF
ex7'FaxFbxFcglFcilFexFeq>F_r-Fgdw6$-F\_l6&FZFicblF^oF[jglFidw-F[ew6$F_rQ5import
~numpy~as~np|+|+F%-F[ew6$F_r-F\_l6%Q1def~inidata_num_F%F^oQ%():|+F%-F[ew6$F_r-F
\_l6&F]avQ/data~=~[None]*F%FfqF]aw?(F\sF2F2FfqFgfm-F[ew6$F_r-F\_l6(F]avQ&data[F
%,&F\sF2FbxF2Q5]~=~np.random.randn(F%FfhelFa^dl-F[ew6$F_r-F\_l6$F]avQ,return~da
taF%Fbiel-Fhg^l6#-F\_l6%F_fblF^oF[jgl>F_r-Fgdw6$-F\_l6&FZFefblF^oF[jglFidw-F[ew
6$F_rF^jgl-F[ew6$F_r-F\_l6%Q,|+def~coefs_F%F^oQ)(data):|+F%?(F\sF2F2FbcnFgfm-F[
ew6$F_r-F\_l6'F]avF^cuFgjelF`dhlQ*].T.flat|+F%Fhjel?(F\sF2F2Fh]oFgfmC'@$F][flC'
>FixF]hbl>Ff[pFa[fl>F[br-Fbjfl6%Ff[pF]iblFf[fl?(FhvF2F2-FgqFb\yFgfm>Ffhbl-F]^q6
$/--Fg\r6$FixFa\fl6#&Ff[pF_[]l&F^ghl6#&F[brF_[]lFfhbl-F[ew6$F_r-F\_l6*F]awF]avF
ixQ:~=~(np.linalg.solve(C[:,:F%F]iblQ'],C[:,F%F]iblQ,:])).flat|+|+F%-F[ew6$F_r-
F\_l6*F]avQ/C~=~np.zeros((F%F`]flFef^lFc]flF_`cl-Fe\m6%FfrFe\hlFaxFa^dl?(F_uF2F
2FfqFgfm?(FhvF2F2-Fafn6#&&F\qFhbuF%Fgfm>Fb]fl-F]^q6$/-&FdpFhbuF_[]l&F^ihl6#,&Fh
vF2FbxF2Fb]fl>Fe_v6$Fe^fl-Fg\r6$)Fb]flFa[oF^p?&FjgrF_erFgfmC(>F[jr7#-Fb\uFjd[l>
Fd`v-Fe\m6%Ffr-Fa[cl6%-Fg\r6$FjgrFgguFh[clQ#1jF%Fajhl>Fd`v-Fa[cl6%Fd`vFg`glFh`g
l>Fd`v-Fa[cl6%-Fa[cl6%Fd`vQ$sinF%Q'np.sinF%Q$cosF%Q'np.cosF%>Fd`v-Fa[cl6%-Fa[cl
6%Fd`vQ%sqrtF%Q(np.sqrtF%Q$tanF%Q'np.tanF%-F[ew6$F_r-F\_l6)F]avQ(C.flat[F%-Fe\m
6%/-FgqFjewF2,&F]^^lF2FbxF2-Fj_w6#-F[\u6%F[jrF[tF2Feg^lFf`flFd`vF]aw-F[ew6$F_r-
F\_l6%F]awF]avQenC~=~C/np.sqrt(np.sum(C*np.conj(C),axis=1,keepdims=True))|+|+F%
-F[ew6$F_r-F\_l6&F]avQ'def~U(F%F]`clQ$):|+F%-F[ew6$F_r-F\_l6'F]avF]avQ1return~n
p.array(F%FbaflFg_al-F[ew6$F_r-F\_l6$F]avQ+return~C,UF%Fbiel-Fhg^l6#-F\_l6%F_ac
lF^oF[jglF%F%F%6#Fbo6WF[bal7'FaxFbxF^^[lF]balFa\lFa\wFegnFg[rFjbwFdaclF`gsFeacl
FfdnFfaclFa[sF_bflF[[zFe_\lF^calFgdn7'FaxFbxFj`lFi]pF_\lFacalFcfwFibalFidyFacal
Fe_\lFgdn7'FaxFbxFj`lFgjrF_\lF^bclFgdnFddoFbbflFbbcl7'FaxFbxF^enFeiqFa\l7'FaxFb
xF^enFbbalFd_l7'FaxFbxFa\lFg[qFa\l7'FaxFbxF^enF`^[lF_\l7'FaxFbxFj`lF`^[lF_\l7'F
axFbxFj`l"$R"Fd_l7'FaxFbxFi]l"$J"Fd_l7'FaxFbxF`\mFgbalFa\l7'FaxFbxFj`lFciqFa\lF
^dtF[cflF\cflFhe^l7'FaxFbxF^enFgbwFa\l7'FaxFbxF^enFaezFa\l7'FaxFbxF^enF^gpF_\lF
cbalFb\bl7'FaxFbxFWFajmF_\l7'FaxFbxFWFexF_\lFcfwF[[zF%,
I3writeTestNumPythonw,F_cclF`cfl6"F%C;>FhnFfj_l>FinFecfl>Fgn-Fgdw6$-F\_l6&FZF\d
clF^oF[jglFidw-F[ew6$FgnQ?from~numpy.random~import~seed|+F%-F[ew6$FgnQ7from~tim
e~import~time|+F%-F[ew6$FgnQYfrom~_common~import~ini_stats,~update_stats,~disp_
stats|+F%-F[ew6$Fgn-F\_l6/Q)from~py_F%F^oQ5~import~inidata_num_F%F^oQ),~coefs_F
%F^oQ',~red_F%FgfclF^[`lFhfclF`[`lF^oF\\`l-F[ew6$Fgn-F\_l6%Q.def~test_num_F%F^o
Fdchl-F[ew6$Fgn-F\_l6$FhnQ*seed(23)|+F%-F[ew6$Fgn-F\_l6$FhnQ*N~=~1000|+F%F_ffl-
F[ew6$Fgn-F\_l6&FhnF\eclF^oQ%')|+|+F%-F[ew6$Fgn-F\_l6$FhnQ4for~i~in~range(N):|+
F%F^gflFcgfl-F[ew6$Fgn-F\_l6$FinQ.tic~=~time()|+F%-F[ew6$Fgn-F\_l6*FinFffclFgfc
lF^[`lFhfclF`[`lF^oF]hfl-F[ew6$Fgn-F\_l6$FinQ@stats['tm'].append(time()-tic)|+F
%-F[ew6$Fgn-F\_l6$FinQ/if~S~is~None:|+F%-F[ew6$Fgn-F\_l6%FinFhnQ+continue|+|+F%
-F[ew6$Fgn-F\_l6$FinQFstats~=~update_stats(stats,S,C,U,d)|+|+F%-F[ew6$Fgn-F\_l6
$FhnQ2disp_stats(stats)F%F`hcl-Fhg^l6#-F\_l6%FehclF^oF[jgl-%0writeInitPythonG6&
F^oFZFctFj]oF%F%F%6#F]_o6<FhhclFihclF`jflF\gpFjdelF_]el7'FaxFbxFWFe]lF_\l7'FaxF
bxFW"$M"F_\lF]`qFd_ilFd_ilFccalF^iclFb]elFdjyF`bflFgjy7'FaxFbxFWF^jsF_\lF`bflF_
eelFf\blF\[zFf\blFcfwF_eelFacalF%,
I0writeInitPythonw,6&FfguF\i_lF_i_lFaccl6#Fjcw6"F%C)>Fgn-Fgdw6$-F\_l6$FZQ-/__in
it__.pyF%Fidw-F[ew6$Fgn-F\_l6'Q3from~.inidata_num_F%F^oF^ailF^oF]aw-F[ew6$Fgn-F
\_l6'Q-from~.coefs_F%F^oQ/~import~coefs_F%F^oF]aw-F[ew6$Fgn-F\_l6/Q+from~.red_F
%FgfclF^[`lFhfclF`[`lF^oQ-~import~red_F%FgfclF^[`lFhfclF`[`lF^oF]aw-F[ew6$Fgn-F
\_l6'Q0from~.test_num_F%F^oQ2~import~test_num_F%F^oF]awF`hcl-Fhg^l6#Q,__init__.
pyF%F%F%F%6#Fbo6*F\doFg_qF_b`lF`eel7'FaxFbxFWFibwF_\lFheilFcfw7'FaxFbxFWFi^mF_
\lF%
