M7R0
I,eigenSolverw,6$'%%probG%'stringG>%'showAPG""!60%$rndG%%fB2CG%"FG%%varsG%%tord
G%"GG%"BG%$degG%#avG%#vrG%"TG%"VG%"SG%#SrG6"6"C2>8$,$-%%randG6#;!%+5"%+5#"""FE>
8%w,6%'%"fG%(polynomG'F/%%listG'F2FP6#%"tG6"F;C$>F>-%&tableG6#-%$zipG6%w,6$%"aG
%"bGF;6$%)operatorG%&arrowGF;/9%9$F;F;F;6#""#6$7'Q!F;!"""#G"#Q"#O7'FeoFfoFgo"#M
Fio7#-%'coeffsG6%F`oF_o.%"mG7#FapO-%$mapG6$w,6#FjnF;6$F\oF]oF;-%#ifG6%-%)assign
edG6#&T#6#F`oF`qF*F;F;6$FSF>6#FG6$7'FeoFfo"#="#\Fio7'FeoFfoFgq"#?Fio9&F;F;F;6#"
"$6%7'FeoFfo"#6"#5Fio7'FeoFfo"#8"#o"#J7'FeoFfo""("#`"#_>6%8&8'8(&-%,readProblem
G6'F`oF*7"F*FG6#7%FGF]r""%>F\s-Fep6$%&numerGF\s@$4-%%typeG6$F\s-FP6#FNYQQThe~ca
se~of~non-polynomial~system~is~not~handledF;>8)-&%)GroebnerG6#%&BasisG6$F\sF^s>
8*&-&Fht6#%*NormalSetG6$FetF^s6#FG>8+-%%nopsG6#F]u>8,-%$addG6$*&8-FG-F>F;FG-%#i
nG6$F`vF]s@$/F_oFG-%'printfG6$Q7Action~polynomial:~%a|+F;F[v>8.-&Fht6#%5Multipl
icationMatrixG6'F[vF]u-FX6#-&%"|irG6#%"=G6%F]u%#~$G7#-%"$G6#;FGFfuFetF^s>8/&-&%
.LinearAlgebraG6#%-EigenvectorsG6#-%&evalfG6#F\w6#Fbo>Fax-&Ffw6#%"/G6%FaxFjw-%"
.G6$-%'VectorG6$Ffu/%%fillGFG&FaxFdu>80-Fdy6$-%'MatrixG6#-Fep6$w,6#F5F;6$F\oF]o
F;-T+6%-&Fht6#%+NormalFormG6%F`oFaqT%T'T)F;F;6,F1FetF0F^sF/F]sF2F]uF-FI6#FG6$7'
FeoFfo"#>"#qFio7'FeoFfoFg[l"#AFioF]sFax>81-%#ReG6#&F]z6$;F;F;-%'selectG6$w,6#%"
cGF;6$F\oF]oF;-%'andseqG6$-%#isG6$&Faq6$%"iGF`o%%realG/Fb]l;FG-%#opG6$7$FGFGFaq
F;F;6$F8F]z6#FG6$7'FeoFfo"#DFh[lFio7'FeoFfoF^^l"#FFio7#-F]x6#;FG-Fg]l6$7$FGFboF
]zO6%F]zF\\l-%.backwardErrorG6&F\sF]sF]zFfuF;F;F;6#FG657'FeoFfo"#9""'Fio7'FeoFf
oF]r"#K"#V7'FeoFfoF]rFarFd_l7'FeoFfoF]r"#eFd_l7'FeoFfoF]rFjqFd_l7'FeoFfoF]r"$."
"#X7'FeoFfoFho"#%*"#]7'FeoFfoF]rFerFd_l7'FeoFfoF]rFhoFd_l7'FeoFfoF]r"#;Fd_l7'Fe
oFfoF]r"#LFd_l7'FeoFfoF]r"#lF[`l7'FeoFfoFjq"#cFjq7'FeoFfoF]r"#uFd_l7'FeoFfoF]r"
#ZFd_l7'FeoFfoF]rFioFd_l7'FeoFfoF]r"#")Fd_l7'FeoFfoF]r"#$*Fd_l7'FeoFfoF]r"#YFir
F;,
I%suppw,6$FMF/F;6"F;C$-F^p6%-%'expandGFbqF_o.%#mnGO<#F^blF;F;F;6#Fbo6%7'FeoFfoF
gr"#sFio7'FeoFfo"#@FhqFjq7'FeoFfoFir"#iFirF;,
I%Suppw,6$F.F/6#F86"F;C$>F>-Fep6%FdalF`oF_oO6$F>-%&unionG6#&F>F;F;F;F;6#Fbo6%7'
FeoFfoFgrFa_lFio7'FeoFfo""*FerFer7'FeoFfoF]r"#CFirF;,
I(degree1w,Ffal6#%$vrsG6"F;C$>F><#&F_oF;O-%$maxG6#-Fep6$w,6#F^blF;6$F\oF]oF;,&-
%'degreeG6$-FjsFbqFaqFG-Fcel6$-%&denomGFbqFaqFGF;F;6$FbdlF>6#FG6$7'FeoFfoFgq"#m
Fio7'FeoFfoFgqFfblFio-Fdal6$F`oF_oF;F;F;6#Fbo6%7'FeoFfoFarFa_lFio7'FeoFfoF\dl"#
BFer7'FeoFfoF]r"#$)FirF;,
I+TestOrder1w,6%%"xG%"yGF06%Fbdl%#dxG%#dyG6"F;C&>F>-%&minusG6$-%'indetsG6#F[r<#
F[r>FI-F_dl6$F`oF>>F\s-F_dl6$F_oF>O52FIF\s3/FIF\s-&Fht6#%*TestOrderG6%F`oF_oF[r
F;F;F;6#F]r6'7'FeoFfoFcrFa_lFio7'FeoFfoF\dl"#SFer7'FeoFfoFd_l"#jFd_l7'FeoFfoF^f
l"#')Fd_l7'FeoFfoF]r"#hFirF;,
I$srtw,6$F7F0F;6$F\oF]oF;-%%sortG6$F`ow,6$F\glF]glF;6$F\oF]oF;-Fghl6%F_oF`oT$F;
F;6$F0F_o6#Fbo6$7'FeoFfoF^^lFailFio7'FeoFfoF^^lFc_lFioF;F;F;6#Fbo6$7'FeoFfoFa_l
"#kFio7'FeoFfoFa_lFb`lFioF;,
I,poly2matrixw,F[cl6$F6F26"F;C%>F>-Fep6$w,6#%#plGF;6$F\oF]oF;-FX6#-Fen6%w,FhnF;
6$F\oF]oF;F^oF;F;F;6#Fbo6$7'FeoFfoFc_l"#UFio7'FeoFfoFc_lFhoFio7#-F^p6%F`oFbjlF]
bl7#F^blF;F;6$F/F_o6#FG6$7'FeoFfoFgq"#vFioF_flF`o>FI7#&&-FiblFaflF\yF;O6$-Faz6#
-Fep6$w,FRF;6$F\oF]oF;-Fep6$w,FhpF;6$F\oF]oF;-F[q6%-F^q6#&FbjlFbqFb^mF*F;F;6$FS
F`o6#FG6$7'FeoFfoFgo"#fFio7'FeoFfoFgo"#IFioFaqF;F;6$F2FI6#FG6$7'FeoFfoFfblFailF
io7'FeoFfoFfblFfflFioF>-Fgy6#FIF;F;F;6#Fbo6&F__l7'FeoFfoF\dl"#zFer7'FeoFfo"##)"
$1"Fd_l7'FeoFfoF]rFd_mFirF;,
I/permuteColumnsw,6%%"MGF7%#V1GF_el6$F\oF]oF;&F`o6$Fb\l7#-%$seqG6$-&%*ListTools
G6#%'SearchG6$F>F_o-Fcv6$F>F[rF;F;F;6#F]r6&7'FeoFfo"#<"#&)Fio7'FeoFfo"#H"#N"")7
'FeoFfoF`amFgoFioFbamF;,
I%expFw,6$F.%"AGF;6$F\oF]oF;-Fep6$w,6#%#sfGF;6$F\oF]oF;-F\bl6#*&&Fbjl6#&F`oFduF
G&F`oF\yFGF;F;6$F.F`o6#FG6$7'FeoFfoFg[l"#WFioFi[lF_oF;F;F;6#Fbo6$7'FeoFfoFgr"#[
Fio7'FeoFfoFgrF`_lFioF;,
I-iniReductionw,6%'F.FPFO'%#ppG%'posintG6+%#F1G%#F2G%$nF1G%"sG%#J1G%$FF2G%$JJ2G
%"XG%#s1G6"F;C(>F>-&Ffw6#FjsFbq>FIF>>F\s-Fhu6#F>>F]s,&-Fhu6#&-FiblFj`mF\yFGF\sF
fo?(F;FGFGF;%%trueGC->F^s-&%1PolynomialIdealsG6#%0PolynomialIdealG6$F>/%/charac
teristicGF[r>Fet-&Fep6#%(indicesG6$w,6#%"jGF;6$F\oF]oF;-%'subsopG6$/F`o%%NULLGF
aqF;F;6$F[dmF>6#FG6$7'FeoFfoF`^lF\alFio7'FeoFfoF`^lFcamFioF>>F]u-Fep6$w,6#F\dmF
;6$F\oF]oF;-Fiem6$F`o/F_fmFbjlF;F;6$FhcmF[r6#FG6$7'FeoFfoFgq"#xFioF_flFet>Ffu-F
d\l6$w,FgfmF;6$F\oF]oF;-&Fjem6#%1IdealContainmentG6%Faq&F`[lFbqFaqF;F;6&F_dmF^s
FadmF]u6#FG6$7'FeoFfoFg[l"#rFio7'FeoFfoFg[lFfblFio7#-F]x6#;FGF\s@$/-Fhu6#FfuF*[
>Ffu-Fep6$w,FgfmF;6$F\oF]oF;7%F`q-Fhu6#&-Fibl6$&F`[lF_qT(F\y-F_dl6$&Fb[lF_qFhjm
F;F;6*FbdmFfuF`dmFetF/F_oF[dmF>6#FG6$7'FeoFfoFb`lF_alFio7'FeoFfoFb`lFgqFio7#-F]
x6#;FGFiim>Ffu-&Fg`m6#%3FindMinimalElementG6$Ffuw,F^jlF;6$F\oF]oF;52Fhbm&F_oF\y
3/FhbmF_\n2&F_o6#F]r&F`oFd\nF;F;F;6#Fbo6$7'FeoFfoF[`l"#*)Fio7'FeoFfoF[`l"#^Fio>
F>&Fet6#&FfuFdu>F\sF\em>F[vF_em@$2F[vF]sC$>FIF>>F]sF[vO-%'removeG6%Fcv7#-F]x6#;
FG-FhuFbq-Fep6$w,Ff[mF;6$F\oF]oF;-Ff`m6$F`o-Fhdm6#FbjlF;F;Fibm6#FG6$7'FeoFfoFb
\mFahmFio7'FeoFfoFb\mF[`lFioFIF;F;F;6#F]r677'FeoFfo"#:Fa_lFioFefl7'FeoFfo"#EF[p
Fd_l7'FeoFfoFioF^`lFd_l7'FeoFfoF]rFdamFd_l7'FeoFfoF]rFeamF]cm7'FeoFfoFgrFdrFd_l
7'FeoFfoFgrFirFd_l7'FeoFfoFgrFhflFd_lFg_n7'FeoFfoFgrFhoF[`l7'FeoFfoF^^lF*Fhr7'F
eoFfoFgr"#(*Fd_l7'FeoFfoFgr"#!*Fd_l7'FeoFfoFgrFfblFd_lF^`n7'FeoFfoFgrF_ilFd_l7'
FeoFfoFgrF[`lF[`l7'FeoFfoFjqFgoFd_l7'FeoFfoFi^m"#PFd_lFgflF;,
I/shiftExpansionw,F[cl6(%#SPG%#sFGFhfmFSF^blF66"F;C&>Fet-%&ArrayG6#Fcs>6$F>FIFa
]m?(F\sFGFGF_^nFeemC%>F]s-F_y6%FIFjw&&F>6#F\sFdu?&F^s&Fgan6#;FboF;0-Fhu6#F]sFG-
%+intersect=G6$F]s-F_y6%FIFjwF^s>-FetFhan-Fc`m6$7$F\sF^s-Fcv6$F^sF]sO-%(convert
G6$FetFPF;F;F;6#Fbo6+7'FeoFfoF`amFa_lFio7'FeoFfoF`^lF_ilFd_l7'FeoFfoF]rF^^lFd_l
7'FeoFfoF]rFeamFeam7'FeoFfoFgrFfflFd_l7'FeoFfoFgrFj`lFeam7'FeoFfoFacm"#nFjq7'Fe
oFfoFgrFdamFd_l7'FeoFfoF]rF^^lFirF;,
I-neighborMonsw,6%%#BsGF/%(sShiftsG6#%$vBsG6"F;C$@(/F[rFG>F>-Fep6%-%"@G6$Fg]l&F
fw6#%"*GF`oF_o/F[rFfo>F>-Fep6%-F[en6$Fg]lF_yF`oF_o/F[rF*>F>-Fep6$Fg]l-Fep6%-F[e
n6$Fg]l<$F]enF_yF`oF_oO-Fegl6$F>F`oF;F;F;6#F]r6(F^_n7'FeoFfoF]rF\dlF[`l7'FeoFfo
FfblFhqFd_l7'FeoFfoF^dlFirFd_l7'FeoFfoFfflFdrFd_l7'FeoFfoF]rFj[lFirF;,
I-rowReductionw,6$F\`mFhcm6&%#tMG%#bsG%"rG%&r2delG6"F;C&>F>-%$modG6$-%*Gaussjor
dG6$)F`o%#%TG.%$rnkGF_o>FI7#-Fc`m6$-Ff`m6$FG&F>6$F\sFb\l/F\s;FGF]hn>F]s-Fi]n6%F
cv7#-F]x6#;FG-Fg]l6$Fi]lF`oFIO6$&F`o6$FIFb\lF]sF;F;F;6#Fbo6'F^_n7'FeoFfoF]rFc`n
Fd_l7'FeoFfoF]r"#bFd_lF[alF[dnF;,
I.scoreFunctionw,6'F`bm%#nFGFh`nFg`n%#NAG6(FhfmFSF^bl%#A1G%#nrG%#ncG6"F;C'>F]sF
\an?(F>FGFGF_oFeemC%>FI-F_y6%F[rFjw&&9'F]emFdu?&F\s&F\[oF[bn0-FhuF`_m&9(F]em-Fa
bn6$FI-F_y6%F[rFjwF\s>-F]sF]em-Fc`m6$7$F>F\s-Fcv6$F\sFI>F]s-F^cn6$F]sFP>6$F^sFe
t6$F^bn-FhuFiglO7&,&FetFGF^sFfoF^sF]sF`oF;F;F;6#""&6,7'FeoFfoFb`lFa_lFio7'FeoFf
oFg[lFd`lFd_lFecnFfcn7'FeoFfoFgr"#yFeam7'FeoFfoFirFaimFjq7'FeoFfoFgrFioFd_lFdcn
7'FeoFfoF]rFi^mFd_l7'FeoFfoF]rFgoFirF;,
I'shiftsw,6*Ffcm'Fjam-FP6#FP'%#_AG-%$setGFi]oFOFgcm'F`dn%(integerG'%)guidVarsGF
P'%*manShiftsGFP6.%#nAGF]jn%#tmGF`jnF8%$sf1GFhfmF^blF\`mF7F`gn%$_A1G6"F;C*>F>-F
hu6#F_o>FIF_^n>F\s-%%timeGF;@'3/F>F*0-Fhu6#9+F*>F]s-Fbfm6$w,FgfmF;6$F\oF]oF;-Fc
`m6$7$F`oFaq-Fcv6$Faq&T&FbqF;F;6&F^blFfuFc^oFh_o6#FG6$7'FeoFfoFg_l"##*Fio7'FeoF
foFg_l"#gFioFh_oFd_o>F]s-Fd`n6$F`oF][oC&>F^s7#-Fc`m6$-F\dn6%<#-Fc`m6$&FetF\y-Fc
v6$Fet-Fd\l6$w,F_bmF;6$F\oF]oF;/FgbmFaqF;F;6$FhfmF]u6#FG6$7'FeoFfo"#dFdrFio7'Fe
oFfoFeboF[aoFioF_oF][o9)/F]u;FGFI@$0-Fhu6#9*F*>F^s-%%map2G6&Fd\l%$hasGF^s&F][oF
]co>F]s7$Fgdl-Fc`m6$-Fc`m6$7$F]uFfu-Fcv6$Ffu&F^sFiuFhbo>F]s-Fi]n6%FcvF]sF[r>6$F
[vF`v-F][m6$-Fgam6$F`oF]sF][o>6$F[vF\w-Fifn6$F[vFc[o>6$F]sFax6$-&Fi]nFcfm6%FcvF
]sF\w<$&&F]sF[yF;&F[rF;O6(F[vF`vF]sFax-Fjdl6#-Fep6$w,F_bmF;6$F\oF]oF;-F_dl6$Fhb
mFbjlF;F;6$F/F][o6#FG6$7'FeoFfoFd`lFh`lFio7'FeoFfoFd`lFioFioF]s,&F`_oFGF\sFfoF;
F;F;6#Feam627'FeoFfoF\dlFa_lFio7'FeoFfoF\dlFfblFer7'FeoFfoF^dlFioFd_l7'FeoFfoF]
rF`_lFd_lFdfn7'FeoFfo"#R"$/"Fd_l7'FeoFfoFgqFcalFd_l7'FeoFfoFgr"$+"Fd_l7'FeoFfoF
grFf_mF[`l7'FeoFfoFd`l"#tFd_l7'FeoFfoFgrFeboFd_l7'FeoFfoFgrFc_lFd_l7'FeoFfoF]rF
_ilFd_lFc`l7'FeoFfoF]rF^flFd_l7'FeoFfoF]rFj`lFirF;,
I(shifts1w,6)F.FjamF[^oF/F0F`dnFa^o6-F]jnFf^oF8Fg^oFhfmF^blFg`n%#spGF^jn%$SFsGF
`jn6"F;C.>F>F_^n>FIF`_o>F\s7#-Fc`m6$-F\dn6%<#-Fc`m6$&F]sF\y-Fcv6$F]s-Fd\l6$w,F_
bmF;6$F\oF]oF;F`boF;F;6$FhfmF^s6#FG6$7'FeoFfoFhrF[[mFio7'FeoFfoFhrFh`lFioF_oF][
oFgbo/F^s;FGF>@$F[co>F\s-Faco6&Fd\lFccoF\sFdco>F\s7#-Fc`m6$-Fc`m6$7$F^sFet-Fcv6
$Fet&F\s6#F^sFiio>F\s-Fi]n6%FcvF\sF[r>6$F]uFfu6$&-FiblF^aoFdu&-Fibl6$-FgamFaflF
][oF\y>F[v-&Ffw6#Fhu6#7#-Fc`m6$-Fd\l6$w,F_bmF;6$F\oF]oF;F`boF;F;Fdio6#FG6$7'Feo
FfoF`^lFhoFio7'FeoFfoF`^lFi^mFioF_oFiio>F`v-Fep6$w,F_bmF;6$F\oF]oF;-Fjin6'F`oFa
q-Fecl6$F`[l-F]en6%&Fa[lFfbmFjwFhbmFa[lFb[lF;F;6*F]jnF>F^hoFfuFg`nF]uF^jnF[v6#F
G6$7'FeoFfoF`_lFahmFio7'FeoFfoF`_lF`amFioF\s>F`v-F[jl6$F`vw,F^jlF;6$F\oF]oF;552
Fgbm&F_oFdu3/FgbmF_^pF^\n3Fa\n-%(testOrdG6%&&F`o6#FfsF\y&&F_oFh^pF\yFbjlF;F;6$F
0Fc[o6#Fbo6$7'FeoFfoFjq"$:"Fio7'FeoFfoFjqFa_nFio>F\w&&F`vFduFd\nO6'-F][m6$-Fgam
6$F`oF\wF][oF\wF[r-F_dl6$&&Fc_pFh^pF\yF][o,&F`_oFGFIFfoF;F;F;6#Fgr60FdflFifoF[g
o7'FeoFfoF]r"#'*Fd_l7'FeoFfoF]rF_]oF[`l7'FeoFfoFcam"#pFd_lF[al7'FeoFfoF]rFa_nFd
_lFhin7'FeoFfoF]rFhrFd_lF^al7'FeoFfoF]r"$;"Fd_l7'FeoFfoF]rF`amFd_l7'FeoFfoF]r"#
))FirF;,
I+actionMonsw,6$FO'%)sActMonsG<$FPFicm6$%#aMGF56"F;C%@%-F^t6$F_oFP>F>F_o@*Ffv>F
>F`o/F_oFbo>F>-F_y6%FGFjwF`o/F_oF]r>F>7$&F_bpF;&F`oF;/F_oFfs>F>7%FdbpFebp-Fc`m6
$&-F_y6%FIFjw-%%subsG6$/FIF^gmF`oF;-Fcv6$FIF`o-Fhv6%Q+|+%-40s%a|+|+F;Q2Action~m
onomials:F;F>OF>F;F;F;6#Fbo6,F]ilFdfn7'FeoFfoFerF[`lFd_l7'FeoFfoFgrFcrF[`l7'Feo
FfoFa_nFioFd_l7'FeoFfoFgo"#TFd_l7'FeoFfoFgo"#aFd_l7'FeoFfoFgoFagoFd_l7'FeoFfoF]
rF^`lFjq7'FeoFfoF]r"#7FirF;,
I*expansionw,6)F7%#RsG%#PsGF_dnF4%#nEG%"JG6&%$B1sG%%nB1sG%%aB1sG%"KG6"F;C(>F>F]
[o>FIFfo?(F;FGFGF;0F\emFIC$>6$FIF\s6$F\em-F]en6%Fc[oFjwF>-%'union=G6$F>-%*inter
sectG6$F\sF[r>F]s-Fep6$w,F_elF;6$F\oF]oF;,&-Ff`m6$F`oFbjlFGFd`oFfoF;F;6&F7F`oF[
epFgbo6#FG6$7'FeoFfoFedpFd_lFio7'FeoFfoFedpF__nFio-Fbfp6$F\sF_o-F_fp6$F>-Fep6$w
,6#F\glF;6$F\oF]oF;&Fb^mF;F;F;6$F\epF^co6#FG6$7'FeoFfoFgqFa_nFioFiqF]s-F[q6%/FI
F\emF>-9!6)F`oF_oF[rF>Fc[oFgboF^coF;F;F;6#Fgr6+7'FeoFfoFedpFa_lFio7'FeoFfoF\dlF
gqFer7'FeoFfoFjqFi^mFd_lFd_n7'FeoFfoFgrF]goFd_l7'FeoFfoFgrFdamFjq7'FeoFfoF]rFhb
lFd_l7'FeoFfoF]rFi^mFjq7'FeoFfoF]rF[[mFjqF;,
I1permSetReductionw,6,F]gnF7%#VsG%#EsGFidpFjdpF4F0%%deg0GFhcm6/F[ep%$nERGF_gn%"
CG%$E1sG%$V1sG%$P1sG%$R1sG%#E1G%#R1G%#P1GF]`m%$tM1G6"F;C2>F>-Fhu6#F][o>FI,&F>FG
-Fhu6#Fc[oFG>F]s-Fd\l6$w,FgfmF;6$F\oF]oF;32FaqF`o1F`oF`[lF;F;6&F[epF>FfipFI6#FG
6$7'FeoFfoF__nFd`lFio7'FeoFfoF__nF`amFio7#-Fc`m6$-Ff`m6$FG&F`oFehn/F\sF^in>F]s-
Fd\l6$w,Fg\lF;6$F\oF]oF;-&%+ArrayToolsG6#%'IsZeroG6#&Fbjl6$-Ff`m6$FG&Fbjl6$Fb\l
F`o;,&F`oFGFGFGF`[lF;F;6&F]gnF`oFfipFI6#FG6$7'FeoFfoF__nF_alFioFe[qF]s>F^s-Fecl
6$F][o-Fegl6$Fc[o-F^cn6$&F_oF_bnF]^o@$/-FhuFijoF>O7)F`oF_oF^sFc[oFgboF>FI>Fet-F
egl6$F[rF^s>F]u-Fd\l6$w,F_elF;6$F\oF]oF;-Fcv6$*&FbjlFGF`oFGF`[lF;F;6&F4F^coFiip
Fet6#FG6$7'FeoFfoF`amFd`lFio7'FeoFfoF`amFjqFioFet@$2Fgu9,OF*>Ffu-Fegl6$-F]en6%F
^coFjwF]uF]u-F_fp6$F^s-Fegl6$Fet-Fecl6$FfuF]u>6%F[vF`vF\w6%-Ffil6$7#&F^sF;Fh_o-
Ffil6$7#&FfuF;Fh_o-Ffil6$7#&F]uF;Fh_o>Fax-Fgy6#7%&F[vF;&F`vF;&F\wF;>F]z-Fi_m6%F
`oF_oFax>F]z-Fegn6$-Fhgn6#F]z9--Fchp6,F]zFaxFetF^sFfuF]uF^coFh_oFc_qF^bqF;F;F;6
#Far657'FeoFfoFg[lFa_lFio7'FeoFfoF\dlFj[lFer7'FeoFfoF^^lFb\mFd_l7'FeoFfoF]rFi`o
Fd_l7'FeoFfoF]rFaamFd_lF[al7'FeoFfoF]rFdrF[`l7'FeoFfoF^dlFg^mFir7'FeoFfoF]rFj[l
Fd_lF``l7'FeoFfoF]rFb\mF[`l7'FeoFfoFa_nF[pFir7'FeoFfoF]rF`^lFd_l7'FeoFfoF]rFhoF
jqFi`l7'FeoFfoF]rF[pFd_lF_cqF_`l7'FeoFfoF]rFg^mFjqF;,
I,solvingSetsw,6(F\`mF7F4F0FdipFhcm65FbipFjdpFidpFcip%"EG%"RG%"PGF]`mF_jpF]hn%$
OutGF[epFfipF_gnFgip%$PRsG%#mEGF\epF_dn6"F;C6>F>-F^cn6$F_oF]^o>FI-Fd\l6$w,F_elF
;6$F\oF]oF;Fi^qF;F;6&F4F[rFbipF>6#FG6$7'FeoFfoFb`lFerFio7'FeoFfoFb`lFg[lFioF>@$
2Fa[oFc[oOF*>F\s-Fegl6$-F]en6%F[rFjwFIFI>F]s-Fegl6$F>-FeclF^\o>6%F^sFetF]u6%-Ff
il6$7#&F]sF;F][o-Ffil6$7#&F\sF;F][o-Ffil6$7#&FIF;F][o>Ffu-Fgy6#7%Ff`q&FetF;F^aq
>F[v-Fegn6$-Fhgn6$-Fi_m6%F`oF_oFfu.F`vFgbo>F\w-F_ip6,&F[v6$;FGF`vFb\lFfuF>F]sF
\sFIF[rF][oFc[oFgbo@$/F\wF*OF*>6)F[vFfuF]sF\sFIFaxF]zFeaq>82-Fd\l6$w,FgfmF;6$F
\oF]oF;F_[qF;F;6$FfipF]z6#FG6$7'FeoFfoF__nFfflFioFe[q7#-Fc`m6$-Ff`m6$FG&F[v6$F
\\lFb\l/F\\lFggq>83-F^cn6$&Ffu6#F^hqF]^o>F^\o6$-Fecl6$F\sF`iq-Fegl6$FIF`iq>Fgeq
Fheq>FfuFffq>F[v-Fegn6$-Fhgn6#F_gqFgbo>84,&-Ff`m6$FG&F[v6$Fb\l,&FaxFGFGFGFGFfoF
G>857#-Fc`m6$-F^cn6$&Ffu6#-F^cn6$&-&Fd\q6#%,SearchArrayG6#F\iqF[bnFPF]^o/F\\l;,
&FcjqFGFGFG,&FcjqFG-FhuFhanFGO<#-Fc`m6$-Ffdp6)FfuF\sFI86F[rFaxF[[r-Fcv6$Ff\rF[[
rF;F;F;6#Fa_l69F__l7'FeoFfoF\dlFcamFerFc_n7'FeoFfoF]rF_dpF[`l7'FeoFfoF^^lFd`lFi
r7'FeoFfoF]rF^dlFd_lFb]o7'FeoFfoF]rFdrFd_lF_`l7'FeoFfoF]rFg^mFd_lF^al7'FeoFfoF]
rFd`lF[`l7'FeoFfoF`amF^^lFir7'FeoFfoF]rF]goFd_l7'FeoFfoF]rFdgoFd_l7'FeoFfoF]rFg
oFd_lFc]rF_]rF_`l7'FeoFfoF]rFirFd_l7'FeoFfoF]rF[`lFd_l7'FeoFfoF]r"$2"Fd_lFdilF;,
I0completeSetTestw,6$F_dnF/6'%#vvGF5%#ttGF^bl%&vars1G6"F;C%>F^sF_o>F>-Fd\l6$w,F
_elF;6$F\oF]oF;-%'andmapG6$w,FfzF;6$F\oF]oF;5-Fcv6$F[_qFd`o-Fcv6$*&FbjlFGF`oFfo
Fd`oF;F;6&F^blF`oF_dnFd`o6#FG6$7'FeoFfoF`^lFeboFioFe\pFaqF;F;6&F`^rF^sF_dnF`o6#
FG6$7'FeoFfoFb`lF[[mFioFidqF`o@%0F\emF*C$>F\s-Fep6$w,FfzF;6$F\oF]oF;-F[q6%-Fcv6
$*&&FaqFduFGF`oFGFd`o7$Fh`rFG7$*&Fi`rFGF`oFfoFfoF;F;6&F^^rF>F_dnF`o6#FG6$7'FeoF
foF`amFaimFioF`_qF^sO6$7$-Fc`m6$&F]sFdu-Fcv6$F]sF\s&F>Fdu7#-Fc`m6$F]ioFgarOF*F;
F;F;6#Fbo6)7'FeoFfoFgqFa_lFio7'FeoFfoF^^lFhoFd_l7'FeoFfoF]rFe`pFd_lFdfn7'FeoFfo
FgrFd_mFd_l7'FeoFfoFgrF^flFir7'FeoFfoFeamFb`lFirF;,
I&getTDw,6*'%$mxnG-FP6#FicmF7Fg]oF4'Fdip%*nonnegintGF0'F_dnF]^o'%%cmplGF_^o6'Fi
dpFcipFecqFfcqF26"F;C&>F>-Fegl6$-F]en6%F][oFjwF^coF^co>FI-Fegl6$F^dq-Fecl6$F>F^
co>F[s6%-Ffil6$FcfqFgbo-Ffil6$7#FgclFgbo-Ffil6$7#&F^coF;FgboO7)F][oFc[o7%F_\rF^
bnF^^qF`o-Fgy6#7%F`fqF\fqFf`qF[rFh_oF;F;F;6#Feam6'7'FeoFfoFeamFa_lFioF^]r7'FeoF
foF]rFd_lFd_lF_]r7'FeoFfoF]r"#()FirF;,
I-templateTestw,6*F\`mF7FjamF4F/F0FdipFhcm6'Ff^oFhcq%$BBsG%%BB1sGF_dn6"F;C*>F>F
`_o>FI-Facq6(F`oF_oF][oFgboF^coFh_o@$/FIF*O6$F*,&F`_oFGF>Ffo>6$F\sF]s-%-selectr
emoveG6$w,6#F_dnF;6$F\oF]oF;0-Fj]rF[gpF*F;F;6$F/Fc[o6#FG6$7'FeoFfoFcamFeilFio7'
FeoFfoFcamFc_lFioFI@$/F_\rF*@%0F^bnF*C%>F]s-Fbfp6#-Fc`m6$-Fi]n6$w,F_elF;6$F\oF]
oF;3-%'subsetG6$FaqF`o0F_^n-Fhu6#FaqF;F;6$F_dnF^s6#FG6$7'FeoFfoFb\mFf_mFioF[_nF
]sFjbn>F]s-&Fep6#Fgr6+Ffbr7#-Fg]l6$FGF`oF_oF[rF][oF^coFgboF]sF*O6$-Fg[n6$F[fqw,
F^jlF;6$F\oF]oF;52&F_oFbir&F`oFbir3/F`jrF_jr2&Fe\nFd\n&Fc\nFd\nF;F;F;6#Fbo6$7'F
eoFfoFg_l"$3"Fio7'FeoFfoFg_lF[[mFioFffrOFefr>F\s-Fbfp6#-Fc`m6$-Fi]n6$w,6#%$Bs1G
F;6$F\oF]oF;FdhrF;F;F[ir6#FG6$7'FeoFfoFd`l"#wFio7'FeoFfoFd`lFc`nFioF\s-Fcv6$F^s
F\s>F\s-Fair6+FfbrFdirF_oF[rF][oF^coFgboF\sFGO6$-Fg[n6$F_fqw,F^jlF;6$F\oF]oF;F]
jrF;F;F;6#Fbo6$7'FeoFfoFhq"#**Fio7'FeoFfoFhqFiinFioFffrF;F;F;6#Feam61F^_nF[go7'
FeoFfoF]rFcalFd_l7'FeoFfoF]rF]cmF[`l7'FeoFfoF`amFioFirFhgoFdfnF\dp7'FeoFfoF`rFj
_lFd_l7'FeoFfoF`rFj`lFd_l7'FeoFfoF`r"$@"Fir7'FeoFfoFedpFerFir7'FeoFfoF]r"#&*Fd_
l7'FeoFfoF]rF[[mFd_l7'FeoFfoF]r"$7"FirF;,
I-colReductionw,6%F\`mF[epFhcm6&F]gnF^gnF_gn%&c2delG6"F;C&>F>-Fegn6$-Fhgn6$F`oF
\hnF[r>FIF_hn>F]s-Fi]n6%Fcv7#-F]x6#;FGF_oFIO6%&F`o6$Fb\l-Fi]n6%Fcv7#-F]x6#;FG-F
g]l6$Fg^lF`oF]sF>F]sF;F;F;6#F]r6'F^_nFc_nFhinFgin7'FeoFfoF]rF^flFirF;,
I0sparseReductionw,6('F\`mFaz'F7FgyFg]o'F[epF^cr'%&spolsGFPFgcm60%#rgGFb]l%"kGF
ap%"nG%$crgG%#M1GF_jpF]hnF_gnF^gn%#ldG%$rpnG%$cpnG6"F;C0>F>-Fep6$w,FgfmF;6$F\oF
]oF;-F]x6#;,&-F]v6$-Fhu6#&Fbjl6#F`[l/F`[l;FG,&F`oFGFfoFGFGFGFG-F]v6$F\bs/F`[l;F
GF`oF;F;6&FjamF[rFb]lFI6#FG6$7'FeoFfoFcrFdrFio7'FeoFfoFcrF__nFioFc[o@$/F\emF*O6
%F*FcsFcs>F[s6$F\emFeir>Fet-Fi]n6%Fcv7#-F]x6#;FGF]sF>>F]u-%$<,>G6$&F`o6$F>Fb\l&
F`o6$FetFb\l>Ffu-Fegn6$-Fhgn6$)&F]u6$Ffim;FGF][oF[hn.F[vFgbo>F\w7#-Fc`m6$-Ff`m6
$FG&Ffu6$F`vFb\l/F`v;FGF[v>Fax-Fi]n6%FcvFcimF\w>F]z&7$FgclFifq6#7%Feaq&FaxF;-F]
x6#;,&F\sFGFGFGF]s>Ffu-Fegn6$-Fhgn6#&F]u6$F\wFidsFgbo>F\wF\es>Fax-Fi]n6%Fcv7#-F
]x6#FidsF\w>F\\l7%FeaqF]fs-F]x6#;,&F][oFGFGFGF^sO6%F[vF]zF\\lF;F;F;6#Fa_l62F`br
7'FeoFfoF]rFj[sFd_l7'FeoFfoF]rFcalF[`l7'FeoFfoFj[lFc`nFirF_`lF_cq7'FeoFfoF]rFca
mFd_l7'FeoFfoF]rF[]nFd_l7'FeoFfoF]rFh`lFd_lFc`lFg]rFggoF_hsF_cqF_`l7'FeoFfoF]rF
fflFirF;,
I*checkDataw,6%F.Fhcm%&iVarsG6#%#nvG6"F;C'@$4-F^t6$F`oF`tC$-Fhv6#QHF~is~not~a~l
ist~of~Laurent~polynomials|+F;OF*@$30F_oF*4-%(isprimeGF]_oC$-Fhv6%QA%a~is~not~p
rime,~use~%a~instead|+F;F_o-%*nextprimeGF]_oOF*>F>-Fhu6#-FhglFbq@$4-F[]l6$31FGF
b]l1Fb]lF>-Fcv6$Fb]lF[rC$-Fhv6#Q:Invalid~indices~in~iVars|+F;OF*OFGF;F;F;6#F]r6
.Fghp7'FeoFfoF]rFg_mF[`l7'FeoFfoFhoFeerFjq7'FeoFfoF]`n"#)*Fir7'FeoFfoF]r"$<"F[`
l7'FeoFfoFc`nFg[tFjq7'FeoFfo"$,""$4"FirF[]r7'FeoFfoF]rF^goF[`l7'FeoFfoF^`lFaamF
jq7'FeoFfoF\apFb`pFir7'FeoFfoF]rF`rFirF;,
I,readProblemw,6'F%'FhcmF^cr'FdhsFP'%,delHardPolyGF^crF^^o6(%*proc_nameG%$ff1G%
$ff2G%'spols0GF.%&p2delG6"F;C1>F]sFcsAQ6../problems/_common.mF;A-%$catG6%Q/../p
roblems/F_F;F`oQ#.mF;>F>-%%evalG6#-Ff]t6$%#C_GF`o@$-F^t6$F>%*procedureGC$>Fjep6
$-F>6#/%)symbolicGF*Fh^t>F]s7#-&Fg`m6#%*SearchAllG6$F*-&Ffw6#F\bl6#-&Ffw6#%"-G6
%FIFjwF\s>F^s-F^cn6$-Fd_t6#-F\^t6#-Ff]t6$%#F_GF`oFP@$/-Fahs6%-FhdmFijoF_oF[rF*Y
Q-Invalid~dataF;>6$F]jnF/6$F^^q7#&-FhglFijoF;>F0-%%tdegG6#&F/F;@$/F][oFGC$>Fet-
Fccm6%F^sF/F_o>F^s-F_cp6$-Fep6$w,6#Fb]lF;6$F\oF]oF;/F`qF*F;F;6$F.F^s6#FG6$7'Feo
FfoFfblFi^mFioF^_mFetF^s>F^s-F_cp6$-Few6%&F/FiglFjw-F_y6%FGFjwF`ctF^s@%3-F^t6$F
^sF`t/Fc[oFG-%'assignG6$.Fd^pFghl-Fict6$F[dtFifl@%Fdis@%-Fcco6$F^s^#FGC$-%&alia
sG6#/%#iUG-Fegn6$-%'RootOfG6#z'Fhgp#FG!FGF_o>F[dm-Fegn6$-F_cp6$/FbdtFhdtF^sF_o>
F[dm-Fegn6$F^sF_o>F[dmF^sAQ.redundantAG.mF;O6(F^sF]jnF/F0F[dmF]sF;6(F]jnF/F0F[d
mFhdtFd^pF;6#Fj\o6>F__l7'FeoFfoFi^mF_dpFd_l7'FeoFfoF]rFerFcal7'FeoFfoF]rF_ilFca
lF_cqFdfn7'FeoFfoFgrFhblFd_l7'FeoFfoFgrF[aoFd_l7'FeoFfoF]rF^`lFd_l7'FeoFfoF]rFj
`lF[`l7'FeoFfoF[`lFf`lF^`lF]alFjbqFdfnF_`n7'FeoFfoFgrF_dpFd_lFcer7'FeoFfoF]r"$I
"F[`l7'FeoFfoFacmFaamFjq7'FeoFfoFaalFd]sFjqFdfn7'FeoFfoFgrFj]sF[`l7'FeoFfoF^^lF
adpFjq7'FeoFfoFeboFhflFd_l7'FeoFfoF]`nF^goFd_l7'FeoFfoFeamF__nFd_l7'FeoFfoF]rFf
flFcal7'FeoFfoF]rF]goFirF;,
I(getDataw,6'F.F]jnF/F0%#tdG6BF4Fdip%$ptnGF7FjamFacrFe`sFhcmFdhsF\`m%#V0GF`gnFj
brF[ep%#nRGF3F_dn%#iqG%#B0GF2F_gnF]asF^asF]gnF_^s%#r1G%#r2G%#r3GFb]lFhfm%#iTGFS
6"F;C8>6+F>FIF\sF]sF^sFetF]uFfuF[v&&Fc[o6#7+FGFboF]rFj\oFa_lFgrFeamF\dlFarF;>F^
s-F[jl6$F^sw,F^jlF;6$F\oF]oF;F^^pF;F;F;6#Fbo6$Fhdq7'FeoFfoFb`lFj[lFio>6$F`vF\w-
F][m6$-Fgam6$F`oF^sF[r>6$F`vFax-Fifn6$F`vFfu>6$F]zF^s6$7#-Fg]l6$FGF`v-F[gm6$&-F
ew6%FaxFjwF^gmF;F^s>6%F\\lF^hqF`iqF`fq>Fcjq-F^cn6$&F]s6#;,$F`iqFfoF;F]^o@%/FetF
G>Fh\r-Fj]r6$FcjqF[r>Fh\r6$Fcs7#-F]x6$F*Fe\o>87-Fi]n6%Fcv7#&FcjqF;Ff\r>F[\u7$&-
Ffil6$F[\uF][oF;&Ff\rF;>F]s-Fgy6#7$&F]s6#;FG,&F\\lFGF^hqFG&F[\uF;>F`v-Fi_m6%F`v
F\wF]s>F^s7#-Fc`m6$-Fep6$w,6#Fg^oF;6$F\oF]oF;FhbmF;F;F;6#FG6$7'FeoFfoF`amF`^lFi
o7'FeoFfoF`amFfblFio-Fd\l6$w,F_bmF;6$F\oF]oF;F`boF;F;6$Fhfm8A6#FG6$7'FeoFfoFc`n
FacmFio7'FeoFfoFc`nF_ilFioF^s/Fd^uF^_s>6%88898:-F^`s6(F`vF]sF^sF\\lF]uFfu@$0F\_
uF*>Fdv6$&F`v6$F]_uF^_u&F]s6#F^_u>6%F`v8;8<-F[^s6%F`vF\\lFfu-%#-=G6$F\\l-Fhu6#F
\`u>6$8>8=-Fjfr6$w,Fg\lF;6$F\oF]oF;-Fcv6$*&FaqFGF\imFGF`[lF;F;6&F4F>F2F[\u6#FG6
$7'FeoFfoFa_nF_dpFio7'FeoFfoFa_nFgoFio7#-F]x6#;FGF`iq>8?-Fep6$w,Fg\lF;6$F\oF]oF
;-F[q6%F\auF^gm,&-Ff`m6$FG&Fa[l6$Fb\l-Ff`m6$F^auFb[lFGFizFfoF;F;6,F4F>F2F[\uF]g
nF[`uF7F]sF[epF\\l6#FG6$7'FeoFfoFcr"$-"FioF[csFdau>8B7$7#-Fc`m6$&Fg`u6#-Ff`m6$8
@Fiau/Ffcu;FG-Fhu6#Fg`u-Fep6$w,Fg\lF;6$F\oF]oF;,&*&FaqFG,&-Ff`m6$*&F`[lFG&Fa[lF
bqFGFa[lFGFfoFGFGFGF`oFGF;F;6(F3F`iqF4F>F2F[\u6#FG6$7'FeoFfoF^flFijrFio7'FeoFfo
F^flFdrFioFf`u>8C-Fep6$w,FgfmF;6$F\oF]oF;&-Fi]n6$w,FdbtF;6$F\oF]oF;/&Faq6$F`oFd
`oF*F;F;6&F]gnFaqFhfmF`o6#FG6$7'FeoFfoFj[lF[pFio7'FeoFfoFj[lF^dlFio<#-F]x6#Fe]l
F;F;F;6$F]gnF[`u6#FG6$7'FeoFfoFedpFeboFio7'FeoFfoFedpF`_lFio<#&F\`uF;O62-Fh_t6%
F_jtFjwF\_uFIF>F\sF]sF^sF\`uF\euF\_uF]_uF]cuF[[rFetF]uFfuF[vF;F;F;6#Fj\o6<Fdfl7
'FeoFfoF]rF\]mFd_lFb_lFggoFc`lFeftFjbqF_`lFdfn7'FeoFfoFgqFirFd_l7'FeoFfoFeamFio
Fd_lF_`lF]hsFc`lF_`l7'FeoFfoF]rFailFd_lF_hs7'FeoFfoF]rF[]nF[`l7'FeoFfoFb`lFb\mF
d_l7'FeoFfoF]rF_dpFd_l7'FeoFfoF]rFg[lFjqFf]r7'FeoFfoF]r"$9"Fd_l7'FeoFfoF]r"$8"F
d_lFbbr7'FeoFfoF]rF]`lFirF;,
I*iniColpivw,6'F7F4F/F0'%$xEsG-FP6#F]^o6*F]htFbipFjdpFidpFcipFgcqFfcqFecq6"F;C+
>F>-F^cn6$&F`o6#;,&Fe\oFfoFfoFGF;FP>FI-Fegl6$-F^cn6$F`oF]^o-Fecl6#&Fc[oF;>F\s-F
d\l6$w,F_elF;6$F\oF]oF;Fi^qF;F;6&F4F_oFbipFI6#FGFgdqFI>F]s-Fegl6$-F]en6%F_oFjwF
\sF\s>F^s-Fegl6$FI-FeclFhar>Fet7$&-Ffil6$7#&-Fegl6$F\s<#FgclF;F][oF;Fgcl>F]uFie
q>Ffu7%&&Fc[oF\yF;&-FeglFbiuF;&-Ffil6$Fe`qF][oF;O6$7%FfuF]uFet7%FiimFgu-Fhu6#Fe
tF;F;F;6#Fj\o6,FghpFdgu7'FeoFfoF]rF]cmFd_lFc_nF^]rFb]o7'FeoFfoF]rFhqFd_lF^]rF_h
s7'FeoFfoF]rF\alFirF;,
I-dispTemplatew,6)'FggtFP'%$nTDGFicmFfcmFO'F0%3ShortMonomialOrderG'Ff^o%&floatG
'%'headerGF_^o6.F]jnFjbrF4FigtF7F_^sFSF_gnFacr%#VrGF_hu%%ptn1G6"F;C*>F>Fe\o>6*F
IF\sF]sF^sFetF]uFfuF[v&-Fdgt6'F[rF>F][oFc[oF`o6#7*FGF]rFfsFj\oFgrFeamF\dlFcr>F`
v&F^s6#-Fi]n6%Fcv7#-F]x6#;FG-Fg]l6$FGF^sFet>F\w7$-Fep6$w,Fg\lF;6$F\oF]oF;F`qF;F
;6$F`]vF`v6#FG6$7'FeoFfoF__nFj[lFioFe[qF]u-F^cn6$&F^sF^xF]^o>Fax&-F[hu6'F`vF\sF
][oFc[oF\wF\y@$/F^coFGC$-Fhv6$-Ff]t6%Q"|+F;-F[q6%/F[vFGQ*Template~F;Q5INCOMPLET
E~template~F;Q&#%g:|+F;F_o-Fhv6(Q8%-20s%-20s%-20s%-20s%s|+F;Q,action~mon.F;Q+[#
E,#R,#B]F;Q+[#E,#R,#P]F;Q%sizeF;Q%timeF;-Fhv6(Q8%-20a%-20s%-20s%-20s%g|+F;F\s-%
+alterCommaG6#7$,&FfarFGF\\vFfo&&F]s6#7$FboF]rF;-Fbav6#Fax-FbavF`_mFgbo@$Fi_v-F
hv6#F_`vF;F;F;6#Fgr6.F^_nFifo7'FeoFfoF]rF]`nFd_lF^]sFeftF[alFdfn7'FeoFfoFgrF]`n
Fjq7'FeoFfoFgr"$0"Fjq7'FeoFfoF]r"$F"Fjq7'FeoFfoF]rF_ilF[`l7'FeoFfoFjqFerFjqF;,
I-saveTemplatew,6$F%Ff\v64FjbrFdipF4FigtF7FjamF_^sFSF_gnF]asFahtF\htFacrFe`sFhc
mFdhs%#fdG%#fnG6"F;C'>F[[r-Ff]t6$Q-templates/t_F;F`o>62F>FIF\sF]sF^sFetF]uFfuF[
vF`vF\wFaxF]zF\\lF^hqF`iq-Fdgt6'F[dmF]jnF/F0F_o>Fcjq-%&fopenG6$F[[r%&WRITEG-%(f
printfG61FcjqQG%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%a|+%aF;F>FIF\sF]s-F
^cn6$F^sFPFetF]uFfu7%F\\lF[vF`vF\w7$F`iqFaxF^hqFcs-%'fcloseG6#FcjqF;F;F;6#Fbo6(
F^_n7'FeoFfoFi\n"$>"Fd_l7'FeoFfoF]r"$6"Fd_lF^]r7'FeoFfoF]r"$g"Fjq7'FeoFfoF]rFed
pFjqF;,
I-readTemplatew,6#F%64F_cvF^cvFjbrFdipF4FigtF7FjamF_^sFS%'xspolsGFahtFdhsF\htFh
cm%$xE0GFggtF^bl6"F;C6>F>Fccv@$4-&%*FileToolsG6#%'ExistsGF]emY6$Q2File~%1~not~f
oundF;F>>FI-F\dv6$F>%%READG>F\s-%&parseG6#-%)readlineGF]em>F]sF[gv>F^sF[gv>FetF
[gv>F]u-F\^t6#-F^cn6$F[gvFgy>Ffu-&Ffw6#F\^t6#F[gv>F[vF[gv>F`vF[gv>F\wF[gv>FaxF[
gv>6$F]zF\\l&F[gvF;>F^hqF[gv>F`iqF[gv-FhdvF`_m>Ffu-Fbfm6$w,FgfmF;6$F\oF]oF;-Fc`
m6$F``o-Fcv6$FaqF\imF;F;6&F^blF[[rFjamFfu6#FG6$7'FeoFfoFfblF\alFioF^_mFfu>Fcjq7
,F^sF]sFet7$&F\sFdu-F]vF]\vF]uFfu-F[q6%-Fcv6$F*F\\lF*FG&F\wFduF^hqF]zO60F\sF]sF
^sFetF]uFfuF[vF`vF\wFaxF]zF\\lF`iqFcjqF;F;F;6#FG68F^_n7'FeoFfoF\dlF]goFer7'FeoF
foF]rF\]mF[`l7'FeoFfoFc`nF^flF^`l7'FeoFfoF]rFfflFd_lFe]rF]hsF]cqFe]rFa\vFc`lFb]
oFf`pF_`lF]cqF]alF]cqFe]rFbevF^hsFfbq7'FeoFfoF]rFj[sFirF;,
I.backwardErrorw,6&FfcmFO'F8FazFdip6+F]jnF[dm%$solGFhfmFh`s%$bweG%#nSG%"dG%#bbG
6"F;C+>F>F_^n>FI-Fd_tFbq>F]u-Fg]l6$Fg^lF[r>Ffu-%$minG6$F][oF]u>F\s7#-Fc`m6$-Few
6%F_oFjw-F^cn6$&F[r6$Fb\lF^sFP/F^s;FGF]u>Fet-F[ds6#-Fc`m6$*&F>Ffo-F]v6$*&-%$abs
G6#-F_cp6$Fhjo&FIF_bnFG-F\^t6#,&-F_cp6$Fhjo-Fep6$Fc]wFg]wFGFGFGFfo/F]sFjioFGFg
\w>Fet-F[jl6#-FjxF]\v@$FiatC%>F[v-F_y6%&Fet6#;FG!"#Fjw&FetF[bn>Ffu-&F[\w6#%&ind
exG6#F[v>Ffu-F[q6%2&F[vFjim,$%'DigitsG#FGFboFfuF]uO7&&FetF^x&Fet6#;,&FfuFGFGFGF
;-Fjdl6#F^`w-&%+StatisticsG6#%.GeometricMeanGFd`wF;F;F;6#Ffs6/F\]oFifo7'FeoFfoF
^dlF]goFd_l7'FeoFfoFg_lF\]mFd_l7'FeoFfoF_]oF]`lFd_lFg`p7'FeoFfoF]rFg_mFd_lFdcnF
dfnFfgo7'FeoFfoFgrF^^lFd_l7'FeoFfoFgrFhoFd_l7'FeoFfoF]rFcilFirF;,
I/templateSolverw,6&F%>%'showAMGF*>%'showCPGF*>%)showRREFGF*6=FdipF4FigtF7FjamF
_^sFgevFdhsF\htF.F/F3F_gnF]asF2Fb]lFhfmF\`mFjgtFh\lF]gnF6%#evG%#cpGFfhsF8F96"F;
C6>Feht&-FcevFbq6#7&-F]x6#;FboFgrF\dlF`rFedp@$-Fcco6$F*F[vYQOThe~case~of~incomp
lete~template~is~not~handledF;>Fcit&-Fas6'F`oF*FfuF*FG6#7$FGF]r>6%FaxF]zF\\l6$&
F\sFd\n-Fg]l6$;FboF]rF]u>F^hq-F^cn6$&F]s6#;,$FaxFfoF;FP>6$F[[rFf\r-F][m6$-Fgam6
$F`vF^sF\w>F[[r-Fi_m6%F[[rFf\rF]s>F[\u-Fi]n6%Fcv7#-F]x6#;FG-Fg]l6$Fg^lF[[rFet>6
$F[[rF]s6$&F[[r6$Fb\lF[\u&F]s6#F[\u@$0F]zF*C$>F[[r&F[[rF]iq>Feew6$,&&F[[r6$;,&F
]zFGFGFGF;FefwFG-Fdy6$&F[[r6$Fefw;FGF]z-Fdy6$-&Fex6#%.MatrixInverseG6#&F[[r6$F[
gwF[gw&F[[r6$F[gwFefwFfo&F]s6#Fefw>F\_u-&Fex6#%6ReducedRowEchelonFormG6#-Fjx6#F
[[r@$FiatC$-Fhv6#QFReduced~row~echelon~form~of~template:F;-%&printG6#-Fjx6#F\_u
>F]_u)-Faz6#-Fep6$w,Fg\lF;6$F\oF]oF;-F[q6%F\au-&Fgy6#%'columnG6$Fa[l<#/-Ff`mF]a
uFG,$)&Fb[l6$-Ff`m6$$FGF*&Fb[l6$Fb\l-Ff`m6$F^auFiz7#;,$Fa[lFfoF;F[hnFfoF;F;6,F4
FIF2F^hqF3FaxF]gnF\_uF7F]s6#FG6$7'FeoFfoFg[l"$t"FioFbim7#-F]x6#;FGFaxF[hn@$FfvC
$-Fhv6#Q.Action~matix:F;-Fghw6#-Fjx6#F]_u>F^_u&-FdxFj[xF\y@$FfdnC%>F[`u-%'facto
rG6#-&Fex6#%9CharacteristicPolynomialG6$F]_u%'lambdaG-Fhv6#QFFactorized~charact
eristic~polynomial:F;-Fghw6#-Fjx6#F[`u>F\`u-FhuF[y>Fg`u)-Faz6#7#-Fc`m6$7#-Fc`m6
$-F[q6%/&F[v6#F`iqFG*&&&F^_u6#,(F\`uFfoF`iqFGF\_wFGFidvFG&&F^_u6#FfoFidvFfo*&Fi
^xFGFe^xFfo/F`iq;FGF\`u/FcjqFc[xF[hn>Ff`u-F^\l6#&Fg`u6$Fb\l-Fd\l6$w,FgfmF;6$F\o
F]oF;-F[]l6$-F^]l6$&Faq6$F`[lF`oFc]l/F`[l;FGFa[lF;F;6(F8Fg`uFb]lF`iqFfhsF\`u6#F
G6$7'FeoFfoF^^lF[aoFioF_^lF`[xO6%Fg`uFf`u-F[_l6&F`vF\wFg`uF>F;F;F;6#FG6AFbcn7'F
eoFfoF]rFcilFd_l7'FeoFfoF]rFaamF[`l7'FeoFfoFj[lFj[sF^`lFg`pFdguF_`lFggoF_`lF^]s
FejvFdfn7'FeoFfoFgrFjqFd_l7'FeoFfoFgrF_evFd_l7'FeoFfoF]rFadpFd_l7'FeoFfoF]rFg]s
F[`l7'FeoFfoFj[lFdrFjq7'FeoFfoFaimFcilFjq7'FeoFfoF]r"$)=Fd_lFhbq7'FeoFfoFjqFb\m
Fjq7'FeoFfoF[`lFg^mFjq7'FeoFfoF]rFacmFd_lFdfn7'FeoFfoFgrFh[lFd_l7'FeoFfoFgrFhrF
jq7'FeoFfoFh`lFaimFjq7'FeoFfoF]rFgqFd_l7'FeoFfoF]rF__pFd_lFi`lFb\vF;,
I+iniProblemw,6)F%'%+sparsePolsGFPFgcm'FdhsF[cr'%$symGF^crFg\tF^^o61F.F]jnF/F0F
[dmF]]tFe`sF^]t%$nuFGF1%#dmG%#d0G%#UPG%#v1G%#v2G6"F;C1>6(F>FIF\sF]sF^sFet-Fas6'
F`oF[rF][oFgboF^co@%/F\_oF*>F]uFet>F]uF_o>Ffu7#-F__t6$F*F^s>F[v-FhdmF]em-Fhv6%Q
)%-40s%a|+F;Q7Number~of~polynomials:F;FI-Fhv6%F_dxQ=Sparse~constant~polynomials
:F;F]u-Fhv6%F_dxQ5Polynomials~removed:F;Ffu-Fhv6%F_dxQ5Number~of~monomials:F;-F
hu6#&-Fibl6$F>F\sF\y-Fhv6%F_dxQ+Variables:F;F\s-Fhv6%F_dxQ)Degrees:F;-Fep6%F_dl
F>F\s-Fhv6%F_dxQ6Degrees~by~variables:F;-Fbfm6$w,FdbtF;6$F\oF]oF;-Fep6$w,FfzF;6
$F\oF]oF;-F_dl6$&Faq6#Fd`o<#F`oF;F;6&F.F`[lFb]lF`o6#FG6$7'FeoFfoFdrF]`nFio7'Feo
FfoFdrFaimFioFaqF;F;6&F/F\sF.F>6#FG6$7'FeoFfoFeilF[`nFio7'FeoFfoFeilFailFioF>>F
`v-Fgt6%F[vF]sF^fm>F\w-&Fht6#%1HilbertDimensionG6$F`vF^fm@%0F\wF*C'-Fhv6%Q)%-40
s%s|+F;Q1Number~of~roots:F;Q$infF;>F]z-Fep6&&Fht6#%5UnivariatePolynomialGF\sF[v
F^fm>6$F\\lF^hq-Fjfr6$w,FdbtF;6$F\oF]oF;-%&evalbG6#FfbtF;F;6$FjbxF]z6#FG6$7'Feo
FfoFi^mFcalFio7'FeoFfoFi^mFc_lFio7#-F]x6#;FGF_\r-Fhv6'Q-%s%a%-25s%a|+F;Q/Variab
les~for~F;F\wQ1-dim.~component:F;&F\s6#F\\l@%/-FhuFdiqF*>FaxFGC$>Fax-F[\w6#-Fep
6$w,6#%"vGF;6$F\oF]oF;,&-FcelF_qFG-%(ldegreeGF_qFfoF;F;Faix6#FG6$7'FeoFfoF^^lFi
inFioF_^lF^hq-Fhv6%F_dxQ8Number~of~roots~(sat.):F;FaxC$>Fax-Fhu6#&-F`uFdvFdu-Fh
v6%F_dxF`hxFaxO6(F^sFIF\sF]s-F[q6%/Fc[oF*FaxFGF]uF;F;F;6#Fgr6>F]ilFgbq7'FeoFfoF
]rFd_mF[`l7'FeoFfoFi^mF[`lFd_l7'FeoFfoFirFaimFd_lFggoF\bx7'FeoFfoF]rF[]nFjq7'Fe
oFfoF]rF[aoFjq7'FeoFfoF]rFirFjq7'FeoFfoF]rFe`pFjq7'FeoFfoF]rF_dpFjq7'FeoFfoF]rF
h`lFjq7'FeoFfoF]rF[cuFjqFf]rF_hsFdfn7'FeoFfoFgrFirFjq7'FeoFfoFgrFahmFd_l7'FeoFf
oFgrFf`lFd_l7'FeoFfoFgrF_alFjqF\dp7'FeoFfoFa_nFd`lFd_l7'FeoFfoF`rFeilFd_l7'FeoF
foF`rF[aoFjq7'FeoFfoFgrFhqFd_l7'FeoFfoFgrFhqFjq7'FeoFfoF]rFiinFirF;,
I/templateFinderw,6-F%>'%(dChangeGF^crF*>Fh\tF*>Fa^oFcs>FdhsFcs>Fc^oFcs>%,prime
NumberG"&4+%>FaapF]r>F`dnFG>FbbxFcs>FebxF*65Fh\v%#TMGF[dmF]jnF/F0FdipFe`sFdapF_
[wF\`mF7FjamF[^o%#mdGFf^o%#dlGF4Fhcq6"F;C,>%#TDGF\an>F>F*>F]zFcs>F\\l<">Fcjq-Ff
]t6#-F]x6$Q"-F;Ficn>FIF`_o>6(F\sF]sF^sFetF]uFfu-F^bx6)F`oF^bqF^coFc[o9.F[rFc_q>
F[v-F]ap6$F^sFh_o?(F`vF*FGF;555Fd_o30F]uFG4-Fcv6$F]u-Fep6$w,6#FggtF;6$F\oF]oF;F
djrF;F;F;6#FG6$7'FeoFfoF[aoFaimFio7'FeoFfoF[aoFailFioFd_y4-Fcv6$FG-Fep6$w,FdayF
;6$F\oF]oF;F`jrF;F;F;6#FG6$7'FeoFfoFb`pF^goFio7'FeoFfoFb`pFj\sFioFd_y3/F]uFG2F>
,$F^^qFboC&@$/F`vF*-Fhv6)Q;%-15s%-15s%-15s%-15s%s|+%s|+F;Q"dF;Q,#cols-#rowsF;Q&
#rowsF;Q'degreeF;F]avFcjq>6(F\wFaxF]zF\\lF^hqF`iq-F[q6%1F`vF_o-Fd]o6*F\sF]zF\\l
F^sF^coFc_qF][oFgbo-Fjgo6)F\sF]zF\\lF^sFetFc_qF][o-Fhv6(Q8%-15g%-15g%-15g%-15g%
g|+F;F`v,&-Fg]l6$Fg^lF\wFG-Fg]l6$Fi]lF\wFfoFbdyF^hqF`iq?&F[[rF[vFeemC'>6$Ff\rF`
iq-Ffer6*F\wFaxF]zF[[rF^sFetF]uF^co@$/Ff\rF*\-%#+=G6$F>FG>-Fd_yF]em7&Fe\uFfuF^c
oFc[o-Fc\v6)-Fd_yF[_xF>F\sF^sFetF`iqFG-Fhv6%Q*|+%-12s%g|+F;Q,Total~time:F;F^`pF
;6#Fd_yF;6#FG68Fbcn7'FeoFfoFarF^dlFer7'FeoFfoF\dlF`amFer7'FeoFfoFe`pF\]mFd_l7'F
eoFfoF_]oFaamFd_l7'FeoFfoFb`pFiguFd_lF[go7'FeoFfoF]rFj]sFd_lF_cqFecn7'FeoFfoFgr
Fi`pF[`l7'FeoFfoFg[lFi]rFjq7'FeoFfoFgr"$k"Fd_l7'FeoFfoFgrFi`oFjq7'FeoFfoFgrFedp
Feam7'FeoFfoF`rFahmFd_l7'FeoFfoF`rFc`nF[`l7'FeoFfoF^^lF*Fadp7'FeoFfoF`rFg[lFjq7
'FeoFfoF`rFiinFd_l7'FeoFfoF`rFg_lFjq7'FeoFfoF]rFhqFjqF;,
I2templateReductionw,6%F%Ff\v>%)nRootTolGF*6=F^_yFe`sFhcmFdhsF/F0F[dmF`jn%#A2GF
jamF\`mF7F4FdipF3F[asF]`mFe^oFapF`_yFh`sF`bm%#V2G%#M2GFgipFhcqFf^o6"F;C1>%$td1G
F_o>F[\u-Ff]t6#-F]x6$F^`yFeer>F>F`_o>6%FIF\sF]s6%&F_o6#Feam&F_o6#F\dl&F_o6#Far>
Fgeq&-Fas6'F`oF\sF]sF*FG6#7%F]rFfsFj\o>6$F[vFfu-Fjfr6$w,F_bmF;6$F\oF]oF;-Fcv6$F
gbmFaqF;F;6$Fe`sFI6#FG6$7'FeoFfoFa_nF]cmFio7'FeoFfoFa_nFcamFio&F_o6#Fa_l>6$FfuF
[v6$-F[jl6$Ffuw,F^jlF;6$F\oF]oF;-Fd^p6%F_\nFhbmFaqF;F;6$F0Fet6#Fbo6$7'FeoFfoFj[
lFhrFio7'FeoFfoFj[lFgoFio-F[jl6$F[vw,F^jlF;6$F\oF]oF;FhjyF;F;Fjjy6#Fbo6$7'FeoFf
oF^flF[`nFio7'FeoFfoF^flFdblFio>F`v7$Fj`qFcaq>6$F\wFax-F][m6$-Fgam6$F]uF`vF^s>6
(F]zF\\lF^hqF`iqFcjqFfu6(F_^pF_\nFejrF\wFaxF`v>F[[r-Fhu6#F`v>Ff\r-F[q6%1FarF[[r
-%%ceilG6#,$F[[r#FGFarFar-Fhv6)Q<|+%-20s%-20s%-20s%-20s%s|+%s|+F;Fi`vFj`vF[avF
\avF]avF[\u?(F\_uFGFGF[[rFeemC.>F]_u&F`vFjhw>F[v-F_cp6$/F]_uF^gmFfu>F[`u&F`iq6$
-F_cp6$/-Ff`m6$F]_uFfuF^gm7#-F]x6#;FG-Fg]l6$Fi]lF`iqFb\l>F\`u-Fep6$w,F_elF;6$F
\oF]oF;-Ff`m6$F`oFaqF;F;6$F]`mFcjq6#FG6$7'FeoFfoFb`lF]cmFioFidq-Fdal6$*&&F]u6#&
F]_uFduFG&F]_uF\yFGF^s>F\`u-Fi]n6%Fcv7#-F]x6#;FG-Fg]l6$FGFcjq-Fd\l6$w,Fg\lF;6$F
\oF]oF;-Fc\q6#&FaqF]]qF;F;6$FhgyF[`u6#FG6$7'FeoFfoFhqFd_mFio7'FeoFfoFhqF[]nFioF
\`u>6$F^_uF[`u6$&FcjqFc`u&F[`u6$Fb\lF\`u>6$Fg`uFf`u-Ffer6*F[`uF^_uF[vF]zF^sFetF
\\lF\s@$/-Fegn6$F\_uFf\rF*-Fhv6$Q0%d%%~completed|+F;,$*&F\_uFGFf\rFfoFar@$5/Fg`
uF*2,&F^hqFGF[rFG&&Fg`uFd\nFd\n\@$2FfbzF^hq>F^hqFfbz>6&F`iqFcjqFfuF\hy6&F[`uF^_
uF[v7&&Fg`uF;FIF\sF]s-Fc\v6)F\hyFGF]uF^sFetFf`uF*-Fhv6%FheyFieyFffrF;6#F\hyF;6#
Fbo6A7'FeoFfoFjqFa_lFio7'FeoFfoFarFg[lFer7'FeoFfoF]`lF_evFd_lF[go7'FeoFfoF]rFb
\mFd_lFaguF^hs7'FeoFfoF]rFg[tFd_l7'FeoFfoF]rFg[lFd_lFggoFagu7'FeoFfoF]rF__nFd_l
F]al7'FeoFfoF]rF_evFjqFecn7'FeoFfoFgrFb`lFd_l7'FeoFfoFgrFcamFd_l7'FeoFfoFgrFj[s
Fd_l7'FeoFfoFgrFj`lFd_l7'FeoFfoFgr"#%)Fd_l7'FeoFfoFgrFerFd_l7'FeoFfoFgrFicnFd_l
7'FeoFfoFgrFe`pF[`l7'FeoFfoF`^lF[aoFjq7'FeoFfoFgrFg^mF[`l7'FeoFfoF\alF*Fadp7'Fe
oFfoFgrFhrF[`l7'FeoFfoFcamF]cmFd_lFcftFj]yF_gyF;,
I+alterCommaw,6#'F][yFPF;6$F\oF]oF;-Ff]t6%Q"[F;&-&Fg`m6#%+InterleaveG6$F`o7#-F]
x6$Q",F;,&F_^nFGFfoFGF;Q"]F;F;F;F;6#FG6$7'FeoFfoFcrFf_mFio7'FeoFfoFcrFfflFioF;,
I*printLinew,6#'%%lineGF'F;6$F\oF]oF;-Fhv6$Q.%-60swritten|+F;F`oF;F;F;6#FG6$Fdf
u7'FeoFfoFedpF`^lFioF;,
I,commonCode1w,6('F^cvF_^o'%#fbGF'FgipF\`mFjbrF_gn6*%#MtG%#iMG%#eMGFh\l%#M0G%$M
0tG%$iM0G%$eM0G6"F;C&>F>-F^cn6$&F][o6$;,&FgboFGFGFGF;Fb\lFX>Fjep6$7#-Fdfm6$F>%+
indexorderG7#-%(entriesG6%F>F^iz.%'nolistG-F`dv6$F`o-Ff]t6.F_oQ,M~=~sparse(F;-F
bav6#-Fep6$w,FdbtF;6$F\oF]oF;FgbmF;F;F;6#FG6$7'FeoFfoFhrFg^mFio7'FeoFfoFhrFiinF
ioFIF_fz-Fbav6#-Fep6$w,FdbtF;6$F\oF]oF;FhbmF;F;F;6#FG6$7'FeoFfoF\apF]`lFio7'Feo
FfoF\apF]`nFioFIQ$,C(F;-FbavFhanQ#),F;&Fc[oFduF_fz,&Fb[vFGFgboFGQ$);|+F;@$0Fgbo
F*C(>F]sw,FhgpF;6$F\oF]oF;-F[q6%0F`oF*-FbjlFbqF*F;F;6$FgipF[r6#FG6$7'FeoFfoFedp
Fd`lFioFefu>F^s-Fdy6$-F_gw6#-Fep6$w,FhgpF;6$F\oF]oF;-FaqFbqF;F;6$Fh\lF]s6#FG6$7
'FeoFfoFcalFirFio7'FeoFfoFcalFacmFio&F][o6$;FGFgboFc][l-Fep6$w,FhgpF;6$F\oF]oF;
F[][lF;F;F\][l6#FG6$7'FeoFfoFj`l"#!)Fio7'FeoFfoFj`lFj[sFio&F][o6$Fc][lFghz>Fet-
F^cn6$F^sFX>F^[p6$7#-Fdfm6$FetF^iz7#-Faiz6%FetF^izFciz-F`dv6$F`o-Ff]t6/F_`vF_oQ
-M0~=~sparse(F;-Fbav6#-Fep6$w,FdbtF;6$F\oF]oF;FgbmF;F;F;6#FG6$7'FeoFfoF[[mFh[lF
io7'FeoFfoF[[mF^flFioF]uF_fz-Fbav6#-Fep6$w,FdbtF;6$F\oF]oF;FhbmF;F;F;6#FG6$7'Fe
oFfoFagoFg_mFio7'FeoFfoFagoF[cuFioF]uF_fz-FbavFjimF_fzFgboF_fzFb[vFc[[l-F`dv6$F
`o-Ff]t6(F_oQ)M~=~M(:,F;FhhzQ-:end)-M(:,1:F;FgboQE)*M0;~%%~Schur~complement~red
uction|+F;F;F;F;6#Fa_l6-F__lFc_nFi`l7'FeoFfoF]r"$i"FjqFdfn7'FeoFfoFgrFd`lFd_l7'
FeoFfoFgrFb`pFd_lFfdz7'FeoFfoFgrFf_mFd_l7'FeoFfoFgr"$m"Fjq7'FeoFfoFgrFj_lFjqF;,
I,commonCode2w,6'FegzFfgzF3Ffhs%$iiqG6$%%iiq1G%%iiq2G6"F;C+>F`an-Fjfr6$w,FdbtF;
6$F\oF]oF;/Fb^mFGF;F;6$Fha[lFc[o6#FG6$7'FeoFfoFi^mF_dpFioFeixF]gs-F`dv6$F`o-Ff]
t6$F_oQ1[V,|ir]~=~eig(T);|+F;@&32F*F\em2F\emF][o@%/F\emFG-F`dv6$F`o-Ff]t6*F_oQ#
S(F;FiarQ),:)~=~V(F;,*F[rFGF][oFfoFfoFGFiarFGQ(,:)./V(F;F[rQ&,:);|+F;-F`dv6$F`o
-Ff]t6,F_oFgc[l-FbavF]emFhc[l-Fbav6#-&Ffw6#%"+G6%,(F[rFGF][oFfoFfoFGFjwF>Q/,:).
/repmat(V(F;F[rQ%,:),F;F\emQ&,1);|+F;/F\emF][o-F`dv6$F`o-Ff]t6,F_oQ'S~=~V(F;,&F
[rFGF][oFfoQ":F;,&F[rFGFfoFGFid[lF[rFjd[lF][oF[e[l@&32F*Fa[o2Fa[oF][o@%/Fa[oFG-
F`dv6$F`o-Ff]t6*F_oFgc[l&FIFduFhc[lF[rFjc[l,*F[rFGF][oFfoFfoFGF_f[lFGF[d[l-F`dv
6$F`o-Ff]t6,F_oFgc[lF\bvQ0,:)~=~repmat(V(F;F[rFjd[lFa[oQ(,1)./V(F;-Fbav6#-Fdd[l
6%Fhd[lFjwFIF[d[l/Fa[oF][o-F`dv6$F`o-Ff]t6,F_oQ.S~=~repmat(V(F;F[rFjd[lF][oFff[
lFbe[lFce[lFde[lF[d[l-F`dv6$F`oF_`v-F`dv6$F`o-Ff]t6$F_oQFI~=~|irisnan(S(1,:))~&
~|irisinf(S(1,:));|+F;-F`dv6$F`o-Ff]t6$F_oQ_o%%I~=~I~&~|irimag(S(1,:));~%%~unco
mment~this~line~for~real~roots~only|+F;-F`dv6$F`o-Ff]t6$F_oQ.S~=~S(:,I);|+|+F;-
F`dv6$F`oQ$endF;F;F;F;6#Fj\o64F__lF^hs7'FeoFfoF]rFd_lFjqFdfnF\dp7'FeoFfoF`rF\\t
Fjq7'FeoFfoF`r"$Z"Fjq7'FeoFfoFgrF\\tFjqFdfnF\dpFhh[lFih[lF[i[lFeguF^ip7'FeoFfoF
]rFg]sFjqF_]y7'FeoFfoF]rFjqFjqF;,
I,writeSolverw,6,F%'%$dirGF''FgipFaz'FfhsFicmFa`sFibr'Figt-FP6#F^cr'FahtFh]o'F_
gnF^cr'Fha[lFP6(%%mxn0GF[epF[htF3F^cvFggz6"F;C6>F>7#-Fg]l6$FGF[r>FI,&&F^coFduFG
Fc_qFfo>F\s&F^coF\y>F]s&F^coFd\n>FetQ%~~~~F;>F^s-F\dv6$-Ff]t6*F_oQ&/red_F;&Fgbo
FduQ"xF;&FgboF\yQ"_F;F`oFi]tF^dv-F`dv6$F^s-Ff]t6'QH%%~Input:~coefficient~matrix
~C~of~size~F;FiarFc[\l&F>F\yF_`v-F`dv6$F^s-Ff]t6'QF%%~Output:~solution~matrix~S
~of~size~F;F][oFc[\lF]sQ#|+|+F;-F`dv6$F^s-Ff]t6)Q2function~S~=~red_F;Fb[\lFc[\l
Fd[\lFe[\lF`oQ&(C)|+|+F;-Fbgz6(F^sFetF[rFc[oFgboFc_q-F`dv6$F^s-Ff]t6'F_`vFetQ4[
L,|ir,P]~=~lu(M(:,1:F;FIQ%));|+F;-F`dv6$F^s-Ff]t6$FetQ)P~=~P';|+F;-F`dv6$F^s-Ff
]t6(FetQ.M~=~[P*L~P(:,F;,&FIFGFGFGQ,:end)]\M(:,F;Fj]\lQ(:end);|+F;-F`dv6$F^s-Ff
]t6&FetQ+M~=~M(end-F;,&F\sFGFfoFGQ+:end,:);|+|+F;-F`dv6$F^s-Ff]t6&FetQ+T~=~zero
s(F;F]sFc[[l-F`dv6$F^s-Ff]t6*FetQ#T(F;-Fbav6#&Fh_oFduQ.,:)~=~-M(:,1:F;F\sQ')\M(
:,F;FafsF\^\l-F`dv6$F^s-Ff]t6&FetF]_\l-Fbav6#&Fh_oF\yQ))~=~1;|+|+F;-Fea[l6'F^sF
etF]sF][oF^bq-FhdvFijo-Fffz6#-Ff]t6)Q%red_F;Fb[\lFc[\lFd[\lFe[\lF`oFi]tF;F;F;6#
Far67F__l7'FeoFfoF\dlFa_nFer7'FeoFfoFcamFd_lFd_l7'FeoFfoF[`lFh`lFd_l7'FeoFfoFg^
mFaimFd_l7'FeoFfoF_]oF]`nFd_l7'FeoFfoF]rFahmFd_l7'FeoFfoF]rF]`nFjq7'FeoFfoF]rF_
alFjq7'FeoFfoF]rFf_mFjq7'FeoFfoF]rFdamFjqF^ipF^a\l7'FeoFfoF]rFd_mFjq7'FeoFfoF]r
Fg_lFjqF_gy7'FeoFfoF]rF[`nFjq7'FeoFfoF]rFeilFjqF^a\lFbev7'FeoFfoF]rFhblFjqF;,
I2writeSolverColpivw,6-F%Fai[lFci[lFdi[lFa`sFibrFei[l'FahtFPF3Fii[lFji[l6(F\j[l
F[epF[ht%#nPGF^cvFggz6"F;C:>F>F`j[l>FI,&Fej[lFGF^bqFfo>F\sFgj[l>F]sFij[l>FetF[[
\l>F^s-F\dv6$-Ff]t6+F_oQ"/F;Fb`\lFb[\lFc[\lFd[\lQ)_colpiv_F;F`oFi]tF^dvFf[\l-F`
dv6$F^s-Ff]t6'F`\\lF][oFc[\lFc_qFa\\l-F`dv6$F^s-Ff]t6)Ff\\lFb[\lFc[\lFd[\lFhb\l
F`oFg\\l-Fbgz6(F^sFetF[rFc[oFgboF^bq@%0FIF*C&Fj\\lF`]\lFe]\l-F`dv6$F^s-Ff]t6&Fe
tQ,M~=~full(M(F;Fj]\lQ+:end,:));|+F;-F`dv6$F^s-Ff]t6%F_`vFetQ.M~=~full(M);|+F;@
$0F\sF*C%-F`dv6$F^s-Ff]t6'F_`vFetQ4[L,U,P]~=~lu(M(:,1:F;F\sF_]\lF`]\l-F`dv6$F^s
-Ff]t6(FetFi]\lFafsF[^\lFafsF\^\l-F`dv6$F^s-Ff]t6&FetQ*M1~=~M(1:F;F\sF[d[l-F`dv
6$F^s-Ff]t6&FetQ(M2~=~M(F;FafsFc^\l-F`dv6$F^s-Ff]t6&FetQ9[Q,R,P]~=~qr(M2(:,1:en
d-F;FegsF_]\l-F`dv6$F^s-Ff]t6(FetQ3A~=~U\[M1(:,1:end-F;FegsQ.)*P~M1(:,end-F;F][
oQ):end)];|+F;-F`dv6$F^s-Ff]t6*FetQ+B~=~R(:,1:F;,(Fb[\lFGFIFfoF\sFfoQ()\[R(:,F;
,*Fb[\lFGFIFfoF\sFfoFGFGQ3:end)~Q'*M2(:,end-F;F][oFbf\l-F`dv6$F^s-Ff]t6(FetQ/M~
=~[-A(:,end-F;,&Fc_qFGFfoFGQ1:end)+A(:,1:end-F;Fc_qQ,)*B;~-B];|+|+F;-F`dv6$F^s-
Ff]t6.FetQ'P1~=~[F;,&F]sFGFGFGFce[l,&F]sFGF\sFGQ%~(1:F;,(F]sFGF][oFfoFfoFGQ%)*P
~F;,&F]sFGF][oFfoFce[lF]sQ$];|+F;-F`dv6$F^s-Ff]t6&FetQ&P2~=~F;-FbavFg_oQ#;|+F;-
F`dv6$F^s-Ff]t6)FetQ5T~=~getT(M,P1(1:end-F;Fc_qQ*),P1(end-F;Fag\lQ&:end)F;Q(,P2
);|+|+F;-Fea[l6'F^sFetFc_qF][oFd`yF]`\l-Fffz6#-Ff]t6)Fb`\lFb[\lFc[\lFd[\lFhb\lF
`oFi]tF;F;F;6#F`r6CFhczFe`\lFf`\lFg`\l7'FeoFfoFg^mFh[lFd_l7'FeoFfoFahmFi\nFd_l7
'FeoFfoF]rF\apFd_lF[a\lF\a\l7'FeoFfoF]rFi\nFjqF^a\lFdfn7'FeoFfoFgrFdrFjq7'FeoFf
oFgrF]goFjq7'FeoFfoFgrFhflFjq7'FeoFfoFgrFhblFjq7'FeoFfoFgrF^`lFjqFdfnF[j\lF\j\l
F]j\lF_gy7'FeoFfoF]rFiinFjq7'FeoFfoF]rFf`lFjq7'FeoFfoF]rFaamFjq7'FeoFfoF]rFi[tF
jqFji\l7'FeoFfoF]rFj\sFjq7'FeoFfoF]rFadpFjq7'FeoFfoF]rFaalFjqF^a\lFbevF^]yF;,
I2writeInidataCoefsw,6$F%Fai[l6.Fj\t%#_CG%&_nameG%&_sizeG%#AsG%#CsG%#ClGF^cvFb]
l%"eG%$idxGFggz6"F;C:>FaxF[[\lAFc]tAFe]t>F>F[^t@$4Fb^tC$-Fhv6#QUCoefficient~fil
e~cannot~be~created~for~this~problem|+F;OF*>FdhyFav@$4-F_fvF]_o-&F`fv6#%.MakeDi
rectoryGF]_o>Ffu-F\dv6$-Ff]t6&F_oQ./inidata_num_F;F`oFi]tF^dv-F`dv6$Ffu-Ff]t6%Q
=function~data~=~inidata_num_F;F`oQ$()|+F;-F`dv6$Ffu-Ff]t6&FaxQ0data~=~cell([1,
F;F^bnQ%]);|+F;?(F[vFGFGF^bnFeem@%/&F]sFc_wFi]l-F`dv6$Ffu-Ff]t6&FaxQ&data|frF;F
[vQ,|hr~=~randn;|+F;-F`dv6$Ffu-Ff]t6(FaxFb^]lF[vQ+|hr~=~randn(F;&-Fbav6#F]^]l6#
;FboF\_wFc[[l-F`dv6$FfuFdh[l-FhdvFjim-Fffz6#-Ff]t6%Q-inidata_num_F;F`oFi]t>Ffu-
F\dv6$-Ff]t6&F_oQ(/coefs_F;F`oFi]tF^dv-F`dv6$Ffu-Ff]t6%Q4function~C~=~coefs_F;F
`oQ)(data)|+|+F;?(F[vFGFGF_\rFeem-F`dv6$Ffu-Ff]t6'Fax&F\sFc_wQ)~=~data|frF;F[vQ
$|hr;|+F;-F`dv6$FfuF_`v?(F[vFGFGFa[oFeemC&@$/F[vFboC$>F^s-F^cn6$&-Faco6%Fg]lF*-
Fd\l6%F^t-F^cn6$&FIF\yF]^o%)functionGFduF'-F`dv6$Ffu-Ff]t6*F_`vFaxF^sQ*~=~C(:,1
:F;-Fg]l6$Fi]lF_f[lQ')\C(:,F;,&Fbb]lFGFGFGQ):end);|+|+F;-F`dv6$Ffu-Ff]t6(FaxQ+C
~=~zeros(F;-Fg]l6$Fi]l&FIFc_wF_fz-Fg]l6$Fg^lF^c]lQ%);|+|+F;>6$FetF]u6$-Fegl6$-F
^cn6$F^c]lF]^o<#F*-F^cn6$F^c]lFP?&F`vFetFeemC$>F\w7#-F__t6$F`vF]u-F`dv6$Ffu-Ff]
t6(FaxQ#C(F;-F[q6%/Fd]xFGF]jv-FbavF[yQ%)~=~F;-F^cn6$F`vF'Ffh\l-F`dv6$Ffu-Ff]t6%
F_`vFaxQVC~=~C./repmat(sqrt(sum(C.*conj(C),2)),1,size(C,2));|+|+F;F^_]lF`_]l-Ff
fz6#-Ff]t6%Q'coefs_F;F`oFi]tAFjetF;F;F;6#Fbo6JFhcz7'FeoFfoFf`lFahmFd_lFaftFbftF
_cq7'FeoFfoF]r"$B"F[`l7'FeoFfoFb\mF^goFjq7'FeoFfoFi]rF__pFirFc`lFcjv7'FeoFfoFho
F^flFjqF`]rF^ip7'FeoFfoF]rFailFjqFecnF\dp7'FeoFfoFi^mFahmFjq7'FeoFfoFedpF]`lFjq
F]i[lFbev7'FeoFfoF]rF]cmFjqFg`pFba\lFecn7'FeoFfoFgrFg^mFjqFeguFecnF\dp7'FeoFfoF
`rFi`oFd_l7'FeoFfoF`rFi`pFjq7'FeoFfoFgr"#"*FjqFgdzFhfy7'FeoFfoF`rFcalFd_l7'FeoF
foF`rF__pFjq7'FeoFfoF]rFeerFjqF]i[lFbevF^cqFbgtF;,
I-writeTestNumw,6)F%Fai[l'%"UGFgyFOFibr'FdipFicm'F^bw%(booleanG6%F^cvFggz%$fb2G
6"F;C<>FIF[[\l>F\s-Ff]t6$FIFI@$Fb\]lFd\]l>F>-F\dv6$-Ff]t6&F_oQ+/test_num_F;F`oF
i]tF^dv-F`dv6$F>Q*rng(23);|+F;-F`dv6$F>Q,N~=~10000;|+F;-F`dv6$F>-Ff]t6%Q%d~=~F;
FgboQ$;|+|+F;-F`dv6$F>-Ff]t6%Q;stats~=~struct('problem','F;F`oQL','tm',[],'err'
,[],'k',[],'kr',[],'N',N);|+|+F;-F`dv6$F>Q.for~i~=~1:N|+|+F;-F`dv6$F>-Ff]t6&FIQ
4data~=~inidata_num_F;F`oQ?();~%%~generate~initial~data|+|+F;-F`dv6$F>-Ff]t6$FI
Q%try|+F;-F`dv6$F>-Ff]t6&F\sQ+C~=~coefs_F;F`oQV(data);~%%~compute~coefficients~
of~polynomial~system|+F;-F`dv6$F>-Ff]t6$F\sQ&tic;|+F;-F`dv6$F>-Ff]t6*F\sQ)S~=~r
ed_F;Fa[[lFc[\lFb[v-F[q6%F^coFhb\lFe[\lF`oQA(C);~%%~solve~polynomial~system|+F;
-F`dv6$F>-Ff]t6$F\sQ<stats.tm~=~[stats.tm~toc];|+F;-F`dv6$F>-Ff]t6$F\sQ>if~isem
pty(S);~continue;~end|+F;-F`dv6$F>-Ff]t6(FIQ*catch~ME|+F;F\sQ+continue;|+F;FIQ&
end|+|+F;-F`dv6$F>-Ff]t6(FIQ)mon~=~@(F;&-FbavFdjpF\_]lQ#)~F;-Fbav6#-F^cn6$F[rFP
Ffh\l-F`dv6$F>-Ff]t6$FIQfn[err,k,kr]~=~numerr(C,mon,S,d);~%%~compute~numerical~
error|+F;-F`dv6$F>-Ff]t6$FIQ>stats.err~=~[stats.err~err];|+F;-F`dv6$F>-Ff]t6$FI
Q8stats.k~=~[stats.k~k];|+F;-F`dv6$F>-Ff]t6$FIQ<stats.kr~=~[stats.kr~kr];|+|+F;
-F`dv6$F>Fg\^l-F`dv6$F>Q5disp_stats(stats,1);F;-FhdvF]em-Fffz6#-Ff]t6%Q*test_nu
m_F;F`oFi]tF;F;F;6#Fgr6>F^_n7'FeoFfoFcrF^^lFd_l7'FeoFfoF`^lF]cmFd_lFcjvF`f]lF_h
s7'FeoFfoF]rF`^lFjq7'FeoFfoF]rFcamFjqF_]y7'FeoFfoF]rFj_lFjq7'FeoFfoF]rFc_lFjqF
\g]l7'FeoFfoF]rFerFjq7'FeoFfoF]rF\\tFjq7'FeoFfoF]rFd`lFjq7'FeoFfoF]r"$E"FjqF`j
\l7'FeoFfoF]rFeboFjq7'FeoFfoF]rFaimFjqFa]y7'FeoFfoF]rFcilFjqF`]yFcdpF`j\l7'FeoF
foF]rF^dlFjq7'FeoFfoF]rFc`nFjqFbevF_]yF;,
I,iniTemplatew,Feev6>F.F/F0FjbrFdipF4FigtF7FjamF_^sFSFgevFahtFdhsF\htFhevFha[lF
[dmFgip%#U0GFag]l%#U1GF]`mF[epF[htF3F_gnF_hu6"F;C->6%F>FIF\sF_s>6/F]sF^sFetF]uF
fuF[vF`vF\wFaxF]zF\\lF^hqF`iq&Fcbw6#7#-F]x6#;FGFcr>Fcjq-F]en6%-Fep6$w,FdbtF;6$F
\oF]oF;-F[q6%-FcvF]_zFfoFGF;F;6$FdhsF\\l6#FG6$7'FeoFfoF`_lF]goFio7'FeoFfoF`_lFb
`lFio7#-F]x6#;FGFa[oFjwF^hq>6$Ff\rF[\u-F][mF`an>F\_u-Ffil6$F[\uF\s>Ff\r-Fi_m6%F
f\rF[\uF\_u>F]_u-F_cp6$-Few6%&FIF`jxFjw-F_y6%FGFjwFgc^lF\_u>F^_u&Ffu6#-Fi]n6%Fc
v7#-F]x6#;FG-Fg]l6$FGFfuF`v>6&F[`uF\`uFg`uFf`u6$F^aq&FaxF\y>Fiau7$-Fecl6$-F^cn6
$F`iqF]^o-Fep6$w,Fg\lF;6$F\oF]oF;F`qF;F;6$F]`mF^_u6#FG6$7'FeoFfoF]goFcalFio7'Fe
oFfoF]goF_dpFioF\w-F^cn6$&Ffu6#;FGFf`uF]^oO62FIF\sFetFf\rF\_uF]_uFfu7%,&F[`uFGF
c\zFfoF\`uFg`uF]zF[vF`vF]sF^sFaxFiauFcjqF;F;F;6#FG6.F__lFf_lFa`pFaguF_`lFh_lF_`
lF`\vF^]sF]alFi`l7'FeoFfoF]rFi]rFirF;,
I0solverGeneratorw,6)F%>%'colpivGFG>%0createCoefsFileGF*>%1createSolverFileGFG>
%/createTestFileGF*>'%(rootDirGF'Q+../solversF;>%'showPMGFG6BFbi[lF/F0F4FgipFag
]lFi`^lF7FigtFahtFjamF_^sFjbrFdipFgevF_huFha[lF_gnF]asF`]vF]`mFa]v%$iT1GF^bw%#i
CG%#jCG%#C1GF.F^blFhfmF\`mFjgt6"F;C:@$4-F_fv6#Fgbo-Fe\]lF_h^l>F>-Ff]t6%FgboFgb
\lF`o@$F]fv-Fe\]lF]em@$Ffdn-Fgj\lF]hl@$3Fe\y/F][oF*OF;>62FIF\sF]sF^sFetF]uFfuF[
vF`vF\wFaxF]zF\\lF^hqF`iqFcjq-Fe`^lFbq>Fcdw-Fg]l6$FjcwF^hq>F[\u&Ffu6#-Fi]n6%Fcv
F_d^lFax>6$F\_uF]_u-F[hu6'F[\uF]sFIF\sF`iq@$Fi_v-Fhv6%Q@|+%a~permissible~monomi
als:|+%a|+|+F;&F]_uFd\n&F\_uFd\n>F[`u-F_ix6#32&F[vFd\nF_j^lFfv@$Fgct-F]g]l6)F`o
F>FetFIF]zF\\lF[`u@$Fjh^lOF;@$-Fcco6$F*FcjqYQWSolver~file~cannot~be~created~for
~incomplete~templatesF;>F\`u7#-Fdfm6$F`^[lF^iz>Fg`u-Fep6$w,FhgpF;6$F\oF]oF;,&Fg
bmFG*&,&FhbmFGFfoFGFGFf]lFGFGF;F;6$FgipF^s6#FG6$7'FeoFfoFcrF_dpFioF[csF\`u>Ff`u
-Faz6$Fe^v<#&-Fen6%w,F^jlF;6$F\oF]oF;/FebpF_oF;F;F;6#Fbo6$7'FeoFfoFerFd_lFio7'F
eoFfoFerFc`nFioF\`uFg`uF;>Fiau-F^cn6$-Fdy6$Ff`uF]uFP>6$F]cuF\eu-F][m6$-Fgam6$Fi
auF\wFI>F]cu-Fi_m6%F]cuF\euFfu@$0F[[rF*>F]cu&F]cu6$Ff\rFb\l>F]cu&F]cu6$Fb\l-Fi]
n6%Fcv7#-F]x6#;FG-Fg]l6$Fg^lF]cuFax@$F[`uC%>F^_u-Fep6$w,F_elF;6$F\oF]oF;-Ff`m6$
*&FaqFGF`oFG7$&&F`[lFd\nF;&&F`[lF\yF;F;F;6&F4F]sF]`mF\_u6#FG6$7'FeoFfoFgqFf`lFi
oF_flF`j^l>F\_u-F[ds6#-Fep6$Fg]lF\_u>F]cu-Fi_m6%F]cuF[\uF\_u@$Fiat@%F[`u-Fda\l6
-F`oF>F^sFa[oF]cuF]zF]_uF^_uFfj^lF[[rFcjq-F^i[l6,F`oF>F^sFa[oF]cuF]zF[vF`vF[[rF
cjqF;F;F;6#FG6JF`br7'FeoFfoF]rFhflF[`l7'FeoFfoFb\mFj`lFjqFb_lFcjvF`f]lFe`l7'Feo
FfoFcamFh`lFjqFe`l7'FeoFfoF[]nF*FirF\dzFe]rF^]sFhax7'FeoFfoF]rFi\nF[`l7'FeoFfoF
jqF[^[lFjqF[dzF`a_l7'FeoFfoFgoFj`lFjqF_]s7'FeoFfoFi^mF*Fir7'FeoFfoF]rF]`lF[`l7'
FeoFfoFfflFaamF^`lFhaxF^]sFhinF]cqFggoF_`l7'FeoFfoF]rFhoF[`l7'FeoFfoFb`lFcamFd_
lFf]rFdfn7'FeoFfoFgrFdgoFd_lF`awFa]oFdfnF\dp7'FeoFfoFgqFg]sFjq7'FeoFfoFedpFdgoF
jqF;
