M7R0
I2F_l2_3view_triang7*,,%#x1G""##"$*z"$+&"""*&%#x7GF*%#x3GF*#!#6"#?*&F,F*%#x4GF*
#"$T("%+5F,#"$L""$]#,,%#x2GF&#"$B%F8F*F+#!$"QF)F1#"#R"$+"F,#!#>F0,2F-F&#!$(\F)F
**&F,F*F%F*F.*&F,F*F:F*F=F,#"$Z"F8*&%#x8GF*%#x5GF*#"#ZFA*&FLF*%#x6GF*#"$f*F5FL#
!$J""$+#,2F2F&#"$>&F)F*FGF3FHF?F,#"$>%F5FK#!$z"F)FP#!#B"$D"FL#F*""&,,FMF&#"$V&F
)F**&FLF*F-F*FN*&FLF*F2F*FfnFL#"#tFA,,FQF&#"$<%F)F*F`oFRFaoFhnFL#!#LF8,4*&F-F*F
%F*F.*&F-F*F:F*F=F-FI*&F2F*F%F*F3*&F2F*F:F*F?F2FZF%F6F:FB#"#@F)F*,4*&FMF*F-F*FN
*&FMF*F2F*FfnFMFbo*&FQF*F-F*FR*&FQF*F2F*FhnFQFgoF-FTF2F[o#"#>"#]F*6",
I2C_l2_3view_triangt+6#>%)symbolicGF*6,%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%
#V0G%"VG%#uhG%"fG6"FhpC->6$8$8%6$7%%$E12G%$E23G%"uG7%7$""$FfrFer7$F&Ffr@%/9$F*>
8&-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&F^r6#%"iGf*6$%"xG%"yGFh
p6$%)operatorG%&arrowGFhp-&T%Fjs6#,&FjrF**&,&9%F*!""F*F*&&T#Fjs6#F*F*F*FhpFhp6&
F`qF^rF_qF]r/F[t;F*-%%nopsG6#F]r>F\s-F^s6$-%'rndMatG6#FfsFau>8,-I$<,>GFds6%-I$<
|gr>GFds6%F%F-FM-Fbv6%F:F2FQ-Fbv6%F*F*F*>8-,(-%$addG6$-F\w6$*$,&&F]v6$F[t%"jGF*
&&F\s6#FfrFcwF[uF&/F[t;F*F&/Fdw;F*FfrF*-I".G6$FcsFds6%*&F,F*)&F]v6$;FhpFhpF*%#%
TGF*&F\sF_u&F]v6$FdxF&F*-F]x6%*&FLF*)FgxFexF*&F\s6#F&&F]v6$FdxFfrF*>8'7#-F^s6$-
%%diffG6$Fiv(F^tF[t/F[t;F*"")>Fby-%$mapG6$%'expandGFby@$0FjrF*OFby>8(-%&minusG6
$-%'indetsG6#Fby-F[[l6#7#F\s>6$8)8*-%,poly2matrixG6%Fby-FduF\[lFfz>8+-%$srtG6$F
c[l-%%tdegG6#-Fgs6#Ffz6%7$%#cfG-%/permuteColumnsG6%Fb[lFc[lFi[lF]rF^rFhpFhpFhp6
#""!Fhp
