M7R0
I0F_optpose2pt_v27(,H%"xG#"%2\"&+]#%"vG#"$h""&+D"%"yG#"'nuR"(++D'%"zG#!%2\"'++5
*$F-""##")"y/a#"*+++D"*$F1F6#!)*fW(G"*+++]#*$F)F6#!#B"$+&*&F)"""F-FC#!&"yc"'+]7
*&F)FCF1FC#"$,("%+?*&F%FCF)FC#!$,(FA*&F-FCF1FC#!(Jq'HF9*&F-FC%"wGFC#!&`]$"&+D'*
&F-FCF%FC#"'^a?"'++D*&F1FCFRFC#"'x+7FY*&F1FCF%FC#"&PV(FY*$FRF6F?*&F%FCFRFC#!$,*
FA*$F%F6#"$t&"%+5#!%F6"(++D"FC,HF%#"&B)fFFF)#!&"fyFUF-#!)xZ!>"")+++DF1#")*R=Y&F
9F5#!+j,&G;""*++++&F:#!*tGWn%FapF>#!$,#"$]#FB#!&Z/$"&++&FG#"'*oR"FYFK#"$`"FfpFN
#"(t%[5"(+++&FQ#!(xr5""'++]FV#"'"Hk#F4FZ#!&@:*F4Fgn#!'n__FcqFjnFdpF[o#""$""%F^o
#!$B""$D"#!)"3H2$")++]iFCz)6$F-F1[[[[[_[[[[sFC][[[[[[[[[sFC!!"",LF%#!+LPEA#*"-+
+++]7F)#",ZH"3TX"-+++++DF-#!/@JURc/E"/+++++]iF1#!-z&3k&ep"0++++++D"FR#",rvhI,#F
irF5#!0B7fy701$"0++++++]#F:#".txRL&QBFgsF>#"*2nYT"FapFB#"-f!>fdr)"-+++++]FG#!,h
lX3'eF\s*&FRFCF)FC#"+"zR9A""+++++5FK#!+$HF+X"FdtFN#!/6)[&e9`AFbsFQ#"-**H^e=CFir
FV#!-$QD*>jcF^tFZ#!-`')Qh4?F^tFgn#"-(fKY<:"F\sFjn#"+xas-6FdtF[o#!+@W`F6FapF^o#"
+$G@:;"Fdt#!-fqP%>(Q"/+++++]7FC,LF%#"(6"=F"*+DJ&>F)#!,><,S+%F\sF-#"-(z#*pIQ$".+
++++]#F1#!.j7!\H!e&FbsFR#!,Lja_i$FirF5#".^K&yDQH"/++++++]F:#!/nl1XM#\#FbsF>#!*R
_tC"FapFB#!+Bk3LP",+++++#FG#"-6f*=.1#F\sFat#!)ZV9qFdtFK#"*<vCb'FdtFN#!/"GYcnU6"
FivFQ#!,H#>+xH",+++++&FV#!,J'**\>=F[xFZ#"-(\!)*z<ZF^tFgn#!-hq89WKF^tFjn#")r)[W'
"*++++#F[o#")VgZCFbrF^o#!(6t='")+++S#"-V"\.ST$FiuFC,LF%#"/H%[g?6w"FbsF)#!-.,GI,
")FbsF-#!0hY?L3rz$"2++++++]7$F1#!064nn(\D*)"2++++++Dc"FR#!.nr$pFJ9"/+++++DJF5#!
0`Z.(y*e'y"3+++++++]7F:#"18kG#H9Q*GF\zF>#!+V.xBDF\sFB#"0Ta(G6L#4"FgsFG#"-8ee*)>
:"-++]il(*Fat#"-*o>1PY"F^tFK#",ZDv*)Q#F^tFN#!2j7np#Hi<dF\zFQ#"/FT0)psG&FbsFV#"/
Lv!RP6'=F_sFZ#"/z3T(H*Q9FbsFgn#!/^p-X/RgFgsFjn#"-*)[?3r>F^tF[o#!,PO!)Qn*F^tF^o#
!+hf<Uk",+++Dc"#"."zG%fv!p"1++++++]iFC6",
I0C_optpose2pt_v2t+6#>%)symbolicGFC6/%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%#V
0G%"VG%#C1G%#C2G%"tG%"RG%&boffaG6"F^\lC0>6$8$8%6$7$%"UG%"uG7$7$F[rF67$"")FC@%/9
$FC>8&-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fg]l6#%"iGf*6$F%F-F
^\l6$%)operatorG%&arrowGF^\l-&T%Fb_l6#,&Fb^lFC*&,&9%FCFerFCFC&&T#Fb_l6#FCFCFCF^
\lF^\l6&Ff\lFg]lFe\lFf]l/Fc_l;FC-%%nopsG6#Ff]l>Fd^l-Ff^l6$-%'rndMatG6#F^_lFf`l>
8,-I$<,>GF\_l6%-I$<|gr>GF\_l6%&&Fd^l6#F6Fd`l""!&FjalF[bl-Fgal6%F\blFial&Fjal6#F
[r-Fgal6%F]blF`bl&Fjal6#F\r>8--Fdal6%-Fgal6%&Fjal6#""&F\bl&Fjal6#""'-Fgal6%F\bl
F\cl&Fjal6#""(-Fgal6%F_clFdcl&Fjal6#F_^l>6$8.8/6$-Fdal6%F)FRF%-Fdal6%-Fgal6%FCF
\blF\bl-Fgal6%F\blF-,$F1Fer-Fgal6%F\blF1F->8'7%-I".G6$F[_lF\_l6%),&-F_el6$F^dl&
&Fd^lFd`l6$;F^\lF^\lFCFCF]dlFC%#%TGFbalFcel-F_el6%),&-F_el6$F^dl&Fgel6$FielF6FC
F]dlFCFjelFgblF^flFcr>80,$-Fdal6#-Ff^l6$)-Fdal6%-Ff^l6$-%%diffG6$&F\elFb_l&F]dl
6#%"jG/Fegl;FCF[r-F`gl6$FbglF--F`gl6$FbglF1Fjel/Fc_l;FCF6#FCF6>F\el7&-F__l6#F\e
l-&I.LinearAlgebraG6$F[_lF\_l6#_Fehl%,DeterminantG6#&Fdfl6$Fiel7$F[rF\r-Fdhl6#&
Fdfl6$Fiel7$F[rF^cl-Fdhl6#&Fdfl6$Fiel7$F\rF^cl>F\el-%$mapG6$%'expandGF\el@$/Fb^
lF\blOF\el>8(-%&minusG6$-%'indetsGFbhl-Ffjl6#7#Fd^l>6$8)8*-%,poly2matrixG6%F\el
-Fi`lFbhlFajl>8+-%$srtG6$F][m-%%tdegG6#-F__l6#Fajl6%7$%#cfG-%/permuteColumnsG6%
F\[mF][mFc[mFf]lFg]lF^\lF^\lF^\l6#F\blF^\l
