M7R0
I.F_relpose_4pt7',X%"xG#!#9"$D"%"vG#"$`""%+]%"yG#"$i""$D'%"zG#!%">'"&]7$%"wG#"%
$G#F,*(F1"""F%F9F5F9#!&$pV"'+]7*(F1F9F%F9F)F9#"&")H("'+]i*(F-F9F%F9F)F9#!$,*"%+
D*(F1F9F-F9F5F9#!#@"%+5*(F1F9F-F9F)F9#"%d<F,*(F-F9F%F9F5F9#!"$"#?*$F%""##!&")H(
F@*&F%F9F-F9#!#H"&Dc"*&F%F9F1F9#"#")F0*$F-FQ#"#@FH*&F-F9F1F9#""(F(*&F5F9F-F9#!&
2j&"&+D'*&F)F9F-F9#FS"'+DJ*&F5F9F%FQ#"$,*FD*&F)F9F1F9#FC"%]7*&F5F9F%F9#FG"$+&*&
F)F9F%F9#!%VAFD*&F5F9F1F9#""$"#5*&F-FQF)F9#F`pFO*&F1FQF5F9#!"(F(*&F1FQF)F9#!#")
F0#!&B7""&D"yF9,XF%#"$"RF0F)#"#LF,F-#!$*>"$]#F1#!'$e8(F@F5#"$F'F,F8#!'dfF"(++D"
F=#"'FS6"'++]FA#"$t&FDFE#!&$4["']i:FI#"$B&F^oFL#"$Y#F0FP#!'FS6F^rFT#"'(\l#F[rFX
#FcqFjoFen#"&$4[FcrFhn#!$"RFgoF[o#!'VSsF@F_o#Fir"'++DFbo#!$t&FDFeo#F`rFgoFho#Fb
rF\qF[p#!&x%\F4F^p#!$#\F0Fbp#!$Y#F0Fdp#F_qFgoFgp#"$*>Fjo#"'f!)f"(+++&F9,XF%#!""
""&F)#!$L'F,F-#!#BF0F1#!'6k5F@F5#"$J)FDF8#!$*zFDF=#!%BYFaoFA#!$,#F0FE#"$d#"&++"
FI#"'*3%\F[rFL#FhuFDFP#"%BYFaoFT#!&*e%*F[rFX#F\uFgoFen#!$d#FiuFhn#F9FapF[o#!%,7
FgoF_o#F^vFcrFbo#"$,#F0Feo#!$-%F0Fho#FhuF,F[p#!'6f]F@F^p#FcvFgoFbp#FcvFDFdp#Fgt
FapFgp#"#BFgo#!&**3%"(++]#F9,XF%#"$8*FgoF)#"$z)FHF-#!$,(FgoF1#"'$4G"F@F5#"%@=F,
F8#!'6.OF[rF=#"'`s5F[rFA#F+FgoFE#"'$Qu"F@FI#"'"*QQF@FL#!$">F0FP#!'`s5F[rFT#!'ru
SF[rFX#F]xFDFen#!'$Qu"F@Fhn#!$8*FDF[o#!'*oR'F@F_o#F^yF@Fbo#!$`"FgoFeo#F+F0Fho#F
hxFaoF[p#!'4h6FaoF^p#"$#QF0Fbp#"$">F0Fdp#FiwFDFgp#"$,(FD#!(d!o8FfwF9z+6%F%F-F1[
[[[[[[[][[[mF9[[[[][[[[[[[mF9][[[[[[[[[[[mF9!Fgt6",
I.C_relpose_4ptt+6#>%)symbolicGF96/%&_nameG%&_sizeG%#AAG%$eqsG%%varsG%#C0G%#V0G
%"VG%$cthG%$sthG%#txG%"rG%"EG6"FjzC.>6$8$8%6$7%%#x1G%#x2G%#thG7%7$FQ""%Fj\l7$F9
F9@%/9$F9>8&-%$seqG6$-I'MatrixG6$%*protectedG%(_syslibG6$-%#opG6#&Fc\l6#%"iGf*6
$F%F-Fjz6$%)operatorG%&arrowGFjz-&T%F_^l6#,&F_]lF9*&,&9%F9FgtF9F9&&T#F_^l6#F9F9
F9FjzFjz6&Fb[lFc\lFa[lFb\l/F`^l;F9-%%nopsG6#Fb\l>Fa]l6$-Fc]l6$-%'rndMatG6#F[^l/
F`^l;F9,&Fe_lF9FgtF9-I$<,>GFi]l6#-Fc`l6#-I'arccosG6$Fh]lFi]l6##F`pFht>6$8,8-6$-
I$cosG6$Fh]lFi]l6#&&Fa]l6#F`p6$F9F9-I$sinG6$Fh]lFi]lFdal>6$8.8/6$-Fc`l6%-I$<|gr
>GFi]l6%""!FgtF5-Fdbl6%F9Ffbl,$F)Fgt-Fdbl6%,$F5FgtF)Ffbl-Fc`lFiz>80-I".G6$Fh]lF
i]l6$F^bl,(*&F^alF9-&I.LinearAlgebraG6$Fh]lFi]l6#_Fhcl%/IdentityMatrixGFgalF9F9
*&,&F9F9F^alFgtF9-Facl6$F_bl)F_bl%#%TGF9F9*&F_alF9-Fc`l6%-Fdbl6%Ffbl,$&F_blFgal
Fgt&F_bl6#FQ-Fdbl6%FidlFfbl,$&F_blFa_lFgt-Fdbl6%,$FjdlFgtF_elFfblF9F9>8'7$-Fc]l
6$&-Facl6%)-Fc`l6$&&Fa]lFa_l6$;FjzFjzF`^lF9FbdlF_cl-Fc`l6$&&Fa]lF[elF`flF9Fhal/
F`^l;F9F[]l,&-Facl6$FadlF_blF9FgtF9>Fdel-%$mapG6$%'expandGFdel@$/F_]lFfblOFdel>
8(-%&minusG6$-%'indetsG6#Fdel-Figl6#7#Fa]l>6$8)8*-%,poly2matrixG6%Fdel-Ff_lFjgl
Fdgl>8+-%$srtG6$Fahl-%%tdegG6#-F\^l6#Fdgl6%7$%#cfG-%/permuteColumnsG6%F`hlFahlF
ghlFb\lFc\lFjzFjzFjz6#FfblFjz
