M7R0
I1F_rollingshutter7,,L%#x1G#"&x)o"&+]#%#x2G#"'2*=""'+]7%#x3G#!'Hx9"'++5%#x4G#!%
.N"&]7$%#x5G#!(L,3""'++]*&F%"""F)F:#!'hB`"'++D*&F%F:F-F:#"'VtEF0*&F%F:F1F:#!'pA
IF8*&F%F:F5F:#!'h&*fF=*&F)F:F-F:#"&zr'"&+D'*&F)F:F1F:#"&^h&FJ*&F)F:F5F:#"'HkDF0
*&F-F:F1F:#"'re8F8*&F-F:F5F:#"&z:'F8*&F1F:F5F:#"(4(f5F8*$F%""##!'tuhF8*$F)Fen#!
'\l5"(+++"*$F-Fen#!'>`OF8*$F1Fen#"',YuF[o*$F5Fen#"'8F:F=#!'F29F=F:,LF%#!&Rd"F=F
)#!'.g9F,F-#"'@;!*F8F1#!&2s("&++&F5#!'VaHF=F9#!'hrMF8F>#"'TRWF8FA#!'R^ZF=FD#!&L
y&F8FG#"'Bo>F=FK#"(@J?"F=FN#"'h0CF0FQ#!'VPCF8FT#!'hXNF8FW#"&td#F8FZ#!'ZeIF8Fhn#
!%.()F(F\o#!'Bh>F8F_o#!'hrDF[oFbo#"&jg""&++%#!(ZN1"F[oF:,LF%#!'$Rm%F=F)#"&xO"F`
pF-#"'"[z"F8F1#"'pR!*F=F5#"'4m8F8F9#"'<SAFJF>#!'()fhF=FA#"%#*["&Dc"FD#"&PW$F4FG
#"',J8F0FK#!'RSrF8FN#!'2HGF8FQ#"&43)F8FT#!&"[$*F8FW#"'f&o"F,FZ#!&xS%F,Fhn#!($=Q
8F[oF\o#"&^l&F=F_o#"'**GKF8Fbo#!&Z(>Far#!'hO5F8F:,LF%#!'hL6FJF)#!&fy""&+D"F-#"'
hKNF=F1#"'2F5F`pF5#"'<UmF=F9#!&@L)F=F>#"'BVdF8FA#"&f&HF4FD#"'(4?*F8FG#"&P_'F=FK
#!&x'oF,FN#!'PH^F8FQ#!'p?FF8FT#!'B#*pF8FW#"&*oMF8FZ#!(T!45F[oFhn#"'@j$)F[oF\o#!
'niIF[oF_o#"&8%eFarFbo#!'Zm;"'++?#!&jO#F`pF:,LF%#"'j&*fF8F)#!'2shF8F-#"&>p%F[oF
1#!'(H]&F8F5#"'Bq_F[oF9#!'6*f"FjwF>#"%,)*FJFA#!&HZ%F,FD#!'n()eF[oFG#!'4njF[oFK#
"(\!H8F[oFN#!'*30"F[oFQ#!'8(R"F=FT#"'^*R$F8FW#"'<ZKF[oFZ#"'\r=F8Fhn#"'pt#*F[oF
\o#"&2c&F[oF_o#"'49ZF[oFbo#!'dzDF8#"'J"3#F[oF:,LF%#"'*R$eF[oF)#!'Z;MF[oF-#!'"pF
(F[oF1#!(Ptz"F[oF5#!'J!G'F8F9#"'6:XF8F>#!'P)=#F=FA#!'r5YF[oFD#!&"))*)F=FG#"'^^*
)F[oFK#"&rL*F[oFN#!'(H&)*F[oFQ#"&jh$FjwFT#"&jF&FJFW#"'HPPF[oFZ#!&B"zF=Fhn#!&pr"
F`pF\o#"&hy"F[oF_o#!&FF%F0Fbo#"'FC`F[o#"'$>(HF8F:,LF%#!'pvfF[oF)#!&rQ'FjwF-#"%B
^FjwF1#!'^)3$F[oF5#"&@:"FeuF9#"(xQ7#F[oF>#!'Vr8F0FA#!'(pF&F8FD#!(@2]"F[oFG#!'tm
7F8FK#!'"ym"F8FN#"',TJF[oFQ#"($)z0"F[oFT#"&PM#F`pFW#!&Lf"F(FZ#"'ttiF[oFhn#!'>'f
#F8F\o#"'8)Q"F8F_o#"&fX"FarFbo#!%"G#"&++##"&p-#F0F:,LF%#"'f_(*F[oF)#"&*z6FesF-#
!&T+)F8F1#"&$p**F0F5#!'8LeF[oF9#!&@&\FJF>#"&T3#F8FA#"'>S=FjwFD#"'H!Q"F,FG#"'>'4
&F[oFK#!(nDl#F[oFN#!'J%G$F8FQ#"'J?[F8FT#!&Fp'FjwFW#!&L&RF,FZ#"'*G4"F8Fhn#!%ZCFe
sF\o#!&ty*F[oF_o#"'(>V"F[oFbo#"&*[iF8#!&//"FesF:,LF%#"'"yD#F,F)#!&<I&F,F-#!&z/%
F4F1#"&*Q)*F=F5#"'(>Q"F8F9#!'4R=F,F>#"($)H5"F[oFA#"%8X"%]iFD#"&,1"FjwFG#"&`i#F(
FK#"&(R%*F0FN#"'ZV]F8FQ#!'4uAF8FT#"&xq$F[oFW#!%p7F[oFZ#!'*)>$)F[oFhn#!'pG5F[oF
\o#!'."e$F[oF_o#"&p5"FJFbo#!'.wUF[o#"&t1&F,F:,LF%#!'$*RtF[oF)#!(hd6"F[oF-#"(^#)
="F[oF1#"'$p#)*F[oF5#"'Z&>'F8F9#"'h"4(F[oF>#"&p4"F[oFA#"'`/zF8FD#!&x?%F0FG#!%2#
)F0FK#!'n"3#F[oFN#!'@e?F8FQ#!'2OSF8FT#"'j#R$F[oFW#!%Ls"%+!)FZ#"'@P6F[oFhn#!'295
F8F\o#!&*QqF[oF_o#!'V'p%F[oFbo#!&$pEF`p#!'(=>"F8F:6"
